### ISSUE TITLE
List of games, which crash the plugin with frame buffer emulation on. 

### ISSUE THREAD

**Issue by gonetz** [gonetz/GLideN64#1]
F1 pole position after 1st screen
South park rally after 1st screen
Turok 2 after 1st screens (is it fixed on your side?)
Monster truck 64 at start
RE2 at start
loadrunner at start
airboarder (J) (not E) at start
vigilante 8: when pressing start at "1 player in menu" (game crash without read every frame?)
superbowling in menu

**Comment by olivieryuyu** [comment]
i close this ticket most of the issue are solved now. separate tickets opened for specific games.

**Comment by gonetz** [comment]
Ok.
