### ISSUE TITLE
gles3 slower than gles2

### ISSUE THREAD

**Issue by min050820** [gonetz/GLideN64#1000]
My device is f240s with adreno 320. I'm not sure whether I'm using freedreno or not. (but I can search my kernel source code if you want)

As the title suggests, gles3 backend is much slower than gles2 backend. I tried disabling any options that were only available in gles2 backend, but that did not show any improvements.

**Comment by gonetz** [comment]
Anniversary bug report : #1000 !

Yes, I know about the problem. I don't have time to investigate it. If you have programming skills and able to build mupen64plus-ae from sources, you may help me. I need to know:
* Is GLES3 build noticeably slower than GLES2 one with frame buffer emulation off?
* If fb emulation is the reason of slowdown, what causes it? Buffer reads or something else?

**Comment by min050820** [comment]
Okay, I'm not thay familiar with Android and Java programming, but I assume renderer is in C/C++, right?

I'll try to test those as soon as possible. :D

**Comment by gonetz** [comment]
Right :)

**Comment by min050820** [comment]
I tried to find any performance issue before actually editing the source code, so I disabled Frame buffer emulation from settings.

That gave N64 logo screen a huge boost for gles3, almost same speed as gles2. However, it didn't gain any boost in main game.

**Comment by min050820** [comment]
Does any of you know difference of N64 logo (60fps) and LoZ:OoT main game(20fps)?

**Comment by gonetz** [comment]
20 FPS is normal for both N64 Zelda games. They are programmed that way.

**Comment by min050820** [comment]
No, not in that way. I knew it renders at 20fps. What I asked is: _does any of you know why game itself won't gain any performance boost but N64 logo does?_

**Comment by gonetz** [comment]
N64 logo is very simple model. You got performance boost on it with fb emulation off - good.Need to find, which part of fb emulation slows rendering. No boost in main game? Ok, there are other things, which slowdown rendering. I already mentioned difference between GLES2 and GLES3 versions:
https://github.com/gonetz/GLideN64/issues/979#issuecomment-217137057
You may try to dig there.

**Comment by min050820** [comment]
Thanks. Now I'll take a look at there. Through I may not be able to help you since I'm not familiar with OpenGL. :( (I barely knows the concept of vertex shader and fragnent shader)

**Comment by fzurita** [comment]
I've been doing some more testing on this. On my Adreno device (after recent changes), GLES 3 is actually faster than GLES 2.0. On my PowerVR device however, GLES 3.0 crawls.

**Comment by fzurita** [comment]
@min050820 Please try using this build: https://drive.google.com/file/d/0B57Ioy26LWegV1RUTVVWTzhPVnc/view?usp=sharing

I have made some pretty big performance improvements on Adreno devices lately with frame buffer emulation enabled.

I'm trying to investigate PowerVR devices right now though...

**Comment by takeshineale128** [comment]
Doesn't lag on paper mario and has fixed the problem

**Comment by min050820** [comment]
@fzurita Uh... That build is still slow on my phone, playing Ocarina of Time. So it comes with two possibilities:
1. That solution was device specific (But I doubt so)
2. That solution doesn't work well with heavy games like Ocarina of Time.
3. Something's wrong with my graphic driver.

Now I'm going to test other games, like Mario 64. Any suggestions are welcome.

**Comment by fzurita** [comment]
Hmmm, on my Adreno device GLES 3 is faster. I'm trying to investigate why GLES 3 is slower on PowerVR devices. Maybe they will lead to a solution that will work on your device.

**Comment by fzurita** [comment]
@min050820 Please try this build:

https://drive.google.com/file/d/0B57Ioy26LWegVUVNS0tPZVg3SlU/view?usp=sharing

In this build the GLideN64 is using the OpenGL ES 2.0 shaders which are much simpler. I'm wondering if it's the shaders causing the slowdown.

**Comment by fzurita** [comment]
Also, this build is a little unstable, you may have to try launching a game a few times.

In my PowerVR, frame rate went from 12fps in GLES 3.0 to 60fps.

Obviously, features provided by the 3.0 shaders are missing.

**Comment by min050820** [comment]
@fzurita It didn't have any inprovements on my device. However, it fixed a bug caused on "NINTENDO" written on N64 logo screen. Maybe I'll open another issue when this issue is done.

Anyway, back to this issue, it didn't have any improvements. Is there any way to log gles states? I'll try to log that if there's any.

**Comment by fzurita** [comment]
What driver version is your device using?

**Comment by min050820** [comment]
I'm not sure of it. I have conpiled my kernel myself, but I have no idea. Do you know any ways to check what driver am I using?
P.S. lsmod not works. I compiled everything as built-in.

**Comment by fzurita** [comment]
There Mupen64plus logcat output will show driver information when loading a game. Can you post your logcat?

**Comment by min050820** [comment]
Here's my logcat:
>05-29 21:00:03.972 12755 12785 I Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build:  ()
>05-29 21:00:03.972 12755 12785 I Adreno-EGL: OpenGL ES Shader Compiler Version: E031.25.03.00
05-29 21:00:03.972 12755 12785 I Adreno-EGL: Build Date: 03/05/15 Thu
>05-29 21:00:03.972 12755 12785 I Adreno-EGL: Local Branch: skarajga_LA.BF.1.1_RB1_18
>05-29 21:00:03.972 12755 12785 I Adreno-EGL: Remote Branch: 
>05-29 21:00:03.972 12755 12785 I Adreno-EGL: Local Patches: 
>05-29 21:00:03.972 12755 12785 I Adreno-EGL: Reconstruct Branch: 
>05-29 21:00:03.972 12755 12785 I OpenGLRenderer: Initialized EGL, version 1.4
Please tell me if I missed anything.

**Comment by fzurita** [comment]
Hmmm, can you post all of your logcat as an attachment?

**Comment by min050820** [comment]
Uh-oh I fear not. Somehow, some apps were posting my phone number and such private things on logcat. I'll try to collect logcat again, with all apps stopped.

**Comment by fzurita** [comment]
Gotcha, you can open up your logcat and search for Mupen64 then only post the matches.

**Comment by min050820** [comment]
>OpenGL ES 3.0 V@84.0 AU@ (CL@)
Is this what you wanted?? `adb logcat | grep Mupen64` only returns very few things and I couldn't find anything that had to with opengl.
Or maybe I'm doing it wrong. Sorry if I was. I'm not familiar with Android that much.

And I found an interesting line as I looked into logcat: FBIOGET_FSCREENINFO failed. I have no idea whether it's what this app said, but it's interesting. I think I'll google it. I'm telling you guys just in case.

**Comment by fzurita** [comment]
Yep, that's what I wanted. Sorry mupen64 all lower case. My phone auto corrects way too much.

**Comment by min050820** [comment]
:D That's the reason I changed my software keyboard. And it's most likely you can disable that feature in Keyboard Settings.

Anyway, I figured it would be convinience to make an option to disable copyFBtoRDRAM.

**Comment by fzurita** [comment]
I think you do have the Qualcomm drivers based on that version number, so not freedreno.

**Comment by min050820** [comment]
Yeah, it must be stock driver since it says `qualcomm-egl`. Now I'm gonna port freedreno to my kernel. ...it goes to kernel right? Android system is so confusing. )X

**Comment by fzurita** [comment]
Same driver version I have actually:

Created GL context OpenGL ES 3.0 V@84.0 AU@05.00.02.042.016 (CL@)

**Comment by min050820** [comment]
Huh? `05.00.02.042.016` part is missing on my info. I wonder why.

**Comment by fzurita** [comment]
Hmmm, not sure actually.

**Comment by fzurita** [comment]
After doing some googling,  I think it may be the audio driver version.

**Comment by min050820** [comment]
Well, I guess we can ignore that.

Can you give me a build with copyFBtoRDRAM disabled? I want to build it myself if I could... but I really messed up with Eclipse. Now Eclipse ADT is missnig and

**Comment by min050820** [comment]
Wha- I closed this issue! My mistake! Sorry!

**Comment by fzurita** [comment]
> Can you give me a build with copyFBtoRDRAM disabled? I want to build it myself if I could... but I really messed up with Eclipse. It wouldn't start up even after removing and getting a new copy. I must have done sonething terrible to my system...

No need for this. You can do this through the plugin configuration.

**Comment by fzurita** [comment]
Is this build any faster in GLES 3.0? https://drive.google.com/file/d/0B57Ioy26LWegRDVlQjd6eGZNb1U/view?usp=sharing

**Comment by min050820** [comment]
> Is this build any faster in GLES 3.0? https://drive.google.com/file/d/0B57Ioy26LWegRDVlQjd6eGZNb1U/view?usp=sharing

>This build is the latest GLideN64 with the old blending from the legacy_blending branch.

Sorry for being late! I broke my phone so badly while flashing a ROM so... well.... I'll test this one as soon as I fix my phone.

**Comment by min050820** [comment]
>Is this build any faster in GLES 3.0? https://drive.google.com/file/d/0B57Ioy26LWegRDVlQjd6eGZNb1U/view?usp=sharing

>This build is the latest GLideN64 with the old blending from the legacy_blending branch.

@fzurita IT WORKED!!!!

However, it contained a serious graphical problem in GLES3 backend, and few graphical gliches.

In gles3, the screen was rendered upside down. I'm sure my phone wasn't flipped because keypad was correctly displayed.

In all backends (gles2 and gles3), with Zelda OoT, there was a graphical issue on its logo. (In intro screen, before loading the file)

In gles2, a gliched box appeared in left-bottom area. It was small.

I'll try to prepare a screenshot soon.

**Comment by fzurita** [comment]
That is a very old build now. Can you try the playstore version? It can be located here:

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by min050820** [comment]
Now gles3 is more or less faster than gles2 backend on my phone. That legacy blending gave a nice boost.

I think now it's safe to close this "Anniversary bug report : #1000" :D
