### ISSUE TITLE
Copy color buffer to RDRAM disabled in GLES 2.0

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1005]
Why is copy color buffer to RDRAM disabled in GLES 2.0? Is enabling it as easy as removing the ```#ifndef GLES2``` in ColorBUfferToRDRAM.cpp (probably not). What else needs to be done?

**Comment by gonetz** [comment]
Current implementation uses glBlitFramebuffer to shrink current frame buffer to size of buffer in RDRAM. GLES2 does not support it. I'm planing to write an auxiliary class, which will copy one buffer to another. For GLES2 it will be plain textured rect rendering with simple path-through shader. OGLRender::drawTexturedRect also can be used for that; it is just too heavy.

**Comment by fzurita** [comment]
Gotcha, good to know.

**Comment by fzurita** [comment]
This seems ok now
