### ISSUE TITLE
Issue with GlideN64 (via mupen64plus) at fullscreen in Linux

### ISSUE THREAD

**Issue by r2rX** [gonetz/GLideN64#1006]
Hey everyone,

I've been experiencing a small issue where the video output, in fullscreen (@ 1920x1080), is shrunk to the bottom-left corner of the screen.

Here's an image for reference:
![gliden64bug](https://cloud.githubusercontent.com/assets/18622885/15669388/d630911c-2728-11e6-919c-d92a5e9df801.png)

This has been happening over the last month or so, keeping up-to-date with git releases of GlideN64, as well as NVIDIA drivers. It's running via mupen64plus (with the core updated to the latest version). The system environment is Ubuntu 16.04 x64 w/ NVIDIA 367.18 drivers.

Here's my GlideN64 configuration in mupen64plus.cfg:

```
# Settings version. Don't touch it.
configVersion = 9
# Enable/Disable MultiSampling (0=off, 2,4,8,16=quality)
MultiSampling = 0
# Screen aspect ratio (0=stretch, 1=force 4:3, 2=force 16:9, 3=adjust)
AspectRatio = 1
# Swap frame buffers (0=On VI update call, 1=On VI origin change, 2=On buffer update)
BufferSwapMode = 0
# Frame buffer size is the factor of N64 native resolution.
UseNativeResolutionFactor = 0
# Bilinear filtering mode (0=N64 3point, 1=standard)
bilinearMode = 0
# Max level of Anisotropic Filtering, 0 for off
MaxAnisotropy = True
# Size of texture cache in megabytes. Good value is VRAM*3/4
CacheSize = 2304
# Enable color noise emulation.
EnableNoise = True
# Enable LOD emulation.
EnableLOD = True
# Enable hardware per-pixel lighting.
EnableHWLighting = False
# Use persistent storage for compiled shaders.
EnableShadersStorage = True
# Make texrect coordinates continuous to avoid black lines between them. (0=Off, 1=Auto, 2=Force)
CorrectTexrectCoords = 1
# Enable frame and|or depth buffer emulation.
EnableFBEmulation = True
# Copy auxiliary buffers to RDRAM
EnableCopyAuxiliaryToRDRAM = False
# Enable N64 depth compare instead of OpenGL standard one. Experimental.
EnableN64DepthCompare = False
# Disable buffers read/write with FBInfo. Use for games, which do not work with FBInfo.
DisableFBInfo = True
# Read color buffer by 4kb chunks (strict follow to FBRead specification)
FBInfoReadColorChunk = False
# Read depth buffer by 4kb chunks (strict follow to FBRead specification)
FBInfoReadDepthChunk = True
# Enable color buffer copy to RDRAM (0=do not copy, 1=copy in sync mode, 2=copy in async mode)
EnableCopyColorToRDRAM = 2
# Enable depth buffer copy to RDRAM.
EnableCopyDepthToRDRAM = True
# Enable color buffer copy from RDRAM.
EnableCopyColorFromRDRAM = False
# Texture filter (0=none, 1=Smooth filtering 1, 2=Smooth filtering 2, 3=Smooth filtering 3, 4=Smooth filtering 4, 5=Sharp filtering 1, 6=Sharp filtering 2)
txFilterMode = 0
# Texture Enhancement (0=none, 1=store as is, 2=X2, 3=X2SAI, 4=HQ2X, 5=HQ2XS, 6=LQ2X, 7=LQ2XS, 8=HQ4X, 9=2xBRZ, 10=3xBRZ, 11=4xBRZ, 12=5xBRZ), 13=6xBRZ
txEnhancementMode = 0
# Deposterize texture before enhancement.
txDeposterize = False
# Don't filter background textures.
txFilterIgnoreBG = False
# Size of filtered textures cache in megabytes.
txCacheSize = 100
# Use high-resolution texture packs if available.
txHiresEnable = False
# Allow to use alpha channel of high-res texture fully.
txHiresFullAlphaChannel = False
# Use alternative method of paletted textures CRC calculation.
txHresAltCRC = False
# Enable dump of loaded N64 textures.
txDump = False
# Zip textures cache.
txCacheCompression = True
# Force use 16bit texture formats for HD textures.
txForce16bpp = False
# Save texture cache to hard disk.
txSaveCache = True
# Path to folder with hi-res texture packs.
txPath = "/home/xxx/.local/share/mupen64plus/hires_texture"
# File name of True Type Font for text messages.
fontName = "FreeSans.ttf"
# Font size.
fontSize = 18
# Font color in RGB format.
fontColor = "B5E61D"
# Enable bloom filter
EnableBloom = 0
# Brightness threshold level for bloom. Values [2, 6]
bloomThresholdLevel = 4
# Bloom blend mode (0=Strong, 1=Mild, 2=Light)
bloomBlendMode = 0
# Blur radius. Values [2, 10]
blurAmount = 10
# Blur strength. Values [10, 100]
blurStrength = 20
# Force gamma correction.
ForceGammaCorrection = False
# Gamma correction level.
GammaCorrectionLevel = 2
```

I haven't modified the plugin settings for a long time but i've posted them just in case i've missed something.

**Comment by tony971** [comment]
I've experienced similar issues with Windows 10. Try increasing the internal resolution.

**Comment by r2rX** [comment]
Thanks for the feedback, tony971. I forgot to mention that i'm using M64Py as the front-end. I edited the mupen64plus.cfg and, under [Video-General], noticed that the resolution was low; 852x639 (which explains the scale of the image when going fullscreen). Despite changing the resolution, it would not apply and, after running M64Py and closing it, the .cfg file would revert the adjustment.

So it seems that, in M64Py, 'Enable Video Extension' was the culprit. The moment I disabled it, I could increase the resolution to 1920x1080 and have games display properly fullscreen. The only caveat is that a game can't run windowed and then go fullscreen (as 1920x1080 is my max monitor resolution and the window will occupy the entire screen, whether windowed or fullscreen).

Then I searched for 'Enable Video Extension' and found the following (from [this](http://www.emutalk.net/threads/54023-M64Py-Python-frontend-for-Mupen64Plus?s=9051b9f9b67d9093afbfabd184ba6dce&p=445601&viewfull=1#post445601) page):

> Important to note, on first start frontend will enable video extension, that is, it will embed OpenGL in Qt window. Unfortunately, when you resize window,
> content will not scale and for now I don't know what is needed for that to work. I tried with PyOpenGL to override resizeGL method of QGLWidget,
> but only with Glide64 plugin I had some success, and only when decreasing window size so that code is commented.

Disabling 'Enable Video Extension' qualms the issue that inspired this report.....however, the emu/plugin used to display fullscreen properly with 'Enable Video Extension' enabled...so I don't remember exactly when it stopped working or why.

Is this something worth investigating? Can this only be solved in the M64Py code or can GlideN64 be adjusted to help (i.e. 'Enable Video Extension' can be enabled but the (fullscreen) resolution is controlled by GlideN64 directly).

**Comment by gonetz** [comment]
I don't know what can I do there. The plugin does not create GL context, it is duty of emulator's core.

**Comment by min050820** [comment]
@r2rX A simple suggestion: Why don't you open an issue here: https://github.com/mupen64plus/mupen64plus-ui-python/issues

**Comment by r2rX** [comment]
No problem, @gonetz . Thought to bring it up and at least learn what the situation is. :)

Sensible idea, @min050820 . I'll probably do that. :)
