### ISSUE TITLE
DepthBufferToRDRAM.cpp needs to explicitly include C-style <math.h>

### ISSUE THREAD

**Issue by wareya** [gonetz/GLideN64#1007]
/home/wareya/dev/gliden64-clean/src/BufferCopy/DepthBufferToRDRAM.cpp: In static member function ‘static u16 DepthBufferToRDRAM::_FloatToUInt16(f32)’:
    /home/wareya/dev/gliden64-clean/src/BufferCopy/DepthBufferToRDRAM.cpp:162:48: error:     ‘floorf’ was not declared in this scope
       idx = std::min(0x3FFFFU, u32(floorf(_z + 0.5f)));

**Comment by gonetz** [comment]
Done
db8d8bee
