### ISSUE TITLE
A few issues with latest "fix_2D" code

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1010]
I get this error when I run it (Raspberry Pi):
```
shader_link error: ERROR:SEMANTIC-52 (fragment shader, line 2) Initializer for uniform
```

It doesn't like these lines:
https://github.com/gonetz/GLideN64/blob/master/src/GLES2/Shaders_gles2.h#L481
https://github.com/gonetz/GLideN64/blob/master/src/GLES2/Shaders_gles2.h#L495

If I take out the "uniform" then it works, but I'm not sure what the ramifications of that are.

Once that is done, I get this error:
```
mupen64plus: /home/pi/GLideN64/src/OpenGL.cpp:403: void OGLRender::TexrectDrawer::init(): Assertion `m_depthScaleLoc >= 0' failed.
```

It looks like that assertion was added in this commit: https://github.com/gonetz/GLideN64/commit/cefffa7c24f0899abda425d974e29afd5005b223 but I haven't been able to figure out how to fix it yet.

**Comment by loganmc10** [comment]
When I run this on a different GLES2 device I get:
```
shader_compile error: 0:37(32): error: cannot initialize uniform uTestColor in GLSL ES 1.00 (GLSL 1.20 required)
```

**Comment by fzurita** [comment]
I think you can fix that by making this modification to the lines you pointed out:
```
"uniform lowp vec4 uTestColor;    \n"
```

You will then have to manually set the uniform from ```ShaderCombiner::update``` method.

From there, you can set it manually to ```(4.0/255.0, 2.0/255.0, 1.0/255.0, 0.0)``` using m_uniforms.uTestColor.set(

**Comment by loganmc10** [comment]
Does it need to be a uniform though? Can't it just be:
```
lowp vec4 uTestColor = vec4(4.0/255.0, 2.0/255.0, 1.0/255.0, 0.0);
```

**Comment by fzurita** [comment]
You are right. I never see that uniform being updated outside the GLSL shader.  It could probably be made into not a uniform.

You should try it!

**Comment by loganmc10** [comment]
I tried it, it worked but now I get:
```
mupen64plus: /home/pi/GLideN64/src/OpenGL.cpp:403: void OGLRender::TexrectDrawer::init(): Assertion `m_depthScaleLoc >= 0' failed.
```
So I'm still trying to figure that part out

**Comment by gonetz** [comment]
Yes, testColor can be just a variable. I wanted it to be a constant, so I made it as uniform with static initialization.

**Comment by gonetz** [comment]
Can be closed now?

**Comment by loganmc10** [comment]
Yes thanks
