### ISSUE TITLE
PowerVR corrupt graphics

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1011]
@gonetz, so while trying to debug PowerVR issues, I updated the Nexus Player to Android N preview. After doing this, it must had updated the PowerVR drivers because I'm seeing a brand new issue. See this screenshot:

![super_mario_64-000](https://cloud.githubusercontent.com/assets/11581687/15797455/04a5150c-29e7-11e6-98e3-d152511b4b95.png)

I have tried GL ES 2.0/3.0/3.1 with no effect. It seems like only 2D is rendered correctly. ADB has no errors. I have the feeling that is has to do with depth since the tile based rendered will not draw any polygons that are behind everything else.

Other plugins seem to work ok. Any ideas as to what I could try?

**Comment by gonetz** [comment]
First, you may test that this is depth buffer related. Disable depth compare:
https://github.com/gonetz/GLideN64/issues/994#issuecomment-222589793

Trees and grass textures look very garbled. May be color/alpha dither or alpha compare work wrong. Try to disable noise. You may also comment alpha compare in shaders. In ShaderUtils.cpp remove
```
	_strShader.append(
		"  if (uEnableAlphaTest != 0) {							\n"
...

```

**Comment by fzurita** [comment]
Sure, I'll try those things.

**Comment by fzurita** [comment]
Ok, I tried what was in the comment in issue #994, no luck. Also tried disabling noise, also no luck. Disabling alpha compare didn't do much either. I guess I'll try stripping the shader to the bare minimum and see if I can get any geometry to show.

**Comment by fzurita** [comment]
My shader is down to this and it's still the same issue:
```
void main()						
{							
  fragColor = vShadeColor;	
}                        
```

**Comment by fzurita** [comment]
Ok, I don't know why I didn't check it earlier, but once I disable frame buffer emulation completely, the issue goes away.

**Comment by loganmc10** [comment]
I wonder if this is the same issue as I'm having in https://github.com/gonetz/GLideN64/issues/994. If you look at first screenshots I posted you see that 2D elements like that are rendered fine, and it only happens with Framebuffer emulation (althoufh it's a little different because I am using that depth renderbuffer stuff)

**Comment by fzurita** [comment]
It's possible, I'll try to narrow down which call is causing the issue, once i find it, you can try it as well.

**Comment by fzurita** [comment]
Ok, I found the specific line that is causing this issue... It's this one:

https://github.com/gonetz/GLideN64/blob/master/src/FrameBuffer.cpp#L599

If I comment out ```glBindFramebuffer``` the issue goes away, but I have no idea what I'm breaking by doing that.

**Comment by fzurita** [comment]
Moving the ```glBindFramebuffer(GL_FRAMEBUFFER, m_pCurrent->m_FBO);``` inside ```if (m_pCurrent->m_size != _size) ``` seems to fix the issue.

Would that fix make sense? It only sounds like we need to bind that frame buffer when we need to clear color on it....

**Comment by gonetz** [comment]
The code makes FBO of selected frame buffer as current render target. This is absolutely necessary, if previous render target was not the same, what generally is true. 

(m_pCurrent->m_size != _size) is a rare case, so when you moved  the line here, you actually disabled it.

**Comment by fzurita** [comment]
What about binding to only GL_DRAW_FRAMEBUFFER or GL_READ_FRAMEBUFFER? Does it really need to be both?

**Comment by gonetz** [comment]
GLES2 does not know about GL_DRAW_FRAMEBUFFER  and GL_READ_FRAMEBUFFER. It uses GL_FRAMEBUFFER only. You may try to replace GL_FRAMEBUFFER by GL_DRAW_FRAMEBUFFER and see, if it helps.

**Comment by fzurita** [comment]
Setting it to GL_DRAW_FRAMEBUFFER doesn't fix it...

**Comment by gonetz** [comment]
Well, the code is correct. If it works incorrect, something wrong with its data. Need to check that all data of m_pCurrent is valid. Buffer textures allocated and not removed. FBO allocated and not removed.
Try to insert 
assert(checkFBO());
after the
glBindFramebuffer(GL_FRAMEBUFFER, m_pCurrent->m_FBO);

**Comment by fzurita** [comment]
Yeah, it's probably a device specific driver bug.

**Comment by loganmc10** [comment]
Commenting out this line:
https://github.com/gonetz/GLideN64/blob/master/src/FrameBuffer.cpp#L600

Also fixes Framebuffer emulation on the Raspberry Pi, here are 2 screenshots showing the difference:

![snapshot2](https://cloud.githubusercontent.com/assets/848146/16233966/45e9b8e8-378d-11e6-8a25-e37d93e843a0.png)
![snapshot](https://cloud.githubusercontent.com/assets/848146/16233972/497df62c-378d-11e6-9cda-3f8184430e93.png)

**Comment by fzurita** [comment]
Specific frame buffer effects seem to still work correctly with that line disabled. @gonetz what would it break when i disable that line?

I was reading online and maybe the same thing could be achieved by having only one FBO and detaching/attaching different textures to the same FBO?

**Comment by gonetz** [comment]
> Specific frame buffer effects seem to still work correctly with that line disabled. @gonetz what would it break when i disable that line?

https://github.com/gonetz/GLideN64/issues/1011#issuecomment-226925701

> I was reading online and maybe the same thing could be achieved by having only one FBO and detaching/attaching different textures to the same FBO?

Bad approach.

**Comment by fzurita** [comment]
Well, at least we are closer to something. It seems to be related to binding to different FBO's. I'll keep investigating as I have the time. Maybe a working approach can be achieved.

I really wish all drivers would behave the same, that is only a dream though, maybe when vulkan that will change.

**Comment by loganmc10** [comment]
When I play GoldenEye or Perfect Dark with that line commented out it is very choppy, almost like it is skipping frames or something. When I play without it it seems smooth (although its a little hard to tell because the graphics are so messed up).

**Comment by gonetz** [comment]
1. If you think that the hardware can't handle more than one FBO, you need to prove it. For example, write a simple test, which will draw something on screen. Render the scene to FBO and then copy FBO to screen. Use two FBO and swap between them each frame. If it will not work, you really found the problem.

2. I suppose, that the problem can be with depth attachment. N64 usually uses only one depth buffer and swaps color buffers only. Thus, all FBO use different color attachment, but depth attachment is the same. Probably, particular combination of hardware/drivers can't handle it. You may try to create and attach separate depth renderbuffer for each new FBO and see if it helps.

**Comment by fzurita** [comment]
Good news.... Whatever you did in this branch fixes the issue: https://github.com/gonetz/GLideN64/commits/feature_copyTexturedRect

**Comment by fzurita** [comment]
I think I'm getting closer to the cause of the problem. Instead of removing that line, I added a glFinish() right before the glBindFrameBuffer in the saveBuffer method.

This fixes the issue! At a cost though, I lose about 15% in FPS. This tells me though that it's some kind of synchronization issue.

**Comment by gonetz** [comment]
Looks like this. Data pipelined to be drawn to current buffer became discarded after switch to new drawing buffer. Serious drivers glitch if it is true.
Slowdown is better than nothing, we can add it as PowerVR specific crutch.

**Comment by fzurita** [comment]
I wonder if this would fix @loganmc10 issue as well.

**Comment by fzurita** [comment]
Replacing the glFinish with a glFlush doesn't fix the problem.

**Comment by loganmc10** [comment]
@fzurita yes, adding glFinish solves the problem for me, although it's obviously not ideal. Adding glFlush seems to work sometimes but is not consistent, which makes sense I suppose.

It seems to me to be a problem with the depth. If you look at this comment when I was dealing with this issue on the Raspberry Pi https://github.com/gonetz/GLideN64/issues/994#issuecomment-222589793, disabling the depth compare actually "fixed" the problem, just the image was incorrect of course.

I wonder if this suggestion would work?

> I suppose, that the problem can be with depth attachment. N64 usually uses only one depth buffer and swaps color buffers only. Thus, all FBO use different color attachment, but depth attachment is the same. Probably, particular combination of hardware/drivers can't handle it. You may try to create and attach separate depth renderbuffer for each new FBO and see if it helps.

**Comment by fzurita** [comment]
I did try out the changes suggested in issue #994 but they didn't really help. I do think you are right, it may be something related to depth... but why does the glFinish fix it?

**Comment by loganmc10** [comment]
You could try adding glFlush() in a different spot, I added it after this line:

https://github.com/loganmc10/GLideN64/blob/new_depth/src/FrameBuffer.cpp#L632

And it seems to solve the problem, but I don't know for sure because I am just taking screenshots via SSH (not in front of my device)

**Comment by fzurita** [comment]
Yeah, sure, I'll give that a try. The root cause of the problem though seems to be driver issues though.

**Comment by loganmc10** [comment]
Perhaps a bit of a hint towards the problem:

if I add
```
const GLenum discards[]  = {GL_DEPTH_ATTACHMENT};
glDiscardFramebufferEXT(GL_FRAMEBUFFER, 1, discards);
```

Right before the glBindFramebuffer() that you identified inside FrameBufferList::saveBuffer(), it looks a little better, it's not perfect but it definitely makes a difference for me.

**Comment by loganmc10** [comment]
Actually it seems to work very well if I add:
```
const GLenum discards[]  = {GL_DEPTH_ATTACHMENT};
glDiscardFramebufferEXT(GL_FRAMEBUFFER, 1, discards);
```

Before these 2 lines:
https://github.com/gonetz/GLideN64/blob/master/src/FrameBuffer.cpp#L163
https://github.com/gonetz/GLideN64/blob/master/src/FrameBuffer.cpp#L593

**Comment by fzurita** [comment]
Hmmm..... So you are telling OpenGL that the depth buffer is invalid. That's probably causing some kind of internal synchronization to take place. It's so add that our two devices behave so similar yet they are completely different GPUs. Maybe the same people made drivers for both....

**Comment by loganmc10** [comment]
I believe this issue is fixed completely by adding these lines:

```
const GLenum discards[]  = {GL_DEPTH_ATTACHMENT};
glDiscardFramebufferEXT(GL_FRAMEBUFFER, 1, discards);
```

Here:
https://github.com/gonetz/GLideN64/blob/master/src/FrameBuffer.cpp#L710

**Comment by loganmc10** [comment]
From what I read glDiscardFramebufferEXT / glInvalidateFramebuffer shouldn't really bring any kind of performance hit, so it might be a good solution if it works for you.

**Comment by fzurita** [comment]
I'll give that one a shot once I have a chance today. It will be really good if it works for my device as well.

**Comment by loganmc10** [comment]
After testing this a bit in front of the TV it looks good. No graphical glitches and frame buffer effects like the Zelda OoT pause screen work perfectly.

The cam spy in Perfect Dark doesn't look right (the image in the lens is all garbled, but it's not a black screen like it was before), I assume this might be because the Pi uses ColorBufferToRDRAMStub.cpp?

**Comment by fzurita** [comment]
It should be able to use the real color buffer to RDRAM now. But you will have to replace the ImageKHR code with raspberry specific code. Maybe this will help:

https://www.raspberrypi.org/forums/viewtopic.php?f=67&t=22620

**Comment by loganmc10** [comment]
Ya I looked at that a bit, Broadcom doesn't believe in documentation so it is hard to find reliable information, but I'll play around with it now that Framebuffer emulation is working

**Comment by fzurita** [comment]
Ok, just tried adding

```
const GLenum discards[]  = {GL_DEPTH_ATTACHMENT};
glDiscardFramebufferEXT(GL_FRAMEBUFFER, 1, discards);
```

in the attachDepthBuffer method. It did't fix it for me. I'll try adding this and glFlush in a few other places and see if anything makes a difference.

**Comment by loganmc10** [comment]
hm interesting, I guess that makes some sense since disabling depth compare didn't make any difference for you and it did for me, it's strange how the problem manifested itself so similarly but it's still somehow different.

**Comment by fzurita** [comment]
Can you tell me if this fixes it for you? Right after the ```glBindFramebuffer(GL_DRAW_FRAMEBUFFER, m_pCurrent->m_FBO);``` add ```glClear(GL_DEPTH_BUFFER_BIT | GL_COLOR_BUFFER_BIT);```

This fixes it for me and I get no drop in performance.

**Comment by loganmc10** [comment]
Ya that didn't fix it for me either, same problem as before

**Comment by fzurita** [comment]
Ok, this works for me, and no corrupt graphics in mario kart. Right after ```glBindFramebuffer(GL_DRAW_FRAMEBUFFER, m_pCurrent->m_FBO);``` in saveBuffer method add

```
   if (_address == gDP.depthImageAddress)
      glClear(GL_DEPTH_BUFFER_BIT);
```

Does this work for you?

I wonder if both solutions could be combined into one.

**Comment by loganmc10** [comment]
No that doesn't work for me, same issue as before.

**Comment by fzurita** [comment]
I'll can submit a pull request with both solutions combined into one.

**Comment by loganmc10** [comment]
Ok, since the fix for my device seems to be specific it can probably be wrapped in an "#ifdef VC"

**Comment by fzurita** [comment]
Well, so is my fix. But neither fix seems to harm performance or have a negative effect for devices that don't need it. So it may not make sense to warship around #ifdefs.

Also, for stuff like this, I would rather use a regular if statement since the plugin knows the name of each renderer.

**Comment by loganmc10** [comment]
Sure, im fine with either way

**Comment by fzurita** [comment]
Ok, I created pull request #1031.

**Comment by gonetz** [comment]
@loganmc10  Is it still actual?

**Comment by fzurita** [comment]
The issue is still present for PowerVR. Also, I got a chance to test on a Mali device and there is random screen flickering with frame buffer emulation enabled.

**Comment by fzurita** [comment]
The glClear/glFinish solution only partially fixes the issue for PowerVR, I still get random screen flickering with it.

**Comment by fzurita** [comment]
I'm going to close this since this is fixed with the glClear in https://github.com/gonetz/GLideN64/pull/1051/files

**Comment by loganmc10** [comment]
@fzurita do you still experience random screen flickering on Mali devices with Framebuffer Emulation enabled? (I notice you mentioned it a few posts up)

**Comment by fzurita** [comment]
Nope. Not after this pull request: https://github.com/gonetz/GLideN64/pull/1069
