### ISSUE TITLE
Color buffer read does not work on Android when 1x native resolution set.

### ISSUE THREAD

**Issue by gonetz** [gonetz/GLideN64#1018]
It does not crash, just does nothing.

**Comment by gonetz** [comment]
@fzurita Could you actualize this issue?

**Comment by fzurita** [comment]
This is not an issue any more.

**Comment by gonetz** [comment]
Thanks!

**Comment by fzurita** [comment]
There is a different problem though. It probably affects windows as well. In Conker's bad fur day, at 1x factor, the pause menu is corrupted. I'll make a new issue.
