### ISSUE TITLE
"filter" can be a reserved keyword

### ISSUE THREAD

**Issue by wareya** [gonetz/GLideN64#1020]
https://github.com/gonetz/GLideN64/blame/master/src/OGL3X/Shaders_ogl3x.h#L690

https://www.opengl.org/registry/doc/GLSLangSpec.4.00.8.clean.pdf

>The following are the keywords reserved for future use.  Using them will result in an error:
>[...]
>filter

**Comment by gonetz** [comment]
Fixed: e7be11f6
Thanks for the info.
