### ISSUE TITLE
Banjo Kazooie U 1.0 weird observation

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1021]
![capture](https://cloud.githubusercontent.com/assets/9299743/15917359/cc5919fa-2db0-11e6-91a8-8e2b72d38804.PNG)
Using PJ64, Countor Factor 1, and pressing F4 during gameplay to unlimit the FPS will cause the game display a lower resolution while using GLiden64. I think its FBE of some sort. you will also see a yellow 2002 with some numbers below it that are constantly changing. 

Do any of you know why this might be? is ther an issue with the plugin or the emulator of some sort?

**Comment by gonetz** [comment]
Does it happen with older versions of Project64, e.g. with 2.2 ?
May be emulator switches graphics plugin on fly by pressing F4?
I can't imagine what can make the plugin work that way.

**Comment by theboy181** [comment]
Does happen on lower versions. But doesn't happen on V1.1 ROM.
Also doesn't happen when using Jabo 1.7 RDP

its like a timing issue? it happens when the emulator drops too many frames as well I believe.

**Comment by gonetz** [comment]
Looks like timing issue. These yellow numbers written to frame buffer by CPU. I don't know for which purpose. Plugins detects that buffer modified by CPU and switches to CFB mode, that is shows low-res image from RDRAM. You may disable color buffer copy and you will get just black screen with numbers then. I can't consider this behavior as plugin's bug.
