### ISSUE TITLE
Perfect Dark Camspy bug at 2x native resolution or above.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#1024]
![gliden64_perfect_dark_000](https://cloud.githubusercontent.com/assets/10704701/16066825/0bc890f4-32fa-11e6-890f-4cc16f9acbbc.jpg)
As you can see, the camspy image kinda loops on itself.

**Comment by gonetz** [comment]
@AmbientMalice seems to be fixed now.

**Comment by baptiste0602** [comment]
It still happen for me, anyone else ?
