### ISSUE TITLE
Paper mario - Wrong electricity effect.

### ISSUE THREAD

**Issue by standard-two-simplex** [gonetz/GLideN64#1025]
In paper mario, whenever and electrical attack is used, there is an animation representing the electrocution. GLideN64 displays it wrong.

Incorrect effect with GLideN64
![paper_mario-001](https://cloud.githubusercontent.com/assets/12202580/16109140/a5d92106-33a7-11e6-9d48-3272ac1b869b.png)

Correct effect with AngryLions sowftware RDP
![nmqe0001](https://cloud.githubusercontent.com/assets/12202580/16108871/108b6d4e-33a6-11e6-85f7-750919de3e5e.png)

Savestate:
https://drive.google.com/file/d/0B8aIJkrbGl-zZ1pmRVZTdV9kZVU/view?usp=sharing

**Comment by gonetz** [comment]
Use "Emulate N64 depth compare" option. It is must here.

**Comment by standard-two-simplex** [comment]
I managed to make it work in Project64 but not in mupen64plus.
I used the same settings. Do you have no problem in mupen64plus?

**Comment by gonetz** [comment]
Can't check it right now. I'll tell you later.

**Comment by standard-two-simplex** [comment]
It turns out I was testing on different enemies.
The effect is not working on White Clubba's in neither emus and working on the rest of enemies I just tried.

https://drive.google.com/file/d/0B8aIJkrbGl-zMXA3alJ5WGgyQjQ/view?usp=sharing
A savestate in a fight with him.

**Comment by standard-two-simplex** [comment]
I tested on angrylions plugin and that enemy has the same wrong effect. I wonder if it happens in real n64.

**Comment by gonetz** [comment]
Testing on N64 can be tricky. It not always reads .fla files created by emulators.

**Comment by angrylion7** [comment]
Could you upload a Project64 savestate?

**Comment by gonetz** [comment]
White Clubba, mupen64plus, latest build of GLideN64:
![paper_mario-001](https://cloud.githubusercontent.com/assets/8983092/16199200/804f9e7a-372a-11e6-9186-3597b8d3155a.png)
![paper_mario-004](https://cloud.githubusercontent.com/assets/8983092/16199247/b0fc8f9c-372a-11e6-86be-cb193927c7fc.png)

**Comment by standard-two-simplex** [comment]
OK. So maybe it was my bad. Due to the square shape of the upper left part I thought it was bugged.

**Comment by gonetz** [comment]
Can it be closed?
