### ISSUE TITLE
Paper Mario - Pause Menu Background Incorrectly Emulated

### ISSUE THREAD

**Issue by RibShark** [gonetz/GLideN64#1026]
Here is what it should look like (using the Angrylion Graphics Plugin): 
![nmqe0000](https://cloud.githubusercontent.com/assets/1957489/16121650/fcd61e4e-33db-11e6-9e41-700ac15f1cf2.png)

As you can see everything including the scenery, background and characters is shown as the background to the pause menu.

Here is what it looks like under GLideN64 with "Copy Depth Buffer to RDRAM" set to either "Software" or "Disable":
![gliden64_paper_mario_000](https://cloud.githubusercontent.com/assets/1957489/16121772/71777f4a-33dc-11e6-8f9f-5b8ed4c09293.png)

All the scenery and characters are gone, leaving just the background. (With "Copy Depth Buffer to RDRAM set to "from VRAM", no graphical elements are visible leaving just a black background.)

**Comment by SigmaVirus** [comment]
I can confirm this issue on newer versions and the last working version of GLideN64 that showed the pause menu correctly for me was dated 2015-09-28.
However it's not game breaking, but would be nice to have displayed correctly.

**Comment by standard-two-simplex** [comment]
For the record, with the current build (rev.93be54a) the background in pause menu is black.

**Comment by SigmaVirus** [comment]
Sometimes it's grey too, it's really weird.

**Comment by ichee** [comment]
In latest version, set "Copy video card depth buffer to N64 memory" to never. Menu background then renders correctly.

**Comment by ichee** [comment]
Fixed in latest master with copyToRDRAM is set to synchronous.

**Comment by gonetz** [comment]
Good to know, thanks!
