### ISSUE TITLE
PowerVR slow Uniform buffer objects

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1029]
In PowerVR devices, Uniform buffer objects are very slow. Do uniform buffer objects provide any advantage in performance for devices where it doesn't cause a slow down?

If there is no performance advantage to uniform buffer objects in any devices and it causes performance issues in some devices. Should  we consider getting rid of them since they are detrimental at worst and no performance advantage at best?

I think we could use the uniform set approach everywhere.

**Comment by gonetz** [comment]
Serious question, which requires careful measuring.

**Comment by gonetz** [comment]
I've measured performance of desktop build from the state before UBO implemented and right after it.
UBO version works slightly faster on my PC. However, difference is subtle, circa 0.5% - on level of measurement bias. So, taken in account bad performance on mobile GPU this technology is rather harmful for the project.

**Comment by fzurita** [comment]
Ok, good to know. In reality, I have only seen it affect PowerVR badly.  With other GPUs I'm not seeing an impact as long as we use bufferData instead of BufferSubData

**Comment by gonetz** [comment]
@fzurita I made use of uniform blocks optional in this branch:
https://github.com/gonetz/GLideN64/compare/optional_uniform_block

Windows build still uses UniformBlock but can use UniformSet as well.
I currently put it in separate branch, but I think it will be merged to master soon.

I tested GLES3 Android build with UniformSet. It works ok, but still slower than GLES2 variant. The main slowdown somewhere in frame buffer emulation code. GLES3 is close to GLES2 with fb emulation off, but still slower on circa 15% Performance drops circa on 40% with fb emulation on.

**Comment by gonetz** [comment]
Android code need just few corrections in the makefile:
replace
```
LOCAL_SRC_FILES         := $(MY_LOCAL_SRC_FILES) $(SRCDIR)/OGL3X/UniformBlock.cpp $(SRCDIR)/OGL3X/GLSLCombiner_ogl3x.cpp \
                           $(SRCDIR)/common/GLFunctions.cpp $(SRCDIR)/BufferCopy/ColorBufferToRDRAM_GL.cpp

```
by
```
LOCAL_SRC_FILES         := $(MY_LOCAL_SRC_FILES) $(SRCDIR)/GLUniforms/UniformSet.cpp $(SRCDIR)/OGL3X/GLSLCombiner_ogl3x.cpp \
                           $(SRCDIR)/common/GLFunctions.cpp $(SRCDIR)/BufferCopy/ColorBufferToRDRAM_GL.cpp

```

**Comment by fzurita** [comment]
That's interesting. For me GLES3 is faster than GLES2 in my Adreno device. It was only hurting my PowerVR device. You do have a different device driver version.

Did replacing Blitframebuffer with your alternate approach make a speed difference in your device?

**Comment by gonetz** [comment]
> Did replacing Blitframebuffer with your alternate approach make a speed difference in your device?

No, no difference.

**Comment by fzurita** [comment]
Ok, this change is VERY nice for PowerVR. Performance is equivalent to Adreno now with frame buffer emulation disabled!

**Comment by fzurita** [comment]
With frame buffer emulation on PowerVR is much slower than Adreno still.

**Comment by gonetz** [comment]
That is very strange. I have all buffers copy disabled. That is the code does the same work as with GLES2. It is exactly the same with NO_BLIT_BUFFER_COPY enabled. Still, GLES2 works fullspeed on my device with fb enabled and looks faster than GLES3 even without fb.

**Comment by fzurita** [comment]
Are the settings exactly the same between the two profiles?

**Comment by fzurita** [comment]
Look at this file after running with GLES 2.0, then look at it again after running with GLES 3.0:

/sdcard/mupen64plus/GameData/SUPER MARIO 64 (U) 20B854B239203BAF6C961B850A4A51A2/CoreConfig/mupen64plus.cfg

I would diff the two versions of the file.

**Comment by fzurita** [comment]
Maybe the issue is with the color format.

**Comment by fzurita** [comment]
PowerVR still has issues with frame buffer emulation on causing a slow down much bigger in GLES3.0 than in GLES2.0. Maybe if I can find the issue in my device, it can lead to your issue as well.

**Comment by gonetz** [comment]
> I would diff the two versions of the file.

Diff shows that only CacheSize, EnableLOD and EnableShadersStorage are different.
I disabled LOD for GLES3 - no visible changes in speed.

**Comment by gonetz** [comment]
> Ok, this change is VERY nice for PowerVR.

I'll add it to master then. FB emulation performance is another issue.

**Comment by gonetz** [comment]
Merged.
