### ISSUE TITLE
Problems with 2D when Render Texrects in Native Resolution selected

### ISSUE THREAD

**Issue by standard-two-simplex** [gonetz/GLideN64#1030]
Many games display wrong 2D hen Render Texrects in Native Resolution is selected. Here are the issues it causes in OOT described, for further clarity:

1) A black box is shown in the place of the number of items, (i.e. slingshot bullets etc.).
2) Text is missing when checking a sign or speaking to an NPC. The blue box/arrow suggesting to press A is missing too.
3) Not glowing hearts occasionally disappear. It often happens just after loading a file, but it is harder to reproduce.
4) Magic bar has wrong color.
5) Number of rupees and small keys missing.

Strange thing, I noticed that when loading file 3, different bugs happen.

Save with 3 files.
https://drive.google.com/file/d/0B8aIJkrbGl-zTmVRRTA2REJObzg/view?usp=sharing

File 1. 
![gliden64_the_legend_of_zelda_000](https://cloud.githubusercontent.com/assets/12202580/16296336/08fa9150-392c-11e6-9d64-025fa92cd0c4.png)
File 2.
![gliden64_the_legend_of_zelda_001](https://cloud.githubusercontent.com/assets/12202580/16296344/127d85a2-392c-11e6-8a13-300145d5b70a.png)
File 3. Numbers are back, but stranger bugs happen.
![gliden64_the_legend_of_zelda_002](https://cloud.githubusercontent.com/assets/12202580/16296347/14e3c8c4-392c-11e6-8388-9f9b31133e88.png)
![gliden64_the_legend_of_zelda_003](https://cloud.githubusercontent.com/assets/12202580/16296348/176057ca-392c-11e6-816c-d4d562ae5b35.png)

**Comment by AmbientMalice** [comment]
This is likely a manifestation of https://github.com/gonetz/GLideN64/issues/975

**Comment by standard-two-simplex** [comment]
I happens each and every time, and going to fullscreen and back doesn't help. The bug #975 happens only from time to time and in different textures.

**Comment by gonetz** [comment]
Try to reboot your PC. If you will get the same errors, it is something new. If errors gone, it is #975

**Comment by standard-two-simplex** [comment]
I have the exact same issues after reboot too.

**Comment by oddMLan** [comment]
Maybe try deleting the texture cache and shaders GLideN64 generated? Reset to default settings?

**Comment by standard-two-simplex** [comment]
The bug appears only when Render Texrects in Native Resolution is selected.

**Comment by gonetz** [comment]
You did not say about it in problem description.

**Comment by standard-two-simplex** [comment]
I just discovered it, while testing different settings.

**Comment by oddMLan** [comment]
Render texrects in native resolution = 2Dfix branch?
or = 1x native resolution factor?

Sorry, I haven't been able to test the latest builds due to IRL stuff

**Comment by AmbientMalice** [comment]
@oddMLan Yea, it's the 2Dfix branch. It's been merged into the main branch now.

**Comment by standard-two-simplex** [comment]
Its a general issue, it happens in many games. Therefore, I change the title to address it correctly.

**Comment by gonetz** [comment]
Should be fixed by 30d6d127aa
