### ISSUE TITLE
Mario Kart 64 Observation

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1035]
I think I might have a clue on how jabo was able to get the jumbotron running at 30fps with next to no performance loss. 

He is bypassing the FBE and sending the screen updates to the jumbotron. You will see in a four player game that the jumbotron will have the entire four player spilt screen sent to it. 

If you use AL RDP it will only show a static image of the start of the race. 

To further this concept 1080s jumbotron uses this same emulation trick. You can see that the jumbotron doesn't display the camera effects with the white noise and scrolling image. 

It's a hack, but a great performance hack. You loose some accuracy for it though. Legend of Dragoon has figured out a way to increase the loops to have the screens display more fps but I wonder if this would kill performance? Still would be neat to see I hate the low fps on the jumbotrons. 

Thoughts?

**Comment by Nes-player4Life** [comment]
Sounds great. Anything to make Mariokart a better game in worth gold.

**Comment by loganmc10** [comment]
Why not just disable Framebuffer Emulation when playing Mario Kart? If you want speed over accuracy that is the way to go. Or just disable EnableCopyColorToRDRAM, I believe that would disable the jumbotron as well.

**Comment by weinerschnitzel** [comment]
I think this belongs in a separate fork of GLideN64 that boasts hacks and enhancements. As you stated the performance hack removes expected functionality.

**Comment by tony971** [comment]
Pass. I actually use that splitscreen multiplayer.

**Comment by theboy181** [comment]
After reading these comments I have come to the conclusion that no one really indestood my observation. 

In order to understand the observation look at the frame rate of the jumbotron on luigis raceway with GLideN64 and then Jabo. You will see that there is no performance loss with Jabo and that the FPS is 30 on the jumbotron instead of 7. 

The goal hear would be to improve the jumbotron performance and its framerate. Enhanced gameplay is always welcome.

**Comment by loganmc10** [comment]
Ya but you're modifying the way the game looks from the original, why not just put a big smiley face on the jumbotron? That would improve performance as well.

**Comment by standard-two-simplex** [comment]
What he meant is that the screen in Luigi's raceway is working as intended (smooth picture) with Jabo's plugin, whereas with GLideN64 it is choppy (game runs at intended fps, but screen texture is not updated, so it looks like its frameskipping).

**Comment by oddMLan** [comment]
GLideN64 is working like intended, as in the original console. The original console's Jumbotron is choppy as well.

**Comment by standard-two-simplex** [comment]
I only tried in Luigi's raceway, but GLideN64 is nowhere near the original console.
GLideN64: there is even tearing.
![gliden64_mariokart64_001](https://cloud.githubusercontent.com/assets/12202580/16503407/3603a51e-3f13-11e6-9984-4faa21daa5fc.png)
Real N64 video.
https://youtu.be/kIIzE_H7D2g?t=5m50s

**Comment by theboy181** [comment]
Not claiming that GLideN64 is doing it wrong at all. I.m trying to point out an opportunity for an enhancement just like Jabo's 1.7 Plugin . When we are doing HLE I don't think that the accuracy of the lower FPS is anyone's concern, so why not improve it if we can.

**Comment by AmbientMalice** [comment]
The real console updates 1/6 of the image each frame, or something like that. The tearing is likely less noticable at 320x240.

**Comment by theboy181** [comment]
LOD submitted to loop on GIT somewhere the other day.. You can notice the screen tearing at 320x240 as well.

**Comment by theboy181** [comment]
T

**Comment by tony971** [comment]
I really just don't want multiplayer shown in the window.

**Comment by gonetz** [comment]
@theboy181 Thanks for the idea.
Since the project has plenty of much more important tasks to do, I hardly will look at this anytime soon.
However, this is free project and if some dev is going to try it - good luck.

**Comment by MasterFox2492** [comment]
It's 2023 and this is still a problem. How in the world this system is still managing to present development challenges this far in the future is truly astounding. Starting to give up hope that this console will ever have 100% compatibility on anything other than original hardware.
