### ISSUE TITLE
Android: Performance regression with Native 1080P resolution.

### ISSUE THREAD

**Issue by retrobenny** [gonetz/GLideN64#1036]
The older version of the plugin as of 4/24/2016 ran MUCH faster in Native resolution mode compared to all of the updated versions after it.
The resolution,that's the part you can check in both the latest update copy and the older version mentioned to compare differences.

The main solution is to find some optimizations for rendering it at higher resolutions.
Having stuff like color to RDRAM (even async mode) on still causes slower speeds,so getting all of these optimized may help immensely.
Can software rendering also be done on frame buffering and/or color to RDRAM to hopefully lower overhead and gain even more speed?

**Comment by fzurita** [comment]
To do color buffer to RDRAM, you have to get the color buffer out of the GPU somehow, so you can't really do software mode for that. Only way I can think of is to have a software renderer that runs in parallel to the hardware renderer and at that point  you might as well be all in software.

So, do you get a slow down when you run at 1080p but run with native resolution set to 2x? Or do you have to lower the resolution as well?

**Comment by fzurita** [comment]
Also, if you run with async color buffer to RDRAM, it will be almost as fast as running with the frame buffer enabled.

**Comment by fzurita** [comment]
There is one valid point here though. Even though one can choose native resolution of like 2x, there are still some things that are being rendered at full resolution (is 1920x1080).

This did not seem to be an issue though until the new blending was added.

**Comment by gonetz** [comment]
> This did not seem to be an issue though until the new blending was added.

Current code renders FBO to screen without blending.

**Comment by gonetz** [comment]
> Can software rendering also be done on frame buffering and/or color to RDRAM to hopefully lower overhead and gain even more speed?

Of course, software render can be implemented for color buffer too. However, software rendering is serious task for desktop CPUs, so you hardly will get more speed on mobile hardware with it.

**Comment by retrobenny** [comment]
What about the beefy Shield TV hardware,wouldn't it be powerful enough to run it near its full potential?
Does the hardware rendering rely mainly on the GPU or does it make more use of CPU as well?
The Shield TV X1 GPU is on a really crappy clock speed of 200-300Mhz.

Thinking,depth being faster in software would assume everything else "could" be faster on the software end (can HLE software even be fully done?) if the idea is software switching to the more spacious CPU processing Ghz and maybe even multithreading could take huge advantage of it.
(unless software is like the horridly slow switch in Conker on the censor pixelation of Buga's Knuts)

If only someone could figure out how to render that pixelation effect properly in the normal mode.

**Comment by LegendOfDragoon** [comment]
>(can HLE software even be fully done?)

Why not? I don't think it's a good idea for weak CPUs though.

**Comment by AmbientMalice** [comment]
Of course HLE software renderers are possible. Jabo 1.7 is an HLE software renderer. Not a very good one, but it works.

**Comment by gonetz** [comment]
> Thinking,depth being faster in software would assume everything else "could" be faster on the software end

Software depth buffer rendering implemented in GLideN64 is very primitive. Depth buffer work is much simpler than rendering to color buffer, but my render reduced its complexity even more to get result as fast as possible. Depth buffer should not look nice, it just need to be more-less correct. Full software rendering of N64 graphics is hard computational task. Nobody proved yet, that Android hardware can handle it. Also, I have no intention to write software render myself.

**Comment by fzurita** [comment]
@retrobenny Do you think this can be closed with the legacy blending fix?

**Comment by retrobenny** [comment]
I would assume so,I don't see any bugs happening from it.

**Comment by olivieryuyu** [comment]
@retrobenny 

can you check status and close if needed? last blending update should have give a huger performance boost.

**Comment by retrobenny** [comment]
Can't confirm anything until I can actually test it on Android whenever the updates are ready.
(core issues in Mupen caused input to become messy,but was mentioned to only lose input if "resume" is used)
Still waiting on a functional build in order to test things,its out of my hands currently.

**Comment by fzurita** [comment]
@retrobenny you can get around resume being broken by just restarting the game. Feel free to test.

**Comment by retrobenny** [comment]
But your Drive link is broken for me because I believe that you might've deleted the file to prevent letting anyone run into nasty issues. 🙃

**Comment by fzurita** [comment]
Huh, whoops. I thought I had a working link. I'll post it again once I get home.

**Comment by retrobenny** [comment]
Closing this issue after your response/s because performance is now excellent and nearly identical to legacy blending,but you get all of those fancy visual effects. (exception being DK64's Tag Barrel transition effect lagging/at least Shield TV can render the most effects properly with its Desktop GL access)

Please release this update soon if you can confirm nothing else is oddly broken.
A minor nitpick,the touchscreen controls appear briefly on game boot even though I have the profile for each game set to disabled and it is a little annoying,is that a workaround for an issue?

**Comment by fzurita** [comment]
That's a strange one, go to settings, then input. Make sure accessibility is set to "Big screen mode" or auto detect.

**Comment by fzurita** [comment]
Also, I can't release yet. There are some annoying bugs I need to fix.

**Comment by retrobenny** [comment]
I use the full mode to avoid losing settings access for some things I like to have available.
Hope you can iron out those bugs. 👍

Closing issue now.
