### ISSUE TITLE
Missing GLN64 ARM Neon optimizations

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1037]
The GLN64 arm neon optimizations are missing. See this file to see what I mean:

https://github.com/mupen64plus-ae/mupen64plus-ae/blob/master/jni/mupen64plus-video-gln64/src/3DMathNeon.cpp

I'm sure these would provide a nice performance boost in Android/Raspberry Pi

Edit: So I don't forget, here is another file that has Neon optimization in GLN64 that are missing from GLideN64.

https://github.com/mupen64plus-ae/mupen64plus-ae/blob/master/jni/mupen64plus-video-gln64/src/gSPNeon.cpp

And here is a listing of all optimizations that GLN64 for Android uses that may be missing from GLideN64 as well: https://github.com/mupen64plus-ae/mupen64plus-ae/blob/master/jni/mupen64plus-video-gln64/Android.mk

    __CRC_OPT
    __HASHMAP_OPT
    __TRIBUFFER_OPT

**Comment by gonetz** [comment]
@fzurita  GLideN64 code already has legacy win32 asm code. I don't mind to add neon asm as well, but I don't have time for that. Could you take this task?

**Comment by fzurita** [comment]
Yep, I was actually planning to do it. I created the issue so I wouldn't forget.

**Comment by fzurita** [comment]
So I don't forget, here is another file that has Neon optimization in GLN64 that are missing from GLideN64.

https://github.com/mupen64plus-ae/mupen64plus-ae/blob/master/jni/mupen64plus-video-gln64/src/gSPNeon.cpp

**Comment by fzurita** [comment]
3DMath neon optimizations were easy to port. I don't see much of an improvement in performance though.

I'm porting the gSP neon optimizations now, those are a little trickier.

**Comment by fzurita** [comment]
The gSP Neon optimizations may actually be helping. Doesn't seem by much though, maybe 5% improvement.

**Comment by fzurita** [comment]
The __TRIBUFFER_OPT optimizations looks interesting, but much harder to port. I'll probably try running GLN64 without them to see if it makes any difference.

**Comment by gonetz** [comment]
@fzurita Neon code is in master. Do you plan to do anything else for this ticket?

**Comment by fzurita** [comment]
I was planning to look at the __TRIBUFFER_OPT compiler define in glN64, but I can make another ticket for that.
