### ISSUE TITLE
Model alignment issues on Mario Party 1/2/3 on Raspberry Pi

### ISSUE THREAD

**Issue by carydias** [gonetz/GLideN64#1038]
Looking for any hints on how to help debug this one.

Using the latest code-base on a Raspberry Pi, in all three of the Mario Party games, the game squares do not align with the background texture.

Furthermore, the characters themselves appear to be invisible.  It could be that they are aligned with the game squares on some other part of the board off-screen.  Changing the resolution does seem to move the squares around somewhat.  But it could be random.

Can anyone give me some pointers as to how to help debug this?

The errors also occur using:
https://github.com/ricrpi/mupen64plus-video-gles2n64
I'd imagine much code is shared between the two plugins..,?

![image](https://cloud.githubusercontent.com/assets/11141903/16398727/fc640d08-3d0f-11e6-8391-bb4acb8cfa8a.png)
![image](https://cloud.githubusercontent.com/assets/11141903/16398746/15877568-3d10-11e6-9a60-c38d093d7942.png)

**Comment by loganmc10** [comment]
The only way i found to fix this is to run at native resolution (320x240), I was using a bit of a hack to SDL2 to accomplish this and still play full screen.

Now that Framebuffer emulation works on the Raspberry Pi you could try enabling that and setting UseNativeResolutionFactor to 1, I haven't tried that yet though.

**Comment by carydias** [comment]
It does seem that forcing everything to 320x240 does make this work...  I also found your SDL patch Logan - nice work.

Setting EnableFBEmulation = True on GLideN64 on the Pi results in no video still with the latest code.  

I'll keep digging.

**Comment by loganmc10** [comment]
I'm surprised you have no video with the latest code. I've been using Framebuffer Emulation on my Raspberry Pi successfully for the past few days.

**Comment by carydias** [comment]
Logan, do you mind supplying your [Video-GLideN64] properties?

Maybe I have a conflicting setting.

**Comment by carydias** [comment]
Can confirm:
EnableFBEmulation=True
UseNativeResolutionFactor=1

Causes the game to run in 320x240 and all the components are aligned as expected. :-)

Thanks for your help @loganmc10

**Comment by loganmc10** [comment]
Ya framebuffer emulation is probably going to be more taxing, you might have to overclock the GPU (gpu_freq=500 in config.txt) if you haven't already.

**Comment by gonetz** [comment]
@carydias  is it still actual?

**Comment by Eloo** [comment]
Mario Party seems still to be broken with the GLideN64 version RecalBox uses.
Any solutions or workarounds aside from the 320x240 hack?

**Comment by pschiume** [comment]
Have anyone succeed with the 320x240 hack?  I still can't display the game correctly.

I'm using MUPEN64PLUS emulator with GLIDEN62 as core.

I'm editing the conf file localted in /recalbox/share/system/configs/mupen64/mupen64plus.cfg with:
EnableFBEmulation=True
UseNativeResolutionFactor=1

When I restart recalbox, the EnableFBEmulation return to False.

Thanks in advance for your help
