### ISSUE TITLE
Add support for RSPTHREAD in mupen64plus

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1049]
I am trying to get the opensource graphics driver for the Raspberry Pi working with GLideN64. It uses a lot more CPU than the closed source driver, so it would be nice to be able to use RSPTHREAD with mupen64plus, so that GLideN64 can have it's own thread, since the Pi has 4 cores.

It actually works quite well, but I had to make a few minor changes to get it to work or I get these errors:

```error: invalid initialization of non-const reference of type 'APICommand&' from an rvalue of type 'APICommand'
  _callAPICommand(ProcessUpdateScreenCommand());```

In PluginAPI.h, the line needed to be "void _callAPICommand(APICommand && _command);" (two &'s), same with "void PluginAPI::_callAPICommand(APICommand && _command)" in CommonAPIImpl_common.cpp.

Also, in MupenPlusAPIImpl.cpp, there is this line: "_callAPICommand(acRomClosed);", but it doesn't look like "acRomClosed" exists. If I comment out that line it all seems to work, but I'm sure that's not right.

I didn't submit a pull request because I'm not sure if the double &&'s will break anything on the Windows build with Zilmar graphics.

**Comment by loganmc10** [comment]
I'm not suggesting RSPTHREAD be enabled by default for mupen64plus (I'm not sure what all the side effects would be), but it would be nice to have the option for certain devices with weaker multi-core CPU's

**Comment by loganmc10** [comment]
I have a working branch of this here if anyone wants to try:

https://github.com/loganmc10/GLideN64/tree/rspthread

You just have to define RSPTHREAD (-DRSPTHREAD) somewhere in CMakeLists.txt

**Comment by gonetz** [comment]
RSPTHREAD does not make GLideN64 working in its own thread and will not help you to get more from your 4core cpu. This feature has only one purpose: do all GL calls in the same thread, otherwise GL will crash. Project64 has/had an issue: it calls plugin initialization from one thread, but de-initialization called from another thread. Thus, plugin creates its own thread to work with GL. Mupen64plus works with threads correctly, thus RSPTHREAD is useless for mupen64plus build of GLideN64.

**Comment by loganmc10** [comment]
hm now that I'm home and I'm testing this more it appears that is right, my total CPU usage still doesn't go over 100% in top. I guess there is no way to accomplish this because everything needs to stay synchronised? Anyway the answer is obviously not with RSPTHREAD so I'll close this issue

**Comment by gonetz** [comment]
Yes, emulator stays still until graphics plugin finish its work with current display list and vice versa.
