### ISSUE TITLE
Power League Baseball 64: missing 3d & very weird black background in game

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#105]
![dfg](https://cloud.githubusercontent.com/assets/8987490/4942800/0d5aa9c2-65ef-11e4-89dd-11e3ea9314ad.jpg)

**Comment by gonetz** [comment]
Another impostor ucode, which claims that it is "RSP SW Version: 2.0D, 04-01-96" but in fact it is something else. In this case actual ucode belongs to F3DEX family.
I have added it to "special ucodes" list, to the company of other similar impostors like WaveRace US custom ucode.
