### ISSUE TITLE
Zooming into effects causes performance usage overload.

### ISSUE THREAD

**Issue by retrobenny** [gonetz/GLideN64#1052]
My usual test game is Banjo-Tooie so here is one easy example of the issue.
It even causes my Shield TV Pro itself to lag with full UI slowdown.
The issue can be triggered by looking at a single fire torch in Mayahem Temple's Treasury at the top entrance.

My plugin settings are at the fastest I can get them to prove it still slows down,but using Native primary resolution at 1080P where it previously ran really well in April.

Settings: Enable LOD,Persistant Shader Storage,Frame Buffer on default "buffer" refresh,Color to RDRAM **disabled**,Native Resolution Factor 4x (faster somehow),Prevent Read/Write FBinfo unchecked,Read Color Buffer in 4KB checked and Read Depth Buffer in 4KB checked (despite color/depth buffers being disabled),

Some screenshots and 2 savestates with and without the 60fps hack code.

Full speed 60fps viewed indirectly.
![indirect fire 60fps hack lagfix](https://cloud.githubusercontent.com/assets/16418716/16642392/25c37ee2-43d0-11e6-842f-a995af62afa2.png)
Slowdown 60fps close and direct.
![close direct fire 60fps hack lagfix](https://cloud.githubusercontent.com/assets/16418716/16642396/2ffa44c2-43d0-11e6-8875-d3084eccc623.png)
Devastating slowdown 60fps zoomed in,even affecting device itself.
![zoomed fire 60fps hack lagfix](https://cloud.githubusercontent.com/assets/16418716/16642403/416abc0a-43d0-11e6-87fd-60aeaa9bb14f.png)
And slowdown SEEMS less bad on hackless 30fps but the same devastating effect on the device.
![zoomed fire no hack](https://cloud.githubusercontent.com/assets/16418716/16642426/678c92f0-43d0-11e6-85c4-85d60b1b68b3.png)

Hope I didn't break it when I accidentally uploaded the same pic twice and had to backspace it.

Now the savestates in a zip file.
[Slow Fire Torch Savestates.zip](https://github.com/gonetz/GLideN64/files/351416/Slow.Fire.Torch.Savestates.zip)

Hope you can debug this issue as it affects most games in various conditions such as Zelda OOT with 51fps out of 60fps on the file select screen.

**Comment by retrobenny** [comment]
Probably should have said this immediately,so I apologize for not doing so.

Forgot to mention,be careful when loading the savestates,when they can put a Shield TV on its knees,there's no telling what might happen with other devices other than possibly overheating them or worse case scenario frying them,so look away immediately via analog stick to make the slowdown go away and look at it again briefly when attempting to debug it.

**Comment by fzurita** [comment]
I don't think it could be that bad. It's hard for software that doesn't have root privileges to cause damage to software.

**Comment by retrobenny** [comment]
Don't be so sure about it,some devices are not well equipped in the processor brands as obvious issues in several qualcomm chips,even some of the more recent ones.
For example,something as simple as reicast running can cause a panic attack on a FireTV box,flat out rebooting it,unless they fixed it in a later build,but that project seems to be dead unfortunately.

**Comment by retrobenny** [comment]
Brought it down to one primary instance,the high resolutions and rendering stuff at them.
Either if you use 1080P regardless of resolution factor use besides pointless 1x degrade,or using any small size with 4x resolution scale,it gets very slow and demanding in most places,especially the fire torch.
So the main thing is that rendering at a higher resolution has gotten quite a bit too demanding,so it will need some tinkering to hopefully get it optimized to make that smooth performance return.
Gruntilda: I wouldn't know much more to say,so I hope all of this helps in some way.

**Comment by fzurita** [comment]
@gonetz the legacy_blending branch fixes this slowdown.

**Comment by gonetz** [comment]
Good to know that it is useful for something. I may add it to master at any moment.

**Comment by gonetz** [comment]
@retrobenny legacy_blending option is in mupen64plus-ae master. Please test

**Comment by retrobenny** [comment]
Oh,sorry I didn't think about it until now that I should test the option on/off to see if it triggers correctly,sorry about that guys. I'm on it!

**Comment by retrobenny** [comment]
Okay I tested it and the option works just fine with checked running at solid speeds and unchecked running at new blending's slower speeds.

I still wonder if something could be done to optimize it like figuring out a proper way for multithreaded blending or offloading it to another core without losing anything.

If GLideN64 could be thoroughly multithreaded entirely,it would be crazy fast with the most accurate settings enabled,but I doubt it could work properly unfortunately,even though Cen64 proved to run decently with emulation multithreading.

Although,theoretically if Vulkan was used,multithreading with it is supposedly easier to do and it works even better than how GL does it,Vulkan IS faster too and has lower overhead.
Also,what do you think about the recent RetroArch N64 Vulkan (ParaLLEl) implementation?

**Comment by loganmc10** [comment]
This new blending mode happens with GPU shaders. Vulkan multithreading wouldn't help. Although I suppose there might be some feature in Vulkan that could handle the blending better? Who knows. Not many devices out there current support Vulkan, especially mobile devices.

Also, ParaLLEl is a port of Angrylion to Vulkan, and they hope eventually GL 4 or something. It currently has all kinds of graphical glitches, and it will never run well on mobile devices, I doubt it would ever work properly even on a Shield.

**Comment by retrobenny** [comment]
"especially mobile"? I thought mobile was the main reason of Vulkan benefits?
Many qualcomm devices are getting Vulkan drivers which means they can access up to GL 4.5 features.
So a Vulkan variant would greatly help accross all brands,more-so for Shield TV with even faster speeds from the lower overhead bonus.
Still have yet to see EGL and ES 3.x VS. Vulkan single thread performance comparison unfortunately.

**Comment by fzurita** [comment]
I think it would be worth trying to port ParaLLEl to Android. If the GPU can do Vulkan and is strong enough, I don't see why it wouldn't work equivalent to PC.

I may give it a shot. I was able to port the libretro implementation of Glide64 to Mupen64plus-AE. I'm thinking it would be a similar process except that I have to port a LLE RSP as well. Who know, maybe I'm being naive about it.

**Comment by loganmc10** [comment]
I'm talking about paraLLEl, not Vulkan. I mean that paraLLEl is not going to work well on mobile devices. There is too much work to do, you can re-arrange the API however you like, but the GPU still has the same hardware, and Vulkan multithreading isn't going to help offload any work that the GPU has to do.

**Comment by retrobenny** [comment]
The numbers are solid in the provided Vulkan fish benchmark compared to GL ES 3.x but lacks EGL.
Vulkan outperforms ES 3.x rather well and splits off the load to all cores better.

Still,as it stands,ParaLLEl uses Vulkan,and this tidbit...
"Vulkan is a low level API that gives direct access of the GPU to developers who want the ultimate in control." Also,"efficient multi-threading" "new level of performance on existing hardware" too.

Alone,the direct access part should mean it can raise the GPU scaling to anything higher than 300Mhz whenever it wants so performance doesn't stay sluggish.
That could make a world of difference in the way it might allow higher GPU Mhz above the pathetic scaling of 200-300Mhz.
I wonder if the same could be done with Dolphin if a Vulkan implementation was made,if I assume correctly,it could potentially raise the GPU scaling to a much more deserving height to maintain performance,all while having less overhead,then again,the JitARM64 is the current bottleneck for Dolphin.

If otherwise unable to boost the GPU via Vulkan,maybe we can get enough people to complain about Shield TV's lackluster GPU performance in demanding situations so they can mitigate it on the next OTA update with a better "Max Performance" profile,renaming the current one to just "Performance".

Does the legacy blending mainly focus on CPU? That would explain the performance gap.

**Comment by gonetz** [comment]
> Does the legacy blending mainly focus on CPU? That would explain the performance gap.

No, legacy blending uses only GPU fixed functionality, while new blending is shader-based.

**Comment by retrobenny** [comment]
Okay,found this one again,closing it because performance issues related to blending have been dealt with and now both types run near identically or at least way better.
