### ISSUE TITLE
Regression in latest Texture Cache fixes.

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1054]
The floor tiles in GoldenEye are showing up wrong. It becomes apparent very quickly in the first level (the Dam)
I tested this here:
154c06b14f2c8bc39442eee179e8bf7c5698a98b

and then again here:
803eb1d3814e469b811f3b60b5df35d8197b71f6

and it is definitely a regression with the recent texture cache fixes.
![snapshot](https://cloud.githubusercontent.com/assets/848146/16665299/4e331872-4440-11e6-89b3-7056d23b20e0.png)

They flicker back and forth between the correct texture and the incorrect one. I don't notice anything else wrong except the floors, and I haven't noticed this in any other game so far.

**Comment by Frank-74** [comment]
There's a similar bug in Glide64.  When changing weapon, the floor tiles switch resolution when the gun is changed for a split second.  When the sniper rifle butt is selected, the floor tiles stay on the lower resolution.  Jabo has a hack that stops updating the display, so there is a micro stutter on changing weapons.  More noticeable with higher counter factor setting.

**Comment by loganmc10** [comment]
It flickers just walking around, and it will stay permanently on the wrong texture if you stop moving. I'm pretty sure it is just a case of the texture cache loading up the wrong texture because the checksums are the same when they shouldn't be.

**Comment by loganmc10** [comment]
Also, when I run Perfect Dark on debug mode, about 3-4 seconds in this assert fails:

```Textures.cpp:1460: void TextureCache::update(u32): Assertion `current.format == pTile->format' failed.```

This is with the regular CRC calculator

**Comment by matthewharvey** [comment]
I get the same assert after about 3-4 seconds in Beetle Adventure Racing.

**Comment by gonetz** [comment]
@loganmc10 @matthewharvey I found that games can use the same data for two textures with different formats, so I added tile format and size to checksum. Please check, it may fix the reported issues. 
https://github.com/gonetz/GLideN64/commit/d1749518caeebcc463d824d602797a6b46ef17dc

**Comment by matthewharvey** [comment]
I'm still seeing texturing issues (conflicts of some kind maybe?) on Beetle Adventure Racing. There is supposed to be just fence on the right and left here, but the metal grating gets in the way as the mipmap gets smaller.

![screenshot from 2016-07-12 06-31-43](https://cloud.githubusercontent.com/assets/1594441/16764155/8a463ce6-47fa-11e6-87ae-e8ccd7082c37.png)

**Comment by loganmc10** [comment]
The floor tile issue is still present in GoldenEye, buy I only notice it on the first level (the dam)

**Comment by Jj0YzL5nvJ** [comment]
Many new bugs in GoldenEye with mupen64plus

Tested in [0ffaf66](https://github.com/gonetz/GLideN64/commit/0ffaf66de0f7dd1add8d84924a20127609db4516):
http://imgur.com/a/K19k4

Old bugs, tested in [154c06b](https://github.com/gonetz/GLideN64/commit/154c06b14f2c8bc39442eee179e8bf7c5698a98b)
http://imgur.com/a/moozU

**Comment by gonetz** [comment]
Should be fixed now: feb446c3

**Comment by loganmc10** [comment]
This is fixed now, GoldenEye looks normal to me. thanks! Since other people reported some issues I'll hold off closing this until they report back as well I guess?

**Comment by matthewharvey** [comment]
Fixed for Beetle Adventure Racing as well.
Thanks!

**Comment by Jj0YzL5nvJ** [comment]
Fixed in mupen64plus too.

Even so, I continue seeing the same "bug" mentioned in 154c06b... "maybe" this not a bug. In TV and low-res it would go unnoticed. With glide64* this don't happen...

**Comment by gonetz** [comment]
@Jj0YzL5nvJ what's wrong on your screen shots from 154c06b? I can't see any particular issue beside garbage on left and right of the screen.

**Comment by Jj0YzL5nvJ** [comment]
This a capture using glide64mk2:
![goldeneye-000](https://cloud.githubusercontent.com/assets/12230570/16897112/e4ddb446-4b64-11e6-94aa-8a7057540f9b.png)

In GLideN64 154c06b and 0263eb3, the textures seem blurry to the distance.

**Comment by gonetz** [comment]
> the textures seem blurry to the distance.

It is not a bug. GE and PD use mip-mapped textures heavily. The further an object the less detailed tile is used for it. You may disable mip-mapping emulation if you don't like it.

**Comment by Jj0YzL5nvJ** [comment]
Yeah, you are right. I don't really mess much the configuration file.

Well, "EnableLOD = False" to me /gg

**Comment by gonetz** [comment]
@loganmc10 is anything left to do for this ticket?

**Comment by loganmc10** [comment]
No I believe this is fixed
