### ISSUE TITLE
Assertion when using optimized texture CRC calculation

### ISSUE THREAD

**Issue by matthewharvey** [gonetz/GLideN64#1060]
Observed after 3-4 seconds after the start of 3D (after logos) on Beetle Adventure Racing, among other games.

Bisected back to 2bc803d

**Comment by loganmc10** [comment]
This won't get fixed, the optimized CRC calculator probably isn't perfect but it's much faster, it's a trade off. Gonetz didn't write it snd neither did I, it was "poached" from a mobile optimized version of gln64.

**Comment by matthewharvey** [comment]
This crash was reported in Perfect Dark as well. I reproduced that crash as well.

After d1749518caeebcc463d824d602797a6b46ef17dc both of these crashes are gone, so I'm closing this issue.
