### ISSUE TITLE
__VEC4_OPT creates incorrect lighting for CBFD

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1063]
With __VEC4_OPT enabled:
![conker_bfd-000](https://cloud.githubusercontent.com/assets/11581687/16975347/6031d518-4e13-11e6-9674-caae04246e5b.png)

Without __VEC4_OPT:
![conker_bfd-001_correct](https://cloud.githubusercontent.com/assets/11581687/16975503/2dcb843c-4e15-11e6-9bb8-ea78bbe47ad7.png)

Check the tail.

Also, this game uses special versions of the gSPLightVertex4 and gSPPointLightVertex4 which don't have any neon optimizations.

I haven't noticed this with any other game yet.

**Comment by gonetz** [comment]
I guess, I made a mistake in gSPPointLightVertex4 or gSPLightVertex4 for this game.

**Comment by fzurita** [comment]
Yeah, I'm looking into it. I'm not seeing any obviously incorrect differences from the non-optimized versions of these functions.

**Comment by gonetz** [comment]
BTW, do you see any positive effect from VEC4 optimization?

**Comment by fzurita** [comment]
The neon optimizations require this enabled and I do hear very good performance improvements with the neon optimizations enabled, but only under specific circumstances.

**Comment by fzurita** [comment]
I do see difference that doesn't make sense in gSPCBFDVertex, 

```
vtx.a = vertex->color.a * 0.0039215689f;
```

This is being set twice.

**Comment by fzurita** [comment]
It definitely has to do with this piece of code:

```
#ifdef __VEC4_OPT
		for (; i < n - (n%4) + v0; i += 4) {
			u32 v = i;
			for(int j = 0; j < 4; ++j) {
				SPVertex & vtx = render.getVertex(v+j);
				vtx.x = vertex->x;
				vtx.y = vertex->y;
				vtx.z = vertex->z;
				vtx.s = _FIXED2FLOAT( vertex->s, 5 );
				vtx.t = _FIXED2FLOAT( vertex->t, 5 );
				if (gSP.geometryMode & G_LIGHTING) {
					const u32 normaleAddrOffset = ((v0+v+j)<<1);
					vtx.nx = (float)(((s8*)RDRAM)[(gSP.vertexNormalBase + normaleAddrOffset + 0)^3]);
					vtx.ny = (float)(((s8*)RDRAM)[(gSP.vertexNormalBase + normaleAddrOffset + 1)^3]);
					vtx.nz = (float)((s16)(vertex->flag&0xFF));
					vtx.a = vertex->color.a * 0.0039215689f;
				}
				vtx.r = vertex->color.r * 0.0039215689f;
				vtx.g = vertex->color.g * 0.0039215689f;
				vtx.b = vertex->color.b * 0.0039215689f;
				vtx.a = vertex->color.a * 0.0039215689f;
				vertex++;
			}
			gSPProcessVertex4(v);
		}
#endif

```

inside the gSPCBFDVertex method. If I comment that optimization out, the issue goes away.

**Comment by gonetz** [comment]
vtx.nz = (float)((s16)(vertex->flag&0xFF));
                    vtx.a = vertex->color.a * 0.0039215689f; // this line must be removed

**Comment by fzurita** [comment]
Yep, I did attempt removing that line, it didn't make a difference. Also
```
vtx.nz = (float)((s16)(vertex->flag&0xFF));
```

Is different from the non-optimzed version:
```
vtx.nz = (float)((s8)(vertex->flag&0xFF));
```

I tried changing that too and it didn't fix it though. I didn't think it would though since it's just a cast.

**Comment by fzurita** [comment]
This line is also different:

```
const u32 normaleAddrOffset = ((v0+v+j)<<1);
```

From the non-optimized version.

**Comment by gonetz** [comment]
Yes. 
((v+j)<<1); ?

**Comment by fzurita** [comment]
Yep, I just tried that. It fixed it.

**Comment by gonetz** [comment]
Great!

**Comment by gonetz** [comment]
Pull request?

**Comment by fzurita** [comment]
Yeah, sure, I'll submit.

**Comment by gonetz** [comment]
Ok
