### ISSUE TITLE
Poor performance on Adreno 304 even though GPU is not "maxed"

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1067]
I've been looking at the performance of GLideN64 on an Android phone with an Adreno 304. Admittedly it is a fairly weak GPU, but even so, it seems that there is a bottleneck somewhere that could be addressed. I assume it would benefit other GPU's as well.

According to the GPU Profiler, the shaders (and the ALU's) are only about 70% busy, and the GPU as a whole is about 35% busy. Yet Smash Bros (the game I am testing with), is very laggy, about 25 FPS.

The screenshots show some of the results from the profiling. The Adreno GPU profiler gave some performance tips that you can see.

It seems like it could be a couple things: Perhaps there are too many draw calls? It seems to complain that each draw call doesn't actually draw too much. This could be addressed by some form of batching or using VBO's it seems?

There are other things that could be done on Android devices like using compressed textures, or using glEGLImageTargetTexture2DOES() instead of glTexImage2D(), but I am running this at 320x240, I doubt the size of the textures is a big issue.

![untitled2](https://cloud.githubusercontent.com/assets/848146/17039202/7f235f5c-4f56-11e6-8843-79b00d4e548d.png)
![untitled1](https://cloud.githubusercontent.com/assets/848146/17039203/7f240d58-4f56-11e6-9f2e-13c084b22981.png)
![untitled3](https://cloud.githubusercontent.com/assets/848146/17039201/7f22b322-4f56-11e6-8c97-9d0e2aa7fe1c.png)

**Comment by loganmc10** [comment]
I run into this with an Adreno 405 and an Adreno 320. The 405 runs pretty much exactly the same as the 304, even though it has about twice the ALUs. The 320 runs a bit better, but it should run much much better than the 304, and it's only marginal. Looking at the 320 in Snapdragon Profiler (during Smash Bros), says that the GPU is 12-15% utilised.

This tells me that there is some kind of bottleneck holding these devices back. I don't know if its unique to Adreno devices, I don't have any other mobile device, just my beloved Raspberry Pi.

**Comment by gonetz** [comment]
Backface culling disabled: it is for rectangles. Enabling it will not speed up rendering. It is possible to get rid of enable/disable GL calls though.

Uncompressed textures are hardly the problem.

VBO is not used, it's true. I'm planing to add them.

Few primitive par draw call: that depends on how game is written. Some games can accumulate hundred polygons per draw call, others one-two.

Discrete triangles: this is N64 specific. Display list consists of discrete triangles.

**Comment by loganmc10** [comment]
I'm just going to post this here so I remember to read through it thoroughly later:

https://github.com/hrydgard/ppsspp/issues/2007

It seems like the exact same problem

**Comment by fzurita** [comment]
Interesting, so they basically did some of the stuff that the draw calls were doing in software so that they could do less draw calls. Almost like batching up a bunch of draw calls into one.

**Comment by loganmc10** [comment]
This is definitely something that affects Adreno devices more. I've been testing with a phone with a Mali T860-MP2, which is supposed to be similar to an Adreno 405, but the Mali device blows the Adreno 405 out of the water with GLideN64, full speed on GoldenEye and Smash Bros with the Mali phone.

**Comment by retrobenny** [comment]
I would like to try out an update with that change for less draw calls to see if it runs any faster than it currently does on my Shield TV.
I wonder if there's any other exhaustive primitive stuff that can be done in software with better results to performance and lowering all calls and commands to a much lower amount?
I say primitive meaning standard functions that don't have overly-complex coding that would otherwise require using hardware to do them to maintain optimal performance.

**Comment by loganmc10** [comment]
> I would like to try out an update with that change for less draw calls to see if it runs any faster than it currently does on my Shield TV.

All you have to do is write it first.

**Comment by retrobenny** [comment]
I don't have the prowless or the skill to do such a thing. :(

**Comment by LegendOfDragoon** [comment]
@loganmc10 do you know any similar profiling programs like that for the PC? I'd like to profile, if I knew a good one to use.

**Comment by Sarkie** [comment]
@loganmc10 I'm getting poor performance with Adreno 305 in my Moto G, can play with the other plugins with graphical errors, but they are playable. 

I assume you are using

https://developer.qualcomm.com/download/adrenoprofiler/adreno-profiler-64bit.zip

in your screenshot?

**Comment by loganmc10** [comment]
Correct

**Comment by Sarkie** [comment]
![gpu](https://cloud.githubusercontent.com/assets/283203/17594096/f3b954a4-5fdf-11e6-9047-d387e5afde27.png)

Not sure what parts of the profiler which might be useful for you.

**Comment by loganmc10** [comment]
hey @fzurita if you ever get a chance can you try this branch of GLideN64 with mupen64plus-ae?

https://github.com/loganmc10/GLideN64/tree/ebo2

I don't have an Adreno device handy anymore to test this to see if it makes any kind of a difference.

That uses a VBO for the glDrawElements call along with a cache, similar to how the texture cache works, so instead of uploading the triangles from the CPU to the GPU every time glDrawElements is called (multiple times per frame), it switches to a VBO with the information cached in GPU memory.

If that increases performance at all, something similar could probably be done for the glDrawArrays calls, but that would be more complicated.

**Comment by fzurita** [comment]
Yeah, sure, I'll give it a shot tonight. I hope that is the magic bullet for Adreno.

**Comment by fzurita** [comment]
I'm seeing 20% drop in performance for games that already performed well. For games that had bad performance, like banjo kazooi and ssb, I'm seeing no difference in performance.

**Comment by loganmc10** [comment]
There is definitely an opportunity to combine some draw calls. If you look at a snippet this apitrace (this is using the VBO code I'm working on, but the principle is the same regardless), you can see that it sets the GL program, draws some triangles, sets a different GL program, draws some triangles, then switches back to the first GL program, draws some triangles, etc...

By reordering the draw calls, instead of "flip flopping" between programs, you could combine them into larger draw calls.

However I'm sure implementing that would be tricky, you don't really know what you're going to be drawing until it's "right in front of you", so you'd have to store the information in some kind of cache, then when you are ready, reorder the draw calls and draw it all.

![vbo](https://cloud.githubusercontent.com/assets/848146/17788298/2fc13baa-654a-11e6-9535-16a5c6a115d0.png)

**Comment by fzurita** [comment]
Is this output from the Adreno GPU profiler?

**Comment by loganmc10** [comment]
No that is from apitrace: http://apitrace.github.io/

There is some way to get it to work on Android, but I've never figured it out, I believe you probably need a rooted phone, but the GL calls of the program would be the same on Android or on a laptop (besides any Android #ifdef's, and assuming the same GLES/GL settings were used).

Apitrace basically captures all the GL calls, so you can look at them, and the values that were passed to them, it also has some basic performance profiling tools, but it's mostly useful to be able to look at what GL calls are happening.

**Comment by fzurita** [comment]
Gotcha

**Comment by retrobenny** [comment]
What about with EGL via GLideN64,could that work without needing to use root to access functions?
If you meant the Apitrace thing then disregard this first question.

I also wish that normal Glide64 had an EGL variant if it would help the rendering at all,which it definitely should,for not having the missing polygon issues and other common bugs,then we'd finally have a well performing plugin with less glitches caused by the Android-specific GLES type limitations.

What is the normal Glide64 plugin on AE based on anyway? Is it older,or the Final 2012 version?

**Comment by fzurita** [comment]
No idea what it's based on. Maybe gonetz would know since he wrote it a long time ago. We pull directly from this branch:

https://github.com/mupen64plus/mupen64plus-video-glide64mk2

**Comment by gonetz** [comment]
As I can see, glide64mk2 branched from Final 2012 version, but I have no relation to it.

**Comment by loganmc10** [comment]
I wonder if this is somehow related to https://github.com/gonetz/GLideN64/issues/470

I've seen a few issues where people stated that for some reason GLideN64 didn't trigger "performance mode" on their Nvidia cards and they had to disable power management. When I tested this on my Adreno device I noticed that the GPU clock speed wasn't at it max, maybe it's a similar issue and there is some way to get the Adreno devices to throttle up the GPU clock speed?

**Comment by fzurita** [comment]
You can if you are rooted.

**Comment by loganmc10** [comment]
Ya unfortunately I don't have that Adreno phone anymore, I returned it and got a Mali device when I ran into this issue. I would be really interested if someone with a rooted Adreno device could force their GPU to whatever it's max clockspeed is and see if there is a difference.

If that is the issue there may be some way to "trick it" into going into performance mode or something.

**Comment by fzurita** [comment]
I do have a rooted Adreno device. I'll give myself a note to try it later.

**Comment by loganmc10** [comment]
By the way @fzurita it might also be worth looking at:

https://www.khronos.org/registry/gles/extensions/QCOM/QCOM_binning_control.txt

Adreno is supposed to have a technology called "FlexRender" that magically picks the best way to render the scene, but that extension is supposed to allow you to pass some values to glHint() and force it to a certain rendering mode, maybe it is getting it wrong using its magic method?

**Comment by fzurita** [comment]
Hmm, interesting. I wasn't aware of that extension. I'll give that a shot, maybe it will be a magic bullet.

**Comment by fzurita** [comment]
I looked up the extension and it seems that it's very unlikely that we will get any measurable performance improvement according to qualcomm themselves:

https://developer.qualcomm.com/forum/qdn-forums/maximize-hardware/mobile-gaming-graphics-adreno/28454

**Comment by fzurita** [comment]
That's a pain, I need a custom kernel to change the GPU clock speed, not worth it. I don't think there would be a way to force a higher GPU clock speed from within an app any ways.

**Comment by fzurita** [comment]
By the way, the qualcomm snapdragon 820 with the Adreno 530 seems to have no performance issues at all with GLideN64. It seems to run everything lightning fast. At least in my ZTE Axon 7.

**Comment by retrobenny** [comment]
Well qualcomm usually clocks really high,so it will run very well if no throttling occurs,if their Vulkan drivers are good enough it would prove itself in performance from using less power and lower overhead.

I am curious how well your high-end qualcomm will perform with this monstrous test...
As Shield TV slows to a pathetic crawl in this scenario,please fzurita,try the ultimate test of Banjo-Tooie in CountPerOp=1 and one of the 60fps code combos on the infamous HailFire Peaks (Icy Side) oil rig ledge:
80014F53 0004
8003F4F2 000D
D207913F 0000
8007913F 0001
The extra lines create a perfectly smooth and lagless 60fps via emulators but still has the same issues.
Alternate code:
80014F53 0004
800154E7 0003
8003F4F2 000D
Also,my funpleted save via direct link of 2shared for immediate access to that level.
http://dc208.2shared.com/download/XlbVB6lM/BANJO_TOOIE.eep?tsid=20161013-175916-6790a1d3

My (our) problem is Shield TV's p*** poor clock rate settings with Energy Star compliance,what's the point of all that RAW power if I can only use a weary fraction of it?
Mupen64Plus AE/FZ and the GLideN64 part really needs the custom profile added to Shield TV like Dolphin has for higher clock rates in their next OTA upgrade,please get their attention upon doing so,mentioning that Shield TV's hardware shouldn't be weaker and a bit slower than your high-end qualcomm device is when compared to Shield TV's processor specs.

**Comment by fzurita** [comment]
Yeah, sure, I'll try it. What settings do you use for those tests?

**Comment by retrobenny** [comment]
Good thing this part is not as lethal as zooming in on the fire really closely,or it could literally fry your device as that really tears into the hardware with slowdown and even laggy UI response times.

For you,I would say use the standard settings of ES 3.1 at 1080P "stretch" (if possible on it) but with shader storage and texure caching disabled,Noise and HW Lighting enabled,4x Native Scale Factor for better performance,no sampling enhancements or bloom of any kind,no depth buffering or fragment depth,and without the (slow) texrect fix.
(If a 3.2 variant gets made with optimizations,you can test it again to see if performance skyrockets in comparison.)

Just get at the ledge and force the camera view at the most intensive distance/angle for the heaviest performance impact,I would also go down there to split up and ledge again with Kazooie while Banjo stays down there so performance hits harder,then try a Clockwork egg for even more impact.
Google Drive link coming soon above.

**Comment by retrobenny** [comment]
Hey,didja get me dose' pitcha's of Bear-bird man!?

I am REALLY curious how the results will be.

**Comment by fzurita** [comment]
I haven't tried it yet. I suspect it won't be as good as the shield TV since the shield TV still has a more powerful GPU.

**Comment by retrobenny** [comment]
Don't be so sure,the Shield TV GPU is usually underclocked to hell,hence why performance is so poor at times with GLideN64's performance intensive features.
If only they built it even better for keeping it cool and not being an energy-starved weakling,then things would run better in all scenarios.

Joke: Energy Star=Energy Starved - "ved"

**Comment by fzurita** [comment]
I just tried it actually. And, just as I suspected, with everything turned up, I'm getting like 30fps in that area.

The Adreno 530 is only as powerful as the Shield Tablet K1 chip.

**Comment by fzurita** [comment]
I think it has more to do with the NVidia drivers being more optimized. There isn't really much going on in these games.

**Comment by retrobenny** [comment]
Probably the emulator itself has reached its limit because on all other plugins,I could never get it to sustain 60fps on Shield TV in that area.

**Comment by loganmc10** [comment]
I'm going to close this, not much that can be done. Some devices are going to be slow
