### ISSUE TITLE
Android: DK64 transparency function broken/inconsistent on legacy blending.

### ISSUE THREAD

**Issue by retrobenny** [gonetz/GLideN64#1070]
Trees,enemies and objects appear with pop-in instead of fading in/out properly.
In "Rare" occasions,it worked correctly once after fiddling with settings and quickly stopped again.
Pictures are taken at the same spot via savestate loading for the most precise result even though that can lead to different responses than normal from the plugins,I made sure to load when already near the spot where I made the save for less risks.

Glide64:
![donkey_kong_64-000](https://cloud.githubusercontent.com/assets/16418716/17080578/c8e51b44-50fa-11e6-9245-4182d58332d4.png)
GLideN64 Full GL:
![donkey_kong_64-001](https://cloud.githubusercontent.com/assets/16418716/17080591/f2122296-50fa-11e6-82ef-28db0bc7581b.png)

I tried all sorts of changed settings and couldn't get it to work correctly on any variant,I didn't try the 2.0 variant though,hmm.
Could it be another thing to put on the Glide64 roadmap?

Edit: Noise,LOD,Async Color to rdram,HW Depth,Depth Compare and still not working,but is Compare acting up?
If anything,Depth stuff and Color to rdram both have nothing to do with it as Glide64 works correctly without those on in Android,what could be breaking it though?

**Comment by retrobenny** [comment]
Darn,legacy blending is the problem,disabling it makes it fade properly.

**Comment by gonetz** [comment]
Legacy blending is for speed on old devices. It is supposed to be less accurate than the main method.
