### ISSUE TITLE
ES 2.0 DK64 Zipper transition doubled with incorrect colors.

### ISSUE THREAD

**Issue by retrobenny** [gonetz/GLideN64#1071]
Another strange issue of many that the 2.0 variant has been known for.

Selecting file:
![donkey_kong_64-002](https://cloud.githubusercontent.com/assets/16418716/17081930/89010b74-5130-11e6-99a7-5ddafe4a069c.png)

Starting gameplay:
![donkey_kong_64-003](https://cloud.githubusercontent.com/assets/16418716/17081935/ac5261b8-5130-11e6-9bf9-acfe89b66193.png)

Not really anything else to say here other than I used the default profile.

**Comment by gonetz** [comment]
Do you have similar issues with other games? For example, Perfect Dark blurred pause screen?

**Comment by retrobenny** [comment]
Can't find any because it seems to have disappeared since an update,likely due to "fixed profile" being part of one of the updates.
Just tried minutes before typing this,and ES 2.0 looks correct now.

**Comment by gonetz** [comment]
Please close then.

**Comment by retrobenny** [comment]
Sorry,okay then.
