### ISSUE TITLE
CBFD more incorrect lighting

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1073]
I'm not sure if this broke recently. I have tried this in several devices with NEON and VEC4 optimizations enabled/disabled and it makes no difference.

I have also tried new/legacy blending.

In CBFD lighting is incorrect in some instances, it's hard to capture in a screenshot, but if you play the intro cut scene where Conker is on the throne, it will become very apparent.

Where the character is only supposed to be partially lit in a gradual fashion on and off due to some fire burning, the whole character is highlighted on and off.

This also happens in game but it's more noticeable in this intro cut scene.

**Comment by gonetz** [comment]
Bugs in lighting implementation for this game are very possible. The game uses custom and very tricky way for lighting. I made my best to decode it and I can't do it better.

**Comment by fzurita** [comment]
OK. LLE mode world OK,

**Comment by fzurita** [comment]
I think I see what the problem is. When the character is supposed to be not lit at all, it's instead being fully lit. I'll mess around with the gSP CBFD functions to try to find the problem. It sounds like a wrapparound issue though.

**Comment by gonetz** [comment]
It is possible. Currently color value clamped, not wrapped.

**Comment by fzurita** [comment]
Ok, I started digging a little bit. In the ```gSPPointLightVertex4_CBFD``` function, ```light.x``` is coming up as  zero for the 2nd light sometimes. This is causing intensity to turn to NaN which is causing the final RGB output to be NaNs.

I added a check for NaN, and skipping applying the light for that iteration. The lighting looks much better now, but still not correct. I'm going to look at the output of a real N64 (youtube) to determine what it's supposed to look like. Whatever I came up will be just an approximation though.

**Comment by fzurita** [comment]
So if I take out gSPPointLightVertex4_CBFD, gSPLightVertex4_CBFD, gSPLightCBFD,  gSPCBFDVertex by commenting out their contents. Part of conker's model is still being lit. It's this section that is still being lit that has the incorrect lighting. What function is setting the color of the remaining vertexes???
