### ISSUE TITLE
Widescreen hack broken with frame buffer emulation enabled

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1078]
The widescreen hack is broken with frame buffer emulation enabled. See this screenshot:
![super_mario_64-000](https://cloud.githubusercontent.com/assets/11581687/17272643/c32d7588-5669-11e6-8a4f-08aaf9f5b2b3.png)

This used to work fine before.

**Comment by fzurita** [comment]
It almost looks like some things are being drawn in their old places.

**Comment by gonetz** [comment]
Desktop version works correct. I think, it can be result of Neon optimizations.

**Comment by gonetz** [comment]
Yes, it is VEC4_OPT

**Comment by fzurita** [comment]
Oh, interesting. I'll have to see which optimization is broken. It should be easy to do by just replacing each one individually.

**Comment by gonetz** [comment]
I'll fix it

**Comment by fzurita** [comment]
Is it just VEC4 and not VEC4 neon? If it's in one of the neon functions it will be hard to fix. That code is hard to read for me.

**Comment by gonetz** [comment]
I've fixed gSPProcessVertex4: c7c90cb7eb141
If it has Neon counterpart, it should be fixed the same way.

**Comment by fzurita** [comment]
Ok, I'll see if I can do it. That Neon code is hard to understand.

**Comment by gonetz** [comment]
I don't see Neon version of gSPProcessVertex4

**Comment by fzurita** [comment]
Ok, good news then!

**Comment by fzurita** [comment]
Fixed!
