### ISSUE TITLE
Per pixel lighting broken with shader cache with Adreno and Android

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1080]
When shader cache that has per pixel lighting enabled is loaded, we get an incorrect result:

![super_mario_64-000](https://cloud.githubusercontent.com/assets/11581687/17392797/d3bfecd2-59ed-11e6-8744-fb86a736d30a.png)

This is the case with at least Android and Adreno.

**Comment by fzurita** [comment]
It almost looks like the per pixel lighting computation is not happening at all in the shader.

**Comment by gonetz** [comment]
I can't reproduce it. You probably loaded obsolete shader. I not always bump shader storage version, so it can happen. Please clear 'shaders' folder and test again.

**Comment by fzurita** [comment]
Already tried that. It's not helping. Probably an Adreno only issue.

**Comment by fzurita** [comment]
This may be related to not being able to generate binaries for all shaders issue that I put a workaround for.

**Comment by fzurita** [comment]
On an unrelated note, I put a beta version of mupen64plus for Android on the playstore; https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

That means your plugin is in the playstore now.

**Comment by gonetz** [comment]
> That means your plugin is in the playstore now.

Cool! How often you are planning to update it?

**Comment by fzurita** [comment]
I'm updating whenever I think something significant enough has been fixed or changed.

Right now this is quite often since a lot of issues are being reported. So I'm fixing things and updating as I go along.

**Comment by fzurita** [comment]
Problem is on my end.

**Comment by fzurita** [comment]
Ok, the problem is in the code. In the tcUniformSet bindWithShaderCombiner we have this check:

```
GBI.isHWLSupported()
```

This check is being performed before any microcodes have been loaded. This is because the shader cache is loaded before the game starts running.

**Comment by fzurita** [comment]
Ok, I came up with a better fix. I added the HW Lighting enabled state of the shader to the m_inputs of the shader. So along these lines:

```
	const bool bUseHWLight = config.generalEmulation.enableHWLighting != 0 && GBI.isHWLSupported() && usesShadeColor();

	if( bUseHWLight )
	    m_nInputs |= 1 << HW_LIGHT;
```

This seems to work ok.

**Comment by fzurita** [comment]
See my last 6 commits here:

https://github.com/mupen64plus-ae/mupen64plus-ae/commits/GLideN64_GL_Errors

I fixed all the GL Errors I have observed. I'm not getting any more of them with OpenGL ES 3.0.

I also fixed the HW Lighting with shader storage in that branch.

I'm going to clean this up and create a pull request.

**Comment by gonetz** [comment]
Can it be closed now?

**Comment by fzurita** [comment]
Yep

**Comment by fzurita** [comment]
Good news. After these set of commits, my old Adreno device no longer crashes with 3 point texture filtering.
