### ISSUE TITLE
Buffer Swapping on Adreno Devices

### ISSUE THREAD

**Issue by min050820** [gonetz/GLideN64#1089]
On my G Pro (Adreno 320), sometimes black or partically black frame is shown. And it also looks like it sometimes does not swap buffer at all, causing laggy animations.

It might be related to #1074

**Comment by fzurita** [comment]
Which version of Mupen64Plus are you running it on?

**Comment by min050820** [comment]
Playstore FZ edition. Package manager reports its version is "3.0.6 (beta)"

**Comment by fzurita** [comment]
Which game?

**Comment by min050820** [comment]
Ocarina of Time. I confirmed setting 'Swap Frame Buffer' to 'on VI update call' reduces flicker. Probably because it renders same frame multiple times.

**Comment by fzurita** [comment]
Interesting, I don't have this issue.  It must be another driver version specific issue.

**Comment by fzurita** [comment]
Does the problem go away if you disable frame buffer emulation?

**Comment by min050820** [comment]
Yes! But it seems it breaks Widescreen Hack. (is it normal?)

**Comment by min050820** [comment]
P.S. I'm in school so I wouldn't be able to reply soon. School ends about 6 hours later.

**Comment by fzurita** [comment]
Weird, that is not normal.

**Comment by min050820** [comment]
>Weird, that is not normal.
Did you mean the Widescreen hack? I just confirmed that widescreen hack does break when frame buffer emulation is disabled.

**Comment by fzurita** [comment]
Yeah, I just checked it. It seems broken without frame buffer emulation.

**Comment by gonetz** [comment]
Widescreen hack probably never worked without frame buffer emulation. I fixed it: ba434bab0409

**Comment by min050820** [comment]
Maybe before it gets fixed, I'm gonna disable Frame Buffer emulation. ....Only if I could build it. (Eclipse hates my pc)

**Comment by fzurita** [comment]
@min050820 is there any way you can take a video of what it looks like?

**Comment by min050820** [comment]
@fzurita Uhh... I'll try to capture it tomorrow using a video capture app on Playstore. (If you wonder why not right now, It's 1:00AM here)

**Comment by fzurita** [comment]
You must be in the opposite side of the world, it's 12pm here. Whenever you have a chance is fine. Thanks.

**Comment by min050820** [comment]
After the update to '3.0.6 (beta)' on Playstore version, this bug was fixed. Yay...? Anyway, I'm gonna close it since it's fixed now.

**Comment by min050820** [comment]
Wait! The latest revision probably did not fix it, but make it happen much less frequently. I'm gonna test it with other plugins (a.k.a. Glide64) and record it. I'll reopen this when I confirm it.

**Comment by fzurita** [comment]
Interesting... I don't believe I did anything to fix it.

**Comment by min050820** [comment]
@fzurita o.O really? Man, this must be really complicated. It seems like it's affected by Hires texture pack. Whenever I turn on hi res texture pack (with one installed, of course), I can reproduce this issue.

It seems like frame lagging/hicupping is gone. And like what I said, this is somewhat rare now.

And if I recall correctly, the old revision had errors regardless of hires texture pack, and it was very very often to the point of unplayable. (If you give me old revision, I'll try that too)

And I tried to record it but this issue hates me. This issue doesn't show itself when I turn on recoder! And it shows when I turn off recoder. (maybe it's related to gpu driver)

P.S. I'm using Android native screen recording API.
P.P.S. Can you give me previous version apk? Maybe I'll be able to record on previous version.

**Comment by fzurita** [comment]
Layer today, I'll give you a build that took out s hack I did for PowerVR devices. I want to make sure that's not breaking your device.

**Comment by fzurita** [comment]
Ok, I'm getting reports in the playstore about the game issue I think. An issue that only happens with high resolution texture packs enabled.

**Comment by fzurita** [comment]
@min050820 can you try this build?

https://drive.google.com/file/d/0B57Ioy26LWegUmhNUWk5MVl1WFU/view?usp=sharing

Does it make a difference?

**Comment by min050820** [comment]
That didn't make any improvement to it. I will try to record it again, but no guarentee though.

(Since it's confirmed, I'm reopening it. Is that okay with you?)

**Comment by fzurita** [comment]
Ok, so it's not the hack that was causing the problem. It must be a completely different problem then.

**Comment by min050820** [comment]
What texture pack? o.O I haven't thought about it.

After trying other ones: Texture pack itself doesn't seem to matter, but idk.

But like I mentioned earlier, the old version was toally unplayable and playstore version update fixed it a lot (but it's still remaining), so compairing that commit might help to figure it out.

**Comment by fzurita** [comment]
So the last playstore update with GLideN64 fixes addressed most of it? I did fix a bunch of GL Errors I was getting in my Adreno device. That probably helped at least a little.

**Comment by min050820** [comment]
No, not this update. I was talking about old post.
>After the update to '3.0.6 (beta)' on Playstore version, this bug was fixed. Yay...? Anyway, I'm gonna close it since it's fixed now.

It's two days ago and you replied:
>Interesting... I don't believe I did anything to fix it.

**Comment by fzurita** [comment]
Yep, I knew that's what you meant. v3.06 fixed a bunch of GL errors. I was not trying to address the issues you were seeing, but I'm thinking that it may have contributed.

**Comment by min050820** [comment]
Then this issue might be causes by one or more of these possibilities:
1. There is more GL errors caused by bad driver
2. There are actually seperated issues, one caused by gl errors, and other one caused by unknown reason (for now), and they make similiar look.

In case of case 1, is there any way to track gl errors? Perheps using terminal emulator or adb?

**Comment by fzurita** [comment]
Here is what Gonetz told me a few weeks ago. This way seemed to work OK for me.

> I usually put if (isGLError) to RSP_ProcessDList() after
GBI.cmd[RSP.cmd](RSP.w0, RSP.w1); 
that way you may see which command produced the error and put isGLError inside that command.

**Comment by min050820** [comment]
Welp, like I told you on issue #1000, eclipse hates my PC. But since I managed to build a simple android application, I'm gonna try to build this project once again.

(P.S. I won't blame you for not remembering me! There's really a lot of people here and you can't remember every single of them!)

**Comment by fzurita** [comment]
I do remember the conversation. I recommend using Android studio, I think it's actually easier to setup. The Gradle files for it are also already included in the tools directory of the project.

**Comment by min050820** [comment]
Really?! Thanks for remembering me! \*jumps around the room\*

Anyway, I'm installing SDK right now. I'll edit ASAP when it's downloaded.

**Comment by fzurita** [comment]
@min050820 is this still an issue?

**Comment by min050820** [comment]
No, I think it's fixed.
