### ISSUE TITLE
GUI proofreads and translations

### ISSUE THREAD

**Issue by gonetz** [gonetz/GLideN64#1090]
I've finished with GUI modifications. No changes planned until new Public Release. Thus, it is good time to update translations. I updated all translations files with new English text, which need to be translated: 21f46db869.

Also, it will be very nice if somebody with good skills in English grammar will proofread my English texts in UI forms and tooltips. To do that, load src\GLideNUI\GLideNUI.pro project file to QTCreator, open configDialog.ui form and edit it. Alternatively, you may just give me corrections in comments to this issue.

**Comment by Frank-74** [comment]
First speed read, but what is "Deposterize textures"?

What do you mean by deposterize?

**Comment by oddMLan** [comment]
https://github.com/gonetz/GLideN64/issues/826

**Comment by gonetz** [comment]
Yes, it is not my term.  May be de-posterize is more correct. Can you suggest better word for this technique?

**Comment by Frank-74** [comment]
Posterize has a description in the dictionary, but deposterize doesn't.  Another term for posterize is "colour banding".  But what is the opposite of colour banding?  "Increase colour resolution"?

**Comment by gonetz** [comment]
'Decrease color banding' then, because it is what that technique does.

**Comment by Frank-74** [comment]
'Decrease color banding' makes more sense to anyone, without needing to look up in the dictionary what it means.

**Comment by standard-two-simplex** [comment]
When I compile GLideNUI with QTCreator I get this output files.
![sin titulo](https://cloud.githubusercontent.com/assets/12202580/17818327/68517062-6643-11e6-93af-3b21c3c0a844.png)
Shouldn't there be a GLideNUI.lib file, to link towards the main project?

Also, OS_WINDOWS is not defined for some reason even though I am in windows. I needed to replace the ifdef OS_WINDOWS parts with just the windows includes in order to compile. Any idea why?

**Comment by gonetz** [comment]
I use MSVS project files for Windows builds. Windows - related parts of cmake project file need corrections.

**Comment by gonetz** [comment]
I've corrected options and tool-tips in GUI. Proofread is really needed.

**Comment by standard-two-simplex** [comment]
If no one has offered for the task so far, I will gladly take it. What has to be done exactly? Correct existing tooltips and write missing ones?

**Comment by Frank-74** [comment]
All English language is good.  It's translation of new English text to other languages that I think need doing.

**Comment by gonetz** [comment]
> If no one has offered for the task so far, I will gladly take it. What has to be done exactly? Correct existing tooltips and write missing ones?

Yes. Not only tooltips, but controls labels too, if necessary.

> All English language is good. Gonetz, your English is better than most English, who were born in England, under the age of 25.

I still make lots of grammatical errors in my texts. The GUI was already proofread once, before first public release, so it still looks so-so. I added many new controls, and their tooltips should be checked. I also updated tooltips for some older options, so it is better to check everything. After that translation files can be updated with new English text and translation process started.

**Comment by gonetz** [comment]
@standard-two-simplex 
> If no one has offered for the task so far, I will gladly take it. 

Have you taken it? Any progress?

**Comment by standard-two-simplex** [comment]
I haven't started. I have been quite busy this weeks. I'll PM you when I can.

**Comment by gonetz** [comment]
Ok.

**Comment by gonetz** [comment]
Not actual anymore because of
https://github.com/gonetz/GLideN64/issues/1213
