### ISSUE TITLE
Adreno: junk in borders with frame buffer emulation disabled

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1093]
Whenever frame buffer emulation is disabled, with at least Adreno GPUs, some games produce junk around the borders. Here is screenshots of that with super smash brothers:

![smash_brothers-000](https://cloud.githubusercontent.com/assets/11581687/17889472/5f788116-68fe-11e6-9146-2c647df97de5.png)

![smash_brothers-001](https://cloud.githubusercontent.com/assets/11581687/17889481/6a23ac76-68fe-11e6-80cb-adf648c86e46.png)

It works fine with frame buffer emulation enabled.

**Comment by Nes-player4Life** [comment]
Then leave it on. /solved.

**Comment by loganmc10** [comment]
I actually don't get this with GLupeN64 on Android, doesn't mupen64plus-ae do this for all the graphics plugins?

**Comment by fzurita** [comment]
Hmm, interesting. Let me check on that.

**Comment by fzurita** [comment]
Glide64 = no
glN64 = yes
Rice = yes
Angrylion = no

Not sure what to make of that.

**Comment by fzurita** [comment]
This seems to be fixed now.
