### ISSUE TITLE
Super smash brothers depth issues

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1097]
Here is output from Angrylion:
![smash_brothers-002](https://cloud.githubusercontent.com/assets/11581687/18024354/0d69148c-6bd6-11e6-96c8-d1c62fad4a62.png)

Here is GLideN64:
![smash_brothers-003](https://cloud.githubusercontent.com/assets/11581687/18024364/2ecb7dfe-6bd6-11e6-8bfd-b2aa5c3e065b.png)

I believe Angrylion is correct.

**Comment by gonetz** [comment]
Could you give me a savestate? I don't want to play to stage 6.

**Comment by fzurita** [comment]
Here you go:
[depth_issues.sav.zip](https://github.com/gonetz/GLideN64/files/459454/depth_issues.sav.zip)

It's for mupen64plus.

**Comment by gonetz** [comment]
Hmm, no problems on desktop:
![smash_brothers-000](https://cloud.githubusercontent.com/assets/8983092/18317107/3b6db336-7547-11e6-97eb-72fc740004df.png)

**Comment by fzurita** [comment]
Nice, another Adreno bug.

**Comment by fzurita** [comment]
Maybe we should start putting labels on all bugs specific to Adreno? That way it will be easier to find them all.

**Comment by gonetz** [comment]
Good idea

**Comment by fzurita** [comment]
I'm not sure what you did, but this is fixed in the latest build.

**Comment by gonetz** [comment]
It may return then. My recent changes cause regressions, fixes for these regressions break recent fixes. The code will be unstable for some time.

**Comment by fzurita** [comment]
I'll reopen it if I see that it comes back,
