### ISSUE TITLE
1080 Snowboarding - missing color overlays

### ISSUE THREAD

**Issue by ngs428** [gonetz/GLideN64#1099]
In race, the damage bar should be green with red showing where the damage is at.  Bar is grey only.  Track overlay in race in the bottom right is grey and should be green.
![wrong - in race track progress and damage](https://cloud.githubusercontent.com/assets/13911615/18031336/cb00de0a-6ca1-11e6-891c-8a7c66b6de7f.jpg)

Here is the correct screen from Wiki
![n64_1080](https://cloud.githubusercontent.com/assets/13911615/18031361/cd2b4fd4-6ca2-11e6-8dae-d9495f1cfa7e.jpg)

 
Rider and board attributes should show multi colored bars, all bars are purple. 
![wrong - board select screen](https://cloud.githubusercontent.com/assets/13911615/18031341/e74e0fe2-6ca1-11e6-9895-a6fffed2efa3.jpg)

Here is the correct screen colors for board select and similar for the rider select:
![nintendo64--1080 snowboarding_aug18 23_23_25](https://cloud.githubusercontent.com/assets/13911615/18031366/00e74378-6ca3-11e6-9c63-bd897a78de59.png)

The grey overlays didn't even show until I made some of the changes the MupenFZ developer recommended.  [https://www.reddit.com/r/EmulationOnAndroid/comments/4z26yw/1080_snowboarding_mupen_fz_edition/d6sqvh2](url)

I am using a Nvidia shield with Mupen64plus FZ.  Open GL.

**Comment by gonetz** [comment]
Probably it was a bad build of Mupen64plus FZ. Current gplay build runs 1080 properly on my shield with Full OpenGL profile.

**Comment by ngs428** [comment]
Are you using the default settings for the full OpenGL profile?

**Comment by ngs428** [comment]
Yes, I just tried the default settings for full OpenGL and it works just fine!  Nice!

**Comment by fzurita** [comment]
Hmm interesting, not sure how I ended with a bad build. Glad it's fixed now.
