### ISSUE TITLE
wrong noise usage

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#11]
premier manager 64: the balloon in menu displayed wrong noise
Pro Mahjong Kiwame 64: in menu
Ms. Pac-Man Maze Madness during intro
F1 Pole Position Menu
mario Golf in background during intro

**Comment by gonetz** [comment]
Please re-check on current version. For example, noise in KI is not wrong - software LLE plugin works the same.

**Comment by olivieryuyu** [comment]
tested on real N64, i cannot see noise in KI.

**Comment by gonetz** [comment]
>tested on real N64, i cannot see noise in KI.
Hmm, noise looks natural here - only area above the cloud is noised.
But you're right. Video from the real N64 shows that part of the logo above the cloud is not visible:
https://www.youtube.com/watch?v=mkfqh9CL32s
Logo works correct if noise emulation is disabled. I guess that noise dithering is really used here, but noised area has zero alpha. My noise implementation adds random alpha to that area and make it visible. LLE software works the same. Original hardware does not dither zero values. Need to prove it.

**Comment by gonetz** [comment]
Hopefully fixed. 
Need carefully testing for all noise based effects. It was hard to make them all working right.

**Comment by olivieryuyu** [comment]
tested with Pro Mahjong Kiwame 64 and even the wrong usage of noise in this game is gone.
KI fixed as well.

Great job :)

**Comment by olivieryuyu** [comment]
Angrylion explained me that the noise was normal here, he even did some tests for this.

Hence i guess there is something odd

**Comment by AmbientMalice** [comment]
There's also the fact enabling noise breaks Perfect Dark. https://github.com/gonetz/GLideN64/issues/518

**Comment by gonetz** [comment]
@AmbientMalice #518 is not related to this issue.

@olivieryuyu do you suggest to revert that fix? You know, that on real hardware the part of logo above the cloud is not visible. You may see it on LCD monitors or on videos recorded from video capture devices. Thus, it can't be explained by fading luminophor of CRT TV.

**Comment by olivieryuyu** [comment]
i will forward you the concerns of angrylion here by email. Not sure either what is correct here.
