### ISSUE TITLE
Dr mario: wrong background in game & missing falling capsules

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#110]
![fffffffffffffff](https://cloud.githubusercontent.com/assets/8987490/4963199/2c440610-66ff-11e4-95b7-b475c5450ec3.jpg)

**Comment by theboy181** [comment]
![capture](https://cloud.githubusercontent.com/assets/9299743/6282968/2f6a5634-b892-11e4-924d-f530b2f8fc7d.PNG)
Working with Copy FB to RDRAM, and RENDER FB as texture. 

Garbage at the bottom of the screen.

**Comment by gonetz** [comment]
RENDER FB as texture is must for this game because pills are rendered by CPU directly to frame buffer.

Fixed many issues with frame buffer emulation and Render FB as texture in particular. Everything works fine, Copy FB to RDRAM is not needed.

**Comment by theboy181** [comment]
Copy FB to RDRAM IS needed needed. If I don't select these two I get the pills but a white background.

**Comment by gonetz** [comment]
It is fixed in my code. The build is not uploaded yet.
