### ISSUE TITLE
Android: Changes likely related to blending broke a lot of stuff.

### ISSUE THREAD

**Issue by retrobenny** [gonetz/GLideN64#1101]
Some games started looking different,my recent Smash Bros. issue/regression post relates to this.
I can't get the trees in DK64 to fade into view on non-legacy,not even LLE mode works correctly! 😧 
Something must be really badly broken to cause rendering to be incorrect on LLE.
I guess I was right about the oddly fast performance unfortunately.

I hope you can find the causes of these issues.

**Comment by gizmo98** [comment]
I can't seem to get LLE running on a rpi as well. It was working more orless some weeks earlier. It works on a PC, so it could be a GLES problem.

**Comment by gonetz** [comment]
@gizmo98 please try to find the commit, which breaks LLE on rpi. It should be easy if it worked until recently. I can't help you there. 

Android issues are harder to trace. mupen64plue-ae repository contains lots of commits not related to GLideN64, thus bisection is not very efficient.

**Comment by retrobenny** [comment]
One way for android would be to go back to the older GLideN64 while keeping all of the other emu changes to test for differences.

**Comment by fzurita** [comment]
Last I checked LLE mode works correct in my device. You just have to remember to switch the RSP to CXD4-LLE video

**Comment by fzurita** [comment]
@retrobenny I think there is something broken on the front end (Mupen64Plus-ae). The casing in the EnableLegacyBlending setting changed from **e**nableLegacyBlending to **E**nableLegacyBlending.

I just found a bug in our config file parser that doesn't update the setting if the config setting case changed because it's doing a case insensitive search when when search for the value to write, but it's case sensitive when writing it.....

**Comment by gizmo98** [comment]
I just retested with a rpi. LLE mode works if i use rsp-z64.

**Comment by fzurita** [comment]
The arm CXD4 RSP was a little broken before. If you pull the latest CXD4 from https://github.com/mupen64plus/mupen64plus-rsp-cxd4 that one seems to work ok.

**Comment by retrobenny** [comment]
Good to know what caused it as a simple fix,so not entirely an issue on the plugin's part in that case.

**Comment by retrobenny** [comment]
Closing the issue,but @gizmo98 should open a new issue for the LLE on rpi so it can be discussed directly.
