### ISSUE TITLE
Everything looks yellow with Native Res Texrects

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1102]
When I enabled generalEmulation.enableNativeResTexrects, things look all yellow, not every shot, but many elements are yellow. I experience this with GLupeN64 and mupen64plus-ae (it happens on the Raspberry Pi, Desktop, and Android).

I've attached a screenshot from mupen64plus-ae

![screenshot_20160829-123641](https://cloud.githubusercontent.com/assets/848146/18062750/665cb09c-6de5-11e6-98b9-e6d26f6c6800.png)

**Comment by fzurita** [comment]
If you open up the sidebar while in-game, there is a built in screenshot functionality that will get a screenshot without the controller overlay.

**Comment by loganmc10** [comment]
OK thanks, do you experience any weird color issues like that when you enable Native Res Texrects on Android?

**Comment by loganmc10** [comment]
Another one, the opening logo to Majoras Mask should look like this:
![687474703a2f2f6b733339323435372e6b696d737566692e636f6d2f6f726265612f73747566662f706963732f7363726f74732f6c6962726574726f2f676c7570656e36342f4c6567656e642532306f662532305a656c64612c2532305468652532302d2532304d616a6f726127](https://cloud.githubusercontent.com/assets/848146/18064470/db67ad4a-6dec-11e6-87bd-28a5939a9258.png)

But with enableNativeResTexrects enabled it looks like this:
![zelda_majora s_mask-000](https://cloud.githubusercontent.com/assets/848146/18064488/e6af1e86-6dec-11e6-8d38-956bb9fe7fe6.png)

Taken on mupen64plus-ae (FZ edition)

**Comment by fzurita** [comment]
Yep, I'm seeing graphical issues with it enabled.

**Comment by gonetz** [comment]
Hmm, I see that problem with Zelda MM on Linux. Windows build for mupen64plus works ok.

**Comment by fzurita** [comment]
I'm not sure what before this. It was working ok before quite recently. I guess I could try to dissect to which commit broke it.

**Comment by matthewharvey** [comment]
I can reproduce on Debian using pretty close to the latest Mesa.
I tried to bisect back, but it has been with us for almost as long as the texrects option. Also, it looks like every time I recompile my texrect option gets set back to false on the first run, which made bisecting difficult.

**Comment by gonetz** [comment]
Yes, config version changed several times after that option was introduced.  If config version differs from the current one, plugin resets all options to defaults. That option is off by default.

**Comment by Jj0YzL5nvJ** [comment]
Bisected to 0aaadb1507ac8c81596c274707f10d4bb27f4bf5
99af3839e3289da5d1c429d9f54ba47cbdc898f6 was the last time that NativeResTexrects worked... "properly"

**Comment by gonetz** [comment]
Thanks! Yes, the feature does not work with uniforms set enabled.

**Comment by gonetz** [comment]
Hopefully fixed.

**Comment by loganmc10** [comment]
The yellow-ness is fixed. But now I get a black screen during the Super Smash Bros intro in GLES2 mode, but not full OpenGL. Also, the characters are "invisible" in GLES2 mode now.

Also, on Fedora in GLES2 mode, it segfaults with this message
```
0x00007fffefbc121b in ColorBufferToRDRAM::_copy(unsigned int, unsigned int, bool) () from /usr/local/lib/mupen64plus/mupen64plus-video-GLideN64.so
```

if EnableCopyColorToRDRAM is enabled (I'm not sure if this is new or has been around for a while).

**Comment by loganmc10** [comment]
I'll fill separate issues for those things
