### ISSUE TITLE
Pokemon Stadium missing some menu items

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1104]
When I open the game, the menu looks like this:
![1](https://cloud.githubusercontent.com/assets/848146/18146548/9486ed76-6f8d-11e6-9cdb-a381f449a00f.png)

![2](https://cloud.githubusercontent.com/assets/848146/18146550/97369508-6f8d-11e6-9fcb-c33107ba2a67.png)

If I exit (Press B to go back to the start screen), and then go back in, all the icons are there. This was tested with mupen64plus on Ubuntu 16.04.1

**Comment by gonetz** [comment]
I can't reproduce it, all icons are in place from the start. Tested both U and E versions.
The same GLideN64 revision with default settings, Ubuntu 14.04

**Comment by fzurita** [comment]
This sounds like that transient issue that happens every once in a while starting up. It's like alpha for textures didn't work correctly.

**Comment by loganmc10** [comment]
It does seem to be some kind of a driver specific thing? Those screenshots were taken inside VMware Player (I do some testing like that because of the computer I'm using), it is reproducible 100% of the time inside VMware. I still need to test it on my regular laptop and the Raspberry Pi.

**Comment by gonetz** [comment]
I tested on real Linux workstation with NVidia card, not on virtual machine.

**Comment by Yui12** [comment]
I wonder if it is connected to this issue since it randomly happens. It's not easy to reproduce as well. #1062

**Comment by loganmc10** [comment]
I just tested on my regular Linux laptop and the Raspberry Pi and I can't reproduce this issue. The only time I can reproduce it is inside VMware, and with GLupeN64 on Android (but not mupen64plus-ae). GLupeN64 is a RetroArch port of mupen64plus+GLideN64. It's a little strange.

I'm okay to close this since I am testing admittedly strange use cases, although it does seem this is possible out there in "crappy driver" land.

**Comment by gonetz** [comment]
Sounds like it should be closed then

**Comment by loganmc10** [comment]
I figured this out, I thought I would post this here just for the curious.

GLupeN64 was keeping track of the glBindTexture state. So if you bound texture "50" and then tried to bind it again later, that call would just get skipped over.

However, sometimes glDeleteTextures is called, which on **some** drivers will set the bound texture to 0. So if you later on try to bind texture "50", it will think "50" is already bound, but it was actually deleted and recreated, and the current bound texture is 0.

So I just had it stop keeping track of the glBindTexure calls and do it every time. For some reason the VMware driver doesn't handle this situation very well with regular mupen64plus+GLideN64 either
