### ISSUE TITLE
Body Harvest graphics missing (Regression)

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#1107]
I haven't tested thoroughly, but I think it is related to https://github.com/gonetz/GLideN64/commit/669337f5ab88d1d35d0c44d557a1c54218cdd904 Could be wrong, though.

![gliden64_body_harvest_000](https://cloud.githubusercontent.com/assets/10704701/18231503/9fb4e490-72fe-11e6-9b76-f6201beceecc.jpg)

**Comment by gonetz** [comment]
Fixed
