### ISSUE TITLE
Super Smash Bros all black using GLES2 or Framebuffer Emulation disabled

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1108]
This commit:

669337f5ab88d1d35d0c44d557a1c54218cdd904

Breaks the Super Smash Bros intro (it's all black now), when in GLES2 mode

**Comment by loganmc10** [comment]
@fzurita just a heads up that if you update GLideN64 for mupen64plus-ae you might run into some serious glitches for GLES2 like this.

**Comment by fzurita** [comment]
Ok, thanks.

**Comment by loganmc10** [comment]
Specifically this if statement breaks it:
https://github.com/gonetz/GLideN64/blob/7dca7f8f4d9ea8727b539b58962e910d5808422f/src/gDP.cpp#L773

If I comment out that if statement it works properly again.

**Comment by loganmc10** [comment]
This is also broken on the desktop if Framebuffer Emulation is disabled.

**Comment by loganmc10** [comment]
Another easy way to reproduce this: Open up Super Mario 64 with Framebuffer Emulation disabled.

**Comment by gonetz** [comment]
Ok, thanks!

**Comment by gonetz** [comment]
Should be fixed now. At least it works on desktop without fb emulation and with shader depth write  disabled.

**Comment by loganmc10** [comment]
Thanks, the only time it happens now is with GLES2 mode and generalEmulation.enableFragmentDepthWrite=1, so is that basically an unsupported configuration now (if so it might be a good idea to force it to be disabled, instead of just making it the default)?
