### ISSUE TITLE
Mario Tennis pause menu causes Adreno devices to crash

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1110]
The device driver seems to be crashing when bringing up the Mario Tennis in-game pause menu. I have yet to track down which call is causing the crash to happen since I can't seem to get a back trace.

**Comment by fzurita** [comment]
Ok, I started trying to figure this one out. The one thing I notice when trying to check for GL errors in this game is that whenever we call ```glDrawArrays``` in OpenGL.cpp line 1931, I'm getting a GL error with status 0x506, meaning that the frame buffer is incomplete

When calling ```glCheckFramebufferStatus``` on ```GL_DRAW_FRAMEBUFFER```, I'm getting a status of ```GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_EXT```. I looked up this error code online, and here is what it means:

GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS
Not all attached images have the same width and height.

**Comment by fzurita** [comment]
Another GL error I'm seeing, glTexImage2D, for GLES 3.0/3.1 should use GL_R8 for the internal format.

**Comment by gonetz** [comment]
AFAIR, only GLES2 has limitation that all attached images must have the same width and height.
N64 games often use small aux color buffers with the same full size depth buffer. Mario Tennis is among these games. I put special code to avoid GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS with GLES2. In FrameBufferList::attachDepthBuffer() :

```
#ifdef GLES2
	if (pDepthBuffer->m_pDepthBufferTexture->realWidth == m_pCurrent->m_pTexture->realWidth) {
#else
	if (pDepthBuffer->m_pDepthBufferTexture->realWidth >= m_pCurrent->m_pTexture->realWidth) {
#endif // GLES2

```

The depth buffer will not be attached to FBO if its width is not the same as width of color buffer texture in case of GLES2. Height should be tested too, but I decided that it is redundant.

**Comment by fzurita** [comment]
Ok, I think GLES 3 has the same limitation. I'll have to check GLES 3.1

**Comment by fzurita** [comment]
Ok, same problem in GLES 3.1. That means that I have to change the code to this
```
#ifdef GLESX
    if (pDepthBuffer->m_pDepthBufferTexture->realWidth == m_pCurrent->m_pTexture->realWidth) {
#else
    if (pDepthBuffer->m_pDepthBufferTexture->realWidth >= m_pCurrent->m_pTexture->realWidth) {
#endif // GLES2
```

What does the GLES version of the plugin lose by this?

**Comment by gonetz** [comment]
> Ok, same problem in GLES 3.1.

May be it is only on Adreno?

> What does the GLES version of the plugin lose by this?

New depth issues of course. Need to test, which games will be affected and how serious.

I think the problem can be avoided if DepthBuffer object will create new depth buffer texture with the same size as color buffer has.  From the other side, it **may** lead to other issues since previous data in depth buffer will be lost.

**Comment by fzurita** [comment]
I found this nifty feature in Android that allows you to get a backtrack every time a glError happens. There are certainly a lot of errors in GLES 3.1 version of the plugin. I'm trying to fix them all, I'll submit a pull request once I'm done.

**Comment by fzurita** [comment]
Ok, after fixing all the GL Errors in this game, the pause menu no longer crashes the device.

**Comment by fzurita** [comment]
This is fixed.

**Comment by Sarkie** [comment]
Just an FYI this was crashing on my Nvidia K1 Shield also.

**Comment by fzurita** [comment]
Is it still crashing?

**Comment by Sarkie** [comment]
@fzurita will test tonight, you updated the play store build with the fix I assume?

**Comment by fzurita** [comment]
Nothing had been updated in the play store build, I guess it was now of a rethorical question. I should re-open the issue. By the way, it will not crash if you restart the game and then load a save state.

**Comment by olivieryuyu** [comment]
can i be checked again? do you still have a crash?

**Comment by fzurita** [comment]
Sure, I will check it again.

**Comment by fzurita** [comment]
Yep, it's still crashing. But I blame bad Android drivers, so there is really no way to fix it. I'll go ahead and close it since the workaround is not worth it.
