### ISSUE TITLE
Static Code Analysis

### ISSUE THREAD

**Issue by Sarkie** [gonetz/GLideN64#1111]
Hi,

Do you guys run any static code analysis?

I ran cppcheck.sourceforge.net  and it come with quite a few interesting "issues" that might have been overlooked, out of bounds errors and portability errors.

![image](https://cloud.githubusercontent.com/assets/283203/18344012/92800ee2-75ad-11e6-80d2-2488fce23499.png)

I couldn't install it, but you could also run PVS Studio viva64.com against the code too as they produce good results also.

**Comment by mudlord** [comment]
PVS Studio needs a license key to be usable.

**Comment by Sarkie** [comment]
Ok but what about the CPPCheck errors noted above?

**Comment by olivieryuyu** [comment]
@gonetz 

I guess this one should be closed.

**Comment by gonetz** [comment]
Let it be active. May be someday I'll try that CPPCheck.

**Comment by Sarkie** [comment]
PVS also has an Open Source option for free if you had a message to the head of each file

**Comment by gonetz** [comment]
Code checked by PVS Studio. Closed.
