### ISSUE TITLE
Extreme G logo old bug

### ISSUE THREAD

**Issue by Tasosgemah** [gonetz/GLideN64#1112]
https://i.ytimg.com/vi/c-E4uofhLKw/maxresdefault.jpg

I get the old bug again (left picture) when using recent versions of the plugin. I remember this being fixed like a year ago but it's now back. Enabling depth compare fixes the effect but places the logo behind the backgrounds and there's also a weird wireframe on the graphics.

**Comment by gonetz** [comment]
I also had "logo behind the backgrounds" issue. I reset graphics settings to defaults, enable N64 depth compare and problem gone.

**Comment by Tasosgemah** [comment]
Ok, doing this fixed the issue. 

Antialiasing also caused the wireframe bug.

**Comment by gonetz** [comment]
> Ok, doing this fixed the issue.

Can it be closed then?

**Comment by Tasosgemah** [comment]
Yeah, i think it's stable now, meaning it doesn't randomly appear for me. Thanks.

Is there a list of games that need the Depth Compare option? Some games on the ini are mentioned but i have found more (water levels in Goemon's Adventure).

**Comment by gonetz** [comment]
> Yeah, i think it's stable now

Ok, closed.

> Is there a list of games that need the Depth Compare option?

Hardly. However, many such games mentioned in this bug tracker. You just need to search :)
