### ISSUE TITLE
Nushi Zuri 64: fb background doesn't work anymore

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1115]
![sans titre](https://cloud.githubusercontent.com/assets/8987490/18415863/71dbbb54-7801-11e6-9604-dd648d233f33.jpg)

**Comment by gonetz** [comment]
Yep, it is killed by recent modifications related to depth buffer emulation.

**Comment by olivieryuyu** [comment]
fixed

**Comment by olivieryuyu** [comment]
sorry but tested again

it works during intro

but just go out of the first house and press B

![nooo](https://cloud.githubusercontent.com/assets/8987490/18688618/7652c6ce-7f85-11e6-92f8-7e1b4d1179b2.jpg)

btw this game got another issue here  #977

**Comment by gonetz** [comment]
Depth buffer copy must be disabled, otherwise validity check wont work.

**Comment by olivieryuyu** [comment]
ok
