### ISSUE TITLE
Chou-Kuukan Night Pro Yakyuu King 2: black screen in menu (fb/VI issue)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1116]
start a new game (just press a all the time). At one point the game goes to a black screen.

without fb it appears correctly:

![sans titre](https://cloud.githubusercontent.com/assets/8987490/18415951/f606ce3e-7804-11e6-9c11-cb232ca89905.jpg)

**Comment by gonetz** [comment]
Regression?

**Comment by olivieryuyu** [comment]
yes it is a regression

**Comment by olivieryuyu** [comment]
fixed

**Comment by gonetz** [comment]
Good. I did nothing special to fix this game
