### ISSUE TITLE
Adreno noise emulation bugs

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1117]
It seems that some Adreno driver versions don't work correctly when noise emulation is happening. Here is a screenshot:

![screenshot_2016-08-23-00-01-51](https://cloud.githubusercontent.com/assets/11581687/18417061/02a509a0-77f4-11e6-8660-f8c656b5f013.png)

The bad thing about mobile devices is that you can't really update a driver unless you install a custom ROM.

**Comment by fzurita** [comment]
@gonetz while you are adding labels, you may want to add the Adreno label to #1093 and #1110

**Comment by gonetz** [comment]
done

**Comment by fzurita** [comment]
I don't think this is worth fixing.

**Comment by Jj0YzL5nvJ** [comment]
That looks similar to the noise issues on [SSSV](https://github.com/gonetz/GLideN64/issues/1764).
In SSSV case:

-  Noice not disappear even then noise emulation is disabled and you look the noice object from a long distance.
-  The noise emulation only works correctly with:  `EnableFragmentDepthWrite = False` and `EnableFBEmulation = False`. But looks corrupted from a long distance perspective.

**Comment by fzurita** [comment]
In this case it's purely due to buggy drivers.
