### ISSUE TITLE
Star Wars Episode One Racer Flicker and Black Screen with Frame Buffer Emulation

### ISSUE THREAD

**Issue by jaburgeson** [gonetz/GLideN64#1119]
Hi Everyone,

It appears in the latest builds, star wars episode one racer has developed a weird effect where the intro flickers and the game shows a black screen past the title screen.  You can hear audio, but sadly no picture.

This regression happen in the past month or so.

Disabling Framebuffer fixes the issue somewhat, but this used to not be required.

**Comment by gonetz** [comment]
Fixed
