### ISSUE TITLE
Feature Request: Option for faster 1080P method at the cost of visual clarity.

### ISSUE THREAD

**Issue by retrobenny** [gonetz/GLideN64#1120]
I know this sounds difficult and confusing,but particularly regarding blending performance and other things being upscaled to 1080P,there is a faster way of using higher resolution options in Mupen64Plus AE if all of the other rendering still uses the original resolution while the emulator setting does the upscale that it normally does with other plugins.
For example,the main difference is the usual less jagged lines on higher resolutions while the rest of the rendering is still the original size and has no extra performance impact,the Glide64 plugin is a good example of the much lower impact on performance for generally higher visual quality than being on 640x480 or 320x240 while some 3D depth (not the buffering kind) is missing due to how the screen is drawn.

In case of differences,maybe it only needs an option similar to whatever the other plugins do on higher resolutions to prevent the heavy performance impact.
My guess is that GLideN64 renders accordingly to the resolution setting of Mupen64Plus AE with increased clarity on 1080P at the cost of a chunk of performance due to its scaling method and extra buffering while other plugins use a shortcut method that has less clarity but with better performance,likely being a quick upscale of the buffer instead of using another buffer for the higher resolution.

Sorry if this is another big waste of your time,but performance has become a major concern.

**Comment by gonetz** [comment]
You may use rendered resolution as factor of native resolution. For example, original 320x240 will be rendered as 640x480 for factor 2 and then upscaled to 1080P. It should be much faster than render right into 1080P.

**Comment by retrobenny** [comment]
I already do this with 4x and that is faster than not using it but it still hits hard on the performance with even that.
I guess the breakdown would be that GLideN64 takes the original buffer and makes another one in 1080P while the emulator also adds to it,so you are left with a 1080P framebuffer from a 320x240 framebuffer into the emulator scaling phase.
The other plugins just upscale the one buffer into 1080P with much less work.

**Comment by gonetz** [comment]
No, GLideN64 renders frame buffer texture into main buffer created by emulator. Moreover, if you select 4:3 aspect and widescreen resolution, frame buffer texture will be 4:3 and it will be drawn on center of main frame buffer.

**Comment by retrobenny** [comment]
Sorry for the massive wall of text,I have a lot of ideas to share.

You are the professional here,so I guess there's nothing that can be done but to attempt on improving how blending works on the processing portion so that it doesn't have such a massive impact for properly rendering effects and devices like Shield TV can be fully utilized properly without the sluggishness from performance impacts maxing out the normal (wimpy) limits set on its under-utilized powerful GPU.
One goal could be to replace legacy blending with a better way of good performance without losing any effects,only losing some accuracy,the alternative would be a hacky version of the new blending to replace the legacy option.
Maybe the main thing needed is an Nvidia profile like Dolphin has where the GPU clock is raised for the app so that GLideN64 can actually run at a decent framerate consistently.
This needs to make it in before the big OTA upgrade happens with Nougat,also in hopes that emulators still work after knowing that at least Dolphin Emu stopped working on Nexus from Nougat.

The only other thing to help would be to improve Mupen64Plus AE's RSP Recompiler performance by a large margin so it can run,at most,double the performance than what it currently runs at.
The fastest plugin can barely run the Hailfire Peaks Icy oil rig ledge in Banjo-Tooie at full speed.

Other ideas include adding multithreading for blending shaders to offload into a CPU thread optionally of a core not being used by Mupen at all or as much,static blending shaders after they get created if even possible so repetition no longer causes immense slowdowns the closer you look at an effect.
And/or the most alternate idea of adding Vulkan support so that GPU control is more direct,LLE at excellent speeds with asynced compute shader support,less processor Mhz usage,better multithreading support for even lower Mhz each core with less heat.

I wonder if compute shading would also work on HLE,or is that only an LLE thing?
But could that be done on MLE for the best of both worlds?
(proper rendering and HD resolutions via post-processing on the LLE effects to avoid oddities of them)

**Comment by gonetz** [comment]
Sorry, but I hardly understand your points.

GLideN64 has plenty of room for optimization, it is undoubted. Optimization is a huge, technically hard work. It requires careful investigation, which modules of the plugin have strong influence on performance. We need statistics about that influence for different games. Serious optimization is hardly possible without such analysis. Who will do it? I barely have time for bugfixes. To be honest, I barely have time for anything.

**Comment by retrobenny** [comment]
Then sorry for me wasting even more of the limited time you have nowadays just wanted to throw some ideas to see if anything sticks.

If only someone knowledgable could make a version that focused on performance while still being able to render at least 80% of it all at the cost of accuracy loss and with game-specific customizations to suit every need much like .rdb files on emulators do already but further custom for every game to run at good performance with most everything intact.
The better thing would be full utilization of Vulkan so more devices can have the full benefits of it instead of just Nvidia chipsets with the desktop OpenGL access.
