### ISSUE TITLE
Feature request: Aspect Override Option like Jabo 1.7

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1121]
Using this option fixes some of the widescreen issues in SSB
![capture](https://cloud.githubusercontent.com/assets/9299743/18420563/3a65aaa8-782a-11e6-9f30-b7706292249c.PNG)
Without the option in GLideN64 it doesn't work correctly.

![capture](https://cloud.githubusercontent.com/assets/9299743/18420574/787058fc-782a-11e6-9b1b-9d7e42e6d810.PNG)

**Comment by oddMLan** [comment]
Im all about that asspect :smirk:

**Comment by theboy181** [comment]
Jabos Aspect fix does seem to have some issues too.. It might not be a good addition. Maybe a GS code that eliminates the off screen culling?

**Comment by natepley** [comment]
Sure it's not perfect, but it definitely seems to help.  I hope that Jabo's fix or something like it can give us excellent widescreen.

**Comment by gonetz** [comment]
Do you want to get it to work like this:
![gliden64_smash_brothers_001](https://cloud.githubusercontent.com/assets/8983092/19407885/5781f94c-92d9-11e6-91a4-b272ae930bbc.jpg)
?

It does not need a special option. It needs adjusting of current "widescreen" mode. As this is a hack, it can't work properly for all cases.

**Comment by gonetz** [comment]
Adjusted.

**Comment by theboy181** [comment]
This now seems to work better than Jabo!! Thanks!

I was wondering if there was a way to fix the FBE that stretches out the image at the end of a round, and see why links sword animations (up-b move) are drawn outside the screen area and the other effects are not. This would make for a perfect widescreen hack for this game.

It does deserve one too.
![capture](https://cloud.githubusercontent.com/assets/9299743/19413745/ac6c92fc-92eb-11e6-8a46-685f841fc09f.PNG)
![capture](https://cloud.githubusercontent.com/assets/9299743/19413758/12ebf7a2-92ec-11e6-88ce-ef8ba9c26b20.PNG)
![capture](https://cloud.githubusercontent.com/assets/9299743/19413765/52c355f0-92ec-11e6-916b-f6eda7a9ec69.PNG)

**Comment by gonetz** [comment]
I'm afraid it will require too much tuning for general code.
May be somebody will make a fork of GLideN64 with all necessary hacks for this game.

**Comment by gonetz** [comment]
Original issue is fixed.
