### ISSUE TITLE
High controller Input lag

### ISSUE THREAD

**Issue by budtz** [gonetz/GLideN64#1124]
I get a lot of input lag. In Mario64 its noticeble that he jumps after I press the botten. I tried retroarch and input lag was gone. But emulation here is terrible. 

Can it be reduced? I use project64 so it might be that. How about the original hardware?

**Comment by loganmc10** [comment]
If you use RetroArch a good test would be to try GLupeN64:

https://github.com/loganmc10/GLupeN64

Binary Builds:
http://loganbuildbot.s3-website-us-east-1.amazonaws.com/

GLupeN64 is a RetroArch port that uses this graphics plugin. If there is no input lag then the issue is not with this graphics plugin.

**Comment by jaburgeson** [comment]
I tried loading this core and it just crashes when I load a rom.  retroarch_debug doesn't actually show anything.

Is the build on the website 64bit?

**Comment by loganmc10** [comment]
Yes it's 64 bit

**Comment by gonetz** [comment]
@budtz GLideN64 is a graphics plugin. Why do you think it is responsible for controller input lags? It uses no controller input functions except for the case when texture dumping enabled.

**Comment by budtz** [comment]
Well i tried GlupeN64 but there was still lag about the same as with project64. The only combination that gives lower lag is mupen64 in retroarch but that has terrible emulation.

**Comment by gonetz** [comment]
Again, how that problem related to GLideN64 graphics plugin?

**Comment by loganmc10** [comment]
@gonetz There might be something to this. RetroArch has a feature that lets you step through the game frame by frame.

With Framebuffer Emulation disabled, the reaction is instant (if I press "jump", Mario jumps on the very next frame)

With Framebuffer Emulation enabled, the reaction is slow (if I press "jump", Mario jumps about 5 frames later). I realize that with Framebuffer Emulation enabled it is duping the frames or something (every 2nd frame looks identical to the last), but it is still delayed.

Another example: in Super Smash Bros menu, going to the next menu takes 1 frame with Framebuffer Emulation disabled, when it is enabled it takes 8 frames to get to the next menu.

@budtz Can you try with Framebuffer Emulation disabled and see if you notice a difference?

**Comment by loganmc10** [comment]
You can also perform this test with mupen64plus (p for pause, then hold down the jump key, then tap "/" to go frame by frame)

On Mario 64: 3 frames until he jumps vs 1 with Framebuffer Emulation disabled.
On Super Smash Bros: 2 frames vs 1 to get to the next menu.

I guess RetroArch handles the frames a bit differently, but the difference is still present in mupen64plus

**Comment by budtz** [comment]
Thx. Its the framebuffer. Turning it of reduces the lag greatly but i get stuttering and widescreen issues if i do

**Comment by gonetz** [comment]
> With Framebuffer Emulation enabled, the reaction is slow (if I press "jump", Mario jumps about 5 frames later). I realize that with Framebuffer Emulation enabled it is duping the frames or something (every 2nd frame looks identical to the last), but it is still delayed.

N64 Video Interface updates TV screen 60 times per second for NTSC. 60 vi/s. Mario 64 updates frame buffer 30 times per second. 30 FPS. That is VI shows each frame twice.

Now to GLideN64. When fb is off, plugin skips VI update calls until frame buffer changed. When buffer changed plugin swaps buffers.
When fb is on, VI works depends on selected screen update option. By default, desktop version renders current frame buffer to screen on each VI update call, as real N64 does. For Mario 64 each frame will be shown twice, for Zeldas 3 times. You may select update on buffer change and get the same behavior as with fb off.

**Comment by loganmc10** [comment]
When I test this using mupen64plus, FB off, there is no input lag, meaning that when I hold "jump", Mario is in the air the very next frame.

With FB on, there are 2 unique frames (things change each frame) before Mario is in the air, he is in the air on the 3rd unique frame.

Somehow the mupen64plus frame stepper skips the duplicate frames. RetroArch does not, that it why RetroArch takes 5 frames (3 unique and 2 duplicates like: unique - duplicate - unique - duplicate - unique/Mario has jumped)

**Comment by budtz** [comment]
I still get some lag using update on color buffer. also, i get stutters. seems best lag-wise to have it disabled.

to get rid of stuttering i need to set it to on vertical interupt

**Comment by gonetz** [comment]
> Somehow the mupen64plus frame stepper skips the duplicate frames.

It hardly does anything like this - there are no such feedback from graphics plugin to core.

**Comment by loganmc10** [comment]
> It hardly does anything like this - there are no such feedback from graphics plugin to core.

I'm not saying the core knows what the graphics plugin is doing. mupen64plus probably just advances every "real" frame (30 FPS in Mario 64), and RetroArch advances every buffer swap.

**Comment by loganmc10** [comment]
@gonetz it does seem to really be happening. Is it possible that with Framebuffer emulation enabled it is rendering a scene that happened 2 frames ago? Like the rendering is 2 frames behind the core?

Also, it does seem to depend on the FPS, Mario 64 seems to be 2 frames behind, while Smash Bros (which I believe runs at 60 FPS) is only 1 frame behind.

**Comment by weinerschnitzel** [comment]
Out of curiosity, does Counter Factor on the emulator side affect this?

**Comment by budtz** [comment]
It seems to me that in Mario 64 the lag is more noticeble than in other games. So it fits with my expiriance that the lag is not the same in every game. I have set counter Factor to 1. Wold that have any effect?

**Comment by loganmc10** [comment]
To be honest I can't believe you guys even notice the lag, you're talking ~66 ms of lag (2 frames at 30 FPS).

**Comment by budtz** [comment]
It must be more for me. Its clear mario jumps after i Press jump. Without lag he jumps after. Any other games than n64 does not do this for me.

**Comment by gonetz** [comment]
> @gonetz it does seem to really be happening. Is it possible that with Framebuffer emulation enabled it is rendering a scene that happened 2 frames ago? Like the rendering is 2 frames behind the core?

No, it is impossible.

However, plugin renders to a buffer, which is not immediately shown. Usually game uses two color buffers - one for rendering, other one displayed on screen. Game swaps buffers when rendering finished. Some games use triple buffering: one buffer for rendering, one waits to be displayed and one displayed on screen. Triple buffering usually use games running at 60 fps.

VI has address of buffer to show on screen. Thus, if new buffer rendering is finished, but VI commanded to show previous buffer, it will show previous buffer. You may check in debugger, does it happen for Mario 64.

When fb emulation is off, color buffer address register ignored.

**Comment by loganmc10** [comment]
I was kind of wondering if that was the case, so it's your opinion that this "lag" was present on real N64 hardware and having framebuffer emulation disabled unnaturally works around the lag?

**Comment by gonetz** [comment]
It not necessary presents on real N64. As I know, problem of timings and synchronizations in emu core is very complex. Probably emulator updates VI origin register too late.

**Comment by gonetz** [comment]
BTW, software lle plugin fully emulates VI. You may check it as well.

**Comment by Jj0YzL5nvJ** [comment]
To me this sounds related to XInput. Is ["DirectX Runtimes"](https://www.microsoft.com/en-us/download/details.aspx?id=8109) installed?

**Comment by budtz** [comment]
Yep its installed just fine and works for all other kinds of games just fine.

is there a way it could not be installed?

**Comment by loganmc10** [comment]
@budtz as per @gonetz suggestion I just tried this with mupen64plus-libretro (RetroArch), and angrylion, a software LLE graphics plugin.

It has 3 frames of "lag", just like GLideN64 does with Framebuffer Emulation enabled, so I believe it is working properly.

**Comment by Jj0YzL5nvJ** [comment]
> is there a way it could not be installed?

DX Runtimes needs be installed manually. The default runtimes only have a partial compatibility.

> For a long time it has been necessary for the DirectX redistributables to be installed for PCSX2 to work. However, by moving to a newer Windows SDK which isn't XP compatible and adjusting the code to load libraries that are already present on these operating systems, the need for the DirectX redistributables to be installed on Windows 8.1 and Windows 10 has been eliminated. (Caveat: SCP Xinput Wrapper users that need pressure sensitivity will still require the DirectX redists to be installed since the XInput wrapper wraps around XInput 1.3 and not XInput 1.4)

http://pcsx2.net/278-q3-2016-progress-report.html

**Comment by gonetz** [comment]
@loganmc10 Good to know, thanks!

**Comment by gonetz** [comment]
loganmc10 found that the problem is rather on emulator's side. The lag appears when plugin uses VI origin register, which is updated by emu core. I can't see what I can do about it.

**Comment by loganmc10** [comment]
By the way, this seems to be a Mario 64 specific problem. I tested both Super Smash Bros and Zelda: OoT and GLideN64 and Glide64 behave the same (in Smash Bros they "punch" on the 2nd frame and in Zelda Link's feet move on the.... 15th frame when I move forward, but it is the same in both plugins)
