### ISSUE TITLE
micro machines missing shadow

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1125]
start a new game

some shadows are missing (fb effects?)

here with a software plugin

![sans titre](https://cloud.githubusercontent.com/assets/8987490/18490982/a8003e26-7a04-11e6-8861-2d710eedbdb4.jpg)

**Comment by gonetz** [comment]
> some shadows are missing (fb effects?)

Looks like this. It works with Jabo plugin as well. Jabo seems to use software rendering for this, because when I make savestate and then load it with GLideN64, shadows are on place.

**Comment by olivieryuyu** [comment]
fixed with copy auxiliary colors buffers to N64 memory option!
