### ISSUE TITLE
Comunity texture pack for OOT

### ISSUE THREAD

**Issue by budtz** [gonetz/GLideN64#1129]
Is it possible to use the comunity texture pack for zelda? I cant seem to get it to work

**Comment by gonetz** [comment]
It worked for me when I tested it circa year ago.

**Comment by budtz** [comment]
I cant get it to do anything. it all acts the same as if i hadnt clicked load textures.

I use a dev build: rev.603706e it says. its from this site.

**Comment by gonetz** [comment]
Can you run this pack with Glide64?
Can you run other texture packs with GLideN64?

I may check that comunity texture pack, if you will give me download link.

**Comment by budtz** [comment]
I got it to work. I made a mistake in the path. 

It works though there is the issue with lines in the sky but this is not gliden64 related i think

**Comment by gonetz** [comment]
As I remeber, these lines in the sky appear with Glide64 too. Something is wrong with pack's textures.
