### ISSUE TITLE
Mortal Kombat 4 tries to draw 258 triangles.

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1130]
VERTBUFF_SIZE is set to 256 (in OpenGL.h)

However, in Mortal Kombat 4, right after you select your character, but before you choose your difficulty level. It tries to draw 258 triangles (I guess vertices would be a better term).

You can see this by printing the value of triangles.num in OGLRender::_prepareDrawTriangle

For some reason it doesn't seem to care that you are stepping outside of the bounds of the array with the regular code, but when using VBO's (the code I am testing), this results in a segfault.

**Comment by gonetz** [comment]
triangles.num is not number of vertices. It is number of elements. triangles.elements has ELEMBUFF_SIZE bound, which is 1024.

**Comment by loganmc10** [comment]
ok thanks, using ELEMBUFF_SIZE solves the crash using VBO's
