### ISSUE TITLE
Majora's mask in-game pictures look incorrect with software depth buffer

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1131]
This was reported to me by a user of Mupen64Plus AE, I don't have a save state unfortunately. With the hardware depth buffer, the in-game pictures look correct, see this screen shot:

![screenshot_2016-09-22-21-27-10](https://cloud.githubusercontent.com/assets/11581687/18772693/157be0ea-8117-11e6-9d90-97bb7a347a3f.png)

With the software depth buffer, they look like this:

![screenshot_2016-09-22-21-25-32](https://cloud.githubusercontent.com/assets/11581687/18772700/1c615016-8117-11e6-926d-6e7bdca701ae.png)

**Comment by gonetz** [comment]
Fixed

**Comment by fzurita** [comment]
That was fast. I'll check if it's fixed later.

**Comment by fzurita** [comment]
Confirmed by user that it was fixed.
