### ISSUE TITLE
I think Mickey Speedway USA is broken again.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#1132]
Testing with mupen64plus, and the intro "ripple" screens are grey.

**Comment by olivieryuyu** [comment]
depth buffer issue i guess

**Comment by olivieryuyu** [comment]
yes you need to deactive depth buffer to not have this issue

**Comment by AmbientMalice** [comment]
>yes you need to deactive depth buffer to not have this issue

That doesn't work. It's still broken.

**Comment by gonetz** [comment]
I know what's wrong. Proper fix will take time.

**Comment by gonetz** [comment]
Fixed
