### ISSUE TITLE
Little glitch in GoldenEye intro

### ISSUE THREAD

**Issue by Jj0YzL5nvJ** [gonetz/GLideN64#1133]
http://imgur.com/a/HgINX

 The mirrored texture to the right disappear after a move of camera. This only occur with mupen64plus-rsp-hle plugin, rsp-cxd4-sse2 and rsp-z64 are unaffected.

I bisected this to 5efd89ccd223347d3d2bc58f245d41a4d6ea2a41. In 154c06b14f2c8bc39442eee179e8bf7c5698a98b and previous, every rsp plugin does same work.

**Comment by matthewharvey** [comment]
Discussions in #159 seem to imply that the gun barrel texture wrapping around is not the correct behaviour anyway.

This video seems to imply that it did not wrap around on the console. https://youtu.be/D6l6_WKxRck?t=16

**Comment by AmbientMalice** [comment]
IIRC, it works in this branch. https://github.com/gonetz/GLideN64/tree/new_texrect_coords

**Comment by olivieryuyu** [comment]
duplicate #159 

interesting to know its works with the new texrecs branchs though

@gonetz 

can it be closed?
