### ISSUE TITLE
LOD emulation on LLE is inverted?

### ISSUE THREAD

**Issue by Jj0YzL5nvJ** [gonetz/GLideN64#1135]
mupen64plus-rsp-hle + EnableLOD = True
![goldeneye-003](https://cloud.githubusercontent.com/assets/12230570/18811721/842cfe24-8276-11e6-922a-5dcd2d25e3f8.png)

mupen64plus-rsp-hle + EnableLOD = False
![goldeneye-008](https://cloud.githubusercontent.com/assets/12230570/18811722/89d6d264-8276-11e6-8874-e7cd7442c0ea.png)

mupen64plus-rsp-cxd4-sse2 + EnableLOD = True
![goldeneye-009](https://cloud.githubusercontent.com/assets/12230570/18811723/8f14b5b6-8276-11e6-9897-3bc826922aba.png)

mupen64plus-rsp-cxd4-sse2 + EnableLOD = False
![goldeneye-010](https://cloud.githubusercontent.com/assets/12230570/18811725/94105b9c-8276-11e6-822a-b92ea2cbec8f.png)

**Comment by gonetz** [comment]
Fixed

**Comment by Jj0YzL5nvJ** [comment]
Yeah, is fixed now.
 I've seen many minor glitches with LLE plugins in GE. I do proper reports most later.
