### ISSUE TITLE
Mahjong Master: texture issue

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#114]
ok

**Comment by olivieryuyu** [comment]
enabledepthcompare fixes depth issue

**Comment by oddMLan** [comment]
Bug looks different now
![gliden64_ _ _003](https://cloud.githubusercontent.com/assets/7278372/15263602/6fbbda88-1920-11e6-9ded-982ea63d223a.png)
With the added bonus of broken texture mapping, which seems to be a regression. Fixed by native resolution x1.

Black line fix doesn't help.

**Comment by olivieryuyu** [comment]
yes it is worst now

**Comment by olivieryuyu** [comment]
RDP issue apparently as LLE is the same than HLE

**Comment by olivieryuyu** [comment]
fixed under S2DEX patreon...

**Comment by gonetz** [comment]
@olivieryuyu should be closed now, no?

**Comment by olivieryuyu** [comment]
need to check if it is still working as it was related to evangelion texture mapping fix.

**Comment by olivieryuyu** [comment]
no idea how it is fixed but it is fixed
