### ISSUE TITLE
Texture pack fail

### ISSUE THREAD

**Issue by LuismaSP89** [gonetz/GLideN64#1140]
There are some issues when you use a texture pack like this:

http://www.emutalk.net/threads/55307-Zelda-Ocarina-of-time-Community-Retexture-Project-V7

I think, the problem is that Gliden64 doesn´t support transparency in images, but i don´t know if this is the problem or not.

The texture pack works well with other plugins like the Rice 0.4.4.

Note: Using Gliden64 compiled at 2016/09/26

Two images attached, one with the Rice 0.4.4 and the other one with Gliden64.

![rice 0 4 4](https://cloud.githubusercontent.com/assets/12205048/18856725/ae5af6d6-845d-11e6-8f25-1c3afe4f8f1b.jpg)
![texture fail](https://cloud.githubusercontent.com/assets/12205048/18856726/ae62bc2c-845d-11e6-9b9c-4ea50b3e1680.jpg)

**Comment by gonetz** [comment]
This issue was already reported. This pack does not work well with Glide64 and GLideN64. Since both plugins have no issues with original textures and with Djipi's texture pack, the problem is with textures in Community pack.
