### ISSUE TITLE
Yoshi's Story black screen in some levels if frame buffer is enabled

### ISSUE THREAD

**Issue by Tasosgemah** [gonetz/GLideN64#1143]
I get a black screen (i can only see some UI elements) if i move one step in the level "piranha grove" when framebuffer effects are enabled. The screen appears and becomes black again randomly as i move through the level.

I don't have a save file to access the level but i use a cheat that unlocks all trial levels:

Master code (you need this): 

DE000400 0000

Unlock trial levels: 

810F8E5C 7FFF
810F8E5E FFFF

I'm using PJ64 2.3 and the latest build of the plugin.

**Comment by gonetz** [comment]
Fixed
