### ISSUE TITLE
Wonder Project J2 - Textures with boxes at higher resolution.

### ISSUE THREAD

**Issue by orbea** [gonetz/GLideN64#1145]
OS: `Slackware64-current`
`mupen64plus-2016.09.13_5fa30ab-x86_64-1_SBo`
`GLideN64-d5412d3_2016.09.27_master-x86_64-1_git`

In the game `Wonder Project J2` and with resolutions of `640x480` or higher several textures in this game will have boxes around them during certain animations. This is easiest to reproduce by watching the bird blink in the start menu. With `EnableNativeResTexrects` the issue is mitigated, but not fully solved. The rsp plugin does not make a difference. I can additionally reproduce this with GLupeN64.

__GLideN64 + 640x480__
![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/mupen64plus/Wonder%20Project%20J2%20-%20Kpruro%20no%20Mori%20no%20Jozet%20(Japan)%20%5bEn%20by%20Ryu%20v1.0%5d-160929-141359.png)
__GLideN64 + 640x480 + EnableNativeResTexrects__
![2](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/mupen64plus/Wonder%20Project%20J2%20-%20Kpruro%20no%20Mori%20no%20Jozet%20(Japan)%20%5bEn%20by%20Ryu%20v1.0%5d-160929-144133.png)
__GLideN64 + 320x240__
![3](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/mupen64plus/Wonder%20Project%20J2%20-%20Kpruro%20no%20Mori%20no%20Jozet%20(Japan)%20%5bEn%20by%20Ryu%20v1.0%5d-160929-142520.png)

**Comment by AmbientMalice** [comment]
I'm not sure this can actually be fixed. It's a filtering issue where the textures overlaid don't look right at higher resolutions. You should play stuff like this at 1x native scaling, I think.

**Comment by orbea** [comment]
Fair enough, if that is the case this can be closed without fixing. I will wait for more discussion first.

**Comment by gonetz** [comment]
Yes, texture filtering does not work right at higher resolutions. That's why all these 'native resolution' options added. I see no other way to fix that issue.
