### ISSUE TITLE
Donkey Kong 64 - Textures stretching.

### ISSUE THREAD

**Issue by orbea** [gonetz/GLideN64#1148]
OS: `Slackware64-current`
`mupen64plus-2016.09.13_5fa30ab-x86_64-1_SBo`
`GLideN64-d5412d3_2016.09.27_master-x86_64-1_git`

In the game `Donkey Kong 64` certain areas will cause the textures to stretch erratically. This can be easily reproduced by standing, moving or jumping in front of Dr. Cranky's Lab near the start of the game.

This can also be reproduced in glide64, glide64mk2 and GLupeN64. However it does not occur with mupen64plus-libretro.

Apitrace - http://ks392457.kimsufi.com/orbea/stuff/trace/mupen64plus/gliden64_donkey_kong_64.trace.xz
Apitrace log - http://pastebin.com/u4AtuXMS

![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/mupen64plus/Donkey%20Kong%2064%20(USA)-160929-171843.png)

**Comment by Isotarge** [comment]
Hi obrea, I've been doing a lot of research over the last few years regarding this bug, and it's a core issue, not an issue with any specific video plugin. I have a fix that patches RDRAM and gillou is working on one that doesn't.

Please see my report at [mupen64plus-core](https://github.com/mupen64plus/mupen64plus-core/issues/145) for more information.

This issue should be closed.

**Comment by orbea** [comment]
That is interesting. given how it occurs in mupen64plus, GLupeN64, but not in mupen64plus-libretro. maybe @loganmc10 might have an idea what the difference is? If the above is true this should be closed, but I would like to see a little more discussion first.

**Comment by gonetz** [comment]
Yes, it's a core issue, not an issue with any specific video plugin.
Early versions of Project64 also had that bug.

**Comment by loganmc10** [comment]
@orbea I'm not sure what libretro did to fix this bug, twinaphex might know

**Comment by orbea** [comment]
I was wrong, this is in mupen64plus-libretro too.
