### ISSUE TITLE
Broken Pokemon stadium 2 in-game portraits

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1149]
One of the recent updates broke Pokemon stadium 2 in-game portraits. At least I'm getting reports that it used to work. They look like black silhouette for the first set of Pokemon that comes out, like this:
![pokemon_stadium_2-000](https://cloud.githubusercontent.com/assets/11581687/19009883/7e9a3ec0-8746-11e6-80d1-e1844dda4443.png)

Follow up Pokemon look ok though:
![pokemon_stadium_2-001](https://cloud.githubusercontent.com/assets/11581687/19009895/aa22353e-8746-11e6-9a3d-6fca88189836.png)

**Comment by orbea** [comment]
I can reproduce this too, but its fixed in @loganmc10 vbo branch and in GLupeN64 too.

https://github.com/loganmc10/GLideN64/tree/vbo

**Comment by loganmc10** [comment]
@orbea does it happen in GLES2 or GLES3 mode in GLupeN64? Those versions don't use VBOs so it should work the same as mupen64plus would.

**Comment by orbea** [comment]
I was wrong, it was that it was loading the save states produced a similar issue as described by fzurita, but starting a match without a save state works. Sorry for the false alarm.

**Comment by orbea** [comment]
@fzurita Any chance you can make an apitrace? Maybe its a video driver bug? That would explain why its not reproducible here. An apitrace should be useful in determining if other video drivers can reproduce it.

You can make one with `apitrace trace mupen64plus --gfx mupen64plus-video-GLideN64` and you can replay it to make sure the trace is good with `apitrace replay mupen64plus.trace`. You can compress it before uploading by using `xz -9 mupen64plus.trace`.

**Comment by fzurita** [comment]
This is in Android with mupen64plus-ae, I'm not setup to easily do an apitrace right now.

It would not surprise me at all of our was a driver bug with Adreno

I do need to get setup to do apitrace though, I'm sure it would help debug the number of issues we have right now with Adreno devices.

**Comment by orbea** [comment]
I tried the mesa GLES2 driver on my desktop, I still couldn't reproduce it.

**Comment by fzurita** [comment]
I just tried on the NVidia Shield TV with full OpenGL drivers and I got the same issue, I tried every single setting I could think of. Only one that made a difference was having frame buffer emulation off which cause portraits to display junk instead.

**Comment by fzurita** [comment]
I just went back a few versions behind, and this was not introduced at least within the last week.

**Comment by gonetz** [comment]
I also can't reproduce it with desktop build.

**Comment by fzurita** [comment]
Interesting, it's broken only in Android.

**Comment by fzurita** [comment]
Ok, I took some time to find the commit that broke this in Android. It was this one:

https://github.com/gonetz/GLideN64/commit/e28bebd17e6066a525b7ab95bd776669d6cfcd7a

**Comment by gonetz** [comment]
@fzurita It looks like a compiler issue. I just moved this line from CheckForFrameBufferTexture to FrameBuffer::isValid()
Could you try to compile without compiler optimizations and check it again?

**Comment by fzurita** [comment]
Hmm, interesting, yeah, sure. I'll well also inspect this code carefully to see if logic changed somehow.

**Comment by gonetz** [comment]
The only change: 
previously m_validityChecked modified only when isValid() returned true.
Now it modified even when validity check fails. However, it does not matter because invalid buffer will be removed anyway.

**Comment by fzurita** [comment]
Yeah, I saw that difference. I wonder if there is some Android specific code that is making this fail only on Android.

By the way, I forced rechecking of validity in gDP.cpp by passing a flag to isValid and that fixes the issue. That tells me that there is something subtle going on, since it shouldn't make a difference since the buffer had been removed.

**Comment by fzurita** [comment]
Ok, this fixes the problem in Android. 

```

bool FrameBuffer::isValid() const
{
	if (m_validityChecked == video().getBuffersSwapCount())
		return true; // Already checked

	const u32 * const pData = (const u32*)RDRAM;

	if (m_cleared) {
		const u32 testColor = m_clearParams.fillcolor & 0xFFFEFFFE;
		const u32 ci_width_in_dwords = m_width >> (3 - m_size);
		const u32 start = (m_startAddress >> 2) + m_clearParams.uly * ci_width_in_dwords;
		const u32 * dst = pData + start;
		u32 wrongPixels = 0;
		for (u32 y = m_clearParams.uly; y < m_clearParams.lry; ++y) {
			for (u32 x = m_clearParams.ulx; x < m_clearParams.lrx; ++x) {
				if ((dst[x] & 0xFFFEFFFE) != testColor)
					++wrongPixels;
			}
			dst += ci_width_in_dwords;
		}
		return wrongPixels < (m_endAddress - m_startAddress) / 400; // threshold level 1% of dwords
	} else if (m_fingerprint) {
		//check if our fingerprint is still there
		u32 start = m_startAddress >> 2;
		for (u32 i = 0; i < 4; ++i)
			if ((pData[start++] & 0xFFFEFFFE) != (fingerprint[i] & 0xFFFEFFFE))
				return false;

		m_validityChecked = video().getBuffersSwapCount();

		return true;
	} else if (!m_RdramCopy.empty()) {
		const u32 * const pCopy = (const u32*)m_RdramCopy.data();
		const u32 size = m_RdramCopy.size();
		const u32 size_dwords = size >> 2;
		u32 start = m_startAddress >> 2;
		u32 wrongPixels = 0;
		for (u32 i = 0; i < size_dwords; ++i) {
			if ((pData[start++] & 0xFFFEFFFE) != (pCopy[i] & 0xFFFEFFFE))
				++wrongPixels;
		}
		return wrongPixels < size / 400; // threshold level 1% of dwords
	}

	m_validityChecked = video().getBuffersSwapCount();

	return true; // No data to decide
}

**Comment by gonetz** [comment]
What the point to move it there?
In most cases the functions will return before that line. You may remove m_validityChecked use and get the same effect. 

Truly speaking, I don't understand what is going on there. Could you add some  traces to FrameBufferList::removeBuffer? Namely, address of buffer to remove and list of (start addresses) remaining buffers? I wonder, will these traces different with and without your changes.

**Comment by fzurita** [comment]
The old code only used to update m_validityChecked if isValid returned true, I was just imitating that functionality.

Yeah, I'll add some traces when I get a chance.

**Comment by gonetz** [comment]
> The old code only used to update m_validityChecked if isValid returned true, I was just imitating that functionality.

No, you did not.

```
return wrongPixels < (m_endAddress - m_startAddress) / 400;
return wrongPixels < size / 400; // threshold level 1% of dwords

```
it also can return true;

**Comment by fzurita** [comment]
Whoops, I missed that case. I'll make m_validityChecked update for that case too and see what happens.

**Comment by fzurita** [comment]
I could be wrong, but I think I see a potential problem with the logic. For a specific buffer address, ```FrameBuffer::isValid``` can return true the first time it's run for a frame. If it becomes invalid after, we won't check it again until the next frame, so it will not be removed until the next frame.

It seems like we need to remove it earlier than the next frame, otherwise the portraits won't show correctly.

**Comment by gonetz** [comment]
>I could be wrong, but I think I see a potential problem with the logic. For a specific buffer address, FrameBuffer::isValid can return true the first time it's run for a frame. If it becomes invalid after, we won't check it again until the next frame, so it will not be removed until the next frame.

Buffer becomes invalid when corresponding memory area in RDRAM is changed by CPU. CPU does not alter RDRAM during RDP work, at least it must not do it intil FullSync. Thus, no reason to check buffer validity more than once per frame.

> Edit: After adding enough logging, this is exactly what I'm seeing happening in this case. The buffer is checked once for one frame number and it turns out to be valid. We again check it again and we say it's valid even though, if we would had done all the checks, it would had turned out to be invalid.

Interesting. I'll remove m_validityChecked check and try to catch that case.

> I bet that FBInfo::fbInfo.isSupported() must be returning true.

No. FBInfo support detection is platform independent. If fbInfoDisabled option is set, isSupported will return false. If emulator does not call FBInfo functions, isSupported also will return false. 

fbInfoDisabled is set to 1 by default for mupen64plus. Nevertheless, I can't reproduce the issue with portraits on desktop. I checked windows and linux builds, no problems.

**Comment by fzurita** [comment]
Interesting, this check is what is breaking the portraits:
```else if (!FBInfo::fbInfo.isSupported() && !pBuffer->isValid()) {```

I wonder why the above check in VI.cpp and the below check in gDP.cpp:
```
		if (bRes) {
			bRes = pBuffer->isValid();
			if (!bRes)
				fbList.removeBuffer(pBuffer->m_startAddress);
		}
```

Are being called within the same frame in Android. First one returns true, second also returns true but should return false....

Is this not happening in desktop or retroarch (within Android)?

**Comment by gonetz** [comment]
Yep, you right! Previously, m_validityChecked flag was modified from CheckForFrameBufferTexture. isValid() call from VI.cpp did not change it. Desktop build uses bsOnVerticalInterrupt swap mode. I guess, Android uses other options. Thus, m_validityChecked now became different for Android and desktop.

**Comment by fzurita** [comment]
Whoops, I didn't think of toggling that option. What is the recommended swap mode for optimal performance?

**Comment by gonetz** [comment]
I guess bsOnColorImageChange is best for performance. bsOnVerticalInterrupt is for best compatibility.

**Comment by gonetz** [comment]
I fixed this issue. The problem occurs when buffer swapped not on each VI Update call. It is possible, that buffer became invalid between VI Update calls, but because the first time it was valid, isValid returns true until next buffers swap.

**Comment by fzurita** [comment]
Gonetz, I believe that your fix is what I tried myself and that didn't work. I had to force the check in gDP.cpp and not VI.cpp.

I'll check it again just to make sure, but just letting you know ahead of time just in case it doesn't work.

**Comment by gonetz** [comment]
I reproduced the bug on desktop when I changed buffer swap mode. My changes fixed it.

**Comment by fzurita** [comment]
Ok

**Comment by fzurita** [comment]
Ok, it works, closing. I must had done something wrong when I tried it your way.
