### ISSUE TITLE
Pokemon Stadium 2 (PAL) - Freeze after nintendo logo with OpenGL

### ISSUE THREAD

**Issue by orbea** [gonetz/GLideN64#1150]
OS: `Slackware64-current`
`mupen64plus-2016.09.13_5fa30ab-x86_64-1_SBo`
`GLideN64-d5412d3_2016.09.27_master-x86_64-1_git`

In the PAL version of the game `Pokemon Stadium 2` will freeze immediately after the nintendo logo while displaying garbage. However the game will work with glide64 and the NTSC-U version will work with GLideN64. It is also reproducible in GLupeN64.

![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/mupen64plus/2016-09-30-190746_1680x1050_scrot.png)

**Comment by orbea** [comment]
This only occurs with OpenGL and not GLES2.

**Comment by gonetz** [comment]
Fixed

**Comment by orbea** [comment]
Awesome, I can confirm its fixed here too, thanks!.
