### ISSUE TITLE
SM64 Last Impact: Incorrect Audio When "Copy Frame Buffer to RDRAM" is Enabled

### ISSUE THREAD

**Issue by RibShark** [gonetz/GLideN64#1153]
When loading the ROM Hack "SM64 Last Impact", if "Copy Frame Buffer to RDRAM" is set to "Sync" or "Async", then anywhere after the title screen, the audio will be messed up. Music will use various sound effects from the game (in the proper pitches, however) instead of the proper instruments, and when a sound effect should play, such as when Mario jumps, a different sound effect will play instead. I have tested this on Project64 2.3 using various audio and video plugins. No matter what audio plugin is used, this will happen, and only with GLideN64 with "Copy Frame Buffer to RDRAM" enabled.

**Comment by gonetz** [comment]
Does it work correct with software graphics plugin?

**Comment by AmbientMalice** [comment]
These romhacks generally don't comply with proper N64 behavior, so yea, testing with Angrylion's would be ideal.

**Comment by RibShark** [comment]
This also happens with Angrylion's plugin. I should have tested this earlier. I'll close this report now. Sorry for bothering you.

**Comment by AmbientMalice** [comment]
The romhack must be doing some pretty non-kosher stuff. Still, if it works without copying FB to RAM, then that's okay.

**Comment by gonetz** [comment]
I guess, it uses frame buffer area in RDRAM for its own data. That is the rom is not intended to run on real console.
