### ISSUE TITLE
Super Smash Bros Intro not playing with Framebuffer Emulation enabled

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1154]
When Framebuffer Emulation is enabled, the Smash Bros intro does not play, it gets "stuck" when the character poses, like this:

![screenshot from 2016-10-03 21-48-48](https://cloud.githubusercontent.com/assets/848146/19062045/69f6f98a-89b3-11e6-90ff-e0321324bc9c.png)

The audio still plays in the background, with Framebuffer Emulation disabled, it works

**Comment by gonetz** [comment]
Fixed

**Comment by loganmc10** [comment]
thanks!
