### ISSUE TITLE
Mario Artist Talent Studio - Ending photo bugged rendering

### ISSUE THREAD

**Issue by LuigiBlood** [gonetz/GLideN64#1157]
![image](https://cloud.githubusercontent.com/assets/952602/19121961/b787d996-8b28-11e6-80fa-763969a2e3a2.png)
To reproduce it, you can save the default character in a container (red menu, and then click the 64DD disk). Go back to the main menu, select the yellow menu, Talent, and then click the balloon with the character. Wait until the show is done and the photo should appear.

Auxiliary buffer is required.

**Comment by LuigiBlood** [comment]
Basically a checkup: Still happens on 2.0 release.

**Comment by olivieryuyu** [comment]
i think it happens in few games. FB is calculated in half or a quarter (i.e Waialae country club, KEN GRIFFEY SLUGFEST)

**Comment by LuigiBlood** [comment]
![image](https://cloud.githubusercontent.com/assets/952602/24666151/c3f8c06c-195f-11e7-80b7-a44b4408ff7a.png)
It finally works. That said, the last digit is missing.

**Comment by oddMLan** [comment]
Could that be a core issue akin https://github.com/project64/project64/issues/633

**Comment by LuigiBlood** [comment]
Yes it shows up in Angrylion RDP.

**Comment by LuigiBlood** [comment]
In latest WIP build (d8ac5a7), the last digit shows up.
However, there is another issue.
![image](https://user-images.githubusercontent.com/952602/31851359-a470835e-b664-11e7-958c-d64926b968ff.png)
I went on doing 2 people at once and the other one simply does not render in the ending photo.

It's rather simple to do it, just need to save 2 people in the same folder/container, and then play the whole Talent folder.

**Comment by LuigiBlood** [comment]
I must mention, it works fine on angrylion.

**Comment by olivieryuyu** [comment]
oh gosh

microcode is RSP Gfx ucode F3DPEX      fifo 2.06F Yoshitaka Yasumoto 1998 Nintendo.

**Comment by LuigiBlood** [comment]
I do not know when it was fixed, but I tried using a fairly recent version and it had no issues anymore.
