### ISSUE TITLE
Balloons invisible in DKR with VEC4_OPT

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1159]
![dkr](https://cloud.githubusercontent.com/assets/848146/19158464/0cfa855e-8ba6-11e6-925b-116fa259b08f.png)

This happened fairly recently (I played this the other day and they were there)

**Comment by gonetz** [comment]
I can't reproduce it with desktop build.

Could you find, which commit breaks it for you?

**Comment by loganmc10** [comment]
@gonetz I figured it out, they disappear with VEC4_OPT is on, however it works on Android, so maybe it works when NEON_OPT is on as well?

@fzurita

**Comment by loganmc10** [comment]
I thought it happened recently because I was playing this on my phone the other day and it worked, then I tried it a few days later on the computer and it didn't work, so I assumed something recent broke it, however this issue has been around for a while.

**Comment by fzurita** [comment]
This kind of issue is easy to debug. All you have to do enable the VEC4 optimization and comment out rack place where they are used one at a time and the run. Eventually, you will find the one place in the code where the VEC4 optimizations break the code.

Once you find the place, all you have to do is compare the optimized version to the non optimized version and see where they are different.

**Comment by loganmc10** [comment]
Well given that it works with NEON_OPT, I assume the problem is somewhere in gSPTransformVertex4_default, gSPTransformNormal4_default, or gSPBillboardVertex4_default. Even if I found the issue I don't really have the coding skill in that area to fix the problem, so for now I'm just going to have GLupeN64 only enable VEC4_OPT for Neon

**Comment by fzurita** [comment]
Ok, I would leave this issue open though since it does point out to something being wrong with the VEC4 optimization.

**Comment by gonetz** [comment]
Fixed
