### ISSUE TITLE
NO_BLIT_BUFFER_COPY causes flickering when not used with GLES2

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1160]
If I try to use NO_BLIT_BUFFER_COPY with anything other than GLES2, I get flickering (every other frame is black) in Super Mario 64.

**Comment by loganmc10** [comment]
Other games seem to work ok I only tested Diddy Kong Racing and Pokemon Stadium 2, they don't flicker

**Comment by fzurita** [comment]
Hmm, I have tried it on Android and I don't get that issue. It could be settings related. Maybe it has to do with the BufferSwapMode.

**Comment by loganmc10** [comment]
It probably does, try on vertical interrupt and Super Mario 64

**Comment by gonetz** [comment]
NO_BLIT_BUFFER_COPY does not cause flickering in SM64 on desktop for me.

**Comment by loganmc10** [comment]
Hmm okay maybe it was some settings I had, this was probably something I did wrong
