### ISSUE TITLE
Zelda: Ocarina of Time - White screen with EnableCopyColorFromRDRAM

### ISSUE THREAD

**Issue by orbea** [gonetz/GLideN64#1165]
When setting `EnableCopyColorFromRDRAM` to True and starting the game Zelda: Ocarina of Time it will white screen while sound and input still work. This does not occur with other games, but it affects mupen64plus + GLideN64 and GLupeN64 with OpenGL, GLES2 and GLES3 on both Slackware Linux and android.

**Comment by gonetz** [comment]
Is it always white or only in pause screen?
Was it working before?
If it is a regression, could you find the commit, which causes it?

**Comment by orbea** [comment]
Always white. The white screen will only occur with frame buffer emulation enabled. As far as I am aware this has been broken, I tried some older commits and it still occurred there.

**Comment by gonetz** [comment]
I tested current master on Ubuntu - no such issues.
Try to clear content of ~/.cache/mupen64plus folder or disable Shader Cache option.

**Comment by orbea** [comment]
I have tried both and that option makes no difference. That is strange that you can't reproduce it with when I can with mupen64plus, mupen64plus-ae (Black screen instead of white) and RetroArch on both Slackware and android and more than one rom.

**Comment by gonetz** [comment]
Sorry, I inexactly read your message. Yes, you will get white screen with that option because of "copyWhiteToRDRAM" hack for Zelda OOT. This hack fills frame buffer area in RDRAM with white color. That removes delay in pause screen open. Obviously, when you read that buffer from RDRAM to screen, the screen will be white. Remove hack_subscreen in the code if you really need that option.

**Comment by orbea** [comment]
Alright, thanks for the explanation. It was unexpected when I was testing out unknown options. I guess the best solution would be to fix the pause screen delay without such a hack, but I understand that would not be easy. I guess this can be closed now.

**Comment by retrobenny** [comment]
I know its closed but,honestly,that fix patch needs to be replaced with the other code that originated on the debug Master Quest version of OOT.
I ported it to the (U) 1.0 version myself and it works wonders while also preventing crashes on Counter Factor 1/CountPerOp=1 too!
There's also the lagfix (80007CE2 000D) code which would crash if this ported code is not enabled.

Subscreen Delay Fix
D01C7021 0002
801DA5CB 0002
D01C7021 0002
801C7021 0003
The difference is that the value is not constantly used but only the instant when pausing to skip the delay and preventing crash risks.
