### ISSUE TITLE
[mupen64plus] Paper Mario crashes upon loading a room in Shy Guy Toy Box (savestate in description)

### ISSUE THREAD

**Issue by AlessandroPorcelli91** [gonetz/GLideN64#1168]
I have been using one of the recent weekly builds, can anybody check this? 
[Paper Mario (U) [!].zip](https://github.com/gonetz/GLideN64/files/519645/Paper.Mario.U.zip)

**Comment by fzurita** [comment]
No crash here, but is it supposed to be really hard to see in that room?

**Comment by gonetz** [comment]
AFAIR, there was a room, where you can see anything only with sun fellow (forgot his name) in your hands.

**Comment by AlessandroPorcelli91** [comment]
I shall try again with the latest nightly build in that case. If no crash happens I will close this. Thanks for trying folks.

**Comment by AlessandroPorcelli91** [comment]
Alright, I have downloaded the latest master and it looks like the regression has been since fixed, I'm closing this.
