### ISSUE TITLE
Quake 64 depth issues

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#1169]
This seems to be a regression. Not sure when it appeared. Distant entities render through walls, and then disappear when you get closer to them.

![gliden64_quake_000](https://cloud.githubusercontent.com/assets/10704701/19274483/986d2d28-9013-11e6-8c56-b67707b1eae4.jpg)

**Comment by gonetz** [comment]
I can't reproduce it.

**Comment by olivieryuyu** [comment]
me neither

**Comment by AmbientMalice** [comment]
Must have been a temporary regression. I built latest source, and issue is gone.

**Comment by AmbientMalice** [comment]
Issue is back again.
