### ISSUE TITLE
GoldenEye Multiplayer - 3&4 player not rendering

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1173]
![image](https://cloud.githubusercontent.com/assets/848146/19353443/aafe5b2a-9120-11e6-9438-16ae0317d6d3.png)

I'm not sure how long this issue has existed for.

**Comment by loganmc10** [comment]
Does anyone have any ideas about this? It seems like it's probably been around for at least a couple months. I don't see any GL errors being generated.

2 player mode also has the issue (the player on the bottom isn't visible)

**Comment by AmbientMalice** [comment]
I think the bug has been around since the start.

**Comment by loganmc10** [comment]
Disabling Framebuffer Emulation fixes the problem

**Comment by AmbientMalice** [comment]
Well, it could be forced disabled, but it's really not ideal.

**Comment by loganmc10** [comment]
No it shouldn't be disabled, I mentioned that just as a hint as to where the problem probably lies

**Comment by loganmc10** [comment]
I've been troubleshooting another issue (the depth issues in the Raspberry Pi and some Android phones) and I added a glClear(GL_DEPTH_BUFFER_BIT) after each glBindFramebuffer() call, and it almost fixes this problem.

The bottoms players now show up, but it "flickers" every 3 seconds or so with the improper image. There is something up with depth buffer clearing....

**Comment by Blue-Ike** [comment]
This issue seems kind of related to #836.

**Comment by LuismaSP89** [comment]
Yes, this is a really annoying problem, the players can move around the scenario and the other players can see them, but it´s like the player 3 and 4 where playing at blind man's bluff game.

**Comment by Exequiel3k** [comment]
I noticed by disabling "EnableFragmentDepthWrite" & "EnableFBEmulation", it fixes the 4 screens multiplayer issue.

With all that in mind, I tried to automate it via m64p custom.ini but the "FragmentDepthWrite" isn't being disabled which causes constant flickering/misalignment..
This is how I wrote it:

[GOLDENEYE]
Good_Name=007 - GoldenEye (E)(U)
FragmentDepthWrite\enable=0
FrameBufferEmulation\enable=0
N64DepthCompare\enable=1

Does it have to be written in a different way??

**Comment by loganmc10** [comment]
The options should look like:

```
frameBufferEmulation\N64DepthCompare=1
frameBufferEmulation\enable=0
generalEmulation\enableFragmentDepthWrite=0
```

I don't think N64 Depth Compare is going to do anything if you have Framebuffer emulation disabled

Also, unfortunately I must have missed enableFragmentDepthWrite when I implemented ini reading for mupen64plus, it's missing. I'll have to submit a PR to add it before it'll be able to read that from the ini file

**Comment by Exequiel3k** [comment]
Alright, thanks for the update👍

**Comment by Exequiel3k** [comment]
On a side note, if its doable, is it possible to add NativeResTexrects as well in the ini reading?

**Comment by loganmc10** [comment]
That's already in there as ```generalEmulation\enableNativeResTexrects```

You can see what is currently read in https://github.com/gonetz/GLideN64/blob/master/src/mupenplus/Config_mupenplus.cpp by looking at the Config_LoadCustomConfig() function

**Comment by Exequiel3k** [comment]
Thx for the info, I was wondering what was being read or not :p

**Comment by williansti** [comment]
this problem remains unsolved? here is the same problem, impossible to play 007 gondeneye for 4 with this plugin

**Comment by Exequiel3k** [comment]
if you're using m64p (the latest version), paste this into the custom.ini file:

[GOLDENEYE]
Good_Name=007 - GoldenEye (E)(U)
frameBufferEmulation\enable=0
generalEmulation\enableFragmentDepthWrite=0

Solved my problem for goldeneye 4 player..

**Comment by loganmc10** [comment]
The same thing should work in Project64

**Comment by williansti** [comment]
I am using updated project64, the tip does not work adding it to screens 1 and 2 flashes, screens 3 and 4 remain defective.

Project64 Git 2017/10/25
GLideN64 2017/10/29

![without the fix](https://user-images.githubusercontent.com/10545674/32382484-7dbac3e0-c09c-11e7-958b-fedc8d27bf87.jpg)

![with the fix](https://user-images.githubusercontent.com/10545674/32382488-83641fda-c09c-11e7-910e-2501cd527f30.jpg)

**Comment by Exequiel3k** [comment]
My code is based on using latest version of m64p..

**Comment by fzurita** [comment]
To me this seems like a problem with depth on the LLE triangles used to draw the sky.

**Comment by Exequiel3k** [comment]
Just a little heads up, I recently updated the build and noticed the quick fix isn’t working anymore. I can no longer play 4 split screen since it’s either flashing and/or only the sky is visible on the bottom screens. Just thought I’d let you’ll know..

**Comment by LuismaSP89** [comment]
@gonetz Is not in this thread/post, let´s hope he see and solve this problem.

**Comment by truskj** [comment]
I play a lot of GoldenEyeX, a mod for perfect dark, it suffers from the same problem. 
but I found that having the screen split set to vertical instead of horizontal, this will remedy the problem.
even if you are playing in four player mode, the setting still makes a difference. 
People playing GE are out of luck, but I imagine the same thing will work in Perfect Dark.

**Comment by Blue-Ike** [comment]
The latest WIP (Master + FB Fixes) addressed and fixed these issues on Goldeneye and on Perfect Dark as well. Multiplayer screens for both 3rd and 4th player are now rendered and are playable. #836 was closed by me since that's no longer an issue either. Therefore, this can also be closed.
