### ISSUE TITLE
Racing Simulation - Monaco Grand Prix: missing gfx (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1174]
![sdfsdf](https://cloud.githubusercontent.com/assets/8987490/19381982/6c02e2fe-91fe-11e6-8d35-e0d2961c1afc.jpg)

**Comment by olivieryuyu** [comment]
due to fb emulation

**Comment by gonetz** [comment]
I can't reproduce it.

**Comment by olivieryuyu** [comment]
ok works with mupen and PJ64, not 1964
