### ISSUE TITLE
Mischief Makers incorrect textures (regression?)

### ISSUE THREAD

**Issue by lKomus** [gonetz/GLideN64#1175]
It looks like the plugin is displaying again incorrect textures for the platforms and the walls in 2-2, 2-8 and 2-10 levels.

Messing with enabling and disabling the framebuffer change the textures for some reason.
The three pictures show three different states between messing with this.

![project64_2016-10-14_16-13-32](https://cloud.githubusercontent.com/assets/4800879/19390635/35177fc2-9229-11e6-80ad-18127d99e4bb.png)
![project64_2016-10-14_16-03-56](https://cloud.githubusercontent.com/assets/4800879/19390411/4d66400a-9228-11e6-9de3-1d7dc7d14286.png)
![project64_2016-10-14_16-04-28](https://cloud.githubusercontent.com/assets/4800879/19390413/4f2be336-9228-11e6-8e36-bdef9ce1e025.png)

[GLideN64.txt](https://github.com/gonetz/GLideN64/files/529677/GLideN64.txt)
(this is the .ini options file I renamed in .txt so that Github could upload it. I tried messing with some options but nothing worked)

I did another test with the earliest compiled master in March which was a month after this issue was apparently fixed, and the issue is still present.

**Comment by gonetz** [comment]
Looks like it never worked properly.

**Comment by gonetz** [comment]
Fixed

**Comment by lKomus** [comment]
Thanks for the quick fix! Will close the issue when I can test it.

**Comment by lKomus** [comment]
Everything is correct now, fixed!
