### ISSUE TITLE
madden nfl 2002 wrong gfx (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1178]
![dfsf](https://cloud.githubusercontent.com/assets/8987490/19419197/91f295ce-93d2-11e6-985a-09e26939925e.png)

tested with 1964 and mupen

**Comment by gonetz** [comment]
Something is wrong with emulator you are using. I can't reproduce it with mupen64plus or Project64

**Comment by gonetz** [comment]
@olivieryuyu please be sure that you run that game in HLE. I have missing polygons problems only in LLE.

**Comment by olivieryuyu** [comment]
![dsfsdf](https://cloud.githubusercontent.com/assets/8987490/19840353/e6d59362-9ef3-11e6-9b19-7aebb0e714f9.jpg)

the same, weirdly texture are mirrored sometimes.

**Comment by gonetz** [comment]
Could you find, which commit causes that regression?

**Comment by olivieryuyu** [comment]
yep will check out

**Comment by olivieryuyu** [comment]
ok so i ran with older version, then everything was fixed, even with the last version.

so i guess it is due to a shaders storage issue.

Weird, really weird

**Comment by gonetz** [comment]
> so i guess it is due to a shaders storage issue.

Most likely. I always forget to up shader storage version after shaders modifications.
