### ISSUE TITLE
Paper Mario wrong colors, CRC_OPT is the issue

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1179]
I'm not sure if this is a regression or not, but a certain enemy Paper Mario had incorrect colors. Here are screenshots:

![paper_mario-001](https://cloud.githubusercontent.com/assets/11581687/19420949/7b604c88-93c4-11e6-8f95-bf1bd545c88c.png)

![paper_mario-002](https://cloud.githubusercontent.com/assets/11581687/19420963/9b442aa6-93c4-11e6-8b38-bd5009aabe79.png)

And a save state for mupen64plus
[wrong_colors.sav.zip](https://github.com/gonetz/GLideN64/files/532113/wrong_colors.sav.zip)

And here is what it should look like with Angry lion:
![screenshot_2016-10-16-17-21-31](https://cloud.githubusercontent.com/assets/11581687/19420990/17e22a68-93c5-11e6-9a52-ab487e9f6cf9.jpg)

Check the turtles. They should all be different colors.

**Comment by fzurita** [comment]
Also, it looks like the auto crop feature is getting a little too much off.

**Comment by gonetz** [comment]
Desktop build works properly here.

**Comment by gonetz** [comment]
Try to disable optimized CRC.

**Comment by fzurita** [comment]
Ok

**Comment by fzurita** [comment]
Yep! Good instinct, disabling optimized CRC fixes this.

**Comment by gonetz** [comment]
I always suspected that CRC optimization may bring more troubles than goods.

**Comment by gonetz** [comment]
@loganmc10 May be it is the reason to remove that optimization? I think that fast asm implementation of CRC32 for ARM7 exists somewhere.

**Comment by loganmc10** [comment]
Ya you can remove it, hopefully some better method exists somewhere

**Comment by fzurita** [comment]
@gonetz Can you switch the android makefile to use the non-optimized version? I would figure that it would be silly for me to make a pull request for such a small change.

**Comment by loganmc10** [comment]
@gonetz you can probably just get rid of it altogether

**Comment by gonetz** [comment]
@fzurita @loganmc10 Ok, I'll remove it altogether.

**Comment by gonetz** [comment]
Removed
