### ISSUE TITLE
Minor Issue - Mischief Makers: Confettis in 3-10 are all black

### ISSUE THREAD

**Issue by lKomus** [gonetz/GLideN64#1181]
This issue was also present in Glide64 and many other video plugins. Only Angrylion seems to properly render them.

GLideN64
![project64_2016-10-16_20-24-48](https://cloud.githubusercontent.com/assets/4800879/19450230/e528c2a0-94a8-11e6-9d72-835cce227f95.png)
Angrylion
![project64_2016-10-16_20-26-37](https://cloud.githubusercontent.com/assets/4800879/19450232/e5e90cea-94a8-11e6-9e4a-7579f0292202.png)

**Comment by olivieryuyu** [comment]
Savestate?

**Comment by lKomus** [comment]
My bad, here it is:
[Mischief Makers (U) (V1.0).pj.zip](https://github.com/gonetz/GLideN64/files/534504/Mischief.Makers.U.V1.0.pj.zip)

**Comment by gonetz** [comment]
Could you provide savestate for older version of Project64 or for another emulator?

**Comment by lKomus** [comment]
Sorry I wasn't available until now. Here's one made with PJ64 1.6
[MISCHIEF MAKERS.pj.zip](https://github.com/gonetz/GLideN64/files/536876/MISCHIEF.MAKERS.pj.zip)
