### ISSUE TITLE
Broken camera in Majora's Mask

### ISSUE THREAD

**Issue by SigmaVirus** [gonetz/GLideN64#1185]
Seems like the camera in Majora's Mask is broken:
![majora s mask](https://cloud.githubusercontent.com/assets/14175085/19508647/a0b44bd4-95da-11e6-9845-87394909aa8b.png)

These are my settings for GLupeN64:
**glupen64-cpucore = "dynamic_recompiler"
glupen64-rspmode = "HLE"
glupen64-43screensize = "640x480"
glupen64-169screensize = "320x180"
glupen64-aspect = "4:3"
glupen64-BilinearMode = "3point"
glupen64-EnableFBEmulation = "True"
glupen64-UseNativeResolutionFactor = "0x"
glupen64-EnableCopyAuxiliaryToRDRAM = "False"
glupen64-EnableCopyColorToRDRAM = "Async"
glupen64-EnableCopyDepthToRDRAM = "FromMem"
glupen64-EnableCopyColorFromRDRAM = "False"
glupen64-EnableHWLighting = "False"
glupen64-CorrectTexrectCoords = "Off"
glupen64-EnableNativeResTexrects = "False"
glupen64-EnableLegacyBlending = "False"
glupen64-astick-deadzone = "15"
glupen64-pak1 = "none"
glupen64-pak2 = "none"
glupen64-pak3 = "none"
glupen64-pak4 = "none"**

I don't know when it got broken or what commit that broke it because it worked quite recently (a couple of weeks ago)

**Comment by gonetz** [comment]
Bug in glupen64? Desktop build works ok with these settings.
![gliden64_zelda_majora s_mask_000](https://cloud.githubusercontent.com/assets/8983092/19508999/7793e274-9606-11e6-94c9-9893f74d9825.jpg)

Or may be camera does not work only in this particular place?

**Comment by SigmaVirus** [comment]
Interesting, thanks for your fast input @gonetz 
It doesn't seem to be related to a particular place and I can reproduce it everywhere.

If it doesn't happen on standalone version of mupen64plus I'll make sure to report this issue to GLupeN64 instead.

**Comment by loganmc10** [comment]
@gonetz This is because I have NO_BLIT_BUFFER_COPY set for all platforms.

I found through some profiling that it's generally faster to just draw the full screen quad rather than using glBlitFramebuffer. Copying a framebuffer is an expensive move, especially on mobile platforms.

Anyway I'll get rid of the NO_BLIT_BUFFER_COPY for now, if you're ok with this not working with NO_BLIT_BUFFER_COPY feel free to close the issue. I have not tested this with GLES2 to see if it works there, where NO_BLIT_BUFFER_COPY is normal.

**Comment by SigmaVirus** [comment]
This is fixed so I'll close this issue now.
Thanks for all your hard work!

**Comment by loganmc10** [comment]
@gonetz Is it possible for this to work with NO_BLIT_BUFFER_COPY?

I assume the code path that is broken is:
FrameBuffer_CopyDepthBuffer()
ColorBufferToRDRAM::get().copyToRDRAM(pCopyBuffer->m_startAddress, true);
_prepareCopy(_address)
ogl.getRender().copyTexturedRect(......
