### ISSUE TITLE
Discussion: Simplified GLSL shaders

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1186]
Right now, the shaders have many if statements, for instance, here is a typical GLES3 shader that has been compiled by Mesa, so this gives you a decent idea what it looks like once all the functions and such have been unrolled (I think I count 14 if statements, some of which are not based on Uniforms, which is really bad for performance, but I believe they are necessary for alpha testing):

```
#version 300 es
uniform sampler2D uTex0;
uniform sampler2D uDepthTex;
uniform lowp vec4 uFogColor;
uniform mediump vec2 uScreenScale;
uniform lowp int uAlphaCompareMode;
uniform lowp int uAlphaDitherMode;
uniform lowp int uColorDitherMode;
uniform lowp int uFogUsage;
uniform lowp ivec2 uFbMonochrome;
uniform lowp ivec2 uFbFixedAlpha;
uniform lowp int uEnableAlphaTest;
uniform lowp int uCvgXAlpha;
uniform lowp int uAlphaCvgSel;
uniform lowp int uRenderTarget;
uniform lowp float uAlphaTestValue;
uniform mediump vec2 uDepthScale;
in lowp vec4 vShadeColor;
in mediump vec2 vTexCoord0;
out lowp vec4 fragColor;
uniform sampler2D uTexNoise;
void main ()
{
  lowp vec4 readtex0_1;
  lowp vec3 color2_2;
  lowp float alpha2_3;
  lowp float alpha1_4;
  highp float tmpvar_5;
  tmpvar_5 = clamp (((
    ((gl_FragCoord.z * 2.0) - 1.0)
   * uDepthScale.x) + uDepthScale.y), 0.0, 1.0);
  gl_FragDepth = tmpvar_5;
  lowp vec4 tmpvar_6;
  tmpvar_6 = texture (uTex0, vTexCoord0);
  readtex0_1 = tmpvar_6;
  if ((uFbMonochrome.x == 1)) {
    readtex0_1 = tmpvar_6.xxxx;
  } else {
    if ((uFbMonochrome.x == 2)) {
      readtex0_1.xyz = vec3(dot (vec3(0.2126, 0.7152, 0.0722), readtex0_1.xyz));
    };
  };
  if ((uFbFixedAlpha.x == 1)) {
    readtex0_1.w = 0.825;
  };
  alpha1_4 = readtex0_1.w;
  if ((uEnableAlphaTest != 0)) {
    lowp float alphaValue_7;
    lowp float tmpvar_8;
    if ((uAlphaCompareMode == 3)) {
      lowp float tmpvar_9;
      highp vec4 tmpvar_10;
      tmpvar_10 = texelFetch (uTexNoise, ivec2((gl_FragCoord.xy / uScreenScale)), 0);
      tmpvar_9 = tmpvar_10.x;
      tmpvar_8 = tmpvar_9;
    } else {
      tmpvar_8 = uAlphaTestValue;
    };
    alphaValue_7 = clamp (readtex0_1.w, 0.0, 1.0);
    if (((uAlphaCvgSel != 0) && (uCvgXAlpha == 0))) {
      alphaValue_7 = 0.125;
    };
    if ((alphaValue_7 < tmpvar_8)) {
      discard;
    };
  };
  alpha2_3 = alpha1_4;
  if (((uCvgXAlpha != 0) && (readtex0_1.w < 0.125))) {
    discard;
  };
  color2_2 = vec3(1.0, 1.0, 1.0);
  if ((uColorDitherMode == 2)) {
    lowp float tmpvar_11;
    highp vec4 tmpvar_12;
    tmpvar_12 = texelFetch (uTexNoise, ivec2((gl_FragCoord.xy / uScreenScale)), 0);
    tmpvar_11 = tmpvar_12.x;
    lowp vec3 _color_13;
    mediump vec3 tmpvar_14;
    tmpvar_14 = vec3((ivec3(255, 255, 255) | (
      ivec3((vec3(255.0, 255.0, 255.0) * tmpvar_11))
     & 7)));
    _color_13 = (tmpvar_14 / 255.0);
    color2_2 = _color_13;
  };
  if ((uAlphaDitherMode == 2)) {
    lowp float tmpvar_15;
    highp vec4 tmpvar_16;
    tmpvar_16 = texelFetch (uTexNoise, ivec2((gl_FragCoord.xy / uScreenScale)), 0);
    tmpvar_15 = tmpvar_16.x;
    lowp float _alpha_17;
    mediump int iAlpha_18;
    mediump float tmpAlpha_19;
    lowp float tmpvar_20;
    tmpvar_20 = (readtex0_1.w * 255.0);
    tmpAlpha_19 = tmpvar_20;
    iAlpha_18 = (int(tmpAlpha_19) | (int(
      (tmpAlpha_19 * tmpvar_15)
    ) & 7));
    _alpha_17 = (float(iAlpha_18) / 255.0);
    alpha2_3 = _alpha_17;
  };
  lowp vec4 tmpvar_21;
  tmpvar_21.xyz = color2_2;
  tmpvar_21.w = alpha2_3;
  fragColor = tmpvar_21;
  if ((uFogUsage == 1)) {
    fragColor.xyz = mix (color2_2, uFogColor.xyz, vShadeColor.w);
  };
  if ((uRenderTarget != 0)) {
    if ((uRenderTarget > 1)) {
      highp vec4 tmpvar_22;
      tmpvar_22 = texelFetch (uDepthTex, ivec2(gl_FragCoord.xy), 0);
      if ((tmpvar_5 >= tmpvar_22.x)) {
        discard;
      };
    };
    gl_FragDepth = fragColor.x;
  };
}
```

In some scenes, glUseProgram is already being run pretty much after every draw call anyway, we might as well be using a smaller shader, here is a frame from the Smash Bros opening showing the glDraw\* and glUseProgram calls

![image](https://cloud.githubusercontent.com/assets/848146/19526043/5454be08-95e0-11e6-9ef9-5125937a8393.png)

I believe getting rid of the Uniform if statements, compiling smaller shaders, and switching to them using glUseProgram will likely provide a big performance improvement, mostly on mobile devices.

I bring this up because I'm not 100% sure how to accomplish this, if someone is willing to give this a try that'd be great, or give me some kind of pointer on how to accomplish this task, I'd gladly try to test it out myself.

Admittedly this is sort of a "hunch" I have, but those are pretty complicated shaders for mobile devices to be running.

**Comment by dankcushions** [comment]
doesn't the glsl-optimizer accomplish this?

**Comment by loganmc10** [comment]
@dankcushions no, that shader I posted has been run through glsl-optimizer.

Most people say that branching on a uniform is not that bad, because the uniform will at least stay the same for all the fragments that are being processed, so the GPU driver should be able to basically "re-compile" the shader without that if statement since it knows the value will stay constant. That is the reason non-uniform if statements are bad, they destroy the GPU's ability to work in parallel as fast as it could because it doesn't know the branch it needs to take. It seems that most drivers actually execute both branches and just takes the correct result when it's done, basically doubling the work that the GPU needs to do.

But the point is that nobody really knows what the GPU will do with the shader, and mobile drivers have a tendency to suck, so ~14 if statements is a lot for it to optimize and figure out what path to take, etc...

You can Google "multiple shaders vs uniform branching" to get an idea about this problem, although most the discussion centers around Desktop GPU's, not mobile.

**Comment by loganmc10** [comment]
The real downside to having multiple smaller shaders is that you need to call glUseProgram to switch the shader, but that (and other state changes like glBindTexture) are already happening all the time anyway, because with emulation you can't order the draw calls as neaty as you probably would if you were writing a program from scratch, so I don't think it would add much of an extra cost in this case.

This is what Apple says about it:
```
Your app may perform best if you avoid branching entirely. For example, instead of creating a large shader with many conditional options, create smaller shaders specialized for specific rendering tasks. There is a tradeoff between reducing the number of branches in your shaders and increasing the number of shaders you create. Test different options and choose the fastest solution.

If your shaders must use branches, follow these recommendations:

Best performance: Branch on a constant known when the shader is compiled.
Acceptable: Branch on a uniform variable.
Potentially slow: Branch on a value computed inside the shader.
```

**Comment by loganmc10** [comment]
There are probably other optimizations that could be made, for instance it looks like this is potentially being run multiple times:

```
texelFetch (uTexNoise, ivec2((gl_FragCoord.xy / uScreenScale)), 0);
```

Certainly that is redundant right?

**Comment by gonetz** [comment]
I have thought about it.

Currently shader does not only mixes color inputs, but also takes into account various parameters of pixel pipeline. The same shader can work for all pipeline flags set. It is possible to make simpler, less general shaders, but it will make plugin's shader creation code even more complex. Also, such complex shaders, as mipmap, hardly can be simplified.

I'm not planning to start works on optimizations until new public release.

**Comment by fzurita** [comment]
I did some work on getting rid of conditionals under this issue: https://github.com/gonetz/GLideN64/issues/1045

It can definitely be done, specially if we switch from alpha testing to alpha blending.

**Comment by loganmc10** [comment]
By the way @fzurita I noticed in that issue you mentioned that switching shaders more frequently would be bad for GLES2 since there is no shader cache but I don't think that is the case. It's true that it would need to compile more shaders (although they would be smaller and simpler), but that still only happens once, it doesn't recompile the shader when you switch to it if it already exists.

**Comment by loganmc10** [comment]
By the way @fzurita I noticed in that issue you mentioned that switching shaders more frequently would be bad for GLES2 since there is no shader cache but I don't think that is the case. It's true that it would need to compile more shaders (although they would be smaller and simpler), but that still only happens once, it doesn't recompile the shader when you switch to it if it already exists.

**Comment by fzurita** [comment]
Yeah, I think you are right. I'm definitely no GLSL expert.

**Comment by loganmc10** [comment]
By the way, on the topic of optimization, another thing I thought of that *might* increase performance (and probably wouldn't be as difficult of a change as the shader thing).

Using Array Textures to store the textures in the texture cache. There are a lot of glBindTexture calls happening, and often it is just cycling through textures that have the same properties (width, height, format, etc..)
![image](https://cloud.githubusercontent.com/assets/848146/19732962/c68a4bda-9b5f-11e6-847d-05a083822c09.png)

[Array Textures](https://www.opengl.org/wiki/Array_Texture) allow you to store textures of the same type (width, height, etc..) in 1 object, so you only need 1 glBindTexture call to bind them all, then you just pass a glUniform to tell the shader which item in the array you need to use. This would potentially allow the GPU to work on drawing in larger batches.

Array Textures aren't available in GLES2 however.

**Comment by loganmc10** [comment]
After talking to some devs and doing more research, it seems that branching based on Uniforms should be essentially free, so maybe this isn't a big issue. At any rate, it would probably be a lot of work to change it around just to see if it's any better, there is probably better "low hanging fruit" in terms of optimizations, so I'll close this
