### ISSUE TITLE
Valgrind - 28131 errors from 64 contexts

### ISSUE THREAD

**Issue by orbea** [gonetz/GLideN64#1190]
OS: `Slackware64-current`
`valgrind-3.11.0-x86_64-1_SBo`
`libdrm-2016.09.22_9e24d0c_master-x86_64-1_git`
`mesa-2016.10.19_7b7eb71_master-x86_64-1_git`
`mupen64plus-2016.10.20_96b3c79-x86_64-1_git`
`GLideN64-2016.10.24_67fd477_master-x86_64-1_git`

When running mupen64plus + GLideN64 through valgrind numerous errors are reported, resolving these might lead to a better GLideN64? Granted some of these may be connected to other plugins.

This was made using Ocarina of Time, the beginning up until the Zelda logo in the opening animation.
```
==16056== HEAP SUMMARY:
==16056==     in use at exit: 564,814 bytes in 7,089 blocks
==16056==   total heap usage: 2,158,030 allocs, 2,150,941 frees, 354,160,951 bytes allocated
==16056==
==16056== LEAK SUMMARY:
==16056==    definitely lost: 5,243 bytes in 11 blocks
==16056==    indirectly lost: 216 bytes in 5 blocks
==16056==      possibly lost: 151,981 bytes in 4,782 blocks
==16056==    still reachable: 407,374 bytes in 2,291 blocks
==16056==         suppressed: 0 bytes in 0 blocks
==16056== Rerun with --leak-check=full to see details of leaked memory
==16056==
==16056== For counts of detected and suppressed errors, rerun with: -v
==16056== Use --track-origins=yes to see where uninitialised values come from
==16056== ERROR SUMMARY: 28131 errors from 64 contexts (suppressed: 0 from 0)
```
Valgrind log - http://pastebin.com/Xny2tBPF

For comparison here is a similar issue report made with RetroArch + GLupeN64.

https://github.com/loganmc10/GLupeN64/issues/86

**Comment by gonetz** [comment]
I don't see info about memleak location in the log.
valgrind gives you a hint:
Rerun with --leak-check=full to see details of leaked memory

**Comment by orbea** [comment]
With `--leak-check=full`.
```
==27079== LEAK SUMMARY:
==27079==    definitely lost: 5,243 bytes in 11 blocks
==27079==    indirectly lost: 216 bytes in 5 blocks
==27079==      possibly lost: 151,981 bytes in 4,782 blocks
==27079==    still reachable: 407,374 bytes in 2,291 blocks
==27079==         suppressed: 0 bytes in 0 blocks
==27079== Reachable blocks (those to which a pointer was found) are not shown.
==27079== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==27079==
==27079== For counts of detected and suppressed errors, rerun with: -v
==27079== Use --track-origins=yes to see where uninitialised values come from
==27079== ERROR SUMMARY: 28323 errors from 222 contexts (suppressed: 0 from 0)
```
Log - http://pastebin.com/muduh3ph

**Comment by gonetz** [comment]
As you may see, all "definitely lost" records related to code outside of GLideN64.

**Comment by orbea** [comment]
Good point, I guess this can be closed and this can be brought up elsewhere. In the event it leads back to GLideN64 this can be reopened. Thanks for the responses.
