### ISSUE TITLE
Remove GLES3_1

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1192]
There is really no reason to separate GLES 3.0 and 3.1 via ifdefs.

It would be better to check GL_MAJOR_VERSION/GL_MINOR_VERSION and use regular if statements. Perhaps I am missing something? They are both linked to the same library (-lGLESv3). That way there wouldn't need to be 2 different versions.

This is already what happens to detect image texture support on the desktop.

@fzurita any objections?

**Comment by fzurita** [comment]
No objections at all, I completely agree.

**Comment by fzurita** [comment]
The same argument can be made against NO_BLIT_BUFFER_COPY, this can be done equally well by all GLES versions, I think it should be a configuration parameter.

**Comment by loganmc10** [comment]
I'm not sure about that, it exists because GLES2 doesn't support glBindFramebuffer

I've ran into issues with NO_BLIT_BUFFER_COPY like this: https://github.com/gonetz/GLideN64/issues/1185

**Comment by fzurita** [comment]
Yes, I know that's why it exists, but NO_BLIT_BUFFER_COPY  can still be used when using GLES 3.0/3.1 to workaround buggy drivers.

**Comment by loganmc10** [comment]
Ya RetroArch has its own system for GL function loading so it's not as much of an issue for me, but there would be issues with definitions and functions only available in 3.1 that would need to be sorted out

**Comment by fzurita** [comment]
Yeah, I've been meaning to make a pull request to switch everything to EGL function loading, which is the correct way to do it. Then Android would only need 1 library for all Open GL versions.

**Comment by loganmc10** [comment]
I personally don't think it's great to have configuration options to work around driver bugs. It just makes the options confusing for most people (fragment depth writing is an example). Most projects will detect the GPU and apply fixes as needed (Dolphin Emulator is a good example of a project that does a lot of that)

**Comment by fzurita** [comment]
Yeah, you are probably right about that, but I think they just gave up on Android. There are too many driver versions each with their own individual bugs.

**Comment by loganmc10** [comment]
OK we'll I'll close this and submit a pull request later in the week potentially
