### ISSUE TITLE
ccbl test rom: incorrect colors with default parameters (HLE) with flat shaded triangle

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1194]
Select any model with default parameters: colors are incorrect with GlideN64 but fine with Angrylion and Rice.

![thumbnail_gliden64](https://cloud.githubusercontent.com/assets/8987490/19805766/928e7a32-9d16-11e6-94f8-b52cc3729f5b.jpg)

![thumbnail_angrylion](https://cloud.githubusercontent.com/assets/8987490/19805770/95520536-9d16-11e6-8a01-1a90ebb3853b.jpg)

**Comment by mudlord** [comment]
May I ask where you got those test roms? :3

**Comment by olivieryuyu** [comment]
SDK

**Comment by olivieryuyu** [comment]
it works in LLE mode. Nothing to do with a ucode issue though (ccbl is using the standard f3dex microcode)
