### ISSUE TITLE
Sim City 64 - Too much stuttering / HLE City Rendering Issue

### ISSUE THREAD

**Issue by LuigiBlood** [gonetz/GLideN64#1200]
Basically this game stutters on the main menu, and especially in the city.
To the point that angrylion is actually faster than GLideN64 when it's about rendering the city, which is quite ridiculous.

The city also has a few rendering errors.

Took the latest master build.

**Comment by LegendOfDragoon** [comment]
HLE or LLE?

**Comment by AmbientMalice** [comment]
I can confirm this. Both HLE and LLE. I'm pretty sure it's a regression because I tested the game many months ago and it seemed fine. Interestingly, the game runs full speed when you open any sort of menu. Maybe some sort of texture cache issue?

**Comment by LuigiBlood** [comment]
It never seemed that GLideN64 on LLE was really viable to me.

**Comment by LuigiBlood** [comment]
Basically a checkup: Still happens on 2.0 release.

**Comment by LuigiBlood** [comment]
I do not know what really happened but Sim City 64 seems to be faster now. Not fullspeed but definitely more playable on d8ac5a7 WIP build.

**Comment by LuigiBlood** [comment]
I just noticed what's wrong: every single 3D object is rendered at the middle of the screen. Might be a transform issue perhaps? I think just fixing this would make it much more playable.

**Comment by olivieryuyu** [comment]
@gonetz 

this game uses this special matrix command D5 (as Pokemon Snap). May be a lead...

**Comment by olivieryuyu** [comment]
@gonetz 

Can you have a look a this one? Seems HLE.

**Comment by gonetz** [comment]
Please make me a savestate to check. I don't know how to control that game.

**Comment by olivieryuyu** [comment]
[Sim City 64 (J) [CART HACK].pj.zip](https://github.com/gonetz/GLideN64/files/2922924/Sim.City.64.J.CART.HACK.pj.zip)

Please note that it is the 64dd version of the game which can be found here 64DD.org.

**Comment by gonetz** [comment]
I can't load 64dd version - it always crashes with "unknown memory action".

**Comment by LuigiBlood** [comment]
Make sure 8MB RAM is selected? You may want the updated RDB.

**Comment by olivieryuyu** [comment]
you need to use the PJ64 version of the website.

**Comment by weinerschnitzel** [comment]
I'm seeing the usual bilinear filtering issues for the faces in some message boxes at higher resolutions, but the game otherwise looks really good. Setting CounterFactor/CountPerOp to 1 will mess with the timing for cars but can play at 60 fps.

I think all the issues here are resolved.

**Comment by gonetz** [comment]
Fixed. Please test with latest WIP build from #1574

**Comment by LuigiBlood** [comment]
This is fixed and playing just fine in 60 FPS.
