### ISSUE TITLE
Paper Mario with GLES 2.0 issues

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1205]
The ground is doing fine weird things when running in GLES 2.0 mode in Paper Mario. Here is a screenshot:

![paper_mario-001](https://cloud.githubusercontent.com/assets/11581687/19957552/0d801ae2-a16e-11e6-8eca-7189ab25561d.png)

Correct with GLES 3.0:
![paper_mario-002](https://cloud.githubusercontent.com/assets/11581687/19957565/297633b2-a16e-11e6-8a78-d1b771287282.png)

**Comment by fzurita** [comment]
@gonetz is there something special about the texture that creates the artifact here?

**Comment by gonetz** [comment]
May be you can tune LOD shader for GLES2.

**Comment by fzurita** [comment]
I'll look into it. Maybe it's not that hard.

**Comment by fzurita** [comment]
I was able to get it to work by using these two extensions in a GLES 2.0 device:
```
#extension GL_EXT_shader_texture_lod : enable
#extension GL_OES_standard_derivatives : enable
```

Any modern GLES 2.0 device should have these extensions. The odd thing is that I can't get the extensions to work in GLES 3.0 devices.... Maybe I have somehow force a GLES 2.0 context.

**Comment by loganmc10** [comment]
@fzurita most devices will give you the "best" context they can, so even if you request a GLES2 context and run the GLES2 code, it will using whatever is the highest context.

It is generally the same on the Desktop, if you request 3.3 and your computer supports 4.5, you'll get a 4.5 context. You probably won't have much luck trying to force it into a lower context, there is certainly no actual GL function to do this.

In any case, you can't count on a GLES 2 device having those extensions, so the only proper way to do it would be to query for the presence of those extensions anyway before enabling that code.

**Comment by fzurita** [comment]
Yeah, the checking portion is not bad at all, if the extensions are not supported, the LOD option can be forced to off.

**Comment by fzurita** [comment]
This is funny, I can force OpenGL ES 1.0 mode but not OpenGL ES 2.0 mode.

**Comment by loganmc10** [comment]
Well the way it is supposed to work is that it is supposed to give you the highest context it can that is compatible with the context you requested. OpenGL ES 3 is completely backwards compatible with 2.0.

There was probably some stuff that changed between 1.0 and 2.0 that made 2.0/3.0 not completely backwards compatible with 1.0

**Comment by fzurita** [comment]
It's possible. I'm surprised it wouldn't support all the extensions in GLES 2.0 though, it's just a pain.

**Comment by gonetz** [comment]
Can it be closed?

**Comment by fzurita** [comment]
Yep

**Comment by gonetz** [comment]
Does it really work on GLES2 devices, e.g. with Mali 400 ?

**Comment by fzurita** [comment]
I tried an Adreno 306 device which only supported GLES 2.0 and it worked there.

**Comment by gonetz** [comment]
Good to know. Need to check it on my Note2. I did not expect that GLES2 can do this. Cool!

**Comment by fzurita** [comment]
Yep, only if the right extensions are supported.

**Comment by fzurita** [comment]
Oddly enough, when I look up the Adreno 306, it's supposed to support GLES 3.0, but the driver only says that it supports GLES 2.0.
