### ISSUE TITLE
Is CorrectTexrectCoords working

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1209]
It may have been my imagination, but with this set to auto and the Native Resolution Factor set to 2x, I wouldn't get black lines in the Super Mario Kart character select screen. Now it seems that no matter what setting I use, I can no longer get rid of the black lines.

**Comment by loganmc10** [comment]
Ya CorrectTexrectCoords does nothing for the black lines for me either.

@gonetz assuming this can get working again, would it make sense to make "Auto" the default for this setting instead of Disabled? Looking at the code it certainly won't hurt performance.

**Comment by fzurita** [comment]
I can still get rid of the black lines by using NativeResTexrects, but that really kills performance in Android.

**Comment by AmbientMalice** [comment]
Turning it on by default is a bad idea.

**Comment by loganmc10** [comment]
Well then I guess the other question is: if it doesn't work can it be removed altogether? Doesn't the Native Resolution Texrects feature solve the same problem?

**Comment by AmbientMalice** [comment]
>Well then I guess the other question is: if it doesn't work can it be removed altogether?

Are you sure it doesn't work? Test something like Mega Man 64.

**Comment by gonetz** [comment]
AmbientMalice is right: none of these options is the silver bullet.

**Comment by gonetz** [comment]
> Is CorrectTexrectCoords working

Yes, it is working when problem can be solved by simple texrect coords correction.
