### ISSUE TITLE
Excessive clipping in LoZ:OOT in GLES

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1211]
There is currently excessive clipping when weapons are being held in first person view work with GLES modes work LoZ: OOT. Here is an example:

![the_legend_of_zelda-000](https://cloud.githubusercontent.com/assets/11581687/20030052/4560e358-a333-11e6-8c0b-eb4db64f47ef.png)

Same with Glide64:
![the_legend_of_zelda-001](https://cloud.githubusercontent.com/assets/11581687/20030135/58f773bc-a335-11e6-8f89-576aedd07706.png)

**Comment by fzurita** [comment]
Seems related to this:

https://github.com/gonetz/GLideN64/issues/588

**Comment by gonetz** [comment]
Most likely it is. Desktop build works correct there. Glide64 uses software clipping, so it works correct on mobiles as well.

**Comment by fzurita** [comment]
There is some discussion about how to simulate this fictionally using the vertex shader here:

http://stackoverflow.com/questions/7408855/clipping-planes-in-opengl-es-2-0

It seems to me that using the vertex shader to adjust everything to be within the clipping planes would work.

Is the minimum vertex z position -32768 and max 32767 from the N64?

**Comment by gonetz** [comment]
No. Screen Z is in range [0, 32767]. When it is out of that range {when z/w is out of [-1, 1]), polygon is clipped.

**Comment by fzurita** [comment]
So, this could be easily fixed if these two extensions are supported:
```EXT_clip_cull_distance```
```GL_ARB_depth_clamp```

Unfortunately, most devices don't seem to support GL_ARB_depth_clamp is only supported by full OpenGL and not GLES. Although, most OpenGL ES 3.0+ devices have support for ```EXT_clip_cull_distance``` which gives access to ```GL_CLIP_DISTANCEX``` and ```gl_ClipDistance``` and ```gl_CullDistance``` in shader code. I don't think EXT_clip_cull_distance is enough to fix the problem.

**Comment by fzurita** [comment]
Hmmm.... Changing  ```glDepthRangef``` may be equivalent to enabling/disabling DEPTH_CLAMP in OpenGL ES. I'm going to investigate this.

**Comment by rcaridade145** [comment]
https://github.com/dolphin-emu/dolphin/search?utf8=%E2%9C%93&q=bSupportsDepthClamp Don't know if this can be of any help

**Comment by fzurita** [comment]
I did try to look into how dolphin does it at some point and I think that they have the same problem that we do.

**Comment by rcaridade145** [comment]
@fzurita concerning glDepthRangef https://www.reddit.com/r/gamedev/comments/2i2jvn/gldepthrangef_and_depth_clipping_on_opengl_es_2/

**Comment by fzurita** [comment]
Yeah, I did investigate  glDepthRangef. Unfortunately I don't think it can do what we need it to do. It's limited to 0.0 to 1.0. It's good for for clipping within that region but not for having clipping planes less than 0.0. We ideally need -1.0.

The best option I can think of is using the Glide64 method.

**Comment by rcaridade145** [comment]
What i've seen is for instance

```
vector4 p = OriginalProjection.MulPosition (vector3(0, 0, 450));
 
float newFar = p.z/p.w;
 
newFar = 0.5*(newFar+1.0);
 
glDepthRangef (0, newFar);
```
which tries to map -1 to 0 and all the others to that interval [0,1]

**Comment by fzurita** [comment]
Ok, I'm going to try to understand this. Maybe it can fix of problem.

**Comment by loganmc10** [comment]
@gonetz it seems like this is possible to fix via shaders

https://stackoverflow.com/questions/5960757/how-to-emulate-gl-depth-clamp-nv

Basically in the Vertex shader you do:

```
// transform z to window coordinates
    z = gl_Position.z / gl_Position.w;
    z = (gl_DepthRange.diff * z + gl_DepthRange.near + gl_DepthRange.far) * 0.5;

    // prevent z-clipping
    gl_Position.z = 0.0;
```

I assume for ```gl_Position.z = 0.0;``` you could do ``` if (gl_Position.z < 0) gl_Position.z = 0.0``` and that should leave far plane clipping enabled right?

Then in the fragment shader you do:

```
gl_FragDepth = clamp(z, 0.0, 1.0);
```

And the "z" variable is declared as ```varying float z;``` in both shaders. That should disable near plane clipping as far as I understand. I'm just not exactly sure how to put it in the shades as the correct time, like do we need a uniform that gets set when you would normally enable GL_DEPTH_CLAMP?

**Comment by fzurita** [comment]
Yeah, I saw that too but wasn't sure how to implement it:

https://stackoverflow.com/questions/5960757/how-to-emulate-gl-depth-clamp-nv

**Comment by fzurita** [comment]
Here is a save state 
[zelda 1.2 (U) swingshot.zip](https://github.com/gonetz/GLideN64/files/1799816/zelda.1.2.U.swingshot.zip)

**Comment by fzurita** [comment]
And an in-game save:

[Legend of Zelda, The - Ocarina of Time (U) (V1.2) [!].zip](https://github.com/gonetz/GLideN64/files/1799837/Legend.of.Zelda.The.-.Ocarina.of.Time.U.V1.2.zip)
