### ISSUE TITLE
HW Lighting calculation is not accurate so results are being clamped and signed extended

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1215]
Per pixel lighting seems to have broken in the last few builds. It shows in Super Mario 64 and the Legend of Zelda: OOT. The issue is much worse in LoZ: OOT.

**Comment by gonetz** [comment]
It is caused by this line
`_strShader.append("  color1 += vec3(-2.0) * (vec3(1.0) - step(color1, vec3(1.0))); \n");
`
but I can't get why. At this place there should be no difference how light was calculated, software or hardware.

**Comment by fzurita** [comment]
That's a good hint, I'll look into it.

**Comment by fzurita** [comment]
From there visual output, it almost looks like the sign extend is happening AFTER the calc_lights function, but in the code, I can clearly see that it's happening before.

**Comment by fzurita** [comment]
ok, I see. The sign extension is happening after calc_lights:
```
	if (bUseHWLight)
		strFragmentShader.append("  calc_light(vNumLights, vShadeColor.rgb, input_color); \n");
	else
		strFragmentShader.append("  input_color = vShadeColor.rgb;\n");

	strFragmentShader.append("  vec_color = vec4(input_color, vShadeColor.a); \n");
	strFragmentShader.append(strCombiner);
```

```strCombiner``` is where sign extension is done.

**Comment by fzurita** [comment]
So I see one main difference between ```calc_light``` and ```gSPLightVertex_default```. In ```calc_light``` you don't have access to ```_vtx.(nx,ny,nz)``` so instead you are using ```normalize(vShadeColor.rgb)```.

**Comment by gonetz** [comment]
You cought the wrong scent. Hw lighting works correct. It uses shadercolor.rgb because vertex color is in fact normals when lighting is used. This us how N64 lighting works. If you will remove sign-extend transformation, you will get perfect Hw lighting back. My hypothesis : since Hw lighting calculates light per pixel, it's value differs from less accurate standard method. Probably at some points result is a bit too bright, which causes result of combiner be wrapped to negative value.

**Comment by fzurita** [comment]
Interesting, Angrylion is not per pixel?

Angrylion:
![screenshot_2016-11-07-20-35-26](https://cloud.githubusercontent.com/assets/11581687/20083504/bddda37c-a52a-11e6-8453-7bd817411b84.jpg)

GLideN64 with hw lighting enabled:
![bomberman64u-000](https://cloud.githubusercontent.com/assets/11581687/20083523/de5a4e02-a52a-11e6-86bf-eda39c59453c.png)

**Comment by fzurita** [comment]
Here is a capture from a real N64: https://www.youtube.com/watch?v=mE1DaVMN6pE

**Comment by gonetz** [comment]
LLE plugins do not deal with lighting at all. RSP calculates the lighting, LLE plugin rasterises the result using Gouraud shading.

**Comment by fzurita** [comment]
Ok, I see. In the youtube video I linked with real output from the N64, the output looks a bit darker than with HW lighting. It does look more like Angrylion, but I guess that could be an artifact of how the video was captured. Look at 3:39 in the video.

**Comment by gonetz** [comment]
The larger polygon lit, the greater difference between Phong shading (hw light) and Gouraud one.

**Comment by fzurita** [comment]
Yeah, that makes sense, I'm trying to do some research on those lighting methods.

**Comment by gonetz** [comment]
I'm afraid sign-extend transformation have to be disabled in case of HW lighting, because Phong shading can get result, which programmers of combiner equation did not expect. I need to do some testings.

**Comment by fzurita** [comment]
ok.

**Comment by gonetz** [comment]
Fixed. There was a stupid bug in calc_light shader.

**Comment by fzurita** [comment]
You may want to increment the shader  storage version.

**Comment by gonetz** [comment]
Good point,  thanks.
