### ISSUE TITLE
Bomberman 64 - The Second Attack: small texture error + missing blending effects

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#122]
Just let the intro running and you get this:

![bomberman2](https://cloud.githubusercontent.com/assets/8987490/4992531/076a482c-69a2-11e4-8e89-6cd4cf55e0fe.jpg)

normally here the area where the player is should blink in red. 

![bomber642](https://cloud.githubusercontent.com/assets/8987490/4992540/2bdff292-69a2-11e4-8f3f-f008fde50ea4.jpg)

Correct with Glide64 (if i remember correctly it is a blender issue)

![glide64 correct](https://cloud.githubusercontent.com/assets/8987490/4992549/61466d58-69a2-11e4-8ba2-c1852293a0d6.jpg)

**Comment by gonetz** [comment]
Fixed texture loading problem.
Implemented special blending mode for flashing map area.
Fixed flickering on map screen with FB enabled.

**Comment by olivieryuyu** [comment]
fixed :)
