### ISSUE TITLE
HW Lighting doesn't work in GLES 2.0

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1224]
For some reason HW lighting is not working in GLES 2.0. I'm not sure when it broke.

**Comment by gonetz** [comment]
Is not it fixed with 8a92860271 ?

**Comment by fzurita** [comment]
No. The problem seems to have been around before the lod implementation in GLES 2.0.

**Comment by fzurita** [comment]
It works now. 866fe9f7e9c08c7040f423534130e7a746a30027 probably fixed it.
