### ISSUE TITLE
Many games look blurry

### ISSUE THREAD

**Issue by Mario54321** [gonetz/GLideN64#1225]
Use the GLideN64 GUI build from November 6 https://drive.google.com/file/d/0B0YqMPjGo3B2TGpsenpZeTVsWUU/view?usp=sharing with either Project64 or Mupen64Plus. Set the windowed resolution either to 320 x 240 or 640 x 480. Also, make sure you're using the monitor's native resolution. As an example play Super Mario 64 (U) or Paper Mario (U). Notice how parts of the games look blurry. It is more noticeable with text and when the windowed resolution is 320 x 240. However, if "Emulate frame buffer" is unchecked in the GLiden64 GUI then this problem appears to go away. Another thing is the GLideN64 build from August 28 https://drive.google.com/file/d/0B0YqMPjGo3B2elZELVRqT1FIMHM/view?usp=sharing doesn't seem to have this problem.

August 28 build 320 x 240

![gliden64 august 28 paper mario 320 x 240](https://cloud.githubusercontent.com/assets/23304422/20164992/73003d34-a6d7-11e6-8ae5-044953282f98.png)

August 28 build 320 x 240

![gliden64 august 28 sm64 320 x 240 2](https://cloud.githubusercontent.com/assets/23304422/20165000/7bf1ca02-a6d7-11e6-826c-d802ef01dd34.png)

August 28 build 320 x 240

![gliden64 august 28 sm64 320 x 240](https://cloud.githubusercontent.com/assets/23304422/20165002/80cd3ade-a6d7-11e6-8a9a-493f284af157.png)

August 28 build 640 x 480

![gliden64 august 28 sm64 640 x 480](https://cloud.githubusercontent.com/assets/23304422/20165006/85895044-a6d7-11e6-84e2-576a091bd639.png)

November 6 build 320 x 240

![gliden64 gui november 6 paper mario 320 x 240](https://cloud.githubusercontent.com/assets/23304422/20165068/0d7270f8-a6d8-11e6-9f6b-ce484179f8c8.PNG)

November 6 build 320 x 240

![gliden64 gui november 6 sm64 320 x 240 2](https://cloud.githubusercontent.com/assets/23304422/20165073/13f26096-a6d8-11e6-937f-fe19dfd7ef59.PNG)

November 6 build 320 x 240

![gliden64 gui november 6 sm64 320 x 240](https://cloud.githubusercontent.com/assets/23304422/20165074/171abc28-a6d8-11e6-9db9-d00172d35f2f.PNG)

November 6 build 640 x 480

![gliden64 gui november 6 sm64 640 x 480](https://cloud.githubusercontent.com/assets/23304422/20165075/1dd3b5b0-a6d8-11e6-82ca-06bfe607ba20.PNG)

**Comment by AmbientMalice** [comment]
You need to post what settings you're using.

**Comment by Mario54321** [comment]
Here are the settings

![video](https://cloud.githubusercontent.com/assets/23304422/20166905/ddd845a8-a6e5-11e6-93b5-150afc5eaca5.png)

![emulation](https://cloud.githubusercontent.com/assets/23304422/20166917/e9535468-a6e5-11e6-9391-5acc92e23d43.png)

![frame buffer](https://cloud.githubusercontent.com/assets/23304422/20166920/ee88f726-a6e5-11e6-86c1-f611743326e0.png)

![texture enhancement](https://cloud.githubusercontent.com/assets/23304422/20166925/f88f7678-a6e5-11e6-9b1a-88ed4a99ee83.png)

![texture enhancement 2](https://cloud.githubusercontent.com/assets/23304422/20166929/fd306f5c-a6e5-11e6-834b-884a9c7ca0a8.png)

![filters](https://cloud.githubusercontent.com/assets/23304422/20166934/065b65be-a6e6-11e6-9ad0-d7918eed59ea.png)

![osd](https://cloud.githubusercontent.com/assets/23304422/20166938/0b096c5a-a6e6-11e6-91cb-9f55ed9383d8.png)

**Comment by Nes-player4Life** [comment]
Enable noise/Turn it off. Set your resolution higher 320x240 is tiny. Try 640, Or 1280x

**Comment by AmbientMalice** [comment]
I wonder whether this might simply be the VI emulation scaling the image to a proper N64 size with borders introducing a slight blurring.

**Comment by gonetz** [comment]
I described the problem in #1246
This one has to many irrelevant information, so I close it.
