### ISSUE TITLE
Nushi Zuri 64 - Shiokaze ni Notte: wrong gfx (gSPSetStatus)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1230]
Incorrect gfx in game for this game, certainly due to the missing implementation of gSPSetStatus (http://level42.ca/projects/ultra64/Documentation/man-v5-1/n64man/gsp/gSPSetStatus.html)

In S2DEX, G_MW_GENSTAT replace G_MW_FOG in F3DEX. gSPSetStatus has an impact a texture loading.

![sans titre](https://cloud.githubusercontent.com/assets/8987490/20238275/bd85cd94-a8e7-11e6-8442-07613a4b6173.png)

**Comment by gonetz** [comment]
Fixed! Thanks olivieryuyu for the discovery.
Actually, three commands were not implemented: gSPSetStatus, gSPSelectDL, gSPSelectBranchDL
They all used by this game.

**Comment by AmbientMalice** [comment]
I wonder if those commands were used in anything else. Good work, @Gonetz, and good work, @olivieryuyu. You've been contributing a lot in terms of documenting missing and faulty ucode stuff.

**Comment by gonetz** [comment]
Nushi Tsuri 64 (J) does not use them. May be some another Japanese 2D title use them. Anyway, it was pleasure to remove "unimplemented" warning :)

**Comment by olivieryuyu** [comment]
wonderful!!!!
