### ISSUE TITLE
G_TEXTURE_GEN doesn't work correctly (HLE)!

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1232]
The result of G_TEXTURE_GEN does not work properly in HLE.

Here a very simple test under ccbl to prove it.

Set those parameters

![1](https://cloud.githubusercontent.com/assets/8987490/20249778/f1349732-aa00-11e6-9667-b5e480a252f5.jpg)

![22](https://cloud.githubusercontent.com/assets/8987490/20249797/4a49565a-aa01-11e6-879c-2c35ade8730b.jpg)

Select ModuleI (other options show you the same bug, it is quite a general one)

![23](https://cloud.githubusercontent.com/assets/8987490/20249798/4e980f30-aa01-11e6-9367-e22a70d66fb1.jpg)

Result is the one in HLE:

![hle](https://cloud.githubusercontent.com/assets/8987490/20249812/9c4978fe-aa01-11e6-8cc0-22d327969b63.jpg)

It is wrong (tree should not be in this direction)

In LLE it is like this.

Seems the texture coordinates is not fine in HLE.

![3](https://cloud.githubusercontent.com/assets/8987490/20249814/aff8e542-aa01-11e6-9bf1-0e6e2c30f208.jpg)

I double checked on real N64 with my everdrive, LLE is correct.

The only plugin correct is Jabo. It is also the only plugin correct with Chopper Attack issue #99

**Comment by gonetz** [comment]
It does not work because this test rom does not set LookAt structure. Plugin incorrectly set default LookAt state. Fixed
