### ISSUE TITLE
fogworld demo: wireframe does not work (line3d issue in HLE)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1242]
GlideN64

![line3dnotworking](https://cloud.githubusercontent.com/assets/8987490/20456126/3e2a1dfc-ae6e-11e6-8dbf-d7cbe6f36709.jpg)

Angrylion

![angrylion](https://cloud.githubusercontent.com/assets/8987490/20456127/468e3d20-ae6e-11e6-84c4-5e03246ccd0c.jpg)

savestate and test rom

[a tester.zip](https://github.com/gonetz/GLideN64/files/601496/a.tester.zip)

**Comment by olivieryuyu** [comment]
it seems plugin cannot detect L3DEX 2.08 xbus

**Comment by olivieryuyu** [comment]
as per some docs about this demo:

New feature of Line Microcode:

Now when a regular triangle display list (which would ordinarily be used with the gspFast3D microcode) is sent to the gspLine3D microcode, the triangles are drawn as lines.  Each gSP1Triangle command causes the 3 edges of the triangle to be drawn. Notice	that this is very inefficient since triangle commands describing adjacent triangles will both cause the common edge of the triangle to be drawn.  This new gSP1Triangle feature of the line microcode is demonstrated in the new demo fogworld.  Run fogworld, go to the view menu, andselect Wireframe to see it work.

**Comment by gonetz** [comment]
Does it work now?

**Comment by olivieryuyu** [comment]
No

Would you like to get it fixed? This feature is not used in any game apparently.

**Comment by gonetz** [comment]
If it is not used, no.
