### ISSUE TITLE
(request) Use GetUserDataPath() to determine path when creating gliden64.log

### ISSUE THREAD

**Issue by orbea** [gonetz/GLideN64#1243]
As explained in issue https://github.com/GLupeN64/GLupeN64/issues/110 can GLideN64 use `GetUserDataPath()` to determine the path when creating gliden64.log? It would help keeping the file in a consistent place for glupen64 as well distinct from the upstream gliden64.log. This is only a small request / suggestion. :)

**Comment by gonetz** [comment]
Done: 1c94b4720eb

**Comment by orbea** [comment]
Thank you!
