### ISSUE TITLE
Last column problem.

### ISSUE THREAD

**Issue by gonetz** [gonetz/GLideN64#1246]
Mario54321 noticed in #1225 that many games started to look blurry. This issue is not as simple as it looks and it worth to discuss.

Blurry image caused by this commit: "Do not show rightmost pixels in frame buffer when AA and divots elimination enabled in VI.", 4c226bcc95

Problem description: "Some games have strange glitch, which looks like vertical line of pixels outside of right bound of the image. Examples: JFG title screen, both Zelda games when new game started. Software plugin has the same issue, but when image passes VI stage, the problem disappears. Most likely VI filters somehow eat the rightmost pixels. I suspect that it is result of divots elimination. Thus, the fix works like this: when divot flag is set the rightmost column of pixels is not shown."

Screenshots made with GLideN64 to illustrate the problem (Zelda OOT):
![wrong_column](https://cloud.githubusercontent.com/assets/8983092/20471651/2088e3e0-afe6-11e6-9dae-c1155880e14c.png)

Wrong column of pixels outlined by red. Wrong pixels belong to background picture. That picture is covered by black opaque fillrect, except for the rightmost column.
You may compare it with screen shot from angrylion's software lle plugin, with DAC filters disabled:

![czle0000](https://cloud.githubusercontent.com/assets/8983092/20471805/330ccb3e-afe7-11e6-892f-c55a0bd0cd32.png)

magnify the image and you will see the same problem.

So, rightmost column of pixels must not be displayed. Now the problem: how to display the frame buffer? Suppose for simplification, that we use native resolution.

Current solution:
We have 320x240 buffer which have to be mapped to 320x240 window. Rightmost column must be discarded. Video Interface takes 319x240 area of frame buffer and stretches it to 320x240 area in the window.

Original not stretched buffer:
![noblur](https://cloud.githubusercontent.com/assets/8983092/20472282/07cec77a-afeb-11e6-9f4f-90d001f8d9ba.png)

319x240 stretched it to 320x240
![blur](https://cloud.githubusercontent.com/assets/8983092/20472304/3791c71e-afeb-11e6-8d9c-a10a465a1a77.png)

The problem is clearly visible. How to fix it? I don't know.

I can't increase frame buffer size to 321x240 and cut the last column - it will cause too many other glitches. 

I can reduce output area to 319x240. It will fix blur, but we will get one pixel width black border on the right (or on the left, if you prefer).

Thoughts?

**Comment by AmbientMalice** [comment]
I reckon you should just add a black pixel border. It's generally preferable to blurring.

**Comment by gonetz** [comment]
Add a black pixel border.
Ok. Who has another opinion?

**Comment by oddMLan** [comment]
Black pixel border would be the easiest solution... but
How hard is it to implement the N64 Divot filtering in GPU shaders? How translatable is AL's code to work with it?

**Comment by Aquatakat** [comment]
Keeping in mind that all images in original N64 hardware are scaled to 480, I'm alright with some blurriness for accuracy.

**Comment by Mario54321** [comment]
Though for users with low resolution monitors this can be very annoying to see when playing. Also some don't care about accurate N64 video output. They just want want to have a clear image.

**Comment by Aquatakat** [comment]
How many users nowadays have monitors lower than at least 720p?

**Comment by loganmc10** [comment]
Most Raspberry Pi users play with the screen resolution set to 640x480

**Comment by Mario54321** [comment]
According to http://gs.statcounter.com/#mobile_resolution-ww-monthly-201610-201610-bar 360 x 640 is the most common resolution for mobile users.

**Comment by oddMLan** [comment]
I would rather have the crispest image possible at the cost of 4 pixels of black border at higher resolution, than a blurred image. Give me them pixels.
Then again... wouldn't the cropping option be specially useful here? One could slightly zoom the image if the black border bothered them. You can't get rid of the blurriness as easily though.
Black pixel columns would be the lesser of two evils.

Then again, if DAC filters were implemented in shaders, they would fix some issues like #769
However, I do not know if it's possible to emulate them in plain OGL GPU shaders

**Comment by gonetz** [comment]
N64 DAC filters have no sense for 32 bit msaa GL color buffer.  Forget about it.
Crop can't  help to remove black boarder, created by Video Interface.
I see only two alternatives: 319x240 => 320x240 with blurring or 319x240 => 319x240 with black boarder.

**Comment by Aquatakat** [comment]
Maybe the solution here is to implement both and offer a GUI option, with the default being to use the black border.

**Comment by gonetz** [comment]
b32d8020b

**Comment by olivieryuyu** [comment]
The line is in the middle of the screen, not in last column for some games.
