### ISSUE TITLE
Can't save game specific settings

### ISSUE THREAD

**Issue by Tasosgemah** [gonetz/GLideN64#1248]
I'm using the option to save game specific settings but each time i load a rom and change some settings, these settings remain changed globally.

For instance, i want to use custom crop values for Wave Race. I load Wave Race and put a custom crop value. But then when i load any other game, those values are still there. If i disable them, they are also disabled when i load wave race.

I know there is a GLideN64.custom.ini file but that doesn't add any values automatically. The only way is to manually open it with notepad and fiddle with it but i never managed to make any setting work. I tried adding Wave Race in there and put these values:

cropMode=2
cropWidth=8
cropHeight=4

But no luck. I used the Rom names like [WAVE RACE 64] (that's the actual Rom name according to rom info) or [WAVE%20RACE%2064] (that's how other games handle spaces in the ini it seems) but still no luck.

Is there a way to make custom setting work?

**Edit:** Many Custom Settings seem to not work for any game it seems. There's already an entry for Extreem-G so i add this line:

enableNativeResTexrects=0

That's because there are some depth issues in this game if the option is enabled (i want it enabled globally). But despite adding this line, the game ignores it and still think it as "1" or enabled. So i have to disable it globally to fix just one game...

**Comment by Tasosgemah** [comment]
Ok, i figured out how to manually add values correctly.

I had to add these lines: generalEmulation\enableNativeResTexrects=0

instead of just this: enableNativeResTexrects=0

Same with Wave Race, i had to add this:

video\cropMode=2
video\cropWidth=8
video\cropHeight=4

Instead of this:

cropMode=2
cropWidth=8
cropHeight=4

That's how you do it manually. Is there any way to do this from the GlideN64 GUI, automatically, without having to do it using the Notepad? Thanks and sorry for the false alarm.

**Comment by gonetz** [comment]
You can't save settings in custom in with GUI. It is not implemented.

**Comment by gonetz** [comment]
Implemented now in Project64 build.
Enable  "Use per game settings" option, run game, open config dialog, change settings. Changes will be saved as custom settings for the running game.
