### ISSUE TITLE
Blast Corps: shadows doesn't work (even with fb on)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#125]
Missing/wrong shadows:

![blast corps shadows](https://cloud.githubusercontent.com/assets/8987490/4995141/07dc2c18-69bf-11e4-86ac-d11d15b5e20b.jpg)

**Comment by olivieryuyu** [comment]
shadows works only with red truck but not on the yellow one?

still some kind of flickering

**Comment by gonetz** [comment]
Fixed

**Comment by Predator82Germany** [comment]
LGTM
Oli should test

**Comment by olivieryuyu** [comment]
Fixed
