### ISSUE TITLE
[Project64] Banjo-Tooie Groggy Crash

### ISSUE THREAD

**Issue by vgf89** [gonetz/GLideN64#1250]
It seems my issue is identical to this guy's: https://github.com/gonetz/GLideN64/issues/968, except that I'm using Project 64 2.3. I've tested with the 1.2 public release of GLideN64 and the latest WIP build from https://github.com/gonetz/GLideN64/issues/885.

This crash happens regardless of recompiler or interpreter setting in PJ64. This crash doesn't happen with Glide64.

EDIT: I've attached the save state. Just walk forward and behold the crash
[Banjo-Tooie (U).pj.zip](https://github.com/gonetz/GLideN64/files/604945/Banjo-Tooie.U.pj.zip)

**Comment by Frank-74** [comment]
Using latest Project64 github master, and latest GLideN64 WIP.  I've loaded that save state 5 times and gone into the next area with no crash.

I renamed the save to "Banjo-Tooie (U).pj.zip", the link adds a "." after Tooie instead of a space.

**Comment by gonetz** [comment]
Be sure that you don't have any cheats enabled.

**Comment by olivieryuyu** [comment]
can it be closed?

I have zero issue as well.

**Comment by gonetz** [comment]
Yes, we added a workaround for this issue.
