### ISSUE TITLE
roadster trophy: no more wheels!!!! (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1258]
![sans titre](https://cloud.githubusercontent.com/assets/8987490/20635521/46805a58-b35e-11e6-901b-eba35fa93464.jpg)

**Comment by gonetz** [comment]
Another crazy trick from N64 programmers..

**Comment by oddMLan** [comment]
Why did it work before without a hack?

**Comment by gonetz** [comment]
I'm not sure when it was broken. Likely, after software depth buffer was added, which makes impossible to check buffer validity by RDRAM content. Also, other changes could differ check result for this particular game. As I said, that situation is non-standard and standard methods do not work there.
