### ISSUE TITLE
Work properly with apitrace.

### ISSUE THREAD

**Issue by orbea** [gonetz/GLideN64#1265]
OS: `Slackware64-current`
`apitrace-7.1-x86_64-2_SBo`
`mesa-2016.11.25_af98c6c_master-x86_64-1_git`
`mupen64plus-2016.11.27_3ca2c4a-x86_64-1_git`
`GLideN64-2016.11.28_a3760c9_master-x86_64-1_git`

When tracing GLideN64 with apitrace I get unsupported warnings. It would be really great if these could be avoided for the benefit of apitrace. It will help debugging both GLideN64 and GlupeN64. One idea would avoid it only for debug builds. GLupeN64 had an similar issue which was resolved like that as documented in issue https://github.com/GLupeN64/GLupeN64/issues/88.

When tracing the nintendo logo in Ocarina of Time here are the warnings.
```
apitrace: warning: glVertexAttribPointer: call will be faked due to pointer to user memory (https://github.com/apitrace/apitrace/blob/master/docs/BUGS.markdown#tracing)
apitrace: warning: glMapBufferRange: MAP_PERSISTENT_BIT w/o FLUSH_EXPLICIT_BIT unsupported (https://github.com/apitrace/apitrace/issues/232)
apitrace: warning: glMapBufferRange: MAP_PERSISTENT_BIT w/o FLUSH_EXPLICIT_BIT unsupported (https://github.com/apitrace/apitrace/issues/232)
```
@loganmc10 Indicated this commit as being related. https://github.com/gonetz/GLideN64/commit/313741d8276f0e018ba0c137892d67794468cc28

**Comment by loganmc10** [comment]
Now that I read the documentation, this might be some kind of a bug with apitrace. The documentation for glMapBufferRange (https://www.khronos.org/opengles/sdk/docs/man3/html/glMapBufferRange.xhtml) says:

> GL_MAP_FLUSH_EXPLICIT_BIT... This flag may only be used in conjunction with GL_MAP_WRITE_BIT.

This is using GL_MAP_READ_BIT, so apitrace is kind of asking for the impossible, for what it's worth, besides the warning, everything seems to work fine, the apitrace replays show up and whatnot, it might be something to bring up with apitrace.

**Comment by orbea** [comment]
I asked in #apitrace and got this.
```
09:22 <siro__> apitrace is pretty clear here, it simply can't trace memory mapped persistant
09:22 <siro__> only the corner case where glFlushMappedBufferRange is called is working
```

**Comment by loganmc10** [comment]
I guess I would disagree about the "pretty clear" part, but either way, since there is no way to use FLUSH_EXPLICIT_BIT with GL_MAP_READ_BIT, there is no "work around" to this issue.

apitrace could change the message to something like "MAP_PERSISTENT_BIT unsupported with GL_MAP_READ_BIT".

The apitrace still seems to work though, just that warning message appears.

**Comment by orbea** [comment]
`apitrace-2016.12.09_849af149_master-x86_64-1_git`
`GLideN64-2016.12.15_107b646_master-x86_64-1_git`

With a git version of apitrace the only warning is.
`apitrace: warning: glVertexAttribPointer: call will be faked due to pointer to user memory (https://github.com/apitrace/apitrace/blob/master/docs/BUGS.markdown#tracing)`

@gonetz As this does not cause any known problems I will close this.
