### ISSUE TITLE
Black screen in Wave Race 64 with a DEBUG build

### ISSUE THREAD

**Issue by orbea** [gonetz/GLideN64#1266]
OS: `Slackware64-current`
`mesa-2016.11.25_af98c6c_master-x86_64-1_git`
`mupen64plus-2016.11.27_3ca2c4a-x86_64-1_git`
`GLideN64-2016.11.28_a3760c9_master-x86_64-1_git`

When testing Wave Race 64 with a debug build of GLideN64 it will black screen during the nintendo logo, but will work correctly in the intro sequence. Without a debug build the logo will blink once, but this may be a different issue.

This occurs with both nouveau and the llvmpipe, but it does not occur with glide64 so it seems to be a GLideN64 issue. It also occurs in GLupeN64 as discovered in issue https://github.com/GLupeN64/GLupeN64/issues/122.

apitrace - http://ks392457.kimsufi.com/orbea/stuff/trace/gliden64_waverace_debug.trace.xz
apitrace log - http://pastebin.com/DCvVNNDs

**Comment by gonetz** [comment]
Is it still actual?

**Comment by loganmc10** [comment]
I just tested a debug and release build in Linux and I can't reproduce it, the N64 logo shows up properly in both instances.

**Comment by gonetz** [comment]
Thanks!
