### ISSUE TITLE
Kirby 64 LLE missing effects

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1267]
With HLE you can see "stuff" going into Kirby's mouth, with LLE you just see the wind.

I believe there are other effects like the fire sword that don't look right in LLE

HLE:
![screenshot at 2016-11-28 10_16_54](https://cloud.githubusercontent.com/assets/848146/20680527/a68d88bc-b55c-11e6-97c5-85940312022e.png)

LLE:
![screenshot at 2016-11-28 10_18_26](https://cloud.githubusercontent.com/assets/848146/20680533/a8a97250-b55c-11e6-98cb-05966b6f015e.png)

**Comment by AmbientMalice** [comment]
This is likely the same issue as missing 2D elements in Indiana Jones and Duke 64 and stuff like that.

**Comment by karashata** [comment]
The effects aren't missing entirely, actually. They're just rendered behind pretty much everything but the background.

![untitled](https://cloud.githubusercontent.com/assets/4993762/21474131/246a314e-cae9-11e6-9134-9017ab738e80.png)

**Comment by loganmc10** [comment]
Going to close, given that the game works in HLE, there is no real need to solve this problem

**Comment by AmbientMalice** [comment]
>Going to close, given that the game works in HLE, there is no real need to solve this problem

The LLE depth issue affects a wide range of games.

**Comment by loganmc10** [comment]
Probably true, but a game that actually needs LLE should be used as the test case

**Comment by weinerschnitzel** [comment]
I think it is worthwhile to note any discrepancy between HLE and LLE. Some cases may be better to test than others, but i think all should be tracked.

Please keep open!

**Comment by loganmc10** [comment]
I don't think GLideN64's goal was ever to be a fully accurate LLE plugin (I could be putting words into gonetz's mouth I suppose).

Who is honestly going to work on this problem? There are literally only a handful of games that need LLE, I can list them off: World Driver Champ, Stunt Racer, Indiana Jones, Rogue Squadron, Battle for Naboo.

I think there is a higher chance of the microcode for those games getting implemented than there is that these LLE problems are sorted out. Probably for the better anyway, since a proper HLE implementation will provide much better performance.

**Comment by LegendOfDragoon** [comment]
>I think there is a higher chance of the microcode for those games getting implemented than there is that these LLE problems are sorted out.

Well I wouldn't count on HLE working before LLE. If LLE doesn't work properly for games like Indiana Jones, how will HLE work?

**Comment by loganmc10** [comment]
> Well I wouldn't count on HLE working before LLE. If LLE doesn't work properly for games like Indiana Jones, how will HLE work?

What? Look at this game (Kirby), it works better in HLE than LLE. Indiana Jones works in LLE, just like World Driver or Rogue Squadron does, it's just that GLideN64 has some inaccuracies specifically tied to LLE.

Look at Resident Evil 2, it works much better in HLE than LLE

**Comment by LegendOfDragoon** [comment]
> Look at this game (Kirby), it works better in HLE than LLE.

Iirc, those games use documented ucodes. I believe there's more likely to be a problem when you have to reverse engineer a ucode that has graphical issues in LLE. Although it is possible that HLE won't be affected, I just wouldn't count on that.

**Comment by gonetz** [comment]
Implementation of LLE triangle command is far from perfect. Z value sometimes decoded incorrectly, so depth compare issues. Nobody wants to take that task and write well working implementation. Everything is documented,  it is just necessary to understand and carefully implement.

**Comment by purplemarshmallow** [comment]
Is this really a problem with the lle triangle command? The implementation was taken from z64gl and these depth issues don't appear with z64gl

**Comment by gonetz** [comment]
The implementation could be taken with errors.
