### ISSUE TITLE
San Francisco Rush 2049 - Black screen with framebuffer emulation

### ISSUE THREAD

**Issue by orbea** [gonetz/GLideN64#1271]
OS: `Slackware64-current`
`mupen64plus-2016.11.27_3ca2c4a-x86_64-1_git`
`GLideN64-2016.11.29_91f0158_master-x86_64-1_git`

When starting  San Francisco Rush 2049 it will black screen / freeze with a bar of garbage displayed at the top of the screen. It will work if framebuffer emulation is disabled. Additionally it will work with glide64 and it has been reported to work with project64 + GLideN64.

This appears to be a regression after reading issue https://github.com/gonetz/GLideN64/issues/387, but I have not been able to start older commits where it may have worked... It also occurs with GLupeN64 as reported in issue https://github.com/GLupeN64/GLupeN64/issues/126.

Apitrace - http://ks392457.kimsufi.com/orbea/stuff/trace/gliden64-sanfranrush2049.trace.xz
Apitrace log - http://pastebin.com/UY2QPhXy

![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/mupen64plus/2016-11-29-093016_1680x1050_scrot.png)

**Comment by orbea** [comment]
It will also work with `EnableCopyColorToRDRAM = 0`.

**Comment by loganmc10** [comment]
This actually was an issue with GLupeN64, I was converting the rom name to all uppercase, so the string comparison in GLideN64.custom.ini was failing. mupen64plus doesn't read GLideN64.custom.ini so it's up to the user to figure out the right settings there.

**Comment by orbea** [comment]
Perhaps an issue should be made for mupen64plus to use GLideN64.custom.ini if available?

**Comment by loganmc10** [comment]
ya that would be a good idea, right now there is no system for mupen64plus to read the GLideN64.custom.ini file, I believe this would need to be implemented in GLideN64 though, not mupen64plus

**Comment by gonetz** [comment]
> I believe this would need to be implemented in GLideN64 though, not mupen64plus

I don't want to have another ini file loader and parser in plugin's code.

**Comment by orbea** [comment]
If you think its better to bring this up with the mupen64plus devs? I can do that.

**Comment by Frank-74** [comment]
I thought the plugin already had an ini file parser?  Couldn't the existing one be modified to use the custom ini if the option to use custom settings is checked?

**Comment by loganmc10** [comment]
Reading GLideN64.custom.ini is only supported by Project 64 (https://github.com/gonetz/GLideN64/blob/master/src/GLideNUI/Settings.cpp), it requires Qt.

It probably could be re-written to be a little more cross-platform. I believe @fzurita integrates GLideN64.custom.ini into mupen64plus-ae, I haven't looked at exactly how that works, and I wrote a "quick and dirty" ini parser for GLupeN64:
https://github.com/GLupeN64/GLupeN64/blob/master/custom/GLideN64/mupenplus/Config_mupenplus.cpp#L19-L71

**Comment by fzurita** [comment]
What I do is convert the file to the same format that our existing INI parsers can handle in mupen64plus-ae. Once it's converted, if the current profile is a built in profile, I will override the setting based on my custom GLideN64.custom.ini .

Here is my version of the file:
https://github.com/mupen64plus-ae/mupen64plus-ae/blob/master/app/src/main/assets/mupen64plus_data/GLideN64.custom.ini

GLideN64 could use its existing INI parser and my version of the file to override the normal settings.

**Comment by AmbientMalice** [comment]
Why does the game freeze with framebuffer emulation, anyway?

**Comment by gonetz** [comment]
> If you think its better to bring this up with the mupen64plus devs?

IMO, it would be best to get custom ini support from mupen64plus side. mupen64plus great advantage is that it takes all OS specific and routine tasks on itself. Custom ini functionality cold be used not only by GLideN64.

**Comment by gonetz** [comment]
> Why does the game freeze with framebuffer emulation, anyway?

Hmm, right question.

**Comment by orbea** [comment]
I made an issue for mupen64plus, but I will leave this issue open too since the black screen / freeze indicates a deeper problem.

**Comment by orbea** [comment]
@gonetz As seen in the mupen64plus core issue implementing this correctly may not be easy unless someone with the correct skill set volunteers.  As my programing ability is limited, I leave this up to you and the others how to best solve this...

**Comment by gonetz** [comment]
>  I leave this up to you and the others how to best solve this.

Are we talking about custom ini support in mupen64plus, or about issue with San Francisco Rush 2049?

**Comment by orbea** [comment]
I meant the custom ini support there, it seems like something that should be solved, but as where it should be solved and how is another question...

**Comment by gonetz** [comment]
I see no issues in plugin's code.
Currently, the only solution is to disable color buffer copy for this game.

**Comment by AmbientMalice** [comment]
Can anyone confirm whether this is fixed? San Francisco Rush seems to work fine with framebuffer enabled in PJ64 now. Maybe VI refactor fixed the underlying issue?

**Comment by loganmc10** [comment]
Huh yeah I just tried it with mupen64plus and it does seem to be fixed now. The line for it in GLideN64.custom.ini can probably be removed now.

**Comment by AmbientMalice** [comment]
Accuracy improvements for the win!

**Comment by gonetz** [comment]
Good. Closed.

**Comment by loganmc10** [comment]
Well GLideN64.custom.ini should be updated and the entry for this game removed

**Comment by orbea** [comment]
Thanks for closing this, but I can't test it. GLideN64 no longer starts for me and I'm honestly not inclined to find out why anymore...
