### ISSUE TITLE
Dynamic code adaptability to GL versions.

### ISSUE THREAD

**Issue by gonetz** [gonetz/GLideN64#1276]
GLideN64 currently supports the following graphics API:  OpenGL, GLES2, GLES3, GLES3.1
OpenGL support also divided on GL 3.3 and GL 4.3+
It causes the following problems:
* The code contains lots of GL version - specific code, separated by #ifdef (or if() for OpenGL versions)
* Android emulator distributes 4 GLideN64 binaries for each supported CPU family. (see https://github.com/gonetz/GLideN64/pull/1249)

My primary concern is variety of version specific code. I made lots of efforts to keep all specific stuff in separate files, but it still plagues parts of code, which intended to be general for all GL versions.
Now I want to try to create a proxy class, which will separate algorithms in code from concrete graphics functions and hide all details about their initialization and use. I (think that I) know how to do it on desktop, but I don't have good understanding of the situation on mobile platforms. I want to clarify the following:
* Is it possible to get all necessary functions, provided by GLES_X version and defined in  <GLESX/glx.h> via EGL mechanism? For example, if I found that GL version is GLES2.0, can I get all functions from gl2.h via eglGetProcAddress? 
* Is EGL/egl.h available for all supported Android devices?

This also related to number of GLideN64 build for Android. If we can load everything via eglGetProcAddress, can we provide only one version of GLideN64, which will ask for necessary GL context via 
```
	CoreVideo_GL_SetAttribute(M64P_GL_CONTEXT_MAJOR_VERSION, _);
	CoreVideo_GL_SetAttribute(M64P_GL_CONTEXT_MINOR_VERSION, _);

```
?

**Comment by fzurita** [comment]
> Is it possible to get all necessary functions, provided by GLES_X version and defined in <GLESX/glx.h> via EGL mechanism? For example, if I found that GL version is GLES2.0, can I get all functions from gl2.h via eglGetProcAddress?

Yes. In fact, the gl31.h header file is backwards compatible with gl3.h and g2.h. All functions can be loaded using eglGetProcAddress. If we try to retrieve a gles 3.1 function in a device that has an older gl version, we won't get a valid function.

> Is EGL/egl.h available for all supported Android devices?
Yes, EGL is standard in Android starting in API level 9. Mupen64Plus AE currently has a required API level of 15.

**Comment by fzurita** [comment]
Here is where it says that gles 2, 3, 3.1, and 3.2 can share header files:

https://www.khronos.org/registry/gles/#headers32

**Comment by gonetz** [comment]
So, we can load everything needed via EGL. Great!
Can we provide only one version of GLideN64, which can ask application for GL context of any GL version supported by device?

**Comment by fzurita** [comment]
I think that will be more difficult. I don't think GL and GLES headers are compatible. We should see how dolphin does this and use them as a model. I think they use one binary for all GL versions.

**Comment by gonetz** [comment]
glad can generate a common header for all GL versions.
In fact, it is not so important. I can use different loaders for each GL version. Each loader may use its own header. I more concerning about link issues: do you need to link separate lib for each GLES version?

**Comment by fzurita** [comment]
No, they can all link against the EGL shared object library.
