### ISSUE TITLE
Is it possible for GLideN64 to use the new UID shader storage method?

### ISSUE THREAD

**Issue by retrobenny** [gonetz/GLideN64#1278]
Dolphin emulator has recently gotten support for a greatly improved shader generation storage that can be used between all backends (not D3D currently,but Vulkan and OpenGL can share it) and every new revision installed instead of clearing it with a fresh,stutter-filled start,but this comes at the cost of a slower boot cycle.

I ask,can the UID method be used on GLideN64 as well?
At least for Full GL so Shield TV would be even more useful to have,GLES may likely have issues anyway.

**Comment by fzurita** [comment]
Yep, it's possible. And it would even be compatible with GLES 2.0. With there UID method, you are sitting information on how to generate the shaders and you are generating them all at start up. Also, the UID method can be combined with the current method.

**Comment by retrobenny** [comment]
If you and Gonetz agree to it,maybe there can also be a multi-threaded shader dedicated to loading the already stored shaders in a streamlined fashion so the games would boot without any delays while keeping the original singe-threaded shader intact for each left over new one generated.

And if this also works across different versions and GLES types plus Full GL,filled up shader files could be shared,possibly in the same server as the boxart,to completely avoid most-if-not-all stutters altogether.
In this case,a button would be added to download the UID shaders for each game you select the option in while another option could be to check your list of games for downloading each shader set for every listed game in Mupen's library at the time of selecting the option.
So having 30 games listed would end up with those 30 games worth of shader filesets and much less bothersome shader stutters.

**Comment by loganmc10** [comment]
Aren't the shader binary formats GPU/driver specific?

**Comment by fzurita** [comment]
Yes, but you if you know all the possible mux combinations for a game ahead of time, you can use them to generate all possible combinations at once.

**Comment by loganmc10** [comment]
That part I get, but it seems like having them in a downloadable format like box art would be impractical, they would still need to be generated on the user's device the first time.

**Comment by fzurita** [comment]
Yes, they would have to be generated based on the mux combinations the first time a plugin starts a game.

**Comment by retrobenny** [comment]
Then,in the case of it having to for the first time,there can be a flag that checks if you have done so before that prevents you from downloading the filled set until it sees one that was created.
Or would there be a deadlock in all situations,barring out any way of doing this? (which kinda sucks if true)

**Comment by gonetz** [comment]
If I got it right, the idea is simple: emulator load special data file, which contains list of combine modes, used by the game. Plugin can use that list to create all combine shaders before game start and then game will run smooth. 
It is possible and easy to implement. Each combiner has 64bit key. This key is enough to create the shader. It is possible to dump not only binary shader storage, but also list of keys in text form, e.g. Json. Such file can be stored on server along with other game data, like boxarts.

**Comment by AmbientMalice** [comment]
How bad is N64 shader creation stuttering, anyway? Dolphin is one of the only emulators where this is a serious issue, AFAIK.

**Comment by gonetz** [comment]
It is noticeable on mobile devices.

**Comment by retrobenny** [comment]
Several stutters on Zelda games and sensitive moments stutter on Paper Mario right when attacking enemies within battles which can mess up your timing for stronger attacks.
What about the multi-threaded storage loader at start idea,would you agree to using that to eliminate the delayed boot with a streamlined loading sequence in realtime as the game boots?

**Comment by LegendOfDragoon** [comment]
>What about the multi-threaded storage loader at start idea,would you agree to using that to eliminate the delayed boot with a streamlined loading sequence in realtime as the game boots?

But then you'd get messed up graphics. I'd rather just have a delayed boot.

**Comment by oddMLan** [comment]
>But then you'd get messed up graphics. I'd rather just have a delayed boot.

Yeah. I used to use Ishiiruka dolphin but the messed up graphics due to async shader generation (also slower than the official branch) made me leave it

**Comment by LegendOfDragoon** [comment]
>Yeah. I used to use Ishiiruka dolphin but the messed up graphics due to async shader generation (also slower than the official branch) made me leave it

How long ago did you try Ishiiruka. I thought it was faster than official branch :( . Maybe I'll try official and see if that runs full speed on my comp. Anyway, I'd rather have broken graphics than stuttering, but in this case, if it's just combiner inputs, then having a database and precompiling is the best route imo. N64 doesn't have that many games and combiner is only 8 bytes, so the database won't be that big.

**Comment by oddMLan** [comment]
Recently, and it was like 40% slower on my computer. A while ago it was faster, but now the official branch is faster

**Comment by gonetz** [comment]
> What about the multi-threaded storage loader at start idea,would you agree to using that to eliminate the delayed boot with a streamlined loading sequence in realtime as the game boots?

It is to early to discuss multi-threaded load, since we don't have any load implemented yet.

**Comment by Craftyawesome** [comment]
> But then you'd get messed up graphics. I'd rather just have a delayed boot.

Ishiiruka uses async shaders all the time, leaving broken graphics. What dolphin is going to do is compile UIDs in a separate thread but until it's compiled it works like old versions of dolphin.

**Comment by loganmc10** [comment]
I don't know how long you guys think this is going to take, it's probably 2-3 seconds at the absolute most.

**Comment by LegendOfDragoon** [comment]
>Recently, and it was like 40% slower on my computer. A while ago it was faster, but now the official branch is faster

I did not see any significant difference on my end, when i tested Smash Bros Melee. What game(s) did you compare the 2 with? In Dolphin's case, I'd rather have the broken graphics instead of stuttering.

But with N64, I don't think stuttering is as big of a problem to begin with. I wouldn't bother with any multithreading for shader compilation.

**Comment by oddMLan** [comment]
>What game(s) did you compare the 2 with? In Dolphin's case, I'd rather have the broken graphics instead of stuttering.

Super Mario Galaxy 1 & 2, Punch Out. Just those, enough to realize it was running slower in my computer. The GFX card is a huge determining factor in which version runs better. In my case, my card has good support of the newest APIs so naturally it runs better with those. For people who have older cards that only run well with D3D9, Ishiiruka might be their best bet.

**Comment by LegendOfDragoon** [comment]
Is it really stuttering, just because of combiner shaders? I find that surprising, given how small the  combiner code is.

>The GFX card is a huge determining factor in which version runs better.

I figured it has something to do with gfx hardware. I might as well delete Dolphin from my computer and just continue playing games on my wii. That stuttering is a complete turn-off and their software renderer isn't even functional.

**Comment by Craftyawesome** [comment]
> tested Smash Bros Melee
Unplayable stuttering on melee? It doesn't really happen past go for me.
> their software renderer isn't even functional.
It was just there for accuracy but now it's arguably worse in accuracy too.

**Comment by oddMLan** [comment]
This can be closed. Shader Keys is equivalent to the proposed approach in the original post.
