### ISSUE TITLE
[Regression] Quake 2 metallic effect in the menu is broken.

### ISSUE THREAD

**Issue by RazielZnot** [gonetz/GLideN64#1279]
Texture is very dim and statically attached to the models.
![project64 2016-12-02 19-33-30-08](https://cloud.githubusercontent.com/assets/20717026/20842111/6070bc78-b8c7-11e6-823d-3f538291c3e1.png)

**Comment by olivieryuyu** [comment]
confirmed, light issue i guess :(

**Comment by gonetz** [comment]
Dim colors is not an issue, it looks like this in LLE mode.
Texture coords generation is broken  for this game.

**Comment by RazielZnot** [comment]
> it looks like this in LLE mode
No, this is HLE. In fact, in LLE mode coords are okay.

**Comment by gonetz** [comment]
I mean that colors are dim in LLE too.

**Comment by RazielZnot** [comment]
Oh, okay.

**Comment by olivieryuyu** [comment]
fixed

@ RazielZnot, can you closed the ticket pls?
