### ISSUE TITLE
In Diddy Kong Racing, plugin stutters between transition of characters in intro

### ISSUE THREAD

**Issue by oddMLan** [gonetz/GLideN64#1287]
The plugin seems to be switching to Frame buffer for a frame right before the next character appears

**Comment by LegendOfDragoon** [comment]
Are you sure the video plugin is at fault?

**Comment by weinerschnitzel** [comment]
Noob question DDKR == Diddy Kong Racing Debug ROM?

**Comment by oddMLan** [comment]
Diddy Kong Racing, retail version
>Are you sure the video plugin is at fault?

well, it doesn't happen with other plugins

**Comment by fzurita** [comment]
This can happen if you have texture filtering enabled.

**Comment by oddMLan** [comment]
It still happens with default settings.
It doesn't happen with Frame buffer emulation disabled.

**Comment by gonetz** [comment]
The game stops to update frame buffer before switch to next character. It is just for a few frames, you are keen-eyed to notice that. I guess, that without new frames plugin switches to show RDRAM content.
Where is plugin's bug here?

**Comment by oddMLan** [comment]
I see, it's just like you said; since there are no new frames to show plugin switches to frame buffer. It's just that the frame buffer is always one frame behind, which makes the image stutter when the switch to RDRAM happens. I was reading your blog and this just seems that async mode is always one frame behind. In sync mode the switch to RDRAM still happens, but it's always the current frame, so the stutter dissapears. I guess for games where there's noticeable stutter due to the plugin showing the RDRAM content from one frame behind I will enable sync copy 😊

**Comment by Frank-74** [comment]
There's a similar problem with goldeneye surface level when switching weapons.
