### ISSUE TITLE
EnableCopyDepthToRDRAM = 2 breaks Mario Golf transitions?

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1293]
Hopefully someone can verify this for me, but it seems that the new default of EnableCopyDepthToRDRAM = 2 (Software), breaks the Mario Golf transitions?

EnableCopyDepthToRDRAM = 0
![off](https://cloud.githubusercontent.com/assets/848146/20899274/0affe8f0-bae7-11e6-9712-c4bf56c430c7.png)

EnableCopyDepthToRDRAM = 2
![on](https://cloud.githubusercontent.com/assets/848146/20899283/11ed7c0e-bae7-11e6-947e-3fc43cc98650.png)

**Comment by gonetz** [comment]
Yes, depth copy should be off for this game.

**Comment by gonetz** [comment]
Software depth buffer copy breaks validity check in this game. Copy from RDRAM has no issues.

**Comment by loganmc10** [comment]
Could we add EnableCopyDepthToRDRAM = 0 to GLideN64.custom.ini?

**Comment by loganmc10** [comment]
It looks like this game needs fragment depth writing as well or else some surfaces are see through

**Comment by gonetz** [comment]
> Could we add EnableCopyDepthToRDRAM = 0 to GLideN64.custom.ini?

Any config option can be added to custom ini.

**Comment by gonetz** [comment]
> It looks like this game needs fragment depth writing as well or else some surfaces are see through

Yes, it must be enabled too.
