### ISSUE TITLE
Feature request - buildbot aka build automation

### ISSUE THREAD

**Issue by Gagert** [gonetz/GLideN64#1294]
The great thing about software projects such as these are that updates comes at a steady pace by a community of enthusiast developers. However, it seems like GlideN64 is not easy to build, at all. I have begun my quest of completing this tutorial https://github.com/gonetz/GLideN64/issues/742 for being able to test the latest features of the development versions of GlideN64, but as of now it's not exactly user-friendly to build the files from the source code.

As seen in the linked guide, it's required to have a whole bunch of libraries installed just to build GlideN64. Thereby many of us have to wait for the official releases to test the new features, and even bug-test new features.

The Gamecube/Wii emulator Dolphin has some kind of build automation that spits out the latest code-revisions of the emulator many times a day, and the Dolphin team releases a new stable version every now and then (a new version number by the Dolphin team every two years or so).

I have no idea how much effort that would be required to make build automation for the GlideN64 plugin, but if it is possible without too much effort, it sure would be a nice allowing new features to be tested by a bigger group of testers than as of today.

**Comment by gonetz** [comment]
It would be great to setup auto build system for GLideN64.

**Comment by loganmc10** [comment]
For Linux this is dead simple, you just add a file called ```.travis.yml``` to the base directory of the repo with these contents:

```
dist: trusty
sudo: required
language: cpp

compiler:
 - gcc

before_script:
 - ./src/getRevision.sh
 - cd projects/cmake
 - cmake -DMUPENPLUSAPI=On ../../src/

script: make
```

Then you need to configure Travis CI for the repo (on GitHub go to Settings->Integrations and Services->Add Service->Travis CI), I can't remember exactly all the steps to turn on Travis CI but it's quite simple.

For Windows it's likely a little more complicated, I've heard that AppVeyor is the popular choice for Visual Studio builds.

Part of the issue will be hosting, I'm not sure there is an easy way to upload the final product to Google Drive or something like that.

For GLupeN64 I use Travis CI to create builds for Linux, Android, and Windows (cross-compiled). If the build is successful it uploads it to Amazon S3 for people to download. However, S3 is not free, nor are most proper hosting solutions.

**Comment by gonetz** [comment]
Moved to #1613
