### ISSUE TITLE
Copy video card frame buffer to n64 memory UI issue

### ISSUE THREAD

**Issue by Craftyawesome** [gonetz/GLideN64#1295]
The dropdown says software has fewest game issues, but hovering over it with your mouse seems to indicate vram is most accurate.

**Comment by AmbientMalice** [comment]
Technically, VRAM **should** be more accurate, but it's bugged currently.

**Comment by gonetz** [comment]
VRAM contains most complete and accurate depth buffer. I would not say that copy depth buffer from VRAM is bugged. It rather not always happens in proper time and it is unavoidable. Software depth buffer is not as accurate, but software rendering allows to keep depth buffer in RDRAM always in actual state, thus it has fewest game issues.

There is no issue in GUI: copy vram is most accurate, but it does not guarantee correct emulation.
