### ISSUE TITLE
Mario Artist Talent Studio Regressions

### ISSUE THREAD

**Issue by LuigiBlood** [gonetz/GLideN64#1296]
If I enable Auxiliary Buffer along with Render frame buffer as texture on this build https://github.com/gonetz/GLideN64/issues/885#issuecomment-264685995

Mario Artist Paint Studio: When putting stamps, the framebuffer render goes haywire and is very unstable. The issue is that I need the framebuffer render to see the cursor.
Mario Artist Talent Studio: Right from the title screen, it flickers with a bunch of textures. The face editor is also very unstable as it uses the auxiliary buffer, and the face instead has parts of the regular framebuffer on it when saved when it's not supposed to.

EDIT:
Actually I'm trying other builds where I was sure it worked but now it doesn't. I didn't update my drivers (there are none, my GFX card is considered too old).

EDIT2: Maybe I'm wrong. Seems it happens after commit 7a4ef39? There are less issues if you use synchronous frame buffer, but there's still the face problem, which definitely worked as it should be on build 7a4ef39.

**_EDIT3: Read the later posts._**

**Comment by loganmc10** [comment]
I really doubt that https://github.com/gonetz/GLideN64/commit/7a4ef394b11611966a70a570c2ebf791188f72ce caused any framebuffer problems, all that did is allow you to build without GLideNHQ (high res textures packs/texture filtering), but that's not even the default, the default behavoiur (including GLideNHQ) never changed.

**Comment by LuigiBlood** [comment]
What I meant was something happened AFTER that commit.

**Comment by LuigiBlood** [comment]
Here's a screenshot of the face problem:
![image](https://cloud.githubusercontent.com/assets/952602/20943525/0f2bb4da-bc00-11e6-8e76-d2d459680d76.png)

**Comment by LuigiBlood** [comment]
Basically a checkup: Still happens on 2.0 release.

**Comment by LuigiBlood** [comment]
Decided to change the name to be more accurate at what's actually at stake.
Using Sync Frame Buffer, the games are a lot more stable. But that doesn't fix the issues with Talent Studio like that screenshot has shown.

**Comment by LuigiBlood** [comment]
On the latest WIP build (2017/02/21), Talent Studio crashes after the 64DD logo.

**Comment by fzurita** [comment]
Can you produce a back trace? I'm not setup to run 64DD software in Android....

**Comment by LuigiBlood** [comment]
I can't really try it out right now but I think it happens upon changing microcode. Glide64 for PJ64 couldn't deal with it and that was after the 64DD logo as well until I added it to the INI file.

**Comment by LuigiBlood** [comment]
Can't seem to do a backtrace. If you want more details: I'm using Project64, on Windows 7 Ultimate x64, with an AMD Radeon HD5700. It's old, I know.

**Comment by LuigiBlood** [comment]
On 2017-04-03 WIP build, Talent Studio is working.
Loading screen is for some reason blinking.

However, good news: the face issue is fixed.
![image](https://cloud.githubusercontent.com/assets/952602/24665964/312df7c0-195f-11e7-8bf0-23e853e43f8d.png)
And not only that, another issue was fixed as well: #1157
Another issue appeared however, but I will make a whole issue about this instead.

**Comment by LuigiBlood** [comment]
Oh yeah I forgot, other issues did happen:
![image](https://cloud.githubusercontent.com/assets/952602/24666249/144682fc-1960-11e7-86da-da56cc07797e.png)
This icon disappears depending on the movie being played. That's definitely not normal.

Another one as well:
![image](https://cloud.githubusercontent.com/assets/952602/24666286/2f8af37c-1960-11e7-9fe8-4f9b7cea224d.png)
01, 02, 03... is supposed to appear. Except the last digit is missing for every of them.

**Comment by LuigiBlood** [comment]
On d8ac5a7 WIP build, these issues seemed to be fixed.
