### ISSUE TITLE
Goldeneye 007 ucode

### ISSUE THREAD

**Issue by Gillou68310** [gonetz/GLideN64#1300]
@gonetz, @olivieryuyu

I checked goldeneye's ucode, it's based on the gspF3DNoN.fifo ucode with some particularities:

-The POPMTX command (0xbd) doesn't exist.
-Instead both 0xbc and 0xbd commands points to the MOVEWORD command. It should not matter since the 0xbd command doesn't seems to happen in this game.
-The 0xb1 command points to a custom TRI1 command that loads up to 4 triangles. The code is different from the TRI4 command which is used right now.

Here's the implementation:
https://github.com/Gillou68310/GLideN64/commit/069afbaa49db7fc7ff67e05c3a45248584e16be5

Also I rewrote the source from disassembly for people who are interested.
[GOLDENEYE_TRIX.txt](https://github.com/gonetz/GLideN64/files/649473/GOLDENEYE_TRIX.txt)

@olivieryuyu
You talked about an LLE hack to draw the sky in this game, what are you referring to?

**Comment by weinerschnitzel** [comment]
You make it sound like you just HLE'd GoldenEye's skies??

Could you provide a picture, and does the flickering occer since it isnt using LLE draw triangles?

**Comment by olivieryuyu** [comment]
Ah so my little eyes were right, GE007 does not use a standard ucode :)

The sky in Goldeneye is not appearing without using directly LLE triangle commands to display it with all HLE plugin. So it is a kind of hack of HLE by using LLE when specific conditions are met (rdphalf cont).

Some people believed that the sky is drawn without going through by a microcode command.

**Comment by Gillou68310** [comment]
Oh I see it now. Well I checked but my ucode implementation doesn't fix that issue. I can take a closer look at it now that I know what we are talking about :-)

**Comment by olivieryuyu** [comment]
The sky is also missing in perfect dark. Here there is a specific tri command for this game. May it is the same, dunno.

**Comment by olivieryuyu** [comment]
@gonetz: where in your code the sky LLE command are triggered? no idea where it is :(

**Comment by Frank-74** [comment]
One of the featured fixed for Jabo's 1.6.1 was 'fixed calculations of sky triangles'.

**Comment by olivieryuyu** [comment]
i guess he fixed the issue with the LLE sky triangle which exists nowadays in GlideN64. 

May be indeed the game send directly the triangles in LLE.

**Comment by AmbientMalice** [comment]
GoldenEye/Perfect Dark/Killer Instinct don't use display lists for rendering the skies.

**Comment by weinerschnitzel** [comment]
How do you know that the sky is not rendered via display lists?

**Comment by LegendOfDragoon** [comment]
>How do you know that the sky is not rendered via display lists?

Because it's using ProcessRDPList. That's why killer instinct doesn't work with Rice's Video plugin.

**Comment by olivieryuyu** [comment]
It is true that KI has nearly no difference in its ucode with the one of SuperMario64. I guess there is no mystery to solve and the sky is send by RDP list directly.

**Comment by gonetz** [comment]
RSP is necessary to process polygons: apply matrix transformation, apply clipping. It is not necessary for sky polygons, because their parameters are static, except for texture coordinates. Thus, sky polygons can be send directly to RDP.

**Comment by gonetz** [comment]
> @gonetz: where in your code the sky LLE command are triggered? no idea where it is :(

F3D_RDPHalf_1 => RDP_Half_1

**Comment by olivieryuyu** [comment]
So if I understand correct, the sky is done by generating a succession of triangles sent directly to the RDP by the means of G_RDPHALF_1 and G_RDPHALF_CONT. It is not closed like a texture rectangle with G_RDPHALF_2 as it is keep being drawn all the time.

**Comment by Gillou68310** [comment]
RDP triangle commands are described in the following document starting at page 12.
[GFXBI.pdf](https://github.com/gonetz/GLideN64/files/651610/GFXBI.pdf)

For example if the RSP wants to send a shade, texture, zbuff triangle (biggest command) to the RDP, forty four 32bit words need to be send using 21 G_RDPHALF_1 and G_RDPHALF_CONT combo plus 1 G_RDPHALF_1 and G_RDPHALF_2 combo to terminate the transfer.

G_RDPHALF_CONT is used instead of G_RDPHALF_2 to avoid rsp yielding in the middle of the data transfer.

The current implementation doesn't looks like a hack to me but reflects what the real hardware is doing.

**Comment by olivieryuyu** [comment]
Perfect, then no mystery, just Rare devs used a weird way to draw a mere sky :)

**Comment by gonetz** [comment]
@Gillou68310 
> Here's the implementation:


Looks good. Please make pull request

**Comment by AmbientMalice** [comment]
Good work. It's great to see emulation becoming more accurate. I look forward to further ucode improvements.

**Comment by loganmc10** [comment]
What exactly does this fix if not the sky?

**Comment by Gillou68310** [comment]
Accuracy ;-)

**Comment by Gillou68310** [comment]
> Looks good. Please make pull request
> 
> I took it myself.

Thanks @gonetz, I guess we can closed this, there's no other mystery in this ucode.

**Comment by gonetz** [comment]
> What exactly does this fix if not the sky?
> Accuracy ;-)

Better understanding, how this particular **custom** ucode works. Gilles, thanks!
