### ISSUE TITLE
Xbrz issues

### ISSUE THREAD

**Issue by LuismaSP89** [gonetz/GLideN64#1301]
When using xbrz filter, many graphical bugs appeared (Using last version of emucr´s build) This doesn´t happens in the latest buidls.

![gliden64_the_legend_of_zelda_004](https://cloud.githubusercontent.com/assets/12205048/21195141/dad5f00e-c232-11e6-858f-6d5306ddd5af.jpg)
![gliden64_the_legend_of_zelda_000](https://cloud.githubusercontent.com/assets/12205048/21195142/dad70ea8-c232-11e6-9910-e994f2c5f797.jpg)
![gliden64_the_legend_of_zelda_001](https://cloud.githubusercontent.com/assets/12205048/21195140/dad5275a-c232-11e6-8d1b-fe0589604a6e.jpg)
![gliden64_the_legend_of_zelda_002](https://cloud.githubusercontent.com/assets/12205048/21195144/dadd51fa-c232-11e6-997e-76c6d7b861c7.jpg)
![gliden64_the_legend_of_zelda_003](https://cloud.githubusercontent.com/assets/12205048/21195143/dada895c-c232-11e6-979b-8e815f6b5700.jpg)

**Comment by gonetz** [comment]
Disable "Decrease color banding" option.

**Comment by gonetz** [comment]
Fixed "Decrease color banding" option.
@LuismaSP89 you may download the fix here:
https://github.com/gonetz/GLideN64/issues/885#issuecomment-267341217

**Comment by LuismaSP89** [comment]
Yes, it works now, thanks a lot Gonetz ; )
