### ISSUE TITLE
Early Fast3D games - Tiny HLE improvment proposals

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1303]
A small proposal of mine, nothing outstanding and nothing urgent.

I tried to dump all Fast3D games (before F3DEX so) (may be I missed some, dunno) and separate them according to the fact that they do have G_PERSPNORMALIZE in their ucode or not, meaning also that the place of the RDPHALF commands are changed, meaning:

F3D_PERSPNORM        0xB4
F3D_RDPHALF_1          0xB3
F3D_RDPHALF_2          0xB2
F3D_RDPHALF_CONT        0xB1

As well I checked out which games have clipping on or off (mostly off but sometimes they are on actually)

I made a list of those:

![image](https://cloud.githubusercontent.com/assets/8987490/21334148/633d42fa-c655-11e6-8ca2-dccecb8d3889.png)

Mario Kart has also this G_PERSPNORMALIZE in its code. I noticed that it does not have at all RDPHALF_CONT.

Would it be an idea to separate the FAST3D ucode in 2 (version 1 for early/custom games and version 2 for other games)? It would avoid doing some tricks in the code to check the right place of the RDPHALF command and potentially be a bit more accurate.

I think that there is already a place where to set the clipping for the games so that one should be easy :)

**Comment by gonetz** [comment]
> which games have clipping on or off

Do you mean Near plane clipping (NoN) on/off or all clipping planes on/off ?
Some ucodes disable only near plane clipping, some not using clipping at all.

> Would it be an idea to separate the FAST3D ucode in 2

Do you have an idea, how to separate them? By ucode name, by ucode checksum or somehow else?

**Comment by olivieryuyu** [comment]
- Near plane clipping (NoN). I think in your code you have a place where you set true or false for this according to the crc of the ucode.

- Most of the games with G_PERSPNORMALIZE is with microcode string "RSP SW Version: 2.0D, 04-01-96", except:

WonderProject2
Majhong Master
Cruis'n USA
Doraemon - Mittsu no Seireiseki

Their code are similar to RSP SW Version: 2.0G actually. So it would be better to create an exclusion list.

Custom microcodes have already specific place in your code, so it is not an issue.

The only remote case is actually Mario Kart 64 :( It is the most early F3DEX game (0.95) and I guess this function is a leftover in the code, which disappeared totally after.

**Comment by gonetz** [comment]
How you search for G_PERSPNORMALIZE in ucode dump?
May be it will be safer for the plugin to do the same?

**Comment by LegendOfDragoon** [comment]
I finally am free :smile: . @olivieryuyu you still want me to upload that modified RSP for dumping gfx ucodes?

**Comment by olivieryuyu** [comment]
@LegendOfDragoon 

I found that PJ64 and Nemu were capable to do the same so I guess it is fine, thanks you.

@gonetz: I don't know if the plugin can do this. Will send you an email.
gonetz:

**Comment by olivieryuyu** [comment]
found a new game with G_PERSPNORMALIZE, Power League Baseball 64. It says RSP SW Version: 2.0D, 04-01-96 but it is nearly the same code than Mario Kart 64.

**Comment by olivieryuyu** [comment]
I dunno if it can help out the plugin but in gbi.h there is a mention that the value for Near plane clipping (0x703)can be located at flags of G_SETGEOMETRYMODE: 

 * DO NOT USE THE HIGH 8 BITS OF GEOMETRYMODE:  * The high byte is OR'd with 0x703 to form the clip code mask.  * If it is set to 0x04, this will cause near clipping to occur. If it is zero, near clipping will not occur.

**Comment by olivieryuyu** [comment]
It would be nice to get this implemented at one point in time. Nothing urgent but well I would lead to get more precision on the ucode implementation and less hack in the code.

**Comment by gonetz** [comment]
Implemented.

@olivieryuyu @theboy181 Please test, that I did not break games from olivieryuyu's list:
https://drive.google.com/file/d/1DiM4qyKqPUADTqleajdZNtp_h-9SMuoA/view?usp=sharing

**Comment by theboy181** [comment]
is Zelda using cliping? 
![image](https://user-images.githubusercontent.com/9299743/44882660-180f4e80-ac69-11e8-8734-9c465a6d5df9.png) GLideN64 vs AL+

**Comment by olivieryuyu** [comment]
F3DSETA,		false,	true,	false,	0x2edee7be }, // RSP SW Version: 2.0D, 04-01-96

That is Kuiki Uhabi Suigo. Seems persp norm is on false (not on)when it should be on true (on)

**Comment by gonetz** [comment]
> is Zelda using cliping?

It is not clipping issue,  it is depth compare.  N64 depth compare option may help.

F3DSETA ucode has its own init function, where flags already set to right values. Fast3dpersp flag can be set to true for it as well, it will not change anything.

**Comment by gonetz** [comment]
> F-Zero still had clipping issues with this build, was it fixed after this release?

Yes

**Comment by gonetz** [comment]
> F-Zero still had clipping issues with this build, was it fixed after this release?

Yes

**Comment by olivieryuyu** [comment]
Wave Race 64 - Shindou Edition (J) (V1.2) is broken

**Comment by oddMLan** [comment]
What about the N64DD games? (Ie. Super Mario 64 DD port).. I assume it also uses a newer version of the ucode

**Comment by gonetz** [comment]
> Wave Race 64 - Shindou Edition (J) (V1.2) is broken with this commit.

Yep. Wayne Gretzky's 3D Hockey roms use 3 different ucodes but only (U) version falls into the list.
(J) version uses the same ucode as Wave Race 64 - Shindou Edition (J) , so both were broken.
Fixed.

**Comment by gonetz** [comment]
> What about the N64DD games?

Don't have one. Please test, if you have them.

**Comment by olivieryuyu** [comment]
there is a mess on early ucode...

Super Mario 64 Shindou Edition as well.
Super Mario E version as well.

have new version of ucode (without persp norm) but not supermario u and J.

**Comment by gonetz** [comment]
Yes, I noticed that.

**Comment by gonetz** [comment]
> Shindou Edition and SM64 (E), are any graphic errors inmediately noticeable?

Immediately. "Press start" texrect does not work.
