### ISSUE TITLE
Wave Race 64 and Star Wars Shadows of Empire: same ucode

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1304]
May be I am incorrect but the ucode dump of Wave Race 64 and Star Wars Shadows of Empire seems to be completely identical. Same TRI command, same G_QUAD, same G_VTX, same everything.

Hence my proposal to reduce those 2 games in the 1 ucode in the GlideN64.

It is certainly a early/beta version of F3DEX.

**Comment by gonetz** [comment]
Interesting. F3DWRUS ucode works fine with Star Wars Shadows of Empire. 
F3DSWSE ucode does not work with Wave Race 64.
Interesting, how author of F3DSWSE ucode get that formula for number of vertices: _SHIFTR(w0, 4, 12) / 33 + 1. It works correct for SWSE
F3DWRUS uses _SHIFTR( w0, 9, 7 ) and it works for SWSE too.

I agree that F3DSWSE can be removed.

**Comment by gonetz** [comment]
52b95f6

**Comment by olivieryuyu** [comment]
Tested, works fine it seems :)
