### ISSUE TITLE
Documented source code for F3DEX2 ucode 

### ISSUE THREAD

**Issue by Gillou68310** [gonetz/GLideN64#1305]
[F3DEX2.zip](https://github.com/gonetz/GLideN64/files/666870/F3DEX2.zip)

For people who are interested, I spend some time to document the source code from the F3DEX2 ucode disassembly. This is still a WIP so a lot of things are missing. I won't have much time to work on it in the following weeks so I decided to share it in it's current state.

**Comment by olivieryuyu** [comment]
Woa amazing!!! Thanks!

**Comment by gonetz** [comment]
I think such information should be in wiki section.

**Comment by olivieryuyu** [comment]
https://github.com/gonetz/GLideN64/wiki/F3DEX2-ucode-documentation

@Gillou68310 

Would you close the ticket?

**Comment by Gillou68310** [comment]
Sure ;-)

**Comment by olivieryuyu** [comment]
tu peux toujours updater la pièce jointe du ticket, le wiki pointe vers celle-ci :)
