### ISSUE TITLE
Perfect Dark: TRIX instead of TRI4

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1307]
I noticed that Perfect Dark has nearly the same TRI code than GoldenEye 007. 

The only difference is that the code doesn't compute a normal per triangle. I guess the normalization is done at vertex level, which explains why G_VTX is different. It may also explain that the colors are done per vertex and not per triangle.

So TRIX should be used instead of TRI4 to be consistent and more accurate.

**Comment by olivieryuyu** [comment]
Actually as TRI4 is only used IN GE and PD which are special ucode, TRI4 should disappear from the code.

F3DEX2CBFD_Tri4 is specific to CBFD. I don't think any other games uses TRI4.

**Comment by gonetz** [comment]
> Actually as TRI4 is only used IN GE and PD which are special ucode

Are you sure?

**Comment by olivieryuyu** [comment]
Not at 100% but I cannot think of a game using TRI4. DKR and JFG does not seems to use TRI4. Am I wrong here?

**Comment by gonetz** [comment]
Looks like they does not.

**Comment by olivieryuyu** [comment]
Perfect :)

**Comment by fzurita** [comment]
> Perfect

No pun intended? :)
