### ISSUE TITLE
Banjo kazooie shadows render in the air

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1309]
Shadows coming from point lights that go over an edge end up being rendered in the air. Here is an example of what it should look like, this was sent to me: 

![grh310n](https://cloud.githubusercontent.com/assets/11581687/21444319/4167e942-c87a-11e6-9366-a0022fe88944.jpg)

**Comment by AmbientMalice** [comment]
Try turning on N64 depth. Probably a similar issue to Perfect Dark's blood and bullet decals.

**Comment by fzurita** [comment]
Hmm... interesting, that shader seems to be broke in GLES-3.0/3.1. I should probably fix that.

**Comment by AmbientMalice** [comment]
>Hmm... interesting, that shader seems to be broken in GLES-3.0/3.1.

It requires GL4.5, I think. Dunno whether it can be fixed on GLES3.

**Comment by gonetz** [comment]
It requires image textures support:
```
#ifdef GL_IMAGE_TEXTURES_SUPPORT
#ifndef GLESX
	m_bImageTexture = (((majorVersion >= 4) && (minorVersion >= 3)) || OGLVideo::isExtensionSupported("GL_ARB_shader_image_load_store")) && (glBindImageTexture != nullptr);
#else
	m_bImageTexture = (majorVersion >= 3) && (minorVersion >= 1) && (glBindImageTexture != nullptr);
#endif
#else
	m_bImageTexture = false;
#endif

```

**Comment by gonetz** [comment]
@fzurita could you upload the save?

**Comment by fzurita** [comment]
@retrobenny do you have a save state for this? I would like to see if it's an issue with N64 depth compare.

**Comment by retrobenny** [comment]
Of access to Grunty Industries in that general spot?
(I may need to get the Bazza battery placed into that if I forgot to)

**Comment by fzurita** [comment]
Yeah, like the picture.

**Comment by fzurita** [comment]
Cool, it's probably the same. If N64 depth compare fixes it, then I think we can close it.

**Comment by retrobenny** [comment]
Sorry for the delay,also an image of what it looks like for me.

![banjo_tooie-009](https://user-images.githubusercontent.com/16418716/39071234-e485e468-44ab-11e8-89c7-c93c83a71b21.png)

[Bazza Superlife.Banjo-Tooie (U) [!].sav.zip](https://github.com/gonetz/GLideN64/files/1933506/Bazza.Superlife.Banjo-Tooie.U.sav.zip)

**Comment by gonetz** [comment]
@retrobenny Thanks for the save!
Yes, shadow works correct here too with N64 depth compare:
![banjo_tooie-000](https://user-images.githubusercontent.com/8983092/39080046-1e2d7e38-4551-11e8-9697-9dcc94c1dc57.jpg)

**Comment by gonetz** [comment]
Worth to add that option to custom settings for Banjo.

**Comment by loganmc10** [comment]
Now that performance is not an issue it would be nice to sort out the remaining issues with N64 Depth Compare and make it a default option for all games, but I know your time is very limited

**Comment by gonetz** [comment]
Yep, not right now.
For example, this option is not compatible with Naboo ucode I'm working on now.
I don't know why.
