### ISSUE TITLE
Wrong "depth" in Harvest moon: shadows in game, clouds in menu

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#131]
![screen55](https://cloud.githubusercontent.com/assets/8987490/5024488/489f7f1e-6b0b-11e4-9c6c-6ec15d4ba0c5.jpg)
![screen61](https://cloud.githubusercontent.com/assets/8987490/5024489/4b077e14-6b0b-11e4-976e-3ec25b87713f.jpg)

**Comment by gonetz** [comment]
Enable N64 depth compare.

**Comment by Predator82Germany** [comment]
Should be in #297

**Comment by gonetz** [comment]
Looks like another NVidia incompatibility problem.

**Comment by Predator82Germany** [comment]
I like NVIDIA but with your plugin I hate them ;)

**Comment by gonetz** [comment]
I need NVidia card to debug such issues.

**Comment by Predator82Germany** [comment]
Can I help more?

**Comment by gonetz** [comment]
If nothing is logged in gliden64.log, then I have no clue what is going on. Depth compare is a complex shader, it's hard to debug it without hardware on hands. May be later.

**Comment by Predator82Germany** [comment]
No log sorry

**Comment by olivieryuyu** [comment]
works on amd indeed. slow option though

**Comment by olivieryuyu** [comment]
closed, it works with correct option and correct gfx card
