### ISSUE TITLE
GoldenEye missing portraits GLES2

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1310]
![screenshot_20161222-224805](https://cloud.githubusercontent.com/assets/848146/21447884/00aea070-c899-11e6-9492-2916b5b714a1.png)

Nvidia shield tablet and mupen64plus FZ

**Comment by fzurita** [comment]
Interesting, is this also happening with GLupeN64? You didn't seem to mention that one.

**Comment by loganmc10** [comment]
Ya happens there too, I try to use mupen64plus for bug reports to rule out any differences since the code is a bit different.

It doesn't happen with GLES3 and it doesn't happen with GLES2 on my phone or computer, seems to only happen on the shield tablet

**Comment by fzurita** [comment]
Hmm... since the shield tablet has GLES3.0, 3.1, and Full OpenGL available, I would say it's low priority. Specially since as you say, it happens with that device only?

**Comment by loganmc10** [comment]
Ya definitely low priority, just thought I'd report it, it might affect other devices as well, who knows
