### ISSUE TITLE
Smash 64 Graphical Inaccuracies

### ISSUE THREAD

**Issue by RomanTripp** [gonetz/GLideN64#1317]
There are a couple of graphical inaccuracies that I've found in the 2.0 version that was not in the previous builds. For example, the main part of Dreamland's texture seems very blurred. Also some of the flowers (the left one in front of the left bush) and 1 of the ponds (the small right one) seem to appear backwards or upside down. I've tried tweaking the settings to fix this but have had no luck. Here are some comparison images, with the previous version on top and the newest 2.0 version on bottom (sorry for bad quality, github doesn't support bmp and the only other screenshot option from plugin with jpg, but the inconsistencies are still able to be seen just fine)
![gliden64_smash_brothers_001](https://cloud.githubusercontent.com/assets/22534698/21595623/83bbdef6-d0f5-11e6-87c9-853e8266385e.jpg)
![gliden64_smash_brothers_000](https://cloud.githubusercontent.com/assets/22534698/21595624/84cb87f6-d0f5-11e6-912a-0d98d99e09b0.jpg)

**Comment by retrobenny** [comment]
For the most blatantly visible problem,the main texture is VERY broken,not just blurred,its largely stretched lines instead of the waffle cone,even the cone tips are missing.
What a messy visual bug,the same kind of thing happens in regular Glide64 on other stages like Pikachu's Platform bonus stage,not sure about PJGlide though.

**Comment by RomanTripp** [comment]
Sorry for the late response, I had forgotten I posted this.
I had only used v1.2 prior to this. The main broken Dreamland texture wasn't in v1.2, but the upside down small pond and the reversed flowers existed in v1.2.

**Comment by LegendOfDragoon** [comment]
Only seems to affect HLE for some reason.
