### ISSUE TITLE
Animal Forest broken menu

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1326]
Animal Forest is a fan translation of Dōbutsu no Mori.

Normally I wouldn't bring up ROM hacks, but this one works perfectly in angrylion, so I presume it should work properly.

GLideN64 HLE flashes between these 2 frames:

![screenshot from 2017-01-09 22-03-55](https://cloud.githubusercontent.com/assets/848146/21834262/103122ca-d771-11e6-9896-b2b8e1043199.png)

![screenshot from 2017-01-09 22-03-56](https://cloud.githubusercontent.com/assets/848146/21834269/1aa6b1ca-d771-11e6-8934-0d298ca2d8f6.png)

GLideN64 LLE looks like this:

![b5b2c27c-d73e-11e6-9a7a-b4472590de6a](https://cloud.githubusercontent.com/assets/848146/21834274/2ccabf36-d771-11e6-9921-f36cd452d961.png)

Angrylion looks like this:

![screenshot from 2017-01-10 20-10-25](https://cloud.githubusercontent.com/assets/848146/21834281/36439132-d771-11e6-9ea0-216c374ee061.png)

**Comment by loganmc10** [comment]
This is what is looks like with Framebuffer Emulation disabled (doesn't flicker, just has this image):

![image](https://cloud.githubusercontent.com/assets/848146/21854764/3cb4296a-d7d9-11e6-81e8-8092e6d04d39.png)

**Comment by loganmc10** [comment]
Still happening with current master

**Comment by AmbientMalice** [comment]
This looks fairly similar to Resident Evil 2's background issue, IMO.

**Comment by loganmc10** [comment]
The weird thing is that the issue is only present in the fan translation, the original Japanese version works fine, but both versions work fine with angrylion

**Comment by gonetz** [comment]
```
	else if (strstr(RSP.romname, (const char *)"THE LEGEND OF ZELDA") != nullptr ||
			 strstr(RSP.romname, (const char *)"ZELDA MASTER QUEST") != nullptr ||
			 strstr(RSP.romname, (const char *)"DOUBUTSUNOMORI") != nullptr)
		config.generalEmulation.hacks |= hack_subscreen;

```
may be subscreen hack has a side effect?

**Comment by loganmc10** [comment]
The current RSP.cpp has Animal Forest in the subscreen hack as well, I've tried it both ways. It's not a high priority obviously, just found it strange

**Comment by loganmc10** [comment]
Ok I've made a bit of a discovery with this:

Whenever the menu starts to go haywire, it starts to spit out a bunch of ```[GLideN64]: error - unknown ucode!!!``` messages to gliden64.log, but not until then (the log is empty when the game starts).

Is there someone that could point be in the right direction on this? Perhaps someone familiar with ucodes like @olivieryuyu ? I assume it's nothing too complicated since this is just a fan translation. Perhaps there is some portion of an already existing ucode that just needs to be applied to this game.

**Comment by loganmc10** [comment]
The documentation for the translation is here:

http://www.romhacking.net/translations/1581/

I grepped through the docs for "microcode" and "ucode" and there are a few lines like this:

```
JAL	800904B8	;insert "set foreground color" microcode op
```
```
800904B8	3EA38	insert "set foreground color" microcode op
```
```
4D294	8009ED14	replace microcode text command with speaker's name
```
But I don't really know what that kind of thing means.

**Comment by loganmc10** [comment]
I tracked down the missing ucode!

https://github.com/gonetz/GLideN64/pull/1448

Fixes the menu, now it looks like just angrylion and the Japanese ROM

**Comment by gonetz** [comment]
Great, thanks!
