### ISSUE TITLE
VRAM usage limite and Enchaced texture cache size

### ISSUE THREAD

**Issue by davjaks** [gonetz/GLideN64#1328]
When I try to use a texture pack of 806MB after the loading of the texturares appears a message warning that the memory can not be allocated.

Is there any way to increase the 999MB limit?
This limit prevents the person from using the texture without compression.

**Comment by Frank-74** [comment]
I think you need to patch the emulator to be able to use more than 1GB.  There exists a 4GB patch for Project64 somewhere.  You'll have to do a google search for it.  It's probably on Emutalk.

**Comment by Aquatakat** [comment]
Wherever GLideN64.dll is, you could try editing GLideN64.ini's `txCacheSize=` value.

If it works maybe we could increase the max value for that field in the UI.

**Comment by gonetz** [comment]
It will not help. The texture pack can't fit memory allocated for 32bit process in conventional RAM, not video memory.

**Comment by gonetz** [comment]
> Is there any way to increase the 999MB limit?

64bit build or 4GB patch for Project64
