### ISSUE TITLE
Parlor! Pro 64: texture issue

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#133]
![screen68](https://cloud.githubusercontent.com/assets/8987490/5035823/a49c2f96-6b7a-11e4-9439-61100a27ac02.jpg)

LLE Software

![fs](https://cloud.githubusercontent.com/assets/8987490/5035825/a7257d94-6b7a-11e4-9e87-24e1f6cdab52.jpg)

Rice seems the only one to avoid this issue, may be with a hack, cannot say

**Comment by olivieryuyu** [comment]
is it fixable? :(

**Comment by gonetz** [comment]
Have not check it yet.

**Comment by olivieryuyu** [comment]
4bit CI texture i guess :)

**Comment by gonetz** [comment]
Do you know something special about 4bit CI textures?

**Comment by olivieryuyu** [comment]
well yes and no. What i can see that 4bit texture are treated differently in the sprite microcode.

I am not sure however how i should interpret them. The code is a bit messy, even with so many comments.

**Comment by olivieryuyu** [comment]
the command used to draw the 2D are just horrendous. 800 lines of asm just for one commmand... it is a big as the ground generation command in SWRS!

@gizmo98 : as you are interested in S2DEX, any idea where the issue could be? it should be in command 0xC2 and/or 0x05.

**Comment by gizmo98** [comment]
@olivieryuyu i can take a look if i have fixed my current PR problem.

**Comment by olivieryuyu** [comment]
thanks

i think i have a lead actually, hopefully it is the source of the issue :)

**Comment by gonetz** [comment]
The problem rectangle is rendered by Sprite command 0xC2
https://level42.ca/projects/ultra64/Documentation/man/pro-man/pro25/index25.5.html

It uses the following formulas for texture coordinates:
```
x' = A * x + B * y + X
y' = C * y + D * y + Y
```
where A, B, C, D, X, Y are values from the 2D matrix.

2D matrix for this sprite is
```
A	0.0
B	-44.0
C	1.0
D	0.0
X	257.0
Y	150.0
```

(objX, objY) = (0, 0)
ImageW = 8, ImageH = 1
Upper left vertex has coordinates (objX, objY) = (0, 0)
Lower right vertex has coordinates (objX + ImageW/scaleW, objY + ImageH/scaleH) = (8, 1)
If you substitute the values to the formulas above, you will coordinates
(213, 150) - (257, 158)
I checked coordinates in LLE, they are (235, 149.5) - (279, 157.5)
That is vertex x must be `matrix X +- matrix B/2`
But this is impossible, objX=objY=0.
However, there is something special about this sprite: ImageH = 1
We have
```
 upper left y = objY = 0
 lower right y = objY + ImageH/ScaleH = 0 + 1/1 = 1

```
and things work wrong.
I suspect that actual code work slightly different: it takes objY - 0.5
In that case
```
  upper left y = objY - 0.5 = -0.5
  lower right y = objY - 0.5 + ImageH/ScaleH = -0.5 + 1/1 = 0.5
```
In this case we have +/- B*0.5 in x' calculation formula and result becomes correct! Moreover, it is the same, as in LLE mode.

I'm checking if this change cause regressions.
BTW, Stefan, your commit c76daedfc04 causes regression in Nintama Rantarou 64 Game Gallery (J)

**Comment by olivieryuyu** [comment]
fixed
