### ISSUE TITLE
Mortal Kombat Trilogy dark line under characters

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1332]
In Mortal Kombat Trilogy, a dark line is shown under all characters next to the shadow while in battle. It's easy to reproduce the issue, just start a battle.

**Comment by makoron1k** [comment]
Hello! It was possible to solve this problem?

**Comment by gonetz** [comment]
May be. Later.

**Comment by makoron1k** [comment]
**gonetz** А когда? Можно поинтересоваться?

**Comment by makoron1k** [comment]
Было бы здорово починить. Это действительно единственный плагин за все время, который делает в игре изображение сглаженным четко (за исключением появляющейся рваной тени под ногами, которой не должно быть).

**Comment by gonetz** [comment]
Подозреваю, что это будет непросто сделать. Исправления в текстурах в одной игре часто ломают что нибудь в другой.
Сейчас я занят другими проблемами, даже приблизительно не скажу, когда смогу переключиться.

**Comment by standard-two-simplex** [comment]
Is this one fixed?

**Comment by fzurita** [comment]
It does indeed look fixed in the latest matter.
