### ISSUE TITLE
Super Smash brothers charge up color change missing

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1334]
When characters charge up their attacks or do a smash move, their colors light up. This does not seem to be currently happening.

Correct behavior:

![0](https://cloud.githubusercontent.com/assets/11581687/22394507/43494740-e4f1-11e6-89d9-09d098e6238e.png)

Current behavior:
![0 1](https://cloud.githubusercontent.com/assets/11581687/22394511/51d6e90c-e4f1-11e6-816c-52188ff86243.png)

**Comment by retrobenny** [comment]
Double check your settings,I have mis-presumed a few times before realizing what profile and settings I was using.
For example,legacy blending breaks that feature.

**Comment by weinerschnitzel** [comment]
@LegendOfDragoon, if you haven't already seen this one.

Are character colors in Team Battle affected as well?

**Comment by fzurita** [comment]
Ok, it could be settings, let me double check and I'll close of it is.

**Comment by fzurita** [comment]
Yeah retroben, you are right. I forgot to toggle that settings.
