### ISSUE TITLE
Tony Hawk's Pro Skater 2 Shadow Glitch

### ISSUE THREAD

**Issue by Catarax** [gonetz/GLideN64#1337]
Tony Hawk's Pro Skater 2 USA version (Left of the First level)
GLideN64 2.0 on M64Py / Project64 (Default settings)
![screenshot_1](https://cloud.githubusercontent.com/assets/3964507/22447949/231701bc-e756-11e6-8d9d-f2e9a0b40fb5.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/3964507/22447952/2581cc98-e756-11e6-9b54-ede6c0d8772e.png)

Note : Jabo D3D render properly

**Comment by olivieryuyu** [comment]
bug confirmed.

Here with Rice plugin for instance

![sans titre](https://user-images.githubusercontent.com/8987490/31359592-e92bd700-ad4a-11e7-9a65-0af6e207c504.jpg)

**Comment by gonetz** [comment]
Fixed

**Comment by oddMLan** [comment]
New blending finally defeated? 😁
There is always one THAT game...

**Comment by gonetz** [comment]
You almost defeated it with #1488. Similar problem.
I found a workaround solution, which cost me several regressions. Now this one.

**Comment by DonelBueno** [comment]
This issue can be closed, no?

**Comment by gonetz** [comment]
Yes
