### ISSUE TITLE
Runs faster with Firefox running at the same time?

### ISSUE THREAD

**Issue by deuxsonic** [gonetz/GLideN64#1346]
I've noticed a strange quirk using this alongside the GE-PD release of the 1964 emulator which comes with the 2.0 release of GLideN64 which works excellent (almost solid 60 FPS), but only when Firefox is also running. When it is not, the framerate is only about half of what it would be. I've never encountered anything like this before and I'm baffled and I don't encounter the same issue using other video plug-ins, some of which are faster but produce highly inaccurate results. GLideN64 does a far better job than any other video plug-in so I would like to figure out why it's doing this. I'm using a GeForce 560 SE, 4 GB RAM, the latest GeForce drivers, an AMD Phenom II X4 955 CPU, nGlide.

I'm curious if Firefox when running since it is GPU-accelerated is loading some profile from the GeForce drivers that presents a much more favorable environment for the emulation to run in? Is there some driver profile I could create for 1964 using Nvidia Inspector that would be most favorable for GLideN64 to run in? Is it some setting I'm using with the plug-in?

**Comment by loganmc10** [comment]
Yes it's probably the Nvidia driver settings

See https://github.com/gonetz/GLideN64/issues/470

**Comment by deuxsonic** [comment]
There is a lot of talk of the framebuffer, and in this instance GoldenEye is the game I use to test this, and the game doesn't actually need the frame buffer so it's actually disabled in the custom ini, so this would not be the issue. The other issue listed in the thread, the Nvidia power management, I made sure it is set for max performance and restarted but it's still doing it. I tried editing the Mozilla Firefox GeForce driver profile to add the emulator's binary, but it doesn't seem to do anything and then creating a new profile with the emulator's binary with the settings I could copy over but it's the same result.

**Comment by fzurita** [comment]
I think this should be reported to Nvidia directly.

**Comment by deuxsonic** [comment]
I think I'm going nuts. Games that run FASTER with a resource hog running instead of slower. That is something I could try though. Post in their forums and see if anyone else has experienced something like this.

**Comment by deuxsonic** [comment]
Could #1335 potentially fix this? I tried the built copy linked to in that thread but it doesn't display correctly.

**Comment by fzurita** [comment]
There are a lot of issues left in #1335. Also, based on your description of the problem, I doubt it will fix it since I don't think it's an issue with the plugin.

It's probably the Nvidia power management bring over aggressive.

**Comment by deuxsonic** [comment]
I just tested Chrome and it actually has the same effect, and in addition to that, it only has the performance-boosting effect when it is on monitor #2 (I use a dualview setup.) The driver is set to single screen performance mode though, so what is going on...

**Comment by Aquatakat** [comment]
I wonder if you'd get similar performance boosts with other OpenGL plugins like Rice or glN64.

**Comment by AmbientMalice** [comment]
>It's probably the Nvidia power management being over aggressive.

It's almost certainly this. Been an issue with emulators for some time.

**Comment by deuxsonic** [comment]
I do get better performance with some other video plug-ins but they are considerably less accurate. I wouldn't stick to this plug-in if others were as good.

**Comment by gonetz** [comment]
> I do get better performance with some other video plug-ins but they are considerably less accurate.

Accuracy costs performance.

**Comment by deuxsonic** [comment]
That has absolutely nothing to do with what this topic is about.

**Comment by Aquatakat** [comment]
I meant can you measure a difference in performance in one of the other OpenGL plugins when you have a Firefox window open vs. not, because if so then it would absolve GLideN64 of any problems.

**Comment by AmbientMalice** [comment]
I'm pretty sure this problem is Google Chrome's fault because Chrome is deliberately designed with the goal of power saving first, performance last, and also Nvidia's fault because their power saving tech, while valuable, has some issues.

**Comment by gnutechs** [comment]
This could be related to how some programs such as Firefox, Chrome and Windows Media Player increase the system timer resolution of Windows when open.

**Comment by fzurita** [comment]
That would easy to test if you can find a program or a setting that does only that.

**Comment by deuxsonic** [comment]
Could someone put together a little program that increases system time resolution and nothing else? If this is indeed the cause, I could pass the program's source to the person maintaining the emulator to have it integrated.

**Comment by Frank-74** [comment]
In project64 I put in option to increase thread priority.

You need to edit Project64.cfg, put CN64TimeCritical=1 under the [default] section.

**Comment by fzurita** [comment]
Here is a tool that changes windows timer resolution:

http://www.lucashale.com/timer-resolution/

Try a value of 1 to 10ms, I take no responsibility if doing that causes system instability.

**Comment by deuxsonic** [comment]
You're right, it turns out it's a timing issue. Firefox sets the timer to the maximum resolution while running, and sets it back to a lower resolution when it is closed. By using the tool to force the max resolution, the problem goes away.

**Comment by fzurita** [comment]
Now if we can get project 64 to adjust the timer resolution on their own. You should make an issue in their GitHub page.

**Comment by gonetz** [comment]
Fixed?

**Comment by deuxsonic** [comment]
Yes, it was a problem with the emulator.

**Comment by vgturtle127** [comment]
@deuxsonic Please report this to the Project64, Mupen64Plus, and 1964 CE teams on GitHub. I frequent all three, if you need anything while there.
