### ISSUE TITLE
PilotWings blend mode hack still needed?

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1348]
#define hack_pilotWings	(1<<5) //Special blend mode for PilotWings

I saw in the code this hack and was wondering if it was still useful.

**Comment by gonetz** [comment]
Yes, it turns yellow boxes into whales.

**Comment by olivieryuyu** [comment]
even with the new blender?

**Comment by gonetz** [comment]
I think, it is coverage related.

**Comment by olivieryuyu** [comment]
oh damn!
