### ISSUE TITLE
Many texrects do not appear when using 'Render 2D elements in N64 resolution' (refactor_graphics)

### ISSUE THREAD

**Issue by Aquatakat** [gonetz/GLideN64#1361]
Both games seem to be rendering repeatedly to a background frame buffer?

![image](https://cloud.githubusercontent.com/assets/9537912/22680865/9aab67f6-ecc7-11e6-94d2-fff4ef6c8e97.png)

Also Tetrisphere's menu doesn't appear. Everything else looks OK, especially frame buffer effects in both games.

**Comment by Aquatakat** [comment]
The New Tetris is also missing a lot of graphics:

![image](https://cloud.githubusercontent.com/assets/9537912/22681014/5ab36dfa-ecc8-11e6-8595-5e4a8734e7fb.png)

**Comment by Aquatakat** [comment]
I played a bit more with these games and the problem doesn't occur when 'Render 2D elements in N64 resolution' is disabled.

**Comment by gonetz** [comment]
Strange. This functionality is not implemented at all in that branch.

**Comment by Aquatakat** [comment]
I was going to do some comparison images for you in The New Tetris but when that feature is enabled nothing appears in menus for me making them hard to navigate. That lack of rendering probably explains the repeating image I have in Aidyn Chronicles and Tetrisphere.

**Comment by gonetz** [comment]
'Render 2D elements in N64 resolution' is re-implemented.  New binary:
https://drive.google.com/file/d/0B0YqMPjGo3B2aDdiUHdEWV9tNjg/view?usp=sharing

The problem should be fixed now.

**Comment by Aquatakat** [comment]
Looks perfect again.

![image](https://cloud.githubusercontent.com/assets/9537912/22914543/43d12738-f22e-11e6-8691-b03844ddcbe0.png)
