### ISSUE TITLE
Polygons don't meet when using N64-style depth compare and AA

### ISSUE THREAD

**Issue by Aquatakat** [gonetz/GLideN64#1362]
This issue does not occur with XG-2

![image](https://cloud.githubusercontent.com/assets/9537912/22681696/dce659f6-eccb-11e6-943e-eda2d745f6db.png)

**Comment by gonetz** [comment]
Which build you are using for testing? The branch updated often.

**Comment by Aquatakat** [comment]
184ff8f

**Comment by gonetz** [comment]
10 days old. Can you build current state?

**Comment by gonetz** [comment]
Please test with current build:
#1364

**Comment by Aquatakat** [comment]
The problem hasn't changed with 8004dc2.

**Comment by AmbientMalice** [comment]
That kinda looks like an accurate N64 depth issue.

**Comment by Aquatakat** [comment]
You're right - it only happens when N64 depth compare is on.

@gonetz I'll let you close this issue if you like seeing as it's an experimental feature.

**Comment by AmbientMalice** [comment]
Well, accurate N64 depth seems bugged with TWINE in this branch, so there's obviously something that needs fixing.

**Comment by oddMLan** [comment]
![imagen](https://cloud.githubusercontent.com/assets/7278372/22724299/7be32fc8-ed82-11e6-96cc-d6d12ae0d8b1.png)

Could reproduce with AA enabled. With AA disabled it doesn't happen

**Comment by gonetz** [comment]
I tested accurate N64 depth with other games. It works for me and should work for you. I run it without AA.

**Comment by Aquatakat** [comment]
Yes it's fine with AA disabled.

![image](https://cloud.githubusercontent.com/assets/9537912/22725081/ffa21ab8-ed87-11e6-96f3-b756b7b00326.png)

**Comment by AmbientMalice** [comment]
I'm not using AA, and I'm getting a sort of shimmering distortion on objects in TWINE.

**Comment by Aquatakat** [comment]
![image](https://cloud.githubusercontent.com/assets/9537912/22725123/5bf369d4-ed88-11e6-877c-f601507b22f9.png)

I changed the title

**Comment by gonetz** [comment]
Please test with new build:
https://drive.google.com/file/d/0B0YqMPjGo3B2aDdiUHdEWV9tNjg/view?usp=sharing

**Comment by Aquatakat** [comment]
Same problem unfortunately. I noticed the OSD works again though:

![image](https://cloud.githubusercontent.com/assets/9537912/22914445/c0e615e0-f22d-11e6-9a0d-e46e8381a33e.png)

**Comment by Aquatakat** [comment]
![image](https://cloud.githubusercontent.com/assets/9537912/22915084/f6c3002a-f231-11e6-9b32-a8394e4b263d.png)

I've noticed that the problem is milder when using 2x AA, so maybe that means it's only happening on pixels that AA is trying to change?

**Comment by gonetz** [comment]
It is not refactor_graphics branch regression. Current Release works the same. It can be explained. Depth buffer is single sampled when N64 depth compare is on. Depth compare fails between polygons because its continuity becomes broken on polygons bounds in case of multisampling. I hardly can fix it, so lets consider it as "feature": N64 depth compare is incompatible with MSAA.

**Comment by Aquatakat** [comment]
Sure.

**Comment by Frank-74** [comment]
I don't get the polygons don't meet with N64 depth compare and 2xAA problem.  But I do get distant objects appearing in front of near objects.  IntelHD Graphics.  GL 4.0 support.

![gliden64_extremeg_002](https://cloud.githubusercontent.com/assets/11056843/22946065/43301be8-f2ee-11e6-8334-3f87c04d966c.png)
