### ISSUE TITLE
Ubuntu [16.04] -- can't build

### ISSUE THREAD

**Issue by Dorzalty** [gonetz/GLideN64#1371]
Hello,

I'm trying to build GLideN64 for Ubuntu (for Mupen64Plus), however, the [steps from here](https://github.com/gonetz/GLideN64/wiki/Build-From-Source-(Linux)) do not work. After I try these steps:

chmod +x getRevision.sh
./getRevision.sh

I get this on the second step: 

fatal: Not a git repository (or any of the parent directories): .git current revision ""

Following the note in the instructions, I went to create a "Revision." file, however, it already existed. I opened it to change it from "#define PLUGIN_REVISION """ to "#define PLUGIN_REVISION "1"" and reran the steps. However I got the same issue. I looked back into the file and saw that it reverted back. So I moved it to the desktop and created a new one with "#define PLUGIN_REVISION "1"", however it reverted again once I ran the steps.

What am I doing wrong here?

Thanks!

**Comment by gonetz** [comment]
getRevision.sh creates Revision.h file using unformation from git repository. If you created Revision.h manually, don't run getRevision.sh, go to next step.

**Comment by Dorzalty** [comment]
Oh! Thank you so much! I just went to the next step (mkdir step), made the plugin and cp it to the correct location. 

However using it in the emulator results in a black screen with audio. Switching back to rice fixes it though, so I think I messed something up. I didn't get any errors or dependency warnings and I built off of Release 2.0, so I don't know what I might have done.

Should I try an older release? Or try to remake it?

**Comment by gonetz** [comment]
It can be problem with Mesa driver. Check this thread:
https://github.com/gonetz/GLideN64/issues/1313

**Comment by loganmc10** [comment]
@Dorzalty you need to do this before launching:
```
export MESA_GL_VERSION_OVERRIDE=3.3COMPAT
```
This is fixed in the "refactor_graphics" branch if you want to give that a try, it will make it's way into the master branch eventually.

**Comment by Dorzalty** [comment]
That did it guys! Thank you so much! 

Oh, and just out of curiosity, does this plugin support custom texture loading by any chance?

@loganmc10 

I'll give the branch a try! :)

**Comment by loganmc10** [comment]
Yes you can look in ~/.config/mupen64plus/mupen64plus.cfg for the options

Some relevant options:
```
txHiresEnable - Use high-resolution texture packs if available.
txPath- Path to folder with hi-res texture packs.
```

**Comment by Dorzalty** [comment]
Thanks for the info @loganmc10! 

I just built from the branch and it went well. I'll go to the .cfg file now. :)

**Comment by Dorzalty** [comment]
Hello,

It took me a moment earlier to get it installed on my Ubuntu because of missing dependencies, but yup, I got M64Py too. I prefer it to CuteMupen by a lot. Way easier to use and is just cleaner looking. :)


Oh, and for the textures...are we supposed to place the .htc files within " /home/USER/.local/share/mupen64plus/hires_texture" (specified in the cfg) or within a folder within "hires_texture"? I can't seem to get command Mupen64Plus or M64Py to actually load the files.

**Comment by gonetz** [comment]
within a folder within "hires_texture"

Path in config points on original texture pack with png textures. GLideN64 converts png to Open GL textures and stores result in .htc file within a folder within "hires_texture"

**Comment by Dorzalty** [comment]
Ah! Then I must have done something wrong with my .htc placement within hires_textures. lol thank you for all the help, I really appreciate it. :)

**Comment by gonetz** [comment]
I was wrong. .htc saved in cache folder for mupen64plus
On Linux it should be 
~/.cache/mupen64plus/

**Comment by Dorzalty** [comment]
I see! I do not seem to have that folder. It should work fine if I create it myself, right?

**Comment by gonetz** [comment]
Yes, you can create it. I checked again, on Ubuntu .htc file must be in
~/.cache/mupen64plus/cache/

**Comment by Dorzalty** [comment]
Okay, I created it, but it doesn't load the .htc file when placed in "/home/USER/.cache/mupen64plus" or if I make a "cache" folder within that folder. Strangely enough, when I press configure on the plugin within M64Py it points to here for the tx path:

/home/user/.local/share/mupen64plus/hires_texture

however that doesn't load the files either. I'm really confused now.

**Comment by gonetz** [comment]
>  when I press configure on the plugin within M64Py it points to here for the tx path:

/home/user/.local/share/mupen64plus/hires_texture


This is because "Path in config points on original texture pack with png textures." 

 Be sure that you have hires textures option enabled.  Also, you may enable texture enhancement  option, hq4x for example. Plugin will save enhanced textures in .htc file when you exit the game. That way you will get correct name for hd texture cache file for your game.

**Comment by Dorzalty** [comment]
So that path requires or points to a dump of the original texture pngs? Oh!

I believe I had the correct options enabled to load the [.htc from here](http://www.emutalk.net/threads/53556-Merry-Xmas-OOT-2011-and-MM-2001?p=443121&viewfull=1#post443121). I checked this option within the plugin menu:

http://i.imgur.com/wL42B2o.png

**Comment by gonetz** [comment]
> I believe I had the correct options enabled to load the .htc from here.

You had to say it from the start.
So, your path to file must be
`~/.cache/mupen64plus/cache/THE LEGEND OF ZELDA_HIRESTEXTURES.htc`
Required options:
* txHiresEnable
* txHiresFullAlphaChannel

Options, which **must be off** 
* txForce16bpp
* txHiresAltCRC

**Comment by Dorzalty** [comment]
I'm terribly sorry for not saying that from the start. I foolishly thought they were all the same so it didn't matter. 

Anyways, that did it! Turning those options off and placing the htc here _/home/USER/.cache/mupen64plus/cache_ like you said loaded the textures right up! 

Thank you so much for all the help. :)

**Comment by gonetz** [comment]
>  I foolishly thought they were all the same so it didn't matter.

Actually, content of .htc file depends on options I mentioned. If your current options does not correspond the .htc file, it is removed and re-created from png textures. It is in normal case, where you have texture pack with png textures. Djipi does not provide texture pack in png form, he uses .htc as some kind of DRM protection. Thus, it is important to use the same settings, as he used.

Since the problem solved, I close it.
