### ISSUE TITLE
S.C.A.R.S. segfault at race start.

### ISSUE THREAD

**Issue by shadowflash** [gonetz/GLideN64#1373]
Emulator (mupen64plus 2.5.0) crashes with this: 
python3: /build/mupen64plus-video-gliden64-UEsFVf/mupen64plus-video-gliden64-2.0/src/Textures.cpp:1464: void TextureCache::update(u32): Assertion `current.width == sizes.width' failed.

It happens exactly when you are about to see green light and start the race.

**Comment by gonetz** [comment]
Should be fixed with f42823478
