### ISSUE TITLE
Settings won't save

### ISSUE THREAD

**Issue by Suckabackyem** [gonetz/GLideN64#1375]
Hi
First time using this plugin so I don't know if the settings not saving is intentional or not.
Basically I use a 4K Monitor and the native resolution is VERY small on my screen. If a 1080p image is one quarter of my resolution just imagine how small 480p is.

I tried to change the resolution in the settings but when I hit ok and open the settings again, everything has been reverted back to default. Can someone please help me here because if I can't change the settings then this plugin is a bit useless for me :/

I made a gif showing my issue.
https://media.giphy.com/media/l3q2WazT2zaOrZE7C/source.gif

**Comment by AmbientMalice** [comment]
You need to run PJ64 with administrative permissions.

**Comment by Suckabackyem** [comment]
Haha wow, I am honestly surprised I didn't think of that. Thanks for your help :D

**Comment by gonetz** [comment]
Fixed, I suppose.
