### ISSUE TITLE
Mahjong Hourouki Classic: background color issue during intro

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#138]
during the intro, the background here is brown instead of being black.

![screen52](https://cloud.githubusercontent.com/assets/8987490/5042214/7ebf25e2-6bd1-11e4-9cad-5a53fc17cf69.jpg)

**Comment by olivieryuyu** [comment]
can it be fixed?

**Comment by gonetz** [comment]
Not checked it yet

**Comment by gonetz** [comment]
Fixed
