### ISSUE TITLE
Not an issue: Request mult htc support

### ISSUE THREAD

**Issue by Nes-player4Life** [gonetz/GLideN64#1383]
Requesting feature to allow separate htc's to be loaded upon users selection.
{Selection box} Htc
{Selection box} Htc2
{Selection box} Htc3
{Selection box} Htc4 loads Filename.Htc4

**Comment by gonetz** [comment]
This must be per game setting. It is hard.
I can suggest a compromise : select folder to store/load htc file

**Comment by Nes-player4Life** [comment]
I like that compromise. At the moment all htc's are loaded from /cache would you allow this directory to include subdirectories, or htc's loaded only from /cache but allow the user to chose the logical location of the directory. Such as how the Hires_textures directory is selected.

**Comment by gonetz** [comment]
> Such as how the Hires_textures directory is selected.

Yes, that way.

**Comment by gonetz** [comment]
I added 2 new config options: path to cache folder and path to folder with texture dumps.
.htc files loaded from cache folder, so you may put different .htc for the same game into different folders and switch between them using this config option. By default cache folder is Plugin\GFX\cache for Project64. It is standard cache folder in case of mupen64plus.

Test build for mupen64plus:
https://drive.google.com/file/d/1cIKYGdQCJF_lLZpB0bLAJz01Gxb737yn/view?usp=sharing

Project64 build needs changes in GUI.
@Aquatakat, could you make these changes?
Code is in branch https://github.com/gonetz/GLideN64/tree/texture_cache_path
Changes required in Texure enhancement tab => Texture pack subtab. It has option 'Texture pack path'. It is necessary to add two new paths: "Texture cache path" for resulted .htc textures and "Dumped textures path" for textures to dump. I tried to make these changes myself, but I don't quite understand how it is made now.

**Comment by gonetz** [comment]
@Nes-player4Life  I have made draft support of that feature in GUI.
Test build: 
https://drive.google.com/file/d/1ZqNpl3ehUxD2sx_r6Exv87wsy2AjRf1Q/view?usp=sharing
