### ISSUE TITLE
LoZ:OOT Community Texture Pack 7 white lines [newbie]

### ISSUE THREAD

**Issue by ailin-nemui** [gonetz/GLideN64#1384]
![screenshot from 2017-02-18 21-44-25](https://cloud.githubusercontent.com/assets/5665186/23096796/6925cd14-f624-11e6-8277-a69c5a2fdfb8.png)

Why does it happen? Can I fix it? Mupen64+ 2.5 / GLideN64 eb2ce86 / [Texture V7](http://www.emutalk.net/threads/55307-Zelda-Ocarina-of-time-Community-Retexture-Project-V7) / Nvidia GTX 750

Thanks for your help!

**Comment by Nes-player4Life** [comment]
Miss-aligned from inferior Rice texture development.

**Comment by gonetz** [comment]
> Can I fix it?

Yes, if you are texture artist: find these textures and make them properly.

**Comment by gonetz** [comment]
Duplicate of #611, #1140

**Comment by ailin-nemui** [comment]
Thanks, for reference to the fix http://www.emutalk.net/threads/55307-Zelda-Ocarina-of-time-Community-Retexture-Project-V7?p=459707&viewfull=1#post459707

**Comment by gonetz** [comment]
At last someone did it. 
@Nes-player4Life You could point on this fix from the start.

**Comment by Nes-player4Life** [comment]
I forgot all about it. Apologies @gonetz
