### ISSUE TITLE
Mia Hamm Soccer 64: missing title screen, missing VI transition effects

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#139]
missing title screen, here in LLE software

![mia2](https://cloud.githubusercontent.com/assets/8987490/5042322/66cea4ec-6bd3-11e4-87c2-a4922fee2f19.jpg)

missing VI transition effects, here in LLE software. If fb is on, GLideN64 sent a checkFBO() error. 

![mia3](https://cloud.githubusercontent.com/assets/8987490/5042327/7912db5a-6bd3-11e4-9cd4-24b932387f76.jpg)

**Comment by olivieryuyu** [comment]
fixed

**Comment by gonetz** [comment]
Really? When?

**Comment by olivieryuyu** [comment]
well here what i can get with Mupen.

![c91a6b7e-cdb9-11e5-9ce4-874ec8bd928d](https://cloud.githubusercontent.com/assets/8987490/12945200/329e7692-cfec-11e5-81f1-f33cd696d52f.jpg)

So the title appears (super!!!) and the transition effects kinda works.

There is however a downsize: the transition effect, which looks like framebuffer based effect, is screwing up the menu. I was to open a new ticket about it when i got a internet connection lost. Will create a new ticket accordinlgy.
