### ISSUE TITLE
[Feature Request] Configurable hotkey for enabling/disabling Vsync

### ISSUE THREAD

**Issue by DonelBueno** [gonetz/GLideN64#1390]
It would be nice being able to disable Vsync when you disable the framelimiter (F4 on P64), so you can go past 60 fps when you want to speed up the gameplay, but also to enable it back to avoid screen tearing when you are on 60 fps (framelimiter enabled).

Since GLide can't have control over this, the idea is to have a configurable hotkey to toggle Vsync on the fly.

Discussed in issue #1364

**Comment by DonelBueno** [comment]
@gonetz, any idea on when you will be able to implement this?

**Comment by gonetz** [comment]
Implemented in #1497.
I close this task.
Please report in #1497 if something does not work.
