### ISSUE TITLE
Building with clang causes graphics glitches when HW Per pixel lighting is enabled

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1391]
I'm getting a strange graphical glitch when building with clang in Android. Mario's hat keeps switching between brown and the normal red color. I'm not sure what's causing that. @gonetz Have you seen this type of glitch before?

None of the other graphics plugins show different behavior when clang is used, at least it seems.

**Edit 1**
I managed to narrow it down with it being an issue with HW Per pixel lighting. Somehow we are getting a different result somewhere.

**Comment by fzurita** [comment]
It's one of the VEC4 optimizations...

**Comment by gonetz** [comment]
That's strange. Math is used to calculate lighting when HW lighting is off. This, problems with Neon asm should rather be without HW lighting.

**Comment by gonetz** [comment]
"Android NDK: GCC is now deprecated, everyone should be switching to Clang"
This is not a news for more than year, but I read about it only now. OMG!

**Comment by fzurita** [comment]
Yep, I had

**Comment by fzurita** [comment]
It's InverseTransformVectorNormalize that is the problem. I must be doing something bad in my implementation.

**Comment by fzurita** [comment]
@gonetz Btw, now that we are using clang in Android, debugging works well now. The code is actually stopping at my break points.

**Comment by gonetz** [comment]
Good to know,  thanks

**Comment by fzurita** [comment]
Fixed now with Gizmo's fixes.
