### ISSUE TITLE
"Original N64 Resolution" breaks Majora's Mask (E)

### ISSUE THREAD

**Issue by SigmaVirus** [gonetz/GLideN64#1396]
This setting is causing all sorts of trouble with Majora's Mask
![setting](https://cloud.githubusercontent.com/assets/14175085/23297997/17082a16-fa7c-11e6-9640-6e3f9f775f5b.png)

Result 1:
![result](https://cloud.githubusercontent.com/assets/14175085/23298026/3e9cb074-fa7c-11e6-9d26-1e743d9ad352.png)

Result 2:
![result 2](https://cloud.githubusercontent.com/assets/14175085/23298059/5de088a2-fa7c-11e6-86b1-0602f627092d.png)

If I however set the "Internal resolution" option to "Same as output resolution" everything works properly again.

When set to "Original N64 Resolution", toggling between fullscreen temporarily fixes the problem but you're in for a ride if you try to enter the Bomber Notebook which makes the screen shake again.
And if it starts to shake again and you try to take a picture all sorts of fun visual glitches can occur.

I have tested this with Public release 2.0 and the latest download from here;
https://github.com/gonetz/GLideN64/issues/1364 called GLideN64_7139e5b.7z

These are my specs:
i7 4790K at stock
ASUS Nvidia 1060 6GB
16GB RAM
Windows 10 x64

I've tried all of my other games and this game seems to be most affected.

**Comment by gonetz** [comment]
Screen shakes only with (E) version. Camera does not work with (U) too.

**Comment by SigmaVirus** [comment]
OK, thanks for clarifying this Gonetz!

I take it you mean the camera is broken with (USA) set to "Original N64 Resolution" also?
Because everything in the game seems to work properly when set to "Same as output resolution"

I also want to stress out that I have only changed two options (3-Point Bilinear & Original N64 Resolution) and left everything defaulted. 

What could be causing the shakes in the European version?

**Comment by gonetz** [comment]
Yes, camera does not work only with native resolution.
Shakes in the European version most likely caused by an issue in Video Interface emulation.

**Comment by gonetz** [comment]
I see the problem. It will (hopefully) be fixed, but not soon.

**Comment by SigmaVirus** [comment]
Glad to hear it, there's no rush so take your time.
Maybe it will fix the rest of the small issues I had with this option as well.

**Comment by ichee** [comment]
Screen shaking occurs in (U) version as well, but only in bombers notebook. With Original N64 resolution enabled, it can be fixed by enabling "Copy auxiliary color buffers to N64 memory" or by disabling "Emulate frame buffer". Also, the camera can be fixed by disabling "Enable N64-style depth compare", although, at least in (U) version, there is a long delay in taking pictographs.

**Comment by gonetz** [comment]
Shakes in the European version is fixed with #1414
Camera still does not work in native resolution.

**Comment by gonetz** [comment]
Camera fixed too.

**Comment by SigmaVirus** [comment]
@gonetz 
Cool, thanks for fixing it!

Any chance of a test build so I can try it out?

**Comment by AmbientMalice** [comment]
@SigmaVirus 

Here. https://github.com/gonetz/GLideN64/issues/1364#issuecomment-287617539

**Comment by gonetz** [comment]
Yes, #1364, latest build.

**Comment by SigmaVirus** [comment]
Thanks, it seems like most of my problems have been solved now, however something new just happened.
After you take a picture with the camera the entire screen starts to flash/shake like crazy and it only goes away if I toggle fullscreen.

It's hard to take a screenshot of this because it don't show what's happening.

**Comment by gonetz** [comment]
Please disable shader cache and test again. I see no shaking/flashing.

**Comment by SigmaVirus** [comment]
OK, disabling shader cache worked and I don't see anymore issues here.
I think this can be closed now, but feel free to reopen if not.

Thanks for all your help!

**Comment by gonetz** [comment]
@SigmaVirus Thanks for bug reports
