### ISSUE TITLE
Ocarina of Time subscreen crash (new)

### ISSUE THREAD

**Issue by ichee** [gonetz/GLideN64#1400]
Ocarina of Time crashes when opening the subscreen with "Copy auxilary color buffers to N64 memory" enabled.

**Comment by fzurita** [comment]
That option seems to break many things. I wonder if there would be a way to auto detect when it's needed.

**Comment by AmbientMalice** [comment]
>I wonder if there would be a way to auto detect when it's needed.

Unlikely, because whether it is needed is completely subjective. It's an accuracy improvement. The reason the game is crashing is likely the subscreen white hack.

**Comment by gonetz** [comment]
>  The reason the game is crashing is likely the subscreen white hack.

Hardly. Subscreen white hack enabled for main buffers, not for auxiliary ones. Usually, if  "Copy auxilary color buffers to N64 memory" leads to crash it means that height of the buffer detected incorrect and some useful data in RDRAM was overwritten during buffer copy to RDRAM.

I changed buffer height calculation in "VI refactoring" branch. Currently I have no crash with that option.

**Comment by AmbientMalice** [comment]
>I changed buffer height calculation in "VI refactoring" branch. Currently I have no crash with that option.

Wonderful news.

**Comment by ichee** [comment]
Fixed with refactor merge.
