### ISSUE TITLE
[LLE] Weird brightness striping issue

### ISSUE THREAD

**Issue by ichee** [gonetz/GLideN64#1401]
Brightness is striped looking, almost trajectory oriented, when when run in LLE. Happens mostly the same way with all games. Doesn't occur in HLE.

With LLE:
![glitch](https://cloud.githubusercontent.com/assets/22252639/23395653/bd6fd9f6-fd5d-11e6-8080-f7f4f932e16b.PNG)

With HLE:
![fine](https://cloud.githubusercontent.com/assets/22252639/23395861/ceccfade-fd5e-11e6-8111-30d675d9c890.PNG)

**Comment by olivieryuyu** [comment]
fixed?

**Comment by gonetz** [comment]
Hardly.

**Comment by gonetz** [comment]
Should be fixed now.
