### ISSUE TITLE
Status of building on MacOS?

### ISSUE THREAD

**Issue by fprimex** [gonetz/GLideN64#1405]
Hi, I've been contributing to [mupen64plus-gui](https://github.com/m64p/mupen64plus-gui) a bit, so I thought I would try to get the full program compiled on my Macbook Air. I've made a lot of progress, but I'm getting hung up where shaders are coming in to play. My Macbook Air of course has Intel graphics.

I'm using nasm and sdl2 from homebrew. Just looking for some input on what I should do from here. Do I need to install mesa from homebrew and try that, or is there some other approach I should be taking? Are there Mac specific build instructions? Are Intel Macs just doomed and I should build on my old Mini? Thanks.

I can dump more details, patches, errors, etc if that turns out to be needed / useful. Just haven't had time to do it all up proper and have just been hacking at it.

**Comment by gonetz** [comment]
Hello,

The main problem with MacOS port was lack of core profile support. MacOS requires to use core profile to access OpenGL 3.3 functions. This problem is currently solved. So, it is time to try to port the code again. The main problem now is that besides lack of free time I have no Mac.

Regarding Intel graphics, it should work but there were several issues related to it. I can't help there because I don't use Intel graphics.

**Comment by gonetz** [comment]
@fprimex I fixed compilation on Mac. I don't know, does the plugin actually work or not, I fixed only compilation and link issues. You may build and try it on your Macs.  To build:
* cd projects/cmake
* cmake -DMUPENPLUSAPI=On ../../src/

Then copy plugin/release/mupen64plus-video-GLideN64.dylib to mupen64plus plugins folder. I don't know where it is located on Mac.

**Comment by fprimex** [comment]
Thanks! I will give this a shot as soon as I can.

**Comment by fprimex** [comment]
Appears to have done the trick, even on my Intel graphics system: MacBook Air (11-inch, Early 2015). Not commenting on performance at all, though. I'll do some other issues for that if any come up that are reproducible and not the fault of weak, integrated hardware.

**Comment by gonetz** [comment]
Please attach a screenshot or two with GLideN64 running on MacOsX. You may enable VI or percent counter to show actual performance.

**Comment by fprimex** [comment]
[Video](https://1drv.ms/v/s!AjDZIIpQcHVngRcQGPLSlFQmXKhv) (8.3MB)

Note that this video is recorded with a demo of ScreenFlow and then encoded as an mp4. It's pretty representative of what I see without recording, and includes the garbled bit of audio accurately. A lossless video is ~470MB so I didn't provide that one.

Unfortunately, for some reason if I enable any counters I get a black screen. The audio plays so I know emulation is progressing. I haven't looked into that further.

**Comment by gonetz** [comment]
Great, thanks!  Good to see that it actually works. Don't you mind if I upload it on YouTube?

**Comment by fprimex** [comment]
By all means, please go ahead. If anyone has a licensed version of screenflow ($100 USD) I can provide either the mupen app package to run or full movie projects to remove the watermark.

**Comment by gonetz** [comment]
I don't think it is necessary. This simple proof is enough. Mac users now can check how it works themselves.

Did you have any problems with building the plugin? May be it is time to create wiki instruction, how to build for Mac.

**Comment by GB-CG** [comment]
@fprimex Have you thought of using OBS Studio to capture the footage instead?

**Comment by fprimex** [comment]
I have not done any game recording or streaming so I just went with what I knew - screencast software. I installed SoundFlower and can use Quicktime Player to record stuff with audio now. I got OBS but haven't set it up yet.

**Comment by fprimex** [comment]
> Did you have any problems with building the plugin? May be it is time to create wiki instruction, how to build for Mac.

After pulling master I just used the normal unix instructions. There is one change that could be make to the CMakeLists.txt to shut up the rpath warning. I'm sure I'll be rebuilding a lot so I'll get it written up. Happy to contribute to the wiki.

**Comment by santiagoitzcoatl** [comment]
@fprimex which version of MacOSX are you using?

I successfully built the plugin for Mac but I can't get to run mupen64plus with it.
I got this error: 

`Core Error: SDL_SetVideoMode failed: Failed creating OpenGL context at version requested`

could you share your setup or a compiled  mupen64plus app with GLideN64 in it, please?

**Comment by fprimex** [comment]
@santiagoitzcoatl The last build I did with my own scripts was a very long time ago. I may have one more recent than this, but this is the one I have in my onedrive:

https://1drv.ms/u/s!AjDZIIpQcHVngS8xtIDusDaEW4e4

I was using whatever the latest MacOS was at the time, I'm pretty sure. If I were to try again, should I use master or is the newest MacOS build stuff in a PR or branch?

**Comment by santiagoitzcoatl** [comment]
@fprimex thanks for the file.

It runs with issues.

Btw, it only rant once, and after that it couldn't locate the plugins anymore and crashed.
It also rewrote my config file for my other mupen64plus versions. 

I fixed this by taking the plugins and the core library out of the app container and pointed the directories accordingly from the app configuration. 
> _– It's a hack but works._

Now it runs almost properly, 👍 
I will try to change some of the configuration and see if I could get it working without issues and report back. Probably a more recent build will do better. Thanks again.

I'm not sure about how MacOS versions are handled in this repository, I'm sorry.
But it seems there's no specific branch for MacOs versions or something similar.

...btw I'm still running an old OS (10.10)

**Comment by santiagoitzcoatl** [comment]
@fprimex I have the same issue as this with **mupen64plus-gui**

https://github.com/m64p/mupen64plus-gui/issues/33
