### ISSUE TITLE
Dr. Mario 64 framebuffer problem

### ISSUE THREAD

**Issue by LuismaSP89** [gonetz/GLideN64#1408]
If you use the framebuffer on "Tried default and custom settings" Dr. Mario looks fuzzy and pixelated, it doesn´t upscale nothing, and the image filters like xbrz or hq doesn´t work.

If you use the framebuffer off, the game looks as it should be, ok with the filters, ok with upscaling, but when you´re going to start a game and play, all the screen looks corrupted.

If i do a screenshot with the framebuffer on, it looks ok... i don´t understand this... but i remember a issue in goldeneye with the fullscreen mode, where the fire of the weapon´s shot was like a square. Exiting and re-entering fullscreen fixed it, and later, the bug was fixed in a update of GlideN64. I don´t know if that's nearly more or less right, but this doesn´t work in this case.

**Comment by olivieryuyu** [comment]
@LuismaSP89 

Frambuffer cannot be upscaled in this case.

@gonetz 

would you confirm and and if so close?

**Comment by weinerschnitzel** [comment]
IIRC, the pills are cpu drawn. Wouldnt those be the only item that could not be upscaled? (Im not in a location to test this atm)

**Comment by LuismaSP89** [comment]
The thing is, that no matters the config. If you use framebuffer on, it looks totally pixelated (Using a big screen is nearly unplayable) and if you use framebuffer off, when you try to start a game, it looks totally corrupted, and nothing can be seen.

**Comment by oddMLan** [comment]
IMO it doesn't look that bad.
Related #378 (game becomes pixelated due to cpu editing the frambuffer)
and #791 (possible solution)

**Comment by LuismaSP89** [comment]
Solved with the latest changes 4 days ago. Closing.
