### ISSUE TITLE
Build From Source (Linux)  

### ISSUE THREAD

**Issue by aperfeito** [gonetz/GLideN64#1411]
If you create the Directory build cmake give this error :   
      [aperfeito@alarm build]$ cmake -DMUPENPLUSAPI=On
CMake Error: The source directory "/home/aperfeito/Downloads/mupen64plus-libretro/GLideN64/src**/build**"  **"Create as Wiki"** does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
    
     If you not Create and running the cmake as : cmake -DMUPENPLUSAPI=On the MakeFile is create and when you run make this is happend:

  [ 97%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/BufferCopy/ColorBufferToRDRAM_GL.cpp.o
[ 98%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/BufferCopy/ColorBufferToRDRAM_BufferStorageExt.cpp.o
[100%] Linking CXX shared library plugin/release/mupen64plus-video-GLideN64.so
GLideNHQ/lib/libpng.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/mupen64plus-video-GLideN64.dir/build.make:1663: plugin/release/mupen64plus-video-GLideN64.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:69: CMakeFiles/mupen64plus-video-GLideN64.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

   I compile from the source using : Linux alarm 3.10.18-18-ARCH #5 SMP Mon Feb 20 14:21:15 PST 2017 armv7l GNU/Linux

**Comment by loganmc10** [comment]
You are missing the ```..```

The wiki says to do:
```cmake -DMUPENPLUSAPI=On ..```

Not:
```cmake -DMUPENPLUSAPI=On```

**Comment by aperfeito** [comment]
Yeah The problem is not a cmake is good OK the issue is when do make

________________________________
De: Logan McNaughton <notifications@github.com>
Enviado: sexta-feira, 10 de março de 2017 18:35:25
Para: gonetz/GLideN64
Cc: Alexander Nunes Perfeito; Author
Assunto: Re: [gonetz/GLideN64] Build From Source (Linux) (#1411)


You are missing the ..

The wiki says to do:
cmake -DMUPENPLUSAPI=On ..

Not:
cmake -DMUPENPLUSAPI=On

**Comment by aperfeito** [comment]
Logan ,


     As  you said in the wiki I do cmake -DMUPENPLUSAPI=On ..

       Create the directory build inside and when I do make this happend below :


[100%] Linking CXX shared library plugin/release/mupen64plus-video-GLideN64.so
../GLideNHQ/lib/libpng.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/mupen64plus-video-GLideN64.dir/build.make:1663: plugin/release/mupen64plus-video-GLideN64.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:69: CMakeFiles/mupen64plus-video-GLideN64.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
[aperfeito@alarm build]$



________________________________
De: Alexandre Perfeito <perfeitona@outlook.com>
Enviado: sexta-feira, 10 de março de 2017 19:20:28
Para: gonetz/GLideN64
Assunto: Re: [gonetz/GLideN64] Build From Source (Linux) (#1411)


Yeah The problem is not a cmake is good OK the issue is when do make

________________________________
De: Logan McNaughton <notifications@github.com>
Enviado: sexta-feira, 10 de março de 2017 18:35:25
Para: gonetz/GLideN64
Cc: Alexander Nunes Perfeito; Author
Assunto: Re: [gonetz/GLideN64] Build From Source (Linux) (#1411)


You are missing the ..

The wiki says to do:
cmake -DMUPENPLUSAPI=On ..

Not:
cmake -DMUPENPLUSAPI=On

**Comment by loganmc10** [comment]
Yes that is a problem with the CMake scripts. You can get around it by doing this:

```cmake -DNOHQ=On -DMUPENPLUSAPI=On ..```

but it is a bug in the CMake script for GLideNHQ

**Comment by aperfeito** [comment]
Logan ,


      Now its Ok . Update Wiki.

               Thread close


Best Regards

Perfeito, Alexandre

________________________________
De: Logan McNaughton <notifications@github.com>
Enviado: sexta-feira, 10 de março de 2017 20:49:35
Para: gonetz/GLideN64
Cc: Alexander Nunes Perfeito; Author
Assunto: Re: [gonetz/GLideN64] Build From Source (Linux) (#1411)


Yes that is a problem with the CMake scripts. You can get around it by doing this:

cmake -DNOHQ=On -DMUPENPLUSAPI=On ..

but it is a bug in the CMake script for GLideNHQ

**Comment by gonetz** [comment]
>> but it is a bug in the CMake script for GLideNHQ

script needs a parameter to use system libpng. Currently the script silently uses system libpng for some OS.
Script uses pre-built libpng to avoid problems with Ubuntu 14, which has outdated libpng.

**Comment by gonetz** [comment]
> script needs a parameter to use system libpng.

implemented in e32dd5449f6

@aperfeito I guess it can be close now

**Comment by aperfeito** [comment]
I will Test

**Comment by aperfeito** [comment]
First I did git clone all again start to 0 and when

My package  is libpng-1.6.29-1 for ARMv7 Arch kernels current installed

 I compile from the source using : Linux alarm 3.10.18-18-ARCH #5 SMP Mon Feb 20 14:21:15 PST 2017 armv7l GNU/Linux

I test right now 04/19/2017 12:47pm PST give me this as when i run make :

[ 98%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/mupenplus/MupenPlusAPIImpl.cpp.o
[ 99%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/Graphics/OpenGLContext/mupen64plus/mupen64plus_DisplayWindow.cpp.o
**[100%] Linking CXX shared library plugin/release/mupen64plus-video-GLideN64.so
../GLideNHQ/lib/libpng.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/mupen64plus-video-GLideN64.dir/build.make:2339: plugin/release/mupen64plus-video-GLideN64.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:69: CMakeFiles/mupen64plus-video-GLideN64.dir/all] Error 2
make: *** [Makefile:84: all] Error 2**

____________________________________________________________________________
When I did As Logan said before as describe below give the success results

> 
loganmc10 commented on Mar 10
Yes that is a problem with the CMake scripts. You can get around it by doing this:

cmake -DNOHQ=On -DMUPENPLUSAPI=On ..

but it is a bug in the CMake script for GLideNHQ

[ 98%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/Graphics/OpenGLContext/mupen64plus/mupen64plus_DisplayWindow.cpp.o
[100%] Linking CXX shared library plugin/release/mupen64plus-video-GLideN64.so
[100%] Built target mupen64plus-video-GLideN64

The Problem exist .. If user follow the Wiki the Crash in the same problem to build

**Comment by loganmc10** [comment]
Sorry you need to do it this way:

```
cmake -DUSE_SYSTEM_LIBS=On -DMUPENPLUSAPI=On ..
```

**Comment by aperfeito** [comment]
Ok,

  Now I start All again using:

My package is libpng-1.6.29-1 for ARMv7 Arch kernels current installed

I compile from the source using : Linux alarm 3.10.18-18-ARCH #5 SMP Mon Feb 20 14:21:15 PST 2017 armv7l GNU/Linux

I change the orientation as Wiki said in the line 

cmake -DMUPENPLUSAPI=On ..

by as loganmc10 put a minutes ago:

**cmake -DUSE_SYSTEM_LIBS=On -DMUPENPLUSAPI=On ..**

 and 
I test right now 04/19/2017 13:06pm PST give me this as when i run cmake :
Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
**-- Found PNG: /usr/lib/libpng.so (found version "1.6.29")   --> new
-- Found Freetype: /usr/lib/libfreetype.so (found version "2.7.1")** 
-- Found OpenGL: /usr/lib/libGL.so  

and after this I run this command : **make -j5** My case is quad core ARM and give success as you saw below:

[100%] Linking CXX shared library plugin/release/mupen64plus-video-GLideN64.so
[100%] Built target mupen64plus-video-GLideN64

The files as create inside of  build/plugin/release

Now its Ok . Update Wiki.

Close Threated after Wiki will Update for me
