### ISSUE TITLE
Native Resolution misalignment

### ISSUE THREAD

**Issue by ichee** [gonetz/GLideN64#1416]
Games have various textures and text that are misaligned and excessively blurry at native resolution. Looks like a possible 'off by one' issue. Most don't occur at higher than native.

offset:
![offset](https://cloud.githubusercontent.com/assets/22252639/23830671/8db51946-06e6-11e7-9eae-e65cd5f76c4b.PNG)

misaligned:
![offset2](https://cloud.githubusercontent.com/assets/22252639/23830718/b7a40482-06e7-11e7-9b37-dbf0b3906161.PNG)

blurry:
![blurry](https://cloud.githubusercontent.com/assets/22252639/23830673/95a8e330-06e6-11e7-9c2d-6a8f9baf7432.PNG)

**Comment by OldGnashburg** [comment]
Good eye.

**Comment by oddMLan** [comment]
![GLideN64_THE_LEGEND_OF_ZELDA_015](https://user-images.githubusercontent.com/7278372/68371461-00004e00-00fc-11ea-8c6f-61dfa484c803.gif)
Seems to be an off by one error in the VI setup indeed. Notice how angrylion has a 2-pixel row of white pixels at the top. Reminds me of #2100. The white stripe of pixels hides the green garbage pixels of that game. 
@gonetz have any idea what the row of white pixels is supposed to be?

**Comment by gonetz** [comment]
> have any idea what the row of white pixels is supposed to be?

No.

**Comment by gonetz** [comment]
@ichee @oddMLan Could you re-check that issue with the current master?
It should be fixed now with "Use screen coords #2334" merged.

**Comment by ichee** [comment]
Issue seems to be mostly fixed, but neither bilinear filtering options seem to work, and some parts of the image are a bit offset still.

![ocarina](https://user-images.githubusercontent.com/22252639/115513077-ac7eb300-a250-11eb-8678-3edd9f080aea.png)

**Comment by gonetz** [comment]
Here a comparison with AL RDP (without DAC filters)
![ZeldaOOT](https://user-images.githubusercontent.com/8983092/115539369-1a65c180-a2c7-11eb-979d-f3c039fe45fc.png)

Could you point me on the image offset issue here?
Regarding bilinear filtering  - it works. I can see the difference between N64 3 point and standard 4 point bilinear filtering.
The work of bilinear filtering is just not as noticeable as with hi-res.

**Comment by ichee** [comment]
It may just be due to the lack of DAC filters, since angrylion doesn't look as pixelated to me.

Offset pixels I was referring to in above screenshot is where it says 'Death Mountain' and 'Save', though again, it may just be due lack of DAC filter.

On my end, however, 'standard' and '3 point' look the same, as if neither take effect.

Running on Windows 10 with an Nvidia GPU, if relevant.

**Comment by weinerschnitzel** [comment]
@ichee bilinear filter will affect textures that are bilinear filtered. It shouldn't be confused with a forced bilinear filter for all textures or filter on output result.

The difference between 3 point and traditional bilinear filtering is very noticeable on the stairs in Kakariko Village. 

Have a look here:  http://filthypants.blogspot.com/2014/12/n64-3-point-texture-filtering-in.html?m=1

**Comment by gonetz** [comment]
The original issue is fixed.
