### ISSUE TITLE
Aidyn Chronicles menu icons enlarged or text cut

### ISSUE THREAD

**Issue by ichee** [gonetz/GLideN64#1420]
In the inventory menu, the icons next to items appear to be enlarged or stretched.

![enlarged](https://cloud.githubusercontent.com/assets/22252639/23898789/d602068e-0888-11e7-9e4d-2b9170f2a302.PNG)

When toggling fullscreen with menu closed, icons are corrected, but some of the text is cut off.

![alignment](https://cloud.githubusercontent.com/assets/22252639/23898653/355b5afa-0888-11e7-8163-17f066eb63f9.PNG)

Toggling fullscreen while on inventory screen corrects both issues.

![normal](https://cloud.githubusercontent.com/assets/22252639/23898693/5b9aaf40-0888-11e7-8546-3d3b4bf8423c.PNG)

Neither issue are present on 1.2.

**Comment by gonetz** [comment]
Fixed.

**Comment by gonetz** [comment]
@ichee please test and close.

**Comment by ichee** [comment]
Confirmed working normally now.
