### ISSUE TITLE
Right place for platform optimized code snippets

### ISSUE THREAD

**Issue by gizmo98** [gonetz/GLideN64#1427]
I optimized a part of an existing function for arm neon which runs 6x faster now. I do not want to replace the whole function. So i used "#ifdef __ARM_NEON__" macro to replace existing code with an optimized neon function if CFLAGS define "-mfpu=neon". I placed the optimized code snippet in ./arm/neon_opt.h and include this file if __ARM_NEON__ is defined. So the original c file will not be bloated with assembler or intrinsics for different platforms.

Example:
https://github.com/gizmo98/GLideN64/commit/747f0d2efa9d19c160bda3f5de7a0b96878b2a49

I don't know if this is the right way. Any suggestions?

**Comment by gonetz** [comment]
I think it will depend on case. RSP_LoadMatrix already looks ugly and your changes do not make it much worse. However, you asked about the right way. IMO, the right way is to move matrix load code to separate cpp files: LoadMatrix.cpp, LoadMatrix_x86.cpp, LoadMatrix_x64.cpp, LoadMatrix_neon.cpp and correct project files.

**Comment by gizmo98** [comment]
I also think this is the best way if a whole function is replaced. But what should be done if only a small part like a loop of a big function is optimized? Create a c function and a neon function of the loop or use #ifdef?

**Comment by gonetz** [comment]
Idea to optimize everything with asm code looks suspicious for me. Current compilers can optimize code  very well. Are you sure that your code works noticeably faster?

In case where you are sure that you can write better code than compiler, it should be separate function imo. Such function will be inlined by link time optimization with great probability.

**Comment by gizmo98** [comment]
I compared runtimes of some 3DMath functions. No matter which optimization level was used neon asm was always faster. GCC cannot autovectorize for arm neon very well. I wrote the above sample code with a loop and gcc produced code which was two times slower with -O0-O2. With -O3 it was smart enough to produce code with a comparable runtime. C code was still 6x slower. 

With arm neon you can load 32 32Bit values, 64 16Bit values or 128 8Bit values in registers and do mult/add/sub/shift/swp/rev with one instruction on a quad register (4x32Bit or 8x16Bit or 16x8Bit). If you can read/write continuous from/to an array and have no conditions in a loop arm neon code should be a whole lot faster. So working on a texture, do color conversion of a whole lot of pixels or do matrix multiplications are perfectly suitable. 

I would prefer neon intrinsics over asm code, so gcc can optimize neon code for the target platform.

**Comment by gonetz** [comment]
This is impressive result indeed. What about clang? @fzurita now uses clang for Android build.

**Comment by fzurita** [comment]
From my research, clang produces code that is faster than gcc for the most part, but it's marginal. In some situations​ gcc wins and some clang wins. I'm sure NEON will help clang as well.

This is not where we are going to get the most bang for the buck though. I think that will come from software skinning, or draw call reordering and batching.

**Comment by gizmo98** [comment]
This can be closed!
