### ISSUE TITLE
Majora's Mask - No geometry visible with N64 depth compare (regression)

### ISSUE THREAD

**Issue by oddMLan** [gonetz/GLideN64#1431]
To reproduce, first off, make sure Shader Storage is disabled. And enable N64 depth compare.
The effects are inmediate. No N64 spinning logo, no spinning mask, no geometry at all is visible.

![gliden64_zelda_majora s_mask_000](https://cloud.githubusercontent.com/assets/7278372/24083592/2875db72-0c97-11e7-8646-571f53680f0b.png)
![gliden64_zelda_majora s_mask_001](https://cloud.githubusercontent.com/assets/7278372/24083629/bf210d58-0c97-11e7-8db9-2f3825eb998a.png)

Strangely enough, if you open GLideN64 settings during gameplay, then click "Reset settings" AND re-enable N64 depth compare, now it works properly.
![gliden64_zelda_majora s_mask_002](https://cloud.githubusercontent.com/assets/7278372/24083634/ef65c9f4-0c97-11e7-8edc-ddf8d90ef2fc.png)

Was reported before in issue #1418, but opened separate issue now that the other one it's closed
Doesn't happen in Public Release 2.0. The recent VI refactor is not related to this issue, it happened before that.

**Comment by oddMLan** [comment]
Tested under AMD Radeon R7 250 with Project64 build and Mupen64plus build
GLideN64 latest WIP 0eeba0e

**Comment by loganmc10** [comment]
Tested Windows+mupen64plus+Nvidia, latest master, same thing, no GL errors.

**Comment by fzurita** [comment]
It may be related to the changes that were done by me or gonetz after I modified the code to use two red only textures instead of a RG texture. Adreno has similar issues but for all games. I couldn't figure it out.

**Comment by gonetz** [comment]
Bad commit: 151fdf5ecc2e2

**Comment by gonetz** [comment]
Fixed

**Comment by gonetz** [comment]
@oddMLan please test with
https://drive.google.com/file/d/0B0YqMPjGo3B2N2R2Rll4NktXbWM/view?usp=sharing

**Comment by oddMLan** [comment]
Fixed.
