### ISSUE TITLE
Super Smash Bros Black textures (regression)

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#1439]
Doesn't occur on most recent build provided by Gonetz. So likely caused by https://github.com/gonetz/GLideN64/commit/6f35e5a237add13d54bc7c9b2105df3e0b0d8d78

![smash_brothers-002](https://cloud.githubusercontent.com/assets/10704701/24180590/71c98276-0f01-11e7-8124-281d07f0f4c4.png)

**Comment by loganmc10** [comment]
I don't actually get black textures, but I can confirm that it is caused by https://github.com/gonetz/GLideN64/commit/6f35e5a237add13d54bc7c9b2105df3e0b0d8d78:
![smash](https://cloud.githubusercontent.com/assets/848146/24180809/b8283094-0e7c-11e7-9584-2bd2d60f176a.png)

**Comment by gonetz** [comment]
Well, unexpected turn.

**Comment by gonetz** [comment]
Fixed

**Comment by AmbientMalice** [comment]
Fantastic work, Gonetz.

**Comment by gonetz** [comment]
Alas, nothing fantastic. Made wrong changes - regressions - revert changes. Texturing is hardest part of N64 emulation.
