### ISSUE TITLE
Pokemon Stadium Menu Items Missing (Regression)

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1446]
Some of the text is missing:

![pokemon_stadium-000](https://cloud.githubusercontent.com/assets/848146/24377032/296afc0a-12fb-11e7-8c53-0f9f7fa25b20.png)

If I leave that menu and go back to it, the text is there:
![pokemon_stadium-001](https://cloud.githubusercontent.com/assets/848146/24377034/2bc7cc80-12fb-11e7-825a-5c19b61a85a1.png)

This is with mupen64plus on Windows 7, Nvidia card, using 5bfac0a664a30eac55c33708dd347e42df12d14f

**Comment by loganmc10** [comment]
Here is the first bad commit:
952769a67128379851219b45dbce219fdb5a856e

**Comment by gonetz** [comment]
Hmm, the code looks correct.

**Comment by loganmc10** [comment]
Fixed, thanks!
