### ISSUE TITLE
Bug in gSP.cpp?

### ISSUE THREAD

**Issue by gizmo98** [gonetz/GLideN64#1451]
I stumbled over code which looks strange.

gSP.numLights can be 0-12:
https://github.com/gonetz/GLideN64/blob/2acc3c77752f2935405b0b8086cd71d91c4242ea/src/gSP.cpp#L1642

gSP.lights has 12 elements:
https://github.com/gonetz/GLideN64/blob/2acc3c77752f2935405b0b8086cd71d91c4242ea/src/gSP.h#L79

If gSP.numLights is 12 these lines will access memory outside of gSP.lights:
https://github.com/gonetz/GLideN64/blob/2acc3c77752f2935405b0b8086cd71d91c4242ea/src/gSP.cpp#L127
https://github.com/gonetz/GLideN64/blob/2acc3c77752f2935405b0b8086cd71d91c4242ea/src/gSP.cpp#L163
https://github.com/gonetz/GLideN64/blob/2acc3c77752f2935405b0b8086cd71d91c4242ea/src/gSP.cpp#L195
https://github.com/gonetz/GLideN64/blob/2acc3c77752f2935405b0b8086cd71d91c4242ea/src/gSP.cpp#L395
https://github.com/gonetz/GLideN64/blob/2acc3c77752f2935405b0b8086cd71d91c4242ea/src/gSP.cpp#L450
https://github.com/gonetz/GLideN64/blob/2acc3c77752f2935405b0b8086cd71d91c4242ea/src/gSP.cpp#L480
https://github.com/gonetz/GLideN64/blob/b78c2796763a54af5e48a95aa7a5fc1b9df0ffff/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramUniformFactory.cpp#L768
https://github.com/gonetz/GLideN64/blob/7139e5b8d1387d89a6a8010859a7f2ae46120aa3/src/ZSort.cpp#L248

Moreover i do not really understand why something should be read from gSP.Light n+1 if we have only n lights?

**Comment by gonetz** [comment]
N64 can use up to 8 lights. You can find that limit in all docs and manuals.
12 is set for CBFD, which somehow managed to bypass this limitation and actually can use 12 lights.
Thus, gSP.numLights can be [0, 7] in general and [0, 11] for CBFD . 
 n <= 12 condition is incorrect, must be n < 12

> Moreover i do not really understand why something should be read from gSP.Light n+1 if we have only n lights?

I don't understand the question. Suppose, gSP.numLights is 7, that is all 8 lights are used. gSP.Lights[0]- gSP.Lights[6] are directional lights, gSP.Lights[7] is ambient light.

**Comment by gizmo98** [comment]
So gSP.numLights = 7 means use 8 lights and CBFD uses up to 12 lights (gSP.numLights = 11). Understood. gSPNumLights checks the right number of lights now. Ok. But is gSPUpdateLightVectors correct? It only updates numLights-1 LightVectors atm. Shouldn't it update all LightVectors?
https://github.com/gonetz/GLideN64/blob/master/src/gSP.cpp#L906

**Comment by gonetz** [comment]
gSPUpdateLightVectors updates light direction vector. Ambient light has no direction. The function is correct.

**Comment by gizmo98** [comment]
Ok. Thanks for clarifing how it works. 👍

**Comment by gonetz** [comment]
You welcome. You may find better explanation in N64 programming manual.
