### ISSUE TITLE
Wires are too small (Mario Artist)

### ISSUE THREAD

**Issue by LuigiBlood** [gonetz/GLideN64#1456]
Happens on Mario Artist Talent Studio and Polygon Studio (where it is more obvious)
Tried 5e51b38 (2017-04-03) WIP build.

Currently:
![image](https://cloud.githubusercontent.com/assets/952602/24666423/91992b6a-1960-11e7-8205-80ea6376e6db.png)

What is supposed to happen:
![image](https://cloud.githubusercontent.com/assets/952602/24666512/d682bd54-1960-11e7-8860-3a4a646c271e.png)

**Comment by gonetz** [comment]
Could you get me a savestate from this place?

**Comment by LuigiBlood** [comment]
It's the main menu of Polygon Studio. Literally the first thing you see after the Title Screen (just press Start a lot)

**Comment by LuigiBlood** [comment]
On d8ac5a7 WIP build, this is fixed.
