### ISSUE TITLE
Star Wars: Rogue Squadron Regressions (No Video)

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1459]
I get no video after the main opening sequence now. Once it gets to the menu, everything is black.

I tested a commit from Feb 28 and it worked, it seems to have something to do with the VI refactoring, once I try those commits, the game seems to break completely, it came out the other end of those commits with the opening sequence working, but the menu broken.

**Comment by loganmc10** [comment]
This is the commit where the problems first start:

e6811b4d4f864ddd51a17585e3c5af05552f102a

**Comment by loganmc10** [comment]
I should also note that when it was "working" the menu shook quite a bit, so I assume there was something special going on with the VI before.

**Comment by loganmc10** [comment]
I'm really not sure what the flickering is about, I'm curious if anyone else can reproduce that. m_textures.size() at the point where I get the flickering is only ~100, so I don't see why maxCacheSize would make a difference.

**Comment by jaburgeson** [comment]
I get this as well.

After opening cut scene it is just black.  If you leave it there, eventually a demo mode will start and then recycle the opening sequence.

**Comment by Frank-74** [comment]
I get black screen at menu with latest WIP in Project64 too.  But if I open graphics config and click OK, menu screen appears.

**Comment by loganmc10** [comment]
@gonetz is there anything I can do to help diagnose this issue? I believe the same thing happens in Indiana Jones if my memory is correct.

**Comment by gonetz** [comment]
I don't know how to answer. I did not check that problem yet. You already found regression commit. Next step is to find a mistake and fix it. I will do it eventually.

**Comment by loganmc10** [comment]
Just to confirm what @Frank-74 , I experience this same thing in Indiana Jones, but toggling full screen will make the menu appear. So it seems like re-initializing the plugin solves the problem.

**Comment by loganmc10** [comment]
https://github.com/gonetz/GLideN64/issues/1536#issuecomment-319276156
