### ISSUE TITLE
HD Texture Dump/Edit textures request

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1465]
Can please have the Dump(D) reload texture(R) keys only work while the window is selected? This can get very annoying when using image editors that have hotkeys mapped to these letters.

Thanks

**Comment by gonetz** [comment]
Done. Build:
https://drive.google.com/file/d/0B0YqMPjGo3B2OVNHTUVBUUktMmM/view?usp=sharing

**Comment by theboy181** [comment]
Works Great!! Please don't hesitate to add in master.
