### ISSUE TITLE
Turok2: missing flashlight

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#147]
![nolight](https://cloud.githubusercontent.com/assets/8987490/5139981/993f6fe6-7165-11e4-84ea-6713512554ff.jpg)

**Comment by AmbientMalice** [comment]
This bug also affects Turok 3's weapons - but the effect is more subtle. I'm curious as to the cause. Could it perhaps be a ucode problem?

**Comment by olivieryuyu** [comment]
just checked again, still the same

**Comment by olivieryuyu** [comment]
you may use cheats to access the level hive of the mantids: there is some ennemies shooting at you: the lights are following their bullets. works in LLE not HLE.

**Comment by gonetz** [comment]
I need a savesate. Preferably not for PJ64 2.3

**Comment by olivieryuyu** [comment]
will do tonight.

**Comment by olivieryuyu** [comment]
here you go: a savestate from 1964 v1.1

[Turok 2- Seeds of Ev-E0B92B9480E87CBD.zip](https://github.com/gonetz/GLideN64/files/570161/Turok.2-.Seeds.of.Ev-E0B92B9480E87CBD.zip)

it is for the European version of the game.

when bullets are fired, the ground is lighted in LLE, not in HLE.

HLE

![hle](https://cloud.githubusercontent.com/assets/8987490/19986328/8bd820c6-a216-11e6-9615-40704db447ea.jpg)

LLE

![lle](https://cloud.githubusercontent.com/assets/8987490/19986327/8bd7f038-a216-11e6-8906-0a69a2f3110c.jpg)

Quite obvious when runnning the game at this point.

**Comment by AmbientMalice** [comment]
Also, any projectiles from your weapons that hit surfaces cause a brief flash of yellow light. The game(s) look very odd without their various lighting effects, but people have gotten used to it, I suppose.

**Comment by AmbientMalice** [comment]
@gonetz Do you think this is an issue that would be feasible to fix at some point? I'm aware that making Majora's Mask's (and Conker's) point lighting work was difficult, and these games are far less high profile, but what's your opinion here? Do you think it's a minor tweak to the ucode, or could it be something major?

**Comment by gonetz** [comment]
I have no idea how it works. I spent yesterday evening to investigate how flashlight works. My logs show that walls do not use lighting at all! All parameters are the same with or without flashlight. I don't see what can change colors of vertices for walls polygons.

**Comment by olivieryuyu** [comment]
I am surprised it is actually a modification of the ucode. I would think more something that changed in f3dex version 2. Only a wild theory of course.

**Comment by olivieryuyu** [comment]
@gonetz: just a suggestion: Foresaken from the same devs shows this kind of lights (as the one shown in my screenshots from 1964) and it works with fdex version 1 version. May be doing a comparison to understand how the devs did implement the lights could lead you to the source of the issue in fdex version 2? Just an idea, may be it won't lead to anything or is completely irrelevant.

**Comment by gonetz** [comment]
Point lighting can be simulated with standard ucodes. There are guPosLight and guPosLightHilite functions, which calculate light structure for given object. "The light direction and intensity are determined by the positional relationship (distance and direction) between the light and the object being lit". As I understand, the light then applied as usual. Since guPosLight called each time the object moves, new light created and it makes effect of point lighting. I guess, Quake and Forsaken use that option.

Turok 2 works differently. When flashlight works, game loads several light structures, but does it in a strange non-standard way, with data overlapping. I don't see where these light are used somehow. These lights are not loaded when flashlight is off. That's all I can see. I don't know what to do with that.

**Comment by AmbientMalice** [comment]
@gonetz Thanks for looking into the issue, anyway. You're doing a great service to N64 emulation.

**Comment by gonetz** [comment]
Thanks :) Pity, that I can't crack that problem. I'm afraid, it requires to disasm the ucode with RSP plugin, which is beyond my skills.

**Comment by olivieryuyu** [comment]
A new mystery so: nearly all Acclaim games uses a non standard lights system, may be even a customized ucode.

**Comment by olivieryuyu** [comment]
one short question pls: does glideN64 manage LightsM structure as explained in  gdSPDefLights and gSPSetLightsM?

I cannot see any reference in the source to this but may be I don't read properly the code

**Comment by gonetz** [comment]
```
typedef struct {
        Ambient		a;	/* Ambient light */
        Light		l[M];	/* Diffuse light */
} LightsM;
* Number of diffuse lights (integer 0~7) will be set for M.
```

LightsM is an macro name for Lights0 ~ Lights7 structures, which are loaded with gSPLight in GLideN64 code.

**Comment by olivieryuyu** [comment]
got it

**Comment by AmbientMalice** [comment]
@Gillou68310 do you think you might be able to look into this issue at some point?

**Comment by Gillou68310** [comment]
Sure :-)
I'm working on majora's mask ucode right now but don't hesitate to remind me about this issue when I'm finished with majora's mask.

**Comment by olivieryuyu** [comment]
It is a custom microcode. Dumping and comparing with F3DEX.NoN standard microcode. However the code does not seems as complex as the code of Zelda MM.

[TUROK 2.xlsx](https://github.com/gonetz/GLideN64/files/721281/TUROK.2.xlsx)

**Comment by theboy181** [comment]
@AmbientMalice 

https://www.youtube.com/watch?v=JufWZeE4HZo

;)  thought you would like this.

**Comment by AmbientMalice** [comment]
@theboy181 I bought the remaster of Turok 2, and TBH I'm quite displeased by some of the alterations. The flashlight in the remaster is ridiculous. The UI art style changes are weird. The default lighting is far too bright and bloomey. There's no weapon wheels for some reason.

**Comment by theboy181** [comment]
@AmbientMalice 

Well since its not good the above link is the 64 Version with 60 FPS hack... I was hoping to get you excited by that. 

Thoughts?

**Comment by AmbientMalice** [comment]
>Well since its not good the above link is the 64 Version with 60 FPS hack... I was hoping to get you excited by that.

Firstly, the remaster isn't **bad** and they are still patching it. Secondly, hacking Turok 2 N64 to run at 60fps is definitely interesting. I think it would also be worth trying to hack the game to disable look spring and to reverse the inverted aim, to be more like Turok 3.

**Comment by olivieryuyu** [comment]
So I started to investigate the light issue of Turok2 (warm up before trying Zelda MM lights). The microcode is a custom one but it is very slightly modified fortunately.

So the data provided by moveword are different as from L2.

It seems to be the same structure of data for G_MVO_LOOKATX, G_MVO_LOOKATY, G_MVO_L0 and G_MVO_L1 with 24 bytes each and then 8 group of 16 bytes.

The code do some checks and would they go through those checks some calculation would be carried out

The data obtained seems to be only 8 bytes which are used by the rest of the code as it would for the standard F3DEX1 ucode.

**Comment by Frank-74** [comment]
Armorines - Project S.W.A.R.M. uses point lighting too.  Another Acclaim game to look at...

**Comment by AmbientMalice** [comment]
Dude, if you can figure out the lighting in Acclaim Austin/Iguana games, you are my personal hero. Those games rendering incorrectly has annoyed me for years.

**Comment by olivieryuyu** [comment]
Ok so I think I understand what the code is doing. Question is now to interpret this correctly.

@gonetz 

Will send you the information about this matter in the coming days

**Comment by olivieryuyu** [comment]
so turok2 & 3, armories and south park uses this light system.

**Comment by gonetz** [comment]
Yep, but ucode mimics for standard f3dex2. Ucode id string says it is f3dex2, so I can detect it only by checksum.

**Comment by olivieryuyu** [comment]
indeed same ucode string, that is why without dumping the ucode, we could never figure out it was not the  standard F3DEX2 ucode.

I dumped the Acclaim games and only thoses 4 games (turok 2 and turok 3, Armorines - Project S.W.A.R.M and South Park) has this light system. 

:)

**Comment by olivieryuyu** [comment]
and voila :)

**Comment by gonetz** [comment]
http://gliden64.blogspot.ru/2017/06/acclaim-custom-lighting.html

**Comment by theboy181** [comment]
Great work guys!!! Another win for solving things that have been broken for years.

**Comment by AmbientMalice** [comment]
Fantastic work.
