### ISSUE TITLE
Zelda: OoT Texture Pack flickers before day/night transition

### ISSUE THREAD

**Issue by OldGnashburg** [gonetz/GLideN64#1470]
Tested with Djipi's 2015 HD Texture pack, using GLideN64 release 2.0 and the most recent build of GLideN64. When the day/night sky starts to change color before the transition of day/night, the sky textures flicker and disappear, and are replaced with what I believe are the original textures for the sky, it happens for a second or less. It happens so quick that I wasn't able to get a screenshot, however I managed to get a save state for Project 64 v.2.3.2 shortly before it happens.

https://drive.google.com/file/d/0B8toXeLeWCyrWE1QR3h3a2NZSGc/view?usp=sharing

**Comment by theboy181** [comment]
I'm certain this is the same bug I reported for HD textures. 

Seems that there is an issue with the texture sizes so new crc's are getting created. If you dump the textures from ram you will see that there will be newly created textures that have random distortion a in them.

**Comment by OldGnashburg** [comment]
Should I close this then?

**Comment by gonetz** [comment]
> Should I close this then?

No. I'll check it someday.

**Comment by gonetz** [comment]
This day came. Yes, it blinks for a moment. Thanks to that ticket I know that the bug is old and not caused by my recent works.

**Comment by gonetz** [comment]
Fixed.
