### ISSUE TITLE
Picture of Link broken with depth compare and copy auxiliary color buffers

### ISSUE THREAD

**Issue by OldGnashburg** [gonetz/GLideN64#1471]
Enabling either depth compare, copy auxiliary color buffers, or both breaks the picture of Link in Ocarina of Time Item Menu

With both enable N64 style depth compare and copy auxiliary color buffers to N64 Memory. And with just depth compare (Disappears)
![gliden64_the_legend_of_zelda_089](https://cloud.githubusercontent.com/assets/11412147/25134739/9d861944-240d-11e7-8514-a597069bf835.jpg)

With just Copy Auxiliary color buffers to Nintendo 64 Memory (Low Resolution, even on original N64 resolution setting)
![gliden64_the_legend_of_zelda_086](https://cloud.githubusercontent.com/assets/11412147/25134779/b12f0712-240d-11e7-8988-aa1a1dcf6b91.jpg)

With neither on
![gliden64_the_legend_of_zelda_091](https://cloud.githubusercontent.com/assets/11412147/25135287/2c25160e-240f-11e7-8b9b-a1f354131e54.jpg)

**Comment by gonetz** [comment]
> With just Copy Auxiliary color buffers to Nintendo 64 Memory (Low Resolution, even on original N64 resolution setting)

It is not a bug. "Copy Auxiliary color buffers to Nintendo 64 Memory" works exactly as this: copies aux buffer to RDRAM in original low resolution. When buffer copied to RDRAM, it will not disappear when you change settings or load from savestate.

Picture of Link now should work with N64 style depth compare enabled in latest master + fb_fixes build:
https://github.com/gonetz/GLideN64/issues/1574#issuecomment-425714381
