### ISSUE TITLE
Texture Enhancments performance.

### ISSUE THREAD

**Issue by truskj** [gonetz/GLideN64#1472]
hey, great work on the plugin.

I'm getting some serious performance issues when I enable any from of texture enhancements.
I can enable all of the other effects, eg: AA, Bloom, crop, even an Internal resolution of 10x as well as HD texture packs. The games I try run fine with at most times a solid framerate. 
but enabling any of the texture filters gives me huge performance drops.
In perfect dark I can have all features disabled and apply only "smoothing 1" and it still drops to around 80% speed. this just doesn't seem right to me. Disabling FrameBuffer will give me a little bit of speed up but I don't think this is the problem.

I saw a previous thread mentioning the Nvidia power settings causing similar issues for another user.
changing this did not help me, but I feel something in the control panel is causing it as after adjusting some settings the problem was gone briefly. but it again returned and I've been unable to isolate what it could be.

anyone have any thoughts on this?

Geforce GTX 970M
Intel I7-6700HQ
Nvidia Driver Ver 381.65

**Comment by truskj** [comment]
Well, I found out the solution to my problem. in the Nvidia Control Panel, there was a setting called "Threaded optimization".
Disabling this feature gave me an instant speed up, now I get perfect speeds with my texture enhancements.
Hope this helps other users.

**Comment by oddMLan** [comment]
Issue solved? Please close this ticket.
