### ISSUE TITLE
Issues using when internal ROM name contains colon

### ISSUE THREAD

**Issue by blackgamma7** [gonetz/GLideN64#1477]
I noticed that if the rom has a colon in its internal name (Gex: enter the gecko, Turok: Dinosuar hunter) then there several complications - no texture caching or dumping and the next loaded game has some sort of error. to make sure, I edited the colon out of the header and it worked fine.

**Comment by gonetz** [comment]
Fixed with 1e3e06a036

**Comment by olivieryuyu** [comment]
Can it be closed?
