### ISSUE TITLE
N64-style 3 point Not working in Diddy Kong Racing

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1481]
N64-style 3 point seems to work in MK64, but has no difference in DKR.

**Comment by Aquatakat** [comment]
It's working OK for me.

Off:
![image](https://cloud.githubusercontent.com/assets/9537912/26029984/191a3ad4-3801-11e7-8e87-e353b4a459ee.png)

On:
![image](https://cloud.githubusercontent.com/assets/9537912/26029986/27cc8758-3801-11e7-92ab-e56ceb41cd76.png)
