### ISSUE TITLE
Frame buffer emulation 1 frame delay

### ISSUE THREAD

**Issue by jordanbarkley** [gonetz/GLideN64#1485]
FBE is great. However, toggling the option delays video by a single frame (tested against GLideN64 w/o FBE emulated, Jabo 1.6 and the, Nemu Graphics plugin).

A fix for this would be wonderful

**Comment by loganmc10** [comment]
People have discussed this before. Perhaps those other graphics plugins are artificially removing a frame of delay that was present on the real console.

Jabo 1.6 and Nemu aren't a good test. You need to either compare it to a real console using some sort of timing system, or perhaps a more accurate software graphics plugin.

**Comment by gonetz** [comment]
If 1 frame delay exists, it can be result of VI emulation. GLideN64 displays the frame pointed by VI register. It is not necessary the most recently drawn frame. Other plugins display most recent frame, as well as GLideN64 without FBE. Plugins without proper VI emulation usually render right to video card frame buffer and thus just can't select buffer to display.
Of course, I can hack VI to display most recent frame. As with any hacks, it will have bad consequences in some games. But it can be made optional, yes.

**Comment by Squall-Leonhart** [comment]
I actually theorised that when first reading of the 'issue'.  I just never got to replying to jordan on discord with said theory.

**Comment by oddMLan** [comment]
Didn't someone already come to the conclusion that this delay doesn't happen if VI interrupt is set to color buffer change?

**Comment by jordanbarkley** [comment]
Following up to say that FBE on matches console. I have a test ROMs to prove it.

I think a toggle would be sweet

**Comment by jordanbarkley** [comment]
^^

**Comment by theboy181** [comment]
Please let me know when there is an option available too.
