### ISSUE TITLE
Screen Tearing 

### ISSUE THREAD

**Issue by MasterKairi0** [gonetz/GLideN64#1486]
you know what to do also for any reason im using  djipi 2016 OOT and MM packs with this

**Comment by tony971** [comment]
[I'm sure they'll figure out your specific issue.](https://media.makeameme.org/created/Its-like-hes.png)

**Comment by MasterKairi0** [comment]
well i tried using 1920x 1080  with 29 hzs and it works but i like it
better at stock 60 hz

**Comment by theboy181** [comment]
Have you turned on vsync?

**Comment by MasterKairi0** [comment]
yes lol it just doesnt work when the camera moves fast like in zelda oot or
mm

**Comment by theboy181** [comment]
What gfx card are you using and do you have the settings set to?

I would also make sure you ha e your monitor set to 60hz

**Comment by MasterKairi0** [comment]
amd rx 480 nitro plus oc'd  60 hz and  high quality settings with vsync
enabled  im going to try to add it to crimson and force vsync and let you
know bud

**Comment by olivieryuyu** [comment]
is it still a relevant issue? This pack is normally compatible with GlideN64.

**Comment by gonetz** [comment]
No news from ticket starter. Closed.

**Comment by MasterKairi0** [comment]
i fixed the issue a long time ago i forgot how
