### ISSUE TITLE
A Bug's Life LOD vertex combiner issue [Regression]

### ISSUE THREAD

**Issue by oddMLan** [gonetz/GLideN64#1488]
![abug](https://cloud.githubusercontent.com/assets/7278372/26227540/0ac6994c-3be8-11e7-85ab-ffdebb06ea19.gif)

GLideN64 paints vertexes darker than it should, so the transition effect from higher detail to lower detail zones becomes very jarring and evident.

Savestate for PJ64 2.3
https://puu.sh/vUovE/115a9f5ea0.zip

Occurs both in HLE and LLE modes

**Comment by oddMLan** [comment]
Changing any of the settings will not affect the darkened zones, which makes me think this is a combiner issue.

**Comment by oddMLan** [comment]
This is a REGRESSION! Doesn't happen with Mupen64plus + legacy blending enabled.
(btw can you enable legacy blending on zilmar-spec emus?)

**Comment by gonetz** [comment]
> btw is it possible to enable legacy blending on zilmar-spec emus?

Only with code rebuild. Standard blending must work right, legacy blending must not be needed.

**Comment by gonetz** [comment]
The issue fixed.

**Comment by oddMLan** [comment]
Not fixed!

**Comment by loganmc10** [comment]
@oddMLan did you disable shader caching or clear your shader cache?

**Comment by oddMLan** [comment]
Yes, as usual. Reset to defaults, deleted old shader cache. Tested on both Project64 and Mupen64Plus.

**Comment by loganmc10** [comment]
Yeah I just tested your save state with the latest master, it does still look the same:

![a_bug s_life-000](https://user-images.githubusercontent.com/848146/28999092-46b9ec1c-79f8-11e7-8440-e9b59930adb2.png)

**Comment by oddMLan** [comment]
I didnt know mupen64plus supported PJ64 savestates?

**Comment by loganmc10** [comment]
Yeah it can open them natively, no conversion needed. I don't know how good it is, but I've never had an issue

**Comment by gonetz** [comment]
Looks like there is some memory initialization issue. It should look like this (taken with latest posted WIP build): 
![gliden64_a_bug s_life_000](https://user-images.githubusercontent.com/8983092/29000516-44e67dac-7a97-11e7-8a1c-03aff166e516.jpg)

However, when I load the save, sometimes it looks as nothing is fixed. I change some setting, disable custom ini, reload save again - it works properly. Reload again - the bug is there.
So, this reported bug is fixed, but another (and more nasty) issue is still there.

**Comment by oddMLan** [comment]
![image](https://user-images.githubusercontent.com/7278372/29000676-9d45589e-7a27-11e7-81d1-3fef56c9b32d.png)

Hm... yeah. I disabled per-game settings, enabled per-pixel lighting and that fixed the blending, disabled per-pixel lighting and reloaded, and it showed correctly too. Restarted the emulator, loaded the save and it showed correctly without changing any settings. Restarted, deleted shader cache and it showed incorrectly. Did the same routine to fix the blending, disabled shader storage, deleted shader cache, restarted the emulator and loaded the save, and it showed correctly. Restarted a couple more times, and it kept showing correctly. Re-enabled shader cache, restarted, and it was incorrect again. Disabled shader cache without bothering to attemp to fix the blending beforehand, deleted shaders, and it kept showing incorrectly now every time I restarted and loaded the save.

Here's the shaders generated (labeled proper when it showed correctly and wrong when it showed unfixed).

[shaders.zip](https://github.com/gonetz/GLideN64/files/1202878/shaders.zip)

**Comment by gonetz** [comment]
Should be totally fixed now.

**Comment by olivieryuyu** [comment]
@oddMLan 

can you pls check and close if possible?

**Comment by oddMLan** [comment]
Sorry, I don't have access to a computer I can test it ATM, maybe for the following couple weeks

**Comment by oddMLan** [comment]
Was able to do a quick test, the bug is squashed :)

![image](https://user-images.githubusercontent.com/7278372/31111175-091c5ad8-a7c1-11e7-92c5-95d758fb135a.png)
