### ISSUE TITLE
Ocarina of time retexture pack crashing in latest builds

### ISSUE THREAD

**Issue by LuismaSP89** [gonetz/GLideN64#1489]
http://www.emutalk.net/threads/55307-Zelda-Ocarina-of-time-Community-Retexture-Project-V7

This pack crashes in latest builds, when 900+ MB of video ram is used during cache. (Got a Nvidia GTX 970 with 4GB)

My latest build is from April 3rd, and all was working OK.

**Comment by theShrike760** [comment]
Same issue confirmed on fireTV box with same pack. I noticed it failed around the 840MB mark. I was going to try and remove some of the textures to get it under 800MB and try again. Ill post results. 

BTW: I had this from the author: Crashing is due to memory utilization. GLideN64 is coded in a way that makes it need the whole texture pack loaded in memory. The Zelda texture pack is really big and Android doesn't like it when a process takes too much memory, which causes the crash.

**Comment by LuismaSP89** [comment]
The thing is that it doesn´t crash for me with the GlideN64 build of the past month. And i got 16 GB of RAM in my PC. So, there´s something that has been changed in the latest 1-4 weeks.

**Comment by theShrike760** [comment]
Confirmed a smaller size worked. Around 550mb before zipping did the trick. But now I see not touching sky tiles.

**Comment by LuismaSP89** [comment]
@theShrike760 

Mmm... yeah, maybe that is the problem. I hope for a fix soon, it´s really annoying reduce the texture pack. It would be perfect support for example texture packs between 1 and 2GB.

**Comment by theShrike760** [comment]
I ended up giving up and going back to the other pack. Even with the smaller size my game kept crashing randomly. Hopefully when they fix your issue it'll fix it crashing on android as well.

**Comment by fzurita** [comment]
There are two separate crashes in Android. First crash is due to the memory limitations and second crash is due to texture pack errors. I created an issue on the texture pack errors crash: https://github.com/gonetz/GLideN64/issues/1478

**Comment by gonetz** [comment]
@LuismaSP89 I made several fixes for texture packs. Please test again. Note:  You need fixed version of Project64 (with large address aware) to load Community-Retexture-Project-V7.

**Comment by LuismaSP89** [comment]
@gonetz  Solved, and it seems (at least it appears to me) that the textures loading time is decreased : )

**Comment by gonetz** [comment]
Can it be closed?

**Comment by LuismaSP89** [comment]
@gonetz Yes.
