### ISSUE TITLE
Better Bilinear Filtering?

### ISSUE THREAD

**Issue by Yui12** [gonetz/GLideN64#1495]
I notice that the force filtering with this plugin is weaker than it is in other plugins. Will there be any chance this will be changed in the future? Honest question.

**Comment by oddMLan** [comment]
Bicubic filtering?

**Comment by Yui12** [comment]
Something similar to Glide64's method of filtering as opposed to GlideN64's version (Standard).

**Comment by mudlord** [comment]
What the hell.

**Comment by AmbientMalice** [comment]
What do you mean by "force filtering"? GLideN64 doesn't let you bilinear filter textures the developers intentionally point sample filtered. Glide64's problem was that it filtered things it wasn't supposed to, in addition to having a setting to force filtering on everything, which is IMO a terrible idea.

**Comment by Yui12** [comment]
Sigh, really?

I guess no one knows what I'm talking about. I don't know how else to explain it better. It seems like all I did was make myself look stupid somehow. Well, fuck this shit, I'm done.
