### ISSUE TITLE
Yoshi Story Crashes after a few minutes.

### ISSUE THREAD

**Issue by Smashman4** [gonetz/GLideN64#1499]
I'm using Project 64 1.6 on windows 10 (since I think it's the fastest) and when I play Yoshi's Story, it crashes after a few minutes, is there any setting that fixes this? I turn everything off except buffering.

Forgot to add that sometimes it would freeze for a very long time, and run like normal.

**Comment by gonetz** [comment]
Are you sure that it is GLideN64 problem? Have you tried to play this game with other graphics plugin?

**Comment by Smashman4** [comment]
I'm pretty sure it is. I'll test it out on other graphics plugins later to make sure.

**Comment by loganmc10** [comment]
I played through the whole first level on mupen64plus and didn't experience any crash.

**Comment by Frank-74** [comment]
No problems here with GLideN64 and latest PJ64 either.

You probably have a bad dump of the ROM.

**Comment by Smashman4** [comment]
Hmmm. I'll try another rom and see if that fixes it.

**Comment by Frank-74** [comment]
@Smashman4 Well, I'm using latest Project64 2.4.  It may be a problem with 1.6.  Though I have seen lots of comments about bad dumps of this particular ROM which causes crashing, from sites I cannot mention here.

**Comment by Smashman4** [comment]
The good clue was the one I had the problem with.

**Comment by Frank-74** [comment]
> The good clue was the one I had the problem with.

No problems with latest GLideN64 and latest Project64 here.  I played for an hour with no problems.  Default settings.

**Comment by Smashman4** [comment]
> No problems with latest GLideN64 and latest Project64 here. I played for an hour with no problems. Default settings.

Is 2.0 public release the latest version of GLideN64?

**Comment by Frank-74** [comment]
@Smashman4 Get latest GLideN64 WIP here:- https://github.com/gonetz/GLideN64/issues/1364#issuecomment-300204726

**Comment by Smashman4** [comment]
I think that did the trick. Thank you so much for all of your help.

**Comment by olivieryuyu** [comment]
please close then

**Comment by Smashman4** [comment]
OK. Closing now.
