### ISSUE TITLE
Widescreen hack breaks Disney's Tarzan amusingly

### ISSUE THREAD

**Issue by Aquatakat** [gonetz/GLideN64#1501]
![image](https://cloud.githubusercontent.com/assets/9537912/26600735/682d2d66-453a-11e7-9b31-9b4e73e00830.png)
![image](https://cloud.githubusercontent.com/assets/9537912/26600754/82758088-453a-11e7-8916-532150fcdc5c.png)

This game is weird.

**Comment by gonetz** [comment]
Fixed.

**Comment by Aquatakat** [comment]
Looks good.
