### ISSUE TITLE
OoT Ending Screen Freeze Effect Color Wrong and Doesn't Work With AA

### ISSUE THREAD

**Issue by Aktanusa** [gonetz/GLideN64#1505]
Hi there!  I tried searching for a solution to this issue before posting, but I couldn't find a solution.  I also tried every setting in the Frame buffer tab but didn't find anything to fix this problem.  Here it is on Glide64 Final working fine:
![glide64 final](https://user-images.githubusercontent.com/7632881/26909367-4395d5bc-4bce-11e7-8aaf-ac612b1c1dba.png)
and here it is on GLideN64 2.0:
![gliden64 2 0](https://user-images.githubusercontent.com/7632881/26909380-52747fd4-4bce-11e7-93f5-a05ecdd465e1.png)
An addition issue occurs if I turn on anti aliasing:
![gliden64 2 0 w aa](https://user-images.githubusercontent.com/7632881/26909388-6685ae12-4bce-11e7-9b71-e09f4e0b1eac.png)

It seems in general this effect is not well emulated as even the effect itself with the screen slowly going to orange is completely missing in GLideN64 while it shows up fine in Glide64.

**Comment by Frank-74** [comment]
Have you tried the latest WIP?

https://github.com/gonetz/GLideN64/issues/1364#issuecomment-300204726

**Comment by Aktanusa** [comment]
I found that after I have already posted and the problem is still there =(

**Comment by Aquatakat** [comment]
Can you post a save state?

**Comment by Aktanusa** [comment]
Sure, it's for Mupen, Japanese OoT Version 1.0.  I can't seem to attach the ZIP, but it contains two save states, slot 8 is just before the whole ending, and slot 9 is just the way end.

**Comment by Aquatakat** [comment]
It works with AA on for me, but the colour is incorrect like you said.

![image](https://user-images.githubusercontent.com/9537912/26911262-5e37aca6-4bc9-11e7-81a6-2ec762914f55.png)

**Comment by Aktanusa** [comment]
I wonder if the AA problem is GPU specific.  What GPU do you have?

**Comment by Aquatakat** [comment]
I have an AMD R9 380.

**Comment by Aktanusa** [comment]
Well I'm baffled then, as I have an AMD R9 280X

**Comment by Frank-74** [comment]
Same issue here with Intel HD Graphics.

Loading the end save, it's colour, then a flash and black and white.

**Comment by Aktanusa** [comment]
@Frank-74: What happens with AA? Do you have my problem, or is it working fine like @Aquatakat?

**Comment by Frank-74** [comment]
@Aktanusa AA is working fine here.  I tested with 2x and 8x AA.

**Comment by fzurita** [comment]
Maybe it's a depth buffer to RDRAM issue? Can you try toggling it on and off?

**Comment by Aktanusa** [comment]
@fzurita: which option exactly?  I'm pretty sure I've tried them all, but I'll try again.

**Comment by fzurita** [comment]
EnableCopyDepthToRDRAM try 0, 1, 2

**Comment by Aktanusa** [comment]
Oh, you mean "Copy video card depth buffer to N64 memory" which is copyDepthToRDRAM in GLideN64.ini.  Yea I tried 0, 1, and 2.  They are all the same grey screen.

**Comment by Frank-74** [comment]
It goes black and white after this screen.  Which I had a VERY hard time trying to capture.  It only appears for about 1/10th of a second.
![gliden64_the_legend_of_zelda_001](https://user-images.githubusercontent.com/11056843/26948093-0daea874-4c8d-11e7-9cbd-5f9234087928.png)

If I reload the snapshot, this screen doesn't appear.  You just see the side on view switch to black and white.

**Comment by Aktanusa** [comment]
@Frank-74: That problem can be fixed if I turn off "Use emulator help to read/write frame buffers".  Of course the grey is still there though, instead of orange.

**Comment by Frank-74** [comment]
When I turn off Use emulator help to read/write frame buffers, it flashes a black screen here.

**Comment by Aktanusa** [comment]
@Frank-74 : Huh, interesting, it doesn't do that for me.

**Comment by loganmc10** [comment]
I tested this on mupen64plus, same problem, no setting makes any difference. It's probably just something that needs to be fixed in the code itself. It is some sort of framebuffer effect though, turning off framebuffer emulation makes the picture become "full colour" (no grey or brown)

**Comment by Frank-74** [comment]
Turning off framebuffer emulation in Mupen64 0.51, makes the emulator crash here.

**Comment by Aquatakat** [comment]
I get the same result as @loganmc10 with Mupen 0.5.1, it doesn't crash, just displays in full colour.

**Comment by loganmc10** [comment]
> It runs AWFUL! Stuttery, VI's less than 50, crackly sound. 

Lol I can run OoT at 60 VI/s on my 4 year old cellphone so it might be you...

**Comment by fzurita** [comment]
@Frank-74 the default audio plugin in Mupen64plus is pretty terrible. It causes all sorts of issues. Unfortunately, that's the only official audio plugin I'm aware of. Android uses its own audio plugin that bypasses all these issues.

@loganmc10 didn't you have your own version of audio-sdl that fixes some of this?

**Comment by loganmc10** [comment]
Yeah I use/put together https://m64p.github.io

That includes the latest mupen64plus and GLideN64, plus an audio plugin (https://github.com/m64p/mupen64plus-audio-sdl2) that puts the samples into a buffer so it doesn't have a speed limiter

**Comment by loganmc10** [comment]
But even with the regular audio plugin I could play OoT full speed on an old laptop

**Comment by fzurita** [comment]
Right, it's going to depend a lot in hardware and OS.

**Comment by Frank-74** [comment]
@loganmc10 Cheers, your version runs much better.  Only problem is I cannot load the save above.  'Load state from' doesn't seem to work.

**Comment by loganmc10** [comment]
Those saves are for Mupen64, there is a program to convert them, I'll upload the converted save states when I'm in front of my computer in a bit

**Comment by Aktanusa** [comment]
@Frank-74: I have an in game Mupen save, but I think you still need to beat the final boss, lol.  I'm also not sure if the save with work with PJ64.

**Comment by Frank-74** [comment]
@Aktanusa Ingame .sra saved in Mupen64, works in Project64.  Just tested.
All that is needed is to rename the sra to its Internal Name.  THE LEGEND OF ZELDA.sra.

**Comment by Aktanusa** [comment]
@Frank-74: Cool, do you still want the save? The final castle still needs to be done as well as the final boss.

**Comment by Frank-74** [comment]
@Aktanusa Yes please.  I'll follow a walkthrough to complete it.

**Comment by Aktanusa** [comment]
@Frank-74: I should actually mention that because it's made from a TAS, you only have 3 hearts of health.  It be real hard for someone new. Hmm, maybe I can force a save closer to the end of the boss only.  Here it is anyway if you want a challenge!

[https://www.mediafire.com/?i96gxga96osuz2e](https://www.mediafire.com/?i96gxga96osuz2e)

**Comment by Frank-74** [comment]
@Aktanusa I'll give it a go.  BTW, the internal save loads into any version ROM.  I just loaded yours into (U) 1.2 version fine.

**Comment by loganmc10** [comment]
Here are those save states in mupen64plus format:

[mupen64plus.zip](https://github.com/gonetz/GLideN64/files/1062872/mupen64plus.zip)

**Comment by Aktanusa** [comment]
@Frank-74:  That's good to know.  Apparently doesn't also apply to save states.  Yea I'll make a save where you just need to defeat the final boss.  The other option is to make your own save with the info here:

[http://wiki.spinout182.com/w/Ocarina_of_Time:_Save_Format](http://wiki.spinout182.com/w/Ocarina_of_Time:_Save_Format)

**Comment by Aktanusa** [comment]
@Frank-74:  Here is the save with just the final boss.  It will still be hard with so little hearts, but you can do it!

[https://www.mediafire.com/?lpk8a34iaztna0j](https://www.mediafire.com/?lpk8a34iaztna0j)

**Comment by Frank-74** [comment]
@Aktanusa Sorry I haven't gotten around to playing the end boss yet.  Easy enough to beat it, I can give myself max hearts and infinite energy if need be.  Just been busy with other stuff.  I'll do it over the weekend, make a save in PJ64 near the very end, and try it with the different versions of OoT.

**Comment by Aktanusa** [comment]
@Frank-74: No worries, I'm glad you're testing things out at all =).  Also I saw it being hard so I kind of expected not to happen either.  The ending is suppose to be done like this: [https://www.youtube.com/watch?v=x97xdk3Fv7o&feature=youtu.be](https://www.youtube.com/watch?v=x97xdk3Fv7o&feature=youtu.be).  I'm joking though, as that is probably frame perfect.

**Comment by gonetz** [comment]
Fixed. Text build:

https://drive.google.com/file/d/0B0YqMPjGo3B2R0lONW9KZ3NXamc/view?usp=sharing

**Comment by loganmc10** [comment]
Just a note: You'll probably have to clear your shader cache (or disabling shader caching) to properly test

**Comment by Aktanusa** [comment]
Okay, will test in a bit.
