### ISSUE TITLE
GT64 - Championship Edition: missing polygon (week 9 regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#151]
ok

**Comment by gonetz** [comment]
Could you re-upload the save file?

**Comment by olivieryuyu** [comment]
https://1fichier.com/?ert8g6sanb

for Mupen 5.1

**Comment by gonetz** [comment]
Seems to be fixed.

**Comment by olivieryuyu** [comment]
not fixed. there is no fog anymore now.

here with angrylion plugin

![angrylion](https://cloud.githubusercontent.com/assets/8987490/6951575/996db568-d8bc-11e4-9446-0d2f1dd44f86.jpg)

and gliden64

![gliden64](https://cloud.githubusercontent.com/assets/8987490/6951582/a1cf9334-d8bc-11e4-83ac-7a19cae55b8d.jpg)

**Comment by gonetz** [comment]
Current version:
![gt64-006](https://cloud.githubusercontent.com/assets/8983092/18705284/dbfe2f4e-8017-11e6-8fa8-0cb6c60226b7.png)

**Comment by olivieryuyu** [comment]
will test tonight for the fog

the missing polygon bug is still here anyhow

**Comment by gonetz** [comment]
yes

**Comment by olivieryuyu** [comment]
fog fixed, still missing polygon due to branchz

**Comment by gonetz** [comment]
BranchLessZ fixed!
It was a problem with precision.

**Comment by olivieryuyu** [comment]
fixed
