### ISSUE TITLE
Starcraft 64 textures off center?

### ISSUE THREAD

**Issue by erfg12** [gonetz/GLideN64#1518]
- If you mouse over with the cursor, the bottom of the cursor will have the top of the cursor on the bottom.
- Timers on the top (TERRAN 3) show the top of the timer on the bottom.
- Message boxes show the top border on the very bottom.

So basically some images will render the tops of images on the bottom of them.

![gliden64_starcraft_64_000](https://user-images.githubusercontent.com/2896026/27749886-7de36f90-5da3-11e7-8d80-f28eab94d73a.png)

![sc2](https://user-images.githubusercontent.com/2896026/27749885-7de05dc8-5da3-11e7-9ca6-cd12fd0efe3b.png)

![gliden64_starcraft_64_003](https://user-images.githubusercontent.com/2896026/27750284-22c8ec1e-5da5-11e7-81ae-84ee6c69ca0a.png)

![gliden64_starcraft_64_000](https://user-images.githubusercontent.com/2896026/27772629-5c9ba478-5f34-11e7-8827-a6e58f960ac1.png)

**Comment by erfg12** [comment]
Ok it looks like using LLE instead of HLE fixes this.

**Comment by gizmo98** [comment]
HLE should be fixend.
