### ISSUE TITLE
Request: Add options to disable Scissoring on the RDP

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1519]
The WS hack that is now included with GLideN64 that @gonetz updated a few months ago would benefit from the ability to turn off culling that happens with scissoring command in the RDP.
https://level42.ca/projects/ultra64/Documentation/man/pro-man/pro12/12-03.html#01

I'm not sure if this is totally controlled by HW, and some hacks may need software solutions to fix the culling issues.

**Comment by gonetz** [comment]
Culling and scissoring are different things. However, disabling any of them is a bad idea.

**Comment by theboy181** [comment]
Why is it a bad idea?  Would this not fix most of the WS hack issues?

**Comment by gonetz** [comment]
It may fix some and add some new. As I understand, most of WS hack issues are objects disappear out of normal 4:3 viewport. Objects disappear because of optimizations in game code, not because of scissoring.

**Comment by theboy181** [comment]
Is i have understood from looking at the docs, some of the scissoring is handed by the RDP and some from software. retroben and I have been chasing for software hacks, but when it comes to the RDP having control of the size of the area, it could help speed up the process, by illuminating the HW side of things.

anyway, I know you are busy so I will close this issue, and we will continue to study and identify a good method of hacking every ROM we are interested in.  

Thanks for your input, its appreciated.

:)
