### ISSUE TITLE
Perfect Dark (U) v1.1 - Area 51 Infiltration intro problem

### ISSUE THREAD

**Issue by Frank-74** [gonetz/GLideN64#1523]
At the start of the intro to the level, the video doesn't display, just the noise like this.

![gliden64_perfect_dark_005](https://user-images.githubusercontent.com/11056843/27990356-224999d4-644c-11e7-9f58-9d7e0665f8e8.jpg)

My save, start game, solo mission, it's the next mission to play.
https://www.dropbox.com/s/geixoegi2yih0kc/Perfect%20Dark.eep?dl=1

Later on in the intro, video is seen, but it jerks and stutters around.
![gliden64_perfect_dark_008](https://user-images.githubusercontent.com/11056843/27990383-505ff704-644d-11e7-8558-2d74dfc1b42f.jpg)

This is how it should look:
https://www.youtube.com/watch?v=VR1haFq8qIg

**Comment by Yui12** [comment]
I came across this as well. Disabling, "Render 2D Elements in N64 Resolution sort of fixes it since the video is cropping is slightly off.

![gliden64_perfect_dark_000](https://user-images.githubusercontent.com/13986398/28080886-57521908-6622-11e7-9488-5dd2b9275244.png)

....but this is what happens when you do disable it. Re-enabling the setting doesn't fix it until you restart the level or go back to the main menu where you can select single or multiplayer. 

![gliden64_perfect_dark_001](https://user-images.githubusercontent.com/13986398/28080946-82751360-6622-11e7-989d-18eba2056e46.png)

**Comment by Frank-74** [comment]
Hmmm.  Opening config and clicking ok makes the video appear and the static turn black/white.

The video jumps around though.  It seems to go forward a few frames and jump back a couple of frames.  Very jerky.

**Comment by Yui12** [comment]
Well the fix is not permanent for some reason though since the game will just have pure static for me no matter what you do sometimes which means the 2D setting will have no effect. It sometimes works though. I wanted to say this since it will be helpful when it comes to tracking down the source of the bug.

**Comment by Frank-74** [comment]
I've recorded a video of what happens here: https://youtu.be/-G2oud4V9ik

You can see the blue static, I open gfx config, click ok, video appears.  You can see how stuttery and jumpy it is.  When it gets past the static, it's smooth.

**Comment by Yui12** [comment]
I should show you what happens on my setup. You're is something that I don't experience. I don't even get any stuttering at all. My CPU is i3 4370 and video card is a 750 Ti if that helps.

https://youtu.be/rOEMgoe_Eso

**Comment by Frank-74** [comment]
@Yui12 My specs are much lower.  Pentium N3540 quad core at 2.2Ghz, Intel HD Graphics.

I only get the frames jumping around, like forward/reverse, with threaded version of GLideN64.

But the blue static issue is the same.

Instead of changing any options, just click OK in the config.  I sometimes have to do it a couple of times before the video is displayed.

**Comment by Yui12** [comment]
That explains why it's jerky. My CPU has very fast single core that is on par if not better than some older i5s. What is even strange is if you try to mess around with the settings before starting a game, the the blurry background goes all black. Just how it is if "read every frame" was disabled in Glide64.

**Comment by Frank-74** [comment]
I think it's a problem with Async mode.  It's better performance and not stuttery at all with synchronous.  Though synchronous mode flashes a black screen on the video instead, and static is blue.  Opening config/ok sometimes makes the static black/white, but then I lose the video.

**Comment by Frank-74** [comment]
Solved!

It's caused by Project64 counter factor. It's set to 2, when set to 1 (Or set overclock to x2), video is smooth with async and static works properly.

**Comment by loganmc10** [comment]
@Frank-74 do you know of any downsides to having CF=1 for Perfect Dark?

**Comment by Frank-74** [comment]
@loganmc10 Yes, it messes a bit with audio/video timing (sync).  Only really noticeable on intro video sequences though.

**Comment by AmbientMalice** [comment]
Counter Factor 1 messes up the overall speed of the game. It's especially noticable when using combat stimulants. Also, it causes a problem where skipping cutscenes -- the intro to Carrington Villa in particular, causes the music to stop playing.

It's another example of why the hack-based approach to timing was not a great idea.

**Comment by loganmc10** [comment]
@Frank-74 have you tried any other video plugins? I experience the same thing on mupen64plus (video works properly with CountPerOp (CF) set to 1). However, I tried Glide64, and it worked with CountPerOp (CF) = 2.

**Comment by Frank-74** [comment]
@loganmc10 Yes, CF=2 is fine with Glide64 and Jabo 1.6.1.

**Comment by AmbientMalice** [comment]
What about an accurate plugin like Angrylion's? Or does that freeze in LLE?

**Comment by Yui12** [comment]
I personally tried both plugins and GlideN64 in LLE and Angrylion's and they freeze after the rare logo fades out so can't test with LLE on my setup.

**Comment by valcheeky** [comment]
Loading a savestate works with Angrylion

**Comment by Yui12** [comment]
Well that is a good idea and it worked. Here are the results.

Angrylion's Plugin (This plugin runs really slow 34VI on my machine though so it was not pleasant to get it running.

![npde0000](https://user-images.githubusercontent.com/13986398/28197716-91c492c2-680d-11e7-9de4-867737f723ce.png)

![npde0001](https://user-images.githubusercontent.com/13986398/28197733-b257b3b6-680d-11e7-8ffa-3bd441f57bfb.png)

GlideN64 LLE (It's fast, but this plugin has issues with many games having these white lines breaking through the visuals. 

![gliden64_perfect_dark_000](https://user-images.githubusercontent.com/13986398/28197741-ba20c178-680d-11e7-8513-a5feb3d8f684.png)

**Comment by gonetz** [comment]
@Frank-74  
>It's caused by Project64 counter factor. It's set to 2, when set to 1 (Or set overclock to x2), video is smooth with async and static works properly.

Can it be closed then?

**Comment by AmbientMalice** [comment]
The problem is that this issue doesn't occur on Angrylion's and Counter Factor 1 makes this game misbehave.

**Comment by gonetz** [comment]
I managed to get correct result few times with CF 2. It is pure synchronization problem. Synchronization problem can't be solved on plugin's side. When emulator produces good display list, plugin works correct. May be it is possible to find what is wrong and find a workaround,  but it is not right. 
Btw, how it works with other emulators?

**Comment by loganmc10** [comment]
@gonetz the same thing happens in mupen64plus. It works with CountPerOp=1, but it also works with Glide64 with CountPerOp=2, so it does work with that, and it does with work Angrylion at CountPerOp=2

**Comment by gonetz** [comment]
I tested current master with Project64 2.4 and mupen64plus. Area 51 Infiltration intro works without problems with both emulators.

**Comment by gonetz** [comment]
Works fine for me, so closed. Please reopen if problem still not fixed.
