### ISSUE TITLE
we want to use your source code as Apache or BSD license compared to GPL 2 after your agreement.

### ISSUE THREAD

**Issue by byungjoohwang** [gonetz/GLideN64#1524]
Dear gonetz,

This is Mr. Byungjoo Hwang working for LGElectronics in S.Korea.

When I googled, your open source is based on the GPL v2.

We want to use one source code only as CRC32_ARMV8.cpp. but Our company is not permitted about GPL.
If you are agree, could you please change open source license as Apache 2 or BSD 3 license because
GPL v2 is the strong copyleft license.

Best regards,
Byungjoo Hwang

**Comment by twinaphex** [comment]
I'd argue this would be even more reason to keep it as GPLv2. No corporate welfare for you.

**Comment by fzurita** [comment]
It's very unlikely that gonetz will relicense this project

**Comment by gonetz** [comment]
I personally don't mind if any part of my code will be used with non-gpl license. The problem is that CRC32_ARMV8.cpp is not my code. I'm not expert in arm asm. You need to ask the author of that file, because he can have different opinion about this matter.

**Comment by gizmo98** [comment]
I am the author. I don't mind if this code is used with non-gpl licence. 

The main idea was taken from this site: 
https://wiki.linaro.org/LEG/Engineering/OPTIM/CRC

I think our implementation is no 1:1 reimplementation because we use intrinsics and a different structure.

**Comment by gonetz** [comment]
@byungjoohwang Stefan made CRC32_ARMV8.cpp dual-licensed:
92f5246eb62b
Does it fix the problem with licensing for you?

**Comment by byungjoohwang** [comment]
I'm closed. Thank you for your support so much!

**Comment by gonetz** [comment]
You welcome. You may consider to support our project too, for example there:
https://igg.me/at/swrs
