### ISSUE TITLE
LOZ: Majora's Mask Lens of Truth Don't Work

### ISSUE THREAD

**Issue by Krix1502** [gonetz/GLideN64#1525]
![base profile 07 12 2017 - 16 03 18 02](https://user-images.githubusercontent.com/30120100/28121535-b18405a4-671b-11e7-8718-108eb349e5e9.png)
I use Project 1.6 and 2.3 and newest WIP Gliden64 build/Public Release 2.0 and still don't work. Maybe Djipi Texture Pack is problem? Please help.

**Comment by AmbientMalice** [comment]
It's very likely a texture pack probelm. Does removing the texture pack fix it?

**Comment by Yui12** [comment]
Seems like it is. Works fine after testing.

![gliden64_zelda_majora s_mask_001](https://user-images.githubusercontent.com/13986398/28148755-9101f904-673d-11e7-8bb9-8060eb8f4754.png)

**Comment by gonetz** [comment]
I several times explained, that LoT texture **must not ** be re-textured. It breaks LoT algorithm. Find and remove texture for LoT from the pack and everything will work fine.
