### ISSUE TITLE
Paper Mario: Black sprites in Forever Forest

### ISSUE THREAD

**Issue by FraganciaGH** [gonetz/GLideN64#1528]
![pm_black_sprites](https://user-images.githubusercontent.com/14110425/28343611-7c59f4d0-6c1e-11e7-91ec-b2a176dd101b.png)

I'm using the public release 2.0 of GlideN64
The black sprites aren't limited to Forever Forest, it happens in the Toad Town sewers and Dry Dry Ruins.
It seems to happen whenever you enter an area that's dimly lit.

**Comment by Pop000100** [comment]
it has to do with the fix black lines option check use n64 resolution for 2d elements.

**Comment by DonelBueno** [comment]
Try the last build posted here: https://github.com/gonetz/GLideN64/issues/1364

**Comment by FraganciaGH** [comment]
@DonelBueno 
I tried the latest build as well, it didn't make a difference.

@Pop000100 
I tried that and it didn't help, it made the texts slightly harder to read though
![pm_bs_p1](https://user-images.githubusercontent.com/14110425/28720976-0069f81e-73af-11e7-87cc-1b06339b403d.png)
![pm_bs_p2](https://user-images.githubusercontent.com/14110425/28721016-21745342-73af-11e7-9e1f-f20a27e1a030.png)


Sprites turn normal for the duration you are submerged in water with Sushie in the sewers.
![pm_bs_p3](https://user-images.githubusercontent.com/14110425/28721132-9c6f5510-73af-11e7-8771-1788146a26da.png)
![pm_bs_p4](https://user-images.githubusercontent.com/14110425/28721138-9fbc9e9e-73af-11e7-91b4-10c71950592b.png)

I did manage to find a temporary fix to this problem, which is to switch graphics plugins when the game is running, it only lasts for as long the game is running.
e.g switching to Jabo's Direct3D8 in the affected areas before switching back to GlideN64 2.0

**Comment by FraganciaGH** [comment]
So it turns out that the black sprites only seem to occur when I use the multiplayer version of Paper Mario made by Skelux.

Development thread
http://origami64.net/showthread.php?tid=727
Release video
https://www.youtube.com/watch?v=t06oKd7Aq38

I compared the original and the multiplayer one and the original doesn't have this issue leading me to assume the problem lays purely with the MP version.
I think I will close this issue and report this issue over to the development thread for paper mario multiplayer.
