### ISSUE TITLE
Emulating Nintendo 64 3-sample Bilinear Filtering (using Shaders)? Code available

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#153]
It is an "enhancement" but it looks nice and is closer to the N64 way of filtering

Some games may get rid of some issues (Quest 64 letters?)

See code and explanation here:

http://www.emutalk.net/threads/54215-Emulating-Nintendo-64-3-sample-Bilinear-Filtering-using-Shaders

Seems nice, may be hacky?

**Comment by gonetz** [comment]
Implemented. Feedback needed.

**Comment by gonetz** [comment]
Can be closed?

**Comment by olivieryuyu** [comment]
we can close the general ticket as it is implemented. However there is some stuff that are not fixed by this implementation. i was expecting that for instance Bomberman Hero title screen would not have blues all around.

![arf](https://cloud.githubusercontent.com/assets/8987490/6885518/53fcc172-d623-11e4-80f1-eb40274fa682.jpg)

**Comment by olivieryuyu** [comment]
we could open separate tickets in this respect for those issues
