### ISSUE TITLE
Very Slight 2D Image Graphical Glitches in Hey You, Pikachu!

### ISSUE THREAD

**Issue by Ecksters** [gonetz/GLideN64#1532]
If you enter an area and then open the PokeHelper and say "Go Home" the game will almost always play some cute image with you at home, these images for some reason have lines going through them:
![Hey You, Pikachu! 2D Image Glitch](http://i.imgur.com/Hxd1VVd.png)

![Hey You, Pikachu Another 2D Image Glitch](http://i.imgur.com/Cmy9ucR.png)

What's interesting is that the glitch clearly follows the smaller images themselves on the 2nd image here, as they're animated for a bit.

Save States/Save File to get past the first part without the mic are here:
https://www.mediafire.com/folder/ve1rdcrkiry2q/Hey_You%2C_Pikachu!

Using Save States in PJ64 crashes for me soon after the new state is loaded, anyone else having this issue?

**Comment by loganmc10** [comment]
I believe lines like that show up when the game isn't be played at native resolution. I think enabling "Native Res Texrects" or settings "native resolution factor" to 1 will fix it.

The same thing happens to the player portraits when choosing a player in Mario Kart

**Comment by gonetz** [comment]
"Fix black lines between 2D elements" may help too.

**Comment by Ecksters** [comment]
So I tested with Fix black lines between 2D elements, none of those settings seem to fix it, and "Render 2D elements in N64 resolution" also doesn't fix the issue. However, I can't see it if I do Original N64 resolution, but multiples of N64 resolution still have the lines.

**Comment by gonetz** [comment]
"Render 2D elements in N64 resolution" works for me:
![pikachu](https://user-images.githubusercontent.com/8983092/28753971-5f7046d4-7566-11e7-9df0-6b89fde199b9.png)

**Comment by gonetz** [comment]
I close this ticket. Issues with 2D graphics are not this game specific. General solution is to use rendering in native resolution.
