### ISSUE TITLE
compiling on arm libpng.a problem

### ISSUE THREAD

**Issue by knuxyl** [gonetz/GLideN64#1533]
```
../GLideNHQ/lib/libpng.a: error adding symbols: File format not recognized
```

also NEON flag throws a bunch of errors about unsupported instruction or something

**Comment by gizmo98** [comment]
Adding -DUSE_SYSTEM_LIBS=On and export CFLAGS=-mfpu=neon -march=native -mfloat-abi=hard before cmake runs should solve your problem.

**Comment by gonetz** [comment]
To avoid misunderstanding:
1.  export CFLAGS=-mfpu=neon -march=native -mfloat-abi=hard
2. Add "-DUSE_SYSTEM_LIBS=On " to cmake parameters.
That is 
cmake -DUSE_SYSTEM_LIBS=On -DNEON_OPT=On -DMUPENPLUSAPI=On path_to_sources
