### ISSUE TITLE
Star Wars Rouge Squadron Title screen balck

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1536]
I noticed when testing this game today that the title screen works with GLideN64 if you fail a campaign by crashing 3 times. You will eventually get back to the title screen and it will render instead of being black. 

I hope this is a clue to why it will not render when you start a game on first run. Here is a save state that meets this condition. 

[Star Wars - Rogue Squadron (U) (V1.1).pj.zip](https://github.com/gonetz/GLideN64/files/1168481/Star.Wars.-.Rogue.Squadron.U.V1.1.pj.zip)

**Comment by loganmc10** [comment]
It also works if you toggle full screen or open/close the config dialog in PJ64. Basically if you restart the plugin then the black screen goes away. The problem started in the VI refactoring

**Comment by LegendOfDragoon** [comment]
prolly related to interlacing

**Comment by olivieryuyu** [comment]
https://sourceforge.net/p/angrylions-stuff/code/99/tree//trunk/mylittle-nocomment/n64video.cpp?diff=55bb05dc27184618d775bec1:98

@gonetz 

This commit seems interesting. Apparently it fixes many issues in games with interlacing and may be it would help to fix the menu of SWRG. I can imagine that it does have an impact on the height of the framebuffer effects which few games still miss to handle correctly.

**Comment by gonetz** [comment]
>>This commit seems interesting. 

Badly organized commit. Several different fixes merged in one commit. Hard to find, what can be useful for my needs.

**Comment by theboy181** [comment]
@LegendOfDragoon do you have the meaning behind this commit ? I'm sure @gonetz could use your halp

**Comment by gonetz** [comment]
I don't need help to fix this issue, since I already fixed it. The fix will be available with next alpha/beta for Indiegogo campaign.

**Comment by theboy181** [comment]
I am wondering what was needed to fix this issue, and if it helped Gauntlet's health bar.

**Comment by gonetz** [comment]
> I am wondering what was needed to fix this issue, and if it helped Gauntlet's health bar.

Nothing special. I removed an optimization, which had bad impact in this case. I doubt that it will help any other game.
