### ISSUE TITLE
Paper mario has jumbled textures.

### ISSUE THREAD

**Issue by Pop000100** [gonetz/GLideN64#1538]
![gliden64_paper_mario_000](https://user-images.githubusercontent.com/20156032/28709106-48925980-732b-11e7-90fe-05ade2f015f8.png)
![gliden64_paper_mario_001](https://user-images.githubusercontent.com/20156032/28709107-4898c0ae-732b-11e7-94c8-6b9b6ae45be9.png)

i have tried tinkering with setting i haven't found a fix.

**Comment by gonetz** [comment]
Looks like some texture enhancement filter enabled.

**Comment by fzurita** [comment]
Not having LOD enabled can cause a similar issue.

**Comment by Pop000100** [comment]
i disabled all texture enhancement and it still occurs.

> Not having LOD enabled can cause a similar issue.

how do you enable Level of detail

PS forgot to say  PJ 2.3 is the running version

**Comment by gizmo98** [comment]
@fzurita 
Thank you for this information! Raspberry Pi does not support LOD. I was always wondering why some textures look wrong.

**Comment by fzurita** [comment]
@gizmo98 no problem. @Pop000100 it looks like LOD is always enabled for the zilmar spec plugin. So I'm not sure what your problem is.

**Comment by gonetz** [comment]
> it looks like LOD is always enabled for the zilmar spec plugin.

No, it does not. There is an option for it: "Enable N64-style mip-mapping"
Mip-mapping on:
![gliden64_paper_mario_000](https://user-images.githubusercontent.com/8983092/28764820-c2d347ea-75f1-11e7-97c2-4a423052d346.jpg)

Mip-mapping off:
![gliden64_paper_mario_001](https://user-images.githubusercontent.com/8983092/28764832-ccdb4b02-75f1-11e7-9ca3-6c909adac72a.jpg)

Thus, mip-mapping **must be on** for this game.

**Comment by fzurita** [comment]
Ok, thanks, I completely missed that option, so I jumped to the conclusion that it was always enabled.

**Comment by gonetz** [comment]
Actually my answer was for @Pop000100, because it shows the root of his problem.

**Comment by gonetz** [comment]
I close this ticket because solution is found.
