### ISSUE TITLE
Turok 2/Turok 3 Per Pixel Lighting Rainbow Weapons.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#1542]
Without Per Pixel Lighting:
![gliden64_turok_2 _seeds_of_ev_001](https://user-images.githubusercontent.com/10704701/29016865-8d1d937a-7b97-11e7-9076-3a77187d62b6.jpg)

With Per Pixel Lighting:
![gliden64_turok_2 _seeds_of_ev_000](https://user-images.githubusercontent.com/10704701/29016878-9729b2c2-7b97-11e7-9c47-56d01079671c.jpg)

**Comment by gonetz** [comment]
Ok, I'll disable Per Pixel Lighting for this microcode.

**Comment by adiastra** [comment]
I dont know, rainbow weapons are kinda cool ;)

**Comment by tony971** [comment]
> Ok, I'll disable Per Pixel Lighting for this microcode.

Unrelated, but the same needs done for F3DAM.

**Comment by AmbientMalice** [comment]
I assume the reason this breaks is because the Turok ucode approximates point lighting?

**Comment by gonetz** [comment]
Yes. Hardware lighting must not be used for games with custom lighting methods.

**Comment by gonetz** [comment]
@tony971 F3DAM uses standard lighting. Does it have problems with hardware lighting too?

**Comment by tony971** [comment]
Yes, you can see the issues on the main screen of Hey You, Pikachu! With hardware lighting, the shadows on Pikachu's body are inconsistent and fragmented.

**Comment by DonelBueno** [comment]
Pokémon Stadium and Pokémon Stadium 2 also have issues with per-pixel lighting. The shadows on the pokémon bodies get messed up.

**Comment by fzurita** [comment]
Similar issue with South Park 64, all the characters are rainbow colors in that game.

**Comment by AmbientMalice** [comment]
That's because Turok 2, 3, South Park, and Armorines all use the same ucode and same engine.

**Comment by mudlord** [comment]
Whats stopping you from writing shaders for each different light microcode then?
