### ISSUE TITLE
libretro support

### ISSUE THREAD

**Issue by orbea** [gonetz/GLideN64#1544]
Hi,

Can we please have an upstream supported libretro core? GLupeN64 worked a lot better than GLideN64 does with mupen64plus upstream. Do to extremely silly reasons not worth going into here the GLupeN64 maintainer called it quits and the core now rebranded as mupen64plus-libretro has been stagnating since. The project worked too well to abandon and it would be great if someone with the will and the required skill set could maintain it properly. Thanks!

https://github.com/libretro/mupen64plus-libretro

**Comment by AmbientMalice** [comment]
GLupeN64 ended up becoming https://github.com/m64p/mupen64plus-GLideN64 Backporting changes to a version of mupen64plus that is compliant with the established plugin standard is fairly simple. (GLideN64 is complaint with both the Zilmar and mupen64plus specifications.)

It's really up to SP and other Libretro people to backport GLideN64 improvements to their version(s) of GLideN64. I think you're asking in the wrong place. I am under the impression that there is currently more focus on parallel-n64's vulkan renderer ATM.

**Comment by orbea** [comment]
I understand the difficulties hence why I was trying to reach out to people who are familiar with GLideN64 and could continue the project properly. The libretro project has an abundance of cores and not nearly enough devs to maintain them all, it would really help if some could help out in cases like this when a worthy core as GLupeN64/mupen64plus-libretro starts to fall out of date. When GLupeN64 was maintained many issues were solved as a result, this includes in GLupeN64, GLidenN64, RetroArch and even mesa, there is a lot of room for cooperation here. :)

Also Parallel-n64 has a pretty different focus and should not be in direct competition with GLideN64.

**Comment by SigmaVirus** [comment]
I absolutely love GLupeN64! That project died way too soon to be honest.

GLupeN64 set to native 320x240 resolution with a nice NTSC S-Video shader looks so damn good that it's ridiculous.

I'm still using official GLupeN64 in RetroArch even today and find it working very very well for the most part but I still have to rely on Project64 1.7.0.50 rev23 with latest GLideN64 sometimes.

It's a shame it had to end so soon, good N64 alternatives are hard to find and even https://github.com/m64p/mupen64plus-GLideN64 or ParaLLEl-N64 isn't just the same.

**Comment by orbea** [comment]
Yea, there was more to GLupeN64 than just GLideN64, mupen64plus-core and the rsp plugin are required too. I'm not sure what the best way to address this is, but regardless I think its a good thing for mupen64plus and GLideN64 development to collaborate on. mgba provides an excellent libretro core which is maintained in their cmake build and I think it would be very valuable to have an updated version of GLideN64 + mupen64plus-core + rsp plugins which doesn't fall into the trap of yet another unmaintained libretro core. The honest reality is that there are just that many cores than developers and if any qualified n64 emu devs want to help fill that gap I can at least help with debugging.

Also, good to see you around @mudlord. :)

**Comment by oddMLan** [comment]
I think this ticket can be closed. mxw4 is the current maintainer of the libretro core (mupen64plus-next). Last time I checked, code is already keeping up with upstream.

**Comment by gonetz** [comment]
Ok, closed

@m4xw please reopen or open new issue if something is required for libretro support from GLideN64 side .
