### ISSUE TITLE
Crash in Cruis'n Exotica (VEC4_OPT)

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1549]
Crashes a few seconds after the game starts. It worked fairly recently, here is the backtrace:

```
Thread 1 "mupen64plus" received signal SIGSEGV, Segmentation fault.
0x00007fffec1e352f in gSPVertex (a=286331136, n=17, v0=4294967279) at /home/loganmc10/mupen64plus-GLideN64/GLideN64/src/gSP.cpp:1010
1010					vtx.x = vertex->x;
(gdb) backtrace
#0  0x00007fffec1e352f in gSPVertex (a=286331136, n=17, v0=4294967279) at /home/loganmc10/mupen64plus-GLideN64/GLideN64/src/gSP.cpp:1010
#1  0x00007fffec1b6dcb in F3DEX2_Vtx (w0=17895680, w1=286331136) at /home/loganmc10/mupen64plus-GLideN64/GLideN64/src/F3DEX2.cpp:52
#2  0x00007fffec1f273f in _ProcessDList () at /home/loganmc10/mupen64plus-GLideN64/GLideN64/src/RSP.cpp:55
#3  0x00007fffec1f2c58 in RSP_ProcessDList () at /home/loganmc10/mupen64plus-GLideN64/GLideN64/src/RSP.cpp:153
#4  0x00007fffec213d8b in PluginAPI::ProcessDList (this=0x7fffec96fce8 <PluginAPI::get()::api>)
    at /home/loganmc10/mupen64plus-GLideN64/GLideN64/src/common/CommonAPIImpl_common.cpp:159
#5  0x00007fffec1afce1 in ProcessDList () at /home/loganmc10/mupen64plus-GLideN64/GLideN64/src/CommonPluginAPI.cpp:23
```

**Comment by Tasosgemah** [comment]
Looks fine on PJ64, i managed to play a whole track. Using the 9818306 GlideN64 build.

Maybe it only affects Mupen?

**Comment by loganmc10** [comment]
I doubt it, it looks like it's pointing to an invalid pointer or something. Maybe it doesn't cause a crash in Windows or Project64, bit it's still an issue with GLideN64

**Comment by loganmc10** [comment]
I guess it's older than I thought. I tested all the way back to April of this year and it still happens there. It only happens with VEC4_OPT though, which explains why it wasn't happening in PJ64 (the PJ64 build doesn't have that enabled).

**Comment by gonetz** [comment]
It is mupen64plus core bug. I made zilmar-spec build with VEC4_OPT, it does not crash with Project64.
mupen64plus passes wrong parameters to vertex command. Start vertex index becomes negative, but since unsigned int is used, it becomes just huge and out of bounds read happens.
I can add a test for parameters validity, but it is workaround for real problem.

**Comment by loganmc10** [comment]
Just to make sure I understand, you're saying that the problem is ```v0=4294967279```? I just tested this again on Linux and I couldn't reproduce it, so either some recent change to mupen64plus fixed it, or it somehow only affects mupen64plus on Windows

**Comment by gonetz** [comment]
> the problem is v0=4294967279?

Yes

**Comment by loganmc10** [comment]
I tracked it down, it was a core bug that was fixed by commit https://github.com/mupen64plus/mupen64plus-core/commit/2379d07f85498517c6d91e39a2c4e7c2967172d9 in mupen64plus. thanks!
