### ISSUE TITLE
Feature Request: Add cropping to the outer border to remove that darn overscan.

### ISSUE THREAD

**Issue by retrobenny** [gonetz/GLideN64#1554]
This is a quality of life feature request that I am sure that pretty much everyone wants so they can scale per game with overscan border cropping to remove or at least greatly reduce the bordering in case some games output multiple resolutions that may end up cut off of the screen.
The guide is to make sure the game is in its largest scale so that cropping the outer border doesn't get cut off because of cutscene border distance confusion.

An alternate option could be done via emulator compliance that adjusts the window scale for windowed mode to cut out the borders upon enabling the setting to be added to GLideN64 and something more difficult to handle that in full screen due to complications.

Edit: the borders look worse the larger your resolution settings are,so 1080P or 4K even with equivalents of integer scale of 1X native N64 resolution will look devastating!!!

The end result for 640x480 would change this...

![image](https://user-images.githubusercontent.com/16418716/29603869-58b00332-87ab-11e7-963d-0333a03db16c.png)

To THIS! (but think of it with the window intact and without my snipping inaccuracy)

![image](https://user-images.githubusercontent.com/16418716/29603931-84988e38-87ab-11e7-9d09-23d935383fdf.png)

Does anyone agree?

**Comment by tony971** [comment]
I just set the crop mode to 2 and manually trim it off.

**Comment by retrobenny** [comment]
I didn't know there was another mode that did that?!?

How? All it did for me was that it cut off content within the black border that remained intact instead of shrinking.

Would someone please provide a step-by step guide in the options via images how to make this happen?
I need to make the most out of my screen space by having the windows filled since plugin options are very limited in newer PJ versions of master that contain Shygoo's debugger.
It would allow to make better video recordings via the specified PJ64 window without those borders.

Despite that existing in crop apparently,I think it would still be better to have an option to keep 1:1 scale of the chosen resolution but to remove the borders by making the window smaller to enclose those overscan bars.
This would make it look better than stretching or zooming into the image at all and save some extra screen space for something like the memory viewer and the commands breakpoint window,that's if its possible.

**Comment by theboy181** [comment]
Ben. I shared a code where I was able to return a game to full screen by removing the black borders in that jap gambling game. I'm sure that other games will have the same concepts. I think it's a good idea to study how that hack works and make a GS code to restore the game to 640x480. Cropping hack can lead to undesirable results in GLideN64

**Comment by retrobenny** [comment]
Read the last parts for simpler info,I apologize for my passion at the bottom.

I believe that game has the default overscan capable of fitting the entire screen while it uses either less scaling or less of a resolution to simulate the overscan instead of actually using it on the VI process or whatever you call the real equivalent to VI Emulation.
This is unfortunate for games that don't do that,as Banjo-Tooie freaks out if I set its values to full 0140 00F0 sometimes and the game uses several unique slots for the less than 640x480 scale it uses for TV screens.
I managed to increase the view on DK64 but its missing some stuff and has problems because of the instrument playing causing resolution swaps and the cuttscenes actually manipulating the resolution unlike Zelda Ocarina's cutscene bars.
Making the overscan minimal for this game via my idea of making the emulator window shrink to obscure the intact overscan would be better than using a code to do it because it would be global for the entire render make and the scale would be untouched.

My idea in concept is to trick the emulator itself to shrink its window to reduce the overscan without touching the actual render size,so technically you would be getting screen cutoff of the overscan while still rendering it fully,now beyond the dimensions of the window/fullscreen viewport itself.
You just don't have it visible to you if you make the emulator hide it from view but it will actually still be emulated and rendered despite being obscured.

This idea would be extra effective with very large resolution scales by using the largest integer and/or stretching so that the game fits without almost no bordering aside from natural cutscene borders.
(unless you use my cutscene border removal code for Zelda OOT which keeps the view at a maximum)

On an ending note,one of my codes attempting to boost resolution caused GLideN64 to exhibit flickering and would likely also do this with Angrylion LLE and the actual console,so codes can be terribly unusable sometimes.
(you forgot that I got screen flickering at one point on that Jap gambling game {its Pachinko |put Solid Snake Pachinko machine reference here| } with the resolution code you shared)

The GFX plugin can control the emulator window size,especially with the example of extreme widescreen resolutions,so this idea of mine is very much possible to accomplish,it takes the window itself and shrinks it down to meet the non-overscan portion of the screen without touching the actual scale and without affecting VI Emulation at all if things can end up coded properly after enough programming optimization.
It could also be programmed to allow stretching/adjusting to upscale safely to match what the window size would be and bring it up to where overscan normally is,technically being larger than 640x480 while the window is that size but still not actually cropping anything,just scaling it and still having overscan cutoff outside of the screens regions.

Every 4 and 3 for the 4:3 aspect could be used for maximum precise integer scaling to end up with strange sounding resolutions that still apply the correct aspect ratio,so the integer scaling would work well in fullscreen to minimize the overscan visibility by having it cutoff as far as possible for game specific settings that people could figure out and help add to a growing list.
By this you aren't cropping it but instead obscuring its visibility without zooming in and using a slightly larger resolution that goes offscreen in order to fill it with the game's entire render size without using any actual cropping,as cropping doesn't change the window size but instead zooms in the game render without shifting the overscan if using normal cropping while the mentioned other cropping method has been said to actually break things because it physically manipulates the VI overscan instead of doing something potentially safer that leaves VI overscan itself untouched but obscured from view.

way tl;dr

Sorry for the long-worded but in-depth explanation.

The simplified answer would be like simulating an Uber-TV that can show the game with the least amount of or almost no overscan borders at all with no negative side-effects.
Simulate that type of TV then make that the window size and have the option to use resolution compensating to adjust it back to conventional sizes for an overscan-less 640x480 window for example.
With this you aren't removing the overscan or modifying VI,just hiding most of it from view. by changing the window size.
I would say the current single TV (or multiple TV's?) "emulated" has a terribly large overscan size which explains the huge chunk of bordering.
Why I say emulated TV is because at least a certain Dreamcast emulator has choices to simulate HDMI or other cable types and Dolphin has settings to use progressive mode for simulating the use of those component cables instead of composite cables which I can admit the real console had better quality audio and video with component cables and progressive scan when jamming to Big Blue on Melee through my stereo's speakers via the TV headphone jack into its ironically composite audio slots that still sounded better than both being composite.

**Comment by retrobenny** [comment]
Got a better much shorter answer.

Instead of cropping the game screen or cropping overscan,you would be cropping the emulator window itself!
This would leave VI emulation and the game rendering untouched.
Aside from using different resolutions than 1x Native which is being done anyway,but this is different than the cropping part.

**Comment by gonetz** [comment]
> Add cropping to the outer border to remove that darn overscan.
Done in #1818
