### ISSUE TITLE
Under-utilized CPU usage bug on Synchronous FBCopy with new PJ64 builds.

### ISSUE THREAD

**Issue by retrobenny** [gonetz/GLideN64#1557]
Using GLideN64 Public Release 2.0 because it doesn't glitch graphics on resets,if I use Synchronous FBCopy,even with the fastest of other settings,I get abnormally slow performance while Asynchronous performs at adequate levels,even really good performance on Interpreter.
Game tested is Toy Story 2 on Interpreter even though its known to crash via TLB Miss currently since the oldest 2.x versions as 1.7 lacks this crash.

Good performance-
![image](https://user-images.githubusercontent.com/16418716/29744647-b0fd31ca-8a6e-11e7-80a9-90023fa0dc46.png)

Bad performance with low CPU usage regardless of fps limit-
![image](https://user-images.githubusercontent.com/16418716/29744653-d976bf7c-8a6e-11e7-800c-94c512b14a30.png)

With Synchronous I get a fixed rate of 18VI/s and 9DL/s according to the OSD with a negligible 7-9% CPU usage instead of in the 30% range,even with unlimited fps in use.

Note: Google Drive is still being garbage because it won't play videos directly,I blame the YT integration.
I also can't stand the greatly reduced quality of my already small filesizes where things become unreadable because of their encoding phase,this is why I started using 1080P instead of 720p to reduce how crappy they end up. If I have to,I will upload these to my YT channel as unlisted.

**Synchronous** (ignore OBS usage as PJ64 2.4.0-444 also gets low usage on no recording with no other program taking any):

https://drive.google.com/open?id=0B1nr_75cEfQOVVdwRk11cTAtRmM

**Asynchronous** (video much shorter due to avoiding the known emulation crash):

https://drive.google.com/open?id=0B1nr_75cEfQObE1RRkJ2ejh6Qkk

The .mov format should be easily playable as both Windows 10's default and the latest Media Player Classic Home Cinema can play this format just fine.
I am using .mov now to try to get better encode quality than the MP4 format.

Edit: It also runs Synchronous at 18VI/s 9DL/s even on full recompiler with both caches and Advanced Block Linking enabled.

**Comment by loganmc10** [comment]
There is nothing wrong with the CPU, the bottleneck when using synchronous copies is the GPU (or more specifically, data copying between the GPU and CPU). This is the whole reason asynchronous copies were implemented

**Comment by retrobenny** [comment]
So should I overclock my Nvidia GeForce GTX 940MX to either match 940M's 1Ghz or to 10% more than its current clock to mitigate this?
This would potentially also boost fps in a number of other emulators and games on higher settings at the risk of making my laptop hotter.

![image](https://user-images.githubusercontent.com/16418716/29745303-abad9b98-8a7c-11e7-85a6-4a6b40405418.png)

**Comment by retrobenny** [comment]
![image](https://user-images.githubusercontent.com/16418716/29745649-80a9ed2a-8a86-11e7-89fb-e9cf8c27342d.png)

**Comment by LegendOfDragoon** [comment]
Underutilized CPU usage isn't a bug. That's how things work.

The code could use some optimizations to reduce the bottleneck.

**Comment by retrobenny** [comment]
Ninja'd!

Stock clocks btw.

**Comment by retrobenny** [comment]
And 1080P runs like crap with the other features enabled,not worth doing the benchmark there.

First thing this tells me is that I need the best cooling fan I can get for a half decent price. 30$-90$/100$

**Comment by retrobenny** [comment]
I wonder,if Sync mode can get some much wanted optimizations,would Async mode also benefit with faster performance?
If that is true,then it would benefit both modes with Async's benefits being tenfold or perhaps greater than that. So much that modern blending would actually start performing decently on Android when using Native scale (1080P on my SATV) on Mupen64Plus FZ Edition.

**Comment by gonetz** [comment]
What actions expected from my side to close this ticket?

**Comment by retrobenny** [comment]
Find a few ways to optimize Sync mode to make it run a bit faster...😕
This is focused on those who want 1:1 timing (no risk of frame drops and to avoid issues found in Async) but also wanting decent performance.

Any improvements on Sync mode would most likely improve Asynchronous mode's performance too.

**Comment by gonetz** [comment]
It is not in my competence. You need to ask GPU vendors about it.

**Comment by retrobenny** [comment]
So, do you believe that its something with the drivers?
I would figure trying to refactor the whole color buffer at an attempt to reduce its performance intensive tasks would be a good starting point.
It still doesn't add up why the usage can't reach at least around 30% for a single CPU core's maximum and only reaches less than 20% usage.

Either that or someone can try to find out how to make Asynchronous mode never drop frames at the very least.
Though,the frame drops may be a Windows only issue,I get no drops at all when on Android and Asynchronous mode is in use,at least when the game is set with CountPerOp 1 and max VI Refresh Rate of 3000 which makes it definitely never drop frames at the cost of broken timing,but I think using CPO 1 still prevents the frame drops.
(really could use a proper OC'ing option in FZ Edition to avoid desyncs with stuff like DK64 and 60fps codes that can be caused by a higher VI Refresh Rate value)

**Comment by fzurita** [comment]
If FBInfo is implemented, you can get all the benefits of sync buffer reads with almost none of the performance penalties. This is because GLideN64 will only read when the core asks it to read.

**Comment by retrobenny** [comment]
Is the task for FBInfo support directed to the emu developer or anyone else that has access to doing so?
If so,I should ask zilmar and/or post an issue there requesting for FBInfo support so that GLideN64 can make good use of it.

Hmm...would FBInfo work on Asynchronous mode?
That would make performance insanely fast if both can be used and it they get along just fine.

**Comment by loganmc10** [comment]
Fbinfo is currently broken in GLideN64, there is a ticket:

https://github.com/gonetz/GLideN64/issues/1559

Once that is fixed, I will finish fixing it in mupen64plus, I've already started the work:

https://github.com/mupen64plus/mupen64plus-core/pull/376

**Comment by olivieryuyu** [comment]
now can we close this ticket? There is not much that can be done here.

**Comment by retrobenny** [comment]
Yeah,I guess. The focus would be on FBInfo support becoming functional so that the option has a reason to exist.

**Comment by olivieryuyu** [comment]
thanks!
