### ISSUE TITLE
3-point texture filtering doesn't work with mipmapped textures.

### ISSUE THREAD

**Issue by DaRkL3AD3R** [gonetz/GLideN64#1558]
http://imgur.com/a/tobYp

Same output as bilinear filtering when selecting 3-point N64 style.

**Comment by AmbientMalice** [comment]
It's impossible/extremely difficult to apply 3-point to mipmapped textures.

**Comment by Papermanzero** [comment]
In general the filtering feature has to be reworked.
https://github.com/gonetz/GLideN64/issues/944

Currently we have bilinear and 3-point as seperate filters. Plus, we have smooth and sharpen filters as on-top filters. Glide64 has the feature to use the original n64 filter setting, to filter all textures according to 3 point, and to filter all textures with biliear.

**Comment by DaRkL3AD3R** [comment]
Testing the latest build https://drive.google.com/file/d/1LG-_khXKTUqe_-B2uv-3_YkSkvSe9oEq/view?usp=sharing and finding 3-point texture filtering is still not working properly. The example pictures in my OP post (https://imgur.com/a/tobYp) are exactly the same with the new builds. Only difference is now triangles are randomly missing from various surfaces in games.

**Comment by gonetz** [comment]
I know, that 3 point texture filtering works. The problem that it was not applied to mip-mapped textures, which always use standard bilinear filtering, as illustrated on your original screen shot from Turok. I used the same place from Turok to test my fix. I got different results with both filtering methods for wall textures, which use mip-mapping. The bush texture does not use mip-mapping. As I remember, wall textures in Zelda MM do not use mip-mapping either, so they are not good for testing that fix. The difference in Turok wall texture between both filtering modes is very subtle, but visible.

**Comment by DaRkL3AD3R** [comment]
On latest build as of today, there is new glitch with 3-point texture filtering. Seems to do with mipmapping and sharp angles. See here: https://imgur.com/a/97K9Qhu

And to be sure, pixel accurate plugins look like the bilinear version of these pics, no green smear on mipmaps. But at least triangle stripes disappearing has stopped.

**Comment by gonetz** [comment]
I fixed this issue too. Text build:
https://drive.google.com/file/d/12WXQ4fy5uwqRNXW9udKwKDrT5nhegQ6j/view?usp=sharing

The bug was in very unexpected place. The fix may improve emulation of mip-mapped textures in general. Good, that you noticed that glitch.

**Comment by DaRkL3AD3R** [comment]
Very nice, textures looking great again on this test build.

**Comment by oddMLan** [comment]
Oh boy, maybe the fence glitch in DK64 is fixed with this... can anyone check?
