### ISSUE TITLE
Star Wars - Rogue Squadron . Feature Request for WS Hack.

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1560]
Star Wars - Rogue Squadron (U) (V1.1)

81121820 3FAA
81121822 3D71

Note: this is WIP and doesn't work well with the cut scenes yet, but will be dealt with once other culling issues can be resolved. 

This hack is a great start, but I am having the same old issue with the anything outside of the 4:3 are culling things like the backgrounds. This can be observed on other games like SSB64. 

I was hoping @gonetz would look a little closer at his plugin to see if this issue is related to view port rendering size, and see if the hack can be extended to make better hacks for games in the future.

I have come across some other ways to get around this issue like making the backgrounds larger, but more info would be appreciated. 

![image](https://user-images.githubusercontent.com/9299743/29847142-0946b5e2-8ccf-11e7-908b-f1aca43896ac.png)

**Comment by gonetz** [comment]
2D objects are big problem for WS hack. 2D backgrounds have size of original frame; plugin can only stretch it. Obviously, not all 2D objects need to be stretched, For example, HUD does not. Looks like background in this game does not pass the test for objects to stretch.

**Comment by theboy181** [comment]
here is the thing. The background clouds do stretch but the lower part and I assume it's not a texture but a colour set to the render window coverage, does not.  An you test the code to see what I'm talking. About?

**Comment by gonetz** [comment]
I run the game with your codes, the hack works. I don't have save from this level to check the problem with background.

**Comment by theboy181** [comment]
Can be seen on any level.  No save needed. You will also need to set the ws up in the setting. I use 640x240 for testing in a window with the aspect option.

**Comment by gonetz** [comment]
> Can be seen on any level. 

I can not see it on the first level (800x480):
![gliden64_rogue_squadron_003](https://user-images.githubusercontent.com/8983092/30585662-cfb25f0e-9d57-11e7-9c3d-2412c2a0553e.png)

**Comment by theboy181** [comment]
My hack is working?  I’m puzzled. This does not work for me. What version did you test with. Can you test with 854x480? This is closer to the 16:9 ratio

**Comment by Frank-74** [comment]
480 * 16 / 9 = 853.

**Comment by theboy181** [comment]
853.33x480 if we are pointing fingers. What gives Frank?

**Comment by Frank-74** [comment]
@theboy181 Not pointing fingers, just giving the calc to work out exact 16:9 ratio from the height.
But pointing fingers,  480 * 16 / 9 does NOT equal 853.33.  It's exactly 853.
853 / 16 = 53
853 / 9 = 94
No remainder.

**Comment by gonetz** [comment]
854x480
![gliden64_rogue_squadron_005](https://user-images.githubusercontent.com/8983092/30635566-fdd0621c-9e1c-11e7-9c9b-6b3963e23498.png)

Looks like part of the screen is not cleared.

**Comment by gonetz** [comment]
Yes, buffer is not fully cleared. 
@theboy181 here the hacked build with force buffer clear:
https://drive.google.com/file/d/0B0YqMPjGo3B2RG83RXM2dHhmWTg/view?usp=sharing
It works much better with your cheats. Proper fix, if it is possible, will take more time. You may continue your work with that hack.

**Comment by oddMLan** [comment]
Would force depth buffer clear help other games too? Some games that get smears with the Widescreen hack, for instance. Or would you rather improve the heuristics of the Widescreen hack?

**Comment by AmbientMalice** [comment]
>Would force depth buffer clear help other games too?

There are a number of N64 games that require depth buffer clears to render correctly and correctly implementing it would fix a range of subtle issues, but the problem is that on a real N64, depth buffer clearing is done by the CPU. Forcing it clear is a hack, one that Glide64 employed. It's really not an ideal solution.

**Comment by loganmc10** [comment]
> And there's no easy way to detect that the CPU has cleared the depth buffer.

Couldn't something similar to FBInfo help? Have the emulator core watch the depth buffer and notify the graphics plugin if it was cleared?

**Comment by theboy181** [comment]
@gonetz Thank you very much! I feel like there is hope again..
This hack, is a lot slower than the other builds. is this to be expected? With my 60FPS hack on the game is unplayable.

Star Wars - Rogue Squadron (U) (V1.1)
60 FPS Hack

8002E4E8 0000

Note: Needs OC X2  to maintain 60FPS

**Comment by theboy181** [comment]
Also, is this hack game specific? I tested SSB64 and the intro when using WS has backgrounds that don't clear as well.

**Comment by gonetz** [comment]
> but the problem is that on a real N64, depth buffer clearing is done by the CPU.

Nope, it is done by RDP using Fillrect command with cycle mode = Fill.

What the problem with buffer clear and RS widescreen:
* Color and depth buffers cleared by RDP with Fillrect command.
* Fillrect has coordinates of rectangle to fill.
* If fillrect coordinates are (0, 0, buffer_width, buffer_height), that is whole buffer is cleared, plugin uses glClear command for fast clear the whole buffer.
* if fillrect clears not the whole buffer, plugins renders 2D rectangle to buffer. Rectangle fill the area within it with specified color.
* Widescreen hack keeps proportions of 3D objects. That is 3D objects look the same in original and widescreen modes. 2D objects correspond to original screen size. If there is 2D background or rect, which has size of original screen - such rect can be only stretched to fill whole wide screen. From the other side, small 2D objects must not be stretched. The magic is to select good criteria to separate small 2D objects from large ones. Where to send bound - which objects to stretch and which left as is?
* Looks like fillrects, which clear buffers in RS do not pass the test for large 2D objects and not stretched. Thus, only area corresponding to original buffer is cleared.

Hack: always use glClear to clear buffers. This will break many games, but works ok for RS.

This build is slow because it is not optimized debug build. I'll make release build later.

**Comment by theboy181** [comment]
Thanks. That was good news. I’m excited to get back to tweaking the drawdistance and widescreen. I’ll have something more complete soon. Have to see if I can hack the functions instead of per level settings.

**Comment by AmbientMalice** [comment]
>Nope, it is done by RDP using Fillrect command with cycle mode = Fill.

I was thinking of what you said regarding Eiko St Andrews. https://github.com/gonetz/GLideN64/issues/161

>**The game may use CPU to clear depth buffer, because software gfx plugin works correct here. Hardware plugin must use a hack, like "force depth buffer clear".**

https://github.com/gonetz/GLideN64/issues/161

**Comment by theboy181** [comment]
Is anyone even excited about WS hacking?  I find it hard to find others who are active and interested in making them .

**Comment by AmbientMalice** [comment]
>Is anyone even excited about WS hacking?

It's an extremely useful and important feature.

>I find it hard to find others who are active and interested in making them.

They're not exactly trivial to make -- some with framerate hacks.

**Comment by theboy181** [comment]
tbh, if I can learn, a street rat could too.

**Comment by theboy181** [comment]
@gonetz is the speed just because you built as debug? could I get a release build, or was your post about a proper fix part of the problem ?

**Comment by gonetz** [comment]
> is the speed just because you built as debug?

Yes. It is not-optimized build.

>  could I get a release build, or was your post about a proper fix part of the problem ?

Proper fix will not be ready soon. I will do release build with this hack, but I want to complete my current changes first. I will push them to repository, put the hack above and make special release build for you. It will take 1-3 days.

**Comment by theboy181** [comment]
Here is a my WIP code for WS. It should fair better in your testing

Star Wars - Rogue Squadron (U) (V1.1)
Widescreen Hack (16:9)

D012181C 0001
81121820 3FA0
D012181C 0001
81121822 0000
D012181C 0002
81121820 3FCC
D012181C 0002
81121822 CCCD
D012181C 0008
81121820 3FAA
D012181C 0008
81121822 3D71

Note: Needs more testing

**Comment by theboy181** [comment]
Any updates on this? 

I as also wondering if there was something that cuts the 2d elements at the 4:3 ratio in the GFX plugin that could be adjusted too. Could there be a hack that allows 2d elements to be drawn outside this area?

SSB64 has examples where 2d elements get sniped as soon as they exceed the 4:3 are of the screen.

**Comment by gonetz** [comment]
Release build with WS hack:
https://drive.google.com/file/d/0B0YqMPjGo3B2YlNqU0tWRzdaMzg/view?usp=sharing

**Comment by theboy181** [comment]
@gonetz is this build game specific? F-Zero in game is BLACK SCREEN.

**Comment by theboy181** [comment]
Pressing PAUSE in SSB64 = WHITE SCREEN

**Comment by gonetz** [comment]
No, it is not game specific. It may break any game.

**Comment by Frank-74** [comment]
At the beginning of Body Harvest, when the ship is landing, half the sky is black.  This release build is also much slower than the last WIP3 version.

**Comment by gonetz** [comment]
Update:
https://drive.google.com/open?id=0B0YqMPjGo3B2eVRNOEhwdmd1Qmc

**Comment by theboy181** [comment]
@gonetz what is different about this build ?

**Comment by gonetz** [comment]
I just rebased the hack on current master.

**Comment by Nes-player4Life** [comment]
You are the man!

**Comment by theboy181** [comment]
I thought this hack wrecked some games though. Like F-Zero.

**Comment by gonetz** [comment]
Yes, it is just a temporal hack for this particular game.

**Comment by theboy181** [comment]
Did I misunderstand that this hack was now in Master? I cant seem to get it working with WIP3

**Comment by loganmc10** [comment]
It's not in master. When gonetz said he rebased on current master he meant that he updated the build posted here with the latest changes from the master branch

**Comment by gonetz** [comment]
Exactly

**Comment by theboy181** [comment]
Thanks, but that wasn't what lead me to believe that I think.. Just too busy lately I guess and theroy crafting, and hallucinating again, I guess. 

To confirm this is a per-game hack? I will not be able to reproduce this hack with any other game, without hacking the plugin? 

what do I need to change in the source to add other games, like F-Zero?

**Comment by theboy181** [comment]
Update to WS Hack.

New code improves the culling for the enemies and the hangar levels. If you see more issues you want me to fix, please let me know what you find.

Star Wars - Rogue Squadron (U) (V1.1)
Widescreen Hack (16:9)

D012181C 0001
81121820 3FAA
D012181C 0001
81121822 3D71
D012181C 0002
81121820 3FE0
D012181C 0002
81121822 0000
D012181C 0008
81121820 3FAA
D012181C 0008
81121822 3D71
D012181C 0002
81121824 4180
800179F5 0015
8005A94F 00FF

Note: Used with GLiden64 set to "try to adjust games to fit" and "16:9"

**Comment by theboy181** [comment]
@gonetz is there anyway to have this part of the background clear too? you can see how the screen rolling in doesn't get cleared.

![image](https://user-images.githubusercontent.com/9299743/31581952-ea8b8f98-b12b-11e7-830f-b3594fb18008.png)

**Comment by theboy181** [comment]
@gonetz I found an issue with the WS hack during the cut scene at the end of the first level

![image](https://user-images.githubusercontent.com/9299743/31582253-9b07f094-b133-11e7-9046-ae0750a3c4cf.png)
[Star Wars - Rogue Squadron (U) (V1.1).pj.zip](https://github.com/gonetz/GLideN64/files/1385207/Star.Wars.-.Rogue.Squadron.U.V1.1.pj.zip)
Save state, just crash into the enemy to get cut scene going.
