### ISSUE TITLE
Feature idea: Multithreaded Blending Option

### ISSUE THREAD

**Issue by retrobenny** [gonetz/GLideN64#1563]
Since blending for GLideN64 is based on shaders,it could probably be threaded and/or Async supported to workaround terrible blending performance overhead for now until optimizations can hopefully minimalize its heavy impact on performance even on really powerful hardware when using 1080P upscaling.
This would be the same thing that color buffer already does with its Asynchronous mode but would increase performance even more when combined.

I think modern blending at 1080P on my SATV actually performs BETTER than my really decent laptop's GTX 940MX when up-scaling to enhanced 1080P potentially because that Nvidia Tegra X1 GPU may even outrank my laptop's card.
And SATV was designed with power saving in mind and also is much older in the GPU type release at May 1st 2015.
(even though my laptop GPU stats say otherwise with higher values in all categories and GDDR5 video memory)
It would still greatly increase performance across platforms if Async multithreading is added to the blending.

Sorry if I am being really annoying with adding so many issue posts with feature requests lately.
This is just an idea that popped up,since color buffer uses Async to avoid the nasty performance of Sync mode,why can't blending use that as well to mitigate the huge performance impact in general and more importantly from raising the scale size for sharper resolutions?
Blending is a really expensive process in the modern blending because of the issue with zooming in closer to effects and the lag of multiple particles of effects being rendered all at once.
If this idea works like color buffer Async does,it could be just as fast or even faster than legacy blending (legacy=GLn64 blending),meaning it could replace it for better rendering accuracy at excellent performance!

I understand if anyone has to bash at me for mentioning this kind of idea.

**Comment by Frank-74** [comment]
> It would still greatly increase performance across platforms if Async multithreading is added to the blending.

Have you tried fzurita's threaded version?
Example of performance increase in Perfect Dark here: https://github.com/gonetz/GLideN64/pull/1452#issuecomment-309251508
From 58 VI/s to 160 VI/s.

Latest version posted for zilmar spec is here: https://github.com/gonetz/GLideN64/pull/1452#issuecomment-309282558

**Comment by retrobenny** [comment]
Thanks for linking that. Me-> 🤦‍♂️
Is that still not applied to later master versions?
So that was exactly what was already thought of and dealt with,maybe this will alleviate performance problems with Interpreter compared to other GFX plugins.

**Comment by retrobenny** [comment]
Darn! I tested between that and Public Release 2.0 and the public one is a few frames faster for me with the same settings I tried on that version.
Maybe my OpenGL drivers are too good for the benefits of it.
I guess later master builds are slower than the public release.

So I would still need legacy blending access for bleeding edge performance on Interpreter.
(it actually is a lot better than using glN64 since that plugin itself is really broken on new hardware as GLideN64 has so much stuff working excluding the lighting effects on SSB,but Banjo-Tooie runs great on legacy blending with most effects still fully intact)
It would be nice if someone could try to improve legacy blending's compatibility to at least make SSB64 lighting work and other effects be fixed without heavy performance impacts.

**Comment by gonetz** [comment]
Legacy blending uses standard OpenGL blending facility. Blending is a part of so-called "fixed" part of pixel pipeline. It does not depend on shaders and can't be (in general) modified in shaders. Thus, it works fast. Abilities of OpenGL blending are not enough to fully emulate N64 blending. However, in most cases it allows pretty close approximation and thus left for slow mobile GPU.

Normal blending uses shader program to blend output of color combiner with blender inputs, such as fog color or blend color. Result of shader blender is then blended with pixel color in frame buffer using OpenGL blending. Since shader blender program is part of fragment shader, it is already runs as parallel as possible on GPU level. No multi-threading on plugin's level can help it run faster. The only way to make it faster is to simplify the blender program.
