### ISSUE TITLE
Mario Tennis (USA) - missing bottom half of scoreboard

### ISSUE THREAD

**Issue by clobber** [gonetz/GLideN64#1564]
macOS 10.12.6
AMD Radeon R9 M370X
Mupen64Plus @ 138625a
GLideN64 @ bbc7131
rsp-cxd4 @ 664759f

<img width="752" alt="screen shot 2017-09-04 at 4 16 08 pm" src="https://user-images.githubusercontent.com/1303132/30038842-c9f7639a-918e-11e7-87d0-7873703cd965.png">

However, if I enable `copyAuxToRDRAM=1` in GLideN64.custom.ini I can get the bottom half of the scoreboard but now the character shadows are missing:
```
[MarioTennis]
Good_Name=Mario Tennis (U)
frameBufferEmulation\copyAuxToRDRAM=1
```

<img width="752" alt="screen shot 2017-09-04 at 4 16 56 pm" src="https://user-images.githubusercontent.com/1303132/30038876-2f0df9c4-918f-11e7-9958-f004411858f6.png">

Can anyone confirm if this is a Mac or mupen64plus-specific issue and if it's working correctly on Linux or Windows? Paging @loganmc10 since I know he uses Mupen64Plus.

Side note: I've noticed that the settings in the main GLideN64.ini are not being read at all, and possibly getting reset in Config_mupenplus.cpp which in turn is not reading or setting defaults from Config.cpp.

**Comment by loganmc10** [comment]
Same issue in Linux. I know there is some hacky stuff in the code to get the scoreboard working, maybe somewhere along the way it broke.

> Side note: I've noticed that the settings in the main GLideN64.ini are not being read at all, and possibly getting reset in Config_mupenplus.cpp which in turn is not reading or setting defaults from Config.cpp.

GlideN64.ini is only used for Project64. In mupen64plus it reads the defaults from Config.cpp and inserts those into mupen64plus.cfg, it works properly on my machine.

**Comment by clobber** [comment]
>Same issue in Linux.

Thanks for confirming!

>In mupen64plus it reads the defaults from Config.cpp and inserts those into mupen64plus.cfg, it works properly on my machine.

Ah that's right, I forgot all about the cfg file.

**Comment by clobber** [comment]
Thanks!
