### ISSUE TITLE
Conker's Bad Fur Day (USA) - pub walls are green on Intel Iris Pro GPU

### ISSUE THREAD

**Issue by clobber** [gonetz/GLideN64#1565]
macOS 10.12.6
Intel Iris Pro 1536 MB
Mupen64Plus @ 138625a
GLideN64 @ bbc7131
rsp-cxd4 @ 664759f

I have a dual-GPU machine and switched from my discrete AMD GPU over to the integrated Intel and on the Intel the pub walls are green instead of brown:

<img width="789" alt="screen shot 2017-09-04 at 10 23 27 pm" src="https://user-images.githubusercontent.com/1303132/30043942-34e71cf0-91c0-11e7-99f1-523315cf8d57.png">

Can anyone else with an Intel GPU confirm this?

**Comment by olivieryuyu** [comment]
youo gpu does not support opengl 4.4, which is a requirement for GlideN64 I think.

**Comment by AmbientMalice** [comment]
I'm pretty sure GLideN64 only requires GL3.3, with GL4 being used for accurate N64 depth compare.

**Comment by clobber** [comment]
Right, I don't think this is a GL version features issue, otherwise it probably wouldn't look correct on my AMD Radeon R9 M370X in the same machine:

<img width="752" alt="screen shot 2017-09-04 at 10 00 45 pm" src="https://user-images.githubusercontent.com/1303132/30079927-7c12b49a-9247-11e7-9b22-60168fd175b1.png">

More likely it is an Intel bug, either driver or something that can be mitigated with a workaround in GLideN64 - if we can replicate this on other Intel GPU's.

**Comment by loganmc10** [comment]
I have a Linux machine with an Intel GPU that I use all the time and I don't have this issue. It's probably some kind of a driver bug.

**Comment by olivieryuyu** [comment]
Can it be closed pls?

**Comment by clobber** [comment]
>Can it be closed pls?

Um no? Maybe we can get some more confirmation or testing on Intel GPU's (specifically, the same model as mine on other platforms) first or a word from @gonetz

**Comment by loganmc10** [comment]
I ran into a person that had a similar issue when I was working on glupen64 (mupen64plus+GLideN64 for RetroArch)
![687474703a2f2f6b733339323435372e6b696d737566692e636f6d2f6f726265612f73747566662f706963732f7363726f74732f6c6962726574726f2f676c7570656e36342d6d6172696f36342d77696e646f777331302e706e67](https://user-images.githubusercontent.com/848146/30226647-0748bb60-9494-11e7-9e1a-a0bbb153227f.png)

Same thing, the problem existed using integrated (Intel) graphics, but when they switched to their Nvidia card, it went away. This was on Windows 10. Eventually a driver update fixed it for them.

I can't seem to find what first made the issue appear. I seem to remember it had something to do with VBO's. You can try disabling bufferStorage (force it to false):
https://github.com/gonetz/GLideN64/blob/master/src/Graphics/OpenGLContext/opengl_GLInfo.cpp#L58-L59

In the end though, it does seem to be some kind of driver related issue.

**Comment by clobber** [comment]
>You can try disabling bufferStorage (force it to false):
https://github.com/gonetz/GLideN64/blob/master/src/Graphics/OpenGLContext/opengl_GLInfo.cpp#L58-L59

Well `bufferStorage` is already false here because `isGLES2` is false.

`const char * strVersion = reinterpret_cast<const char *>(glGetString(GL_VERSION));` returns `4.1 INTEL-10.25.17` here, so `isGLES2` is always false.

**Comment by loganmc10** [comment]
You mean it evaluates to false on your machine? It will be true on machines that support GL_ARB_buffer_storage

**Comment by clobber** [comment]
Yep it evaluates to false.

**Comment by loganmc10** [comment]
Yeah then I'm not really sure. Do any errors get printed out to gliden64.log? I'm not sure where that goes on a Mac, but it should probably be in the same folder as the "save" and "screenshot" folders if they exist.

**Comment by clobber** [comment]
I found an old log in `~/.local/share/mupen64plus` from a week ago but it doesn't look relevant to this. Just to check, I renamed it, opened the game again and no new log was written. Does the log only write when there are OpenGL errors generated?

**Comment by clobber** [comment]
Hey all and @gonetz, this was fixed for me in one of the recent commits, from the last 10 days or so. Sorry I don't yet know which one though. I will close this out.

**Comment by loganmc10** [comment]
It must have been the changes to the blender, I assume the new method is not only faster, but makes more GPUs happy
