### ISSUE TITLE
Patreon

### ISSUE THREAD

**Issue by gonetz** [gonetz/GLideN64#1569]
Hello,

I setup again my Patreon page:
https://www.patreon.com/Gliden64

If you want to support my work on regular basis - welcome!
Any feedback is welcome too. Any promotion is welcome as well :)

Any sum can help. Hundred 1$ patrons will give me circa 90$ per month (100 - (platform +transfer fees)). Its not much, but with that money I'll be able to upgrade my PC regularly without hurting family budget. 

I added "Early access" reward for 5+ patrons. I'm planing to publish betas with new features on Patreon first. First such beta is already available for download. It fixes F-Zero issues #638 and #639.
Features will be published on GitHub after beta testing start, withing two weeks.
Regular bug fixes will be published on GitHub as usual, with WIP build available at weekend.

**Comment by Papermanzero** [comment]
Crossing fingers that you reach the amount of cemu :-)

**Comment by theboy181** [comment]
I think that expecting Cemu types of yields is obserd.  However, I wish you luck and I can’t wait for public releases.

**Comment by gonetz** [comment]
N64 emulation is not hot topic to get thousands of patrons. Even hundred can't be reached without proper promotion. Promotion in social media is hard thing for such "asocial" man as me.

**Comment by theboy181** [comment]
Cemu has a little thing called BOTW. ;) if you can get GLideN64 working with it I’m sure you will hit 30,000 a month too.

**Comment by weinerschnitzel** [comment]
I do think some of the rewards kind of muddy the waters for progressing a project in an open source fashion. I can't help but feel salty towards CEMU's model and think of it as a greedy breach of crowd funding. I know I don't get to decide, but if my pledge has any influence, please keep as much progress open source (for all.) Happy you opened this again @gonetz and very intrigued with your reverse engineering adventures @oliveiryuyu.

**Comment by gonetz** [comment]
All the progress is and will be open source. Early access means exactly this: early access to things, which soon became public.

**Comment by Papermanzero** [comment]
Maybe you can add further options to patreon to get more supporters or to attract more people. 
Depends on your level of freedom.
e.g. Polls for Features (participation of users concerning feature/issue priorities), dedication on the patreon site.

**Comment by gonetz** [comment]
@Papermanzero I thought about it. I can't promise that feature selected by supporters will be implemented/fixed asap. There is clear algorithm for tasks priorities: regressions, stability, compatibility, speed, bells and whistles. If patrons will vote for "supercubic filtering" feature, I will not be able to take it because I have couple of regressions to fix.

If hundred people will support the project with minimal sum, it will be enough. I believe that GLideN64 has more than hundred active users.

**Comment by Papermanzero** [comment]
Thatˋs what I thought and meant with level of freedom. It is true that you have dependencies and some kind of duties if you offer that option towards patreons. The compromise would be to state clearly that you focus on bugs and stability. But anyway, you patreon is increasing and this is already awesome. :)

**Comment by oddMLan** [comment]
Does this need to be open?
