### ISSUE TITLE
Regression in Cruis'n Exotica

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1572]
https://github.com/gonetz/GLideN64/commit/8985e38bc030bff1adc5dbd4a70cc74691bb085c has completely broken the graphics in Cruis'n Exotica. I guess now we know which game uses that command!

**Comment by olivieryuyu** [comment]
ahha let me see that, interesting!

**Comment by olivieryuyu** [comment]
very clear that it is not the common F3DEX2 ucode. Amazing!

**Comment by olivieryuyu** [comment]
@gonetz 

Yes it is something like gSPDlistCount as 0xD5 in this ucode. A sub displaylist is created and when it is over, it goes back to the main display list. There is stack and when it reach zero, it goes back to the main display list.

**Comment by gonetz** [comment]
@loganmc10 @olivieryuyu Thanks!

**Comment by theboy181** [comment]
You guys are always amazing me.. !! great stuff..

**Comment by olivieryuyu** [comment]
@gonetz 

What is the command in DKKR ucode using gSPDlistCount? Command 0x06?

**Comment by gonetz** [comment]
@olivieryuyu 
F3DDKR_DMA_DL			0x07

**Comment by gonetz** [comment]
Command 0x06 is standard DisplayList command from F3D.

**Comment by gonetz** [comment]
Cruis'n Exotica ucode string:
"RSP Gfx ucode F3DEX       fifo 2.08  Yoshitaka Yasumoto 1999 Nintendo."
Pokemon snap
"RSP Gfx ucode F3DEX.NoN   fifo 2.08H Yoshitaka Yasumoto 1999 Nintendo."
Kirby 64
"RSP Gfx ucode F3DEX       fifo 2.04H Yoshitaka Yasumoto 1998 Nintendo."

Looks like I need to revert my latest changes. The only way to select right behavior for 0xD5 command by ucode string is to check for 'H' in version. Alternatively, Cruis'n Exotica ucode can be added to the list of special ucodes.

**Comment by olivieryuyu** [comment]
OK. 0x07 is a bit different. It looks like it download a RPD command sub display list (a bit like in the turbo3d ucode) and send it the RPD before going back to the main list.

**Comment by gonetz** [comment]
gSPDlistCount implemented as this:
* gSPDlistCount  has two parameters: 'count' and 'address'. 'address' is address of new sub display list. 'count' is number of commands in that sub dlist. Count is second byte of the command in case of F3DDKR_DMA_DL 0x07 and last byte in case of 0xD5 for F3DEX2.
* gSPDlistCount increments display lists stack, and set new stack value to 'address'. 'count'+1 is saved in RSP.count
* New sub-display list is running. RSP.count decremented after each command. When  RSP.count becomes zero, display list stack decreased and execution returned to previous display list.

That is, "it download a RPD command sub display list and send it the RPD before going back to the main list" as you described. gSPDlistCount logic is the same for F3DDKR and for F3DEX2 (in the plugin), only 'count' position in command is different.

**Comment by olivieryuyu** [comment]
Indeed it is the same concept: create sub displaylist, execute the commands of this sub displaylist and go back to the main displaylist :)

I am so surprised that Cruis'n Exotica uses a non standard ucode. I thought that F3DEX2 was really a standardized ucode but at the end it is not true, we discover customs things ever day :)

**Comment by gonetz** [comment]
I guess that Special* commands in gbi.h are reserved for ucode extensions. Strange that ucode string for  Cruis'n Exotica does not have any hint that ucode has an extension.

**Comment by olivieryuyu** [comment]
fixed
