### ISSUE TITLE
Controller bounding for mupen64plus to a specified number

### ISSUE THREAD

**Issue by HansKockrich** [gonetz/GLideN64#1573]
Hi there,

I have a problem regarding the bounding of controllers for mupen64plus.

I have 3 controllers (Thrustmaster dual analog 3.2 / FireStorm Dual Power 2 / Thrustmaster analog gamepad) and I want to bound each controller to a specified number (e.a. the blue controller is always player number 1, the red one always player number 2 and the green one always player number 3 even if I switch the usb ports.

How is that possible?

So far I set up my controllers via "InputAutoCfg.ini" and assigned all the buttons. Only the bounding of the controllers won't work?!

I really tried a lot and even in different forums I couldn't find a solution :-(

Can anyone help me?

PS: Here is my "InputAutoCfg.ini":

[Thrustmaster dual analog 3.2]
plugged = True
plugin = 2
mouse = False
device=1
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = hat(0 Right)
DPad L = hat(0 Left)
DPad D = hat(0 Down)
DPad U = hat(0 Up)
Start = button(3)
Z Trig = button(8)
B Button = button(1)
A Button = button(0)
C Button R = axis(3+)
C Button L = axis(3-)
C Button D = axis(2+)
C Button U = axis(2-)
R Trig = button(6)
L Trig = button(4)
Mempak switch =
Rumblepak switch =
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)

[FireStorm Dual Power 2]
plugged = True
plugin = 2
mouse = False
device=2
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = hat(0 Right)
DPad L = hat(0 Left)
DPad D = hat(0 Down)
DPad U = hat(0 Up)
Start = button(3)
Z Trig = button(8)
B Button = button(1)
A Button = button(0)
C Button R = axis(3+)
C Button L = axis(3-)
C Button D = axis(2+)
C Button U = axis(2-)
R Trig = button(6)
L Trig = button(4)
Mempak switch =
Rumblepak switch =
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)

[Thrustmaster analog gamepad]
plugged = True
plugin = 2
mouse = False
device=3
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
DPad R = hat(0 Right)
DPad L = hat(0 Left)
DPad D = hat(0 Down)
DPad U = hat(0 Up)
Start = button(3)
Z Trig = button(8)
B Button = button(1)
A Button = button(0)
C Button R = axis(3+)
C Button L = axis(3-)
C Button D = axis(2+)
C Button U = axis(2-)
R Trig = button(6)
L Trig = button(4)
Mempak switch =
Rumblepak switch =
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)

**Comment by loganmc10** [comment]
You were right to open the issue at https://github.com/mupen64plus/mupen64plus-input-sdl/issues/49, it doesn't belong here, this can be closed
