### ISSUE TITLE
Zelda MM: coronas and related lighting working LLE only?

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1576]
Testing the game in details for lights, I noticed something interesting.

It seems (I can be wrong though) that coronas are source of lighting.

At the very beginning of the game in West Clock Town, you go at the stairs.

in HLE there is no coronas but in a specific position you have the building in the background suddenly lit. In LLE it does not lit like this.

![hle](https://user-images.githubusercontent.com/8987490/30555501-0130c36e-9ca8-11e7-98ef-575f19ba04f0.jpg)

in LLE you have a coronas and it raises the lighting significantly. There is nothing like this in HLE.

![lle](https://user-images.githubusercontent.com/8987490/30555505-044dcde4-9ca8-11e7-956c-0eb6fd29d2b8.jpg)

It is strange that coronas works only in LLE and the related lighting as well.

**Comment by Jj0YzL5nvJ** [comment]
In Perfect Dark also occurs a "similar" problem. https://github.com/gonetz/GLideN64/issues/1559#issuecomment-330180585
With Hi-Res enables you can see other unexpected effect...

Save state: https://0x0.st/RpV.zip

The most interesting thing is that this only happens in `cxd4-sse2` plugin. But I think GLideN64 is obfuscating LLE in the `hle` plugin. #1561

**Comment by gonetz** [comment]
> in a specific position you have the building in the background suddenly lit.

The same issue, as in #1417. Regression after lighting calculation rewrite. Works ok with PR 1.2

> in LLE you have a coronas and it raises the lighting significantly. There is nothing like this in HLE.

I think coronas with LLE is because of wrong depth buffer copy. Angrylions plugin has no coronas here.

**Comment by olivieryuyu** [comment]
ok let's close then :)
