### ISSUE TITLE
F3D Display Lists are invisible if put in the 16mb RDRAM area.

### ISSUE THREAD

**Issue by MelonSpeedruns** [gonetz/GLideN64#1577]
Hello there! I'm an admin from the SM64O community, and I just wanted to let you know that we're working on adding multiple characters to SM64. To do that, we expended the game to use 16mb of RAM. Unfortunately, it seems that the models that are stored after the usual 8mb of ram are invisible!

I'd also like to report that custom characters for SM64 shows up as totally black characters. Model and animations all seem fine though.

Thanks for your time!

**Comment by theboy181** [comment]
Is this directly related to GLideN64 or the emulator?

**Comment by LegendOfDragoon** [comment]
A lot of plugins don't work well in 16mb, including Angrylion's. Many plugins assume 8MB is the limit.

**Comment by theboy181** [comment]
I did not know that. Thanks.

**Comment by gonetz** [comment]
GLideN64 uses ether 4 or 8 mb memory limit. The limit is easy to rise of you need it, it is just a mask applied to address of object in RDRAM

**Comment by theboy181** [comment]
I think they are suggesting you add it so SM64Online will work with your plugin. :)

**Comment by AmbientMalice** [comment]
Depending on how the romhack was made, there's a decent chance it won't render correctly on GLideN64 and Angrylion's regardless of RDRAM settings. Insert rant about how romhacks should never be written in a way that doesn't work on original hardware.

**Comment by theboy181** [comment]
I think Kaze pointed out already this is not a ROM hack. :)

**Comment by AmbientMalice** [comment]
>I think Kaze pointed out already this is not a ROM hack for real HW. :)

Which means it will inevitably stop working as N64 emulators become more accurate, and the onus will be on the romhack to be rewritten, not the emulator to compromise accuracy. Writing rom-hacks that violate hardware specifications is a really, really bad idea. Something like 16MB RAM is actually complaint with N64 hardware specifications. The methods these rom hacks often use to texture geometry are not.

**Comment by theboy181** [comment]
But fun is ok right?  It’s ok if these hacks don’t work down the road. Truth be told they are not retail games they are hacks. Other truth be realized emulation is a hack. :)

**Comment by AmbientMalice** [comment]
>It’s ok if these hacks don’t work down the road.

No, no it is not. It is in everyone's best interest for rom hacks to be well written and complaint with hardware specifications so that they will work on any emulator however far into the future that is also complaint with hardware specifications. A secondary problem is that poorly written rom hacks lead to crappy, outdated emulators floating around long after they should have been retired. You get a ZSNES situation.

>Truth be told they are not retail games they are hacks.

Which doesn't matter one bit. GoldenEye rom hacks are almost always hardware complaint. Perfect Dark rom hacks are almost always hardware complaint. N64 fan translations are pretty much always hardware complaint. Super Mario 64 rom hacks are an ugly exception, and that is extremely unfortunate.

**Comment by gonetz** [comment]
> I think they are suggesting you add it so SM64Online will work with your plugin. :)

If you wanna have fun - grab sources and do whatever you want. 
I don't want to participate in that.

**Comment by theboy181** [comment]
Why the hate?

**Comment by gonetz** [comment]
> Why the hate?

Hate? You got me wrong. No hate. And nothing personal. When I wrote "you" I did not mean you personally. You == anyone. Sorry, I did not intend to offended you, 

This is open source project, which anyone can adopt for his needs. Anyone may add support for any hardware extensions. I will not participate in that.

**Comment by theboy181** [comment]
Would you accept a PR?

**Comment by MelonSpeedruns** [comment]
Good, I will edit the plugin myself so it supports more than 8mb. I was wondering, what about the black characters issue? It doesn't happen on console and the other graphic plugins.

**Comment by gonetz** [comment]
> Would you accept a PR?

As a separate feature branch - no problems.
As a commit to master - depends on how it is made.

> I was wondering, what about the black characters issue?

IIRC, such issue was already reported. It also was related to some SM64 modification. Such issues have low priority, I did not investigate it yet.

**Comment by Frank-74** [comment]
https://github.com/project64/project64/issues/1031 needs to be implemented in Project64/mupen, so RSP and GFX plugin can easily get the RDRAM size.

**Comment by gonetz** [comment]
Would be great to get it. Current RDRAM size detection is ugly.

**Comment by olivieryuyu** [comment]
shoiuld we close this ticket?

**Comment by gonetz** [comment]
I think it can be closed. If https://github.com/project64/project64/issues/1031 will be implemented, it also will fix this issue.

**Comment by oddMLan** [comment]
![imagen](https://user-images.githubusercontent.com/7278372/41820299-820019e2-7784-11e8-87b7-a86a95b80e94.png)
I changed RDRAMsize in RSP.cpp to 0xFFFFFF (16MB) and it still doesn't show anything. Any other places where it needs to be changed?

**Comment by LegendOfDragoon** [comment]
Didn't zilmar already add the rdram size function? could just add the function and use that.
