### ISSUE TITLE
Perfect Dark regression: Wrong particles

### ISSUE THREAD

**Issue by Tasosgemah** [gonetz/GLideN64#1578]
The latest version of the plugin (ef6f470) has this issue in Perfect Dark

https://s26.postimg.org/9rueo0ywp/Untitled.png

So instead of red sparkles you get these triangles. They also appear when you shoot enemies. This issue doesn't exist in the previous WIP version or the one currently bundled with m64p.

**Comment by Frank-74** [comment]
Same here.  Doesn't happen with the recent builds in this thread : https://github.com/gonetz/GLideN64/issues/1555
I don't get red sparkles though, they're whitish.

**Comment by AmbientMalice** [comment]
There's a decent chance it'll be fixed by this. https://github.com/gonetz/GLideN64/pull/1566

**Comment by Tasosgemah** [comment]
Seems to be correct with the "optimized blend" build.

**Comment by AmbientMalice** [comment]
This can be closed, right?
