### ISSUE TITLE
Perfect Dark SW Depth Buffer Problem.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#1580]
I'm aware the SW depth buffer has a range of issues, but in PD lens flares/coronas appear through surfaces when they shouldn't.

SW:
![perfect_dark-010](https://user-images.githubusercontent.com/10704701/30648120-a312927a-9e60-11e7-8807-c19f6f83af0b.png)

HW: (Angrylion's behaves this way, too.)
![perfect_dark-011](https://user-images.githubusercontent.com/10704701/30648121-a32a3858-9e60-11e7-94ed-b120344d9b1c.png)

**Comment by olivieryuyu** [comment]
do i have a savestate?

**Comment by AmbientMalice** [comment]
Here you go. http://s000.tinyupload.com/?file_id=10718279234758737540

**Comment by olivieryuyu** [comment]
indeed in software it does not work but from VRAM it does.

**Comment by gonetz** [comment]
The bug was hard to find. Fixed.

**Comment by AmbientMalice** [comment]
Thanks a lot Gonetz. I should check whether this has fixed any other games that acted odd with software depth buffer. (I'm pretty sure there were others.)

**Comment by Frank-74** [comment]
Tested b6c6ac0.
Getting black at certain distances/angles.  Also white line above lights.
![gliden64_perfect_dark_000](https://user-images.githubusercontent.com/11056843/31249456-4829a87a-aa0f-11e7-885c-33e3c2b0659f.jpg)

PJ64 savestate for Perfect Dark (U) v1.1, just walk forward slowly, and problem will appear.  I put the zip quick save and eep in this zip.  Saved on Infiltration level, near the start.
https://www.dropbox.com/s/sa9vf3am555do55/PJ64_PerfectDark_Saves.zip?dl=1

**Comment by Frank-74** [comment]
Also, collision detection is broken in Body Harvest with this build.

**Comment by olivieryuyu** [comment]
@AmbientMalice 

Can you reopen please this ticket?

Interesting to know that this commit breaks Body Harvest!.

**Comment by Frank-74** [comment]
It's the if (orbits == 0) part that breaks Body Harvest collisions.

**Comment by gonetz** [comment]
That's odd. Please give me saves to test Body Harvest quickly.

**Comment by Frank-74** [comment]
Just start a new game with Body Harvest and run up to the houses, you go through walls.  Enter the house next to the draw bridge, pull the lever inside to lower the bridge then try crossing the bridge.

Loading save state is a problem as it loads with the error.  You can save when collisions are working, start a game with broken plugin, and collisions will work after loading save state.  Or save broken, load save with fixed plugin and collisions won't work.

**Comment by gonetz** [comment]
:((( In that case fix will take eternity.
Is that problem with saves on Project64 only, or other emulators (mupen64plus?) work the same?

**Comment by Frank-74** [comment]
The game sets the collision for the area your in, when you enter an area.  So it's same with all emulators.
It only takes few seconds to run up to houses at start of first level.  You walk through walls and fall through stairs.

**Comment by gonetz** [comment]
> Getting black at certain distances/angles. Also white line above lights.

b6c6ac0 can cause these problem. And it does not. I just checked your save, no such problems. Something is wrong with your build.

**Comment by gonetz** [comment]
> The game sets the collision for the area your in, when you enter an area. So it's same with all emulators.
It only takes few seconds to run up to houses at start of first level. You walk through walls and fall through stairs.

Without save state I can't compare depth buffers from the same point to find the difference. That makes already complicated depth render debugging much harder.

**Comment by gonetz** [comment]
@Frank-74 Does Body Harvest collision detection work incorrect with copy depth buffer from VRAM?

**Comment by Frank-74** [comment]
Body Harvest collision never worked with copy depth buffer from VRAM.
It started working with software depth buffer after the VI Refactor.

I just reset default settings in GLideN64, and now my Perfect Dark save is working ok too.  Weird.

**Comment by gonetz** [comment]
>Body Harvest collision never worked with copy depth buffer from VRAM.
It started working with software depth buffer after the VI Refactor.

Hmm. VRAM depth buffer is more correct than software one. This issue with PD proves it. I corrected software render to make it work the same way as hardware render works. Previously some polygons just not rendered in software, thus depth buffer did not modified properly and coronas becomes visible through surface. May be the same situation is with Body Harvest : some polygons were not rendered, but the result from this bug was positive. Now result is the same as with hardware rendering. This leads to hypothesis that something is incorrect with depth compare or depth write on hardware side.

**Comment by Frank-74** [comment]
There's more details on the problem, with depth buffer not being accurate enough for Body Harvest here:
https://github.com/project64/project64/issues/428#issuecomment-276536352

**Comment by gonetz** [comment]
Original issue is fixed, so I close this ticket.
#550 reopened.

**Comment by olivieryuyu** [comment]
commit fixes also #1308
