### ISSUE TITLE
 pokemon stadium 2 gliden64 start screen bug

### ISSUE THREAD

**Issue by squalorx** [gonetz/GLideN64#1582]
Question about project 64 with gliden64 (both of them on latest version), when i play pokemon stadium 2 the screen that ask me to press start and the next screen (where you can choose battle, event and white city) are broken, the game works fine, but that 2 screen are broken. The funny thing is, i already played that game before on the same emulator and with the same plugin without this bug,but it was a long time ago(probably at the end of 2016). If i go in and out of full screen the image gets back to normal. This bug doesn't make the game unplayable but it bothers me everytime i start the game. 
i'm using the Ntsc-U version, the same happens if i use the japanese version. If i use the European version this bug won't happen, but sometime the emulator will go black screen close after the intro if i use the europen version ( something like 60% of the times that i try to open it).

PS: sorry for any english mistake, english is not my first language.

screenshots of the problem
https://i.imgur.com/fAC4lmr.png
https://i.imgur.com/g1oXThz.png
https://imgur.com/4x4cjbt

spec: gtx 630 1gb
fx 6300
8 gb memory
 i'm using windows 10 with the creators update

**Comment by loganmc10** [comment]
You need GLideN64.custom.ini

https://github.com/gonetz/GLideN64/blob/master/ini/GLideN64.custom.ini

I think for Project64 you put that in the same folder as the DLL file

**Comment by squalorx** [comment]
thanks for the info, i will try it when i get home

**Comment by squalorx** [comment]
thanks mate, the custom ini file fixed it.
