### ISSUE TITLE
Custom Robo V2 Soft Lock (Mupen64plus only)

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#1583]
The game soft locks with a black screen and music playing when you start a new game. (Just keep pressing A). Seems to work fine with Angrylion's.

**Comment by gonetz** [comment]
How about other plugins?

**Comment by AmbientMalice** [comment]
Not sure, because this seems to be a mupen64plus-only problem and the build I have only has GLideN64 and Angrylion's. (I'll rename the issue to match.)

**Comment by Papermanzero** [comment]
Here is the current mupen64plus build with all plugins
https://bitbucket.org/ecsv/mupen64plus-mxe-daily/downloads/

**Comment by AmbientMalice** [comment]
Closing this. I think the issue is on m64p's side, and even Angrylion's seems to freeze now.
