### ISSUE TITLE
Star Wars: Rogue Squadron HLE glitches.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#1584]
Incorrect section on Factor 5 logo.

![rogue_squadron-000](https://user-images.githubusercontent.com/10704701/30696904-8d75bfd0-9f20-11e7-813e-b71c0bf30c79.png)
![rogue_squadron-001](https://user-images.githubusercontent.com/10704701/30696903-8cb6a550-9f20-11e7-807a-4f09ecee41c3.png)

Smeared floor texture in briefing room:
![rogue_squadron-004](https://user-images.githubusercontent.com/10704701/30696956-bef6fa2e-9f20-11e7-901c-23ed890a5642.png)
![rogue_squadron-003](https://user-images.githubusercontent.com/10704701/30696957-bef866ac-9f20-11e7-9688-3043dfee47d7.png)

**Comment by olivieryuyu** [comment]
hmm looks like a regression

**Comment by gonetz** [comment]
regression. commit b4400c1d242
