### ISSUE TITLE
Foresaken 64: wrong intro (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1585]
It is an old regression: I had to go back public release 1.2 to get it worked correctly.

the fading from one screen to another does not work correctly anymore: it goes black suddently and even some 3d graphics disappear. You just need to run the intro and compared version 1.2 and current version, it is pretty much obvious then.

![gliden64_forsaken_007](https://user-images.githubusercontent.com/8987490/30709667-4c93045e-9f03-11e7-8989-6876e0244ff8.jpg)

![gliden64_forsaken_016](https://user-images.githubusercontent.com/8987490/30709666-4c90e8e0-9f03-11e7-9a27-9ffd6f26e4a9.jpg)

**Comment by gonetz** [comment]
Fixed

**Comment by olivieryuyu** [comment]
Fixed
