### ISSUE TITLE
VS2015 Compatibility

### ISSUE THREAD

**Issue by standard-two-simplex** [gonetz/GLideN64#1586]
In order to compile with VS2015, one must compile ``libpng``, ``zlib`` and ``freetype`` with VS2015 and replace the files.

It would be nice to add them to master to make pulling and compiling easier.

_________________________________________________

When trying to compile with vs2105, I get errors (unresolved externals symbol).

I need to link ``legacy_stdio_definitions.lib`` and manually  redefine `` extern "C" { FILE __iob_func[3] = { *stdin,*stdout,*stderr };}`` in some file as explained [here](https://stackoverflow.com/questions/30412951/unresolved-external-symbol-imp-fprintf-and-imp-iob-func-sdl2).

Could those changes be added so it becomes easy to fetch from upstream and compile?
 
Edit: the errors were due to libraries ``libpng`` and ``zlib`` being compiled with an older version and shipped with the code. I edit the first post to describe the real issue.

**Comment by fzurita** [comment]
I think you only need to do all that if you don't recompile all the library dependencies with VS2015 as well. The only way I was able to get this running with VS2015 was to grab all the library dependencies sources, compile with VS2015 and make the GLideN64 VS project link against those new versions.

**Comment by gonetz** [comment]
I have all msvs2015 changes in my private branch. I still can't find time to make proper fix and switch to MSVS 2015 in release builds. It will be done when I fix more urgent problems.

**Comment by standard-two-simplex** [comment]
@fzurita Which dependencies did you compile? I compiled everything not in this repository. I'm only missing ``__iob_func`` which I think are part of SDL. Did you compile any of that?

>I have all msvs2015 changes in my private branch. I still can't find time to make proper fix and switch to MSVS 2015 in release builds. It will be done when I fix more urgent problems.
@gonetz Ok, no problem. I leave the ticket open as a reminder and as reference for anyone coming with a similar problem.

**Comment by fzurita** [comment]
libz and libpng

**Comment by standard-two-simplex** [comment]
I just compiled those two but I can't see them anywhere in project dependencies. Am I supposed to add them as extra dependencies? Weird.

**Comment by fzurita** [comment]
Yeah, GLideNHQ needs those. I'm not sure if they're is a way to omit them if you don't want high resolution texture support.

**Comment by loganmc10** [comment]
Cmake has the NOHQ option, which disables GLideNHQ. All it does it omit compiling GLideNHQ and it compiles in TxFilterStub.cpp in it's place.

**Comment by standard-two-simplex** [comment]
Oh ok. GlideNHQ is compiling with the shipped libpng and zlib.
The one giving me problems is GlideN64.  Right now I got this,
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\..\src\uCodes\F3D.cpp)	GLideN64	F:\Programming\GLideN64\src\GLideN64.h	7	
```
Any ideas? This hasn't happened to me with earlier versions.

**Comment by fzurita** [comment]
It looks like a variable is missing a type qualifier. That could be as simple as adding "int" to the left side of a variable. That does seem like an actual bug in the code.

**Comment by standard-two-simplex** [comment]
I tested a little bit and I think I did that myself when adding
`` extern "C" { FILE __iob_func[3] = { *stdin,*stdout,*stderr };} ``
without that I get
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol ___iob_func	GLideN64	F:\Programming\GLideN64\projects\msvc12\libGLideNHQ.lib(pngerror.obj)	1	
```
which I don't know how else to solve. Adding that piece used to get around in the past.

**Comment by fzurita** [comment]
Did you rebuild FreeType using VS2015?

**Comment by standard-two-simplex** [comment]
No. Will try that.

**Comment by standard-two-simplex** [comment]
Can't get it to work now. I will continue tomorrow.

**Comment by fzurita** [comment]
@standard-two-simplex Are you following this guide by any chance? That should make it easy:

https://github.com/gonetz/GLideN64/issues/742

**Comment by standard-two-simplex** [comment]
@fzurita thanks, I had only checked the guide in wiki.
I managed it. I deleted all dependencies, installed them again compiling with vs2015 and it worked. The culprit was indeed `` libpng`` or ``zlib``.

**Comment by gonetz** [comment]
MSVS 2015 support:
1479354d9092e73803fcf

Updated wiki:
https://github.com/gonetz/GLideN64/wiki/Build-From-Source-(Windows)

**Comment by standard-two-simplex** [comment]
Thanks! I'll check it first time tomorrow.

**Comment by gonetz** [comment]
I updated Build From Source (Windows) wiki once again:
https://github.com/gonetz/GLideN64/wiki/Build-From-Source-(Windows)
You may download my ready for you static QT build. Everything else is simple.

I also found that pnglib in new QT does not contradict with pnglib in GLideNHQ, at least in VS 2015 build. Thus, I switched to png screen shots format for zilmar spec build.

**Comment by gonetz** [comment]
I updated Build From Source (Windows) wiki once again:
https://github.com/gonetz/GLideN64/wiki/Build-From-Source-(Windows)
Added link for QT static build for Visual Studio 2013.
Png screen shots work with VS 2013 too.

**Comment by standard-two-simplex** [comment]
Working fine! One question: if I compile without changing the output directory I get an error and no file can be found in the directory I set as Mupen64PluginsDir. Any ideas why?
I managed to compile just by pulling and changing that.

**Comment by gonetz** [comment]
Build failed if directory set as Mupen64PluginsDir does not exist. I fixed that in latest commit.

**Comment by Frank-74** [comment]
On extracting the msvc2015 static .7z archive, windows defender said malware detected and removed something.   This is the report:

Category: Trojan
Description: This program is dangerous and executes commands from an attacker.
Recommended action: Remove this software immediately.
Items: 
file:C:\QT\qt-5_7_1-x86-msvc2015-static\bin\qmllint.exe

Can I do without that file?

**Comment by gonetz** [comment]
I think yes. I suppose it is internalization related.

**Comment by gonetz** [comment]
@Frank-74 please send this file to https://www.virustotal.com I wonder, how much systems will detect Trojan in it.

**Comment by Frank-74** [comment]
It's ok.  It built with no warnings in build about it.  And it's working fine in Project64.
The only problem with my build is tooltips take 1 minute to disappear.

**Comment by standard-two-simplex** [comment]
I copy pasted an existing directory, and I think the fix commit was merged. Can it be there were some spaces in the directory name? I'll do some extra tests after work.

**Comment by gonetz** [comment]
> Can it be there were some spaces in the directory name?

Space should not be a problem. I set N64PluginsDir to 
`C:\Users\Me\N64\Project64 2.3\Plugin\GFX\`
and it works for me. Note, there is space in `Project64 2.3`

**Comment by standard-two-simplex** [comment]
It's working now with no change whatsoever. Something must've prevented my pc from creating the file yesterday.

I close the issue, since using VS2015 is straightforward now.
