### ISSUE TITLE
Beetle Adventure Racing! snow is grey! (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1587]
blender i guess

![sans titre](https://user-images.githubusercontent.com/8987490/30719673-a1457d26-9f24-11e7-850c-a38b08a2278c.jpg)

**Comment by loganmc10** [comment]
Are you sure this is a regression? If it is it's really old, I tested all the way back to 5e51b386f179bf29bcfc82c5670c5058deb30ace and the snow is still grey there

**Comment by gonetz** [comment]
Was it white with any Public Release?

**Comment by olivieryuyu** [comment]
fixed
