### ISSUE TITLE
quake2: glitches and depth issue (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1589]
Weird glitches on the body and other elements at the start of games which affects depth as well.

![sans titre](https://user-images.githubusercontent.com/8987490/30731042-550d752a-9f6b-11e7-8482-53cf072bd303.jpg)

**Comment by gonetz** [comment]
So many regressions... looks like I opened gates to hell :(

**Comment by AmbientMalice** [comment]
Could you explain the error a bit more? It looks pretty much the same in Angrylion's and GLideN64 to me.

![quake_ii-002](https://user-images.githubusercontent.com/10704701/30733941-7c851512-9fbc-11e7-88d5-a3581de973fa.png)
![quake_ii-003](https://user-images.githubusercontent.com/10704701/30733942-7c8781d0-9fbc-11e7-9d06-7b252910fc19.png)

Maybe you were running game in LLE mode?

![quake_ii-004](https://user-images.githubusercontent.com/10704701/30734047-edcb4dd6-9fbc-11e7-8f77-9830af0ab5e5.png)

**Comment by gonetz** [comment]
I see no problems here. Screen shots with Angrylion's from the same point:

![nq2e0000](https://user-images.githubusercontent.com/8983092/30793566-184da1a8-a1ed-11e7-9133-847cf8e38afd.png)

**Comment by olivieryuyu** [comment]
i did not mean this. The corpse and other elements of the game has wrong depth and flickers.

See new screenshot

![gliden64_quake_ii_008](https://user-images.githubusercontent.com/8987490/30821995-a424b1fa-a227-11e7-94bc-4880c1dfc5b9.jpg)

**Comment by gonetz** [comment]
> The corpse and other elements of the game has wrong depth and flickers.

They look ok for me.

> See new screenshot

I see objects poke through on your screen shot. Does not happen for me either. May be run it in LLE mode? Please try to retest with default settings.

**Comment by olivieryuyu** [comment]
I have just tested on my laptop with an Intel integrated graphic card with default configuration. Same issue.

It is only fixed by changing the framebuffer swap on from VI to VI origin change.

**Comment by olivieryuyu** [comment]
It seems emulator related. Closed!
