### ISSUE TITLE
007 golden eye: wrong intro

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#159]
![885a0602-6993-11e4-8286-0a0cb57498e9](https://cloud.githubusercontent.com/assets/8987490/5328001/d4e384be-7d69-11e4-87f8-2e715b5f6633.jpg)

**Comment by Mushman** [comment]
The horizontal lines are gone, but the right of the screen is still incorrect. It now repeats the gun barrel texture.

**Comment by AmbientMalice** [comment]
No longer flickers on right hand side, but gun barrel texture wraps around to right hand side, which is incorrect.

![goldeneye-001](https://cloud.githubusercontent.com/assets/10704701/13836230/dd2a16fa-ec4a-11e5-91d3-ca1d364c4bea.png)

**Comment by Jj0YzL5nvJ** [comment]
Fixed by 7aeb1018ea19c29389fcc2839033d136453893ec

**Comment by olivieryuyu** [comment]
Oh Nice

**Comment by theboy181** [comment]
Sweet!!  Now MP fix?
