### ISSUE TITLE
Wild Waters: graphics are messed up (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1591]
![sans titre](https://user-images.githubusercontent.com/8987490/30775354-06e0b164-a092-11e7-8350-202ae04ec35b.jpg)

Used to work with public release 2.0 correctly

**Comment by gonetz** [comment]
Looks ok for me:

![gliden64__000](https://user-images.githubusercontent.com/8983092/31008015-c8bd94b6-a52c-11e7-9e30-6b84b3b5c7e8.jpg)

**Comment by olivieryuyu** [comment]
hmm let me check again

**Comment by olivieryuyu** [comment]
Zero idea how i got this bug. Ok it seems fine so closed.
