### ISSUE TITLE
request: webhook

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1592]
Can you please add the webhook for Yappybot (discord)

This will allow the Discord community get update information from your project

Create webhook to https://www.yappybots.tk/

More information here.
https://github.com/YappyBots/YappyGithub

**Comment by gonetz** [comment]
ok

**Comment by gonetz** [comment]
test

**Comment by gonetz** [comment]
test 2

**Comment by theboy181** [comment]
Thanks!!
