### ISSUE TITLE
Blast Corps Stage select lines are wrong

### ISSUE THREAD

**Issue by Tasosgemah** [gonetz/GLideN64#1595]
This is how the lines look in GlideN64:

https://s26.postimg.org/pbmzvii0p/Untitled.png

This is how they should look:

http://www.deathofanalog.org/n64thstreet/wp-content/uploads/2013/01/cooter.jpg

Just the lines are wrong. The yellow circles in the correct picture are just platinum medals in the GlideN64 picture.

**Comment by olivieryuyu** [comment]
Again grey color instead of the right one... something is in the air!

**Comment by gonetz** [comment]
I need a savestate to check it

**Comment by Tasosgemah** [comment]
Here's my save state at the map screen

http://www56.zippyshare.com/v/CC4Ypq9N/file.html

**Comment by gonetz** [comment]
Fixed

**Comment by olivieryuyu** [comment]
@Tasosgemah 

please close if fixed
