### ISSUE TITLE
World Driver Championship shadows are.....grey!

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1596]
The race starts off like this:

![world_driver_champ-001](https://user-images.githubusercontent.com/848146/30839663-9b02633e-a230-11e7-83b4-4e5698123c49.png)

But after about 10 seconds the shadows look like this:

![world_driver_champ-002](https://user-images.githubusercontent.com/848146/30839677-a7b9b23a-a230-11e7-8bbb-0e2de629f283.png)

Fairly recent regression I believe

**Comment by gonetz** [comment]
Could you find the commit, which causes it?

**Comment by loganmc10** [comment]
bad commit: d4dbe7c094509df0f843b94d898f69a57f13d6d7

**Comment by gonetz** [comment]
Thanks!

**Comment by gonetz** [comment]
Nope, I tested with parent commit of d4dbe7c. The bug is still there.

**Comment by gonetz** [comment]
Fixed
