### ISSUE TITLE
Tetrisphere lines between textures

### ISSUE THREAD

**Issue by Frank-74** [gonetz/GLideN64#1598]
![gliden64_tetrisphere_001](https://user-images.githubusercontent.com/11056843/30880784-9e2c7d6c-a2fb-11e7-953b-c1389d97ad6c.jpg)

Setting fix black lines between adjacent fixes most of it, but you still get this:
![gliden64_tetrisphere_000](https://user-images.githubusercontent.com/11056843/30880872-c4cc0398-a2fb-11e7-8031-667515fc7885.jpg)

Needs to be set to Always.  Should these fixes be added to the custom ini?

[TETRISPHERE]
Good Name=Tetrisphere (U)
generalEmulation\correctTexrectCoords=2

**Comment by gonetz** [comment]
Done.
