### ISSUE TITLE
Mario Tennis (USA) - missing character selection icons (regression)

### ISSUE THREAD

**Issue by clobber** [gonetz/GLideN64#1599]
macOS 10.13
AMD Radeon R9 M370X

<img width="693" alt="screen shot 2017-09-26 at 2 21 51 pm" src="https://user-images.githubusercontent.com/1303132/30880942-b2a2df34-a2c9-11e7-8b99-2658f782e722.png">

Appears to be broken from commit https://github.com/gonetz/GLideN64/commit/81cc0854dce4e3914dbc71b0067cf9d7549c936e

**Comment by oddMLan** [comment]
I'd be surprised if @gonetz isn't pulling his hair out right now...

**Comment by DonelBueno** [comment]
This also happens on Windows + Nvidia.

**Comment by mudlord** [comment]
@oddMLan Thats why I refuse to work on this codebase to be bloody honest. That and dealing with other people's bullshit...

**Comment by AmbientMalice** [comment]
There really needs to be more comprehensive regression testing before new code is committed, but testing every N64 game in every region is a lot of work.

**Comment by clobber** [comment]
>but testing every N64 game in every region is a lot of work.

@AmbientMalice That's where a testing suite made of save states at critical points in known problematic games might come in handy.

**Comment by gonetz** [comment]
@clobber It will not save us from regressions. For example, this place never was a critical point.

**Comment by gonetz** [comment]
Each new feature potentially can cause regressions.

**Comment by clobber** [comment]
@gonetz I'm interpreting that as "regression testing won't save us from regressions" which I don't think is what you mean. What I'm suggesting is take 50 of the top N64 games, maybe ones known for certain use of features and problem issues, and make save states in 3-4 places throughout the games. From visual inspection alone, that should be enough to check for at least *some* regressions. I'm not suggesting you do all this on your own, but rather in a way that everybody has access to in order to lessen the burden of regression testing.

**Comment by loganmc10** [comment]
I think one of the guys from the mupen64plus team is working on something like this. He's got a bunch of save states and a python script that takes a bunch of screenshots and compares them against good ones or something. I haven't looked into it too much, but if he gets it up and running I'll make sure to try and integrate it with GLideN64

**Comment by gonetz** [comment]
I agree, lack of automatic, semi-automatic and even regular testing has bad impact on project quality.
I support the idea to make first step in that direction and create a test base with save states and reference screen shots, so every one can load that base and run tests on its hardware. Can you help with it?

I suggest to create new project here on GitHub, e.g. GLideN64-Testig. Or even N64GraphicsTesting, because that base can be used not only for GLideN64 testing.

@loganmc10 You just took my idea while I wrote it :)

**Comment by gonetz** [comment]
There are plenty of save states in GLideN64 tickets. They all can be added to such base.

**Comment by oddMLan** [comment]
Dolphin has a similar system, but instead of savestates they use FIFO logs (1 frame snapshots). And it has an automated system that scans for visual differences (even the most minor) from these, whenever a new commit is made. The system then flags those games that displayed differently.

https://fifoci.dolphin-emu.org/about/

If GLideN64 ever gets a DirectX backend, a system like this is an absolute must.

**Comment by gonetz** [comment]
> If GLideN64 ever gets a DirectX backend

Hardly. Only if somebody will do it as an DirectX exercise. 

> system like this is an absolute must

I would start from something simple. Anyway, I need help with it.

**Comment by oddMLan** [comment]
Gathering savestates from parts that have broken before or are prone to break would be a good start, someone would get a good idea from past tickets. At least we know Project64's savestates are compatible with Mupen64plus with no conversion needed; dunno if the same thing applies the other way around though.

Would be eager to help with that but I can't atm :(
. When I have access to my computer again and some time I would definitely help with that

**Comment by loganmc10** [comment]
> At least we know Project64's savestates are compatible with Mupen64plus with no conversion needed

Sometimes, if you're lucky, I wouldn't count on it

**Comment by gonetz** [comment]
@loganmc10 
>if he gets it up and running I'll make sure to try and integrate it with GLideN64

Could you take this task? Integrate existing base or create a new one. If such base will exist, I'll update it with saves from my collection.
Also, it is better to use mupen64plus saves. mupen64plus will be easier to use for automatic testing due to its command line interface.

**Comment by loganmc10** [comment]
Yeah I'll look into it, I'll definitely be using mupen64plus

**Comment by gonetz** [comment]
Thanks in advance

**Comment by clobber** [comment]
Thanks - it's fixed.
