### ISSUE TITLE
request: MK64 full speed jumbotron

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1602]
any chance you could add the ability to have the frame buffer do more that 4fps on the jumbotrons in Mario Kart?

I think there are a couple of games that would also benefit from hacks like these.

**Comment by olivieryuyu** [comment]
4fps? Do u have a savestate?

**Comment by theboy181** [comment]
I'm exaggerating about the FPS, but you can see that the Giant TV display on Luigi's Racway, and Warios Stadium updated 1/4th of the games0 30fps.

You shouldn't need a save state, as it the first race. :)

**Comment by olivieryuyu** [comment]
I think it is how it looks like on a real N64.

**Comment by theboy181** [comment]
I'm exaggerating about the FPS, but you can see that the Giant TV display on Luigi's Raceway, and Warios Stadium updated 1/4th of the games 30fps.

Yes this is a HACK. kinda like High Resolution, Widescreen, and HLE. :)

You shouldn't need a save state, as it the first race. :)

@LegendOfDragoon  has spent some time hacking a ROM to achieve this, and documenting the ASM.

https://gist.github.com/LegendOfDragoon/b9ba58841fbfd224264c8815de912721

Jabo also created a HW FB hack for this in his plugin. Closed Source though, so it dies with his ability to care about emulation anymore.

**Comment by gonetz** [comment]
> any chance you could add the ability to have the frame buffer do more that 4fps on the jumbotrons in Mario Kart?

No. The game is programmed that way. Frame buffer already read at 30 fps, but it does not change the game. The only way to improve it is a hack as in Jabo's plugin.

> I think there are a couple of games that would also benefit from hacks like these.

No. This hack must be implemented individually for each game.

Sorry, no chance.
