### ISSUE TITLE
Perfect Dark Multiplayer Split screen N64-Style Depth Issue

### ISSUE THREAD

**Issue by Blue-Ike** [gonetz/GLideN64#1609]
I was running Perfect Dark on Project64 emulator checking out any issues with the multiplayer and found this problem.
 In GlideN64 Public Release 2.0 when you check the option in frame buffer tab "Enable N64-Style Depth Compare (Experimental)" it seems to correct an issue with the bottom half split screen.
![gliden64_perfect_dark_001](https://user-images.githubusercontent.com/16857573/31044693-087f045c-a5a2-11e7-8e5e-f34ed73ebdc7.png)

Now when that option is unchecked in both GlideN64 Public Release 2.0 and the latest WIP build released a few days ago, the bottom half screen looks like this.
![gliden64_perfect_dark_002](https://user-images.githubusercontent.com/16857573/31044727-beeb164a-a5a2-11e7-8400-ed798540480d.png)

Finally, now when I check  "Enable N64-Style Depth Compare (Experimental)" in the new latest WIP Build release both top and bottom screens are missing the physical character models and as you walk you can see through walls exposing whats further up on the level map.
![gliden64_perfect_dark_003](https://user-images.githubusercontent.com/16857573/31044758-41691d60-a5a3-11e7-916b-83f01398c5c0.png)

I created a save state.
[Perfect Dark (U) (V1.1).pj.zip](https://github.com/gonetz/GLideN64/files/1346321/Perfect.Dark.U.V1.1.pj.zip)
Here's a download link in case.
[http://www76.zippyshare.com/v/LvoCk0w3/file.html](url)

**Comment by loganmc10** [comment]
This is probably related to: https://github.com/gonetz/GLideN64/issues/1173

**Comment by Blue-Ike** [comment]
Just tested with the current master that was released 14 hrs ago and the problem still persists.

**Comment by Blue-Ike** [comment]
I play GoldenEye X too. I know what you're talking about but that option only works for two player split screen. If players want to play horizontal or play 3 & 4 player games than this issue continues to occur. GoldenEye has the same issue. Hoping this issue can be resolved for the next public release.

**Comment by Blue-Ike** [comment]
I just tested it out and you're right. I previously thought that option only worked for 2 player split screen games but when I had 3 players on and switched from Horizontal to Vertical I noticed the menu window's aspect ratio changed. It wasn't as wide as it was on Horizontal. The Vertical option does work for multiplayer with no flickering. 

I even tested out my Slayer Fly-by-wire/Seeker (GE-X) theory. out and it fixes the issue #836 I posted of it. Now the 3rd amd 4tj players screens in the bottom can use the Slayer/Skker in PD/GE-X.

However, the horizontal "split screen" option needs to be fixed in Perfect Dark and in Goldeneye. And yes, that video option is NOT available in Goldeneye. So this issue with the Horizontal Split screen DEFINITELY needs to be fixed.

**Comment by Blue-Ike** [comment]
I just tested it out and you're right. I previously thought that option only worked for 2 player split screen games but when I had 3 players on and switched from Horizontal to Vertical I noticed the menu window's aspect ratio changed. It wasn't as wide as it was on Horizontal. The Vertical option does work for multiplayer with no flickering at all. 

I even tested out my Slayer Fly-by-wire/Seeker Guided Missile (GE-X) theory. out and it fixes the issue #836 I posted of it. Now the 3rd amd 4th players screens in the bottom can use the Slayer/Seeker's secondary functions in PD/GE-X.![gliden64_goldeneye_x_002](https://user-images.githubusercontent.com/16857573/36405467-d0fcd724-15be-11e8-92e8-977c6f6afcf1.png)

Now when you use Horizontal and play 2 player game and use the Slayer/Seeker's secondary function it still has the old issue.
![gliden64_goldeneye_x_006](https://user-images.githubusercontent.com/16857573/36405717-113f0414-15c0-11e8-85ac-7ffd2a807c00.png)

Here is a save state of the two player game with the horizontal split screen option. Just use the shoot button for the second player being controlled once you start it up.
[GoldenEye X (v.5e Clouds).pj.zip](https://github.com/gonetz/GLideN64/files/1738784/GoldenEye.X.v.5e.Clouds.pj.zip)
The bottom split screen when using the slayer/seeker weapon's secondary function should look like how it does on the first image I posted with the 4 players. It's a blue hue screen  but it's not supposed to show sky.

This issue needs to be fixed since it effects the horizontal screen in Perfect Dark and GoldenEye X. The original GoldenEye game does NOT have that option available so this issue needs to be fixed for the sake of GoldenEye007 and it's players.

**Comment by tjd2** [comment]
That split screen issue is still here :(. That's bad. Jabo direct3d is only plugin, which runs split screen in Perfect Dark properly

**Comment by Blue-Ike** [comment]
The latest WIP (master + FB fixes) has fixed all these multiplayer splitscreen issues with Perfect Dark and Goldeneye. Plus the Slayer/Seeker fly-by-wire/Guided Missile rendered screens in both PD and GE-X have been fixed as well. This issue can safely be closed along with #1173 .

**Comment by gonetz** [comment]
Thanks
