### ISSUE TITLE
Eiko St Andrews: wrong 3d 

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#161]
When fb should be used by the game for the background, 3d screw up (even with fb on)

![noooooooddddddddddd](https://cloud.githubusercontent.com/assets/8987490/5330427/58657b34-7df2-11e4-9045-3b29b28f9b3f.jpg)

I have other issues (wrong sky, wrong arrow) under Mupenplus but not other emu with this game. It is not a Mupenplus issue, it is plugin issue imo. Glidemk2 has not those issues for instance.

**Comment by gonetz** [comment]
'Depth buffer clear' command is missing. It's not called in both HLE and LLE modes. The game may use CPU to clear depth buffer, because software gfx plugin works correct here. Hardware plugin must use a hack, like "force depth buffer clear".

**Comment by olivieryuyu** [comment]
the game has both a viewport and a depth issue. I was actually wondering if it was not linked. 

https://github.com/gonetz/GLideN64/issues/1426

**Comment by olivieryuyu** [comment]
hmm what is this depth buffer command in microcode?

**Comment by gonetz** [comment]
> hmm what is this depth buffer command in microcode?

SetDepthImage set address of depth image in RDRAM.

To clear depth buffer, program calls SetColorImage with address of depth buffer and renders depth values into it, usually with fillrect command.

**Comment by olivieryuyu** [comment]
hmm and what about a depth compare issue? here as well it can explain why software plugin works but not hardware ones. If i use depth compare option, the characters doe not disappear anymore but we have another issue

![untitled](https://user-images.githubusercontent.com/8987490/27440076-eb564ea2-5769-11e7-991d-42cfc6e417a9.jpg)

Possible?

Weird fact is that the issue only occurs when the background get into a framebuffer. Not sure it is related though.

**Comment by gonetz** [comment]
It is not depth compare issue. It is lack of depth buffer clear issue. Here the hacked version with forced  depth buffer clear call at the beginning of display list:

https://drive.google.com/file/d/0B0YqMPjGo3B2RHFpdjFGV0w5b0U/view?usp=sharing

If N64 CPU does depth clear, software plugin will work fine, because it works with depth buffer in RDRAM.

**Comment by loganmc10** [comment]
@gonetz if you use that build you posted with GoldenEye multiplayer you'll see that it partially fixes https://github.com/gonetz/GLideN64/issues/1173. The bottom half of the screen is now visible, but it flickers. Perhaps a hint as to what is wrong in that case as well

**Comment by AmbientMalice** [comment]
Would it be worth implementing the depth buffer clear hack as an option? I wonder how many games this issue affects, even subtly?

**Comment by gonetz** [comment]
Implemented depth buffer clear option.
@olivieryuyu can it be closed?
