### ISSUE TITLE
Add scalefx-9x please

### ISSUE THREAD

**Issue by Eignar17** [gonetz/GLideN64#1610]
add please @gonetz 
https://github.com/libretro/slang-shaders/blob/master/scalefx/scalefx-9x.slangp

**Comment by gonetz** [comment]
I need c++ code to add texture filter.

**Comment by gizmo98** [comment]
@Eignar
You askes the same question here:
https://github.com/libretro/glsl-shaders/issues/34

Glsl shader post filter support adopted from libretro would be nice.
https://github.com/libretro/glsl-shaders

**Comment by Eignar17** [comment]
@gizmo98 effect not works in texture add in to GLideN64 fix problem texture bad quality

**Comment by gonetz** [comment]
I close this ticket since I can't find c++ code for scalefx.

@gizmo98 
> Glsl shader post filter support adopted from libretro would be nice.

There is an [opinion](https://github.com/gonetz/GLideN64/issues/732#issuecomment-339070167) that the project does not need its own post filters support - external tools can take care about it. This can be discussed in #732
