### ISSUE TITLE
shadows of empire: black triangles (regression!)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1612]
![sans titre](https://user-images.githubusercontent.com/8987490/31052528-46d0241c-a687-11e7-899e-89e384ec3f9a.jpg)

**Comment by gonetz** [comment]
Interesting. The game programmed with an error. It sets mipmap level to 7, but defines only 6 tiles. Fist tile has size 32x32, 6th tile has size 1x1. OpenGL requires that width and height of each next tile in mipmap texture must be halved. 1x1 is minimal texture size, it can't be halved. OpenGL does not create texture, which violates the rule and we see just black polygon. Older version of GLideN64 uses another GL function, which is probably less strict.

**Comment by gonetz** [comment]
Fixed

**Comment by olivieryuyu** [comment]
fixed
