### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by gonetz** [gonetz/GLideN64#1613]
I started to setup Automatic build for GLideN64.
There are several services, which provide Continuous integration for GitHub open source projects for free. I started with AppVeyor to make Windows builds. I just started to learn how to setup AppVeyor. Deployment does not work yet. You may download artifacts of latest successful build (that is the plugin dll) for mupen64plus from here:

https://ci.appveyor.com/project/gonetz/gliden64/build/artifacts

artifacts for older builds can be found in history:

https://ci.appveyor.com/project/gonetz/gliden64/history

I also planing to setup auto build for Linux, but a bit later.

Auto builds for zilmar-spec can be tricky. AppVeyor has QT in their virtual building environment, but it  hardly is what I need. Thus, zilmar-spec builds most likely will be published as usual - manually, in WIP builds thread.

**Comment by fzurita** [comment]
You could always make the static QT library part of the github code, like the libz and libpng.

**Comment by gonetz** [comment]
I wish to avoid it as far as possible. Static QT for MSVS 2015 is circa 2GB.

**Comment by fzurita** [comment]
I don't mean the whole source code, just the compiled binary.

**Comment by fzurita** [comment]
I guess you would need the headers as well, which are rather large. So, never mind.

**Comment by remyabel** [comment]
Any chance of using Travis CI for Linux (and other systems)? I can submit a PR for a `.travis.yml` if you decide to pursue it.

**Comment by gonetz** [comment]
I added project to CircleCI for Linux and Mac builds, but still can't find time to properly setup build here.

**Comment by gonetz** [comment]
@remyabel I setup Travis CI for Linux and MacOsX. README.md has links to build status tokens.

I would like to setup zilmar-spec build too. It can be done, if there will be a server to keep GLideNUI.lib. I don't want to put that lib to the project because it is 370MB debug+release. It is possible to setup build script to load the lib from the server before build starts. I just don't know, where to place the libs.
