### ISSUE TITLE
VidExt_ResizeWindow is called if fullscreen is enabled

### ISSUE THREAD

**Issue by gizmo98** [gonetz/GLideN64#1616]
**System:**
- Intel Core i3 with integrated GPU
- Ubuntu 16.04 with hardware enablement stack HWE
- Monitor resolution is 1024x768
- SDL 2.0.4
- fresh compiled mupen64plus and plugins

**Problem:**
If mupen64plus is started with `--fullscreen` display flickers and there is no picture. According to logfile VidExt_ResizeWindow() is called in fullscreen mode multiple times. The requested (fullscreen) resolution of 1024x796 is not supported. 
[runcommand.txt](https://github.com/gonetz/GLideN64/files/1349293/runcommand.txt)

```
Core Error: VidExt_ResizeWindow() called in fullscreen mode.
(EE) Error setting videomode 1024x796
(II) Setting video mode 1024x768...
Core: Setting video mode: 1024x768
```

I don't think VidExt_ResizeWindow() should be called if fullscreen is enabled.

**Comment by loganmc10** [comment]
Do any of the video plugins actually work with --fullscreen?

This works with mupen64plus-gui (https://github.com/m64p/mupen64plus-gui)

**Comment by gizmo98** [comment]
mupen64plus-video-glide64mk2 works. I have not tested any other plugin.

**Comment by loganmc10** [comment]
Does it change your monitor's resolution to match the resolution in the VideoGeneral config section? Or does it upscale the image to match the current monitor resolution?

**Comment by loganmc10** [comment]
But either way, stopping ResizeWindow from being called in fullscreen won't break mupen64plus-gui.

https://github.com/gonetz/GLideN64/blob/master/src/Graphics/OpenGLContext/mupen64plus/mupen64plus_DisplayWindow.cpp

m_bFullscreen needs a bit of work, it's not properly tracking the fullscreen state (it doesn't get toggled when _changeWindow is called)

Then inside ```DisplayWindowMupen64plus::_resizeWindow()``` you can just wrap ```CoreVideo_ResizeWindow()``` instead a check for !m_bFullscreen

**Comment by gizmo98** [comment]
This ubuntu SDL2 version tries to change monitor resolution. But resolution change faily if requested resolution is higher than max Monitor resolution.

**Comment by gizmo98** [comment]
@loganmc10 
I don't think mupen64plus-gui is broken. I just see flickering if pc tries to change modes all the time.

DisplayWindowMupen64plus::_resizeWindow() disables fullscreen --> m_bFullscreen = false;
https://github.com/gonetz/GLideN64/blob/ad48345ec02274d321df760676cb8237ddbb555c/src/Graphics/OpenGLContext/mupen64plus/mupen64plus_DisplayWindow.cpp#L131

As you said it should be toggled if CoreVideo_ToggleFullScreen() is called in
void DisplayWindowMupen64plus::_changeWindow()
https://github.com/gonetz/GLideN64/blob/ad48345ec02274d321df760676cb8237ddbb555c/src/Graphics/OpenGLContext/mupen64plus/mupen64plus_DisplayWindow.cpp#L146

**Comment by gizmo98** [comment]
We do not keep track if fullscreen is set or not. mupen64plus-core has a VidExt_InFullscreenMode function which returns fullscreen state.
https://github.com/mupen64plus/mupen64plus-core/blob/e805380a3a284074698a7d6c61e1ff70e3cc2271/src/api/vidext.c#L85

GLideN64 does not use this function:
https://github.com/gonetz/GLideN64/blob/e28bebd17e6066a525b7ab95bd776669d6cfcd7a/src/inc/vidext.h#L35

**Comment by gonetz** [comment]
@gizmo98 could you provide solution for this problem with PR? It will be easier to discuss the concrete code.
