### ISSUE TITLE
1x native resolution factor breaks pause menu in CBFD (Adreno only)

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1617]
Using 1x native tradition factor breaks the pause menu in CBFD. Example:

![conker_bfd-002](https://user-images.githubusercontent.com/11581687/31084125-9704af7c-a761-11e7-8d22-802e94519777.png)

My guess is that it has to do with the resolution the game runs at since for example, Mario kart effects work correctly at 1x (monitor in first course).

This pause menu works correctly at 2x native resolution.

**Comment by Frank-74** [comment]
With latest deaf612 build, I'm not seeing any problems with pause menu on nativeResFactor=1.
First time I ran, I had inverse green/blue colours on pause menu.  I restored defaults, set native resolution and restarted.  Now it's fine.

**Comment by fzurita** [comment]
Ok, must be Android only.

**Comment by loganmc10** [comment]
Tested with mupen64plus+Windows, no issues (tested during the opening cutscene and in-game)

**Comment by fzurita** [comment]
I did further testing and this only affect Adreno.... not sure why though.

**Comment by fzurita** [comment]
Fixed by #2480
