### ISSUE TITLE
Wrong detection of expansion pack by plugin/emu with fb + depth buffer write on

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#162]
I started with 1964 and the game doesn't start with with fb + depth buffer write.

Weirdly with fb + depth buffer write the detection of the expansion pack from 1964 get running from D to E and game doesn't start.

![yy](https://cloud.githubusercontent.com/assets/8987490/5330487/15833ddc-7df8-11e4-87fc-df60622ea30d.jpg)

**Comment by gonetz** [comment]
"the game doesn't start" - which game?

**Comment by olivieryuyu** [comment]
rat attack

**Comment by olivieryuyu** [comment]
fixed
