### ISSUE TITLE
[Help wanted] Setting up a post processing filter.

### ISSUE THREAD

**Issue by standard-two-simplex** [gonetz/GLideN64#1620]
I would like to try playing around with post processing, but I'm not sure about how to do it.
I'd appreciate help with the steps up to the point where I have a function of the type `` myfilter(buffer,dest_buffer)`` or similar.
What are those steps and how to implement them?

**Comment by fzurita** [comment]
Look at https://github.com/gonetz/GLideN64/blob/master/src/PostProcessor.cpp and how it's used. You should be able to take a glsl shader and apply it as an additional post processing step.

Although, the way it's currently coded does not seem very maintainable.

**Comment by gonetz** [comment]
> Although, the way it's currently coded does not seem very maintainable.

Alas, its true.

It would be better to incorporate Dolphin's post-processing module.

If you want just to play with post-processing shaders, you may replace shader program for existing post filters: gamma correction or orientation correction.

**Comment by standard-two-simplex** [comment]
Let me see if I understood the pipeline correctly.
1. A buffer is created of size of the output.
2. A dummy rectangle is rendered on top of it.
3. The value of ``gl_FragColor`` is changed in shader.
Is that it?
Also, is the uniform ``Sample0`` the one I need to fetch texels?

**Comment by gonetz** [comment]
> A dummy rectangle is rendered on top of it.

Why dummy? Fullscreen textured rectangle.

> is the uniform Sample0 the one I need to fetch texels?

Sample0? I see it only in blur shader, which was disabled during refactoring.

Check GammaCorrection or OrientationCorrection shader in src\Graphics\OpenGLContext\GLSL\glsl_SpecialShadersFactory.cpp

**Comment by standard-two-simplex** [comment]
> Why dummy? Fullscreen textured rectangle.

I meant dummy as in there's no texture which corresponds one to one to the rectangle, and then values are set in shader.

> Check GammaCorrection or OrientationCorrection shader in src\Graphics\OpenGLContext\GLSL\glsl_SpecialShadersFactory.cpp

Thanks, I had only checked ``postProcessor.cpp``. So ``uTex0`` contains the rendered scene, right? How does VI interact with this, does ``uTex0`` already have black borders or are they applied later?

**Comment by gonetz** [comment]
> uTex0 contains the rendered scene, right?

Right.

> uTex0 already have black borders or are they applied later?

Depends on how game is programmed. The game may add black borders with RDP, or it can place image on screen with borders in VI. In first case buffer texture will have black borders, in second case not.

**Comment by standard-two-simplex** [comment]
I understood how it works so the issue is no longer necessary.
