### ISSUE TITLE
Shader CTD

### ISSUE THREAD

**Issue by Danfun64** [gonetz/GLideN64#1628]
Getting this for some reason on a self compiled Mupen64Plus setup: http://paste.debian.net/989689/

I seem to get further and further along each time I restart the emulator for some reason http://paste.debian.net/989690/

Setting EnableShadersStorage to False allows me to play the game without crashing.

**Comment by retrobenny** [comment]
CTD... (crash to desktop?)

If you already had storage made on a different version,it could be the cause of issues.
Keep copies of the shader storage if you have any still (for future reference) by moving them elsewhere to renew the shader storage and test again with it set to true to see if the problem persists on a set of fresh shader storage sessions.
If the crashing issue still occurs,it could be some storage file corruption issue that would need sorting out.

I personally don't like using shader storage and hope that a solution can be made soon to eliminate the shaders stutters entirely so there will no longer be a need for storage with a mirrored idea of what another certain console emulator currently does,but that idea may have to wait if nobody from elsewhere designs it with a branch,many more pressing issues on the plugin to fix first...including this one. 😉

**Comment by Danfun64** [comment]
Deleted the file and started again. Problem stopped... then again I changed the RSP setting, so that might have something to do with it...idk

**Comment by Danfun64** [comment]
I tried deleting my config, but the issue still no longer occurred. As this issue doesn't seem reproducible, I am closing it for now...
