### ISSUE TITLE
Cruis'n Exotica: heavy gfx errors

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#163]
![buggg](https://cloud.githubusercontent.com/assets/8987490/5330495/f3c66ed4-7df8-11e4-932a-f661a1b47aac.jpg)

Was fixed few weeks ago

**Comment by olivieryuyu** [comment]
cannot be fixed?  WCW Backstage Assault is fixed

**Comment by olivieryuyu** [comment]
it is now completely completely wrong

![sans titre](https://cloud.githubusercontent.com/assets/8987490/13006713/159bbabe-d18b-11e5-90eb-acfc6dacbff5.jpg)

**Comment by purplemarshmallow** [comment]
LLE looks correct

**Comment by olivieryuyu** [comment]
fixed
