### ISSUE TITLE
x64 MSVC target for mupen64plus

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1632]
Every time I try to do this in Visual Studio it seems to edit way too many things.

@gonetz when you get a chance can you add an x64 target for the msvc15 mupen64plus build?

**Comment by gonetz** [comment]
ok

**Comment by gonetz** [comment]
@loganmc10 : I made x64 target for mupen64plus builds in MSVS 2015 project: daecd15ca8

Please check that resulted dll works with 64bit mupen64plus.

**Comment by loganmc10** [comment]
Yep built on the first try and works without issue, thanks!
