### ISSUE TITLE
MRC - Multi Racing Championship missing ground

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1634]
Once a race is entered, there are big sections on the ground that are missing. The issue is very easy to see, just start a race.

Hmm, I wonder if it's an issue with the core, Angrylion had the same problem.

**Comment by AmbientMalice** [comment]
I can't reproduce this. What emu, and what version?

**Comment by fzurita** [comment]
Mupen64plus in latest GitHub version. It's probably a bug with the core. I'll open an issue there instead and close this one.

**Comment by AmbientMalice** [comment]
>Mupen64plus in latest GitHub version.

64 or 32 bit?

**Comment by fzurita** [comment]
32 bit. It works fine when running in interpreter mode instead of dynarec.
