### ISSUE TITLE
Goldeneye minor UI bugs.

### ISSUE THREAD

**Issue by LuismaSP89** [gonetz/GLideN64#1636]
This problem has been going on for months, but it doesn´t happen with older builds of Gliden64 (I don´t know how much time ago) but i used the same settings.

Images attached:

![2](https://user-images.githubusercontent.com/12205048/31592164-9c69bd48-b226-11e7-8f30-83e844f22466.jpg)
![1](https://user-images.githubusercontent.com/12205048/31592165-9c87b17c-b226-11e7-8070-9c82190e1f2d.jpg)

**Comment by fzurita** [comment]
How do you get the game in Spanish? Does the USA version of the game have the same issue?

**Comment by Frank-74** [comment]
I believe it's a modded/patched Goldeneye: http://www.goldeneyevault.com/viewfile.php?id=205

**Comment by LuismaSP89** [comment]
Yes, it´s a patched version from USA game. I tested it with a USA version without patching and works the same.

**Comment by LuismaSP89** [comment]
Ok, after downloading many other versions, i managed to solve the problem. Sorry. Closing issue.

**Comment by fzurita** [comment]
What was the problem in case somebody else has it too?

**Comment by LuismaSP89** [comment]
To be honest, i don't know. Maybe with other rom, the shader cache is build again?
