### ISSUE TITLE
International Superstar Soccer 64 shadows problem

### ISSUE THREAD

**Issue by Frank-74** [gonetz/GLideN64#1637]
(U) version:
![gliden64_i_s_s_64_000](https://user-images.githubusercontent.com/11056843/31646058-74015c18-b2f7-11e7-87e0-444bc7b85bab.jpg)

(E) region has black screen with frame buffer emulation enabled.

**Comment by AmbientMalice** [comment]
Try enabling N64 depth compare.
https://github.com/gonetz/GLideN64/issues/103

(E) region version is probably separate issue.

**Comment by Frank-74** [comment]
Ah, that's not going to work for me GL4.0, needs 4.3.
Close anyway, as it's been dealt with before.

**Comment by maximus210793** [comment]
How can I fix the issue on delta ?

**Comment by mightysabean** [comment]
How can we fix on delta emulator
