### ISSUE TITLE
Zelda Ocarina shadowy floor graphic glitch. (oops its on Intel)

### ISSUE THREAD

**Issue by retrobenny** [gonetz/GLideN64#1642]
No matter what settings I use,this weird glitch appears on the floor when viewed at this angle at the depicted location in the picture.
This is on the full improved blending Rev.deaf612 build.

![image](https://user-images.githubusercontent.com/16418716/32138881-b836d27a-bc00-11e7-94d3-d60feae95d11.png)

If you turn around or view it in any other angle,it doesn't appear.

Project64Video doesn't have this issue. (can't use Glide64 Final 2012 to test it)

![image](https://user-images.githubusercontent.com/16418716/32138898-01bee6f8-bc01-11e7-8136-28b4b68ad558.png)

Still using my Nvidia GPU and its a GeForce 940MX on somewhat old but really stable drivers.

**Comment by retrobenny** [comment]
A savestate for V1.0 to test.

[Glitched 1.0 Floor.pj.zip](https://github.com/gonetz/GLideN64/files/1424668/Glitched.1.0.Floor.pj.zip)

It also appears in V1.2 as well and it doesn't even have to be in that exact spot,just somewhere around the area facing a similar direction.

**Comment by gonetz** [comment]
Is texture filtering set to "standard" or "3-point"?
3-point filtering is broken in current master.
Standard one works fine, I can't reproduce the problem.

**Comment by retrobenny** [comment]
That sucks.

I use 3-point normally because I like the genuine look and hate blur from bilinear and also because the stairs in Zelda only render properly with 3-point as they have been shown to look broken with bilinear on original Glide64.

**Comment by gonetz** [comment]
> 3-point filtering is broken in current master.

Looks like I had obsolete shader storage. I updated it and everything works. I can't reproduce the bug you reported.

**Comment by retrobenny** [comment]
And I don't use shader storage,yet I see the issue,meaning its very likely not caused by shader storage.
Did you test the commit deaf612 I mentioned? Could it be a GPU specific issue?
Maybe the savestate usage makes it "misbehave" since savestates can be problematic for debugging issues.
A native save file would be more reasonable especially since its globally usable on every version of the game.
You can always save the game via loading the save state then using the sub-screen (since its stable to do this with Ocarina) and then walk back to the spot and turn at every angle to look for the issue.

**Comment by gonetz** [comment]
I tested with recent master (https://github.com/gonetz/GLideN64/issues/1574#issuecomment-340250162)
I set default settings, then set 3point filtering and set custom settings and shaders storage off.
I loaded from native save in link's house. I moved to the place where you have the problem. No problems for me.

Commit https://github.com/gonetz/GLideN64/commit/deaf61299f12168b775d7e2d448b9eca149c0e7e
is really GPU specific. The issue appeared on GPUs, which support glTexStorage2D, which require OpenGL 4.2 or tex storage extension. If GPU does not support texture storage, plugin uses glTexImage2D, which seems to be less restrictive to correctness of texture level. Anyway, the fix makes texture level correct for both texture image and texture storage.

**Comment by retrobenny** [comment]
Just tested that build and still see the issue,wonder what could be causing it since you have no problems with it.

**Comment by gonetz** [comment]
May be this issue is Intel GPU specific. I tested on AMD and nVidia.

**Comment by retrobenny** [comment]
Had the silly thing on Intel.

I swore that it defaulted to Nvidia but once I used the context menu to force it to use Nvidia,the issue went away.

My other problem is that Nvidia is slower than using the Intel GPU if even only by a few fps.
I desperately need some life hacks to make my Nvidia GPU's inherent performance not suck.

**Comment by gonetz** [comment]
Sounds like the problem is not plugin related and the ticket can be closed.
