### ISSUE TITLE
Plugin freezes game when changing settings when game is booted. BSOD involed.  

### ISSUE THREAD

**Issue by Yui12** [gonetz/GLideN64#1645]
I'm on Windows 7 by the way. The latest Master has this problem for me and I have no idea why. The BSOD happens when I try to go back to the graphics menu settings after the freeze occurs. BSOD doesn't happen when I just simply click out of the emulator without doing anything else after the freeze occurs. Have no idea if its me or a fatal bug in the plugin.

**Comment by AmbientMalice** [comment]
What emulator are you using?

**Comment by Yui12** [comment]
I forgot, it is Project 64 2.3.2. I updated, and it still has the same problem.

**Comment by Yui12** [comment]
I must be the only one that has this problem considering how no one else is reporting this. In that case, then what BS luck for me. I guess I'll have to find that older version I was using for now which sucks for me.

**Comment by LegendOfDragoon** [comment]
>I must be the only one that has this problem

I wouldn't make that assumption. I have been having odd issues on my end. I just haven't devoted the time to narrowing down possibilities. I don't get BSOD or anything, but some weird stuff, like frozen screen. I suspect my issue might at least be partially due to constantly testing many different versions of the plugin.

**Comment by Yui12** [comment]
Sorry about that. I'm a bit stressed right now when it comes to my personal life at the moment, but anyway the screen freezing is about right.  I also keep forgetting that I can still play games with the plugin as long as I don't mess around with the setting after loading the game.

**Comment by Yui12** [comment]
Does anyone else have this problem? I think it is me, but don't know why.

**Comment by gonetz** [comment]
It depends on game. I can change settings during gameplay for most games, but some games e.g JFG freeze  or crash. I pause games to change settings safely.

**Comment by Yui12** [comment]
Wait a minute, you're right! Pausing it before changing the settings does prevent the whole emulator from freezing. Strange thing is that I tried this once and it didn't work. I guess that solves the problem, but I'm hesitant to close this issue since most people don't know about it. Strange workaround, but it's no big deal in the end. Thanks I guess, but it now suddenly worked after testing a few games.

**Comment by Yui12** [comment]
Alright, problem seems to be fixed now or I never noticed this, but it automatically pauses now when you access the config options.

**Comment by gonetz** [comment]
It doesn't pause - plugin stops rendering when config dialog is open. Emulaton coninues, unless you press pause before opening the config.

**Comment by Yui12** [comment]
Strange since I notice that after I open and close it in the middle of a gaming running, the system option in Project 64 says resume even though I didn't bother to pause first, but alright.
