### ISSUE TITLE
Mario Tennis: Glicthes during intro

### ISSUE THREAD

**Issue by DonelBueno** [gonetz/GLideN64#1649]
GLide (Latest WIP Builds 3)

![32514843-5ed321f6-c3e5-11e7-8d53-609bc1050dcc](https://user-images.githubusercontent.com/4239694/32516415-67f22156-c3ea-11e7-9243-dc6ae9f5631f.png)

Angrylion:

![project64 2017-11-14 18-31-30-81](https://user-images.githubusercontent.com/4239694/32803334-558385fc-c96a-11e7-9ca8-e03b169fb4d0.png)

GLide (Latest WIP Builds 3)

![32514846-5f0ee0d8-c3e5-11e7-82ce-83d6d0a97989b](https://user-images.githubusercontent.com/4239694/32516424-72534594-c3ea-11e7-88d9-a84ce42de13d.png)

Angrylion:

![32514848-5f2fd018-c3e5-11e7-85d1-f859cc9b3364b](https://user-images.githubusercontent.com/4239694/32516429-74fbc8fc-c3ea-11e7-8c90-844f8dc0f382.png)

Tested on Windows. Tested public releases 2.0 and 1.2, both present the same glitches. I think it has awlays been like that.

Funny thing is: shadows look fine during gameplay.

**Comment by gonetz** [comment]
> I think it has awlays been like that.

Yes.

> shadows look fine during gameplay

true.

**Comment by gonetz** [comment]
Shadows look better with N64 depth compare enabled. Not perfect, but better. N64 depth compare is imperfect by itself without coverage emulation.

As for cone of light. I guess it is another manipulation with texture format, which can't be directly reproduced on GPU. That is special code needed.

**Comment by DonelBueno** [comment]
The shadows on intro are fixed (even with depth compare disabled), but the light cone issue is still there.

**Comment by DonelBueno** [comment]
Closing this in favor of #230. Since the shadow issue is already fixed, now it is a duplicate of #230.
