### ISSUE TITLE
New shader cache breaks with hardware per pixel lighting enabled

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1650]
@gonetz This is probably important.

For example, in Super Mario 64:

- First make sure hardware per pixel lighting is enabled.
- Delete the shader file for the game.
- Start the game and enter the game to let some shaders generate.
- Exit the game and delete the .shaders file but leave the key file.
- Resume the game, shaders file will be regenerated from key file.
- Everything will have rainbow colors.

**Comment by gonetz** [comment]
Confirmed.

**Comment by gonetz** [comment]
I disabled hardware per pixel lighting  for games with custom lighting. This is done per ucode. Ucode is known when game started to run. Shaders created from storage during RomOpen API command, when rom is not started yet and plugin does not know which ucode will be used. It disables hardware lighting for shaders generation, but enables it later, when game started. I need to think how to sort it out.

**Comment by fzurita** [comment]
Fixed

**Comment by oddMLan** [comment]
CBFD doesn't support hardware lightning? I've never noticed any issues with it

**Comment by fzurita** [comment]
It does not support it

**Comment by gonetz** [comment]
> I've never noticed any issues with it

It is because it was silently disabled for this game regardless of config option.
