### ISSUE TITLE
Shader keys never created (Mesa)

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1651]
I thought https://github.com/gonetz/GLideN64/commit/c5c0fbeb6fe3ea6b0de8c6353910dc6bdb038ec5 should have taken care of this.

However, testing in Linux with Mesa (Mesa doesn't support shader binarys), the .keys file is never created for any game.

**Comment by gonetz** [comment]
Yes, it should fix it. I force disabled shaders binary in glinfo, and plugin created .key files. I tested on Windows. May be there is Linux specific code, which prevents this functionality.

**Comment by loganmc10** [comment]
Sorry this was my mistake. I thought the key files would be in ```.local/mupen64plus/shaders``` but they are in ```.cache/mupen64plus/shaders```
