### ISSUE TITLE
Zelda OOT, bad lighting with HW per pixel lighting

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1652]
Here is a screenshot:

![the_legend_of_zelda-002](https://user-images.githubusercontent.com/11581687/32616136-97e20c90-c53f-11e7-8f76-84bd1dd83689.png)

It looks fine with HW per pixel lighting disabled.

This must be a recent bug since it used to work correctly quite recently.

**Comment by gonetz** [comment]
What is bad? I see no difference with Release 2.0 in work of HW per pixel lighting.

**Comment by fzurita** [comment]
This is what it should look like. See Link's hat:

![the_legend_of_zelda-003](https://user-images.githubusercontent.com/11581687/32668264-0ee8b818-c60b-11e7-9fdc-b8a7ff1cafff.png)

**Comment by gonetz** [comment]
No, this is what it should look like with standard lighting.
Per-pixel lighting works differently and produces different result. It is normal.
Can you find a version with hardware lighting, which gives result as on your second screen shot?

**Comment by fzurita** [comment]
Maybe my memory is incorrect as to when it worked correctly last. I thought it worked correctly not as long ago.

**Comment by gonetz** [comment]
It was broken in November 2016. Not so long ago :)

**Comment by gonetz** [comment]
Fixed.

**Comment by fzurita** [comment]
Confirmed

**Comment by fzurita** [comment]
For comparison, it now looks like this:

![the_legend_of_zelda-005](https://user-images.githubusercontent.com/11581687/32688904-95b6b560-c6a7-11e7-99ab-410021736866.png)
