### ISSUE TITLE
Need help with testing new texrect code

### ISSUE THREAD

**Issue by gonetz** [gonetz/GLideN64#1656]
There is one old problem: #146
The problem caused by inability of current code to deal with integer overflow because it uses floats.
I needed to rewrite large part of texture coordinates calculation code for texrects to fix it.
I did it. The problem #146 solved. Texrects are used by almost all games. I could make a mistake somewhere. I almost sure that I did some. I need help with testing.

Test commit: 32e0d17468b1

Test build for Windows:
https://drive.google.com/file/d/1D0I1scAEIdHD9IeYVYHi6jV5w0AAGdXK/view?usp=sharing

**Comment by AmbientMalice** [comment]
I've tested a bunch of usual subjects like 40 Winks and Top Gear games. No regressions found. However, the original game still has problems.

![gliden64_mlb_featuring_k_g_jr_002](https://user-images.githubusercontent.com/10704701/32694644-1bc60f86-c791-11e7-833c-942f2987b8d7.png)

**Comment by loganmc10** [comment]
Doesn't that happen with angrylion as well? Maybe I'm remembering wrong but I thought I saw that there as well

**Comment by AmbientMalice** [comment]
>Doesn't that happen with angrylion as well? Maybe I'm remembering wrong but I thought I saw that there as well

There is flicking as each screen fades in, but the backgrounds do render on Angrylion's.

**Comment by gonetz** [comment]
Background is another issue not addressed by this fix.

**Comment by mudlord** [comment]
I hate to be judgmental, but wasn't this a problem from the beginning (and much longer ever since HLE existed)?

Seems everything comes back to fixed point/integer usage:
* The combiner, including every single shader.
* Texture coordinates
* Microcode handling.
* etc.

Makes me wonder why not everything is done in fixed point/ints whenever possible.

**Comment by standard-two-simplex** [comment]
In beetle adventure racing, traffic signs show wrong at some distance. Looks like mip-maps are sometimes wrong.

![beetle_adventure_rac-000](https://user-images.githubusercontent.com/12202580/32739663-da4c05fe-c8a0-11e7-9e36-98c02019b7a5.png)

You have a shift done with bitwise operations and one with multiplication by ``shiftScale``. Isn't one of them redundant?

**Comment by gonetz** [comment]
> You have a shift done with bitwise operations and one with multiplication by shiftScale. Isn't one of them redundant?

No. bitwise applied to original S and T parameters of texrect. shiftScale applied to (_params.lrx - _params.ulx) * _params.dsdx, that is to offsetS. In other words, old code:
`(S + offsetS) * shiftScaleS`
new code:
`bitwiseShiftScaleS(S) + floatShiftScaleS(offsetS)`
When bitwiseShiftScaleS does not cause integer overflow, results of old and new code are the same.

Texture glitches on your screen shot belongs to regular triangles. not to texrects. Thus, this issue is not related to texrects fixes. Besides, I can't reproduce it. BAR works correct for me with this fix and with master branch.

**Comment by standard-two-simplex** [comment]
> No. bitwise applied to original S and T parameters of texrect. shiftScale applied to (_params.lrx - _params.ulx) * _params.dsdx, that is to offsetS.

That's true, I overlooked it.

**Comment by gonetz** [comment]
The fix added to master.
