### ISSUE TITLE
[macOS] Picture size changes

### ISSUE THREAD

**Issue by StenApp** [gonetz/GLideN64#1659]
@gonetz 

When is start Mupen64plus and load a rom my window is bigger as the game shown.
if I push the buttons it flickers between the full window resolution and the smaller size.
![big](https://user-images.githubusercontent.com/32524257/32701385-90d01f22-c7d4-11e7-9ff3-21657af79e0c.jpg)
![small](https://user-images.githubusercontent.com/32524257/32701433-9fe1048a-c7d5-11e7-9147-527a4ce6de74.jpg)

**Comment by loganmc10** [comment]
This may be an issue with mupen64plus-gui on a Mac, not specific to GLideN64. It does work on Windows or Linux

**Comment by StenApp** [comment]
Damn, I cannot get this fixed. I have ugly flickering between those two pictures.
Sometimes Goldeneye logo gets rendered in big picture but with it's painted at the upper left edge of the smaller picture.

**Comment by gonetz** [comment]
I have only command line access to Mac build workstation,  I can build  but  can't debug the application. You may try to add logs using LOG () function from Log.h it will log to gliden64.log file in mupen64plus folder. You may log parameters from DisplayWindowMupen64plus::_resizeWindow() and see, which window size plugin gets from emulator.

**Comment by StenApp** [comment]
```
[gles2GlideN64]: _setAttributes
[gles2GlideN64]: Create setting videomode 800x600
OpenGL major version: 4
OpenGL minor version: 1
OpenGL vendor: ATI Technologies Inc.
OpenGL renderer: AMD Radeon Pro 560 OpenGL Engine
```
no errors in Gliden64.log

**Comment by StenApp** [comment]
@gonetz is there any method to distinguish between OpenGL errors, OS errors and mupen64plus errors?

**Comment by gonetz** [comment]
Yes. OpenGL probed for errors with special glError function. OS errors detection is OS dependent, I know nothing about Mac. I also never tried to debug Mupen64plus. Mupen64plus uses SDL2 for work with OpenGL,  so problems can be on this side too.

**Comment by StenApp** [comment]
I suspect SDL2

**Comment by loganmc10** [comment]
mupen64plus-gui doesn't use SDL2 for OpenGL/display, it uses Qt 5

**Comment by StenApp** [comment]
I'm baffled with that error

**Comment by StenApp** [comment]
broken on MacBook Pro retina graphic/emulator error

**Comment by joeldenning** [comment]
I ran into this today - what I've been able to figure out so far about it is that it's related to me having connected my laptop to an external monitor. Previously, the game would be full window on my mac screen, but now it's only a quarter of the window on the mac screen. However, when the game is on my external monitor, there is no issue.
