### ISSUE TITLE
Quest64 filtering issue with text

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#166]
![filtering](https://cloud.githubusercontent.com/assets/8987490/5331126/ec1290f6-7e1a-11e4-8bd8-08c81884b3be.jpg)

link with  #153?

**Comment by Aquatakat** [comment]
There are a few games with a similar issue like Rush 2's menu.

**Comment by gonetz** [comment]
Yes, #153 fixes this issue.

**Comment by olivieryuyu** [comment]
idd, very good :)

**Comment by gonetz** [comment]
The N64 bilinear filtering by itself does not fix the text issue. Text is fixed by a hack in N64 bilinear filtering shader. The hack spoils textures with zero alpha and thus must be removed. Without the hack the pink outline is back.

**Comment by AmbientMalice** [comment]
This is fixed when running in native resolution.

**Comment by olivieryuyu** [comment]
fixed with native texrec
