### ISSUE TITLE
Majora's Mask - custom textures broken on moon

### ISSUE THREAD

**Issue by Nerrel** [gonetz/GLideN64#1662]
Using the MM point lighting WIP build, the texture for the back/sides of the moon is partially broken when using custom textures.  The same texture is used for the sides, back, and underside of the moon.  It maps correctly on the sides, but for some reason is stretched into a series of lines on the bottom of the moon only:
https://c1.staticflickr.com/5/4571/37731149054_47c223dcb0_o.jpg

This did not happen in the 2.0 release; the texture mapped the same way all over the moon's surface.  It seems to have nothing to do with the texture itself- this even happens when using the dumped original texture as a custom texture:
https://c1.staticflickr.com/5/4561/37731141424_56908178bc_o.jpg

I haven't seen any other texture problems anywhere else in this build.  One thing unique to this texture is that it is abnormally large at 128x128, while most textures in the game max out at 64x64, if that has anything to do with it.

**Comment by gonetz** [comment]
> One thing unique to this texture is that it is abnormally large at 128x128

Yes, the problem is with it. Texture of such size can't be loaded into N64 texture memory. Size of actual texture in TMEM is 64x64. That is the game set tile size larger than size of actual tile. It works on N64 hardware because address of fetched texel is automatically wrapped and does not cross TMEM bounds. Hardware plugin can't make GPU to wrap texture address, thus it should either force mirroring (that is use hack), or load pre-mirrored texture of 128x128 size (use workaround). GLideN64 uses second approach. Hires texture corresponds to actual 64x64 texture. Texture mirroring must be forced to use it properly. I'll add that hack for hires textures. Will see, how well it will work.

**Comment by gonetz** [comment]
@Nerrel 
I put the fix to hires_texture_fixes branch

Test build:
https://drive.google.com/file/d/1yuKR3FyCTdgD34wr6zBvWgjmmYzk13ke/view?usp=sharing

Please test that no new issues appeared.

**Comment by Nerrel** [comment]
Thank you.  The texture works now and I didn't notice anything else being broken, although the mirroring gives a less attractive result:
https://c1.staticflickr.com/5/4574/38413011316_13fffd4795_o.jpg

It would be kind of hard to reduce the obvious mirroring with a texture that's dense with details like this.  Is this mirroring the only possible solution?  These textures are mapped in a way that will have seams no matter what, but 2.0 did look more natural:
https://c1.staticflickr.com/5/4545/38413004576_b697c0e9b7_o.jpg

Also, after reading some of the other issues, I wasn't aware textures needed to be a factor of 2x.  I have many 5x textures that seem to be working just fine... are there any specific situations where these odd integer scales would become problematic?

**Comment by gonetz** [comment]
>Is this mirroring the only possible solution?

I will check what else can be done. 

 > I have many 5x textures that seem to be working just fine..

Rice format defines scale factor for hires textures as power of two. 2x 4x and so on. Using arbitrary scale factors may lead to unpredictable issues because loading code does not expect it.

**Comment by gonetz** [comment]
@Nerrel I replaced 'force mirror' by 'force mirror/wrap'. If tile has mirror flag, it will be mirrored, otherwise texture will be wrapped. It is still a hack, but it alters only one tile parameter, not two. The result for moon is better now.

Test build:
https://drive.google.com/file/d/1hZA6y0prDZrqK6addCG1nr6PjqLpZN77/view?usp=sharing

**Comment by Nerrel** [comment]
That does look much better, thanks.  I guess I can close this now?

**Comment by gonetz** [comment]
Yes. Please report if you will notice regressions with this fix.

**Comment by Nerrel** [comment]
This issue seems to be happening again in the Deku shrine race area.  Textures are dumping very strangely and inconsistently with the newest versions (I tested Naboo alpha 1 and 3) with excessive tiling that seems totally wasteful and incorrect.   I went back to 2.0 and found that the textures were dumping much smaller and with less tiling; here are two textures as dumped by the 3 revisions I was tried:
https://c2.staticflickr.com/2/1779/42023134020_f4b2d9be5b_h.jpg

I tried replacing the textures as dumped by Naboo alpha 1, excessive tiling and all, and found that they were displayed incorectly in-game.  However, they worked fine in 2.0.  The tree in these images demonstrates the difference;
Alpha 1: https://c1.staticflickr.com/1/856/43831389501_cc1d9f78c4_c.jpg
2.0:  https://c1.staticflickr.com/1/856/43831389821_5e955cc8ff_c.jpg

Here is a savestate for this area.  The tree area can be reached quickly by just following the butler for amoment, but almost all of the textures within this location seem to suffer from the issue.  I have not had any issue with textures dumping or displaying like this anywhere else in the game using the Naboo alpha builds, so the problem is limited to just this cave.  
https://mega.nz/#!jBtD1T6a!gI9kZyvqncBRLnWQDTdWUwK-cEfDl_iCF_5vx_IaF28

 I have N64 mip-mapping disabled, "try to adjust game to fit" on, and the resolution is set to a multiple of 7x.  Otherwise, the emulation settings are at default and I'm on Windows 10x64 using Nvidia.  Let me know if you need any other information.
