### ISSUE TITLE
Config dialog crashes until I restart computer

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1663]
In project 64, at be random times, I can no longer open the config settings dialog. When in try to open it, project 64 will crash. I can't seem to figure out what is causing it because when I use the debug build, it doesn't crash any more. That makes it really hard to debug.

The only way in have figured out how to recover is to restart the whole computer, then it starts working again.

**Comment by gonetz** [comment]
Does it happens only with Project64? Could you try to reproduce it with 1964 or Mupen64?

**Comment by fzurita** [comment]
Yeah, sure, next time it starts happening.

**Comment by fzurita** [comment]
I just tested 1964, it crashes there as well.

**Comment by gonetz** [comment]
@fzurita Is the problem still actual? I don't have problems like this.

**Comment by fzurita** [comment]
I haven't tried reproducing it. I'll close it for now.

**Comment by gonetz** [comment]
Ok. Please reopen if the problem still presents.
