### ISSUE TITLE
[macOS] Graphics are broken

### ISSUE THREAD

**Issue by StenApp** [gonetz/GLideN64#1669]
I don't know what the problem is, graphics stay broken...
Running High Sierra with Radeon  Pro 560, OpenGL 4.1.
Tested angrylions and GlideN64, both bring same problems.

Any hint is welcome....

https://github.com/m64p/mupen64plus-GLideN64/issues/38

**Comment by loganmc10** [comment]
duplicate of https://github.com/gonetz/GLideN64/issues/1659

**Comment by gonetz** [comment]
No need to create duplicated tickets , it does not help to solve the problem.
