### ISSUE TITLE
Racing Simulation 2: background textures in menu + lines

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#167]
![gdhfghdghf](https://cloud.githubusercontent.com/assets/8987490/5331149/bf4fd4a6-7e1b-11e4-8c86-76620502aae1.jpg)
![arfggg](https://cloud.githubusercontent.com/assets/8987490/5331150/c1f2e0fe-7e1b-11e4-950c-544217ab4e61.jpg)

**Comment by olivieryuyu** [comment]
commit f6be5fd : no more lines but bad gfx and crash when arriving in menu

![sans titre](https://cloud.githubusercontent.com/assets/8987490/13897155/efc8a986-eda6-11e5-82ef-f98f295aba6f.jpg)

**Comment by gonetz** [comment]
I see. Will be fixed.

**Comment by AmbientMalice** [comment]
Seems fixed. Can be closed.

**Comment by olivieryuyu** [comment]
fixed
