### ISSUE TITLE
OOT - major graphic glitches in cutscene

### ISSUE THREAD

**Issue by KingOfHyrule** [gonetz/GLideN64#1673]
![gfx bug](https://user-images.githubusercontent.com/31485246/33285951-a8e699a0-d392-11e7-8d18-840cee3bfca3.jpg)
This cutscene happens near the end of the game, and has some kind of mask applied over it. At the beginning/middle of the game, this scene actually happens in real time, and works as expected. Just this "memory" scene glitches.

Save file and save state, for convinience (mupen):
[oot saves.zip](https://github.com/gonetz/GLideN64/files/1507363/oot.saves.zip)

**Comment by loganmc10** [comment]
bad commit: 977fddf3ea9e0271a1280d94ad94dc7df0991eda

**Comment by KingOfHyrule** [comment]
Also, on the "The end" screen:
![gfx bug 2](https://user-images.githubusercontent.com/31485246/33289776-66caff36-d39f-11e7-99f0-2cc08ee32141.jpg)

Save state:
[Legend of Zelda, The - Ocarina of Time (U) (V1.2) [!].st1.zip](https://github.com/gonetz/GLideN64/files/1507644/Legend.of.Zelda.The.-.Ocarina.of.Time.U.V1.2.st1.zip)

**Comment by gonetz** [comment]
Fixed: 37cc010e856
