### ISSUE TITLE
Custom Robo graphic glitch in WIP Builds 3

### ISSUE THREAD

**Issue by Bangaio65** [gonetz/GLideN64#1678]
Latest build posted here: https://github.com/gonetz/GLideN64/issues/1574

Project 64 2.3.2.3

GLideN64_41b0bffe (default settings) - objects sink on part of floor (N64-style depth compare doesn't make a difference)
Public Release 2.0 (default settings) - works correctly

![customrobo-glitch01](https://user-images.githubusercontent.com/34227483/33537037-f1d03b80-d897-11e7-8bf9-f7ad967e3932.png)

Savefile (story mode):
[custom robo.zip](https://github.com/gonetz/GLideN64/files/1525736/custom.robo.zip)

**Comment by rez-** [comment]
bad commit: 591eda8

**Comment by rez-** [comment]
fixed if you change:
```
"  if (uDepthSource == 1) gl_FragDepth = uPrimDepth;	\n"
"  else gl_FragDepth = clamp((gl_FragCoord.z * 2.0 - 1.0) * uDepthScale.s + uDepthScale.t, 0.0, 1.0);	\n"
```
back to:
`"  gl_FragDepth = clamp((gl_FragCoord.z * 2.0 - 1.0) * uDepthScale.s + uDepthScale.t, 0.0, 1.0);	\n"`
in src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramBuilder.cpp at line 1386

**Comment by rez-** [comment]
did some testing:
UDepthSource: 0.989176 gDP.primDepth.z = 0.978351
UDepthSource: 0.990001 gDP.primDepth.z = 0.980002
UDepthSource: 0.9878 gDP.primDepth.z = 0.975599
UDepthSource: 0.989176 gDP.primDepth.z = 0.978351
UDepthSource: 0.990001 gDP.primDepth.z = 0.980002
UDepthSource: 0.9878 gDP.primDepth.z = 0.975599
UDepthSource: 0.989176 gDP.primDepth.z = 0.978351
UDepthSource: 0.990001 gDP.primDepth.z = 0.980002
UDepthSource: 0.9878 gDP.primDepth.z = 0.975599
UDepthSource: 0.989176 gDP.primDepth.z = 0.978351
UDepthSource: 0.990001 gDP.primDepth.z = 0.980002
UDepthSource: 0.9878 gDP.primDepth.z = 0.975599
UDepthSource: 0.989176 gDP.primDepth.z = 0.978351
--
seems that the function UDepthSource::update() in  src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramUniformFactory.cpp is the culprit

**Comment by gonetz** [comment]
Do you log before of after uniform update?

**Comment by gonetz** [comment]
Fixed.

**Comment by rez-** [comment]
thanks gonetz! great work! :D
