### ISSUE TITLE
PJ64: End emulation in Full-screen mode is broken

### ISSUE THREAD

**Issue by bryc** [gonetz/GLideN64#1680]
I enabled "Start ROM fullscreen" in PJ64, and was hoping to use F12 to exit emulation and return to ROM list. Pressing F12 for "End emulation" while fullscreen in GLideN64 does not work properly. Game screen freezes, then pressing any key shows broken PJ64 window with no title-bar:

![image](https://user-images.githubusercontent.com/1408749/33666564-649e4c52-da68-11e7-8741-2f1da034ba07.png)

Upon loading a 2nd ROM in this state, again with "Start ROM fullscreen", GLideN64 fails to go fullscreen properly.

This occurs in both stable release **Public Release 2.0** and [latest WIP](https://github.com/gonetz/GLideN64/issues/1574#issuecomment-347005879), and occurs on both Win10 laptop (both integrated mode and NVIDIA high-performance GPU mode) and Win7 desktop. Also, using build of master git PJ64.

**Comment by gonetz** [comment]
@bryc Fixed. Test build:
https://drive.google.com/file/d/1JxgJXAuZleo-PNJ56NijNA5VMuZlm_18/view?usp=sharing

Please test.

**Comment by bryc** [comment]
### First: A bad configuration that **crashes** Windows 7 PC when enter full-screen mode.

```cfg
[video]
fullscreenWidth=0
fullscreenHeight=0
fullscreenRefresh=0
windowedWidth=640
windowedHeight=480
```

Not sure how these options were saved, I can't reproduce  :cry:. But it will instantly crash my PC and force restart if trying to go full-screen with these values. I was using old GLideN64.ini produced by WIP build in main post. Before it happened, I changed full-screen resolution from 1650 x 1050 (16:10) to 1920 x 1080 (16:9), and also pressed Restore Default. 

Also if helpful, I believe window mode changed to 320 x 240 by itself when it was 640 x 480 before. I did not do that (Possibly happened when choosing Restore Default).

**** 

Now actual tests of fix build: 

### Windows 10 Home

Title bar issue is fixed, and also the other issue with screen freeze is fixed. No longer see black screen or last frame of game after end emulation.

### Testing Windows 7 Ultimate

Title bar issue appears fixed, but remains one issue:

When press F12, emulation ends, but there is a black screen covering everything. Mouse is visible, and changes cursor to "resize" or "pointer" when moving mouse over things, but cannot see anything. 

When interacting with windows behind black overlay (right click, resize, ALT+Tab), some of the black overlay is erased when updating portion of screen.

Example: After testing I had black screen. I ALT+Tab to a Windows Explorer window, which erased some of the black overlay but kept some of it still. It cannot be captured in screenshot (Print screen). So I took this photo:

![image](https://user-images.githubusercontent.com/1408749/34012906-84bfe4d8-e0e3-11e7-9e2d-f65770e08cf1.png)

It is possibly some left over OpenGL rendering buffer that does not get screen cleared. When switch Full-screen to Window mode, no such problem occurs (Win7).

**Comment by gonetz** [comment]
Thanks!

Good that the problem is fixed at least for Win 10.

I don't have Windows 7 PC anymore to test. Thus, hopefully somebody else will find how to fix these issues.

Regarding wrong settings: if you will find scenario, how to get them, please let me know. I can't reproduce it. It must be some non-trivial sequence of settings changes, which causes such effect.

**Comment by bryc** [comment]
My ability with C/C++ is very limited so hopefully someone with Win7 can look at this.

 > Regarding wrong settings: if you will find scenario, how to get them, please let me know. I can't reproduce it. It must be some non-trivial sequence of settings changes, which causes such effect.

Will keep trying - is it possible to detect 0 0 0 values as unsupported mode and replace with default? At least that will prevent crash of PC.

**Comment by gonetz** [comment]
It is possible to detect 0 0 0 values, but why? You must not get these values if program works correct. If it works incorrect, then the bug must be fixed , not its consequences.

**Comment by gonetz** [comment]
Please reopen if problem still exists.
