### ISSUE TITLE
Pi 3: Speed Issues

### ISSUE THREAD

**Issue by steeeb** [gonetz/GLideN64#1682]
Hi Everyone.

I'm aware that the latest version is causing issues on the Pi 3 with missing textures.

As an aside - performance on the Pi 3 has massively dropped from 17th September to the latest working build that isn't missing textures (late November).

If anyone would like anything testing I am keen on getting the performance better on the Pi 3.

What is the best way for me to see where specific performance drops are happening? By disecting between 17th Sept and late Nov to see what is causing the performance issues?

Goldeneye 007 in particular suffers. In late November firing the gun makes it go crazy. In 17th Sept build it's mostly somewhat playable.

**Comment by fzurita** [comment]
Can you try building the branch in this pull request and check if it makes any performance difference?

https://github.com/gonetz/GLideN64/pull/1681

You may get some GLSL shader errors, in which case you wouldn't see anything, if you do get shader errors in the GLideN64.log file, can you post them here?

**Comment by steeeb** [comment]
Thanks. Built the PR will try and test it later. :)

**Comment by steeeb** [comment]
@fzurita 

UI-Console Error: dlopen('/opt/retropie/emulators/mupen64plus/lib/mupen64plus/mupen64plus-video-GLideN64.so') failed: /opt/vc/lib/libbrcmEGL.so: undefined symbol: glPointSizePointerOES
UI-Console Error: Specified Video plugin not found: mupen64plus-video-GLideN64.so
Core Status: Rom closed.

Get that error when trying to start a game with GLideN64 within Retropie on Raspberry Pi 3 using your pull request.

**Comment by fzurita** [comment]
Strange, that shouldn't have anything to do with my pull request. My pull request shouldn't have changed any dependencies. Do you get the same issue if you try to build and use the master branch?

**Comment by steeeb** [comment]
Trying that now :)

**Comment by steeeb** [comment]
Sorry, was using the older version of mupen64 from 7th September I previously mentioned.

I've tried it and it seems no worse compared to master (with a patch applied to fix the textures issue), to me I would say it's the same.

Goldeneye is now playable though on both master (with patch) and your pull request. It seems pretty much the same as the 17th September build I mentioned.

But it does look to work. Tried a few other games like Super Mario 64, but didn't compare to master. Super Mario 64 does work great.

**Comment by fzurita** [comment]
Ok, so compared to master(with patch), you see no difference in performance?

**Comment by steeeb** [comment]
Not on Goldeneye, no (which is the only game I've done a direct comparison on - since it has obvious slowdowns so is a good indicator).

**Comment by steeeb** [comment]
Those slowdowns could well be down to something else or could still be overbearing too much to make any smaller gains obvious though of course.

It's a good sign that it works fine though!

I can do more comparisons but not today. But it sounds like this is something that is in the right directions and should be merged in any case.

**Comment by steeeb** [comment]
There is definitely an improvement in Pokemon Stadium, which was another game that has slight slowdowns, it seems to play perfect on your PR.

**Comment by steeeb** [comment]
I've just tried the binary that Retropie currently uses from 30th Nov and Goldeneye is noticeably slower using that.

So there are definite improvements from then.

**Comment by fzurita** [comment]
Can you try disabling the speed limiter and enabling the FPS display? It would be good to see if there is a performance difference in any specific area of the game.

**Comment by steeeb** [comment]
This seems on par than it was months ago. So closing the ticket.
