### ISSUE TITLE
Turok 2: Seeds of Evil (and maybe other Iguana made games) - Object Dynamic Light Issue

### ISSUE THREAD

**Issue by CharuV2** [gonetz/GLideN64#1683]
Hello, I just want to thank everyone and the creator for making an amazing graphics plugin!

Anyways, the reason why I write this issue is because while there is certainly dynamic light in HLE for games that Iguana made, I've noticed (mainly Turok 2) that it doesn't apply to objects... somewhat. A great example of this are the opening logos, especially the Iguana logo where the character shoots. The iguana is suppose to light up along with the surrounding area, but it simply doesn't.

![hle](https://user-images.githubusercontent.com/34499615/33923936-bdce423a-dfa1-11e7-8d42-c9123ef1eb01.png)
HLE light

![lle](https://user-images.githubusercontent.com/34499615/33923948-cb71eb26-dfa1-11e7-8935-058428dc1f67.jpg)
LLE light

Another good example is the first area of Hive of the Mantis with the turrets. When they shoot, the actual turret should be lighting up too.

![hle](https://user-images.githubusercontent.com/34499615/33924155-b9035528-dfa2-11e7-9aa6-f20cd8a24928.png)
HLE light

![lle](https://user-images.githubusercontent.com/34499615/33924162-c04e0b16-dfa2-11e7-92e6-412cf88267ee.jpg)
LLE light

...Of course, the dynamic lights that are part of the map/level seem to apply to objects no problem. Good example of that is if you let the first demo play after the logos.

Anyways, once again, I'm happy this is being actively worked on, cheers!

**Comment by fzurita** [comment]
Which build are you using? The latest builds implemented lighting ucode for this game.

**Comment by CharuV2** [comment]
I should be using the current WIP build.

This has happened in previous builds prior too though! Even the build that introduced dynamic lighting to Iguana games! So I know it's not because the build I have at the moment is outdated or anything.

I think I should go more in detail exactly what the issue is with gifs with the turret I screenshotted.

There is dynamic light, don't get me wrong. You all did an amazing thing by emulating the dynamic lights in these games. However, it's just the objects (like explosive barrels, enemies, movable things, ect) that seem to not have ANY dynamic lighting applied to them.

![hle](https://user-images.githubusercontent.com/34499615/33957955-1bdcc4cc-e011-11e7-9619-24c51097f257.gif)
HLE

![lle](https://user-images.githubusercontent.com/34499615/33957966-20eefb7e-e011-11e7-88b7-764ee1d73a0a.gif)
LLE

**Comment by mudlord** [comment]
> The latest builds implemented lighting ucode for this game.

Seems then its incomplete.

**Comment by gonetz** [comment]
I see, thanks.

**Comment by olivieryuyu** [comment]
Oh oh we missed this...

**Comment by CharuV2** [comment]
Works like a charm, that was an amazingly fast fix!

Thanks!
