### ISSUE TITLE
Missing menu in last legion UX (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1687]
![sans titre](https://user-images.githubusercontent.com/8987490/34070180-32bee178-e261-11e7-8418-b75cf26c0082.jpg)

**Comment by gonetz** [comment]
Current WIP build, default settings, Project64 2.3:
![gliden64_lastlegion_ux_000](https://user-images.githubusercontent.com/8983092/34070671-9f409e64-e29c-11e7-989f-2839b1602d47.png)

**Comment by olivieryuyu** [comment]
it works ok with PJ64 but not with 1964 or Mupen 0.5.

Seems is odd.

**Comment by olivieryuyu** [comment]
on top there is a depth issue in the title

![sans titre](https://user-images.githubusercontent.com/8987490/34072548-9190eca0-e289-11e7-8092-203563db5855.jpg)

The yellow sign should be behind the text.

**Comment by loganmc10** [comment]
Looks ok in mupen64plus to me:

![lastlegion_ux-000](https://user-images.githubusercontent.com/848146/34072653-786fe17c-e248-11e7-9083-1ed892e5ac4e.png)
![lastlegion_ux-001](https://user-images.githubusercontent.com/848146/34072654-788d6120-e248-11e7-9382-1b740f2e56c9.png)

**Comment by olivieryuyu** [comment]
seems a bug from my side. Weird!
