### ISSUE TITLE
Project64 crashes with latest GlideN64 wip builds

### ISSUE THREAD

**Issue by dezraj** [gonetz/GLideN64#1689]
I am having a weird crash when using most recent wip builds such as 9da53626 and 01369668. It happens with Mario Kart 64 (US) and the Kerber's texture pack. I load the game, enter fullscreen, play a session and when I exit fullscreen, end emulation (F12 key) and close the emu by clicking in the "X", Windows will show a prompt telling me that Project64 stopped working, so I have to click on the "close program" to close it. Then if I run Project64 again and load the same game now the emu will show nothing after "emulation started", I just see a 0 FPS and a black screen. If I close the emu, the project64.exe process this time will not be stopped nor Windows will show me a prompt to force close the program. So I have to end the process in the task manager. Here's a video of the problem happening:

https://www.youtube.com/watch?v=bOuUbscO9lw

I suppose the issue is caused by this weird crash. If the emulator crashes, it seems something is corrupted within Project64 settings, to the point that I can't even set up the same plugin again. So I have to use an older wip build that does not crash the emu in this very same scenario (to create "good settings" in the emu perhaps) before I can move to the most recent wip build again (to reproduce the problem).

My setup:
e8400
gtx 285
Win 7 sp1 x64
Project64 2.3.2.3

By the way, I see a little difference starting from build 9da53626 in the Mario Kart home screen. Before there was a line crossing the "1996 Nintendo", now this line is gone, take a look:

![mario kart 64 line](https://user-images.githubusercontent.com/27839354/34126598-499ec8c4-e421-11e7-913a-f052bd4b8716.jpg)

![mario kart 64 no line](https://user-images.githubusercontent.com/27839354/34126632-6b850aa2-e421-11e7-816b-589c1f7fbf59.jpg)

Thank you in advance for any help.

**Comment by gonetz** [comment]
Video is not available.

I already have complain that plugin does not exit correctly on Windows7. Unfortunately, I don't have Win7 configuration to test and fix it.

You said that older WIP bilds work more correct. Could you say, when the problem started? I need latest "good" commit and oldest "bad" one. Commit checksum is in the name of archives with WIP bulds and in the name of the plugin, you may see it in plugin selection dialog.

**Comment by dezraj** [comment]
Thanks for you reply Gonetz. The video is available now, you check it out.

So I did some testing with the latest builds to pinpoint when the crash started to happen.

How I did my testing:

- I set Project64 to the default Jabo's Direct3D8 plugin;
- I erase GlideN64.custom.ini, GlideN64.dll and GlideN64.ini files from the Project64's GFX plugin folder;
- I copy the new plugin files GlideN64.custom.ini and GlideN64.dll to Project64's GFX plugin folder;
- I run the emulator, choose the plugin, set the plugin graphic options as exactly as I do in the video, run Mario Kart 64;
- I enter fullscreen, exit fullscreen, end emulation (F12 key), close the emu (the "X" in the top right corner);

Here are my results so far:

02ec742 - works without issue. I notice that the textures pack loads really fast in this build.
42d65694 - sometimes works without issues, sometimes Project64 will show an error when I close it and the process is not killed, so I have to kill it in the task manager. When the textures pack loads really fast, I have no problems when closing the emu. But when the textures pack loads by going through all the textures files (as if it was the first time the plugin loaded this textures pack, just as we see in the video), Project64 will show an error when I close it and so I need to kill the process myself.
41b0bffe - same as above.
9da53626 - Crash is consistent. The textures pack always loads by going through all the textures files, as if it was the first time ever the plugin loaded this textures pack.
01369668 - same as above.

I hope this can help you to invesgate the cause. Thank you again for your time. ;)

**Comment by gonetz** [comment]
@dezraj 

Thanks for the info.
I have a feeling that the problem can be related to QT version and / or compiler version.

Please download this archive:
https://drive.google.com/file/d/14ll5yYM0hE2l_0WcQuDaPvHPdYGYPht5/view?usp=sharing

Inside you will find 3 builds of the current master code. 2 builds made with Visual Studio 2013, but with different version of QT: 5.4 and 5.7 The third build made with Visual Studio 2015 and QT 5.7

Please test all three versions and tell me if there is any difference between them on your system.

**Comment by dezraj** [comment]
Thanks for your reply Gonetz. For my tests below I used the same process as described in my previous post. Here are my results:

- GLideN64_d8418540_vs2013_qt5_4 - just as with the latest wip build, crash is consistent with this version. The textures pack always loads by going through all the textures files, as if it was the first time ever the plugin loaded this textures pack.
- GLideN64_d8418540_vs2013_qt5_7 - With this version I could never make the game to show in the screen, that is, I always have a 0 FPS and a black screen. In this build the textures pack does not go through all the textures files.
- GLideN64_d8418540_vs2015_qt5_7 - same results as with vs2013_qt5_4.

Interesting is that after these tests I tried to return to wip build 02ec742, which I thought worked without issues, but now I'm having the same results as with the latest build.

So I tried one wip build before, 365838e, and now this is working fine. I saw in this build the very same behavior I had with 02ec742, that is, textures are loaded really fast (the plugin doesn't go through all the texture files, as we see in the video for the latest builds).

To finish my testing I tried going back to build 02ec742 one more time and now it started working fine again. So it seems like build 365838e "cleaned" something in the emulator so that it could work again.

I suppose the issue is related to this loading of all the textures, or anything that triggers that.

Thank you so much again for your time!

**Comment by gonetz** [comment]
> The textures pack always loads by going through all the textures files, as if it was the first time ever the plugin loaded this textures pack.

This means only one thing: texture cache did not saved properly on disk. That is .htc file is not created or created with errors. You need to run debug build to find why. Debug version of GLideNHQ makes detailed log of its work. Here the debug build:
https://drive.google.com/file/d/1UqjStCo8LieeFzkahZHfuSKWXbe8VWvX/view?usp=sharing

Run it with hires texture packs enabled. If .htc file is not found, plugin will look for hires textures in Plugin/hires_texture folder (if you did not change it in settings). 
glidenhq.dbg will be created in emulator's folder.
On the first run it should look like this:
```
	------------------------------------------------------------------
0:	 GLideNHQ version 1.00.00.13480
0:	 Copyright (C) 2010  Hiroshi Morii   All Rights Reserved
0:	    email   : koolsmoky(at)users.sourceforge.net
0:	    website : http://www.3dfxzone.it/koolsmoky
0:	
0:	 GLideN64 GitHub : https://github.com/gonetz/GLideN64
0:	------------------------------------------------------------------
80:	Number of processors : 8
80:	Number of processors : 8
80:	Number of processors : 8
80:	gzfp:0 file:MARIOKART64_MEMORYCACHE.htc
80:	Number of processors : 8
80:	gzfp:0 file:MARIOKART64_HIRESTEXTURES.htc
80:	-----
80:	using Rice hires texture format...
80:	  must be one of the following;
80:	    1) *_rgb.png + *_a.png
80:	    2) *_all.png
80:	    3) *_ciByRGBA.png
80:	    4) *_allciByRGBA.png
80:	    5) *_ci.bmp
80:	  usage of only 2) and 3) highly recommended!
80:	  folder names must be in US-ASCII characters!
80:	-----
80:	path: C:/Games/N64/Plugin/hires_texture/MARIOKART64
80:	-----
80:	path: C:/Games/N64/Plugin/hires_texture/MARIOKART64/Animals+Creatures
80:	-----
80:	file: MARIOKART64#06E8FF38#2#1#7833AA9C_ciByRGBA.png
80:	rom: MARIOKART64 chksum:06E8FF38 7833AA9C fmt:2 size:1
80:	png format 128 x 256 bitdepth:8 color:6 interlace:0 compression:0 filter:0
80:	read in as 0 x 0 gfmt:0
80:	required alpha bits:8 zero acomp texels:2024 rgb as intensity:0
80:	best gfmt:8058
80:	zlib compressed: 131.07kb->33.56kb
80:	[    1] added!! crc:7833AA9C 06E8FF38 128 x 256 gfmt:8058 total:0.00mb
80:	texture loaded!
80:	-----

....

80:	gzfp:1cf9e150 file:MARIOKART64_HIRESTEXTURES.htc

```

On the second run, when MARIOKART64_HIRESTEXTURES.htc is created, log looks like this:

```
0:	------------------------------------------------------------------
0:	 GLideNHQ version 1.00.00.13480
0:	 Copyright (C) 2010  Hiroshi Morii   All Rights Reserved
0:	    email   : koolsmoky(at)users.sourceforge.net
0:	    website : http://www.3dfxzone.it/koolsmoky
0:	
0:	 GLideN64 GitHub : https://github.com/gonetz/GLideN64
0:	------------------------------------------------------------------
80:	Number of processors : 8
80:	Number of processors : 8
80:	Number of processors : 8
80:	gzfp:0 file:MARIOKART64_MEMORYCACHE.htc
80:	Number of processors : 8
80:	gzfp:c892bb0 file:MARIOKART64_HIRESTEXTURES.htc
80:	[    1] added!! crc:00000000 0031696B 128 x 128 gfmt:8058 total:0.00mb
80:	[    2] added!! crc:00000000 006ABAAB 256 x 128 gfmt:8058 total:0.04mb
...
80:	[  671] added!! crc:FF791FDC 2D9B3009 256 x 128 gfmt:8058 total:13.42mb
80:	hirestex: r_crc64:00000000 F6024169, g64crc:00000000 C9837047
80:	zlib decompressed: 20.12kb->65.54kb
80:	hires hit: 128 x 128 gfmt:8058
80:	hirestex: r_crc64:00000000 F6024169, g64crc:00000000 C9837047
80:	zlib decompressed: 20.12kb->65.54kb
80:	hires hit: 128 x 128 gfmt:8058
....

```

**Comment by gonetz** [comment]
Please reopen if problem still exists
