### ISSUE TITLE
Pilotwings: wrong horizon, missing polygons

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#169]
![pilotwings1](https://cloud.githubusercontent.com/assets/8987490/5331543/b3626c30-7e2f-11e4-9d0a-be6edf6ca3af.jpg)
![sdfzzzz](https://cloud.githubusercontent.com/assets/8987490/5331547/cde38f08-7e2f-11e4-99d1-af0bb9fd2530.jpg)

Please use cheats to access all levels. Everfrost level is a good example.

**Comment by gonetz** [comment]
Hopefully fixed

**Comment by olivieryuyu** [comment]
fixed
