### ISSUE TITLE
Option to disable bilinear filtering

### ISSUE THREAD

**Issue by Alien-Grey** [gonetz/GLideN64#1691]
Is it possible to add an option to disable bilinear filtering?
The image looks too blur on a small high resolution screen.

**Comment by gonetz** [comment]
It is possible.
I will not touch texture filtering until new Public Release.
After that texture filtering options can be discussed.

**Comment by oddMLan** [comment]
#2088 is a duplicate of this, but has more detailed information and the intent is clearer. I suggest closing this ticket.

**Comment by gonetz** [comment]
Ok, closed in favor of #2088
