### ISSUE TITLE
Outlines on 2d objects in Kirby 64: The Crystal Shards

### ISSUE THREAD

**Issue by delta7890** [gonetz/GLideN64#1695]
See attached pics, played on Mupen64plus:
![kirby64-000](https://user-images.githubusercontent.com/34465681/34369824-33dad452-ea8d-11e7-95a4-f12910bc6262.png)
![kirby64-001](https://user-images.githubusercontent.com/34465681/34369825-35dcd5f2-ea8d-11e7-9967-7599836fe0c1.png)
![kirby64-002](https://user-images.githubusercontent.com/34465681/34369826-37ec631c-ea8d-11e7-991e-fa48c358e705.png)

Said outlines do not appear using the angrylion plugin.

**Comment by gonetz** [comment]
> Said outlines do not appear using the angrylion plugin.

Usually such outlines do not appear with GLideN64 too when it works in native resolution.

**Comment by delta7890** [comment]
Interesting.  Not sure which graphics options to change to force native resolution.

**Comment by loganmc10** [comment]
The option is ```UseNativeResolutionFactor``` in mupen64plus, set that to 1 for native resolution

**Comment by delta7890** [comment]
Hm...are there other options that need to be changed as well?  Outlines are still visible even in native resolution.
![kirby64-003](https://user-images.githubusercontent.com/34465681/34532669-fbe48482-f084-11e7-8240-a20af8bc1040.png)

**Comment by oddMLan** [comment]
"fixed" by enabling color bleeding. correct solution would require programmable blending, which is not possible in opengl

**Comment by oddMLan** [comment]
Do you think it halos removal should be added to custom ini for this game? @gonetz

**Comment by gonetz** [comment]
Yes, I forgot about it.
