### ISSUE TITLE
Invisible pill in Dr Mario

### ISSUE THREAD

**Issue by phrone** [gonetz/GLideN64#1698]
Every sprite on the screen looks correct, but when Dr Mario throws a pill, it doesn't appear until it's landed on another object. This doesn't happen in Glide64. Is this a bug or a configuration thing?
I'm using mupen64plus. Here is my plugin config:

[Video-GLideN64]

# Settings version. Don't touch it.
configVersion = 20
# Crop resulted image (0=disable, 1=auto crop, 2=user defined crop)
CropMode = 0
# Crop width pixels from left and right of resulted image (in native resolution)
CropWidth = 0
# Crop height pixels from top and bottom of resulted image (in native resolution)
CropHeight = 0
# Enable/Disable MultiSampling (0=off, 2,4,8,16=quality)
MultiSampling = 8
# Screen aspect ratio (0=stretch, 1=force 4:3, 2=force 16:9, 3=adjust)
AspectRatio = 1
# Swap frame buffers (0=On VI update call, 1=On VI origin change, 2=On buffer update)
BufferSwapMode = 0
# Frame buffer size is the factor of N64 native resolution.
UseNativeResolutionFactor = 0
# Bilinear filtering mode (0=N64 3point, 1=standard)
bilinearMode = True
# Max level of Anisotropic Filtering, 0 for off
MaxAnisotropy = 1
# Enable color noise emulation.
EnableNoise = True
# Enable LOD emulation.
EnableLOD = True
# Enable hardware per-pixel lighting.
EnableHWLighting = False
# Use persistent storage for compiled shaders.
EnableShadersStorage = True
# Make texrect coordinates continuous to avoid black lines between them. (0=Off, 1=Auto, 2=Force)
CorrectTexrectCoords = 0
# Render 2D texrects in native resolution to fix misalignment between parts of 2D image.
EnableNativeResTexrects = False
# Do not use shaders to emulate N64 blending modes. Works faster on slow GPU. Can cause glitches.
EnableLegacyBlending = False
# Enable writing of fragment depth. Some mobile GPUs do not support it, thus it made optional. Leave enabled.
EnableFragmentDepthWrite = True
# Use GLideN64 per-game settings.
EnableCustomSettings = True
# Enable frame and|or depth buffer emulation.
EnableFBEmulation = True
# Copy auxiliary buffers to RDRAM
EnableCopyAuxiliaryToRDRAM = False
# Enable N64 depth compare instead of OpenGL standard one. Experimental.
EnableN64DepthCompare = False
# Disable buffers read/write with FBInfo. Use for games, which do not work with FBInfo.
DisableFBInfo = True
# Read color buffer by 4kb chunks (strict follow to FBRead specification)
FBInfoReadColorChunk = False
# Read depth buffer by 4kb chunks (strict follow to FBRead specification)
FBInfoReadDepthChunk = True
# Enable color buffer copy to RDRAM (0=do not copy, 1=copy in sync mode, 2=copy in async mode)
EnableCopyColorToRDRAM = 2
# Enable depth buffer copy to RDRAM  (0=do not copy, 1=copy from video memory, 2=use software render)
EnableCopyDepthToRDRAM = 2
# Enable color buffer copy from RDRAM.
EnableCopyColorFromRDRAM = False
# Texture filter (0=none, 1=Smooth filtering 1, 2=Smooth filtering 2, 3=Smooth filtering 3, 4=Smooth filtering 4, 5=Sharp filtering 1, 6=Sharp filtering 2)
txFilterMode = 0
# Texture Enhancement (0=none, 1=store as is, 2=X2, 3=X2SAI, 4=HQ2X, 5=HQ2XS, 6=LQ2X, 7=LQ2XS, 8=HQ4X, 9=2xBRZ, 10=3xBRZ, 11=4xBRZ, 12=5xBRZ), 13=6xBRZ
txEnhancementMode = 0
# Deposterize texture before enhancement.
txDeposterize = False
# Don't filter background textures.
txFilterIgnoreBG = False
# Size of filtered textures cache in megabytes.
txCacheSize = 100
# Use high-resolution texture packs if available.
txHiresEnable = True
# Allow to use alpha channel of high-res texture fully.
txHiresFullAlphaChannel = True
# Use alternative method of paletted textures CRC calculation.
txHresAltCRC = False
# Enable dump of loaded N64 textures.
txDump = True
# Zip textures cache.
txCacheCompression = True
# Force use 16bit texture formats for HD textures.
txForce16bpp = False
# Save texture cache to hard disk.
txSaveCache = True
# Path to folder with hi-res texture packs.
txPath = "C:/Users/xx/AppData/Roaming/Mupen64Plus/hires_texture"
# Path to folder where plugin saves texture cache files.
txCachePath = "C:/Users/xx/AppData/Roaming/Mupen64Plus/cache"
# Path to folder where plugin saves dumped textures.
txDumpPath = "C:/Users/xx/AppData/Roaming/Mupen64Plus/texture_dump"
# File name of True Type Font for text messages.
fontName = "arial.ttf"
# Font size.
fontSize = 18
# Font color in RGB format.
fontColor = "B5E61D"
# Force gamma correction.
ForceGammaCorrection = False
# Gamma correction level.
GammaCorrectionLevel = 2
# Show FPS counter.
ShowFPS = True
# Show VI/S counter.
ShowVIS = False
# Show percent counter.
ShowPercent = False
# Counters position (1=top left, 2=top center, 4=top right, 8=bottom left, 16=bottom center, 32=bottom right)
CountersPos = 8

**Comment by loganmc10** [comment]
You need GLideN64.custom.ini 

EnableCopyColorFromRDRAM needs to be enabled for this game, the GLideN64.custom.ini file will do that

**Comment by phrone** [comment]
@loganmc10 You are correct, changing the EnableCopyColorFromRDRAM to True fixed the problem. However, I don't think the GLideN64.custom.ini and GLideN64.ini do anything to help. I've tried placing them both in the emulator's folder, and the one in appdata/roaming/mupen64plus (i'm using windows). Also, it seems to me that the setting names in the emulator cfg file are different than those in the plugin ini files. For example, EnableCopyColorFromRDRAM appears as frameBufferEmulation\copyFromRDRAM. Is this intentional?

**Comment by loganmc10** [comment]
GLideN64.custom.ini needs to go in the same folder as mupen64plus.ini, GLideN64.ini won't do anything

The naming differences are intentional

**Comment by Jj0YzL5nvJ** [comment]
By the way, I did neither get the *.ini files working in Linux. Where these supposed to be placed for a local user in Linux?

**Comment by loganmc10** [comment]
mupen64plus looks for ini files in the "Data Dir" path, you can set this when you launch mupen64plus-ui-console with the ```--datadir``` option. 

If this option is not set, mupen64plus will look in /usr/local/share/mupen64plus, /usr/share/mupen64plus, and your current directory.

**Comment by phrone** [comment]
Thanks for your quick replies, logan! (Windows) I specified the data dir, turned on verbose mode, and there is no indication that the plugin ini files are taken into account. The individual EnableCopyColorFromRDRAM setting doesn't seem to be overriden when I launch Dr Mario.

**Comment by loganmc10** [comment]
It's hard for me to say what the issue could be, its just not finding the ini files. You can take a look at https://m64p.github.io

That is mupen64plus bundled with the latest GLideN64. It includes the GLideN64.custom.ini file, and if you launch mupen64plus-gui.exe and open Dr. Mario, you'll see that it automatically reads all the settings it needs.

It could be so many things, maybe you need quotations around the path you are specifying, it's really hard to say...

**Comment by phrone** [comment]
Right, I tried the bundle and it works fine through the GUI, but I wonder why it doesn't do the same with the command-line executable. I tried with and without quotations, although that shouldn't matter, as the path I'm giving it doesn't include spaces. Should we close the issue or are you interested in getting to the bottom of the problem? We are kinda out of the initial scope of the question.

**Comment by loganmc10** [comment]
Well it's definitely not an issues with GLideN64, so yes this issue should be closed. I'm not really sure what I could do to get to the bottom of the problem though

**Comment by phrone** [comment]
You're right, maybe I should seek some opinions in the mupen tracker. Thank you for your assistance!
