### ISSUE TITLE
Disabling mipmapping breaks texture filtering for mipmapped textures.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#1699]
This seems to be a fairly recent regression. This is latest build on Mupen64plus.
Off:
![conker_bfd-009](https://user-images.githubusercontent.com/10704701/34462280-d98477f8-ee8b-11e7-8372-671e8e59de2e.png)
On:
![conker_bfd-010](https://user-images.githubusercontent.com/10704701/34462281-d9c03f4a-ee8b-11e7-823d-6a4ed8247bbb.png)
Affects Perfect Dark, too, and probably others.

**Comment by fzurita** [comment]
It doesn't happen with GLES.

**Comment by gonetz** [comment]
Fixed.
