### ISSUE TITLE
Fullscreen with framebuffer disabled doesn't work

### ISSUE THREAD

**Issue by Craftyawesome** [gonetz/GLideN64#1700]
It seems to show the game at the top half only? Only settings changed from default was 1920x1080, 60hz, and vsync. Tested on project 64 and bizhawk.

**Comment by fzurita** [comment]
Try enabling the gamma correction shader and set it to 1.0. For some reason that fixes it in Android.

**Comment by Craftyawesome** [comment]
Did not work.

**Comment by gonetz** [comment]
Fixed
