### ISSUE TITLE
WS issues with F-Zero X

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1701]
![image](https://user-images.githubusercontent.com/9299743/34464989-2384e6aa-ee4e-11e7-8544-a602671ab548.png)

This looks like the same issue we had with Star Wars Rouge Squadron

Has there been any efforts to try and find a more balanced solution for the WS hacks?

**Comment by gamemasterplc** [comment]
that game sets a polygon for the background which is insufficiently sized for widescreen dependent on the internal FOV setting and so needs a vert- and zoom out to work right. A code that has widescreen without background glitches is below.

F-Zero X NTSC-U:
81082A94 3C1B
81082A96 43D5
81082AA0 AFBB
810D5284 42C8
810D5310 42C8
810D5340 4305

**Comment by theboy181** [comment]
Actually resolved this issue with retroben this today. BTW the 64dd version works with the WS hack.

**Comment by gamemasterplc** [comment]
post the code here that fixes the issue. also he might want to have a toggle for vert- widescreen hack
