### ISSUE TITLE
Majora's Mask - flashback cutscene glitched

### ISSUE THREAD

**Issue by Nerrel** [gonetz/GLideN64#1702]
This problem has occurred in every release of GlideN64 I've used, even predating the 2.0 release, but I did not see an open issue for it.  

There is a flashback near the beginning of the game where Zelda gives Link the ocarina of time.  It's in black and white and seems to have the framebuffer blur effect in heavy use along with a grain filter of sorts.  In past versions, the scene would not render at all and there would only be a black image, but text and 2D elements would still display.

In the current release, things are improved and the 3D objects are visible, but heavily glitched.  Textures and portions of models flicker in and out of visibility, and the black widescreen bars don't show up.  

https://c1.staticflickr.com/5/4593/38797285084_10ca0732ac_c.jpg
https://c1.staticflickr.com/5/4643/24637828057_60a1c9b8c1_c.jpg

It does not seem to matter what settings I use... aside from setting the aspect ratio to "try to fit" and using a higher resolution, the settings are at default.  If it helps, I can upload a savestate from just before the scene takes place later when I get time.

**Comment by gonetz** [comment]
It is a problem on your side. This cut scene worked with 2.0 release and it works with the current one:
![gliden64_zelda_majora s_mask_000](https://user-images.githubusercontent.com/8983092/34597438-37e921dc-f219-11e7-9f28-bd995505624a.png)

No special settings needed. Note: the game may not work correctly if you use hacked rom. Plugin uses some hacks to emulate this game, and these hacks enabled if internal name of the rom is ZELDA_MAJORA'S_MASK. Also, be sure that you run the game in HLE mode. Frame buffer emulation work incorrect in LLE for this game.

**Comment by fzurita** [comment]
@Nerrel can you post a save state?

**Comment by gonetz** [comment]
@fzurita PJ64 save:
https://drive.google.com/file/d/1sBMU7VJV9J3C5U-5PRCz0dlV7lDWYKuA/view?usp=sharing

**Comment by fzurita** [comment]
In Android, this scene is very glitched. Much worse than what @Nerrel is showing. I can take a look.

**Comment by Nerrel** [comment]
I'm unable to get the scene to work... the rom (USA version) isn't hacked, and I've always used HLE.  I also tried setting everything to default, like the aspect ratio and resolution, just in case.  Anything else I can try?

**Comment by fzurita** [comment]
Is this scene using the monochrome effect hack?

**Comment by loganmc10** [comment]
@fzurita can you provide a mupen64plus save state?

**Comment by AmbientMalice** [comment]
@loganmc10 Isn't this the game's opening scene?

**Comment by fzurita** [comment]
Here you go:

[majora_broken_cutdcene.zip](https://github.com/gonetz/GLideN64/files/1608330/majora_broken_cutdcene.zip)

**Comment by Nerrel** [comment]
@AmbientMalice no, this scene is played after getting the ocarina back from skull kid after the first three day cycle ends.

**Comment by gonetz** [comment]
> Is this scene using the monochrome effect hack?

Yes

**Comment by loganmc10** [comment]
@fzurita for some reason I can't load that save state, it just says "failed to load"

**Comment by fzurita** [comment]
Did you extract it?

**Comment by loganmc10** [comment]
Yeah it was a .sav file inside

**Comment by fzurita** [comment]
Also, it's for the USA version of the game. And in case you are curious, I was able to load the pj64 save state directly from mupen64plus as well.

The .sav file is the right file to load.

**Comment by fzurita** [comment]
Maybe the file become corrupt somehow, here it is again:
[majora_broken_cutscene.zip](https://github.com/gonetz/GLideN64/files/1608969/majora_broken_cutscene.zip)

**Comment by loganmc10** [comment]
Oh ok, anyway the PJ64 save state worked for me in mupen64plus, it looks normal to me in Linux:

![zelda_majora s_mask-000](https://user-images.githubusercontent.com/848146/34641519-df3f66a4-f2c2-11e7-883d-8b1e0deedec5.png)

**Comment by fzurita** [comment]
There seem to be done driver issues causing problems. I'm not sure what is special about the monochrome hack. I don't see any GL errors being generated.

**Comment by gonetz** [comment]
There is nothing special about the monohrome hack in glsl. It is just a standard dot product. It may not work with GLES 2 though - looks like I forgot to add necessary code to GL ES 2 texture read shader.

**Comment by gonetz** [comment]
It can be a problem with colorNoiseDither or alphaNoiseDither.
@fzurita could you run this scene with noise disabled?

**Comment by fzurita** [comment]
I did already try that and it didn't help.

**Comment by fzurita** [comment]
Here is what it looks like in Android. Maybe it's some kind of depth issue:

![zelda_majora s_mask-000](https://user-images.githubusercontent.com/11581687/34649354-8b979076-f37b-11e7-85aa-27040304322d.png)

**Comment by gonetz** [comment]
Depth issue? Hardly. As I remember, this scene works as this:

Render 3D objects, copy result to an auxiliary buffer. Render text
Render 3D objects, blend with aux buffer, copy result to an auxiliary buffer. Render text.
Render 3D objects, blend with aux buffer, copy result to an auxiliary buffer. Render text.
...

Copy to aux buffer is necessary to have motion blur for 3D objects only, not for text. Aux buffer blended with main buffer as texture, no depth info used. It may not work only if buffer does not have alpha channel: zelda monochrome hack set alpha to zero. Thus, buffer must have 32bit RGBA format. If it is not so on Android for some reason, the effect will not work.

**Comment by fzurita** [comment]
Gotcha, as far as I know, 32 bit RGBA is being used.

Thanks for laying it out, that's a good hint to help investigate the issue.

**Comment by Nerrel** [comment]
I should add that I'm experiencing this issue on Windows 10 x64 using Nvidia (GTX970).

**Comment by gonetz** [comment]
> I should add that I'm experiencing this issue on Windows 10 x64 using Nvidia (GTX970).

It should work perfectly fine with this configuration. Could you look for GLideN64.log file in Plugin folder? It may contain error messages.

**Comment by fzurita** [comment]
@gonetz I seem to be stuck, in Android, the blending does not seem to be working well. The old image seems to be retained forever.

I can see that ```FrameBuffer::getTexture``` is getting called. Is this where we are grabbing the texture to blend? Where is the blending actually happening?

**Comment by Nerrel** [comment]
I have these errors repeating over and over in the log (506 is the most common):
OpenGL Error: invalid value (501)
Stream error while loading shader cache! Buffer is probably not big enough
OpenGL Error: out of memory (505)
OpenGL Error: 506
OpenGL Error: invalid operation (502)

I tried clearing the log then restarting pj64 and reloading the savestate to see if I could limit the errors to just that scene, but nothing appears.

**Comment by loganmc10** [comment]
Maybe this scene is somehow using a large amount of video memory? Android devices typically have low memory compared to desktops, could be one explanation, although I'm not sure about @Nerrel's PC, or if there is a tool to monitor GPU memory usage in Windows

**Comment by gonetz** [comment]
> Maybe this scene is somehow using a large amount of video memory?

No, it should not. It uses one additional full screen buffer. It is not a problem for PC GPUs.

@fzurita Could you try to disable the monochrome hack for this game in code and run again?

**Comment by fzurita** [comment]
Here is what it looks like with the back disabled:

![zelda_majora s_mask-000](https://user-images.githubusercontent.com/11581687/34721379-7d84cd28-f510-11e7-90f8-c3907404ede1.png)

Either way, I can't get the 3d geometry to ever show up.

**Comment by fzurita** [comment]
Also, it shows up correctly in my PC. I have a GTX 980.

**Comment by fzurita** [comment]
From what can tell, it seems to me that the auxiliary buffer is never getting any geometry rendered into it.

**Comment by gonetz** [comment]
Auxiliary buffer is just a copy of main buffer. If that copy never happen, need to find why. I have no idea. Similar code used in intro with spinning mask.

**Comment by fzurita** [comment]
@gonetz At this point, I think there is something wrong with the blending of FBOs. Only one of the buffers is shown, which I think is the one where monochrome effect is being rendered. The one with the monochrome effect is supposed to be fully transparent?

Am I completely mis-understanding how the effect works?

**Comment by Nerrel** [comment]
I decided to try the scene using Mupen64plus (I've been using the newest Project64) and it seems to work just fine there:
https://c1.staticflickr.com/5/4700/28083596059_72728f58fe_o.jpg

I don't know if that means that the problem is specific to PJ64 itself, or if it could be an issue with the zilmar-specs version of GlideN64; the fact that the scene also has problems on Android would suggest that it's still an issue with the plugin. Either way, I hope that helps.

**Comment by Nerrel** [comment]
I wanted to ask again if those results above mean this is a Project64 issue and not a GlideN64 problem; if so, I can take the issue to P64's github instead.  Thanks again for the help

**Comment by fzurita** [comment]
It's not a project 64 issue. I have the exact same issue in an Nvidia Shield TV in full GL mode with mupen64plus-ae. The glitches look identical to your screenshots.

**Comment by loganmc10** [comment]
I can reproduce this in VMware Mesa but not on a regular laptop with Mesa.

The last time I ran into an issue like this was here: https://github.com/gonetz/GLideN64/pull/1503

It was a memory initialization issue, not a GPU issue. Different platforms handle memory differently it seems.

**Comment by loganmc10** [comment]
I would look for variables related to monochrome behaviour that don't have their value explicitly set

**Comment by loganmc10** [comment]
@Nerrel can you try the latest WIP build located here: https://drive.google.com/file/d/1YjBzzUZ7dT3WVh7a4VEf-ozJXY6j0Xz-/view?usp=sharing I believe your issue should be fixed in this build

**Comment by Nerrel** [comment]
Fixed indeed!  Thank you so much.   I'll close this if there's nothing more to be done here.  
![Test result](https://c1.staticflickr.com/1/788/41465036052_9da6881134_z.jpg)

**Comment by fzurita** [comment]
Not yet

**Comment by loganmc10** [comment]
I submitted this PR to fix this same issue on mobile devices: https://github.com/gonetz/GLideN64/pull/1798

**Comment by Nerrel** [comment]
So I can close this issue then? 

Also, in a different area of the game that WIP build above had a fairly bad glitch not present in the last builds in which solid objects became transparent.  Should I open an issue, or was that a rough build where regressions like that might be expected?

**Comment by fzurita** [comment]
Please make a new issue and can you also post a save state in the be issue?

**Comment by fzurita** [comment]
This issue should also be closed.

**Comment by Nerrel** [comment]
Sure thing, thanks.
