### ISSUE TITLE
Harvest Moon 64 black screen with FBE enabled

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1703]
Harvest Moon 64 seems to currently be showing a black screen when frame buffer emulation is enabled.

**Comment by loganmc10** [comment]
I just tested on Linux and it looked fine to me, but this machine doesn't support OGL 4.3/image textures. I think Harvest Moon has N64 Depth Compare on in GLideN64.custom.ini, so my machine won't enable that, perhaps that has something to do with it, some issue with N64 Depth Compare?

**Comment by fzurita** [comment]
Yep, that would do it. GLES doesn't work with N64 depth compare, so when it's forced to on, it causes a black screen.
