### ISSUE TITLE
Flickering has returned in Gauntlet Legends

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1705]
As noted here:

https://github.com/gonetz/GLideN64/pull/1623#issuecomment-355864674

Flickering has returned in Gauntlet Legends. However it's not the whole screen going black, just certain elements.

I bisected the issue to this commit: https://github.com/gonetz/GLideN64/commit/732c27a07d285b6de6b2ed8ff6ea56e34b778cfb

**Comment by fzurita** [comment]
I can confirm this.

**Comment by fzurita** [comment]
Ok, I see how it could had broke it. It removed this statement from ```DisplayWindow::swapBuffers()```

```
gDP.otherMode.l = 0;
```

Was that the correct thing to do?

**Comment by fzurita** [comment]
This can't be the issue. I put back the ```gDP.otherMode.l = 0;``` in ```DisplayWindow::swapBuffers()``` and it didn't fix it.

**Comment by gonetz** [comment]
Please test commit, which adds WDC. Gilles removed Gauntlet related hack in it.

**Comment by fzurita** [comment]
That's the one I used to test.

**Comment by gonetz** [comment]
Does gauntlet flicker if you build from state before WDC added?

**Comment by fzurita** [comment]
According to the original pull request, it broke more than a month ago. I'll try to find the offending commit soon.

**Comment by loganmc10** [comment]
I posted the offending commit in the original post  (https://github.com/gonetz/GLideN64/commit/732c27a07d285b6de6b2ed8ff6ea56e34b778cfb) someone could verify that though.

The flickering is different, I don't think it's related to the original flickering. Now only certain elements flicker (turn black), not the whole screen.

The changes to WDC won't have made any difference. All that changed was @Gillou68310 removed the check for Gauntlet Legends in the code that fixed the flickering. Before, it only applied to Gauntlet Legends, now it's not game specific (although in practice only Gauntlet Legends makes use of it), so the behaviour shouldn't have changed.

**Comment by fzurita** [comment]
@loganmc10 I tried reverting that commit and it didn't fix the problem.

**Comment by loganmc10** [comment]
Did you revert the commit or just add ```gDP.otherMode.l = 0;``` back in?

You forgot

```
if ((config.generalEmulation.hacks & hack_doNotResetOtherModeH) == 0)
	gDP.otherMode.h = 0x0CFF;
```

That checks that the hack is not applied, so it is applied for every game except Quake 2

**Comment by loganmc10** [comment]
And it used to do ```gDPSetTextureLUT(G_TT_NONE);``` and now it doesn't as well

**Comment by fzurita** [comment]
Duh, thanks, I read the code incorrectly. I'll test again.
