### ISSUE TITLE
Destruction Derby 64 (U) Multi Player View Port issues

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1707]
![image](https://user-images.githubusercontent.com/9299743/35197403-b7e4786a-fe93-11e7-9752-171d1e19bea9.png)

**Comment by gonetz** [comment]
Is it some specific place, which has that glitch? I started the game in two players mode, no issues.

**Comment by theboy181** [comment]
been a while since I posted that, I will double check but that looks like 2p mode, may have been the demo.

**Comment by gonetz** [comment]
@theboy181 Have you found how to reproduce that issue?

**Comment by theboy181** [comment]
I’m away from my computer this week I’ll test again and give an update or close depending on my findings. 

I’ll take some time to look at my other threads too. I’m sure there has been progress on some of them. :)

**Comment by theboy181** [comment]
Was unable to reproduce with latest builds.
