### ISSUE TITLE
GlideN64 very slow on Ubuntu

### ISSUE THREAD

**Issue by Lithium64** [gonetz/GLideN64#1708]
I'm running the latest linux build of m64p (ubuntu build don't works correctly here) on Ubuntu 17.10 and GlideN64 is very slow, on windows with this same PC it have a highly superior performance. Even using the angrylion-plus plugin on ubuntu it have a much higher performance.

My specifications are

i3 4150 3.50ghz
12 GB RAM
Radeon R7 260X 2GB VRAM
Ubuntu 17.10
Kernel 4.14.13
Mesa 17.3.2

**Comment by Jj0YzL5nvJ** [comment]
Welcome to the club #1561

**Comment by Lithium64** [comment]
@Jj0YzL5nvJ Thanks, it's the same issue.
