### ISSUE TITLE
Indy Racing 2000 (U) Speedometer broken 

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1709]
Should look like this
![image](https://user-images.githubusercontent.com/9299743/35203124-76b3c33a-fedb-11e7-8cf2-acecf3e694d2.png)

**Comment by olivieryuyu** [comment]
and how it looks like now?

**Comment by theboy181** [comment]
Its one ROM away from Indiana Jones. ;)

![image](https://user-images.githubusercontent.com/9299743/35475491-3fa6eca0-0354-11e8-906b-41f083dc7eb1.png)

**Comment by rez-** [comment]
No problems here with latest version (486e041)

![indy_racing_2000-000](https://user-images.githubusercontent.com/10398036/35733270-0aea4de0-081d-11e8-946e-b33a0dc74c70.png)

**Comment by theboy181** [comment]
Hmm. I wonder if it’s a setting I have enabled in the ini. Do you have a recent build available for me to test

**Comment by gonetz** [comment]
https://drive.google.com/file/d/11j3_Uc9sg7sYbSfjqqKSZD7OZJrREfgu/view?usp=sharing

**Comment by gonetz** [comment]
Just tested - no problems with speedometer.

**Comment by gonetz** [comment]
Issue with "render 2D elements in N64 resolution"

**Comment by theboy181** [comment]
Fixed in current master
