### ISSUE TITLE
Flygin dragon: wrong gfx bands and then crash under mupenplus (but not emu related bug?)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#171]
Very weird issue

Only on Mupenplus the plugin shows errors with with some lines or bands appearing between frame and then it crashes (black screen) before at title screen.

No error under other plugin under Mupenplus and with other emus with GlideN64.

![bad](https://cloud.githubusercontent.com/assets/8987490/5331594/31cf070c-7e32-11e4-89be-8fd7e7d7a628.jpg)

**Comment by AmbientMalice** [comment]
Still getting black bands with mupen64plus, but no crashing.

**Comment by gonetz** [comment]
Fixed

**Comment by olivieryuyu** [comment]
fixed
