### ISSUE TITLE
Mario Golf (U) bug in GLideN64 3.0 regresion

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1710]
![image](https://user-images.githubusercontent.com/9299743/35469790-bb98dd40-02f1-11e8-828f-338b0af5736c.png)
The items in the select screen get pushed and squished on the left side of the screen. dosnt happen on earlier versions.

**Comment by olivieryuyu** [comment]
confirmed

**Comment by rez-** [comment]
I cannot reproduce, latest version (486e041) and public release 3.0 are working fine for me.

![mariogolf64-000](https://user-images.githubusercontent.com/10398036/35732932-b4cbe1d6-081b-11e8-85a0-50d409ce6432.png)

**Comment by gonetz** [comment]
It is another issue with "render 2D elements in N64 resolution"

**Comment by theboy181** [comment]
fixed in current master!
