### ISSUE TITLE
Spiderman: fog applied wrongly when transparency should be used

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1712]
At the very beginning of the first level, simply jump on the crate and then leave them close to their border

here with Angrylion

![image](https://user-images.githubusercontent.com/8987490/35536929-b69c5c3c-0548-11e8-8118-46a3b79f9250.png)

here with gliden64

![image](https://user-images.githubusercontent.com/8987490/35536961-d1f18be2-0548-11e8-9129-2e78537d6402.png)

It seems to be a RDP bug.

**Comment by rez-** [comment]
bad commit: 3c61198

**Comment by gonetz** [comment]
Should be fixed in latest master.
