### ISSUE TITLE
Perfect Dark (Missing Transition Animation at end of Title Intro Screen - PD Logo Doesn't Disappear)

### ISSUE THREAD

**Issue by pdrome** [gonetz/GLideN64#1715]
There is a pause loading the title screen with perfect dark of about 8 seconds (when booting the game after the n64 logo turns into the perfect dark logo, you can also skip to this part by pressing start a few times once the rare logo shows up).  I'm using the February 5th 2018 release of m64p. It occurs using both cxd4 and rsp-hle, and dynarec, cached interpreter, and pure interpreter.

Works fine in angrylion.

I found no settings combination in gliden64 to fix it. Game otherwise appears to be playable thus far.

**Comment by Yui12** [comment]
Wasn't there always a pause in the emulation of this game in general? Glide64 even had this problem of it being black screen pauses between the intro, and before a level boots up.

**Comment by pdrome** [comment]
That's a good point and something I hadn't considered earlier.  I looked into it a bit more.

So with gliden64, the logo just stays there during a pause of about 8 seconds.  Then either the load screen or a cut scene from the first level plays (immediately following the pause) depending on whether or not you press start during this time.

With angrylion or glide64, the logo gets washed away by an erase type effect.  Then there is a pause of about 8 seconds while you wait for the load screen or a cut scene. So I guess the pause is still there either way, but it is the effect is missing.

**Comment by loganmc10** [comment]
Related :  https://github.com/ata4/angrylion-rdp-plus/issues/49

**Comment by truskj** [comment]
Not sure if this is helpful, but Perfect dark had plenty of long pauses... in between missions and after the intro. even selecting character in combat simulator had short pauses between loading models. lately I've been using the OC feature in the new PJ64 and all pauses are gone.. maps and menu load instantaneously and 4 people can be selecting characters seamlessly. I always have display FPS and display percentage on. if the frames drop below 10 but the percent is still 99-100.. then you know its a problem with the game, not the plugin.. (most of the time).

**Comment by pdrome** [comment]
The pauses are there no matter which plugin you are using and I wouldn't be surprised if that was the console behavior (I'd test if my n64 still worked). However, in this case the issue is a missing eraser-type transition animation after the title screen completes it's animation.

I should really change the title and throw up a video.

**Comment by pdrome** [comment]
Title fixed.  I'll make a video this evening.

**Comment by Jj0YzL5nvJ** [comment]
https://youtu.be/MX_QoNfCNKY?t=53m2s

Another way to unleash the event is if you choose **Accept** before a mission. Such also work by choose **Decline** in a place other than the Carrington Institute.

Example: After completing, failing or aborting a mission and choosing any.
https://youtu.be/MX_QoNfCNKY?t=2m12s
https://youtu.be/MX_QoNfCNKY?t=4m15s
https://youtu.be/MX_QoNfCNKY?t=56m44s

P.S: Works fine in glide64mk2 too.

**Comment by pdrome** [comment]
Thanks for the videos showing the normal behavior @Jj0YzL5nvJ .  Here is a side-by-side against Angrylion RDP plus.  Angrylion doesn't quite run full speed on my machine so I chose to sync the videos at the issue.

[![Video showing issue](https://img.youtube.com/vi/uFKZ5v6sNAo/0.jpg)](https://youtu.be/uFKZ5v6sNAo "Video showing issue")

**Comment by gonetz** [comment]
Fixed. @loganmc10 thanks for the tip :)
