### ISSUE TITLE
Missing Ground Textures in Super Smash Bros.

### ISSUE THREAD

**Issue by thecoreyburton** [gonetz/GLideN64#1716]
On certain stages in Super Smash Bros. textures are not displayed. The easiest way to replicate this problem is to start the game, go into "1P Mode", then "Bonus 2 Practice". Select Pikachu and hit go. Alternatively, here's a [savestate](https://github.com/gonetz/GLideN64/files/1715151/btp.zip).

![Comparison](https://user-images.githubusercontent.com/12134368/36081744-186a9d30-0ff7-11e8-8175-a9d0d845daaf.jpg)

On the left is the Rice plugin, displaying the textures how I would expect. On the left is GLideN64 displaying a yellow-brown texture instead.

**Comment by rez-** [comment]
strange enough, when you go down a bit, when your less high, the tiles back are normal.

![smash_brothers-000](https://user-images.githubusercontent.com/10398036/36754020-330c342e-1c08-11e8-813c-d8958b7eaec0.png)
![smash_brothers-001](https://user-images.githubusercontent.com/10398036/36754021-33225394-1c08-11e8-9f0c-1ec936916bbb.png)

**Comment by gonetz** [comment]
This issue is inherited from glN64.

**Comment by theboy181** [comment]
Too bad the Grass in Dreamland has issues will, was hoping this was related to that.

**Comment by thecoreyburton** [comment]
Thank you gonetz. The fix solves the issue I was experiencing.

**Comment by gonetz** [comment]
I'm not sure that this fix is safe and will not cause regressions in other games, thus it is not in master yet.
