### ISSUE TITLE
Micro Machines 64 Turbo (U) Regresion

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1725]
Issue with latest builds of GLideN64 and this game. The tracks go in the opposite direction of the smoke.
![bugs](https://user-images.githubusercontent.com/9299743/36459961-17ab14e0-166b-11e8-85dd-29a3a7647f89.gif)
Here is an older version where it works as it should
![bugs2](https://user-images.githubusercontent.com/9299743/36459972-24aeb336-166b-11e8-800e-893ee7075d82.gif)

**Comment by theboy181** [comment]
Looks like it has something to do with multiple of N64 Resolution setting.

**Comment by rez-** [comment]
when I use normal resolution in m64p, all is fine, when i do fullscreen, the smoke goes the wrong way..
public release is 1.2 working
public release 2 i cant check, it stays in native resolution
public release 3 is broken

**Comment by gonetz** [comment]
I can't reproduce it.

**Comment by rez-** [comment]
Hmm, that's odd. Maybe it has something to do with the GFX card. I used Nvidia. I'll check my Intel one as well.

**Comment by gonetz** [comment]
May be that. I use Radeon.

**Comment by theboy181** [comment]
I checked both my Nvidia setups. It happens with anything above 2x. I tested without the 2d items checked, but same issue.

**Comment by theboy181** [comment]
Updated my Nvidia Drivers. Issue still occurs at any setting above x2

**Comment by theboy181** [comment]
Tested with Current Master. Still broken when set to higher resolutions.

**Comment by theboy181** [comment]
Can anyone else confirm this bug on  NVIDIA gfx card?

**Comment by loganmc10** [comment]
Yes I can reproduce this in mupen64plus + Windows + Nvidia. It's not the smoke that is going the wrong way, the track is going the wrong way, and yes, only at higher resolutions

**Comment by theboy181** [comment]
Thanks.. its an odd bug.. do you have ATI to test against ?

**Comment by loganmc10** [comment]
I just tested Linux + VMware and saw the exact same issue, I don't think it's GFX card related. I tested using 4X native resolution

**Comment by theboy181** [comment]
wonder why @gonetz cant reproduce it then ?

**Comment by gonetz** [comment]
I set 4X native resolution and 8X native resolution - the problem is not reproduced for me.

@loganmc10 if you can reproduce the problem, could you find the regression commit?

**Comment by rez-** [comment]
by the way, same result with Intel

**Comment by loganmc10** [comment]
@gonetz I tried to bisect this. It broke sometime during the graphics refactoring. It's very hard to pinpoint because many of those commits don't compile or produce a black screen, etc. I tested a commit from Dec 28, 2016 and it worked, and by Feb 2, 2017 it was broken. So it was sometime in between there, but it will probably be very hard to pinpoint the exact spot.

**Comment by fzurita** [comment]
@loganmc10 Can you run the "undefined behaviour sanitizer" against this?

**Comment by loganmc10** [comment]
Nothing unusual with this game happens, just a couple messages related to the Depth Buffer, same as every other game

**Comment by Jj0YzL5nvJ** [comment]
I can reproduce this on Xubuntu 16.04.4 LTS with nouveau (Mesa 17.3.6) using mupen64plus (CLI) **by changing the resolution to 1280x960**.

**Comment by olivieryuyu** [comment]
so you mean the behavior is resolution related?

**Comment by loganmc10** [comment]
Yes it happens at high resolutions only

**Comment by Jj0YzL5nvJ** [comment]
Like @gonetz's case, I can't reproduce on Xubuntu 16.04.4 LTS using amdgpu (Mesa 17.3.6 & Mesa 18.1.0-devel).

**Comment by loganmc10** [comment]
I just had this reported to me about Blast Corps: https://github.com/m64p/mupen64plus-GLideN64/issues/69

Probably the same issue, only happens at high resolutions, GPU driver specific, flips the image

**Comment by loganmc10** [comment]
I finally figured this out @gonetz the issue is in the ```_drawThickLine``` command:

https://github.com/gonetz/GLideN64/blob/9497a9b8681324234a49a12a1976b92e0ffd78e3/src/GraphicsDrawer.cpp#L911

If you force it to use _drawThickLine, you'll see the issue in this game. It only happens on certain GPUs at certain resolutions because m_maxLineWidth is different depending on the GPU.

**Comment by theboy181** [comment]
Sweeeeeeeet find!!!!!

**Comment by gonetz** [comment]
@loganmc10 Thanks! Fixed in 8212a1f

**Comment by theboy181** [comment]
This is awesome news. Was this linked any other issues ?  Should I close?

**Comment by loganmc10** [comment]
I had someone report an issue with Blast Corps that was caused by the same bug (https://github.com/m64p/mupen64plus-GLideN64/issues/69) I'm sure other games could have been affected, but it sounds like it should be fixed now (I haven't personally tested)

**Comment by gonetz** [comment]
> Should I close?

If you can confirm that it is fixed, yes, please close.
I forced _drawThickLine and then fixed it, so the problem must be fixed for all cases, but better to get confirmation. Test build:
https://github.com/gonetz/GLideN64/issues/1574#issuecomment-385879877

**Comment by Pixelnarium** [comment]
The bug in Blast Corps I reported is fixed now.

**Comment by theboy181** [comment]
FIXED :)
