### ISSUE TITLE
OSD Display: Rendering Resolution

### ISSUE THREAD

**Issue by thecoreyburton** [gonetz/GLideN64#1733]
Is it possible to add a "display rendering resolution" option to the OSD display?

The idea is that if the plugin is set to "same as output resolution" it would display the output resolution, if the plugin was set to "original N64 resolution" it would display the game's native resolution (eg. 320x238 or 640x237) or if the plugin was set "multiple of native resolution" it would display the current multiplied value (eg. 640x476 or 1920x711).

Users can use this information in multiple ways, such as determining what the game's native resolution is and perhaps deciding what size they want to set the window to based on this information.

**Comment by gonetz** [comment]
It is possible. I'll do it.

**Comment by thecoreyburton** [comment]
Thank you gonetz!

Would it also be possible to add an option to play the game at the exact resolution it is rendering at? By this, I mean disable the aspect ratio correction and instead set the window size to the current rendering resolution if it's set to original n64 resolution or a multiple of n64 resolution.

I know this will make some games appear stretched or strangely sized (to regular users) but for console accuracy this would be extremely useful (and also interesting)!

**Comment by AmbientMalice** [comment]
>I know this will make some games appear stretched or strangely sized (to regular users) but for console accuracy this would be extremely useful (and also interesting)!

The N64 itself doesn't output at those resolutions. All output is resized to a fixed size by the video interface.

**Comment by thecoreyburton** [comment]
> The N64 itself doesn't output at those resolutions. All output is resized to a fixed size by the video interface.
Ah, sorry for my incorrect assumption. I stand corrected. 

Still, I would still be very interested in seeing a 1:1 representation of the rendering resolution as an option somewhere in the plugin.

**Comment by gonetz** [comment]
Rendering resolution can vary within one game, e.g. high resolution in menu to draw sharp 2D and low resolution in game to render more polygons. What should plugin do -resize window?

**Comment by thecoreyburton** [comment]
I think yes. If it's setting the window size to the rendering resolution when this new option is enabled, then when the rendering resolution changes in-game so should the window size.

**Comment by gonetz** [comment]
It is too complex. I will not have time for that this year.

**Comment by thecoreyburton** [comment]
That is understandable. The "display rendering resolution" option to the OSD should be plenty until then.

**Comment by theboy181** [comment]
How would full screen react to these window changes?

**Comment by thecoreyburton** [comment]
>How would full screen react to these window changes?
That is a very good question. I only thought of the idea with the intent of getting uncorrected frames that are 1:1 to the render resolution when it's set to "original N64 resolution" or "multiple of native resolution". This was the best idea that came to my mind, but perhaps a better idea serving the same purpose is needed.

Regarding the current idea and fullscreen, if there is no good solution then perhaps the option would be disabled in fullscreen. I am unsure.

**Comment by vadosnaprimer** [comment]
Rendering at fullscreen forces the screen's resolution anyway, so there's no sense in using this mode to watch pixel-perfect content. As for rendering pixel-perfect content and then stretching that to fullscreen, there's no certainty it'd look as good as rendered at fullscreen res altogether.

**Comment by thecoreyburton** [comment]
Thank you for implementing this!

I have two questions about how native resolution is handled in relation to overscan. Using "Banjo-Kazooie" as an example, I notice the native resolution is 292x214. This game also has a noticable portion of overscan. Does the native resolution refer to the game's viewport and overscan, or just the viewport on it's own?

My second question is how is the overscan created? Do the games generate it themselves? Is it a feature of the console? or is it the plugin which does it?

**Comment by theboy181** [comment]
Is there a link to this build?

**Comment by gonetz** [comment]
@thecoreyburton 
Native resolution refers to rendering buffer size in RDP. That is it is size of picture, rendered by the game. This picture is then mapped to TV screen by Video Interface.

> My second question is how is the overscan created?

Do you mean black bars around the picture? They can be either rendered by RDP or Video Interface can add them. Game developers could choose either way. You may disable frame buffer emulation. This will disable VI emulation too. If overscan created by VI, you will see it. You may also use "crop" option. Plugin can crop black bars created by RDP. Overscan created by VI can't be cropped.

@theboy181 
Windows builds for mupen64plus can be downloaded from
https://ci.appveyor.com/project/gonetz/gliden64/history
Select revision of interest, click to ARTIFACTS, download dll.
I did not upload zilmar-spec build for this feature yet.

**Comment by dankcushions** [comment]
@vadosnaprimer 
> Rendering at fullscreen forces the screen's resolution anyway, so there's no sense in using this mode to watch pixel-perfect content. As for rendering pixel-perfect content and then stretching that to fullscreen, there's no certainty it'd look as good as rendered at fullscreen res altogether.

for lower spec systems like the raspberry pi, i wish fullscreen could act this way. ie, the system doesn't have the power to run gliden64 at native 1080p, but we also don't want to run in a tiny window. currently retropie uses sdl to upscale a small mupen64plus window to full screen, but a native solution would be better

...but maybe this is mupen64plus's responsibility rather than the plugin... i don't know.

**Comment by theboy181** [comment]
@gonetz had a look at the link you provided. Is there any reason you are not maintaining zilmar spec any longer? 
I was worried that your crowed funding would only have mupen support too. This might eliminate some of the possible funding for you and your teams efforts.  :(  ( I also do all my debugging in zilmar spec emulators :( )

**Comment by loganmc10** [comment]
@theboy181 GLideN64 fully supports the zilmar-spec. Gonetz just has mupen64plus spec auto-builds working via AppVeyor. I believe it was more difficult to get the auto-builds of the zilmar-spec working because of the dependency on Qt. It someone figured that out, then auto-builds of the zilmar-spec version would happen as well.

The only thing that the mupen64plus version supports that the zilmar spec doesn't is the HLE versions of Gauntlet Legends, WDC, and Stunt Racer. But that is not GLideN64's fault, the zilmar spec needs to be updated to pass SP_STATUS_REG to the GFX plugin, once that happens, those games will work in HLE with GLideN64.

Indiana Jones should work in HLE with zilmar spec just like it will with mupen64plus

**Comment by theboy181** [comment]
This makes more sense now. Thanks for clearing that up. :)  Ir's good to hear that its a setup error and not a movement change from zilmer spec emulators.

**Comment by AmbientMalice** [comment]
>Indiana Jones should work in HLE with zilmar spec just like it will with mupen64plus

It'll probably crash at the end of every level, though.

**Comment by loganmc10** [comment]
> It'll probably crash at the end of every level, though.

Impossible to say without testing, but yes it does that in LLE currently. Running the game in HLE might get around that bug. Either way that still isn't a reflection of GLideN64's support of the zilmar-spec, that is just an emulator issue.

**Comment by theboy181** [comment]
@ambientmalace are you the one moanjng on 4chan about this game? You able to do some testing and report your findings to the appropriate developers?

**Comment by AmbientMalice** [comment]
@theboy181 Sorry, but I have no idea what you're talking about.

**Comment by theboy181** [comment]
Sorry, there was someone complaining and not trying to do anything on 4chan. It was in the same tone as your comment. You should help that person out by reporting anything you may know about the issues causing the problems on emulators. :)

**Comment by loganmc10** [comment]
mupen64plus used to have the same issue of Indiana Jones freezing at the end of each level. I didn't track it exactly, but I believe it had something to do with the SI interrupt timing/flags, mupen64plus handles that a bit differently from PJ64. From what I remember, PJ64 only delays the SI interrupt for certain games, and doesn't set any of the SI flags. mupen64plus always delays the SI interrupt, and it sets the SI_STATUS_DMA_BUSY flag until the interrupt is triggered. It's the same situation for the PI interrupt, I don't think PJ64 delays that interrupt at all, mupen64plus always delays that interrupt, and it sets PI_STATUS_DMA_BUSY until the interrupt is triggered. It's probably one of those things, but I could be remembering wrong.

**Comment by theboy181** [comment]
So there is no issue in Mupen? If so, that 4Channer needs to be informed!

**Comment by loganmc10** [comment]
> So there is no issue in Mupen? If so, that 4Channer needs to be informed!

The only issue I'm aware of is this one: https://github.com/mupen64plus/mupen64plus-core/issues/542

The game doesn't work right with the 32-bit dynarec, but it works fine with the 64-bit dynarec. It sounds like the problem might have been pinpointed, but I haven't had the time to look at it or test the fix yet. With 64-bit mupen64plus I'm not aware of any bugs with Indiana Jones.

**Comment by theboy181** [comment]
no reason for any of the negativity then I suppose! Good the hear the issue has been possibly pinpointed!

**Comment by AmbientMalice** [comment]
>So there is no issue in Mupen?

You mean with Angrylion's? There are a few problems. The first is of course that performance is really not good. The second is that particle effects aren't rendered correctly. (Due to an LLE RSP issue). The third is that the game has interlacing and so looks kinda ugly due to combing artifacts.

https://github.com/gonetz/GLideN64/issues/1259#issuecomment-362923669
