### ISSUE TITLE
SD Hiryuu no Ken Densetsu: OpenGL Error in LLE

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1736]
I was testing this game in LLE and came across this GL error:
```
glGetError(glTexStorage2D) = GL_INVALID_VALUE
major api error 1281: GL_INVALID_VALUE error generated. Invalid texture format.
glGetError(glTexSubImage2D) = GL_INVALID_VALUE
major api error 1281: GL_INVALID_VALUE error generated. <levels>, <width> and <height> must be 1 or greater.
```

It happens first at this screen, and only in LLE:

![sd_hiryu_stadium-000](https://user-images.githubusercontent.com/848146/36699486-033a0c66-1b0a-11e8-8599-b11d09144670.png)

**Comment by loganmc10** [comment]
Here are the calls that generated the error:

![image](https://user-images.githubusercontent.com/848146/36699614-6f08f538-1b0a-11e8-9f4d-c656721f0e58.png)

I think the "Invalid texture format." is incorrect, the texture format looks fine, I believe the issue is that it is trying to create a texture with ```width=0```

**Comment by gonetz** [comment]
@loganmc10 please test again with the current master.

**Comment by loganmc10** [comment]
Looks good now, I don't get that error anymore
