### ISSUE TITLE
GLideN64 3.0 Regression

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1739]
@gonetz 

I was not sure till just now, after some testing. 3.0 has a regression where some triangles in several game will fail to render for a frame or two. I tested against current WIP, 3.0 release, Glide64 and an older build I have (AIO opt).

Bug happens in current WIP, and 3.0 - I hope that you are able to reproduce, and squash it.

[Roadsters Trophy (U) (M3) - Project64 2.4.0.9999 3_1_2018 9_49_44 PMTrim.zip](https://github.com/gonetz/GLideN64/files/1773885/Roadsters.Trophy.U.M3.-.Project64.2.4.0.9999.3_1_2018.9_49_44.PMTrim.zip)

**Comment by gonetz** [comment]
I run the game exactly  as on your video but was unable to reproduce the bug.
I run it with Project 64 2.3.2
Could you give me a savestate to test?

**Comment by theboy181** [comment]
I reset my GLideN64 settings and the issue has gone away with this save state. Let me monitor this a little closer. It was happening in another game last night. Only this game had buildings in the back ground that would would disappear.  

In another game, Virtual Chess, the pieces would flash with missing triangles. I'm not sure what causes is exactly, but when it does happens I can make a save state, and change to other video plugins, and it will be fine. It only happen on the GLideN64 plugin. 

Ill ping you when it happens next.

**Comment by theboy181** [comment]
Have not seen the issue in a while. closing for now.
