### ISSUE TITLE
GLideN64 3.0 Regression (Noise)

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1740]
Kirby64, noise is broken.

![image](https://user-images.githubusercontent.com/9299743/36907819-71705258-1dee-11e8-9bf9-8094352bbef6.png)

Not sure if its the same issue that is breaking water effects in Geomon when AA is on.

**Comment by gonetz** [comment]
May be it is result of your widescreen hack? I tested the game with default settings, no issues with noise.

**Comment by theboy181** [comment]
I’ll test again but I don’t have a WS hack set

**Comment by theboy181** [comment]
Still happening, any other suggestions?
![image](https://user-images.githubusercontent.com/9299743/36982508-d749ad24-2044-11e8-8999-c2b0aa50f92e.png)

I guess its not best quality setting. I have this set on all the time. Any chance it can be fixed?

**Comment by theboy181** [comment]
![image](https://user-images.githubusercontent.com/9299743/36982686-4b23efb6-2045-11e8-85ae-a17e0adb29b0.png)
Here is an older version on GLideN64 with the setting turned on.

**Comment by theboy181** [comment]
same setting is breaking Indy Racing
![image](https://user-images.githubusercontent.com/9299743/36983477-565262ee-2047-11e8-9827-7acda64a6e0f.png)

**Comment by gonetz** [comment]
Hmm, so it is native res 2D setting breaks the things. I'll check what's wrong with it.

**Comment by theboy181** [comment]
fixed by current WIP! Great Work @gonetz
