### ISSUE TITLE
Super Mario Star Road: Black Screen Issue (Frame Buffer Emulation)

### ISSUE THREAD

**Issue by SuperToad64** [gonetz/GLideN64#1745]
Every time I try to run Super Mario Star Road I get a completely black screen. Once I disable Frame Buffer Emulation I get this:

https://cloud.githubusercontent.com/assets/4800879/7552485/2268820e-f6b7-11e4-848d-4359335a1a94.jpg

https://cloud.githubusercontent.com/assets/4800879/7552476/c4b3c2ae-f6b6-11e4-80d3-66de5ede6219.jpg

This happens with almost all of the Super Mario 64 Rom hacks. It seems it has been an issue since 2015. With new Super Mario 64 hacks on the rise, this should be fixed. The reason I am using GlideN64 is because it is the only plugin that I know of that lets you make a custom windowed size. I am trying to use the entirety of my screen in windowed mode while playing Super Mario star Road.

I have tried all of the settings inside Project64's graphics settings within GlideN64, nothing makes the black textures go away. But disabling Frame Buffer Emulation gets rid of the black screen. It is unplayable with the black textures though. It works in Glide64 because they use software frame buffer emulation. If you added a software frame buffer emulation setting it would probably fix all rom hacks. Any help would be appreciated.

I am running Project64 version 2.3.2.202 and I have the latest public Release of GlideN64 which is 3.0. I have already tried the recent WIP version of GlideN64 and it still doesn't work.

Similar to issue #525, but it was closed with no fix.

**Comment by loganmc10** [comment]
> With new Super Mario 64 hacks on the rise, this should be fixed.

The bug is with the ROM hack, not the GFX plugin. These ROM hacks don't work on a real N64, they won't work with accurate GFX plugins like Angrylion or GLideN64.

I doubt this will be fixed, you can try to ask the ROM author to fix the ROM. There are some ROM hacks that are well written and work on real N64's (the recent "Goldfinger N64" comes to mind), and they also work with GLideN64

**Comment by SuperToad64** [comment]
Is there a way to add software emulated frame buffer like Glide64 does? If not do you know of any other project64 plugin that allows you to make custom windowed resolutions. I was told that Glide64 has a list of windowed resolutions that you can edit, but I could not find it.

**Comment by SuperToad64** [comment]
I was thinking that some Custom Settings could fix this problem. Because it is centered around the Frame Buffer. But I could not find a list of settings for the tag frameBufferEmulation. Does anyone have a list of all the different Custom Setting commands that you can enter into the GLideN64.custom.ini? Because it would be helpful for testing purposes.

**Comment by gonetz** [comment]
> I doubt this will be fixed

Yes, it will not.

**Comment by SuperToad64** [comment]
BUUUT . . . I got a fix from Discord64!!! It turns out the problem was a bad 0xFC setcombine. So the ROM file was at fault.

It looks like Last Impact will have some issues as well:

Quoted by Trenavix

    yeah last impact is pretty trashed on everything that's not jabo's because kaze hardly tested anything
    if you do the setcombine trick on it it's playable but has some bugs here and there

So with the same vaules you can fix Last Impact the same way.

Thanks to Trenavix, here is the solution, its called the setcombine trick. You must use a Hex editor and replace all the values of this:
![fix super mario star road](https://user-images.githubusercontent.com/37228863/37260483-158c84c4-256a-11e8-8fb5-cf632f2aedce.png)

Make sure you have the hex-values option checked. You must replace all instances of FC 12 7F FF FF FF F8 38 with FC 12 18 24 FF 33 FF FF. Then save the rom, it's that easy! So issue #1745 is closed, Thanks again Trenavix! Someone might want to add this at the end of the issue.

**Comment by SuperToad64** [comment]
Yet again Trenavix saves the day! When I set the resolution to anything over 1600 x 1200 in windowed and fullscreen it does this:

![aspect ratio 1](https://user-images.githubusercontent.com/37228863/37312690-6a589804-2622-11e8-80d5-a6c8d86a24d5.png)

![aspect ratio 2](https://user-images.githubusercontent.com/37228863/37312696-6f0f50a4-2622-11e8-9f85-f49483dcc9cf.png)

So since Frame Buffer Emulation is disabled I cannot set the aspect ratio. So Trenavix presents us with a .bps patch that will fix all of that. It even fixes the black screen that is present when Frame Buffer Emulation is switched on with GlideN64! So now Super Mario Star Road has no problems whatsoever.

This new edition is called Super Mario Star Road Enhanced Edition. It even adds 3D spinning models of all the coins, they look like they are from Super Mario Sunshine. Here is what it adds:


> Readme By SuperToad64:
> 
> Super Mario Star Road Enhanced Edition
> Patch By Trenavix - Discord64 Developer
> 
> To be used on a 8mb sm64 rom, Usually the general rom used is Super Mario 64 (U) [!].z64. You can get it from here: https://sites.google.com/site/supermario64download/Home/download-super-mario-64
> 
> patch with Flips.exe (Floating IPS Patcher) Download it here: https://www.smwcentral.net/?p=section&a=details&id=11474
> 
> Use the Super_Mario_Star_Road_Enhanced.bps (Version 1.1) First, if you have any problems use Star_Road_Console_Test.bps (Version 1.0), which doesn't include the texture fixes for the coins.
> 
> Changelog:
> 
> Star_Road_Console_Test.bps (Version 1.0): I got rid of the metal wing textures (I don't think you can even see those in star road ever) and used their data for polygon data
> 
> Super_Mario_Star_Road_Enhanced.bps (Version 1.1):  Fixed some ambient/diffuse colours on the red and blue coins so they no longer look greyscale and all coins have shading. Also fixed rom name.

So there you have it, it fixes all of the issues I have had thus far and adds some sweet looking new 3D coins, how can I say no? Totally Awesome! You can download it from the attachment below, enjoy!!

[Super Mario Star Road Enhanced Edition.zip](https://github.com/project64/project64/files/1804787/Super.Mario.Star.Road.Enhanced.Edition.zip)

Screenshots:



![super mario star road enhanced](https://user-images.githubusercontent.com/37228863/37312953-69ac8432-2623-11e8-8252-9182c3f2dc46.png)

![super mario star road enhanced 2](https://user-images.githubusercontent.com/37228863/37312958-6e306aaa-2623-11e8-9839-da7ac0c7ebba.png)

**Comment by loganmc10** [comment]
Again, you shouldn't post links to illegal downloads (including the ROM hack) on a GitHub page

**Comment by alexchandel** [comment]
@SuperToad64 Last Impact has the same issue. You know of a patch for that?

**Comment by SuperToad64** [comment]
@alexchandel Yes, this same fix should work for Last Impact as well. Just follow the instructions above and it should work. Enjoy!

**Comment by alexchandel** [comment]
@SuperToad64 It partially worked. The visual issues are mostly gone now. However, the music and sound effects are still very distorted (they sound like running & jumping sounds of different pitches), and the game hangs as soon as I enter the first level from the overworld.  I tried the find and replace on Last Impact v1.1.  Do you have any suggestions?

**Comment by gh3tt0smurf** [comment]
I tried changing the hex values and it says that those values you posted do not exist.  I tried doing it with both hex editor programs.

**Comment by jerkstore369** [comment]
Wow, thanks! A lot of people use OpenEmu and star road doesn't work on it as OE uses mpen64plus. The Enhanced Edition works, however all the characters are too skinny compared with the original. Like the graphics are squished. Maybe the horizontal resolution has been changed from the original. Is there any way to change this? Make it looks more like the original instead of squished? Thanks.

**Comment by pleasejustgo** [comment]
@SuperToad64 I know it's been a while but I just found this recently trying to get star road working with mupen64plus. Last Impact 1.2 does not have the codes mentioned above. Any idea how to fix it? Thanks.

**Comment by poudink** [comment]
To anyone who ended up here: this is how you get SM64 hacks working.
First, follow this: https://www.smwcentral.net/?p=viewthread&t=78265&page=5&pid=1478773#p1478773
This will fix most of the issues with the hacks in GlideN64. After going through the MarioMender64 procedure, you won't even need to disable framebuffer emulation anymore.
Then, disable MSAA in the GlideN64 settings. It seems to cause some HUD artifacts. Also stay away from xBRZ scaling, it makes some of the text weird. HQ4X seems to do a better job.
Then with a hex editor, replace all instances of 0xBA00140200000000B900031DC8113078B600000000010000 with 0xBA00140200000000B900031D00443078B600000000010000. This will fix billboards in foggy areas. The MarioMender64 script is supposed to take care of that already, but it didn't seem to work for me.
Finally, you may need to do the fix already mentioned in posts above: replacing all instances of 0xFC127FFFFFFFF838 with 0xFC121824FF33FFFF. For me, this was only needed to fix some of Kaze's custom objects.
This is kind of a tedious process to do for every older hack. Would be very nice to have a tool to automate the process. I may get around to it some day. Still though, it works. After doing this, the only remaining issue I could find was a slightly glitchy texture on Kaze's flip-swap platform.
