### ISSUE TITLE
Alternate Solution to Issue #1745 - Adding Custom Windowed Resolutions To Old Glide64 Plugin

### ISSUE THREAD

**Issue by SuperToad64** [gonetz/GLideN64#1746]
Since issue #1745 was closed without much discussion and not solved I am offering a different solution. Since we cannot play ROM hacks on GlideN64 because of the black screen issue and the black texture issues why not add custom windowed resolutions to the old Glide64 plugin? That way people who want Custom Windowed Resolutions can have them when playing ROM hacks. I wouldn't mind if you guys added all of the new graphic options to the old Glide64 plugin as well, if it's possible. Because there were some really great additions like Anti-aliasing, Internal Resolution Scaling, the new enhancement method 6xBRZ, and of course the most important of all Custom Windowed Resolutions. I think it would be a reasonable goal to include these in the old Glide64 plugin. Is there any way you guys could make this happen? if you want to see the reason why I want Custom Windowed Resolutions refer to issue #1745.

**Comment by loganmc10** [comment]
You are asking this in the wrong place, you might want to try: https://github.com/project64/project64

**Comment by loganmc10** [comment]
The only version of glide64 that is maintained (that I know of) is here:

https://github.com/project64/project64/tree/master/Source/Project64-video

It was renamed to Project64-video

**Comment by SuperToad64** [comment]
Interesting find, didn't know that it was renamed. Thanks, I'll look into it.

**Comment by SuperToad64** [comment]
Nevermind, I found out how to download Project64-Video. It is included in their development builds. In the newest version v2.4.0-668-gc506db5 that was built in 2nd March 2018 there is the same black screen issue if you turn frame buffer emulation off. But if frame buffer emulation is left on it crashes the rom with this message:

CN64 System::RunRSP()
Unknown Memory Action
Emulation Stop

Tracking down the cause I found out that the last build where everything works fine is the v2.4.0-509-g64bcfa1 built in 25th September 2017. It even runs with hardware frame buffer emulation which is very weird. Because in Glide64 Final it would crash the rom if you had hardware frame buffer emulation on. So this signifies that it is not the ROM at fault.

So all of the builds after the v2.4.0-509-g64bcfa1 built in 25th September 2017 have the same issues I am experiencing with GlideN64. So now the newest versions of Glide64 don't even work because something was changed between the v2.4.0-509-g64bcfa1 built in 25th September 2017 and the v2.4.0-512-g8d60ef1 built in 26th September 2017. Sadly there is no build between these so I don't know what code messed up the frame buffer emulation. 

Here is the project64 development builds site: https://www.pj64-emu.com/nightly-builds

Even the latest version of  Project64-Video doesn't have the ability to add Custom Windowed Resolutions like GlideN64 does and it still has the weird crash from frame buffer emulation and the black screen issue. So some change in the code has made this weird glitch not the ROM files themselves. I will have to contact project64 through their Github, maybe then we can find the fix for this problem. Thanks for all of your help as it is greatly appreciated.

**Comment by oddMLan** [comment]
Ok. Could you close this issue then?

**Comment by SuperToad64** [comment]
Yes. Sorry about that. Hopefully more testing will determine the cause at Project64's github.

**Comment by SuperToad64** [comment]
Issue Fixed! Refer to Issue #1745 for the fix.
