### ISSUE TITLE
Kirby 64 - screen jumps in full screen.

### ISSUE THREAD

**Issue by Kidboy17** [gonetz/GLideN64#1750]
I'm using Project 64 2.3.2.3 and the newest WIP of GLideN64 rev.7aeb1018. 

Throughout the game, the screen slightly jumps up and down in a semi-fast manner. When using Glide64 for PJ64 : 2.3.2.3 this does not happen.

EDIT: Forgot to add that the misty/smokey effect that comes off the Dark Matter creature are pixelated and blocky. With Glide64 that comes with PJ64, the effect is much, much less but still there.

EDIT 2: I've included screenshots. First one is using GLideN64. Second is using Glide64 which comes with Project 64.
![gliden64_kirby64_001](https://user-images.githubusercontent.com/37382324/37430600-d7653600-278f-11e8-80ea-98ef71a502c0.png)

![glide64_kirby64_02](https://user-images.githubusercontent.com/37382324/37430641-fcd29e8c-278f-11e8-9492-45d3490944bc.png)

**Comment by Kidboy17** [comment]
To be honest, I don't know if the first picture or the second picture is the "correct" way it is suppose to look. I find videos and screen shots of both so i have no idea now.

But the screen twitching/jumping is definitely present with the newest WIP of GLideN64.

**Comment by Kidboy17** [comment]
So I found two more graphical errors and also experienced a major system crash twice which resulted in losing all my keyboard shortcuts and having me to reinstall Project 64.

First the graphical errors.
The different colored leaves on the ground during the movie, a few will appear and disappear rapidly. I circled the one that is most noticeable. It's hard to see, so I have included the save state. I have tested this using default settings with GLideN64 newest WIP, Glide64 that comes with PJ64 and with angrylion's RDP Plus r7. Both GLideN64 and Glide have the error, angrylion does not.
[Kirby 64 - The Crystal Shards (U).pj.zip](https://github.com/gonetz/GLideN64/files/1816896/Kirby.64.-.The.Crystal.Shards.U.pj.zip)

![kirby 1](https://user-images.githubusercontent.com/37382324/37487685-93990ca6-284f-11e8-93a6-15e04a8dfd8e.png)
![kirby 2](https://user-images.githubusercontent.com/37382324/37487692-972c0382-284f-11e8-85cb-f282094bd0c1.png)
![kirby 3](https://user-images.githubusercontent.com/37382324/37487695-98fc14b8-284f-11e8-9afd-d6c8b26670db.png)
Also when you enter and exit fullscreen, the curtains disappear completely.
![gliden64_kirby64_008](https://user-images.githubusercontent.com/37382324/37487864-18930b78-2850-11e8-9a33-b4a6ebf0f51c.png)
![gliden64_kirby64_009](https://user-images.githubusercontent.com/37382324/37487869-1b84ba8e-2850-11e8-85c0-ed21618cfb92.png)

The system crash happened when I was using GLideN64 newest WIP. I was in windows mode 640x480 going to fullscreen mode 1920x1080. The screen went black and my system restarted. I thought this was odd so I tried it again, resulting in the same thing. When I went back to try it out on a different game, I lost all my keyboard shortcuts for PJ64. I ended up redownloading and reinstalling PJ64 2.3.2. I have no idea why this would happen.

**Comment by theboy181** [comment]
Is it possible that your video card doesn’t meet the GLideN64 OpenGL hw requirements?

**Comment by Kidboy17** [comment]
My graphics card is a Nvidia Geforce GTX 780 Ti with 4095mb of Vram

**Comment by gonetz** [comment]
1. Screen shakes indeed in fullscreen. I don't see that shaking in windowed mode. I'll try to find, what's wrong.
2. Pixelated noise effect is right. You may compare with angrylion's plugin. I could not make noise properly when I worked on Glide64.
3. The issue with colored leaves is depth compare issue. Enable "Frame buffer"=>"Enable N64-style depth compare" to fix it.
4. " when you enter and exit fullscreen, the curtains disappear completely." It is not a plugin's bug. This is consequence of game's optimization.  The curtains rendered only once. When you change window mode, rendering buffers re-created. New buffers have no curtains because game does not draw them.
5. Can't say anything regarding the system crash.

**Comment by Kidboy17** [comment]
@gonetz Thank you for getting back to me! You were correct about the Frame Buffer. It corrected the leaves. Does this feature have any negative effects?

I compared it with Angrylion and it is the same effect on GLideN64 so I assume its a correct effect then. Here is a screenshot

![untitled](https://user-images.githubusercontent.com/37382324/37735612-cfd92ce4-2d0b-11e8-9ca9-ab5b4a81b8fa.png)

**Comment by gonetz** [comment]
"Enable N64-style depth compare" has at least two drawbacks: 
* it is incompatible with MSAA
* plugin works slower when it is enabled. It may run full speed still.

**Comment by gonetz** [comment]
screen jumps is fixed.

**Comment by Kidboy17** [comment]
Awesome glad to hear it! I will close this issue then.
