### ISSUE TITLE
Mario Party 3 - Curtain Call Mini Game

### ISSUE THREAD

**Issue by Kidboy17** [gonetz/GLideN64#1751]
In Mario Party 3 mini game Curtain Call when choosing which character appeared, there is overlapping of the characters images. This has never been fixed with Jabo's, Glide or GlideN64.
![gliden64_marioparty3_001](https://user-images.githubusercontent.com/37382324/37430279-eb390482-278e-11e8-9dfe-2b8cf1e9e1f7.png)

**Comment by loganmc10** [comment]
Duplicate of https://github.com/gonetz/GLideN64/issues/692

**Comment by Kidboy17** [comment]
Ah ok. Thank you. This can be closed then if necessary.
