### ISSUE TITLE
Paper Mario - Text error

### ISSUE THREAD

**Issue by Kidboy17** [gonetz/GLideN64#1753]
In the beginning of the game, after the first battle with Bowser when you meet the star spirits, their text is messed up. Using Project 64 with newest WIP. 

![gliden64_paper_mario_000](https://user-images.githubusercontent.com/37382324/37442785-76d859b2-27c5-11e8-8798-e1b84d6ea300.png)

This is the text when using Glide64 that comes with Project 64.
![glide64_paper_mario_01](https://user-images.githubusercontent.com/37382324/37442803-8a226846-27c5-11e8-92d3-f6d6a7113762.png)

**Comment by loganmc10** [comment]
Do you have any non-default settings? I think that text requires noise emulation to be enabled

**Comment by loganmc10** [comment]
This is what it looks like on my PC:

![paper_mario-002](https://user-images.githubusercontent.com/848146/37443465-fc302106-27d1-11e8-8ead-952d46784885.png)

A single screenshot doesn't really do it justice because it is a noise effect and the spots are moving around constantly.

**Comment by Kidboy17** [comment]
I've set the Bilinear filtering to N64 stlye 3 point, enable per-pixel lighting and render 2d elements in N64 resoultion. Everything else is default.

And noise is enabled.

**Comment by gonetz** [comment]
per-pixel lighting is useless for this game, but it should be harmless too.
"render 2d elements in N64 resoultion" most likely causes the problem.

**Comment by Kidboy17** [comment]
@gonetz You are completely correct. "Render 2d elements in N64 resolution" is the option that causes the error.
