### ISSUE TITLE
NEON_OPT makes spinning Nintendo logo invisible in GoldenEye

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1755]
At the opening sequence of GoldenEye, there is a spinning "Nintendo" logo. NEON_OPT makes this disappear.

Enabling HWLighting fixes the problem.

Also, enabling this code:

https://github.com/gonetz/GLideN64/blob/master/src/gSP.cpp#L479

Also fixes the problem, so I assume the problem is in the gSPLightVertex_NEON function

@gizmo98

**Comment by gizmo98** [comment]
I will take a look later.

**Comment by loganmc10** [comment]
Another game that I believe is affected is Beetle Adventure Racing. The colours of the cars is all wrong unless hardware lighting is enabled

![beetle_adventure_rac-001](https://user-images.githubusercontent.com/848146/37500151-7456947e-288d-11e8-8227-88c7c36d7dcf.png)


Should look like this:

![beetle_adventure_rac-000](https://user-images.githubusercontent.com/848146/37500156-7f68dfe8-288d-11e8-9da6-2024ed1e6569.png)

**Comment by gizmo98** [comment]
I have always tested every new neon function with beetle adventure racing. I have never seen wrong colors. DotProductMax4FullNeon() could be problematic. Some clobber registers are missing. Here is a commit with all missing registers (not tested yet):   
https://github.com/gizmo98/GLideN64/commit/c9bf51d584c542769995b3a1cc963cb214eba6d3

**Comment by gizmo98** [comment]
Strange. Everything looks good under Raspbian Stretch with GCC 4.9.
Please test if this commit fixxes the problem:
https://github.com/gizmo98/GLideN64/commit/13897968e74c0c43bef26baaa7e77f085cd58974
![img_8046](https://user-images.githubusercontent.com/6412699/37554970-84dc6a2c-29e0-11e8-8c41-3d11f4b7ee4a.JPG)

**Comment by loganmc10** [comment]
That fixes the issue with Beetle Adventure Racing, excellent work! However the issue with the missing Nintendo logo in GoldenEye is still there

**Comment by gizmo98** [comment]
Can you test this branch? I can see the "Nintendo" logo on my pi but neon asm input register definition seems to be incomplete.
https://github.com/gonetz/GLideN64/compare/master...gizmo98:neon-fixes2

**Comment by loganmc10** [comment]
Now I'm not sure, now at the "One Player" screen, I get a completely solid color background, with or without your change. The GoldenEye Nintendo logo is still missing with HW lighting though.

Maybe @fzurita can confirm the issue with Beetle Adventure Racing?

@gizmo98 can you try compiling with Clang on the Raspberry Pi? I am testing this on Android which is using clang to compile everything.

**Comment by loganmc10** [comment]
Ok I figured out the problem, it's different when compiling for debug / release.

For GoldenEye, with both debug and release, no Nintendo logo.

For BAR, with debug build, car colour is good, menu background is missing. With release build, car colour is messed up, menu background is there.

This is all with clang/Android.

**Comment by gizmo98** [comment]
I have updated my branch some minutes ago. I have added more input register definitions. Can you try again?

**Comment by loganmc10** [comment]
I get:

```
src/Neon/3DMathNeon.cpp:35:7: error: invalid input constraint '0' in asm
      : "0"(m0), "1"(m1), "2"(dest)
```

**Comment by gizmo98** [comment]
GCC seems to be much more tolerant. There was not even a warning. I have replace "+r" with "=r".

**Comment by loganmc10** [comment]
No difference on my phone, same issues remain

**Comment by gizmo98** [comment]
I added one more commit. Clang seems to be sensitive if Condition code register is missing.  https://github.com/gonetz/GLideN64/commit/ac76278df48695268c07ecbd8939f8eb7604ea05

**Comment by loganmc10** [comment]
Still nothing unfortunately, and https://github.com/gizmo98/GLideN64/commit/70bc53af72aeee5e4e221a17ced596b3f6ede26c actually causes most of the graphis to disappear.

**Comment by gizmo98** [comment]
Fixed. I convert everything to Neon intrinsics. Neon intrinsics are more compatible and can be used with aarch64 as Welle. I will report when conversion is done.

**Comment by gizmo98** [comment]
@loganmc10 
I have converted all functions. Could you test this branch?
https://github.com/gonetz/GLideN64/compare/master...gizmo98:neon-fixes2

**Comment by fzurita** [comment]
I just tried it, the Nintendo logo is still black for GoldenEye. Does it work in your end with this version gizmo98?

**Comment by gizmo98** [comment]
@fzurita
I thought it is black. It looks like this: https://m.youtube.com/watch?v=TpYocIwoiYM. Logan wrote it disappears.

**Comment by fzurita** [comment]
Yes, that's what I meant, the whole screen is black and the spinning logo is not visible.

**Comment by gizmo98** [comment]
Ok. It works on my end then. Which Rom version are you using?

**Comment by fzurita** [comment]
A known good dump of the US version.

**Comment by fzurita** [comment]
And I can confirm disabling all the neon optimizations does fix it.

**Comment by fzurita** [comment]
I left the neon optimizations on, but disabled ```-ffast-math``` as a compiler option and that fixes it. I have the feeling it's related to that compiler flag.

**Comment by fzurita** [comment]
@gizmo98 I think you should still make a pull request since the intrensics version is better.

**Comment by loganmc10** [comment]
Ok I'll close this since it was related to a compiler flag, but I would agree that a PR for the code changes would still be good anyway, an arm64 version of mupen64plus-ae will probably materialize within the next year or two, so if these changes will make the NEON optimizations compatible with arm64 that will be worthwhile
