### ISSUE TITLE
Mario Kart 64 - Minor graphic glitches *Update*

### ISSUE THREAD

**Issue by Kidboy17** [gonetz/GLideN64#1756]
Noticed a couple glitches while playing Mario Kart 64. I'm using PJ64 2.3.2 with the newest GLideN64 WIP on default settings.

I circled in red the errors. As you drive closer, they disappear.
![mariokart1](https://user-images.githubusercontent.com/37382324/37494197-000a6cd0-2865-11e8-8129-6b3f737eff66.png)
![mariokart2](https://user-images.githubusercontent.com/37382324/37494200-058fc29a-2865-11e8-93b5-e566691c7689.png)
![mariokart3](https://user-images.githubusercontent.com/37382324/37494202-07c53a54-2865-11e8-9de3-642dbf4bde52.png)

On Rainbow Road, the Neon Light images don't appear correctly until you drive closer.
![gliden64_mariokart64_008](https://user-images.githubusercontent.com/37382324/37494249-3dbb33ac-2865-11e8-86dc-0da9b6b8079e.png)
![gliden64_mariokart64_009](https://user-images.githubusercontent.com/37382324/37494252-4384c294-2865-11e8-9eb9-c68004763266.png)

On DK Jungle Parkway, the trees have this faint blue outline
![gliden64_mariokart64_002](https://user-images.githubusercontent.com/37382324/37494389-d6f800c2-2865-11e8-819d-32422f46ebd3.png)
![gliden64_mariokart64_001](https://user-images.githubusercontent.com/37382324/37494442-10506c56-2866-11e8-80c4-4f53bf41d461.png)

Also, if you do not have "Render 2d elements in N64 resolution" you get lines across the characters in the select screen.
![gliden64_mariokart64_000](https://user-images.githubusercontent.com/37382324/37494299-75686784-2865-11e8-8dcb-9f0f92fcce59.png)

**Comment by theboy181** [comment]
The black lines on the 2d characters are normal(known issue) but the other issues you are reporting are starting to look hw repeated. Pm me on pj 64 and we can look a little closer if you want.

**Comment by theboy181** [comment]
Is that level or an object. Object may be part of the draw distance. I would try it with the dad hacks.

**Comment by Kidboy17** [comment]
I use the Extended Draw Distance GS hack you posted on Discord. It works wonderfully for this game. I believe its level and not object with the walls being closer than they should. Maybe the sword is considered level as well in the case.

**Comment by gonetz** [comment]
I suppose that currently only this issue can be fixed:
"On Rainbow Road, the Neon Light images don't appear correctly until you drive closer."
Could anyone give me a savestate to test it?

**Comment by Kidboy17** [comment]
[Mario Kart 64 (U).pj.zip](https://github.com/gonetz/GLideN64/files/2365055/Mario.Kart.64.U.pj.zip)

**Comment by johnmanko** [comment]
@Kidboy17 How is that patch applied?

**Comment by Kidboy17** [comment]
@johnmanko If you are talking about the Gameshark codes all you have to do is get the hexadecimal codes on the N64 Discord channel, copy and paste them in the GS section of emulator you are using. I'm using Project64

**Comment by oddMLan** [comment]
![a](https://user-images.githubusercontent.com/7278372/68377819-48be0400-0108-11ea-831f-765ea86b472d.gif)

>I suppose that currently only this issue can be fixed:
"On Rainbow Road, the Neon Light images don't appear correctly until you drive closer."

It happens on Angrylion too. And on real hardware as well: https://youtu.be/eJF-u9xWIH8?t=174
All the other issues happen in hardware as mentioned in https://github.com/gonetz/GLideN64/issues/1756#issuecomment-378404005

This issue can be closed.
