### ISSUE TITLE
VR Headset Crowd funding request

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1757]
@gonetz I hope that you will consider adding VR support to your project list. I would love to see you do a full Crowd funded campaign for VR support in GLideN64.

**Comment by gonetz** [comment]
I doubt that such campaign will be successful. Even if it will, I have no time resources to work on it. I barely can fix remaining issues.

There was a PR regarding VR support:
https://github.com/gonetz/GLideN64/pull/1552

May be somebody can take it and make it properly. I don't have VR Headset to test.

**Comment by justinmichaud** [comment]
@gonetz I have some time before school starts up again. I can take another crack at getting the VR support to work, if you let me know what you would and would not be willing to merge.

Cheers!
Justin

**Comment by gonetz** [comment]
As I understand, VR support from graphics plugin side is stereoscopic rendering.
Thus, I would like to see general support for stereoscopic rendering, with little-to-none changes on front-end side.
