### ISSUE TITLE
GlideN64 Won't Show FPS, VIS, Percent, or Others

### ISSUE THREAD

**Issue by pdrome** [gonetz/GLideN64#1758]
Seems like the font routing isn't working with Ubuntu 16.04.03 and 16.04.04. Maybe others as well.

Bisected to gonetz/GLideN64@30f56c9 by @Jj0YzL5nvJ.  Here is the original issue in m64p:

m64p/mupen64plus-GLideN64#62

**Comment by loganmc10** [comment]
mupen64plus has an OSD, and they just include the ttf file with the project (https://github.com/mupen64plus/mupen64plus-core/tree/master/data). I'll probably submit a PR tomorrow to have it search for a "font.ttf" file in the shared data directory before (or after) searching in the system paths

**Comment by gonetz** [comment]
@pdrome Yes, /usr/share/fonts/liberation fonts are not installed on Ubuntu by default.
I reverted 30f56c9: ed223c9

**Comment by pdrome** [comment]
Problem solved. Thanks!
