### ISSUE TITLE
Texture cache fails to save to disk

### ISSUE THREAD

**Issue by Nerrel** [gonetz/GLideN64#1761]
Using Project64, current dev build (I've patched this to enable it to use 4GB of RAM instead of 2GB)
Windows 10x64

I'm working on a texture pack that currently takes up 350mb on disk.  This ends up using an entire Gb of memory when loaded, so it's important to use **save texture cache to hard disk** and **compress texture cache** to keep the size down and avoid long loads.  

The textures I've loaded should save to the cache after ending emulation, and the total size of the cache file should be 416mb.  Instead, after the cache file is created the emulator hangs after the cache reaches 160-190mb in size and stops responding.   The emulator has to be closed at this point, or else it will eventually crash.  No error log is generated in GlideN64's plugin folder. 

It's possible that the cache will save correctly every rare once in a while, but _very_ rarely. This happened in GlideN64 2.0, but didn't seem to fail as consistently then.  In 3.0 and the newest development versions, the only way to successfully create a texture cache is to delete the failed partial cache file, load the texture pack again, then load a save state, which will force the textures to be saved to the hdd while emulator is still running.  This method works flawlessly every time.  

The pack I'm using is for Majora's Mask, located here:
https://mega.nz/#!TAlxUbhK!MK6mu2eJsSEBxLHqkxO-Wlrh3crNQYqR5ZCE-X3Fpn8

Let me know if there's any other information I need to provide, thanks.

**Comment by Nerrel** [comment]
Is no one able to reproduce this?  I assume I could get around this problem by uploading the cache file itself for players to use instead of the png textures, but it does seem problematic that the texture cache is so broken (at least in my experience).  Is it possible that this is the result of something wrong with the texture pack itself?  I tried downloading other large texture packs to test but they usually seem to be .dat files, not png images.

**Comment by Nerrel** [comment]
Thanks for looking into it.  The problem is that (without using a savestate) GlidN64 will attempt to create the texture cache after ending emulation- in Project64, by going to file>end emulation.  _This_ attempt almost always fails. 

After ending emulation, the cache file will appear in its folder and will begin to grow in size. 
![image of cache](https://c1.staticflickr.com/1/962/41829818211_d55a3a6fed_z.jpg)

 After getting to around 200mb, the cache stops growing and the program will just hang like this indefinitely unless it eventually crashes (the finished cache should be 450mb).  
![image of cache2](https://c1.staticflickr.com/1/910/27961808588_5b399f23b2_z.jpg)

If I click X to close P64 after the cache creation has frozen, P64 will usually still be active in my tasks list and consuming a large amount of CPU power:
![image of tasks](https://c1.staticflickr.com/1/976/40023407400_ce05e871fa_z.jpg)

It will often continue like that for hours.  I have to end the task to get it to stop, or restart P64 and have it alert me that the process is already active and then choose to close the old session.  The cache file will be left only partially complete.  

Not everyone has a savestate on hand, and asking users to create one and load it in order to generate a cache is a little convoluted.  It would be better if players could just load the texture pack once, then have the cache naturally generate when they end their play session, which is what GlideN64 attempts to do.

**Comment by gonetz** [comment]
So, the problem is with saving loaded cache to hdd. Ok, it is really the problem. I broke cache save when optimized cache load. It will be fixed.

**Comment by gonetz** [comment]
@Nerrel I made texture cache save right after the load from texture pack. User will have to wait not only for load but also for save, but it is more safe. Load from saved cache is as fast as before.

Build:
https://drive.google.com/file/d/1PZImeWoip4Bc1MSo8eDSnGYljE5_irMa/view?usp=sharing

**Comment by Nerrel** [comment]
That works for me.  With a big pack, I don't think the extra wait time really matters since the player is going to be waiting a while either way.  Thanks!
