### ISSUE TITLE
Space Station Silicon Valley - Multiple issues

### ISSUE THREAD

**Issue by Jj0YzL5nvJ** [gonetz/GLideN64#1764]
This game has many broken effects and details, some of them you don't notice them until you see the images in succession.

https://imgur.com/a/MwBwO
https://imgur.com/a/IeBOi
https://imgur.com/a/2EUDC

-  Textures that are only visible from camera angles near the edges of the screen.
-  Details that are only visible by deactivating LOD, the game incorporates its own "LOD", similar to the one used by Perfect Dark in the NPCs.
-  The static on the screens is always visible from a long distance even with `EnableNoise = False`.
-  The static on screen only looks correctly with `EnableFragmentDepthWrite = False`.
-  Extra overscan border by using `EnableFBEmulation = False`, for some strange reason.
-  Etc.

**Comment by olivieryuyu** [comment]
would you please provide savestates?

The "LOD" issue seems to be quite valid.

**Comment by Jj0YzL5nvJ** [comment]
¬¬u
It's the first level ...whatever: https://0x0.st/sB3c.zip

**Comment by Tasosgemah** [comment]
I can confirm some of these issues, i got the one described in the 3rd picture.

**Comment by Tasosgemah** [comment]
The screens still look wrong on the release 4

https://i.postimg.cc/65YVcV6N/2.png
