### ISSUE TITLE
Goldeneye broken skies

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1778]
After this commit, skies have a strange effect:

https://github.com/gonetz/GLideN64/commit/bdb0f7ca94df7fc127aa6b7190f9494c16f25905

Here is a screenshot after that commit:

![goldeneye-000](https://user-images.githubusercontent.com/11581687/38159722-6c1ba81c-347c-11e8-88d0-661c432a465a.png)

This effect only happens if the player is moving. One thing special about the sky is that it's drawn using LLE commands.

**Comment by gonetz** [comment]
Thanks! I'll check it ASAP.

**Comment by gonetz** [comment]
@fzurita I can't reproduce it on my PC. Do you have that regression with mobile device?

**Comment by fzurita** [comment]
Yep, mobile device.

**Comment by loganmc10** [comment]
I'll look into this on Monday

**Comment by gonetz** [comment]
Is it fixed now?

**Comment by fzurita** [comment]
Yep
