### ISSUE TITLE
Some PAL Games have a black border

### ISSUE THREAD

**Issue by Papermanzero** [gonetz/GLideN64#1781]
Some PAL games like Super Mario 64 (German Version) or Mario Kart 64 PAL have black borders.
Even if cropping is activated the black border is visible.
Means, it is not possible to play certain PAL games without black borders.
Especially the black border on top and bottom of the screen are not necessary.

**Comment by gonetz** [comment]
It is how these games are programmed. Super Mario 64 NTSC has buffer size 320x240. NTSC has 480 active scan lines, height of 240 allows the game to run in non-interlaced mode. PAL has 576 scan lines. Thus, there were two ways to port game to PAL without altering the game code:
* stretch 320x240 image to 320x288 screen  - image quality will suffer.
* add black boarders to vertically center the image.
The game uses black boarders approach. Plugin emulates it.
Disable frame buffer emulation if you don't like  black boarders in these games.
