### ISSUE TITLE
Paper Mario zoom-in when Mario approaches screen

### ISSUE THREAD

**Issue by NurioHin** [gonetz/GLideN64#1789]
I am using GLideN64 3.0 on Project64 2.3.2, playing the US version of Paper Mario.

When playing Paper Mario, in some rooms, if you walk 'toward the camera' the image will zoom in a little. It's a very sudden cut and as mentioned, only happens in certain rooms. So far, I saw it happen in a room in the Dry Dry Ruins and also in the sewers under Toad Town.
I don't have this issue with other graphics plugins, including GLideN64 2.0

![gliden64_paper_mario_001](https://user-images.githubusercontent.com/18533703/38468631-68aa6d8e-3b49-11e8-8755-692037dbb507.png)
Camera zoom is normal...

![gliden64_paper_mario_002](https://user-images.githubusercontent.com/18533703/38468639-74ae05f0-3b49-11e8-9ca8-8702ee1a9187.png)
Taking the tiniest step downward suddenly zooms the camera in by a fair amount

If you manage to stand right on the edge where it will zoom, it'll continually swap between zoomed and not-zoomed. And it even seems to stretch the image, judging by Mario suddenly growing slightly taller

I've tried changing various settings in GLideN64 3.0, but none of them seem to affect this behavior. I don't have any sort of cropping turned on, and I also tried changing the resolution to no avail.

Here is a savestate where Mario is in the sewers: [Paper Mario (U).pj.zip](https://github.com/gonetz/GLideN64/files/1887538/Paper.Mario.U.pj.zip)

**Comment by thecoreyburton** [comment]
I've experienced this too, but I could never reliably reproduce it. I was using a build I had compiled myself at the time, prior to August last year (and therefore prior to the 3.0 release) and at the time, I wasn't sure if it was something I had done during the build process.

It seems to occur infrequently throughout the game. Like you, I noticed it in Dry, Dry Ruins, along with also experiencing it in the game's ending, and more aggressively in Shooting Star Summit. There were definitely more cases, but I can't remember the specifics as it was a while ago now.

**Comment by TeconMoon** [comment]
I can also verify that this is an issue, the easiest spot in the game to reproduce the problem consistently so far has been Shooting Star Summit. I will post a video of the issue once I can get it recorded.

Usage:
- Project 64 2.3.2
- GLideN64 Public Release 3.0
- Clean Paper Mario USA 1.0 Rom

This has been tested with the default GLideN64 settings but I can try other settings if it will help isolate the issue.

**Comment by loganmc10** [comment]
I can reproduce the issue, I'll bisect to what commit caused this bug

**Comment by loganmc10** [comment]
@gonetz this is the commit that caused this issue: https://github.com/gonetz/GLideN64/commit/cebca46e0aa3a935a6bb039466079d3d9bcbff4e

It is very easily reproducible by using the save state posted in the first post (https://github.com/gonetz/GLideN64/files/1887538/Paper.Mario.U.pj.zip) and just walking down

**Comment by gonetz** [comment]
@loganmc10 Thanks! The commit introduces some optimizations, which sound reasonable for rects. Why update viewport if rects use screen coordinates? However, if it cause that issue, there is some side effect I missed.  It would be good to find, what happens there but it may take time. For now we can remove these lines
`gSP.changed &= ~CHANGED_VIEWPORT; // Don't update viewport
`

**Comment by gonetz** [comment]
Fixed

**Comment by gonetz** [comment]
@NurioHin please test and close if fixed.

**Comment by TeconMoon** [comment]
Is anyone able to post a build of the latest commit? I'd like to test this without setting up an environment to compile it myself

**Comment by Jj0YzL5nvJ** [comment]
[WIP Builds 3 - 02/May/2018](https://github.com/gonetz/GLideN64/issues/1574#issuecomment-385879877)

**Comment by NurioHin** [comment]
@gonetz Sorry, I must've missed the notification of your reply. I tested it now with [the version linked here](https://github.com/gonetz/GLideN64/issues/1574#issuecomment-385879877) and the issue is gone!
