### ISSUE TITLE
Copy Depth Buffer from RDRAM?

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1801]
Right now there are functions to copy the color buffer to/from RDRAM. But there only seems to be functions to copy the depth buffer to RDRAM.

It seems (and I could be wrong), that some games are modifying the depth buffer from the CPU. I think this may be what is causing this issue: https://github.com/gonetz/GLideN64/issues/1173

If I clear the depth buffer right after the wnd.swapBuffers() call, the graphics show up for the bottom player (though it still flickers down there).

Is this a valid theory? Could games be clearing (or modifying) the depth buffer from the CPU and we are missing it?

**Comment by fzurita** [comment]
For that issue, I think LLE commands are not being processed correctly. I think depth values are being calculated wrong.

It would be easy to test, just set depth values for LLE triangle commands to the furthest back. I think would work.

**Comment by loganmc10** [comment]
It worked before without framebuffer emulation, when gonetz modified things so that even without framebuffer emulation an FBO is used, since then it's broken whether or not FBE is enabled

**Comment by gonetz** [comment]
I suppose that depth issues in #161 are because depth buffer cleared by CPU.

**Comment by fzurita** [comment]
Could a fingerprint approach be used to find writes by the CPU like we do for color buffers?

https://github.com/gonetz/GLideN64/blob/master/src/FrameBuffer.cpp#L295

**Comment by gonetz** [comment]
> Could a fingerprint approach be used to find writes by the CPU like we do for color buffers?

Too much efforts imo. "Force depth buffer clear" option should solve the issue without overheads.

**Comment by gonetz** [comment]
I added "forceDepthBufferClear" option. If it will not help any game but Eikou no Saint Andrews I'll remove it from UI.

**Comment by AmbientMalice** [comment]
A lot of testing will be needed. Unfortunately, it doesn't properly fix Perfect Dark's Combat Simulator. Player 2's graphics improve, but there's constant flickering all over scene geometry.

**Comment by loganmc10** [comment]
Yeah I think multiplayer goldeneye will be the same, bottom screen is much better with force depth buffer clear, but it still seems to flicker every 3rd frame or something

**Comment by gonetz** [comment]
May be this hack need to be extended to fix multiplayer issues. Multiplayer may use several depth images.

**Comment by loganmc10** [comment]
Multiplayer is fixed ,so I don't know of any issues this would fix, I'll close it
