### ISSUE TITLE
Various Graphic Glitches in Pokemon Stadium

### ISSUE THREAD

**Issue by AlexN64gamer** [gonetz/GLideN64#1804]
When trying to play Pokemon Stadium 1 in HLE mode, trainer portraits doesnt show properly after you win a match, also I found some other glitchy stuff like Wartortle´s shell with a light blue line around, (instead of the normal white colour) or Sandshrew´s belly in the same light blue colour, im using Project64 2.3.2-202 (last stable release) and gliden64 3.0 with default config

**Comment by tony971** [comment]
Why report bugs from last stable release? It may have already been fixed. And even if this is the issue that causes it to get fixed, that still won't affect the last stable release.

https://github.com/gonetz/GLideN64/issues/1574#issuecomment-385879877

Try the latest build and see if you still have the issue.

**Comment by AlexN64gamer** [comment]
I think you didnt understand well, last stable release of project64 not GlideN64, so no matter the version of the emulator, the glitch will still be there if it is the pulgin fault, thanks for the feedback

**Comment by tony971** [comment]
> gliden64 3.0
