### ISSUE TITLE
Perfect Dark high-res mode issues

### ISSUE THREAD

**Issue by Legiaoday** [gonetz/GLideN64#1807]
When the high resolution option (in-game) is checked some 2D elements will not render properly in the multiplayer mode (combat simulator).
The ammo and weapon pickups will not show any names, the main menu will not show anything aside from the window itself and the round outline of the radar will not be rendered.

![base profile screenshot 2018 05 06 - 19 02 03 09](https://user-images.githubusercontent.com/25484098/39679338-6032fbfa-5172-11e8-8e54-5506e55bd587.png)

How it's supposed to look:

![1964_2018_05_06_19_06_49_686](https://user-images.githubusercontent.com/25484098/39679344-7cb027e4-5172-11e8-849f-0bbd073f9a40.jpg)

I'm using this [latest build ](https://github.com/gonetz/GLideN64/issues/1574#issuecomment-385879877) posted by gonetz. I tested it on Project64 2.4 and 1964.

Edit: Even with the high-res disabled, the outline around the radar still isn't rendered properly.

**Comment by gonetz** [comment]
Fixed
