### ISSUE TITLE
Corrupt graphics in Beetle Adventure Racing

### ISSUE THREAD

**Issue by jaburgeson** [gonetz/GLideN64#1813]
The VW Logo on all the Vehicles is corrupted and is not displaying correctly.

Verify problem by going to vehicle selection screen

Using mupen64, latest build from m64p.github.io

<img width="1440" alt="screen shot 2018-05-11 at 10 11 09 pm" src="https://user-images.githubusercontent.com/4240091/39952614-695070b0-5568-11e8-93df-b07347a8aea8.png">

**Comment by gonetz** [comment]
I can't reproduce it on my Redeon.
@jaburgeson, have you tried older versions? Public release 3.0 for example.
If older versions work for you it is regression. Otherwise it is graphics card driver bug.

**Comment by jaburgeson** [comment]
My apologies, I believe this was an issue with my RSP configuration.  All is resolved now.
