### ISSUE TITLE
Missing text in Donald Duck - Going Quackers

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1814]
![39978555-0d39785a-56f6-11e8-83dd-f664d571a44c](https://user-images.githubusercontent.com/848146/40005761-09e3d9d8-5756-11e8-9c5a-6463c10a29cb.png)

This only happens when you have "Enabled Native Res Texrects" on.

This is the commit that broke it: 5ccc40423feaa38e4c586aebeefd2bdd4c72cf66

**Comment by RibShark** [comment]
![gliden64_rayman_2_000](https://user-images.githubusercontent.com/1957489/40453972-eede2004-5ede-11e8-96d1-cbda636a1e02.png)
Rayman 2: The Great Escape (which runs on the same engine) has an identical issue.

**Comment by gonetz** [comment]
Should be fixed now. Please test with the latest WIP build.

**Comment by theboy181** [comment]
working here
