### ISSUE TITLE
Regression with TWINE

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1815]
![image](https://user-images.githubusercontent.com/9299743/40033277-828b42bc-57ac-11e8-9cee-57a2e7944d83.png)

Default settings with AA set and new WIP#3 release

**Comment by loganmc10** [comment]
I don't think that's a regression. That's how N64 Depth Compare looks with AA enabled

**Comment by theboy181** [comment]
Older versions with default settings do not do this with aa turned on though.

**Comment by AmbientMalice** [comment]
>Older versions with default settings do not do this with aa turned on though.

I can only assume the older version(s) you were testing were missing the ini files that apply the per-game overrides. TWINE has had N64 depth compared forced for as long as I can remember.

**Comment by theboy181** [comment]
That makes sense then, I keep forgetting that's a thing, Thanks. I guess the issue is when the INI forces it it allows the AA to enable, as when you use the GUI it will not.

**Comment by gonetz** [comment]
Yes, GUI prohibits user to enable incompatible settings. 
Need to disable MSAA in code when  N64 depth compare enabled.

**Comment by gonetz** [comment]
Fixed with 9fb63e0
