### ISSUE TITLE
Regression Donald Duck - Goin Quackers

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1816]
Game letters will partially disappear if 
![image](https://user-images.githubusercontent.com/9299743/40033320-c2a48750-57ac-11e8-97af-0f6009f6879d.png)
Is set to on.

**Comment by loganmc10** [comment]
Duplicate of https://github.com/gonetz/GLideN64/issues/1814

**Comment by gonetz** [comment]
Closed as duplicate.
