### ISSUE TITLE
Banjo-Tooie depth issues (Adreno)

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1817]
There are strange depth issues going on with Banjo-Tooie. This is straight from the intro area:

![banjo_tooie-001](https://user-images.githubusercontent.com/11581687/40115545-da134bd2-58de-11e8-9f27-377b8b58c2c3.png)

This is probably a recent issue since I remember this working fine.

Correct:
![banjo_tooie-002](https://user-images.githubusercontent.com/11581687/40115821-af67d172-58df-11e8-99c9-87692531ba95.png)

**Comment by fzurita** [comment]
This is on Adreno. If I disable fragment based depth, the issue goes away. @loganmc10 this may have to do with the recent changes to allow disabling of near place clipping on GLES.

**Comment by loganmc10** [comment]
Just to be clear, are we talking about the missing eggs?

**Comment by fzurita** [comment]
Whoops, not the missing eggs. Look at the water on the left.

**Comment by loganmc10** [comment]
It's possible, I don't see that issue on the desktop. I don't currently have my Android environment setup, can you try setting ```noPerspective``` to false in GLInfo.cpp? That will disable the near plane clipping stuff.

**Comment by fzurita** [comment]
Odd, I can't reproduce the issue in the latest master branch of GLideN64, I'll go ahead and close it.

**Comment by fzurita** [comment]
Never mind, I had forgotten to update GLideN64 settings so everything was going to defaults. It's actually still a problem.
Setting ```noPerspective``` to false fixes the issue.

**Comment by fzurita** [comment]
Forgot to re-open this.

**Comment by loganmc10** [comment]
Sorry I haven't forgotten about this, I just haven't had much time lately.

Can you try forcing this value to 0.0f:

https://github.com/gonetz/GLideN64/blob/master/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramUniformFactory.cpp#L711

I suspect it may be because of the polygon offset hack I had to put in place to get that working

**Comment by fzurita** [comment]
Setting the polygon offset hack to 0.0 doesn't fix it.

**Comment by loganmc10** [comment]
Weird ok, I tested this on my laptop using the noperspective stuff and I couldn't reproduce it. I wonder if it's an Adreno thing?

If you can, you could try a Shield device in GLES mode to see if it has the same issue, that's the only other device that supports this extension as far as I know

**Comment by fzurita** [comment]
I finally got around to trying this. The issues doesn't happen with the shield tv in GLES mode.

**Comment by fzurita** [comment]
On the plus side, Oreo seems to have fix the driver crash with N64 depth compare on the shield tv.

**Comment by fzurita** [comment]
Closing in favor of https://github.com/gonetz/GLideN64/issues/2435
