### ISSUE TITLE
Goldeneye regression?

### ISSUE THREAD

**Issue by Tasosgemah** [gonetz/GLideN64#1820]
When hugging walls in Goldeneye i get this sometimes

![untitled](https://user-images.githubusercontent.com/12124465/40451953-f73dd848-5ee8-11e8-8bfe-49daa2c14179.png)

Basically, i can see through polygons. This happens with the latest wip from the wip thread. I'm using PJ64.

**Comment by loganmc10** [comment]
I wasn't able to reproduce this (tried walking around the lookout tower at the very beginning of the Dam level). Do you have any non-default settings set?

**Comment by Tasosgemah** [comment]
No everything is default settings.

Maybe is the version i'm using of PJ64? I'm getting builds from here

http://hyvart.com/download/project64/ci/

This doesn't happen with Mupen.

**Comment by loganmc10** [comment]
oh I'm not sure then, I tested mupen64plus

**Comment by Tasosgemah** [comment]
OK NP. Thanks for the response. I'm going to dig a bit more myself, see if i can find what causes this.

**Comment by Tasosgemah** [comment]
Ok, seems the problem occurs in LLE mode. HLE is OK.

**Comment by gonetz** [comment]
@Tasosgemah could you test it again with the current master?

**Comment by Tasosgemah** [comment]
> 
> 
> @Tasosgemah could you test it again with the current master?

Sure, is it the "qt_build" in the releases?

**Comment by oddMLan** [comment]
> Sure, could i have a link for it?
@Tasosgemah

https://ci.appveyor.com/project/gonetz/gliden64/branch/master/artifacts

**Comment by Tasosgemah** [comment]
Seems fixed for me.
