### ISSUE TITLE
Blurry image output on Linux

### ISSUE THREAD

**Issue by newperson1746** [gonetz/GLideN64#1823]
Just compiled from git, along with mupen64plus git. System is a MacBookAir7,2 with Ubuntu 18.04 with Mesa 18.2.0-git (from ppa:oibaf)+ Intel HD Graphics 6000. I've noticed that the image output looks blurry compared to glide64mk2 at default settings. There is also a border when in fullscreen mode on GLideN64 that does not really exist in windowed mode at native resolution (320x240) Please open the screenshots and view them at 1x size (no scaling) so that the image is being kept at the original size without scaling artifacts. On chrome, you can do this by just clicking on the image and then clicking it again to magnify. Yeah, I know theres #1554 but that's overscan, and its something that glide64mk2 doesn't need to do to output a crisp image. 

1) glide64mk2 at default settings at 1440x900 fullscreen:
![glide64mk2](https://user-images.githubusercontent.com/19787725/40581393-2cbaa0c6-6125-11e8-8657-3e57be7b3e42.png)
Notice the crisp, _borderless_ screen with text that looks quite sharp. The borders on the sides are just due to the 4:3 mismatch with my laptop's 16:10 screen. It's not part of the actual render.
2) GLideN64 at default settings at 1440x900 fullscreen:
![gliden64_fullscreen](https://user-images.githubusercontent.com/19787725/40581397-42516a64-6125-11e8-859c-31db4dca4480.png)
Now notice the non-crisp, bordered screen with text that looks a little blurry. If you compare the circles at the very bottom of both screenshots, you'll notice that the GLideN64 border appears to cut off the curtains' circles a bit. If you compare them side to side, the glide64mk2 screenshot _does_ render the bottom edge of the circles that are cut off by the black bar in gliden64. If you look very closely, the gliden64 screenshot also cuts off a bit of the top of the screen. The glide64mk2 screenshot shows more of the bottom of the circles at the very top. On the right side of the screen, gliden64 is also cutting off a little bit of the edge when compared to glide64mk2. You see more of the partially in-screen circles on the right on glide64mk2 than on gliden64. However, gliden64 does _not_ cut off the left edge of the screen at all when compared to glide64mk2. In short, the top, bottom, and right edges of the screen are cut off. **This could be another issue?** On #1457 some of the border stuff is discussed. It probably is that GlideN64 is doing the proper thing and glide64mk2 is not, as was discussed there. I don't seek to harm or insult with this long report (I know, I'm sorry), I just wanted to see how and why the two handle it differently and why it blurs more on GlideN64. That's all.

3) GLideN64 at default settings at 320x240 windowed:
![gliden64_windowed](https://user-images.githubusercontent.com/19787725/40581405-68d78e70-6125-11e8-8bb1-80e21afea84b.png)
Notice that it looks perfectly crisp. Also, interestingly, notice that there is only a small border, and on the bottom only.

4) GLideN64 at default settings at 640x480 windowed:
![gliden64_640x480](https://user-images.githubusercontent.com/19787725/40581408-77423ca8-6125-11e8-9ce6-9de6af551319.png)
Notice that this too looks perfectly crisp. A border begins to appear at the bottom but not at the sides.

5) GLideN64 at default settings at 960x720 windowed:
![gliden64_960x720](https://user-images.githubusercontent.com/19787725/40581412-91b233f4-6125-11e8-8b2e-74f99cdacd02.png)
Notice that this too looks perfectly crisp. In fact, **all the resolutions that are integer multiples of 320x240 look perfectly crisp and seemingly identical to glide64mk2's crispness.** BUT, when I set it to a non integer resolution, like 748x561, then:
![gliden64_748x561](https://user-images.githubusercontent.com/19787725/40581415-b551b852-6125-11e8-8c23-638409028c9c.png)
Oh, that looks pretty bad. It seems like it is scaling an integer resolution multiple down to the requested size. (kind of how apple does retina scaling for macbook pros, they run at 3360x2100 for a 2x 1680x1050, which is then downscaled to a 2880x1800 physical panel) This would be fine, except that glide64mk2 can do 748x561 and still look perfectly crisp:

![glide64mk2_748x561](https://user-images.githubusercontent.com/19787725/40581426-f95b38d4-6125-11e8-93fe-612c08d02ae5.png)

Since it is not an integer multiple, the text is distorted (like on the doubled pixel border on the word 'created' in the screenshot,) but it maintains its sharpness and crispness. Also notice that there is no border here either. What might be the issue here? It's: 1) A screen border that only occurs in GLideN64. 2) A blurry screen output when rendering resolution is _not_ an integer multiple of 320x240. 

I wanted to see what the issue might be since glide64mk2 has neither of these issues. No pressure, I just want to see what might be up.

Even though its running on the default config (not changed at all except enabling the show rendering resolution options,) here is my GLideN64 section from the mupen64plus.cfg: 
```
[Video-GLideN64]

# Settings version. Don't touch it.
configVersion = 21
# Crop resulted image (0=disable, 1=auto crop, 2=user defined crop)
CropMode = 0
# Crop width pixels from left and right of resulted image (in native resolution)
CropWidth = 0
# Crop height pixels from top and bottom of resulted image (in native resolution)
CropHeight = 0
# Enable/Disable MultiSampling (0=off, 2,4,8,16=quality)
MultiSampling = 0
# Screen aspect ratio (0=stretch, 1=force 4:3, 2=force 16:9, 3=adjust)
AspectRatio = 1
# Swap frame buffers (0=On VI update call, 1=On VI origin change, 2=On buffer update)
BufferSwapMode = 0
# Frame buffer size is the factor of N64 native resolution.
UseNativeResolutionFactor = 0
# Bilinear filtering mode (0=N64 3point, 1=standard)
bilinearMode = True
# Max level of Anisotropic Filtering, 0 for off
MaxAnisotropy = False
# Enable color noise emulation.
EnableNoise = True
# Enable LOD emulation.
EnableLOD = True
# Enable hardware per-pixel lighting.
EnableHWLighting = False
# Use persistent storage for compiled shaders.
EnableShadersStorage = True
# Make texrect coordinates continuous to avoid black lines between them. (0=Off, 1=Auto, 2=Force)
CorrectTexrectCoords = 0
# Render 2D texrects in native resolution to fix misalignment between parts of 2D image.
EnableNativeResTexrects = False
# Do not use shaders to emulate N64 blending modes. Works faster on slow GPU. Can cause glitches.
EnableLegacyBlending = False
# Enable writing of fragment depth. Some mobile GPUs do not support it, thus it made optional. Leave enabled.
EnableFragmentDepthWrite = True
# Use GLideN64 per-game settings.
EnableCustomSettings = True
# Enable frame and|or depth buffer emulation.
EnableFBEmulation = True
# Copy auxiliary buffers to RDRAM
EnableCopyAuxiliaryToRDRAM = False
# Enable N64 depth compare instead of OpenGL standard one. Experimental.
EnableN64DepthCompare = False
# Force depth buffer clear. Hack. Needed for Eikou no Saint Andrews.
ForceDepthBufferClear = False
# Disable buffers read/write with FBInfo. Use for games, which do not work with FBInfo.
DisableFBInfo = True
# Read color buffer by 4kb chunks (strict follow to FBRead specification)
FBInfoReadColorChunk = False
# Read depth buffer by 4kb chunks (strict follow to FBRead specification)
FBInfoReadDepthChunk = True
# Enable color buffer copy to RDRAM (0=do not copy, 1=copy in sync mode, 2=Double Buffer, 3=Triple Buffer)
EnableCopyColorToRDRAM = 2
# Enable depth buffer copy to RDRAM  (0=do not copy, 1=copy from video memory, 2=use software render)
EnableCopyDepthToRDRAM = 2
# Enable color buffer copy from RDRAM.
EnableCopyColorFromRDRAM = False
# Texture filter (0=none, 1=Smooth filtering 1, 2=Smooth filtering 2, 3=Smooth filtering 3, 4=Smooth filtering 4, 5=Sharp filtering 1, 6=Sharp filtering 2)
txFilterMode = 0
# Texture Enhancement (0=none, 1=store as is, 2=X2, 3=X2SAI, 4=HQ2X, 5=HQ2XS, 6=LQ2X, 7=LQ2XS, 8=HQ4X, 9=2xBRZ, 10=3xBRZ, 11=4xBRZ, 12=5xBRZ), 13=6xBRZ
txEnhancementMode = 0
# Deposterize texture before enhancement.
txDeposterize = False
# Don't filter background textures.
txFilterIgnoreBG = False
# Size of filtered textures cache in megabytes.
txCacheSize = 100
# Use high-resolution texture packs if available.
txHiresEnable = False
# Allow to use alpha channel of high-res texture fully.
txHiresFullAlphaChannel = True
# Use alternative method of paletted textures CRC calculation.
txHresAltCRC = False
# Enable dump of loaded N64 textures.
txDump = False
# Zip textures cache.
txCacheCompression = True
# Force use 16bit texture formats for HD textures.
txForce16bpp = False
# Save texture cache to hard disk.
txSaveCache = True
# Path to folder with hi-res texture packs.
txPath = "/home/newhacker1746/.local/share/mupen64plus/hires_texture"
# Path to folder where plugin saves texture cache files.
txCachePath = "/home/newhacker1746/.cache/mupen64plus/cache"
# Path to folder where plugin saves dumped textures.
txDumpPath = "/home/newhacker1746/.cache/mupen64plus/texture_dump"
# File name of True Type Font for text messages.
fontName = "FreeSans.ttf"
# Font size.
fontSize = 18
# Font color in RGB format.
fontColor = "B5E61D"
# Force gamma correction.
ForceGammaCorrection = False
# Gamma correction level.
GammaCorrectionLevel = 2
# Show FPS counter.
ShowFPS = True
# Show VI/S counter.
ShowVIS = False
# Show percent counter.
ShowPercent = False
# Show internal resolution.
ShowInternalResolution = True
# Show rendering resolution.
ShowRenderingResolution = True
# Counters position (1=top left, 2=top center, 4=top right, 8=bottom left, 16=bottom center, 32=bottom right)
CountersPos = 8


```
UPDATE: I managed to "fix" the "issue" of the overscan borders on the right, bottom, and top edges. It looks even sharper than glide64mk2 now! No more blurriness :+1: The borders now look identical to glide64mk2 and don't cut off more than glide64mk2 on all three sides. All I had to do was `EnableFBEmulation = False`. Since it disables FBEmulation, I guess this has adverse effects, but I must be used to them already since this is how glide64mk2 has worked for years, and all the other nintendo 64 emulators that I've used and their graphics plugins like Jabo's Direct3D and the original Glide64. It looks awesome, but I guess this is not a "fix" but a downside as discussed in #1457. I like it however :+1: 
![gliden64_disablefbemulation](https://user-images.githubusercontent.com/19787725/40581652-1f318558-612c-11e8-82e9-5f247060c51d.png)
The internal resolution and rendering resolution debug infos disappeared as well. I guess that's also a side-effect of my disabling framebuffer emulation...

 Is there anything to do about the blurriness however? That seems like it still is an issue because with FB Emulation on it shouldn't be blurry at non-integer resolutions, or should it?

**Comment by AmbientMalice** [comment]
Regarding the right hand side, there is a single pixel border along the right hand side of the screen because a number of N64 games output garbage along the right hand edge. As you increase the resolution, the width of that column increases. It's a separate issue to the normal overscan stuff because it's compensation for a problem inherent in these games. The fix was discussed here. https://github.com/gonetz/GLideN64/issues/1246 GLide64 does not emulate the N64 Video Interface properly. That's why letterboxing tends to be broken and black borders tend to be missing. The reason why GLideN64 adds a black column along the right is to ensure that you don't get outputs like 239x240.

For reference, this is how it looks on my PC. That's a native resolution factor of 8, scaled to a 1080p output. Have you tried the native resolution factor? I personally don't use monitor resolution, and prefer to use a factor of native, which is then scaled for the screen. Emulators like Dolphin do the same thing.
![marioparty2-000](https://user-images.githubusercontent.com/10704701/40582073-6563bad8-61ad-11e8-94f0-f8be19f8905d.png)

Also, this is how the game looks on Angrylion's, which mimics an N64's native output.
![marioparty2-001](https://user-images.githubusercontent.com/10704701/40582062-314558ec-61ad-11e8-88dc-19090324dd46.png)

**Comment by gonetz** [comment]
Blurry image is result of Video Interface work. I explained how Video Interface emulated in several articles:
http://gliden64.blogspot.com/search?q=Video+Interface

The problem is that size of rendered frame buffer with picture is not necessary the same as size of output screen. Mapping may causes blurriness. Thus, it is better to use high level of native resolution factor, as AmbientMalice suggests. That way image will be scaled **down** with good chance to avoid blurriness.
Another way is to disable frame buffer emulation and get one-to-one correspondence of rendered and output buffers.

Anyway, "Blurry image" problem is not a bug and will not be fixed.
