### ISSUE TITLE
1080 Snowboarding title logo regression

### ISSUE THREAD

**Issue by Tasosgemah** [gonetz/GLideN64#1824]
![untitled](https://user-images.githubusercontent.com/12124465/40625969-4cc42cda-62be-11e8-8de8-c076769b34a0.png)
You can see the bottom of "1" there's something wrong.

Couldn't fix it with any option including default setting or native internal resolution.

Public 2 release doesn't have this issue.

**Comment by Tasosgemah** [comment]
May be related to this:

![untitled](https://user-images.githubusercontent.com/12124465/40627022-04b3eb7c-62c5-11e8-8bbc-4cc18b1355a4.png)

Bust A Move 2 - Arcade Edition (attract mode)

**Comment by theboy181** [comment]
Just noticed this too.. 

Here is a hack to get you through it, till the team looks into fixing it. Do you know what version this started at? 

![1080_hd_enhanced](https://user-images.githubusercontent.com/9299743/43085873-e7ea6e1e-8e50-11e8-82dc-abdc146d290d.gif)

1080 Snowboarding (JU) (M2)
HD Enhanced Hack

810A2F9C 0000
810A2F9E 0000
810F908E 43FF
81109A5A 3F00
81109A5C 4612
8109C4FA 5000
8109C4FC 0042

Note: Increased Draw Distance, and Level of Detail

**Comment by theboy181** [comment]
@gonetz can you please have a look at this when you can? Such a great game, that deserves to get some attention. Also the first game on the ROM list. ;)

**Comment by rez-** [comment]
confirmed fixed:
![1080_snowboarding-000](https://user-images.githubusercontent.com/10398036/45110547-e1db3e80-b142-11e8-8316-ad66160e24f8.png)
great work gonetz:)

**Comment by theboy181** [comment]
Nice work
