### ISSUE TITLE
NBA Live 99 messed up textures

### ISSUE THREAD

**Issue by Tasosgemah** [gonetz/GLideN64#1826]
There is something wrong with the player's skin textures

![untitled](https://user-images.githubusercontent.com/12124465/40691819-cc4d704e-63b6-11e8-8d58-aecbacc8445b.png)

**Comment by Tasosgemah** [comment]
@gonetz 
Not sure what WIP version was the last good one. It's still broken in the Public Release 3 but it looks fine in Public Release 2.

Also, in PJ64 it needs to uncheck "32-bit engine", else the polygons become corrupted. Not sure if this is an emulator thing or a plugin.

**Comment by LegendOfDragoon** [comment]
>Also, in PJ64 it needs to uncheck "32-bit engine"

Problem is, users don't contribute to the official RDB settings. Most games run fine with 32-bit engine enabled, but some games do require it (Sports games, Rare, Factor 5, Boss Game Studio, etc). I never tested this game, but I'll take your word for it and assume it's required for this game. I could do a pull request and improve the settings for a few games.

**Comment by Tasosgemah** [comment]
@LegendOfDragoon 

Can i ask, what's the point of this 32bit engine option? AFAIK it was a speed up setting maybe? But that was back to the Pentium 3-4 days so is it important to be enabled by default in most games? Theoretically, if it was disabled in all games none would have a problem with it?

**Comment by LegendOfDragoon** [comment]
>AFAIK it was a speed up setting maybe?

Yes, it is only for speed up, but it is a good one.

>But that was back to the Pentium 3-4 days so is it important to be enabled by default in most games these days?

He actually first implemented it in PJ64 2.x, so the option isn't that old. Same argument could be made for using async mode by default instead of sync mode, or using HLE instead of LLE. 

Considering most of the work has been done and all we have to do is tweak settings for a few games, it's worth keeping imo.

**Comment by rez-** [comment]
![nba_live_99-000](https://user-images.githubusercontent.com/10398036/45109237-3da3c880-b13f-11e8-8925-12295847a619.png)
confirmed! 👍
