### ISSUE TITLE
Tom & Jerry / PPG CHEMICAL X: texture issues

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#183]
It is the same developer for both games and there is same texture issues

![tom](https://cloud.githubusercontent.com/assets/8987490/5372066/73a45e30-8043-11e4-9aaa-d42ba6f827af.jpg)
![dssdfsdfddd](https://cloud.githubusercontent.com/assets/8987490/5372068/7848884e-8043-11e4-861e-1ebdc122ae08.jpg)
![sdfdfdfsdf](https://cloud.githubusercontent.com/assets/8987490/5372069/7bad49ac-8043-11e4-818b-99001fe327d4.jpg)
![dsd](https://cloud.githubusercontent.com/assets/8987490/5372072/7e60af18-8043-11e4-810a-7886ad2d97d0.jpg)

**Comment by gonetz** [comment]
Fixed
