### ISSUE TITLE
N64 Depth Compare

### ISSUE THREAD

**Issue by AlexN64gamer** [gonetz/GLideN64#1830]
Which games should have N64 depth compare enabled? does it affect other games if its permantly active?

**Comment by gonetz** [comment]
You may check custom ini for games, which need it:
https://github.com/gonetz/GLideN64/blob/master/ini/GLideN64.custom.ini

> does it affect other games if its permantly active?

Sure. Almost all games use depth compare. N64 depth compare incompatible with MSAA.
If you have MSAA disabled, all games should work as good or better than with standard depth compare.

**Comment by thecoreyburton** [comment]
@gonetz is there any chance of compatibility between MSAA and N64 depth compare in the future?

**Comment by gonetz** [comment]
I don't see how to make writes to image textures MSAA compatible. AA techniques based on image post processing can be used with N64 depth compare.

**Comment by thecoreyburton** [comment]
Good idea! From experience, post-processing AA filters are never quite as good as SSAA or MSAA, but such a method would definitely be a nice alternative to have for situations where n64 depth compare is required,

**Comment by AmbientMalice** [comment]
Personally N64 depth compare should probably be enabled by default. It helps heaps of games in really subtle ways. As an example, Perfect Dark and the Banjo games need it to handle decal clipping properly.

**Comment by oddMLan** [comment]
Any kind of postprocessing antialiasing would be possible with Reshade if it got proper support for GLideN64 :/

**Comment by mudlord** [comment]
Or added a extra FBO pass from the post processing that already exists. The FXAA shader is trivial at best. SMAA, not so much.

**Comment by gonetz** [comment]
Is there a way to test FXAA or SMAA with other graphics plugins? If they can produce good result, we can add them as post-processor.

**Comment by thecoreyburton** [comment]
If it's just for a visual comparison, you should be able to force such options in most modern graphics card control panel software. Prior to GLideN64, I forced SSAA on Glide64 this way.

**Comment by gonetz** [comment]
I see only FXAA and MFAA on NVIDIA control panel. FXAA is good, but is it worth to implement in the plugin if user just can enable it in the control panel?

**Comment by AmbientMalice** [comment]
>FXAA is good, but is it worth to implement in the plugin if user just can enable it in the control panel?

The number of users willing to poke around in the Nvidia control panel is extremely small. Also, Intel GPUs don't can't force FXAA through drivers. Don't think AMD can do it, either.

**Comment by thecoreyburton** [comment]
> Intel GPUs don't can't force FXAA through drivers. Don't think AMD can do it, either.
That's correct. AMD have their own post-AA that functions in a similar way.

I think having it implemented in GLideN64 has many benefits. As @AmbientMalice said, many users probably will not be willing to use control panel settings. It also prevents users who are unable to access such an option from being unable to have anti-aliasing while N64 depth-compare is enabled. It will also provide some consistency as to the output from the plugin across machines.

**Comment by DonelBueno** [comment]
GLideN64 log is saying my GPU doesn't support N64 depth compare, but I think it should.

I'm using a GTX 770 with the latest drivers from NVIDIA, it does support OpenGL 4.5 AFAIK. What extensions are required for N64 depth compare?

**Comment by gonetz** [comment]
N64 depth compare requires image textures. Image textures enabled if 
either OpenGL version >= 4.2 or `GL_ARB_shader_image_load_store` extension supported.

**Comment by loganmc10** [comment]
Since he optimizations it also requires one of several extensions. Unfortunately the GTX 770 doesn't support these extensions (GL_INTEL_fragment_shader_ordering or GL_ARB_fragment_shader_interlock)

**Comment by DonelBueno** [comment]
Actually, it only supports OpenGL 4.3 =/

**Comment by Kidboy17** [comment]
I have a 780ti and it supports up to 4.4. So is it pointless for me to have n64 depth compare enabled if I don't have 4.5?

**Comment by loganmc10** [comment]
Its not really about what OpenGL version you have, although 4.2 would be the minimum for N64 Depth Compare.

The extensions needed aren't currently part of any OpenGL version as far as I am aware, they are extensions to the OpenGL spec, only supported by some cards, I don't believe the 780 supports them either

**Comment by loganmc10** [comment]
> Isn't it possible to drop these optimizations but to keep the "N64 depth compare" feature in cases where the card doesn't support OpenGL 4.5, but does support Open GL 4.2-4.4?

Sorry I didn't see this before. The argument I made when I submitted these changes was this:

Non-optimized N64 Depth Compare is incredibly slow, not playable on a lot of cards. If the goal is to one day have N64 Depth Compare be a default option (which is ideal), then it needs to be able to perform well. Right now, we could have N64 Depth Compare default to "on" and it would perform well, on computers that don't support the extension, it would be turned off and they would perform well.

If you allowed the non-optimized path and made it a default option, many computers would perform terribly with the default settings

**Comment by DonelBueno** [comment]
Good point, but I remember it being fast enough when I tested it some time ago.

You should allow users to use the non-optimized path via ini edit, while keeping the default option to be off.

**Comment by gonetz** [comment]
Support for optimized and not-optimized version is painful for developers and confusing for users. 
Currently the situation is simple and indeed the option can be on by default. If your hardware supports necessary features, N64 Depth Compare will work well for you.
