### ISSUE TITLE
Feature: Profiles

### ISSUE THREAD

**Issue by gonetz** [gonetz/GLideN64#1836]
I implemented profiles support for **zilmar-spec** version.
Now all settings belongs to some profile.
You may have as many profiles as you need.
All profiles saved in the GLideN64.ini file.

You may add, remove or switch profiles when no game is running.
To add profile click to current profile name, edit it and press 'Add' button.
New profile created from the current one, that is it have the same settings as the current profile. You may reset new profile to defaults as usual.
Switch between profiles causes immediate settings reload.
If you made some changes and switched to another profile, your changes will be discarded. When you press OK button, current settings saved to current profile. You may also remove current profile.

Note: now plugin does not reset GLideN64.ini to defaults when config version changed. If you will switch to profile with obsolete settings, plugin will read all actual settings from this profile and then update it.

When game is running, manipulations with profiles disabled. Settings behavior depends on  "Use per-game settings" option:
* If "Use per-game settings" option is enabled, custom settings override profile ones. When you open configuration dialog during gameplay, you see settings for the current game. If there are no per-game settings for current game in GLideN64.custom.ini, all settings will be taken from the current profile. If you press OK, all settings with non-default values will be saved to GLideN64.custom.ini as custom settings for the current game. Current profile not changes.
* If "Use per-game settings" option is disabled, all your changes in settings will be saved to the current profile.

I need your feedback and bug reports.

Test build:
https://drive.google.com/file/d/11haUox0lBmQ_Uout7x-Qd7O213Jti0hc/view?usp=sharing

**Comment by AlexN64gamer** [comment]
Seems like a usefull feature, Ill give it a try

**Comment by gonetz** [comment]
In master.

**Comment by oddMLan** [comment]
Important QoL suggestion.

When "Per-game settings" is enabled and a game is loaded, the "Restore Defaults" option should REMOVE the game entry from GLideN64.custom.ini, thus making it use the global settings.

When configuring the global settings, "Restore Defaults" is fine working as-is now.
