### ISSUE TITLE
turok incorrect mips mapping 

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1839]
jabo (seem correct)

![jabo](https://user-images.githubusercontent.com/8987490/41311435-9160b83c-6e84-11e8-9cf1-c76f89186a64.jpg)

Gliden64 (looks weird)

![gliden64](https://user-images.githubusercontent.com/8987490/41311445-99d1dbd6-6e84-11e8-8f73-e5d502141d6a.jpg)

**Comment by gonetz** [comment]
Is it a regression?

**Comment by AmbientMalice** [comment]
Jabo's is wrong, though. This is how it looks on Angrylion's. I think it's a texture blending effect.
![turok_dinosaur_hunte-002](https://user-images.githubusercontent.com/10704701/41330635-f5635c8e-6f17-11e8-9043-3cd3ba045a91.png)

**Comment by olivieryuyu** [comment]
here how it looks like with PR1.1

![pr1](https://user-images.githubusercontent.com/8987490/41332290-8b981b12-6edd-11e8-859d-a3b30f3c89e8.jpg)

it changed as from PR1.2 so it would be between 1.1 and 1.2 that the change occured.

**Comment by olivieryuyu** [comment]
here with angrylion at the exact same place (better for comparison)

![lle an](https://user-images.githubusercontent.com/8987490/41332395-fb5fd232-6edd-11e8-9269-eec4fcf35b58.jpg)

**Comment by gonetz** [comment]
I don't see much difference between GLideN64 and  angrylion's plugin.

**Comment by olivieryuyu** [comment]
You mean with current version or 1.1?

**Comment by gonetz** [comment]
Screen shot form the current version looks close to screen shot from angrylion's plugin. Difference is subtle.

**Comment by olivieryuyu** [comment]
Ok let s close then
