### ISSUE TITLE
International Superstar Soccer 98

### ISSUE THREAD

**Issue by AlexN64gamer** [gonetz/GLideN64#1845]
this game is broken in its PAL version, NTSC works ok, but trying to load the PAL version with GlideN64 3.0 results in a black screen with the game being emulated beyond the right border of the screen

**Comment by theboy181** [comment]
Try to duplicate the settings form the NTSC version to the PAL version. I think I remember defining the settings on this game but not the PAL counter part

**Comment by theboy181** [comment]
Why PAL btw?

**Comment by AlexN64gamer** [comment]
because PAL version has World Cup France 98 national teams squads updated and licenced, while the NTSC version only has the kits, but not the names of the players, I tried same setting as NTSC on PAL but it doesnt seem to change anything

**Comment by gonetz** [comment]
Fixed. mupen64plus build van be found in artifacts for 2a677a23:
https://ci.appveyor.com/project/gonetz/gliden64/history
