### ISSUE TITLE
GB Tower on Pokemon Stadium 1 and 2

### ISSUE THREAD

**Issue by AlexN64gamer** [gonetz/GLideN64#1846]
Im sorry to post about this matter again, specially to Sergey cause he knows I already posted a while ago about the same, but I posted about the Game Boy Tower not working in project64 in their github, and they tested pk stadium 2 with Angrylions rdp plus plugin and it works, some guy told me that if it doesnt work with my favorite video plugin (GlideN64) but does with Angrylions, that means the problem is GlideN64, what do you think about this? and if that so, would there be a way to make that game mode work with GlideN64?

**Comment by gonetz** [comment]
Please explain, how to run it with Project64 and Angrylions plugin and where GlideN64 fails.

**Comment by olivieryuyu** [comment]
do u have a save state? 

I understood that there a small specific ucode at this place.

**Comment by Jj0YzL5nvJ** [comment]
A save state in this case has no use. Firstly, you need a GB emulator to generate the Flash RAM files (* .sav) for the GB/GBC ROMs.
https://youtu.be/zmYwHsMsA9w

See [Source/nragev20/README.txt](https://github.com/project64/project64/search?q=%22GB+Tower%22&unscoped_q=%22GB+Tower%22) and [this](https://github.com/project64/project64/issues/1461#issuecomment-398613463).

In mupen64plus, modifying with the value 'SiDmaDuration' has effects in GB Tower. Between 16384-65536 ...with 65537 overflows?

**Comment by AlexN64gamer** [comment]
in order to run it on Project64 with Angrylions plugin, you just need to have a .sav file which is your saved gameboy game, and .rom which is the "cartridge" that your going to "insert" into the transfer pak, which is emulated by Nrage plugin (comes by default with Project64 lastes build) go to input settings, and in the last tab, select "transfer pak" in the "game" directory select the pokemon red, blue or yellow .rom, and in the "save" directory select the .sav file which should be in the same folder as the game, then start emulation and go to GB Tower, it should load the game properly, but with a very poor framerate, (unplayable) and only in Pokemon Stadium 2, PK stadium 1 doesnt even past the loading screen, alltough it correctly displays the pokemon from your party, which GlideN64 doesnt do, so, I think that it likely has to do with graphics plugin

**Comment by LegendOfDragoon** [comment]
>it should load the game properly, but with a very poor framerate, (unplayable)

This is due to a problem with pj64's recompiler. You can use cpu interpreter for better performance in the meantime, ironically. This could be fixed by fixing the advanced block linking code, since that would get rid of the excessive exceptions.

**Comment by AlexN64gamer** [comment]
I used cpu interpreter with both games, (stadium 1 and 2) stadium 2 only gets a few more frames, but still to slow, stadium 1 gives a black screen after loading, settings are the same (Angrylions, Nrage input)

**Comment by gonetz** [comment]
@AlexN64gamer Such scenario is too much for me. I don't have time for these manipulations. Could you give me archive with emulator and roms/saves all properly set up, so I could just run the emulator and see the problem?

**Comment by AlexN64gamer** [comment]
ok, I will Sergey, im setting it up to send you

**Comment by purplemarshmallow** [comment]
I tested it and I would say there is no problem on the gfx plugin side

**Comment by AlexN64gamer** [comment]
@purplemarshmallow How can you say there is no problem on the gfx plugin side? I have tested GB towe in both Angrylions and GlideN64, Pokemon Stadium 1 it doesnt even boot on both plugins, Pokemon Stadium 2 Angrylions boots but fps is EXTREMELY slow, and GlideN64 doesnt even boot, so obviusly gfx plugin has something to do with it, of course I understand there is an important part from the emulator itself, Ive already wrote in the Project64 github, and let them know the problem

**Comment by LegendOfDragoon** [comment]
I think this issue can be closed. I've tested performance of graphics done on cpu and it wasn't particularly slow for demos. I'm going to trust purplemarshmallow on this one.

Stadium 1 just doesn't work and is an emulator issue. Has nothing to do with graphics plugins. Stadium 2 is slow because of PJ64 as I've already stated.

**Comment by purplemarshmallow** [comment]
>I have tested GB towe in both Angrylions and GlideN64, Pokemon Stadium 1 it doesnt even boot on both plugins, Pokemon Stadium 2 Angrylions boots but fps is EXTREMELY slow, and GlideN64 doesnt even boot, so obviusly gfx plugin has something to do with it

@AlexN64gamer the GB tower does boot for me with GLideN64 in Stadium 2. Maybe there's a problem with your config. What RSP plugin do you use? What PJ64 version? All default settings?

Have you tried GLideN64 in LLE mode? It should work in both HLE and LLE but maybe it helps to find the problem
