### ISSUE TITLE
Ocarina of Time Link's portrait missing with N64 deph compare

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#1850]
Link's portrait in the equipment subscreen is missing if N64 depth compare is enabled
![gliden64_the_legend_of_zelda_000](https://user-images.githubusercontent.com/7283660/42124093-1e4afb8c-7c5d-11e8-92f3-b09fa4bb6af9.jpg)

**Comment by gonetz** [comment]
Fixed

**Comment by purplemarshmallow** [comment]
fixed
