### ISSUE TITLE
Black Screen on Intel HD Graphics 3000

### ISSUE THREAD

**Issue by tjd2** [gonetz/GLideN64#1851]
I have HP elitebook 2560p with Intel HD graphics 3000
GlideN64 public release 2.0 crashes after launching any game.
GlideN64 latest master displays black screen with stuttering audio.
Any idea what can i do?
Other plugins like glide64, Jabo direct3d (and games like Mafia II) work fine. I am using HP drivers. Should i try official?

**Comment by loganmc10** [comment]
I don't think that card supports OpenGL 3.3 (on Windows anyway), which is the minimum required for GLideN64

**Comment by tjd2** [comment]
Yes. My graphics card is crappy. At least Glide64 works (but flickers in Combat Simulator. Any idea why? It can be fixed only by disabling framebuffer emulation, which breaks some effects)

**Comment by StenApp** [comment]
The official drivers don' support an OpenGL version higher that 3.1

https://de.wikipedia.org/wiki/Intel_HD_Graphics

**Comment by gonetz** [comment]
Closed because "The official drivers don't support an OpenGL version higher that 3.1"
