### ISSUE TITLE
Borderless fullscreen possible?

### ISSUE THREAD

**Issue by daninthemix** [gonetz/GLideN64#1852]
Just wondering if borderless fullscreen is possible with PJ64?

Proper fullscreen is annoying because it always switches to a window when losing focus (for example when clicking around on a second screen, while PJ64 / Glide is fullscreen on monitor 1. It works fine in a window as you'd expect, but we need the window to fill the screen, without the PJ64 menus.

**Comment by LegendOfDragoon** [comment]
I believe this fork of angrylion, uses borderless https://github.com/ata4/angrylion-rdp-plus/releases/download/r7/angrylion-plus.dll

Try testing that plugin, so that you can find out whether borderless solves your issue.

**Comment by Jj0YzL5nvJ** [comment]
That's a feature request for PJ64, unless they implement a non-exclusive fullscreen mode. Your best option is to [forcefully inject a fake fullscreen mode](https://pcgamingwiki.com/wiki/Glossary:Borderless_fullscreen_windowed).

**Comment by LegendOfDragoon** [comment]
>That's a feature request for PJ64, unless they implement a non-exclusive fullscreen mode

It's up to the video plugin, not emulator.

**Comment by daninthemix** [comment]
@Jj0YzL5nvJ I tried Borderless Gaming and it removed PJ64's title bar but didn't remove the menus or the status bar at the bottom :-/

**Comment by Jj0YzL5nvJ** [comment]
Hmm... GameCompanion - [Exclusive Virtual Fullscreen/Window](https://youtu.be/tbjxgCPreIw?t=2m21s)

**Comment by daninthemix** [comment]
Nope - gives me a fullscreen view that only shows the top-left one quarter of the PJ64 output window.

**Comment by Jj0YzL5nvJ** [comment]
Then good luck, you need a "non-exclusive fullscreen mode" or a "non-GUI borderless windowed mode".
In theory, a virtual desktop can do the trick, but I don't think many can fake the exclusive mode. PJ64 needs to implement a non-exclusive mode for multi-monitors.

**Comment by daninthemix** [comment]
Well, this is slightly mad but with TWO programs together I can get what I want.

1) Fullscreenizer will hide the bottom status bar.
2) Borderless Gaming will hide the top menu bar.

**Comment by gonetz** [comment]
How this issue related to GLideN64?
Which fixes you expect from graphics plugin?

**Comment by gonetz** [comment]
Reopen if some steps from plugin's side are necessary.
