### ISSUE TITLE
Near Plane Clipping issue with GLideN64 and AL+ ( not on HW, or AL Vanilla)

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1855]
![gameover](https://user-images.githubusercontent.com/9299743/42361386-12520682-80a3-11e8-83d5-5e497bc9375a.gif)

Works fine in JABO, and IN AL RDP  looks like it might be an OPENGL issue. AL+ has same issue.

**Comment by ata4** [comment]
In Angrylion+, it appears to be related to the [branchless clipping optimization](https://github.com/ata4/angrylion-rdp-plus/commit/1e79070ffa6bf6ad80ba2753c917d1a8d3319f8c#diff-4aed20957cd1293af790d37ed0c91cdfR170). Restoring the original AL code fixes the issue. Not sure if GLideN64 uses the same optimization, though.

**Comment by theboy181** [comment]
Its a mystery on GLideN64 then.

**Comment by theboy181** [comment]
might be same issue shown here

https://github.com/gonetz/GLideN64/issues/289

**Comment by theboy181** [comment]
[F-ZERO X (U).pj5.zip](https://github.com/gonetz/GLideN64/files/2335119/F-ZERO.X.U.pj5.zip)
using this save state fly off the edge to see the issue described above.

Looks like F-Zero does not share the same CRC like aerofighter

https://github.com/gonetz/GLideN64/issues/289

**Comment by gonetz** [comment]
Yes, it is also near plane clipping issue.

**Comment by gonetz** [comment]
Fixed

**Comment by theboy181** [comment]
:). This is great stuff.  Was I at all helpful in these fixes?

**Comment by gonetz** [comment]
Sure! Thanks :)
