### ISSUE TITLE
Texture Cache corruption

### ISSUE THREAD

**Issue by DonelBueno** [gonetz/GLideN64#1857]
When you activate "Save enhanced texture cache to hard disk" and any texture scaling option, some games textures become corrupted on the second run (when the cache is actually going to be used).

Exiting from full screen to windowed also has the same effect, even if  "Save enhanced texture cache to hard disk" is not checked.

Here is the list of games I own that present the issue:

007 - The World Is Not Enough
1080° Snowboarding
Mario Kart 64
Kirby 64

It works on public release 2.0, but not on public release 3.0. So it's a very old issue.

**Comment by gonetz** [comment]
Could you give me screen shots from Mario Kart 64 as example of the problem?

**Comment by James-Strich** [comment]
I think I'm having this same issue with a Zelda pack. On the second run the screen just goes black.

**Comment by DonelBueno** [comment]
@gonetz sorry, I hadn't seen your comment before. I coudn't reproduce the issue on Mario Kart without the texture pack I use, so here are screenshots from Kirby 64 (no texture pack used):

![project64_2018_10_13_15_41_03_823](https://user-images.githubusercontent.com/4239694/46908873-82214180-ceff-11e8-896d-d127898370c1.png)
![project64_2018_10_13_15_41_18_012](https://user-images.githubusercontent.com/4239694/46908874-82b9d800-ceff-11e8-84a7-4690ca2a0bfe.png)

**Comment by gonetz** [comment]
@DonelBueno I fixed an issue with enhanced textures load. It can be related to this issue. Please check with latest WIP build from #1574

**Comment by DonelBueno** [comment]
@gonetz I just checked and it still happens =/

**Comment by gonetz** [comment]
I have similar issues with HD textures from here #1885
Texture mapping code needs serious modifications to fix that.

**Comment by DonelBueno** [comment]
The build on #1885 fixes all the issues on this topic =D

I have no words to describe my gratitude, thank you very much!

**Comment by gonetz** [comment]
Great! I'm moving  in the right direction then. Thanks for testing!
