### ISSUE TITLE
F-Zero X regression

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1859]
Using Render 2D elements in N64 resolution causes black blocks around texts in game.

![image](https://user-images.githubusercontent.com/9299743/42719567-8b019fb4-86cc-11e8-8b1f-603bb4adfa54.png)

**Comment by theboy181** [comment]
There is also the introduction of these lines in the transition now when you press start.

![image](https://user-images.githubusercontent.com/9299743/42719624-b7ad8f7c-86cd-11e8-9811-cf751cbfc095.png)

**Comment by gonetz** [comment]
Is not it fixed in latest WIPs?

**Comment by theboy181** [comment]
I’ll check when I get back from my camping trip

**Comment by gonetz** [comment]
I close it as it is fixed for me. Please reopen if the problem still exists.
