### ISSUE TITLE
Kirby 64 - Strange red lines in credits.

### ISSUE THREAD

**Issue by CharlesCorrin** [gonetz/GLideN64#1861]
Using the most recent build for GlideN64 at the time of this writing (compiled by Gonetz himself) the credits are messed up. There's a strange red circle around the pictures. Some of the pictures also have red lines in them.

You can see how it's supposed to look starting at 10:05 of the following video:
https://www.youtube.com/watch?v=mEnuTQaTLYk

The options are mostly set to their defaults. I only changed it to use native N64 resolution and N64 3-point and disabled the "use emulator help to read/write frame buffers" option.

The emulator is a current (as of this writing) build of Project64 from emucr.

CPU: Pentium G3258
GPU: GeForce GTX 750 Ti

Here's a save state where you can see the problem easily:
[Kirby 64 - The Crystal Shards (U).pj.zip](https://github.com/gonetz/GLideN64/files/2194941/Kirby.64.-.The.Crystal.Shards.U.pj.zip)

**Comment by olivieryuyu** [comment]
confirmed. Seems a filtering issue of same kind...

**Comment by CharlesCorrin** [comment]
As of the newest GlideN64 build released by Gonetz (July 24th edition), this bug is still occurring.

**Comment by CharlesCorrin** [comment]
Update for the August 12th 2018 build: this problem is no more. Thank you and great job. :3
