### ISSUE TITLE
Save state load will undo GFX settings ( profile bug)

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1862]
I saved a state when I had render 2d elements selected. I changed the setting (disabled), then loaded (PJ64) the render 2d setting got changed back.. 

Not sure if Im liking the new profiles. Seems bugged.

**Comment by gonetz** [comment]
Is not it the same bug as #1879?

**Comment by gonetz** [comment]
Should be fixed now. Please test.

**Comment by theboy181** [comment]
Oops. Yes all fixed.
