### ISSUE TITLE
Super Smash Brothers Regression

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1863]
with latest build SSB64 has a regression with the 2D stage elements. I think this was found in some of the older plugins too.

![image](https://user-images.githubusercontent.com/9299743/42766536-9b244b3a-88cf-11e8-8325-f386ddc3e652.png)

**Comment by weinerschnitzel** [comment]
Looks like insert matrix issue that Rice Video used to have. Does #1835 affect this?

**Comment by theboy181** [comment]
I tired to ask what this would do, and no one took the time to explain.. If this is caused by this commit, then I fear for GLideN64's future. There have been many regressions lately, and I think that the project is just accepting things without properly testing first.

I do hope there is some traction on the many regressions that have been reported lately.

**Comment by weinerschnitzel** [comment]
It's a regression prone type of project, but there are some competent people fixing things and keen eyed people reporting issues properly. And consistently I'm confident that we are ahead of the regression game. No worries here.

**Comment by gizmo98** [comment]
@theboy181 
Savestate please! I will try to bisect the wrong commit.

**Comment by theboy181** [comment]
All you need to do is go to vs mode and pick dreamland stage

**Comment by gizmo98** [comment]
@theboy181
Thank you! I will take a look.

**Comment by gizmo98** [comment]
@theboy181 
I have found a small difference between my PR and gonetz refactored code. Results are different if fractional element is to be changed and the current matrix value is negativ. I need to check this modification later:
https://github.com/gonetz/GLideN64/commit/6993042c4ce6143a16de088eba3ee9fc2f7b3213#diff-69d8715ec7f9fd627ec4f5516edd003d

**Comment by theboy181** [comment]
Your code doesn’t have this issue, the refactoring does?

**Comment by gizmo98** [comment]
Yeah. Gonetz ask me to test the refactoring but i had no time because i was on vacation. So it's more or less my problem...

I checked the above posted commit. It fixes the problem.
