### ISSUE TITLE
Config_SetDefault() in mupen64plus version sets MaxAnisotropy to a boolean instead of an integer

### ISSUE THREAD

**Issue by LMLB** [gonetz/GLideN64#1867]
https://github.com/gonetz/GLideN64/blob/9fb63e0460bea5ca54b9df082cc722fec41cf9d4/src/mupenplus/Config_mupenplus.cpp#L60

This makes [mupen64plus-gui](https://github.com/m64p/mupen64plus-gui) (and maybe other front-ends) use a checkbox for `MaxAnisotropy` instead of a textbox (unless you manually change it to a number in `mupen64plus.cfg`).

**Comment by gonetz** [comment]
It was rather a typo. Fixed. Thanks for pointing on this.
