### ISSUE TITLE
Resident Evil 2 Texture Alignment Issues

### ISSUE THREAD

**Issue by CallistoNTG** [gonetz/GLideN64#1869]
Certain backgrounds have vertical lines. This problem is fairly easy to verify. Simply boot the game and enter the options menu.

![resident_evil_ii-011](https://user-images.githubusercontent.com/41622989/43136918-848bb786-8f8d-11e8-8320-f53243da0a48.png)
![resident_evil_ii-012](https://user-images.githubusercontent.com/41622989/43136920-84d14af8-8f8d-11e8-9711-a8721d9536d3.png)

**Comment by gonetz** [comment]
Fixed in native res with "Use screen coordinates", #2470
Comment from standard-two-simplex: Fixed in native. In order to fix it in higher resolutions measures that may harm other games have to be taken, so I don't recommend it.
