### ISSUE TITLE
Neon Genesis Evangelion Glitching Backgrounds

### ISSUE THREAD

**Issue by CallistoNTG** [gonetz/GLideN64#1870]
The backgrounds render incorrectly but the correct versions are visible for an instant at certain camera angles. To see this, simply start a new game and skip all the cutscenes.

Angrylion:
![evangelion-000](https://user-images.githubusercontent.com/41622989/43173122-80771a64-8ff6-11e8-8e18-85e0e3226c8f.png)
GLideN64.
![evangelion-001](https://user-images.githubusercontent.com/41622989/43173123-858fd554-8ff6-11e8-98ce-9683ac699ac9.png)

**Comment by olivieryuyu** [comment]
confirmed, I am not sure any HLE plugin avoid this issue.

**Comment by olivieryuyu** [comment]
this one is fixed
