### ISSUE TITLE
GlideN64 3.0 doesnt let project64 start up

### ISSUE THREAD

**Issue by maxinuno16** [gonetz/GLideN64#1871]
I wanted to play project64 with my friends online so I downloaded this custom build for this specific thing with netplay. When I try to use it instead of a console to connect\host it appears an error. Only for me and not my two friends. I found out that if I use the other graphics plugin called Jabo's Direct3D8 I dont get any problems. What is the difference between the two? I dont care about graphics quality at all, so anything is fine. The error says: 

"CN64System::EmulationStarting: Exception caught
File: N64System\N64Class.cpp
Line: 493"

I am using:
32 bit pc windows and cpu, 
with 4gb ram, 
mobile intel 4 series express chipset family graphics card, 
pentium dual core cpu t4200
I am not sure but I dont think my pc supports OpenGL after 3.0, if that helps

**Comment by theboy181** [comment]
I could be wrong here but this issue it talking about downloaded roms and should be deleted.

**Comment by theboy181** [comment]
Can I get you to remove the sites name. Roms are illegal and you ripping people off on what sites host them are sketchy.

**Comment by maxinuno16** [comment]
the issue is using gliden64 with pj64, because it starts almost fine with the other video pugin.
With gliden64, pj64 doesnt even start and I get that error. This is with "public release 3.0"

**Comment by maxinuno16** [comment]
sorry, I am very new to this, but anyway thanks for the tip and the warning.

**Comment by AlexN64gamer** [comment]
So, as I get from this conversation... Everytime we want to post and issue here in your github, we HAVE to be talking about an owned n64 cartridge? knowing that nowadays almost every n64 game you want to buy is highly overpriced, and also its like I can go outside and go to the first gamestop I find and buy N64 cartridges like nothing... theyre not THAT common, in fact theyre really rare to see nowadays,  sorry if I sounded mean but this sounds like a joke to me...

**Comment by theboy181** [comment]
There will be only assumptions of the ROM being legit unless otherwise indicated. The OP named the ROM site he obtained the game at and if you have been following the news lately you will see that Nintendo is taking ROM sites down with lawsuits instead of their usual letters. 

ROMS and links to ROMS have never been acceptable her. 

I hope that makes sense.

**Comment by AlexN64gamer** [comment]
Nintendo is in their right to do that cause its their property, but I think that attitude towards games released more than 20 years ago, is not the best to promote their good name among their fans with less money...

**Comment by olivieryuyu** [comment]
this is a driver issue with Intel.

Please close
