### ISSUE TITLE
Mario Golf (U) "Render 2D elements in N64 resolution" issues

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1883]
When this setting is on, it fixes the BG picture in the menus. This is why I use this setting. However, this setting destroys the BALL in game. See GIF.

This code is a LOD hack for the BALL, and helps make seeing the difference easier.
![ball](https://user-images.githubusercontent.com/9299743/44011350-f78211f2-9e6c-11e8-9220-c7613ebae1ec.gif)

Mario Golf (U)
Ball LOD Hack

D11FF108 58E0
811FF10A 0008
D11FF108 58E0
811FF12C 0000
D11FF108 58E0
811FF12E 0000
D11FF108 58E0
811FF138 0000
D11FF108 58E0
811FF13A 0000

Note: Makes the ball look detailed when in flight.

**Comment by gonetz** [comment]
Please test with current master. If it still not fixed, please give me savestate to check.

**Comment by theboy181** [comment]
I’ll take a look at it tomorrow evening. Th is for tackling this

**Comment by theboy181** [comment]
Looking GOOOOOOOOD!!!

**Comment by brianmdunbar** [comment]
Sorry to necro this post, but I didn't know where else to comment. Clicking "Open Issue" on the github page didn't do anything for me. 

I'm seeing several issues in Mario Golf 64:

- The ball and cup disappear after the ball is hit
![Image](https://github.com/user-attachments/assets/223205ae-20e4-4785-af80-9b8cfba5df2f)
- When in the zoom (jump view) the grid and flagpole disappear.
![Image](https://github.com/user-attachments/assets/3bf2ea90-7cb1-46ed-87ea-6d240027ccef)
- When using the "cup view" the hole and grid disappears.
![Image](https://github.com/user-attachments/assets/3d83cdb7-76b8-463f-8b41-859e4911979a)

I've changed just about every setting looking for a fix. Are you seeing this issue as well? I'm using EmulatorJS with libretro-mupen64plus_next emulator.
![Image](https://github.com/user-attachments/assets/04489a5b-974f-4941-a778-5b2f8c6b83a4)
