### ISSUE TITLE
Bug on Screen (Frigate - 007 Goldeneye)

### ISSUE THREAD

**Issue by GamingTVYT** [gonetz/GLideN64#1887]
Hello, I'm doing tests in several games using the most current Plugin (GLideN64_43e0ad50) and the screen (Frigate) happens a bug at the beginning of the game, Mar keeps flashing the background. I am using (mupen64plus) the name of the rom is (Goldeneye.v64) I will leave my Savestate from the exact point where the Bug occurs.
[Goldeneye.zip](https://github.com/gonetz/GLideN64/files/2290518/Goldeneye.zip)
![g](https://user-images.githubusercontent.com/30762805/44153721-65b0e7f2-a07f-11e8-9d7a-20ab455cc3be.png)

**Comment by StenApp** [comment]
https://github.com/gonetz/GLideN64/issues/1834

**Comment by gonetz** [comment]
Duplicate
