### ISSUE TITLE
South Park - Chef's Luv Shack: wrong graphics

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1890]
i tested with angrylion and then on real N64 (works ok)

The gfx in most of the plugin, HLE and LLE, are wrong.

here the bugs

![gliden64_south_park _chef s_l_001](https://user-images.githubusercontent.com/8987490/44311669-b12da200-a3eb-11e8-8a19-82abfc6d680d.jpg)
![gliden64_south_park _chef s_l_010](https://user-images.githubusercontent.com/8987490/44311670-b12da200-a3eb-11e8-96c7-6f3d847086b2.jpg)
![gliden64_south_park _chef s_l_012](https://user-images.githubusercontent.com/8987490/44311671-b12da200-a3eb-11e8-85d1-10b012700380.jpg)
![gliden64_south_park _chef s_l_015](https://user-images.githubusercontent.com/8987490/44311672-b12da200-a3eb-11e8-8af0-032ef8f79788.jpg)
![gliden64_south_park _chef s_l_023](https://user-images.githubusercontent.com/8987490/44311673-b12da200-a3eb-11e8-9a69-62bf87c8ae50.jpg)

**Comment by olivieryuyu** [comment]
most likely linked to modifyvtx command. colors, texture coords, X, Y and Z are modified.

**Comment by theboy181** [comment]
WOW. Was going to report this..

**Comment by olivieryuyu** [comment]
@gonetz 

This is most weirdest bug ever... !!

**Comment by olivieryuyu** [comment]
And this is fixed :)

No idea where and how though :)

First HLE plugin to do so

**Comment by gonetz** [comment]
Cool!
