### ISSUE TITLE
wildwaters: gfx are messing up in game

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1891]
regression?

**Comment by gonetz** [comment]
Seems to be platform-dependent regression.
It works fine on AMD+Radeon, but Intel+GeForce is broken.

**Comment by gonetz** [comment]
Problems on GeForce started with a625225323c9
VBO - problems
Unbuffered drawer - ok.

**Comment by olivieryuyu** [comment]
@gonetz 

still ongoing :(

**Comment by olivieryuyu** [comment]
fixed
