### ISSUE TITLE
Goemon - Mononoke Sugoroku: wrong gfx

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1892]
![geomon](https://user-images.githubusercontent.com/8987490/44419740-4f507200-a57c-11e8-96d1-c736de0fc8fc.jpg)

this button should not appear (tested with angrylion and real N64)

Just start a new game

**Comment by theboy181** [comment]
are the player stats correct? looks like the numbers are getting chopped off.

**Comment by olivieryuyu** [comment]
yes this is also incorrect.

**Comment by olivieryuyu** [comment]
figures are now ok, not the button
