### ISSUE TITLE
starcraft gfx bug

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1893]
![starcart](https://user-images.githubusercontent.com/8987490/44419823-82930100-a57c-11e8-9cec-9f7927e8816f.jpg)

just need to start a new game

**Comment by gizmo98** [comment]
Do you still see this issue? I think this can be closed.

**Comment by gonetz** [comment]
It is not reproduced with current master. Closed. Please reopen if it will return back.
