### ISSUE TITLE
Pokemon Puzzle League (U) BG scrolling issue

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1896]
![pokeabug](https://user-images.githubusercontent.com/9299743/44439608-34303300-a579-11e8-8b70-4e0195d92bd5.gif)
Seems that the original starting frame populates the BG causing a jittery effect. you can see in one frame in this gif.

**Comment by gonetz** [comment]
@theboy181  Fixed now. Use "backgrounds rendering mode - stripped".
