### ISSUE TITLE
Last Legion UX regression

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1901]
![image](https://user-images.githubusercontent.com/9299743/44613776-d0eb0e80-a7cd-11e8-8737-02ef17002c24.png)

**Comment by gonetz** [comment]
Is native res texrects option enabled?

**Comment by theboy181** [comment]
yes, 
![image](https://user-images.githubusercontent.com/9299743/44613993-a8fdaa00-a7d1-11e8-9290-16e69891f08e.png)

**Comment by theboy181** [comment]
The 2d textures in so many games look awful without it. What is the plan with this option?

**Comment by gonetz** [comment]
The plan is to fix the issues of course.

**Comment by gonetz** [comment]
Fixed
