### ISSUE TITLE
Mario Tennis missing framebuffer effect with N64 depth compare

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#1905]
Framebuffer effects can be missing if N64 depth compare is enabled

<img width="569" alt="unbenannt" src="https://user-images.githubusercontent.com/7283660/45383077-72fe5980-b60a-11e8-9b8f-8f2fc2ca6fe2.PNG">

**Comment by gonetz** [comment]
@purplemarshmallow Please test with latest Master + fb_fixes:
https://github.com/gonetz/GLideN64/issues/1574#issuecomment-425714381

**Comment by Kidboy17** [comment]
![gliden64_mariotennis_000](https://user-images.githubusercontent.com/37382324/46313089-d16c8700-c57b-11e8-86c2-42759a68ffa3.png)
![gliden64_mariotennis_001](https://user-images.githubusercontent.com/37382324/46313102-d6c9d180-c57b-11e8-83c6-c052a7db9ce2.png)
 Looks like it is fixed. The shadow on the top right is from the camera Lakitu floating in the air.

**Comment by purplemarshmallow** [comment]
Yes
