### ISSUE TITLE
GB Tower

### ISSUE THREAD

**Issue by AlexN64gamer** [gonetz/GLideN64#1908]
Hey everybody, sorry to post about the same matter again, you are free to close this issue whenever you feel its ok, I just want to share my frustration about reading in some forums on the internet, not so long ago, about 2016 or 17, comments from people that just said, instead of taking the challenge to actually emulate the full behavior of the GB tower in pk stadium, "just use a gameboy emulator, its the same" thats one of the dumbest commentary I have ever seen, and frankly I feel like punching that person in the face, ITS NOT THE SAME, pk stadium GB Tower emulator, included other features like the doduo and dodrio special borders that have NEVER been replicated in any emulator, so PLEASE, I know im risking to be annoying, and if so, I accept any critic, but I kindly BEG again for it, would a GB Tower full speed and issues-free emulation be possible in the future? thanks a lot in advance

**Comment by dankcushions** [comment]
you've already got an open issue for this: https://github.com/gonetz/GLideN64/issues/1846

**Comment by LegendOfDragoon** [comment]
Use a software rendering gfx plugin and it will run fine

**Comment by olivieryuyu** [comment]
it is useless to have duplicate ticket

**Comment by AlexN64gamer** [comment]
> Use a software rendering gfx plugin and it will run fine

Im afraid it doesnt work dan, Ive already tried, black screen and the speed of the gb tower is useless (below 1 fps) so... its still not possible to run it

**Comment by LegendOfDragoon** [comment]
Use cpu interpreter and it will work. If the fps too slow, then nothing you can do. Graphics plugin hardly matters for GB Tower, so both issues should be closed.

**Comment by LegendOfDragoon** [comment]
@gonetz  you can close this issue :smiley: .
