### ISSUE TITLE
Perfect Dark 4 player combat simulator exit crash

### ISSUE THREAD

**Issue by Blue-Ike** [gonetz/GLideN64#1909]
The latest WIP Build crashes Perfect Dark when you have 4 players on and exit a game. A error message window pops up saying "Fatal Error: Stopping Emulation". This is on pj64 2,3.0.210. The emulator doesn't crash completely. Once you press the ok button on the pop up window the game emulation closes. You don't really need a save state for it. Just go to combat simulator>press start on all four available player ports open>start game. Once you start the game press start, in-game menu go to and select end game, then close and exit each player's window starting. Wait a few seconds and then pop up window appears with the error message. 

However, I tested it with a 2 and 3 player game and it doesn't seem to crash with 2 players or 3 when exiting a match.

**Comment by Blue-Ike** [comment]
I downloaded the latest public release from the official website and the issue still occurs. The last build didn't have this issue.

**Comment by Blue-Ike** [comment]
After testing GE and PD with the latest Build with fb fixes, PD seems to no longer crash playing multiplayer with either 2, 3, and 4 players. I think this issue can safely be closed.

**Comment by gonetz** [comment]
Please close if fixed.
