### ISSUE TITLE
Star Wars Episode I - Racer: Overlapping

### ISSUE THREAD

**Issue by Jj0YzL5nvJ** [gonetz/GLideN64#1911]
Some 3D objects can overlap on menus...

angrylion's RDP Plus:
http://0x0.st/s3R5.png

GLideN64:
http://0x0.st/s3RR.png

m64p savestate: http://0x0.st/s3R7.zip

**Comment by gonetz** [comment]
Fixed

**Comment by Jj0YzL5nvJ** [comment]
Confirmed. Thanks.
