### ISSUE TITLE
Duke Nukem 64: 2D Render Issue

### ISSUE THREAD

**Issue by Kidboy17** [gonetz/GLideN64#1915]
Duke Nukem 64 does not work in HLE mode but it works fine in LLE mode. Using Project 64 with newest WIP (Master+FB).

Starting Menu:
![gliden64_duke_nukem_000](https://user-images.githubusercontent.com/37382324/46315205-ab49e580-c581-11e8-8bbb-5e6e9780179c.png)

In Game:
![gliden64_duke_nukem_001](https://user-images.githubusercontent.com/37382324/46315213-b3098a00-c581-11e8-8aa3-437b689bfc49.png)

**Comment by gonetz** [comment]
Fixed

**Comment by Kidboy17** [comment]
The fix works but now there is a 2D render issue. If you have the option on, the enemies don't appear until closer to your character and only show half their body. If the option is off, no problem is shown.
2D Render enabled:
![gliden64_duke_nukem_004](https://user-images.githubusercontent.com/37382324/46585712-e38d7000-ca28-11e8-9b40-d43594c33784.png)
![gliden64_duke_nukem_006](https://user-images.githubusercontent.com/37382324/46585717-ec7e4180-ca28-11e8-818f-b528f4e2cd0e.png)
2D Render Disabled:
![gliden64_duke_nukem_005](https://user-images.githubusercontent.com/37382324/46585718-f607a980-ca28-11e8-8ddd-009db93b4e31.png)

**Comment by gonetz** [comment]
I'll check it, thanks!

**Comment by gonetz** [comment]
Fixed. Please test.

**Comment by Kidboy17** [comment]
The issue has been fixed with 2D render.
