### ISSUE TITLE
Gauntlet Legends: HLE Not playable

### ISSUE THREAD

**Issue by Kidboy17** [gonetz/GLideN64#1916]
Gauntlet Legends works in LLE but not in HLE mode. Using project 64 with newest WIP (Master+FB). Really hope this game gets fixed, would love to play it with some friends in the future.

**Comment by oddMLan** [comment]
It works with Mupen64Plus. Project64 needs modifications to their RSP plugin in order to support Gauntlet Legends in HLE mode with GLideN64.

**Comment by gonetz** [comment]
Closed as core-related.
