### ISSUE TITLE
Vigilante 8 Menu and In-game issues.

### ISSUE THREAD

**Issue by Kidboy17** [gonetz/GLideN64#1917]
Vigilante 8 has menu and in-game issues. Enabling and disabling Render 2D Elements and N64 Depth compare do not affect the issues. This is happening in both HLE and LLE mode of the newest WIP build (Mater+FB). Just start the game, scroll through the characters and drive around in the first level.

Character Menu:
![gliden64_vigilante_8_000](https://user-images.githubusercontent.com/37382324/46316547-56a86980-c585-11e8-9553-5979eb59196d.png)

In Game:
![gliden64_vigilante_8_001](https://user-images.githubusercontent.com/37382324/46316558-5d36e100-c585-11e8-8696-18e71129eca8.png)

**Comment by gonetz** [comment]
Fixed
