### ISSUE TITLE
Extreme-G: wrong transition effect between screen (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#192]
![etremg1](https://cloud.githubusercontent.com/assets/8987490/5427776/75033f8c-83ac-11e4-8705-0a0a498a92e2.jpg)
![etremg2](https://cloud.githubusercontent.com/assets/8987490/5427777/77425328-83ac-11e4-8351-ed38c40ae96c.jpg)
![etremg3](https://cloud.githubusercontent.com/assets/8987490/5427778/796db944-83ac-11e4-8e50-0044b7bc147e.jpg)

**Comment by gonetz** [comment]
Please test with latest build.

**Comment by olivieryuyu** [comment]
fixed
