### ISSUE TITLE
Star Fox 64 flickering and garbage textures

### ISSUE THREAD

**Issue by Tenolius** [gonetz/GLideN64#1920]
Using the Master + FB fixes (rev 83ef31b2) in Star Fox 64 causes flickering. It temporarily dissapears when entering or exiting fullscreen, but happens again when there is some sort of transition(loading screen or level) in the game.

![starfox01](https://user-images.githubusercontent.com/12527930/46460490-f6761b00-c770-11e8-94eb-a11affc5dca8.png)
![starfox02](https://user-images.githubusercontent.com/12527930/46460497-faa23880-c770-11e8-8207-0a3a081d169c.png)

The flickering does not occur on the second version of Master + FB fixes (rev fbc91e76), but now some garbage texture appears as soon as the main menu is shown, and stays like this for the rest of the game.

![starfox03](https://user-images.githubusercontent.com/12527930/46460756-c8450b00-c771-11e8-9c6f-015a93db62c2.png)

NOTE: I have HD Textures activated, but these issues still remain when deactivating them, so it's definitely not related to this.
My current PJ64 version is Project64 2.4.0-697-g4c5f5c4. These are my settings on the Frame buffer section:

![project64_01](https://user-images.githubusercontent.com/12527930/46460972-58835000-c772-11e8-892c-29d83f1cb583.png)

I've played around by tweaking some of these options without having any results.

NOTE: None of these issues occur when using Public Release 3.0. As shown above, I have the same settings applied on the Frame Buffer section of this version.

**Comment by Kidboy17** [comment]
Can confirm, I get the pixelated border on the top as well with newest WIP build (Master+FB)

Menu:
![gliden64_starfox64_003](https://user-images.githubusercontent.com/37382324/46506814-696fa800-c7ea-11e8-90bb-e38b42179a8c.png)

In game:
![gliden64_starfox64_004](https://user-images.githubusercontent.com/37382324/46506819-6ffe1f80-c7ea-11e8-8732-bc53c7c4f4ba.png)
