### ISSUE TITLE
Legend of Zelda: Majora's Mask Issue

### ISSUE THREAD

**Issue by Kidboy17** [gonetz/GLideN64#1921]
With the latest WIP build (Master+ FB), Majora's Mask has become unplayable. I have messed with different settings, deleted the shaders folder but nothing has fixed it.

![gliden64_zelda_majora s_mask_003](https://user-images.githubusercontent.com/37382324/46507168-0f6fe200-c7ec-11e8-9ae1-9e1d5933799a.png)
![gliden64_zelda_majora s_mask_004](https://user-images.githubusercontent.com/37382324/46507174-13036900-c7ec-11e8-8a40-70530f7a085e.png)
![gliden64_zelda_majora s_mask_000](https://user-images.githubusercontent.com/37382324/46507181-18f94a00-c7ec-11e8-9473-47eea29b5e49.png)
![gliden64_zelda_majora s_mask_001](https://user-images.githubusercontent.com/37382324/46507182-1b5ba400-c7ec-11e8-8392-56847a70dfae.png)

**Comment by Jj0YzL5nvJ** [comment]
Bisected to 5e1c8a6b582c289792756ddcb1b9f5066fa75442

**Comment by gonetz** [comment]
Fixed. Thanks for the bug report and bad commit detection.

**Comment by Kidboy17** [comment]
@gonetz Of course! Thank you for your speedy fixes. I look forward to the next WIP to test out the fixes you have recently made to the other games I have posted about.

**Comment by Kidboy17** [comment]
Game is fixed. Thanks Gonetz!
