### ISSUE TITLE
1080 Snowboarding Black Screen Issue.

### ISSUE THREAD

**Issue by Kidboy17** [gonetz/GLideN64#1923]
So far anytime you attempt to do a trick on a half-pipe in this game, the screen goes black and the music stops. The trick I do is just jumping off the half-pipe lip, pressing B and any direction. You can do races normally but anything involving the half-pipe causes this issue.
To replicate: Just do Trick Attack (Pick Half-Pipe course) or Training and take the left track at the fork in the course.
Using Project 64 build: 2.4.0.668-gc506db5
It is currently a problem in the newest build of the WIP (Master+FB)
https://drive.google.com/file/d/1SBAZ9OqaBkejDyKzOaW2dEkENdNZeJiX/view?usp=sharing
I also tried with this build and got the same issue
https://drive.google.com/file/d/1vQiGjOGdMbwc5P6s7xl3U4VzAYL0AGkW/view?usp=sharing

**Comment by Kidboy17** [comment]
Not sure if anyone has tested this yet. I have a feeling that this could be a Project 64 core issue.

**Comment by gonetz** [comment]
Please test it with another graphics plugin, e.g. Jabo D3D.

**Comment by Kidboy17** [comment]
Yeah its a core issue. I tried Jabo and AL, both reproduced the problem. I'll go ahead and close this.

**Comment by LegendOfDragoon** [comment]
I could have sworn that issue was fixed. Iirc, the issue is the cpu recompiler settings in rdb. @Kidboy17 can you try cpu interpreter?
