### ISSUE TITLE
Mario Party 3: Curtain Call Issue (Can not open old issues closed by Gonetz)

### ISSUE THREAD

**Issue by Kidboy17** [gonetz/GLideN64#1926]
The issue still happens on the newest WIP (Master+FB) released today with n64 depth compare enabled. Using Project 64 2.4.0.668-gc506db5.

Sorry for making a new issue but I can not open the original issue since it was closed by Gonetz and I was not the original creator of it. #692 

![gliden64_marioparty3_002](https://user-images.githubusercontent.com/37382324/46586204-d4f68700-ca2f-11e8-8716-3860b47e5344.png)

**Comment by gonetz** [comment]
I just tested mupen64plus build, it works fine with n64 depth compare enabled.
I don't have savestate for  Project 64.

**Comment by Kidboy17** [comment]
[Mario Party 3 (U).pj.zip](https://github.com/gonetz/GLideN64/files/2459010/Mario.Party.3.U.pj.zip)

I hope this is an actual problem and not just on my side, lol.

**Comment by Tenolius** [comment]
I just tested it as well and it works for me. I am using depth compare enabled too, Project64 2.4.0-697-g4c5f5c4 and Master+FB fixes rev 067840da. Maybe just double check in the ROM's game settings if it's not using a different plugin or revision? (right click and select Edit Game Settings then proceed to the plugins section). I sometimes select different settings or plugins for some games depending on particular issues that could or not work for them.

**Comment by oddMLan** [comment]
@Kidboy17  Make sure you delete the "shaders" folder or disable shader generation under GLideN64 options, restart the emulator and try again.

**Comment by Kidboy17** [comment]
Lol, now I am at a lose for words. Doubled checked my settings, made sure everything was default except N64 depth compare, deleted my shader folder and disabled the store shaders. Still get the same issue. I went ahead and even messed with every frame buffer setting with N64 depth compare enabled, while deleting my shader folder numerous times and the issue never fixed itself. This so bizarre, why am I the only one lol....?

Its completely fine with angrylion which Im sure you are all aware of.
![marioparty3_0000](https://user-images.githubusercontent.com/37382324/46708003-64976380-cbf1-11e8-841d-2ab70359ef4f.png)

**Comment by loganmc10** [comment]
Are you sure your PC supports N64 Depth Compare? Can you look in gliden64.log?

**Comment by Kidboy17** [comment]
"Your GPU does not support the extensions needed for N64 Depth Compare."


I feel ashamed...... I really thought my Nvidia 780ti was capable of it. It supports OpenGL 4.4

**Comment by loganmc10** [comment]
N64 Depth Compare relies on extensions to the OpenGL spec (not part of core OpenGL), not every GPU supports it, but most newer graphics cards do.

**Comment by Kidboy17** [comment]
I did not know that, thank you very much Logan :)

I guess I can close this issue then since I'm the only one who can't use N64 Depth Compare lol
