### ISSUE TITLE
Black screen in mortal kombat 4

### ISSUE THREAD

**Issue by notcompute** [gonetz/GLideN64#1929]
mortal kombat 4: right after startup, black screen.
tested with the new: Master + fb_fixes:

**Comment by Tenolius** [comment]
I can confirm the issue happens in this game using the latest Master + FB Fixes.

**Comment by gonetz** [comment]
Another regression from 62b8103e462
That fix brings more troubles than benefits.

**Comment by notcompute** [comment]
fixed with latest latest Master
