### ISSUE TITLE
Perfect Dark No text/notifications in multiplayer

### ISSUE THREAD

**Issue by Tenolius** [gonetz/GLideN64#1930]
Using the latest Master + FB Fixes build rev 067840da. Anytime you get a notification of some sort (defeating another player or getting killed) no text is displayed, only an empty green box will appear.

Example shown on the lower-left screen:
![pd01](https://user-images.githubusercontent.com/12527930/46912923-56ba4900-cf37-11e8-8efc-a0914a483e39.png)

**Comment by gonetz** [comment]
Do you have Hi-Res enabled in in-game Video settings?

**Comment by Tenolius** [comment]
Yes, I have it enabled.

**Comment by gonetz** [comment]
I have notifications working ok when Hi-res is off.

**Comment by gonetz** [comment]
The issues is duplication of #1807

**Comment by gonetz** [comment]
Fixed. Test build:
https://drive.google.com/file/d/1k238MN1z-8xl6bsloSG2aoLtmO4Ijj4H/view?usp=sharing

**Comment by Tenolius** [comment]
Issue solved in rev 68a2c939
