### ISSUE TITLE
Zelda OOT 'N' logo lightning absent [regression]

### ISSUE THREAD

**Issue by oddMLan** [gonetz/GLideN64#1932]
Latest master:
![imagen](https://user-images.githubusercontent.com/7278372/46922189-41d2c980-cfba-11e8-96e5-0d45e2debb1d.png)

Latest WIP (1df96ceb)
![imagen](https://user-images.githubusercontent.com/7278372/46922224-c58cb600-cfba-11e8-92bb-913808ddc3cd.png)

**Comment by gonetz** [comment]
Must be emulator's issue or something with drivers. I can't reproduce it. Tested with revision 1df96ce

**Comment by Kidboy17** [comment]
I use Project 64 and I am not experiencing this issue.
![gliden64_the_legend_of_zelda_007](https://user-images.githubusercontent.com/37382324/46934712-a3705380-d00d-11e8-8b36-e4099da16a2c.png)

**Comment by Squall-Leonhart** [comment]
the lighting effect is specific to the Zelda Ucode, its been a long time working/not working thing

**Comment by oddMLan** [comment]
Cannot reproduce anymore, even when trying to use the 'faulty' build (turns out it wasn't the case). My bad. Must've been a temporary issue on my end, which a restart must have had fixed.
