### ISSUE TITLE
indiana jones and the infernal machine, (freeze)

### ISSUE THREAD

**Issue by notcompute** [gonetz/GLideN64#1934]
![indiana jones and the infernal machine](https://user-images.githubusercontent.com/42537199/47163495-60a4c900-d2f6-11e8-976a-7600a89e33d9.jpg)

if you let the game demo run, you eventually come to this point then the demo just freeze

**Comment by StenApp** [comment]
https://github.com/gonetz/GLideN64/issues/1574#issuecomment-399801879

**Comment by gonetz** [comment]
@StenApp  Thanks!
Closed as core issue.
