### ISSUE TITLE
Lode Runner 3-D: No video output if framebuffer is enabled

### ISSUE THREAD

**Issue by thecoreyburton** [gonetz/GLideN64#1937]
When the game boots, there is just a blank screen. Pressing buttons (such as start) interacts with the game as though it was visible, causing sound effects to play and being able to navigate through the menus.

To fix this, frame buffer is disabled and the game displays again.

**Comment by gonetz** [comment]
I see what causes the problem.
The way this game allocates frame buffers needs special treatment in code.

**Comment by gonetz** [comment]
Fixed
