### ISSUE TITLE
Mario Tennis: Invisible Menus (Regression)

### ISSUE THREAD

**Issue by Kidboy17** [gonetz/GLideN64#1940]
EDIT: The WIP from October 17th has no issues. https://drive.google.com/file/d/1NmHCcoD_E7m4aSFbhELb-32R0leXgXa2/view?usp=sharing

The menus for choosing a play mode in Mario Tennis have vanished. I am using Project 64 2.4.0.668-gc506db5 and default settings. The issue happens in the newest WIP released 14 days ago, https://drive.google.com/file/d/17yKKOiE8qyXv0KT38YTCQDmaaGDwYZtg/view?usp=sharing it also happens with the WIP using Stefan's fix https://drive.google.com/file/d/1-Zpt7qq_UDbgsE0q-TXeQHMAeVaVh2QP/view?usp=sharing
![gliden64_mariotennis_000](https://user-images.githubusercontent.com/37382324/47969182-981ab180-e028-11e8-9c19-553cddd62127.png)
![gliden64_mariotennis_001](https://user-images.githubusercontent.com/37382324/47969183-9bae3880-e028-11e8-9b82-8486ae6b0328.png)
![gliden64_mariotennis_002](https://user-images.githubusercontent.com/37382324/47969185-a072ec80-e028-11e8-8112-d1173d409da5.png)
Interesting enough, if I enable Copy auxiliary color buffers to N64 memory, ALL the menus disappear not just the Play Mode menus.
![gliden64_mariotennis_003](https://user-images.githubusercontent.com/37382324/47969211-e760e200-e028-11e8-8f18-70e476d722fc.png)

The Play Mode menus were showing with this WIP build from August 12, before the FXAA was added. https://drive.google.com/file/d/1htSop9L_DTpcnYAhepCQrRbEVcdFda0P/view?usp=sharing
This menu is partially broken, all the others are fine.
![gliden64_mariotennis_004](https://user-images.githubusercontent.com/37382324/47969237-51798700-e029-11e8-9d81-936bc7008144.png)
![gliden64_mariotennis_005](https://user-images.githubusercontent.com/37382324/47969238-54747780-e029-11e8-9aff-040c825232ca.png)
![gliden64_mariotennis_006](https://user-images.githubusercontent.com/37382324/47969239-576f6800-e029-11e8-844a-6dae1449d379.png)

**Comment by Kidboy17** [comment]
This WIP from October 17th has every menu working correctly. Somehow a commit that was added to the WIP of October 21st has caused this issue in Mario Tennis.

Here is the working WIP: https://drive.google.com/file/d/1NmHCcoD_E7m4aSFbhELb-32R0leXgXa2/view?usp=sharing

**Comment by Exequiel3k** [comment]
I was recently getting invisible menus in that game when I had enableNativeResTexrects = TRUE
Can you try with that = FALSE / "0"

**Comment by Kidboy17** [comment]
With the newest build https://drive.google.com/file/d/12sJs30B-yvgYCE5mo2njk8bdKmESsGBX/view?usp=sharing The issue is back if you have Render 2D Elements enabled. When enabled all the menus in the game except for Player select and Continue are invisible.

**Comment by gonetz** [comment]
Seems to be fixed now. Please test with latest WIP build from #1574

**Comment by Kidboy17** [comment]
Tested it out with the lastest WIP using Render 2D Elements and the menus are all there. Nicely done!
