### ISSUE TITLE
Paper Mario - Watts attack transparency

### ISSUE THREAD

**Issue by Krusher97** [gonetz/GLideN64#1942]
https://youtu.be/1aQ1QVvwxos

The yellow opaque rectangle should not be present. This is running on mupen64plus.

Savestate for the fight : [Paper Mario (U) [!].zip](https://github.com/gonetz/GLideN64/files/2580358/Paper.Mario.U.zip)

**Comment by Kidboy17** [comment]
This happens with all electrical attacks, not just Watts. Happens on Project 64.

**Comment by gonetz** [comment]
GLideN64 VS al rdp:
![shock](https://user-images.githubusercontent.com/8983092/48532885-caec6180-e8d4-11e8-8371-e2a0dd654b1d.jpg)
Who first will guess which option need to be activated?

**Comment by thecoreyburton** [comment]
If I recall, this is a problem fixed with N64 depth compare.

**Comment by Krusher97** [comment]
N64 depth compare doesn't change anything

**Comment by theboy181** [comment]
Lle?

**Comment by gonetz** [comment]
Yes, it is N64 depth compare.  If it does nothing for yoy, it must be unsupported by your hardware. Check gliden64.log for error messages.

**Comment by Krusher97** [comment]
A 750Ti does not support N64 Depth Compare?

**Comment by loganmc10** [comment]
> A 750Ti does not support N64 Depth Compare?

Correct, it doesn't support the needed OpenGL extensions

**Comment by loganmc10** [comment]
I know you've asked this before. I believe the needed extension (shader interlocking) was first introduced (for Nvidia) on Maxwell G2 cards, yours is a Maxwell G1 card

**Comment by Kidboy17** [comment]
Nvidia GTX 960 and above can use N64 Depth Compare.

**Comment by gonetz** [comment]
Yes. How the description text should look to avoid misleading?

**Comment by Kidboy17** [comment]
@gonetz Pretty much what oddMLan suggested if that is possible. Also just add " Feature only supported by Nvidia GTX 960 and later video cards."
 Im not sure what the equivalent is for Radeon, I haven't used one since 2005.

**Comment by oddMLan** [comment]
What's the approach in situations like these? in Mario Party 3 the Curtain Call minigame requires N64 depth compare in order to look correct, but since it's virtually the only thing in the game that requires it, it doesn't warrant a INI entry forcing N64 depth compare, right? So I'm guessing it should be the same here. Do you keep a list of situations in which N64 depth compare might be needed, but is not essential to the game? Maybe that information should be in a Wiki entry.

**Comment by loganmc10** [comment]
N64 Depth Compare should be fast now, there should be no harm in adding it to the INI file. If the user's computer doesn't support N64 Depth Compare, it just won't turn it on.

**Comment by olivieryuyu** [comment]
Can we close the ticket please?

**Comment by gonetz** [comment]
I'll better enable it by default. As Logan said,  there should be no harm in enabling it.
At least, list of games, which have problems with it enabled is shorter than list of games which have benefits from it.

**Comment by oddMLan** [comment]
Also the good thing is that FXAA was recently added, so there's no disadvantage of using it now.
