### ISSUE TITLE
Finishing HLE - Help needed

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1944]
Hi Guys!

I am about to quench all HLE known bugs. Is there any bug which you may be aware of?

For that you need to compare HLE and LLE with GlideN64 and see if there is difference.

HVQM and SDEX issues does not need to be reported.

If nothing comes up, I will stop my work on HLE deciphering. So please help to find any remaining bugs!

See ya!

**Comment by oddMLan** [comment]
I've noticed this for a while, but thought it was really minor so I didn't report it.

HLE
![conkerhle](https://user-images.githubusercontent.com/7278372/48824722-65f49980-ed22-11e8-9ae8-f62b1d4dc6c0.png)

LLE
![conkerlle](https://user-images.githubusercontent.com/7278372/48824752-83296800-ed22-11e8-8d1e-78ce6225ded2.png)

LLE has dimmer (and much more accurate) lightning.

**Comment by olivieryuyu** [comment]
Ok sounds a candidate for decoding.

**Comment by olivieryuyu** [comment]
where are the lens flare?

**Comment by olivieryuyu** [comment]
> 
> 
> maybe this? #1509

Nope

**Comment by Stajin** [comment]
To add to the reported Turok bug on reddit - here is the link to the post so you can ask the person reporting directly as they don't use Github.

[https://www.reddit.com/r/emulation/comments/9z166z/gliden64_dev_asking_for_hle_bugs_to_fix/](url)

**Comment by Kidboy17** [comment]
#1731 Is this a possible candidate?

**Comment by Kidboy17** [comment]
Here is one for HLE only, #1912

**Comment by olivieryuyu** [comment]
> 
> 
> #1731 Is this a possible candidate?

Nope it is the same in LLE.

**Comment by olivieryuyu** [comment]
> 
> Here is one for HLE only, #1912
> 

OK

**Comment by olivieryuyu** [comment]
> 
> Another one, #1736
> 

Nope

**Comment by ShareScene** [comment]
and... what about Resident Evil 2 ucode? is it completely deciphered?

**Comment by loganmc10** [comment]
> and... what about Resident Evil 2 ucode? is it completely deciphered?

Yes I believe so, works fully in HLE (https://gliden64.blogspot.com/2017/04/resident-evil-2.html)

**Comment by McCoy2X** [comment]
RE2 works properly now, but if I'm not mistaken, it's still the same hack from Glide64 to display the backgrounds correctly. The correct behaviour has never been fully deciphered.

**Comment by loganmc10** [comment]
Perhaps, but either way that is not a ucode issue (HLE vs LLE)

**Comment by Tasosgemah** [comment]
The water levels in Goemon's Great Adventure are messed up. Also, many 2D backgrounds (like the mountain in the first level or town) have a line around them that doesn't go away with the native resolution for 2D elements option.

**Comment by oddMLan** [comment]
Guys, olivieryuyu is asking only about issues where HLE looks different than LLE mode.

**Comment by LegendOfDragoon** [comment]
@olivieryuyu would you be interested in HLEing GB Tower in pokemon stadium 2?

**Comment by olivieryuyu** [comment]
@LegendOfDragoon 

Just provide a savestate before getting into the screen where the ucode starts.

**Comment by LegendOfDragoon** [comment]
@olivieryuyu PJ64 seems to clear the transfer pack data when loading a save state. I guess you can hold off on it until this issue is fixed. I may look into fixing it next weekend. I even made a savestate at the game pack check screen and there's no game pack when loading the save state.

**Comment by olivieryuyu** [comment]
> 
> 
> > To add to the reported Turok bug on reddit - here is the link to the post so you can ask the person reporting directly as they don't use Github.
> > [https://www.reddit.com/r/emulation/comments/9z166z/gliden64_dev_asking_for_hle_bugs_to_fix/](url)
> 
> Cannot find the bug. Need PJ64 savestate.

Found where it is but it works in LLE and HLE without any issue.

![gliden64_turok_dinosaur_hunte_000](https://user-images.githubusercontent.com/8987490/49046777-8b2b5100-f1d5-11e8-9892-e99b5941c6c2.jpg)

**Comment by olivieryuyu** [comment]
Holy Moly, Conker lighting is quite something. There is not one but actually two lighting modes!

**Comment by Frank-74** [comment]
There's still Stunt Racer 64 and World Driver Championship to be HLE'd...

**Comment by loganmc10** [comment]
@Frank-74 that is already done

**Comment by Frank-74** [comment]
@loganmc10 Has it?  I still get RunRSP error on booting WDC with HLE Gfx in Project64.  Using latest WIP GLideN64.

**Comment by ShareScene** [comment]
it was implemented long time ago by Gillou68310

**Comment by ShareScene** [comment]
https://github.com/gonetz/GLideN64/pull/1717

**Comment by Frank-74** [comment]
Well, WDC LLE Gfx boots fine with latest GLideN64 WIP.  Choosing HLE Gfx results in RunRSP error.  How do I get it to run HLE gfx with Project64?

**Comment by LegendOfDragoon** [comment]
@Frank-74 i think it only works in mupen64plus.

**Comment by theboy181** [comment]
At this point mupen is the emulator of the future. They have been adding hacks to get their games running so that development for GLideN64 can continue. At the time this game was added to their comparability list more contributions were added to the puzzle from their developers.

**Comment by loganmc10** [comment]
It wasn't any kind of hack that allowed World Driver Championship to work with HLE, we extended the gfx_info API to include SP_STATUS_REG, that is what was needed for WDC and Stunt Racer:

https://github.com/mupen64plus/mupen64plus-core/pull/423

If PJ64 did something similar then those games would work in HLE

**Comment by theboy181** [comment]
I’m sorry. I did t realize that that’s how the real hw worked. What about gauntlet then? Hack?

**Comment by loganmc10** [comment]
Gauntlet Legends was a similar situation, the GFX plugin needs to be able to modify the SP_STATUS bit.

It's not really a matter of hack/no hack, because of the plugin system, the GFX plugin didn't have the ability to modify all of the RSP registers, it was a shortcoming of the original API design many years ago

**Comment by olivieryuyu** [comment]
Guys, this is getting off topic. Can you please provide HLE bugs? Conker deciphering is already started. Mario Party should next. Anything else?

**Comment by schubertguilherme** [comment]
Hello, olivieryuyu, slowdown game Mortal Kombat Trilogy in stage "The Subway" and bug graphics in Top Gear Hyper Bike "textures". Fix please. Hugs and sucess.

**Comment by olivieryuyu** [comment]
> Hello, olivieryuyu, slowdown game Mortal Kombat Trilogy in stage "The Subway" and bug graphics in Top Gear Hyper Bike "textures". Fix please. Hugs and sucess.

Nothing to do with HLE.

**Comment by theboy181** [comment]
The stage in hyper bike? What is the issue then?

**Comment by Frank-74** [comment]
Top Gear Hyper Bike is same bug with ground textures in LLE and HLE with GLideN64.  But Angrylion gets it right.

**Comment by olivieryuyu** [comment]
Conker nearly over. Anything else?

**Comment by StenApp** [comment]
Is there a list of non HLE related errors?

**Comment by olivieryuyu** [comment]
Nothing else ?

**Comment by ShareScene** [comment]
I think u should take a look Resinde Evil 2, because ucode is not totally deciphered... instead of that is totally hacked.

**Comment by olivieryuyu** [comment]
There is no ucode issue.

**Comment by schubertguilherme** [comment]
It happens on all the transition screens of the game. Using last WIP build. Flashes screen.

![49401707-16a16680-f72f-11e8-8d62-cb42724a513c](https://user-images.githubusercontent.com/36903073/49447987-0933bd00-f7bf-11e8-9da2-36163dcec4a1.jpg)

**Comment by olivieryuyu** [comment]
This is not a HLE bug !

**Comment by GamingTVYT** [comment]
@schubertguilherme What is the WIP you are using, please? I'm going to test here to see if the same error occurs.

**Comment by schubertguilherme** [comment]
OK thanks, sorry. With this WIP working. https://drive.google.com/file/d/0B0YqMPjGo3B2OERNOEVHMGdaQ2c/view?usp=sharing

**Comment by Kidboy17** [comment]
Issue #1484 ? Even though it uses per pixel lighting, the issue is only in HLE mode.

**Comment by gonetz** [comment]
Per-pixel lighting is HLE-only feature, because graphics plugin does lighting calculations only in HLE mode. Per-pixel lighting issues are not related to microcode decoding. Per-pixel lighting is a hack which just does not always work well.

#1647 is not HLE issue. Plugin works the same in LLE mode.

RE2 has no microcode decoding issues.

Top Gear Hyper Bike issues are not HLE related.

and so on.

So, HVQM, CBFD and Mario Party are the only unsolved HLE issues.
HVQM, CBFD already decoded and just waiting to be implemented.

**Comment by CallistoNTG** [comment]
I could be wrong, but didn't someone mention that World Driver Championship has missing coronas in HLE?

**Comment by olivieryuyu** [comment]
> I could be wrong, but didn't someone mention that World Driver Championship has missing coronas in HLE?

Did u try in LLE and is it different?

**Comment by ShareScene** [comment]
https://github.com/gonetz/GLideN64/issues/190 It is HLE only issue.
https://github.com/gonetz/GLideN64/issues/230 LLE software looks ok

**Comment by olivieryuyu** [comment]
> #190 It is HLE only issue.
> #230 LLE software looks ok

190 is not an issue of HLE as such. It is the implementation in OpenGL of the solution which is hard to do.
230 is a framebuffer issue, not a HLE issue.

**Comment by gonetz** [comment]
Yes, #190 is OpenGL related. OpenGL clipping need to be disabled somehow to show uncut logo. Or use software clipping, as in Glide64. Anyway, it is not HLE issue.

#230 is unclear what is it: frame buffer or depth compare issue, may be both. In any case it is not HLE related.

**Comment by olivieryuyu** [comment]
Mario Party fixed

Anything else?

**Comment by olivieryuyu** [comment]
@gonetz 

 #1953

**Comment by thecoreyburton** [comment]
Not sure about this one, but I think it's HLE exclusive: https://github.com/gonetz/GLideN64/issues/1904

**Comment by olivieryuyu** [comment]
> 
> 
> Not sure about this one, but I think it's HLE exclusive: #1904

Nope

**Comment by olivieryuyu** [comment]
CBFD lighting is so nice

![gliden64_conker_bfd_002](https://user-images.githubusercontent.com/8987490/50796170-03a32880-12d1-11e9-8160-25e9bfc299b2.jpg)

Any other bugs?

**Comment by gonetz** [comment]
Speaking of HLE bugs, #1964 is probably the last one.

**Comment by olivieryuyu** [comment]
> Speaking of HLE bugs, #1964 is probably the last one.

Hmm not sure in which way it is...

**Comment by olivieryuyu** [comment]
there is also HVQM.

**Comment by theboy181** [comment]
Actually, https://github.com/gonetz/GLideN64/issues/1976 looks like HLE bug too.


Explanation here. https://github.com/gonetz/GLideN64/issues/1970

**Comment by olivieryuyu** [comment]
I don't see how it is HLE related but ok

**Comment by theboy181** [comment]
@olivieryuyu its broken in HLE not LLE. ?

**Comment by olivieryuyu** [comment]
i can be broken in HLE for other reasons than a microcode issue.

**Comment by theboy181** [comment]
I think you meant "it", :) I hope you are not broken. :p

Ok, I see what you are saying. How can I tell if its HLE related then?

**Comment by gonetz** [comment]
We have "HLE issue" notion for very different things, thus the confusion.

There are (they were ?) issues caused by incorrect/incomplete high-level implementation of microcode. This ticket is for such kind of issues. These issues are fixed thanks to oliveryuyu.

There are issues in HLE mode, which caused by OpenGL limitations - some transformations, performed in software by RSP plugin in LLE mode can't be made on hardware level, for example #190.
I'm not sure, what causes issues in #1964,  but most likely it is another OpenGL related issue.
If it is so, HVQM is indeed the only remained problem, which is related to microcode decoding and implementation.

**Comment by LegendOfDragoon** [comment]
Hopefully someone can send olivieryuyu a save state for Pokemon Stadium 2 GB Tower :smile: .

**Comment by olivieryuyu** [comment]
well without a savestate I won't be able to do so. When HVQM is implemented, I will close this ticket and HLE matters most likley forever.

**Comment by Frank-74** [comment]
Just found this post which says transfer pack saves only load with N-Rage 1.82a.
https://forums.emulator-zone.com/showthread.php?t=2449

**Comment by LegendOfDragoon** [comment]
@Frank-74 i think any of the 1st or 2nd gen pokemon games are fine. I guess you can make a save state right after starting GB Tower.

**Comment by Frank-74** [comment]
@LegendOfDragoon What is the problem with HLE?  I ran with Pokemon - Yellow Version - Special Pikachu Edition.  I couldn't see any issue with HLE and GLideN64 after starting GB Tower and playing from the gameboy save.  Shouldn't there be unsupported ucode message or something?
The only problem is CPU recompiler stalls in GB Tower, but interpreter runs full speed.

**Comment by LegendOfDragoon** [comment]
The task type is technically "audio", but it does graphics (and maybe audio too).

**Comment by Frank-74** [comment]
@LegendOfDragoon Tried save after starting GB Tower, on loading back, it freezes.  Think problem may be that transfer pack broke in N-Rage from 1.83, 2.3c was used for Project64 and it doesn't account for transfer pack.  I think @olivieryuyu  needs a save to load in latest Project64 to debug.  Source for 1.82a (working) and 1.83 (broken) is here: http://members.chello.at/n-rage/dinput8/downloads.html.  I need to study it.  Not much time as moving from house to flat soon.

**Comment by Frank-74** [comment]
@olivieryuyu I managed to get it working.  I put them in the folders as I have them in my pj64.  So you can just extract to your Project64 folder.  You'll need the "Pokemon - Yellow Version - Special Pikachu Edition (USA, Europe) (GBC,SGB Enhanced).gb" rom.

Save: Latest Project64 F5 save .zip and .fla
Roms: The gameboy .sav file.  (I haven't added the rom)
Plugin/Input: The N-Rage 1.82a plugin.
Download: https://www.dropbox.com/s/8r7mnjnbpu1v45k/PokeStad2_Saves_cont_plug.zip?dl=0

Select Transfer Pack in the plugin, and choose the gameboy .gbc and .sav file.

Video of running Pokemon Stadium 2 and starting GB Tower, running and making F5 save, then loading F7 save.  It works for you hopefully.
https://www.dropbox.com/s/4mtzfds5lr1kng2/2019-01-15%2002-11-51.mp4?dl=0

**Comment by olivieryuyu** [comment]
@Frank-74 

I will check this out but i am not really sure that there is even a microcode for this GB tower. It can be CPU based only.

**Comment by olivieryuyu** [comment]
No more microcode issue known

**Comment by be227** [comment]
I have tried out the new version I got 2 stadium to work The first one is still not doing anything, it's just blank. technically all the games got be into stadium 2
