### ISSUE TITLE
Pokemon Snap LLE Render 2D Elements in N64 Res Error

### ISSUE THREAD

**Issue by Kidboy17** [gonetz/GLideN64#1945]
On Project 64 using latest WIP in LLE mode, enabling Render 2D elements causes the game to produce a blank, purplish screen. 
![gliden64_pokemon_snap_002](https://user-images.githubusercontent.com/37382324/48927776-dbc94400-ee8d-11e8-8819-9a200a2c445a.png)

**Comment by gonetz** [comment]
Seems to be fixed
