### ISSUE TITLE
Inquiry - Same game on 2 different formats = different quality of output

### ISSUE THREAD

**Issue by Exequiel3k** [gonetz/GLideN64#1946]
Hey,
I was playing around trying to find better output frames and I stumbled upon this:
The same game/region/size in two different formats (.v64 vs .z64) caused the game to output less pixelated in one than the other, without altering the settings. 

I tried this on other games and it happened as well (i.e. Mario tennis).

In this exemple, z64 displays a smoother image than v64 (click on the image) but in other games it could be the opposite. I even relaunched the games a couple of times and I had the same results.

![screen](https://user-images.githubusercontent.com/33066084/49094434-3f5bc480-f234-11e8-9bbd-11ffc1269157.png)

I thought formats had no impact on output, but it seems something is causing discrepancies after all...

**Comment by theboy181** [comment]
Interesting. Anyone confirm this

**Comment by oddMLan** [comment]
Wtf. Weirdest bug ever!

**Comment by LegendOfDragoon** [comment]
Perhaps the dump quality isn't always the same.

**Comment by Exequiel3k** [comment]
I've never used GoodN64; simply had two different dumps from different sources...

**Comment by theboy181** [comment]
Try byte swapping the rom and see if that changes it?

**Comment by loganmc10** [comment]
It's pretty obvious that byte swapping something isn't going to make it a little more pixelated.

I don't know about PJ64, but mupen64plus will print the CRC of the game, which will be the same no matter what byte-swapping is being used. If the CRCs are the same, then they are the same ROM image.

It's most likely that you have some per-game setting for whatever emulator you are using, and it's only being applied to one ROM but not the other.

**Comment by theboy181** [comment]
I like that suggestion but when I read the OP I trust that he knows what he is doing.

**Comment by Exequiel3k** [comment]
I’m using m64p, and the only per-game setting is enable native res...

**Comment by theboy181** [comment]
What video plugin are you using? GLIDEN64 uses pregame settings

**Comment by Exequiel3k** [comment]
I’m using the latest windows m64p 64bit with gliden64 video plugin. 
I used the per-game settings file to add “native res... = enabled” for this game.

I have not messed with any other custom settings on Mario kart.

**Comment by gonetz** [comment]
May be these two dumps have different internal names? For example: "MARIO KART 64" and "mario kart 64".
per-game settings activated if ROM internal name is the same as in settings.
Right image looks as if native resolution is activated. Left image looks like window resolution is used.

**Comment by theboy181** [comment]
There is an option in the PJ64 version of GLideN64 to turn off pergame settings, does this not exist for Mupen? Can the OP please test?

**Comment by Exequiel3k** [comment]
I ran a scan using GoodN64 and I got the following:

**.Z64** -> "434389c1 2bcee11c **Mario Kart 64 (U) [!]** (L-12582912)|579c48e2 11ae9525 30ffc873 8709f078 d5dd215e|e72fdcbb 4edec325 35a62b67 2c4559b0 4b07a081"

**.V64** ->"89654ba4 871be031 **Mario Kart 64 (U) [h1C]** (L-12582912)|7b7bc18f a156601b e87a890f 950bf57f 8f2cd54e|b64b73d4 f243062b 6f48ca88 de316ac8 684e2587"

**Comment by gonetz** [comment]
You may copy Mario Kart per game-settings for different internal ROM name and get both roms looking the same.
