### ISSUE TITLE
Mortal Kombat Trilogy Slowdown Stage "The Subway"

### ISSUE THREAD

**Issue by schubertguilherme** [gonetz/GLideN64#1948]
Mortal Kombat Trilogy Slowdown in stage "The Subway" and Top Gear Hyper Bike not working textures.

**Comment by schubertguilherme** [comment]
weinerschnitzel OK thanks

**Comment by LegendOfDragoon** [comment]
keep it open lol. I dont think anyone reported the mortal kombat issue before.

**Comment by theboy181** [comment]
What is the issue?

**Comment by theboy181** [comment]
Is there a way to get to the subway via LEVEL select? Can you get a save?

**Comment by weinerschnitzel** [comment]
I didn't see open issues for these specific games/issues. @purplemarshmallow's opened issue had more to do with research into addressing framebuffer issues like seen in Hyper Bike but not specifically to track the texture issue.

Please keep open. We should track separately and not confuse these in olivier's HLE thread.

**Comment by Frank-74** [comment]
Level Select cheat.
At the character screen highlight Sonja (top line, 4th along),  press up+start.  After choosing the character you wish to play you will be able to select which level you start on.

**Comment by gonetz** [comment]
Just a savestate please.

**Comment by theboy181** [comment]
No issue here. 

This has nothing to do with GLideN64. Change the counter factor to one, or even better overclock the game with PJ64.

The tournament ladder also drops below 50Vi until it zooms in.

**Comment by Frank-74** [comment]
@theboy181 no, first time I played this game.  I've only seen the first level and subway using the level select cheat I posted above.

**Comment by theboy181** [comment]
@Frank-74  do you discord anymore, and can the OP take this issue (not really an issue) to the PJ64 GitHub? 

I would like to make this a case to review the CF=2 (default) settings. I think that CF=1 is a more optimal choice for PJ64 emulation.  I never use any other setting, unless the game has an issue with CF=1.

Anyway, this was a good observation, and I hope that it will create some conversations for the NEXT release of PJ64

**Comment by Frank-74** [comment]
@theboy181 Haven't opened up Discord since I left a while back.
I made some changes to current PJ64 git.  Added overclock to new default settings, removed HLE setting because it broke LLE, removed AIUpate from PJ64 and audio plugin.  I put a link to it at the PJ64 "Getting wrongly locked to 50 VI/s issue.

**Comment by schubertguilherme** [comment]
Thank you very much guys, solved the problem of the whole game, it is at full speed now no slowndowns at all. It's another game. Thanks to Frank - 74 and everyone. Working full speed.

![untitled](https://user-images.githubusercontent.com/36903073/49333111-4a9a5180-f5a0-11e8-93a3-984813e6b06d.jpg)

**Comment by LegendOfDragoon** [comment]
@schubertguilherme great to hear. Thanks for the report. I think you can close this issue now. Perhaps in the future, PJ64 will be set to CF=1 for that game.

**Comment by schubertguilherme** [comment]
Thanks... closing issue.
