### ISSUE TITLE
Rejection process issues

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1954]
Fox Sports College Hoops '99

During intro, grey screen appears in HLE (though unlikely to be a HLE issue as such)

![gliden64_fox_sports_hoops_99_020](https://user-images.githubusercontent.com/8987490/49685499-8c695180-fae4-11e8-8ba1-2a605665623c.png)

**Comment by olivieryuyu** [comment]
The grey disappears with the commit https://github.com/gonetz/GLideN64/commit/bb8c13cccea43f3da80dbe5bff613c9f9de04539

but all 3D as well !!!

![gliden64_fox_sports_hoops_99_023](https://user-images.githubusercontent.com/8987490/49694936-09eb9b00-fb93-11e8-8901-e9d80a1d02bb.png)

**Comment by olivieryuyu** [comment]
@gonetz

**Comment by olivieryuyu** [comment]
Mortal Kombat 4: black screen

**Comment by olivieryuyu** [comment]
space invaders

![gliden64_space_invaders_000](https://user-images.githubusercontent.com/8987490/49695157-dca0ec00-fb96-11e8-9429-8a64b990311f.png)

**Comment by gonetz** [comment]
@olivieryuyu 
Fox Sports College Hoops '99
"RSP Gfx ucode F3DLX.Rej   xbus 2.07  Yoshitaka Yasumoto 1998 Nintendo."

This ucode should use reject box instead of clipping, should not it?

**Comment by olivieryuyu** [comment]
Correct but recent implementation seems to lead to issues.

**Comment by gonetz** [comment]
Yes, I see where. Fix is ready.
