### ISSUE TITLE
[Android] Banjo-Tooie renders white with frame buffer disabled

### ISSUE THREAD

**Issue by 101cats** [gonetz/GLideN64#1958]

**Comment by 101cats** [comment]
Loading the game with any texture pack under GlideN64 will not fully load the texture pack. This is a bug.

**Comment by 101cats** [comment]
If frame buffer is disabled, you have a white game with only Banjo showing up and some items in the background that you can pick up in the game. Images don't render their size properly.

**Comment by gonetz** [comment]
"Banjo-Tooie renders white with frame buffer disabled" - it is not a bug. Dynamic shadows in that game require frame buffer emulation. Thus, closed.

"Loading the game with any texture pack under GlideN64 will not fully load the texture pack."

It is different issue, not related to original issue topic. Please open another ticket for it. Please also provide more details to reproduce: GLideN64 version, texture pack link, error message you get. All it in the new ticket of course, not there.
