### ISSUE TITLE
Bomberman 64 The Second Attack - Battle mode artifact

### ISSUE THREAD

**Issue by vadosnaprimer** [gonetz/GLideN64#1959]
![gliden64_bomberman64u2_000](https://user-images.githubusercontent.com/7092625/49698379-da10b780-fbd3-11e8-9cce-8428576ca6cf.png)

Notice how the HUD at the top looks like the texture starts to duplicate vertically and then gets cut off. This isn't visible in (what I believe to be) [console footage](https://www.youtube.com/watch?v=2oOxy6MKtXk).

ROM name: `Bomberman 64 - The Second Attack! (U) [!].z64`
PJ64 savestate: [Bomberman 64 - The Second Attack! (U).pj.zip](https://github.com/gonetz/GLideN64/files/2660595/Bomberman.64.-.The.Second.Attack.U.pj.zip)

Used PJ64 and GLideN64 latest releases and default settings.

**Comment by olivieryuyu** [comment]
S2DEX issue, works with current patreon

**Comment by vadosnaprimer** [comment]
What's the estimate for the fix to become public?

**Comment by olivieryuyu** [comment]
some weeks

**Comment by gonetz** [comment]
@olivieryuyu It does not S2DEX issue as the problem presents in LLE mode too, even in native resolution. Some issue with texture mapping.

**Comment by gonetz** [comment]
Fixed with "Use screen coordinates", #2470
