### ISSUE TITLE
Extreme-G XG2 (U) - missing culling/scissoring effect

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1963]
AL plugin the reflections work as they should (just transparent modes that are scissored to create this effect)

![image](https://user-images.githubusercontent.com/9299743/49956885-31a47100-febb-11e8-93bf-ec18fe998034.png)

GLideN64 (current)

![image](https://user-images.githubusercontent.com/9299743/49956960-5993d480-febb-11e8-9a8a-716b7bf7ab53.png)

Anyone have any idea how this effect is done?

**Comment by theboy181** [comment]
UPDATE:

Looks like 
![image](https://user-images.githubusercontent.com/9299743/49957109-b2636d00-febb-11e8-953a-f294c1d23310.png)

Was not turned on for this game - Should it not be set to on in the pergame config?

**Comment by oddMLan** [comment]
N64 depth compare should just be enabled by default globally

**Comment by theboy181** [comment]
Actually, the game seems to be broken with it on when you are in game. I tested with 2P mode and the GFX were messed up. 
![image](https://user-images.githubusercontent.com/9299743/49960942-302c7600-fec6-11e8-8948-f33b752545f6.png)

You cant use AA with this option on, so I disagree with you oddMLan.

**Comment by oddMLan** [comment]
> You cant use AA with this option on, so I disagree with you oddMLan.

You can use FXAA though.

**Comment by GamingTVYT** [comment]
Multisample-antiasing is not compatible with n64.....

**Comment by GamingTVYT** [comment]
Pictures.

**Comment by gonetz** [comment]
@theboy181 I guess you have GeForce card. Extreme-G XG2 works ok with N64 depth compare on my Radeon. It can be tricky to find, what's wrong with geforces.

**Comment by theboy181** [comment]
The first game in this series is working. :(  Try a 2p game with it enabled?

**Comment by gonetz** [comment]
Yes, 2p game works perfectly fine with N64 depth compare enabled.

**Comment by theboy181** [comment]
Hmm. I’ll do more testing. I hope anothe GeForce user can test too

**Comment by gonetz** [comment]
I do believe that the problem with  GeForce really exists. I just don't know yet how to find it. Do you see anything suspicious in GLideN64.log? Except for VI_V_SYNC_REG too big.

**Comment by theboy181** [comment]
@Nvidia, can you please test ;)

**Comment by theboy181** [comment]
Fixed in current master.
