### ISSUE TITLE
Wayne Gretzky's 3D Hockey: missing gfx and flickers (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1966]
![gliden64_w g _3dhockey_002](https://user-images.githubusercontent.com/8987490/50028250-56016a00-ffef-11e8-84a3-fe25c511d768.png)

flickers and missing gfx

**Comment by gizmo98** [comment]
S2DEX issue?

**Comment by olivieryuyu** [comment]
no

**Comment by gonetz** [comment]
It is rather Project64 issue. mupen64plus build works ok with this game.

Flickering caused by this fix: 3faa383c55. Can be avoided by choosing another swap buffers mode.

Missing graphics  - broken between release 2.0 and release 3.0

**Comment by gonetz** [comment]
There was really a bug with that game. I must be used wrong version to check, sorry.
Fixed now.
