### ISSUE TITLE
Possible Amd Regression?

### ISSUE THREAD

**Issue by GreyTalisman** [gonetz/GLideN64#1968]
Hey, The issue is i switched from my i5 intel hd chipset computer to Ryzen 5 2400 vega 11.
I am using the same build and settings but i am experiencing black borders around transparent objects like text, shadows etc. they keep flashing between black squares and then going back to normal rendering.
I would assume this is a problem with the open gl behavior of the Radeon vega gpu but it is just a guess.

Even Fps counter has black background. Alpha channel issue maybe?  When i use public release 3.0 these problems stopped. 

Tested with the latest build of gliden64+Mupenplus+project64 with Hle native resolution,Correct texture
N64 DeptCompare no Enhancements I tested most builds from latest back to public3.0.
Lle is completely broken by the way.
Some Screenshots
![1](https://user-images.githubusercontent.com/42304043/50217498-e34f1080-0399-11e9-9ed1-1bce6d44db16.jpg)
![2](https://user-images.githubusercontent.com/42304043/50217504-e77b2e00-0399-11e9-85ab-cbdb23f66daa.jpg)

**Comment by GreyTalisman** [comment]
This is a sample from Project 64, On the right side you can see Gpu utilization for last build is %13 While utilization is %70 for public release 3.0. The letter on the boxes have alpha channel issue.
Last Build
![1](https://user-images.githubusercontent.com/42304043/50223507-7abd5f00-03ac-11e9-8274-1d3d9319e44b.jpg)
Public Release 3.0
![2](https://user-images.githubusercontent.com/42304043/50223511-7c872280-03ac-11e9-9bb7-f9849a5e4c23.jpg)

**Comment by GreyTalisman** [comment]
Thanks for the reply but the issue remains.. maybe my plugin is flawed . Any chance that you can share yours with me?
![1](https://user-images.githubusercontent.com/42304043/50227317-8ada3c00-03b6-11e9-9aa7-77240df3c4ef.jpg)

**Comment by schubertguilherme** [comment]
I use & set resolution original console for avoid problems.

![01](https://user-images.githubusercontent.com/36903073/50228412-045e3400-038f-11e9-9b58-e7b41895d345.jpg)
![Uploading 02.jpg…]()

**Comment by schubertguilherme** [comment]
> Thanks for the reply but the issue remains.. maybe my plugin is flawed . Any chance that you can share yours with me? Do you also use Ryzen?
> ![1](https://user-images.githubusercontent.com/42304043/50227317-8ada3c00-03b6-11e9-9aa7-77240df3c4ef.jpg)

I use Intel Graphics HD 4000

**Comment by GreyTalisman** [comment]
Yea, This is not relevant as i mentioned in my post. I was also using  Intel Graphics HD 4000 with no problems, when i changed my computer to Ryzen 5 with Radeon Vega 11 chipset these problems start to occur different architectures and drivers mate.

**Comment by loganmc10** [comment]
Is it the same computer? Can you trying disabling shader storage?

For mupen64plus, there is a "mupen64plus" folder inside your AppData/Roaming folder, you can try deleting that as well

**Comment by GreyTalisman** [comment]
Not the same computer unfortunately. I had a mini pc from 2011 which i used for emulation but i built mini itx pc with "ryzen 5 2400g 3.9 ghz integrated radeon vega 11 Open Gl 4.6 support" just for emulation. It is wonderful and cheap. I can play ps2, gamecube, dreamcast effortlessly. But somehow i am having these issues i never had with my ancient computer. So i assume it must have something to do with the plugin. but who knows.

**Comment by Frank-74** [comment]
Have you tried alternate drivers?  If you're using amd's general reference drivers, they might not be suitable for your integrated radeon.  Cheap might mean a cutdown radeon with some features not available.  Try using the manufacturer drivers instead

**Comment by oddMLan** [comment]
AMD's Adrenalin drivers have issues with OpenGL under certain configurations. My only solution was to reinstall a newer build of Windows, then most of the issues went away.

You could using the drivers that came with the Motherboard, like @Frank-74 said. But before that you make sure to disable driver storage as per @loganmc10's suggestion to see if you still have any issues with your current drivers.

**Comment by GreyTalisman** [comment]
Thanks for the replies, This is the first time in my life that i am using amd. I was not aware of their open gl problems. I do not think i want to spend several ours just to fix this issue since other console emulators are working sufficently as i wanted. Industry is moving away from open gl and dropping support and focusing on Vulkan and DirectX. I will just wait for a new approach to n64 emulation meantime. I will close this issue.
In my research i have discovered some nice explanations. before i go i will share these with you. It will referance other people when they google about these.

From pcsx2 github:
"Due to a buggy driver OpenGL will perform poorly on AMD GPUs. The driver lacks performance optimizations and several extensions are currently broken.

The issues have been reported on the AMD support forum for a year now, but any fixes AMD has released so far have either introduced new bugs or reintroduced old bugs.

There is a PCSX2 discussion thread regarding the mentioned issues here.

SSO (Separate Shader Objects Extension) is broken on AMD drivers.
Confirmed fixed as of driver release 18.11.1
It causes garbled graphics every time the extension is enabled. It was momentarily fixed in 16.7.3 release, but it was reverted in 17.2.1 to fix the BSOD issue below. A (hopefully temporary) workaround to address the issue has been added to PCSX2. Link to issue on AMD support forum is here.

Dual Source Blending is broken on AMD drivers.
Confirmed fixed as of driver release 18.11.1
You can use 17.1.2 atioglxx.dll and override_GL_ARB_separate_shader_objects=1 gsdx.ini option to restore old behaviour in newer PCSX2 build. But be wary this causes BSODs and crashes in the display driver on Windows when Blending Unit Accuracy is set to None (so keep it at least to the default "Basic" level). Link to issue on AMD support forum is here.

OpenGL runs 10-70% slower compared to Direct3D.
This is an optimization issue on AMD's side. There is no workaround for this issue. People will need to wait for a proper working driver. Link to issue on AMD support forum is here".
