### ISSUE TITLE
1080 Snowboarding (JU) FB off breaks games ( regression)

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1976]
If you turn off FBE in this game the game will break. This is a regression. With FBE on it can mess up in different ways in some 2P modes in split screen.

![image](https://user-images.githubusercontent.com/9299743/50507663-49d7cc80-0a33-11e9-9ba2-713192cd9801.png)

![image](https://user-images.githubusercontent.com/9299743/50507728-8c010e00-0a33-11e9-9fa5-5df1fd6e3540.png)

**Comment by theboy181** [comment]
Was working fine back in March.

![image](https://user-images.githubusercontent.com/9299743/50508224-d84d4d80-0a35-11e9-838e-10fe7613dd61.png)

**Comment by theboy181** [comment]
Just a modified basic audio plugin. Nothing special just works for most of my testing

**Comment by schubertguilherme** [comment]
Very good, i can test?

**Comment by theboy181** [comment]
Hold on Ill ask.

**Comment by theboy181** [comment]
Can you join the PJ64 forums, and ask in a thread there?

**Comment by Exequiel3k** [comment]
Can we come back to the issue at hand, since I have it as well :p

**Comment by gonetz** [comment]
2P issue happens if N64 depth compare is enabled.
Currently split screen mode incompatible with N64 depth compare.

2P mode also does not work if you load it from a savestate, but I don't consider it as an issue: frame buffer based effects not guaranteed to work when game loaded from a savestate.

**Comment by gonetz** [comment]
Should be fixed now.

**Comment by theboy181** [comment]
@gonetz I had to enable N64 depth compare to make it work, with latest WIP#3? is that what you mean? 

(you tested with my cheat code) ?>

**Comment by theboy181** [comment]
![image](https://user-images.githubusercontent.com/9299743/51444538-99fe2380-1cad-11e9-8725-3dddf25f3460.png)

This is the one that forces the issue. 

81109A5A 3F00
81109A5C 4612

**Comment by gonetz** [comment]
> I had to enable N64 depth compare to make it work, with latest WIP#3? is that what you mean?

2P mode should work now with and without N64 depth compare.

> (you tested with my cheat code) ?>

No, I just run the game in VS mode. It works for me. Should I run it with the cheat code?

**Comment by gonetz** [comment]
I tried - works for me. I'm not sure that I enabled the cheat correctly, see the screen shot:
![1080](https://user-images.githubusercontent.com/8983092/51607991-ced9d700-1f48-11e9-94ae-e4c3198b48d6.jpg)
May be I need to do something else to activate the cheat?

**Comment by Frank-74** [comment]
Check Remember Selected Cheats in Settings>Advanced.

**Comment by gonetz** [comment]
Fixed

**Comment by gonetz** [comment]
@theboy181 please test with latest WIP build.
