### ISSUE TITLE
[RPi3 | cross compile] libbrcmEGL.so: undefined symbol: glPointSizePointerOES

### ISSUE THREAD

**Issue by 5schatten** [gonetz/GLideN64#1978]
Well I try to build the GLideN64 module for m64p and I use this [package ](https://github.com/5schatten/LibreELEC.tv/blob/libreelec-9.0-rr/packages/5schatten/emulation-standalone/m64p/depends-m64p/GLideN64/package.mk)for compiling. I've added a [patch](https://github.com/5schatten/LibreELEC.tv/blob/libreelec-9.0-rr/packages/5schatten/emulation-standalone/m64p/depends-m64p/GLideN64/patches/GLideN64-01-cross-compile.patch) for cross compiling that sets the correct include paths for RPi vendor files. GlideN64 works fine for my Generic buils but I struggle to make it work for my RPi builds.

Once I've startet mupen64plus it fails to load a game because of `UI-Console Error: dlopen('/usr/lib/mupen64plus/mupen64plus-video-GLideN64.so') failed: /usr/lib/libbrcmEGL.so: undefined symbol: glPointSizePointerOES`

`mupen64plus/mupen64plus-video-GLideN64.so` links to `libbrcmEGL.so` which lacks this symbol while `libbrcmGLESv2.so`  cover it.

**libbrcmGLESv2**
`supervisedthinking@linux-mint-BS:~$ nm /home/supervisedthinking/le90-rr/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.0-devel/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/lib/libbrcmGLESv2.so |grep glPointSizePointerOES
00011948 T glPointSizePointerOES`

**libbrcmEGL**
`supervisedthinking@linux-mint-BS:~$ nm /home/supervisedthinking/le90-rr/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.0-devel/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/lib/libbrcmEGL.so |grep glPointSizePointerOES
         U glPointSizePointerOES`

So I was wondering if it's my part to update my build in some way of if there is any option to add `-lGLESv2` to GLideN64

https://github.com/gonetz/GLideN64/blob/master/src/CMakeLists.txt#L117
https://github.com/gonetz/GLideN64/blob/master/src/mupen64plus-video-gliden64.mk#L138

Mupen64Plus Log file:
https://pastebin.com/AiPFvM4f

**Comment by gizmo98** [comment]
Have you patched the following line as well?
https://github.com/gonetz/GLideN64/blob/9fb63e0460bea5ca54b9df082cc722fec41cf9d4/src/Graphics/OpenGLContext/GLFunctions.cpp#L202

**Comment by 5schatten** [comment]
Yes I added a [patch](https://github.com/5schatten/LibreELEC.tv/blob/libreelec-9.0-rr/packages/5schatten/emulation-standalone/m64p/depends-m64p/GLideN64/patches/RPi/GLideN64-02-GLFunctions.patch) that updates the path according to this:

> raspi3:/usr/lib # ls /usr/lib/libbrcmGLESv2.so
> /usr/lib/libbrcmGLESv2.so

**Comment by 5schatten** [comment]
fixed by disabling gold linker & adding `libbrcmGLESv2.so` to link flags in CMakeList.txt.

**Comment by gonetz** [comment]
Should we patch CMakeList.txt in master to avoid this problem?

**Comment by 5schatten** [comment]
Have a look at my patch -> I also added `CMAKE_FIND_ROOT_PATH` for cross compilation since sysroot is mostly not equal to root.
https://github.com/5schatten/LibreELEC.tv/blob/libreelec-9.x-rr/packages/5schatten/emulation-standalone/m64p/depends-m64p/GLideN64/patches/GLideN64-100.01-cross-compile.patch

**Comment by gonetz** [comment]
Thanks! I added it with 2d15d2d20a8d4f
