### ISSUE TITLE
Fullscreen Blowing up image and cropping it.

### ISSUE THREAD

**Issue by SilentHeII** [gonetz/GLideN64#1980]
Basically, whenever I enter fullscreen with GlideN64, say with Majora's Mask or any other game, the game displays the Nintendo logo blown up and off center toward the right, cutting off more than a third of the screen. This happens with every game and the only way to fix it that appears to work is by entering the Graphic config menu, and selecting OK. Switching to fullscreen from there displays everything correctly. This happens on any aspect ratio, on any resolution, but I primarily want to use my TV's resolution of 1920 x 1080.

**Comment by gonetz** [comment]
More details please: Version of emulator, plugin, graphics card, drivers. Have you tried other graphics plugin or GLideN64 with another version of emulator?
I have no issues with 1920 x 1080 in fullscreen, and information you provided give me no clue where to dig.

**Comment by SilentHeII** [comment]
Sorry, I could have sworn I added some screenshots with my speccy, but I guess not. I'm away from my actual computer I use to play on it, but I hope this helps.

- Ryzen 5 1600 CPU
- Gigabyte NVidia 1080ti GPU updated with the latest drivers
- Project64 2.3.2
- The version of GlideN64 is the stable 3.0 release
- Angrylion works perfectly when switching to fullscreen as does the default Jabo
- I used the default settings with the plugin with the only change being the fullscreen resolution and the refresh rate defaults to 24 but neither that nor 60 resolves the issue.

**Comment by theboy181** [comment]
What happens with you RESTORE DEFAULTS?

**Comment by SilentHeII** [comment]
When I restore defaults or keep the fullscreen resolution at native, it appears to work just fine. But changing the resolution from there causes the same issue as before. 
https://imgur.com/a/PVBecbI

**Comment by SilentHeII** [comment]
Ahhh... Wow. This is rather embarrassing. Upon further investigation, it appears this issue is caused having text and icons set to 125% in Window's Display Settings.

**Comment by gonetz** [comment]
> To further expand and hopefully help those with similar issues. 

We need some knowledge base for such issues. Many such tips hidden in long closed tickets, and problem rises again.
