### ISSUE TITLE
VI fixes

### ISSUE THREAD

**Issue by gonetz** [gonetz/GLideN64#1981]
This is inspired by #1977 and https://github.com/gonetz/GLideN64/issues/1977#issuecomment-452258006
Cite from angrylions commit message for revision 87:

> rdp: new tests revealed the shocking truth: the VI aggresssively and regardlessly of any data alignment specificities cuts off either 7 or 8 pixels closest to h_start and h_end, so that nothing ever appears on the screen unless (h_end - h_start) is 16 pixels or greater (this removes marginal garbage graphics on the far right in Mario Tennis, Turok 2 Seeds of Evil intro and probably other games); 

I built angrylions software LLE plugin from the latest sources on SourceForge. Indeed, all games have black boarders from left and right. I compared picture in Indiana rendered by angrylions plugin with image from my N64 console. I don't have video capture devices to take screen shot, but as far as I can see, picture from N64 is the same as emulated one.

This fix "removes marginal garbage graphics on the far right". GLideN64 also suffers from this problem, so I ported angrylions fix to GLideN64.
Please help me to test it.
The fix is in vi_fixes branch.
Test build for Project64:
~~https://drive.google.com/file/d/1k17xP-yrATGO251ynuFDUEEjTGY2HDdS/view?usp=sharing~~
https://drive.google.com/file/d/1K0uaUdvkrcwGXhWc0tU2zeTIpCJfk42L/view?usp=sharing
Build of angrylions rev 112:
https://drive.google.com/file/d/1OxbngLjW6jaBLncM59uiwWgYxypFJJu3/view?usp=sharing

How to test:

1.  Configure GLideN64:
* Select windowed resolution 1024x768
* Select N64-style 3 point filtering
* Select Original N64 resolution
2. Select LLE mode in emulator: Options->Settings->Plugin uncheck Graphics HLE
3. Run any game
4. Run another instance of Project64, select "My little plugin" (it is angrylion's plugin) as graphics plugin and run the same game.
5. Both plugins should render nearly the same picture, with the same black boarders and the same graphics inside these boarders.

**Comment by theboy181** [comment]
@legendofdragoon had done something else in AL experimental plugin. Instead of extending the black bars, he swapped the right hand image to the left side of the screen, maximizing the entire image, while correcting the issue. 

His fix didn't remove it, it improved it. Could you possible address it in the same way?

**Comment by LegendOfDragoon** [comment]
I didn't do anything special for this, to be honest.

>I also think that disabling AA filters in the ROM can fix this issue too.

I don't think so, but i'd be very intrigued if it did fix this issue.. The problem is that in certain games, the RDP isn't always drawing to the first and last 8 pixels of each row, which is why you're seeing garbage pixels.

**Comment by gonetz** [comment]
I fixed several issues in VI emulation code. Link to test build updated.

**Comment by oddMLan** [comment]
GLideN64 Latest WIP with VI fixes (85062921)
![imagen](https://user-images.githubusercontent.com/7278372/51297854-6d14ec80-19df-11e9-8308-584f6e33178c.png)
![imagen](https://user-images.githubusercontent.com/7278372/51297990-fc220480-19df-11e9-82e9-65d06e410efd.png)

GLideN64 8e621210
![imagen](https://user-images.githubusercontent.com/7278372/51297967-dc8adc00-19df-11e9-90f3-259807766eb7.png)
![imagen](https://user-images.githubusercontent.com/7278372/51298019-16f47900-19e0-11e9-8f3e-07a85f6e4304.png)

All default settings, as you can see there is some slight blurring introduced with the VI fixes, while the previous version without them looks crisp... is this intended? 🙁

**Comment by theboy181** [comment]
VI filters are working in HLE?   I love it, but what is actually going on?

**Comment by theboy181** [comment]
@oddMLan we should try to see if turning off AA filters works in HLE now. :)

**Comment by oddMLan** [comment]
@theboy181 I'm pretty sure VI filters are not implemented, it's just some weird resizing taking place blurring the picture. Like it's one pixel off or something.

**Comment by theboy181** [comment]
looks like just changing 
![image](https://user-images.githubusercontent.com/9299743/51300276-312e5700-19e0-11e9-82cc-366c9290d3db.png) takes away the AA effect. :(

**Comment by LegendOfDragoon** [comment]
Imo, that smoothing looks better for super mario :smile: .

**Comment by gonetz** [comment]
@oddMLan 
< is this intended? 
Not exactly. Video Interface maps RDP image to TV screen. VI emulation part does the same: maps FBO texture to OpenGL main buffer. For SM64,  RDP image is 320x240 while output image is 640x480. Thus, some scaling is used. Plugin tries to create FBO texture of the same size as size of output buffer to avoid scaling and get crisp image. It is not always possible because VI may add black borders to output image  and image in FBO texture must be scaled to fit the place among the borders.
This fix emulates "VI cuts off either 7 or 8 pixels closest to h_start and h_end". If angrylion's implementation is correct, VI just do not show first 8 and last 8 pixels of mapped image, drawing them black. Since each pixel in RDP image line corresponds to two pixel in output image (320 => 640) VI will draw first 8 pixels black, then RDP line [4, 316] mapped to [8, 632], then again 8 black pixels. Plugin needs to calculate these offsets for input and output images, taking in account the scale with which original RDP image is mapped to screen and scale between VI image size and user window size. I guess some rounding errors during all these mappings lead to difference between size of input image and output one, which leads to use of bilinear filtering and thus blurring.

**Comment by olivieryuyu** [comment]
Ken Griffey Jr.'s Slugfest intro shows nearly the gfx but they are flickering now.

**Comment by oddMLan** [comment]
The unintended blurriness is fixed \o/
