### ISSUE TITLE
Conker PAL

### ISSUE THREAD

**Issue by AlexN64gamer** [gonetz/GLideN64#1982]
Can someone please tell me what are the best settings to use with Project64 2.3.2 and GlideN64 lastest WIP version for Conker´s Bad fur day PAL version? are there any specific options I have to check? thank you for your time guys I appreciate it : )

**Comment by oddMLan** [comment]
This is an issue tracker to report issues and bugs, not a support forum.

But I can tell you that you don't need to worry about the settings, the defaults are the best.

@gonetz  Should we have a FAQ in the Wiki?
