### ISSUE TITLE
Ocarina of time - Temple of time issue

### ISSUE THREAD

**Issue by LuismaSP89** [gonetz/GLideN64#1984]
![sin titulo6](https://user-images.githubusercontent.com/12205048/51149914-6e6dda00-1864-11e9-854b-e2fba9b37a16.jpg)
![sin titulo5](https://user-images.githubusercontent.com/12205048/51149915-6e6dda00-1864-11e9-9750-d33efeb05cdd.jpg)

Some wrong graphics here. This problem seems to happen only in this area (At least for me) you can test it by loading a game from temple of time. Go outside. Exit emulator, reload, and the problem happens. The first time I thought the problem is the with "store texture cache" option but this happens too even with that option disabled. (But less frequently) With this option enabled, this happens 100% for me. With the option disabled, only happen sometimes (If link rolls and hits a wall in this area the problem is triggered when the option is disabled)

EDIT: After more and more testing, it seems that the problem is related with the texture enhancement. You need to select "Texture  sharp filtering 2 + 6brxz, hq4x,etc" and voilá, the problem is here.

I put my Gliden64.ini in order to test it.
[GLideN64.zip](https://github.com/gonetz/GLideN64/files/2757644/GLideN64.zip)

My specs: 
Windows 10 x64
i7 4790k
16GB DDR3
GTX 970

Using project64 (x86 build)
Using Gliden64 build from 12-Jan-2019

**Comment by LuismaSP89** [comment]
[test2.zip](https://github.com/gonetz/GLideN64/files/2757752/test2.zip)
Another video with the "roll triggering"

**Comment by gonetz** [comment]
Backgrounds stripped mode does not work good in non-native resolutions even without any enhancements. That is why I recommend to use it with "Render 2D elements in native resolution" mode. 
Texture filtering or enhancements work poor for stripped backgrounds.
You also may use "Disable enhancements for backgrounds" option.
I corrected it, and now it effectively disables enhancements of backgrounds regardless of selected "Backgrounds rendering mode".

**Comment by LuismaSP89** [comment]
But this problem doesn't happening before "as far as I know" even using enhancements for backgrounds. ¿?

**Comment by gonetz** [comment]
"Stripped" backgrounds mode implemented quite recently.
Previously you could met this problem only in LLE mode.

**Comment by LuismaSP89** [comment]
Ok, closing the issue since it's solved disabling the background enhancements.
