### ISSUE TITLE
Printf debug statements broken in LLE in Multiple Debug/Prototype games.

### ISSUE THREAD

**Issue by AriaHiro64** [gonetz/GLideN64#1989]
Noticed this a while ago in zelootma but seems to be a wide spread issue. seems to be related to rendering 2d at native resolution.

**Comment by AriaHiro64** [comment]
When disabled it works but with noticable lines on the edge of the text, the last commit that worked seems to be oct 17. These really benefit from the option tho as they are not filtered on N64 hardware anyway.

**Comment by gonetz** [comment]
Fixed.
