### ISSUE TITLE
Indiana Jones: Project 64 Snow Particles Issues

### ISSUE THREAD

**Issue by billkings95** [gonetz/GLideN64#1998]
@gonetz Hi!

I'm using the latest GlideN64 builds to play Indiana Jones and the Infernal Machine in Project64 emulator (version 2.4.0.857).

The game seems to work fine, except that I need to change the CPU core style to Interpreter before finishing each level because the emulator crashes in the Indy Trading Post scene.

In addition, in Tibet levels, snow particles are going through walls and entering indoor places (I've attached a screenshot below).

Is there a configuration in the plugin that can solve this particle problem, or is it a Project64 bug?

Thanks for the help and keep up the great work! 👍

![](https://user-images.githubusercontent.com/40545497/52181639-30b4ff00-27db-11e9-996c-d1e43b10893d.PNG)

**Comment by gonetz** [comment]
CPU issues are not my responsibility. They can't be fixed on graphics plugin side.

The issue with snow particles is fixed in commit 78e98d88. Please download my ;latest WIP build from #1574 to test it.

**Comment by billkings95** [comment]
@gonetz,

The fixes applied in the last version of the plugin (GLideN64_837f173e) solved the problem of the snow particles during the gameplay (screenshots below).

Thank you for your help in solving this problem and for developing this awesome plugin for the Nintendo 64 emulation scene. 

After long years waiting to play this game, I'll be finishing it in the coming weeks. Any other graphic issues I might find, I'll be in touch through here. 

Thanks! 😄 

![indy-1](https://user-images.githubusercontent.com/40545497/52311745-2cc9de00-298f-11e9-94b2-d39251b7e1f0.PNG)

![indy-2](https://user-images.githubusercontent.com/40545497/52311748-32272880-298f-11e9-97dc-941f70b23199.PNG)
