### ISSUE TITLE
Paper Mario - Black lines around Badge Points Menu

### ISSUE THREAD

**Issue by Kidboy17** [gonetz/GLideN64#2002]
There are now these black lines/borders around the Badge Points in the Badge Menu. The only option that removes these black lines is having the output in Original n64 resolution enabled.
![gliden64_paper_mario_000](https://user-images.githubusercontent.com/37382324/52508606-0cc23680-2baa-11e9-964a-245b071d7245.png)

**Comment by gonetz** [comment]
"There are now"  - is it recent glitch, which does not present in older builds?

**Comment by Kidboy17** [comment]
The glitch is present in older builds. Public Release 3.0 has the glitch but can be removed if you enabled "Render 2D Elements". 
The second oldest build that I could access is this one from Jan 12 https://drive.google.com/file/d/16wfY8ogj51HlvD4mBayQAzPhz8UwbCdw/view?usp=sharing 
Google gives me errors saying it violates their terms if I try to download anything older from them. The glitch is present in this one and enabling " Render 2D Elements" does not fix the problem like it did in Public Release 3.0

**Comment by Kidboy17** [comment]
This is still present

**Comment by IronYoshi64** [comment]
Yeah this is literally like 1 of 2 remaining visual bugs I know of in this game for me. If this can fixed, without causing regressions, that will be awesome! :)

**Comment by Kidboy17** [comment]
![GLideN64_MARIOKART64_000](https://user-images.githubusercontent.com/37382324/81508455-16f54800-92b9-11ea-91bb-000319e357f4.png)
 
There are black line boxes around the arrows in Mario Kart. Only way to fix this is use Original N64 Resoultion option.I am wondering if this is the same problem that Paper Mario has.

**Comment by gonetz** [comment]
Fixed with "Use screen coordinates", #2470
"Enable native-res bounds for texture coordinates" should be on.
![paper_mario-007](https://user-images.githubusercontent.com/8983092/115502428-1faf1600-a29f-11eb-933d-4c87e9203f2d.png)
