### ISSUE TITLE
mupen64plus 64bit windows builds

### ISSUE THREAD

**Issue by oscarbidabehere** [gonetz/GLideN64#2003]
I checked https://github.com/gonetz/GLideN64/issues/1574
and https://ci.appveyor.com/project/gonetz/gliden64/builds generated artifact and only found 32bit builds of the plugin. Is there some place I could get the 64bit windows builds for mupen64plus or maybe build with appveyor both versions?

Thanks in advance!

**Comment by gonetz** [comment]
I usually recommended m64p builds (https://m64p.github.io/) but now download links are available only to to Patreon subscribers. It is still the best option if you don't mind to support Logan's efforts.
Other options: wait for update of my WIP builds or build from sources. Latest option is the simplest if you have Visual Studio 15 or 17 installed. I'm planning to add appveyor script to build both 32bit and 64bit versions, but it is low priority task.

**Comment by gonetz** [comment]
I added appveyor script to build both 32bit and 64bit versions: d12f9fe5
Now you may visit
https://ci.appveyor.com/project/gonetz/gliden64/history
and download build artifacts for any platform.
