### ISSUE TITLE
MSAA crashes in Project64 on Intel Celeron N2830

### ISSUE THREAD

**Issue by Pingler** [gonetz/GLideN64#2004]
Turning on MSAA and then loading any rom results in a black screen with an error message in Project64 2.3 and more recent dev builds. The game never starts, but ending emulation under the file menu returns to Project64's home screen.
<img width="441" alt="msaa panic handler" src="https://user-images.githubusercontent.com/47263169/52537985-f8fa0a00-2d3a-11e9-9b28-e50dc6f5e281.png">

Turning on MSAA while the game is running displays another black screen and error message. Clicking ok immediately ends emulation, returns to the home screen, and brings up the Line 605 message again
<img width="440" alt="msaa panic handler 2" src="https://user-images.githubusercontent.com/47263169/52538263-a15d9d80-2d3e-11e9-94d3-11017b9b692f.png">

In Project64 1.6, MSAA simply crashes the emulator.

Tested with different GLideN settings, in HLE Graphics, LLE Graphics, GlideN64 3.0 and more recent builds, with default RSP, with several versions of HatCat's Rsps, Aziaudio, Interpreter mode; doesn't seem like any combination of plugins or  settings fixes the issue.

Intel Celeron N2830, Intel HD Graphics, Windows 8.1, 4gb ddr3 ram

**Comment by Kidboy17** [comment]
I do not experience any black screens or error messages when using MSAA. I am using Project 64 dev build 2.4.0.866 with latest WIP build of GlideN64. Video card is Nvidia GTX 780 ti, maybe integrated graphics can't run something like MSAA?

**Comment by Pingler** [comment]
https://github.com/gonetz/GLideN64/issues/1831#issuecomment-394356080
n2830 supports opengl 4.0, MSAA works in other programs

**Comment by gonetz** [comment]
@Pingler I tested Project64 with GLideN64 using 8x MSAA on integrated Intel HD Graphics 630. It works without issues. I hardly can help you because I can't get such hardware as yours. Anyway, can you check content of gliden64.log, which is located in Project64\Plugin\GFX\gliden64.log ? May be it has some error messages related to plugin's initialization.

**Comment by Pingler** [comment]
Seems to only say "vactivelines lesser than 0" regardless of starting with msaa on or off
[gliden64.log](https://github.com/gonetz/GLideN64/files/2880265/gliden64.log)

**Comment by gonetz** [comment]
It is not related to plugin initialization. I need to remove that message from release builds, as it rather confusing for users.
I can't fix the issue with MSAA without hints of what is going on.
I only may suggest you to use FXAA as an alternative.
