### ISSUE TITLE
NET64 issues

### ISSUE THREAD

**Issue by Zwataketa** [gonetz/GLideN64#2008]
So, I ran into graphical issues with NET64 (an online client for Super Mario 64 that has special characters, for reference) using the Glide64 plugin, leading me to want to try the GlideN64 client. It doesn't work once the client is connected if I change characters if I try to use GlideN64. 

While this technically doesn't count as an "issue with the plugin" per se, could it be possible to make the plugin work with Net64? Also, here's the error I get upon connecting the client for reference: "CN64System::RunRSP
Unknown memory action

Emulation stop"

**Comment by oddMLan** [comment]
The Net64 mandates use of a modded version of Project64 + a modded Glide64 with extra RDRAM (allowing above 8MB RDRAM) to load all the characters. Unfortunately the source to that modded version was never released, so the modifications to make Net64 with GLideN64 and the latest version of Project64 are not implemented. In theory it is possible to implement those modifications but they have to be done at the emulator level first.

**Comment by gonetz** [comment]
Lets close it until situation with modification's sources will change.
