### ISSUE TITLE
Turok 64 Missing lens flare

### ISSUE THREAD

**Issue by DaRkL3AD3R** [gonetz/GLideN64#2009]
https://imgur.com/a/boa9Crp

The strange thing is, I made a save state with Angrylion plugin and when I load that save state, lens flare is rendering properly on GlideN64. But eventually it crashes the plugin when I restart the game from in-game menu.

**Comment by gonetz** [comment]
Do you run GlideN64 in HLE or LLE? Do you have depth buffer render enabled?

In most games lens flare effect works properly only if depth buffer filled with correct values.
GlideN64 has software render for N64 depth buffer, which produces quite correct result, but it works only in HLE mode.

Regarding save state with Angrylion plugin: save state contains dump of whole RDRAM. Angrylion plugin renders pixel-accurate depth buffer, which is stored in RDRAM. When you load savestate made with Angrylion plugin you have perfect depth buffer and lens flare works correct.

**Comment by DaRkL3AD3R** [comment]
Both HLE and LLE has no lens flare. And do you mean the experimental depth buffer shader setting? Because yes I have tried that and still nothing.

**Comment by gonetz** [comment]
No, I mean "Copy video card depth buffer to N64 memory" option, which should be set to "In software" to get the effect working.

**Comment by DaRkL3AD3R** [comment]
Yes that setting was already set to software depth buffer by default. Thanks for clearing that up.

**Comment by gonetz** [comment]
I found why it does not work. Turok uses the same mechanism for lens which Perfect Dark uses for coronas.
It must be enabled per game.
Now it works, but you need to set "Copy video card depth buffer to N64 memory" option to "From VRAM". It is rare case, where this method works better than software render. Software render does not work with alpha and can't discard pixels, which should be discarded by alpha test. It rarely has impact on result of depth buffer effect, but this is a case.

**Comment by DaRkL3AD3R** [comment]
I cannot replicate those results. As you can see, setting it to "From VRAM" doesn't work for me. Still no lens flare: https://i.imgur.com/uhLkcY6.png

I have tried LLE and HLE, many other settings. What am I missing?

**Comment by gonetz** [comment]
I made several fixes. You need to make build from current master branch and test with it. Or wait for my next WIP build.

**Comment by DaRkL3AD3R** [comment]
Fixed now with latest builds. Thanks, one less thing to worry about now.
