### ISSUE TITLE
Background dumping inconsistent (Zelda OoT)

### ISSUE THREAD

**Issue by GhostlyDark** [gonetz/GLideN64#2010]
We noticed differences in background dumping in #2007.
Affected background files are the **big ones**, which can either be loaded as **one piece** (bgMode aka backgroundsMode = 0) or **splitted** (bgMode aka backgroundsMode = 1).
The **file size** of the dumped images differs with using different **RSP** plugins.
As far as my testing goes, Interpreter vs. Recompiler settings do not make a difference.

As an example, this is Link's House background from above (start the game and press C-Up in Link's House):

PJ64 RSP: `THE LEGEND OF ZELDA#CDAD9309#0#2_all` (153.942 bytes)
![the legend of zelda cdad9309 0 2_all](https://user-images.githubusercontent.com/31742919/53093380-8e558500-3517-11e9-8e18-81eab127e5f0.png)

m64p RSP-HLE: `THE LEGEND OF ZELDA#CBA9E984#0#2_all.png` (154.496 bytes)
![the legend of zelda cba9e984 0 2_all](https://user-images.githubusercontent.com/31742919/53093419-aa592680-3517-11e9-8d20-ef013150828f.png)

m64p RSP-CXD4-SSE2: `THE LEGEND OF ZELDA#631C2E06#0#2_all.png` (154.768 bytes)
![the legend of zelda 631c2e06 0 2_all](https://user-images.githubusercontent.com/31742919/53093453-bf35ba00-3517-11e9-8227-ec05a7c24bea.png)

**Note:** Dumping the background as **splitted files** is just as inconsistent. On top of that, the background files are then **corrupted**.
![the legend of zelda 97bcc54d 0 2_all](https://user-images.githubusercontent.com/31742919/53093699-75999f00-3518-11e9-9452-b09bdbbb7dc5.png)

**Comment by gonetz** [comment]
PNG is compressed format, so if content is different file size may change too. I'm sure images dimensions are the same.  Different background content is not graphics plugin issue: plugin just reads ready image  from RDRAM.

**Comment by GhostlyDark** [comment]
Not sure if it is just the RSP plugin, since I did get yet another set of textures IDs when using the mupen64plus-rsp-hle with mupen64plus-qt and a WIP of mupen64plus (the one without a GUI).

Whatever the cause, it does really not depend on the graphics plugin, since the Project64 dumps are done with Rice Video and loaded fine with GlideN64 with an otherwise same configuration.

But why do splitted background files show signs of corruption? Not that is matters much to me, since one piece backgrounds are far easier to retexture and the splitted backgrounds are varying in checksums regardless. Just curious.

Closing this as the different file sizes / checksums are not a fault of GlideN64.

**Comment by weinerschnitzel** [comment]
RSP does the jpeg decoding for those textures. 

Mupen64plus hle rsp handles this, and zilmar ended up using it for the android version of pj64. I'd bring this up on on pj64s github because it's an inconsistency between the rsp recompiler and the hle rsp plugin for android.

If you want to test a zilmar spec mupen64plus rsp hle plugin, I put one on emutalk a few years ago.

http://www.emutalk.net/threads/55880-Mupen64Plus-RSP-HLE-v2-5-Zilmar-Spec

**Comment by GhostlyDark** [comment]
@weinerschnitzel I still wait for a new WIP build of GlideN64 to be able to dump the background textures with Project64, but I did see that the game falls back to vanilla textures in a few instances when using my texture pack with that RSP.

**Comment by GhostlyDark** [comment]
Regardless of the RSP plugin, splitted backgrounds are always corrupted upon dumping. That might be an issue with GlideN64.
