### ISSUE TITLE
STARCRAFT 64: does not work with one piece option

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#2013]
in game the game is messed up

**Comment by gonetz** [comment]
Should be fixed now.

**Comment by olivieryuyu** [comment]
![here](https://user-images.githubusercontent.com/8987490/53643637-dd489c00-3c34-11e9-9745-7a6928ae653a.jpg)

**Comment by olivieryuyu** [comment]
![gliden64_indiana_jones_020](https://user-images.githubusercontent.com/8987490/53646188-dae94080-3c3a-11e9-817e-b3b7200c789a.png)

**Comment by olivieryuyu** [comment]
![gliden64_indiana_jones_012](https://user-images.githubusercontent.com/8987490/53646494-9ca05100-3c3b-11e9-98a7-4f0d1e521c17.png)

**Comment by olivieryuyu** [comment]
![ground2](https://user-images.githubusercontent.com/8987490/53646555-c194c400-3c3b-11e9-8eb5-7851f2d50c25.jpg)

**Comment by olivieryuyu** [comment]
![gliden64_battle_for_naboo_008](https://user-images.githubusercontent.com/8987490/53647019-e0478a80-3c3c-11e9-9d67-3f403edd1509.jpg)

**Comment by olivieryuyu** [comment]
![gliden64_battle_for_naboo_021](https://user-images.githubusercontent.com/8987490/53647747-79c36c00-3c3e-11e9-9fbb-546b15724390.png)

**Comment by olivieryuyu** [comment]
![gliden64_indiana_jones_000](https://user-images.githubusercontent.com/8987490/53648174-885e5300-3c3f-11e9-9a04-faa0dab14e56.png)

**Comment by gonetz** [comment]
What is it?

**Comment by olivieryuyu** [comment]
the pics used in the wiki

https://github.com/gonetz/GLideN64/wiki/The-masterpiece-graphic-microcode-behind--the-Nintendo-64-version-of--Indiana-Jones-and-the-Infernal-Machine-and-Star-Wars-Episode-I:-Battle-for-Naboo

**Comment by gonetz** [comment]
Interesting way to add pics to wiki.
It would be better to open new task for it though.
