### ISSUE TITLE
gasp: wrong depth in menu

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#2019]
![gliden64_g a s p fighters ne_000](https://user-images.githubusercontent.com/8987490/53697886-3dc30f00-3dd6-11e9-9981-fd55267cccfb.png)

**Comment by gonetz** [comment]
Are you using the latest WIP build? If yes, please give me your ini file.
I can't reproduce the issue:
![gliden64_g a s p fighters ne_000](https://user-images.githubusercontent.com/8983092/53790610-ed74ba00-3f59-11e9-91e4-50c1173bf834.png)

**Comment by olivieryuyu** [comment]
i do use the last WIP. Tried with PJ64 and Mupen. I am under Nvidia.

**Comment by gonetz** [comment]
It is HLE bug. I tested with LLE, sorry.
