### ISSUE TITLE
Make GLideNUI a git submodule in a separate repo

### ISSUE THREAD

**Issue by oddMLan** [gonetz/GLideN64#2020]
Also include only the minimal qt components necessary to compile GLideNUI, instead of having to download and compile Qt in its entirety (the non-lazy way) which could take a couple hours at least (4 hours on my computer).

Here's a link to the dolphin-emu qt repo which handles it this way.
https://github.com/dolphin-emu/ext-win-qt

You could theoretically do the same with GlitchHQ, freetype and all other third-party components. One big advantage to this is that every individual component should be easier to update from the upstream. To clone all the submodules when setting up a local repo, just run `git submodule update --init --recursive` in the cloned directory.

Thoughts?

**Comment by gonetz** [comment]
I see no benefits.

> One big advantage to this is that every individual component should be easier to update from the upstream. 

It is not necessary. GLideN64 has no needs in updated third-party components. Those which provided by OS or comes with repo are enough.

GLideNUI by itself is a small project and it can live inside the main repo. Currently you may clone GLideN64, run cmake command to setup, run make and that's all. On windows, you just load the solution with Visual Studio and build. If you need to build GLideNUI, you download ready static QT libs (see https://github.com/gonetz/GLideN64/wiki/Build-From-Source-(Windows)) place it somewhere and set path to them in Visual Studio QT plugin. You do it just once and forget about that stuff.

Don't forget that Dolphin as a large application, while GLideN64 is mere plugin.
