### ISSUE TITLE
ready 2 rumble 2 : wrong gfx in intro

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#2021]
![gliden64_ready_to_rumble_000](https://user-images.githubusercontent.com/8987490/53740352-4a0da180-3e94-11e9-804a-e27e40cb14b6.png)

**Comment by gizmo98** [comment]
Looks like a tile loading issue. 1080 Snowboarding had an comparable issue:
https://github.com/gonetz/GLideN64/issues/1824

**Comment by gonetz** [comment]
Fixed. Test build:
https://drive.google.com/file/d/1SFUb9-jLnnQO6k1XHtJg5e_zhcRL8zW8/view?usp=sharing
