### ISSUE TITLE
Chou Kuukan Nighter Pro Yakyuu King 2 (J) missing polygons in HLE

### ISSUE THREAD

**Issue by gonetz** [gonetz/GLideN64#2023]
During intro, some polygons are missing at the bottom of 3D models:
![GLideN64_���Է���ݸ�2_003](https://user-images.githubusercontent.com/8983092/54084915-0a4e2a80-436a-11e9-9870-f9d2517735cf.png)

LLE is ok:
![GLideN64_���Է���ݸ�2_000](https://user-images.githubusercontent.com/8983092/54084923-2f429d80-436a-11e9-84a7-c72eaaecee7d.png)

**Comment by olivieryuyu** [comment]
glide64 and other plugin does not have this issue.
