### ISSUE TITLE
Mario Paint Studio (64dd) requires render N64 fb to output

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#2024]
otherwise there is no hand in menu

![GLideN64__000](https://user-images.githubusercontent.com/8987490/54108639-c9432e00-43dc-11e9-83eb-c68a89e37c6a.png)

internal name (cart hack): 

NUD-DMPJ-JPN_convert

Original 64dd dump:

DMPJ

@gonetz 

Can you add this in the ini? :)

**Comment by gonetz** [comment]
Done: 4456d09b5
