### ISSUE TITLE
Unable to photograph Gloomy Galleon Fairy - Donkey Kong 64

### ISSUE THREAD

**Issue by teconmoon** [gonetz/GLideN64#2026]
DK64 for the most part works great with this plugin, however there is a bug that prevents you from photographing a fairy in the Gloomy Galleon level.

One of the banana fairies is in a cage in a sunken ship area accessible by Tiny. The cage itself can’t be entered, but the game intends for you to photograph the fairy through the cell bars. The cell bars are a flat texture with transparency, but for whatever reason the game can’t take the picture through the bars as intended. Someone reported this issue with Glide64 a long time again, and the workaround was to use Jabo’s plugin for that once section of the game (wasn’t ever resolved)

The game has a red frowny face / green smiley face to indicate whether or not the camera recticle is on the fairy or not before taking the picture, but even if you’re pointing right at the fairy it never turns green, therefore the picture can’t be taken.

I’ll try and upload a save state soon to test with

**Comment by gonetz** [comment]
Yes, I need a save state to test.
This is obviously a frame buffer effect. It probably needs special support in code. For example, GLideN64 has some special code for camera in Zelda MM.
Another solution, which may help you right now is to use FBInfo, that is info from emulator about frame buffer reads and writes. It helps to emulate fb effects in Jet Force Gemini and in Pokemon Snap. You need to use Mupen64 or mupen64plus to get FBInfo. FBInfo support is disabled in GLideN64 for mupen64plus by default. You need to uncheck "DisableFBInfo" option to enable FBInfo.

**Comment by teconmoon** [comment]
Thanks for the response. Please find the save state linked below. I went ahead and tried enabling FBInfo per your previous reply, it didn't allow the fairy to be photographable and also broke screen transitions such as selecting a save file or entering / exiting the tag barrels.

The controls for the camera is Z + C-down to equip the camera, and A to take a picture. The smiley face should turn green when the fairy is in the recticle. This is the only area of the game affected by this issue that I have found so far.

https://drive.google.com/open?id=1uLe8fEDr5pNb82LtNhnoqh18DmscDVwd

**Comment by gonetz** [comment]
Ok, the issue is easy to solve. FBInfo really does not help much there.
As I understand, the problem is with depth buffer. The game uses depth buffer data to detect that the fairy is in the rectangle. For some reason, data prepared by default software depth buffer render is not precise enough. You need to set "EnableCopyDepthToRDRAM" to 1, that is copy from VRAM. That is enough to take the picture:
![donkey_kong_64-024](https://user-images.githubusercontent.com/8983092/54472189-1cf7b200-47f7-11e9-832e-3189f7f3d5f6.png)

**Comment by teconmoon** [comment]
That worked, thanks! I ended up adding this to my GLideN64.custom.ini file:

[DONKEY%20KONG%2064]
Good_Name=Donkey Kong 64 (U)
frameBufferEmulation\copyDepthToRDRAM=1

**Comment by oddMLan** [comment]
Then the INI needs to be updated, no?

**Comment by olivieryuyu** [comment]
there is many games that needs depth video from vram because in software it does not work. This is odd.

**Comment by gonetz** [comment]
Many? Turok, this one. What else?

Software depth render is intentionally simple and thus imprecise. Precise render requires color and alpha processing. It is not odd that sometimes lack of alpha processing does matter.

**Comment by gonetz** [comment]
Regarding of adding copyDepthToRDRAM=1 to custom.ini: if it does not cause slow downs it should be added.

**Comment by olivieryuyu** [comment]
Coronas in 108 snowboarding does not work in software for instance. I cannot remember of other games out of head but I think there is others.

Bad thing also is that software is needed for the building collision in Body Harvest but then fb effects for the map does not work. fb efffects works with from vram option but then the collision does not work..

**Comment by teconmoon** [comment]
Hi there, lots of good discussion here. In response to @gonetz, adding the flag to custom.ini for Donkey Kong 64 hasn’t resulted in slowdown, I’d recommend adding it to the ini

**Comment by gonetz** [comment]
> Coronas in 1080 snowboarding does not work in software for instance.

In which part of the game? For example, coronas work ok in intro with software depth render.


> adding the flag to custom.ini for Donkey Kong 64 hasn’t resulted in slowdown, I’d recommend adding it to the ini

Ok, thanks.

**Comment by PiXHULA** [comment]
@gonetz Hi! I've been experiencing the same issue. Would it be possible to get some reference on where and how to change the setting? Which file? mupen64plus.ini? And do I only change the dk64 version I'm playing on or all of them in that file?

Thanks in advance!

**Comment by gonetz** [comment]
@PiXHULA 
This setting already changed for DK64 in GLideN64.custom.ini
This file included into main and wip releases.
Make sure that this file exists in the same folder where plugin's dll file placed.
You need to enable custom settings in plugin's settings.
These settings usually stored in mupen64plus.cfg. You need to set "EnableCustomSettings" to True.
If you are using mupen64plus with some GUI launcher, mupen64plus-gui for example, you may do it with GUI. Otherwise open mupen64plus.cfg in text editor and correct the setting.
