### ISSUE TITLE
Android; Conker breaks at 4K with multi-threading.

### ISSUE THREAD

**Issue by retrobenny** [gonetz/GLideN64#2029]
On my Shield TV Pro (2015) the graphics freak out on Conker when the walking to the bar scene starts within a few seconds but only when multi-threading is enabled.

Github is utter garbage for attachments! (on Android,my Shield TV in a browser)
I would post an image but it won't let me for some reason because it never goes through!!!

Sad part is that I couldn't even use the built-in screenshot function on Mupen64Plus FZ Edition because its not generating screenshots for some reason either.
I had to use some app to get the screenshot to begin with.

Micro$oft kind of ruined Github because it was perfectly fine before they took it over,I was able to upload files and interact with other options which now I can't even access at all!

**Comment by retrobenny** [comment]
Oh yeah,it was the F * * * * * * edit button that is also broken since they took over,clicking it does NOTHING on my particular Android device.

**Comment by retrobenny** [comment]
https://drive.google.com/open?id=1GrINToOFXAujLm1MY2Olv7IKs9971-M4

**Comment by fzurita** [comment]
Looks like a buffer is being overrun. I'll take a look, thanks for reporting.

**Comment by fzurita** [comment]
@retrobenny What are your exact settings? I'm having problems reproducing this.

**Comment by retrobenny** [comment]
Here is a slimmed down version for my most recent custom GLideN64 profile.
(slimmed down by removing every instance of glide64mk2 and rice and gln64 entries)

[ThreadN64]
CorrectTexrectCoords=0
EnableNoise=True
enableHalosRemoval=False
videoPlugin=libmupen64plus-video-gliden64.so
DisableExtraMem=False
txCacheCompression=False
txEnhancementMode=0
MaxAnisotropy=16
viInterpolation=0
EnableCopyAuxiliaryToRDRAM=False
viMode=0
viHideOverscan=False
r4300Emulator=2
txHiresEnable=False
EnableLOD=True
EnableLegacyBlending=False
txHiresFullAlphaChannel=False
BackgroundsMode=1
ForceGammaCorrection=False
EnableHWLighting=True
GammaCorrectionLevel=10
txCacheSize=128
rspSetting=rsp-hle
EnableCopyDepthToRDRAM=2
UseNativeResolutionFactor=0
txFilterMode=0
ForceDepthBufferClear=False
EnableCopyColorToRDRAM=3
EnableFBEmulation=True
WidescreenHack=False
EnableCopyColorFromRDRAM=False
txSaveCache=False
bilinearMode=False
EnableNativeResTexrects=False
BufferSwapMode=2
EnableFragmentDepthWrite=True
txDeposterize=False
EnableN64DepthCompare=False
txFilterIgnoreBG=False
FXAA=True
txForce16bpp=False

Also,take note that I used the ADB screen size command (wm size 3840x2160) to make my Shield TV show in true 4K on top of manually using the resolution settings for 4K 60hz.
This adb change seems to impact the limited 3GB of ram quite a bit.
And the current version recently updated still has the issue upon testing moments ago.

**Comment by fzurita** [comment]
Thanks!

**Comment by fzurita** [comment]
Is it happening anywhere in the game?

**Comment by fzurita** [comment]
@retrobenny what was the exact resolution that you picked?

**Comment by fzurita** [comment]
Ok, found the problem, easy fix. I'll include the fix next update.

**Comment by fzurita** [comment]
@retrobenny Please test the latest in the Play store.

**Comment by retrobenny** [comment]
No longer get the vertex explosion issues,though I think I may have seen a tiny moment of slight glitching when Conker enters the door where pieces vanish very briefly.
This might be from me turning off the flickering removal option (not GLideN64 related,its a global option) since I found that it seems to no longer happen,at least not on Shield TV via GLideN64.

**Comment by fzurita** [comment]
@retrobenny can you close this?

**Comment by retrobenny** [comment]
What about the part I mentioned about a tiny glitch at the door when Conker walks in?

I can confirm there is that one specific moment only in 4K multi-threaded but maybe I should check again to see if it changed since the most recent update to see if it persists.

**Comment by gonetz** [comment]
@retrobenny could you update the current status of that issue?

**Comment by retrobenny** [comment]
It seems to no longer have vertex explosions at the doorway on build 3.0.222 at least and runs okay at 2880x2160.

I refuse to have the newer updated versions on my Shield TV because of SAF/Scoped Storage making things nightmarish with file access and wasting storage space or aging the storage lifespan to keep extra copies of stuff normally or remake copies for files every time when in use to retain storage space.

Everyone needs to push against those Android 11 SAF/Scoped Storage "features"/"enhancements" and put a stop to them or apps will continue to be very tedious to use in the near future.
The only options would be to have app devs nice enough to keep off-store versions without it and for people to use Android Pie or older instead of 10 or 11.

Guess I should close the issue anyway since it appears to work fine now,even with FXAA enabled on top of that.
