### ISSUE TITLE
Font rasteriser doesn't perform gamma correction

### ISSUE THREAD

**Issue by Clownacy** [gonetz/GLideN64#2030]
Hi. I recently started using FreeType for a project of mine, and along the way I had an issue with ugly thin letters. It turns out this was caused by a lack of gamma correction. While using this plugin, I noticed the same problem (the font is Courier New):

![image](https://user-images.githubusercontent.com/7667009/55115583-c0d93b80-50dc-11e9-8f0c-5032a20984a0.png)

This is caused by a naive interpretation of FreeType's output: the glyph 'bitmaps' it produces define the "brightness" of each pixel, however, a light's brightness, and our _perception_ of its brightness, are two different things - much like sound, apparently we perceive light logarithmically. For more info, I recommend reading [this](https://blog.johnnovak.net/2016/09/21/what-every-coder-should-know-about-gamma/).

The FreeType group itself also mentions the need for gamma correction [here](https://www.freetype.org/freetype2/docs/text-rendering-general.html). They recommend a gamma of 1.8. This produces much more pleasant text:

![image](https://user-images.githubusercontent.com/7667009/55116032-eb77c400-50dd-11e9-94ec-a1125bb7c0eb.png)

Granted, it doesn't look 100% correct in this screenshot either, though I think this might have to do with the letters being drawn 'between pixels' by OpenGL. I can't say for sure though. Still, it's an improvement.

I would have made a pull request to address this, but my solution is awful: I merely tacked this bit of code onto TextDrawer.cpp's Atlas constructor:

```
if (g->bitmap.buffer != nullptr) {
	updateParams.x = ox;
	updateParams.y = oy;
	updateParams.width = g->bitmap.width;
	updateParams.height = g->bitmap.rows;
	// New code start
	for (unsigned int y = 0; y < g->bitmap.rows; ++y)
		for (unsigned int x = 0; x < g->bitmap.width; ++x)
			g->bitmap.buffer[g->bitmap.pitch * y + x] = pow(g->bitmap.buffer[g->bitmap.pitch * y + x] / 255.0, 1.0 / 1.8) * 255.0;
	// New code end
	updateParams.data = g->bitmap.buffer;
	gfxContext.update2DTexture(updateParams);
}
```

**Comment by gonetz** [comment]
@Clownacy Thanks for the info! Yes, it looks better with this correction.
