### ISSUE TITLE
Killer Instinct Gold (Freeze First Fight)

### ISSUE THREAD

**Issue by schubertguilherme** [gonetz/GLideN64#2031]
Before starting the first fight the game freezes during the (Round 1) and then becomes normal. You can adjust this ... last WIP of Gliden 64.

![39893-Killer_Instinct_Gold_(USA)-2](https://user-images.githubusercontent.com/36903073/55323609-e86e3200-5455-11e9-96c6-37fc72ef85a7.jpg)

It happens after the narrator says "Ready" and a quick freeze happens.

**Comment by Yui12** [comment]
4.0 doesn't seem to have this problem on my end.

**Comment by GamingTVYT** [comment]
Uses the latest version of Project 64 and the updated Gliden64 plugin. It did not freeze here.

**Comment by gonetz** [comment]
No reply from schubertguilherme. Hopefully, the problem is resolved.
