### ISSUE TITLE
Star Wars: Rogue Squadron doesn't work on Intel HD (Bay Trail)

### ISSUE THREAD

**Issue by arnoldsecret** [gonetz/GLideN64#2034]
Only a black screen is displayed. Tested on Mupen64Plus and Mupen64Plus-Next, on RetroArch.

Intel HD (Bay Trail)
Windows 8.1 x64

**Comment by gonetz** [comment]
I have only Intel HD Graphics 630 with Win 10 on hands.
I tested Star Wars: Rogue Squadron with it, no issues.

Btw, do you have audio working? Just to be sure that the game is actually runs.

**Comment by arnoldsecret** [comment]
no audio at all.

**Comment by gonetz** [comment]
Have you tried to run this game with angrylion's software lle plugin?
If it does not work too, it is emulator's issue.

**Comment by arnoldsecret** [comment]
LLE does work, seems it's an HLE issue.

**Comment by gonetz** [comment]
Try to set R4300Emulator option to 1.
It is in Core settings.

**Comment by loganmc10** [comment]
They are testing the retroarch port, not the official release for Mupen64Plus or PJ64, it's likely an issue with the port

**Comment by gonetz** [comment]
@arnoldsecret Please test Rogue Squadron with official release for Mupen64Plus.
