### ISSUE TITLE
Kirby 64 Texture Enhancements problem

### ISSUE THREAD

**Issue by KSSMarx** [gonetz/GLideN64#2043]
When i try to set any Enhancements in GlideN64 Settings - Texture Enhancement - N64 Textures some textures are appearing not how they should:
For example, this is how Waddle Dee and Dark Matter look in the cutscene before first level's boss while using 6xBRZ:
![K64](https://user-images.githubusercontent.com/49493832/55901315-50114380-5bf3-11e9-909a-95ce3fa448db.png)
It definitely isn't supposed to look like that, because every other footage and emulation of the game (including the official ones) don't have that and it just looks wrong.

**Comment by DonelBueno** [comment]
I thing it's the same issue I described here: https://github.com/gonetz/GLideN64/issues/1857.

As a workaround, you can disable "Save enhanced texture cache to hard disk".

**Comment by KSSMarx** [comment]
> Maybe it's related to the issue I described here: #1857.
> 
> As a workaround, you can disable "Save enhanced texture cache to hard disk".

I've tried, but the same thing happens.
![k64-2](https://user-images.githubusercontent.com/49493832/55923846-91c0df00-5c31-11e9-8363-fe2efe94631f.png)

**Comment by gonetz** [comment]
@KSSMarx Please test it again with my latest build from #1885

**Comment by DonelBueno** [comment]
@gonetz I've tested with your latest build and it is fixed.

**Comment by gonetz** [comment]
Good, thanks. I need to fix issues with WDC and test this issues again before closing it.

**Comment by oddMLan** [comment]
Can this be closed?
