### ISSUE TITLE
Project 64 1.6 - Super Mario 64 video jittering intensely

### ISSUE THREAD

**Issue by JG-GIT** [gonetz/GLideN64#2047]
I'm not exactly sure how this happens, but it does.
![what the hell](https://user-images.githubusercontent.com/39865752/57487900-f130ff80-726e-11e9-822a-7d12266de6fe.PNG)

**Comment by JG-GIT** [comment]
I have found out that this happens on EVERY GAME due to the frame buffer.
If I disable it, it makes a mess onscreen.

**Comment by gonetz** [comment]
@JG-GIT is it still actual? On which platform it happens?

**Comment by olivieryuyu** [comment]
can it be closed?
