### ISSUE TITLE
[Shader cache] if you bump MESA you'll end up with a blank screen

### ISSUE THREAD

**Issue by 5schatten** [gonetz/GLideN64#2049]
I recognized this before. If you bump MESA to a version which changed the way how shaders are handled they have to be rebuild afaik. For example Dolphin does this once I bump MESA.

Recently I updated MESA 19.1.0-rc1 to 19.1.0-rc2 & ended up with a blank black screen after I've launched mupen64plus with the GLideN64 graphics plugin. You even hear the sound output but the screen stays black.

Once you manually "clean" the shader cache in `~/.cache/mupen64plus/shaders` so basically delete them you can run the game again & it works fine.

So my question is it's possible to check the MESA or graphics driver version in common & rebuild the shader cache if the driver has been updated?

Plugin version: https://github.com/gonetz/GLideN64/releases/tag/Public_Release_4_0

**Comment by gonetz** [comment]
@5schatten Hi!
Sorry for late reply. Yes, it is possible to check graphics driver version and rebuild the shader cache if the driver has been updated. Moreover, it was implemented years ago, see src/Graphics/OpenGLContext/GLSL/glsl_ShaderStorage.cpp
When shader storage saves, it stores strings returned by glGetString(GL_RENDERER) and glGetString(GL_VERSION). When it loads, it compares these stings from storage with actual ones and rebuilds the storage if the strings do no match. May be these strings did not change between MESA 19.1.0-rc1 and 19.1.0-rc2?

**Comment by gonetz** [comment]
No reply from 5schatten. Hopefully, the problem is resolved.

**Comment by Air-max-fr** [comment]
Hello @gonetz ,
hello,
I apologize for my casual approach to an already open (and abandoned) topic
I’m looking for someone who can help me solve a problem of shader on dolphin.
It is a bit a bottle to the sea that I send, perhaps I would be saved :)
I’m looking to create a shader that duplicates the image of the game, but back to back.
I made a table-cocktail arcade game for my kids, and I use a libretro shader for libretro consoles, but this one doesn’t work (yet .glsl) with dolphin, and screams errors :D !

If you (or anyone who strays here) can help me, I will not forget to have eternal gratitude :)

Thank you in advance ;)

**Comment by gonetz** [comment]
@Air-max-fr 
Sorry, I can't help you with it. I know nothing about libretro shaders or dolphin shaders.

**Comment by Air-max-fr** [comment]
It doesn’t matter, it’s already very nice of you to answer...many don’t:/
God save you for better days
