### ISSUE TITLE
Clay Fighter Sculptor's Cut: no 3d at boot screen

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#205]
![clay](https://cloud.githubusercontent.com/assets/8987490/5516279/2c9d876a-8894-11e4-9a92-60b56d598c40.jpg)

legacy code

**Comment by gonetz** [comment]
A nominee in "create weird but working program code" contest.

Fixed.

**Comment by olivieryuyu** [comment]
fixed
