### ISSUE TITLE
Which feature needs which OpenGL version

### ISSUE THREAD

**Issue by StenApp** [gonetz/GLideN64#2050]
Hi there,

my MacBook Pro 2017 (Intel HD Graphics 630/Radeon Pro 560 4 GB VRAM)
supports only OpenGL 4.1 under macOS, 4.6 (probably) under Windows/Linux.

Can you tell me which feature needs which OpenGL version?
Let's say frame buffer emulation, or other things.

**Comment by oddMLan** [comment]
should add a "question" tag to this.

**Comment by gonetz** [comment]
IIRC, OpenGL 4.1 is enough for all GLideN64 features but N64 depth compare, which requires 4.3
