### ISSUE TITLE
#WIP 4 and Vigilante 8 2nd Offense

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#2053]
WIP 4 breaks this game.

Used to work really well on WIP 3

**Comment by theboy181** [comment]
You can see all sorts of GFX issues in  game. The terrain is the largest example.  I also noticed that menus are broken, and are extremely resource heavy,.

**Comment by gonetz** [comment]
Hello,

Do you mean that Vigilante 8 2nd Offense is broken after PR4?

**Comment by theboy181** [comment]
I checked wip4 and the last wip3. Not too sure when it broke.

**Comment by DonelBueno** [comment]
I just tested here and WIP 4 works perfectly, no performance or graphics regressions.

**Comment by theboy181** [comment]
From the download  -

**Comment by gonetz** [comment]
@theboy181 I see no new issues with Vigilante 8 2nd Offense running on latest WIP build.
Please check it again.

**Comment by GamingTVYT** [comment]
Hello guys, any news about the graphics correction of the game? Multiplayer mode? screen menu and transitions fixed?

**Comment by gonetz** [comment]
No news about the graphics correction of the game. No new problems with WIP builds either. Closed.
