### ISSUE TITLE
this is opengl 3.x only? trying to use it on rpi3 

### ISSUE THREAD

**Issue by Askmewho** [gonetz/GLideN64#2060]
thats all.. I achieved to compile it but it fails on executing

Core: SDL_SetVideoMode failed: Could not create GL context: GLXBadFBConfig

**Comment by gonetz** [comment]
I don't have rpi to test. The plugin worked on that platform in (near ?) past.
You will help me greatly if you will find when rpi support was broken.

**Comment by Askmewho** [comment]
@gonetz Ok, but I am trying another approach. I disable bcmhost and enable mesa (with bcmhost it happened the same thing anyway) . Ive compiled the latest version of mupen64plus and I have SDL 2.0.9. Anyway, the plugin doesnt have any sdl deps from what I can read right now.  it find some conflict with mupen64plus sdl? dont know.. I made a debug plugin... how to debug??

I am getting a lot more performance on mesa, this is with rice:
https://www.youtube.com/watch?v=f8Yq_5TTZGM&t=576s

but as you see, its a bit glitchy, so I need to test this gliden64 plugin :)

**Comment by Askmewho** [comment]
its the fbdev... 99% sure. i am on it!!!

**Comment by gonetz** [comment]
The plugin doesn't have any sdl deps. The emulator creates GL context and provides it to the plugin.

> I made a debug plugin... how to debug?

Debug build has GL_DEBUG defined. With that define any error in GL command logged into gliden64.log.
Something like 
`2019/05/22,19:26:53.360,opengl_command.cpp:22,ERROR, " OpenGL error: 0x502, on function: glBindBuffer"`. 
I don't remember location of gliden64.log on Linux, but I'm sure you will find it.

**Comment by Askmewho** [comment]
I believe than its than the rpi has fbdev. thats why it cant create context, i have compiled it without fbdev (yes, i dont know very well what it is but its related with the framebuffers) . it happened the same on ppsspp, but they have the rule to enable it. and now it works perfect.

**Comment by Askmewho** [comment]
pandora should have the same problem... but I cant find any rule from -DPANDORA refer to that... and I wont use the armv6 config of pandora.

**Comment by Askmewho** [comment]
so... if the emulator creates the GL context I dont understand why other plugins can create gl context and not this plugin...

**Comment by gonetz** [comment]
Did you find gliden64.log? What is in it?

**Comment by gizmo98** [comment]
@Askmewho I'm quite sure latest source is running with retropie and recalbox. Otherwise users had already complaint. 

We use custom SDL2 builds with dispmanx support to run mupen64plus without X. If you use the open source driver kms support should be enabled to achieve the same thing. I have never run mupen64plus with X on a pi. Maybe you need a custom build as well. 
https://github.com/RetroPie/SDL-mirror/commits/rpi-2.0.9

If SetVideoMode fails you could compare Rice and GLideN64 attribute values:
https://github.com/mupen64plus/mupen64plus-video-rice/blob/master/src/OGLGraphicsContext.cpp#L49
https://github.com/gonetz/GLideN64/blob/master/src/Graphics/OpenGLContext/mupen64plus/mupen64plus_DisplayWindow.cpp#L51

**Comment by Askmewho** [comment]
Thanks, I am a bit loose. what you mean its than I should recompile sdl2 with dispmanx support and recompile mupen64plus with that sdl ? that would fix SetVideoMode fails or its related with something else (like the attribute values you appoint here). I am unable to run this plugin on X like with the other plugins?

**Comment by Askmewho** [comment]
ok!! so I have news @gizmo98 

Ive changed the following values:
	CoreVideo_GL_SetAttribute(M64P_GL_CONTEXT_MAJOR_VERSION, 3);
	CoreVideo_GL_SetAttribute(M64P_GL_CONTEXT_MINOR_VERSION, 3);

to

	CoreVideo_GL_SetAttribute(M64P_GL_CONTEXT_MAJOR_VERSION, 2);
	CoreVideo_GL_SetAttribute(M64P_GL_CONTEXT_MINOR_VERSION, 1);

and it runs but doesnt show nothing, just sound.
so, seems to me than its 3.x on full opengl setup (mesa here)

**Comment by gizmo98** [comment]
Sounds like you are using OpenGL2.1 instead of OpenGLES2. GLideN64 needs GLES2 or OGL3.3. If i remember correctly SDL2 must be build with GLES support enabled and OGL support disabled. Which distribution are you using?

**Comment by Askmewho** [comment]
Yes, I wanted to use the full profile on porpoise... Mmm it will not run good at all on gles, even on mesa gles libs l. I will give it a shot anyway. Thanks

**Comment by Askmewho** [comment]
there is any possibility than opengl 2.1 been supported on the future?? I will recompile SDL without it and do preload just to check than it runs on gles2

**Comment by Askmewho** [comment]
@gizmo98 It want run with my libGLESV2.so or libEGL.so libs (note than these are from mesa, not broadcom) , no change on both (with or without EGL ON) with SDL with or without OpenGL. Dont know what more I cant try, seems to me than it keeps considering than I am running on opengl 2.1 bu I am not, could you add a definition to use mesa libs instead of broadcom libs?? I Will try raspberrt pi config (Mesa=off) but replacing the libs on the glcontext stuff.

**Comment by Askmewho** [comment]
Doesnt matter... it wont run on X at all... so, the best attempt was with GL but as you tell me it wont support GL 2.1 . I know than you have a lot of work (and are doing a great job being the best developed plugin for mupen so far)  but I dont know why you support GLES 2 and not GL 2.1 , that doesnt have sense to me. Hope than you all could do something about it. many thanks for your time sir.

**Comment by Askmewho** [comment]
its a bit sad because mesa actually did a great work here with rice with a very difficult game to emulate

https://www.youtube.com/watch?v=f8Yq_5TTZGM&t=576s

**Comment by gonetz** [comment]
> why you support GLES 2 and not GL 2.1

Minimal GL version, which is required for basic plugin's functionality is 3.3. Older versions just lack of necessary functionality.
" OpenGL ES 2.0 is roughly based on OpenGL 2.0, but it eliminates most of the fixed-function rendering pipeline in favor of a programmable one in a move similar to the transition from OpenGL 3.0 to 3.1" -Wikipedia.
GL ES 2.0 has most of features required for basic functionality. Shading language differs though, so many shaders have special GL ES 2.0 version. This makes it hard to continue GL ES 2.0 support. fzurita suggests to drop GL ES 2.0 support at all.  So, there is no possibility that opengl 2.1 will be supported in the future. Rather opposite, GL ES 2.0 support can be stopped.

**Comment by gizmo98** [comment]
> its a bit sad because mesa actually did a great work here with rice with a very difficult game to emulate
> 
> https://www.youtube.com/watch?v=f8Yq_5TTZGM&t=576s

Two years earlier it was running quite well with GLideN64 GLES2 but had some glitches and stability issues. Could be my old repo can still be used to build retropie with open source support. https://github.com/RetroPie/RetroPie-Setup/issues/2093

There are also some ugly fixes to prevent broadcom driver blob detection:
https://github.com/RetroPie/RetroPie-Setup/compare/master...gizmo98:rpi-kms?expand=1#diff-fe35047c4f73377c42592c2271157752R65

If you need X11 (with screen tearing) a sdl2 version with X11 and GLES support should be sufficient.

**Comment by loganmc10** [comment]
The Raspberry Pi 4 was just announced and it supports OpenGL ES 3. It's probably time to just drop GLES 2 support and tell people that public release 4 was the last one to support it.

**Comment by Askmewho** [comment]
Yeah, but has far as i knowe the pi 4 will run mesa drivers by default, and as i know for now the are full opengl 3.0, not 3.3

**Comment by Askmewho** [comment]
As far as i know (triple ! Hahha), opengl its much better than gles, and ive seen it going from mesa gles to full opengl from mesa.  Anyway, gles3 should run okey.
