### ISSUE TITLE
Release 4.0 does not contain bin folder

### ISSUE THREAD

**Issue by MickL** [gonetz/GLideN64#2063]
From the description:

> Content:
> src - source files
> bin - binary builds for Windows:

But there is no bin folder like on 3.0 release. Could you please do a 4.0.1 release with the missing dll's?

**Comment by gonetz** [comment]
I just downloaded GLideN64_Public_Release_4.0.7z from GitHub. 
Its content has the following structure:
* GLideN64_Public_Release_4.0
   * bin
     * Mupen64Plus
     * Mupen64Plus_x64
     * Zilmar-specs
  * sources

all dll's are in the corresponding sub-folders.
