### ISSUE TITLE
artifacts with depth compare on

### ISSUE THREAD

**Issue by budtz** [gonetz/GLideN64#2066]
I now get artifacts with depth compare on. In every game. small glitches like noise.

Could it be a drive rissue?
i have an nvidia card

**Comment by gonetz** [comment]
Do you mean "N64 depth compare"?

**Comment by budtz** [comment]
Yes

**Comment by gonetz** [comment]
Please give me a screen shot and mark the problem on it.

**Comment by budtz** [comment]
![deptpartifact](https://user-images.githubusercontent.com/17853217/60398107-cec3b000-9b54-11e9-8b29-c3b423796c06.png)

**Comment by budtz** [comment]
Issue is in all games. its evident on the hands and nose here. goes away when I disable N64 depth compare option

**Comment by gonetz** [comment]
I'm not sure is it a driver issue? Hardly, imo.
I have that issue too, in many games. It can be problem with synchronization of reads/writes to image texture buffer.  The synchronization relies on some extensions. This is a hard matter for investigation, I can't promise results soon.

**Comment by budtz** [comment]
Ok thx. Ive just never seen/noticed it untill today and I havnt changed anything or used the emulator in some time.

**Comment by purpasmart96** [comment]
I don't seem to get artifact in question on 4.0 release, using a gtx 980ti

**Comment by loganmc10** [comment]
N64 depth compare now relies on some pretty wacky OpenGL extensions. I've seen some phones have the same issue. It's likely that your graphics card drivers don't properly inplemeothe extensions. If you haven't, I would try updating your graphics drivers to the latest available version

**Comment by loganmc10** [comment]
To give you an example: I had very similar issues on my phone that has an Adreno GPU, when my phone was updated to Android 9, the issue went away. I assume the Android update was also bundled with a new GFX driver

**Comment by budtz** [comment]
Thats a good bet. That would also explain why I havnt seen it before. Ill try later.

**Comment by pcca-matrix** [comment]
Same artifact with Geforce RTX 2080 SUPER  but not With AMD RX580 and GTX950  tried some differents driver wth the RTX but no way , artifacts is in all games that use depth compare ON

**Comment by gonetz** [comment]
I re-implemented "Compatible" N64 depth compare mode. It works without issues on my card:
![Banjo](https://user-images.githubusercontent.com/8983092/76142810-aa38b400-60a3-11ea-8a8a-1afdf88d9d02.jpg)
