### ISSUE TITLE
Aero Fighters Assault - Startup Error

### ISSUE THREAD

**Issue by PixelCrusader** [gonetz/GLideN64#2069]
When booting the game, the expected behavior is for the company logos and licensing information to fade from black, before transitioning into white and then into the planes flying.

![AeroFighters Assault (USA)-190711-021651](https://user-images.githubusercontent.com/40935002/61031281-323bb200-a38d-11e9-8d47-18b19fbd9e2a.png)

Currently, booting the game almost completely cuts the company logos and licensing, prematurely changing into the planes flying.

This behavior was observed on Mupen64Plus-gui using the GLideN64 Public Release 4.0 as well as RetroArch's latest version of Mupen64Plus-Next, which uses a port of GLideN. Real hardware was used to confirm the discrepancy. 

The example picture above was taken from RetroArch running an older version of their mupen64plus core (af7a4bf). This could mean that this is a regression. 

Video of how the game should look:

https://www.youtube.com/watch?v=0ceyDL-bSR0&t=09s

https://www.youtube.com/watch?v=MhYAA8niTQM

https://www.youtube.com/watch?v=2C-ulZRmTT8

**Comment by Aquatakat** [comment]
This seems to be working fine on zilmar-spec emulators.

**Comment by gonetz** [comment]
Yes, it is mupen64plus core issue, which happens with any graphics plugin. Project64 works correct, as Aquatakat noticed.

**Comment by Tasosgemah** [comment]
The older mupen64 core doesn't have this issue, don't know if that's useful information.
