### ISSUE TITLE
The stretch option does not seem to work on PAL games.

### ISSUE THREAD

**Issue by amergin6699** [gonetz/GLideN64#2072]
whatever PAL game I launch with stretched checked , it does not work as expected.

I understand that some games can't get rid of black border ,and i already read the other issue on the resoltion problem on pal games.
But with gliden64 it is for almost all pal games,
If i use project64 video plugin with strecthing checked , almost all Pal games are stretched correctly.

it seems that it stretches while keeping the aspect ratio , "stretch" or "try to adjust game to fit" gives exactly the same result.

stretch should stretch even while deforming and "try to adjust game to fit" should keep the aspect ratio when strechting or did I misunderstand how stretch works in gliden64 ?

when you use the emulator with bezels, it's really very disturbing, the screen is sometimes completely off center.

Is there a way to fix , or any other settings? except overscan which requires a manual setting for each games ...

<b>GLIDEN64 - try to adjust game to fit</b>
<a href="https://ibb.co/Sd7GG1P"><img src="https://i.ibb.co/dLJxx3r/adjust.jpg" alt="adjust" border="0"></a>

<b>GLIDEN64 - Stretch</b>
<a href="https://ibb.co/DwyxxbT"><img src="https://i.ibb.co/L9WLLPH/stretch.jpg" alt="stretch" border="0"></a>

<b>Project64 Video Plugin Stretch</b>
<a href="https://ibb.co/Kq1JdkN"><img src="https://i.ibb.co/LtG3mWQ/pj64.jpg" alt="pj64" border="0"></a>

**Comment by pcca-matrix** [comment]
I have the same trouble with all the european release (PAL) but apparently it is not possible with this plugin to have real stretching for some obscure reason,
Dont't know if it's project64 related or if the probleme happen on mupen too , never tried

Use Project 64 original video plugin instead if you want to have a nice rendering on rocketlauncher with  bezel , that's what I do ...

**Comment by amergin6699** [comment]
@pcca-matrix  pj64 plugin is'nt old glide64 plugin ? same author as gliden64

also why when framebuffer is enabled screen area  is cropped by 1 line or 2  ? that does not happen with glide64 , that's not really accurate.

**Comment by CallistoNTG** [comment]
This is accurate behavior. On real hardware, the games will output with a border. GLideN64's relatively accurate Video Interface (VI) emulation allows it to accurately render the borders. Glide64, aka Project 64 Video, does not handle the VI properly, or really at all.

**Comment by amergin6699** [comment]
@CallistoNTG I do not speak about black boder for accurency.

look at this picture , when FB is on, gliden64 crop 1 or 2 lines from real n64 screen that's what i'm talking about.
[<a href="https://imgbb.com/"><img src="https://i.ibb.co/Tkqj8DB/Diff.jpg" alt="Diff" border="0"></a>](url)
it's also for that i do not understand why it is not possible to remove theses black edge while the screen is cropped by the plugin, 
at this stade we know the exact coordinates and size of the screen area, just stretch it (zoomù) to the size of the windows resolution (windowed mode) or fullscreen resolution ! maybe with post filter.

I'm not an expert, I'm just trying to understand why it's so diffcult ? we do not talk about keeping an aspect ratio, just a simple stretch.

It is obvious that it cannot remove black borders on some pal games (waverace, bettle adv, aerofighter, etc..)  but I do not speak for these games.

**Comment by CallistoNTG** [comment]
The cropping is accurate behavior. You can read the details here. https://github.com/gonetz/GLideN64/issues/1981 The N64 hardware crops a few pixels from the left and right of the framebuffer. It is necessary to mimic this behavior because a number of N64 games display garbage along the sides of the screen because a real N64 will never show those areas. PAL games have  borders of their own that are added in by the game.

**Comment by amergin6699** [comment]
@CallistoNTG
Thanks for the infos  , i dont remember this behavior on real hardware. i would check on my real N64 later.

Im starting to put crop setting for every pal games , i'll put the ini here when i finish , if it can help some

**Comment by pcca-matrix** [comment]
i'm really  interessed about your ini when finished

**Comment by amergin6699** [comment]
Here is the ini with overscan for all PAL games (tested with PJ64 1920x1080 internal resolution set to same as output).

 [ini](http://www.mediafire.com/file/9vvk8183licvs14/GLideN64.custom.ini/file)

Only 1 game miss because of a plugin bug , unable to write ini setting for the game 
WcW-nWo Revenge

here is what's is written inside .ini

[WCW%20]
%20NWO%20%20REVENGE\frameBufferEmulation\overscanPalLeft=1
%20NWO%20%20REVENGE\frameBufferEmulation\overscanPalRight=1
%20NWO%20%20REVENGE\frameBufferEmulation\overscanPalTop=-1
%20NWO%20%20REVENGE\frameBufferEmulation\overscanPalBottom=1

Enjoy

**Comment by gonetz** [comment]
@amergin6699 I suppose, this question is clarified and can be closed now.

Related info:

- http://gliden64.blogspot.com/2018/05/overscan.html
- #1981

**Comment by pcca-matrix** [comment]
@amergin6699 
Nice work  , perfect with Project64 and rocketlauncher bezels mode !!

**Comment by amergin6699** [comment]
@gonetz 
yes it is clarified you can close the issue.

@pcca-matrix 
Thanks

**Comment by ytrezq** [comment]
@gonetz I know it unrelated, but how can the official virtual console manages to have all N64 games running at 640*480 without cropping?
I doubt that getting the custom roms extracted from .rodata and running would solve that problem.
