### ISSUE TITLE
GlideN64 crashes on game start w/ CRT Emudriver (r7 240)

### ISSUE THREAD

**Issue by thaKnza** [gonetz/GLideN64#2076]
Been using GlideN64 for a long time. Recently installed an r7 240 into my system alongside my GTX 1080. I have special drivers installed for the r7 called CRT Emudriver that sends a 15khz analog signal out of the VGA port to put a picture onto a Toshiba SD CRT TV so that I can run emulated N64 games at their original native resolutions on the target display technology of the time.

If I have the TV set as my primary display and try to run a game in fullscreen, the emulator crashes. This happens on Mupen64Plus or Project64. This does not happen with any other graphics plugin, only GlideN64 seems to have this problem.

**Comment by gonetz** [comment]
Can you check what is in Plugin/GFX/gliden64.log ?

**Comment by thaKnza** [comment]
It's funny, I just tried your latest dev build last night and it works fine
now. If you are curious or want to avoid regression I can re-install 4.0
and get the log for you.
