### ISSUE TITLE
Majora's Mask - Shadows on invisible platforms

### ISSUE THREAD

**Issue by Jj0YzL5nvJ** [gonetz/GLideN64#2078]
angrylion's RDP Plus r7-142:
https://i.imgur.com/nGxHfel.png

GLideN64 4.0:
https://i.imgur.com/qlU5Zwc.png

mupen64plus save state: https://0x0.st/zVTI.zip

**Comment by gonetz** [comment]
Enable N64 depth compare to fix that issue.

**Comment by gonetz** [comment]
@Jj0YzL5nvJ
Does "N64 depth compare" option fix the problem for you?
If yes, please close this issue.

**Comment by Jj0YzL5nvJ** [comment]
Currently, said fracture isn't supported on AMD Mesa drivers.
