### ISSUE TITLE
Ready 2 Rumble Boxing: wrong 2d depth in menu/game

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#208]
![nope](https://cloud.githubusercontent.com/assets/8987490/5517909/57433014-8907-11e4-9e35-25f6ae01a871.jpg)
![nope2](https://cloud.githubusercontent.com/assets/8987490/5517910/598e0452-8907-11e4-8059-f535979ca2aa.jpg)

**Comment by gonetz** [comment]
Please check with latest build.

**Comment by olivieryuyu** [comment]
fixed
