### ISSUE TITLE
FXAA Corruption

### ISSUE THREAD

**Issue by cobhc2019** [gonetz/GLideN64#2085]
Hello,

As mentioned by myself in the below issue, there is corruption caused by the FXAA built into the renderer in regards to 2D elements. Which is a shame as it's quite an authentic implementation.

https://github.com/libretro/mupen64plus-libretro-nx/issues/83

Thank you.

**Comment by gonetz** [comment]
FXAA is post-processing filter. It filters the whole image. It can't be disabled for 2D elements.
In fact, it has no handles to tweak. It seems that 320x240 resolution is too small for that algorithm to produce good result. I don't see how that problem can be resolved.
