### ISSUE TITLE
GlideN64 on gles 3.0 on rpi4

### ISSUE THREAD

**Issue by Askmewho** [gonetz/GLideN64#2087]
Hi, its possible to run this plugin on gles 3.0 under x11?  because ive tried with egl on and with SDL2 (with full gl profile and it gives a segfault as expected) but with a non full profile gl SDL2 it claims than it needs glx profile.

**Comment by Askmewho** [comment]
@gonetz @gizmo98 we chat this topic before I believe, Ive compiled every single mupen module + sdl2 to not use opengl, but rather gles, and Ive get a segfault (which I will debug if you need so, but its a bit difficult because I use a python frontend) . At least it doesn't say than it cant create gl context.

**Comment by m4xw** [comment]
@Askmewho Fixed in https://github.com/libretro/mupen64plus-libretro-nx/commit/3dae33e95cb4d860cdc45dcb6227b5c8f5f69197
You can backport it.

**Comment by Askmewho** [comment]
fixed with that! push it!
