### ISSUE TITLE
Feature request: interger or nearest neighbor scaling for non output resolutions

### ISSUE THREAD

**Issue by AriaHiro64** [gonetz/GLideN64#2088]
Any resolution selected that isn't the windows resolution gets blury at least on my system and the only plugin that does this is angrylion/plus. it would be nice to have a hardware accelerated solution to this
GlideN64
![image](https://user-images.githubusercontent.com/45049787/65216695-cefe8800-da7f-11e9-838a-e7b479347b3c.png)

AngryLionPlus
![image](https://user-images.githubusercontent.com/45049787/65216756-ffdebd00-da7f-11e9-91d3-967d63163ada.png)

**Comment by oddMLan** [comment]
Maybe as an addendum to ticket #2082 but yeah it would be cool to draw the output surface with nearest neighbor and rounded to the nearest integer so all pixels are proportional. Gonetz is overworked with other stuff atm so it might not be in soon

**Comment by DeathWrench** [comment]
According to this thread, setting was accessible through .ini at one point.
https://github.com/gonetz/GLideN64/issues/2082

**Comment by gizmo98** [comment]
Angrylion looks like native resolution upscaled to windows resolution with nearest neighbor. Maybe it should be possible to select bilinear or nearest neighbor upscaling if nativresfactor != 0.

**Comment by Jj0YzL5nvJ** [comment]
https://github.com/gonetz/GLideN64/issues/1981#issuecomment-455050395
https://github.com/gonetz/GLideN64/issues/1574#issuecomment-453771887

**Comment by AriaHiro64** [comment]
a work around ive found is reshade with this shaderhttps://www.dropbox.com/s/jo9nsw5wb19nghy/VirtualResolution.fx?dl=0

**Comment by dankcushions** [comment]
agree with this one. the current upscaling from low (eg 1x native resolution) to fullscreen (eg, 1080p), is quite ugly and usually not what you'd want. nearest neighbour would be a great option!

**Comment by gonetz** [comment]
I made an experimental branch for this task.
Here I use hybrid texture filter implemented for task #2116 in Video Interface to draw frame buffer image to screen. Branch name 2088_hybrid_filter. I need your feedback. Where to look? I made comparison screen shots for Paper Mario subscreen. The game runs in native resolution, screen resolution is 1080p.
* Current master, bilinear 
![GLideN64_PAPER_MARIO_000](https://user-images.githubusercontent.com/8983092/69474915-75a53300-0df9-11ea-92fe-a6d131c2101b.jpg)
* Hacked to force nearest-neighbor
![GLideN64_PAPER_MARIO_001](https://user-images.githubusercontent.com/8983092/69474949-c1f07300-0df9-11ea-9be4-8ca838ea585b.jpg)
* Branch, hybrid filter 
![GLideN64_PAPER_MARIO_002](https://user-images.githubusercontent.com/8983092/69474954-d5034300-0df9-11ea-9cea-256f4e79ad73.jpg)

Lets look closely to "Boots": 
![Boots](https://user-images.githubusercontent.com/8983092/69474982-02e88780-0dfa-11ea-89d4-b0b3977be1c1.png)

It illustrates all the problems with image scaling described in article
https://colececil.io/blog/2017/scaling-pixel-art-without-destroying-it/

Bilinear is blurry, but no image distortion. Nearest-neighbor is distorted (look at o in Boots). Hybrid is not that sharp as Nearest-neighbor but not as distorted as well.

**Comment by gonetz** [comment]
Test build:
https://drive.google.com/file/d/1m4Wx6mpXdtT4Z83jxzMDqX5rWYDbt8mO/view?usp=sharing

**Comment by oddMLan** [comment]
![pie](https://user-images.githubusercontent.com/7278372/69475255-21159f80-0d88-11ea-9d71-150376afa529.gif)

Just from your example I noticed
Nearest vs Hybrid. Hybrid fixes the uneven pixels in letter P from "Pieces"

**Comment by oddMLan** [comment]
Maybe neareast option should be kept for low end devices (read: gles2), although I doubt this filter would be much of a slowdown? As it currently stands, the codepath for gles2 doesn't even use this filter.  The reference implementation of the hybrid filter says

`
#if __VERSION__ < 130
/* For this verison to work, you need to extract the texture dimensions:
 *
 *     GLint width, height;
 *     glGetTexLevelParameteriv(0, 0, GL_TEXTURE_WIDTH, &width);
 *     glGetTexLevelParameteriv(0, 0, GL_TEXTURE_HEIGHT, &height);
 *
 * then  tell the shader:
 *
 *     glUniform2iv(glGetUniformLocation(shader_program, "texture_size"),
 *                  width, height);
 */
uniform ivec2 texture_size;

ivec2 get_texture_size(sampler2D tex)
{
#if __VERSION__ < 130
    return texture_size;
#else
    return textureSize(tex, 0);
#endif
}`

so making it work for gles2 is just a matter of making this change. no?

**Comment by gonetz** [comment]
> Maybe neareast option should be kept for low end devices (read: gles2)

I set nearest filter instead of linear for frame buffer textures. Since hybrid is disabled for GLES2, it will use plain nearest atm.

> so making it work for gles2 is just a matter of making this change. no?

Yes.

**Comment by gonetz** [comment]
Done in 488d52d
@AriaHiro64 please test the latest WIP build from AppVeyor. If it is what you need, please close this issue.

**Comment by AriaHiro64** [comment]
![image](https://user-images.githubusercontent.com/45049787/69933923-69c30c00-149e-11ea-8f60-4ed025894be2.png)
yep this issue can be closed

**Comment by auwsmit** [comment]
Suggestion/Request: Can this please be an option rather than forced one way or the other? I really prefer bilinear filtering on the entire screen when I'm playing most N64 games at native or 2x resolution. (Unless I'm missing something and this is already an option somewhere that I haven't noticed)

Sure, the hybrid filter is nice and clean and has correct proportions, but it still looks very sharp and pixelated. I don't really want that unless the game is made of uniform pixel art, like Dr Mario. Many N64 games were intended to have their pixels blurred and blended by CRT screens of yore, and I find that bilinear blending approximates this effect pretty well.
