### ISSUE TITLE
Zelda 64 Skybox duplicates

### ISSUE THREAD

**Issue by GhostlyDark** [gonetz/GLideN64#2094]
Let's sum up the information gathered in #1885:

Both Ocarina of Time and Majora's Mask suffer from this since the beginning of 2019. The last GLideN64 build that did not have this issue is the one from 2018-12-18.

**ProtomanX on the issue in Ocarina of Time:**
> i tested to see if OOT was going the same thing, both games have the same issue both on project 64 and mupen plus with the current wip 4 build. heres video proof of skybox texture issues in OOT just from the intro alone. https://mega.nz/#!cksFiALK!tUcYsIBnqoF_B6PSCDKJHfZXXia0s13pP1O5sL4uXek

**Nerrel on the issue in Majora's Mask:**
> The skybox problem in Majora's Mask is that the custom sky textures only load on certain hours of the day. At 6AM they don't load and if I turn on texture dumping I get an identical set of sky textures with different filenames:
> ![image of 6](https://camo.githubusercontent.com/467db79a005b200d122937ba3612f0e55a3a6476/68747470733a2f2f6c6976652e737461746963666c69636b722e636f6d2f36353533352f34383830343136303439375f383532396637623436315f7a2e6a7067)
> 
> Then at 7AM the custom textures do load, and at 8AM they fail again. The custom textures don't seem to load again after that until 12PM. Basically, the plugin keeps switching between two skyboxes throughout the day when the game should only be using one.
> (custom textures loaded at 7) ![image of 7](https://camo.githubusercontent.com/e7311fc1d684120f8065d36590feedc06c11bb97/68747470733a2f2f6c6976652e737461746963666c69636b722e636f6d2f36353533352f34383830343136303435325f646333666432646138645f7a2e6a7067)
> (back to default textures again at 8) ![image of 8](https://camo.githubusercontent.com/46d4d28e38caa91ffd4af061800c7149cf94b19f/68747470733a2f2f6c6976652e737461746963666c69636b722e636f6d2f36353533352f34383830333636373037385f653336653661383534665f7a2e6a7067)
> 
> It's obviously not the correct behavior since as far as I know the game only has two skybox textures, one for day and one for night. I think the sky textures look like this on the actual ROM, and GlideN64 dumps them in 48 pieces:
> ![image of old sky](https://camo.githubusercontent.com/797378a3b468eb4febab60cd841fbc3e8184292a/68747470733a2f2f6c6976652e737461746963666c69636b722e636f6d2f36353533352f34383830333736393136335f303865363132646263315f6f2e706e67)

**Me having issues renaming existing HD assets in order to retexture the duplicate skybox:**
> I think the sky combinations are covered by existing texture packs. It seems both Zelda games switch to a duplicate of each of the combinations, which can be dumped and retextured. So for every skybox combination there is for GLideN64 (2018-12-18) there are two identical skyboxes for GLideN64 (2019-XX-YY).
> 
> Assuming the duplicate skyboxes share the exact same textures aside from having different hashes, it should be possible to rename existing HD assets in order to retexture the second skybox. I tried exactly that and ran into the issue that the second skybox is aligned wrong after retexturing.
> 
> ![zelda_majora's_mask-003](https://user-images.githubusercontent.com/31742919/65817900-d99de780-e20c-11e9-939e-862db4a1201b.png)
> 
> **Skybox assets:**
> https://mega.nz/#!VrRW3YqJ!ii5QA3k7K5Ekz3GBNPVVlZWzMNfPX5cgMws-eH03Atk
> 
> MM Skybox 1: Dumped with GLideN64 (2018-12-18)
> MM Skybox 2: Duplicate skybox of GLideN64 (2019-08)
> MM Skybox HD 1: Nerrel's retextured skybox
> MM Skybox HD 2: Nerrel's skybox renamed to match the duplicate skybox using the batch file
> 
> I used Luni's Toolbox to compare both vanilla skyboxes to create the batch file.

**Comment by gonetz** [comment]
May be I don't understand something, but problem's description is misleading:

>  for every skybox combination there is for GLideN64 (2018-12-18) there are two identical skyboxes for GLideN64 (2019-XX-YY).

From the description I concluded that you have to double number of skybox textures for new version of GLideN64. Actually, as I see, number of skybox textures for old and new version is the same. New version calculates texture CRC differently, so you have to rename old texture set. Am I right?

**Comment by gonetz** [comment]
Ok, I understand.
Older version can load textures from MM Skybox HD 1 at 6 am, new version can't.

**Comment by gonetz** [comment]
Hopefully fixed in cd9524c3
Test build:
https://drive.google.com/file/d/1dv8DzLyMJu5RcnhuTvei9nyt5inRUUZv/view?usp=sharing

**Comment by GhostlyDark** [comment]
Thank you gonetz! The skyboxes work again as expected with that change.
I'll reopen the issue in case something pops up.
