### ISSUE TITLE
Is the math correct?

### ISSUE THREAD

**Issue by standard-two-simplex** [gonetz/GLideN64#2095]
I have followed some of the progress here lately, and I am glad of the great progress you guys have made. 
However, I am concerned about the clamp, mirror and wrap shader math being incorrect.
```
"highp vec2 clampWrapMirror(in highp vec2 vTexCoord, in highp vec4 vClamp,		\n"
			"	in highp vec2 vWrap, in lowp vec2 vMirror, in highp vec2 vScale)			\n"
			"{																				\n"
			"  highp vec2 texCoord = clamp(vTexCoord, vClamp.xy, vClamp.zw);				\n"
			"  lowp vec2 one = vec2(1.0);													\n"
			"  lowp vec2 clamped = step(vClamp.zw, texCoord);								\n"
			"  lowp vec2 notClamped = one - clamped;										\n"
			"  lowp vec2 wrapped = step(vWrap , texCoord);									\n"
			"  lowp vec2 notWrapped = one - wrapped;										\n"
			"  texCoord = clamped * texCoord + notClamped * (wrapped*mod(texCoord, vWrap) + notWrapped*texCoord);			\n"
			"  highp vec2 intPart = floor(texCoord);										\n"
			"  highp vec2 fractPart = fract(texCoord);										\n"
			"  lowp vec2 needMirror = step(vec2(0.5), mod(intPart, vec2(2.0))) * vMirror;	\n"
			"  texCoord = clamped * texCoord + notClamped * fractPart;						\n"
			"  texCoord = (one - vMirror) * texCoord + vMirror * fractPart;					\n"
			"  texCoord = (one - texCoord) * needMirror + texCoord * (one - needMirror);	\n"
			"  texCoord *= vScale;															\n"
			"  return texCoord;																\n"
			"}																				\n"
```
Here are my concerns:
1.
``` 
"  lowp vec2 clamped = step(vClamp.zw, texCoord);								\n"
```
This only checks if it was clamped from above and uses the already clamped `texCoord` instead of the original `vTexCoord`. Not sure if the N64 can handle negative texture coordinates (I think it can, but I recall there were some restrictions), but the following should be safer.
```
" lowp vec2 clamped = step(vClamp.xy, vTexCoord) - step(vClamp.zw, vTexCoord); \n"
``` 
2.
```
"  lowp vec2 wrapped = step(vWrap , texCoord);			\n"
```
Same issue as before. However, considering that clamped coordinates also need wrapping or mirroring (in general), and that mirroring can be done with the help or wrapping, I wouldn't create this variable. 
3.
```
"  lowp vec2 needMirror = step(vec2(0.5), mod(intPart, vec2(2.0))) * vMirror;	\n"
```
I'm not sure I understand this part completely. When mirroring is needed `vWrap` contains double the value of the place to wrap, so I don't know why you mirror after `0.5` and not `1.0`.
4.
```
"  texCoord = clamped * texCoord + notClamped * fractPart;						\n"
			"  texCoord = (one - vMirror) * texCoord + vMirror * fractPart;					\n"
			"  texCoord = (one - texCoord) * needMirror + texCoord * (one - needMirror);	\n"
```
Looks a little bit clumsy. I think mirror can be accomplished by just doing `texCoord= - texCoord; \n` and then wrapping with `texCoord = mod(texCoord, vWrap); \n`, but `vWrap` shouldn't be twice the regular value, as it currently is. Angrylion's plugin does this neatly but in integers, I'll try to find a link to the algorithm later.

I don't have a computer setup for pulling and compiling, so I would appreciate if someone would test it. I will try to write the full algorithm later, when I'll have the time to think calmly.

**Comment by oddMLan** [comment]
Hello @standard-two-simplex, long time no see!
What do you think of #1047 and
https://github.com/standard-two-simplex/GLideN64/tree/new_texrect_coords
https://github.com/standard-two-simplex/GLideN64/tree/new_texel_fetch

Do you think some improvements can still derived from these or had these been totally superseded by the current code (these branches are stale and from years ago, after all).

On a different note, do you think adding point sample filtering (per #574/#2082) is something you can do as well? I see one of the commits from the aforementioned branches mentions something about point filtering, so I'm curious. Ogre battle and other 2d games with sprites would look crisper and benefit from it.

**Comment by gonetz** [comment]
@standard-two-simplex
Hi! Glad to see you again :)

Thanks for reviewing my code.
That clamping-wrapping-mirroring matter a bit tangled, so I easily could make it wrong somewhere.
The task is to support N64 way of wrapping-mirroring.
The main difference is that if clamping bound is set, texture coordinate wrapping/mirroring goes until that bound and then clamped by that bound.

So, lets consider your concerns:
1. 
>  This only checks if it was clamped from above and uses the already clamped texCoord instead of the original vTexCoord.

Yes, it is intended. vClamp default values are {-max, -max, max, max}. If clamping is not set, 
`clamp(vTexCoord, vClamp.xy, vClamp.zw)`
will return unchanged vTexCoord.
If clamping is set, vClamp contains actual clamp values and clamping above will return clamped vTexCoord. Thus, if
`step(vClamp.zw, texCoord)`
returns 1, we know that wrapping must not be applied, texCoord already has correct value.
You're right, lower bound of the clamped value is not checked, but it is not actually necessary.
When clamping is set, clamping value is always [0, clamingBound]
That is texture coordinate does not wrapped in negative direction when clamping is set.
If clamped coordinate is inside [0, clamingBound) we need try to wrap it.
You may check `class UClampWrapMirrorTex` to see how input arrays are initialized.

2. 
> considering that clamped coordinates also need wrapping or mirroring (in general), and that mirroring can be done with the help or wrapping, I wouldn't create this variable.

Originaly it was 
`texCoord = clamped * texCoord + notClamped * mod(texCoord, vWrap);`
fzurita found recently that mod(texCoord, vWrap) works incorrect on GLES2 devices when vWrap contains default value { 10000.0f, 10000.0f }
Mod works incorrect with values that large. So, fzurita added `wrapped `to make code safer. That fixed issues with GLES2

3.

 > I'm not sure I understand this part completely. When mirroring is needed vWrap contains double the value of the place to wrap, so I don't know why you mirror after 0.5 and not 1.0.
 
It is simple. I could take any number in (0, 1) in
` step(vec2(0.5), mod(intPart, vec2(2.0)))`

In integers it looks as
intPart % 2 != 0. That is intPart must be odd. May be it can be written more elegant way.

4.

> I think mirror can be accomplished by just doing texCoord= - texCoord; \n and then wrapping with texCoord = mod(texCoord, vWrap); \n, but vWrap shouldn't be twice the regular value, as it currently is.

Well, may be. I agree that the current version of mirroring part looks clumsy. If you can make it nicer, please do it.

**Comment by standard-two-simplex** [comment]
Hi again.

> Thus, if `step(vClamp.zw, texCoord)`returns 1,  we know that wrapping must not be applied

Are you sure? According to the N64 programming manual, clamping, wrapping and mirroring the same texture is allowed. See the [example here at the bottom](http://n64devkit.square7.ch/pro-man/pro13/13-04.htm#11), and consider the same example but with SH=5.

> That is texture coordinate does not wrapped in negative direction when clamping is set.

Texture coordinates can be negative, but tile coordinates can't. It is not very clear to me what tile coordinates mean, i.e., I don't know which operations happened from texture coordinate to tile coordinate. Only (SL,TL) subtraction? Or clamp mirror and wrap too?

I would assume it is the second one (`(S adj, T adj)` in the diagram), as I can't see how to get a positive tile coordinate by subtracting positive (SL,TL) from a negative texture coordinate, but it's only an assumption.

See [this ](http://n64devkit.square7.ch/pro-man/pro13/13-03.htm) and the diagram [here](http://n64devkit.square7.ch/pro-man/pro13/13-06.htm).

> Mod works incorrect with values that large.

Ok, I see. Perhaps it's worth separating the case where the mask is 0, where clamp is forced and mirror and wrap disabled. For the rest of the cases, `vWrap` should have reasonable numbers.

> It is simple. I could take any number in (0, 1) in
`step(vec2(0.5), mod(intPart, vec2(2.0)))`. In integers it looks as `intPart % 2 != 0`. That is `intPart` must be odd.

True, I missed you were taking the integral part.

**Comment by standard-two-simplex** [comment]
I believe something like this with `aTexWrap` initialized to zeroes and `aTexWrap[t][0/1]*=2.0` lines removed could work. Totally untested though, there will probably be mistakes, but the idea is there. I will think again about it tomorrow.

```
"highp vec2 clampWrapMirror(in highp vec2 vTexCoord, in highp vec4 vClamp,					\n"
	"	in highp vec2 vWrap, in lowp vec2 vMirror, in highp vec2 vScale)				\n"
"{														\n"
	"  highp vec2 texCoord = clamp(vTexCoord, vClamp.xy, vClamp.zw);					\n"
	"  lowp vec2 clampNotForced = step(vec2(0.0),vWrap);							\n"
	"  lowp vec2 clampForced = one - clampNotForced; 							\n"
	"  lowp vec2 one = vec2(1.0);										\n"
	"  lowp vec2 clamped = step(vClamp.xy, vTexCoord) - step(vClamp.zw,vTexCoord);				\n"					
	"  lowp vec2 notClamped = one - clamped;								\n"
	"  lowp vec2 needMirror = step(vec2(1.0), mod(texCoord, vec2(2.0))) * vMirror;				\n"   // Is there need for integral part?
	"  texCoord = (vec2(2.0) * needMirror - vec2(1.0)) * texCoord;						\n"
	"  texCoord = clampForced * texCoord + clampNotForced * mod(texCoord,vWrap); 				\n" 
	"  texCoord *= vScale;											\n"
	"  return texCoord;											\n"
"}														\n"
```

**Comment by standard-two-simplex** [comment]
@oddMLan I don't like polluting issue threads with casual forum conversation, so let's keep it to this time only. If you want anything else, just use private messaging.

> What do you think of #1047 and
https://github.com/standard-two-simplex/GLideN64/tree/new_texrect_coords
https://github.com/standard-two-simplex/GLideN64/tree/new_texel_fetch

The issue thread has quite interesting information about a bug in the texture coordinates. Wrong texture coordinates reach the fragment shader wich provokes many noticeable artifacts in many games.

The branches do not have too much to add. Sampling with in integers with texelFetch is a nice idea, but it requires quite a big rewrite of the fragment shader, which is too daunting a task for me. I don't understand most of the code in the repository. 

> do you think adding point sample filtering (per #574/#2082) is something you can do as well? 

No. Not only am I not familiar with some of the code about it, but I also believe it is not a good idea. Game programmers choose how to filter textures and they usually make a choice with visual appealing in mind. I see no good reason to force one or the other. Artifacts like the ones in Paper Mario are not due to the filtering method, more like noticeable due to it. Nearest neighbor might hide the symptoms but will not cure the disease (probably wrong texture coordinates). 

As for the magnification filter between the internal resolution and full screen resolution, I guess it could make sense. I would still personally prefer the bilinear filter. It may be a bit blurry, but it isn't blocky nor does it take the risk of creating random artifacts due to non integer scaling ([see figure 14-3](http://n64devkit.square7.ch/pro-man/pro14/14-01.htm#01)).

**Comment by oddMLan** [comment]
@standard-two-simplex
GitHub removed the private messaging feature a while back. Maybe if I want to further discuss it I can open an issue in your repository, or continue in the Ogre Battle issue thread. Thanks for the insight BTW.

**Comment by theboy181** [comment]
Or he could discord with us.  :)

**Comment by gonetz** [comment]
> Are you sure? According to the N64 programming manual, clamping, wrapping and mirroring the same texture is allowed. 

Yes. Clamping, wrapping and mirroring the same texture is allowed. However, wrapping and mirroring applied only until texture coordinate is below the clamping bound.
As soon as clamping bound is reached, clamped value is used.
If vTexCoord crosses the bound, `step(vClamp.zw, texCoord)` returns 1.

>Texture coordinates can be negative, but tile coordinates can't. 

What is tile coordinates? Tile has size, mask and flags for clamping and mirroring.
Vertex has initial texture coordinates, one pair of S and T coordinates. S and T can be negative.
These S and T transformed to actual indexes for particular tile.
That is, if combiner uses two textures T0 and T1, indexes for fetching texels from each textures calculated from vertex S and T.
It is currently done in vertex shader:
```
mediump vec2 calcTexCoord(in vec2 texCoord, in int idx)		
{															
    vec2 texCoordOut = texCoord*uCacheShiftScale[idx];			
    texCoordOut -= uTexOffset[idx];							
    return (uCacheOffset[idx] + texCoordOut)* uCacheScale[idx];
}				
```												
texCoord here is original vertex S and T.
Resulted coordinates then clamped-wrapped-mirrored in fragment shader.
Note, that hardware clamp-wrap-mirror is not disabled:

```
params.wrapS = _pTexture->clampS ? textureParameters::WRAP_CLAMP_TO_EDGE :
			_pTexture->mirrorS ? textureParameters::WRAP_MIRRORED_REPEAT : textureParameters::WRAP_REPEAT;
params.wrapT = _pTexture->clampT ? textureParameters::WRAP_CLAMP_TO_EDGE :
			_pTexture->mirrorT ? textureParameters::WRAP_MIRRORED_REPEAT : textureParameters::WRAP_REPEAT;

```

That is if texture coordinate is negative after clampWrapMirror shader, it will be wrapped by hardware.

>Ok, I see. Perhaps it's worth separating the case where the mask is 0, where clamp is forced and mirror and wrap disabled. For the rest of the cases, vWrap should have reasonable numbers.

More cases - larger the shader. Currently version works with all situations.

> Totally untested though, there will probably be mistakes, but the idea is there. I will think again about it tomorrow.

Thanks!
I need time to understand and test it.

**Comment by standard-two-simplex** [comment]
I found 2 mistakes, I edited the algorithm.

**Comment by standard-two-simplex** [comment]
To clarify what I meant before,

> Yes. Clamping, wrapping and mirroring the same texture is allowed. However, wrapping and mirroring applied only until texture coordinate is below the clamping bound.
As soon as clamping bound is reached, clamped value is used.
If vTexCoord crosses the bound, step(vClamp.zw, texCoord) returns 1.

What I meant is that the clamping bound can be outside of the tile to sample, i.e, the clamping bound can be inside the wrapping bound. Therefore, you need to wrap/mirror the clamped coordinate as well.

Consider the case of a texture with width 8, mirror enabled at width 8 (mask=3) and clamp enabled and with clamping bound SH = 11. A texture coordinate 16 for example, would be clamped to 11, then mirrored to 6. So the 6th texel would be fetched.

> What is tile coordinates?

The N64 programming manual defines texture space and tile space. Texture space can be understood as a big rectangle with each coordinate lying in the inaterval (-1024,+1023.99). The texture coordinates of a pixel are derived from interpolating the texture coordinates of the vertices of the primitive. 

The manual is less clear defining the tile space. I believe (I had to interpret for this, didn't find a clear reference, so it might be wrong) it means the rectangle  `(0,tileWidth)x(0,tileHeight)` from were texels are fetched. So texture coordinates are transformed into numbers that can be looked up in the texture.

> That is if texture coordinate is negative after clampWrapMirror shader, it will be wrapped by hardware.

True. However, if wrapping manually, it shouldn't be necessary to rely on it.

**Comment by gonetz** [comment]
@standard-two-simplex 

> Consider the case of a texture with width 8, mirror enabled at width 8 (mask=3) and clamp enabled and with clamping bound SH = 11. A texture coordinate 16 for example, would be clamped to 11, then mirrored to 6. So the 6th texel would be fetched.

I see your point now, thanks. In my algorithm that wrapping/mirroring performed by hardware.
The purpose of the shader is to say the hardware when to stop. Btw, I never met situation when as in your example. Clamping always set to limit number of wrappings/mirrors but never to stop them somewhere in the middle.

> I found 2 mistakes, I edited the algorithm.

Mirroring does not work:
![GLideN64_ZELDA_MAJORA'S_MASK_001](https://user-images.githubusercontent.com/8983092/66257159-b2708880-e7bf-11e9-8d52-e084c9dd1312.png)

I think `texCoord = needmirror ? -texCoord : texCoord` is wrong.
In my code it is  `1 - texCoord` and it works.

**Comment by standard-two-simplex** [comment]
> I never met situation as in your example

I doubt it was a common practice for game devs. I was explicitly mentioned in the programming manual though, as a clever way to make the insignia for a plane wing and save texture memory, so perhaps someone adopted it.

> I think `texCoord = needmirror ? -texCoord : texCoord` is wrong.

The idea is to combine `texCoord = needmirror ? -texCoord : texCoord` with the wrap in the following line `mod(texCoord,vWrap)`. 

To see an example, if `vWrap=0.7` and `texCoord=1.2` it would work this way: 1.2 -> (if mirror needed change sign) -> -1.2 ->(mod 0.7) -> 0.2.

I think there's another mistake. I realize clampNotForced is incorrectly set, as it always returns 1 and the value is always clamped. `vWrap` needs to be initialized to any negative value.

**Comment by gonetz** [comment]
Mirror works now, thanks. However, black outline appears some places:
![GLideN64_ZELDA_MAJORA'S_MASK_002](https://user-images.githubusercontent.com/8983092/66264080-2f841800-e829-11e9-9ec5-113b0d717b1f.png)

**Comment by gonetz** [comment]
> -1.2 ->(mod 0.7) -> 0.2.

mod(-1.2, 0.7) = -0.5

**Comment by standard-two-simplex** [comment]
> lack outline appears some places

That's gonna be harder to debug.

> mod(-1.2, 0.7) = -0.5

mod is define as `mod(x,y) = x - y*floor(x/y)`. Therefore, it returns a value between [0,y) for a positive y, and a value (y,0] for a negative y.
```
-1.2/0.7 = -1.714...
floor(-1.7) = -2
0.7*(-2) = -1.4
-1.2-(-1.4) = 0.2
```

**Comment by gonetz** [comment]
Cite https://en.cppreference.com/w/cpp/numeric/math/fmod
" The floating-point remainder of the division operation x/y calculated by this function is exactly the value x - n*y, where n is x/y with its fractional part truncated.
The returned value has the same sign as x and is less than y in magnitude."

So, C++ fmod(-1.2, 0.7) = -0.5

Cite https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/mod.xhtml:
"mod returns the value of x modulo y. This is computed as x - y * floor(x/y)."

So, glsl mod(-1.2, 0.7) = 0.2

I'm surprised.

**Comment by gonetz** [comment]
> That's gonna be harder to debug.

My guess is that clamp works incorrect.

I used saved state from #1885:
https://github.com/gonetz/GLideN64/issues/1885#issuecomment-443466285
but the link to save file is not valid anymore, so I re-uploaded it:
https://drive.google.com/file/d/1vNRFxaSzBKhAVPVsFpRo6U5Yvxe9G6eD/view?usp=sharing

**Comment by standard-two-simplex** [comment]
Mirror seems to be broken in paper mario. Attack any enemy to see a broken star.
![paper_mario-001](https://user-images.githubusercontent.com/12202580/67641026-e8a4b200-f8fe-11e9-9569-76654b263653.png)

Savestate in case you need it.
[Paper Mario (U) [!].zip](https://github.com/gonetz/GLideN64/files/3776335/Paper.Mario.U.zip)

**Comment by gonetz** [comment]
Yep, broken. Thanks!

**Comment by standard-two-simplex** [comment]
> Update: fixed in 0338f27

I confirm fixed in master (I guess you meant 5484972b).
One question. Why `pTile->clamps != 0 && pTile->masks == 0`? Isn't `masks == 0` supposed to force clamp regardless of the value of  `clamps`?

**Comment by gonetz** [comment]
It is kind of hack.
Initially it was
```
_sizes.width = width;
_sizes.height = height;
```
but Zelda debug rom set texture size in very specific way, and that code does not work.
I added alternative way to get texture size in 5c5c218e4, but it broke Paper Mario.
This condition needed to narrow usage of the alternative way.

**Comment by standard-two-simplex** [comment]
There doesn't seem to be an issue with current code so I will close the issue.
It might be possible to tidy up the code, but I failed to fix the remaining bugs in the code I suggested above so I will leave it for now.
