### ISSUE TITLE
VS 2017 Whole Program Optimization (/GL) breaks Zelda OOT N64 rotating logo (AMD issue)

### ISSUE THREAD

**Issue by oddMLan** [gonetz/GLideN64#2098]
![image](https://user-images.githubusercontent.com/7278372/66286356-f928b600-e885-11e9-96fe-e890c371570a.png)

AMD Radeon R7 240 drivers 19.6.1, Win10 LTSC x64, deleted shader cache, restarted computer

**Comment by oddMLan** [comment]
@gonetz If you got a second could you look at the Discord64 server (#gliden64 channel) for a moment? there's something we want to overlook with you

**Comment by oddMLan** [comment]
Apparently it's the /GL flag cauing the breakage. If I disable it, the logo displays fine.
Maybe the latest VS 2017 changed something.
My msbuild ver. is 15.9.21.664

**Comment by gonetz** [comment]
@oddMLan I did not visit discord for a long time and forgot how to enter it.
Please send a short instruction on my email.

**Comment by gonetz** [comment]
Microsoft Visual Studio Professional 2017 
Version 15.9.11
No problems with Zelda OOT logo on GeForce.
I'll try to update and rebuild.

**Comment by gonetz** [comment]
I updated VS to ver. 15.9.16
It is current version. I rebuilt GLideN64 with it. Still no problems with Zelda OOT logo.

**Comment by oddMLan** [comment]
What Toolkit/SDK are you using for the Solution?
It asks for the Windows 8.1 SDK, but when prompted, I retargeted to Windows 10 SDK `10.0.17763.0`

Last thing I suspect can be breaking the whole program optimization, is GLideNUI, though that sounds unlikely... since I got it from the "lazy way" for VS2017 in the wiki page. Installed the QT VS Addon, not from [here](https://marketplace.visualstudio.com/items?itemName=TheQtCompany.QtVisualStudioTools-19123) (I got an error from the server at the time)
but from here https://download.qt.io/official_releases/vsaddin/2.4.1/

I installed it, restarted VS, then configured QT VS Tools, added my path to the precompiled Qt files. Then I had to do some extra steps I didnt remember, because I was getting errors like this when trying to build GLideNUI

![image](https://user-images.githubusercontent.com/7278372/66423440-97209b80-e9c0-11e9-905b-78f08ef39c4d.png)

Then I right clicked the solution in the Solution Explorer > Qt Project Settings. Qt Modules Tab, enabled "Widgets". Less errors now. So go back and enable what I think will be necessary, GUI, Core, Multimedia, OpenGL, etc. I went again and left only the following modules: Core, GUI, UI Tools, Widgets and Windows Extras. The result? Logo is still broken with /GL on my end.

I attach the Release and Debug builds here, and see if one of the optimizations is breaking AMD but not Nvidia... though I doubt it.
[Debug.zip](https://github.com/gonetz/GLideN64/files/3704081/Debug.zip)

**Comment by gonetz** [comment]
First, I use QT Visual Studio Tools addon, which I found in Tools->Extensions and Updates panel, Online section. May be it is the same vsaddin as the one you installed. I had no errors with building GLideNUI using my "lazy way" static build for VS2017 I just open GLideN64 solution, choose solution QT version (right click the solution) and build.

Second, your builds works fine on my GeForce, both release and debug. That is Zelda logo is correct.
May be something wrong with new AMD drivers? My radeon is quite old, and I had no issues with Zelda logo on it too. I did not test your builds with it though.

You may also build GLideN64 for mupen64plus and check, how it works. If the problem persists with mupen64plus, it definitely is not a  problem with QT.

**Comment by oddMLan** [comment]
Okay, I'll build a mupen ver. and check with it.

**Comment by oddMLan** [comment]
![image](https://user-images.githubusercontent.com/7278372/66460267-632e9000-ea2b-11e9-9809-3bd2f94f980f.png)
Nope, still broken with Mupen64Plus

**Comment by gonetz** [comment]
I tried your builds from Debug.zip on my desktop with AMD CPU + Radeon.
Zelda logo works correct with both builds.
It seems to be a problem with your configuration. May be you have some Reshade filters enabled?

**Comment by oddMLan** [comment]
I don't have external shaders applied. Are you using the latest drivers? Maybe it is a problem only with the latest drivers. Although, I wonder why the /GL flag is breaking it, and why disabling it fixes it. It doesn't make sense. I also disabled AMD's driver cache, and that didn't fix it.
Your builds have the /GL flag, and they work correct on my end. For the VS project, I chose "Retarget solution" to Windows 10 SDK 10.0.17763.0. What SDK do you use? I can try downloading a previous SDK, and see if that is a problem.

**Comment by gonetz** [comment]
> Are you using the latest drivers?
No, ver. 22.19.677.257, two years old.

> Your builds have the /GL flag, and they work correct on my end. 

I use VS 2015 mostly.

> What SDK do you use?

I have only one option in "Retarget solution" : 8.1

**Comment by oddMLan** [comment]
I uninstalled my GFX driver with DDU, and did a clean install of a newer version. Same issue.
Changing the SDK to Windows 8.1 didn't solve the issue either.
I just confirmed that this is a VS 2017 problem. Compiling in VS 2017 with the VS 2015 toolset doesn't have this issue on my AMD card with latest drivers, even with /GL .
However, on your end my VS 2017 build with /GL didnt manifest the issue. So this is a very specific compiler + driver issue...

**Comment by oddMLan** [comment]
Clearly some optimization done by VS 2017 is breaking on AMD and not Nvidia. Is there a good way to compare the relevant code between VS2015 and VS2017, both with /GL? What code does the N logo lightning? Some lightning normalization step?

**Comment by gonetz** [comment]
> Is there a good way to compare the relevant assembly code generated across VS2015 and VS2017, both with /GL?

Never did anything like this.

> What code does the N logo lightning? Some lightning normalization step?

LIGHTING + TEXTURE_GEN (generation of texture coordinates depending on LookAt structures) :
gSPProcessVertex

**Comment by Craftyawesome** [comment]
I am having the same issue on oot 1.0, but on nvidia. Only on 1.0, not on 1.2.
![image](https://user-images.githubusercontent.com/19976035/68986093-12f4db80-07ea-11ea-8571-b5afd0db8ec5.png)
GLideN64-517723d3 (appveyor zilimar)
Nvidia GTX 1060 441.20 drivers (latest)

**Comment by oddMLan** [comment]
AppVeyor builds use VS 2017. Good to know that it is reproducible on Nvidia too. Sounds like a bad compiler optimization. @fzurita got any ideas that can help us diagnose the issue?

**Comment by kev4cards** [comment]
This happens for me, also. Same GlideN64 build, same game version, and same graphics card+driver. The problem also occurs with Intel UHD Graphics 630 (integrated, i7-8750H processor). I can see part of the N go from black to color as it rotates from the right to the front (if that's worth anything).

On a side note (most likely unrelated), checking "render N64 frame buffer to main screen" produces a white screen.

**Comment by oddMLan** [comment]
Fixed, no significant performance hit noticed.
