### ISSUE TITLE
PJ64 All Game wont start while using GlideN64

### ISSUE THREAD

**Issue by 72888hshu** [gonetz/GLideN64#2099]
So I am using Project64 1.6 early cuz Jabo's Direct3D8 fit me. But when I want to play Pokemon Snap and I find out it cant display my pictures propely, so I google searched out and find out the "copy from RDRAM" things. So I downloaded the Project64 2.3.2 to try it out, but it gave me the "CN64System::EmulationStarting: Exception Caught
File: .\N64System\N64Class.cpp
Line: 485"error.
I try out the other version of GlideN64 but its the same for all game.

My spec(toaster but still can run game):
Intel(R) GMA 3150
Intel(R) Atom(TM) CPU N455 @1.66GHZ
2GB RAM
1TB HDD

![GlideN64 PJ64 #1](https://user-images.githubusercontent.com/48046222/66312292-ff309c80-e942-11e9-90a2-9c3f9e8bb706.PNG)
![GlideN64 PJ64 #2](https://user-images.githubusercontent.com/48046222/66312298-ffc93300-e942-11e9-8318-e5961f74f34a.PNG)

btw I can use other plugins to play but I want to use GlideN64

**Comment by gonetz** [comment]
I can't find exact information about OpenGL version supported by Intel(R) GMA 3150,
but it seems that 2.0 is the best it can do. GLideN64 **requires** at least OpenGL 3.3
Your "toaster" should be able to run Glide64, which included into Project64 2.x distributives.

**Comment by 72888hshu** [comment]
Thanks for helping me, its definitely (sorry my english suck) the OpenGL problem cuz its only support to OpenGL 1.4. I will try using Glide64.
