### ISSUE TITLE
Mia Hamm Soccer 64: wrong textures in menu (regression & HLE)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#210]
![ooops](https://cloud.githubusercontent.com/assets/8987490/5518124/ac24104e-8916-11e4-86c6-5d09e8bbb775.jpg)

**Comment by AmbientMalice** [comment]
What's quite fascinating is how the splash screen is split down the middle, and each side has totally different corruption to the other.

![mia_hamm_soccer_64-000](https://cloud.githubusercontent.com/assets/10704701/14064208/efa80ad6-f43c-11e5-847a-e3d8967768bd.png)

**Comment by olivieryuyu** [comment]
well this pic is an improvment compared to before.

the RDP command are slightly used in ZStorp differently. 

http://www.jax184.com/projects/ultra64/Nintendo%20Ultra64%20Programming%20Manual+Addendums.pdf

most important being the addendum abou the Zstorp mircrocode

**Comment by olivieryuyu** [comment]
@gonetz 

just something I noticed: should the command value for RDPHALF 1 & 2 (E1 anf F1) be F3DEX2_RDPHALF_1 and F3DEX2_RDPHALF_2 in the ucode?

i can see now they are set if they were from F3DEX1.

**Comment by gonetz** [comment]
May be they need to be redefined for this ucode.

**Comment by olivieryuyu** [comment]
It works ok in LLE so it is a HLE bug

**Comment by olivieryuyu** [comment]
closed
