### ISSUE TITLE
Rugrats' Scavenger Hunt: Screens look heavily distorted at default resolution

### ISSUE THREAD

**Issue by oddMLan** [gonetz/GLideN64#2100]
GLideN64
![1](https://user-images.githubusercontent.com/7278372/66329104-ce207f80-e8e2-11e9-8731-9eddd077e115.png)

Angrylion Plus R7
![2](https://user-images.githubusercontent.com/7278372/66329157-e98b8a80-e8e2-11e9-8ce0-09655f4bdd94.png)

related bugs: ?
Workaround: select a high enough factor of internal resolution, the distortion disappears. But this shouldn't be happening at 640x480 ~~(native)~~ default resolution

**Comment by oddMLan** [comment]
Also there's a green row of pixels in the upper left corner that shouldn't be there, plus a white row of pixels at the top that _should_ be there, apparently.

**Comment by oddMLan** [comment]
Glide64 suffers from this also, but it's much less noticeable. Including the green row of pixels at the top left

**Comment by gamemasterplc** [comment]
640x480 is not anywhere close to a multiple of this game’s resolution or is this game’s resolution. The real game resolution is 512x240.

**Comment by gonetz** [comment]
Its true. When you select "native resolution" option, result is the same as with Angrylion plugin.

**Comment by oddMLan** [comment]
I forgot to try with native resolution. If it's fixed by native resolution, should it be closed? It's something that can hardly be fixed otherwise, correct?
Note: DKO's experimental filtering branch fixes this, even at non-native resolutions.

**Comment by gonetz** [comment]
> If it's fixed by native resolution, should it be closed?

Yes. It is old well known issue that 2D backgrounds look bad in non-native res. Thus, there are options to render 2D in native res.

**Comment by oddMLan** [comment]
> Thus, there are options to render 2D in native res.

Native texrects doesnt fix the issue, though. Why?
Only "Original N64 resolution" or factors of it look correct.

**Comment by gonetz** [comment]
> Native texrects doesnt fix the issue, though. Why?

Native texrects option fixes rendering of filtered backgrounds. Backgrounds here are not filtered.
I guess, non-integer scaling causes the issue. The game looks better in 1024x768 than in 960x720.

**Comment by gamemasterplc** [comment]
1024x768 is however still a non-integer scale vertically. Reducing the height to 720 does however give an integer scale vertically at the cost of a slightly wrong aspect ratio. You would need to scale to 2560x1920 which is 5 times horizontally and 8 times vertically to get the correct aspect ratio.
