### ISSUE TITLE
Multiplayer camera rotation issue in Conkers Bad Fur Day

### ISSUE THREAD

**Issue by kcghost** [gonetz/GLideN64#2101]
In CBFD multiplayer, some of the players experience a camera rotation and "snap" back to original position every second or so, regardless of controller input.

To reproduce, start up CBFD, go to multi, go left to BEACH mode, enable all four players and start playing. By default players 2 and 4 are tediz, and both suffer camera snap. I reproduced with actual controllers, but I doubt you would even need controllers to reproduce, just binds for all four players start buttons to enable them.

From some research it seems this issue also applies to DK64 and there are some obtuse workarounds:
[mupen retroarch issue](https://github.com/libretro/mupen64plus-libretro/issues/80)
[dk64 workaround](https://github.com/libretro/mupen64plus-libretro/issues/86#issuecomment-452648612)

Perhaps these resources can help in developing a real fix.
I tried messing around in the custom.ini file abit to fix it but I don't really know what I am doing, perhaps it is as simple as an ini change.

**Comment by gonetz** [comment]
As I remember, weird camera rotation in CBFD can be caused by incomplete frame/depth buffer emulation. Try to enable software depth buffer render. For mupen64plus it is "EnableCopyDepthToRDRAM=2"

**Comment by kcghost** [comment]
I seems that is already the [default?](https://github.com/gonetz/GLideN64/blob/9409abd671c22246291153cf919018d1096f91fc/src/Config.cpp#L57).  I also tried EnableCopyDepthToRDRAM = 1 like DK64's custom settings, and tried EnableN64DepthCompare = True, but all seem to have the same result.

**Comment by gonetz** [comment]
>I seems that is already the default?

It should be default, yes. The problem should be in multiplayer, since single player mode works smooth. Graphics plugin should prepare and write some data back to RDRAM. I assume that the plugin does it wrong for some buffers in multiplayer mode. I'll check it, but can't promise that it will be soon.

**Comment by kcghost** [comment]
Thanks! I am fairly well set up to test this, let me know if you'd like me to confirm any potential fixes.

**Comment by kcghost** [comment]
Did some testing this evening and found this issue does not occur in Public_Release_3_0, so it is a regression of some sort.

**Comment by kcghost** [comment]
Did git bisect testing and identified [this commit](https://github.com/gonetz/GLideN64/commit/3d4629337693a8867629e77acfd4876fa2f7bfe4) as the issue: "Correct condition for depth buffer copy hack for Perfect dark."

I am having some trouble building a working windows plugin on the master branch (crashes?), but I have confirmed that reverting this commit off the Public_Release_4_0 tag solves the issue for CBFD.

I have no idea what is going on in this change so I wouldn't know what the correct fix is that would encapsulate both CBFD and PD  :)

**Comment by ll33ee** [comment]
Solved...
Use Video Plugin: angrylion's Pixel-Accurate N64 Plugin
Config multi option (Characters, Lives, Time... ), when start Multi, Save state and End emulation.
Select your favorites plugins, start emulation and Load state and play.
You can Restart... but Quit or end game, you need to repeat the steps or Load state.
Enjoy!

**Comment by weinerschnitzel** [comment]
@ll33ee are you reporting the issue still present in GLideN64 with a build newer than 19 days ago?

**Comment by gonetz** [comment]
The original issue is fixed with 1fdd028

**Comment by ll33ee** [comment]
@weinerschnitzel, **Yes, is fixed!**! :O
First I found this, updated months ago: https://github.com/gonetz/GLideN64/releases
Here **NEW** ✅ **https://ci.appveyor.com/project/gonetz/gliden64/branch/master/artifacts**
"**newer than 19 days ago**" Thanks!

@gonetz Oh, Interesting. Thank you for the information 😮
