### ISSUE TITLE
Graphical issues when using 16MB of RAM in Mupen

### ISSUE THREAD

**Issue by zmarotrix** [gonetz/GLideN64#2104]
I'm not sure if this is an error exactly since this was not intended, but graphics start to malfunction when enabling more than 8MB of RAM in Mupen64. Is there a hardcoded limit somewhere? 

Specifically, we are using zzplayas models stored in the end of the 16MB of RAM in OoT and even though they were working fine at the end of 8MB, they are starting to have several small issues in 16MB. Since we have already modified the Mupen64Plus core, we are thinking it's an issue with GLideN64.

example
`gMoveWd(opa->p++, G_MW_SEGMENT, G_MWO_SEGMENT_8, 0x06005000);`
This would work but if I start to point outside of the normal RAM, it will load, but it will not render correctly.

**Comment by gonetz** [comment]
> Is there a hardcoded limit somewhere?

Yes. However, if GFX_INFO version is >=2, plugin uses provided RDRAM_SIZE, see PluginAPI::InitiateGFX in src\mupenplus\CommonAPIImpl_mupenplus.cpp

**Comment by zmarotrix** [comment]
Thank you! We did find a work around for the time being but I'll be sure to keep this in mind!
