### ISSUE TITLE
Turok 2 Ink mode not working

### ISSUE THREAD

**Issue by LuismaSP89** [gonetz/GLideN64#2106]
Ink mode is available in the cheats section, you need to enter the code:

bewareoblivionisathand

Once entered, you have access to this mode, but with gliden64 only shows all the screen in white color. Tested with many builds of Gliden64 with no success.

Sorry for no providing a screenshot... but that's all, only a white screen shows. If you disable the ink mode, the game looks again as it should.

**Comment by oddMLan** [comment]
That feature requires coverage emulation, which is currently not emulated.

**Comment by CrashOveride95** [comment]
> That feature requires coverage emulation, which is currently not emulated.

Is that the same reason Line Mode in GoldenEye is broken?

**Comment by gonetz** [comment]
Yes, Line Mode in GoldenEye also requires coverage emulation.

**Comment by mudlord** [comment]
Wouldn't that mean compute shader usage to emulate coverage to a extent?

**Comment by gonetz** [comment]
that mean that we need to compute coverage somehow, yes.

**Comment by mudlord** [comment]
The Vulkan port of Angrylion does this via compute shaders, then again, everything in that plugin is handled on the GPU itself. Including rasterization.

**Comment by gonetz** [comment]
Yes, very impressive achievement.

**Comment by standard-two-simplex** [comment]
Fixed

**Comment by LuismaSP89** [comment]
Sorry but not fixed at least for me. All the screen remains white with only minor objects correctly rendered, but too far yet from the n64 real ink mode in this game.

**Comment by oddMLan** [comment]
Comparison pics would help to see what you're talking about. Could you provide screenshots between GLideN64 and Angrylion that highlight the issue?

**Comment by LuismaSP89** [comment]
Sure, here you can see how it looks in Gliden64:

![1](https://user-images.githubusercontent.com/12205048/104234769-3817c500-5454-11eb-89d1-8a86d6b86eb7.jpg)

And here how it looks on a real N64 / Angrylion's plugin, (It's like a polygon mode or something else)

![2](https://user-images.githubusercontent.com/12205048/104234764-364e0180-5454-11eb-8f22-cce7fbde3006.jpg)

In both images you can see the same portal, but it's the only thing rendered correctly in the Gliden64 using this Ink & Pen cheat mode.

**Comment by oddMLan** [comment]
OK thanks, that definitely looks wrong. What is your OS, GPU, and graphics driver version? Can you also provide a save state?

**Comment by LuismaSP89** [comment]
My apologies, I didn't noticed the "pixel coverage calculation" new feature.

Now it works, at least at 99%, I can see some lines not rendering but maybe its only my perception.

Closing.

**Comment by oddMLan** [comment]
This is a supporting argument to enable it as a ini setting for games that make noticeable use of it (Turok 2, south park, can't think of anything else).

**Comment by LuismaSP89** [comment]
Yes indeed.

On the other side, what about enabling it for most games? Can been some improvements even if the game doesn't use this "Pen & Ink mode"?  The description says that is recommended enabled by default. Why not force it for all games unless the user disables it?

**Comment by gonetz** [comment]
> I can see some lines not rendering but maybe its only my perception.

No, it is an issue with this feature in master. Fixed in soft_clip branch.



> what about enabling it for most games?

up to 40% performance drop on mobile GPUs.
