### ISSUE TITLE
Pokémon Stadium 2 - Cut off pokémon portraits

### ISSUE THREAD

**Issue by DonelBueno** [gonetz/GLideN64#2110]
The pokémon portraits that appear before the pokémon selection are cut off on the bottom.

GLideN64:
![Project64_2019_10_26_18_29_58_458](https://user-images.githubusercontent.com/4239694/67627374-65695a80-f831-11e9-9a55-a06d6c735832.png)

Angrylion Plus:
![Project64_2019_10_26_18_29_16_185](https://user-images.githubusercontent.com/4239694/67627375-67cbb480-f831-11e9-9701-4f4cd3f5dfa1.png)

Running on Project64 2.3x, Windows 10, Geforce GTX 1070.

**Comment by gonetz** [comment]
Fixed

**Comment by DonelBueno** [comment]
Confirmed fixed, thank you.
