### ISSUE TITLE
Blast Corps regression

### ISSUE THREAD

**Issue by Tasosgemah** [gonetz/GLideN64#2113]
In the latest version WIP of the plugin this happens:

https://i.postimg.cc/J4KdFZGY/Untitled.png

At the bottom left and right the images are supposed to be 2D images of the vehicles. But now they appear cut in half and upside down.

**Comment by standard-two-simplex** [comment]
@Tasosgemah You can drag & drop images into the comment section to display them.

![](https://i.postimg.cc/J4KdFZGY/Untitled.png)

**Comment by Tasosgemah** [comment]
OK, thanks

**Comment by gonetz** [comment]
I have fixed this issue. Test build (shaders storage must be disabled):
https://drive.google.com/file/d/15Q2jMqmtriX2E0FO8lyTerR9D7RCsEmu/view?usp=sharing

This problem is fixed, but I'm not sure that the fix does not lead to regressions. Please test other games too.

**Comment by Tasosgemah** [comment]
Looks good on PJ64. Even with shader storage enabled.

I couldn't make the plugin work on mupen though.

**Comment by gonetz** [comment]
> I couldn't make the plugin work on mupen though.

I run it with no problems. It is 32bit version.

**Comment by Tasosgemah** [comment]
> 
> 
> > I couldn't make the plugin work on mupen though.
> 
> I run it with no problems. It is 32bit version.

I must be running the 64bit version of the emulator then.

Could test the plugin fine on PJ64, looks good with a few games i usually test.
