### ISSUE TITLE
Textures do not load from uncompressed HTS files

### ISSUE THREAD

**Issue by GhostlyDark** [gonetz/GLideN64#2120]
**What's broken:**
GLideN64 does not load any hires textures from uncompressed HTS cache unless the **Compress texture cache** option is activated.

**What works:**
HTC cache does not have this issue. An uncompressed HTC file loads without **Compress texture cache** being activated, just like it should be.

**How to reproduce:**
1) Generate HTS cache without using compression.
2) Load that HTS file without ticking the compression option.

![HTS](https://user-images.githubusercontent.com/31742919/68077961-aaf7cb80-fdcd-11e9-87c8-a6146824dc62.png)

**Reason: (not needed for bug fixing)**
Disabling compression gets rid of the stuttering that occurs when using lots of high resolution textures (512x512 and above) like Nerrel's MM N64HD does. The stuttering is also present when using compressed HTC cache. I assume the stuttering is a result of the textures needed to be decompressed. At these resolutions the decompression is costly. HTS does not introduce any additional stuttering when streamed from a SSD.

**Comment by GhostlyDark** [comment]
I failed to realize that it does load when **Compress texture cache** is activated. That means if I want to generate uncompressed HTS cache I need to deactivate compression and once it is generated I need to enable it when I want to load it. Otherwise the hi-res textures won't show.

The issue with that workaround is that I have to remove/rename the PNG that is used to generate the cache. Otherwise the uncompressed HTS file gets killed and a new compressed HTS file gets generated.

This issue is probably a duplicate of #2079.

**Comment by gonetz** [comment]
Thanks for the explanations. I did not test that code without compression. Some logic is broken without it.

**Comment by gonetz** [comment]
Fixed in 09764fe. You're right - use of uncompressed cache removes the stuttering. The cache file size doubled though.

**Comment by GhostlyDark** [comment]
Fixed. Thank you gonetz!
