### ISSUE TITLE
PNG with ICC Profile breaks cache on x64

### ISSUE THREAD

**Issue by GhostlyDark** [gonetz/GLideN64#2125]
**What's broken:**
Certain PNG files cause a crash when trying to generate cache. It turns out that image files with a certain profile are causing this. ImageMagick puts this out:
`iCCP: profile 'ICC Profile': 'GRAY': Gray color space not permitted on RGB PNG`

**Affected platforms:**
This only happens with Project 64 (64-bit) and mupen64plus (64-bit) as this is not reproducable with their 32-bit counterparts. Tested on Windows 10 1903 x64.

**Workaround:**
Stripping the image or reexporting with GIMP fixes this.
Using GLideN64's 32-bit version instead works as well.

**Reproduce:**
[ImageMagick Full Output](https://github.com/gonetz/GLideN64/files/3803931/identify.txt)
[Test Images](https://github.com/gonetz/GLideN64/files/3803932/Test.Images.zip)

**Comment by gonetz** [comment]
Fixed with 4b263e39
I tested mupen64plus x64 only.
The fix included into latest WIP build, #2037

**Comment by GhostlyDark** [comment]
Grabbed the x64 mupen build from AppVeyor since the WIP build is a few hours too old.
I can confirm that it is fixed. Thank you again!
