### ISSUE TITLE
Problem with ISS64 and Geforce Kepler

### ISSUE THREAD

**Issue by Anths2016** [gonetz/GLideN64#2127]
The problem of shadows remains.

**Comment by gonetz** [comment]
Do you have N64-style depth compare enabled?

**Comment by mudlord** [comment]
Do kepler spec video cards have OGL 4.3?

**Comment by gonetz** [comment]
Good question.
@Anths2016 please open gliden64.log. If your see
`"Your GPU does not support the extensions needed for N64 Depth Compare."`
here, then you need newer card.

**Comment by Anths2016** [comment]
Yes unfortunately. :(
"Your GPU does not support the extensions needed for N64 Depth Compare."

**Comment by gonetz** [comment]
Closed, since  Kepler doesn't support required OpenGL level.
