### ISSUE TITLE
Majoras mask graphical glitch

### ISSUE THREAD

**Issue by LuismaSP89** [gonetz/GLideN64#2133]
Graphics glitch in the latest version of Gliden64, it happens when you charge the spin attack. Some red circles can be seen in the edge of the sword and near the link's hand. (Image attached)

![MM](https://user-images.githubusercontent.com/12205048/68713526-5529dd00-059e-11ea-9840-62e89234070f.jpg)

Tested with project64.

Specs:

Windows 10 x64
I7 4790k
GTX 970
16 GB DDR3

**Comment by standard-two-simplex** [comment]
It should be ok in the last build here: https://github.com/gonetz/GLideN64/pull/2130

**Comment by gonetz** [comment]
Fixed
