### ISSUE TITLE
Convert a folder of PNG files to an HTC archive independently of Project64?

### ISSUE THREAD

**Issue by treymerkley** [gonetz/GLideN64#2137]
I'm trying to generate an HTC file that would exceed the 4Gb limit of PJ64 and do it on Linux for use in Mupen64Plus. Is there a way I can generate that file? The archive looks different from a tar file, zip, and 7z.

**Comment by gonetz** [comment]
Yes, you can do it, especially on Linux, if you have enough RAM. You need to use 64bit versions of Mupen64Plus and GLideN64 to build HTC exceeding the 4Gb limit, and 64bit is default for Linux. 
GLideN64 generates HTC file if you set txHiresEnable and txSaveCache options for GLideN64 and if txPath points on the folder with hires packs. Just run the game, and if hires packs folder has subfolder with the same name as internal name of the game running, the plugin will start to build the texture cache file. HTC keeps all textures in memory, so you need plenty of RAM. You may use HTS format instead, which loads hires textures from HDD. Enable txHiresTextureFileStorage option for that.

**Comment by treymerkley** [comment]
Perfect, thanks!

**Comment by HansFan2001** [comment]
Is there a way to convert PNG, OBJ, and MTL files to HTC?
