### ISSUE TITLE
Z-buffer issue with DOOM 64?

### ISSUE THREAD

**Issue by MX9000** [gonetz/GLideN64#2138]
Hi to all members!
I'm playing the game Doom 64 (USA) (Rev A) with Project64 nightly build v2.4.0-1066-g83ae431 and graphic plugin GLideN64_Public_Release_4.0.7.
My notebook has an i7-4930MX CPU with integrated Intel HD Graphics 4600 and a NVIDIA Quadro K4100M discrete card, OS is Windows 7 64 bit.
I have noticed that at the start of the game the enemies overlap the corner of the first corridor.
I tested the option Enable N64-style depth compare with both GPUs but the glitch is the same.
I attach a screenshot.
Thanks to all.

![GLideN64_Doom64_002](https://user-images.githubusercontent.com/58113425/69480981-28cb5780-0e0d-11ea-8764-8b3c07b737b4.png)

**Comment by gonetz** [comment]
Yes, the problem exists. However it seems that the problem is with game's engine, not with GLideN64. Angrylion's software graphics plugin has the same issue:
![Doom_al_rdp](https://user-images.githubusercontent.com/8983092/69617349-a8a22d80-106a-11ea-918e-e25674aa8515.jpg)
