### ISSUE TITLE
Can't open a Goldeneye rom more than once using GlideN64 [1964]

### ISSUE THREAD

**Issue by GEZKA** [gonetz/GLideN64#2139]
Im using GlideN64 by Gonetz, and it works great. Except for one thing: I can't open a goldeneye rom more than once at a time. Basically I open a rom, then I close the rom. But after that I cant open the rom again. I'd have to close 1964 and then run it again.
Would like to know why, as im considering to switch to Glide64. :/

**Comment by oddMLan** [comment]
We need more information. What version of GLideN64 are you using? What OS, CPU and GPU most importantly, do you have?

**Comment by GEZKA** [comment]
I'm using the Final build of GLideN64. My CPU is an Intel(R) Core(TM) i5-4300U @ 1.90GHz 2.50 GHz with 16 GB's of RAM-memory. I'm using Windows 10(64 bit), my GPU is a NVIDIA GeForce GT 720M 389.08. The issue only happens when I'm opening a GE rom more than once. Not nescessarily has to be one specific rom. Once I've opened a rom, and then closed it, I cannot open another rom or the same rom again. It doesn't rely on fullscreen, as the issue occurs in windowed mode aswell. Hope that's enough information.

**Comment by oddMLan** [comment]
Did you solve the issue?

**Comment by GEZKA** [comment]
yes i solved it.

Outlook for Android<https://aka.ms/ghei36> downloaden
________________________________

**Comment by gonetz** [comment]
> Did you solve the issue?
> yes i solved it.

So where the problem was and how you solved it?
