### ISSUE TITLE
ISS02000: enablefb cause wrong texture during intro

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#214]
Here ISS2000 during intro

![reg](https://cloud.githubusercontent.com/assets/8987490/5519195/0630b84a-8948-11e4-8fc7-9334dd5eab9c.jpg)

**Comment by gonetz** [comment]
Fixed

**Comment by olivieryuyu** [comment]
not fixed in current version

**Comment by gonetz** [comment]
Fix uploaded

**Comment by Predator82Germany** [comment]
Fixed with Mar19

**Comment by olivieryuyu** [comment]
fixed
