### ISSUE TITLE
Jet Force Gemini Black line following character

### ISSUE THREAD

**Issue by kev4cards** [gonetz/GLideN64#2148]
Same problem as CBFD. The issues ran concurrently. However, Jet Force Gemini's problem still remains.

Screenshot from first level right outside ship:

![GLideN64_JET_FORCE_GEMINI_000](https://user-images.githubusercontent.com/21962903/69895438-79571f00-12fd-11ea-990e-a8826588fc09.png)

Specs: i7-8750H, GTX 1060, Win 10 1903 Home, Project64 2.4.0-976, 32-bit GlideN64 (appveyor commit 2b5e878)

**Comment by BiatuAutMiahn** [comment]
Related to #2112 I believe

**Comment by oddMLan** [comment]
Try running in native resolution without Antialiasing. does it still appear?

**Comment by kev4cards** [comment]
Figured it out. I didn't have "copy auxiliary color buffers to N64 memory" checked. I had anti-aliasing already off. I didn't realize I needed the aforementioned frame buffer option checked. It would be good to add that to the default profile, I assume. I leave this open so Gonetz can see then close it. Thanks everyone.

**Comment by gonetz** [comment]
JFG uses shadows post-processing, which makes dynamic shadows look soft. This post-processing performed on CPU level, and thus the image of the shadow must be in RDRAM.  "copy auxiliary color buffers to N64 memory" option does exactly this - it copies frame buffer texture to RDRAM. You will have other issues with shadows without that option, like a garbage behind the shadow when you jump. So yes, it is better to have that option enabled by default for JFG.

**Comment by BiatuAutMiahn** [comment]
This black line issue propagates to libretro/mupen64plus
