### ISSUE TITLE
Rogue Squadron - White screen overlay

### ISSUE THREAD

**Issue by Levan7** [gonetz/GLideN64#2153]
I'm using Project64 Git (2019/12/03) and GLideN64 Git (2019/11/23)

So when i start the game the game gets some kind of white over layer and i can't find a way to get rid of it

This is how it looks
https://i.imgur.com/ibxKLsy.mp4
https://i.imgur.com/S4NuA6B.mp4

**Comment by IronYoshi64** [comment]
@Levan7 What settings are you using for Project64 and GLideN64?

**Comment by Levan7** [comment]
@IronYoshi64 
I changed the graphics a bit added fxaa and aa filtering the other plugin settings is set to default.

![1](https://user-images.githubusercontent.com/5770076/70724112-6e47ba00-1d13-11ea-93a3-a242ca10a6e8.png)

[GLideN64.txt](https://github.com/gonetz/GLideN64/files/3956404/GLideN64.txt)

**Comment by IronYoshi64** [comment]
@Levan7 Try without the FXAA and AA settings. Also you can try using the latest wip GLideN64 version:
https://ci.appveyor.com/project/gonetz/gliden64/branch/master/artifacts
I also notice you have hardware lighting on from the GLideN64.txt file you attached, that may also be a problem with your issue you are having.

**Comment by Levan7** [comment]
@IronYoshi64 
Well i changed hardware lighting to 0 but didn't help tried disabling fxaa and aa didn't help tried the GLideN64 build you provided (Used zilmar-spec) didn't work

**Comment by IronYoshi64** [comment]
@Levan7 Hmm ok. Well it was worth the try though. Some time later today I will boot up my copy of the game and see if I can replicate your issue, etc. If I find a fix with certain settings, I will post them here so you can see them.

**Comment by IronYoshi64** [comment]
@Levan7 Also, what is your exact Game Settings for the game? Right click on it from rom browser, then click Edit Game Settings. What are your settings for both the Config and the Recompiler? Pretty much, what is your Rom Database (RDB) settings for the game?

**Comment by Levan7** [comment]
@IronYoshi64 
Is this the things you are talking about

![1](https://user-images.githubusercontent.com/5770076/70736826-9c84c400-1d2a-11ea-93ea-daaa1bcd06f7.png)
![2](https://user-images.githubusercontent.com/5770076/70736827-9d1d5a80-1d2a-11ea-8197-e0f698c638a1.png)

**Comment by IronYoshi64** [comment]
@Levan7 Yes that's it. I wanted to know if any of the RDB settings got messed up in some way or if something was setup wrong. Everything looks fine there.
Also, you do have Emulate frame buffer on right? Also is Enable N64-style depth compare On, from Frame buffer tab?
Also are you on a laptop or desktop? Do you have a dedicated video card installed in your computer, or are you using Integrated graphics for your system?

**Comment by Levan7** [comment]
@IronYoshi64 

Emulate frame buffer was on but  N64-style depth compare was off, after enabling it i still got the same issue.

I'm using 1050ti desktop windows 10 64bit

![1](https://user-images.githubusercontent.com/5770076/70737807-d48d0680-1d2c-11ea-9a68-fddd587d7123.png)
![2](https://user-images.githubusercontent.com/5770076/70737808-d48d0680-1d2c-11ea-8bce-c6c8eb1ae406.png)

**Comment by Levan7** [comment]
@IronYoshi64 One very important thing i noticed after a pc restart this bug disappears for some time it returns after some playtime can it be driver incompatibility.

Don't think it is GFX card issue because haven't noticed any problem with it outside project 64

**Comment by IronYoshi64** [comment]
@Levan7 So it disappeared, then later it came back?
To me that actually reminds me of a bug I had with Yoshi's Story when I had Shader Cache enabled. Random objects would disappear like fruit bubbles and certain platforms after playing for a long time. For that game, disabling the Enable shader cache option fixes that. I think that may be what is happening for you here.
Try to disable shader cache for the game. Also to be safe and refresh things, go where the Project64.exe is, go inside Plugin > GFX > shaders folder, and delete all what is there. This will guarantee that shader cache will be rebuilt and not get corrupted in some way.
Also as a side note, I notice you are using a slightly older build of Project64. The latest right now is 2.4.0-1077: https://www.pj64-emu.com/nightly-builds

**Comment by Levan7** [comment]
@IronYoshi64 
Thank you, you really helped me troubleshoot this issue big thank you :)
