### ISSUE TITLE
Mario Tennis- Green Dots on Start Menu

### ISSUE THREAD

**Issue by kev4cards** [gonetz/GLideN64#2157]
There are glowing green dots (in sync with "press start") on the start menu of Mario Tennis. The problem has existed since Public Release 1.0 (maybe earlier) for both HLE and LLE. Everything looks fine in angrylion-plus r8.

![GLideN64_MarioTennis_001](https://user-images.githubusercontent.com/21962903/71133090-80b86c80-21c7-11ea-9318-739f16d62615.png)

**Comment by IronYoshi64** [comment]
Yeah I have those too, as well as there is a few other garbage pixels in various areas and some other menus. Here is more screenshots of the garbage pixels.
Bottom left corner of N64 logo title screen:
![GLideN64_MarioTennis_001](https://user-images.githubusercontent.com/57850880/71145150-22e74d00-21e6-11ea-8098-06219b156d91.png)
Exhibition pause screen:
![GLideN64_MarioTennis_000](https://user-images.githubusercontent.com/57850880/71145199-588c3600-21e6-11ea-8bca-d0a13ad3c7b1.png)
Thin black line under the Bob-ombs:
![GLideN64_MarioTennis_004](https://user-images.githubusercontent.com/57850880/71145273-a3a64900-21e6-11ea-8f3a-c3a284e752a6.png)
Red/pinkish outline of the text in Play Mode:
![GLideN64_MarioTennis_002](https://user-images.githubusercontent.com/57850880/71145345-e36d3080-21e6-11ea-93ac-e8e018afbc09.png)
I found out you can eliminate the above pictures issue if you have "Enable colored halos" option On (I do not know if having that on causes other issues right now):
![GLideN64_MarioTennis_003](https://user-images.githubusercontent.com/57850880/71145405-25967200-21e7-11ea-89b6-615780b885f1.png)

**Comment by kev4cards** [comment]
The pinkish outline does not appear in native resolution FWIW.

The black lines under the bob-ombs go away if you check the "copy auxiliary color to N64 memory" box under the frame buffer tab. However, the shadows of the players will become corrupted.

I haven't found anything that affects the garbage pixel lines or the two green dots above the zeroes on the start screen. I think the garbage pixel line is a regression (not sure, though).

**Comment by standard-two-simplex** [comment]
Issues in the first three pictures are due to degenerate rectangles. For example, the pause menu has rectangle with `ulx: 348.0, lrx: 604.0, uly: 36.0, lry: 36.0`, which has height `0`. I'm guessing the N64 rasterizer discards any generated span/scanline.

The issues are present in master due to `lry = max(lry, uly + 1.0f);` in `gDPTextureRectangle()` introduced in the old commit 048a1576fbfd189b0fbd6292eaa57b1e8620b6df.

Goldeneye has rects of height `0.75` which render correctly in native res even without that commit but incorrectly in non-native resolutions. 
```
x: 0.000000 - 439.750000, y: 16.000000 - 16.750000 
x: 0.000000 - 439.750000, y: 17.000000 - 17.750000 
```

Perhaps it is worth discarding any rectangles with height 0 or negative. Something like:
```
bool degenerate = lry - uly <= 0.0f || lrx - ulx <= 0.0;
...
if (!degenerate) 
  drawer.drawTexturedRect(params);
```

I'm not very sure about keeping `lry = max(lry, uly + 1.0f);`. It is ok for goldeneye and perhaps other similar situations, but might be creating some issues. Perphaps it's better making this game specific.

**Comment by kev4cards** [comment]
I tend to agree that `lry = max(lry, uly + 1.0f);` does not seem to be right. I need to review the patents and command summary related to the N64 RDP to see if there are any clues on how to better approach this. I've been busy with other matters as of late, so I haven't been able to playtest, check for regressions, and give myself a better understanding of the RDP as I would like.

**Comment by gonetz** [comment]
> The issues are present in master due to `lry = max(lry, uly + 1.0f);` in `gDPTextureRectangle()` introduced in the old commit [048a157](https://github.com/gonetz/GLideN64/commit/048a1576fbfd189b0fbd6292eaa57b1e8620b6df).

Thanks for finding that!
I replaced `lry = max(lry, uly + 1.0f);` by `lry = ceil(lry);` , 9561a586e
It fixes issues with zero-height rects and still works for Goldeneye .

**Comment by kev4cards** [comment]
Can confirm. The green dots and garbage pixel lines are gone. However, a new issue (HLE only) popped up between this commit and July 17th. The scoreboard names are displayed incorrectly, and the scoreboard and serve speed meter have brick framing on the normal fast court instead of the correct blue like the image above.

**Comment by gonetz** [comment]
> The scoreboard names are displayed incorrectly, and the scoreboard and serve speed meter have brick framing on the normal fast court instead of the correct blue like the image above.

Screenshot please. I don't see problems with scoreboard.

**Comment by standard-two-simplex** [comment]
I can't see issues either. Besides, Mario Tennis has no texrect call where `lry` has non-zero fractional part (at least ingame, where I tested).

**Comment by kev4cards** [comment]
I can't reproduce it anymore. I think it was probably a fluke. Cleared the shader cache to be sure. Sorry for the false alarm.
