### ISSUE TITLE
Project 64 Crashes if you open GlideN64 Video Settings when they are already open.

### ISSUE THREAD

**Issue by zmarotrix** [gonetz/GLideN64#2158]
If you already have the GLideN64 settings window open and you try opening it again, it crashes the whole emulator.

**Comment by IronYoshi64** [comment]
I can confirm that this does in fact Exits the entire emulator when you open the graphics settings when it is already open, although I think for most users, they wouldn't do that in the first place. IDK.

**Comment by Searinox** [comment]
In addition Project64 process hangs if the program's main window is closed while the GlideN64 window is still open. Both windows will close but the process will hang in the background. Still occurs even after this fix.

**Comment by gonetz** [comment]
The last problem is harder to fix. Plugin has no handles to force close opened dialog.

**Comment by Searinox** [comment]
The best solution to all these would be to just start the plugin window in a manner that blocks all other windows from the emulator. Every other plugin and dialog window from the emulator I've seen doesn't allow you to interact with the rest of the emulator while it's open.
