### ISSUE TITLE
Yoshi's Story wobbly/warping backgrounds and paths

### ISSUE THREAD

**Issue by IronYoshi64** [gonetz/GLideN64#2162]
Sadly this comment https://github.com/gonetz/GLideN64/commit/ed5e475acbbf2812b7073ee92d0e856d9984237d did successfully fix that issue, which is awesome, but now there is another small regression in Yoshi's Story due to it.

The backgrounds in all the levels and some pathways now have this weird wobbling/warping/blurry effect. It is hard to see the issue with pictures, so here is a 30 second .wmv video file (in a zip) I recorded showing what happens when using GLideN64-ed5e475a.

[yoshi story wobbling backgrounds video.zip](https://github.com/gonetz/GLideN64/files/4017477/yoshi.story.wobbling.backgrounds.video.zip)

**Comment by gonetz** [comment]
@IronYoshi64 I just noticed that commit 0d522ee was not merged to master. However, I don't see the problem with YS backgrounds using current master. Could you confirm that the issue is gone?

**Comment by IronYoshi64** [comment]
Yup it is fixed. Using the github-actions build 0dfd849 from Aug 30, 2021, no issues I can see anymore. Cool!

**Comment by IronYoshi64** [comment]
Closing this issue because it is no longer an issue. Thanks.
