### ISSUE TITLE
Incorrect Texture filtering in many games with "0d522ee9" build

### ISSUE THREAD

**Issue by IronYoshi64** [gonetz/GLideN64#2163]
This comment https://github.com/gonetz/GLideN64/commit/0d522ee9c3c3e9f562d61290256b75bc7f339cb6 yet again did fix that issue, but this build caused incorrect texture pixelating in several other games.

I notice in several games that use I believe texture mirroring and/or merging of certain textures, this caused some major incorrect pixelated spots in many games with that build.

Here are some pictures I captured with red arrows pointing to the wrong filtering areas in some games. I suggest viewing the pics in full screen to see the areas better.

SM64:
![SM64 - marked](https://user-images.githubusercontent.com/57850880/71745761-b8aee900-2e30-11ea-8499-0cad18d35249.png)
Paper Mario:
![PaperMario - marked](https://user-images.githubusercontent.com/57850880/71745807-dbd99880-2e30-11ea-9ead-73e45e12d83b.png)
Majora's Mask:
![ZeldaMM - marked](https://user-images.githubusercontent.com/57850880/71745819-e7c55a80-2e30-11ea-86f1-b45b7d97b504.png)

I have a feeling this is an issue in several other games, not just what I have here.

**Comment by gonetz** [comment]
Thanks for testing! I'll check these problems.

**Comment by gonetz** [comment]
I can't find a good solution yet, so I reverted my fixes for #2155 and reopened it.

**Comment by IronYoshi64** [comment]
@gonetz No problem! I test lots of things almost every time a new build comes out for this plugin and for PJ64 dev builds. I kind of felt like a jerk posting this issue cause I know you work so hard to fix these issues, in yet, sometimes those fixes cause other issues in unexpected ways. Anyways, if you ever need more help testing various things, let me know, I would be more than happy to help in any way I can!

**Comment by gonetz** [comment]
@IronYoshi64 your reports are very helpful, thanks! I can't test everything myself, and often regressions discovered months and even years after modification was made.
