### ISSUE TITLE
Pilotwings 64 Missing Snow Effect

### ISSUE THREAD

**Issue by mmarino4** [gonetz/GLideN64#2165]
Levels with a snow effect do not display the snow layer.  

An example of a level with snow is Rocket Belt, Class B, Test 2 (More Rings).

Video of the level on original hardware:
https://www.youtube.com/watch?v=1HmclM7t86k

**Comment by gonetz** [comment]
Please give me a savestate to test.

**Comment by mmarino4** [comment]
Here you go. If I did this correctly, one is on the level to select and one is in level. 

-----Original Message-----

**Comment by gonetz** [comment]
The snow is rendered by CPU. 
It should be emulated with FBInfo enabled, but it does not, at least  with my version of mupen64plus.
Another way is to set EnableCopyColorToRDRAM to 0 and  EnableCopyColorFromRDRAM to 1. It helps.

**Comment by mmarino4** [comment]
Thank you for the info. It actually works with just FBInfo enabled on my version as well as the EnableCopyColor settings.

**Comment by gonetz** [comment]
Can we close this issue then?

**Comment by mmarino4** [comment]
Yes. Thanks again.
