### ISSUE TITLE
HVQM homebrew fails

### ISSUE THREAD

**Issue by CrashOveride95** [gonetz/GLideN64#2167]
HVQM homebrew tests I've made don't seem to work properly on GLideN64. I've tested on both Mupen64Plus and Project64, and both seem to loop in ```_ProcessDList```
```0x00000058: CMD=0x00 W0=0x00000000 W1=0x00000000
0x00000060: CMD=0x00 W0=0x00000000 W1=0x00000000
0x00000068: CMD=0x00 W0=0x00000000 W1=0x00000000
0x00000070: CMD=0x00 W0=0x00000000 W1=0x00000000
0x00000078: CMD=0x00 W0=0x00000000 W1=0x00000000
0x00000080: CMD=0x3C W0=0x3C1A8003 W1=0x275A4FC0
0x00000088: CMD=0x03 W0=0x03400008 W1=0x00000000
0x00000090: CMD=0x00 W0=0x00000000 W1=0x00000000
0x00000098: CMD=0x00 W0=0x00000000 W1=0x00000000
0x000000A0: CMD=0x00 W0=0x00000000 W1=0x00000000
0x000000A8: CMD=0x00 W0=0x00000000 W1=0x00000000
0x000000B0: CMD=0x00 W0=0x00000000 W1=0x00000000
0x000000B8: CMD=0x00 W0=0x00000000 W1=0x00000000
0x000000C0: CMD=0x00 W0=0x00000000 W1=0x3C0BA460
0x000000C8: CMD=0x8D W0=0x8D6B0010 W1=0x316B0001
0x000000D0: CMD=0x15 W0=0x1560FFE0 W1=0x00000000
0x000000D8: CMD=0x3C W0=0x3C0BB000 W1=0x8D640008
0x000000E0: CMD=0x02 W0=0x02C02825 W1=0x3C015D58
0x000000E8: CMD=0x34 W0=0x34218B65 W1=0x00A10019
0x000000F0: CMD=0x27 W0=0x27BDFFE0 W1=0xAFBF001C
0x000000F8: CMD=0xAF W0=0xAFB00014 W1=0x3C1F0010
0x00000100: CMD=0x3C W0=0x3C1A8003 W1=0x275A4FC0
0x00000108: CMD=0x03 W0=0x03400008 W1=0x00000000
0x00000110: CMD=0x00 W0=0x00001012 W1=0x24420001
0x00000118: CMD=0x00 W0=0x00403825 W1=0x00405025
0x00000120: CMD=0x00 W0=0x00405825 W1=0x00408025
0x00000128: CMD=0x00 W0=0x00403025 W1=0x00406025
0x00000130: CMD=0x8D W0=0x8D220000 W1=0x00E21821
0x00000138: CMD=0x00 W0=0x0067082B W1=0x10200002
0x00000140: CMD=0x00 W0=0x00602825 W1=0x254A0001
0x00000148: CMD=0x30 W0=0x3043001F W1=0x01A37823
0x00000150: CMD=0x01 W0=0x01E2C006 W1=0x00627004
0x00000158: CMD=0x01 W0=0x01D82025 W1=0x00C2082B
0x00000160: CMD=0x00 W0=0x00A03825 W1=0x01625826
0x00000168: CMD=0x10 W0=0x10200004 W1=0x02048021
0x00000170: CMD=0x00 W0=0x00E2C826 W1=0x10000002
0x00000178: CMD=0x03 W0=0x03263026 W1=0x00C43026
0x00000180: CMD=0x3C W0=0x3C1A8003 W1=0x275A4FC0
0x00000188: CMD=0x03 W0=0x03400008 W1=0x00000000
0x00000190: CMD=0x01 W0=0x01EC6021 W1=0x00EA7026
0x00000198: CMD=0x01 W0=0x01CB3826 W1=0x0206C026
0x000001A0: CMD=0x03 W0=0x030C8026 W1=0x3C0BB000 
```

If anyone wants to try for themselves here is the ROM: https://cdn.discordapp.com/attachments/274693924638162944/669881771482939392/nuboom240.n64
 When the ROM starts up, press Start to start the video.

**Comment by StenApp** [comment]
https://github.com/gonetz/GLideN64/issues/663

**Comment by CrashOveride95** [comment]
> Sergey and I agreed on not implementing the ucode in GlideN64. Let's hope we can find an easy way to fix the issue in the RSP.

¯\_(ツ)_/¯

**Comment by StenApp** [comment]
I don‘t know if that‘s the origin of your problem but to me it is not fixed yet 🙁

**Comment by Narann** [comment]
It has been merge in upstream, if anyone want to test.

**Comment by m4xw** [comment]
@Narann Still freezes here, Pokemon and Yakouchuu work.
I poked Gillou about it.

**Comment by Narann** [comment]
Does it work on original hardware?

**Comment by m4xw** [comment]
@Narann I am told as much, this specific issue is caused by the ucode detection tho, see https://github.com/mupen64plus/mupen64plus-rsp-hle/pull/69#issuecomment-581877592

**Comment by CrashOveride95** [comment]
> Does this homebrew works on original hardware?

Yes it does, [proof](https://files.catbox.moe/dgg2y9.mp4)

**Comment by gonetz** [comment]
> this specific issue is caused by the ucode detection

But then you agreed that since GLideN64 already has the ucode detection, it simpler to move this ucode implementation to GlideN64, right? I don't mind. @Gillou68310 - will you port HVQM ucode to GLideN64?
Also I missed what is RE2 ucode? Is it modification of HVQM? And how it will work? Currently RE2 video decoded by RSP (or CPU?), graphics plugin just displays the ready frame buffers from RDRAM.

**Comment by LegendOfDragoon** [comment]
>it simpler to move this ucode implementation to GlideN64, right?

It makes a lot more sense to move the ucode to GLideN64, if it's a graphics task.

>Currently RE2 video decoded by RSP (or CPU?),

Currently in Project64's and cxd4's RSP, it basically forces LLE for the video scenes, even though its a graphics task.

**Comment by gonetz** [comment]
> It makes a lot more sense to move the ucode to GLideN64, if it's a graphics task.

There was a long discussion in https://github.com/mupen64plus/mupen64plus-core/issues/546
is this a graphics task or RSP one. A strong argument by bsmiles32 : "I would also strongly suggest implementing this ucode in the rsp-hle plugin as it will benefit all video plugins at once and it is more "logical" in the sense that it makes rsp-hle/rsp-cxd4 interchangeable." As I understand, this ucode already implemented in rsp-hle, and the main reason to port it to GLideN64 is a problem with ucode detection and thus necessity to use clumsy ucode-detection algorithm already implemented in GLideN64.

**Comment by StenApp** [comment]
Why is the ucode detection in the graphics plugin, shouldn‘t that be the work of the core?

**Comment by loganmc10** [comment]
This seems to work fine in the latest build of mupen64plus, you can test here:

https://github.com/loganmc10/m64p/releases/tag/Feb2520

**Comment by gonetz** [comment]
The situation with HVQM is still unclear for me. What is expected from GLideN64 to fix that issue?

**Comment by m4xw** [comment]
@gonetz Sorry to keep you out of the loop.
Gillou ended up rewriting the ucode detection and dispatch logic https://github.com/mupen64plus/mupen64plus-rsp-hle/commit/25b83af2f4a7c4274ca6a132920e6aab3d8c12c4
However there are still some Issues compared to real hw (black tiles and other shenanigans).
IIRC these happen on ParallelRSP + AL too, even tho they behave slightly different.
It's been a while, so would need to check to tell you the current behavior.
I think this specific Issue can be closed for now and if the other issues turn out to be GLideN, we can open another.

**Comment by gonetz** [comment]
@m4xw ok, thanks.
