### ISSUE TITLE
Quake 2 see through walls

### ISSUE THREAD

**Issue by Tasosgemah** [gonetz/GLideN64#2174]
I get this glitch with both the standalone GlideN64 and in RetroArch

![Quake II (USA)-200209-054833](https://user-images.githubusercontent.com/12124465/74095938-b65f3f00-4b00-11ea-986e-1f5d054cdcf4.png)

Doesn't seem to affect a much older version of the plugin.

**Comment by gonetz** [comment]
I see no issues with my Q2 saves. Do you have a savestate to check?

**Comment by Tasosgemah** [comment]
I didn't play much, that picture is from the the very first level. In the room after the elevator. Should take half a minute to reach.

**Comment by quicksilver7837** [comment]
My raspberry pi3 (gles2) has the same issue but my PI4 (which is gles3) doesn't have this issue. What hardware are you using?

**Comment by Tasosgemah** [comment]
Α Desktop PC with i5 4670 and GTX 1060.

I noticed that the issue occurs in the current Mupen64plus-Next but if i use an ancient Muprn64plus core (the one before the Next came along), the issue is no longer there. That old core uses an old version of GlideN64 from 3 or 4 years ago. So this has to be a regression,

**Comment by gonetz** [comment]
I can't reproduce that issue. Current master:
![GLideN64_QUAKE_II_000](https://user-images.githubusercontent.com/8983092/76138276-dee34600-6078-11ea-9ecb-f65d13051ada.jpg)

**Comment by fzurita** [comment]
I have one user complaining of this, so it's still an issue. It could be related to a setting.

**Comment by fzurita** [comment]
Anyone have a save state?

**Comment by Tasosgemah** [comment]
> Anyone have a save state?

Im away from my gaming PC but this happens in the very first map, in the room after the elevator.

**Comment by fanofandroidemulation** [comment]
I have the same problem
![Screenshot_2023-08-04-23-34-41-165_com retroarch aarch64](https://github.com/gonetz/GLideN64/assets/132107233/1d30a625-f002-47e1-923d-875af3114521)
