### ISSUE TITLE
Invisible racers in episode one pod racer on pi 4

### ISSUE THREAD

**Issue by quicksilver7837** [gonetz/GLideN64#2176]
The pod racers are invisible or have some type of clipping issue on the raspberry pi 4. I'm using the latest glES 3.1 mesa drivers.

https://github.com/gonetz/GLideN64/pull/1747

The above merged pull request seems to imply that this issue should be solved for gles3 capable devices but I'm still experiencing this issue. Unless of course fragment shader depth write is not available on all gles3 devices?

**Comment by loganmc10** [comment]
If my memory serves me right, the extension ```GL_NV_shader_noperspective_interpolation``` is required for that to work properly:

https://github.com/gonetz/GLideN64/pull/1783

Despite the name of the extension, it's not just supported by Nvidia, many Adreno GPUs support the extension as well, but probably not the Raspberry Pi

**Comment by quicksilver7837** [comment]
While not the answer I was hoping for, I do appreciate you looking into it. I will go ahead and close the issue.

**Comment by dankcushions** [comment]
https://www.khronos.org/registry/OpenGL/extensions/NV/NV_shader_noperspective_interpolation.txt

looks like it's part of GLES 3.1. pi4 is GLES 3.1 compliant, but you will need mesa 19.3, which i'm not sure is available via apt-get/whatever yet.

**Comment by loganmc10** [comment]
No it's not part of GLES3.1, it was "written against" 3.1, meaning an extension of 3.1, but it's not part of the standard

**Comment by dankcushions** [comment]
oh :( given that the pi 4 MESA drivers are under active development, support MIGHT be something we could request. there is a mesa development mailing list: https://lists.freedesktop.org/mailman/listinfo/mesa-dev, if anyone wants to follow this up.

**Comment by quicksilver7837** [comment]
I would be happy to do that but I'm not quite sure what/how I should be asking for.

**Comment by loganmc10** [comment]
Just as an FYI, there is a website that shows you what extensions are supported by what Mesa drivers:

https://mesamatrix.net/

Scroll down for OpenGL ES. I don't see the Raspberry Pi/Videocore on that website though, maybe it needs to be added. I also don't see GL_NV_shader_noperspective_interpolation on the list, which probably means it's not currently supported by any Mesa drivers
