### ISSUE TITLE
Incorrect text rendering in Japanese version of Super Mario 64

### ISSUE THREAD

**Issue by ToruTheRedFox** [gonetz/GLideN64#2178]
Here's a comparison between GLideN64 and Angrylion RDP Plus
![image](https://user-images.githubusercontent.com/15708278/74653796-d0dc8c80-5180-11ea-9b85-127b3e521490.png)

**Comment by oddMLan** [comment]
Nice catch.

**Comment by standard-two-simplex** [comment]
@ToruTheRedFox Fixed in master?

**Comment by ToruTheRedFox** [comment]
yes
![image](https://user-images.githubusercontent.com/15708278/97308744-1c3f5280-1859-11eb-92de-0b128b5ed583.png)
![Uploading image.png…]()

**Comment by ToruTheRedFox** [comment]
yes
![image](https://user-images.githubusercontent.com/15708278/97308798-2d885f00-1859-11eb-80b9-9846407ca11d.png)

**Comment by ToruTheRedFox** [comment]
figured I probably should close this since it's fixed now
