### ISSUE TITLE
GLideNUI warning

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#2185]
I see this warning from GLideNUI now:
```
QMetaObject::connectSlotsByName: No matching signal for on_n64DepthCompareCheckBox_toggled(bool)
```

I think it probably started with this commit: https://github.com/gonetz/GLideN64/commit/0692abea4aa4ed33b7cd3e7def1f24560e513bcd

**Comment by StenApp** [comment]
It changed to 

> n64DepthCompareComboBox
