### ISSUE TITLE
Make the shader storage folder obey m64p's ConfigDirPath

### ISSUE THREAD

**Issue by cascardian** [gonetz/GLideN64#2186]
This is basically what's needed to be able to make m64p fully portable. Right now, on Windows at least, it saves to %AppData% regardless of setting. I don't know if this is an issue anywhere else.

On the PJ64 side, it saves to the plugin path.

**Comment by loganmc10** [comment]
Shaders are not portable. They are binary files that are specific to the graphics card and driver on your machine. It doesn't make sense to make them portable

**Comment by loganmc10** [comment]
GlideN64 stores shaders in the Cache path (defined by ConfigGetUserCachePath), not the config path, since they aren't configuration files.

**Comment by cascardian** [comment]
I see, yes. This _is_ handled correctly on GLideN64's side and, from what I can tell, mupen simply doesn't expose this as a configurable option to the user. Exposing it on GLideN64's side also seems pretty pointless for the work involved, unlike txPath etc. That means this issue is not really relevant to this repository. Thanks!
