### ISSUE TITLE
Unknown memory action on Magical Tetris Challenge

### ISSUE THREAD

**Issue by Trimint123** [gonetz/GLideN64#2192]
Emulation stop on Project64. It was happened when beating the stage and the game tries to show the result score. I test the same situation with other plugin and it work perfectly fine.
![Untitled](https://user-images.githubusercontent.com/25479107/77217185-12cb6a80-6b53-11ea-8944-f7424b555659.png)

**Comment by olivieryuyu** [comment]
@gonetz 

bug confirmed

It is an HLE one, both occuring with one piece or strip.

**Comment by olivieryuyu** [comment]
[Magical Tetris Challenge (U).pj.zip](https://github.com/gonetz/GLideN64/files/4460123/Magical.Tetris.Challenge.U.pj.zip)

**Comment by Trimint123** [comment]
Alright, thank you very much.

**Comment by olivieryuyu** [comment]
can u reopen it? it is a valid bug!

**Comment by Trimint123** [comment]
My bad.

**Comment by loganmc10** [comment]
Confirmed on mupen64plus as well, it crashes on this line:

https://github.com/gonetz/GLideN64/blob/master/src/uCodes/S2DEX.cpp#L750

With a floating point exception

**Comment by gonetz** [comment]
> Probably needs a fix similar to this: af63737#diff-cf35bb98f0dbe7ed6b602e2e82764320

Yes, it helps, thanks!
