### ISSUE TITLE
The legend of zelda: majora's mask textures issue

### ISSUE THREAD

**Issue by Elvergazo64** [gonetz/GLideN64#2194]
i'm using public realease 4.0, i haven't done anything with the configuration, i just loaded majora's mask and this happens:
![GLideN64_ZELDA_MAJORA'S_MASK_000](https://user-images.githubusercontent.com/62580516/77381455-8b911900-6d43-11ea-8500-a19617956299.png)
![GLideN64_ZELDA_MAJORA'S_MASK_002](https://user-images.githubusercontent.com/62580516/77381463-9481ea80-6d43-11ea-881c-59a2be60a6b2.png)
![GLideN64_ZELDA_MAJORA'S_MASK_004](https://user-images.githubusercontent.com/62580516/77381466-98157180-6d43-11ea-9951-aecb9bb77e64.png)
![GLideN64_ZELDA_MAJORA'S_MASK_005](https://user-images.githubusercontent.com/62580516/77381475-9ba8f880-6d43-11ea-8119-2190b461e04c.png)
![GLideN64_ZELDA_MAJORA'S_MASK_006](https://user-images.githubusercontent.com/62580516/77381485-9e0b5280-6d43-11ea-8a51-cd50561af20a.png)
![GLideN64_ZELDA_MAJORA'S_MASK_007](https://user-images.githubusercontent.com/62580516/77381491-a06dac80-6d43-11ea-8570-a2bbfa67f99a.png)
![GLideN64_ZELDA_MAJORA'S_MASK_000](https://user-images.githubusercontent.com/62580516/77382607-6baf2480-6d46-11ea-9010-0870aea6a5c9.png)
![GLideN64_ZELDA_MAJORA'S_MASK_001](https://user-images.githubusercontent.com/62580516/77464498-e28f0080-6dcc-11ea-8b8d-6df70d0c8a8c.png)
![GLideN64_ZELDA_MAJORA'S_MASK_003](https://user-images.githubusercontent.com/62580516/77464641-1cf89d80-6dcd-11ea-9668-e226cd60f49e.png)
![GLideN64_ZELDA_MAJORA'S_MASK_004](https://user-images.githubusercontent.com/62580516/77465279-fe46d680-6dcd-11ea-8073-b6908dc3cc0a.png)

**Comment by IronYoshi64** [comment]
That may be either a depth buffer issue for you, or maybe your cache/shader files for the game is corrupted. What emulator are you using and the version of it?

**Comment by Elvergazo64** [comment]
> That may be either a depth buffer issue for you, or maybe your cache/shader files for the game is corrupted. I not fully sure though. What emulator are you using and the version of it?

I´m using project 64 version 2.3.2.202

**Comment by IronYoshi64** [comment]
You may want to get the latest Dev build of PJ64 from here: https://www.pj64-emu.com/nightly-builds
You can also get the latest stable Dev build of GLideN64 here: https://ci.appveyor.com/project/gonetz/gliden64/build/artifacts
Also can you let us know what is your computer specs/hardware, etc?

**Comment by Elvergazo64** [comment]
> hardware,

I used the 2 links you provided me but the problem still happens
also this is my pc specs:
![image](https://user-images.githubusercontent.com/62580516/77384801-ecbcea80-6d4b-11ea-8929-a79a8349e91b.png)

**Comment by gonetz** [comment]
Probably some shaders compiled with errors. Please find **gliden64.log** file in Project64\Plugin\GFX folder. If this file created, please open it in a text editor and look for error messages.

**Comment by Yui12** [comment]
It looks like a driver issue. I don't have this problem on my end. Wonder if it is an issue with your graphics driver. If it is, maybe updating it will fix it.
