### ISSUE TITLE
FlappyBird HUD elements not displayed

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#2197]
FlappyBird is a homebrew ROM that runs on an actual N64:

[FlappyBird.zip](https://github.com/gonetz/GLideN64/files/4406749/FlappyBird.zip)

Here is how it looks in Angrylion:
![Screenshot from 2020-03-30 22-26-49](https://user-images.githubusercontent.com/848146/77987036-f27b7880-72d5-11ea-8796-bd82dde01f4d.png)

Here is how it looks in GLideN64:
![Screenshot from 2020-03-30 22-28-05](https://user-images.githubusercontent.com/848146/77987044-fc04e080-72d5-11ea-9967-3123995ffbbc.png)

This game doesn't use the RSP at all (you can run it without an RSP plugin). It does however call ProcessRDPList from the CPU/emulator, it didn't show anything until 3f55f30ea2feab4f9d561aa977aa8d1a67bf2ee5

On mupen64plus, you need to run this game with the Pure Interpereter (R4300Emulator=0). I'm not sure if it boots in Project64, I would suspect not.

I tried various FB Emulation options, as well as the new_lle branch, no luck

**Comment by loganmc10** [comment]
@gonetz , commenting out these lines:
https://github.com/gonetz/GLideN64/blob/master/src/BufferCopy/RDRAMtoColorBuffer.cpp#L305-L306

Fixes the issue, it's unclear to me if that is some kind of optimization? Or is it to make sure data isn't overwritten when it shouldn't be?

**Comment by gonetz** [comment]
These lines were added in b085593d2a
I suppose, you need to check Dr.Mario for regressions.
