### ISSUE TITLE
Remapping hotkeys

### ISSUE THREAD

**Issue by anonymous7002** [gonetz/GLideN64#2198]
When I use GlideN64 v4.0 on Mupen64, it works fine, but one thing is annoying.
I have mapped the camera inputs to WASD, and when I press D, texture dump is toggled.
I want to be able to remap hotkeys.

**Comment by gonetz** [comment]
Why not just disable texture dump? It is optional.

**Comment by anonymous7002** [comment]
Toggle means switching between two states.
I want to be able to remap hotkeys. That's what I'm talking about

**Comment by anonymous7002** [comment]
Yes, but it would still be nice to have an ability to remap hotkeys so your usual game keyboard controls don't overlap with hotkeys.

**Comment by gonetz** [comment]
Ok. Then this task is related to more general one #1497

**Comment by gonetz** [comment]
Done. Check #1497
