### ISSUE TITLE
Cruis'n world gauge texture not updating

### ISSUE THREAD

**Issue by standard-two-simplex** [gonetz/GLideN64#2199]
Commit 85a8635952db2e3ca558a90b3b52c3f4be02c92d seems to be breaking the gauge, at least on my end. It is being updated only when it reaches the middle and near the top part.

It shows one of this 4 all the time
<img src="https://user-images.githubusercontent.com/12202580/78430717-3aebbb00-7675-11ea-8102-9c316467ada3.png" width="320px">
<img src="https://user-images.githubusercontent.com/12202580/78430693-39ba8e00-7675-11ea-8160-e54ddd0264cd.png" width=320px>
<img src="https://user-images.githubusercontent.com/12202580/78430704-3a532480-7675-11ea-905f-34323181d299.png" width="320px">
<img src="https://user-images.githubusercontent.com/12202580/78430713-3aebbb00-7675-11ea-98b7-a5d7d0d57da9.png" width="320px">

**Comment by loganmc10** [comment]
Thanks I'll take a look today

**Comment by loganmc10** [comment]
It doesn't appear to be a problem with the XXH3 algorithm itself, the problem also exists with CRC32, but you are correct that it was introduced in that commit
