### ISSUE TITLE
Level of Detail value

### ISSUE THREAD

**Issue by standard-two-simplex** [gonetz/GLideN64#2203]
While I was working with shaders I noticed that the level of detail calculation is different from the standard one that OpenGL uses.

Currently, master runs code equivalent to 
```
"  mediump vec2 dx = abs(dFdx(vLodTexCoord)) * uScreenScale;	\n"
// "  mediump vec2 dy = abs(dFdy(vLodTexCoord)) * uScreenScale;	\n"
"  mediump float lod = max(dx.x,dx.y);				\n" /*CURRENT MASTER*/
// "  mediump float lod = max(dx.x + dx.y, dy.x + dy.y);	\n" /*LINEAR*/
// "  mediump float lod = sqrt(max(dot(dx,dx),dot(dy,dy)));	\n" /*QUADRATIC*/
```
which doesn't use derivation by `y`. OpenGL [suggests](https://www.khronos.org/registry/OpenGL/specs/gl/glspec42.core.pdf#subsection.3.9.11) the quadratic formula above. I checked angrylion's sources (function `tclod_4x17_to_15()`) and it seems he is performing a linear approximation of the quadratic approach.

I saw that in the past something similar to the linear equation was being used, but I haven't found the commit (nor the reason) why it was removed. Is there any reason for it?

I tested different options and this are the results. 
<table>
  <tr>
  <td>
<img src="https://user-images.githubusercontent.com/12202580/78716383-1c105180-791f-11ea-8e22-62a8621959c3.png" width="320px">
</td><td>
<img src="https://user-images.githubusercontent.com/12202580/78716389-1e72ab80-791f-11ea-9aef-c50e6793ba60.png" width="320px">
</td> 
 </tr>
 <tr>
  <td>Angrylion</td><td>Linear</td> 
 </tr>
 <tr>
  <td>
<img src="https://user-images.githubusercontent.com/12202580/78716396-20d50580-791f-11ea-9683-12abcde35fe2.png" width="320px">
</td><td>
<img src="https://user-images.githubusercontent.com/12202580/78716414-26cae680-791f-11ea-91c4-2da97a78328a.png" width=320px>
</td> 
 </tr>
 <tr>
  <td>Quadratic</td><td>Current master</td> 
 </tr>
</table>

LoD is smaller in master so the most detailed texture is used more easily. I propose using linear above, which is most similar to the code in angrylion's software plugin.

**Comment by gonetz** [comment]
Initially I used the following code for lod:
```
"  mediump vec2 dx = dFdx(vLodTexCoord);				\n"
 "  dx *= uScreenScale;									\n"
"  mediump vec2 dy = dFdy(vLodTexCoord);				\n"
"  dy *= uScreenScale;									\n"
"  mediump float lod = max(length(dx), length(dy));		\n"
```
It is not exactly the linear equation, since 
length returns the length of the vector, i.e. `sqrt(x[0]^2+x[1]^2+…)`
It had issues, and I replaced it with the current code in 2199dd42904
It refers issue #571

> I propose using linear above, which is most similar to the code in angrylion's software plugin.

Done in a73da69e1. I checked issue #571, no regression here.

**Comment by standard-two-simplex** [comment]
Cool! I close the issue.
