### ISSUE TITLE
unoptimized render 2d elements at N64 res bugs

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#2204]
BATTLEZONE intro

![GLideN64_BATTLEZONE_007](https://user-images.githubusercontent.com/8987490/78799898-123c2c00-79bb-11ea-8c23-10126b1a792e.png)

Carmageddon: missing O

![GLideN64_CARMAGEDDON64_001](https://user-images.githubusercontent.com/8987490/78800017-3b5cbc80-79bb-11ea-84a9-c8dce3c44bad.png)

**Comment by gonetz** [comment]
Does it work correctly in "optimized" mode? Unoptimized does not mean more compatible or more correct.

**Comment by olivieryuyu** [comment]
optimized works but not unoptimized

**Comment by gonetz** [comment]
Optimized mode if proffered. I left unoptimized one just for a special case.

**Comment by olivieryuyu** [comment]
then the optimized case should be a mere "hack" no, not an actual option :)

**Comment by gonetz** [comment]
Unfortunately, both modes are rather hacks.

**Comment by olivieryuyu** [comment]
right but one is buggy. Nearly all game i use with the unoptimized option has issues. Which case does it help?

**Comment by gonetz** [comment]
Commit bc05d5f0d8:
Make optimization implemented in e0418c3c342c6 as optional.
S. F. Rush looks much better without the optimization.
Fixed #2068 S. F. Rush and Rush 2 - Regressions

**Comment by olivieryuyu** [comment]
I see :)

it is quite game specific but fine
