### ISSUE TITLE
Goldeneye multiple issues after build of April 7th

### ISSUE THREAD

**Issue by LuismaSP89** [gonetz/GLideN64#2206]
Some issues are happening after the changes made in april 7th:

* Always use clip ratio 1 for rects and screen-space triangles.
* Revert "Set clip ratio to 1 in TexrectDrawer."
* Set default clip ratio to
* Set clip ratio to 1 in TexrectDrawer.
* Update viewport on clip ratio change.
* Set gSP.clipRatio default value to 1 for all ucodes but Rej ones, where it is 2.
* Magnify clipping space by ClipRatio.
* Change type for BlueNoiseItem fields from char to signed char.

-The issues can be seen on goldeneye for example there are a zoom-in gameplay, "you can see it on your current weapon" and some texture errors such as transparency glitches and many others "Images attached"

Using a build from 6th of april doesn't have this problems.

My specs:

Windows 10x64
GTX 970
16GB DDR3
i7 4790k

![2](https://user-images.githubusercontent.com/12205048/78940289-e3ef4700-7ab5-11ea-9a5c-e740bf3cc559.jpg)
![1](https://user-images.githubusercontent.com/12205048/78940295-e5b90a80-7ab5-11ea-9efd-8466d42b8993.jpg)

**Comment by standard-two-simplex** [comment]
I can't reproduce. Try deleting shader cache.

**Comment by LuismaSP89** [comment]
Solved by deleting the shader cache. But maybe the plugin in the future should delete the shader cache by itself between versions to avoid problems like this. 
Closing.

**Comment by gonetz** [comment]
> But maybe the plugin in the future should delete the shader cache by itself between versions to avoid problems like this.

Plugin rebuilds shader cache when shader cache version changes. It always happens between public releases, but during development we often forget to up shader cache version. Thus it is common advice to clear/disable shader cache.
