### ISSUE TITLE
quake 2 reflections broken

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#2207]
![GLideN64_QUAKE_II_005](https://user-images.githubusercontent.com/8987490/78947238-1d7b7e80-7ac5-11ea-8d36-954fd1cdeb01.png)

**Comment by loganmc10** [comment]
Could it be your shader cache? It looks pretty normal to me

![quake_ii-000](https://user-images.githubusercontent.com/848146/79060562-c223ca80-7c43-11ea-9062-c0c312ad17f0.png)

**Comment by loganmc10** [comment]
Here is another angle, I haven't really played this game before so I can't say it looks correct, but it looks good to me:

![quake_ii-001](https://user-images.githubusercontent.com/848146/79060580-1038ce00-7c44-11ea-8f67-60a8a6b01e13.png)

**Comment by olivieryuyu** [comment]
tested with really last master.

there is clearly a bug

**Comment by olivieryuyu** [comment]
May it is a compilation of the zilmar build of the CI?

With LLE patreon3 it works perfectly.

I tested with plugin up to 5 months from CI, same bug

**Comment by gonetz** [comment]
> May it is a compilation of the zilmar build of the CI?

More exactly, it is problem with VS 17. If I build with VS 13 or VS 15 the reflection works correct.
Probably some bad floating point optimization.

**Comment by oddMLan** [comment]
With VS2019 the N logo in OOT is also broken in AMD. Disabling /GL (interprocedural optimization) fixes it. Might also help here? At a performance cost, I guess.

**Comment by mudlord** [comment]
Wouldn't surprise me. Even for non emulation related code of mine, **modern** MSVC makes broken code.
