### ISSUE TITLE
why this plugin needs a non GL sdl2 for utilizing GLES backend PI4 on x11

### ISSUE THREAD

**Issue by Askmewho** [gonetz/GLideN64#2209]
Hi!, while this plugin its the best in terms of compatibility and quality I have to preload tu much stuff to make it run on x11. doing just that for utilizing a different plugin seems ridiculous. There is any way to be able to foce gles instead on gl on my existing SDL2 gl enabled library and that way be able to create context??

**Comment by loganmc10** [comment]
This is all up to the mupen64plus frontend, not the video plugin. What frontend/software are you using to run mupen64plus/GLideN64?

**Comment by Askmewho** [comment]
I am running on mupen64plus-qt. But ive compiled mupen64 core again and forcing gles and... It doesn't work preloading again neither (my tests on this plugin on x11 were a lot time ago). I think there was a not pushed fix to this.. I will research the issue tracker.. overall, x11 support on this plugin for arm/gles it's quite a headache

**Comment by loganmc10** [comment]
We can chat about it on discord - https://discord.gg/8XRuJ4F - it will probably require some discussion, but all the GL context creation, x11, gles, etc is handled by the mupen64plus frontend, this plugin supports GLES, it's used white a bit on Android
