### ISSUE TITLE
Regression: Duplicate image in Dr. Mario

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#2211]
![dr mario_64-000](https://user-images.githubusercontent.com/848146/79379458-30a2aa00-7f1c-11ea-9951-a7f96a410710.png)

Appears to be caused by one of the Clip Ratio commits

**Comment by standard-two-simplex** [comment]
Could it be you're loading an older savestate? I can't reproduce.

**Comment by loganmc10** [comment]
No I'm not using a savesate, I tried on 2 different computers. Do the pills show up during the game for you?

The game should have copyFromRDRAM/Render N64 framebuffer to output enabled via GLideN64.custom.ini, this issue won't show up without that enabled

**Comment by standard-two-simplex** [comment]
I tend to have custom settings disabled to make sure I'm testing the settings I enable.

It seems every game is wrong with copyFromRDRAM. I will check.

**Comment by standard-two-simplex** [comment]
Commit a73da69e10423896fb0ecf003574ea3046e0fb53 creates the issue. I also notice it creates an issue in Indiana Jones and the infernal machine (some garbage in intro).

@gonetz I'm not sure how the valuekeeper works, but it seems from the picture that clipratio is 2 in the vertex shader and 1 in the viewport transform.

**Comment by gonetz** [comment]
> I'm not sure how the valuekeeper works

valuekeeper set gSP.clipRatio to 1 in its ctor and set it back to previous value in its destructor.  Right now I can't say how clipratio became different for the vertex shader and the viewport transform.
