### ISSUE TITLE
SM64 koopa's shorts are not correct in hle

### ISSUE THREAD

**Issue by Craftyawesome** [gonetz/GLideN64#2212]
HLE:
![hle](https://user-images.githubusercontent.com/19976035/79403169-22747e00-7f5c-11ea-95b2-736b07bb80cb.png)

LLE
![lle](https://user-images.githubusercontent.com/19976035/79403175-24d6d800-7f5c-11ea-90c9-e4009430b5ff.png)

Angrylion
![angrylion](https://user-images.githubusercontent.com/19976035/79403181-286a5f00-7f5c-11ea-99b6-3d8b0c24e9f5.png)

**Comment by IronYoshi64** [comment]
Wow. I play Super Mario 64 so much, how in the world have I never noticed this before?! Yeah, Koopa Troopa's underwear is suppose to be a purplish-pinkish color. I was wondering if this was ever not an issue in GLideN64's life. Turns out this issue has been a thing ever since GLideN64 started, versions 1.2, 2.0, 3.0, 4.0, and the newer dev builds too has been having this issue. I wonder what is causing the mis-coloration?

**Comment by Craftyawesome** [comment]
> Wow. I play Super Mario 64 so much, how in the world have I never noticed this before?! Yeah, Koopa Troopa's underwear is suppose to be a purplish-pinkish color. I was wondering if this was ever not an issue in GLideN64's life. Turns out this issue has been a thing ever since GLideN64 started, versions 1.2, 2.0, 3.0, 4.0, and the newer dev builds too has been having this issue. I wonder what is causing the mis-coloration?

It seems to have the same behavior with just about any plugin. Jabo and glide64 seem to break in hle and work (in this particular case) in lle

**Comment by gonetz** [comment]
savestate please

**Comment by gonetz** [comment]
Thanks. Could you make a savestate for PJ64?

**Comment by cascardian** [comment]
Sure. Here you go (newest build): 
[SM64 (USA) PJ64 savestates.zip](https://github.com/gonetz/GLideN64/files/4495424/SM64.USA.PJ64.savestates.zip)

**Comment by gonetz** [comment]
Thanks!
I checked all HLE plugins - all work the same here.
Almost all polygons for koopa, as well as for most of other models, use just shade (vertex) color. The shade color is the result of lighting calculation. Lighting works the same for almost all N64 games and implemented nearly the same in all HLE plugins. Color for polygons of koopa's shorts calculated with one ambient light and one directional light. It is very simple. I don't see, what can go wrong. Nevertheless, vertices in LLE mode do have different color. May be @olivieryuyu can check the lighting code for this ucode and find some discrepancy?

**Comment by olivieryuyu** [comment]
interesting :)

**Comment by olivieryuyu** [comment]
funny bug :)

I believe it is a bug in the progamming of the game itself, leading to unexpected results :)

**Comment by cascardian** [comment]
I'd just like to add that I've checked various recordings from real N64s online (mostly 120 star speedruns) and they all show the vertex coloration that you see in LLE/Angrylion.

A small sampling:
https://www.youtube.com/watch?v=iI8Giq7zQDk&t=1h1m32s
https://www.youtube.com/watch?v=LV7SsyTI4u4&t=23m36s
https://www.youtube.com/watch?v=rMUB8ZLqM-o&t=21m50s
https://www.youtube.com/watch?v=-2SeVglezl0&t=7m49s
https://www.youtube.com/watch?v=IjMEEPgFIkQ&t=21s

@olivieryuyu 
Shindou is the same:
[Super Mario 64 - Shindou Edition (J).pj.zip](https://github.com/gonetz/GLideN64/files/4530982/Super.Mario.64.-.Shindou.Edition.J.pj.zip)

HLE:
![sm64shindou-hle](https://user-images.githubusercontent.com/6861423/80248442-33b23e80-8670-11ea-8069-b7dd63504bce.png)

LLE:
![sm64shindou-lle](https://user-images.githubusercontent.com/6861423/80248459-3c0a7980-8670-11ea-9c5d-cd27f43fdcae.png)

Angrylion:
![sm64shindou-angrylion](https://user-images.githubusercontent.com/6861423/80248479-43ca1e00-8670-11ea-9af4-4814e90a57bd.png)

**Comment by olivieryuyu** [comment]
weird stuff, clearly breaking normal behavior of light, mostly like due a programmming bug of the game itself

**Comment by olivieryuyu** [comment]
@gonetz 

the code is doing weird thing in fixed point math when normalizing light direction.

**Comment by gonetz** [comment]
> mostly like due a programmming bug of the game itself

I found the source of that bug. It looks rather as deliberate trick, an intended violation of rules.

**Comment by weinerschnitzel** [comment]
Does this affect #2218?
