### ISSUE TITLE
Regression: Pokemon Snap detection broken in mupen64plus

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#2213]
Offending commit: https://github.com/gonetz/GLideN64/commit/41ecf66e80946ac920d8c226615227a9b3628ed5#diff-1adda28a6cd326396df18e27fb54ffb4

Camera no longer properly detects the Pidgeys at the start of the first level

**Comment by gonetz** [comment]
>Offending commit: 41ecf66

Dithering?!

**Comment by gizmo98** [comment]
@loganmc10 
Please test if setting framebuffer dithering = 0 fixes the problem.

**Comment by loganmc10** [comment]
Yes, setting "RDRAM image dithering" to disable, Bayer, or Magic Square works fine. It is just the Blue noise dithering that breaks it

**Comment by gizmo98** [comment]
Maybe blue noise dithering is to random for pokemon snap and this game does not find what it is searching for in framebuffer.
