### ISSUE TITLE
MSAA max not 16x in UI

### ISSUE THREAD

**Issue by retrobenny** [gonetz/GLideN64#2216]
I can set it manually in custom ini to 16x and it supposedly works but the UI only allows 8x as the highest setting.
Setting the custom ini to 16x also makes it show 16x in the UI despite the 8x issue.
Please look into fixing this so that it can be set via the UI instead of having to manually enter it into the custom ini.
I want to do comparisons of 16x to 8x so I can see what kind of differences I get visually,but that is not possible currently due to UI lacking access to 16x.

This is on GLideN64 rev.cb8c958f as depicted on PJ64's Plugins menu for me.

Edit; Upon testing with a snipping tool reference,I see that 16x further reduces "jaggies" beyond 8x while also in 4K upscale and doesn't even hurt performance that bad in the game tested,staying around 40% gpu usage on Nvidia GeForce RTX 2060 Super though hitting 52% on the 2D graphic pause menu.

**Comment by retrobenny** [comment]
What makes matters worse is that upon changing any other setting in UI such as internal resolution on a different tab,the MSAA setting reverts back down to 8x instead of staying on 16x meaning you have to close the emulator then edit the custom ini again to get it back to 16x.

This happened when I found that 9x is as close to my windowed size as possible,barely going over it.
Window being 2720x2040 to compensate for the taskbar with 2720 being an approximation to match the scale with 2040 which still partially overlaps vertically but is not that bad since the window can be moved a little to make up for it.
Turns out I get 100% GPU usage on 60fps Banjo-Tooie when at 12x and editing in 16x MSAA but 9x scale with 16x MSAA runs decent enough.
(really wish I had a 2080Ti or the upcoming Nvidia Ampere)

**Comment by oddMLan** [comment]
Apparently this is one way to do it:
https://stackoverflow.com/a/49918835/3529902

Assuming this works as well as it seems we'd get the real supported MSAA levels instead of hardcoding it up to 8x.

**Comment by gonetz** [comment]
The author of `wglChoosePixelFormatARB`  solution says : "there is no need to create fake contexts".
It is no so. `wglChoosePixelFormatARB` function is an extension. The only way to get it is via `wglGetProcAddress`.
To query WGL extensions, you must first create an OpenGL context and then make it current.
Moreover, if you close the context before you call `wglChoosePixelFormatARB` the result will be wrong.

So, OpenGL context is necessary to detect supported MSAA levels. OpenGL context creation is not a light function. It may take some time, up to a second. So, plugin's configuration dialog may open with an additional delay.

I implemented max supported MSAA level detection in detect_max_msaa branch. Actually it is not max possible level, I decided not to check levels above 16X and below 4X.

**Comment by retrobenny** [comment]
The UI part works for showing and selecting 16x MSAA for me now on both WTL and QT but trying to open graphics settings while a game is running immediately crashes PJ64.

Tested on 2.4.0-1394.

**Comment by gonetz** [comment]
Yes, release build crashes. I fixed it in 8690ae4ac7

**Comment by retrobenny** [comment]
I can confirm it is now working on my end and the 16x MSAA setting is sticking after making changes to adjust cropping,though I noticed an oddly appended 0 at the end of the tested game's settings in the custom settings ini file.
Just a random 0 on its own below all other applied settings with "Good_Name" just above it.

**Comment by Squall-Leonhart** [comment]
@gonetz 

Where Nvidia is concerned, GL_MAX_SAMPLE goes up to 32, with both the 16x and 32x methods being xS hybrid methods, I remember 16xS harming the detail of certain hd textures where 32xS doesn't, is there any reason for the restriction to 16x, or were you just unaware that nvidia translates msaa formats above 8x to hybrid techniques that can for better or worse affect the texturing system?
