### ISSUE TITLE
2 Homebrew games that work in LLE but not HLE

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#2217]
Puzzle Master 64
[pm64.zip](https://github.com/gonetz/GLideN64/files/4495490/pm64.zip)

Shuffle Puck 64
[shufflepuck64.zip](https://github.com/gonetz/GLideN64/files/4495493/shufflepuck64.zip)

```
Load microcode (RSP SW Version: 2.0G, 09-30-96) type: 0 crc: 0x9e7587df romname: Puzzle Master 64
Load microcode (RSP SW Version: 2.0G, 09-30-96) type: 0 crc: 0x9e7587df romname: Shufflepuck 64
```

Interestingly they both seem to report the same CRC and ucode, I tried forcing a few different ucodes, but couldn't get anything to display in HLE

**Comment by loganmc10** [comment]
I believe these games are supported, at least somewhat, in Rice:
https://github.com/mupen64plus/mupen64plus-video-rice/blob/master/src/RSP_Parser.cpp#L420-L426

It seems like maybe it is F3D with some additional commands?

**Comment by StenApp** [comment]
>     case 8: // Ucode 0 with Sprite2D, Puzzle Master 64
>         memcpy( &LoadedUcodeMap, &ucodeMap0, sizeof(UcodeMap));
>         LoadedUcodeMap[RSP_SPRITE2D_BASE] = RSP_GBI_Sprite2D_PuzzleMaster64;
>         LoadedUcodeMap[RSP_SPRITE2D_SCALEFLIP] = RSP_GBI1_Sprite2DScaleFlip;
>         LoadedUcodeMap[RSP_SPRITE2D_DRAW] = RSP_GBI0_Sprite2DDraw;
>         status.bUseModifiedUcodeMap = true;
>         break;

Looks like a task for @olivieryuyu as he is the ucode decoder king
