### ISSUE TITLE
Taz express: little bug

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#2218]
![an](https://user-images.githubusercontent.com/8987490/79775591-c67f7000-8334-11ea-80b2-9d49a9c967f9.jpg)

![GLideN64_Taz_Express_000](https://user-images.githubusercontent.com/8987490/79775607-cbdcba80-8334-11ea-9a9d-0fdeee30fe60.png)

The grey box is not correct with gliden64.

**Comment by gonetz** [comment]
A little but quite serious bug in texture load. Thanks for the report!
