### ISSUE TITLE
GLideN64 compatibility list

### ISSUE THREAD

**Issue by andrea-petrucci-1975** [gonetz/GLideN64#2225]
Has someone made a compatbility list for GLideN64 plug-in?

**Comment by gonetz** [comment]
Just put all games to the list and set status "playable"
[Issues](https://github.com/gonetz/GLideN64/issues) is the list of known issues.

Yes, it would be good to have a nice looking compatibility list. If you want to create some, you welcome. You may create it right here, in Wiki section.

**Comment by andrea-petrucci-1975** [comment]
created https://github.com/gonetz/GLideN64/wiki/Compatibility-List

**Comment by gonetz** [comment]
> PERFECT (400 - 100%)

It definitely needs corrections :)

**Comment by oddMLan** [comment]
I would put the 64DD games under "Playable"

**Comment by andrea-petrucci-1975** [comment]
> > PERFECT (400 - 100%)
> 
> It definitely needs corrections :)

sure! everyone can move games from PERFECT to other category

**Comment by andrea-petrucci-1975** [comment]
> > > PERFECT (400 - 100%)
> > 
> > 
> > It definitely needs corrections :)
> 
> sure! everyone can move games from PERFECT to other category

and would be great to add some info

EXAMPLE:

INTRO
- super mario 64
The game freeze after the screen with big Mario face
use this option in GLideN64 to pass over this screen:
- xyz
- zxy

**Comment by osaeed18** [comment]
I think a Google docs sheet would work very well as a N64 compatibility sheet. You can create a new sheet for N64 DD games too.

**Comment by gonetz** [comment]
Closed because of #2316
