### ISSUE TITLE
mupen64plus.cfg - Disable N64-style mip-mapping

### ISSUE THREAD

**Issue by GhostlyDark** [gonetz/GLideN64#2233]
Using Logan's old GUI (Dec 2018) or mupen64plus via command line, I am missing the option in mupen64plus.cfg to disable N64-style mip-mapping.

**Comment by loganmc10** [comment]
I see it:

![image](https://user-images.githubusercontent.com/848146/80528417-21c3ea80-8953-11ea-997c-1c5215a5a3e2.png)

You can download the latest version of m64p with the GLideN64 GUI here: https://m64p.github.io/

**Comment by GhostlyDark** [comment]
Using the new GUI misses the point. It won't fix the missing option for command line users.

**Comment by loganmc10** [comment]
It's there, I believe it is called ```bilinearMode``` (Bilinear filtering mode (0=N64 3point, 1=standard))

**Comment by loganmc10** [comment]
It's there, it is "EnableLOD"

**Comment by GhostlyDark** [comment]
That's probably it.
Thx! I would have bever guessed.
