### ISSUE TITLE
[Regression] SM64 Weird Shading on sand texture in Joly Roger Bay

### ISSUE THREAD

**Issue by IronYoshi64** [gonetz/GLideN64#2234]
Hey. I notice for SM64 a very strange lighting/shading issue on the sand textures for Joly Roger Bay. This issue is a random regression. Using default settings. Using latest dev build of GLideN64, it looks really bad. I already tried deleted all  my shader cache, still looks wrong.
Here are 2 screenshots I took to see what the issue looks like:
![GLideN64_SUPER_MARIO_64_000](https://user-images.githubusercontent.com/57850880/80552653-f100a700-898c-11ea-8bce-37abce7b8d96.png)
![GLideN64_SUPER_MARIO_64_001](https://user-images.githubusercontent.com/57850880/80552658-f52cc480-898c-11ea-9684-e872ff4a095e.png)

**Comment by gonetz** [comment]
Savestate please.

**Comment by IronYoshi64** [comment]
Sure. Here are 2 saved states for SM64 USA. One at the start of Joly Roger Bay, and one in the Ocean Cave:
[sm64 joly roger bay 1.pj.zip](https://github.com/gonetz/GLideN64/files/4551800/sm64.joly.roger.bay.1.pj.zip)
[sm64 joly roger bay 2.pj.zip](https://github.com/gonetz/GLideN64/files/4551803/sm64.joly.roger.bay.2.pj.zip)

**Comment by retrobenny** [comment]
I think I ran into this when testing the WTL version made for PJ64,only thing is I bumped into hot-pink fog when turning the camera on the slope in Bob-omb Battlefield near the wooden posts,another angle close up becomes an intense green and other colors on parts close to a culling point by viewing the slope too closely.

**Comment by gonetz** [comment]
> Sure. Here are 2 saved states for SM64 USA. One at the start of Joly Roger Bay, and one in the Ocean

Hmm. Another HLE issue with this game. It is correct with LLE.

**Comment by olivieryuyu** [comment]
:(

**Comment by gonetz** [comment]
The regression is caused by switching off the perspective correction for shade color in shaders.
With perspective correction enabled GLideN64 looks as wrong as other HLE plugins - that is not very noticeable. However, LLE looks perfect with perspective correction disabled. So, the problem is with shade color, that is with lighting calculation.

**Comment by IronYoshi64** [comment]
Wait, in other HLE plugins the sand is wrong as well? I never notice that, cause it looks perfect in them to me? So, is there a fix that can resolve this issue in HLE mode?

**Comment by standard-two-simplex** [comment]
It happens also in some other games/areas. It is specially noticeable when the objects are close to the camera.

Turok 3 deathmatch
![turok_3__shadow_of_o-000](https://user-images.githubusercontent.com/12202580/80810748-c0a34d80-8bc4-11ea-8dfd-37a04124c17b.png)

Mario 64 first area
![super_mario_64-000](https://user-images.githubusercontent.com/12202580/80810750-c13be400-8bc4-11ea-8bb4-5b9585060076.png)

**Comment by gonetz** [comment]
> Wait, in other HLE plugins the sand is wrong as well? I never notice that, cause it looks perfect in them to me?

It is hard to notice:
![SM64_sand](https://user-images.githubusercontent.com/8983092/80852942-eed16d80-8c56-11ea-9cfe-0b61de0da7c4.jpg)

**Comment by Craftyawesome** [comment]
It looks like HLE is still a bit off to me.
HLE
![HLE](https://user-images.githubusercontent.com/19976035/80916413-79cd6900-8d26-11ea-92e8-37bbb8ebec05.png)

LLE
![LLE](https://user-images.githubusercontent.com/19976035/80916414-7d60f000-8d26-11ea-83c7-b331314930c8.png)

Angrylion
![Angrylion](https://user-images.githubusercontent.com/19976035/80916416-805be080-8d26-11ea-8978-2f1380acfdd7.png)

State: 
[Super Mario 64 (U).pj.zip](https://github.com/gonetz/GLideN64/files/4570628/Super.Mario.64.U.pj.zip)

**Comment by IronYoshi64** [comment]
Yeah, I believe this fixed only half the issue sadly, but things still are not quite right. The issue still exists, but it seems like from very specific angles and/or when zoomed out or in enough with the camera. This issue needs to be reopened.
Here are some more screenshots from me, and more state saves:
![GLideN64_SUPER_MARIO_64_002](https://user-images.githubusercontent.com/57850880/80916756-51db0700-8d20-11ea-9b58-92ed6d851926.png)
![GLideN64_SUPER_MARIO_64_003](https://user-images.githubusercontent.com/57850880/80916761-56072480-8d20-11ea-81e7-8ff7cdd13cf4.png)
![GLideN64_SUPER_MARIO_64_004](https://user-images.githubusercontent.com/57850880/80916763-5b646f00-8d20-11ea-8273-edf4f8d900d3.png)
[sm64 bobombbattlefield.pj.zip](https://github.com/gonetz/GLideN64/files/4570690/sm64.bobombbattlefield.pj.zip)
[sm64 jollyrogerbay 01.pj.zip](https://github.com/gonetz/GLideN64/files/4570692/sm64.jollyrogerbay.01.pj.zip)
[sm64 jollyrogerbay 02.pj.zip](https://github.com/gonetz/GLideN64/files/4570693/sm64.jollyrogerbay.02.pj.zip)

**Comment by gonetz** [comment]
> It looks like HLE is still a bit off to me.

Yes, fog with HLE is slightly more dense than with LLE, but I don't know why. I have no idea how to fix it. Interesting, but in Zelda fog is the same for HLE and LLE.

> The issue still exists, but it seems like from very specific angles and/or when zoomed out or in enough with the camera.

I suppose, it is another issue.

**Comment by olivieryuyu** [comment]
There is indeed this weird issue with colors in plenty of place...

For the fog small difference, that could come from perspective normalization?

**Comment by IronYoshi64** [comment]
This issue I think is completely fixed as well from https://github.com/gonetz/GLideN64/commit/03b404bd4e609f8ca797cff12d8e15af370d0847
Closing this for now. Seems to be good for now :D
