### ISSUE TITLE
HLE Gauntlet Legends not booting on PJ64

### ISSUE THREAD

**Issue by OtavioRaposo** [gonetz/GLideN64#2239]
Self explanatory title.
The game seems to be on infinite loop.
LLE works fine.

I'm using:
- PJ64 - v2.4.0-1159-gbdd1d1e
- GLideN64-7d4d0f28-QT_for_Project64

**Comment by loganmc10** [comment]
This is an issue with PJ64, it works in HLE with mupen64plus

**Comment by OtavioRaposo** [comment]
Is it possible to solve the issue in PJ64 or there's no known workaround?

**Comment by loganmc10** [comment]
It's definitely possible to solve, this was the commit that allowed it to work in mupen64plus:

https://github.com/gonetz/GLideN64/pull/1623

Mupen64plus extended its API to make it work, PJ64 would need to do the same thing

**Comment by OtavioRaposo** [comment]
So there's a real difference between M64p and PJ64 when it comes to compatibility.
It's not just about solving gfx plugin's problems then.

**Comment by LegendOfDragoon** [comment]
You should close this issue and open an issue in Project64 tbh.
