### ISSUE TITLE
SM64 strange green textures

### ISSUE THREAD

**Issue by OtavioRaposo** [gonetz/GLideN64#2240]
Using m64p Build Apr 27 2020.
Tried standard and non-standard video config. None seems to solve the glitch.

Savestate:
[Super Mario 64 (U) [!].zip](https://github.com/gonetz/GLideN64/files/4571886/Super.Mario.64.U.zip)

Picture:
![Untitled](https://user-images.githubusercontent.com/36393971/80926644-d2c0ef80-8d6e-11ea-880d-3c7000536cdb.png)

**Comment by IronYoshi64** [comment]
Yup, this is currently an issue I am having as well. A similar glitch happens in several games now too. I believe this issue is also what this issue is now too: https://github.com/gonetz/GLideN64/issues/2234
