### ISSUE TITLE
Pokemon Snap: Album Picture Corruption with Mew

### ISSUE THREAD

**Issue by Kidboy17** [gonetz/GLideN64#2241]
![GLideN64_POKEMON_SNAP_000](https://user-images.githubusercontent.com/37382324/80938541-60600780-8d8e-11ea-8957-7f6a69116aaa.png)
![GLideN64_POKEMON_SNAP_001](https://user-images.githubusercontent.com/37382324/80938546-635af800-8d8e-11ea-8879-717d5bcf01f3.png)
[Pokemon Snap (U).pj.zip](https://github.com/gonetz/GLideN64/files/4572885/Pokemon.Snap.U.pj.zip)

Using Project 64 Dev Build: v2.4.0-1159-gbdd1d1e
GLideN64 newest build with latest commit 7d4d0f2

**Comment by gonetz** [comment]
What is your dithering setting?

**Comment by Kidboy17** [comment]
Enable 5bit quantization and Blue Noise.

This problem has been around since 10/27/2018. I made a post about it back then but it got ignored/never got answered and the post got deleted. I was hoping it would eventually get fixed with new commits but since it hasn't, I figured I would bring attention to this problem again.

**Comment by StenApp** [comment]
https://github.com/gonetz/GLideN64/issues/1938 -->this is a duplicate then
I think it wasn't on the top priority list...

**Comment by weinerschnitzel** [comment]
I wouldn't get too discouraged if your issue hasn't gotten a reply. If it hasn't been closed, you should still consider it recognized.

**Comment by tony971** [comment]
#2213 you shouldn't be using blue noise dithering with this game

**Comment by Kidboy17** [comment]
What dithering should I be using for games? Blue noise for most and something else for this game?

**Comment by StenApp** [comment]
https://github.com/gonetz/GLideN64/issues/2213#issuecomment-614683455
> Yes, setting "RDRAM image dithering" to disable, Bayer, or Magic Square works fine. It is just the Blue noise dithering that breaks it

Please try this

**Comment by gizmo98** [comment]
@StenApp game specific settings set bayer dithering for pokemon snap. Your problem is two years old. So there is certainly no problem with new RDRAM dithering options.

**Comment by purplemarshmallow** [comment]
The problem is the "testValue" in WriteToRDRAM.h
removing the test value fixes this problem

**Comment by gonetz** [comment]
> The problem is the "testValue" in WriteToRDRAM.h
> removing the test value fixes this problem

Thanks!

testValue check is used to discard black pixels with zero alpha. Usually it helps to write only useful data to RDRAM buffer and avoid many glitches when RDRAM buffer is used as a texture. In Pokemon Snap: Album Picture case black pixels are part of the image and thus must be copied. The pixel coverage calculation may help to fix alpha for these pixels (make it non-zero), need to check it. @Kidboy17 could you test it again with the current master and Coverage enabled?

**Comment by standard-two-simplex** [comment]
I can confirm it working in master. It is also working with coverage disabled, possibly because the blender part still works with default 1.0 coverage.

**Comment by gonetz** [comment]
Good! @Kidboy17 can it be closed then?

**Comment by Kidboy17** [comment]
Yes it can be closed. Thank you for fixing this old problem!
