### ISSUE TITLE
Threaded video should be off by default

### ISSUE THREAD

**Issue by GhostlyDark** [gonetz/GLideN64#2249]
Threaded video is causing the Zelda games (Ocarina of Time + Majora's Mask) to break, either freeze at boot or crash randomly. This happens on Windows and Android and on other platforms as well I assume.

It should be off by default until threaded video is stable.

**Comment by IronYoshi64** [comment]
> 
> 
> Threaded video is causing the Zelda games (Ocarina of Time + Majora's Mask) to break, either freeze at boot or crash randomly. It should be off by default until threaded video is stable.

Is it really? I haven't been having issues actually?

**Comment by loganmc10** [comment]
Yeah I've never heard of or seen this before either

**Comment by IronYoshi64** [comment]
@GhostlyDark what emulator are you having issues in. Also version of the emulator as well?

**Comment by GhostlyDark** [comment]
Project64, Mupen64PlusFZ, mupen64plus (Logan's GUI)...
I keep getting reports on this from users using the texture pack. If threaded video is on, Zelda breaks.

**Comment by IronYoshi64** [comment]
@GhostlyDark Can you post your Game settings for both OOT and MM please, Just to make sure your settings are not all weird and messed up.

**Comment by GhostlyDark** [comment]
The settings don't matter.

![image](https://user-images.githubusercontent.com/31742919/81329608-1da87300-909f-11ea-9878-d71fe0a6030f.png)

![image](https://user-images.githubusercontent.com/31742919/81329647-2600ae00-909f-11ea-97f2-74534fddabec.png)

![image](https://user-images.githubusercontent.com/31742919/81329664-29943500-909f-11ea-9b54-cf310385e274.png)

![image](https://user-images.githubusercontent.com/31742919/81329677-2e58e900-909f-11ea-8bf6-ee7a2703f8f8.png)

**Comment by loganmc10** [comment]
But it only happens when using the texture pack?

**Comment by GhostlyDark** [comment]
No, it's unstable no matter if you use or not use a texture pack.

**Comment by IronYoshi64** [comment]
Also what I meant by game settings, is like the setting you get to in Project64 by Right clicking the game on the Rom browser, and clicking Edit Game Settings

**Comment by GhostlyDark** [comment]
It'll crash either right away or at some point. Threaded video is simply unstable. Doesn't matter which emulator or platform, it even happens on Switch as far as I know.
These settings don't matter for this issue, but here you go:

![image](https://user-images.githubusercontent.com/31742919/81331101-5ea18700-90a1-11ea-9b22-1e60b64c6803.png)

![image](https://user-images.githubusercontent.com/31742919/81331109-62350e00-90a1-11ea-80ea-cd4f5179167d.png)

**Comment by GhostlyDark** [comment]
The crashes seem to be different for everbody, but always reproducible. E.g. leaving Clock Town in MM, booting the game in OoT etc.

**Comment by IronYoshi64** [comment]
Well it could be an issue with the settings if they are are all messed up, which for you, they appear not to be. Also what build are you using for Project64 and what are your currently selected plugins?

**Comment by GhostlyDark** [comment]
Project64 2.4-850

![image](https://user-images.githubusercontent.com/31742919/81331949-9ceb7600-90a2-11ea-81df-31ea4c80833d.png)

Just another reminder: mupen64plus crashes with threaded video as well.

**Comment by loganmc10** [comment]
> Threaded video is simply unstable

I don't think others are experiencing this issue. It looks like from your GitHub activity that you are working on some kind of OoT/MM enhanced version? Why not just disable threaded video in whatever package you are distributing?

**Comment by GhostlyDark** [comment]
It's not just me. Nerrel confirms it on Windows, Pingle confirms it on Windows, slash004 had crashes on Switch (not entirely sure they are caused by threaded video, but it was on, so probably)...other users over at Admentus' Discord server confirmed it...it's not just me.

**Comment by loganmc10** [comment]
I don't you'll get much traction unless you can provide a save state that can reproduce it, or maybe a backtrace from a crash to point to where the issue exists.

**Comment by IronYoshi64** [comment]
Hmm ok. Also I not sure about that Mupen64plus HLE RSP plugin though. I don't see a problem with the default RSP plugin. Maybe its that, IDK for sure. Also I guess if several people are having this issue as well, it might be best to turn off Threaded video for both OOT and MM for now, through the GLideN64.custom.ini file.

**Comment by loganmc10** [comment]
> Also I guess if several people are having this issue as well, it might be best to turn off Threaded video for both OOT and MM for now, through the GLideN64.custom.ini file.

It would be better to get a backtrace and fix the root issue

**Comment by GhostlyDark** [comment]
[crash.txt](https://github.com/gonetz/GLideN64/files/4595208/crash.txt)

**Comment by loganmc10** [comment]
Can you try with the latest version available here: https://m64p.github.io

Whatever version you are using there is a little old

**Comment by GhostlyDark** [comment]
You mean the one that removed support for one in-game button to be mapped to multiple buttons ont he gamepad? Or broke HD texture support entirely?

That one boots. But I am 100% it'll crash randomly at some point. I try and see if I can get a crash log for such.

**Comment by loganmc10** [comment]
> You mean the one that removed support for one in-game button to be mapped to multiple buttons ont he gamepad? Or broke HD texture support entirely?

Yes correct that one, I'm glad it boots for you

**Comment by GhostlyDark** [comment]
[crash.txt](https://github.com/gonetz/GLideN64/files/4595394/crash.txt)

**Comment by m4xw** [comment]
> 
> 
> Project64, Mupen64PlusFZ, mupen64plus (Logan's GUI)...
> I keep getting reports on this from users using texture packs. If threaded video is on, Zelda breaks. It happens pretty much since threaded video was first introduced.

IIRC ```
	std::vector<char> GlDrawArraysUnbufferedCommand::m_attribsData(2 * 1024 * 1024, 0);
	std::vector<char> GlDrawElementsUnbufferedCommand::m_attribsData(2 * 1024 * 1024, 0);```
These had to be bumped

**Comment by GhostlyDark** [comment]
I doesn't look like this is going anywhere, so I'll close it.

One thing I want to add however is that the increase in input lag when using the threaded renderer is very significant. I am one of those persons that usually doesn't care about it much, as I tend to run games with VSync on and don't bother activating my TV's game mode, while all of the postprocessing is still on. But in case of the threaded renderer, I found the games to be dreadful to play. I can only recommend turning the option off.

**Comment by Jj0YzL5nvJ** [comment]
mupen64plus/mupen64plus-core#769
