### ISSUE TITLE
Bomberman Hero: black textures intro and in game

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#225]
start a new game to get there

![aie](https://cloud.githubusercontent.com/assets/8987490/5548922/ec6ab504-8b7d-11e4-9889-bee74dd911ad.jpg)

Glide64 is fine here

![glide64ok](https://cloud.githubusercontent.com/assets/8987490/5548923/f0949712-8b7d-11e4-8c13-29db953a7505.jpg)

**Comment by gonetz** [comment]
Please check with latest build.

**Comment by Predator82Germany** [comment]
With emulate frame buffer I get a stroboscoped flickering & wrong position of image

**Comment by olivieryuyu** [comment]
fixed

Predator open a new ticket please for your issue
