### ISSUE TITLE
Zelda: OnePiece backgrounds broken

### ISSUE THREAD

**Issue by GhostlyDark** [gonetz/GLideN64#2251]
This doesn't look so good. Happens with any "single-file" background.

![image](https://user-images.githubusercontent.com/31742919/81336724-218dc280-90aa-11ea-8e0e-e4a175ad2a09.png)

This does not happen using stripped mode.

**Comment by IronYoshi64** [comment]
Yeah I default everything to Stripped, and have very little to no issues in several game xD

**Comment by GhostlyDark** [comment]
@gonetz 
Thanks for taking a look. I have to disappoint you though. It's not quite fixed. HD textures loaded in OnePiece mode still don't look quite right.

![image](https://user-images.githubusercontent.com/31742919/82366508-93eb9480-9a12-11ea-8267-602ec067d926.png)
