### ISSUE TITLE
[Regression] Conker's BFD: Only Displays Black screen

### ISSUE THREAD

**Issue by IronYoshi64** [gonetz/GLideN64#2253]
In latest builds of GLideN64, both QT and WTL versions, there is absolutely no video output for Conker's Bad Fur Day. Audio is fine, but visually you only get a completely black screen, all the time.

Again, this seems to be another bad regression for this comment here: https://github.com/gonetz/GLideN64/commit/096115d99794bf8f6b171fe71cb5084f4ea51fa8

Something that I think will be useful is that I know it works with this comment: https://github.com/gonetz/GLideN64/commit/03b404bd4e609f8ca797cff12d8e15af370d0847 .

I have a feeling that some other games might have this same issue.

**Comment by backgamon** [comment]
Allready posted just below:
https://github.com/gonetz/GLideN64/issues/2252

**Comment by IronYoshi64** [comment]
Oh. Yeah I did notice that, but I thought that was actually fixed from the Overscan options being off, so I thought this was a new issue. Well now we know more issues with it xD

**Comment by gonetz** [comment]
Please test again with latest builds.

**Comment by IronYoshi64** [comment]
> 
> 
> Please test again with latest builds.

Ok. I tested again a couple of things. And Yes, Conker is no longer just a black screen. Great!

Also, the Overscan option seems to be working again! I tested both SM64 and Conker, everything seemed fine! Yay! :)

I used this build: https://github.com/gonetz/GLideN64/commit/3f9911ab9dd4ad7de26194aa0c3e1c56d7b7afb8

**Comment by gonetz** [comment]
Ok, thanks.
