### ISSUE TITLE
RE2 backgrounds

### ISSUE THREAD

**Issue by Piloto40** [gonetz/GLideN64#2254]
Resident Evil 2 backgrounds are buggy.

**Comment by Kidboy17** [comment]
What emulator and version are you using? What version of GLideN64 are you using? What are you settings for the plugin?

**Comment by Piloto40** [comment]
Project64 2.4.0.1168, GlideN64 1.0.585.
Settings:
![2020-05-10 (0)](https://user-images.githubusercontent.com/61851437/81507433-d656f800-92d3-11ea-959e-8f9afae7e262.png)
![2020-05-10 (1)](https://user-images.githubusercontent.com/61851437/81507434-d6ef8e80-92d3-11ea-96b0-c1342feeacfc.png)
![2020-05-10 (2)](https://user-images.githubusercontent.com/61851437/81507435-d7882500-92d3-11ea-86da-2f78f6b4220a.png)
![2020-05-10 (3)](https://user-images.githubusercontent.com/61851437/81507436-d7882500-92d3-11ea-9246-1ea543ae35f9.png)

**Comment by gonetz** [comment]
It's better to ask what  "buggy backgrounds" means? Most likely it is something reported in #2152 or other open issues.

**Comment by Piloto40** [comment]
Like this gonetz
Sorry my English
![2020-05-11](https://user-images.githubusercontent.com/61851437/81575442-6bfa9200-937d-11ea-87b1-e4356170a88a.png)

**Comment by gonetz** [comment]
It could be temporal regression. I can'r reproduce it with the current master. Please test again with latest build. Please disable shader storage first.

**Comment by Piloto40** [comment]
Now fixed
Thanks gonetz :)
