### ISSUE TITLE
Harvest Moon 64 Graphical Glitches 

### ISSUE THREAD

**Issue by Kidboy17** [gonetz/GLideN64#2255]
Harvest moon 64 has these artifacts that rapidly change throughout the game. It's extremely hard to capture it on photo, not sure how to do a video. Changing the options around does not fix the problem it only makes the artifacts more pronounced. Native resolution does not fix it either.
![GLideN64_HARVESTMOON64_001](https://user-images.githubusercontent.com/37382324/81512221-ca6b3600-92d3-11ea-8a55-dcc5ad5127f6.png)
![GLideN64_HARVESTMOON64_002](https://user-images.githubusercontent.com/37382324/81512223-cccd9000-92d3-11ea-9d3c-8583bd2f699e.png)
![GLideN64_HARVESTMOON64_003](https://user-images.githubusercontent.com/37382324/81512299-8167b180-92d4-11ea-992a-071deb80934c.png)
![GLideN64_HARVESTMOON64_004](https://user-images.githubusercontent.com/37382324/81512301-83317500-92d4-11ea-92a5-52aa2cd911dc.png)

**Comment by loganmc10** [comment]
I think this happens because of N64 Depth Compare. It is enabled as a per game option for this game. This only happens with certain GFX cards I think.

You could try changing N64 Depth Compare from "fast" to "compatible"

**Comment by Kidboy17** [comment]
> I think this happens because of N64 Depth Compare. It is enabled as a per game option for this game. This only happens with certain GFX cards I think.
> 
> You could try changing N64 Depth Compare from "fast" to "compatible"

That fixed the issue.

**Comment by loganmc10** [comment]
Yeah the fast mode relies on some OpenGL extensions that don't seem to be implemented the same across all graphics cards, it randomly becomes broken or fixed with driver updates.

Compatible mode is pretty slow though, so it's just a tradeoff. There may be some way to fix fast mode, I'm not sure

**Comment by Kidboy17** [comment]
There are black boarders around the falling Cherry blossom pedals in the beginning and a green outline around the sign. Nothing I do can change that. Angrylion does not produce this.
GLiden64:
![GLideN64_HARVESTMOON64_011](https://user-images.githubusercontent.com/37382324/81512483-ad376700-92d5-11ea-9ecd-d80d3182150a.png)
![GLideN64_HARVESTMOON64_013](https://user-images.githubusercontent.com/37382324/81512491-b6283880-92d5-11ea-87f9-2ea70efd4084.png)
Angrylion:
![HARVESTMOON64_0002](https://user-images.githubusercontent.com/37382324/81512519-f982a700-92d5-11ea-8336-5780ce5bbc15.png)
![HARVESTMOON64_0000](https://user-images.githubusercontent.com/37382324/81512520-fedff180-92d5-11ea-8e0a-4bf7917a31a5.png)

**Comment by gonetz** [comment]
>>You could try changing N64 Depth Compare from "fast" to "compatible"

>That fixed the issue.

Closed then.

> There are black boarders around the falling Cherry blossom pedals in the beginning and a green outline around the sign. Nothing I do can change that. 

This is another story.
