### ISSUE TITLE
N64 Depth Compare causes black dots on Nvidia turing/rtx cards.

### ISSUE THREAD

**Issue by BParks21** [gonetz/GLideN64#2256]
With depth compare enabled black dots appear on 3D textures in all games I've tested. I can't reproduce this on Pascal cards, only Turing.
![Super_Mario_64_USA-200509-214817](https://user-images.githubusercontent.com/12180630/81524840-bdc0ff00-9320-11ea-81d5-2591f390705e.png)
![Banjo-Kazooie_USA_Rev_A-200509-215002](https://user-images.githubusercontent.com/12180630/81524841-be599580-9320-11ea-9543-90ceacd5173a.png)

**Comment by loganmc10** [comment]
Can you try the "compatible" mode? Fast mode seems to have some issues with various GFX cards and drivers

**Comment by BParks21** [comment]
@loganmc10 Yes compatible does fix it. This option is missing in a libretro port of the plugin hopefully it can be added. https://github.com/libretro/mupen64plus-libretro-nx/issues/193

**Comment by gonetz** [comment]
> Yes compatible does fix it.

Closed.

**Comment by oddMLan** [comment]
Sucks that such a limited set of gfx cards can use the Fast option

**Comment by gonetz** [comment]
Sucks that we can't detect when Fast mode can be safely used. Nvidia cards support necessary extensions but still may work incorrect.
