### ISSUE TITLE
Pachinko Nichi & other Seta games: "lighting" (HLE)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#2259]
I studied the "lighting system" of some Seta games which have a rewritten fast3d ucode (completely rewritten but full compatible gbi wise with fast3d)

I was thinking that I got wrong by saying that the lighting was working correct in HLE but actually....

i have some doubts

See the screen in Pachinko 365 Nichi:

LLE

![LLE](https://user-images.githubusercontent.com/8987490/81583743-0ecd0380-93b2-11ea-8184-31ad43d63727.png)

HLE:

![HLE](https://user-images.githubusercontent.com/8987490/81583778-1c828900-93b2-11ea-927b-38fdaa403c3a.png)

I see a color difference.

Do you?

**Comment by olivieryuyu** [comment]
Stunning is the hair, color is really different. HLE is too bright, LLE is darker overhaul.

**Comment by olivieryuyu** [comment]
Same in Eiko St Andrews

![HLE](https://user-images.githubusercontent.com/8987490/81584576-3375ab00-93b3-11ea-8859-07d02b69a062.png)

![LLE](https://user-images.githubusercontent.com/8987490/81584589-37a1c880-93b3-11ea-9728-c7d491bbac87.png)

**Comment by oddMLan** [comment]
The difference so small is impossible to notice unless you're comparing HLE/LLE side by side. Is it worth looking into it?

**Comment by olivieryuyu** [comment]
I spent already a lot of time on it :)

thinking about it the "lighting system " only appears when the players arrives in Eikou. Would it be a way to manage the framebuffer/colors buffer? Wild idea for the time being.

**Comment by LegendOfDragoon** [comment]
@olivieryuyu it does look darker in LLE. Out of curiosity, how did you notice the slight difference? I find it impressive that you discovered this, because I wouldn't have noticed unless i looked at both at the same time.

**Comment by olivieryuyu** [comment]
some Seta games have a rewritten fast3d ucode (completely rewritten but full compatible gbi wise with fast3d)

I noticed that a long time ago, notably because the Y was reversed.

I am trying to get in the ucode i am trying to develop an optimized way to do lighting

I was curious the Seta microcode which does something completely different and for which neither Sergey or me have a clue about.

**Comment by gonetz** [comment]
> I was curious the Seta microcode which does something completely different and for which neither Sergey or me have a clue about.

Could you explain it in details here? The Seta microcode does really weird computations instead of traditional lighting. I don't understand what is it, but someone else may find it out.

**Comment by oddMLan** [comment]
We discussed somewhat about it in the Discord64 server, you may want to check #n64_dev there

**Comment by olivieryuyu** [comment]
Here how lights seems to work

1. calculate n
        
top of modelview matrix:

                1    2     3    
                
                4    5     6    
                
                7    8     9                           
        
    n = sqrt((1 + 4 + 7)² + (2 + 5 + 8)² + (3 + 6 + 9)²) * 0x1BB (???)
        
2. We change the elements of the top of the modelview matrix        
        
                1/n    2/n    3/n        
                4/n    5/n    6/n        
                7/n    8/n    9/n    
        
3. multiply this new matrix with the normals   
        
4. multiply 3. by the the light directions  
        
5. add each elements of 4. together        
        
6. multiply 5. by the colors of the light

I can notice that the ambient light shares the same value for R, G and B

I can notice that the unique light shares the same value for R, G and B

Completely senseless to me.

**Comment by mudlord** [comment]
1. looks like a different way I usually see to compute the dot product. Very clever.
It looks like doing a horizontal add like you can easily do in SSE plus a hardcoded val for multiply.

http://ok-cleek.com/blogs/?p=20540

**Comment by standard-two-simplex** [comment]
Step one is calculating some [norm of the matrix](https://en.wikipedia.org/wiki/Matrix_norm) and, thus, step two is normalizing it.

Compatible norms satisfy <img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/364426f722171a6db592ef9950c2373997c97b72">.  I'm guessing that the idea is to have the results of modelview matrix times vertex normal almost normalized and thus skip normalizing normal vectors (at world coordinates). You get this by using a normalized modelview matrix and normalized vertex normals (at model coordinates).

The result would be faster lighting (normalizing one matrix is faster than normalizing many vectors) but less realistic lighting, as normal vectors won't be exactly normalized.

Ideally one should use a compatible norm, but it seems to me the algorithm is prioritizing ease of calculations. I would say those computations result in the L12 norm. Notice I said L12 and not the more standard L21. There's also the nuance of the hardcoded multiplication.

The rest of the steps seem standard to lighting computation.

Hope this helps.

**Comment by olivieryuyu** [comment]
i believe you could be right :)

**Comment by weinerschnitzel** [comment]
Did this get implemented? If not, sounds low priority but very cool and would be neat to see emulated accurately.
