### ISSUE TITLE
Golden Eye: Line Mode not supported (Coverage)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#226]
![coverage](https://cloud.githubusercontent.com/assets/8987490/5558988/75ebe7d0-8d3b-11e4-8d68-1164d1c8f18b.jpg)

https://www.youtube.com/watch?v=8I5COJH5e68

Works with angrylion but not Gliden64. Use coverage obviously.

Savestate from 1964 here

http://uptobox.com/9m4cbd3jdeon

**Comment by purplemarshmallow** [comment]
B/W mode in South Park isn't working
i think it's the same issue
angrylion:
![1](https://cloud.githubusercontent.com/assets/7283660/7561343/90d8d42c-f7cb-11e4-8a0e-08bdd34feee7.jpg)

**Comment by olivieryuyu** [comment]
i didn't know there was a B&W mode in this game :)

**Comment by purplemarshmallow** [comment]
Turok2/3 pen and ink mode
![ntke0000](https://cloud.githubusercontent.com/assets/7283660/9704559/4f359580-54ac-11e5-9e33-f03201d562b7.jpg)
