### ISSUE TITLE
Earthworm Jim 3D texture mapping regression

### ISSUE THREAD

**Issue by oddMLan** [gonetz/GLideN64#2261]
Steps to reproduce. Just keep pressing start until you arrive to the file select menu
GLideN64 499ba7d
Project64 v2.4.0-1170-g0462f63
AMD R4 Graphics
Shader Cache disabled
Native resolution doesn't help
![GLideN64_EARTHWORM_JIM_3D_000](https://user-images.githubusercontent.com/7278372/81696341-a06f5c00-9418-11ea-8e42-5a1460f457f3.png)

LLE looks the same but in the intro it also has this black box
![GLideN64_EARTHWORM_JIM_3D_001](https://user-images.githubusercontent.com/7278372/81696767-3905dc00-9419-11ea-9d84-5d8547243a3f.png)

**Comment by standard-two-simplex** [comment]
Try deleting shader cache, I can see the first picture correctly.

**Comment by oddMLan** [comment]
I deleted and disabled the shader cache and it made no difference for me

**Comment by standard-two-simplex** [comment]
Can you check if it is correct before commit f5ee3523ef961d7a6173fc34dd93f40e61416b81 and incorrect after that one?

**Comment by oddMLan** [comment]
Sure, in a sec

**Comment by oddMLan** [comment]
Commit https://github.com/gonetz/GLideN64/commit/2616ba9587d8f42d53bbffbb7ddb29802be17c94 (right before the out of bounds fix one you linked) is correct:
![GLideN64_EARTHWORM_JIM_3D_002](https://user-images.githubusercontent.com/7278372/81699948-dc0c2500-941c-11ea-9c55-4a122823fc6e.png)

**Comment by oddMLan** [comment]
both issues fixed by #2265
