### ISSUE TITLE
Mario Party 3 - wrong textbox

### ISSUE THREAD

**Issue by oddMLan** [gonetz/GLideN64#2262]
![GLideN64_MarioParty3_000](https://user-images.githubusercontent.com/7278372/81698556-06f57980-941b-11ea-98d9-75f385178cec.png)

**Comment by oddMLan** [comment]
Regression caused by (you guessed it) commit https://github.com/gonetz/GLideN64/commit/f5ee3523ef961d7a6173fc34dd93f40e61416b81

**Comment by standard-two-simplex** [comment]
@oddMLan I will look at it, no need to create more issues about it.
Post pictures in this thread if you want.

**Comment by oddMLan** [comment]
To be fair I didn't know they were all related to the same issue, sorry

**Comment by standard-two-simplex** [comment]
Please check if this fixes the issues you encountered #2265.

**Comment by oddMLan** [comment]
Fixed by #2265
