### ISSUE TITLE
battle for naboo unplayable

### ISSUE THREAD

**Issue by nero81af** [gonetz/GLideN64#2267]
Hi there,
I'm trying to understand why battle for naboo isn't working as expected. Setup
- pj64 2.3.2.202
- GLideN64 4.0
menu are working, but once in game, the camera is completely messed up. I can provide screenshots
![Capture](https://user-images.githubusercontent.com/7045350/81860317-dfabc300-9566-11ea-8b8c-0b3aa154c37f.PNG)

**Comment by oddMLan** [comment]
@nero81af it's a problem with the version of PJ64 you're using
need to download the latest dev build and you'll see that the graphics show up correctly now
https://www.pj64-emu.com/nightly-builds

**Comment by StenApp** [comment]
What changed, that just greater versions than pj64 2.3.2.202 work?

**Comment by gonetz** [comment]
It is a core issue, not a plugin's one. Closed.
