### ISSUE TITLE
Banjo Kazoiie: incorrect puzzle effect even with enablecopycolortordram (refb): only half screen

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#227]
![what](https://cloud.githubusercontent.com/assets/8987490/5561736/b8617280-8ded-11e4-9b79-66ee8193cc3e.jpg)

**Comment by theboy181** [comment]
With the version released today, this seems to be working. The textures on the puzzle piece look lower resolution though, but I may be incorrect.
