### ISSUE TITLE
Cant find "Force Point-Sampled" feature in video settings.

### ISSUE THREAD

**Issue by Ardi-san** [gonetz/GLideN64#2273]
In GLideN64 Final there is a setting to set filter to Point Sampling:
![1st image](https://user-images.githubusercontent.com/38388109/82105787-1ca0c280-96eb-11ea-9c12-e6bed996e63c.png)
But on GLide64 4.0 Public Release I cant find the option anywhere, not even messing with config worked:
![2nd image](https://user-images.githubusercontent.com/38388109/82105814-49ed7080-96eb-11ea-959f-da59f68e5598.png)

Point Sampling is really good for 2D games such as Mischief Makers and I like it on 3D games to get the sharp PS1-esque visuals I prefer to the blurry filtered ones.

**Comment by gonetz** [comment]
There are no "GLideN64 Final." There is In "Glide64 Final" It is absolutely different plugin with different settings.
