### ISSUE TITLE
So where is the chat thread around here

### ISSUE THREAD

**Issue by Nes-player4Life** [gonetz/GLideN64#2274]
Long time no see all i hope you all are in good HP.
I fired up PJ64for the first time in months, with the 5/12/20 build and i have to say I'm impressed with the progress.

**Comment by oddMLan** [comment]
Hey @Nes-player4Life, we chat every day about N64 emulation in our Discord server. Almost 500 members. Gonetz is a part of it tho he is more active here. If you wanna join here's an invitation link https://discord.gg/nZwu3Ye

**Comment by Nes-player4Life** [comment]
Thanks.
