### ISSUE TITLE
Unplayable performance with any kind of texture enhancement.

### ISSUE THREAD

**Issue by truskj** [gonetz/GLideN64#2279]
Windows 10
Geforce GTX 970M Driver ver. 8.1.956.0 (fairly recent, 2020)
Intel i7 6700HQ
Project64 2.4.0.641
Gliden64 Public Release 4.0 
(Also tested on various newer WIP and LLE builds)

This happens in a few games I've tried lately, but right now I'm trying Space Station Silicon Valley.

Switching on any kind of texture enhancement absolutely cripples the frame rate.
I can have 8x resolution, MSAA, AF, PJ64 overclocking etc. and won't get a dint in my frame rate in pretty much all the games I play. Solid 30/60 fps.

However, the moment I turn on any form of texture enhancement the frame rate will drop to 25%.
even if it's only "smooth filtering 1". Can confirm it still happens when I disable all other graphical enhancements, and even disable frame buffering. 

Interestingly, in Silicon Valley, the frame loss only occurs when the camera is moving, as in when the emulator is loading textures. if I stand still the frame rate recovers till I move again.
I tried using texture cache but it made no difference. Shader cache is switched on.

It's worth pointing out I reported perhaps the same issue back in 2017, however back then I managed to solve my issue by changing a setting or two in the Nvidia control panel. This time however, no settings appear to remedy the situation.

any thoughts?

**Comment by gonetz** [comment]
Please attach your GLideN64.ini here. I tried to get slowdown in Silicon Valley. I set 6XBRZ but it does not affect performance on my PC with Geforce 1050

**Comment by truskj** [comment]
Had to zip,
jumping in the water in the first stage makes it very apparent as the bubble sprites appear.

thank you.
[GlideN64_ini.zip](https://github.com/gonetz/GLideN64/files/4655937/GlideN64_ini.zip)

**Comment by truskj** [comment]
not sure if it helps, but I've uploaded a video preview to show what I'm talking about.
https://youtu.be/m5xXyhsYOTo

**Comment by Jj0YzL5nvJ** [comment]
First of all I want to make two observations:
LOD / Mip-mapping does not work with Silicon Valley. The grass looks bad, and it's not because of the low bitrate.
The removal of halos produces unwanted effects, such as removing the edges of the dog's eyelid.

Now your problem is called **NVIDIA Optimus**. GPU switching ultimately breaks the shader storage, so it's better to disable it.
[Another solution would be to rename "project64.exe" to "bf3.exe".](https://www.ngemu.com/threads/cant-add-epsxe-in-nvidia-control-panel.206712/)

**Comment by truskj** [comment]
Thanks for your suggestions, Jj0YzL5nvJ.

Switching off Shader storage in both Gliden64 and NvidiaCP made no difference.
renaming to bf3.exe made some funky things happen, like discord notifications started appearing in my emulator haha... but still the problem persisted.

**Comment by truskj** [comment]
Just confirmed, problem is not present in Public Release v3.0
Can run at 6xBRZ with no issues.

**Comment by Jj0YzL5nvJ** [comment]
@truskj, as you may have already noticed, I'm not a fan of NVIDIA for my own good reasons. Optimus drivers have a bad reputation and [your chip series](https://www.google.com/search?q=GTX+970+slow+3.5GB) doesn't help much in that regard.

[How to Monitor GPU Usage in the Windows Task Manager](https://www.howtogeek.com/351073/how-to-monitor-gpu-usage-in-the-windows-task-manager/)

Let's see if we can find the logic of your problem. In **trial and error** should be the answer.
Every time you try new GLideN64 versions, **disable shader storage or erase the old shaders** in the plugin settings to avoid "false positives".
**Texture enhancements cannot cause these symptoms** unless you exceed NVIDIA's [fast memory limit](https://youtu.be/jPlCIUh_Tp0).
The extensions used by the `N64-style depth compare` are **performance expensive**. Don't use it if it's not fixing glitches.
Some specific anti-aliasing and anisotropic settings can **degrade performance for no apparent reason** in native PC games. By extension, that's also a possibility in emulators.

**Comment by truskj** [comment]
I've been doing a lot of trial and error, with plugins, pj64 version, RSP, nvidia CP settings, etc etc. with very little, if any, results. (this includes AF and AA disabled in the control panel, both pj64 profile and globally)
as far as Gliden64 version goes, Public v3.0 does not have this problem at all...  I can reproduce this result easily as I use save states at the problematic areas. cleaning any cache files I see too.
the problem does vary with each Gliden64 release. 

I can confirm this, Public v4 is at it's worst, and the WIP builds slightly get better, and today I got the latest compiled Gliden64 from EmuCR (I know these builds aren't supported or advised, but I can't compile glide myself), on this version it seems to be a lot better, the slow down is still there, but it seems to happen less often. It's very distinct, I can run around fine at 100% speed, (600%+ if I disable frame limiter) but the moment the dog jumps in the water, causing the splash to appear, it drops to 30%, then instantly recovers when the splash particles fade away.

I've been watching the resource manager and the GPU never really gets above 20%, I think this is normal because if I load up perfect dark and crank up the enhancements I can get a readable 100% GPU usage pretty easily.

If I jump in the water and cause the slowdown, the gpu usage actually lowers to 10%, probably because it is rendering less frames now.

interestingly, 80% of the time these specific crippling framerate issues appear, my "system" process suddenly starts using about 3% of "GPU 1 - copy", and then stops whenever the framerate recovers.
so I've got a feeling that's a culprit.

I actually haven't updated windows in half a year, maybe it's that?

**Comment by gonetz** [comment]
I can confirm the issue:  jump in the water in Space Station Silicon Valley causes serious slowdown when texture filter is enabled. I tested it on Geforce GTX 970M and on GTX 1050 and the problem appears on the both. The intriguing thing is that it happens only with **release** build. Debug build has no performance drop on the jump in the water. It can be hard to track down.

**Comment by truskj** [comment]
Ok, Gonetz. Thanks for confirming, it's nice to know its not just my laptop then.
off topic, but is there a place to get the current debug build? I usually check the WIP threads but that one seems a bit out of date.

**Comment by gonetz** [comment]
It was a bit tricky but I found that bug and squashed it: c2f3b02e4
I tested it on Geforce GTX 970M, no more slowdowns in Silicon Valley.
Test build should be ready soon here:
https://ci.appveyor.com/project/gonetz/gliden64/branch/master/artifacts
please test it.

**Comment by truskj** [comment]
Just tested it, problem seems to be completely gone.
good work! Closing.
