### ISSUE TITLE
Debug build crashes on Linux

### ISSUE THREAD

**Issue by gonetz** [gonetz/GLideN64#2282]
I need to test debug build functionality on Linux. When I run it with latest mupen64plus-gui from May 23, it crashes with 
```
: ./mupen64plus-gui
(II) Setting video mode 640x480...
terminate called after throwing an instance of 'std::runtime_error'
  what():   OpenGL error: 0x502, on function: glDisable

```
Release build works.

The issue introduced by commit 92bcbe59819 "Fix issues with threaded OpenGL when debug is enabled". When I reverted changes in opengl_Wrapper.cpp the problem gone. Looks like that commit fixes issues with debug build on Windows but breaks Linux debug build.
@fzurita Could you check it? 
@loganmc10 may be you have an idea what that commit breaks?

As a side note - I tried to use standard mupen64plus, but mupen64plus-bundle-linux64-2.5.9 can't run on my PC with any graphics plugin. The problem exactly like this: https://github.com/mupen64plus/mupen64plus-core/issues/349, that is 
```
Core: Setting 32-bit video mode: 640x480
Core Error: SDL_SetVideoMode failed: Could not create GL context: GLXBadFBConfig
Video Error: Failed to set 32-bit video mode: 640x480
```
glxinfo reports that "core profile version string: 3.3":
```
glxinfo|grep OpenGL
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: llvmpipe (LLVM 9.0, 128 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 19.2.8
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.1 Mesa 19.2.8
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

```

**Comment by Jj0YzL5nvJ** [comment]
> As a side note - I tried to use standard mupen64plus, but mupen64plus-bundle-linux64-2.5.9 can't run on my PC with any graphics plugin.

Works fine on upstream. See `m64p_get.sh` and `m64p_build.sh` in [m64p_helper_scripts.tar.gz](https://github.com/mupen64plus/mupen64plus-core/blob/master/tools/m64p_helper_scripts.tar.gz).
You may prefer to add `export NEW_DYNAREC=1` before building...

>
```
 OpenGL renderer string: llvmpipe (LLVM 9.0, 128 bits)
```

That's not right, you're not using hardware acceleration.
```
$ cat /var/log/Xorg.0.log | grep WW
$ cat /var/log/Xorg.0.log | grep EE
$ cat /var/log/Xorg.0.log | grep NI
$ cat /var/log/Xorg.0.log | grep '??'
$ glxinfo -B
```

**Comment by gonetz** [comment]
> That's not right, you're not using hardware acceleration.

What can be done? My gfx card is amd redeon.

**Comment by fzurita** [comment]
This is the problem;
```OpenGL error: 0x502, on function: glDisable```

Debug builds are set to automatically terminate and create a core dump when a GL error happens. The driver on that machine is generating a GL error on glDusable. You can use gdb to get a back trace to the source of the GL error.

**Comment by Jj0YzL5nvJ** [comment]
`LLVMpipe` literally means you don't have a hardware driver. Make sure you have the latest version of `linux-firmware` or equivalent for AMD GPUs in your distribution.

If you installed `amdgpu-pro` before installing `dkms`, you will have to reinstall `amdgpu-pro` every time the kernel is updated. It is recommended to install `dkms` and then install the proprietary driver.
Free drivers don't need `dkms`... but it's still recommended to have it on hand for VM drivers.

If you are using the free drivers, you will have to [diagnose](https://github.com/gonetz/GLideN64/issues/2191#issuecomment-605532350) what is happening by yourself.

**Comment by gonetz** [comment]
I managed to enable hardware acceleration:
```
glxinfo|grep OpenGL
OpenGL vendor string: X.Org
OpenGL renderer string: AMD Radeon(TM) HD 8800 Series (PITCAIRN, DRM 3.27.0, 4.15.0-101-generic, LLVM 7.0.1)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.2.0-rc3
OpenGL core profile shading language version string: 4.50

```
Now I can run mupen64plus with GLideN64. To my surprise, debug build of GLideN64 works without "OpenGL error: 0x502, on function: glDisable" with mupen64plus. However, when I run it with mupen64plus-gui the problem is still there. I guess it is some incompatibility with mupen64plus-gui. Anyway, it is not a problem with threaded code. error: 0x502 means GL_INVALID_OPERATION: "Given when the set of state for a command is not legal for the parameters given to that command" 
Sounds strange of course for glDisable command, but probably mupen64plus-gui does something weird.
