### ISSUE TITLE
Sin and Punishment crashes on Glide64 on Project64 2.3.2.202.

### ISSUE THREAD

**Issue by Tuscarorachief081** [gonetz/GLideN64#2284]
The error according to the log is: 
2020/05/28 17:00:34.923 01500,Error,Exception Handler,CMipsMemoryVM::FilterX86Exception,Invalid memory adderess: C98CACC8
2020/05/28 17:00:34.923 01500,Error,RSP,CN64System::RunRSP,exception generated
2020/05/28 17:00:34.923 01500,Error,User Interface,CNotificationImp::FatalError,CN64System::RunRSP()
Unknown memory action

Emulation stop
______________________________________________________________________________________________________
The emulator throws this error when using Glide64 every time I get to the title screen and than press start. Jado's Direct3D 8 works fine. 

My specs:
i9 9900K
RTX 2080 Ti (Driver 445.87)
16 GB DDR4
Windows 10 Pro version 1909 (OS Build 18363.836)

**Comment by Kidboy17** [comment]
try the dev build of GLideN64 here: https://ci.appveyor.com/project/gonetz/gliden64/branch/master/artifacts

Use the newest dev build of Pj64 here:
https://www.pj64-emu.com/nightly-builds

**Comment by gonetz** [comment]
Project64 2.3.2.202 is pretty old. I can't reproduce that crash with Project64 2.4.X
Also, you reported about issue with Glide64. It is a different plugin.
Please test again with recent builds of Project64 and GLideN64.
