### ISSUE TITLE
"Enable noise" option removed?

### ISSUE THREAD

**Issue by IronYoshi64** [gonetz/GLideN64#2286]
Hey. I was testing various builds of GLideN64 and I noticed that the "Enable noise" option was removed a while ago. Why was this option removed? I kind of liked that you can toggle the noise on and off in PR 4.0 and some older dev builds after that. Was this option removed because of the added dithering options?

This is the option I am talking about, from PR 4.0:
![FSCapture-1966](https://user-images.githubusercontent.com/57850880/83356073-189ab480-a329-11ea-9dae-727796e8f7b7.png)

**Comment by gonetz** [comment]
This option removed because noise emulation works well and there is no need to disable it.
The less options the better.

**Comment by IronYoshi64** [comment]
> 
> 
> This option removed because noise emulation works well and there is no need to disable it.
> The less options the better.

Oh ok. I get it. I do sort of like the idea you can toggle it off and on, but I see why It was removed. Thanks for the answer.
