### ISSUE TITLE
Out of topic: Freak Boy for N64

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#2296]
Hope it is fine to post a request support here for a little while :)

Explanation here:

https://www.obscuregamers.com/threads/fundraiser-freak-boy-for-n64.2451/#post-15385

**Comment by gonetz** [comment]
It's fine. 800 euro as a partial recoup - you have expansive hobby

**Comment by olivieryuyu** [comment]
yes it is unfortunately expensive and I must now ask a bit of support

indeed, i have just noticed that paypal is not accepted for gofundme (damn!!) so i updated the link on obscuregamers with instructions to pay with paypal. Fee free to drop me an email if you wanna fund me a bit :)
