### ISSUE TITLE
Potential recent Blending Regressions

### ISSUE THREAD

**Issue by m4xw** [gonetz/GLideN64#2300]
Hey @gonetz  and @standard-two-simplex 
Rebased from 4f58d66e960a575a35ef3d783cca25fd71f5bc25 (<- confirmed working) to 1467582e8f98bfda2e9d0e6bc4b0c6db80d73051 seems a lot of stuff broke related to blending (it came in via this commit on my repo: https://github.com/libretro/mupen64plus-libretro-nx/commit/246034e0e7c2f190b05f8352351a4b41ea00a6d7 )
I have a big release tomorrow, so hints are appreciated, otherwise I will ship last known working.

I see no Shader errors reported:
```
2020/06/25,12:38:11.056,GLideN64/src/Graphics/OpenGLContext/mupen64plus/mupen64plus_DisplayWindow.cpp:59,VERBOSE, "[GlideN64]: _setAttributes"
2020/06/25,12:38:11.056,GLideN64/src/Graphics/OpenGLContext/mupen64plus/mupen64plus_DisplayWindow.cpp:78,VERBOSE, "[GlideN64]: Create setting videomode 640x480"
2020/06/25,12:38:11.057,GLideN64/src/Graphics/OpenGLContext/opengl_GLInfo.cpp:46,VERBOSE, "OpenGL major version: 4"
2020/06/25,12:38:11.057,GLideN64/src/Graphics/OpenGLContext/opengl_GLInfo.cpp:47,VERBOSE, "OpenGL minor version: 6"
2020/06/25,12:38:11.057,GLideN64/src/Graphics/OpenGLContext/opengl_GLInfo.cpp:50,VERBOSE, "OpenGL vendor: NVIDIA Corporation"
2020/06/25,12:38:11.057,GLideN64/src/Graphics/OpenGLContext/opengl_GLInfo.cpp:68,VERBOSE, "OpenGL renderer: GeForce GTX 1060 6GB/PCIe/SSE2"
2020/06/25,12:38:11.137,GLideN64/src/Graphics/OpenGLContext/ThreadedOpenGl/RingBufferPool.cpp:122,VERBOSE, " Increasing buffer size from 102400 to 1048576"
2020/06/25,12:38:11.290,GLideN64/src/GBI.cpp:472,VERBOSE, "Load microcode (RSP Gfx ucode F3DZEX.NoN  fifo 2.06H Yoshitaka Yasumoto 1998 Nintendo.) type: 17 crc: 0x70a3227c romname: THE LEGEND OF ZJLDA"
```

![image](https://user-images.githubusercontent.com/13141469/85703875-133e4900-b6e0-11ea-8505-b4adef4b98a8.png)
![image](https://user-images.githubusercontent.com/13141469/85703889-176a6680-b6e0-11ea-82ee-8c6d6695cc8e.png)
![image](https://user-images.githubusercontent.com/13141469/85703909-1cc7b100-b6e0-11ea-8d47-d5e4e4aa7eb5.png)

**Comment by m4xw** [comment]
Now that I think about it, if this happens to work on your end, this might be a GL  state issue and my wrapper would require some trivial changes.
Would be nice if someone could rule that out tho.

**Comment by rez-** [comment]
A bit offtopic but what a strange romname: THE LEGEND OF Z**J**LDA ?

**Comment by m4xw** [comment]
It's a typo when I did a region patch

**Comment by standard-two-simplex** [comment]
@m4xw I can't reproduce your issues with mupen64plus 2.5.9 and gliden64 from this repository. If you're using OpenGL 4.6 the issue is likely on your end.

Can you check if it happens to you with native rects enabled, disabled or both?

Similar issues happen if `SRC1_COLOR` and `SRC1_ALPHA` are used in `GraphicsDrawer::_dualSourceBlending()` but shaders dont set/use correctly the second output via `layout(location=0, index=1) fragColor1;`. Can you check if code runs through `_dualSourceBlending()` and the correspondent if branch in `glsl_CombinerProgramBuilder.cpp`?

**Comment by m4xw** [comment]
> Can you check if it happens to you with native rects enabled, disabled or both?

Disabled by default here.
I currently suspect that I need to account for the state handling for my fork, just hoped it wouldn't be that, didn't have to update it since a year.

I could check `_dualSourceBlending` when i get home in 4h+

**Comment by m4xw** [comment]
Seems i actually had the function in my GL state wrapper and there was a bug that went unnoticed up until now because it wasn't in use.

```
   gl_state.blendfunc_separate.used     = true;
   gl_state.blendfunc_separate.srcRGB   = sfactor;
   gl_state.blendfunc_separate.dstRGB   = dfactor;
   gl_state.blendfunc_separate.srcAlpha = sfactor;
   gl_state.blendfunc_separate.dstAlpha = dfactor;
   glBlendFunc(sfactor, dfactor);
```
Must've totally brainfarted that when doing some copy pasta when I first wrote the core....
That's some 5am coding right there
