### ISSUE TITLE
AppVeyor mupen64plus x86 package name is incorrect

### ISSUE THREAD

**Issue by oddMLan** [gonetz/GLideN64#2302]
![imagen](https://user-images.githubusercontent.com/7278372/86391015-f230a780-bc4d-11ea-8a11-a274ed1f6e05.png)

It should be
build\GLideN64-2f5280c8-for-Mupen64Plus.7z

In my own fork the names are correct
https://ci.appveyor.com/project/oddMLan/gliden64/builds/33647928/artifacts
![imagen](https://user-images.githubusercontent.com/7278372/86391766-2ce70f80-bc4f-11ea-9413-c3dabf2c755c.png)

Please make sure that Mupen64PluginsDir variable isn't being overridden in AppVeyor's web interface 

https://www.appveyor.com/docs/build-configuration/
- Environment variables. Variables defined on UI are getting merged with those ones defined in appveyor.yml. **Variable values with the same names are getting overridden with values from UI.**

**Comment by gonetz** [comment]
Yes, I had Mupen64PluginsDir variable defined in AppVeyor's web interface. Removed.
