### ISSUE TITLE
Zelda HD HUD elements look off

### ISSUE THREAD

**Issue by GhostlyDark** [gonetz/GLideN64#2303]
HD textures for HUD elements look a bit off. The magic bar gauge (OoT + MM) has too much height. The shadow of the "ammo numbers" (OoT + MM) is too much, especially on the top. Text like MM "Dawn of the X Day" looks off where the seaming is (same on Boss titles for OoT and MM). Icons in MM when picking up items have their shadow cut off.

I haven't figured out which version exactly introduced this. I suspect this issue was introduced a month or two ago.

![magic-bar](https://user-images.githubusercontent.com/31742919/86531388-03351f00-bec1-11ea-894b-5e066a1596b7.png)
![ammo-numbers](https://user-images.githubusercontent.com/31742919/86531389-03351f00-bec1-11ea-8b20-203647775004.png)
![dawn](https://user-images.githubusercontent.com/31742919/86532088-5b6f1f80-bec7-11ea-8fdb-ca5ff7a176c9.png)
![pickup-icons-mm](https://user-images.githubusercontent.com/31742919/86531392-03cdb580-bec1-11ea-937c-ceec8cc06ab3.png)

**Comment by standard-two-simplex** [comment]
@GhostlyDark Can you post the textures, please?

**Comment by GhostlyDark** [comment]
These are for Majora's Mask. Heart Piece icon and ammo numbers work in Ocarina of Time as well (MAJORA'S MASK#... -> THE LEGEND OF ZELDA#...). Included both SD and HD versions.

[HUD-Elements.zip](https://github.com/gonetz/GLideN64/files/4913403/HUD-Elements.zip)

**Comment by standard-two-simplex** [comment]
Please, check if this build solves the issues. https://github.com/gonetz/GLideN64/pull/2306/commits/885aedfc41b3d4e5a45a49fcae220099184b4703

Can't test if my code broke the heart piece shadow easily. If it is still broken, can you give me a savestate where it shows?

**Comment by GhostlyDark** [comment]
The text for Bosses and "Dawn of the Xth Day" look correct now. The magic bar and the ammo numbers are correct now as well.
The icons still have the exact same issue as before.

PJ64 32-bit, Majora's Mask (USA) Savestate: Picking up a Heart Piece
[mm-hc.pj.zip](https://github.com/gonetz/GLideN64/files/4914459/mm-hc.pj.zip)

**Comment by standard-two-simplex** [comment]
I updated the PR. The heart piece issue is fixed.

The problem was that the size of original texture was 24x24 and the size of the HD texture 256x256. That is, the HD texture is 10.66666 times bigger in each dimension. `hdRatio` was being computed in integers, thus, rounded down to 10, which meant only the 240x240 part of the texture was being used.

Now any HD texture size should work. Still, I would recommend making the HD textures 2x, 4x, 8x ... of the original size to avoid potential issues with mirroring and wrapping, because the N64 only mirrors and wraps in power of two boundaries.

**Comment by GhostlyDark** [comment]
That particular icon is Nerrel's fault :)

The PR seems to fix the issues without any downsides. I use that build from now on when doing texture work, so I should notice any regressions.

**Comment by GhostlyDark** [comment]
Fixed by #2306
