### ISSUE TITLE
Threaded video locks MSVC version of mupen64plus-ui-console (white window)

### ISSUE THREAD

**Issue by Jj0YzL5nvJ** [gonetz/GLideN64#2319]
As the title says, "ThreadedVideo = True" leaves the emulator in a perpetual locked state.
https://0x0.st/iYCR.png

[It can be tested by putting together this Frankenstein.](https://github.com/mupen64plus/mupen64plus-core/issues/651#issuecomment-618239512)

Or using these:

Custom build: [mupen64plus_v2.5.9-81-g729ea2e2_x86_v141_xp_Release.7z](https://i.fiery.me/WTYE3.7z)
<details>
  <summary>Details</summary>

```
Size:  1702617 bytes

CRC32:  2c62804a
MD5:  5686fcce03e92255adb9912b1fbd4e2b
SHA1:  415f19cfe2f20cc57e3c70bafbc72c2b9c02706b
TIGER:  9bc3c8e537382aeaa035876e44c223cd2c60ce1cc13cf923
SHA256:  24e9993472ab4f1ec200fe08ac5a3ef337bc57ef28f220a6c75e2441c35e908f
SHA512:  46bf91953ee66a89e907426955850077e83bb70a7e8ec0243d14e5792161068b9523c1473cd6ba2a716de0526db476a702740d5760309a7b6b1c3a3e8a3f6c3a
```
</details>

Custom build: [mupen64plus_v2.5.9-81-g729ea2e2_x64_v141_xp_Release.7z](https://i.fiery.me/PxP6N.7z)
<details>
  <summary>Details</summary>

```
Size:  1952199 bytes

CRC32:  82c8e052
MD5:  77cf209011dfaf7f811f7ea181fa2443
SHA1:  79a4b2217b6be67556aa56b1c4c67d0ee6aa7435
TIGER:  d6f5266b46be5c0ae01b5b900d906f571352aa2b0efd586b
SHA256:  58a1f5fa61801722b340c0d9d758375cf4cdfb28c792db6ab8024b481bb92b48
SHA512:  69d6a7f9476215ab576a6825a51d71d28d5b7ff51b3c3101227711a701c30c7b3d419458dd7f2aa330c46cb2a355ab178fc3d7143671fbbe5a744350ca37ca57
```
</details>

**Comment by loganmc10** [comment]
This is an issue with mupen64plus, not gliden64

**Comment by Jj0YzL5nvJ** [comment]
Too many problems with MSVC, not to mention "native" ones... especially on x86
https://github.com/mupen64plus/mupen64plus-core/issues/769
