### ISSUE TITLE
Mario Tennis: wrong texture (depth?) during intro

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#232]
![marriotennis4](https://cloud.githubusercontent.com/assets/8987490/5562403/f79e164e-8e18-11e4-8eec-e08054b50e66.jpg)

This bug is in the whole intro.

**Comment by theboy181** [comment]
Turning up the Anisotropic filtering to X2 or higher seems to resolve the wrong texture depth issue for me in PJ64

**Comment by theboy181** [comment]
I am unable to use the AF mode to fix this issue since the last few updates.

**Comment by gonetz** [comment]
Fixed

**Comment by olivieryuyu** [comment]
fixed
