### ISSUE TITLE
Project 64 Crashes Upon Selecting Configure Graphics Plugin

### ISSUE THREAD

**Issue by Rockman82** [gonetz/GLideN64#2323]
I've installed all the files correctly, but when I go to configure the plugin, Project 64 crashes. Version 3.0 does this as well. I have go go all the way back to GlideN64 2.0 for it to work. Keep in mind that the plugin DOES work when I run a game, I just can't get into the graphics customization menu. I've tried removing other graphics plugins where GlideN64 4.0 is the only one available but I still get a crash. I don't know if it's hardware incompatibility, a bug, or something I'm missing. Help would be greatly appreciated. I've included the crash log below. Thank you!

2020/08/23 09:49:25.899 44308,Error,User Interface,WinMain,Exception caught (File: "main.cpp" Line: 101)

![image](https://user-images.githubusercontent.com/70102595/90981400-5ec97380-e526-11ea-9720-5903b9d09542.png)

**Comment by IronYoshi64** [comment]
This many be lack of system requirements? IDK? Also in the GLideN64.ini file, maybe try to turn off the option Threaded video or so? I don't know if that will help, but I heard it sometimes does for crash issues for some folks.

**Comment by oddMLan** [comment]
Don't download GLideN64 and put it in the Plugins folder, use the one that comes bundled with Project64. Does that one crash as well?

**Comment by Rockman82** [comment]
> 
> 
> This many be lack of system requirements? IDK? Also in the GLideN64.ini file, maybe try to turn off the option Threaded video or so? I don't know if that will help, but I heard it sometimes does for crash issues for some folks.

I'll give this a try. My computer has a Ryzen 7 3700X, a GTX 1660 and 16gb of ram, so I doubt it's specs. Unless perhaps it's an AMD or Nvidia conflict? I'll give the threaded video option a try.

**Comment by oddMLan** [comment]
>And no, the Glide that comes with the emulator does not crash.

Then use that one. It's the same as the latest version available in the GLideN64 repo. Or you could manually update it by going to https://ci.appveyor.com/project/gonetz/gliden64/branch/master/artifacts
Download the "WTL" version (without x64).

**Comment by Rockman82** [comment]
> 
> 
> > And no, the Glide that comes with the emulator does not crash.
> 
> Then use that one. It's the same as the latest version available in the GLideN64 repo. Or you could manually update it by going to https://ci.appveyor.com/project/gonetz/gliden64/branch/master/artifacts
> Download the "WTL" version (without x64).

Thank you! I think I'll stick with this from here on out.

**Comment by oddMLan** [comment]
If your issue is solved can you close it?
