### ISSUE TITLE
Goldeneye textures glitch

### ISSUE THREAD

**Issue by LuismaSP89** [gonetz/GLideN64#2325]
I updated Gliden64 yesterday and I've encountered some issues in Goldeneye 64. This is strange case, because in some cases it depends on the lightning (You can see the differences between image 1 and 2) This affects specially the characters and weapons textures.

This problem must started recently, since I updated Gliden64 some weeks ago until the last time yesterday.

![1](https://user-images.githubusercontent.com/12205048/92490727-a708b700-f1f1-11ea-8e13-dae09d928e72.jpg)
![2](https://user-images.githubusercontent.com/12205048/92490730-a708b700-f1f1-11ea-82f2-fa2ec844988f.jpg)
![3](https://user-images.githubusercontent.com/12205048/92490723-a53ef380-f1f1-11ea-808e-92741893f286.jpg)
![4](https://user-images.githubusercontent.com/12205048/92490724-a6702080-f1f1-11ea-9d33-641cb2687413.jpg)

Specs: Windows 10 x64
16 GB DDR3
GTX 970   4GB GDDR5
i7 4790k

Using Project64 x86 nightly build (Tested also with other versions with same result)

Also deleted all the texture cache data for the plugin.

**Comment by MojoJojoDojo** [comment]
I also got issues with the latest m64p .
I got sky textures on the walls for some reason.

**Comment by Jj0YzL5nvJ** [comment]
@MojoJojoDojo, that happens when you use widescreen hacks in a game with native anamorphic widescreen support... pay attention to the ammunition.
https://imgur.com/a/ITFDqXl

**Comment by Jj0YzL5nvJ** [comment]
https://youtu.be/eM16F_dM1Js

**Comment by standard-two-simplex** [comment]
Fixed in master

**Comment by LuismaSP89** [comment]
Yes, thank you. Closing then : )
