### ISSUE TITLE
default config revert

### ISSUE THREAD

**Issue by Nes-player4Life** [gonetz/GLideN64#2330]
disabling textures and save and close sets:

textureFilter\txCachePath
textureFilter\txDumpPath
textureFilter\txPath

to the same directory and it is very problematic in dumping as it always dumps to the loading folder.

per game settings also override user-defined

**Comment by gonetz** [comment]
Please explain the problem in details. I don't get what is wrong.

**Comment by Nes-player4Life** [comment]
![image](https://user-images.githubusercontent.com/10325597/93804841-df0df200-fc14-11ea-9ceb-4ecd1a633172.png)
In Project 64 menu without emulation.

![glidn64](https://user-images.githubusercontent.com/10325597/93805083-37dd8a80-fc15-11ea-99f7-c31a9b0835af.png)
 In game.
The options don't stick. Defaults don't stick at the next load either.

**Comment by oddMLan** [comment]
Might be a bug in the WTL interface. Try using the Qt version to confirm if the same problem happens there
https://ci.appveyor.com/project/gonetz/gliden64/branch/master/artifacts.

**Comment by Nes-player4Life** [comment]
using 229xxxxx

**Comment by oddMLan** [comment]
It's a bug in the WTL interface then. I'll try submitting a patch soon.

**Comment by oddMLan** [comment]
@Nes-player4Life Try the newest WTL build again, it should fix the reported issue
