### ISSUE TITLE
toggle textures off (request)

### ISSUE THREAD

**Issue by Nes-player4Life** [gonetz/GLideN64#2331]
toggle textures off key.

we have a refresh key (R)
we have a dump key (D)
if we could have a texture toggle (T) it would be nice.

**Comment by gonetz** [comment]
Do you mean toggle between original and hires?

**Comment by IronYoshi64** [comment]
I think this would be a very nice addition as well! Dolphin has a thing like this, it will be nice to see this in N64 as well.

**Comment by Nes-player4Life** [comment]
> 
> 
> Do you mean toggle between original and hires?

yes, sometimes I find myself clicking to the gfx plugin often in texture development to compare alignment. If we could hotkey the Hires texture option on/off it would be a time saver for artists.

**Comment by Nes-player4Life** [comment]
> 
> 
> 
> 
> > Do you mean toggle between original and hires?
> 
> yes, sometimes I find myself clicking to the gfx plugin often in texture development to compare alignment. If we could hotkey the Hires texture option on/off it would be a time saver for artists.
> 
> ![GlideN64](https://user-images.githubusercontent.com/10325597/93803963-97d33180-fc13-11ea-87f0-4d9adc9b3b05.gif)

**Comment by gonetz** [comment]
Well, it seems it is time to finally implement #1497 and add this one to the list.

**Comment by gonetz** [comment]
I started to work on hotkeys, see #1497
Toggle HD textures hotkey is implemented.
I close this task. Please report in #1497, if something does not work right.
