### ISSUE TITLE
Zelda Majora's Mask - Town Shooting Gallery Missing Effects

### ISSUE THREAD

**Issue by marigi64** [gonetz/GLideN64#2340]
Very minor issue but in Majora's Mask, the X and O sprites are not displayed in the town shooting gallery minigame when hitting octoroks.

Original Hardware:
https://youtu.be/OZI2ywAm9zg?t=67

GLideN64:
![MM-GLide](https://user-images.githubusercontent.com/53112738/94329953-e6614100-0002-11eb-9611-e6998cc440eb.gif)

**Comment by gonetz** [comment]
It is not a minor issue. Thanks for the report.

**Comment by Nerrel** [comment]
I managed to fix this issue with custom textures.  I dumped the X+O from GameCube version and noticed two black textures in the GlideN64 dumps that matched:  ZELDA MAJORA'S MASK#026EFBC3#4#2_all  and  ZELDA MAJORA'S MASK#363815D2#4#2_all.  After replacing them the effect reappeared... I'm not sure what's turning the default textures black, but hopefully the fact that custom textures work helps figure the issue out.  
![image of effect](https://live.staticflickr.com/65535/51187776247_1caeda20ae_b.jpg)

**Comment by standard-two-simplex** [comment]
@Nerrel Do you mind posting the texture that makes the effect work?

**Comment by Nerrel** [comment]
Sure, I should have done that last time
[XO.zip](https://github.com/gonetz/GLideN64/files/6834958/XO.zip)

**Comment by gonetz** [comment]
@Nerrel Thanks!
Your textures have format 4 size 2, that is 16bit I (intensity) texture.
Such format just is not supported in the code. 
I'll check if the game really uses such textures and fix it.

Btw, I'm trying to find a thread, where you complained that hd textures from your Zelda MM pack look blurry with the new version of GLideN64. There was an explanation, what causes that effect. Could you point me on that thread?

**Comment by GhostlyDark** [comment]
@gonetz I assume you are referring to this: https://github.com/gonetz/GLideN64/pull/2528#issuecomment-882089289
The complaints are adressed by https://github.com/gonetz/GLideN64/pull/2593 via "inaccurate texture coordinates" option. Activating that option fixes all the mentioned misalignments.

**Comment by Nerrel** [comment]
Right, everything seems to be fixed by the inaccurate texture coordinates option and users of the texture pack should be able to use the regular builds again as long as that option is enabled.  Thanks for merging that in!

The dumps I provided were straight from Dolphin, I assume they match what the N64 game used but I think every now and then there are slight differences between N64/GC/Wii VC.  Admentus and GhostlyDark would know a lot more about that kind of thing, I've only really worked on the 64 textures

**Comment by gonetz** [comment]
> @gonetz I assume you are referring to this: [#2528 (comment)]

Yes, exactly. Thanks!

>The complaints are adressed by #2593 via "inaccurate texture coordinates" option. Activating that option fixes all the mentioned misalignments.
> Right, everything seems to be fixed by the inaccurate texture coordinates option and users of the texture pack should be able to use the regular builds again as long as that option is enabled. Thanks for merging that in!

Good to know, thanks!

> The dumps I provided were straight from Dolphin, I assume they match what the N64 game used

Yes, the game really uses 16 bit I textures for X and O. It is very unusual case, as 16 bit for one color channel is a waste of resources. It was not expected and supported. Fixed in 9a6f9f6
