### ISSUE TITLE
3D models out of camera?

### ISSUE THREAD

**Issue by FelixHappyGamer** [gonetz/GLideN64#2341]
I really dont know how to explain this, but after toying around with the plugin, I did something that causes Mario 64 to get all models out of camera. For example, on the menu screen, the mario head is nowhere to be seen. I am kinda sleepy right now so I might not be explaining things the best way, but I would like to get some help.

**Comment by weinerschnitzel** [comment]
Probably should figure out what you did to break it. If you update the plugin and revert your settings is there still an issue? If you keep track of your changes, what breaks it?

**Comment by gonetz** [comment]
No answer from FelixHappyGamer 
Closed.
