### ISSUE TITLE
Absolute mess of an output in recent builds

### ISSUE THREAD

**Issue by ToruTheRedFox** [gonetz/GLideN64#2342]
Somewhere after the last stable release, this started to happen: 
![image](https://user-images.githubusercontent.com/15708278/94374983-2d852a00-0108-11eb-9076-1c5efcf0e571.png)
![image](https://user-images.githubusercontent.com/15708278/94374985-370e9200-0108-11eb-88c7-608cc868e2e0.png)
GPU: Intel HD Graphics 4000
OS: Windows 7
Emulator: Project64 2.3.2.202

**Comment by Rosalie241** [comment]
what gliden64 version exactly?

**Comment by gonetz** [comment]
Can it be a problem with Intel drivers? Does the last stable release work fine for you? Do you use the same plugin settings for stable and for current builds?

**Comment by ToruTheRedFox** [comment]
the last stable release (4.0) works fine with the very same settings yes

I'm not sure when this started to happen, but it was quite a while back as I've gone quite a bit back with builds and the issue still persists

**Comment by standard-two-simplex** [comment]
I tested with my old Intel Card. I have two issues.
a42e34f1 creates the black dots, probably because of the workaround removed. I though the problem was the equal function. Is it perhaps it is the matrix times vector multiplication?
c48841cf shows a black screen. boolean dual_source_blending is true because I'm on standard GL, but I guess the drives don't support dual source blending.

**Comment by standard-two-simplex** [comment]
Apparently intel drivers don't compute STVEC properly with the current code. Odd, I can't see a mistake in it.

@ToruTheRedFox Please, test the build in the pull request.

**Comment by ToruTheRedFox** [comment]
it works


although this has led me to notice that the dither pattern is not accurate to hardware, and looks like standard ordered dithering

**Comment by gizmo98** [comment]
Do you have  comparison  screenshots?

**Comment by ToruTheRedFox** [comment]
GLideN64
![image](https://user-images.githubusercontent.com/15708278/95674955-a5912c80-0bab-11eb-841a-87dcb9553383.png)
![image](https://user-images.githubusercontent.com/15708278/95675057-48e24180-0bac-11eb-977c-89ffd44d7655.png)

AngryLion
![image](https://user-images.githubusercontent.com/15708278/95674994-d709f800-0bab-11eb-8502-a989780c5424.png)
![image](https://user-images.githubusercontent.com/15708278/95675004-f012a900-0bab-11eb-9451-169c9caf0a63.png)

**Comment by ToruTheRedFox** [comment]
the dither pattern looks to be scaled without regarding the aspect ratio too, or at least at an uneven scale

**Comment by oddMLan** [comment]
But the original issue is fixed no? Close this ticket & you can open a new ticket for the dithering if you feel that it's not accurate.
My personal tip is, enable 5-bit quantization for dithering if it's not enabled already and that should get it to look more accurate.

**Comment by ToruTheRedFox** [comment]
the original issue is fixed yes
