### ISSUE TITLE
How can I use Texture Enhancement options and Halos Removel in the Linux Version for Mupen64Plus?

### ISSUE THREAD

**Issue by Toadfield** [gonetz/GLideN64#2347]
I used it in the past for Project 64,but I switched to Linux M64P and now I can't find those settings.

**Comment by oddMLan** [comment]
m64p uses a custom fork of GLideN64 which removes those options.

**Comment by Toadfield** [comment]
Thanks,so can I install the normal GlideN64 somehow and use it in M64P or do I have to use another graphical frontend?
Because if I try to install GlideN64 then I get an error message that says that they both conflict.

**Comment by oddMLan** [comment]
I think so. But you need to compile it yourself? (unsure about this)
@Rosalie241 hey, is the buildbot set up yet to make Mupen64Plus with GUI for Windoze?

**Comment by Rosalie241** [comment]
My GUI isn't done yet, yes it's hooked up to appveyor already but it's not ready for end-users yet.

**Comment by Jj0YzL5nvJ** [comment]
CLI users:
Build script: https://gist.github.com/Jj0YzL5nvJ/5242753837eed35768e61c240f572ecd
Angrylion-Plus examples: https://imgur.com/a/NpXxWh7
