### ISSUE TITLE
Frames missing from scoreboards on some courts

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#235]
![capture](https://cloud.githubusercontent.com/assets/9299743/6173068/ff1d626c-b299-11e4-8981-e262da74396b.PNG)

**Comment by gonetz** [comment]
Scoreboard is technically hard to emulate. Proper emulation breaks other  things. Currently it is hacked and works only on some courts.

**Comment by theboy181** [comment]
how does this hack work, and why does is it a challenge?

**Comment by gonetz** [comment]
I described in the blog how Scoreboard is programmed.
It's hard to explain why is it a challenge. The game uses lots of fb effects and it is very hard to support them all properly.

**Comment by gonetz** [comment]
Please test with latest version.

**Comment by theboy181** [comment]
checked a few courts. looked good.
