### ISSUE TITLE
Compile help neeeded

### ISSUE THREAD

**Issue by PimpUigi** [gonetz/GLideN64#2351]
Following the "Build for windows" guide, only the Visual Studio 2013 instructions let me select a QT-Static

However when I try to compile ... I get 13 errors in Textures.cpp : (
I was having issues with GlideNUI.cpp as well but when I added #include < memory> to the top, that compiled fine.
Now I'm completely out of "well maybe if I..."s and I need to ask for help.

![image](https://user-images.githubusercontent.com/7344271/95346206-93e91580-0889-11eb-8aeb-f088eff3a60c.png)

**Comment by PimpUigi** [comment]
Steps to Compile reliably:
1. Install VS 2013
2. Download and install QT Tools VS 2013 Add In from here https://marketplace.visualstudio.com/items?itemName=TheQtCompany.QtVisualStu
3. Download QT-Static for VS 2015
4. Install VS 2017
5. Open VS 2013
6. Select 2015 as the default QT version
7. Open VS 2017
8. Add Universal Windows Platform Development, Desktop Development with C++, Game Development With C++ and check the optional boxes for any Windows 8.1 SDK's
9. Open GLideN64.sln with VS 2017
10. Set Solution QT version to 2015
11. Set to ReleaseQT win32
12. Build GlideNUI
13. Build Solution

**Comment by gonetz** [comment]
It's quite strange that you had to take so winding path. Most of people run directly by "lazy" path for VS 2017 with no issue.

**Comment by PimpUigi** [comment]
I think that path _would work_ (as long as you checked boxes for workloads) except I could only select the 2015 and 2017 Static's with VS 2013. God only knows why. And then they'd be selected in 2017. (this method did not compile in VS 2015)

When it was only the 2017 Static in the list, I get an error when I change the QT Solution, so both had to be there. It was crazy. : (

**Comment by Jj0YzL5nvJ** [comment]
[GLideN64_builder.cmd](https://gist.github.com/Jj0YzL5nvJ/af564b9304ee4f15408951d7e4e530e8)

Guidance:
```
type GLideN64_builder.cmd  | find "defined"
type GLideN64_builder.cmd  | find "%1"
type GLideN64_builder.cmd  | find "curl"
etc...
```

Examples:
```
set ARCH=x86
set QTDIR_x86=D:\QT
set QT_BUILD_x86=qt-5_7_1-x86-msvc2015-static
GLideN64_builder.cmd
```

```
set ARCH=x86
set QTDIR_%ARCH%=D:\Static_Qt_%ARCH%
set QT_BUILD_%ARCH%=qt-5_7_1-%ARCH%-msvc2017-static
GLideN64_builder.cmd
```

```
set PATH=D:\curl-7.67.0-win64-mingw\bin;%PATH%
set ARCH=x64
set TOOLSET=v141
GLideN64_builder.cmd --all
```

**Comment by gonetz** [comment]
@Jj0YzL5nvJ Cool! May be add it to GLideN64 repository?

**Comment by Jj0YzL5nvJ** [comment]
Okay, just let me adapt it to work in a friendly way to the repository.
