### ISSUE TITLE
Inaccurate dithering matrices

### ISSUE THREAD

**Issue by ToruTheRedFox** [gonetz/GLideN64#2359]
The matrices for dithering aren't accurate to hardware. The N64 doesn't use typical dithering matrices like most PC games and the PS1 for example.

GLideN64:
![image](https://user-images.githubusercontent.com/15708278/95883570-0159e200-0d73-11eb-9df8-07cb6d3a165c.png)

AngryLion/hardware:
![image](https://user-images.githubusercontent.com/15708278/95883743-2fd7bd00-0d73-11eb-90a7-63ad19f13d49.png)

**Comment by ToruTheRedFox** [comment]
Although I do think that the ordered-like matrices should be an option for those who prefer them.

**Comment by gizmo98** [comment]
Maybe this happens because we use a real 4x4 bayer matrix if bayer dithering is selected. And as you can see the result looks like dithering with a bayer matrix 😉. Angrylion‘s bayer matrix/pattern didn‘t look like a real bayer matrix so i did not use it.

**Comment by ToruTheRedFox** [comment]
it should be an option for accuracy

**Comment by gizmo98** [comment]
Yeah. Programming manual tells me a 4x4 bayer matrix is used but angrylion‘s matrix does not look like a bayer matrix. Which documentation is right? It is easy to add another 4x4 matrix. So we can check if angrylion‘s matrix produces the same result.

**Comment by ToruTheRedFox** [comment]
the AngryLion matrix looks to be accurate to the real hardware to me (different game but same pattern is visible)
![image](https://user-images.githubusercontent.com/15708278/95889152-f787ad00-0d79-11eb-8273-7dd0b876cba1.png)

**Comment by ToruTheRedFox** [comment]
on hardware, the dithering is blurred by the VI filter, making it create a flat colour or a smooth gradient

**Comment by ToruTheRedFox** [comment]
unless you get rid of it with hardware mods that is

**Comment by ToruTheRedFox** [comment]
I mean it's just FXAA with depth based edge finding and a slight horizontal blur

**Comment by gizmo98** [comment]
A slight horizontal blur would remove dithering fragments. Angrylion bayer matrix looks worse even with blur applied. 
![Dither Comparison 12](https://user-images.githubusercontent.com/6412699/96109715-3be08d80-0edf-11eb-8374-44880137f11a.PNG)
![Dither Comparison 10](https://user-images.githubusercontent.com/6412699/96109718-3d11ba80-0edf-11eb-9a09-b59f98edef4b.PNG)

![Dither Comparison 11](https://user-images.githubusercontent.com/6412699/96109716-3c792400-0edf-11eb-9388-32b76a2c14a0.PNG)

![Dither Comparison 13](https://user-images.githubusercontent.com/6412699/96109711-3aaf6080-0edf-11eb-9f57-ab69a5d6a464.PNG)

**Comment by oddMLan** [comment]
I wonder why they bothered with the blurring step, it looks worse and dithering is not even that noticeable in a CRT.

**Comment by ToruTheRedFox** [comment]
idk either

**Comment by gizmo98** [comment]
@oddMLan 
I read somewhere n64 dither filter should not blur 2D elements too much. I modified blur filter like color = texel(x-1)*0.25 +texel(x)*0.5 + texel(x+1)*0.25. Dithering disappears or looks smoother but 2D elements do not look to much blurred.

![Dither Comparison 12 - b2](https://user-images.githubusercontent.com/6412699/96437277-78c1c280-1206-11eb-9059-8a397223dea0.PNG)
![Dither Comparison3 - b2](https://user-images.githubusercontent.com/6412699/96437636-8ecf8300-1206-11eb-846c-a9ced17a3d6c.PNG)
![Dither Comparison 14 - b2](https://user-images.githubusercontent.com/6412699/96437363-7e1f0d00-1206-11eb-9d41-170349327a02.PNG)
![Dither Comparison22 + b2](https://user-images.githubusercontent.com/6412699/96439805-541a1a80-1207-11eb-9749-df4a669a4c1f.PNG)

**Comment by gizmo98** [comment]
Here are some real ingame blur screenshots. I replaced fxaa shader with the above mentioned blur shader. It does not look so bad. I like the idea to enable blur and aa if a game requests these vi features. The right bayer matrix could be added as well.

Without Blur:
![starfox64-535](https://user-images.githubusercontent.com/6412699/96497827-88afc580-124b-11eb-9dc4-fe10a4e0970f.png)
With Blur:
![starfox64-509](https://user-images.githubusercontent.com/6412699/96497731-67e77000-124b-11eb-82a6-8cac0df09a02.png)

Without Blur:
![starfox64-539](https://user-images.githubusercontent.com/6412699/96497897-a2510d00-124b-11eb-8e46-eb7c561aa1a7.png)
With Blur:
![starfox64-513](https://user-images.githubusercontent.com/6412699/96497924-aaa94800-124b-11eb-9ebb-b2f46cfa3f68.png)

Without Blur:
![super_mario_64-041](https://user-images.githubusercontent.com/6412699/96498354-40dd6e00-124c-11eb-99b2-2f1a7e696332.png)
With Blur:
![super_mario_64-035](https://user-images.githubusercontent.com/6412699/96498327-34f1ac00-124c-11eb-9691-e46901731b53.png)

Without Blur:
![super_mario_64-042](https://user-images.githubusercontent.com/6412699/96498580-8732cd00-124c-11eb-847a-c59458b6a1a1.png)
With Blur:
![super_mario_64-036](https://user-images.githubusercontent.com/6412699/96498556-7d10ce80-124c-11eb-9dbc-3db484b0c4ad.png)

Without Blur:
![super_mario_64-043](https://user-images.githubusercontent.com/6412699/96498870-ebee2780-124c-11eb-840f-d6a8d99f3850.png)
With Blur:
![super_mario_64-038](https://user-images.githubusercontent.com/6412699/96498881-f0b2db80-124c-11eb-9fa1-879adb73e912.png)

**Comment by oddMLan** [comment]
Looks really close to hardware now but it should still be made optional thru the UI imo (and possibly only enable if the dithering is visible, otherwise it's moot).
Are you also giving the option for "accurate" N64 Bayer as well?

**Comment by ToruTheRedFox** [comment]
the FXAA should also use a mask so it doesn't affect 2D elements of the image, and be less noisy (N64's AA is smooth)

and maybe, if possible, but I doubt it, do the weird polygon antialiasing that the N64 does (which does real MSAA-like antialiasing, but only in places where polygons directly touch), and make the FXAA use depth differences to detect edges, rather than colors

**Comment by gizmo98** [comment]
Come on. You cannot do antialiasing with interpolation or signal filtering (blur is in the end a vertical low pass).  ;-)
FXAA needs coverage calculation and this is out of my league.

I will try to add blur alongside the current fxaa and add angrylion's bayer matrix.

**Comment by gizmo98** [comment]
@ToruTheRedFox
You can test two branches.
https://github.com/gizmo98/GLideN64/tree/blur2 has N64 bayer matrix and enables dither filter if dither filter vi register is set. There is no option atm to disable dither filter.
https://github.com/gizmo98/GLideN64/tree/n64bayer just has N64 bayer matrix.

**Comment by ToruTheRedFox** [comment]
I can't build the source myself, it just errors out in many different ways no matter what I try

**Comment by Jj0YzL5nvJ** [comment]
> I can't build the source myself, it just errors out in many different ways no matter what I try

Try with:
```
git clone https://github.com/gizmo98/GLideN64.git
cd GLideN64
git checkout blur2
curl -L -o ..\2358.patch https://github.com/gonetz/GLideN64/pull/2358.patch
git apply ..\2358.patch
start ""  projects\msvc\GLideN64_builder.cmd --x86 --noqt --nom64p
```

The script will require some external CLI tools like [7z.exe](https://www.7-zip.org/), [git.exe](https://git-scm.com/download/win) and [curl.exe](https://curl.haxx.se/windows/) in [PATH](https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/) (`rundll32 sysdm.cpl,EditEnvironmentVariables`).

If it fails at compile time after that, your Visual Studio installation is incomplete or corrupted.
Visual Studio installer does not work OOTB by clicking next, next ...install. In fact, if you do that, you will get an incomplete and mostly useless installation, guaranteed.

**Comment by ToruTheRedFox** [comment]
nah my VS installation is fine as it builds everything else fine

it just can't get the git revision and a few static libraries for some reason

**Comment by Jj0YzL5nvJ** [comment]
> nah my VS installation is fine as it builds everything else fine

So does that mean you can build Project64?
BTW, I recently fixed a bug related to the revision script for GLideN64... #2354

**Comment by ToruTheRedFox** [comment]
I haven't tried building Project64 because I didn't have the need to

but I have built AngryLion before

**Comment by Jj0YzL5nvJ** [comment]
Project64 may fail to generate `Version.h` in similar fashion to GLideN64. Angrylion-Plus is unexpectedly tolerant to revision failures...

Wrong revision: https://i.pinimg.com/originals/05/dc/2f/05dc2fa43266c99d47c2d63e8a43d213.png
Expected revision: https://i.imgur.com/7oP8Ux6.png

**Comment by gizmo98** [comment]
@ToruTheRedFox 
The right pattern should be in master now. I tested it with dither test software http://mattpierce.info/n64-dither.
![-102](https://user-images.githubusercontent.com/6412699/97804611-60639600-1c51-11eb-8a39-51107d66b9bc.png)

My dither filter also does not look so bad. I added logic which does not blur text:
![-105](https://user-images.githubusercontent.com/6412699/97804652-986ad900-1c51-11eb-8c43-6fce998e2dd8.png)

Without this logic text and 2D elements look bad:
![-098](https://user-images.githubusercontent.com/6412699/97804831-9ce3c180-1c52-11eb-89e7-05f584a1c170.png)

**Comment by ToruTheRedFox** [comment]
I still get the old pattern for some reason (I use "Render N64 framebuffer to output")

**Comment by gizmo98** [comment]
NativresFactor = 1 and RDramDithering is off?

**Comment by ToruTheRedFox** [comment]
my configuration is this
![image](https://user-images.githubusercontent.com/15708278/97810594-dfb29300-1c6c-11eb-9814-801c77e0e279.png)

**Comment by gizmo98** [comment]
Please enable „Dithering pattern on output image“ and „5Bit quantization“. Disable RDRam dithering. These settings are most accurate because dithering is only used if a application requests ist. RDRam Dithering option is only usefull for framebuffer effects if higher resolutions are used.

**Comment by ToruTheRedFox** [comment]
I'm still not getting correct results
![image](https://user-images.githubusercontent.com/15708278/97810858-d1657680-1c6e-11eb-8e16-902f393851b8.png)

**Comment by gizmo98** [comment]
@ToruTheRedFox 
I thought about it. I also used a real magic square matrix instead of angrylions matrix. With angrylions matrix it looks like this:
![super_mario_64-113](https://user-images.githubusercontent.com/6412699/98030422-4375c100-1e11-11eb-9221-b660a58432d1.png)

With blur:
![super_mario_64-110](https://user-images.githubusercontent.com/6412699/98030501-643e1680-1e11-11eb-87e0-d50bb349cc81.png)
 
Angrylion's magic square matrix can be found in this branch: 
https://github.com/gizmo98/GLideN64/tree/blur3

**Comment by oddMLan** [comment]
> My dither filter also does not look so bad. I added logic which does not blur text, and borders/edges:
Is it possible to add this logic to the FXAA filter?

**Comment by gizmo98** [comment]
In my blur2 (always on) and blur3 (ini option, default off) branches it is a post filter which runs after fxaa.

**Comment by gizmo98** [comment]
Can one of you verify it looks better or accurate now?

**Comment by ToruTheRedFox** [comment]
from the screenshots you posted, it does, but as I can't compile it myself due to missing dependencies that I don't have the drive space for, I can't test it myself either

**Comment by gonetz** [comment]
> I can't compile it myself due to missing dependencies that I don't have the drive space for, I can't test it myself either

This fix is in the master now, so you may download necessary build from AppVeyor: https://ci.appveyor.com/project/gonetz/gliden64/branch/master

**Comment by ToruTheRedFox** [comment]
except it isn't

I checked

**Comment by ToruTheRedFox** [comment]
dither is the same as it has been

**Comment by ToruTheRedFox** [comment]
well the matrix is there, but it's still not drawing correctly for me (yet another Intel issue?)

**Comment by ToruTheRedFox** [comment]
I don't think the dither texture is being applied with the correct UVs to the output (framebuffer dither works fine)
![image](https://user-images.githubusercontent.com/15708278/98849809-b0a9d780-244b-11eb-8901-848e543c3db7.png)

**Comment by gizmo98** [comment]
Mario64 seems to use magic square pattern. I have angrylion‘s ms pattern in my branches. The result can be seen above. I will do a PR if someone tells me the pattern is right now.

@gonetz appveyor can only be used for upstream/master? I use a linux buildscript for testing. No option for W64/Project64 Users.

**Comment by oddMLan** [comment]
AppVeyor allows building PRs, but gonetz explicitly disabled the feature for whatever reason

**Comment by gonetz** [comment]
> gonetz explicitly disabled the feature for whatever reason

and now can't remember why.

**Comment by rez-** [comment]
wasnt that because of the website? so that you will download latest master and not some PR?

**Comment by gonetz** [comment]
> wasnt that because of the website? so that you will download latest master and not some PR?

No. The link in README.md points to master branch builds.

**Comment by gonetz** [comment]
Should not this issue be closed? 93ddc890e, ec02cc7

**Comment by ToruTheRedFox** [comment]
oh right

**Comment by oddMLan** [comment]
@gizmo98 did you forget to submit the dither filter? I don't see glsl_DitherFilter.cpp in the source tree

**Comment by gizmo98** [comment]
@oddMLan I was not sure if this feature will be used. Gonetz removed blur post processing a long time ago. Dither filter is more adaptive and will not smooth out edges or transitions to 2D elements. 
@gonetz Shall i do open a PR for dither filter feature?

**Comment by fzurita** [comment]
@gizmo98  I tried your dither post processing step in Android and I'm not really seeing much of a difference compared to regular output. Even at 1x resolution.

Is the difference really hard to see?

**Comment by gizmo98** [comment]
@fzurita 
Branch blur2?
You should see it at 1x and 2x native res in Mario64, Lylat Wars, Mario Golf and Castlevania if dithering is enabled.

**Comment by fzurita** [comment]
I used blur3 branch.

**Comment by fzurita** [comment]
Raising the "limit" value to 0.8 makes the effect much more noticeable. I couldn't notice any blur without raising that value.

**Comment by gonetz** [comment]
> @oddMLan I was not sure if this feature will be used. Gonetz removed blur post processing a long time ago. Dither filter is more adaptive and will not smooth out edges or transitions to 2D elements.
> @gonetz Shall i do open a PR for dither filter feature?

I removed my implementation of blur post processing because it was hard to port on the new architecture.  Not a big loss. Reshade has better blur filter. Dither filter is more N64 specific, I have no objections against it. I would like to see comparison screen shots though, with pointers where to look at :)

**Comment by gizmo98** [comment]
@fzurita
It's really just a slight effect to blur dithering a little bit. You can use dither test rom http://mattpierce.info/n64-dither to enable and disable filter at runtime to see the effect. I just use the vertical values of a gauss filter at the moment. The vertical values of a average filter blur more.

@gonetz i will make some screenshots.

A not so accurate solutions would be to use bilateral filtering:
https://www.shadertoy.com/view/4dfGDH
