### ISSUE TITLE
Star Fox 64 Star field starts not correct (too big?)

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#236]
GLideN64
![capture](https://cloud.githubusercontent.com/assets/9299743/6173156/c6a9abec-b29a-11e4-9601-8b3e3338721b.PNG)
AngryLion's
![capture2](https://cloud.githubusercontent.com/assets/9299743/6173184/fbae915e-b29a-11e4-805b-9ebbbcc4df0a.PNG)
Jabo Direct3D8
![captur3e](https://cloud.githubusercontent.com/assets/9299743/6173309/adef964c-b29b-11e4-8422-cfa212c77402.PNG)

You can see  when they are rendered in GLideN64 HLE they don't render correctly.

**Comment by gonetz** [comment]
Fixed.
Please test and close if resolved.

**Comment by theboy181** [comment]
much better!!
