### ISSUE TITLE
Hardware depth buffer emulation lockups up the display list on Smash Brothers

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#2362]
With Smash Brothers, if hardware depth buffer emulation is enabled, pushing "Start" on the Nintendo/HAL log causes the image to freeze up, but sounds can still be heard from the game.

This is 100% reproducible in all configurations I have tried so far. This does not happen if software depth buffer emulation is enabled.

**Comment by loganmc10** [comment]
Yes this is a very old issue I believe, a duplicate of: https://github.com/gonetz/GLideN64/issues/1433

**Comment by fzurita** [comment]
Ok, I'll close it then.
