### ISSUE TITLE
Undefined behaviour

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#2364]
m64p now includes built-in netplay, I'm trying to debug a few desync issues. GLideN64 has quite a few cases of executing undefined behaviour. This is a real problem for netplay, since each client may execute the game differently, which can lead to desyncs.

Here are some of the cases I've found:

```
/home/logan/m64p/GLideN64/src/3DMath.h:45:28: runtime error: left shift of negative value -2
/home/logan/m64p/GLideN64/src/DepthBufferRender/DepthBufferRender.cpp:43:22: runtime error: left shift of negative value -233054
/home/logan/m64p/GLideN64/src/DepthBufferRender/DepthBufferRender.cpp:231:20: runtime error: signed integer overflow: 2068005055 + 125409073 cannot be represented in type 'int'
/home/logan/m64p/GLideN64/src/gDP.cpp:1330:19: runtime error: left shift of 2752524 by 16 places cannot be represented in type 'int'
/home/logan/m64p/GLideN64/src/gDP.cpp:1338:23: runtime error: left shift of negative value -1
/home/logan/m64p/GLideN64/src/gDP.cpp:1348:20: runtime error: left shift of negative value -41746796
/home/logan/m64p/GLideN64/src/gDP.cpp:1351:23: runtime error: left shift of negative value -3
/home/logan/m64p/GLideN64/src/gDP.cpp:1354:23: runtime error: left shift of 131071 by 16 places cannot be represented in type 'int'
/home/logan/m64p/GLideN64/src/DepthBufferRender/DepthBufferRender.cpp:231:20: runtime error: signed integer overflow: 1709260702 + 741890144 cannot be represented in type 'int'
/home/logan/m64p/GLideN64/src/DepthBufferRender/DepthBufferRender.cpp:216:41: runtime error: signed integer overflow: -3047363 + -2147483648 cannot be represented in type 'int'
/home/logan/m64p/GLideN64/src/gDP.cpp:1334:23: runtime error: left shift of negative value -1
```

I've copied the lines here in case they get shifted around by future commits:

https://github.com/gonetz/GLideN64/blob/c7144d07752b324c189f7da5ae26164ca79951af/src/3DMath.h#L45
https://github.com/gonetz/GLideN64/blob/c7144d07752b324c189f7da5ae26164ca79951af/src/DepthBufferRender/DepthBufferRender.cpp#L43
https://github.com/gonetz/GLideN64/blob/c7144d07752b324c189f7da5ae26164ca79951af/src/DepthBufferRender/DepthBufferRender.cpp#L231
https://github.com/gonetz/GLideN64/blob/c7144d07752b324c189f7da5ae26164ca79951af/src/gDP.cpp#L1330
https://github.com/gonetz/GLideN64/blob/c7144d07752b324c189f7da5ae26164ca79951af/src/gDP.cpp#L1338
https://github.com/gonetz/GLideN64/blob/c7144d07752b324c189f7da5ae26164ca79951af/src/gDP.cpp#L1348
https://github.com/gonetz/GLideN64/blob/c7144d07752b324c189f7da5ae26164ca79951af/src/gDP.cpp#L1351
https://github.com/gonetz/GLideN64/blob/c7144d07752b324c189f7da5ae26164ca79951af/src/gDP.cpp#L1354
https://github.com/gonetz/GLideN64/blob/c7144d07752b324c189f7da5ae26164ca79951af/src/DepthBufferRender/DepthBufferRender.cpp#L216
https://github.com/gonetz/GLideN64/blob/c7144d07752b324c189f7da5ae26164ca79951af/src/gDP.cpp#L1334

As you can see, it's not a massive problem, mostly related to calculations in gDP and DepthBufferRender. However it does have the potential to affect netplay sync, because the framebuffer can be read back into N64 memory and affect the outcome of the game.

I don't really feel like I can fix this, since I don't know the intent of the calculations, but I'm hoping somebody can squash these issues to improve the deterministic nature of the emulator.

**Comment by gonetz** [comment]
I fixed all UB issues I could find with ub sanitizer: ddd93673d89f
Please let me know if you find more of them.
