### ISSUE TITLE
Pokemon Stadium 2 (NTSC/PAL): Unknown memory action

### ISSUE THREAD

**Issue by RocketRobz** [gonetz/GLideN64#2367]
Using Public Release 4.0 in Project64 2.4.0.1377-g8ed4a80, when starting up Pokemon Stadium 2, I get `Unknown memory action` message.

**Comment by gonetz** [comment]
Have you tried recent builds from here 
https://ci.appveyor.com/project/gonetz/gliden64/branch/master?
Do you have "Use per-game settings" enabled?

**Comment by RocketRobz** [comment]
Updating to the latest Project64 nightly has fixed it!
