### ISSUE TITLE
Rayman 2 issues with colors [Regression]

### ISSUE THREAD

**Issue by standard-two-simplex** [gonetz/GLideN64#2369]
Bisected to 9a69fe8e

![rayman_2-000](https://user-images.githubusercontent.com/12202580/97272898-d7082a00-1832-11eb-936b-0127a145c0db.png)

**Comment by purplemarshmallow** [comment]
I removed that one line by accident :/
I can correct this

**Comment by gonetz** [comment]
> I can correct this

Please correct.

**Comment by standard-two-simplex** [comment]
Confirmed fixed.
