### ISSUE TITLE
3X native resolution factor breaks Cruis'n USA

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#2374]
Several 2D elements don't seem to be scaled properly with 3X native resolution factor. At 2X everything looks fine.

**Comment by gonetz** [comment]
Please show me these wrong elements on a screen shot. I can't notice a difference between 2X and 3X scale.

**Comment by fzurita** [comment]
Here is what it looks like for me:

![cruis'n_usa-002](https://user-images.githubusercontent.com/11581687/101244978-bfe11580-36d7-11eb-8fce-9fff79b59fd6.png)
![cruis'n_usa-001](https://user-images.githubusercontent.com/11581687/101245003-dbe4b700-36d7-11eb-92a7-d6febcccc9dd.png)
![cruis'n_usa-000](https://user-images.githubusercontent.com/11581687/101245009-e1da9800-36d7-11eb-8e6a-a83a85afbc32.png)

**Comment by gonetz** [comment]
I guess it is GLES-specific.

**Comment by fzurita** [comment]
Yep, probably

**Comment by fzurita** [comment]
More oddities. With Native resolution off 2D elements are not show up at all. For example the sky is completely black. This game seems to only work correctly in mobile with 1x or 2x native resolution factor. Some odd things are definitely happening with this game.

**Comment by fzurita** [comment]
This seems to be an issue specific to Mali devices... I'm just going to close it. I can't find anything odd about the inputs to the driver, so it must be some kind of weird internal bug when a blit is too large.
