### ISSUE TITLE
Ocarina of Time Textures look weird

### ISSUE THREAD

**Issue by Someguy1519** [gonetz/GLideN64#2375]
![Screenshot_20201103-133617_M64Plus FZ Pro](https://user-images.githubusercontent.com/27980228/98044452-c2500700-1ddb-11eb-919c-2191b0e7316d.jpg)
![Screenshot_20201103-133833_M64Plus FZ Pro](https://user-images.githubusercontent.com/27980228/98044482-d09e2300-1ddb-11eb-9017-48491d097057.jpg)
![Screenshot_20201103-133736_M64Plus FZ Pro](https://user-images.githubusercontent.com/27980228/98044501-dc89e500-1ddb-11eb-806d-a8c580431727.jpg)
![Screenshot_20201103-133656_M64Plus FZ Pro](https://user-images.githubusercontent.com/27980228/98044541-ed3a5b00-1ddb-11eb-8175-3ec0dded800e.jpg)
![Screenshot_20201103-133456_M64Plus FZ Pro](https://user-images.githubusercontent.com/27980228/98044674-18bd4580-1ddc-11eb-86fa-ff791fe3c431.jpg)
![Screenshot_20201103-135757_M64Plus FZ Pro](https://user-images.githubusercontent.com/27980228/98045018-b44eb600-1ddc-11eb-88dc-614f9e0b4610.jpg)

**Comment by IronYoshi64** [comment]
Emulator and version of it? What video plugin are you using? System specs? Does this happen for every game for you?

**Comment by Someguy1519** [comment]
I've reproduced this issue on GlideN64 Accurate, Very Accurate and Medium profiles on Mupen64Plus FZ v3.0.244 on Android. I'm on a Snapdragon 835 Galaxy S8+. This only happens on Ocarina of Time.
