### ISSUE TITLE
std::put_time breaks compilation on old G++ versions

### ISSUE THREAD

**Issue by DanTheMan827** [gonetz/GLideN64#2380]
https://github.com/gonetz/GLideN64/blob/e81022ad71e4f653cd1684730fd7af3e18784417/src/Log.cpp#L38

**Comment by Rosalie241** [comment]
define old g++ versions? what version are you using?

**Comment by gonetz** [comment]
What is the reason to use such an old G++ versions?

**Comment by DanTheMan827** [comment]
I ran into this issue when compiling it for the NES/SNES/Sega mini systems

Those all are based on build root 2015.11.1 and have gcc 4.9

**Comment by gonetz** [comment]
Well, it is just a log. Remove that line or replace it with something else.
