### ISSUE TITLE
Linux default build config is missing a necessary CFLAG as of 4.0

### ISSUE THREAD

**Issue by nlburgin** [gonetz/GLideN64#2388]
Note: This was on public release 4.0 (3d74542) so I apologize if this was already fixed in later unreleased commits. I only saw that there didn't seem to be an existing issue for this in the bug tracker.

The following forum post isn't mine, but it's where I found out what was preventing the plugin from working and how to fix it:

https://ubuntuforums.org/showthread.php?t=2448123

Apparently there's a `-pthread` CFLAG that needs to be set, but it isn't set by default and requires the builder to edit CMakeCache.txt before building or else ~~the plugin will instantly crash when mupen tries to load it~~ mupen will fail to load the plugin.

Since it _appears_ to build correctly, and the issues only become apparent when the plugin is actually loaded into m64's core, that may explain why Travis_CI hasn't caught this issue automatically.

Setting build defaults that actually work would make it a lot easier to get this working on linux, and also may encourage distros to package the plugin along with mupen (currently there are build scripts for Gentoo and AUR, but [no official binary packages anywhere](https://repology.org/project/mupen64plus-video-gliden64/versions)... I did find an unofficial package binary package in an ubuntu PPA but it was non-functioning; broken in the same way that my own build-attempt was broken before I applied the fix from the forum post.)

**Comment by Jj0YzL5nvJ** [comment]
#2373?

**Comment by nlburgin** [comment]
That other report doesn't mention pthreads and doesn't have the `undefined symbol: pthread_create` error message, so I'm guessing that's probably not the same one.

**Comment by nlburgin** [comment]
Is it possible this compatibility issue is dependent on the build settings that were used on the Mupen64plus core library? Can that be built both with and without pthread support, having ramifications for the plugins it loads?

I don't know if that's plausible or not but it's a thought I had.

**Comment by Jj0YzL5nvJ** [comment]
https://gist.github.com/Jj0YzL5nvJ/5242753837eed35768e61c240f572ecd

**Comment by gonetz** [comment]
@nlburgin if you have a solution for the problem, which does not create new problems, please provide a PR.

**Comment by ryanmaguire** [comment]
Adding `SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")` to the CMake file fixed this for me. Running Debian 11, pulled from the master branch yesterday.
