### ISSUE TITLE
Enabling FXAA breaks Stunt racer intro

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#2398]
With frame buffer emulation enabled and FXAA enabled and native resolution turned off stunt racer seems to rendering the first screen incorrectly. It works fine after that though. It almost looks like that small part is running at native resolution. Here is what it looks like:

![stunt_racer_64-000 (1)](https://user-images.githubusercontent.com/11581687/101654529-a3faae00-3a0e-11eb-845f-482125e03276.png)

Turning off FXAA fixes it for some reason. It's almost like the uTextureSize in the shader is not set correctly at startup.

**Comment by N64Freak** [comment]
Hi fzurita, i have the same issue with an another Boss ZSort Microcode Game, in this case World Driver Championship
