### ISSUE TITLE
Shader compilation from keys issue when hardware lighting is enabled

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#2418]
When changing the bilinear mode setting, shaders should be recompiled from the shader cache keys, but this is not happning. This is causing odd graphical glitches where mostly they appear the wrong color.

This may also be an issue with the HW lighting setting.

**Comment by gonetz** [comment]
I can't reproduce it. ShaderStorage::_loadFromCombinerKeys is called every time I change shaders-related settings, including  bilinear mode.  I tried to change bilinear mode along with HW lighting - no problems. Do you have that problem for every game?

**Comment by fzurita** [comment]
I was seeing this with battle zone.

**Comment by fzurita** [comment]
Yeah, I just checked, it seems like only battlezone is affected by this. Strange.

**Comment by fzurita** [comment]
And I think I see the problem, ```GBI.isHWLSupported()``` needs to be unique to each key and not global for all keys saved in the keys file.

**Comment by gonetz** [comment]
I implemented your idea to add new bit for HW lighting state to CombinerKey: 955c2f3b17451
Please test https://github.com/gonetz/GLideN64/tree/add_hwlight_bit_to_key branch.

**Comment by gonetz** [comment]
One note: I changed keys file format.
I decided that users can be upset to loose their keys file, so read from a file in the old format is still supported. It will be converted to the new format on next save. I now understand, that reading old key file will lead to the problem we are trying to solve.  However, the key file will be updated right after that, so on the next run or load from savestate the issue should gone.

**Comment by fzurita** [comment]
I tested your branch and it worked as well as I what I had. I'll close my pull request.

**Comment by gonetz** [comment]
Can this issue be closed?

**Comment by fzurita** [comment]
Sure, but it's not merged to master yet.

**Comment by gonetz** [comment]
Yes, I forgot about it.
