### ISSUE TITLE
Yoshi's Story

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#242]
Backgrounds not working in game.

**Comment by gonetz** [comment]
Disable frame buffer emulation for backgrounds.

**Comment by theboy181** [comment]
disable only worked partially. the backgrounds do not draw until you move. Improvement over FB emulation on though.

**Comment by gonetz** [comment]
Yes, I made a mistake during optimizations. Fixed.

**Comment by gonetz** [comment]
Made YS compatible with FB emulation.

**Comment by gonetz** [comment]
Please test and close if resolved.

**Comment by theboy181** [comment]
works great!!
