### ISSUE TITLE
Software clipping and near plane clipping

### ISSUE THREAD

**Issue by gonetz** [gonetz/GLideN64#2427]
I'm working on software polygons clipping. It is in soft_clip branch.
The result is disappointing. It works, but it works exactly as the hardware one.
The main goal is to fix the issue with near plane clipping on GLES devices, on which I can't disable it.
If I remove usage of graphics::ClampMode::NoNearPlaneClipping I get this:
![GLideN64_THE_LEGEND_OF_ZELDA_003](https://user-images.githubusercontent.com/8983092/103481971-b18a3480-4e10-11eb-94ae-262d4b339e2e.jpg)
Glide64 somehow avoids this issue, but I don't understand how. I know why it worked on 3dfx hardware - glide3x worked with screen space coordinates and had no hardware clipping. The plugin skips near plane clipping. If some part of polygon is outside the screen because of it, the scissor cuts it. However, the glide3x wrapper uses OpenGL. It converts screen space vertex coordinates into homogeneous ones before sending them to GPU. OpenGL should clip them but everything looks fine:
![Glide64_THE_LEGEND_OF_ZELDA_01](https://user-images.githubusercontent.com/8983092/103482307-bbad3280-4e12-11eb-8110-9928a533e15c.jpg)
Any idea how it works?

**Comment by standard-two-simplex** [comment]
> Any idea how it works?

I don't know about Glide64, but maybe you can try dividing z of all vertices by a big number (say 1024.0) at the end of the vertex shader and multiplying it back at the beggining of the fragment shader.

This way the near plane test will pass more easily. I think that if you divide all vertices by the same constant, attribute interpolation will still be correct.

**Comment by Jj0YzL5nvJ** [comment]
> Any idea how it works?

[Bitmask?](https://en.wikipedia.org/wiki/Mask_(computing)#Image_masks)

**Comment by gonetz** [comment]
> > Any idea how it works?
> 
> [Bitmask?

Please explain, how bitmask can help here?

> but maybe you can try dividing z of all vertices by a big number (say 1024.0) at the end of the vertex shader and multiplying it back at the beggining of the fragment shader.

Hmm. I removed usage of graphics::ClampMode::NoNearPlaneClipping in GBI.cpp and added 
	" gl_Position.z /= 10.0;	 \n"
to VertexShaderEnd. It fixed the issue with slingshot! I did the same in master and got the same result.

How does it work? Negative z coordinate remained negative after the division and thus the polygon still should be clipped.
As I understand, dividing Z by 10 reduces amount of clipped geometry by 10 times. It is enough to keep all necessary geometry on screen. For example, dividing by 2 is not enough to completely fix the slingshot.
Most likely, Glitch64 (glide3x wrapper for Glide64) does something like this with Z coordinate.

If it works, the need in software clipping is questionable. However, I met a problem: my attempts to multiply Z coordinate by the same constant (10) cause loss of all 3D geometry. I don't understand it. Without scaling Z coordinate back we will have problems with depth compare when primitive uses PrimitiveDepth. Copy depth buffer to RDRAM also will not work.

**Comment by gonetz** [comment]
@fzurita It looks as better way to fix near-plane clipping issues with GL ES. I made a test branch: https://github.com/gonetz/GLideN64/tree/near_plane_clip
Could you test it on games with no near-plane clipping, like Zelda, Ep.1 Racer ?

**Comment by fzurita** [comment]
Yep, I can do that.

**Comment by standard-two-simplex** [comment]
> How does it work? Negative z coordinate remained negative after the division and thus the polygon still should be clipped.
As I understand, dividing Z by 10 reduces amount of clipped geometry by 10 times. It is enough to keep all necessary geometry on screen.

When you perform the multiplication by a perspecitve matrix, w is configured to store the old z (changing sign if necessary) and z is configured so that z=-w at the near plane and z=w at the far plane.

Therefore, the near and far tests become -w <= z  and z <= w.

 Thus you have this situation (where n is the original depth of the near plane).
- Vertex behind the near plane: w >= n > 0 and z >= -w.
- Vertex between the camera and the near plane:  n > w > 0 and z < -w
- Vertex at the camera depth or behind the camera: w <= 0 and z > w (yes, behind the far plane).

See this diagram form the book of Lengyel, E. 
<img src="https://user-images.githubusercontent.com/12202580/103521413-006bb480-4e79-11eb-8588-b9a4dd7d6297.png" width=480>

I believe (but I'm not sure) the last case is handled by w clipping, to avoid clipping the vertices to the far plane. The second case is handled by near clipping. 

By dividing z by 10.0, you are hacking the z test to perform z/10 >= -w which passes more easily as z/10 is greater than z for negative z values. However, you are also relaxing the far test condition, which becomes z/10 <= w. This is not a problem if you clip correctly in software prior to OpenGL clipping, but it can be otherwise.

Finally, the map z -> z/10 keeps the pixels in the same order, so the depth test should pass with the transformation if and only if it passes without it. I would use a power of 2 as divisor to avoid precision loss from the division, since this only changes the exponent bits of the floating point value. The greater the divisor is, the closer you move the near plane towards the camera so you are closer to no near clipping.

The new z in fragment shader can break z based effects (like fog) so it is probably best to restore original information. I realize now that this z is trasformed by glFragDepth() so that fragment depth is between 0 and 1, so it may get a little tricky. It should also possible to map the fragment depth to the N64 range (I believe [0,1024]).

**Comment by fzurita** [comment]
@gonetz I tested Zelda, EP 1 racer, and turok which had some clipping issues as well. They now seem to work correctly in a device that didn't work correctly before.

**Comment by fzurita** [comment]
Hmm, the Adreno device that used to work mostly correctly no longer does. It's almost like the camera is now too far away and we see unrendered areas, see the arm:

![the_legend_of_zelda-001](https://user-images.githubusercontent.com/11581687/103527911-106f9e00-4e51-11eb-99b5-770d31937565.png)

**Comment by fzurita** [comment]
It may be more like in the Adreno device, it's still clipping a little too much.

**Comment by gonetz** [comment]
@standard-two-simplex Thanks for the explanation!
>However, you are also relaxing the far test condition, which becomes z/10 <= w. This is not a problem if you clip correctly in software prior to OpenGL clipping, but it can be otherwise.

Good point! Yes, software clipping should be used prior that hack to avoid performance issues.

@fzurita Great, thanks!


> Edit: Actually, ignore that. That went away after I cleared shader cache. If you do that, you may want to up the shader cache version.

Ok

**Comment by gonetz** [comment]
I added z-clip hack to soft-clip branch.
It is ready for testing now.

I made software clipping optional but it is enabled by default.
It can be disabled only in **mupen64plus**. Support in GUI is not implemented yet. I'm not sure that it should be optional since I don't see reasons to disable it. It is not tested yet, so some scenarios can be broken. It also **may** have impact on GPU performance, but I'm not sure good or bad one. From the one side, clipping increases number of polygons which should be sent to GPU. From the other side, software clipping works in tandem with software culling. Culled polygons are not sent to GPU, so number of polygons decreases. I expect that users will not notice any difference.
Note: pixel coverage calculation currently works correctly only with software clipping enabled.

**Comment by gonetz** [comment]
Various glitches in Beetle Adventure Racing :(

**Comment by Jj0YzL5nvJ** [comment]
> Please explain, how bitmask can help here?

Sorry, 2D logic... I had no idea what `clipping` mean at the time, now I do.

**Comment by fzurita** [comment]
@gonetz I'm seeing a really big performance hit with this change, like in the tune of 40% performance hit in Banjo-Tooie

**Comment by gonetz** [comment]
@fzurita 
There can be another source of performance hit related to software clipping.
It is in clipInHomogeneousSpace(...), line 291
`const float wScale = static_cast<float>(gSP.clipRatio);`
This wScale  enlarges clipping area according to clip ratio. I probably made it wrong and clipping area becomes too large, thus lots of geometry left unclipped. Could you replace it by 
`const float wScale = 1.0f;`
for testing purposes and check how it impacts the performance?
This change will break a thing or two, but for most games it should be only for good.

**Comment by fzurita** [comment]
@gonetz I already made sure that none of that code ran by disabling software clipping and framebuffer emulation. The prioritize hit was still there.

The performance hit comes from the GLSL code changes.

**Comment by gonetz** [comment]
> The performance hit comes from the GLSL code changes.

But your PR restores GLSL code, is not it?
If you disabled the software clipping, you should get the same shaders code as before.
Am I missed something? Sorry, I can't think clearly after hard working day.

**Comment by standard-two-simplex** [comment]
> Edit: The problem appears to be gl_FragCoord.z. Accessing that in Adreno is extremely slow.

What you describe seems like Early Depth Testing being disabled. https://www.khronos.org/opengl/wiki/Early_Fragment_Test

Writing to `gl_FragCoord.z` causes all fragments to be processed, as the result of `gl_FragCoord.z` is needed to perform the depth test. If the fragment shader does not write to `gl_FragCoord.z`, it is possible to know the output before executing the fragment shader and only execute the fragment shader for fragments that pass the depth test.

**Comment by fzurita** [comment]
@gonetz If I disable software clipping I do get the same code as before. I can make the old code take a similar path by disabling support for nosperspective. I also get the same slowdown in the old code before software clipping by forcing the path where gl_FragCoord.z gets used for computing gl_FragDepth.

**Comment by fzurita** [comment]
@standard-two-simplex I came to the same conclusion here in the pull request I made: https://github.com/gonetz/GLideN64/pull/2439

**Comment by gonetz** [comment]
> If I disable software clipping I do get the same code as before.

But you said that "This change restores some of the performance but not all. It's now reaching around 40fps in the same area." 
Why?

**Comment by fzurita** [comment]
In the older code, this path was never executed because Adreno supports the noperspective extensions:
https://github.com/gonetz/GLideN64/blob/8b75b5dc9618048b5d54a482e60e0706197c6bec/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramBuilder.cpp#L1943-L1949

If I force the noperspective to off in the old code, I get the same performance penalty because Adreno now has to execute that.

In the new code, gl_FragCoord.z is used in all cases which causes a slow down in Adreno.

With the new code, if I make changes so that vZCoord is used instead of gl_FragCoord.z then some of the performance is restored but not at the same level as before.

**Comment by gonetz** [comment]
> With the new code, if I make changes so that vZCoord is used instead of gl_FragCoord.z then some of the performance is restored but not at the same level as before.

My question is why it happens if the shader code for Adreno is the same as before with your PR?

**Comment by fzurita** [comment]
It's not exactly the same, the discard statement is no longer there because there is nothing to discard any more since the software vertex clipping should be taking care of that.

**Comment by fzurita** [comment]
> `const float wScale = static_cast<float>(gSP.clipRatio);`
> This wScale enlarges clipping area according to clip ratio. I probably made it wrong and clipping area becomes too large, thus lots of geometry left unclipped. Could you replace it with
> `const float wScale = 1.0f;`

Now that I think about this. I could do this with software clipping enabled and while using vZCoord to see if the performance comes back to previous levels.

**Comment by gonetz** [comment]
As I understand, the performance hit is still there even if software clipping is disabled. If it is because of missing discard, let's put it back.

> Now that I think about this. I could do this with software clipping enabled and while using vZCoord to see if the performance comes back to previous levels.

Yes, please check it too.

**Comment by gonetz** [comment]
> I thought that the pre-clipping implementation also wrote to the depth output. Is it not the case?

GLESX vertex shader uses special output variable, which keeps z/w. Fragment shader uses it instead of gl_FragCoord.z.

**Comment by fzurita** [comment]
Changing wScale to always be 1.0 makes no difference. With my pull request I'm only seeing a 8% performance loss. I already checked and adding uScale back along with the discard restores performance to the previous level.

**Comment by gonetz** [comment]
> Changing wScale to always be 1.0 makes no difference.

It's good.

> I already checked and adding uClampMode back along with the discard restores performance to the previous level.

Great! Lets put it back then.

**Comment by fzurita** [comment]
Ok, I will add it back in my pull request.

**Comment by fzurita** [comment]
Actually, the discard is not helping. It's only helping when I completely disable software vertex clipping and then put the discard back. It's possible that the 8% loss in performance after putting vZCoord back is coming from the CPU utilization of the new vertex clipping.

**Comment by fzurita** [comment]
Yeah, in Mario 64 performance is actually 10% better with software vertex clipping. It really seems like Banjo Tooie is an edge case.

The software vertex clipping would probably benefit a lot from neon instructions.

**Comment by gonetz** [comment]
> I will leave my pull request as is.

Ok. Merged.
