### ISSUE TITLE
Mario Kart 64

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#243]
The borders are wrong for example see red boxes
![83](https://cloud.githubusercontent.com/assets/6679921/6250568/fda4cb24-b78e-11e4-8fc1-1029232488e7.png)
![84](https://cloud.githubusercontent.com/assets/6679921/6250572/02158036-b78f-11e4-851f-4d0bba7246b8.png)
& after a race at the results screen in the upper video the sky changes his color every couple seconds

**Comment by Predator82Germany** [comment]
The error of the pics are gone in Project64 2.2

**Comment by Predator82Germany** [comment]
Sky changes his color every couple seconds is not away

**Comment by gonetz** [comment]
> Sky changes his color every couple seconds is not away

Please test with latest build

**Comment by Predator82Germany** [comment]
Latest build crash on rom-start

**Comment by gonetz** [comment]
Does it crash with this game only or with any rom? It works ok for me, but I changed shaders, so  incompatibility with NVidia is possible.

**Comment by Predator82Germany** [comment]
Every game

**Comment by gonetz** [comment]
What is in the error message?
Is gliden64.log created?

**Comment by Predator82Germany** [comment]
GLideN64-log

shader_link error: Fragment info
-------------
0(69) : error C7011: implicit cast from "ivec3" to "uvec3"

shader_link error: Fragment info
-------------
0(69) : error C7011: implicit cast from "ivec3" to "uvec3"

shader_link error: Fragment info
-------------
0(69) : error C7011: implicit cast from "ivec3" to "uvec3"

shader_link error: Fragment info
-------------
0(68) : error C7011: implicit cast from "ivec3" to "uvec3"

shader_link error: Fragment info
-------------
0(69) : error C7011: implicit cast from "ivec3" to "uvec3"

shader_link error: Fragment info
-------------
0(69) : error C7011: implicit cast from "ivec3" to "uvec3"

shader_link error: Fragment info
-------------
0(69) : error C7011: implicit cast from "ivec3" to "uvec3"

shader_link error: Fragment info
-------------
0(68) : error C7011: implicit cast from "ivec3" to "uvec3"

shader_link error: Fragment info
-------------
0(69) : error C7011: implicit cast from "ivec3" to "uvec3"

shader_link error: Fragment info
-------------
0(69) : error C7011: implicit cast from "ivec3" to "uvec3"

shader_link error: Fragment info
-------------
0(69) : error C7011: implicit cast from "ivec3" to "uvec3"

**Comment by Predator82Germany** [comment]
![2](https://cloud.githubusercontent.com/assets/6679921/6710310/fcb8d9d8-cd7f-11e4-89ea-7ffeec9f3643.png)
![3](https://cloud.githubusercontent.com/assets/6679921/6710309/fcb7f63a-cd7f-11e4-84c1-d9b3877534b9.png)
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/6710308/fcb782ae-cd7f-11e4-8180-ec0603696596.png)

**Comment by gonetz** [comment]
Thanks! Will be fixed right now.

**Comment by Predator82Germany** [comment]
With newer one it crashes again

GLideN64-log:
shader_compile error: 0(6) : error C7011: implicit cast from "int" to "uint"
0(12) : error C7011: implicit cast from "int" to "uint"
0(13) : error C7011: implicit cast from "int" to "uint"

shader_link error: Fragment info
-------------
0(6) : error C7011: implicit cast from "int" to "uint"
0(12) : error C7011: implicit cast from "int" to "uint"
0(13) : error C7011: implicit cast from "int" to "uint"

shader_link error: Fragment info
-------------
0(6) : error C7011: implicit cast from "int" to "uint"
0(12) : error C7011: implicit cast from "int" to "uint"
0(13) : error C7011: implicit cast from "int" to "uint"

shader_link error: Fragment info
-------------
0(6) : error C7011: implicit cast from "int" to "uint"
0(12) : error C7011: implicit cast from "int" to "uint"
0(13) : error C7011: implicit cast from "int" to "uint"

**Comment by Predator82Germany** [comment]
above + new message
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/6712049/e2eba55c-cd8a-11e4-8139-bb58965fefce.png)

**Comment by baptiste0602** [comment]
same problem as Predator82 with GLideN64_18Mar_hotfix

**Comment by gonetz** [comment]
Hmm, that's unexpected. Ok, I've uploaded another fix. Hopefully, it will work properly.

**Comment by Predator82Germany** [comment]
Fixed with Mar19

**Comment by Predator82Germany** [comment]
Hmm ... when I end emulation without close the emulator & start another rom I get everytime any of the above messages
Do I restart the emu & start the same rom again it works
GLideN64 or emu issue?

**Comment by gonetz** [comment]
I guess, it's my fault. I forgot to cleanup resources for that new shader. Will be fixed today.

**Comment by gonetz** [comment]
Please check with latest build.

**Comment by Predator82Germany** [comment]
Seems fixed

**Comment by gonetz** [comment]
Ok, please close it then
