### ISSUE TITLE
Texture engine changes hurt performance in low end devices

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#2430]
After the texture engine changes were made, low end devices are really hurting in performance. Even in simple games, like Mario 64, I'm seeing around a 40% performance reduction after those sets of commits on low end devices.

Low end devices will continue being made, even with GLES 3.0+, so we should consider making those changes optional or maybe improving the efficiency.

I tried looking as to why it was hurting performance so much, but I couldn't find a smoking gun.

**Comment by standard-two-simplex** [comment]
How do you measure performance? Do you just disable the framelimiter and check fps? Or do you have better ways?

I personally don't know how to check if a change is for the better or worse.

**Comment by fzurita** [comment]
Yeah, disabling the limiter and looking at FPS.

But for low end devices, it's easy to tell because they can't reach full speed.

**Comment by standard-two-simplex** [comment]
Please, see if this makes any difference. I reduced calls to clamp_wrap_mirror by half, so hopefully it is faster. However, I see no difference in my laptop.
https://github.com/standard-two-simplex/GLideN64/tree/tex_engine

> we should consider making those changes optional

This is not so simple. You can't simply disable it, as you need an alternative. You would need to either write a faster way of clamping wrapping and mirroring texture coordinates (which I don't know how to do) or using OpenGL's way of doing it (which can't accurately emulate the N64, can be incompatible with other features and is a big piece of code you need to mantain with every change to master). It is not a very good idea in my opinion.

> maybe improving the efficiency

I am open to this, but I don't know what makes it so slow. Perhaps it is the mod operations, but I don't know how to remove them.

**Comment by dankcushions** [comment]
i am open to doing some GL profiling on my pi 4 similar to https://github.com/gonetz/GLideN64/pull/2381, if anyone can give me suitable before / after commits, and a good game to test.

**Comment by gonetz** [comment]
@fzurita which game you can recommend for profiling? It is better be something static, like main  menu or pause screen. IIRC, GE007 has performance issues in menus.

Then we need to find, which part of texture engine hurts the performance. We can disable all its code, measure the result and then enable it back piece by piece. I agree with standard-two-simplex that making texture engine optional is non-trivial task now. It would be very hurting to do.

**Comment by fzurita** [comment]
I was using Golden eye first level to test performance. Around the area where the truck first stops.

**Comment by fzurita** [comment]
@standard-two-simplex Those changes unfortunately didn't make much of a difference in performance :(

**Comment by fzurita** [comment]
This is the last commit where performance was still ok: a140f0a989360c729e6bfeefda99c0e0bb21df81

**Comment by gonetz** [comment]
> I was using Golden eye first level to test performance. Around the area where the truck first stops.

Can you upload a savestate?

**Comment by fzurita** [comment]
Yeah, sure, here are some results though. Keep in mind, this is a very low end device:

**Before texture engine**
mario inside castle sitting in the middle=26-27
zelda kokiri forest=15-16

**master**
mario=21-22
zelda=11

**optimization**
mario=23-24
zelda=9-10

**Comment by gonetz** [comment]
> This is the last commit where performance was still ok: [a140f0a](https://github.com/gonetz/GLideN64/commit/a140f0a989360c729e6bfeefda99c0e0bb21df81)

So, performance was more-less ok with previous version of clamp-wrap-mirror shader.

**Comment by fzurita** [comment]
Yep

**Comment by fzurita** [comment]
At 1X resolution with FBE enabled, the performance impact of the texture engine is not as critical:

**before texture engine:**
mario=43-44
zelda=24-25

**master:**
mario= 41-42
zelda= 23-24

**Comment by standard-two-simplex** [comment]
Well, I tried measuring performance on my computer but I can't see any difference between builds, even in higher resolutions. I spotted one unnecessary `mod()` in `highp vec4 invertedCoord = -texCoord-vec4(1.0);`. I pushed another try to the branch above, but I don't expect it will make any difference.

If you can find out if there are problematic operations in the code we may try to find a workaround. Other than that I don't know what else to do.

**Comment by fzurita** [comment]
Yeah, tried for a while to find what operations are causing the slow down with no luck. Maybe it's just that there is more in the shader. I may try more later to see if it's something specific.

**Comment by fzurita** [comment]
Fixed: https://github.com/gonetz/GLideN64/commit/3d5a39e647fceb5bf17a288df32677773f4a9034
