### ISSUE TITLE
Majora's Mask WS + Redux screen corruption

### ISSUE THREAD

**Issue by GhostlyDark** [gonetz/GLideN64#2437]
Widescreen and Redux aren't exactly compatible with each other. Combining them did work out, albeit with some caveats. One such issue displays as random screen corruptions that happen during or after cutscenes with effects like blur active. It's likely an incompatability issue between the two hacks.

Interestingly though and the reason I am opening this issue: **Garbled text gets fixed upon resizing the window.** Since it is random and disappears when the window gets resized, the only somewhat reliable way to reproduce this is to play the Song of Soaring over and over again to warp to some place  (its cutscene uses blur) until the text looks like a loading bar.

Here are patches for Majora's Mask (USA), WS only and WS + Redux:
[ws-patches.zip](https://github.com/gonetz/GLideN64/files/5835583/ws-patches.zip)

This is how it looks like when the screen gets resized and sometimes during warp cutscenes:
![image](https://user-images.githubusercontent.com/31742919/105029310-7d3e8700-5a52-11eb-94af-cfe227abfaab.png)

Happening at random, text gets garbled during or after a cutscene with a blur effect:
![image](https://user-images.githubusercontent.com/31742919/105028895-eb367e80-5a51-11eb-9aaa-03075364bc79.png)
![image](https://user-images.githubusercontent.com/31742919/105033375-4ec3aa80-5a58-11eb-8d2b-53ef8b7c729c.png)

Some additional notes:
- Widescreen or Redux don't show any issues in isolation
- Disabling cutscene effects prevents the issue from popping up
- The Project64 Video Plugin ends up in a black screen when trying to resize the same WS Redux ROM

**Comment by GhostlyDark** [comment]
Obviously, the corruption issues are an issue with the ROM Hack and not GLideN64 (which have been fixed in the meanwhile).
The main takeaway is that resizing the window fixes graphical issues and happens to unveil corruption, which is something that may or may not be intentional for the video plugin to do. I don't see any reason to keep this issue opened.

**Comment by Thetumtumtree** [comment]
i don't know if this is the right place to ask but i have a glich where three numbers appear on the left side of the screen that seam to change from room to room. i don't know if this is a bug or setting but is there a way to get rid of them?
