### ISSUE TITLE
Bilinear filtering no use for a long time

### ISSUE THREAD

**Issue by shinslash** [gonetz/GLideN64#2438]
There is no difference if set Bilinear filtering Standard or N64-style
And no difference whatever change the ini file "texture\bilinearMode=?"
But it works in GLideN64 public release 4.0.

**Comment by standard-two-simplex** [comment]
They are both bilinear filters, so the change is hardly noticeable. However, it is present in current master. See the black line below the staircase.

3 point bilinear filter
<img src="https://user-images.githubusercontent.com/12202580/105364405-6b4d1780-5bfd-11eb-9da6-cf98e2832dc1.png" width=320>

Standard 4 point bilinear filter.
<img src="https://user-images.githubusercontent.com/12202580/105364418-6e480800-5bfd-11eb-8967-0ca98fd42f6f.png" width = 320>

**Comment by Papermanzero** [comment]
is it possible to add bicubic?

**Comment by shinslash** [comment]
I still think the performance of "public release 4.0." is correct.

**Comment by gonetz** [comment]
As pointed by standard-two-simplex , the difference between two filtering modes is clearly visible. Here another example:
![Filtering](https://user-images.githubusercontent.com/8983092/106388197-03be7580-6410-11eb-8339-337334f4e1bf.png)

Public release 4.0 works the same. If you notice that texture filtering works different with the current build, please post a comparison screen shots.
Btw, why do you edit the ini file manually? Do you use vanilla mupen64plus, with command line interface?

**Comment by gonetz** [comment]
> is it possible to add bicubic?

Yes. The plugin uses texture filtering implemented in shaders. Any filtering can be used, if somebody implement them.
