### ISSUE TITLE
GlideN64 not working on second monitor (tv) when going into full screen move

### ISSUE THREAD

**Issue by kamikazilucas** [gonetz/GLideN64#2442]
i want to have project 64 be in full screen on my tv but even when i put the p64 box on my tv it just goes full screen on the primary monitor anyway, how do i fix this

**Comment by Jj0YzL5nvJ** [comment]
GLideN64, not Glide64. #1852

**Comment by gonetz** [comment]
@kamikazilucas You may choose to duplicate image on your monitors or display it only on the second one (tv). In this case full screen works.

**Comment by kamikazilucas** [comment]
> @kamikazilucas You may choose to duplicate image on your monitors or display it only on the second one (tv). In this case full screen works.

yes but that is super distracting to me

**Comment by gonetz** [comment]
Set TV as the main display then:
![DisplaySetting](https://user-images.githubusercontent.com/8983092/106380359-4d916680-63e4-11eb-986c-1abeaf9cea8d.png)

It works for me. Sorry, I don't know what else can be done.

**Comment by kamikazilucas** [comment]
> Set TV as the main display then:
> ![DisplaySetting](https://user-images.githubusercontent.com/8983092/106380359-4d916680-63e4-11eb-986c-1abeaf9cea8d.png)
> 
> It works for me. Sorry, I don't know what else can be done.

yeah but when i do that all my settings like desktop shortcuts go to the other screen, with jabo when you put the window on the other screen and then fullscreen it goes to the other screen anyway

**Comment by gonetz** [comment]
I don't know how to do that with OpenGL. I'll try to find a solution, but can't promise anything.

**Comment by kamikazilucas** [comment]
> I don't know how to do that with OpenGL. I'll try to find a solution, but can't promise anything.

ok thank you, another way is to have an option in graphics that lets you choose which monitor

**Comment by Jj0YzL5nvJ** [comment]
Borderless fullscreen windowed, Non-exclusive fullscreen mode, Fake fullscreen, etc, call it whatever you want. 
https://www.pcgamingwiki.com/wiki/Glossary:Borderless_fullscreen_windowed

**Comment by gonetz** [comment]
@Jj0YzL5nvJ Thanks! @kamikazilucas have you tried these workarounds? "Windowed Borderless Gaming" looks as a good solution.

**Comment by kamikazilucas** [comment]
> @Jj0YzL5nvJ Thanks! @kamikazilucas have you tried these workarounds? "Windowed Borderless Gaming" looks as a good solution.

yeah i tried borderless gaming and it just made the screen small so it doesn't work

**Comment by gonetz** [comment]
@kamikazilucas  Please try builds from #2686 for Project64
New "borderless window" option supports monitor selection.
I still don't know, how to select non-primary display for true fullcreen mode, but "borderless window" should work with any monitor you have attached.

**Comment by gonetz** [comment]
Fixed with PR #2686
