### ISSUE TITLE
Graphical issues in Diddy Kong Racing

### ISSUE THREAD

**Issue by quicksilver7837** [gonetz/GLideN64#2447]
There seems to be some graphical issues on all the adventure 2 tracks (adventure 1 tracks are fine). These are the regular tracks but in reverse and only available once you have beaten the main game adventure 1. 

This seems to be a regression as this was not an issue about 6-8 months ago which was the last time I played the game. This issue now occurs since I updated. Tested on my pi 4.
![20210205_170113](https://user-images.githubusercontent.com/35534553/107096782-76956b00-67d9-11eb-91b3-ec15c6087be9.jpg)

If helpful I can also attach a save state.

**Comment by Jj0YzL5nvJ** [comment]
> If helpful I can also attach a save state.

Without an attached save status it's like saying "I want to report this issue but I don't want it fixed."

**Comment by quicksilver7837** [comment]
> > If helpful I can also attach a save state.
> 
> Without a save state attached it's like saying "I want to report this issue but I don't want it fixed."

My apologies, I made the report on my phone while on a break at work. I'll be sure to attach a save state as soon as I get a chance.

**Comment by quicksilver7837** [comment]
[Diddy Kong Racing (U) (M2) (V1.1) [!].st0.zip](https://github.com/gonetz/GLideN64/files/5936891/Diddy.Kong.Racing.U.M2.V1.1.st0.zip)
Here is the attached save state. Thanks

**Comment by Jj0YzL5nvJ** [comment]
Well, I can also reproduce this on PC with Radeon RX 560 using HLE. Works fine in LLE.

**Comment by gonetz** [comment]
Thanks for the report and the savestate!
Fixed.

**Comment by quicksilver7837** [comment]
@gonetz looks fixed on my end. Thanks! Should I go ahead and close the issue?

**Comment by gonetz** [comment]
Yes, it is fixed now.
