### ISSUE TITLE
Mario Golf corrupt scoreboards during screen transition.

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#245]
corrupt scoreboards during screen transition.

![capture](https://cloud.githubusercontent.com/assets/9299743/6280018/7df5cb70-b85c-11e4-80d5-3f0b5eca2ce4.PNG)

**Comment by gonetz** [comment]
How to reproduce it?

**Comment by theboy181** [comment]
Must finish a hole. This happens just before the start of the next round after the scores are updated.

**Comment by theboy181** [comment]
This looks like it was working today..
