### ISSUE TITLE
Texture paths not saving correctly

### ISSUE THREAD

**Issue by LiquidateMe** [gonetz/GLideN64#2452]
On Project64 Version 2.3.2.202. 

While a ROM is loaded If I change the texture pack path to "C:/Program Files (x86)/Project64 2.3/Plugin/GFX/Texture" and press ok, when I go back into the menu the Texture cache path and the Texture dump path have also changed to that. Unable to change them back to their own folders even when I press restore defaults. If I close project 64 and reopen they do return to defaults though.

**Comment by LiquidateMe** [comment]
built in version on development project 64 v2.4.0-1474-g89d56ff seems to work fine, unsure why the public one on the v2.3.2 bugs out though

**Comment by Jj0YzL5nvJ** [comment]
NTFS permissions... It's not recommended to install emulators in the system paths to begin with.

**Comment by Squall-Leonhart** [comment]
> NTFS permissions... It's not recommended to install emulators in the system paths to begin with.

irrelevant, the issue is a (since fixed upstream) bug in the pj64 2.3 bundled gliden64
