### ISSUE TITLE
N64 Depth compare broken in Adreno

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#2459]
I'm Extreme-G only the HUD is rendered work Adreno. See screenshot:
![extremeg-000](https://user-images.githubusercontent.com/11581687/107861907-f6918580-6e16-11eb-81a0-9f3debd60889.png)

Not sure at what point it broke.

Edit 1: Disabling software vertex clipping does not fix it.

**Comment by fzurita** [comment]
Ok, it looks like N64 depth compare is broken with Adreno currently.

I went back pretty far back and it was not broken by any recent changes. @loganmc10 Any ideas since you implemented that?

**Comment by fzurita** [comment]
Ok, I went back further. I bisected to this commit: 2600a6bc90f7f367f3a9f2ee3ee86b1efef90af5 That's when N64 depth compare first became broken on Adreno.

**Comment by fzurita** [comment]
@gonetz It seems like the "Fast N64 depth compare" is broken. Is this supported by anything but Adreno?

**Comment by loganmc10** [comment]
I believe it works well on most Intel and Nvidia GPUs, I don't know about mobile devices though

**Comment by fzurita** [comment]
Ok, I found the original pull request and it seems like you got it working pretty well with Adreno here:

https://github.com/gonetz/GLideN64/pull/1792

I'm going to try to see what the difference is to the current implementation in a bit...

**Comment by loganmc10** [comment]
It could be something related to a driver update/newer Android version since that was first written. As I recall it really depended on how those particular GL extensions were implemented by the vendors.

**Comment by fzurita** [comment]
Ok, I think I figured it out, at least partially. Everyhing works right in Adreno if I force imageTextures to off.

**Comment by fzurita** [comment]
Based on what I'm seeing so far, I see no reason for Mali GPUs to not support the fast N64 depth compare.

They have a similar extension to framebuffer fetch that is used for Adreno.

**Comment by Panderner** [comment]
International superstar soccer also affected this issue
![Screenshot_2021-02-14-21-12-33-918_org mupen64plusae v3 fzurita](https://user-images.githubusercontent.com/37503397/107877787-6f710a00-6f09-11eb-8090-2bb372173c22.jpg)

**Comment by fzurita** [comment]
Yeah, I have a fix here for Adreno: https://github.com/mupen64plus-ae/mupen64plus-ae/tree/fix_n64_depthcompare


I'm trying to come with a way to get it working on Mali too.

**Comment by fzurita** [comment]
I couldn't get it working for Mali devices in the end using any fast method. The required extensions just aren't there.
