### ISSUE TITLE
Magical Tetris Challange

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#246]
The "GO" has texture alignment issues, and there is a white line on both sides of  play field.
![capture](https://cloud.githubusercontent.com/assets/9299743/6280131/b6f53504-b85d-11e4-8a59-e32c94879e05.PNG)

**Comment by theboy181** [comment]
With AL's RDP and filters on, this games backgrounds look amazing. Is there anyway you could emulate filters just like pixel accurate plugin? this would make most background menus look as good as they do on the real N64.

I find that most games have some weird misalignment issues regarding 2d textures.

**Comment by theboy181** [comment]
Still has issues, but is a little better using native res.

**Comment by olivieryuyu** [comment]
@theboy181 

it is fixed now, can you check and close?

**Comment by theboy181** [comment]
Yes, sorry I forgot about this ticket. Looks good now.
