### ISSUE TITLE
Unable to find custom resolutions for window mode

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#2463]
@gonetz 

Was the custom resolution setting removed from Gliden64? I like to use this feature with PJ64 and WS hacks.

thanks,

**Comment by gonetz** [comment]
No, custom windowed resolution is still there. Just type the resolution you need in the format 'width x height', for example 640 x 400.

**Comment by theboy181** [comment]
Thank you!  Im getting some errors about textures and disabling them, and I dont have them enabled, but I will investigate and open an issue.
