### ISSUE TITLE
OoT Texrect Drawer regression

### ISSUE THREAD

**Issue by GhostlyDark** [gonetz/GLideN64#2467]
Easily visible with HD textures right from the start. The Nintendo 64 Logo text has also visible lines with original graphics.
It seems to only affect 2D elements. Sorry if I should have posted in #2324 instead.

![image](https://user-images.githubusercontent.com/31742919/109429711-77e33d80-79fd-11eb-9001-3f8471f4dd01.png)

![image](https://user-images.githubusercontent.com/31742919/109429716-829dd280-79fd-11eb-8585-6d775a3986e5.png)

**Comment by oddMLan** [comment]
Are you using match resolution with output? How does it look if you use a native res multiple? Say, 2x?

**Comment by Nerrel** [comment]
On my end the issue is there when using a multiple of native res

**Comment by GhostlyDark** [comment]
Happens with any output resolution, including multiples of native res and even native res looks off.

**Comment by standard-two-simplex** [comment]
@GhostlyDark Do you mind posting the affected HD textures for testing? The ones in the title screen should suffice (only the 2d ones).

**Comment by GhostlyDark** [comment]
Here you go:
[oot-title-textures.zip](https://github.com/gonetz/GLideN64/files/6064620/oot-title-textures.zip)

**Comment by Jj0YzL5nvJ** [comment]
I think more attention should be paid to what GLideN64 does when it reinterprets [Hi-Res pixels](https://github.com/gonetz/GLideN64/issues/2457#issuecomment-779846784).

**Comment by standard-two-simplex** [comment]
@GhostlyDark The issues you're seeing are due to the setting useTexCoordBounds, which disallows texture coordinates exceeding the maximum value they would take in native (times a hd scale). It prevents out of bound texture fetches, but can create hard edges by repeating certain pixels at the boundary.

It is meant to be optional, but the config option is not yet available for PJ64. I thought I had defaulted it to off, but apparently didn't. You may try building [this branch ](https://github.com/standard-two-simplex/GLideN64/tree/use_screen_coords_2), which disables it.

I will check if I made some mistake and can be made compatible with the title screen.

**Comment by GhostlyDark** [comment]
I should add that it also affected other 2D elements beyond the title screen like the Boss text and Mario Kart 64's logo and menu screen. It looks fine on mupen64plus, so I assume switching that setting does it.

For what it's worth, using a multiple of the N64's native resolution looks fine before and after the PR changes. I did spot that Mario Kart 64's copyright texture looks funky while I had 800x600 as window resolution set (which isn't a multiple).

**Current Master**
![image](https://user-images.githubusercontent.com/31742919/110204144-d1ba8c00-7e71-11eb-861a-60b7e9bd6b09.png)

**#2324** 
![image](https://user-images.githubusercontent.com/31742919/110204103-8d2ef080-7e71-11eb-9916-7b9ec53e36f3.png)

**HD textures**
[mk-copyright.zip](https://github.com/gonetz/GLideN64/files/6095174/mk-copyright.zip)

**Comment by gonetz** [comment]
Native-res texrect drawer is not used with HD textures, even if it is enabled.
So, the problem is indeed with the useTexCoordBounds. I think, it also should automatically be disabled when current texrect uses HD texture(s).

**Comment by gonetz** [comment]
@GhostlyDark I think this issue can be closed.
The problem with HD textures can be solved by toggling useTexCoordBounds setting.
If you use HD textures and Multiple of N64 resolution, useTexCoordBounds is better to set off.
If you use internal resolution same as the output one, useTexCoordBounds can be useful - see MK64 copyright HD textures.
If you don't use HD textures, useTexCoordBounds option solves various issues with 2D, see OB64.
