### ISSUE TITLE
AeroFighters Assault low performance

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#247]
Just reporting that this game has performance issues in LLE mode. Seems to run quite well with AL's RDP

**Comment by purplemarshmallow** [comment]
fixed?
it's as fast as other games in LLE
and it's much faster than with angrylion's plugin

**Comment by theboy181** [comment]
Just tested with AL (official compile) of AL RDP it is 5 VI/s faster for me running at a total of 60 VI/s

The intro just before the title screen drops as low as 35 VI/s on GLideN64

**Comment by purplemarshmallow** [comment]
LLE performance is not so good in general. z64gl is much faster. But for me it's still faster than angrylion's plugin. I think it's a general problem not related to this game.

**Comment by theboy181** [comment]
Could be.. I posted this example to @gonetz when he requested from the forum. He was looking for examples of slow games. This game is slower than other plugins. 

can you test with this DLL https://www.dropbox.com/s/wg1tlwv7qwphkon/AngryLion%27s%20PA.dll?dl=0

**Comment by purplemarshmallow** [comment]
Yes, there's a performance drop just before the title screen
does not happen with software renderer

**Comment by theboy181** [comment]
Closing since GLideN64's focus is on HLE emulation.
