### ISSUE TITLE
Indiana Jones and the Infernal Machine - Freeze going to Level 13

### ISSUE THREAD

**Issue by thekovic** [gonetz/GLideN64#2473]
After finishing Level 12 (Meroe), the game drops to 0-1 FPS in the shop between levels. The items and item icons are not rendered and it is impossible to give the game any input making it impossible to progress further.

![image](https://user-images.githubusercontent.com/72971433/112762221-d13f8c00-8ffe-11eb-9a45-5b31f1245392.png)

**Comment by Jj0YzL5nvJ** [comment]
mupen64plus/mupen64plus-core#572
https://ci.appveyor.com/project/gonetz/gliden64/build/artifacts?branch=master

**Comment by thekovic** [comment]
I read through the issue you linked. Sadly, none of the workarounds mentioned there worked for me. The issue is present on both Pure Interpreter, Cached Interpreter and Dynamic Recompiler.

I also downloaded the version of GlideN64 you linked (GLideN64-d27ce478-for_Mupen64Plus.7z). Didn't help either.

I am attaching my config files and a save state to reproduce the issue so you can have more information.

[indy_freeze_config-save.zip](https://github.com/gonetz/GLideN64/files/6223154/indy_freeze_config-save.zip)

**Comment by Jj0YzL5nvJ** [comment]
Works with `CountPerOp = 1`.

**Comment by thekovic** [comment]
That worked! Thank you!

**Comment by olivieryuyu** [comment]
pls close
