### ISSUE TITLE
Black Screen on intel hd graphics 3000

### ISSUE THREAD

**Issue by Nintendelta** [gonetz/GLideN64#2475]
Exactly what the title says

**Comment by IronYoshi64** [comment]
Not enough details. We need emulator, GLideN64 version, any custom settings you applied, etc. Also if not already, get latest master from the appveyor site: https://ci.appveyor.com/project/gonetz/gliden64/branch/master/artifacts

**Comment by Nintendelta** [comment]
> Not enough details. We need emulator, GLideN64 version, any custom settings you applied, etc. Also if not already, get latest master from the appveyor site: https://ci.appveyor.com/project/gonetz/gliden64/branch/master/artifacts

I'm using Project64

**Comment by Jj0YzL5nvJ** [comment]
With which version of Windows?
With which video card?
With which version of the emulator?
With which version of the plugin?
With which game?

**Comment by gonetz** [comment]
@Jj0YzL5nvJ I guess, the reported does not want his problem be solved.
@Nintendelta we are not mind-readers. Please provide all relevant information.
Check other reports as examples.

**Comment by Nintendelta** [comment]
Sorry that I keep things really brief but not I will explain everything. Using windows 7 with the latest version of gliden64 and project 64 2.3.2 my graphics card is intel hd graphics 3000 (I'm using a laptop) and the game is super Mario 64. No I did not put any custom setting in project64. Hope that explains everything

**Comment by gonetz** [comment]
> Hope that explains everything

Yes, it does. GLideN64 requires OpenGL version 3.3 or above.
Your graphics supports OpenGL version 3.1
https://community.khronos.org/t/intel-hd-3000-support-of-opengl/66706

**Comment by Nintendelta** [comment]
> > Hope that explains everything
> 
> Yes, it does. GLideN64 requires OpenGL version 3.3 or above.
> Your graphics supports OpenGL version 3.1
> https://community.khronos.org/t/intel-hd-3000-support-of-opengl/66706
Ok, thanks.
