### ISSUE TITLE
Latest builds broken in official Mupen64Plus?

### ISSUE THREAD

**Issue by BigheadSMZ** [gonetz/GLideN64#2479]
Downloaded latest Mupen64plus from here:
https://github.com/mupen64plus/mupen64plus-core/releases

Downloaded latest GlideN64 build from here:
https://ci.appveyor.com/project/gonetz/gliden64/builds/38700447/artifacts

Threw it all together, set up a batch with:
mupen64plus-ui-console --gfx mupen64plus-video-GLideN64 "../RomPath"

And it just freezes with a white screen. The latest official GlideN64 public release v4.0 works without issue. Maybe I configured something incorrectly? But just replacing the .dll with the older version and I can get games to load fine.

**Comment by Jj0YzL5nvJ** [comment]
mupen64plus/mupen64plus-core#769

Try:
```
mupen64plus-ui-console --gfx mupen64plus-video-GLideN64.dll --set Video-GLideN64[ThreadedVideo]=False "../RomPath"
```

**Comment by BigheadSMZ** [comment]
Thanks, that seems to have done the trick! I am now able to use the latest version in Mupen64Plus without issue.

**Comment by fzurita** [comment]
Yeah, it really should be off by default since the front end has to explicitly support it. I don't believe ui-console supports the threading.

**Comment by Jj0YzL5nvJ** [comment]
> Yeah, it really should be off by default since the front end has to explicitly support it. I don't believe ui-console supports the threading.

Works on Linux x64, fails on Windows x86 and x64 (MSVC). Angrylion-Plus works fine with the same MSVC version.
I don't know how it works with MSYS2 and similar subsystems.

**Comment by gonetz** [comment]
> Yeah, it really should be off by default since the front end has to explicitly support it.

Done in 827cc229
