### ISSUE TITLE
Blast Corps not woring with FB emulation on

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#248]

**Comment by Aquatakat** [comment]
I think this is a duplicate of this: https://github.com/gonetz/GLideN64/issues/125

**Comment by theboy181** [comment]
I'm not sure. I think shadow are working though just weird buggy screen and eventual crash.

**Comment by olivieryuyu** [comment]
duplicate please close ticket!

**Comment by theboy181** [comment]
fixed from todays release
