### ISSUE TITLE
Overscan crop leaves black bars on top and bottom of screen

### ISSUE THREAD

**Issue by mariomadproductions** [gonetz/GLideN64#2483]
This is with mupen64plus-libretro-nx, but I was [told](https://github.com/libretro/mupen64plus-libretro-nx/issues/335) it was an upstream issue. It doesn't happen in m64p.

Compare before applying overscan to after applying overscan:
![Screenshot from 2021-04-22 18-59-03](https://user-images.githubusercontent.com/9919020/115766747-38532500-a3a0-11eb-9893-954e1ff7877b.png)
![Screenshot from 2021-04-22 19-23-09](https://user-images.githubusercontent.com/9919020/115766752-39845200-a3a0-11eb-8d64-94276e6d9097.png)

It works fine for the left and right, but not for the top and bottom. Same result nomatter if RetroArch's automatic overscan crop is turned on or off, and nomatter if RetroArch's integer scanling is on or off.

**Comment by m4xw** [comment]
(Not a GLideN issue)

**Comment by mariomadproductions** [comment]
https://github.com/libretro/mupen64plus-libretro-nx/issues/335#issuecomment-825579592
