### ISSUE TITLE
Failure to compile in Fedora 34

### ISSUE THREAD

**Issue by thesourcehim** [gonetz/GLideN64#2488]
In file included from /mnt/d/projects/git/mupen64plus/GLideN64/src/Graphics/ColorBufferReader.h:4,
                 from /mnt/d/projects/git/mupen64plus/GLideN64/src/Graphics/ColorBufferReader.cpp:2:
/mnt/d/projects/git/mupen64plus/GLideN64/src/./Textures.h:108:15: error: «size_t» does not name a type
  108 |         const size_t m_maxCacheSize = 8000;
      |               ^~~~~~
In file included from /mnt/d/projects/git/mupen64plus/GLideN64/src/Graphics/ColorBufferReader.h:4,
                 from /mnt/d/projects/git/mupen64plus/GLideN64/src/Graphics/ColorBufferReader.cpp:2:
/mnt/d/projects/git/mupen64plus/GLideN64/src/./Textures.h:13:1: note: «size_t» is defined in header «<cstddef>»; did you forget to «#include <cstddef>»?

**Comment by gonetz** [comment]
https://en.cppreference.com/w/c/types/size_t

Please try to include <stddef.h>

**Comment by thesourcehim** [comment]
It helped. Looks like it's a compatibility issue with the new gcc, fedora moved to gcc 11.

**Comment by thesourcehim** [comment]
Can you please add #include <stddef.h> to src/Textures.h ?

**Comment by gonetz** [comment]
Done. Thanks for the report.
