### ISSUE TITLE
"FACTOR 5 GAMES" AA emulation breaks Title Screen's

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#249]
Black Screen at title screen when AA emulation is on.

Indiana Jones, Rouge Squadron,  Battle for Naboo.. ect..

**Comment by theboy181** [comment]
Tested a little further today. When the FBE is used the MENU is rendered really dark, but if you use AERO transparencies you can see that the screen is getting rendered.

To see what I am talking about DRAG the window under the TASKBAR at the bottom of the screen while using AERO. It will show that the menu is actually getting rendered.  (screen grabs didn't show my findings)

**Comment by purplemarshmallow** [comment]
fixed?
Rogue Squadron works perfectly here

**Comment by theboy181** [comment]
Still black for me, looks like its an AA issue.. updated
@ gonetz

**Comment by purplemarshmallow** [comment]
pull request #500 created

**Comment by theboy181** [comment]
Issue still exists with AA on after DEV.

@gonetz

**Comment by theboy181** [comment]
Screen now flashes with AA on .. could it be linked to interlacing?

**Comment by purplemarshmallow** [comment]
But AA + LLE does not seem to work in general

**Comment by theboy181** [comment]
How so?  It looked aliased to me during my rouge squadron test.
