### ISSUE TITLE
Odd issues at certain resolutions after "use screen coordinates to render primitives"

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#2494]
After https://github.com/gonetz/GLideN64/commit/81318c54456957b818e51aa37c31b9ead62ae7c9 there are some odd issues at certain resolutions. At 640x480 or 800x600 everything works fine, but at 1440x1080, I'm seeing issues like this:

![the_legend_of_zelda-000](https://user-images.githubusercontent.com/11581687/116798159-d0e15780-aaba-11eb-877d-53aa756468b5.png)

It seems like the view port is starting at the wrong location.

Also, only Mali GPUs seem to be affected. These are very new GPUs.

**Comment by standard-two-simplex** [comment]
Is the phone's screen resolution big enough to handle those output resolutions? I get a cut picture if I set the resolution above the supported one by my monitor, but not a missplaced one.

What about using a small output resolution and a 5x native rendering resolution? Does it bug too?

**Comment by gonetz** [comment]
> Also, only Mali GPUs seem to be affected. These are very new GPUs.

Probably a driver issue. Desktop is ok in that resolution.
"use screen coordinates ..." indeed changed viewport setting code, but is simpler now.

**Comment by fzurita** [comment]
@standard-two-simplex it is higher than the phone resolution. This shouldn't matter though because Android is creating a virtual frame buffer at my chosen resolution. Then gets downscaled/upscaled to the phone resolution before its shown to the user. 

It is probably a Mali bug.

**Comment by fzurita** [comment]
So before the changes, this is what a setViewPort would like like in ```GraphicsDrawer::_updateViewport()```:
```
2021-05-07 14:37:37.443 26554-26602/org.mupen64plusae.v3.alpha.debug E/GLideN64: GraphicsDrawer.cpp:275,ERROR, "VIEWPORT: offset=0x0 size=1440x1080"
```

After the changes, we have this:
```
2021-05-07 14:31:26.598 25835-25892/org.mupen64plusae.v3.alpha.debug E/GLideN64: GraphicsDrawer.cpp:261,ERROR, "Set viewport update: offset=-4608x-4608 size=9216x9216"
```

**Comment by fzurita** [comment]
@standard-two-simplex from https://www.khronos.org/registry/OpenGL-Refpages/es3/html/glViewport.xhtml

> Viewport width and height are silently clamped to a range that depends on the implementation. To query this range, call glGet with argument GL_MAX_VIEWPORT_DIMS.

**Comment by standard-two-simplex** [comment]
> The new viewport sizes are huge.

Yes, this was intentional. The idea was to map all the screen to a small rectangle [0,1/1024]x[0, 1/1024] to avoid clipping and then use the viewport transform to recover the geometry. I chose 1024 because it is a power of 2 and it bounds any know native resolution of N64 games.

> Can we fallback to the old method in the case where GL_MAX_VIEWPORT_DIMS is < the dimensions that we are trying to use right now?

This would need lots of code restored. Instead, it should be possible to do one of these.
 - Map the screen to a [-1/512, 1/512] x [-1/512, 1/512] rectangle, which should halve the needed viewport size.
 - Map the screen to a [-1/n, 1/n] x [-1/n, 1/n] rectangle, where n is determined dinamically based on the resolution the game chooses. Harder to implement but it should also work. Maybe it is possible to choose a non power of two without losing accuracy, I picked a power of two for safety.

I will implement the first one, which should be OK for your device. If it's not too hard, I might test the other option too.

**Comment by fzurita** [comment]
So this is going to affect some desktop GPUs. A lot of desktop GPUs have a max viewport size of 16384x16348. That means, for a game that renders at 640x480, in a desktop GPU that has a max viewport size of 16384x16384, may resolution will be 5120x3840. See here: https://opengl.gpuinfo.org/displaycapability.php?name=GL_MAX_VIEWPORT_DIMS[0]

**Comment by fzurita** [comment]
Your second option will probably be the wiser one to implement. There are a lot of devices with even smaller max viewport size that should be able to run at a little higher resolutions: https://opengles.gpuinfo.org/displaycapability.php?name=GL_MAX_VIEWPORT_DIMS&esversion=2

**Comment by standard-two-simplex** [comment]
You may try the following two commits
https://github.com/standard-two-simplex/GLideN64/commits/smaller_viewport
They should be tested for missalignments and in the case of the 640x640 clipping space, for games that might render outside of such a screen.

If the 640x640 space works correctly, the max viewport resolution would be halved at most, which I think is quite acceptable. I doubt GPUs will run the fragment shader fast enough, at least my GPU starts being too slow at lower than the maximum resolution allowed.

**Comment by fzurita** [comment]
At 1024x1024, I can go up to 2160x1620 resolution in my front end without issue.
At 640x640, I can go up to 3840 x 2880 resolution without an issue.

Am I looking for a specific issue at the smaller viewport size?

**Comment by standard-two-simplex** [comment]
> Am I looking for a specific issue at the smaller viewport size? 

There are two types of glitches that may happen.
- Missalignments on polygon edges: sometimes texture coordinates accept no precision errors. If there is one, it looks as if some rows of pixels are shifted left/right with respect to the other rows. Usually happens with 2D and is clearly visible.
- Clipped geometry on the side: screen coordinates of 640 are mapped to normalized coordinate 1.0, so anything bigger will be clipped by OpenGL. If any game renders outside of that, it will be unintentionally clipped.

**Comment by standard-two-simplex** [comment]
![ogrebattle64-000](https://user-images.githubusercontent.com/12202580/117583543-f64c1200-b107-11eb-9792-06f1e2d62c7b.png)

This is the type of misalignment that I mean. The menu letters are wrong. It happened while working on the vertex offset, not with these builds.

**Comment by fzurita** [comment]
I see, also, in your code I see that whenever you change one number, you also have to change a corresponding number in the shader. I would recommend setting the number in the shader either using a uniform or more dynamically during shader generation.

**Comment by standard-two-simplex** [comment]
> For example, you could create a constant and in the shader use the constant divided by 2.

Yes a constant can be created, but is needed both in the shader and in updateViewport().

**Comment by fzurita** [comment]
I checked various 2D only games like mischief makers, Yoshi's story, mortal kombat, as well as a few 3d games and I saw no issues.

**Comment by gonetz** [comment]
> Okay I pushed a new commit.

Thanks!
I merged it: 9b57c4f62e
I only added formatting to properly print SCREEN_SIZE_DIM to stringstream.

**Comment by gonetz** [comment]
Err, native-res texrects killed again! I'm reverting the changes for now.

**Comment by gonetz** [comment]
Fixed.

**Comment by gonetz** [comment]
@fzurita please test and close.

**Comment by fzurita** [comment]
@gonetz You should update the GLSL shader storage format version:

https://github.com/gonetz/GLideN64/blob/master/src/Graphics/OpenGLContext/GLSL/glsl_ShaderStorage.h#L23

**Comment by fzurita** [comment]
@gonetz yes, it works correctly, the device can now go up to 3840 x 2880 without issue. Any higher and the same issue appears again. I think ideally it would be better to implement a more dynamic solution, but at least now the lower resolutions can be used.
