### ISSUE TITLE
CBFD Depth issues at 1440x1080

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#2495]
At exactly 1440x1080 resolution,  CBFD has some odd issues. I could only the issue at this specific resolution, not any higher or lower.  See the screenshot: 

![Screenshot_20210501-211031_M64Plus AE](https://user-images.githubusercontent.com/11581687/116798865-c8d8e600-aac1-11eb-93aa-55bccf87ef2c.jpg)

Also, oddly, screenshots don't work at that resolution either. I had to take a picture using an external tool.

**Comment by fzurita** [comment]
This issue seems to go back for quiet a while, so it's not recent. I can try to bisect to the exact revision later.

**Comment by gonetz** [comment]
Can it be related to #2494?

**Comment by fzurita** [comment]
I don't think so since it happens in devices even that have a large maximum viewport. Have you tried this resolution on desktop?

**Comment by gonetz** [comment]
> Have you tried this resolution on desktop?

Yes. I see no problems. I haven't checked the location on your screen shot though.

**Comment by fzurita** [comment]
It may not be a driver bug since it happens with Mali and Adreno GPUs.

**Comment by gonetz** [comment]
Could you give me a save from a place where this bug a clearly visible?

**Comment by fzurita** [comment]
Here you go for mupen64plus 
[depth_bug.Conker's Bad Fur Day (U) [!].zip](https://github.com/gonetz/GLideN64/files/6493700/depth_bug.Conker.s.Bad.Fur.Day.U.zip)

**Comment by gonetz** [comment]
No depth issues with your save on my PC. The only issue - Conker's shadow disappears sometimes.

**Comment by gonetz** [comment]
Could you check, how old the problem is?

**Comment by fzurita** [comment]
I went as far back as when Android started using cmake and the problem is still there. It gets more difficult to check before then.

**Comment by fzurita** [comment]
I can only make the issue go away if I disable frame buffer emulation.

**Comment by gonetz** [comment]
> I can only make the issue go away if I disable frame buffer emulation.

This is strange. The plugin uses FBO with and without fb emulation. It is hardly a depth compare issue.
I just noticed that your screen shot looks weird. It should look like this
![conker_bfd-000](https://user-images.githubusercontent.com/8983092/119262673-3cc06700-bc06-11eb-85a9-f5129e42f3c3.jpg)
That is, the place where Conker is staying is just cut out on your screen shot. It looks like the polygons just removed (clipped, culled). But why it happens only with exactly 1440x1080 resolution? I have no ideas.
