### ISSUE TITLE
Pokemon Puzzle League video issues

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#250]
The video's in this game do not play correctly.

**Comment by gonetz** [comment]
Frame buffer emulation is required for video. I see no problems with video playback.

**Comment by theboy181** [comment]
You are correct that it looks better with FB on but it seems to skip frames (not smooth) are there preferred FB settings?

**Comment by gonetz** [comment]
Intro video runs smooth for me with any settings.

**Comment by theboy181** [comment]
I run some more tests when I get home from work.

**Comment by theboy181** [comment]
OK I have tested and it only seems to happen when you transition from a video to the games. The game backgrounds also have some weird blanking bug.

**Comment by gonetz** [comment]
Please test video with latest build and close the issue if it works ok.
Please open another issue for game backgrounds.

**Comment by theboy181** [comment]
I haven't seen any to GLideN64 since I reported the LLE gfx issue. Is there a newer build?
The intro video with the pokeball is till not correct. the video jumps around.

I can make a video later if you wish.

Detect CPU writes to the FB is the only FBE I have turned on.

**Comment by olivieryuyu** [comment]
the intro works nicely, except a small shaking.

Please close ticket

**Comment by purplemarshmallow** [comment]
videos work for me too
close?

**Comment by gonetz** [comment]
Let's wait for theboy181 decision.

**Comment by theboy181** [comment]
Hey all.

I checked again. the opening video (pokeball) is still shaking, and the background scrolling still glitches out. The transition to the title screen also flashes. 

I just tested against the real HW.

**Comment by purplemarshmallow** [comment]
frame buffer emulation breaks backgrounds in 3d puzzles
maybe update the title
![gliden64_puzzle_league_n64_000](https://cloud.githubusercontent.com/assets/7283660/7458536/730921b2-f295-11e4-97cd-a9c76e5be2ac.jpg)

**Comment by theboy181** [comment]
intro video no longer works

**Comment by Enker** [comment]
Frame buffer emulation also makes some graphics look bad at 1x res. Only happens with HLE.

![controls_hle_1x](https://cloud.githubusercontent.com/assets/24740735/21703444/315889d8-d380-11e6-9796-29ee39a16fbb.png)

**Comment by theboy181** [comment]
leaving open for other issues mentioned here.

**Comment by oddMLan** [comment]
All the other issues mentioned here (intro shaking, graphics bad at 1x res) are not current

only current bug is the one @purplemarshmallow mentioned
![GLideN64_PUZZLE_LEAGUE_N64_000](https://user-images.githubusercontent.com/7278372/68204466-5008d480-ff85-11e9-9ea3-56b70f0c9e02.png)

I suggest renaming the issue to better reflect it

**Comment by olivieryuyu** [comment]
To be closed and a new ticket to be open

**Comment by gonetz** [comment]
Closed. New ticket: #2852
