### ISSUE TITLE
In Project 64, when I exit full screen mode, the screen goes black.

### ISSUE THREAD

**Issue by 23Bluemaster23** [gonetz/GLideN64#2500]

**Comment by gonetz** [comment]
Project 64 version?
GLideN64 version?
OS?
Graphics card?

**Comment by 23Bluemaster23** [comment]
![Project64_lGutVoXS6V](https://user-images.githubusercontent.com/49736771/118398728-efe9f880-b627-11eb-8075-ce63e6a96bf7.png)

Glide N64 4.0.7

![winver_NZYA4gIMYu](https://user-images.githubusercontent.com/49736771/118398778-232c8780-b628-11eb-9dd0-a73eae2244df.png)

![dxdiag_iei1tTtl5C](https://user-images.githubusercontent.com/49736771/118398898-91714a00-b628-11eb-903b-9dd2bf095419.png)

**Comment by Jj0YzL5nvJ** [comment]
In the case of "Intel* Graphics", you must also add the processor series in order to know the exposed capabilities of OpenGL.
Examples: `i7-5700HQ`, `i5-6500`, `i3-7100E`, etc.

**Comment by 23Bluemaster23** [comment]
![explorer_xT1xpF8167](https://user-images.githubusercontent.com/49736771/118499500-001bd980-b6f5-11eb-9e77-3c147fcddc67.png)

**Comment by Jj0YzL5nvJ** [comment]
It's a Gen 3 CPU... Gen 4 also doesn't support OpenGL 3.3 on Windows. Gen 8 or higher is recommended for Intel graphics.

**Comment by 23Bluemaster23** [comment]
So there is no simple solution?

**Comment by Jj0YzL5nvJ** [comment]
The simplest solution is to use a independent video card that supports at least OpenGL 4.5.
Another solution would be to implement [ANGLE](https://en.wikipedia.org/wiki/ANGLE_(software)) for Windows users... I think it would be easier to implement Vulkan... but that would not benefit you at all.

**Comment by gonetz** [comment]
> It's a Gen 3 CPU... Gen 4 also doesn't support OpenGL 3.3 on Windows.
