### ISSUE TITLE
[Regression] Mario Kart 64 - Glitchy gfx in Title screen and other menus

### ISSUE THREAD

**Issue by IronYoshi64** [gonetz/GLideN64#2506]
On GLideN64 rev. be851a3, the version that comes with Project64 3.0, has horrible glitchy graphics in all the Mario Kart 64 title and menus. I using all default settings that are provided with the version, besides the windowed mode and fullscreen mode sizes.

Here are some pictures of what they look like:
![GLideN64_MARIOKART64_000](https://user-images.githubusercontent.com/57850880/119847022-411fa500-bed0-11eb-88a3-378524b5f8e4.png)
![GLideN64_MARIOKART64_001](https://user-images.githubusercontent.com/57850880/119847026-41b83b80-bed0-11eb-9bc9-7c664a0fb9db.png)
![GLideN64_MARIOKART64_002](https://user-images.githubusercontent.com/57850880/119847031-4250d200-bed0-11eb-86de-531a05dbd82a.png)
![GLideN64_MARIOKART64_003](https://user-images.githubusercontent.com/57850880/119847034-42e96880-bed0-11eb-8f3a-acf8d1f3a5ff.png)

**Comment by IronYoshi64** [comment]
Ok. I found out that the WTL version doesn't have the "Enable native-res bounds for texture coordinates" option in its UI and can't be disabled through the custom ini either, so its always forced on. 

For Mario Kart 64, currently using the QT version 15668b90, I found out the best settings for the plugin, which are these:

graphics2D\enableNativeResTexrects=0
graphics2D\enableTexCoordBounds=1

![2021-05-28 09-42-07](https://user-images.githubusercontent.com/57850880/120002445-7690c500-bf9a-11eb-8308-51b6827fa03d.png)

This removes the extreme blurriness and glitchy lines on the menus.

**Comment by oddMLan** [comment]
The current master of GLideN64 has a lot of regressions and hasn't been tested enough and I advised zilmar to include the version before the texture coords refactor (https://github.com/gonetz/GLideN64/commit/1d90610782343ad965c4cfdc2ffc1a8dc39256bc) for 3.0 release but ran out of time because he wanted to push the release on the anniversary date. This is partly my fault for reporting there was an issue so late, but hopefully a hotfix will be pushed to release this weekend.

**Comment by fzurita** [comment]
Yeah, I see the exact same issue in Android too.

**Comment by IronYoshi64** [comment]
> Yeah, I see the exact same issue in Android too.

Oh ok. Good, I glad I not only one that has this issue, so its definably a regression or some certain settings need to be tweaked by default.

**Comment by fzurita** [comment]
It's the default in GLideNUI:
https://github.com/gonetz/GLideN64/blob/master/ini/GLideN64.custom.ini#L155

Does the WTL version of the plugin load GLideN64.custom.ini?

**Comment by IronYoshi64** [comment]
The WTL version does load the custom.ini settings file, but like I said, the "Enable native-res bounds for texture coordinates" option is completely missing and apparently in WTL, its always forced on no matter what. I even tried to manually add the settings that I already posted above and it does not work.

**Comment by fzurita** [comment]
@standard-two-simplex Even forcing enableTexCoordBounds to 1, it graphics don't look correct for Mario Kart 64. The only way I can get them correct is by setting the native resolution factor to 1.

**Comment by fzurita** [comment]
Ok, I think I see part of the problem. EnableNativeResTexrects doesn't work well with EnableTexCoordBounds. Once I disable EnableNativeResTexrects things work well again.

**Comment by standard-two-simplex** [comment]
The problem seems that `bUseTexRectDrawer` in GraphicDrawer::setTextureRectangle() is a strict condition while the scale definition in URasterInfo::update() only checks for `enableNativeTexrects != 0`.

Disabling this line seems to fix the issue. I don't understand why the condition is so strict, so I don't know if this is the correct fix.
https://github.com/gonetz/GLideN64/blob/15668b9064bbc0aca524d9a74ece98aaa9260908/src/GraphicsDrawer.cpp#L1236

**Comment by standard-two-simplex** [comment]
> Ok. I found out that the WTL version doesn't have the "Enable native-res bounds for texture coordinates" option in its UI and can't be disabled through the custom ini either, so its always forced on.

It is actually always disabled and can't be enabled through the custom ini.

> I found out the best settings for the plugin, which are these:
graphics2D\enableNativeResTexrects=0
graphics2D\enableTexCoordBounds=1

There is a bug with the compatibility between enableNativeResTexrects and the new texture coordinate correction, which I cited above. It should be possible to fix.

**Comment by fzurita** [comment]
@standard-two-simplex I'm seeing this exact same problem with the fast path at 1x native resolution factor. Do you have any clues?

**Comment by fzurita** [comment]
@standard-two-simplex Apparently just getting rid of this condition and always setting the vectorOffset to 0.0 fixes the issue at 1x:

https://github.com/gonetz/GLideN64/blob/e9a6f258afd7988f64a990d49be545219fb71e4c/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramUniformFactoryFast.cpp#L39

At other native resolution factors, you still need the native res texrects options.

**Comment by standard-two-simplex** [comment]
> Do you have any clues? 

I'm not very sure what was reverted and what was not. It seems to me that texture coordinates are normalized in the fast path, but the offsets (`uTextureOffset`) are not. That should cause big glitches, why is it not? Are this uniforms affecting the scene in any way?

As I recall, there used to be a 0.5 shift in the old texture filter.
```
"  mediump vec2 offset = fract(texCoord*texSize - vec2(0.5));				\n"
```

The vertex offset replaces that more accurately and also takes in to account the non bilinearly filtered textures, like it was the case of Ogre Battle dialog boxes or BAR menus.

If you remove the vertex shift, you may want to test it well for both bilinear and point sample textures. You can check Zelda OOT Hud and start menu for bilinear (blurry with an incorrect shift) and the pictures in this thread (#1047) for point sample.

**Comment by gonetz** [comment]
> Apparently just getting rid of this condition and always setting the vectorOffset to 0.0 fixes the issue at 1x

Confirmed. With vertexOffset = 0.5f, both filtered and unfiltered textures look incorrect in native res, fast texture path.
