### ISSUE TITLE
[Feature Request] That you can remove in game black borders

### ISSUE THREAD

**Issue by Toadfield** [gonetz/GLideN64#2514]
I saw [this old video](https://www.youtube.com/watch?v=Nh3-d0XJTEQ) today,I newer knew that you could remove those black borders,that would be useful for many games.
So would that work with GlideN64?

**Comment by IronYoshi64** [comment]
Yes, you can remove the black bars from all games using GLideN64's **Overscan** option.
Like for example, if you want to remove bars in SM64, set these like this:
Top - 8
Left - 4
Right - 4
Bottom - 9

**Comment by Toadfield** [comment]
That is something different,in the video you can see what is behind the black border,nothing gets overscanned there.

**Comment by IronYoshi64** [comment]
> That is something different,in the video you can see what is behind the black border,nothing gets overscanned there.

Oh. That is what you meant. Yeah GLideN64 doesn't have have anything really like that. Although for Super Mario 64, i think there is a gameshark code that can do what that dude did in the video for all Plugins.

**Comment by Toadfield** [comment]
There are also other games with those black borders,for example banjo kazooie.

**Comment by IronYoshi64** [comment]
I happen to have a code for SM64 that removes the black bars and shows what's behind it as well.

Remove Vertical Black Bars (larger screen area)
802473A7 00BC
802473B3 0000
8024748E 0000
80247966 0000
80247996 0000
8027B4F6 0000
8027B46A 0000
8027B4AA 0000
8027B582 0000
8027C99F 00BC
8027C9AB 0000
Notes: This removes the black bars at the top and bottom of the screen, for larger screen area. Sadly during the End Credits, this causes some graphical glitches at the top and bottom of the screen, so recommended to turn this off before so.

**Comment by Toadfield** [comment]
Does that code also work with sm64 rom hacks?

**Comment by IronYoshi64** [comment]
> Does that code also work with sm64 rom hacks?

I not sure actually. I never really tried. I assume it would for most of them though.

**Comment by gonetz** [comment]
> I saw [this old video](https://www.youtube.com/watch?v=Nh3-d0XJTEQ) today,I newer knew that you could remove those black borders,that would be useful for many games.
> So would that work with GlideN64?

No. If you want to remove black bars, use overscan. If you want to see, what is behind these bars, use rom hacking.
