### ISSUE TITLE
Extreme G picture is shaking / unstable

### ISSUE THREAD

**Issue by dezraj** [gonetz/GLideN64#2519]
I'm experiencing this weird issue with Extreme G. The picture becomes unstable and start shaking eventually when playing the game. It mostly happens in the game menus as far as I've noticed. I don't know exactly how to trigger it, but it looks like if you let the game demo run until it loads the first race and rapidly press A to leave it, it will probably trigger the bug in the menus.

I've recorded a video of the bug happening in m64p emulator in which I use the method described above to reproduce it: https://drive.google.com/file/d/1WCHv1WtbC69d0Y4p51BJ9pSxoAIL8k9d/view?usp=sharing

It's somewhat difficult to get used to this shaking screen and enjoy the game play, that's why I'm reporting it.

Setup:
Windows 10
i5-10400 with 16gb RAM
Intel UHD630 graphics with latest drivers
m64p and Project64 (latest nightly) with all default plugin options.

An user on the m64p GitHub could reproduce this bug on upstream. Please refer to his post for more info:
https://github.com/loganmc10/m64p/issues/159

Thank you in advance for your time.

**Comment by fzurita** [comment]
Does it happen if you disable threading? It looks similar to the issue with starcraft shaking with treading enabled.

**Comment by dezraj** [comment]
Are you talking about the "enable threaded video" option? If so, it is already disabled. I couldn't find any other options related to "threading" in the plugin interface. All options are default.

**Comment by fzurita** [comment]
Yep, I was referring to that. Since it's not that, it's possible that the game may be doing this on purpose to implement interlaced video.

**Comment by gonetz** [comment]
The game does weird things. These things cause wrong result. Hopefully fixed with 94ce6203b.
