### ISSUE TITLE
Missing top part of screen

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#252]
I took 3 screenshots AL's RDP in PJ, GLideN64 in PJ, and GLideN64 in Mupen64.

![capture](https://cloud.githubusercontent.com/assets/9299743/6315328/7b4b1ad0-b9b3-11e4-8720-747d7f1cc4b6.PNG)

As you will see the top part of the screen is totally missing. I know you talked about this on the forum, but I didn't realize that the GFX were actually missing till today. In Mupen this part of the screen is being used by Mupen's GUI so its not as noticeable, but still not correct.

**Comment by gonetz** [comment]
Please test it with latest version.
