### ISSUE TITLE
Broken N64 Logo in Pokemon Stadium 1 with enableTexCoordBounds off

### ISSUE THREAD

**Issue by m4xw** [gonetz/GLideN64#2523]
Hey @standard-two-simplex @gonetz 
Just wanted to let you know that with enableTexCoordBounds being opt-in, theres a regression occuring in Stadium 1 on the N64 Screen
This only happens when its off and not native res.
![image](https://user-images.githubusercontent.com/13141469/123443706-6f2efc80-d5d6-11eb-9284-c495f492671c.png)

I am not sure what to do for my fork. fzurita opted defaulting it to 1, you guys seem to want it opt-in (hence the ini entries).
Should we just slap it in the INI like the others or any downsides happening with it enabled by default?

**Comment by standard-two-simplex** [comment]
It only happens with UseNativeResolutionFactor = 0 and it is fixed in https://github.com/gonetz/GLideN64/pull/2521

**Comment by gonetz** [comment]
@m4xw #2521 is merged. Please test again.

**Comment by m4xw** [comment]
I cherry picked that PR already and confirm all is fine!
Good to see you back!
