### ISSUE TITLE
Is anisotropic filtering always ON or am I missing something?

### ISSUE THREAD

**Issue by bslenul** [gonetz/GLideN64#2527]
Hey!

So I wanted to mess with the anisotropic filtering option but for some reason it seems to be always ON (an maxed it seems). I've read that with the "Enable LOD/mip-mapping" option enabled there shouldn't be any AF, I ~~double~~ triple checked the settings and AF is set to "0" (so OFF).

Is this a bug or am I doing something wrong? I've tried with Mupen64Plus-Next (libretro core), Project64 and M64Py and they all behave the same :/ I'm super confused about it, I tried a lot of combinations with different settings but no matter what it's always enabled.

Example with Project64:

![image](https://user-images.githubusercontent.com/33353403/125986516-c218f1be-e0f0-451c-99e6-37f333632a5e.png)

![image](https://user-images.githubusercontent.com/33353403/125984088-1d966f5f-42c0-4a9e-96a7-6e5f1952d00a.png)

![image](https://user-images.githubusercontent.com/33353403/125984105-85e05e71-4d79-4f9d-818d-c452000dfb4c.png)

And this is what I expected (screen taken in Mupen64Plus-Next with ParaLLEl plugin and LOD ON):

![image](https://user-images.githubusercontent.com/33353403/125985971-07a22be8-b261-427b-a2db-24f2a50f14b6.png)

Windows 10 (**edit:** same behavior on my Linux Mint VM) / i5-4670K / GTX 970

**Comment by gonetz** [comment]
Hi Bobby,

Yes, anisotropic filtering was totally broken, and probably long ago.
The condition, which set the anisotropic depended on unset variable, so the result was random.
I fixed it. Please test the current master build. I can't say that I see a noticeable difference with and without anisotropic filtering, but I checked in debugger that anisotropic filtering texture parameter is set correctly now.

**Comment by bslenul** [comment]
Hey, thank you for taking some time to look at this! :)

Unfortunately it still seems to be stuck at max value (I checked in the .cfg and the new "anisotropy" setting is properly set to "0"):

![image](https://user-images.githubusercontent.com/33353403/126676181-19222292-7149-4d95-bf62-7ac98b3949d0.png)

And with Rice as a comparison, with anisotropy set to "0" as well, the ground is blurry very quickly:

![image](https://user-images.githubusercontent.com/33353403/126675652-6735cb16-8520-4f95-873e-90661a558569.png)

**Comment by gonetz** [comment]
As far as I know, Rice does not implement proper mip-mapping emulation.
It may explain the difference.
GLideN64 does not use standard OpenGL mip-mapping since it is incompatible with N64 way of doing mip-mapping.
GLideN64 uses shaders-based LOD calculation and textures blending. I'm not sure that anisotropic should have any effect in this case. However, I can guarantee that GL_TEXTURE_MAX_ANISOTROPY_EXT parameter is set correctly now.

**Comment by bslenul** [comment]
Sorry I'm not trying to be a dick or anything, just trying to understand why that blurry effect on the ground isn't reproducible with GlideN64, and why there's no difference with AF at "0" and "16".

Another example with Perfect Dark:

GlideN64 even with AF at "0", ground is never blurred (same result as "16"):

![image](https://user-images.githubusercontent.com/33353403/126767063-48c1eacc-499e-4036-8bb8-75023564ec02.png)

ParaLLel:

![image](https://user-images.githubusercontent.com/33353403/126766809-875958c9-a7c4-4e59-9fac-66286f58a368.png)

Angrylion:

![image](https://user-images.githubusercontent.com/33353403/126766818-61cd08b2-9e32-44fe-a242-e58a58ecbbee.png)

Maybe I'm just missing a setting? "EnableLOD" is ON but I'm not sure if there is any other setting that could have an impact on this?

**Comment by bslenul** [comment]
So I was testing some old builds to see if anisotropy OFF ever worked, and it did but it was 6 years ago 😅 

Public Release 1.1:

![gliden64_1 1-1](https://user-images.githubusercontent.com/33353403/126956823-66488d22-51cb-4439-b443-0acca2a5a357.png)

And then in 1.2 with the exact same settings, can't seem to turn it OFF:

![gliden64_1 2-1](https://user-images.githubusercontent.com/33353403/126957045-d22a9a72-c3a2-4552-8567-cb84efd41726.png)

And interesting thing (could be unrelated tho!), while I was testing these old builds I tried to reproduce #2536 in SpaceStation Silicon Valley, and the "inverted LOD" was not happening in 1.1:

![gliden64_1 1-2](https://user-images.githubusercontent.com/33353403/126957632-d22d5f98-cfdd-4f0b-8f5e-fccac55f8ec8.png)

But started happening with 1.2:

![gliden64_1 2-2](https://user-images.githubusercontent.com/33353403/126957490-0254c0a3-ed84-446a-ab47-31e206fe594e.png)

**Comment by gonetz** [comment]
> So I was testing some old builds to see if anisotropy OFF ever worked, and it did but it was 6 years ago 😅
> 
> Public Release 1.1:

I checked Public Release 1.1
I still can't say that I see the difference between full anisotropy and no anisotropy here. Mip-mapping on-off gives huge difference of course.

**Comment by bslenul** [comment]
Hey!

Yeah, it's looks like in 1.1 it was the opposite issue, like Anisotropy was always OFF 😓 

With latest version (73b2d00) it's a bit better: with LOD ON you get the "blur" on the ground, with it OFF you get sharp textures. So at least you can now choose between a blurrier and a sharper look 👍 

However:
* With LOD ON, Anisotropy value still doesn't change anything, there's no difference between "0" (OFF) and "16".
* The blur effect feels "weird" (you can see some vertical lines):

![image](https://user-images.githubusercontent.com/33353403/127148660-a5b1602a-3822-45bd-8a05-d241e0b64cb2.png)

compared to 1.1:

![image](https://user-images.githubusercontent.com/33353403/127148253-a88b4498-45c6-414d-841d-562af4ccf49a.png)

**Comment by bslenul** [comment]
I was so focused at the ground that I didn't even notice the texture of the wall in the background, looks very pixelated, almost like a PS1 texture.

**Comment by weinerschnitzel** [comment]
Maybe the vertical lines you mention are incorrect mipmap textures. I can't be certain, but I can say that the pixelated texture in the distance is probably expected with LOD and mipmapping enabled.

Lod and mipmapping are to use lower resolution texture data at a distance, but those textures should be higher resolution when you get closer. The Lod and mipmapping effect probably hides any effect anisotropic filtering makes. Anisotropic would have best effect when this is disabled (so only the higher resolution texture data is used.)

I can't test, but I think the 1.1 screenshot is better, closer to intended, than the current for the mid range textures. I could be wrong though.

**Comment by bslenul** [comment]
> I get the same result as below with LOD off and anisotropic on, when I expect some bluring with anisotropic on.

I'm a bit confused, isn't that normal? From my understanding if LOD is OFF it is expected to have sharp textures everywhere and the Anisotropy setting should have no impact at all.

The issue (as I understand it at least...) is with LOD ON, idk if anisotropic filtering works the same as on PC games (e.g. https://techguides.yt/wp-content/uploads/2020/05/AF_2.62.1.jpg), but normally the more you increase the value the further you'll have clean textures.

So to me with LOD OFF it works as it should, it only has issues with LOD ON. But I'm not pretending to be an expert or anything, far from it 😅 So maybe I'm completely wrong.
