### ISSUE TITLE
Space Station Silicon Valley - LOD doesn't look right...

### ISSUE THREAD

**Issue by Jj0YzL5nvJ** [gonetz/GLideN64#2536]
Textures that are further away appear in greater detail than those that are closer to the camera.

**EnableLOD = True**
<img src="https://i.imgur.com/NsekCqp.png" alt="" class="">

**EnableLOD = False**
<img src="https://i.imgur.com/sLD7bWu.png" alt="" class="">

Mupen64Plus savestate: [Silicon.Valley.zip](https://github.com/gonetz/GLideN64/files/6873589/Space.Station.Silicon.Valley.U.zip)

More: https://imgur.com/a/1bFwIt7
#1764

**Comment by standard-two-simplex** [comment]
@gonetz I realise that the changes proposed in #2203 were only merged into the GLES2 branch. I rechecked AngryLion's sources and I think that it is computing the maximum of changes of S and T per X and Y. 

https://github.com/gonetz/GLideN64/pull/2537

I tested the cases discussed in the issue above too.

**Comment by bslenul** [comment]
Idk if I made a mistake with compilation but it seems to work with the 32bit version:

![image](https://user-images.githubusercontent.com/33353403/127137088-ec435d48-44a7-4154-9a99-129c9e4c8adf.png)

but not with the 64bit version:

![image](https://user-images.githubusercontent.com/33353403/127137113-66b9c802-b561-4d2e-88ba-19ed6783e9f6.png)

**Comment by standard-two-simplex** [comment]
It should look the same. You need to clear shader cache, perhaps you had the old cache in one of them.

**Comment by bslenul** [comment]
Oh you're absolutely right, deleting the content of the "shaders" folder fixed it, sorry!

**Comment by gonetz** [comment]
> I tested the cases discussed in the issue above too.

Great, thanks! Merged.

**Comment by Jj0YzL5nvJ** [comment]
<details>
  <summary>It still looks too different than it does with Angrylion-Plus</summary>

<img src="https://i.imgur.com/mHGJPtQ.png" alt="" class="">
<img src="https://i.imgur.com/FN07QQt.png" alt="" class="">
<img src="https://i.imgur.com/Er73v4D.png" alt="" class="">
<img src="https://i.imgur.com/YooBE5q.png" alt="" class="">

</details>

**Comment by gonetz** [comment]
@Jj0YzL5nvJ Try builds from mip_map_load_refactor branch. It looks very close to AL RDP in this scene:
![silicon_valley-001](https://user-images.githubusercontent.com/8983092/131213404-7f2fc99a-935a-4ff8-b470-b1b9d0b7b7ae.jpg)

**Comment by gonetz** [comment]
@Jj0YzL5nvJ can it be closed?
