### ISSUE TITLE
Hi Resolution Textures not correct

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#254]
Not sure if I'm doing something wrong here.

https://www.youtube.com/watch?v=GzqV2tMBwuU&feature=youtu.be

**Comment by gonetz** [comment]
I guess you used old texture pack for SSB. As I remember the pack contains textures with wrong aspect, e.g. with 4x width and 2x height. Such textures will not work correctly with GLideN64.

**Comment by theboy181** [comment]
I grab this pack from emulation64. Is there somewhere else?

**Comment by Nes-player4Life** [comment]
What Aspect as supported?
4X4 8X8 16X16?
Must the files be equal in size?

**Comment by gonetz** [comment]
HD texture size must be power of two of the original texture size. Koolsmoky wrote detailed instruction how to make good working texture pack.

I don't know about good texture pack for SSB.

**Comment by theboy181** [comment]
Andros wont have his way with me!
:) 

Will you be supporting the same method used in Glide64? this pack seems to work with these type of formats used in SSB HD texture pack.

**Comment by Nes-player4Life** [comment]
I'm all for correctly sized files but without odd formats most of the packs will become unusable.
sure it's the pack designers fault but there are some otherwise professional packs that will become unpleasant to play.

**Comment by gonetz** [comment]
I will not add any special code to fix errors in texture packs.
Koolsmoky wrote special test, which checks that texture pack corresponds to all specifications and requirements. Well made packs (that is the ones, which pass Koolsmoky's test) must works correct.

**Comment by theboy181** [comment]
The issue is that the textures that are mirrored or flipped are not working. I think this is not correct? (please issue links to Koolsmoky) some textures are treated like a checkerboard, and this is not working.  

This will require that all textures that do this to be re-made and this will lead to extremely large textures taking up memory.  I have started to fix textures for SSB but I'm finding that new method might actually not work. Lets say that a texture for an eye is flipped and that the texture is called to wink. With this method you wouldn't be able to have the 1 eye wink.

Unless I'm missing something??  Please provide more details on how your HD textures will work. I think once you implement dumping I might be able to see what is going on.

**Comment by Predator82Germany** [comment]
Where is Koolsmoky´s test avaiable?

**Comment by gonetz** [comment]
GLideN64 is powered by the same GlideHQ texture module as Glide64, so you may use Glide64 for texture dumping. HD texture must be power of two of the original texture. If original texture is not mirrored or flipped, HD texture also must not be mirrored or flipped.

Koolsmoky´s test is named test_hq.exe and was posted somewhere on emutalk.
I can't find it among my files. Building it from sources is is tricky and I don't have necessary libs.
You better ask texture artists about it .

**Comment by theboy181** [comment]
After updating more textures I have found that it is impossible to texture correctly with these changes. some textures that are used in more than one location can not be made to fit both places without alignment issues.

Example is the brick texture used in SSB levels. if you correctly make the texture fit one wall it will stretch incorrectly on the next.

**Comment by gonetz** [comment]
Let's do a simple test:
1. Put in the texture pack original brick texture dumped by RiceVideo or Glide64. You may put a mark on it to be sure that the plugin uses texture from the texture pack, not from the ROM. Does this texture work correctly in all places?
2. If test 1 passes, make 2X texture from the original one - just stretch its width and height two times in any graphics editor. Put it in the pack and check how it works. If it works, check 4X variant.

If both tests pass, the problem is with your new brick texture.

**Comment by theboy181** [comment]
Ill back down.. you are correct the textures I have are not the proper sizes.

**Comment by theboy181** [comment]
Couldn't stay aware from this issue..

I'm using Glide64 for PJ to dump textures from the Peach Castle Stage.
for some reason one of the textures that was dumped came out in a resolution of 48x64
![smash brothers bf36c198 2 0 1703b991_cibyrgba](https://cloud.githubusercontent.com/assets/9299743/6407324/77202d2c-bdf2-11e4-95ef-aa181fd14df0.png)
When take this texture and apply it in Glide64 (without any changes) the texture doesn't properly wrap to the moving bridge. If resize the texture to 64x64 and add the missing bricks to the image it works as it should.

However, when I use this texture (48x64) in GLideN64 it doesn't work either. If I resize it to 64x64 where is works in Glide64 I get this strange occurrence.
![capture](https://cloud.githubusercontent.com/assets/9299743/6407350/11e5ae04-bdf3-11e4-8d64-a3c8a0f9e609.PNG)

Something isn't right, and I am unsure if its GLideN64 or something I'm not doing right?

**Comment by theboy181** [comment]
Trying to work with the tree texture int he above pictures, and I can change if in Glide64, but it will not display any changes in GLideN64 it also dumped from PJ with as 48x32

**Comment by gonetz** [comment]
Why closed? Did you sort it out?

**Comment by theboy181** [comment]
Nope. Must have clicked wrong button. Can you look into this?   I just can't seem to find any information on how to texture properly

**Comment by theboy181** [comment]
![capture](https://cloud.githubusercontent.com/assets/9299743/18419428/48f91084-780f-11e6-8fc5-55e41dff61ba.PNG)

**Comment by gonetz** [comment]
![1364983801_uporotyy-lis-v-peterburge-2](https://cloud.githubusercontent.com/assets/8983092/18704811/b6cb690a-8015-11e6-9c16-2bbc5ff165e9.jpg)

**Comment by gonetz** [comment]
btw, is the problem still actual?

**Comment by theboy181** [comment]
Needs testing

**Comment by gonetz** [comment]
@theboy181 I fixed several issues with HD textures recently. Please re-test with my latest master build.

**Comment by theboy181** [comment]
I will test this Sunday.

**Comment by theboy181** [comment]
@gonetz What do you consider your master build? 
Link?

**Comment by gonetz** [comment]
Latest link in #1364
https://drive.google.com/file/d/0B0YqMPjGo3B2Y3R2ZEJxZXZsTHc/view?usp=sharing

**Comment by theboy181** [comment]
Can you please make it so the hotkeys only work when you have the window active? Im going to fix the bad textures in MK64 and I will let you know what issues arise. 
![image](https://cloud.githubusercontent.com/assets/9299743/24843451/d4d4044a-1d57-11e7-9fa5-5b1c64da76d4.png)

**Comment by theboy181** [comment]
![image](https://cloud.githubusercontent.com/assets/9299743/24848238/b2ec405e-1d7a-11e7-8cf2-234045a77e19.png)

**Comment by theboy181** [comment]
![image](https://cloud.githubusercontent.com/assets/9299743/24870464/386e044c-1dcb-11e7-8777-a9def5eeca96.png)

**Comment by theboy181** [comment]
@gonetz 
![image](https://cloud.githubusercontent.com/assets/9299743/24987852/fc2d2416-1fb6-11e7-893f-4479bacadd4f.png)

The texture Dumps for the OK at the bottom right hand corner are acting weird. Is it normal for GLideN64 to dump textures with garbage pixels? Im having to manipulate quite a bit for the texture packs I am creating.

**Comment by gonetz** [comment]
GLideN64 follows Rice video algorithms for dumping and loading textures. All cases of discrepancy with Rice should be investigated. Unfortunately   I don't have enough time for that. It would be great if someone else look at it.

**Comment by theboy181** [comment]
@gonetz I hope you will tune a few things with HD textures.

For example, I have been re-texturing MK64 Menus to HD, and its going well except, textures like the green arrow L OPTION R DATA keep gettign new CRC's.

This means that I have to copy and make several identical versions of the same texture. This (bug?) can be reproduced by updating a texture then, going into the game and quiting back to the menu. 

Depending on how you enter the menu (how you get there) will create new CRC's. Im sure that the ROM only as one texture, so this must be some error that the plugin is doing. 

Would there be any performance benefits in eliminating new CRC creations? I know this would reduce the time it takes to make HD textures.

![image](https://cloud.githubusercontent.com/assets/9299743/25054497/52a3440e-2112-11e7-84c0-b40a4585e2ad.png)
Multiple files of the same texture shown above.

**Comment by theboy181** [comment]
Current Progress 
https://youtu.be/vHrSMrOZV4E?t=25

**Comment by gonetz** [comment]
I guess there is a bug in texture size calculations. Plugin takes more data than necessary, and random garbage around useful data causes wrong checksum. It need to be investigated, but I don't know when I will be able to look at it.

**Comment by theboy181** [comment]
@gonetz Thanks for letting me know. I will take a break from working on this any further. I would hate to waste time if there will be improvements down the road.

I think this feature (polished) will bring some good attention to GLideN64.

**Comment by theboy181** [comment]
@gonetz have you had time to log into the old GLideN64 forums?

**Comment by gonetz** [comment]
@theboy181 I made several fixes in hires textures support. Please test and report the current state of this issue.

**Comment by DonelBueno** [comment]
@gonetz Latest master posted on WIP 3 and the build posted on issue #1662, same results with both (altough other texture packs were improved by that build, like Super Smash Bros.)

![project64 2017-11-16 13-13-47-05](https://user-images.githubusercontent.com/4239694/32900068-bb8171ec-cad3-11e7-9923-2ef4c5594559.png)
![project64 2017-11-16 13-14-00-01](https://user-images.githubusercontent.com/4239694/32900078-bf8d33ca-cad3-11e7-8cd3-79b93f927ced.png)
![project64 2017-11-16 13-14-10-01](https://user-images.githubusercontent.com/4239694/32900106-d0eccf36-cad3-11e7-8949-557b58ece4e6.png)
![project64 2017-11-16 13-14-12-00](https://user-images.githubusercontent.com/4239694/32900114-d6f72764-cad3-11e7-8c4d-803aa74b1d29.png)

Namely the menu fonts are not being loaded. The ones that are being loaded (like OPTION and DATA) contain the whole word on a single file, the ones that are not being loaded have individual files for each letter.

**Comment by theboy181** [comment]
If the new fixes lock the crc to just one per texture (and I hope they do), you will need to find out what the textures output name is and change that textures name acordningly. 

I will test this weekend, and hopefully gonetz will provide the fixes if any are needed.

**Comment by DonelBueno** [comment]
@theboy181 I'm using the highlighted one, should I use the other one?

![sem titulo](https://user-images.githubusercontent.com/4239694/32905354-dae082fa-cae0-11e7-8a41-795c81e9e252.png)

**Comment by theboy181** [comment]
I’m not sure about his pack. I have created my own pack and that’s when I noticed that Gliden64 spit out new CRC when you navigate the menu. I’ll upload my pack it gonetz fixes the issue.

**Comment by DonelBueno** [comment]
Oh, I thought you were using the same pack, my bad.

Great to know you're goingo to upload it =)

And what about .dat texture packs? Do you know how to use them with this plugin?

**Comment by gonetz** [comment]
.dat texture packs are incompatible with GLideN64. There are decoders from .dat back to rice format, but this converting is not lossless. Use only packs in rice format for testing  (that is each texture is a separate .png file), or .htc files from safe sources.

**Comment by DonelBueno** [comment]
Ah, too bad.

Do you intend to implement .dat support someday?

**Comment by gonetz** [comment]
Why? You always may create native GLideN64 cache file from original texture pack. Using .dat or .htc as DRM protection is a bad idea,  these formats are not disigned for that.
