### ISSUE TITLE
Make GLideNUI builds for mupen64plus on AppVeyor

### ISSUE THREAD

**Issue by anonymous7002** [gonetz/GLideN64#2540]
Currently, mupen64plus builds are CLI only, and the settings dialog won't work on most frontends.

**Comment by gonetz** [comment]
@Rosalie241 could you take this task?

**Comment by Rosalie241** [comment]
Sure, but first I'll migrate GLideN64 to github actions in a little while.

**Comment by gonetz** [comment]
> Sure, but first I'll migrate GLideN64 to github actions in a little while.

Then #2530 should be fixed as well.

**Comment by Rosalie241** [comment]
Yes, however if I add github actions *now*, it'll zip the already-made zips, see https://github.com/actions/upload-artifact/issues/39 and I'm unsure if that's a major problem for you (or users), if you're fine with that issue, then I'll switch to github actions and open a PR

**Comment by gonetz** [comment]
Double-zipping is a problem. We don't need a double-zipping :)
