### ISSUE TITLE
I get a blackscreen when I enable msaa

### ISSUE THREAD

**Issue by Toadfield** [gonetz/GLideN64#2551]
I installed the newest project 64 version and those plugins:
![image](https://user-images.githubusercontent.com/68649672/128933668-5a9af19f-7943-4322-bda2-00a7e7defbd9.png)
When I enable msaa and start any game,then I get a blackscreen (but I can still hear audio).
When I disable msaa then it works (but I don't want to play without msaa).

OS: WIndow 10 Home,newest version
GPU: Radeon Sapphire Rx580
CPU: Ryzen 5 3600
Mainboard: AsRock x370 Pro4 (I already installed the chipset driver)

**Comment by Rosalie241** [comment]
Public Release 4 is from 2019, please use the latest 'developer' build from here and test it again: https://ci.appveyor.com/project/gonetz/gliden64/branch/master/artifacts

**Comment by gonetz** [comment]
@Toadfield Public Release 4 supports msaa. I think the problem is in msaa setting.
PR4 does not test if GPU actually supports max msaa level.
I tested GLideN64 with Rx580. msaa 16x indeed causes a blackscreen.
msaa 8x works fine. Please set msaa to 8x.
