### ISSUE TITLE
Beetle  Adventure Racing. Fog is broken.

### ISSUE THREAD

**Issue by gonetz** [gonetz/GLideN64#2556]
Regression. Broken in acfb569dea commit. @standard-two-simplex please check.

**Comment by standard-two-simplex** [comment]
This [PR](https://github.com/gonetz/GLideN64/pull/2557) seems to fix, but halves the max resolution supported.

I do not understand why one implementation is working and the other isn't, so I haven't been able to find a better solution. Vertex X and Y end up being the same, so I fail to see why one is fogged and the other isn't.

**Comment by gonetz** [comment]
Need to check the fog shader: ShadowMapFragmentShader 
May be it needs corrections.

**Comment by standard-two-simplex** [comment]
A special shader is used to perform fog effects? Doesn't the N64 do fog effects as part of the blending stage?

**Comment by gonetz** [comment]
BAR fog is special. It works as post-processing and uses depth buffer as the texture source.

**Comment by standard-two-simplex** [comment]
Ah, I see.

**Comment by standard-two-simplex** [comment]
I found out why this is failing. As you said, the gray rectangles use a special shader. The special vertex shader doesnt apply the changes in VertexShaderEnd() as it uses the special VertexShaderRectNoColor(), but the texture rectangle call updates the viewport as if it did. Thus, the texture rectangle is misplaced.

**Comment by gonetz** [comment]
Thanks!
I'll think how to fix it.
