### ISSUE TITLE
Topgear hyper bike: gl error line 55: regression

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#256]
it cannot even arrive at title screen :(

**Comment by Predator82Germany** [comment]
Only get this:

https://cloud.githubusercontent.com/assets/6679921/6710310/fcb8d9d8-cd7f-11e4-89ea-7ffeec9f3643.png

**Comment by Predator82Germany** [comment]
Fixed with Mar19

**Comment by gonetz** [comment]
No, it's not fixed yet

**Comment by Predator82Germany** [comment]
But I get no message

**Comment by gonetz** [comment]
That's strange. I see the message and I know what causes it.

**Comment by Predator82Germany** [comment]
I´ve used PAL-rom

**Comment by gonetz** [comment]
You're right: PAL rom works without that error.

**Comment by gonetz** [comment]
Fixed GL error.

**Comment by olivieryuyu** [comment]
fixed
