### ISSUE TITLE
Hotkeys not working with mupen64plus CUI

### ISSUE THREAD

**Issue by GhostlyDark** [gonetz/GLideN64#2560]
Before 44dc7e2f0a2070e6e, it was possible to dump textures by pressing "d" and reloading textures by pressing "r". With the introduction of configurable hotkeys, it looks like hotkeys can't be used with command line mupen64plus, thus making it impossible to use those features.

I tried entering various values into `mupen64plus.cfg`, but nothing seemed to work. Hotkeys from the `GLideN64.custom.ini` aren't used either.

**Comment by gonetz** [comment]
It was broken in c36ffa97f7
Fixed in 153caeec
Note: Use capital letters for hotkeys. For example, D for texture dump, R for texture reloading.
