### ISSUE TITLE
Paper Mario Snow

### ISSUE THREAD

**Issue by Rosalie241** [gonetz/GLideN64#2570]
in Paper Mario, snow seems to break when the `Enable N64-style mip-mapping` checkbox is enabled.

`Enable N64-style mip-mapping` enabled:
![image](https://user-images.githubusercontent.com/18737914/132701223-f9e2eca3-0094-4bfb-8e58-376dfa53e13b.png)

 `Enable N64-style mip-mapping` disabled:
![image](https://user-images.githubusercontent.com/18737914/132701311-d308a0bf-7092-436c-846f-4110ad6a71fb.png)

Save State:
[Paper_Mario_U.pj.zip](https://github.com/gonetz/GLideN64/files/7137188/Paper_Mario_U.pj.zip)

**Comment by gonetz** [comment]
The snow is wrong with and without N64-style mip-mapping, check AL RDP for a correct picture.
Snowflake texture has 3 tiles with sizes 128x128, 128x128, 16x16
It is impossible to emulate correctly with old GL mipmaps based  emulation method.
The new texture atlas based method can handle that case.
Unfortunately, it is that rare case, where texture parameters for mip-map tiles differ: tex shift for the last tile is different.
It makes texture coordinate wrong, so we have four snow balls instead of one.
It probably is fixed in experimental mip-map refactoring started by @standard-two-simplex, because that refactoring addresses such issues.

**Comment by standard-two-simplex** [comment]
> It probably is fixed in experimental mip-map refactoring started by @standard-two-simplex, because that refactoring addresses such issues.

Yes, it works on the experimental branch.

It should be possible to add a temporary fix.
https://github.com/gonetz/GLideN64/blob/9ebb11f37b1090090e5fb110a6b7b18b7cb82f7f/src/Textures.cpp#L1414
Unless I missed something, `tmptex.height` in the packed data is used only to compute this ratio. It should be possible to pack `tmptex.mipMapRatio =   tile_0_shift - current_tile_shift` instead and compute `lod_scale = vec2(pow2(mipMapRatio))`. Note that a bit of care should be taken with the sign.

**Comment by standard-two-simplex** [comment]
> It should be possible to add a temporary fix.

@gonetz I managed to write a working example. Feel free to adapt it if you wish to clean it up.

https://github.com/standard-two-simplex/GLideN64/tree/mip_map_shift

**Comment by gonetz** [comment]
Oh, I  already wrote a solution: fix_mipmap_scale
I came to the same idea with texture scale, but it did not work yesterday because of a mistake. Now it works.
I'll check your solution too.

**Comment by standard-two-simplex** [comment]
> Oh, I already wrote a solution: fix_mipmap_scale

Yeah looks good. It's probably better like this, the scale is calculated only once per tile.

**Comment by gonetz** [comment]
> Yeah looks good. It's probably better like this, the scale is calculated only once per tile.

Your code also calculates the scale once per tile, is not it?

**Comment by standard-two-simplex** [comment]
It computes the exponent once, but then has to computer its power of two once per pixel. Also, there are some extra per pixel calculations because I packed it all in one byte.

**Comment by gonetz** [comment]
I guess we again need help from @fzurita 
Francisco, could you test these two branches

https://github.com/gonetz/GLideN64/tree/fix_mipmap_scale
and
https://github.com/gonetz/GLideN64/tree/mip_map_shift

on mobile devices, which can handle accurate texture mapping?
Is there any difference in performance between them?
fix_mipmap_scale uses one additional texel fetch in compare with master.
mip_map_shift uses several additional shader calculations, including two `pow`.

**Comment by fzurita** [comment]
Yep, I'll try to test sometime today.

**Comment by fzurita** [comment]
I'm not seeing much of a difference at all:
```
master
golden eye: 108
perfect dark: 92

fix_mipmap_scale
golden eye: 106
perfect dark: 92


mip_map_shift
golden eye: 107
perfect dark: 92
```

**Comment by gonetz** [comment]
> If anything, mip_map_shift is very slightly faster.

It a bit surprising for me. It is good that both fixes work nearly as fast as current master.
Thanks!

**Comment by gonetz** [comment]
mip_map_shift branch is merged to master. @standard-two-simplex, thanks!
 The bug is fixed. @Rosalie241 thanks for the bug report!

**Comment by gonetz** [comment]
@standard-two-simplex could you add a GLES2 version for your fix?

**Comment by standard-two-simplex** [comment]
Done 6103842468c6439452bdf2769c3460ce91091c8f

@fzurita Please, check for errors with a GLES2 device.

**Comment by gonetz** [comment]
> Done [6103842](https://github.com/gonetz/GLideN64/commit/6103842468c6439452bdf2769c3460ce91091c8f)

Thanks!
