### ISSUE TITLE
Mario Golf: Animated effects render in front of course

### ISSUE THREAD

**Issue by Nejsplitter** [gonetz/GLideN64#2577]
This issue is back again: #312

tested on mupen ae latest, project 64 latest and mupen64plus latest

issue does not exist on mupen64plus latest, 

something interesting , it seems enabling n64 depth compare solves the original issue but enabling it creates a new issue where the player model and water and other things are rendered/unrendered as you move the camera, its like the same problem just switches to affect other assets while fixing the original

**Comment by Nejsplitter** [comment]
hmm something interesting just now, it seems enabling n64 depth compare solves the original issue but enabling it creates a new issue where the player model and water and other things are rendered/unrendered as you move the camera, its like the same problem just switches to affect other assets while fixing the original

**Comment by Nejsplitter** [comment]
This issue is back again: #312

tested on mupen ae latest, project 64 latest and mupen64plus latest

issue does not exist on mupen64plus latest, something interesting , it seems enabling n64 depth compare solves the original issue but enabling it creates a new issue where the player model and water and other things are rendered/unrendered as you move the camera, its like the same problem just switches to affect other assets while fixing the original

**Comment by Nejsplitter** [comment]
@fzurita does the issue also happen on your phone with the latest mupen ae and most accurate Gliden64 settings ? if you go to training mode and keep pressing right and select hole 4, its most visible there the rendering issue (the water)

**Comment by Nejsplitter** [comment]
@fzurita does the issue also happen on your phone with the latest mupen ae, latest Gliden64 and most accurate Gliden64 settings ? if you go to training mode and keep pressing right and select hole 4, its most visible there the rendering issue (the water)

**Comment by fzurita** [comment]
I'll try it soon, I've been busy with other things.

**Comment by fzurita** [comment]
Yeah, I definitely see the issue. Polygons are rendering on front of pre-rendered backgrounds. If you move the camera around, the course is no longer pre-rendered, so depth works correctly.

Not sure what broke it...

**Comment by Nejsplitter** [comment]
Hopefully since it was fixed before, it will be easy enough to understand whats happening, maybe gonetz could take a look if he has some free time.

**Comment by gonetz** [comment]
Bisected to a405ad8659 and 4834359ec1a
a405ad8659 - the game does not work because of error with shader compilation.
4834359ec1 - the game works, but with the regression

**Comment by Nejsplitter** [comment]
interesting, i wonder if there are other regressions in other games that nobody has noticed that will also be fixed also by this

**Comment by gonetz** [comment]
Hardly. It is quite specific case.

**Comment by Nejsplitter** [comment]
Thanks gonetz ! :)

**Comment by gonetz** [comment]
It's not the only regression with Mario Golf.
Currently background image shifted by a pixel when camera stops moving. It causes some distortions in the image.
I'm trying to find, when that issue was introduced.
