### ISSUE TITLE
Unused textures in HTS packs potentially not cleared from memory

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#2579]
I'm getting complaints from a user about this specific texture pack in Android: https://drive.google.com/file/d/1nTLPa2Pyg1mX88xwEK754dBz1_hGDq1a/view

Apparently, this texture pack for Majora's mask is 18GB, there is no Android device or many PCs out there with that much memory.

Eventually, after playing for long enough, the app crashes, and I'm guessing that it's because of memory limitations.

I know I could look this up myself before making the issue, but this acts more like a reminder for me. Are textures from HTS files being removed from memory after they are no longer present in the cache? If they are not, that would likely lead to a crash once memory runs out.

**Comment by Rosalie241** [comment]
HTS doesn't really keep textures in RAM (at most there will be 1 texture stored in memory at the same time, see https://github.com/gonetz/GLideN64/blob/master/src/GLideNHQ/TxCache.cpp#L657), the issue you're most likely seeing is from the insanely high limit in `Textures.cpp` (where it loads textures in VRAM, the default limit is 8000 textures, see https://github.com/gonetz/GLideN64/blob/master/src/Textures.h#L109).

You could try https://github.com/gonetz/GLideN64/pull/2572 & https://github.com/Rosalie241/GLideN64/commit/fa40af37646bee0d99b4a8443864c84c38afdabd (or just use https://github.com/Rosalie241/GLideN64/tree/textures-memory which has both commits) and tell users try to set the limit to 500-1000 or so.

**Comment by fzurita** [comment]
Interesting, yeah, I could see how VRAM limitations can cause the issue as well.

**Comment by gonetz** [comment]
> insanely high limit
> the default limit is 8000 textures

8000 textures had not looked insane number until Nerrel's texture pack appeared. His textures are huge.
Since there are no safe way to detect texture memory size with OpenGL, proper video memory management is problematic (impossible?).

**Comment by Rosalie241** [comment]
> Since there are no safe way to detect texture memory size with OpenGL, proper video memory management is problematic (impossible?).

Maybe I can revise my #2572 PR to track MB's instead,
i.e instead of knowing the exact usage, just track the upload data sizes of textures which we can get using `TxUtil::sizeoftx` and allow users to change that.

It wouldn't be perfect but at least it'd allow people to set *some* limit on how many texture data is stored in VRAM, even though it wouldn't be exact, it'd be better than no option at all imo.

**Comment by gonetz** [comment]
> t'd be better than no option at all imo.

I agree, new option is less evil than crash. If we knew at least total VRAM size, we could use texture memory = VRAM/2 heuristic.

**Comment by gonetz** [comment]
BTW, I just found that @Nerrel finally released his Zelda MM texture pack.
Nerrel, congratulations, incredible work!
It is pity though that the current version of the plugin is not recommended for the pack.

**Comment by Rosalie241** [comment]
> It is pity though that the current version of the plugin is not recommended for the pack.

If you want, I can open a PR to restore the old behavior with an option which'll be disabled by default (something called `Legacy texture mapping behavior`), then Nerrel can recommend upstream GLideN64 again.

**Comment by gonetz** [comment]
May be later. I want the current texture mapping be polished first. Probably, the legacy behavior can be simulated with an uniform option in shaders.

**Comment by gonetz** [comment]
@fzurita I finally checked the PR from Rosalie241 (yep, I'm slow nowadays).
Could you check this branch with Nerrel's pack:
https://github.com/gonetz/GLideN64/tree/Rosalie241-txMaximumAmountInVram
?
I tested it locally with 1GB limit for hires textures. This limit is enough for one-two locations. Then it becomes exceeded, and the cache updates (removes some older textures) in every new location. It should not crash though.

**Comment by fzurita** [comment]
Yep, I'm on it. I'm also having a user that was experiencing crashes with it test it as well.

**Comment by fzurita** [comment]
This appears to be a success, the user that had the crashes no longer has them anymore. So in my opinion, it works great!

**Comment by gonetz** [comment]
Good to know, thanks! The fix committed to master.
