### ISSUE TITLE
very minor issue with reshade (or anything) compatibility, and odd findings with rogue squadron

### ISSUE THREAD

**Issue by CadetSparklez** [gonetz/GLideN64#2581]
I noticed in games that run at 30 fps, that your pc will still interpret the frame rate as the number of vi/s (60). So for example if I limited the frame rate with rivatuner instead of using the built in video speed sync, I'd have to set it to 60 instead of 30 to run at 100% speed.

Now this is a problem for reshade or any post processing because it means it has to do twice the necessary work to reach a render target of 60 fps instead of 30 (made up example for clarity: a preset I could use in a modern game could reach 30 fps, while in dk64 only 40 fps, effectively 20)

Since most games run at 30 fps (over even 60 on 1964 gepd), it would be easy enough (well easier) to make some sort of hack that only sends every second "frame" to the output.

Some exceptions to this are some weird cases like rogue squadron that act differently in different emulators. In 1964 it will always have a vi/s of 90 and will be 30 fps with vertical interrupt and 60 fps with vi origin change or colour buffer swap.

In mupen (well m64p to be exact, not sure if it changes) however, its 60/60 with both vertical interrupt and vi origin change, and 120/120 with colour buffer swap. 
Unless you are in the demo cutscenes where its 60/60 with 0 and 1, and either 60/60 or 40/60 on 2 (similar to the 60/90 in 1964?). The read fps with always be 60/60 on 0 and 1 as expected, but while using 2 its half of the framerate (20 if 40/60 or 30 if 30/60), aka it reads the real framerate even though the emulator doesn't, which is inverse to the behavior of every other game I've tested.

**Comment by Squall-Leonhart** [comment]
lmao

someone close this.

**Comment by gonetz** [comment]
NTSC games have 60 VI/S, PAL games have 50 VI/S. It is how TV standard works.
90 VI/S is a bug, but emu core bug. It can't be fixed on graphics plugin side.

VI/S is not FPS, it is number of tv display refresh per second (vertical interrupt per second). Frame has not necessary change with each VI. If you want to reduce reshade work, you may change "Frame buffer swap on" setting from default "Vertical interrupt (VI)" to "Color buffer change". In that case reshade will not do the same work twice.

**Comment by CadetSparklez** [comment]
oh wait your right in mupen colour buffer change ties to it, whenever I used it in 1964 gepd it would shoot up to 120/120 instead of lowering to 60/60, guess the 60 fps hack caused feedback and screwed with it

thanks again

**Comment by CadetSparklez** [comment]
looks like this was fixed at some point for gepd. Thank you so so much I now have double the amount of time for my post processing to render
