### ISSUE TITLE
Mario Kart 64 - More lines in menu & character selection screen.

### ISSUE THREAD

**Issue by KenanUchiha28** [gonetz/GLideN64#2587]
![Mario Kart 64 (U)-211003-095549](https://user-images.githubusercontent.com/91834977/135756892-8d821ac8-a4dc-44d3-be4d-8ede740e6df5.png)
![Mario Kart 64 (U)-211003-095557](https://user-images.githubusercontent.com/91834977/135756896-84c91a54-74e9-4d65-8bc3-a536be64aa64.png)
![Mario Kart 64 (U)-211003-095605](https://user-images.githubusercontent.com/91834977/135756899-a6c16e6c-15d7-4425-8892-4c5ecd52152d.png)
I'm using MupenPlusNext on Retroarch. Is there a fix to get rid of these lines on Mario Kart 64 menu & character selection screen?

**Comment by GhostlyDark** [comment]
Toggle the `useTexCoordBounds` setting, aka `Enable native-res bounds for texture coordinates`.

**Comment by gonetz** [comment]
> Toggle the `useTexCoordBounds` setting, aka `Enable native-res bounds for texture coordinates`.

You may also play in native resolution (UseNativeResolutionFactor = 1).
If you need hi-res use, toggle useTexCoordBounds` setting.
