### ISSUE TITLE
Kirby 64 broken hud

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#2594]
The second Kirby swallows an enemy, the HUD gets messed up. It looks like this broke recently:

![Screenshot_20211008-235514_M64Plus FZ Pro](https://user-images.githubusercontent.com/11581687/136643389-faebff4a-b3ee-42c5-9ce3-f60183965643.jpg)

**Comment by Squall-Leonhart** [comment]
thats jabo graphics, use gliden64.

**Comment by fzurita** [comment]
@standard-two-simplex @gonetz Broken by https://github.com/gonetz/GLideN64/commit/7e8265bf20e768c40b62d102ecd800e1e347e129

**Comment by fzurita** [comment]
It seems fixed, the only problem I have with Kirby64 now is a flickering border when loading save states, but it may be unrelated.

**Comment by gonetz** [comment]
Border is not rendered each frame. It rendered once, and then only content inside the border is updated. So, if you load from a save state, you loose the border.
