### ISSUE TITLE
Extreme-G 2 XG 2 (U) - Incorrect Loading Screen

### ISSUE THREAD

**Issue by RubenDanielMontemayor** [gonetz/GLideN64#2601]
**Preface**
Emulator: Project 64 3.0.1.5664-2df3434
Video/Graphics Plugin: GLideN64 rev.c36ffa9 (Came with Project 64, Using HLE)
Audio/Sound Plugin: Project64 audio plugin: 3.0.1.5664-2df3434 (Came with Project 64, Using LLE)
Input/Controller Plugin: N-Rage For Project64: 3.0.1.5664-2df3434 (Came with Project 64)
RSP Plugin: RSP plugin 3.0.1.5664-2df3434 (Came with Project 64)

![image](https://user-images.githubusercontent.com/89608049/141594574-1e1f5b30-dc86-4689-b3cb-be8e9ef3046d.png)

Hardware Info:
![image](https://user-images.githubusercontent.com/89608049/141594773-e1d0f427-e6f3-4549-8cf7-a1b23fe47d95.png)
Graphics Card: Nvidia GeForce 940MX
All hardware drivers up to date when checked in device manager.

Ok, now to get to the nitty gritty stuff, seems like whenever I use "In software (fast, fewest, game issues)" for the "Copy video card depth buffer to N64 memory:" configuration, it leads to a nasty gray screen during the loading of a race track. Text looks fine (such as showing the name of the race track). Here is a picture showing you what I mean:
![image](https://user-images.githubusercontent.com/89608049/141595059-91aac8f4-c7c4-4485-831d-9c96a35733ef.png)
![image](https://user-images.githubusercontent.com/89608049/141595086-896a929e-bae0-40a4-a27a-295fea17bfba.png)

As far as I can tell, this is what it is supposed to look like (whenever I choose any of the other available options besides "software"):
![image](https://user-images.githubusercontent.com/89608049/141595132-4fa66606-d295-49f5-988c-61c18793524a.png)

Admittedly, I'm not the best at navigating emulators/plugins and their configurations, so I honestly don't know if there is something else causing this issue. I did notice that the "software" option said it would cause the least problems, so I was genuinely confused whenever the less accurate versions ("never" & "from VRAM") showed the correct picture. Perhaps I misunderstood what the option meant, and I accidentally chose some wrong configurations. Please do let me know if you don't think this is a bug, or of you need any other info to find the cause of this bug, thank you!

**Comment by gonetz** [comment]
Yes, it is a bug, thanks for the report!

Frame and depth buffer emulation is a complex task and it often leads to bad side effects like this one.
Debugging of such bugs is also very difficult. As a temporal solution I disabled depth buffer copy for this game in custom ini: 8cc09e456e
