### ISSUE TITLE
Wrong colors and missing textures turok dinosaur hunter.

### ISSUE THREAD

**Issue by 71knight** [gonetz/GLideN64#2603]
When less accurate blending mode is enabled I get no fog.  When I disable it I get fog but the colors are messed up on the intro screen.  Plus in game the crystal shards bonus point pickups are missing their shiny texture.  Haven't really checked whether the sun flare lens effect is working or not.  I am using Android 10.0.16 with gles3 on Adreno 640 gpu.  I am using mupen64plus-next gles3 with parallel rsp with pure interpreter CPU core and gliden64 rdp latest version from retroarch updater.  Plus extreme g has blocky clouds? in front of the extreme g logo at the title screen.  Any solutions?

**Comment by fzurita** [comment]
Wrong colors usually means that you need to reset you shader cache. Do you get the same problem with M64Plus FZ?

**Comment by 71knight** [comment]
> Wrong colors usually means that you need to reset you shader cache. Do you get the same problem with M64Plus FZ?

I am using m64plus fz.  Great emulator by the way!  Do you know where Android 10 has the shader cache?  I have a rooted phone and can find the files if I knew.  I would like to know location because I have other programs that have shader cache.  I am aware that m64plus fz has delete shader cache, but that is not what I'm looking for.

**Comment by fzurita** [comment]
Yeah, the files are located here in m64plus FZ:
/data/data/org.mupen64plusae.v3.fzurita/files/CoreConfig/UserCache/mupen64plus/shaders

The clear shader cache option deletes the contents of that folder.

Given that m64plus FZ doesn't have that problem, it means that it's an issue with retroarch. I would close this issue and create one in their repo.

**Comment by gonetz** [comment]
> Given that m64plus FZ doesn't have that problem, it means that it's an issue with retroarch. I would close this issue and create one in their repo.

Closed
