### ISSUE TITLE
Mario tennis broken shadows in accurate path

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#2621]
Shadows are currently broken in the accurate shader path:

![Mario Tennis (U)  !  (1)](https://user-images.githubusercontent.com/11581687/145828548-a41d6d6d-15b8-4f4e-be3a-148ee5fc967b.png)

Shadows look fine in the fast path:
![Mario Tennis (U)  !](https://user-images.githubusercontent.com/11581687/145828595-10f4b5ae-d571-47ed-bab5-51a86676a85b.png)

**Comment by fzurita** [comment]
@standard-two-simplex

**Comment by gonetz** [comment]
Bad commit 47aaf2fc99ff9
