### ISSUE TITLE
Majora's Mask misplaced blur

### ISSUE THREAD

**Issue by GhostlyDark** [gonetz/GLideN64#2625]
Makes your eyes hurt. Introduced by e0d5b0be7bad01c1bd24feb650f1ab8311544a72.
![image](https://user-images.githubusercontent.com/31742919/146620669-fd59c113-8499-4aa4-9411-79bad0e920a0.png)

**Comment by gonetz** [comment]
@standard-two-simplex please remind me, what e0d5b0b was for?

**Comment by standard-two-simplex** [comment]
I think everything S2DEX related started with Starcraft being blurry and having an extra line at the bottom, in one piece backgrounds mode.
The starcraft issue was a consequence of using screen coordinates.
