### ISSUE TITLE
In iQue Paper Mario 64, characters become black in dark rooms

### ISSUE THREAD

**Issue by Darth-Koopa** [gonetz/GLideN64#2626]
With this patch, iQue Paper Mario is playable:
https://t.co/2nvRqCs9na
![image](https://user-images.githubusercontent.com/45894930/147038461-78b6b377-975f-4ca3-9616-db3e02545d6b.png)
but characters become black in dark areas like dry dry ruins
can anyone fix this issue?

**Comment by GhostlyDark** [comment]
The patch didn't bother to put in the internal ROM name, which is needed by GLideN64 to determine what per-game hacks to use. Try this updated BPS patch:

[Zhi Pian Mario (China) (iQue).zip](https://github.com/gonetz/GLideN64/files/7765349/Zhi.Pian.Mario.China.iQue.zip)

**Comment by Darth-Koopa** [comment]
> The patch doesn't contain an internal ROM title, which is needed by GLideN64 to determine what per-game hacks to use. Try this updated BPS patch:
> 
> [Zhi Pian Mario (China) (iQue).zip](https://github.com/gonetz/GLideN64/files/7765349/Zhi.Pian.Mario.China.iQue.zip)

![image](https://user-images.githubusercontent.com/45894930/147158408-36f96437-8c39-4895-b8ca-dcd6f79437b5.png)
When I start the game with a new save file, mario just appears here with 0 HP,FP, and BP. Can you resolve the issue?

**Comment by GhostlyDark** [comment]
> ![image](https://user-images.githubusercontent.com/45894930/147158408-36f96437-8c39-4895-b8ca-dcd6f79437b5.png) When I start the game with a new save file, mario just appears here with 0 HP,FP, and BP. Can you resolve the issue?

This has nothing to do with GLideN64. You should get in touch with whoever made that patch to fix such issues.

**Comment by Darth-Koopa** [comment]
> > ![image](https://user-images.githubusercontent.com/45894930/147158408-36f96437-8c39-4895-b8ca-dcd6f79437b5.png) When I start the game with a new save file, mario just appears here with 0 HP,FP, and BP. Can you resolve the issue?
> 
> This has nothing to do with GLideN64. You should get in touch with whoever made that patch to fix such issues.

That person also made a patch allowing iQue Yoshi's Story playable in emulators
https://t.co/OXLy8mQIsk
But it also have graphical issue
![image](https://user-images.githubusercontent.com/45894930/147159544-90b3d05a-a540-416d-9725-fdd97614712f.png)
Can you also inject the rom title for this patch?

**Comment by GhostlyDark** [comment]
I made patches for such use cases. They can be in conjunction with other hacks.
https://github.com/gonetz/GLideN64/issues/2164#issuecomment-577407103

**Comment by Darth-Koopa** [comment]
Thanks a lot!

**Comment by Darth-Koopa** [comment]
> I made patches for such use cases. They can be used in conjunction with other hacks. [#2164 (comment)](https://github.com/gonetz/GLideN64/issues/2164#issuecomment-577407103)

I tested some of your patches using PJ64 and Gliden64: Mario Kart 64 doesn't boot, only black screen. Super Mario 64 won't allow me to select a save data

**Comment by GhostlyDark** [comment]
To clarify, those patches don't fix anything. They merely add an internal ROM title and a Game ID to work around the fact that those are required by GLideN64 and Mupen64Plus/Project64 to enable game specific hacks to fix emulation issues. The rest is up to the emulator and its plugins to handle. As a sidenote, Mario Kart 64 works with Mupen64Plus.

**Comment by Darth-Koopa** [comment]
> To clarify, those patches don't fix anything. They merely add an internal ROM title and a Game ID to work around the fact that those are required by GLideN64 and Mupen64Plus/Project64 to enable game specific hacks to fix emulation issues. The rest is up to the emulator and its plugins to handle. As a sidenote, Mario Kart 64 works with Mupen64Plus.

iQue Super Mario 64 and Mario Kart are playable on pj64, but after applying the patch, the games are not playable. Your patch has caused some unknown issue, hope you can fix them.

**Comment by Darth-Koopa** [comment]
![image](https://user-images.githubusercontent.com/45894930/147278320-5c285760-df8e-4c52-b081-b8198f837edb.png)
![image](https://user-images.githubusercontent.com/45894930/147278352-e7b88721-c258-43eb-8057-6ab53c22c715.png)
I tried the OOT texture pack, you wrote 攻击 as 玫击, which is wrong. Hope you can change that texture to 攻击。
