### ISSUE TITLE
F1 Pole Position 64: wrong background in menu

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#263]
Fixed copy frame buffer to RDRAM, background in F-1 Pole Position car tuning menu

Not fixed for me

![1](https://cloud.githubusercontent.com/assets/8987490/6431088/8df8333a-c024-11e4-884d-1820d260e93c.jpg)

**Comment by gonetz** [comment]
Yep, broken again :(

**Comment by gonetz** [comment]
Fixed
