### ISSUE TITLE
Super Luigi 64 Wont Dump

### ISSUE THREAD

**Issue by ssdip** [gonetz/GLideN64#2634]
So I Tried For A While Now And No Response 
Can Any One Help Me
![Captura de Tela (61)](https://user-images.githubusercontent.com/55263057/148663460-3bacd64f-c33d-46dc-b326-ec4a443a4fce.png)
![Captura de Tela (60)](https://user-images.githubusercontent.com/55263057/148663473-957d9b38-eca9-4f3a-afcf-a3b0544e6eda.png)

**Comment by oddMLan** [comment]
You have to set a Texture Dump hotkey in the "Hotkeys" tab.
Also make sure you're using the Qt version of GLideN64 (not WTL)
Get the latest prerelease (under github-actions) and use the Qt version (x86) https://github.com/gonetz/GLideN64/releases

**Comment by ssdip** [comment]
> Qt

i downloaded qt now gliden64 doesn't show up

**Comment by oddMLan** [comment]
Did the texture dumping work? If it did, you can close the issue

**Comment by ssdip** [comment]
> Did the texture dumping work? If it did, you can close the issue

yes it worked thanks

**Comment by oddMLan** [comment]
:) good to hear
Now please click "Close issue"
