### ISSUE TITLE
Regression: Check that texture fit TMEM before load

### ISSUE THREAD

**Issue by GhostlyDark** [gonetz/GLideN64#2641]
Doesn't happen with HD textures. Regression caused by 7417144f644217845d7106569f78dd3b13091756

![image](https://user-images.githubusercontent.com/31742919/150658318-0233dd06-dba0-4299-a581-dc4503e599cb.png)

Size is 64x64
![THE LEGEND OF ZELDA#0BE442B9#3#2_all](https://user-images.githubusercontent.com/31742919/150658340-c4cf26d0-113d-4fa0-aabb-e7b2e801b2d8.png)
THE LEGEND OF ZELDA#0BE442B9#3#2_all.png

Usable savestate can be found here: https://github.com/gonetz/GLideN64/issues/2569 (blood.pj.zip)

**Comment by GhostlyDark** [comment]
![image](https://user-images.githubusercontent.com/31742919/151176222-14786710-a9dd-4807-aede-c34e1c67fd49.png)

GOLDENEYE#38C2DA20#4#0_all.png
![GOLDENEYE#38C2DA20#4#0_all](https://user-images.githubusercontent.com/31742919/151176258-4d96f13a-f776-4317-bde8-c9a2df3ec81c.png)

GoldenEye, first level. It seems that all textures 64x64 or bigger are affected.

**Comment by fzurita** [comment]
@gonetz Instead of aborting the copy all together, maybe just what is valid memory can be copied if it goes out of bounds. Or you could just make the TMEM buffer bigger to account for that kind of situation.

**Comment by gonetz** [comment]
> @gonetz Instead of aborting the copy all together, maybe just what is valid memory can be copied if it goes out of bounds. 

Yes, it should be done like this. It was a lazy fix, because the problem it fixes was obviously wrong.
I'll do a proper fix. Thanks for the bug report.
