### ISSUE TITLE
Paper Mario Monstar issue

### ISSUE THREAD

**Issue by Darth-Koopa** [gonetz/GLideN64#2642]
In the original Nintendo 64 version of the game, Monstar has a moving iridescent star pattern over it. However, the emulator, incorrectly renders this as a cloud of star-like particles surrounding it. 

Here is the graphic comparsion

The above text is from the Super Mario Wiki and is available under a Creative Commons license. Attribution must be provided through a list of authors or a link back to the original article. Source: https://www.mariowiki.com/Monstar
![image](https://user-images.githubusercontent.com/45894930/150817674-558dd3d4-b81a-49f2-bf5b-99b1927cd879.png)
screenshot from emulator
![image](https://user-images.githubusercontent.com/45894930/150817881-034a89d4-5fe9-4c18-8a18-2100739214d7.png)
image of real console
image from [https://youtu.be/bMIkzLVkvbM](url)

Statesave[Paper_Mario_U.pj.zip](https://github.com/gonetz/GLideN64/files/7926943/Paper_Mario_U.pj.zip)

**Comment by olivieryuyu** [comment]
looks like a nice fb effect :)

**Comment by standard-two-simplex** [comment]
The stars are rendered as a decal over the monster texture. You need N64 style depth compare so the effect shows correctly.

**Comment by Darth-Koopa** [comment]
> The stars are rendered as a decal over the monster texture. You need N64 style depth compare so the effect shows correctly.

![image](https://user-images.githubusercontent.com/45894930/151715339-7ded4475-c924-4d80-bc6b-bd790b9846d7.png)
Issue fixed. thanks
