### ISSUE TITLE
Lens of truth depth issues

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#2647]
It seems like the lens of truth effect in Majora's mask is broken in some situations. Here is an example:
![Legend of Zelda, The - Majora's Mask (U)  !](https://user-images.githubusercontent.com/11581687/151992846-9a79fa47-2edc-4b53-b38b-e74e09738670.png)

The ice is rendering in front of the ghost.

Here is a save state for the USA version of the game for Mupen64plus.
[Legend of Zelda, The - Majora's Mask (U) [!].zip](https://github.com/gonetz/GLideN64/files/7979399/Legend.of.Zelda.The.-.Majora.s.Mask.U.zip)

**Comment by Jj0YzL5nvJ** [comment]
#2074

**Comment by fzurita** [comment]
Yeah, there are some elements in the environment have are rendering in front of everything else when the lens of truth is enabled. Depth is doing something weird...

**Comment by gonetz** [comment]
I tried to fix #2074, but did not find the source of  those problems. I'll again if I have time.

**Comment by gonetz** [comment]
I've advanced with that problem. I need more saves to test.

**Comment by gonetz** [comment]
I opened a PR with the fix: #2674
@fzurita could you test it on Android devices?

**Comment by fzurita** [comment]
Sure, will do.

**Comment by gonetz** [comment]
PR updated.

**Comment by Jj0YzL5nvJ** [comment]
Small issue with the shadows outside the area of effect.
https://imgur.com/a/shTf6uW

**Comment by gonetz** [comment]
> Small issue with the shadows outside the area of effect.

PR with the fix is updated, #2674
