### ISSUE TITLE
Jet Force Gemini: Crosshairs broken

### ISSUE THREAD

**Issue by avengah** [gonetz/GLideN64#2653]
I tried with Project64, Mupen64Plus, Retroarch with Mupen64Plus-Next core and original Mupen64, and original Mupen64 is the only one where the crosshairs display correctly. I've tried messing with various settings but nothing fixes it in the newer emulators without using a different video plugin.

**Comment by oddMLan** [comment]
That's due to the emulator's fault broken or missing FBInfo implementation. The CPU writes the crosshair to the framebuffer but the plugin can't know when this happens. It's the job of the emulator to inform the plugin of this change. Original Mupen64 is the only emulator that properly implements this requirement.

**Comment by avengah** [comment]
I see. Is Mupen64 the best emulator for JFG then, especially as I'm on an old, slow PC? It even gets the rain on Tawfret right as long as Copy auxiliary buffers to N64 memory is off. Apparently most emulators struggle with that!

**Comment by quicksilver7837** [comment]
Do all crosshairs display incorrectly for you or just certain weapons? 

Also have you noticed a strange camera shaking issue on tawfret? Mainly around the village and bridge area? I wonder if it's a related issue?

**Comment by oddMLan** [comment]
> I see. Is Mupen64 the best emulator for JFG then, especially as I'm on an old, slow PC? It even gets the rain on Tawfret right as long as Copy auxiliary buffers to N64 memory is off. Apparently most emulators struggle with that!

Yes, afraid so. Until newer emus get a better FBInfo implementation.

**Comment by avengah** [comment]
> Do all crosshairs display incorrectly for you or just certain weapons?
> 
> Also have you noticed a strange camera shaking issue on tawfret? Mainly around the village and bridge area? I wonder if it's a related issue?

All the crosshairs are broken. None of them show the outer part of the crosshair; the darker green parts that follow behind; you only see the central X with some weapons, and other weapons don't show any part of the crosshair.

I haven't played Tawfret through yet. I have only done quick tests so far. I will let you know when I get there on my playthrough.

I will note that some of the newer LLE graphics plugins like Angrylion, ParaLLEl etc. might possibly be better on faster PCs, but on my old toaster they stutter badly. ParaLLEl runs smoothly only at 1x upscaling. So I'm pretty much stuck using Project64 Video and GLideN64 (and Jabo's works too but is quite glitchy). Banjo-Tooie and Conker run perfectly for me with Project64 and GLideN64. Thanks!

**Comment by avengah** [comment]
I got it mostly working well in m64p with GLideN64 and original mupen64, but there is an issue with the characters' shadows. For crosshairs to show correctly, Copy auxiliary buffers to N64 memory must be off. However, for shadows to display correctly, it must be on. With it off, when you jump, there is a black line that appears next to you on the ground, and it gets thicker and disappears as you go up, then reappears and goes thinner, then disappears as you land. I think this is an issue exclusive to GLideN64 as I never saw it in other plugins.

**Comment by weinerschnitzel** [comment]
I thought there efforts made to make mupen64plus handle fbinfo the same as mupen64 0.51. 

If the behavior is not the same between mupen64 and mupen64plus, maybe there is still room for mupen64plus to improve?

I dont think copy auxiliary buffer to rdram should clobber fbinfo, though. That would be a plugin matter.

**Comment by Jj0YzL5nvJ** [comment]
mupen64plus/mupen64plus-core#931

**Comment by gonetz** [comment]
I fixed several hard-to-find issues with FBInfo and Aux buffer copy both enabled, #2657
Crosshairs and shadows in JFG now work well. Tested with Mupen64. It should work with mupen64plus with Cached Interpreter, but I did not test it.

**Comment by gonetz** [comment]
I tested JFG with mupen64plus, Cached Interpreter mode. FBInfo works fine.
@avengah please test the latest master build.

**Comment by mudlord** [comment]
> This game also uses some softening post-processing of that image on CPU side.

The first game to do Gaussian blur-style soft shadows, which is exceptionally amazing. 
Modern games instead used Shader Model 2.0 pixel shaders and up on render target/FBO textures for this.

Rare was exceptionally ahead of its time.

**Comment by quicksilver7837** [comment]
With the recent changes to this game I am now getting this on my raspberry pi 4 in the second area of the tawfret level also the little video screens on the character select menu are just black and static:
![20220224_223858](https://user-images.githubusercontent.com/35534553/155649302-26237fb9-b195-418b-b9fc-30fc2f31f9d8.jpg)
Prior to the changes the game was playable. If I turn off the gliden64 compatability check the game functions as it did before so this may be caused by changes to the gliden64 compatibility .ini

**Comment by weinerschnitzel** [comment]
@quicksilver7837 are you using a dynarec core? The new settings prefer fbinfo, and if you are not using an interpreter core with mupen64plus, fbinfo will not be used.

Enabling copy color to RDRAM should restore the old functionality if you need to use the dynarec core for speed.

**Comment by gonetz** [comment]
> The new settings prefer fbinfo, and if you are not using an interpreter core with mupen64plus, fbinfo will not be used.

Right. JFG with FBInfo enabled, mupen64plus:
![JFG1](https://user-images.githubusercontent.com/8983092/155871715-3f9aa9ae-ec4f-4376-9238-46be7a1c4b42.jpg)
![JFG2](https://user-images.githubusercontent.com/8983092/155871713-3b578464-01e4-4fd8-bf22-d604fe936d89.jpg)

**Comment by gonetz** [comment]
Fixed with PR #2657

**Comment by JWock82** [comment]
Switching the RDP Plugin to angrylion fixed the issues on Tawfet for me. Runs great now. I get the rain effect without a black screen, I get crosshairs, and I can get through the cutscene where it froze up before. The image is a little more grainy with angrylion, but honestly it looks just like it did on an old CRT TV when I first played the game.
