### ISSUE TITLE
Texture path/default.

### ISSUE THREAD

**Issue by Nes-player4Life** [gonetz/GLideN64#266]
Unable to default the location defined by plugin.

**Comment by gonetz** [comment]
A, what?

According to the current convention for Rice texture packs format, texture Path is path to a folder, which contains 'hires_texture' subfolder, which in turn contains texture packs.
This is probably confusing. I can change it as follow: the Path should point to the folder with hires packs, generally to "Plugin/hires_texture".

**Comment by Nes-player4Life** [comment]
Sorry, I typed to fast and misspoke.

Changing the plugin to read from the folder containing packs may cut down on future users requests.

Most users expect to have the packs read from a folder containing those packs and not a location containing a folder of the texture packs.

Main Issue:
Selecting {Default} option resets other aspects of the plugin but does not return the file path to the Texture pack's default location.

**Comment by gonetz** [comment]
-- Most users expect to have the packs read from a folder containing those packs and not a location containing a folder of the texture packs.

You're right. I had choose a solution which is compatible with current code. Currently texture library search for 'hires_texture' folder under provided Path. It is inherited behavior. I agree that for end user it will be less confusing to provide Path to folder with texture packs, which by default is "Plugin/hires_texture"

-- Selecting {Default} option resets other aspects of the plugin but does not return the file path to the Texture pack's default location.

I forgot to correct that part . Thanks!

**Comment by gonetz** [comment]
Fixed. Texture path now should point to folder with texture packs. Reset to default set it to "Plugin/hires_texture"

**Comment by Nes-player4Life** [comment]
Resolved!
