### ISSUE TITLE
Transparent textures in Densha De Go

### ISSUE THREAD

**Issue by danepowell** [gonetz/GLideN64#2663]
Out of the box, running Densha De Go in Mupen64Plus-Next in Retroarch with Gliden64 plugin, almost all of the textures in the game are transparent. Disabling legacy blending seems to fix this.

Can we add `generalEmulation\enableLegacyBlending=0` to GLideN64.custom.ini for this game? I'm happy to open a PR if this is the right approach.

**Comment by gonetz** [comment]
enableLegacyBlending is off by default. Do you haver other defaults with Retroarch?
Legacy blending is mostly for old GLES2 and GLES3 devices.

**Comment by danepowell** [comment]
Interesting. I am using default settings, and yet legacy blending is enabled. I wonder if this is a bug in mupen64plus-libretro-nx?

I'm using the gles3 core, which is the only one available via Rotroarch on Android. Looking at the config, it looks like the default _should_ be disabled, and yet in reality it's enabled. Here's the commit I'm running on my Shield: https://github.com/libretro/mupen64plus-libretro-nx/blob/018ee72b4fe247b38ed161033ad12a19bb936f00/GLideN64/src/Config.cpp#L47

**Comment by gonetz** [comment]
I guess that settings from Mupen64Plus-Next.default.opt.txt override GLideN64 defaults.
You may ask Retroarch, why they made legacy blending enabled by default. 
May be there were complains on performance.

> Can we add generalEmulation\enableLegacyBlending=0 to GLideN64.custom.ini for this game? I'm happy to open a PR if this is the right approach.

Yes, we can. Please open a PR.
