### ISSUE TITLE
Banjo-Jitterie

### ISSUE THREAD

**Issue by GhostlyDark** [gonetz/GLideN64#2668]
I have no idea what part of the emulation to blame here, but Banjo-Kazooie runs like this:
https://streamable.com/41ql7v

Using mupen64plus CLI (x64) with the Static Interpreter (cxd4) RSP in HLE mode.

This is not reproducable using any other video plugin, nor does it look like this with Project64 using similar settings. It looks fine with the cxd4 RSP doing LLE graphics or using a different RSP plugin.

**Comment by Jj0YzL5nvJ** [comment]
mupen64plus/mupen64plus-core#485
