### ISSUE TITLE
glide64 hotkey problem

### ISSUE THREAD

**Issue by MarioVercetti** [gonetz/GLideN64#2669]
in project64, when i click F1 which is reset button, its selecting save state and crashing the emulator
that happens only if i use glide64 plugin

**Comment by IronYoshi64** [comment]
Is it the Glide64 Final, like the non GLideN64 plugin?

**Comment by gonetz** [comment]
Glide64 is another plugin. It is not supported here.
I checked Project64 with GLideN64, no issues with F1 hotkey.

**Comment by IronYoshi64** [comment]
Yes, Glide64 is a whole different plugin that is very old.

You can completely turn off the hotkeys in Glide64 with a simple setting change.

Open up the Glide64.ini file in notepad or whatever, under [SETTINGS] there is an option called hotkeys = 1, change that 1 to a 0 and save file.
