### ISSUE TITLE
Super Smash Brothers missing effect

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#267]
this effect doesn't seem to emulate correctly, missing all together.

Should look like this [Captured with AL's RDP]
![capture](https://cloud.githubusercontent.com/assets/9299743/6433195/4ea7cada-c01d-11e4-8cee-764dceac8ea8.PNG)

**Comment by olivieryuyu** [comment]
savestate please?

**Comment by theboy181** [comment]
Are you for real?

**Comment by gonetz** [comment]
It's from intro. I don't need a savestate.

**Comment by olivieryuyu** [comment]
yes i am for real the boy181 and I didn't know it was in the intro as I dunno all games by heart.

**Comment by theboy181** [comment]
smash brothers. I don't beleive you. All good though. Thought you were trolling me.

**Comment by olivieryuyu** [comment]
woa this effect seems hard to emulate :/

**Comment by gonetz** [comment]
Suddenly fixed:
![gliden64_smash_brothers_004](https://cloud.githubusercontent.com/assets/8983092/18315708/227ff492-7542-11e6-9f47-490250d6bbfa.jpg)

**Comment by theboy181** [comment]
I will have to test. This will be the first hle plugin to emulate this effect. Nintendo Wii u doest even do it properly. How did you do it!!???  Congrats

**Comment by theboy181** [comment]
Is there a download for me to test ?

**Comment by weinerschnitzel** [comment]
Im pretty sure Rice does it

**Comment by theboy181** [comment]
Did you check?

**Comment by gonetz** [comment]
I'm not sure when it was fix

**Comment by theboy181** [comment]
What version of the plugin do I need to test? the latest on the google drive wasnt working for me. ;(

**Comment by gonetz** [comment]
I'll upload master build this weekend.

**Comment by theboy181** [comment]
How cruel..

**Comment by weinerschnitzel** [comment]
You're right, i was thinking of the wrong lense flare with Rice. Sorry! :p

**Comment by olivieryuyu** [comment]
it does not work before the commit related to the Mario Tennis VS screen. So it must be very recent.

**Comment by AmbientMalice** [comment]
>it does not work before the commit related to the Mario Tennis VS screen. So it must be very recent.

That particular commit also fixed Turok 3's thermal goggles.

**Comment by theboy181** [comment]
@AmbientMalice  are you able to compile and share?

**Comment by AmbientMalice** [comment]
>@AmbientMalice are you able to compile and share? 

Not for Zilmar spec, unfortunately.

**Comment by theboy181** [comment]
@gonetz 

When does the weekend start? ;P

**Comment by theboy181** [comment]
@gonetz 

What commit fixed this, and was the same commit related to Mario Golf getting fixed too?
