### ISSUE TITLE
Early switching to low lods of charcter models in perfect dark using the latest release

### ISSUE THREAD

**Issue by Xii-Nyth** [gonetz/GLideN64#2672]
![1964 2022-03-14 13-01-26](https://user-images.githubusercontent.com/101597311/158258446-23361d14-3206-44ec-a73d-0011d321739f.png)

Other objects are fine however and only switch to low lods when n64 style mip mapping is enabled.

On:
![1964 2022-03-14 12-36-53](https://user-images.githubusercontent.com/101597311/158258691-8d93f9c2-a0af-4376-a014-649d9c4a82b8.png)

Off:
![1964 2022-03-14 12-37-23](https://user-images.githubusercontent.com/101597311/158258795-8eb56255-5182-4621-9cc4-833a72b352ec.png)

**Comment by gonetz** [comment]
n64 style mip mapping is incompatible with HD textures, it is true. If you have it disabled, original low-level textures should not appear if there are high-res ones. Could you give me a link to the HD pack you are using, and a savestate from that point?

**Comment by Xii-Nyth** [comment]
> n64 style mip mapping is incompatible with HD textures, it is true. If you have it disabled, original low-level textures should not appear if there are high-res ones. Could you give me a link to the HD pack you are using, and a savestate from that point?

I made a mistake, it turns out this issue has always existed, even with the old release and without a texture pack. It was just very hard to notice when the background was also a lower resolution.

Anyways in case this could help with anything:

Here is the texture pack (unfinished): https://mega.nz/file/cwImnaKJ#hDHMxQY5Oef5RQJGojmlvB0KiN9abjbaSZw1OCIbWG0

And here is the save state: https://mega.nz/file/N9R0nLQR#kvkfsHZtbeKDfW7yauZee0oUGn__4HTNZp2i8w0nuvc
