### ISSUE TITLE
Although overall of benefit, not sure if these were intended to happen with the new accurate coordinates.

### ISSUE THREAD

**Issue by Xii-Nyth** [gonetz/GLideN64#2673]
As I mentioned in the patreon comment [https://www.patreon.com/posts/some-news-63735468](url)
There were many positive changes other than texture alignment when using the new accurate texture coordinates, along with a few negatives. Ill gives examples of both below.

If these were intended/expected, feel free to close the issue. If not and you are wondering what it might be, it looks similar to disabling Perfect Darks's built in anti aliasing/texture filtering.

<img width="784" alt="ex2" src="https://user-images.githubusercontent.com/101597311/158269321-94602fc0-525c-4fda-8ce5-06c2cf807e11.png">

![ex1](https://user-images.githubusercontent.com/101597311/158269205-a33b64fb-79c3-4eee-9f23-df728844554f.png)

**Comment by gonetz** [comment]
Some differences could be caused by fixes in mip-mapping emulation. PD uses mip-mapping a lot. It is better compare not accurate-vs-non accurate, but accurate-vs-angrylion's plugin, in native-res. Some issues, like gaps and dots between polygons also can be caused by using of high-resolution. Texture mapping is truly accurate only in native res.

**Comment by Xii-Nyth** [comment]
> Some differences could be caused by fixes in mip-mapping emulation. 
Oh well these specific issues occur when toggling enable inaccurate texture coordinates on or off, and both screenshots are taken with the same revision.

The only mip mapping related problems I described in #2672

**Comment by Xii-Nyth** [comment]
Oh wait just realized I mixed up mip mapping and lods. Ill go compare to angrylions then and follow up later
