### ISSUE TITLE
Texture Pack Path For WCW / nWo Revenge Not Sanitized

### ISSUE THREAD

**Issue by flagrama** [gonetz/GLideN64#2676]
`WCW / nWo  REVENGE  `&nbsp;is the internal name of the game. At least on Project64, the `/` is not properly sanitized so only a folder called `WCW` gets created while trying to dump textures. This likely also causes an issue for loading textures. Rice format packs exist for the game which seem to sanitize the `/` to a `-` but weren't tested with GLideN64.

This seems to be the only game released with an internal name with this character. Modifying the internal header to change the `/` to a `-` also worked, but is not very viable for distributing texture packs.

Found out this behaviour with @Oran26thRTI on the project64 discord.

**Comment by gonetz** [comment]
Yes, currently only ':' is replaced by '-' in a rom name.
I uploaded fix 084dd026028, which does the same for '/'.
Enhanced and HD textures should work for this game now.

**Comment by flagrama** [comment]
I'm pretty sure this is good now so I'll go ahead and close this. If Oran26thRTI has issues I'm sure he'll leave a comment.
