### ISSUE TITLE
Custom fonts no longer show up in OSD settings like in older versions?

### ISSUE THREAD

**Issue by Xii-Nyth** [gonetz/GLideN64#2678]
![image](https://user-images.githubusercontent.com/101597311/160673922-6d6e1904-365b-4b62-9d4a-c14b7bac7bef.png)
![image](https://user-images.githubusercontent.com/101597311/160673942-7019e652-0468-4ec0-81e0-09e3c4e84a84.png)
![image](https://user-images.githubusercontent.com/101597311/160673950-8947ee1c-7e58-46a0-8b7b-a3955a91c68b.png)
![image](https://user-images.githubusercontent.com/101597311/160673955-7a2565b8-5b6a-43c2-be16-c3abab654af5.png)
![image](https://user-images.githubusercontent.com/101597311/160673958-246429a4-3a65-46b5-95ca-207f784bd3fe.png)

**Comment by oddMLan** [comment]
You're comparing the Qt version agaisnt the WTL version. The WTL version has a proper Font display. The Qt version doesn't really show the font previews like that.

**Comment by Xii-Nyth** [comment]
Oh no it was just from 2016, then new WTL versions also have the same issue
![image](https://user-images.githubusercontent.com/101597311/160749180-39143e2f-83fd-4c15-9d43-8c2c03e641ff.png)

**Comment by Xii-Nyth** [comment]
Ok I found out I had the right idea editing the config, but you have to use the full name standalone, rather than the file name and path.

![image](https://user-images.githubusercontent.com/101597311/160910187-133521b1-151a-4169-a3c8-b7e45d64fef6.png)
![image](https://user-images.githubusercontent.com/101597311/160910953-5e6e06b2-df8f-4bba-9546-54502db1152b.png)

**Comment by Xii-Nyth** [comment]
@gonetz 
Maybe a note could be added below, which reads:

"If the desired font is not listed below, navigate to your installation where GLideN64.ini is located, and open it with a text editor.

Then find your active profile [Default = User], and change the value of "font\name=_NAME.ttf_" to "font\name=_Full Name of Font.ttf_", and save the file. Do not include the path to where the font is located before the name.

_The font's full name can be found in Settings>Personalization>Fonts_"

**Comment by gonetz** [comment]
> Maybe a note could be added below, which reads:

Done in [a58b944](https://github.com/gonetz/GLideN64/commit/a58b944e061d0458e668929df02ad2a8d1dd510c)
