### ISSUE TITLE
[Request] Choose Display in Video Settings

### ISSUE THREAD

**Issue by ThomasCapella** [gonetz/GLideN64#2682]
I like using multiple displays on my computer. The problem with using Project64 is if I want to use a display that's secondary, I have to set it to my primary. It would be convenient to have a dropdown in the video settings to choose the display you want to use. That way, you can configure video settings and use fullscreen for your preferred display.

**Comment by gonetz** [comment]
@ThomasCapella  Please try builds from #2686 for Project64
New "borderless window" option supports monitor selection.
I still don't know, how to select non-primary display for true fullcreen mode, but "borderless window" should work with any monitor you have attached.

**Comment by ThomasCapella** [comment]
Oh cool. Thank you.

**Comment by ThomasCapella** [comment]
@gonetz That's actually perfect for me. I tend to use borderless anyways.

**Comment by gonetz** [comment]
@ThomasCapella does it work properly with all your displays ? I'd like to get a feedback before merging that feature to the master branch.

**Comment by gonetz** [comment]
> The only thing is it shows the same name for both of them.

If monitors are the same, names also be the same.
I made a correction, which sorts monitors in the list from left to right, so leftmost display will be the first in the list.

**Comment by gonetz** [comment]
Fixed with PR #2686
