### ISSUE TITLE
Cruis'n Exotica broken graphics

### ISSUE THREAD

**Issue by xiartic** [gonetz/GLideN64#2684]
After successfully displaying the intro logo screens. Cruis'n Exotica's graphics break completely on GLideN64's latest and earlier versions. 

GLideN64:
![gliden64](https://user-images.githubusercontent.com/78692485/167693439-9e417b1a-deb7-4bae-be8b-8479cadc18d6.PNG)

![gliden64 2](https://user-images.githubusercontent.com/78692485/167694702-f9d9499b-040e-4233-b3f7-647ff8cb88a3.PNG)

Glide64:
![glide64](https://user-images.githubusercontent.com/78692485/167693461-7d48c9e8-a3c2-48fc-9fb5-9233a241dd7a.PNG)

![glide64 2](https://user-images.githubusercontent.com/78692485/167694715-dda89db9-898d-411e-9515-186a31cd202c.PNG)

**Comment by Jj0YzL5nvJ** [comment]
Make sure to clear your shader cache...

<img src="https://i.imgur.com/dH8Ye0H.png">

<img src="https://i.imgur.com/d8OAngT.png">

P.S: I'm using `EnableInaccurateTextureCoordinates`=`True` because this PC sucks... #2656

**Comment by xiartic** [comment]
Seems like the issue doesn't exist in Mupen64Plus. Now I'm not sure is this an issue how GLideN64 handles things with Project64 or if this is a problem on Project64's side of things. If it's latter then this issue should be closed.

**Comment by Jj0YzL5nvJ** [comment]
This happens in LLE when using [angrylion-plus v1.6-24-g7ff7ae7](https://github.com/ata4/angrylion-rdp-plus/releases/tag/nightly-build):
<img src="https://i.imgur.com/bN2jrsv.png">

**Comment by xiartic** [comment]
Closing this because it's not seemingly an issue with GLideN64.

**Comment by Squall-Leonhart** [comment]
It probably is an issue with GlideN64, since opening and closing its options restores a working image.

looks like a framebuffer clear doesn't fire.
