### ISSUE TITLE
[request] add Chinese language support

### ISSUE THREAD

**Issue by Darth-Koopa** [gonetz/GLideN64#2689]
[GLideN64.zip](https://github.com/gonetz/GLideN64/files/8838388/GLideN64.zip)
I found this Chinese translation of GlideN64. Can you examine it and add it in the offical release?

**Comment by Darth-Koopa** [comment]
![屏幕截图 2022-06-04 151929](https://user-images.githubusercontent.com/45894930/172022561-2e20ba65-831c-4270-be6d-50675f0b259b.png)
In my perspective, it look great.

**Comment by gonetz** [comment]
gliden64_zh.qm is a compiled translation. I need the original translation file, gliden64_zh.ts. ts file can be edited, that is adapted for future updates of plugin's GUI.

**Comment by Darth-Koopa** [comment]
> gliden64_zh.qm is a compiled translation. I need the original translation file, gliden64_zh.ts. ts file can be edited, that is adapted for future updates of plugin's GUI.

This is the original post of the translated glideN64: https://www.ppxclub.com/700309-1-1

**Comment by gonetz** [comment]
Thanks! I hope the author will share his/her work with us.

**Comment by gonetz** [comment]
Done in #2690
@shinyoyo - thanks!
