### ISSUE TITLE
Texture dump doesn't happen (Detailed explanation)

### ISSUE THREAD

**Issue by md500** [gonetz/GLideN64#2693]
**Version information:**

 - Platform: Platform: Windows 10 Enterprise 1809 64bit build 17763.1012
 - Plugin version of Emulator: Project 64
 - GPU: Intel HD Graphics 620 
 - GPU Driver version: 26.20.100.8141
 - GPU Gen: 7th
 - CPU: Intel Core i5-7200U 2.50Ghz (3.10Ghz on turbo)
 - Architecture of Emulator: 32bit
 - Architecture of GlideN64: 32bit
 - Build/commit of Emulator: Dev-4.0.0.5825-3913fb5
 - Build/commit of GlideN64: a2f1660 (using GLideN64-a2f1660-Windows-Project64-WTL-x86.zip on Releases)

**Describe the bug**

Latest plugin version doesnt dump textures in Donkey Kong 64 (not tested if happens in other games). Tried setting File Storage instead of memory cache in N64 textures, Use File Storage istead of memory cache, and Save Enhanced texture cache to hard disk. Only hires_texturesS folder is loaded but texture_dumpS it seems that it does not see the folder and does not dump anything (although the program creates the folder if it is deleted). However Hi Res texture loading works.

![DUMP](https://user-images.githubusercontent.com/3111925/177421891-ac94c889-95f3-4492-837d-4ad7465b180b.png)

Folder permissions is in Everyone (no permissions error)

![PERMS](https://user-images.githubusercontent.com/3111925/177422254-cc8d6335-0f2c-4045-8fd1-be3203522563.png)

In Glide64 Final ( May 8 2012) when "Texture dumping/editing mode"  and "save texture cache to hard disk" is ticked, textures are dumped if i press "D" Button toggle, on keyboard (controls are configured to prevent conflict with Glide64) and hires_texture folder is loaded if there are texture files texture files there if (ej. hires_texture\DONKEY KONG 64\GlideHQ) exists and texture dumping happens in (ej. texture_dump\DONKEY KONG 64\GlideHQ), and Press "R" keyboard button to reload hires_texture regenerating its hires cache related files. In other words, you can dump textures and/or load hires textures at same time with option reloading with "R" button.

![glide64options](https://user-images.githubusercontent.com/3111925/177422147-2ce03058-e00e-4c66-81b0-912f814ec870.png)

GLideN64 finds hires_textures files without GlideHQ (i think to prevent colission if both gfx plugin texture location points to same folder).

But in this case, GLideN64 doesnt dump textures. Tried Pressing D button toggle to dump, but it doesn't do anything...

![LOCATION](https://user-images.githubusercontent.com/3111925/177422314-f4a611bf-ecdf-4a01-9f26-25f396112489.png)

![ResultOfDump](https://user-images.githubusercontent.com/3111925/177424380-66e86a2e-3e42-4f5e-b93f-f87025325d86.png)

**To Reproduce**

Steps to reproduce the behaviour:
1. Open Project64 32bit (64bit not tested)
2. Select GLideN64 Plugin 32bit WTL
3. Options > Graphics Settings.
4. In Texture Enhancement, tick Use File Storage Instead of memory cache, Use Texture Pack, Use file storage istead of memory cache, and Save enhanced texture cache to hard disk. (On my case,changed default folder paths to another with an S, (hires_texturesS,cacheS,texture_dumpS)
5. Run DK64 ROM.
6. While Gameplay press R, to reload hires textures or D to start dumping
7. Check C:/Program Files (x86)/Project64 3.0.1/Plugin/texture_dumpS folder to see if any texture is dumped.
8. No texture dump in Texture_dumpS triggered. In addition, the corresponding game folder textures is not created. Again, no permissions issue because, the permissions are inherited from the Plugin folder and set to Everyone owner and set to total control/full control.

![permissionsS](https://user-images.githubusercontent.com/3111925/177425928-b45453ce-b1ca-4480-b8be-3527cdc2eb1f.png)

**Expected behaviour**
Textures are dumped to configured texture pack folders if "D" button toggle is pressed and "R" to reload hi res textures (and regenerates cache)

**Screenshots**
Screnshots are included to corresponding context.

**Additional context**
I dont know if this works on GlideN64 stable versions and old commits, and i dont know if its works on Project 64 64bit and GLideN64 64bit architecture. Not tested if this issue happens in other games.

**Comment by Jj0YzL5nvJ** [comment]
> * Build/commit of GlideN64: https://github.com/gonetz/GLideN64/commit/a2f16608b395515c60067f29c12d95c63975d33b (using GLideN64-a2f1660-Windows-Project64-WTL-x86.zip on Releases)

The really important part is whether the problem is reproducible with the Qt version.

> [WTL hasnt been updated in quite a while, use the Qt version](https://github.com/gonetz/GLideN64/issues/2518#issuecomment-1159239557)

**Comment by md500** [comment]
@Jj0YzL5nvJ It works on QT version! Now how I can disable framebuffer textures dump? (I paused game but it also dumps framebuffer textures) ? I only want to dump textures in game but no framebuffer textures.

**Comment by Jj0YzL5nvJ** [comment]
Disabling the frame buffer emulation... maybe? I really have no idea.

**Comment by md500** [comment]
@Jj0

> Disabling the frame buffer emulation... maybe? I really have no idea.

Mmm, i forgot to mention that Glide64 Final doent emulate framebuffer. Well back to this case, unticking options and setting, disables Framebuffer emulation, but it dumps textures very well. but i dont know if GLideN64 will determine whether the texture is a framebuffer or not, and add a feature like "Dump also framebuffer textures" or "Render framebuffer as texture"

![Framebufer Disable](https://user-images.githubusercontent.com/3111925/177465391-1434fc93-74c9-4bd5-bb83-6a7dbcd1ce92.png)

**Comment by Jj0YzL5nvJ** [comment]
![efb](https://user-images.githubusercontent.com/12230570/177467199-236815be-cd03-4cda-995d-8fc25de6d016.png)

**Comment by md500** [comment]
> ![efb](https://user-images.githubusercontent.com/12230570/177467199-236815be-cd03-4cda-995d-8fc25de6d016.png)

Emulate framebuffer with copy options disabled (on this case framebuffer like copy options disables "image mirroring?" and textures framebuffer is not dumping.

![Framebuffer enable but processing disabled](https://user-images.githubusercontent.com/3111925/177470758-1ba81bed-b7b2-4180-906c-c8a12219310b.png)

Emulate framebuffer with copy options enabled ( framebuffer copy mirrorring is working, but texture framebuffer is also dumping)

![Framebuffer enable whith video card frame buffer and depth buffer enable](https://user-images.githubusercontent.com/3111925/177471071-52deed95-580f-40e0-a0fa-bbc78b7cb49f.png)

From what I'm seeing it is not necessary to completely disable framebuffer emulation

**Comment by Jj0YzL5nvJ** [comment]
Async mode is for speed, it corrupts some effects:

The broken jigsaw puzzle effect (Async mode):
![banjo-kazooie-008](https://user-images.githubusercontent.com/12230570/31359335-cb280cc2-ad06-11e7-9f3a-2b215e83623f.png)

The correct jigsaw puzzle effect (Sync mode):
![banjo-kazooie-009](https://user-images.githubusercontent.com/12230570/31359355-e7760c80-ad06-11e7-9b8c-6d5df8eb31ca.png)

**Comment by md500** [comment]
> Async mode is for speed, it corrupts some effects:
> 
> The broken jigsaw puzzle effect (Async mode): ![banjo-kazooie-008](https://user-images.githubusercontent.com/12230570/31359335-cb280cc2-ad06-11e7-9f3a-2b215e83623f.png)
> 
> The correct jigsaw puzzle effect (Sync mode): ![banjo-kazooie-009](https://user-images.githubusercontent.com/12230570/31359355-e7760c80-ad06-11e7-9b8c-6d5df8eb31ca.png)

Yeah, it also occurs when i use dk64 camera: on async mode the reticle also shows in the photo, which is not correct. So sync mode is recommended (altough it also dumps texture framebuffer). i dont know if is correct to use "VI Origin Change" at least, in dk64 i dont see any issue about it.

Mmm so the issue to texture dump issue must be closed, and file other bug like framebuffer dumping on texture. someone can link the bug, to prevent duplicate?

**Comment by md500** [comment]
Context about texture dumping: Making texture retexture using Real-ESRGAN, texture framebuffer doesnt make sense when i making hi res textures with Real-ESRGAN. so i had to disable sync/async modes (Copy video card framebuffer to N64 memory set to Never) to prevent it.

**Comment by Xii-Nyth** [comment]
Hey md500 Ive also started on a pack for this but got pushed back since im working on pd. I managed to dump everything with the newest update usuing inaccuate texture coordinates and mipmaps off like I did with perfect dark

**Comment by Xii-Nyth** [comment]
heres my dumps sorted ot a tiny bit

zip is too big and 7z isnt supported, so just rename to .7z
[DONKEY KONG 64.zip](https://github.com/gonetz/GLideN64/files/9804477/DONKEY.KONG.64.zip)
