### ISSUE TITLE
Donkey Kong 64: Hires Textures mixes textures with others textures in hires_texture causing bad look

### ISSUE THREAD

**Issue by md500** [gonetz/GLideN64#2694]
**Version information:**

 - Platform: Platform: Windows 10 Enterprise 1809 64bit build 17763.1012
 - Plugin version of Emulator: Project 64
 - GPU: Intel HD Graphics 620 
 - GPU Driver version: 26.20.100.8141
 - GPU Gen: 7th
 - CPU: Intel Core i5-7200U 2.50Ghz (3.10Ghz on turbo)
 - Architecture of Emulator: 32bit
 - Architecture of GlideN64: 32bit
 - Build/commit of Emulator: Dev-4.0.0.5825-3913fb5
 - Build/commit of GlideN64: a2f1660 (using GLideN64-a2f1660-Windows-Project64-QT-x86.zip on Releases)

**Describe the bug**

Sometimes when i load hires textures, is get mixed with another texture looking so bad. I made my custom textures and improved it with ESRGAN with x8 with only dumped textures (had to play game at 101% to get all dumped textures causing a bunch of 6611 dumped textures and remade it to x8 with ESRGAN), and deleted 1x1 (8x8 on hires) and 8x8 textures (64x64 textures).

The issue will happen more frequently when you are more away of the camera. (C down button).

Doesnt happen on cinematics (Like DK RAP, DK TV,Ending,Outro1 -100%- and Outro2 -101%-)

**To Reproduce**

Steps to reproduce the behaviour:
1. Open Project64 32bit (64bit not tested)
2. Select GLideN64 Plugin 32bit QT
3. Options > Graphics Settings.
4. In Texture Enhancement, tick Use Texture Pack.
5. Run DK64 ROM.
6. Wait while hires textures are loaded (you can copy GlideNHQ from texture_dump to hires_texture).
7. Go to any world. (Doesnt happen on cinematics)
8. The issue happens like the following:

Custom Textures:
![issue](https://user-images.githubusercontent.com/3111925/178093428-2c8bde57-5ed3-48df-a4b7-f647d3750781.png)

Default textures from texture_dump (copy GlideNHQ from texture_dump to hires_texture).

![issue with dumped textures](https://user-images.githubusercontent.com/3111925/178093894-06ae7d68-3585-4029-a52c-baeff32b5ae9.png)

**Expected behaviour**

Assuming that you have custom textures or (hires textured). In this case, hires textures are off.
![expected](https://user-images.githubusercontent.com/3111925/178093438-4c19c38d-17c6-4436-bbd3-a6a4ea9a54b1.png)

**Screenshots**
Screnshots are included to corresponding context.

**Additional context**
Location:
![Location](https://user-images.githubusercontent.com/3111925/178093588-a8d29c0a-a0f8-4ac1-834c-f77300a9d326.png)

Config:
![config](https://user-images.githubusercontent.com/3111925/178093593-62b043ca-c652-4e85-9abd-3b791b2429bb.png)

Size of my custom textures. Textures are x8:

![TexturesAreX8](https://user-images.githubusercontent.com/3111925/178093604-151cb7c8-2bc6-47e4-abc2-56d906088673.png)

Reloaded textures, deleted cache file, copied GlideNHQ from texture_dump to hires_texture to look if happens with stock textures too. Same issue. I dont know if happens with another game (Gonna try Banjo Kazooie with 100% to get all texture_dump complete)

**Comment by Jj0YzL5nvJ** [comment]
Disable: `Enable N64-style mip-mapping`, `Enable per-pixel lighting` and `Enable pixel coverage calculation`

Observations:

- If you use `Store compiled shaders for performance`, clear the shader cache regularly to avoid false positives... or disable it.
- `Multiple of N64 resolution` settings other than multiples of 2 can cause glitches.
- `RDRAM image dithering` to `Blue noise` may cause glitches.
- Enabling `Use no file storage or cache` will save you time when testing...

**Comment by Xii-Nyth** [comment]
ep looks like mip mapping on to me, I havent played dk with a pack yet to check. Then one you are using looks nice, ccan u send it to me so I can see if I have the same issue? :)

**Comment by md500** [comment]
> Disable: `Enable N64-style mip-mapping`, `Enable per-pixel lighting` and `Enable pixel coverage calculation`
> 
> Observations:
> 
>     * If you use `Store compiled shaders for performance`, clear the shader cache regularly to avoid false positives... or disable it.
> 
>     * `Multiple of N64 resolution` settings other than multiples of 2 can cause glitches.
> 
>     * `RDRAM image dithering` to `Blue noise` may cause glitches.
> 
>     * Enabling `Use no file storage or cache` will save you time when testing...

Problem Solved, followed these tips and it works. In banjo tooie and kazzoie (which are games am playing) is necessary to delete 8x8 png textures (seems to mipmapping), including DK64. 

I Think when dumping is done, can i reenable the setting only if all mipmapping textures are deleted.
  
> ep looks like mip mapping on to me, I havent played dk with a pack yet to check. Then one you are using looks nice, 
> ccan u send it to me so I can see if I have the same issue? :)

Cant upload textures due to low upload speed (only 64 KB/s...)

**Comment by Xii-Nyth** [comment]
from my experiance the mipmapped textures will still appear at far distances if enabled, but their chucksums will randomize each time you reload the game, so you cant change them permanantly. If this wasnt the case they could be used for a fog effect.

**Comment by Xii-Nyth** [comment]
just recently found a few places in pd where they wil just pop in rather then fade in even with n64 style mipmapping unchecked. only on 2 levels, however it doesnt happen with accurate tex coord on.
So basically
inaccurate on and mipmaps off for dumping
accurate on and mipmaps on for gameplay
I havent been as thorough with dk like I mentioned in the other post but it seemed to be working
