### ISSUE TITLE
All-Star Baseball '99: wrong 2d in game

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#27]
wrong 2d gfx in game

**Comment by olivieryuyu** [comment]
damn even in LLE it is not correct???? How is it possible?

**Comment by olivieryuyu** [comment]
it works ok with Z64 but not in LLE gliden64? side effects of the special code?

**Comment by theboy181** [comment]
What do you mean about source code for the game?

**Comment by olivieryuyu** [comment]
Lemmy plugin is correct for this game and this specific issue, source is available

**Comment by olivieryuyu** [comment]
Rice avoid the issue by doing this:

 if( options.enableHackForGames == HACK_FOR_ALL_STAR_BASEBALL || 
    {
        t0u0 = (fS0 -tile0.fhilite_sl);
    }
    else
    {
        t0u0 = (fS0 * tile0.fShiftScaleS -tile0.fhilite_sl);

HACK_FOR_ALL_STAR_BASEBALL is to fix the texrec command issues, seems the texture handling is also affected

**Comment by olivieryuyu** [comment]
Now I cannot see any hack in Lemmy plugin for this game. Lemmy solved something?

**Comment by gonetz** [comment]
@olivieryuyu I've fixed issues #27, #128, #209
Since I'm not 100% sure that the fix is correct, I put it in a dev branch 'fix_texrect'.
It need to be tested for regressions.
Test binary:
https://drive.google.com/file/d/0B0YqMPjGo3B2MUVYWmRsMUNWYjg/view?usp=sharing

**Comment by olivieryuyu** [comment]
Sure will test!

**Comment by gonetz** [comment]
Thanks in advance

**Comment by olivieryuyu** [comment]
i tested a bunch of games.

So far on regression in california speed

![dfs](https://cloud.githubusercontent.com/assets/8987490/14328603/b1a6c9b8-fc37-11e5-91ee-9de38a0e8276.jpg)

**Comment by gonetz** [comment]
Thanks! I'll check them

**Comment by gonetz** [comment]
Fixed. Binary (mupen64plus only yet):
https://drive.google.com/file/d/0B0YqMPjGo3B2X1RpbmZvNnQ0U1k/view?usp=sharing

**Comment by olivieryuyu** [comment]
no new bug yet, one issue fixed: #207

**Comment by gonetz** [comment]
Good, thanks!

**Comment by olivieryuyu** [comment]
fixed

**Comment by olivieryuyu** [comment]
I reopen the issue as without hack, the texture in menu are incorrect. Let' see if we can still figure out the matter and fix it properly.

I noticed that the game when arriving in game actually uses G_MODIFYVTX immediate command. So I guess that the scale the texture are modified after being drawn. 

However I cannot see anything odd in the tex rec commands, they seems normally used. The game does not seems to use a custom microcode as well.

**Comment by olivieryuyu** [comment]
Halftexrec is not a hack. It is actually a normal behavior when G RDPHALF 1 is not in used.
