### ISSUE TITLE
toon panic: wrong texture in menu

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#270]
![1](https://cloud.githubusercontent.com/assets/8987490/6479821/a041d2e8-c24b-11e4-8417-253d861b974f.jpg)

**Comment by olivieryuyu** [comment]
should be

![2](https://cloud.githubusercontent.com/assets/8987490/6479822/a7a35250-c24b-11e4-92c4-4739f7348b44.jpg)

**Comment by gonetz** [comment]
Seems to be fixed in latest betas.

**Comment by Predator82Germany** [comment]
Can confirmm seems fixed with Mar19

**Comment by olivieryuyu** [comment]
fixed
