### ISSUE TITLE
Glitch in homebrew (Caribbean Nights)

### ISSUE THREAD

**Issue by Jj0YzL5nvJ** [gonetz/GLideN64#2700]
https://imgur.com/a/WAjdL1B

ROM: http://www.nesworld.com/article.php?system=n64&data=n64homebrew

**Comment by olivieryuyu** [comment]
idd, there is a bug. use fast3d ucode. RDP issue

**Comment by gonetz** [comment]
I finally found some time to check that problem.
The ucode in this game is strange. Its name is "RSP SW Version: 2.0G, 09-30-96"
That is, it is F3D ucode, which is used for example for SM64.
It indeed works as F3D, except for the lighting. Lighting works as F3DEX3, with point light use.
I didn't find, how to detect that properly. I added that rom to specialMicrocodes list, which is used to detect ucode by its checksum. It fixes the problem with lighting, but if another version of that rom exists, it may not work properly.
