### ISSUE TITLE
Black screen on Intel HD 4000 (Fedora Linux 36)

### ISSUE THREAD

**Issue by Jenmet-cy** [gonetz/GLideN64#2704]
Hi. I'm getting issues with GLideN64 in Rosalie's Mupen GUI on Linux (Fedora 36). Any game I open gives me a black screen with audio only. I'm using the latest GLideN64 version. Here's my gliden64.log, if it helps.
[gliden64.log](https://github.com/gonetz/GLideN64/files/9483758/gliden64.log)

**Comment by Jj0YzL5nvJ** [comment]
Try:
```
MESA_GL_VERSION_OVERRIDE="3.3COMPAT" MESA_GLSL_VERSION_OVERRIDE="330" MESA_EXTENSION_OVERRIDE="-GL_ARB_buffer_storage" ./RMG
```

**Comment by Jenmet-cy** [comment]
That worked! Thanks.
