### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by soopadoopacoopa** [gonetz/GLideN64#2713]
I set it
Multisample anti-aliasing (MSAA)
into 16x it cause my hp computer lag
what should i do
![lag issue](https://user-images.githubusercontent.com/66198303/195267766-a54c18c3-0853-4459-9e2e-5c80aa056cce.png)

**Comment by Wtab** [comment]
your computer is underpowered

**Comment by Xii-Nyth** [comment]
why on earth are you using 16x msaa at 1080p?

**Comment by gonetz** [comment]
16x MSAA is an overkill, but if the user sees it, it is supported by this hp pc.

> what should i do

Try to lower that setting. Also, make sure that the lag is not caused by GPU throttling:
https://nvidia.custhelp.com/app/answers/detail/a_id/3130/~/setting-power-management-mode-from-adaptive-to-maximum-performance
