### ISSUE TITLE
Pokemon Puzzle League graphics errors

### ISSUE THREAD

**Issue by xiartic** [gonetz/GLideN64#2725]
GLideN64 renders lines for the blocks even if you set "render 2d elements in native resolution". They're also very blurry.
![GLideN64_PUZZLE_LEAGUE_N64_000](https://user-images.githubusercontent.com/78692485/203112165-74ec7ba3-b861-4c6f-9f35-961c35c7e713.png)

Glide64 Final for comparison.
![Glide64__01](https://user-images.githubusercontent.com/78692485/203112299-427a3948-3aa0-4a37-81d1-50f9f14623c4.png)

After losing or winning the Pokeball doesn't spin like it's supposed to but only flashes between two frames with GLideN64.
![GLideN64_PUZZLE_LEAGUE_N64_001](https://user-images.githubusercontent.com/78692485/203112454-dc3297fc-184d-4ab0-a229-ea0bfc14cb51.png)

Glide64 Final does this properly.

![Glide64__02](https://user-images.githubusercontent.com/78692485/203112489-f46ece49-c717-4159-8b74-ff529065f6ed.png)

The text also has edges around them. Setting "try to remove colored halos around transparent objects" fixes it partially but that will break many other graphical elements.

**Comment by gonetz** [comment]
Pokemon Puzzle League is a pure 2D game. 2D graphics is hard to emulate correctly in high resolutions.
It is better to use 1x native resolution with try to remove colored halos around transparent objects" for this game. Antialiasing is also better to disable. Most of glitches will disappear.
![GLideN64_PUZZLE_LEAGUE_N64_000](https://user-images.githubusercontent.com/8983092/208290435-09ebd19a-66c3-480d-9b5d-05b4744a35b1.png)

**Comment by gonetz** [comment]
> After losing or winning the Pokeball doesn't spin like it's supposed to but only flashes between two frames with GLideN64.

Yes, I did not notice it before, thanks!

**Comment by gonetz** [comment]
> After losing or winning the Pokeball doesn't spin like it's supposed to but only flashes between two frames with GLideN64.

Fixed in c2c6561b7e
