### ISSUE TITLE
Feature request: Texture folder devloper options

### ISSUE THREAD

**Issue by Nes-player4Life** [gonetz/GLideN64#2729]
I was thinking the other day about how the plugin reads folders but not zips and how I often zip a folder up so the contents aren't loaded during editing.
Question is this; can a wildcard be made so any folder contents within a folder name are bypassed during load//reload of a pack.
Example: highres_/yourgamename/pac/foldernotreadname
This could be assigned to a simple key such as (~) or possibly userdefined.

**Comment by gonetz** [comment]
I'd like to avoid adding a new user option. I think a key like "~" is too simple. I suggest to use "~!~" as the escape prefix. It is unlikely that this prefix is used by any existing HD pack.
It is done in PR #2735. Add "~!~" to a folder name inside your HD pack and this folder will be skipped.

**Comment by Nes-player4Life** [comment]
Great news Thank you so much Gonetz. 
Can you belive GlideN64 is almost 10 years old now?

**Comment by gonetz** [comment]
> Great news Thank you so much Gonetz.

You welcome :)

> Can you belive GlideN64 is almost 10 years old now?

Yep. And it still has so many issues :(

**Comment by gonetz** [comment]
PR landed.
