### ISSUE TITLE
Tom and Jerry texture alignment issues.

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#273]
Here is one example..
![capture](https://cloud.githubusercontent.com/assets/9299743/6518520/f8c8bace-c35b-11e4-937f-53c4ea20fa1e.PNG)

PS this game looks amazing with mild bloom on and FSAAx4

**Comment by AmbientMalice** [comment]
I don't think this is a bug. Will likely be "fixed" when the 2D branch gets improved and merged. Also, native resolution.

**Comment by theboy181** [comment]
Fixed with default even. ;)
