### ISSUE TITLE
PD opening

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#2730]
https://github.com/ares-emulator/ares/pull/823/commits/25d49fc8bab40c4f7b70b3880faaf7723a964f77

fixed here

**Comment by Jj0YzL5nvJ** [comment]
If they are trying to create an emulator that fixes hardware defects, it should also show that screen after the reset and  run the game to 60fps.

Seriously, are they recreating EverDrive (or whatever) behaviors and throwing cartridges behaviors to the trash?

**Comment by olivieryuyu** [comment]
https://www.youtube.com/watch?v=a6Ee4VFp3OM

here capture on real n64

**Comment by olivieryuyu** [comment]
I have the same on my N64

**Comment by Jj0YzL5nvJ** [comment]
Nice Mandela Effect, that no happens in my hardware at boot. Only at restart.

Like here: https://youtu.be/MX_QoNfCNKY?t=52m51s

**Comment by Jj0YzL5nvJ** [comment]
Very similar to the [SM64 intro glitch](https://github.com/gonetz/GLideN64/issues/867), many people claim to see it on real hardware, others claim not to be able to reproduce it. I can't reproduce that glitch on my hardware, but I have seen it on other consoles. But usually on such consoles you can see similar glitches with all cartridges, not just SM64.

I have always attributed this difference to the fact that the owner removed the cartridge with the console on and ended up damaging a portion of the console's memory.

**Comment by gonetz** [comment]
Fixed with commit ff47414c2bd.
@olivieryuyu thanks for the link! It helped.

**Comment by gonetz** [comment]
> Nice Mandela Effect, that no happens in my hardware at boot. Only at restart.

I tested with Project64. It sends the necessary data right on the first run, without need to restart. The problem was in VI register data, when vEnd < vStart. The plugin treated that situation as an error and set screen height to zero, so nothing was rendered.

**Comment by olivieryuyu** [comment]
super :)
