### ISSUE TITLE
mupen64plus CLI: Fullscreen mode errors

### ISSUE THREAD

**Issue by GhostlyDark** [gonetz/GLideN64#2736]
Depending on the resolution of the mupen64plus window, the resizing in fullscreen mode fails.

**How to reproduce:**
Going into fullscreen from a 1600x1200 window works fine.
Maximizing the window first and then going into fullscreen doesn't resize the screen properly.
![image](https://user-images.githubusercontent.com/31742919/209436409-5d671003-675f-48c7-8e9c-825be7440a6e.png)

**The following errors are printed by GLideN64 (various resolutions tested):**
```
GLideN64/src/Graphics/OpenGLContext/mupen64plus/mupen64plus_DisplayWindow.cpp:211,ERROR, "Error setting videomode 1024x768 in fullscreen mode"
GLideN64/src/Graphics/OpenGLContext/mupen64plus/mupen64plus_DisplayWindow.cpp:211,ERROR, "Error setting videomode 1606x1251 in fullscreen mode"
GLideN64/src/Graphics/OpenGLContext/mupen64plus/mupen64plus_DisplayWindow.cpp:211,ERROR, "Error setting videomode 3840x2160 in fullscreen mode"
```

**The following errors are printed by mupen64plus-core:**
```
Core Error: VidExt_ResizeWindow() called in fullscreen mode
```

Angrylion-Plus and Parallel don't produce any core errors like shown above.

**Comment by gonetz** [comment]
I can't reproduce it on my PC.
I tested it with old version of mupen64plus (Jan 14 2019).
I set video general to 1600x1200, run a game, maximized the window and then switched to full-screen. No problems with video resize.

**Comment by GhostlyDark** [comment]
I should have specified: Using current master, not the latest release.

There are automated builds of the CLI version available here:
https://bitbucket.org/ecsv/mupen64plus-mxe-daily/downloads/
