### ISSUE TITLE
Glover (Background image problem)

### ISSUE THREAD

**Issue by roioros** [gonetz/GLideN64#2738]
There is a problem with "Glover", the background image is not displayed correctly using the latest version available ------> **GLideN64-7bbde56.**

I had also tried some previous versions and the same thing happened but in the **Public Release 4.0** this problem does not appear.

Here are some examples of what I'm talking about:

![GLideN64_Glover_000](https://user-images.githubusercontent.com/26861500/210006010-f0ee7877-8beb-495e-9908-e3288d518833.png)

Something interesting that I found is that if we activate the option that says "enable inaccurate texture coordinates" it improves a bit, but it still looks incorrect:

![GLideN64_Glover_001](https://user-images.githubusercontent.com/26861500/210006194-e60cec90-70cf-429e-a470-b997e6a961be.png)

**Comment by Nes-player4Life** [comment]
![image](https://user-images.githubusercontent.com/10325597/210120920-c4daab54-e897-4609-9824-b3f95d0cc1b1.png)
PR 4.0
Roioros is correct

**Comment by Jj0YzL5nvJ** [comment]
Looks good with **rsp-cxd4*** and **rsp-parallel** (LLE mode).

**Comment by roioros** [comment]
Is there a way to make it work correctly in HLE, like before?

Thanks.

**Comment by gonetz** [comment]
> Is there a way to make it work correctly in HLE, like before?
> 
> Thanks.

Yes. PR created.

**Comment by gonetz** [comment]
Note: regression commit is 7d237650ef34

It seems that Glover uses slightly different implementation of Sprite2D microcode.
Commit 7d237650ef34 improved Wipeout and Silicon Valley, but broke Glover.
Ucode description is the same for all three games: "RSP SW Version: 2.0H, 02-12-97"
May be @olivieryuyu find time to investigate it? It's not urgent. I just wonder, if the changes are deeper than just decrease of texture coordinates.

**Comment by roioros** [comment]
Fantastic, thank you so much [b]gonetz[/b] for the fix, you're great!

**Comment by gonetz** [comment]
PR landed. Ready for test.

**Comment by olivieryuyu** [comment]
i don't see differences at ucode level.

However you should be careful with the limitation of the Sprite microcode.

		_if (GBI.getMicrocodeType() == F3D_Glover) {
			lrs -= 1.0f;
			lrt -= 1.0f;
		}_

seems a bit this limitation:

These filtering conditions also mean that, when displaying a Y-scaled image, you will need to add 1 to the T value to prevent filtering of texels outside the range

http://n64devkit.square7.ch/n64man/ucode/gspSprite2D.htm

**Comment by olivieryuyu** [comment]
@gonetz 

see above

**Comment by gonetz** [comment]
> These filtering conditions also mean that, when displaying a Y-scaled image, you will need to add 1 to the T value to prevent filtering of texels outside the range

Very good note, thanks!
I corrected the fix.
