### ISSUE TITLE
Jeremy McGrath Supercross 2000: missing jauge line in menu

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#274]
![5](https://cloud.githubusercontent.com/assets/8987490/6532198/03913010-c43f-11e4-8c4f-1cbb059bc521.jpg)

**Comment by AmbientMalice** [comment]
Corrupt line graph shows up in LLE mode.

![jeremy_mcgrath_super-000](https://cloud.githubusercontent.com/assets/10704701/13836643/27743fde-ec4f-11e5-8a59-9c0e14e9694e.png)

**Comment by gonetz** [comment]
Fixed

**Comment by olivieryuyu** [comment]
closed
