### ISSUE TITLE
Zero/null rice CRC hash calculations on dumped textures

### ISSUE THREAD

**Issue by Luctaris** [gonetz/GLideN64#2747]
![image](https://user-images.githubusercontent.com/14159901/211684100-9fe70dd0-6beb-4510-acf0-8c1c3e570c21.png)
![image](https://user-images.githubusercontent.com/14159901/211684118-1933059d-d2ed-4d4a-8fc8-6eeba63ef683.png)
[Conker's Bad Fur Day Tx Bug.zip](https://github.com/gonetz/GLideN64/files/10387563/Conker.s.Bad.Fur.Day.Tx.Bug.zip)

The current implementation of the rice CRC algorithm rarely generates dumped textures that have both their texture and palette hash values set to 0.

Tested on master branch and US version of Conker's Bad fur day. I included a Mupen64Plus save state of the affected area.

**Comment by Squall-Leonhart** [comment]
the rice setting is for loading texture packs, nobody should be creating Rice format packs with gliden64.

**Comment by Luctaris** [comment]
That doesn't make sense... Why include a feature if it's not supposed to be used? If you're not supposed to be dumping/ripping raw textures using GLideN64, what alternative is there?

**Comment by Squall-Leonhart** [comment]
creating packs in a dead format makes less sense.

**Comment by TableGamer** [comment]
I may not be in the right spot for this but, how exactly does this work? I'm wanting to get the models and textures for Ocarina of time and Mejora's Mask.

**Comment by Luctaris** [comment]
> I may not be in the right spot for this but, how exactly does this work? I'm wanting to get the models and textures for Ocarina of time and Mejora's Mask.

You can dump textures pretty easily using GLideN64 by going into the plugin settings and enabling the dump texture option under the Texture Enhancement tab.

I don't believe that GLideN64 has a native method for dumping models, but there are other plugins particularly made to do that. I won't derail this issue thread by mentioning them, but a quick online search for dumping N64 models should list some methods.

Seeing as it's been over half a year since this issue was initially brought to attention and it having a really niche use-case, I'll go ahead and close this issue as stale for the time being.
