### ISSUE TITLE
lode runner: missing blending effect on texts

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#275]
![8](https://cloud.githubusercontent.com/assets/8987490/6534630/3a4112d8-c43f-11e4-9580-04740ad17ff8.jpg)

**Comment by gonetz** [comment]
Fixed

**Comment by Predator82Germany** [comment]
Got screen shake with (E) version

**Comment by gonetz** [comment]
screen shake is another issue. different issues should be in different bug reports, even when they are related to the same game.

**Comment by Predator82Germany** [comment]
Thought it were better here but ok I´ll add new issue

**Comment by Predator82Germany** [comment]
How should the effect look like
See only the same like on the image

**Comment by gonetz** [comment]
"Press start" text should glow. You may see it with Glide64 as well.

**Comment by Predator82Germany** [comment]
Did glow

**Comment by gonetz** [comment]
So, it is fixed :)

**Comment by olivieryuyu** [comment]
fixed
