### ISSUE TITLE
Banjo Kazooie and Banjo Tooie not working in LLE

### ISSUE THREAD

**Issue by Alexn64gamer0712** [gonetz/GLideN64#2750]
neither of those games are working in lle, tried Project64 last official release with default plugins

**Comment by gonetz** [comment]
What is Project64 default graphics plugin? Is It GLideN64?
I checked both Banjo's with mupen64plus and Project64 in LLE with GLideN64, they work.

**Comment by Alexn64gamer0712** [comment]
Hi gonetz thank you for your AWESOME work and quick reply : )  the problem is when I try GlideN64 (default lastest version on Project64) I make sure to check LLE but it hangs on start up showing like a tiny white circle and the sound keeps going and thats all :(  I even tried messing up with game config but nothing changed

**Comment by gonetz** [comment]
I checked Project64 4.0 nightly build. Yes, Banjo Kazooie and Banjo Tooie do not work in LLE mode.
It must be a core issue. I usually use old build of Project64: 2.4.0.228. This old build runs fine both Banjo games in LLE with current build of GLideN64. You may report zilmar about that regression.
