### ISSUE TITLE
Paper Mario lag when opening pause menu

### ISSUE THREAD

**Issue by Datounejr** [gonetz/GLideN64#2760]
So there's a small issue with Paper Mario : when pressing start, it takes 2 seconds to show the menu :

[HowItIs.webm](https://user-images.githubusercontent.com/28830991/220198575-02dad5c2-0f3b-4cc1-a827-3470aec950fd.webm)

Setting "Copy video card frame buffer to N64 memory" to asynchronous makes it worse :

[Asynchronous.webm](https://user-images.githubusercontent.com/28830991/220199176-76ef38ae-0352-492d-8ddf-ae929236185d.webm)

The menu should come up almost instantaneously, as with Angrylion :

[Angrylion.webm](https://user-images.githubusercontent.com/28830991/220199529-ae5d75c8-160d-4d3a-bae7-64bc19c94719.webm)

The problem is present on both OS I tried, Linux (Manjaro) and Android, and different versions of Mupen (RMG on PC, Mupen64Plus on Android)

Let me know if you need any info!

**Comment by Jj0YzL5nvJ** [comment]
If your GPU is NVIDIA, try with `Enable pixel coverage calculation`.

**Comment by Datounejr** [comment]
The issue is present regardless of the GPU, I get it on AMD, Nvidia, and Intel GPU on desktop.
On Android, it happens on both Nvidia and Mali GPU.

**Comment by gonetz** [comment]
PR created: #2762

**Comment by Rosalie241** [comment]
can confirm, that PR fixes the issue, thank you! :two_hearts:

**Comment by Datounejr** [comment]
Yep, fixed! Thank you so much Gonetz, you the bomb!

**Comment by gonetz** [comment]
Thanks for testing. PR merged into master branch.
