### ISSUE TITLE
Mario Golf issues with textures not loading wit FBE on.

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#277]
using copy FB to RDRAM leads to missing textures. I also notice that the FBE is using lower resolution screen capture when the screen fades to black or transitions to the next scene in the intro. You can see this most in the transition from the title screen when you start a game.

![capture](https://cloud.githubusercontent.com/assets/9299743/6542272/9c6f9114-c4a8-11e4-8342-ec440c87fc9e.PNG)

Lower resolution.

![capture](https://cloud.githubusercontent.com/assets/9299743/6542291/ea95fe5a-c4a8-11e4-87a1-94f608767075.PNG)

**Comment by theboy181** [comment]
Textures seem to be working better, but transitions still low resolution.

**Comment by gonetz** [comment]
Transition will always work in low-res in that game. Not all FB effects can be implemented with hardware buffers. That's why copy FB to RDRAM option is necessary. It copies hw buffer to RDRAM and allows game to use it as texture. Low-res is better than nothing.

**Comment by Predator82Germany** [comment]
Fixed with Mar19

**Comment by theboy181** [comment]
Looks good.
