### ISSUE TITLE
It can't run multiworld

### ISSUE THREAD

**Issue by Loganlanner1** [gonetz/GLideN64#2770]
I really want to play a multiworld randomizer

**Comment by gonetz** [comment]
As I can see, the author of that video https://www.youtube.com/watch?v=JNtqBCBnIaw
uses GLideN64, so it is possible.

**Comment by Loganlanner1** [comment]
It mobile

**Comment by GhostlyDark** [comment]
GLideN64 is just a graphics plugin - it won't handle the scripts that are required to run Multiworld.
That's something the emulator does.

Use either:
https://github.com/TestRunnerSRL/bizhawk-co-op/
https://github.com/midoshouse/ootr-multiworld

The latter also supporting Project64, which works with latest GLideN64.

**Comment by gonetz** [comment]
@GhostlyDark thanks!
