### ISSUE TITLE
screenshotting in widescreen fullscreen make screenshots look like shit

### ISSUE THREAD

**Issue by Swim-Swim-Hungry** [gonetz/GLideN64#2771]
clearly not intentional
![GLideN64_SUPER_MARIO_64_000](https://user-images.githubusercontent.com/117381694/229250924-4d2fc9de-c8f6-4851-b014-ac0f72a8190e.png)

**Comment by Swim-Swim-Hungry** [comment]
screenshots of my gliden64 configurations if this helps at all
![image](https://user-images.githubusercontent.com/117381694/229251104-c3c8bc59-a498-4462-be13-6c7a650485e4.png)
![image](https://user-images.githubusercontent.com/117381694/229251166-11f03137-5642-46d9-bf25-fb0e22631566.png)
![image](https://user-images.githubusercontent.com/117381694/229251185-a8786afd-b48d-442a-8386-cc37561a40fa.png)
![image](https://user-images.githubusercontent.com/117381694/229251206-52ded911-c9ba-4df2-80ce-629836f8608d.png)
![image](https://user-images.githubusercontent.com/117381694/229251263-0f0ef4b5-6324-40fa-afc5-cde0d42d33a4.png)

**Comment by Swim-Swim-Hungry** [comment]
fixed by not using the output resolution as the internal resolution
![GLideN64_SUPER_MARIO_64_001](https://user-images.githubusercontent.com/117381694/229251612-fd53e141-5059-45fd-aebb-a70c3182da47.png)

**Comment by Swim-Swim-Hungry** [comment]
not actually output resolution, screenshotting in fullscreen cause this artifact

**Comment by gonetz** [comment]
I can't reproduce that error on my PC.
As I remember, the problem as on your first screen shot appeared when screen width or height was not even.
Current version just crashes when you are taking screen shot from a screen with odd size.

**Comment by Xii-Nyth** [comment]
off topic of glide but on topic to screenshots:
I recomend just using reshade to take screenshots, all emulators/screenshot tools have problems with exclusive fullscreen applications

**Comment by Swim-Swim-Hungry** [comment]
> off topic of glide but on topic to screenshots: I recomend just using reshade to take screenshots, all emulators/screenshot tools have problems with exclusive fullscreen applications

mhm

**Comment by Xii-Nyth** [comment]
well at least we got this hilarious picture of dk out of this
![image](https://github.com/gonetz/GLideN64/assets/101597311/fd92eb3b-5570-41d7-b8ed-db1766f8d5be)
