### ISSUE TITLE
Regression

### ISSUE THREAD

**Issue by master1274** [gonetz/GLideN64#2781]
-![Img_2023-06-12_013302](https://github.com/gonetz/GLideN64/assets/20639709/3f176f9d-3fb3-472e-a88f-c19ee72aa717)
A very old regression. Completely broken image emulation in Gex 3 - Deep Cover Gecko (U). On any Android devices ARM 32-bit (armeabi-v7a). Apparently this problem is related to the dynamic recompiler. In cached mode, the image is emulated, but of course slowly. Apparently the problem appeared in 2021. I have not been able to set the exact date. I was able to understand that this game is being emulated on core Parallel in RetoArch (last core update in 2020). I also managed to find the old version core Mupen64Plus - Next GLES3 for RetroArch. The release date is unknown to me. It was built into the emulator Lemuroid v1.7.1. Having launched it in RetroArch, I found out that there was no problem on it. In the screenshot, the version of the core on which there is no problem

**Comment by master1274** [comment]
https://github.com/mupen64plus-ae/mupen64plus-ae/issues/1110
There I described the problems to the developer M64Plus FZ in detail (video links have already been deleted)

**Comment by master1274** [comment]
I forgot to mention that the problem is not observed on Android ARM64 devices. Only on ARM7

**Comment by gonetz** [comment]
> Apparently this problem is related to the dynamic recompiler.

Then it should be fixed in the core:
https://github.com/mupen64plus/mupen64plus-core/issues/1024
