### ISSUE TITLE
Goldeneye ammo display bug

### ISSUE THREAD

**Issue by Frank-74** [gonetz/GLideN64#2786]
Only happens on a few levels.  If I'm windowed and click into fullscreen it appears normal again.  If it happens in fullscreen and click into windowed it also fixes itself.  Edit:  Using latest GLideN64 master WTL build and latest Project64 Dev4 build.
![GLideN64_GOLDENEYE_001](https://github.com/gonetz/GLideN64/assets/11056843/9fe3dd1a-eb42-43a9-9671-6f143730c911)

**Comment by oddMLan** [comment]
Hey @Frank-74 welcome back! Long time no see. How are you doing? Come say hi on Discord64 when you get a chance.

**Comment by Frank-74** [comment]
> Hey @Frank-74 welcome back! Long time no see. How are you doing? Come say hi on Discord64 when you get a chance.

Hi there, I'm on Project64's discord, can't find a channel called Discord64, do you have an invite link?

**Comment by oddMLan** [comment]
https://discord.gg/sSkQTBpFhv

**Comment by Frank-74** [comment]
Switching Copy video card depth buffer to N64 to Never fixes it.
