### ISSUE TITLE
The Invisible Cap effect of the Spuer Mario 64 is not displayed normally

### ISSUE THREAD

**Issue by Walker-BJ99** [gonetz/GLideN64#2787]
![image](https://github.com/gonetz/GLideN64/assets/75510566/6da01399-a34d-4813-b6b4-dcda707aca19)

As you can see, I don't know anything about emulators and plugins, so I can't provide more information.

Emulator is Project64 3.0.1.5664-2df3434, Plugin is GLideN64 rev.0fee30d.

**Comment by gonetz** [comment]
As I can see, it works properly.
It works the same with AL RDP plugin, which is most accurate graphics plugin:
![SM64-AL](https://github.com/gonetz/GLideN64/assets/8983092/bc522f95-1e4d-4c3b-aec0-b8bd3ac07169)
GlideN64:
![SM64-GLideN64](https://github.com/gonetz/GLideN64/assets/8983092/eb518125-fcc4-49b9-9fe4-7f1af3d00915)
