### ISSUE TITLE
Mariokart 64: Sky texture

### ISSUE THREAD

**Issue by Nes-player4Life** [gonetz/GLideN64#279]
![mk64 issue](https://cloud.githubusercontent.com/assets/10325597/6548079/c321e19c-c5c3-11e4-8c4f-3a55e2d1e341.jpg)

**Comment by Predator82Germany** [comment]
Same as in #243 said, could merged

**Comment by gonetz** [comment]
Please test with latest build

**Comment by Predator82Germany** [comment]
Fixed with Mar19

**Comment by gonetz** [comment]
Nes-player4Life, please test and close.

**Comment by Predator82Germany** [comment]
Now I´ve tested PAL 1,0 & 1.1, NTSC-J 1.0 & 1.1, NTSC-U
This issue seems away

**Comment by gonetz** [comment]
Thanks!

**Comment by olivieryuyu** [comment]
then please close the issue!

**Comment by Nes-player4Life** [comment]
Sorry for the delay 
/Resolved 
![mk64 issue resolved](https://cloud.githubusercontent.com/assets/10325597/6772041/c7b18932-d0c8-11e4-9f1c-aa1d201d5dd6.jpg)
