### ISSUE TITLE
Public Release 5

### ISSUE THREAD

**Issue by ShalokShalom** [gonetz/GLideN64#2793]
Hi there :) 

I see a lot of commits, and no release for 4 years: Is this on purpose? Do you generall advice to build from git now (similar than Dolphin did for years) or is a new release just delayed a lot?

Thanks 👍🏻

**Comment by Jj0YzL5nvJ** [comment]
#2516

P.S: [The current WIP is very good](https://github.com/gonetz/GLideN64/releases/tag/github-actions)

**Comment by ShalokShalom** [comment]
I swear I looked it up, if there was already an open issue :D 

Thanks and great!
