### ISSUE TITLE
GlideN64 NEW ADD

### ISSUE THREAD

**Issue by forz0i** [gonetz/GLideN64#2796]
HI  foe all program 
Plase add 3DFX  (glide3x.dll) to  projecet Glide N64 plugin 
3DFX  glide3x.dll   [dgVoodoo v2.81.1
http://dege.freeweb.hu/dgVoodoo2/bin/dgVoodoo2_81_1.zip)  - for regular usage (released: 2023.07.24)
GlideN64 & 3DFX  best  plugin For  projecet N64
THX for all projecet  GlideN64 plugin

**Comment by Jj0YzL5nvJ** [comment]
`Glide64` ≠ `GLideN64` ≠ `glN64`

**Comment by plasticalligator** [comment]
![image](https://github.com/gonetz/GLideN64/assets/16845709/ce6fd590-d505-4cea-a45c-57640b130f2e)

**Comment by forz0i** [comment]
> Squall
Glide64 Final (10th Anniversary) r282
The ultimate version of Glide64 (created by Gonetz) which is the best graphics plugin for 3DFX based maps. As a reminder, it uses the glide wrapper Glitch64 from Hacktarux and the GlideHQ module (allowing to display textures in high resolutions) from KoolSmoky. It follows directly on Glide64 Napalm WX' Release 1.1 and integrates all the improvements of recent years for the three modules (glide64, glitch64, glideHQ)

**Comment by Squall-Leonhart** [comment]
**Glide_N_64 doesn't use a wrapper.**

**Comment by Jj0YzL5nvJ** [comment]
"Gliden64 Final" requires a bunch of hacks on PJ64 1.6/2.x to work correctly. No current N64 emulator uses it.

@gonetz no longer gives support to Glide64 (Glide API) in any form. This repository is for **GL**ide**N**64 (OpenGL 3.3/4.x API, GLES2/3 API).

The only people interested in continuing to use "Glide64" forks are those who use Raspberry Pi and old versions of Android. And as far as I know, no Glide64 fork requires the wrapper.

**Comment by forz0i** [comment]
i talk for glide64  version PC   render 3d   by direcetx   version glide64 is posible run 3dfx for version PC
version Android  = openal 3.3....
possible add option 3dfx for version PC

**Comment by Squall-Leonhart** [comment]
Ce référentiel ne contient aucun développement pour Glide64

**Comment by weinerschnitzel** [comment]
Oh man. I want to be helpful but I don't know where to begin.

**Comment by forz0i** [comment]
The glide final  2012  possible app date to run old vidéo plugin for
project 64  moderne 2023 version ?

Le dim. 12 nov. 2023 à 08:12, Sergey Lipskiy ***@***.***> a
écrit :
