### ISSUE TITLE
PD garbled text [Linux]

### ISSUE THREAD

**Issue by V1del** [gonetz/GLideN64#280]
PD has garbled text under Linux with Nvidia proprietary drivers

![perfect_dark-001](https://cloud.githubusercontent.com/assets/7619751/6583819/036aad0c-c767-11e4-8e0f-9580dddc4883.png)

OS: Arch Linux x64 Kernel 3.18.6
Mupenversion: mupen64plus/mupen64plus-core@c536bb053ceaa320d75ff67b3cb7a7bbb39072b5 (Standard plugins with versions from that timeframe)
GLideN64: Week 22

glxinfo:
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GT 640/PCIe/SSE2
OpenGL core profile version string: 4.4.0 NVIDIA 346.47
OpenGL core profile shading language version string: 4.40 NVIDIA via Cg compiler
OpenGL version string: 4.5.0 NVIDIA 346.47
OpenGL shading language version string: 4.50 NVIDIA

**Comment by matthewharvey** [comment]
This is happening for me too on the following system:
Debian 9 (testing)
Linux kernel 4.1
Intel HD4000 using Mesa (OpenGL 3.3)
Latest git versions of mupen64plus and GLideN64

**Comment by rockaddicted** [comment]
Hello on rapsberry pi 2 too we have this problem.

**Comment by gonetz** [comment]
Fixed
