### ISSUE TITLE
[Bug] TxHiResNoCache doesn't work for games with colon :

### ISSUE THREAD

**Issue by GhostlyDark** [gonetz/GLideN64#2807]
Using TxHiResNoCache doesn't work with games that contain a colon `:` in the internal ROM Name.
In my recent use case: `Turok 3: Shadow of O`

**Workaround:**
Let GLideN64 generate HTC/HTS cache instead or replace `:` with `-` via hex editing.

**Comment by gonetz** [comment]
Fixed. The name of folder with Hires textures should be the same as name of folder with dumped textures. In case of Turok 3 - Shadow of Oblivion it should be `Turok 3- Shadow of O`, because ':' in the internal name is replaced by '-'
