### ISSUE TITLE
[Glitch][Android] Famista64 : Background become bluescreen.

Please see attached movie.

### ISSUE THREAD

**Issue by nassau-tk** [gonetz/GLideN64#2808]
https://github.com/gonetz/GLideN64/assets/48179091/1a1d7ec4-fa71-467b-a4df-bff4d937e964

It should draw like below.

![Screenshot_20231231-010007.png](https://github.com/gonetz/GLideN64/assets/48179091/d815377b-d952-4089-b5f0-b4269f45d347)
※Software rendering / Angrylion

**Comment by gonetz** [comment]
It seems to be Android-specific. Maybe even device-specific. Windows version looks correct:
![GLideN64_Ì§Ð½À_64_003](https://github.com/gonetz/GLideN64/assets/8983092/86098960-c044-4979-a068-ffd903aad35e)
I don't maintain Android builds. If you use M64Plus FZ, try to ask @fzurita.

**Comment by nassau-tk** [comment]
OK.
@fzurita said to me that report here.

So, l close this topic.

thx!!

**Comment by fzurita** [comment]
Well, I think it's good to have the issue here. Yeah, I have maintained the Android builds, but it's still an issue that should be fixed in this repo.

**Comment by Jj0YzL5nvJ** [comment]
Sorry if I sound tiresome, but I still think that implementing support for [ANGLE](https://en.wikipedia.org/wiki/ANGLE_(software)) could help catch bugs on GLES. I have a suspicion that the OpenGL 3.3 problems with old NVIDIA drivers (#2507, #2656) are actually GLES2 problems in NVIDIA's own _**ANGLE-like**_ layer.

I seem to remember that **ANGLE** can expose `fragment shader interlock` on virtually any device... doesn't that sound tempting enough?

See: https://github.com/libretro/mupen64plus-libretro-nx/compare/develop...angle

**Comment by nassau-tk** [comment]
This issue happen on Retroarch.
