### ISSUE TITLE
Feature Request: Add video Options from VICE?

### ISSUE THREAD

**Issue by xga-cga** [gonetz/GLideN64#2814]
Could you or someone add video options from vice emulator to PJ64, like CRT settings or add it to this plugin?  https://vice-emu.sourceforge.io/
https://www.youtube.com/shorts/ssOZLUHBB9E like this.  Was able to use a commodore amiga monitor with an snes and it was nice, but eventually started to fail and to my knowledge only had 256 color and only had non-rgb.

**Comment by gonetz** [comment]
This is a way too specific request. I doubt that someone will take it.

**Comment by xga-cga** [comment]
ok and gizmo someone commented on post 2780 about already making a CRT filter.
here is info about Amiga, https://blog.johnnovak.net/2022/04/15/achieving-period-correct-graphics-in-personal-computer-emulators-part-1-the-amiga/
found the project CRTsim that looks fun/simple...
https://github.com/MinorKeyGames/CRTSim/tree/master/CRTSim
agreed it looks like the wrong place/time to ask.  thanks for feedback, closing.
