### ISSUE TITLE
Garbled or old textures in blank screens with FBE [Linux]

### ISSUE THREAD

**Issue by V1del** [gonetz/GLideN64#282]
Blank screens or borders can contain garbled textures and/or textures from previously opened games when FBE is enabled. Actual gameplay is unaffected (except from crazy flashing which can occur if the corrupted textures reside in a border area which doesn't get refreshed). Disabling FBE seems to fix this, so might be a suitable workaround for games that don't need them.

![smash_brothers-000](https://cloud.githubusercontent.com/assets/7619751/6585553/dca7cc98-c772-11e4-8a99-fe898b26f94d.png)

Contrary to what one might think, this isn't Perfect Dark going crazy but the transition from F-Zero's intro guitar to the menu screen :stuck_out_tongue:
![f-zero_x-000](https://cloud.githubusercontent.com/assets/7619751/6585634/7a9a05c4-c773-11e4-8c07-4bd0cc66df4a.png)

OS: Arch Linux x64 Kernel 3.18.6
Mupenversion: mupen64plus/mupen64plus-core@c536bb053ceaa320d75ff67b3cb7a7bbb39072b5 (Standard plugins with versions from that timeframe)
GLideN64: Week 22

glxinfo:
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GT 640/PCIe/SSE2
OpenGL core profile version string: 4.4.0 NVIDIA 346.47
OpenGL core profile shading language version string: 4.40 NVIDIA via Cg compiler
OpenGL version string: 4.5.0 NVIDIA 346.47
OpenGL shading language version string: 4.50 NVIDIA

**Comment by Mushman** [comment]
This isn't a Linux exclusive issue, and can even be encountered with Frame Buffer Emulation off. In fact, I'm pretty sure I've seen other plugins make similar artifacts. It's most common in the display's inactive or overscan areas. This behaviour is sort of like the [hall of mirrors effect in Doom](http://doom.wikia.com/wiki/Hall_of_mirrors_effect#Shimmering_effect). Mupen64Plus's OSD can often create the effect.

**Comment by V1del** [comment]
Yeah I know that the OSD can create the effect but that has nothing to do with the used plugin but rather how the OSD injects itself into the buffer. The issue as specified here is only present on linux and only with FBE on

**Comment by V1del** [comment]
Found some resources that suggest some uninitialized OpenGL buffers could be the cause of this issue: http://blog.lxgr.net/posts/2013/05/20/uninitialized-buffers-in-opengl/ https://hsmr.cc/palinopsia/

**Comment by 7oxicshadow** [comment]
I have only tested this in linux....

If you run in windowed mode and load goldeneye, select the dam level BUT do no press next to load it. Instead goto a web browser and start cycling through any random web page(s) then go back to goldeneye and press next to start loading the level you will see a large amount of content from your web browser being displayed in game.

**Comment by 7oxicshadow** [comment]
![corruption](https://cloud.githubusercontent.com/assets/10350138/7784803/cfef9aee-016a-11e5-85a6-012f44d2886a.jpg)

**Comment by matthewharvey** [comment]
Which window manager are you using?
I can't reproduce this using Gnome3 on Debian 9 with kernel 4.1 and the Intel Mesa graphics drivers.
With buffers being filled with garbage, it could be the fault of the window manager, or the graphics driver possibly.

**Comment by 7oxicshadow** [comment]
Fedora 22
Kernel 4.1.10-200
Gnome 3
Nvidia propitiatory drivers. (GTX770)

I will try to replicate again to confirm that the latest version still has the issue.

**Comment by gonetz** [comment]
Fixed for me. Please reopen, if the problem is still here.
