### ISSUE TITLE
Goldeneye missing textures on weapons. [Linux]

### ISSUE THREAD

**Issue by V1del** [gonetz/GLideN64#283]
Some weapons are missing textures, not entirely sure if this one is exclusively on linux, maybe I or someone else can verify later
![goldeneye-000](https://cloud.githubusercontent.com/assets/7619751/6585718/2b5d5078-c774-11e4-905f-55a9c250b18c.png)

OS: Arch Linux x64 Kernel 3.18.6
Mupenversion: mupen64plus/mupen64plus-core@c536bb053ceaa320d75ff67b3cb7a7bbb39072b5 (Standard plugins with versions from that timeframe)
GLideN64: Week 22

glxinfo:
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GT 640/PCIe/SSE2
OpenGL core profile version string: 4.4.0 NVIDIA 346.47
OpenGL core profile shading language version string: 4.40 NVIDIA via Cg compiler
OpenGL version string: 4.5.0 NVIDIA 346.47
OpenGL shading language version string: 4.50 NVIDIA

**Comment by olivieryuyu** [comment]
enableignorecfb option may be the issue. please try to see the difference with and without

**Comment by olivieryuyu** [comment]
may be fixed with last version?

**Comment by Mushman** [comment]
Just tested. It's fixed.

**Comment by olivieryuyu** [comment]
please close the ticket thx!

**Comment by V1del** [comment]
This definitely still happens with the early release build on Linux so keeping it open for now

**Comment by gonetz** [comment]
I've installed Ubuntu as the second OS on my PC, so now I'm able to test that bug. It would be great if you could provide me with a savestate for that problem.

**Comment by Mushman** [comment]
Looks like you just need to get a KF7 Soviet, which you can get from the first guard in Dam, the first level. Is that right @V1del?

**Comment by V1del** [comment]
@Mushman Yeah that's correct but here's a state anyway

https://drive.google.com/file/d/0BxKSInX_4lqZR0tJcXowZmtjQkE/view?usp=sharing

**Comment by matthewharvey** [comment]
Fixed with 53203c048ab3b74b26ec7c7297fd08a623a565ba
