### ISSUE TITLE
Goldeneye - Textures

### ISSUE THREAD

**Issue by baptiste0602** [gonetz/GLideN64#284]
I don't know if it's a bug, but the textures looks weird in Goldeneye

Gliden64 (week23) => default settings :
![image](https://cloud.githubusercontent.com/assets/11183826/6586215/2d62156c-c778-11e4-8a0f-3988d4d0b7e1.png)

In comparaison, Glide64 Final (8 May 2012) :
![image](https://cloud.githubusercontent.com/assets/11183826/6586259/8091b62a-c778-11e4-9d44-183f34fd7095.png)

**Comment by gonetz** [comment]
I see nothing weird. Texture details reduced with distance. It is normal work of mip-mapping mechanism, which is not implemented in Glide64 or any other plugin with hardware rendering. Please compare with software lle plugin or with real console.

You may disable mip-mapping emulation, just uncheck "emulate LOD" option.

**Comment by baptiste0602** [comment]
Ok thanks for the explanation and sorry for the bad report...
