### ISSUE TITLE
CBFD: broken

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#2845]
![GLideN64_CONKER_BFD_011](https://github.com/gonetz/GLideN64/assets/8987490/ebf77ee1-170c-4a23-bd07-a64bc8490ff9)

**Comment by Jj0YzL5nvJ** [comment]
I can't reproduce on [RMG](https://github.com/Rosalie241/RMG/releases/latest)...

**Comment by olivieryuyu** [comment]
Due to the very last commit

https://github.com/gonetz/GLideN64/commit/85bdd452d7090f78a0f76d02121fa59ad079b7f6

**Comment by Jj0YzL5nvJ** [comment]
Yes, 4972e76aea6b327959d1761c786077fd96b6cb30 works perfectly fine.

**Comment by gonetz** [comment]
> Due to the very last commit
> 
> [85bdd45](https://github.com/gonetz/GLideN64/commit/85bdd452d7090f78a0f76d02121fa59ad079b7f6)

Yes, it's my mistake.
I reverted the wrong fix and added a proper (hopefully) one: https://github.com/gonetz/GLideN64/commit/f119c320f9106d7b452d0a1e7b79e1c3e3cee9b1
