### ISSUE TITLE
Superbowling broken

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#2846]
![GLideN64_SUPER_BOWLING_001](https://github.com/gonetz/GLideN64/assets/8987490/5e14e9c5-128f-42bb-bbf2-c574b6eb34a0)

**Comment by gonetz** [comment]
Confirmed.

**Comment by gonetz** [comment]
Fixed.

**Comment by olivieryuyu** [comment]
Super :)
