### ISSUE TITLE
Perfect Dark - Crash after intro with Copy depth buffer to RDRAM

### ISSUE THREAD

**Issue by baptiste0602** [gonetz/GLideN64#285]
With week 23 build, PD crash after intro (just before the first menu) when "Copy depth buffer to RDRAM" is enabled. It doesn't happen in week 22 build.

tested with Project64 2.2.0.1 and mupen64plus

My config:
- Windows 8.1
- Intel Core i7-3770 CPU @ 3.40GHz
- NVIDIA GeForce GTX 670 (with Nvidia drivers 347.52)

**Comment by gonetz** [comment]
Fixed.

**Comment by baptiste0602** [comment]
I confirm, thanks !
