### ISSUE TITLE
Pokemon Puzzle 3D puzzle issue

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#2852]
![](https://user-images.githubusercontent.com/7278372/68204466-5008d480-ff85-11e9-9ea3-56b70f0c9e02.png)

[Pokemon.Puzzle.League.U.pj.zip](https://github.com/user-attachments/files/15855369/Pokemon.Puzzle.League.U.pj.zip)

Works with our good Glide64

![Glide64_PUZZLE_LEAGUE_N64_01](https://github.com/gonetz/GLideN64/assets/8987490/fb4673a3-bc91-48a0-8dc8-496d0d71b2b8)

**Comment by gonetz** [comment]
Some fb effect works incorrect.

> Works with our good Glide64

Part of graphics is missing with it too.

**Comment by gonetz** [comment]
> Some fb effect works incorrect.

I found a very old fb-emulation related bug. It hid very well; I spent several days on it.
The problem should be fixed now.
