### ISSUE TITLE
[Feature Request] Fix the 'borderless fullscreen' option

### ISSUE THREAD

**Issue by duke912** [gonetz/GLideN64#2864]
The borderless fullscreen, available only in PJ64, simply does nothing, it renders at exclusive fullscreen and some programs, like Lossless Scaling, does not work with it. Please fix it

**Comment by GhostlyDark** [comment]
> Should be fixed with commit [24f7f47](https://github.com/gonetz/GLideN64/commit/24f7f47cad6f00d0d851acf683b79ff5ed98da71).

I think you meant to reference 7294f02.

**Comment by duke912** [comment]
> > Should be fixed with commit [24f7f47](https://github.com/gonetz/GLideN64/commit/24f7f47cad6f00d0d851acf683b79ff5ed98da71).
> 
> I think you meant to reference [7294f02](https://github.com/gonetz/GLideN64/commit/7294f02b0062cd2696efeb3078bc81cc91a48c4c).

Tested with both PJ 3.0.1 and latest dev version and get the same results as before, no difference from exclusive fullscreen, Lossless Scaling only works if it's in window mode

**Comment by gonetz** [comment]
> I think you meant to reference [7294f02](https://github.com/gonetz/GLideN64/commit/7294f02b0062cd2696efeb3078bc81cc91a48c4c)

Yes, thanks

**Comment by gonetz** [comment]
> Tested with both PJ 3.0.1 and latest dev version and get the same results as before, no difference from exclusive fullscreen, Lossless Scaling only works if it's in window mode

What is "Lossless Scaling"?

**Comment by gonetz** [comment]
Well, I agree, it is still not a true borderless fullscreen windowed mode. With "borderless mode" the plugin switches to fullscreen instantly and it uses desktop refresh rate, so I thought it worked properly. However, when in windowed mode, "win+r" should not change window size, but it does.

**Comment by duke912** [comment]
> > Tested with both PJ 3.0.1 and latest dev version and get the same results as before, no difference from exclusive fullscreen, Lossless Scaling only works if it's in window mode
> 
> What is "Lossless Scaling"?

A software that comes with a 'frame generation', it creates an overlay that does its 'magic', at the cost of some input lag. The problem is that the game must be running at window mode/borderless fullcreen for it to work, wanna try on some old 30fps locked games.

**Comment by gonetz** [comment]
@duke912 I tested this feature again. As I understand, if the app in OpenGL Non-exclusive Fullscreen Mode (A.K.A. Fullscreen Borderless Window), then it remains full-screen when you press alt-tab or win-r. You can switch to some other app with alt-tab, but your app will still run full-screen and the new app will be on top of it.
For example, yuzu works like this in OpenGL fullscreen borderless mode. But it is not the case, when I use GLideN64 with old versions of Project64, e.g. Project64 2.3
I tried recent release build "Project64 3.0.1.5664" and GLideN64 borderless mode works correct with it. I see no difference with yuzu. I even installed "Lossless Scaling" and it works for me too. Scenario: run a game with Project64, run Lossless Scaling (LS), switch GLideN64 to borderless fullcreen, alt-tab to LS, click "Scale", alt-tab to GLideN64. After 5 sec the screen will blink once and LS FPS counter will appear, if you enabled it.

So, please try the recent GLideN64 (I made a small fix a moment ago) with recent Project64 build.

Important notices:
* switching back to windowed mode may work incorrect when Lossless Scaling is enabled. You need to unscale the window first.
* If you switch between exclusive fullscreen and borderless fullscreen in the config dialog, you may need to restart emulator for taking effect of this change.

**Comment by duke912** [comment]
> @duke912 I tested this feature again. As I understand, if the app in OpenGL Non-exclusive Fullscreen Mode (A.K.A. Fullscreen Borderless Window), then it remains full-screen when you press alt-tab or win-r. You can switch to some other app with alt-tab, but your app will still run full-screen and the new app will be on top of it. For example, yuzu works like this in OpenGL fullscreen borderless mode. But it is not the case, when I use GLideN64 with old versions of Project64, e.g. Project64 2.3 I tried recent release build "Project64 3.0.1.5664" and GLideN64 borderless mode works correct with it. I see no difference with yuzu. I even installed "Lossless Scaling" and it works for me too. Scenario: run a game with Project64, run Lossless Scaling (LS), switch GLideN64 to borderless fullcreen, alt-tab to LS, click "Scale", alt-tab to GLideN64. After 5 sec the screen will blink once and LS FPS counter will appear, if you enabled it.
> 
> I also tried to capture fullscreen window with OBS. It works as well.
> 
> So, please try the recent GLideN64 (I made a small fix a moment ago) with recent Project64 build.
> 
> Important notices:
> 
> * switching back to windowed mode may work incorrect when Lossless Scaling is enabled. You need to unscale the window first.
> * If you switch between exclusive fullscreen and borderless fullscreen in the config dialog, you may need to restart emulator for taking effect of this change.

Just tested some games and it's working as it should, both 3.0.1 and latest dev version

**Comment by gonetz** [comment]
> Just tested some games and it's working as it should, both 3.0.1 and latest dev version

Good. Can we close the issue then?

**Comment by duke912** [comment]
> > Just tested some games and it's working as it should, both 3.0.1 and latest dev version
> 
> Good. Can we close the issue then?

Yes
