### ISSUE TITLE
Lode Runner 3-D vertical stretch

### ISSUE THREAD

**Issue by MusicMantis** [gonetz/GLideN64#2865]
Lode Runner 3-D has its output stretched vertically. As a result, the bottom half of the screen is cut off.
Here is an example of the Nintendo 64 logo that appears when you boot up the game:
![image](https://github.com/user-attachments/assets/9e86daab-0aad-4cba-95cd-3baca5f0a8bd)

I did try a few different things to improve the situation and learned some things:
1) If you disable frame buffer emulation, you can see the logo display correctly (though this breaks many other things).
2) Forcing the aspect ratio to 16:9 improves the situation with less vertical stretch, cutting off less of the screen as a result. A significant portion of the screen is still missing though.

I suspect this could be related to the fact the game has interlaced output. In the past this game has had some motion jitter (shaking up and down) in GLideN64 too. That problem has been long fixed, but I suspect interlaced output may have also been the cause of that.

Thank you for your help!

**Comment by gonetz** [comment]
Hmm, the problem with incorrect aspect in this game was fixed long ago.
I checked all three versions of this rom, (J), (U), (E) and all three look correct.
Screen shot from (E) version, 50 VI/S:
![GLideN64_Lode_Runner_3D_001](https://github.com/user-attachments/assets/957b3805-cef1-49ed-a01f-e938ca250f28)

**Comment by MusicMantis** [comment]
> Hmm, the problem with incorrect aspect in this game was fixed long ago. I checked all three versions of this rom, (J), (U), (E) and all three look correct. Screen shot from (E) version, 50 VI/S: ![GLideN64_Lode_Runner_3D_001](https://private-user-images.githubusercontent.com/8983092/378159499-957b3805-cef1-49ed-a01f-e938ca250f28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MDc4MjksIm5iZiI6MTcyOTQwNzUyOSwicGF0aCI6Ii84OTgzMDkyLzM3ODE1OTQ5OS05NTdiMzgwNS1jZWYxLTQ5ZWQtYTAxZi1lOTM4Y2EyNTBmMjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMDY1ODQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2U0ODMzYTQ2ZTU0M2E2YTI3YTkzYmZmMTc0YWUxZTI4YjhkNmQzZGJlMTQ0YjljZDkyZWFiN2Q1NWUyOTExMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.MUPsoly3g4FEzzche39fns876FNhsbBNmi1AmLjMDhw)

I originally tested using build 89b06f8 (the last commit in August) and the (U) version of the game. I checked again to be sure and the problem is indeed present there.

I tested again using the build a1320da (the latest at my time of replying) and you are correct. The issue has been resolved.

I'm leaving this information here in case it is useful to you or anyone else, as it seems that solution to the problem is in that range of commits, but the problem has indeed been fixed. Thank you!
