### ISSUE TITLE
Waialae Country Club: fb not handled correctly - depth with shadows + map

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#287]
![better](https://cloud.githubusercontent.com/assets/8987490/6764090/8a034956-cf9f-11e4-876e-84f31788067e.jpg)
![sfddsf](https://cloud.githubusercontent.com/assets/8987490/6764091/8cfacb66-cf9f-11e4-8665-f9aadd26adcc.jpg)

**Comment by gonetz** [comment]
As I see, only depth problem with players shadows left.

**Comment by olivieryuyu** [comment]
issue updated

if you do a shoot you will see the first screen

if you move the player around the shadows a passing through the player.

But it is now better

**Comment by olivieryuyu** [comment]
issue with the map is back: it is now cut in half!

![sans titre](https://cloud.githubusercontent.com/assets/8987490/18699029/c5061e9e-7fce-11e6-9408-ed69e9be975a.jpg)

**Comment by AmbientMalice** [comment]
Map is fixed. Shadow depth issue still present.

**Comment by olivieryuyu** [comment]
map is randomly fixed

time to time it is black

![sans titre](https://user-images.githubusercontent.com/8987490/31044123-7e9ed49c-a5c9-11e7-98fb-449217be6ed3.jpg)

**Comment by olivieryuyu** [comment]
actually work with auxiliary buffer.

no depth issue anymore

@AmbientMalice 

can u confirm? if so i close.

**Comment by AmbientMalice** [comment]
Still seems broken for me. Plus both versions kinda break when you load a save state.
