### ISSUE TITLE
Donkey Kong 64 Missing Nintendo Logo at boot

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#288]
Thought this was related to FBE but is not working with FBE turned off either.

**Comment by gonetz** [comment]
Set "Detect CPU writes to frame buffer" on. This option is also necessary for Rayman 2 and many other games, which bypass RDP and load images directly to frame buffer area.

**Comment by olivieryuyu** [comment]
needs to get a ini for handling those cases

**Comment by theboy181** [comment]
Should I close this then or wait for per game config solution ?

**Comment by gonetz** [comment]
Please close.
You may open a separate issue, e.g. "Custom game settings" and prepare preliminary list of games and necessary settings for them.
