### ISSUE TITLE
Mario Golf Lens flare issue

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#291]
![capture](https://cloud.githubusercontent.com/assets/9299743/6657504/a2b60332-cb0b-11e4-892d-b448b0175cbf.PNG)

Lens flare not working as it should.. The lens flare circles are not round on the smaller circles, and the lens flare should vanish because of the trees when the camera moves. You can clearly see this effect in action with AL's GFX plugin.

**Comment by Predator82Germany** [comment]
Still exist with Mar19

**Comment by theboy181** [comment]
the flare effect is working correctly with the trees but the smaller circle is wrong. Is this the plug or the nature of upscaling ?

**Comment by Mushman** [comment]
It looks like the scattering (circles) have actually all been cut off by one pixel from both the bottom and right. It's most evident on the smaller ones because they have a lower resolution.

If you disable ``Emulate N64 Depth Compare``, the lens flare effect appears and disappears correctly. I've experienced similar issues with enabling this setting in Jet Force Gemini, but I don't know if it's expected behavior or not.

**Comment by theboy181** [comment]
Is depth compare required for any of the other FBE effects? If not we can add this as a per game setting then. 

Great find and explainatuon Mushman.

**Comment by Mushman** [comment]
No idea. I only tested the intro after finding this issue. Just off the top of my head though, make sure you check any holes which have water on them. I've seen depth issues on Glide64 where the water will render in front of the fairway.

**Comment by Mushman** [comment]
Just followed up that water rendering issue. Loading Hole 4 in Toad Highlands on Training will show you exactly the problem I'm talking about. It's not affected by ``Emulate N64 Depth Compare``. I will log another issue for it.

**Comment by theboy181** [comment]
What are your exact settings?  I didn't have  Enable N64 Depth Compare on, and the issue still occurs.

I almost wonder if this happens on the real HW but since the up-scaling is minimal you don't notice it. The ball is also like this where is feels like one row of pixels are cut from the right. I beleiv that this is noticeable using AL RDP too.

**Comment by Mushman** [comment]
Thanks for the feedback. You need to have ``Copy depth buffer to RDRAM`` / ``EnableCopyDepthToRDRAM`` (with ``EnableFBEmulation``) for the effect to render correctly.

**Comment by theboy181** [comment]
![capture](https://cloud.githubusercontent.com/assets/9299743/6770106/1e9ae672-d073-11e4-8d5a-49c9edd72662.PNG)

Your correct about the water. Here is a pic for the new issue if you need.

**Comment by theboy181** [comment]
Still not correct..  
Are these correct settings?

![capture](https://cloud.githubusercontent.com/assets/9299743/6770129/06d0ec3e-d074-11e4-82e3-6931ecb8a8c4.PNG)
![capture](https://cloud.githubusercontent.com/assets/9299743/6770131/15a52c02-d074-11e4-9c7c-991fa3d5568d.PNG)

**Comment by Mushman** [comment]
Yes, they're correct. I just tested with those frame buffer settings and the lens flare disappears when it should. Do you see the effect come in and out during scene at all or is it always there?

**Comment by theboy181** [comment]
Mush.. I just double checked what you wrote. I thought you were saying that the circles were fixed with these settings too. These settings are fine for the lens flare fading as it passes by the trees. 

Have you noticed that all circles seem to be cut off on the bottom and right? IE the ball in almost all shots. I'm thinking this is HW specific now, and that the only work around would be HD texture patch.  This game is a mess for texture dumps though..

**Comment by Mushman** [comment]
Ah, I see what you mean. The settings I gave will fix the flare appearing and disappearing, but not how the circle scatters are cut off. Sorry for the confusion.

**Comment by theboy181** [comment]
I have tested with AL RDP and the samll circle is a circle. I am unsure if this it an issue with GLideN64 now or not.
![capture](https://cloud.githubusercontent.com/assets/9299743/6770245/ab22a734-d077-11e4-972f-9eebfc683025.PNG)
![capture1](https://cloud.githubusercontent.com/assets/9299743/6770246/ad775cdc-d077-11e4-80e5-ffdcae700c81.PNG)

At its native resolution its hard to say. The ball looks round in most scenarios in AL RDP too.

**Comment by Mushman** [comment]
I believe you are correct that it is cut off. In the native resolution screenshot, the circle appears symmetrical, whereas in GLideN64, it's quite noticeably not.

**Comment by theboy181** [comment]
the circles are fixed then?   

Why is this tread closed?

**Comment by Mushman** [comment]
This issue has not been closed. The issue which referenced this one is closed.

**Comment by olivieryuyu** [comment]
there is no more the issue.

![sans titre](https://cloud.githubusercontent.com/assets/8987490/14451278/20713ec6-0086-11e6-8802-9cd40a36341f.jpg)

can it be closed?

**Comment by gonetz** [comment]
Fixed
