### ISSUE TITLE
Mario Party GFX issue since last few releases.

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#292]
![capture](https://cloud.githubusercontent.com/assets/9299743/6657523/4c3df04a-cb0c-11e4-8c72-76c5a5e9695b.PNG)

**Comment by gonetz** [comment]
NVidia or AMD ?

**Comment by theboy181** [comment]
AMD

**Comment by gonetz** [comment]
Need to get confirmation from NVidia users. I checked that issue and it looks like a bug in video driver.
As a workaround, disable hardware lighting for games with that issue.

**Comment by Predator82Germany** [comment]
Still exist on my NVIDIA

**Comment by gonetz** [comment]
Please test with latest build.

**Comment by theboy181** [comment]
:)
