### ISSUE TITLE
Yoshi's Story HLE gfx issue

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#293]
![capture](https://cloud.githubusercontent.com/assets/9299743/6657707/ab2f99f6-cb10-11e4-94b7-ab6b171f4123.PNG)
Mystery blocks have GFX  issues in HLE mode.

**Comment by gonetz** [comment]
Same issue as in #292

**Comment by baptiste0602** [comment]
Same problem on Nvidia GTX 670 with Hardware lighting ON.
It doesn't happen when it's disabled.

**Comment by gonetz** [comment]
Please test with latest build.

**Comment by theboy181** [comment]
:)
