### ISSUE TITLE
monaco grand prix: white title screen, wrong textures

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#295]
![dsfdsf](https://cloud.githubusercontent.com/assets/8987490/6677428/29a67802-cc30-11e4-9692-9a7d9c1b91a1.jpg)
![iii](https://cloud.githubusercontent.com/assets/8987490/6677429/2d0ba206-cc30-11e4-93b7-7230263dddd0.jpg)

**Comment by Predator82Germany** [comment]
With Mar19 rom crash on boot

GLideN64-log
[gles2GlideN64]: FBO Incomplete Attachment
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/6730356/1a3a9e4e-ce3c-11e4-99a5-37e0f5bf6986.png)
![unbenannt2](https://cloud.githubusercontent.com/assets/6679921/6730357/1a3bb702-ce3c-11e4-93aa-8765764ce8a1.png)

**Comment by olivieryuyu** [comment]
duplicate
