### ISSUE TITLE
Mario Tennis DARK textures

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#296]
Sometime during replay the sky textures are darker than usual, and this might be related to the reflection on the trophy being too dark?
![capture](https://cloud.githubusercontent.com/assets/9299743/6689635/b5ca8042-cc78-11e4-9d92-724a407f34ac.PNG)

**Comment by Predator82Germany** [comment]
Dark textures seems fixed with Mar19 but other glitches appear
https://www.youtube.com/watch?v=PT4aSGT0JJM

**Comment by gonetz** [comment]
Hmm, (E) version shakes indeed.

**Comment by gonetz** [comment]
Fixed

**Comment by theboy181** [comment]
Bloom stopped working..

**Comment by gonetz** [comment]
Bloom is not related to that issue, so lets fix it in #300

**Comment by theboy181** [comment]
Still dark ? Trophy dark..

**Comment by Predator82Germany** [comment]
Trophy is flickering in yellow (see my video)

**Comment by theboy181** [comment]
Link?

**Comment by theboy181** [comment]
Nvm. Read the date wrong. I'm still getting black trophy.

**Comment by Predator82Germany** [comment]
In 1st comment

**Comment by Nes-player4Life** [comment]
The trophy is affected with AA cranked up, off it should be normal.

**Comment by theboy181** [comment]
Trophy is no longer dark, but the reflection is really block looking, unsure if this is correct?

@ gonetz

Fixed thanks!
