### ISSUE TITLE
Mystical ninja: menu fb effect hang emus

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#299]
![myst](https://cloud.githubusercontent.com/assets/8987490/6703956/d23bd2a6-cd42-11e4-9997-de5568c8fa31.jpg)

**Comment by gonetz** [comment]
Something really mystical with that game. It works ok in LLE mode. HLE display list contains RDP commands which not present in LLE one. The commands do a weird thing. In particular, additional frame buffer is allocated (it does not happen in LLE), and write to RDRAM area corresponding to that buffer probably causes the freeze. I see no bug in my code, but the result is wrong. Probably, special hack will be necessary for this game.

**Comment by olivieryuyu** [comment]
fixed

**Comment by gonetz** [comment]
Cool!
