### ISSUE TITLE
Bloom effect not always working

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#300]
Bloom effect not working in some titles. (Mario Tennis)

The effect seems to be off in March 19th release too. Kirby the effect makes the screen flicker.

Is there away to stop the effect from bleeding in some games with the black borders?

Killer Instinct also shows weird bleeding during Jago's character selection.

**Comment by gonetz** [comment]
Bloom is screen-size post-filter. It is applied to whole image. If some part of the image is not updated, it eventually will be overexposed. Killer Instinct character selection screen is a good example: only character polygons updated there, and only the ones which changes.

If game uses scissor to reduce visible area (black boarders), this scissor also can be used in bloom, so black areas will not affected. I'll check how it work.

**Comment by theboy181** [comment]
Hmm. I wonder  if you could control the bloom area per-game to help some of the borders?

**Comment by theboy181** [comment]
Fixed! Thanks!
