### ISSUE TITLE
Lode Runner 3-D (All) - Screen Shaking

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#301]
Screen shaking

**Comment by olivieryuyu** [comment]
with fb, without it is ok

**Comment by gonetz** [comment]
Yes. Something wrong in my VI emulation code.

**Comment by Predator82Germany** [comment]
Still exist with 28Mar

**Comment by thecoreyburton** [comment]
This is still an issue in the release zilmar spec version, is it a problem in the Mupenplus version too? And does Lode Runner 3D have anything that actually requires framebuffer emulation?

**Comment by thecoreyburton** [comment]
I thought I'd give it a shot in LLE, instead of shaking you get no picture at all. Disabling Frame Buffer  Emulation makes it display correctly again too.

**Comment by thecoreyburton** [comment]
Whilst this is still present, it seems to be gone in some scenes and less consistent in others. Visible from power on.

**Comment by olivieryuyu** [comment]
seems to be completey fixed

can we close?

**Comment by gonetz** [comment]
I did nothing for it. Is it really fixed?

**Comment by thecoreyburton** [comment]
I'm not sure, can you post a compiled version of the build you found it was fixed on olivieryuyu and I'll do a test? I'm unable to compile and tried the build on EmuCR from 10th of February and the problem was as prevalent as ever.

**Comment by olivieryuyu** [comment]
i cannot see any flickering or VI issue

Can you?

**Comment by thecoreyburton** [comment]
Yes, in the build I have it's very intense. Even on the opening N64 logo. Most noticeable at the top. I was testing the (U) ROM for reference. Can you post the build you're using so I can test that here?

**Comment by thecoreyburton** [comment]
This appears to have manifested as flickering on alternate frames in the latest build. Is there a setting or option to combat this?

**Comment by gonetz** [comment]
Let it be open. Screen should not shake with fb emulation.

**Comment by olivieryuyu** [comment]
no flickering for me at all
