### ISSUE TITLE
Pilots Wing wrong shadows

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#302]
Pilots Wing: the shadows are wrongly displayed in game (black polygons from
the aircraft to the ground)

Angrylion:

No, Pilotwings uses z mode 2 (write enables if (infront || max)). I don't
know what's causing wrong shadows there. I've never had this bug in my
plugin. It may be caused by the wrong emulation of "inverse alpha" BL
input. Here "inverse alpha" is used in the 2nd cycle of the BL, so it must
be an inverse of A mux from the 2nd cycle, which in this case is an inverse
of the combined alpha. But it definitely has nothing to do with coverage. »

**Comment by olivieryuyu** [comment]
fixed

awesome!!!!

**Comment by theboy181** [comment]
Current Master I cant get this working. is there an update?

**Comment by gonetz** [comment]
@olivieryuyu Yes, it was hard to find the way to emulate that on hardware.

@theboy181 Supported by my latest build:
https://github.com/gonetz/GLideN64/issues/885
If it does not work for you, clear or disable shaders cache.

**Comment by LegendOfDragoon** [comment]
What commit fixed this issue?

**Comment by gonetz** [comment]
ccff245f85

**Comment by fzurita** [comment]
Shadows don't seem to work with GLES 3.0. What settings are needed to make shadows work?

**Comment by gonetz** [comment]
Shaders must support gl_FragDepth.

CLSLCombiner_ogl3x.cpp, 402:
```
#ifdef GLESX
		"#ifdef GL_NV_fragdepth							\n"
#endif
...
```
