### ISSUE TITLE
Bomberman Hero (E) - Like A Discotheque

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#305]
With emulate frame buffer I get a stroboscoped flickering & wrong position of image
https://www.youtube.com/watch?v=ExlQXpTIMHc

**Comment by olivieryuyu** [comment]
i don't have this issue.

Emu and settings please?

**Comment by Predator82Germany** [comment]
Project64
Default settings
PAL-rom

**Comment by olivieryuyu** [comment]
with PJ64 indeed but I ve just tried with 1964, no issue

**Comment by Predator82Germany** [comment]
Still exist with 28Mar but only on E-rom

**Comment by olivieryuyu** [comment]
did you try with another emulator?

i have no issue with 1964 and mupen so it looks like a VI issue from PJ64

**Comment by olivieryuyu** [comment]
seems now to be fixed!!

Can we close?

**Comment by Predator82Germany** [comment]
It´s still there

**Comment by olivieryuyu** [comment]
correct sorry :(

**Comment by AmbientMalice** [comment]
The game now seems to flicker at the bottom. Looks like top of framebuffer has wrapped around to the bottom or something.

**Comment by gonetz** [comment]
Disable frame buffer copy to fix flicker.

**Comment by olivieryuyu** [comment]
it is nearly fixed, no? I think with the recent VI improvments

**Comment by gonetz** [comment]
It does not flicker for me with disabled  buffer copy.

**Comment by olivieryuyu** [comment]
it does not flicker at all anymore for me, whatever options i use!
