### ISSUE TITLE
Custom pergame ini settigns

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#307]
liking the addition of the INI.

Is it possible to manipulate all settings per game?

ie.

[SMASH_BROTHERS]
frameBufferEmulation\enable=1
font/size=72
video/windowedWidth=320
video/windowedHeight=240

Seems like I can only control the settings for the FBE

I think this would add more options for custom settings if you could control all variables via ini.

**Comment by olivieryuyu** [comment]
ini is for emulation purpose only, not for ad hoc settings which are set according to user preference

Please close ticket

**Comment by theboy181** [comment]
Reading @gonetz description of how the ini should work, it is not working as it should.

**Comment by gonetz** [comment]
These questions are discussed on forum:
http://gliden64.boards.net/thread/87/default-config  - default ini settings
http://gliden64.boards.net/thread/84/custom-game-settings  -  settings, supported in custom section

IMO, currently custom game section must contain only settings essential for correct emulation of given game. Later I may add support for all options, but config for release version must be free of redundant settings. Thus, 
video/windowedWidth=320
video/windowedHeight=240
won't work
