### ISSUE TITLE
Regression: DK64 demo hangs if EnableCopyColorFromRDRAM / Render frame buffer as texture is on

### ISSUE THREAD

**Issue by Mushman** [gonetz/GLideN64#308]
A regression has appeared in the Week 21 ``ab98c42`` February 21 build where Donkey Kong 64 will hang when the first title screen demo finishes if ``EnableCopyColorFromRDRAM`` (and, of course, ``EnableFBEmulation``) or ``Render frame buffer as texture`` is on. When the transition completes, the next demo does not load and the player cannot press Start to go to the main menu. Users can still access the menu if they interrupt the demo before it ends. If the setting is disabled, no hang is encountered and the next demo loads as usual. Other configuration settings do not interfere with this behaviour.

This is present in all versions after the regression appeared on both Mupen64Plus and Zilmar builds. The latest versions I tested were the Week 24 Performance Fix ``10dfc87`` March 21 build for Mupen64Plus and the Week 24 Custom INI ``869bcc6`` March 22 Zilmar build.

**Comment by theboy181** [comment]
![capture](https://cloud.githubusercontent.com/assets/9299743/6770470/11483776-d07e-11e4-9ecd-c68664149f94.PNG)

I'm getting this error on load using PJ64.

**Comment by gonetz** [comment]
Perfectly good bug report, thanks! It makes problem search much easier.

**Comment by gonetz** [comment]
Why you use "EnableCopyColorFromRDRAM" ? The transition effect requires CopyColorToRDRAM.

**Comment by Mushman** [comment]
I had left it enabled after running other games, so it's partially user error on my part. I don't know if DK64's graphics need the setting. I reported it because I thought it was undesirable for a plugin option to disrupt the game this way.

**Comment by gonetz** [comment]
You absolutely right here. It's was a bug, which caused data corruption in RDRAM, it definitely had to be fixed. I considered that option as harmless, because it reads from RDRAM. I thought that you confused it with "copy fb to RDRAM", which usually causes problems. I forgot that "copy from" can write to RDRAM as well. Wrong condition found and fixed. I'll upload the fix today.

**Comment by Mushman** [comment]
Wonderful! I discovered other bugs caused by this setting since reporting this as well, but I'll hold off logging them until I see if the new revision fixes them too.
