### ISSUE TITLE
Jet Force Gemini: Letterboxing if Widescreen is turned on when Frame Buffer Emulation is enabled

### ISSUE THREAD

**Issue by Mushman** [gonetz/GLideN64#309]
If widescreen is switched on in Jet Force Gemini with frame buffer emulation enabled, the game gets letterboxed instead of rendering in the whole area. This happens no matter what aspect setting is used in GLideN64. Disabling frame buffer emulation produces desired behaviour, but in turn, prevents frame buffer effects being used. The intro screens are unaffected.

In Glide64, the letterboxing would always happen unless ``adjust_aspect`` was set to ``0``. Turning frame buffer emulation on didn't change it.

GLideN64, 856×480, Frame Buffer Emulation Off
![Jet Force Gemini rendering to the whole area in widescreen with frame buffer emulation off](http://i.imgur.com/LuKSFxr.png)

Frame Buffer Emulation On
![The screen is letterboxes when frame buffering is emulated, squashing the screen as well](http://i.imgur.com/7g6eOaL.png)

You can enable widescreen by going to *Options* at the main menu and selecting the bottom-right icon.

This is present in all versions except the Week 1 ``af2bb06`` 4 October 2014 build since the F3DDKR microcode wasn't supported yet.

**Comment by AmbientMalice** [comment]
AFAIK, JFG uses letterboxed widescreen, not anamorphic widescreen. So unfortunately, this behavior is correct, and not a bug, as far as I am aware.

**Comment by Mushman** [comment]
I couldn't find a video demonstration on hardware. Nevertheless, even if that is true, could a workaround like the one I mentioned from Glide64 be implemented if that ends up being the case?

**Comment by Predator82Germany** [comment]
Do you use the european-rom?

**Comment by AmbientMalice** [comment]
Gonetz talked about Jet Force Gemini's framebuffer effects in this blog post. http://gliden64.blogspot.in/2014/01/frame-buffer-emulation-part-iii.html

The problem is that the plugin is currently emulating the game the way it is supposed to. The Dolphin team ran into this same issue. Rogue Squadron II/III has letterboxing which is needed to keep aspect ratios correct during cutscenes. (Otherwise you get egg shaped planets.) So any hack that removes black bars is also likely to ruin the game's native letterboxed aspect ratio. The game simply wasn't designed to run in true widescreen.

**Comment by Mushman** [comment]
I forgot about that example in his blog.

I understand that it may not have been designed for true widescreen, but as I've said, it's capable of it. I ran it without the letterboxing in Glide64 and it works here too as long as frame buffer emulation is off. There's been user demand for a plugin-side widescreen hack, but this game has a native widescreen mode which *almost* works as is. It makes sense to solve this.

**Comment by AmbientMalice** [comment]
I *suppose* Gonetz could add an optional hack to ignore scanline commands from the game. But that's his decision. (Although it will cease to be his decision once the plugin is open source, for better or worse.)

I do understand people wanting to run games in widescreen, but it's not always peaches and cream. Accurately emulated N64 games *will* sometimes have letterboxing and borders and stuff like that.

**Comment by Mushman** [comment]
Yeah, I know how important accuracy is. It's why I funded the project! It's just that this is a feature I've used in the past so I thought it wouldn't be much hassle requesting it back.

**Comment by gonetz** [comment]
AmbientMalice is right. The game looks like this because it is programmed that way. If I remove Video Interface emulation for this game, it will fix widescreen but game's intro will be spoiled. Glide64 has very basic VI emulation, and it has special fix/hack for that game. I don't want to add hacks before release, because it will add more chaos to currently not-so-stable code.

**Comment by Mushman** [comment]
The intro and other cutscenes are correct when widescreen is on with in this mode. I see your point though. If you do reintroduce this functionality in the future, I won't mind if it's a non-default game configuration option not available in the UI. That's how it was in Glide64, after all.

**Comment by olivieryuyu** [comment]
i guess it would be good to close the ticket then

**Comment by Mushman** [comment]
:(

**Comment by theboy181** [comment]
@gonetz What is the hack that glide64 uses and would this hack fix the SSB64 stage clear FB stretch?

**Comment by gonetz** [comment]
What is "SSB64 stage clear FB stretch"?

**Comment by theboy181** [comment]
When you have 16:9 set (not stretch) the stage clear FB ends up stretching the aspect when you clear the stage and it shows the results

**Comment by gonetz** [comment]
16:9 - you mean widescreen hack?

**Comment by theboy181** [comment]
Yes. When the windscreen hack is enabled in HLE mode

**Comment by gonetz** [comment]
No, Glide64 hack can't help there.

**Comment by theboy181** [comment]
Is there anyway to fix the fb so it can do widescreen and hi resolution?

**Comment by gonetz** [comment]
I can't say for sure. Probably, widescreen hack can be tuned. It is hack, it is not guaranteed to work always.

**Comment by theboy181** [comment]
How can I turn it on?

**Comment by AmbientMalice** [comment]
He said "tuned", not "turned".
