### ISSUE TITLE
Mario Golf depth issue?

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#310]
![capture](https://cloud.githubusercontent.com/assets/9299743/6770361/54e4978e-d07b-11e4-89f9-1bbf36123e12.PNG)
![capture](https://cloud.githubusercontent.com/assets/9299743/6770362/58789b66-d07b-11e4-87d7-a3eae45f9529.PNG)

This may be related to the water issue described in https://github.com/gonetz/GLideN64/issues/291

**Comment by Mushman** [comment]
Yes it is. I have made a more detailed report of this bug in #312 which covers this behaviour too. Requesting this issue be merged with mine so we can focus on this issue in one place.

**Comment by theboy181** [comment]
Who can merge, @gonetz ?

**Comment by Mushman** [comment]
It might be easier to just close the issue.

**Comment by gonetz** [comment]
Ok, close this one, left #312
