### ISSUE TITLE
Mario Golf ball shadow not correct

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#311]
![capture](https://cloud.githubusercontent.com/assets/9299743/6770418/8478a4e4-d07c-11e4-9dee-6f72f706479d.PNG)
![capture1](https://cloud.githubusercontent.com/assets/9299743/6770431/bbf52640-d07c-11e4-946c-2ec47d2ae968.PNG)
I might just be being picky now. ;)
![capture](https://cloud.githubusercontent.com/assets/9299743/6770421/87d6571c-d07c-11e4-838f-adbbf0aba183.PNG)

The dust behind the ball might not be correct either.. hard to say since at a lower resolution this could be how the effect was achieved.

**Comment by gonetz** [comment]
Fixed
![mariogolf64-000](https://cloud.githubusercontent.com/assets/8983092/14340999/18742574-fcaf-11e5-94c9-22959cdedf9c.png)

**Comment by theboy181** [comment]
Sexy!!!  Thanks!!!
