### ISSUE TITLE
Mario Golf: Animated effects render in front of course

### ISSUE THREAD

**Issue by Mushman** [gonetz/GLideN64#312]
In Mario Golf, animated effects will render in front of the course. This is most obvious on holes with water because the water will render in front of the course instead of behind it, but is not limited to that. An example of this behaviour is on Hole 4 of Toad Highlands at the tee.

![Water in Mario Golf rendering in front of the course](https://cloud.githubusercontent.com/assets/6550546/6770114/5332f0ae-d10a-11e4-9eb4-1bbdad18cd82.png)

If you aim with the control stick, the animated elements are layered correctly, like below. They will render in front again when you stop moving.

![The water stays behind the course when aiming the shot left or right](https://cloud.githubusercontent.com/assets/6550546/6770130/f3f5c75a-d10a-11e4-8491-babe9dd43472.png)

They also draw in the correct place when in view mode.

![The camera doesn't need to be moving for the water to stay in the correct place. like in camera mode](https://cloud.githubusercontent.com/assets/6550546/6770136/31c758f0-d10b-11e4-9302-1d1cf5bc9638.png)

Here's an example on Hole 17 of Toad Highlands where the landing zone and flagpole should be obscured by the hill.

![The hill should completely conceal the grid, but doesn't](https://cloud.githubusercontent.com/assets/6550546/6770522/0edeaec8-d116-11e4-9fc3-43104be570dd.png)

I believe this happens because the course does not get redrawn every frame. It explains why moving your aim works normally as the game has to redraw the course. You might also notice that reloading a save state will make the whole course black until a draw instruction is given.

This issue is present in all versions of GLideN64 using any settings and tested up until the latest builds as of writing.

**Comment by gonetz** [comment]
Please give me a savestate file.

**Comment by Mushman** [comment]
You can access the levels I've mentioned in the report in the Training mode. To get there, at the main menu go to ``Players`` > ``One`` > Any character > ``Training`` and then select either Hole 4 or 17 on Toad Highlands.

**Comment by Mushman** [comment]
The objects which draw over the course could be static but told to redraw every frame anyway too, it seems. Look at the walls on any mini-golf course. This screenshot is from Luigi's Garden Hole 1.

![The walls for all mini-golf courses overlap the screen very noticeably.](https://cloud.githubusercontent.com/assets/6550546/6796664/3c5d9c20-d24b-11e4-8e85-036b435e1528.png)

**Comment by gonetz** [comment]
I'm afraid that can't be fixed without N64 pixel coverage emulation. When camera is not moving most of geometry just not rendered. What is rendered is player and water. It is rendered over 2D image stored in the frame buffer. Water's pixels can't be rejected by depth buffer because the buffer is empty - nothing is rendered. I guess, that on real hardware pixels rejected because of pixel coverage overflow. Software lle plugin emulates pixel coverage and it works correct here.

**Comment by gonetz** [comment]
Let it be open. I'll return to it someday.

**Comment by Mushman** [comment]
Oh, sorry. Just thought that's what you wanted when you labelled it as wontfix.

**Comment by gonetz** [comment]
I intended to set it as low priority, but can't find that option.

**Comment by Mushman** [comment]
Try using [custom labels](https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/).

**Comment by gonetz** [comment]
Thanks!

**Comment by theboy181** [comment]
Any hope yet?  Maybe a hack that renders the entire screen despite it all. ?

**Comment by gonetz** [comment]
Such hack is not possible - no data for rendering.

**Comment by gonetz** [comment]
**εὕρηκα!**
It was not pixel coverage overflow. The game uses depth buffer copy. When screen is not moved, latest valid color and depth buffer used as aux buffers and copied to the current color and depth buffer, as wallpaper. Player's model rendered over.
Another use of depth buffer rendering.
![gliden64_mariogolf64_000](https://cloud.githubusercontent.com/assets/8983092/18246584/c8633de0-7396-11e6-8ec7-c2beaa7dadd3.jpg)

**Comment by AmbientMalice** [comment]
That's really cool.

**Comment by olivieryuyu** [comment]
can it be closed?
