### ISSUE TITLE
PPL: graphic issue in game

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#315]
![bbooqd](https://cloud.githubusercontent.com/assets/8987490/6782003/b315622e-d171-11e4-9478-32aa1e7eb358.jpg)

detect cpu write and refd are on

**Comment by AmbientMalice** [comment]
Is this issue still happening? Not really familiar with this game.

![puzzle_league_n64-001](https://cloud.githubusercontent.com/assets/10704701/24705036/69a214bc-1a4d-11e7-9bf6-9f03c193541f.png)

**Comment by loganmc10** [comment]
I just tested this out on mupen64plus. I experienced the same thing, but only at the end of the match.

**Comment by gonetz** [comment]
@olivieryuyu Is it still actual?

**Comment by olivieryuyu** [comment]
nope
