### ISSUE TITLE
nfl quaterback 98: missing fb effect (whatever option used)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#316]
![qsdsqdsqdsqd](https://cloud.githubusercontent.com/assets/8987490/6782889/124b08d4-d177-11e4-8150-d93c03612e00.jpg)

**Comment by olivieryuyu** [comment]
still not fixed

**Comment by gonetz** [comment]
The problem is harder then I thought. It seems that the games uses pre-generated depth buffer for TV monitor, like in RE2. Without initialized depth buffer the image is just rejected. Glide64 works there thanks to hacks and bugs :)

**Comment by AmbientMalice** [comment]
A pity it needed a game specific hack, but good work.

**Comment by gonetz** [comment]
This effect impossible to implement correctly without special code. Render texture to **depth buffer** not used anywhere else. I hope that the technique I invented here can be reused for RE2.

**Comment by olivieryuyu** [comment]
Seems to not work with pj64

**Comment by AmbientMalice** [comment]
@olivieryuyu I think this game has problems with PJ64 in general. Are you referring to the fact it doesn't boot?

**Comment by gonetz** [comment]
Yes, it does not boot for me with pj64. I use Mupen64 for testing this game.

**Comment by olivieryuyu** [comment]
i can boot it with PJ64.

**Comment by AmbientMalice** [comment]
>i can boot it with PJ64.

I can't, at least not on current PJ64. I used to be able to boot it, but that was only in LLE mode, and GLideN64's depth buffer doesn't work in LLE mode.

**Comment by olivieryuyu** [comment]
i am using the last svn version

**Comment by AmbientMalice** [comment]
Must be a quirk, then. Anyhow PJ64 is automatically set to disable HLE video (HLE GFX=No) for that game, which will break a lot of things, including the depth buffer.

**Comment by gonetz** [comment]
> GLideN64's depth buffer doesn't work in LLE mode

Really? That a news for me. How the games works then?

Seriously, that fix is not HLE/LLE dependent and should work in both modes. I tested it in HLE mode only.

**Comment by AmbientMalice** [comment]
>Really? That a news for me. How the games work then?

Sorry, to clarify depth buffer to RDRAM doesn't work in LLE mode. At least it didn't last time I checked.

**Comment by gonetz** [comment]
depth buffer to RDRAM is not needed for that effect.

It uses quite opposite technique: pre-rendered depth texture is drawn to depth buffer.
The effect is programmed in a smart way. Spinning logo is rendered to an aux frame buffer, which then rendered as texture to TV area. Parts of that logo image can go out of TV screen area at some moments. These parts need to be cut. It can be done with depth buffer, which has zero values outside of TV screen. The game uses depth buffer as color buffer and renders special 16bit texture into it, which corresponds to TV image. Tricky.

**Comment by olivieryuyu** [comment]
so it is fixed in HLE but not LLE?

odd

**Comment by AmbientMalice** [comment]
@olivieryuyu I'll test with mupen64plus LLE.

**Comment by AmbientMalice** [comment]
Okay, so it definitely works in HLE, but not LLE. Tested with mupen64.
![gliden64_quarterback_club_98_002](https://cloud.githubusercontent.com/assets/10704701/14426274/44552780-0031-11e6-98f1-731f50c9479c.jpg)

![gliden64_quarterback_club_98_001](https://cloud.githubusercontent.com/assets/10704701/14426286/5517dc5c-0031-11e6-825a-ada3d0a42ff1.jpg)

**Comment by AmbientMalice** [comment]
This can probably be considered fixed. The game only running in LLE/not running at all is an emulator-side problem, and the LLE bug can probably get its own issue.

**Comment by olivieryuyu** [comment]
Hmm Sergey, would you like to close it?

**Comment by gonetz** [comment]
I'll check why it does not work in LLE and then close.

**Comment by gonetz** [comment]
Fixed: dad7fcb68742007
