### ISSUE TITLE
All-Star Baseball 2001: wrong texture on ground

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#317]
![oops](https://cloud.githubusercontent.com/assets/8987490/6784186/794e9daa-d17e-11e4-9524-2f244f0621da.jpg)

**Comment by purplemarshmallow** [comment]
fixed?
![gliden64_all-star_baseball_20_000](https://cloud.githubusercontent.com/assets/7283660/7835316/2c497d7c-0478-11e5-8fe0-a7c3197393f8.jpg)

**Comment by olivieryuyu** [comment]
fixed
