### ISSUE TITLE
Destruction derby: Speed issues

### ISSUE THREAD

**Issue by Nes-player4Life** [gonetz/GLideN64#319]
Intro and in game are super slow.

**Comment by olivieryuyu** [comment]
confirmed, it is slow

**Comment by olivieryuyu** [comment]
with VI at 60 in GlideN64 we have 12 FPS

Tested with Angrylion

I have in intro 9 FPS for 47 VI

So 12 FPS for 60 VI

May be simply the game is slow by itself or suffer timings issue.

Jabo plugin is slow as GlideN64.

I think we should close!

**Comment by Nes-player4Life** [comment]
I seems to be faster then when I opened the issue.
Project64 1.6 seems to emulate a bit faster then 2.2.
Maybe I'll add this info over at Pj64 Gethub later for @Zilmar but for now I satisfied with the speed.
