### ISSUE TITLE
1080 snowboarding score screen: fb not handled

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#32]
With HWFBE only one, there is neither blurry effect between in game and the score  screen nor the "tv" showing of the last race.

With read every frame one, the blur start but when it should change to the next screen, it crashes with line296 :(

Current state (2nd weekly build)

![black](https://cloud.githubusercontent.com/assets/8987490/4601993/069d4b68-5121-11e4-9432-5be983be929e.jpg)

LLE software plugin

![missing fb1080](https://cloud.githubusercontent.com/assets/8987490/4601987/d9ff1faa-5120-11e4-9718-3e18132f2a89.jpg)
![transition effect](https://cloud.githubusercontent.com/assets/8987490/4601986/d9fe1466-5120-11e4-80c7-e258293fcf4a.jpg)
![transition effect woo](https://cloud.githubusercontent.com/assets/8987490/4601988/d9ff975a-5120-11e4-859d-72bdc09cb5d3.jpg)

**Comment by gonetz** [comment]
Fixed
