### ISSUE TITLE
Yoshi's Story Water effects does not work with AA

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#322]
Water effect does not work with AA on. ;(

**Comment by gonetz** [comment]
Probably the same reason as with #244

For this game it's not that critical, because 2D graphics does not suffer from aliasing.

**Comment by olivieryuyu** [comment]
then please close

**Comment by gonetz** [comment]
No, lets be open. This issue with AA need to be solved.

**Comment by olivieryuyu** [comment]
yes but only ticket for the same issue no?

**Comment by gonetz** [comment]
I need to check is it the same issue.

**Comment by theboy181** [comment]
@gonetz 

Game just crashes when you get to this stage now.

**Comment by purplemarshmallow** [comment]
fixed in 1.1?

**Comment by theboy181** [comment]
Sorry thought I closwd.
