### ISSUE TITLE
Perfect Dark - Crash often

### ISSUE THREAD

**Issue by baptiste0602** [gonetz/GLideN64#323]
Perfect Dark crash often with GLideN64.
It's reproductible : 
- on Project64 : at each time when you keep night vision when the lights are "on" (tested on 3rd mission)
- mupen64plus and 1964mod : After few seconds when you start a mission (tested on 1st and 3rd mission)

I tested (E) version with a lot of combinaisons of FBE option on/off, it happen on each...

No log...

**Comment by V1del** [comment]
I can confirm this, there seem to be certain conditions necessary, but it isn't really conclusive which. (e.g. the mission where you first use the camspy, will always crash in the second to last room with the three guards that use the dragon gun, but not before and others will crash after a few seconds)

**Comment by gonetz** [comment]
I never played that game. Could you give me a savestate, from which I can run into the problem?

**Comment by baptiste0602** [comment]
Savestate from (E) version with PJ64 2.2.0.3 (latest) and GLideN64 April_03

https://drive.google.com/file/d/0ByOA3_oOu6O9TkRjY092Q2oxMmc/view?usp=sharing

**Comment by gonetz** [comment]
Very good savestate, thanks. The problem is 100% reproducible.

**Comment by baptiste0602** [comment]
No crash anymore with checksum option. But i got a huge speed decrease and some textures problems : 
![image](https://cloud.githubusercontent.com/assets/11183826/7051171/92fa2990-de26-11e4-87a5-4a763aeea548.png)

**Comment by baptiste0602** [comment]
Sorry "validity check method" option seems unrelated, slowdows and textures problems happens with both values.

Do you want that I close this issue and I open a new one ?

**Comment by gonetz** [comment]
Huge slowdown seems to be fixed with latest build. I have 60 fps with PJ64 1.6 when NightVision is on.
If it's not fixed for, please open separate tickets for slowdown and for texture issues. I need a savestate to check texture issue.

**Comment by baptiste0602** [comment]
I play an entire mission without crash or texture problems ! It's fixed :)
