### ISSUE TITLE
pga european tour: gauge not working properly (fb effect)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#325]
![pga](https://cloud.githubusercontent.com/assets/8987490/6828333/888d186a-d30d-11e4-9abc-10d4dcd89fda.jpg)

you need to do a shoot

**Comment by olivieryuyu** [comment]
worst today

**Comment by gonetz** [comment]
fixed

**Comment by gonetz** [comment]
@olivieryuyu can we close it?

**Comment by olivieryuyu** [comment]
fixed :)
