### ISSUE TITLE
Ocarina of Time pause delay

### ISSUE THREAD

**Issue by hellbringer616** [gonetz/GLideN64#327]
I posted this over at the PJ64 forums: http://forum.pj64-emu.com/showthread.php?p=61054#post61054
And i'm told that it only worked due to a hack, and that you yourself Gonetz had it working according to your blog.

But as of revision c92740a (which has the gorgeous widescreen hack) pushing pause takes between 7 and 10 seconds to open the menu.

PJ64 version: 2.2.0.2: http://www.emucr.com/2015/03/project64-git-20150325.html
Audio Plugin (if it matters) Azimer's LLE Audio v0.50.2 Beta
RSP: Hatcats Static Interpreter 

Default emulator plugins still have the issue

**Comment by gonetz** [comment]
I don't understand, what's wrong?
Subscreen does not work with "subscreen delay fix" hack.
Without that hack subscreen needs 7-10 seconds to appear.

**Comment by AmbientMalice** [comment]
With angrylion's pixel accurate plugin, the subscreen appears instantly without the hack. There's been some discussion here on the subject. https://github.com/project64/project64/issues/20

My understanding is the game isn't getting the expected result from the video plugin's framebuffer, so it keeps trying until it times out, causing the several second long delay.

**Comment by gonetz** [comment]
Interesting, which result is expected? GLideN64 does not use software rendering, but it is easy to write something to RDRAM color buffer for texrect case.

**Comment by AmbientMalice** [comment]
Cxd4 wasn't entirely sure what the game expects, but in that thread he states.

>This issue really has nothing to do with Project64 itself as a core. I've confirmed that by forcing the frame buffer in DRAM with black pixels, Zelda sub-screen has the delay in angrylion's plugin as well. Conversely, if I fill it with white pixels, the sub-screen opens instantly with no delay in response. So the issue isn't necessarily timing; it's frame buffer readback from RDRAM. If the game's R4300-side CPU code is not happy with the results of the pixels stored into RDRAM (easily the case with a non-pixel-accurate graphics plugin), it is free to decline and fail the frame buffer read test--in which case, Zelda subscreen can fail, Pokemon Snap cameras and motion events can fail, Banjo-Tooie "screen alignment" options adjust can fail...all those FB read effects can fail. Especially on z64gl, which does no frame buffer storage to &RDRAM[VI_ORIGIN_REG & 0xFFFFFF] whatsoever, and fails most demos, independent of HLE or LLE.

So in theory, this behavior is probably a symptom of something more significant. It might be possible to cheat around it, but that would likely leave Pokemon Snap and such games still broken.

**Comment by gonetz** [comment]
Funny, clearing color buffer with white color did the trick - subscreen appears almost instant. Black color (default fill color to clear color buffer) does not work.

**Comment by olivieryuyu** [comment]
is it something that can be tweaked for the games with this issue?

Zelda and Paper Mario comes in my mind

**Comment by gonetz** [comment]
Yes. I'm planing to use "fake" frame buffer to RDRAM copy for Zelda OOT. It will just fill color buffer with white color. Paper Mario subscreen is not so that slow, but it currently does not work properly.

**Comment by olivieryuyu** [comment]
there is also animal forest with this issue that i do remember (pause screen in game).

May be something could be also done for Pokemon Snap?

No idea what is going on and expected.

However it looks very cool to fix this issue :)

**Comment by baptiste0602** [comment]
Fixed with week27 build (tested with mupen64plus).

In PJ64, it crash with "checksum validity check" when you press start and there's still a delay with "fillRDRAM" but i think it's not a gliden64 bug :)

**Comment by baptiste0602** [comment]
No more crash with PJ64 with default settings ! We can close this issue.

**Comment by AmbientMalice** [comment]
Is the delay fixed, @baptiste0602?

**Comment by baptiste0602** [comment]
Yes !

**Comment by gonetz** [comment]
Ok, let's close it

**Comment by Laqueeshous** [comment]
i know this issue was posted a millenia ago, but in 2023 i can confirm subscreen delay is very much still an issue at least in ocarina of time and majoras mask, maybe its my settings idk but i cant for the life of me figure out how to fix it

**Comment by Jj0YzL5nvJ** [comment]
[Make sure you are using the latest version...](https://github.com/gonetz/GLideN64/releases/tag/github-actions)
