### ISSUE TITLE
Roadsters Trophy: doesn't support copy depth buffer to rdram

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#330]
title screen with copy depth buffer to rdram

![sdf](https://cloud.githubusercontent.com/assets/8987490/6844091/413fb7d2-d3a9-11e4-8f3d-419e354fe8a1.jpg)

**Comment by Predator82Germany** [comment]
Can be closed

**Comment by olivieryuyu** [comment]
i would wait Gonetz comments here

**Comment by gonetz** [comment]
Color or Depth copy hangs emulation after logos.

**Comment by gonetz** [comment]
Another example of "creative" way to work with depth buffer, which I could not even imagine.

Fixed.

**Comment by Predator82Germany** [comment]
Works here too with NVIDIA
What is copy color?

**Comment by gonetz** [comment]
Copy color buffer to RDRAM.

**Comment by Predator82Germany** [comment]
Don´t have this option

**Comment by olivieryuyu** [comment]
fixed
