### ISSUE TITLE
Missing V-Sync setting?

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#331]
Didn't know where else to put this.

I cant get GLideN64 to V-Sync with my TV.  I tried different Hz and setting in my video drivers. I was wondering if you would be adding a feature to let the plugin choose if v-sync is enabled?

**Comment by gonetz** [comment]
Mupen64Plus build has V-Sync option. Please check is it work for you.

V-Sync is tricky. It's not core OpenGL feature. Actual implementation is platform dependent, thus I did not want to bother with it. Mupen64Plus takes care about graphics context creation on itself, so it was free for me to add V-Sync for that emulator.

**Comment by theboy181** [comment]
This is really sad that it cant be added. I can't seem to get it to sync with my control panel options, and MupenPlus is not a real option in my opinion.

I guess I will have to see if there is some other method of forcing it somehow.

**Comment by theboy181** [comment]
http://stackoverflow.com/questions/589064/how-to-enable-vertical-sync-in-opengl

Is this helpful for Windows users in anyway?

**Comment by gonetz** [comment]
It was useful for CRT monitors/TV. LCD panels have no vertical sync.

I asked you to test Mupen64Plus because I need to know, can your problem be solved in principal when OpenGL is used. You may also try Jabo graphics plugin, which has V-Sync options, but it uses DX.

**Comment by olivieryuyu** [comment]
please close it as it won't be fixed

Thanks

**Comment by theboy181** [comment]
Thats really too bad, as the plugin looks horrible when the screen tears.

**Comment by nmz787** [comment]
It is tearing on my LCD without vsync enabled... since this is the top google hit for my keywords, can you either link to the page which tells us how to enable vsync?

**Comment by theboy181** [comment]
I tried to report this but @gonetz didn't think the issue was the plugin. I brought it to the attention to @zilmar as suggested but he pointed out that there are OpenGL plugins that support vsync. I could not get vsync running with my viseo cards settings either.  This is a real shame as the display looks horrible.

**Comment by gonetz** [comment]
Ok, I'll ask again: is there N64 OpenGL graphics plugin with V-sync support, which solves tearing problem on your monitor?

**Comment by theboy181** [comment]
HatCat's RDP v5 with OpenGL 1.5.dll Not sure how he handles this but there is no tearing in hats plugin.

**Comment by theboy181** [comment]
Hardware Frame Buffer Textures (experimental) seems to handle the tearing in glN64 when its checked. But the performance seems like its not as smooth.. interesting that FB has some impact on the tearing though.

**Comment by theboy181** [comment]
http://stackoverflow.com/questions/589064/how-to-enable-vertical-sync-in-opengl

Unsure if this helps ?

**Comment by gonetz** [comment]
Yes, unsure.

**Comment by theboy181** [comment]
Do you not get tearing @gonetz?

**Comment by gonetz** [comment]
Never noticed.

**Comment by theboy181** [comment]
It's is possible as the article states that the issue is not apparent on your card. 

Is this something I should reopen?

**Comment by gonetz** [comment]
I need to check how HatCat's RDP v5 creates OpenGL context. Can you get me the link to its sources?
Also, you said "MupenPlus is not a real option in my opinion."  Have you tried it at least? It has V-Sync support.

**Comment by theboy181** [comment]
http://www.emutalk.net/threads/55481-angrylion-s-Per-Pixel-RDP-with-OpenGL

You will find the source there, and the older source on PJ64 forums.

I will test Mupen64Plus later today, but I am unsure how to setup and change plugins via command line.. Do you have a preferred front-end you use?

**Comment by LegendOfDragoon** [comment]
Pretty sure HatCat's fork of Angrylion's plugin does not support Vsync, since it isn't even using double buffering.

**Comment by theboy181** [comment]
https://www.youtube.com/watch?v=cgXjQL4ftyE

You will see the issue here on the peek of the castle. its hard to see using a camera but this gets the point across..

You can also see that Glide64 as the option for v sync in its settings.
![capture](https://cloud.githubusercontent.com/assets/9299743/7785781/ad88cecc-0155-11e5-956b-3532cee24416.PNG)

**Comment by gonetz** [comment]
@theboy181 -  try M64Py frontend.
Why you post that screenshot from Glide64? Does your card support Glide 3x API?
Wrapper does not care about v-sync.
The information I ask from you -  example of OpenGL open source plugin (or other application), which supports V-sync and runs without tearing on your hardware? If HatCat's plugin does not use double buffering, it is not valid example. glN64 also does not use double buffering in frame buffer emulation mode, so it also is not valid example.

**Comment by theboy181** [comment]
Are you simply trying to pint out that there are no vsync plugins that use opengl?

All I know is that I get terrible screen tearing using gliden64. It doesn't happen with al opengl or the others I mentioned.

**Comment by gonetz** [comment]
I simply want an example of an application which works on your hardware to look at its code and see what it it uses for v-sync.

**Comment by gonetz** [comment]
Al opengl, HatCat's plugin and glN64 in fb emulation mode are not valid examples because they don't use double buffering and thus do not swap buffers. Buffer swap is the source of tearing.

**Comment by theboy181** [comment]
Unsure if there are any that have vsync option. That article made is sound like there isn't a vsync option for open gl.

**Comment by gonetz** [comment]
Yes, vsync is not core OpenGL option. There is Windows extension wglSwapIntervalEXT, which probably may help. Or may not. That's why I ask you about the example.

**Comment by theboy181** [comment]
I'm not trying to make it hard. I just don't have any examples. 

I have been told to enable vsync in my video card options but I iust want to make it clear that that isn't working either. 

Any suggestions would be appreciated.

**Comment by gonetz** [comment]
I suggest to try mupen64plus. It uses SDL for vsync control. If SDL does vsync right I can check its sources for solution. But I need to know that it works for you first.

**Comment by theboy181** [comment]
Do you have  a recommended Fornt-end that works with the current version of Mupen64Plus ?

Here is more insight about the issue, I  am unsure if it will help but it defiantly add some more questions as to what the problem might be.

I installed Windows 10 and setup v-sync, and triple buffering in ATI CCC. This fixed the the tearing for both windowed mode, and full screen mode. However, Windows 10 performance in PJ64 is slower than Windows 7. (not related to ATI settings)

I installed the ATI 15.4 Beta drivers in Windows 7 and this fixed the screen tearing in windowed mode, but full screen mode still has tearing.

I read that Aero effect might be the casue of the issue so I used windows classic mode, and this only reduced the tearing in full screen mode, but it was still apparent.

**Comment by theboy181** [comment]
Tested GLideN64 in Mupen64Plus 2.5 using M64py as a front-end

Unchecked "Enable Video Extensions"

Checked "Fullscreen"
Checked "Vertical Sync"

This option fixed the screen tearing the first time I set it, then the second time I tried it didn't. Unless I thought it was OK the first run I am very confused as to why it didn't work the second time.

I did get a SDL.dll is missing error the second time I ran the frontend

**Comment by gonetz** [comment]
To summarize: Mupen64Plus has no screen tearing in fullscreen with GLideN64 as graphics plugin and with "Vertical Sync" enabled. Is it correct?

Ok, I'll look how SDL creates graphics context in SDL sources. I can't promise that it will be soon due to  high load with other stuff.

**Comment by theboy181** [comment]
That is correct. take your time as I think this is only an ATI issue and doesn't plague everyone.

**Comment by phly95** [comment]
It also affects Intel, but the black text issue needs to be fixed first.

**Comment by phly95** [comment]
Also Intel lets you force vsync in the driver so it's not really a problem

**Comment by olivieryuyu** [comment]
should we close as it is on wontfix?

**Comment by gonetz** [comment]
I don't know. May be someday...

**Comment by oddMLan** [comment]
Please close this issue. GLideN64 now has an in-built V-Sync option
