### ISSUE TITLE
Extreme-G XG2 - Level Preview Not Visible

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#333]
Background isn´t there (All Regions)

![unbenannt](https://cloud.githubusercontent.com/assets/6679921/6881314/1f9af800-d55a-11e4-9456-966a81bfb92c.jpg)

**Comment by olivieryuyu** [comment]
due to copy depth buffer to rdram option. Same than for #330

**Comment by Predator82Germany** [comment]
Should merged to *.ini

**Comment by olivieryuyu** [comment]
I would keep it open as a bug, even if it is fixed by ini.
