### ISSUE TITLE
Cruis´n World - Slow

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#336]
Ca. 20 VI/s in menu, race is fine (European & USA Region, don´t know name of the Japan-one)

**Comment by olivieryuyu** [comment]
i have 60 VIs

Are you using PJ64?

If so you need to deactivate fix audio timing option in PJ64 or with 1964

also N64 depth compare is a killing performance option for the time being and should be only used for the game that needs it.

**Comment by Predator82Germany** [comment]
Fixed it
This is an RDB-Setting or?
