### ISSUE TITLE
Nushi Zuri 64: copy frame buffer to rdram doesn't work (REFB)!

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#337]
just start a new game. Works ok with Glide64

![onnooo](https://cloud.githubusercontent.com/assets/8987490/6882312/503d85ec-d580-11e4-927e-613f5b40c493.jpg)

**Comment by gonetz** [comment]
Just started new game with Mupen64 and default plugin's settings, that is copy copy and depth on. No problem with getting in game. Checked twice.

**Comment by olivieryuyu** [comment]
do you have the background?

I have only a black screen with the texts as in my screenshot

**Comment by gonetz** [comment]
Yes, the game works properly for me. At least in the beginning.

**Comment by olivieryuyu** [comment]
will check tonight and close ticket if so

**Comment by Predator82Germany** [comment]
I´ve got the same problem with my NVIDIA

**Comment by gonetz** [comment]
Hmm, I understand. Yes, I have either background or text.
I'll check it tomorrow.

**Comment by gonetz** [comment]
Fixed

**Comment by olivieryuyu** [comment]
fixed
