### ISSUE TITLE
Project64 2.x Custom Game Settings

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#339]
Sync Using Audio OFF for:
Automobili Lamborghini #335
Cruis´n World #336
F-Zero X #334

**Comment by gonetz** [comment]
How graphics plugin can change emulator's settings?

**Comment by Predator82Germany** [comment]
It can´t

**Comment by gonetz** [comment]
So, what the purpose of that ticket?

**Comment by Predator82Germany** [comment]
So to help guys having this problems with GLideN64 & to avoid new issues

**Comment by gonetz** [comment]
It's improper use of bug tracker and it hardly will help. It's better to create a new thread with that hint on the forum.

**Comment by Predator82Germany** [comment]
Ok
