### ISSUE TITLE
Roadsters Trophy: players in menu are now in black (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#340]
![oh no](https://cloud.githubusercontent.com/assets/8987490/6901942/d7158d3a-d710-11e4-8600-f6fe7f4e9c0a.jpg)

**Comment by Predator82Germany** [comment]
The lines are right?

**Comment by olivieryuyu** [comment]
not they are not as well. Looks the same issue than #180

**Comment by gonetz** [comment]
Portrait was broken 21 March. Fixed.
I'll upload the fix today.

**Comment by olivieryuyu** [comment]
fixed
