### ISSUE TITLE
airboarder (J) (not E) gfx doesn't start with fb on

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#342]

**Comment by theboy181** [comment]
It boots here, just black screen and Audio only.

**Comment by olivieryuyu** [comment]
even flickering now

**Comment by gonetz** [comment]
The game is an example of stupid optimization. It uses two frame buffers with slightly overlapping address spaces. The are black boarders around the picture, and these boarders are inside that overlapping area. Thus it is safe for the game to use address space of other buffer.

When plugin's frame buffer emulation algorithm detects that new buffer intersects with previously allocated buffer, old buffer considered as invalid and removed. This is correct behavior. For this game it means that buffer will be removed right after drawing into it is finished, thus black screen or flicker.

I hardly will fix it. The game works ok without FB emulation.

**Comment by olivieryuyu** [comment]
why does it work with E and not J then?

**Comment by gonetz** [comment]
E programmed differently. It is often happens because of different TV standard.
