### ISSUE TITLE
vigilante 8 crash in menu with fb on

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#343]

**Comment by AmbientMalice** [comment]
This crash doesn't seem to happen anymore. However, Vigilante 8 is still very broken on GLideN64.

**Comment by AmbientMalice** [comment]
Basically, neither detection method works correctly. The second improves some menu rendering, but is unstable. The game also needs framebuffer as texture, but this causes crashes.

All things considered, Vigilante 8 seems to be a way more complicated FB game than Mario Tennis.

**Comment by olivieryuyu** [comment]
fixed
