### ISSUE TITLE
excitebike64: black textures (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#345]
![sdf](https://cloud.githubusercontent.com/assets/8987490/6973564/f4388d7c-d98b-11e4-94b4-0953840d022d.jpg)

only when arriving in game

**Comment by gonetz** [comment]
Can't reproduce. Tested (E) rom with PJ64

**Comment by olivieryuyu** [comment]
bug on all versions. Tested again with another emu.

weirdl y you get the bug only when arriving in game, not before.

**Comment by gonetz** [comment]
Ok, I see it.

**Comment by gonetz** [comment]
Fixed

**Comment by olivieryuyu** [comment]
Fixed
