### ISSUE TITLE
tripleplay2000: black background in game (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#346]
![sdfsdf](https://cloud.githubusercontent.com/assets/8987490/6973696/d8cd2ede-d98c-11e4-9086-54df8ff2733f.jpg)

**Comment by AmbientMalice** [comment]
Interestingly, the background appear and disappears as you play.
![gliden64_triple_play_2000_000](https://cloud.githubusercontent.com/assets/10704701/14840119/4d4a7a3a-0c74-11e6-8178-3de6d7122781.jpg)

**Comment by olivieryuyu** [comment]
yep, the bug appeared in the same time than NFL Madden 2002. seems a loading texture issue

**Comment by olivieryuyu** [comment]
not fixable?

**Comment by gonetz** [comment]
Fixed, but I'm not happy with that fix. The problem is serious and my solution may potentially break something.

**Comment by olivieryuyu** [comment]
fixed
