### ISSUE TITLE
quake2, automobile lamborgini: with refb, transition screen in red (due to fb in 32 bits?)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#348]
simple in quake 2 press start to go the menu, the screen gets red

**Comment by AmbientMalice** [comment]
This issue has a knock-on effect.

In order to render Quake II's loadscreens correctly, CPU FB writes are needed - basically, the CPU draws the loading bar over a static FB image. But currently, with CPU FB enabled, the background turns an ugly red while the level loads.

**Comment by olivieryuyu** [comment]
well it is an improvment if the cpu write is detected as it was not before. The red is indeed an issue, certainly due to the 32 bit fb

**Comment by AmbientMalice** [comment]
Disabling expansion pack fixes the problems. Out of curiousity, @gonetz how difficult will this issue be to fix? What bit depth is GLideN64 using for FB currently?

**Comment by purplemarshmallow** [comment]
fixed

**Comment by olivieryuyu** [comment]
fixed
