### ISSUE TITLE
Mario Tennis in game character shadows

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#352]
Look like there might be a regression with Mario Tennis.
![untitled](https://cloud.githubusercontent.com/assets/9299743/6986106/fc2cfcda-d9ee-11e4-938f-20f77e42236e.png)

Turning on AA will cause the shadows to disappear.

GFX issue with the player scores in the top right hand corner. This doesn't look like the score board on the right, and looks incorrect compared to the real HW.

**Comment by gonetz** [comment]
I can't reproduce it. Could you give me a savesate with the problem?

**Comment by Predator82Germany** [comment]
Here are the shadows ok with all regions & NVIDIA

**Comment by baptiste0602** [comment]
I'm not sur it can be related but when you switch windowed/fullscreen mode some glitches can appears (no more "bombs" in the top of the screen) : 
![image](https://cloud.githubusercontent.com/assets/11183826/7068178/ef7daa48-ded0-11e4-83c4-099b3ec4eead.png)

Glitches can happen in others games (Goldeneye skies turn to black, Zelda pause screen got weird color, Mario Tennis pause screen weird or no "logo option) : 
![image](https://cloud.githubusercontent.com/assets/11183826/7068284/93ceb196-ded1-11e4-8cc2-5b5d2c14f7ff.png)

**Comment by theboy181** [comment]
screen captures were gathered just from watching the demos.

**Comment by baptiste0602** [comment]
@gonetz : so, i open an issue for windowed/fullscreen problems ?

**Comment by theboy181** [comment]
Sorry but this issue is still happening. Watch the demo games and shadows only work on some courts. If you watch a few matches you will see.

**Comment by theboy181** [comment]
![capture](https://cloud.githubusercontent.com/assets/9299743/7079245/bad3c240-ded6-11e4-84f5-2916b1030c1f.PNG)
So the shadows eventually do this after you let the game run for awhile.

I recommend using PJ64 and turning off frame limit (F4) and pressing start to skip the Tennis Blimp part.

**Comment by theboy181** [comment]
Shadows appear while using LLE, but the games GFX are messed up in other areas.

**Comment by gonetz** [comment]
@baptiste0602 : missing geometry when you load a savesate or switch to fullscreen is not bug. It is feature. Many games, including Mari Tennis, keep dynamically rendered geometry in auxiliary frame buffers. Savestate load, setting change, windowed mode change cause reset of all GL resources, including previously created auxiliary buffers. To get that geometry back you need to return to the point where it was created.

**Comment by theboy181** [comment]
OK..
This issue with character shadows can be seen when you tun AA on and off.

Can somebody confirm?

Thanks

**Comment by theboy181** [comment]
Update: GFX issue with the player scores in the top right hand corner are working correctly since today's release.

AA seems to be working with shadows too. ..

Thanks
