### ISSUE TITLE
madden nfl 2002: texture issues 

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#354]
![madden2002](https://cloud.githubusercontent.com/assets/8987490/6988246/b02ae020-da4f-11e4-8a69-8d0b49bf518b.jpg)

**Comment by olivieryuyu** [comment]
also some other gfx in game is affected

**Comment by olivieryuyu** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/8987490/13010905/8de8ab3a-d1a4-11e5-95c7-89a3d22e9084.jpg)

**Comment by olivieryuyu** [comment]
works OK with Glide64

**Comment by gonetz** [comment]
Please re-test with current version. Works ok for me with Project64

**Comment by olivieryuyu** [comment]
the second screen is indeed fixed.

But not the first one.

Here with last version of the plugin

![sans titre](https://cloud.githubusercontent.com/assets/8987490/14150945/ce768a1a-f6ab-11e5-9396-62006cd07a67.jpg)

You just need to start a game to see this.

**Comment by gonetz** [comment]
![gliden64_madden_nfl_2000_000](https://cloud.githubusercontent.com/assets/8983092/14151213/aa7e1114-f6ce-11e5-9b2c-fa52577d1524.jpg)
![gliden64_madden_nfl_2000_001](https://cloud.githubusercontent.com/assets/8983092/14151215/aa831ec0-f6ce-11e5-90ed-b68f738eaaf1.jpg)

**Comment by gonetz** [comment]
Ops, I checked madden nfl 2000

**Comment by gonetz** [comment]
Hmm, the bug seems to be random. Looks like copy buffers to RDRAM may spoil the RDRAM. If I load from a savestate created with other plugin, no problems. If I disable buffers copy, no problems either.

**Comment by olivieryuyu** [comment]
well everytime i start a new game, I have this bug. It was working back in days but then somethign changed and this bug appeared.

**Comment by gonetz** [comment]
Can't reproduce that bug with latest build. Default settings. Tested with Project64 and mupen64plus.

**Comment by AmbientMalice** [comment]
Still happening for me. Mupen64plus.
![madden_nfl_2002-001](https://cloud.githubusercontent.com/assets/10704701/15245045/aa0f30be-1947-11e6-8bfa-971643bfb958.png)

**Comment by olivieryuyu** [comment]
fixed!
