### ISSUE TITLE
1080 snowboarding floor texture missing

### ISSUE THREAD

**Issue by baptiste0602** [gonetz/GLideN64#356]
![image](https://cloud.githubusercontent.com/assets/11183826/7052855/75f0b2b4-de31-11e4-93eb-edd9de4c40d9.png)

It's not a resgression from week27 build cause it happen with April03 too. Don't known when this bug started but, in my memory, it was OK in the begining of March.

**Comment by gonetz** [comment]
Fixed

**Comment by baptiste0602** [comment]
I confirm, good job
