### ISSUE TITLE
Mario Golf FB emulation causes crash

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#357]
PJ fails to load game  with copy FB  to RDRAM is selected.

**Comment by gonetz** [comment]
Please check with latest build.

**Comment by Predator82Germany** [comment]
Here it works with all regions & NVIDIA

**Comment by Predator82Germany** [comment]
Here it works with all regions & NVIDIA

**Comment by theboy181** [comment]
working as it should again.
