### ISSUE TITLE
International Superstar Soccer 64 (All) - Gfx Issues

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#359]
From start til ingame there some errors

**Comment by gonetz** [comment]
Please add screenshots with errors.

**Comment by Predator82Germany** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/7068218/2ab69e62-ded1-11e4-95b3-3b29f54cc856.jpg)

**Comment by gonetz** [comment]
Thanks!

**Comment by baptiste0602** [comment]
Seems fixed

**Comment by olivieryuyu** [comment]
this is fixed so it should be closed
