### ISSUE TITLE
Lylat Wars - Crash On ROM-Start

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#363]
With all regions & NVIDIA

**Comment by baptiste0602** [comment]
I confirm with default settings.

No problem with these settings : 

[STARFOX64]
frameBufferEmulation\copyToRDRAM=0
frameBufferEmulation\validityCheckMethod=1

**Comment by gonetz** [comment]
The game crashes on copy to RDRAM. Buffer height calculated incorrectly.

**Comment by Predator82Germany** [comment]
With baptiste´s settings here it works but NVIDIA

**Comment by gonetz** [comment]
Crazy game allocates buffer of less size than necessary. How it works on real console?!

**Comment by gonetz** [comment]
Fixed.

**Comment by baptiste0602** [comment]
I confirm.
It also fix crash with copyColorToRDRAM for Zelda Majora's Mask (E) and Operation Winback (E).

Great job !

**Comment by Predator82Germany** [comment]
I didn´t have copyColorToRDRAM?

**Comment by baptiste0602** [comment]
It's the same as "Copy frame buffer to RDRAM". In mupen64plus, the option is named "EnableCopyColorToRDRAM"
