### ISSUE TITLE
Mario Party 3 - White Boxes Instead Of Blue Boxes With Stars

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#364]
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/7068925/1994c726-ded6-11e4-8446-6ebe4d8666fc.jpg)

**Comment by gonetz** [comment]
Which boxes? Chests must be white, tested with software LLE plugin.

**Comment by Predator82Germany** [comment]
I´ve got it there are white when empty
