### ISSUE TITLE
Super Smash Bros freeze during intro with copyDepthToRDRAM

### ISSUE THREAD

**Issue by baptiste0602** [gonetz/GLideN64#365]
It freeze (no crash and sound is OK) at this scene when copyDepthToRDRAM is enabled : 
![image](https://cloud.githubusercontent.com/assets/11183826/7068840/863efeec-ded5-11e4-9d28-d32f65b44d9a.png)

It freeze also when the intro is started and you press start.
You can bypass freeze if you press start at the N64 logo.

It happen also with older gliden64 builds.

Tested with (E) and (U) version.

**Comment by gonetz** [comment]
The game really incompatible with depth buffer copy. Need to set it off in the custom game settings.

**Comment by baptiste0602** [comment]
OK, i close the issue ?

**Comment by gonetz** [comment]
Yes. I can do nothing else with it.
