### ISSUE TITLE
Mega Man 64 (All) - Intro Squares

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#366]
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/7069113/4744ac44-ded7-11e4-8af2-d10b014f5617.jpg)

**Comment by purplemarshmallow** [comment]
correct in 1x native res

**Comment by paradadf** [comment]
Just an update to this issue:
Now, you don't see squares, but horizontal lines.
This happens every time you look at the sky, anywhere in the game.
![mega_man_64-000](https://cloud.githubusercontent.com/assets/15956550/23134567/93f8cfec-f795-11e6-96c4-6ceee74d1696.png)
Tested on a Raspberry Pi 2.
Here is an in-game savestate in case is helpful:
[Mupen64Plus Savestate](http://www.filedropper.com/megaman64u)

**Comment by theboy181** [comment]
Have you tried using n64 resolution textures?

**Comment by AmbientMalice** [comment]
The skies can only be fixed using native resolution or correct texrect coordinates hack set to forced. The seams on the terrain cannot be fixed without Angrylion's.

**Comment by GamingTVYT** [comment]
@AmbientMalice I'm using the emulator (Project 64) Plugin: GLIDEN64 rev.9a0b2665 and in the '' config '' in Emulation (Render 2D elements in N64 resolution (best ....) I chose 'Always'' the Background now this is without the black marks, but in the Background of the floor, it is possible to see minimal marks.
![project64 04-06-2018 07-14-03 avi_snapshot_00 01_ 2018 06 04_07 14 39](https://user-images.githubusercontent.com/30762805/40912105-034f92d4-67c7-11e8-9987-cc69d169d1d8.jpg)

**Comment by weinerschnitzel** [comment]
Floor looks like #1731

**Comment by gonetz** [comment]
Most likely the same issue.

**Comment by oddMLan** [comment]
Is this fixed with the S2DEX patreon build?

**Comment by olivieryuyu** [comment]
no

**Comment by oddMLan** [comment]
main issue fixed with "fix black lines in 2D elements" set to always
probably should be added to the custom ini

once that's done, this probably should be closed in favor of #1731

**Comment by gonetz** [comment]
> main issue fixed with "fix black lines in 2D elements" set to always
probably should be added to the custom ini

Yes.

> once that's done, this probably should be closed in favor of #1731

#1731 is not related to this one. And it has no simple fix as "fix black lines".
