### ISSUE TITLE
Micro Machines 64 Turbo (All)  - Everywhere Squares

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#368]
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/7069767/018015aa-dedb-11e4-88e0-86b9394ab190.jpg)

**Comment by purplemarshmallow** [comment]
correct in 1x native res

**Comment by olivieryuyu** [comment]
fixed with render 2D in native res.

@gonetz 

can it be closed?

**Comment by gonetz** [comment]
ok
