### ISSUE TITLE
Micro Machines 64 Turbo (All) - Ground Changes Brightness

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#369]
In race the ground changes his brightness every couple seconds

**Comment by Predator82Germany** [comment]
Now race didn´t start anymore

**Comment by AmbientMalice** [comment]
>Now race didn´t start anymore with all regions

Game works for me, but textures are misaligned and terrain changes brightness as camera moves, as though there were some massive shadowing problem.

**Comment by olivieryuyu** [comment]
![2cc298e4-356d-11e5-9309-19461c524605](https://cloud.githubusercontent.com/assets/8987490/9191160/09edb510-3ffe-11e5-9673-be8fd890c978.jpg)

**Comment by olivieryuyu** [comment]
cannot reproduce this bug

**Comment by olivieryuyu** [comment]
can we close?

**Comment by purplemarshmallow** [comment]
I can reproduce this bug

**Comment by gonetz** [comment]
Ok, reopen

**Comment by AmbientMalice** [comment]
I can't seem to reproduce it.

![gliden64_micromachines64turbo_000](https://cloud.githubusercontent.com/assets/10704701/14780638/25c60262-0b21-11e6-82ba-80ef7088cbcf.jpg)

**Comment by gonetz** [comment]
Me too
