### ISSUE TITLE
MRC  Multi Racing Championship - Intro Issue

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#370]
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/7070145/640405d6-dedd-11e4-8854-41e08c755354.jpg)
Let the game show til intro & see the right backlight when the garage opens
With all regions & NVIDIA

**Comment by olivieryuyu** [comment]
same in angrylion plugin

did you check on real hardware?

**Comment by Predator82Germany** [comment]
Haven´t the real hardware

**Comment by gonetz** [comment]
Tested on original HW. It looks the same.
