### ISSUE TITLE
San Francisco Rush  Extreme Racing (All) - Massive Flickering

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#373]
Same like #305

**Comment by olivieryuyu** [comment]
for me it is only black screen now

regression as we got the issue before i think

**Comment by Predator82Germany** [comment]
California Speed has the same problem may if´s a midway issue

**Comment by olivieryuyu** [comment]
seems really like a regression as it was solved at some point :(

**Comment by gonetz** [comment]
Frame buffer emulation must be set off for it.
Emulator calculates VI_H_START incorrectly. Frame height becomes zero each second frame. My VI  emulation code can't handle that.

**Comment by gonetz** [comment]
Fixed

**Comment by Predator82Germany** [comment]
All 3 fixed

**Comment by loganmc10** [comment]
@gonetz I am getting flickering in Rush Extreme Racing, can you confirm?

**Comment by gonetz** [comment]
Confirmed.

**Comment by olivieryuyu** [comment]
confirmed

**Comment by gonetz** [comment]
Seems to be a core issue. I have the same flickering issue with mupen64plus and al plugin.
The problem is that at some moment width of VI output image set in VI_H_START register is zero.
Since commit 3faa383c55 it leads to rendering of blank screen, thus the flickering.
Solution: use another buffer swap option. "On VI origin change" works without flicker.

**Comment by loganmc10** [comment]
So does this only happen with mupen64plus, did PJ64 ever have this issue?

**Comment by gonetz** [comment]
GLideN64 flickers with default settings with both mupen64plus and PJ64.
al plugin included in m64p distributive flickers too. I don't have fresh build of al plugin for PJ64.

**Comment by olivieryuyu** [comment]
same with PJ64 and angrylion + version 7

**Comment by gonetz** [comment]
So, most likely it is a core issue.

**Comment by loganmc10** [comment]
I doubt it, VI_H_START is just written by the game, the emulator core doesn't do any calculating to arrive at that value.

There is the possibility that the emulator should ignore a write of "0" for VI_H_START, but it's also possible that both GLideN64 and Angrylion aren't dealing with the case of VI_H_START=0 properly

**Comment by gonetz** [comment]
GLideN64 did nothing when VI_H_START=0 prior to commit 3faa383. Thus, current frame remained on screen and there was no flickering. It was changed because of #1715.
