### ISSUE TITLE
Star Soldier  Vanishing Earth - Cutted Screen

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#374]
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/7070848/e3adb1c0-dee1-11e4-95b7-6be84d4edacc.jpg)

**Comment by gonetz** [comment]
Can't reproduce.

**Comment by Predator82Germany** [comment]
It´s only the choose mode screen

**Comment by gonetz** [comment]
It's looks like this for me:
![gliden64_star_soldier_000](https://cloud.githubusercontent.com/assets/8983092/7072422/1a5c4b4c-df0e-11e4-85d0-fb87faf38525.jpg)

**Comment by Predator82Germany** [comment]
Again a NVIDIA problem?

**Comment by gonetz** [comment]
It's hardly NVIdia problem. I've uploaded new build, please test with it.

**Comment by Predator82Germany** [comment]
Still exist with 09Apr

**Comment by gonetz** [comment]
Still can't reproduce it. May be it is NVidia issue indeed. Need reports from other NVidia users.

**Comment by Predator82Germany** [comment]
Are there some?

**Comment by baptiste0602** [comment]
same problem on my nvidia

**Comment by gonetz** [comment]
OMG! What else can it be? Is anything in gliden64.log?

**Comment by baptiste0602** [comment]
nope

**Comment by Predator82Germany** [comment]
Was this sarcasm gonetz? ;)
No log

**Comment by baptiste0602** [comment]
FYI, it didn't happen in previous build (week26)

**Comment by gonetz** [comment]
It's not sarcasm. I need starting point to search the problem. So, it is something between Week 26 and Yesterday. I hope that Mupen64Plus build works the same. I'll prepare bunch of builds and upload them for you. You'll tell me, with which one the problem appears. Fastest way is to use Mupen64Plus command line. Unpack new plugin build and in command line prompt type/repeat mupen64plus.exe <rom file name>. I use that method when I need to find quickly a regression bug.

**Comment by gonetz** [comment]
A pack with test builds uploaded.

**Comment by baptiste0602** [comment]
It appears on 6_b623b6e

**Comment by Predator82Germany** [comment]
Right 1-5 works 6 & 7 are broken

**Comment by gonetz** [comment]
Fast answer, thanks!
I'll prepare new bunch of builds for commits between 5 and 6. We will catch it soon!

**Comment by gonetz** [comment]
New pack uploaded.

**Comment by Predator82Germany** [comment]
All broken

**Comment by gonetz** [comment]
Unexpected

**Comment by Predator82Germany** [comment]
Must be good for you :D

**Comment by gonetz** [comment]
Yes, only 2 options left. Uploaded.

**Comment by baptiste0602** [comment]
1 : OK, 2 : broken

**Comment by Predator82Germany** [comment]
Indeed

**Comment by gonetz** [comment]
Thanks! Now I know the bad commit. I'll try to guess, what's wrong with it.

**Comment by Predator82Germany** [comment]
Hope will be easy to find

**Comment by gonetz** [comment]
Uploaded first attempt to fix it.

**Comment by Predator82Germany** [comment]
Seems fixed

**Comment by gonetz** [comment]
Great! My guess is correct. Thanks for help!

**Comment by gonetz** [comment]
Uploaded. Please test and close if fixed.

**Comment by Predator82Germany** [comment]
Can´t test #294 cause a hang on MemPak message
Was it a little issue or a typo?

**Comment by gonetz** [comment]
You may clear mempack first.
It was an issue and not a little one.

**Comment by Predator82Germany** [comment]
Works
baptiste can you confirm?

**Comment by baptiste0602** [comment]
yes ! star soldier & knockout kings are OK
great job

**Comment by Predator82Germany** [comment]
#294 seems ok too
