### ISSUE TITLE
Wave Race 64 (E) - Bottom Cut

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#375]
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/7073076/332cddac-def1-11e4-9cd7-3e9afbf83c53.jpg)

**Comment by olivieryuyu** [comment]
hmm i would have thought it would be fixed with VI emulation

**Comment by gonetz** [comment]
VI emulation still not perfect.

**Comment by olivieryuyu** [comment]
I have 220 as per my calculation for the height.

**Comment by purplemarshmallow** [comment]
I found the problem. Here GLideN64 calculates the offset in RDRAM: https://github.com/gonetz/GLideN64/blob/485f2307efbe4ff545cefcc55d312737fdd4608b/src/FrameBuffer.cpp#L874 
Setting it to 0 fixes the problem. The VI can add black bars but this offset is not taken into account when these bars are drawn. So it's overlapping. This offset must be added somewhere.

But I can't find the code which displays the black bars

**Comment by AmbientMalice** [comment]
Fixed, I assume.

**Comment by gonetz** [comment]
Yes.
