### ISSUE TITLE
Mickey´s Speedway USA - Missing Textures

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#376]
Only with (E) & NVIDIA
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/7084893/0db42888-df72-11e4-9ed5-7f88ffc732c9.jpg)
![unbenannt2](https://cloud.githubusercontent.com/assets/6679921/7084894/0db4d9a4-df72-11e4-86c2-445000c1203e.jpg)
![unbenannt3](https://cloud.githubusercontent.com/assets/6679921/7084896/0db7be12-df72-11e4-931f-1eb8e669f3b7.jpg)
![unbenannta](https://cloud.githubusercontent.com/assets/6679921/7084895/0db74f4a-df72-11e4-9516-9c8cf145e612.jpg)

**Comment by Predator82Germany** [comment]
I think the problem is another one

I´ve set in the *.ini:
[MICKEY%20USA]
frameBufferEmulation\validityCheckMethod=1

[MICKEY%20USA%20PAL]
frameBufferEmulation\validityCheckMethod=1

but this don´t take affect the (E) rom

I must everytime when start the emu & game manually set to fill RDRAM to get it to work

Did GlideN64 have problems with more than one space in intern name?

**Comment by baptiste0602** [comment]
No problem for me with others games wich have 2 spaces in their internal name.

**Comment by gonetz** [comment]
Works for me too. Tracked in the debugger, the section is found and setting set correctly

[MICKEY%20USA%20PAL]
frameBufferEmulation\validityCheckMethod=1

**Comment by Predator82Germany** [comment]
With copyDepthToRDRAM=0 it works
F*** you NVIDIA

**Comment by baptiste0602** [comment]
yes, and i have the same problem

**Comment by gonetz** [comment]
It seems that I need NVidia card :(

Please try to find, when that problem appears first. You need to use my weekly builds for Mupen64Plus.

**Comment by baptiste0602** [comment]
It happened the first time in week25 build

**Comment by Predator82Germany** [comment]
Mupen don´t have this problem but don´t know if I have the right settings

**Comment by baptiste0602** [comment]
I have the problem in mupen64plus. Option is "EnableCopyDepthToRDRAM"

**Comment by Predator82Germany** [comment]
I do

**Comment by tony971** [comment]
I prefer the Mupen64Plus-Qt frontend but that's because my controller's already on the autoconfig.

**Comment by baptiste0602** [comment]
Same problem with Pokemon Snap

**Comment by Predator82Germany** [comment]
I don´t know why but Mickey works now
baptiste?

**Comment by baptiste0602** [comment]
are you sure ? it's not working for me

**Comment by Predator82Germany** [comment]
Argh ... no didn´t work, forgot that I set copydepth to 0 in *.ini :(

**Comment by gonetz** [comment]
It started on week 25 and still present in my latest fix for Star Soldier, right?

Let's try to fix it the same way as with Star Soldier.

**Comment by Predator82Germany** [comment]
Ok

**Comment by gonetz** [comment]
Hmm, it's not NVidia problem. I can reproduce it on my PC.

**Comment by gonetz** [comment]
Fixed

**Comment by Predator82Germany** [comment]
Indeed
