### ISSUE TITLE
Jet Force Gemini: Crash during intro cutscene in Project 64 using Recompiler Core

### ISSUE THREAD

**Issue by Mushman** [gonetz/GLideN64#377]
In Jet Force Gemini's introduction cutscene, Project 64 will crash when using GLideN64 if the Recompiler core is being used. The exact moment the crash happens is in the shot after Vela gets the alert with the grid on her monitor where Lupus runs from the front of the ship (before Juno throws his mug). The crash does not occur with other video plugins and is avoided if using the Interpreter core. The Recompiler core is used by default in Project 64 and is much faster than the Interpreter core.

It is present on all versions of GLideN64 I could test, from the Week 21 Bug Fix ``05572b0`` 25 February build to the Week 27 Second Fix ``277ff95`` 9 April build. Earlier builds are no longer available, so I could not test them to see if this bug is a regression. Changing GLideN64's settings does not affect the crash.

**Comment by LegendOfDragoon** [comment]
It's most likely the emulator's fault tbh. There's a general problem with Protect memory in certain games like this one, Zelda OOT, and even Super Smash Bros.

I say most likely just incase there may coincidentally be a bug in the graphics plugin.

Anyway, the problem I encountered in JFG (with protect memory + cpu recompiler) was with SP_DMA_WRITE. For whatever reason, there's a memory access violation. The weird thing is that when using LLE gfx with cpu recompiler + protect memory, there's some undefined behavior going on and most people won't see any error messages (but pj64 is supposed to show them). One way to get the error messages to show is to use _try{} __except(). I'm sure try catch would work too, just never tried it.

**Comment by Mushman** [comment]
Thanks for the info. If @gonetz finds that this is Project 64's fault too, I will log the issue on their tracker.

**Comment by LegendOfDragoon** [comment]
I reported the issue a while back, so zilmar is aware of the problem. You're welcome.

https://github.com/project64/project64/issues/17

**Comment by Mushman** [comment]
Heh, well never mind then. ;)

**Comment by Squall-Leonhart** [comment]
This issue no longer occurs.

**Comment by Alexn64gamer0712** [comment]
> This issue no longer occurs.

You sure? please tell me the exact settings and plugins so I can test it, thanks in advance

**Comment by Jj0YzL5nvJ** [comment]
> You sure? please tell me the exact settings and plugins so I can test it, thanks in advance

https://github.com/ata4/angrylion-rdp-plus/issues/136#issuecomment-1033651781
