### ISSUE TITLE
Armorines - Project S.W.A.R.M. missing lightning effect in HLE mode

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#381]
The bullets are used as light source. It works with GLideN64 with LLE gfx but not with HLE gfx
![swarm](https://cloud.githubusercontent.com/assets/7283660/7100956/a943c426-e03e-11e4-8626-ea2307d34e9a.png)

**Comment by gonetz** [comment]
Point lighting? Cool!

**Comment by AmbientMalice** [comment]
FYI, this is related to the missing dynamic lighting issue seen in Turok 2. https://github.com/gonetz/GLideN64/issues/147 (Shared Quagmire Engine.)

**Comment by gonetz** [comment]
Quagmire Engine? I have some docs about it. Need to dig them for a clue. Thanks for the info.

**Comment by AmbientMalice** [comment]
I goofed. Quagmire was the Acclaim sports game engine. The engine used by Acclaim Austin\UK FPS titles was simply referred to as "Turok" engine. Sorry for any confusion.

**Comment by purplemarshmallow** [comment]
Just curious
Why is there no fog in LLE? Is it a bug or is it not implemented? Maybe it's already working. I only have the new year beta

**Comment by gonetz** [comment]
Fog does not work in LLE because fog emulation needs correction. Currently plugin checks RSP flags to check that fog is enabled. LLE. needs something else.

**Comment by purplemarshmallow** [comment]
I'll open a new issue then

**Comment by gonetz** [comment]
Ok

**Comment by purplemarshmallow** [comment]
South Park uses the same engine? Same problem here
![gliden64_south_park_000](https://cloud.githubusercontent.com/assets/7283660/10116345/2e2d73a4-6432-11e5-8556-a77d6eb0dd5f.jpg)
![gliden64_south_park_001](https://cloud.githubusercontent.com/assets/7283660/10116348/3a016cf8-6432-11e5-9812-0c3ffde5414a.jpg)

**Comment by olivieryuyu** [comment]
damn turok2 & 3, south park and Armorines - Project S.W.A.R.M. All acclaim games. damn!

**Comment by AmbientMalice** [comment]
Yea, it would be absolutely fantastic if the Turok engine games could have working dynamic lighting in HLE.

**Comment by olivieryuyu** [comment]
it is really a microcode issue. If you take Foresaken from the same developer, which use F3DEX, then the Point lighting may work with normal microcode i think: 

I investigated other games that may use this method: 

Forsaken: just shoot and you will see that the lights is following the bullet.

![sans titre](https://cloud.githubusercontent.com/assets/8987490/19896783/c2697a1c-a055-11e6-9b00-08f3704ba799.jpg)

My wild guess is that the version 2 of F3DEX changed something in the light handling which is not correctly implemented. It is true that GBI.h shows some changes, no idea to which extents.

Is it possible??

**Comment by olivieryuyu** [comment]
another game: Quake2

you shoot a bullet, there is light, as point lighting, no?

![quake2](https://cloud.githubusercontent.com/assets/8987490/19897038/cac23540-a056-11e6-9f4d-609509b473dd.jpg)

This game uses the first version of the F3DEX.

**Comment by olivieryuyu** [comment]
we should combine the two tickets in one, meaning this one and #147

**Comment by gonetz** [comment]
I don't see how to link or combine two tickets.

**Comment by olivieryuyu** [comment]
perfect :)
