### ISSUE TITLE
San Francisco Rush 2049 - Black Screen

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#387]
With all regions

**Comment by olivieryuyu** [comment]
regression

damn: (

**Comment by gonetz** [comment]
The game does not like copy to RDRAM. I don't remember frame buffer usage in it. We can disable copy options in the ini.

**Comment by Predator82Germany** [comment]
Didn´t help

**Comment by gonetz** [comment]
Emulate FB on, all other options off. Validity method: checksum. Works for me.

**Comment by Predator82Germany** [comment]
Works with both copy off
copyToRDRAM=0
copyDepthToRDRAM=0

**Comment by Predator82Germany** [comment]
Set in *.ini?

**Comment by gonetz** [comment]
Already done
