### ISSUE TITLE
Spider-Man (U) - Flickering Push-Start-Screen

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#393]
(U)

**Comment by gonetz** [comment]
Seems to be fixed with latest build

**Comment by Predator82Germany** [comment]
Still there in this screen
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/7120538/1d86b66a-e20e-11e4-853c-02a411c99649.jpg)

**Comment by Predator82Germany** [comment]
Fixed
