### ISSUE TITLE
RTL World League Soccer (G) - Missing Textures

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#394]
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/7117872/e9dec76a-e1fb-11e4-99dc-a7d30c5872da.jpg)

**Comment by Predator82Germany** [comment]
Other regions of the game with same problem
Mia Hamm Soccer
Michael Owens WLS 2000
Telefoot Soccer 2000

**Comment by olivieryuyu** [comment]
duplicate of https://github.com/gonetz/GLideN64/issues/210

@gonetz 

can it be closed?
