### ISSUE TITLE
Donkey Kong 64 (E) - First Screen Issue

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#395]
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/7121040/f650ee2c-e211-11e4-9b37-97460953a3ed.jpg)

**Comment by olivieryuyu** [comment]
still valid bug. The Nintendo Logo simply does not appear. VI/FB issue i guess.

Here with Jabo

![dsfsdf](https://cloud.githubusercontent.com/assets/8987490/20642414/a5586876-b40e-11e6-84f6-81cf6d7ffb57.jpg)

**Comment by oddMLan** [comment]
CFB detection fails?

**Comment by oddMLan** [comment]
On the branch Feature_VI_Refactor, the logo shows up. But the size is wrong. The whole screen is squashed up. #1414 

![imagen](https://cloud.githubusercontent.com/assets/7278372/23845366/d91517ee-0784-11e7-8053-778cbc1537a3.png)

**Comment by gonetz** [comment]
> But the size is wrong.

No, it is correct for given window proportions. You may open that game with angrylion's plugin and get the same picture. It is PAL game. NTSC format has 480 lines, PAL 580. Simplest way to port NTSC game to PAL is to use only 480 lines, leaving black boarders on top and bottom. This is the case.

**Comment by gonetz** [comment]
If you want to see PAL game with NTSC proportions, set window size to 640x580 and set Aspect ratio to Stretch.

**Comment by oddMLan** [comment]
![imagen](https://cloud.githubusercontent.com/assets/7278372/23849170/ba4835e0-0797-11e7-8dc4-2340b7b34f3b.png)
My bad. You are correct that's the accurate output... I just thought it looked weird. I should check with angrylion's rdp beforehand to make sure, heh.

**Comment by gonetz** [comment]
Yes, good to know.

**Comment by olivieryuyu** [comment]
May be it can be closed?

**Comment by gonetz** [comment]
Yes, closed.
