### ISSUE TITLE
Buck Bumble (E) - Missing Textures

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#399]
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/7133825/59db57cc-e297-11e4-83fc-84ffdcec5ef4.jpg)

**Comment by Mushman** [comment]
Game works fine for me on Public Release 1 ``19caac1`` 1 May build, Project64 2.2 and NVidia Geforce GTX 970 with OpenGL 4.5.

**Comment by olivieryuyu** [comment]
i have no issue either. It should be closed

**Comment by Predator82Germany** [comment]
Can´t test cause #607

**Comment by AmbientMalice** [comment]
Seems fixed.

**Comment by olivieryuyu** [comment]
can it be closed?
