### ISSUE TITLE
black fog in nightmare creature is incorrect

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#40]
![sdfffffffffffff](https://cloud.githubusercontent.com/assets/8987490/5331422/5279ca98-7e2b-11e4-8919-f56820fc274c.jpg)

**Comment by gonetz** [comment]
The bug was very hard to find.
Fixed.

**Comment by olivieryuyu** [comment]
fixed!!!! 

yahoo :)
