### ISSUE TITLE
F1 Racing Championship (All) - Gfx Issues

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#403]
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/7134522/d2076424-e29d-11e4-98e3-65f7d9ade7c0.jpg)
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/7134528/f11dedc4-e29d-11e4-96ba-df3f724b7ea8.jpg)
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/7134554/3f387f1a-e29e-11e4-98a5-333af580a7d0.jpg)

**Comment by olivieryuyu** [comment]
this is fixed, can it be closed?
