### ISSUE TITLE
Pokemon Stadium missing ground texture

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#412]
In BATTLE NOW! the ground texture is missing/wrong.
Savestate Pokemon Stadium (U)(V1.0):
https://drive.google.com/file/d/0B7Y6r4SpC_QQenhuSTA2OTRrcDg/view?usp=sharing
GLideN64:
![1](https://cloud.githubusercontent.com/assets/7283660/7169649/d4def9a2-e3c7-11e4-895f-147275ee5bf0.png)
Glide64:
![2](https://cloud.githubusercontent.com/assets/7283660/7169688/1502de4a-e3c8-11e4-9c98-c9b6280e8bed.png)

**Comment by olivieryuyu** [comment]
hmm looks like a mip mapping issue :(

**Comment by gonetz** [comment]
Easy to check - turn LOD emulation off.

**Comment by purplemarshmallow** [comment]
looks the same with lod emulation turned off
I don't think this game uses mip mapping
maybe a combiner issue

**Comment by gonetz** [comment]
Most of games use mip-mapping, including Pokemon ones. This can be combiner, blending and hundred of other issues. I'll check it. Someday.

**Comment by gonetz** [comment]
It was tricky, well hidden legacy bug.

**Comment by gonetz** [comment]
Fixed.

**Comment by purplemarshmallow** [comment]
Fixed :)
