### ISSUE TITLE
Conker's BFD: missing framebuffer effect

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#413]
Savestate: https://drive.google.com/file/d/0B7Y6r4SpC_QQQnBCTFhMYnBZN28/view?usp=sharing
GLideN64:
![1](https://cloud.githubusercontent.com/assets/7283660/7170214/6117fd2a-e3cc-11e4-9643-8470db299175.png)
Glide64:
![2](https://cloud.githubusercontent.com/assets/7283660/7170216/687c904e-e3cc-11e4-99bc-79453cb6b1a2.png)

**Comment by gonetz** [comment]
Thanks for the savestate. I'll check it.

**Comment by purplemarshmallow** [comment]
regression
works with new year beta

**Comment by gonetz** [comment]
It's not plugin's regression. Effect works with Project64 2.1

**Comment by purplemarshmallow** [comment]
That's strange. It never works for me. Not with Project64 2.2 not with 2.1. I also tested 1964 and Mupen and the effect never works. So I don't think it's the emulator's fault. Can anyone else test this? Maybe it's a driver bug. I have a Nvidia GPU.

**Comment by baptiste0602** [comment]
I have the same problem as purplemarshmallow.

**Comment by purplemarshmallow** [comment]
thanks for the testing
also all 2d elements disappear if I disable framebuffer emulation
![1](https://cloud.githubusercontent.com/assets/7283660/7242319/9fd197da-e7c1-11e4-825d-9aaece3172dd.png)

**Comment by gonetz** [comment]
So it worked on NVidia with NY beta. Currently it does not work. NY beta was only for mupen64lus. Could you check the problem with the current mupen64plus build?

**Comment by purplemarshmallow** [comment]
Yes, it worked on Nvidia with NY beta. And it does not work with the current mupen64plus build. But I tested the current zilmar spec version in LLE mode and the effect works there.

**Comment by gonetz** [comment]
> I have the same problem as purplemarshmallow. Nvidia card.

Could you help me with testing?

**Comment by baptiste0602** [comment]
Ok,  i'll try tonight to find when regression happened the first time.

**Comment by gonetz** [comment]
We can try to fix it the same way as with previous NVidia issues: I'll prepare pack of builds, you will check them. Three-four iterations and I'll know where I broke it.

**Comment by Predator82Germany** [comment]
I can then only help when I know the button to start zoom

**Comment by gonetz** [comment]
It is "left" or "right" trigger, don't remember exactly. I'll prepare the pack with mupen64plus builds and send it to you both. Thanks in advance.

**Comment by Predator82Germany** [comment]
need a mupen-savestate

**Comment by gonetz** [comment]
Hmm, I don't have it. It's one of multiplayer mini-games.

**Comment by Predator82Germany** [comment]
Mupen-input is so ...
Can´t get to mini-games

**Comment by Predator82Germany** [comment]
Got it:
1 & 6 crashing
2 - 4 working
5 & 6 with the issue

**Comment by gonetz** [comment]
Thanks! I'll make new pack with builds between 4 and 5

**Comment by Predator82Germany** [comment]
4 & 5 did work
You mean between 5 & 6?

**Comment by Predator82Germany** [comment]
Pack2: All work

**Comment by gonetz** [comment]
You said 4 ok 5 with issue

**Comment by Predator82Germany** [comment]
Have written wrong but corrected under a minute sorry

**Comment by gonetz** [comment]
Ok, new pack

**Comment by Predator82Germany** [comment]
1 & 2 work
3 crashes

**Comment by gonetz** [comment]
New pack.
No need to test everything. I need first bad commit.

**Comment by Predator82Germany** [comment]
2 starts the issue

**Comment by baptiste0602** [comment]
I confirm !

**Comment by gonetz** [comment]
Good news: now I know exact commit which causes that problem.
Bad news: that commit fixes Conker's shadow. 
Very bad news: as I can see it has nothing with OpenGL. I also must see that problem on my PC.

Please give me the savestate, which you use to test the problem.

**Comment by Predator82Germany** [comment]
http://www75.zippyshare.com/v/BLjqn1EV/file.html

**Comment by gonetz** [comment]
A, what is it? Savestate? How to load it?
It should be something like "Conker's Bad Fur Day (U) [!].st0"

**Comment by baptiste0602** [comment]
https://drive.google.com/file/d/0ByOA3_oOu6O9aGtfeHVNVW9wRUU/view?usp=sharing

**Comment by gonetz** [comment]
Thanks!

**Comment by gonetz** [comment]
The same code works with PJ64 2 and does not work with mupen64plus.

**Comment by baptiste0602** [comment]
You speak about which code ? Cause on Early release and Nvidia, this effect doesn't work on mupen64plus and PJ64 2.

**Comment by gonetz** [comment]
NVidia does not matter here. There is a code, which discard some part of graphics if some condition is met. Zoom effect triggers that code with mupen64plus and with Project64 2.2
Project64 2.1.0.1 does not trigger that, I just checked it in debugger. Thus, the effect works with Project64 2.1.0.1. It must work for you too. There is nothing here which can be hardware dependent.

**Comment by Predator82Germany** [comment]
Shadow LGTM
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/7315623/76f466de-ea6f-11e4-803d-54f3ff1d3a40.jpg)
but broke Pause-Screen
![unbenannt2](https://cloud.githubusercontent.com/assets/6679921/7315624/76f506ca-ea6f-11e4-91a1-ebd8c2549c53.jpg)

**Comment by gonetz** [comment]
No no no! We agreed not to put different bugs into the same bugreport. Pause screen in Conker did not work with mupen64plus before my fix.

Is the initial problem fixed? Yes.
Does it cause new issues, which were not there before the fix? If no NEW issue found, the bugreport can be closed.

**Comment by Predator82Germany** [comment]
Ah ... I thought the Pause-Screen issue comes with your last fix
I think it can be closed

**Comment by gonetz** [comment]
Ok. closed.
I found issue with pause screen in mupen64plus. Fixed. No need to open new bugreport.

**Comment by gonetz** [comment]
Thanks for help :)

**Comment by purplemarshmallow** [comment]
Strange
I tested Project64 2.1.0.1 and there was no difference
That's why I thought it might be related to Nvidia
But it does not matter anymore if it's fixed now

**Comment by baptiste0602** [comment]
Great work Gonetz, thanks to you.
