### ISSUE TITLE
Pokemon Stadium 2 framebuffer validity check fails

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#416]
There are many glitches with the default validity method (checksum). They are all gone if "fill RDRAM" is used instead. But after more careful testing I noticed that this may cause freezes when entering/exiting the Pokemon Lab. Using the pokedex in the lab always results in a freeze. The rest of the game works fine with "fill RDRAM". Entering the pokemon lab requires transfer pack emulation.
![1](https://cloud.githubusercontent.com/assets/7283660/7188807/a520d1fa-e47a-11e4-9a53-911180da7d15.png)
![2](https://cloud.githubusercontent.com/assets/7283660/7188810/a85b95b2-e47a-11e4-8aa0-b3c482bca001.png)
![3](https://cloud.githubusercontent.com/assets/7283660/7188811/ab17348c-e47a-11e4-90a0-466aa4e29eca.png)
![4](https://cloud.githubusercontent.com/assets/7283660/7188816/ad7cea8c-e47a-11e4-9e32-e329039c0c60.png)

The Pokemon Lab:
![5](https://cloud.githubusercontent.com/assets/7283660/7188984/fea9c1a4-e47b-11e4-8ba6-9e28fd791841.png)

**Comment by gonetz** [comment]
I have an idea for new validity check method. It may replace the both methods which are currently used. I need volunteers to check it. If you are ready for extensive testing, drop me a line by email. I need your mail to send test builds.

**Comment by purplemarshmallow** [comment]
sent you an email

**Comment by purplemarshmallow** [comment]
I found out that "fill RDRAM" is safe for this game. With the early release build it only causes crashes if "copy frame buffer to RDRAM" is enabled at the same time. With the latest build it is always safe. Maybe because a bug has been fixed. Fingerprint method works most of the time but not always. So I recommend the following settings:

[POKEMON%20STADIUM%20G&S]
Good_Name=Pocket Monsters Stadium GS (J)
frameBufferEmulation\validityCheckMethod=1
frameBufferEmulation\copyToRDRAM=0
frameBufferEmulation\copyDepthToRDRAM=0

[POKEMON%20STADIUM%202]
Good_Name=Pokemon Stadium 2 (E)(F)(G)(U)
frameBufferEmulation\validityCheckMethod=1
frameBufferEmulation\copyToRDRAM=0
frameBufferEmulation\copyDepthToRDRAM=0

frameBufferEmulation\validityCheckMethod=1 because fingerprint method does not always work for this game and the crashes are gone
frameBufferEmulation\copyToRDRAM=0 and frameBufferEmulation\copyDepthToRDRAM=0 because both setting cause crashes with some rom versions (#410) and copyToRDRAM used to cause crashes in combination with frameBufferEmulation\validityCheckMethod=1

**Comment by gonetz** [comment]
Ok, thanks!

Cite: "frameBufferEmulation\validityCheckMethod=1 because fingerprint method does not always work for this game and the crashes are gone" - too good to be true :) Crossing fingers.

**Comment by Predator82Germany** [comment]
Your Pocket Monsters Stadium GS is named Pokemon Stadium Kin Gin here

**Comment by purplemarshmallow** [comment]
The japanese version has a different internal name
I think it's "POKEMON STADIUM G&S"

**Comment by Predator82Germany** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/7349310/562fa536-ecf8-11e4-8161-a22f92bdbdc5.jpg)

**Comment by purplemarshmallow** [comment]
Now I know what you mean
Yes I made a mistake
Good_Name is Pokemon Stadium Kin Gin (J)

**Comment by purplemarshmallow** [comment]
But if I think about it again I'm not sure what's the right thing to do.
fingerprint method works most of the time exept for some rare cases
and fill RDRAM is dangerous but it seems to be safe

**Comment by Predator82Germany** [comment]
Why dangerous?

**Comment by purplemarshmallow** [comment]
"fill RDRAM" may cause crashes but I havent noticed any

**Comment by Predator82Germany** [comment]
Crashs are normal but dangerous?

**Comment by purplemarshmallow** [comment]
What?
Crashes are not normal
The game shouldn't crash

**Comment by Predator82Germany** [comment]
I mean sometimes crashes windows & it´s not really dangerous

**Comment by purplemarshmallow** [comment]
situation is like this:
If we add frameBufferEmulation\validityCheckMethod=1 to the ini framebuffer emulation will be perfect but the plugin will use dangerous writes to RDRAM
If we don't add it framebuffer emulation will work exept for a few rare cases

@gonetz has to decide

**Comment by purplemarshmallow** [comment]
sorry but I have to open it again
I noticed that there are problems with fill RDRAM
If I return to the title screen after Battle Now! this happens:
![gliden64_pokemon_stadium_2_016](https://cloud.githubusercontent.com/assets/7283660/7647204/01a2b7a6-fad1-11e4-9612-7db492cae439.jpg)
this does not happen with fingerprint but fingerprint sometimes breaks portraits:
![gliden64_pokemon_stadium_2_017](https://cloud.githubusercontent.com/assets/7283660/7647224/4682efd0-fad1-11e4-92dd-824bbe314d06.jpg)
so no validity check method is good enough for this game
#215 same problem

**Comment by purplemarshmallow** [comment]
In the library images are often missing/corrupt with both fill RDRAM and write fingerprint to RDRAM
images work with checksum so it must be a problem with framebuffer validity checking
see #542 for more details
![gliden64_pokemon_stadium_2_016](https://cloud.githubusercontent.com/assets/7283660/7728107/86c5267c-ff0d-11e4-881e-5efb3745338b.jpg)

**Comment by purplemarshmallow** [comment]
the problem is with treshold level
if I make it higher images appear correctly but backgrounds break

**Comment by purplemarshmallow** [comment]
fixed by #619
