### ISSUE TITLE
Zelda OoT Window Toggle Menu Bug

### ISSUE THREAD

**Issue by shinra358** [gonetz/GLideN64#417]
This has existed ever since glide was born but maybe if I mention it, it could be looked at this time around since the n64 scene is progressing. When you are in the item menu, and you toggle to window mode from fullscreen mode and vice versa, the background of the menu either turns black or becomes rainbow colored. It doesn't revert until you have closed the menu by pressing start.

**Comment by gonetz** [comment]
It's not a bug.
I already explained that in another issue.
Many N64 games keep dynamically created graphics in auxiliary frame buffers. When graphics plugin uses hardware rendering and hardware frame buffer emulation, it keeps that graphics in temporal video buffers. Settings change or video mode change causes reset of all GL resources and your temporal buffers lost. You must return to the point where these buffers were created to get them back.
