### ISSUE TITLE
Blast Corps background missing

### ISSUE THREAD

**Issue by Aquatakat** [gonetz/GLideN64#418]
![ss 2015-04-17 at 01 14 26](https://cloud.githubusercontent.com/assets/9537912/7209224/c2996858-e503-11e4-9d49-c4efafc5eeaf.jpg)

Where the background used to render it now does the Solitaire win style style copying of each frame.

**Comment by purplemarshmallow** [comment]
Blast Corps hack causes this problem

**Comment by Stu1983** [comment]
is there a way to disable the hack?

**Comment by purplemarshmallow** [comment]
The hack was made to fix the black polygon flickering problem. So if you remove the hack this problem will reappear. But only in HLE LLE will work fine. It's a microcode problem. However LLE has problems with drawing lines.

To disable the hack you have to edit the source and compile the plugin.
