### ISSUE TITLE
custom.ini Mario Golf not working

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#419]
GLideN64.custom.ini "MARIOGOLF64" settings do not work. You can change the values but it has no impact on the game.  When using the GUI settings it does work. 

I tested the .ini by changing Mario Tennis, and the settings that I changed worked for that game.

**Comment by gonetz** [comment]
I did a simple test: disable fb emulation in the GLideN64.custom.ini
[MARIOGOLF64]
Good_Name=Mario Golf (E)(J)(U)
frameBufferEmulation\enable=0

GLideN64.ini is default. Run Mario Golf - no fb emulation.
Which settings from the custom ini do not work for you?

**Comment by theboy181** [comment]
This was related to the default FB emulation settings on. was hoping you would want all setting that are required to be I. The ini.

**Comment by theboy181** [comment]
frameBufferEmulation\enable=0 

Was added to the ini??

are you just messing with me now or does this fix FB emulation some how?

**Comment by Predator82Germany** [comment]
You should test with frameBufferEmulation\enable=0 if it read from *.ini´s

**Comment by gonetz** [comment]
You said that custom ini settings do not work for MarioGolf. I disabled fb emulation in custom settings just to prove that custom settings actually work for this game.

**Comment by theboy181** [comment]
the actual problem what that there were missing settings in the ini..

I reported that and @oliveryouyou said that they were the default settings to they were not needed.

I have sent the correct settings since then ..

**Comment by gonetz** [comment]
So, it's just a misunderstanding.
My position for default settings: if come setting is essential for correct game work its better to put it to the custom ini. If user will change default value of the settings, the game will still work correct.

**Comment by Predator82Germany** [comment]
Should we then all put in?

**Comment by gonetz** [comment]
What do you mean by "all'?

Most of games works ok with any set of frame buffer options, except N64 depth compare.
We don't put such games to custom section.

If we know that Zelda will work incorrect without depth buffer copy, better to put it in the ini. Depth buffer copy is on by default, but if user will set it off, the game still will work correct.
If some option does not matter for the game, don't include it to custom ini. For example, Zelda will work correct with any value of "Detect CPU writes" setting. So, we don't put it in the custom section for Zelda.

**Comment by Predator82Germany** [comment]
I mean when we set it in custom.ini while it´s default, so we should all needed one´s take in there
