### ISSUE TITLE
error and missing settign found in config

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#422]
Please replace with the following

[1080%20SNOWBOARDING]
Good_Name=1080 Snowboarding (JU) (M2)
frameBufferEmulation\copyDepthToRDRAM=1 ;Needed for lens flares

[MARIOGOLF64]
Good_Name=Mario Golf (E)(J)(U)
frameBufferEmulation\copyDepthToRDRAM=1 ;Needed for lens flares
frameBufferEmulation\validityCheckMethod=1 ;fix corrupt textures

1080 had the following setting, but I am unsure why.

video\multisampling=0 ; works with AA on unsure of setting choice

**Comment by olivieryuyu** [comment]
copyDepthToRDRAM=1 is by default normally

**Comment by theboy181** [comment]
I guess, but I figured that the config file should have the required settings in the config file, no?

**Comment by olivieryuyu** [comment]
no it is by default. you only need to add the non default options normally.

**Comment by AmbientMalice** [comment]
@olivieryuyu Considering GLideN64 uses global settings, it may prove necessary to force games to use certain settings to prevent well intentioned tweakers from breaking huge chunks of the N64 library. For example, per-pixel lighting is disabled by default. But if someone enables it, it is enabled for all games - and therefore causes heaps of games to crash, they are likely to become frustrated. Same goes for how anti-aliasing causes games to crash currently.

**Comment by theboy181** [comment]
@gonetz 
I tend to agree with @AmbientMalice. This is also how Dolphin handles there per game settings too. I was under the impression this is how the ini worked.

**Comment by gonetz** [comment]
> For example, per-pixel lighting is disabled by default. But if someone enables it, it is enabled for all games - and therefore causes heaps of games to crash, they are likely to become frustrated.
Why do you think that per-pixel lighting can cause crash? If you know any example, please open an issue for it.

>Same goes for how anti-aliasing causes games to crash currently.
I know no example where anti-aliasing causes games to crash. I know only cases where AA causes improper work of frame buffer effects. 1080 is an example, that's why it is set off in the ini.

>copyDepthToRDRAM=1 is by default normally
Yes, it's true, so the setting looks redundant. However I prefer the settings, which are essential for correct game work be explicitly put in the custom section. This is another hint for developers too.
From the other side, if you are not sure that particular setting is necessary, do not include it.

**Comment by AmbientMalice** [comment]
>Why do you think that per-pixel lighting can cause crash? If you know any example, please open an issue for it.

I can't remember where I encountered it. It may have been an LLE thing. I'll do some testing.

>I know no example where anti-aliasing causes games to crash. I know only cases where AA causes improper work of frame buffer effects. 1080 is an example, that's why it is set off in the ini.

If I boot Perfect Dark with AA enabled, and then open GLideN64's configuration menu while the game is running, the emulator will crash. This doesn't happen with AA disabled.

**Comment by gonetz** [comment]
>If I boot Perfect Dark with AA enabled, and then open GLideN64's configuration menu while the game is running, the emulator will crash. This doesn't happen with AA disabled.

It's not the same as "AA causes game to crash", don't you think? I'll check that scenario. Most likely some variable not cleared properly before GUI call.

**Comment by gonetz** [comment]
https://github.com/gonetz/GLideN64/commit/d4dce42e0d1e50d7c1db83e10ba76de07e5f11b0

Can we close that issue?

**Comment by theboy181** [comment]
Just to be clear you do want the FB settings even if the default has them?

**Comment by gonetz** [comment]
If some setting is essential for correct work of the game, I prefer it to be in the custom settings, even if default value is the same. The user may change default value of a setting, but game will still work correct.

**Comment by theboy181** [comment]
Thanks I thought hat was the direction.
