### ISSUE TITLE
Mystical Ninja Starring Goemon Graphic Corruption

### ISSUE THREAD

**Issue by GreyAlien** [gonetz/GLideN64#423]
Seems to be a number of issues with this game. The biggest one is that textures on the background appear to get corrupted.

Also one of the main character's eyes are not displayed at all. Both isues are shown in the screenshots below.

This one uses glide64 which displays how the game should look a lot better.
![glide64](https://cloud.githubusercontent.com/assets/12082395/7294845/cebad262-e9a8-11e4-85e2-f1645c778d55.jpg)

With gliden64. The graphic corruption is pretty obvious.
![gliden64](https://cloud.githubusercontent.com/assets/12082395/7294955/b7bfcd6e-e9a9-11e4-957a-1be3ab2b65ca.jpg)

**Comment by AmbientMalice** [comment]
Occurs on PJ64, too.

![8gliden64_mystical_ninja_000](https://cloud.githubusercontent.com/assets/10704701/7310054/4212b732-ea69-11e4-8c9c-c8fb1b5b7350.jpg)

Issue looks very similar to texture corruption in Operation Winback when you look in certain directions.

![untitled](https://cloud.githubusercontent.com/assets/10704701/7310061/50cf0500-ea69-11e4-807d-7e37b481349d.jpg)

These bugs are also present in the New Year Beta.

**Comment by stranno** [comment]
Same issue on Mupen64Plus 2.5.

**Comment by AmbientMalice** [comment]
Seems to be fixed in 1.1 release.

**Comment by stranno** [comment]
Yes, no problems so far in 1.1.

![20150509170339](https://cloud.githubusercontent.com/assets/6293197/7550750/dfb298e4-f66d-11e4-8726-6e9418781181.png)
![20150509170029](https://cloud.githubusercontent.com/assets/6293197/7550751/dfb6996c-f66d-11e4-94b6-d005f9b1a89e.png)

**Comment by GreyAlien** [comment]
Does indeed seem fixed. Even some small issues of the floor exterior appearing black which was present in the first public release have been fixed also. Looks like this can be closed then.
