### ISSUE TITLE
Mario Tennis 64 (J) score board black

### ISSUE THREAD

**Issue by exhalatio** [gonetz/GLideN64#424]
JPN version only Score Board is black.
Internal romname is MarioTennis64.
![mt64](https://cloud.githubusercontent.com/assets/7089513/7317429/c4352040-eabb-11e4-9523-3373daece227.jpg)

**Comment by Predator82Germany** [comment]
Fixed in (J) but exist in (E)

**Comment by gonetz** [comment]
OMG!

That is what happens when you can't find general solution and uses dirty hacks :( Hacks are evil.

**Comment by Predator82Germany** [comment]
All regions now work

**Comment by gonetz** [comment]
Thanks!
Closed.
