### ISSUE TITLE
Goldeneye mipmap Issue

### ISSUE THREAD

**Issue by Tasosgemah** [gonetz/GLideN64#426]
This is how the trees look in "Surface" level in Goldeneye:

![untitled](https://cloud.githubusercontent.com/assets/12124465/7337865/dab190f6-ec41-11e4-81dc-426fa29aaabc.jpg)
I think the issue is the new mipmap system.

**Comment by gonetz** [comment]
Is mip map emulation enabled?
Could you give me a savestate?

**Comment by Tasosgemah** [comment]
Yes its with mipmap enabled.

How can i send you my save files?

**Comment by baptiste0602** [comment]
I confirm this issue.

**Comment by AmbientMalice** [comment]
Assuming the trees aren't that blurry on a real N64/Angrylion's, likely related to this. https://github.com/gonetz/GLideN64/issues/158

**Comment by Tasosgemah** [comment]
No, they are not that blurry on the real N64.

**Comment by olivieryuyu** [comment]
looks the same issue than the carpet in PD

**Comment by gonetz** [comment]
I tried to load your saves, but I don't see the problem as on your screen shot. Please give me a savestate which will teleport me right to the problem.

**Comment by purplemarshmallow** [comment]
https://drive.google.com/file/d/0B7Y6r4SpC_QQNnhJM2pDWUxlV2c/view?usp=sharing
But it's for (E) version

**Comment by Tasosgemah** [comment]
Gonetz, if the saves work, all you have to do is chose the "surface" level in the mission select screen. Onle loaded you will be at the exact spot as it's the beginning area of the mission.

But i will try and send you a quick save anyway.

**Comment by gonetz** [comment]
Thanks. I see the problem.

**Comment by AmbientMalice** [comment]
Bug is now fixed by changes for https://github.com/gonetz/GLideN64/issues/158 so this issue can be closed, I think.

**Comment by olivieryuyu** [comment]
please close

**Comment by AmbientMalice** [comment]
@Tasosgemah please close?
