### ISSUE TITLE
Perfect Dark visor and lighting issues

### ISSUE THREAD

**Issue by herpderpus** [gonetz/GLideN64#427]
Night visor and IR visor should highlight enemies when in use, the effect is emulated using Glide64 that comes with PJ64 2.2, but not in GlideN. IR visor should also highlight certain elements such as invisible enemies.

Also darkness is not emulated correctly as moving polygons are not affected by darkness and are fully illuminated in GlideN.

Also despite my PC being pretty high end (3570K and 660Ti) as soon as something uses some kind of special effect in game (visor, motion blur after getting punched, camspy) the framerate drops noticeably.

Glide64 PJ64 edition on the left, GlideN64 on the left.

![glntest](https://cloud.githubusercontent.com/assets/12128480/7339845/ad0eeb54-ec7c-11e4-8eca-d48166868d1f.jpg)

There's no need to provide a save state, all you have to do is enable cheats, enable unlock all levels, and load up mission 3 where you can test the visor and darkness as the level begins during a blackout. I can still provide one if it's needed.

Using PJ64 2.2.

**Comment by AmbientMalice** [comment]
I was gonna make an issue about this, but didn't want to swamp Gonetz. It's a regression, since the lighting worked in the New Year's Beta.

Interestingly, Jabo's plugin suffered from this same issue.

**Comment by gonetz** [comment]
@herpderpus I've fixed the issue. I need your email to send you the fix to test.

**Comment by gonetz** [comment]
Fixed

**Comment by herpderpus** [comment]
I'll test it gladly, my email address is xboy.alt at gmail dot com.

**Comment by gonetz** [comment]
Ok, please close the bugreport
