### ISSUE TITLE
Banjo Kazooie & Tooie (U) Flickering / VI Issue

### ISSUE THREAD

**Issue by thecoreyburton** [gonetz/GLideN64#429]
I do not have MupenPlus working, so this report has been worked out using Mupen + the Zlimar spec plugin.

When running the early release build of GLideN64, I've noticed an issue that is immediately apparent on Banjo-Kazooie (U) (1.0). There's a weird sort of flickering going on, it's almost as if it's rendering the frames out of order, eg. 2, 1, 4, 3, 6, 5, 8, 7 etc. I ran the 1.1 rom and the issue wasn't present.

Turning off "emulate frame buffer" removes this issue, but then of course the game doesn't look right and the jigsaw transitions no longer work. This issue may be present in other roms too. It does not appear to be an issue when using Project 64 however, maybe a separate build for Mupen is required using the zilmar spec but having some sort of fix?

To update, the issue is also present in the 1.1 rom, it's just less frequent and less noticable but still apparent during the title song. It seems to be apparent in Banjo Tooie, too.

Here are two very brief encodes to illustrate the problem: https://www.dropbox.com/s/bm2yzw0brn3xxg0/gliden64-flicker-release.zip?dl=0

**Comment by thecoreyburton** [comment]
I believe this could be the same issue: https://github.com/gonetz/GLideN64/issues/301

**Comment by gonetz** [comment]
Mupen does something unexpected with VI registers when emulates Banjo-Kazooie. My code goes crazy. Currently I may suggest only to use other emulators.

**Comment by thecoreyburton** [comment]
Ah well, I was hoping to encode some old TAS videos with the new plugin. I guess I'll have to wait!

Thank you for your fast reply & all the hard work you've put in to this, we're all so grateful and you've done a fantastic job!

**Comment by DonelBueno** [comment]
Why does GLide64 have black bars on top and bottom of the screen in all games?

**Comment by thecoreyburton** [comment]
My best bet is that the original games were programmed with overscan in mind. Old CRT screens weren't able to display the entire frame, the outside of the frame was cut off my some models, and the amount and location of this varied from model to model. If I'm not mistaken developers put in black areas to account for this. Games like Chameleon Twist 2 have large amounts of overscan whilst games like Super Mario 64 have little. Unless of course you're talking about something different!

**Comment by DonelBueno** [comment]
Well, it that was the case, there would be black bars on the sides too, but that's not the case.

Also, Angrylion's plugin doesn't show them.

**Comment by gonetz** [comment]
It does.

**Comment by gonetz** [comment]
For example, Mario Tennis. I compared black borders width with my plugin and Angrylion's one. The same.

**Comment by thecoreyburton** [comment]
I've also noticed that once the mosquito hits the rareware logo at the start it's meant to fade out to white, but it sorta just suddenly changes out of the blue. Only pixel accurate plugins seem to have this fixed.

**Comment by Mushman** [comment]
Developers for BizHawk had expressed interest on the backer forums for implementing GLideN64, so you shouldn't have to use Mupen for much longer.

The issue you mentioned in your last comment is something I've noticed in other games for transitions. It might be a minor bug, but I certainly would like to see it fixed. Maybe create another issue for it?

**Comment by thecoreyburton** [comment]
Yeah, good idea. I'm active on those forums too (if you look in the Bizhawk dev thread I asked about this plugin when Early Release came)! :)

**Comment by GamingHD** [comment]
This has been fixed, it seems.

**Comment by olivieryuyu** [comment]
please close as it seems to be ok

**Comment by thecoreyburton** [comment]
Issue is resolved.
