### ISSUE TITLE
Chameleon Twist 2 Pre-Boss 

### ISSUE THREAD

**Issue by thecoreyburton** [gonetz/GLideN64#430]
When you jump on the platform to visit any boss at the end of any level in this game, the screen is supposed to fade out as seen here (not my video): at 5:42, in case the timestamp doesn't work: https://youtu.be/bmjWJoQ2lNI?t=342

It's never worked in a Glide plugin as far as I know, but has worked in others such as Jabo. It's not a major issue as it doesn't affect the playability of the game.

**Comment by olivieryuyu** [comment]
do u have a save state?

**Comment by thecoreyburton** [comment]
There you are. Just jump on the purple platform in front of you to trigger the glitch.
https://www.dropbox.com/s/i38yec6zk7rg8je/Chameleon%20Twist%202%20%28U%29%20%5B%21%5D.st0?dl=0

**Comment by thecoreyburton** [comment]
I made a Project 64 savestate of the same problem and tested it in angrylions plugin, the bizarre glitchy effect is still present. I'm willing to close this issue, but I want a second opinion first. Do you think the game is supposed to actually react like this or could it be an emulation error? I can't recall if it did that on the console or not.

https://www.dropbox.com/s/aemx8kuv4sj4v82/ending.pj.zip?dl=0

**Comment by thecoreyburton** [comment]
I take it nobody actually cares about this, and I think the bug is actually part of the game itself and other plugins somehow avoided emulating it.

Seeing as this means GLideN64 is being faithful to the console, I'm closing this unless someone has evidence to the contrary.
