### ISSUE TITLE
Rom Hack Textures

### ISSUE THREAD

**Issue by thecoreyburton** [gonetz/GLideN64#431]
One final issue from me, this time regarding rom hacks (so I'd say this is very low priority, but still worth noting): Super Mario 74 worked fine in Glide64, but pretty much all "new" textures, textures that weren't present in the original game, come out pure black in GLideN64. To replicate this issue, simply load this pre-patched rom and start the game in any save slot: https://www.dropbox.com/s/1qjt24ngsgb9wfd/Super%20Mario%2074.z64?dl=0

**Comment by purplemarshmallow** [comment]
I tested Super Mario 74 with angrylion's pixel accurate plugin. The new textures don't work. And most likely they wouldn't work on real hardware.
So GLideN64 is doing nothing wrong and this is accurate emulation.

**Comment by thecoreyburton** [comment]
Thanks! I only compared it to Glide64, I probably should have thought of that myself. I'm happy to consider this closed.
