### ISSUE TITLE
Build for GLES2

### ISSUE THREAD

**Issue by sergiobenrocha2** [gonetz/GLideN64#432]
Maybe a stupid question, but does cmake detect GLES2? It seems it only search & config for desktop OpenGL. It could be nice to compile for boards like raspberry pi 2 and odroid.

**Comment by gonetz** [comment]
You may set GLES2 define in cmake input parameters, like -DGLES2=On

**Comment by sergiobenrocha2** [comment]
Didn't work

-- Found OpenGL: /usr/local/lib/libGL.so

CMake Warning:
   Manually-specified variables were not used by the project: GLES2

**Comment by gonetz** [comment]
Yes, my cmake project file does not use GLES2 variable.
You need to correct the project for your needs. If you need GLES specific settings in the project and you don't know how to detect GLES support with cmake, you can help cmake with that external variable.
If you use Linux on odroid, you may just try to use my current cmake project. I use it to make PC builds on Ubuntu.

**Comment by gonetz** [comment]
Bear in mind that current project code is not GLES2 compatible.

**Comment by sergiobenrocha2** [comment]
I can build now, closing.
