### ISSUE TITLE
Destruction derby: Logo Texture 

### ISSUE THREAD

**Issue by Nes-player4Life** [gonetz/GLideN64#435]
Latest F-zero hotfix 4/28
![destruction derby64](https://cloud.githubusercontent.com/assets/10325597/7383146/10b7f058-ede8-11e4-9648-9083bc4d86f3.jpg)

**Comment by gonetz** [comment]
Thanks!

Fixed.

**Comment by Predator82Germany** [comment]
Indeed

**Comment by Predator82Germany** [comment]
Closable

**Comment by gonetz** [comment]
Author! Author!

@Nes-player4Life, I 'd like the author check and close the bugreports.

**Comment by Nes-player4Life** [comment]
Thanks.
