### ISSUE TITLE
Ocarina of time depth problems

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#436]
Coronas are visible through walls if you press z
If you don't press z it is correct
copy depth buffer to rdram is enabled
![gliden64_the_legend_of_zelda_001](https://cloud.githubusercontent.com/assets/7283660/7385894/719d3210-ee4d-11e4-8ff4-e075c0fbb693.jpg)
![gliden64_the_legend_of_zelda_000](https://cloud.githubusercontent.com/assets/7283660/7385895/71a17aaa-ee4d-11e4-9ee2-3d60c43dd7c6.jpg)

**Comment by purplemarshmallow** [comment]
regression
works with new year beta

**Comment by gonetz** [comment]
Fixed

**Comment by purplemarshmallow** [comment]
Not 100% fixed
If you press z in a certain distance all coronas disappear
does not happen with Glide64 and angrylion's plugin
Savestate: https://drive.google.com/file/d/0B7Y6r4SpC_QQbHVMZVkzc1VxRVU/view?usp=sharing
![gliden64_the_legend_of_zelda_003](https://cloud.githubusercontent.com/assets/7283660/7393539/b33b8b04-ee8e-11e4-8dd9-ca539d9fbd56.jpg)
![gliden64_the_legend_of_zelda_002](https://cloud.githubusercontent.com/assets/7283660/7393538/b33b9b26-ee8e-11e4-90d9-8e2dd6f60c2d.jpg)

**Comment by purplemarshmallow** [comment]
But I'm picky here
Glide64 also isn't 100% correct if I look closer
close or keep it open?

**Comment by gonetz** [comment]
close. I fixed the bug, which caused initial issue
