### ISSUE TITLE
Ocarina of time missing framebuffer effect

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#437]
in gameover screen
![gliden64_the_legend_of_zelda_000](https://cloud.githubusercontent.com/assets/7283660/7385929/f3f33f20-ee4d-11e4-8570-0fc4ad005c6e.jpg)

**Comment by purplemarshmallow** [comment]
Works with new year beta
I removed the subscreen delay fix cheat in mupen64plus.ini

**Comment by gonetz** [comment]
Fixed

**Comment by gonetz** [comment]
Hmm, not totally fixed yet

**Comment by gonetz** [comment]
Now fixed.
