### ISSUE TITLE
Quake64 silvering dogs

### ISSUE THREAD

**Issue by SatanNintendo** [gonetz/GLideN64#439]
Привет, запустил я тут Quake64, наконец под водой игра работает нормально, а вот с собаками явно что-то случилось, они стали серебрянно-зеркальными, разработчик Русский, он поймёт что я написал.

![gliden64_quake_000](https://cloud.githubusercontent.com/assets/10689866/7393270/7ac52d50-ee95-11e4-9386-89cbbf3bd4c5.jpg)
![gliden64_quake_001](https://cloud.githubusercontent.com/assets/10689866/7393273/7ac93940-ee95-11e4-8402-f304476e5459.jpg)
![gliden64_quake_002](https://cloud.githubusercontent.com/assets/10689866/7393272/7ac900d8-ee95-11e4-87d3-b8bc95f27127.jpg)
![gliden64_quake_003](https://cloud.githubusercontent.com/assets/10689866/7393271/7ac8da9a-ee95-11e4-9cdf-bd45c3264786.jpg)

**Comment by purplemarshmallow** [comment]
#328 related?

**Comment by olivieryuyu** [comment]
same issue

**Comment by gonetz** [comment]
Yes, most likely

**Comment by olivieryuyu** [comment]
please close the duplicate issue thx

**Comment by AmbientMalice** [comment]
Seems fixed.
