### ISSUE TITLE
WinBack Covert Operations (Flying gray square)

### ISSUE THREAD

**Issue by SatanNintendo** [gonetz/GLideN64#440]
А эта проблема так и осталась.
![gliden64_win_back_000](https://cloud.githubusercontent.com/assets/10689866/7393388/195604d0-ee96-11e4-9fee-30a0a0371ffc.jpg)
![gliden64_win_back_001](https://cloud.githubusercontent.com/assets/10689866/7393389/198bcb38-ee96-11e4-956f-747535378d27.jpg)

**Comment by purplemarshmallow** [comment]
duplicate #63
