### ISSUE TITLE
StarFox64: Stactic effect

### ISSUE THREAD

**Issue by Nes-player4Life** [gonetz/GLideN64#443]
I would post as shot but the effect only takes a spit second.
Basically the effect only show as a black screen now. 

EDIT:
I was able to take the shots after all.
![starfox64 good](https://cloud.githubusercontent.com/assets/10325597/7404629/e5b0c91c-eeb3-11e4-9670-0fa7f0044d04.jpg)
Older plugin

![starfox64](https://cloud.githubusercontent.com/assets/10325597/7404635/fed4b7fa-eeb3-11e4-8ee3-14d5ab5089d5.jpg)
Latest Release as of 4/29

**Comment by Nes-player4Life** [comment]
PR# also has this issue.

**Comment by Nes-player4Life** [comment]
Issue still present In May 15 build.

**Comment by gonetz** [comment]
I tried to catch this effect, but I can't notice it. I've made video from the intro:
https://drive.google.com/file/d/0B0YqMPjGo3B2V3FYV2xYb1JwOGc/view?usp=sharing
and watched it frame by frame. I don't see the glitch. May be special condition required to reproduce it? Particular emulator, particular settings enabled? Was it the first game after emulator started, or you played a game before this one?

**Comment by Predator82Germany** [comment]
Looks like real hardware in your video?

**Comment by gonetz** [comment]
Video from GLideN64. I can't reproduce that bug on my graphics card.

**Comment by Predator82Germany** [comment]
Mine: https://www.youtube.com/watch?v=rzcBlmRolS0

**Comment by gonetz** [comment]
I does not see the issues on your video too.
@Nes-player4Life , could you make the video, where the bug would be visible?

**Comment by Nes-player4Life** [comment]
Sorry for the delay it's been one of those weeks.
The screen cuts when user pushes (Start) to transition into game menu.
This is the currant release; with issue: http://youtu.be/MArdZ2w6Ys4
This is a previous release; with proper effect: http://youtu.be/bDNfLbB0s7s

**Comment by GPDP2** [comment]
It's worth noting real hardware actually produces a static effect on black backgrounds on Star Fox 64, which can be clearly seen with Angrylion's plugin, but only when the VI filters are turned on.

**Comment by Predator82Germany** [comment]
How does it look on real hardware?

**Comment by standard-two-simplex** [comment]
I don't get the static effect with angrylions (VI filters on) and every video I checked on youtube has black bar effect on it.
Are you sure that is not what is meant to happen?

**Comment by gonetz** [comment]
Ok, here the video from my own console recorded by my camera from my old CRT TV.
https://drive.google.com/file/d/0B0YqMPjGo3B2QndpWFhsTzZhREU/view?usp=sharing
The transition to menu really takes a spit second. Thus, I also take frame-by-frame shots to show the process in dynamic. As you may see, the first screen shot from the bug report is wrong, the second one is correct. Angrylions (VI filters on) and GLideN64 works correct here.

**Comment by Predator82Germany** [comment]
Then there´s no issue, so close it

**Comment by gonetz** [comment]
Let's wait a word from Nes-player4Life.

**Comment by Nes-player4Life** [comment]
Well, I can't argue with the actual console. I thought for sure the effect existed. I would like to thank all of the members for looking into this issue. I apologize for wasting your time and I wish I could have tested my own cartridge on the real hardware.

@gonetz thanks again for checking into this for me.
/closed

**Comment by gonetz** [comment]
Well said :)
