### ISSUE TITLE
Top Gear Rally reflections not working

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#444]
Reflections on windows are missing. On AL RDP the color is a light blue and they reflect the clouds

**Comment by Predator82Germany** [comment]
F-Zero X too

**Comment by gonetz** [comment]
Does it work in LLE mode?

**Comment by theboy181** [comment]
I couldn't get it working in lle

**Comment by purplemarshmallow** [comment]
I got it working
GLideN64 HLE
![gliden64_top_gear_rally_001](https://cloud.githubusercontent.com/assets/7283660/7428523/442037fa-eff2-11e4-9370-ad7b3021177b.jpg)
GlideN64 LLE, reflections on the roof look different
![gliden64_top_gear_rally_000](https://cloud.githubusercontent.com/assets/7283660/7428528/5fb938c2-eff2-11e4-8483-510c5d9576fe.jpg)
software renderer
![ngre0000](https://cloud.githubusercontent.com/assets/7283660/7428535/6c882c48-eff2-11e4-8ed4-85a4fa5defe6.png)
window color is gray in both HLE and LLE if i don't use a savestate:
HLE
![gliden64_top_gear_rally_002](https://cloud.githubusercontent.com/assets/7283660/7428550/9fd34a10-eff2-11e4-84ce-9785b3b41e60.jpg)
LLE
![gliden64_top_gear_rally_004](https://cloud.githubusercontent.com/assets/7283660/7428555/aff5e510-eff2-11e4-8f29-863424f3b59c.jpg)

**Comment by theboy181** [comment]
If the effect starts working after a save star is loaded, this would be similar to a bug in mario golf I reported.

**Comment by gonetz** [comment]
Will it work if you just switch to fullscreen?

**Comment by purplemarshmallow** [comment]
No
looks like it only works if the savestate was made while using angrylion's plugin...

**Comment by purplemarshmallow** [comment]
Sometimes it works if I make a savestate with GLideN64 and then load it
But it's random

**Comment by theboy181** [comment]
Does this only work in LLE mode when loading from a save state?

**Comment by purplemarshmallow** [comment]
No, LLE and HLE

strange
windows are colored blue with angrylion's plugin
but if I make a Savestate and load it they are rainbow colored

**Comment by theboy181** [comment]
When I load from a AL save state, the windows are correct for only a brief second, then they change back to grey.

**Comment by purplemarshmallow** [comment]
I think it's random

this is correct:
![ngre0001](https://cloud.githubusercontent.com/assets/7283660/7430663/8352f84e-f016-11e4-8105-fb1d3d5cd800.png)

**Comment by theboy181** [comment]
For a full round I was playing the H1 dump and it was working just fine. So it is random
