### ISSUE TITLE
Donkey Kong 64: Blurred Textures

### ISSUE THREAD

**Issue by WizLizard** [gonetz/GLideN64#445]
I don't have a save state or anything atm. Just start a new game and you should see it. I believe this is a mipmap issue, correct me if i'm wrong. I'm not a programmer nor do i know anything about coding but i'm not sure its normal. Using project64 2.2

Note I've only tested the U version.

**Comment by WizLizard** [comment]
Still present in public release 1. Here's an example. 

(https://cloud.githubusercontent.com/assets/12180630/7440045/9719b38c-f06a-11e4-8df9-f3302c7ce54d.png)

(https://cloud.githubusercontent.com/assets/12180630/7440047/b4a49ea8-f06a-11e4-9f23-5111fa92136d.png)

**Comment by Mushman** [comment]
Not a bug. Glide64 doesn't correctly use mipmapping, so textures which are intended to display their mipmaps instead show the full resolution texture. GLideN64 uses correct behaviour. Mipmipping, by nature, means that objects in the distance will have less detail, and it looks like in this case the textures also have a reduced contrast. See [this post on gonetz's blog](http://gliden64.blogspot.ru/2014/10/mip-mapping-emulation.html) for more information.

If you are sure this is incorrect behaviour, please provide more detailed information and screenshots.

**Comment by AmbientMalice** [comment]
I suspect this is normal behavior. Running at 320x240, you'd never be able to see his eyes. However, it COULD possibly be a bug related to the wrong mipmaps used in other Rareware games.

**Comment by WizLizard** [comment]
Thanks for the info! Well here is a video of the game running on the wii u virtual console. The textures don't behave the same way as GLideN64, so is the wii u version incorrect? Sorry for my ignorance i apologize. I did test the plugin with the emulate mip-mapping off and the textures did return to the state of the original glide, which looks more like the wii u behavior in the video. Other than making the textures appear clearer when disabling emulate mip-mapping will this have any negative effects? 

https://www.youtube.com/watch?v=7w98IzVP-Rw

**Comment by Mushman** [comment]
Hm. The Virtual Console ports of old games don't always exactly match the originals, but they usually are very accurate. Try checking footage of the game running on original hardware to be absolutely certain. However, there are issues with GLideN64's mipmapping emulation open at the moment, so it might be true that it's incorrect.

**Comment by WizLizard** [comment]
https://www.youtube.com/watch?v=wz62ryqPzYI

So the mip-mapping seems to present for the grounds textures in the distance if you watch carefully in this video running on the original n64. Although at about 2:52 his eyes and tie do not seem be effected by any mip-mapping. The eyes seem to maintain the solid black and same level of detail and clarity. I think the eyes and tie are the only thing incorrect. I'm positive this is running on the original system due to the year uploaded and the proper emulation of the zipper transition in part 1 of this lets play series. Seems the virtual console is emulating this effect incorrectly and the plugin is doing it partially correct. Idk though you guys know your stuff so i'm curious to find out.

**Comment by WizLizard** [comment]
It's very hard to say though without my hands on the original system though. 2:52 may not be the best comparison either due to how close he is to the camera.

**Comment by Mushman** [comment]
Anisotropic filtering was reported to be faulty in #505. Maybe you should see if it looks any better when that issue gets fixed.

**Comment by WizLizard** [comment]
Will do.

**Comment by WizLizard** [comment]
Update, no change since 1.1

**Comment by AmbientMalice** [comment]
The game seems to work much better after recent mipmapping changes. If the eye mipmaps bother players, disabling mipmaps seems to work with no issues.

**Comment by WizLizard** [comment]
Cool, I'll test it out as soon as i can. I would never disable it. I like the mip-mapping i was just trying to find out if it was being done correctly with the plugin.

**Comment by AmbientMalice** [comment]
@WizLizard here are the updated binaries from last night with the mipmap fixes if you need them drive.google.com/file/d/0B0YqMPjGo3B2WkxOV25sS2cyZVU/view?usp=sharing

**Comment by WizLizard** [comment]
Thanks

**Comment by WizLizard** [comment]
I've tested the plugin since the changes to mimapping. 

With changes:
![9719b38c-f06a-11e4-8df9-f3302c7ce54d](https://cloud.githubusercontent.com/assets/12180630/8270800/4427bf18-17c3-11e5-9679-2775a7ef7f91.png)

Without changes (PR 1.1):
![screenshot 36](https://cloud.githubusercontent.com/assets/12180630/8270802/4d00ffd2-17c3-11e5-8a90-e03fb0fd7d7b.png)

Close?

**Comment by gonetz** [comment]
Please wait. I haven't time to check it myself yet. New result does not look nice enough. Probably it can be improved.

**Comment by WizLizard** [comment]
No problem i will wait.

**Comment by gonetz** [comment]
Please test with this binary:
https://drive.google.com/file/d/0B0YqMPjGo3B2WWNmd01xcUJ5X2M/view?usp=sharing

**Comment by baptiste0602** [comment]
I think it's OK now :
![image](https://cloud.githubusercontent.com/assets/11183826/8437602/5812d946-1f60-11e5-99b6-d621e2d6d499.png)

**Comment by gonetz** [comment]
Ok, close.

**Comment by Joyconboyz9** [comment]
Solution: LOD Emulation in settings. Using Mupen64Plus in Retroarch running Gliden64.

Old post I know; I couldn't find an answer to this online and was having the same issue with DK64 Dinosaur Planet and other games. Hopefully, someone finds this useful if they're having the same issues.
