### ISSUE TITLE
Space Invaders Boss battle gliching

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#448]
@gonetz  

https://www.dropbox.com/s/4snl1f2yjuna2we/Space%20Invaders%20%28U%29.pj.zip?dl=0

With FB emulation on while battling the boss in this game the VI/s are locked @ 60 but the game lags when the boss attacks.

This is really weird, and should be investigated. Game plays fine with AL RDP.

Save included

**Comment by Nes-player4Life** [comment]
I've seen this before in the older beta's. I thought it was fixed.

**Comment by theboy181** [comment]
Nope.. its too bad the game looks awesome with AA.

**Comment by theboy181** [comment]
@gonetz 
Since DEV this game now just flashed black frames with the boss battle described above. Any suggestions?

**Comment by Nes-player4Life** [comment]
It seems the the glitch takes longer to recover when in Full Screen.

**Comment by theboy181** [comment]
This glitch is puzzling. I can't understand what causes it n

**Comment by Nes-player4Life** [comment]
Without FB it runs better the ever but quality takes a nasty hit.

**Comment by gonetz** [comment]
I found why it lags. Video buffer height changes often with no visible reason. It causes reset of frame buffer objects. It is known that PJ64 has problems with VI registers. Please check the game with 1964 and Mupen64.

**Comment by theboy181** [comment]
It's working with other plugins on PJ. Are you sure?

**Comment by gonetz** [comment]
I have corrected my previous comment. Now I'm sure :)

**Comment by theboy181** [comment]
This isn't a tough decision Mickey clearly needs to work over space invaders. :)

**Comment by gonetz** [comment]
I've added an game-dependent-option (that is a hack) to make both games working.

**Comment by theboy181** [comment]
Nice. And thanks.  Still unable to compile using msvs :(

**Comment by purplemarshmallow** [comment]
isn't resetting frame buffer objects a hack? if so it would be better to make a hack for Mickey´s Speedway instead or find a proper fix for Mickey

**Comment by purplemarshmallow** [comment]
#547 might be related to #376 ?

**Comment by purplemarshmallow** [comment]
>I can remove just one line and it will work without lags and with screen shaking as with AL RDP. But it will break #376 again.

I removed the line and Mickey´s Speedway still looks normal!
(revert https://github.com/gonetz/GLideN64/commit/8f4d527a9c3e1fba61fafdddd5d57bc2c578920f)

**Comment by gonetz** [comment]
>isn't resetting frame buffer objects a hack?
No. Change in VI size usually means that internal game resolution changed. That is the game will use new buffers. Thus, the old ones will not be used and thus must be cleared.

>#547 might be related to #376 ?
I did not investigate #547 yet.

>I removed the line and Mickey´s Speedway still looks normal!
Hmm, need to check it. Probably, another part of code does necessary job.

**Comment by gonetz** [comment]
I've checked Mickey´s Speedway with  8f4d527 reverted. The glitch from  #376 is back.
To reproduce it:
- use (E) rom
- use mupen64plus build
- enable depth copy

**Comment by gonetz** [comment]
@theboy181 , binary to test this bug:
https://drive.google.com/file/d/0B0YqMPjGo3B2WGZhTW8tYUJ4N2M/view?usp=sharing

**Comment by purplemarshmallow** [comment]
thanks for the explanation
my mistake, i tested (U) version

**Comment by Nes-player4Life** [comment]
Resolutions 1280x1024 retain original issue.
Lesser resolutions seem to run fine.

**Comment by gonetz** [comment]
>Resolutions 1280x1024 retain original issue.

Fullscreen or windowed? Original issue - slowdown during boss attack?

**Comment by Nes-player4Life** [comment]
Sorry for the late reply real life caught me by the core this week.

@gonetz Gonetz the issue is found in both fullscreen and windowed during the smash attack.

**Comment by gonetz** [comment]
Sorry for the late reply real life caught me too.

I tested the game in 1280x1024 both fullscreen and windowed: no slowdown during the smash attack on my hardware.
