### ISSUE TITLE
can't configurate mupen64plus version

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#449]
In m64py the configure button is grayed out
[Video-Gliden64] section in mupen64plus.cfg is created but it's empty
The only way to configurate the plugin is to create the section in the cfg file with an older version of the plugin and then replace the .dll

**Comment by gonetz** [comment]
It is bug in the frontend.
The cure is very simple. Open command line and type:

mupen64plus.exe --gfx mupen64plus-video-GLideN64.dll m64p_test_rom.v64 

It will create [Video-GLideN64] section in mupen64plus.cfg
After that you may edit settings using m64py

**Comment by purplemarshmallow** [comment]
your solution works
close?

**Comment by gonetz** [comment]
Hmm, actually normal scenario where you just use m64py should work too.
I'll do some correction in that part to make it working.

**Comment by gonetz** [comment]
I corrected that part. Now you should just run any game with m64py and config section will be created.

**Comment by gonetz** [comment]
Please test the Release build. m64py-only scenario should work now.

**Comment by purplemarshmallow** [comment]
confirmed
