### ISSUE TITLE
HWFB leads to black screen in some game now! (regression!)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#45]
The game runs, but with HWFB, it is now a black screen

Topgear Hyperdrive, Airboarder (J), Topgear rally 2 in game, more certainly ...

**Comment by gonetz** [comment]
Topgear Hyperdrive and Topgear rally 2 are fixed.
Airboarder (J) is programmed in very weird way and hardly can be fixed.

**Comment by theboy181** [comment]
Airboarder 64 (j) still black screen with today's release
