### ISSUE TITLE
Paper Mario, FSAA Absent

### ISSUE THREAD

**Issue by thecoreyburton** [gonetz/GLideN64#451]
With both AA and AF set to full, edges look flawless in most games except Paper Mario. The scene shown is in the introduction (start the game, select any file and start and you'll be greeted by this scene). I've circled some areas that should be anti-aliased that aren't. If I were to force GPU AA on my card with Glide64, these same areas would be smooth.

![lines](https://cloud.githubusercontent.com/assets/12134368/7433111/6884a6ba-f071-11e4-9f5e-c1ce0bc50a26.jpg)

**Comment by gonetz** [comment]
FSAA is disabled for this game in custom game settings because some frame buffer effects do not work with it. You may disable "Use custom per-game settings" and enable FSAA for this game, but be warned.

**Comment by thecoreyburton** [comment]
Thank you, I didn't think to check there.

**Comment by Mushman** [comment]
It looks like there's a fix on the way to get framebuffer working with antialiasing due to the developments in #244. Good stuff!
