### ISSUE TITLE
Forced Filtering

### ISSUE THREAD

**Issue by thecoreyburton** [gonetz/GLideN64#452]
Not so much an issue, but in Glide64 when it came to texture filtering there was an option for filtering to either go automatic, force point sampled or force bilinear filtering. I really like the new three point option for accuracy but there are some cases where I'd want to force point sampled or bilinear filtering. Would you be able to add this option to the GUI(s)?

**Comment by gonetz** [comment]
You can't force disable texture filtering.
However, force texture filtering is possible. Open 'Textures' tab and select any Filter you like.

**Comment by thecoreyburton** [comment]
Closed, thank you. Additionally, the filters looked awful at first but unticking compress texture cache and restarting the plugin significantly helped these filters to work.
