### ISSUE TITLE
LLE gfx issues with Emulate frame buffer

### ISSUE THREAD

**Issue by exhalatio** [gonetz/GLideN64#455]
you enable the Emulate frame buffer in LLE gfx, you can see nothing screen is black.
such as Mario Tennis menu port, F-Zero X, Pokemon Puzzle League.

**Comment by purplemarshmallow** [comment]
worked with new year beta

**Comment by purplemarshmallow** [comment]
seems fixed

**Comment by AmbientMalice** [comment]
@purplemarshmallow Games like Turok 3 are still blank with FB enabled in LLE.

**Comment by purplemarshmallow** [comment]
F-Zero X and Pokemon Puzzle League are fixed
Mario Tennis is not fixed
for Turok 3 this is unfortunate because lighning works correctly in LLE

**Comment by AmbientMalice** [comment]
Issue fixed, as far as I can tell.

**Comment by exhalatio** [comment]
Issue fixed, thanks!
