### ISSUE TITLE
Texture pack path not saved correctly

### ISSUE THREAD

**Issue by etking** [gonetz/GLideN64#456]
I want to choose the folder 1964\plugin\Hires_texture as texture folder (because I store all my textures there) but Glide64 run on Project64 2.2 always changes the path to 1964\plugin\Hires_texture\Project64\GFX\Hires_texture after saving the correct folder and leaving the options menu once.

When reopening the settings menu Texture pack path also shows random letters like e or in:
Folder selected: 1964\plugin\Hires_texture
Folder Shown after selection: 1964\plugin\Hires_texture
Folder shown after reopening settings menu: 1964\plugin\Hires_textureIN\Project64\GFX\Hires_texture

**Comment by harlayzhou** [comment]
Couldn't change the path of texture pack in Porject64 2.2.0.3.
There's only two default path can use.
1. Project64\Plugin\GFX\hires_texture
2. Project64\TexturesFX\hires_texture
even couldn't change the name of hires_texture.

**Comment by Mushman** [comment]
Confirmed. When selecting a folder for ``Texture pack path``, the new value will be the default value with the new path overwriting only the beginning of it. The default value is the path to GLideN64 appended with ``hires_texture``.

For example:
Path to GLideN64.dll: ``C:/Emu/Plugin/gonetz``
GLideN64 default custom texture path: ``C:/Emu/Plugin/gonetz/hires_texture``
Desired custom texture location: ``E:/1``
Path GLideN64 uses for custom textures: ``E:/1mu/Plugin/gonetz/hires_texture``

This is a regression from the Week 27 Hotfix ROM Name Checksum ``d3578ec`` 8 April build. The initial Week 27 build is no longer available, so I could not test to see if the regression was present there.

You can work around this bug by using a valid path to your custom textures which is longer than the default path.

Workaround path for the example: ``E:/really long path so I can get these sick textures working``

**Comment by Mushman** [comment]
Gonetz mentioned that it's been resolved. By the sounds of things, a hotfix isn't too far away.

**Comment by gonetz** [comment]
Can be closed?
