### ISSUE TITLE
OOT Green C buttons with Intel HD graphics

### ISSUE THREAD

**Issue by HeyAlucard** [gonetz/GLideN64#457]
Using Intel HD graphics 4600 driver version : 10.18.14.4156
Using public release
![untitled](https://cloud.githubusercontent.com/assets/12204238/7438408/b5295f46-f018-11e4-8175-e7c3ac2cbb6a.png)

**Comment by JamCR** [comment]
I'd like to add that when Navi flashes up it seems to fix some of the colour issues on the buttons

![7](https://cloud.githubusercontent.com/assets/12295203/7514929/37d5ddb6-f4ba-11e4-8cab-84a3f452ea80.png)
![6](https://cloud.githubusercontent.com/assets/12295203/7514931/392ceec0-f4ba-11e4-827b-59328b1987fd.png)

Using Project 2.2 and Intel HD Graphics 5500 (10.18.14.4170)

**Comment by phly95** [comment]
should be merged with issue #512 . This is a serious problem and causes major issues with majora's mask as well. I have also submitted a report to intel as it seems to be on their end here: https://software.intel.com/en-us/forums/topic/560079 I still have not gotten a reply yet ._.

**Comment by gonetz** [comment]
Fixed I guess.
