### ISSUE TITLE
OOT crash 

### ISSUE THREAD

**Issue by LuismaSP89** [gonetz/GLideN64#458]
OOT Crashes when you go out of temple of time (Adult) with default settings "Or with your own settings"

![ootcrash](https://cloud.githubusercontent.com/assets/12205048/7439352/1943feb4-f078-11e4-8457-a7cd5c6fec78.jpg)

**Comment by LegendOfDragoon** [comment]
Does it happen with CPU Interpreter enabled in Project64?

**Comment by LuismaSP89** [comment]
Mm? I don´t know it whas an option or interpreter checkbox in project64, but this happens with all settings by default, (GlideN64 options by default and project64 options by default)

**Comment by LuismaSP89** [comment]
Btw, with other graphical plugins this doesn't happen, so, i think that the problem is not the project64.

**Comment by LegendOfDragoon** [comment]
>Thanks for your help : )

Np :) .

>Btw, with other graphical plugins this doesn't happen, so, i don't think that the problem is on the project64.

Just in case, you should still try CPU Interpreter. It's better to eliminate possibilities as much as possible :) . To select CPU interpreter, click on Edit Game Settings, then click on Recompiler, then you should see an option called CPU core style. Change that from Recompiler to Interpreter.

**Comment by purplemarshmallow** [comment]
It does not crash for me
what rom version?

**Comment by LuismaSP89** [comment]
@LegendOfDragoon  Yep it works ok with the interpeter CPU mode, but this affects at the sound a little, like a small backfire. I don´t know why the recompiler mode works ok with other graphics plugin. But it´s something, thanks a lot ; )
@purplemarshmallow  I use the (U) version of the game.

**Comment by purplemarshmallow** [comment]
Strange
works for me with recompiler
But if it's working for you with interpreter it must be a bug in Project64

**Comment by LegendOfDragoon** [comment]
@LuismaSP89 thanks for testing in CPU Interpreter.

Basically there's some weird bug with Protect Memory, and the error message only displays on certain people's computers and certain plugins. It's supposed to show for everyone, but it doesn't. This Protect Memory issue also affects other games like Jet Force Gemini.

**Comment by LuismaSP89** [comment]
@LegendOfDragoon, 
What a strange thing : /
Thanks to you for helping and locate the problem.

**Comment by gonetz** [comment]
Can it be closed, or I need to fix something?

**Comment by LuismaSP89** [comment]
@Gonetz  With other plugins works properly, and with Gliden64 crashes for me in that part of game "unless selecting interpeter mode" so, i think there's a bug.
¿Do you need a savegame?

**Comment by gonetz** [comment]
Yes, savestate would be nice. I'll try to reproduce it on my PC.

**Comment by LuismaSP89** [comment]
Here it is:

http://we.tl/UkqGn3Tdq4

All you have to do is leave the temple.

**Comment by gonetz** [comment]
OOT has at least 3 (U) versions. Which one crashes?

**Comment by gonetz** [comment]
I tried the following scenario:
Load plugin's default, load (U) rom (I tried all three I have), load Link save, leave the temple.
No problems. 

Project64 1.6, Project64 2.2.0.3

**Comment by gonetz** [comment]
Does it crash for you with FB emulation off?

**Comment by LuismaSP89** [comment]
I use the Project64 2.2.0.3.
The version of the game is:

Ocarina ot time (U) (v1.0)
Catridge ID: ZL
CIC chip: CIC-NUS-6105

**Comment by LuismaSP89** [comment]
Yes, with FB emulation off, still crashes.

**Comment by LuismaSP89** [comment]
Two videos showing the problem with different roms:

- Ocarina ot time (U) (v1.0)
http://we.tl/hBvWeGpGxJ

- Ocarina ot time (U) (v1.2)
http://we.tl/Gtceux7EUy

P.S: Sorry for the video quality.

**Comment by LegendOfDragoon** [comment]
>Can it be closed, or I need to fix something?

It's up to you. Most likely, the problem is only the emulator itself, but if you want to be safe, you can keep this open and further investigate after the Protect Memory issue in PJ64 2.x is fixed.

**Comment by LuismaSP89** [comment]
@gonetz  Yes, must be a emulator problem like LegendOfDragoon tells.
When the protect memory issue find a solution, i´ll try again, and if persists, I can reopen this issue.

Thanks, both of you.

**Comment by LuismaSP89** [comment]
Ok, I tell the issue on the Project64 Issues forum.

**Comment by gonetz** [comment]
Ok, close for now.

**Comment by tony971** [comment]
It's not the plugin. http://forum.pj64-emu.com/showthread.php?t=5023

**Comment by Mushman** [comment]
Should I also close #377 which is a variant of this bug?

**Comment by LegendOfDragoon** [comment]
zilmar made a minor fix. The problem had to do with incomplete exception handling. Some cpu instructions aren't implemented. The reason it only effected some people was because Memcpy can be different, depending on the libraries installed on your computer. Memcpy should now work with latest source.

@Mushman, it should also fix the JFG problem you encountered. Feel free to test it if you're interested.

**Comment by purplemarshmallow** [comment]
@LegendOfDragoon I tested Jet Force Gemini intro cutscene with GLideN64 and the latest Project64, still crashing

**Comment by LegendOfDragoon** [comment]
@purplemarshmallow thanks for the feedback. I'll try debugging on a remote machine and see if I can fix it.

**Comment by LegendOfDragoon** [comment]
@purplemarshmallow  I tested Jet Force Gemini and haven't seen a crash on my end. Can you elaborate?

**Comment by LuismaSP89** [comment]
The problem of the Ocarina of time Crash is solved in the latest builds.

**Comment by purplemarshmallow** [comment]
It's exactly as described in #377 
I'm starting a new game and during the intro cutscene the emulator crashes. Does not happen with interpreter. I'm using the latest version of PJ64 from github and GLideN64 as video plugin. I never had the problem with the crash in Zelda OOT

**Comment by LuismaSP89** [comment]
Then you must go to the Project64 forums and open a new thread for this problem, I hope that the team of Project64 can have this solved quickly.

**Comment by LegendOfDragoon** [comment]
@purplemarshmallow Thanks. I'll try digging deeper.

@LuismaSP89 No need to open a new thread. It's a known issue. zilmar just needs to spend some time fixing the problem. I will try seeing if I can assist him.

**Comment by purplemarshmallow** [comment]
@LegendOfDragoon I tried to run PJ64 with Debugger
I'm getting this: 
Unhandled exception at 0x0258fd45 in Project64.exe: 0xC0000005: Access violation writing location 0x3aa72a40.
I can't see the part of the source code where it crashes, the crash happens in GLideN64.dll

**Comment by LegendOfDragoon** [comment]
@purplemarshmallow On top of PJ64's exception handling being incomplete, there seems to be an additional problem on GlideN64's part, because exception handling doesn't seem to work at all inside the function where this happens. I or someone else will have to compile and debug GlideN64 to figure out why it's not working.

**Comment by purplemarshmallow** [comment]
I haven't compiled the zilmar spec version yet, I don't have Qt installed on my system

**Comment by gonetz** [comment]
I've uploaded GLideNUI.lib on my google drive to simplify life for those developers, who don't want to deal with QT:
https://drive.google.com/file/d/0B0YqMPjGo3B2N2lUcFNveWlTeUU/view?usp=sharing
