### ISSUE TITLE
Goldeneye Texture errors and slowdowns

### ISSUE THREAD

**Issue by LuismaSP89** [gonetz/GLideN64#459]
Multiple errors and slowdowns by playing for example "Frigate level" no water texture, no weapon textures, no bond texture.

When you play a mission, "For example first mission, frigate, etc" apparently all works ok, but when you play during some time (5 minutes or more) in fullscreen, the game have a big slowdown by over the 50% of the real framerate. 

Note: Tried with default settings and custom settings.

![weaponsnotexture](https://cloud.githubusercontent.com/assets/12205048/7439396/6ffb50ee-f079-11e4-9909-31a9daf7af96.jpg)
![bondnotexture](https://cloud.githubusercontent.com/assets/12205048/7439398/70023526-f079-11e4-876d-87a9e73bef85.jpg)
![waternotexture](https://cloud.githubusercontent.com/assets/12205048/7439397/6ffe1edc-f079-11e4-9638-ce0e93a421d8.jpg)

**Comment by Mushman** [comment]
Unable to reproduce. I tested by loading Byelomorye Dam, idling for two loops of the background music, aborting and restarting the mission in both windowed and full screen. I am testing with an NVidia Geforce GTX 970 running OpenGL 4.5.

**Comment by LuismaSP89** [comment]
Mushman, I got your same graphics card, and a i7 4790k processor, please try it on frigate level and you'll see it.

**Comment by LuismaSP89** [comment]
Note: (Tested on U version)

**Comment by Mushman** [comment]
Okay, confirmed it happens on Frigate 'La Fayette'. You should write that it happens without having to play for five minutes and it only occurs on Frigate, unless you find it occurring elsewhere. It also happens when using windowed mode. The bug is also present in Mupen64Plus.

**Comment by LuismaSP89** [comment]
The slowdown happens when i play for a few minutes (not 5 exactly) in any level (tested on Byelomorye Dam, Frigate "LaFayette" and Cradle missions) and it's a different error from the texture missing.

**Comment by Mushman** [comment]
I had consistent performance running Dam for two loops of the background music spinning in place. I don't think performance drops the longer time is spent in a level.

Oh, and here's a 100% file for Goldeneye for testing the bug on Frigate.
http://www.mediafire.com/download/7kd1et7kjz57rat/GOLDENEYE.eep

**Comment by purplemarshmallow** [comment]
The water in Frigate level is incorrect because the plugin uses the LLE triangle command ported from z64gl and it shares the same bug. It's working for the sky but the water is incorrect if you are close. see #406

**Comment by LuismaSP89** [comment]
@Mushman  Can you retry with max settings? "Antialiasing 8x, anisotropic 16x, aspect stretch, fullscreen 1920x1080, texture filter enhancement= Smooth filtering 4, enhancement= 5xbrz" and play in fullscreen mode, for example in craddle level? in few minutes the game takes a great slowdown, fairly unplayable. And this happens always. We have a strong graphics card, and this one should be able to handle this and more.

**Comment by sweatypickle** [comment]
on Project64, exiting from fullscreen to windowed or vice versa causes the proper textures to load.

**Comment by Mushman** [comment]
Okay, yes, playing through Antenna Cradle with all those settings is slower the longer you spend in the level. To test, compare beating the mission as quickly as possible compared to not engaging Alec Trevelyan for a while, paying attention to how fast the ending cutscene plays.

You can easily work around this by not enabling all of those advanced processing settings. I guess it's up to @gonetz to decide how to prioritise this part of the issue.

**Comment by sweatypickle** [comment]
On second look, while the proper textures are loaded, the waffle looking artifact is introduced once returning from fullscreen or vice versa.  This also occurs in #489.

**Comment by LuismaSP89** [comment]
Maybe the slowdowns are referenced too with this: https://github.com/gonetz/GLideN64/issues/470

**Comment by AmbientMalice** [comment]
Main texture errors don't seem to happen anymore. Maybe issue was related to https://github.com/gonetz/GLideN64/issues/744?

**Comment by gonetz** [comment]
Fixed
