### ISSUE TITLE
Compile with libpng, zlib and libboost from the system

### ISSUE THREAD

**Issue by sergiobenrocha2** [gonetz/GLideN64#461]
You should have an option to compile with these shared libs instead statically.

Or build them instead rely on pre-compiled stuff (for amd64 only).

Btw, you'll get an undefined reference with libpng from the system (1.2.50 on ubuntu 14.04):

```
undefined symbol: png_set_longjmp_fn
```

**Comment by gonetz** [comment]
cmake project file really designed to link everything statically. It's the only way to get a build, which will work on different Linix distributions. Fell free to correct it for your needs.

Ubuntu uses outdated libpng. I compiled that lib from sources.

**Comment by sergiobenrocha2** [comment]
Which libpng do you use? 1.6.17 ?

**Comment by gonetz** [comment]
Win32 build most likely use 1.43
Don't remember what was used for Linux. May be 1.6.16

**Comment by sergiobenrocha2** [comment]
png.h says 1.4.1. I built with 1.4.16, it seems it worked.

Using something like this in src/GLideNHQ/CMakeLists.txt:

```
target_link_libraries(GLideNHQ pthread ${CMAKE_CURRENT_SOURCE_DIR}/lib/libpng.a z ${Boost_LIBRARIES} )
```

**Comment by gonetz** [comment]
Thanks,
need to add a new parameter to CMakeList.txt, like DYNAMIC_LINK

**Comment by sergiobenrocha2** [comment]
For anyone wanting to compile for linux with zlib and libboost shared and libpng static, these are the patches:

http://bazaar.launchpad.net/~random-stuff/mupen64plus/mupen64plus-video-gliden64-debian/files/head:/patches/

You need to compile libpng with -fPIC (libpng.patch).

**Comment by sergiobenrocha2** [comment]
It could use mupen headers from the system too.

```
Index: GLideN64/src/PluginAPI.h
===================================================================
--- GLideN64.orig/src/PluginAPI.h	2015-05-19 14:02:26.990757883 -0300
+++ GLideN64/src/PluginAPI.h	2015-05-19 15:19:35.794222208 -0300
@@ -5,7 +5,7 @@
 #include <condition_variable>
 
 #ifdef MUPENPLUSAPI
-#include "m64p_plugin.h"
+#include <mupen64plus/m64p_plugin.h>
 #else
 #include "ZilmarGFX_1_3.h"
 #define RSPTHREAD
Index: GLideN64/src/mupenplus/GLideN64_mupenplus.h
===================================================================
--- GLideN64.orig/src/mupenplus/GLideN64_mupenplus.h	2015-05-19 14:02:26.994757923 -0300
+++ GLideN64/src/mupenplus/GLideN64_mupenplus.h	2015-05-19 15:19:34.382219692 -0300
@@ -1,8 +1,8 @@
 #ifndef GLIDEN64_MUPENPLUS_H
 #define GLIDEN64_MUPENPLUS_H
 
-#include "m64p_config.h"
-#include "m64p_vidext.h"
+#include <mupen64plus/m64p_config.h>
+#include <mupen64plus/m64p_vidext.h>
 
 #define PLUGIN_VERSION              0x020000
 #define VIDEO_PLUGIN_API_VERSION	0x020200

```

**Comment by sergiobenrocha2** [comment]
@gonetz what's the libpng version you are using now?

With 1.4.16 I'm getting this warning:
```
dpkg-shlibdeps: warning: debian/mupen64plus-video-gliden64/usr/lib/x86_64-linux-gnu/mupen64plus/mupen64plus-video-GLideN64.so contains an unresolvable reference to symbol png_init_io: it's probably a plugin
```

And with 1.6.18:
```
dpkg-shlibdeps: warning: debian/mupen64plus-video-gliden64/usr/lib/x86_64-linux-gnu/mupen64plus/mupen64plus-video-GLideN64.so contains an unresolvable reference to symbol dlsym: it's probably a plugin
```

**Comment by sergiobenrocha2** [comment]
It's missing -ldl (dl) in src/GLideNHQ/CMakeLists.txt

**Comment by gonetz** [comment]
I use libpng-1.6.16

I have no unresolvable reference errors. However, I use virtual machine and can't check that my build actually works, because VM does not support required GL version.

If you found an issue in my cmake files and fixed it, please make pull request with the fix.

**Comment by olivieryuyu** [comment]
is there a reason to not close this ticket?

**Comment by gonetz** [comment]
Yes, we added option to cmake to use system libs.
