### ISSUE TITLE
Toy Story 2 depth issues with FB enabled.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#464]
WITH FB:
![gliden64_toy_story_2_000](https://cloud.githubusercontent.com/assets/10704701/7440319/9f00e12e-f0f1-11e4-9a6b-eda441295789.jpg)

WITHOUT FB:
![gliden64_toy_story_2_001](https://cloud.githubusercontent.com/assets/10704701/7440320/a6276086-f0f1-11e4-8a89-557ae7dfb360.jpg)

Using PJ64 built from latest source. Public Release 1 plugin.

**Comment by Predator82Germany** [comment]
Try disable the depth-buffers

**Comment by AmbientMalice** [comment]
>Try disable the depth-buffers

Doesn't work.

**Comment by AmbientMalice** [comment]
On an interesting note, N64 depth compare fixes the missing laser charge graphics, which is nice.

**Comment by Dockolm** [comment]
There is also a HUD problem with this game. Lazer power bar and life bar doesn't show up.

**Comment by AmbientMalice** [comment]
@Dockolm That's fixed with N64 depth mode. Glide64 fixes the problem with a hack.

**Comment by Dockolm** [comment]
Oh, you're right. But N64 depth mode displays 3D triangles.

**Comment by purplemarshmallow** [comment]
N64 depth compare is not compatible with Anti-aliasing. Guess that's the problem here

**Comment by Dockolm** [comment]
I didn't know that, thanks.

**Comment by gonetz** [comment]
@AmbientMalice is it still actual?

**Comment by AmbientMalice** [comment]
@gonetz Yep. Still broken. I think it's related to https://github.com/gonetz/GLideN64/issues/600

**Comment by gonetz** [comment]
You mean, the original issue with window polygon is not fixed?

**Comment by AmbientMalice** [comment]
>You mean, the original issue with window polygon is not fixed?

The issue where 2D elements render through walls when the FB is turned on is not fixed, yes. The secondary issue with the HUD has been fixed.

**Comment by gonetz** [comment]
I see.

**Comment by AmbientMalice** [comment]
Fixed by https://github.com/gonetz/GLideN64/commit/8dad84cc39571c295d10a3b3c9326fa942478fcd

**Comment by gonetz** [comment]
Good. Thanks for testing it.
