### ISSUE TITLE
(LLE) Corrupt Map Lines. (Turok, Doom, Winback.)

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#465]
Several N64 games use a similar technique to render maps that breaks with GLideN64. I believe this bug is inherited from Ziggy's LLE.

HLE:
![gliden64_doom64_001](https://cloud.githubusercontent.com/assets/10704701/7440326/efa893ec-f0f1-11e4-961f-5a0e5b7d0b19.jpg)

LLE:
![gliden64_doom64_000](https://cloud.githubusercontent.com/assets/10704701/7440327/f9519cb8-f0f1-11e4-95e3-8cfbe0292089.jpg)

**Comment by gonetz** [comment]
Fixed

**Comment by fzurita** [comment]
@gonetz How are these lines drawn? They are not working correctly with Adreno, but only when threaded mode is on. I suspect a OpenGL command that is currently async need to be made synced.

**Comment by fzurita** [comment]
I think I narrowed this down. The "Draw Line" call in the unbuffered drawer seems to be doing something wrong in threaded mode. It was a tricky thing to implement, so it looks like I messed up somewhere there.

**Comment by fzurita** [comment]
Ok, this is trickier than I thought. It seems to be the UnbufferedDrawer that has the issue. Even with threading disabled, the unbuffered drawer has issues drawing the map lines.
