### ISSUE TITLE
World Driver Championship Texture Clipping\Corruption.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#466]
This game only runs in LLE, so I dunno whether this is LLE related or not.
![gliden64_world_driver_champ_000](https://cloud.githubusercontent.com/assets/10704701/7440332/491424c8-f0f2-11e4-847a-f46c7706ad2a.jpg)

![gliden64_world_driver_champ_001](https://cloud.githubusercontent.com/assets/10704701/7440333/4cdfd0de-f0f2-11e4-85c2-33532a177101.jpg)

The numbers are noticably clipped.

**Comment by AmbientMalice** [comment]
![gliden64_world_driver_champ_004](https://cloud.githubusercontent.com/assets/10704701/14587562/4d5c34f6-04f8-11e6-99f7-7c255cb078c5.jpg)

![gliden64_world_driver_champ_003](https://cloud.githubusercontent.com/assets/10704701/14587564/542ea0de-04f8-11e6-8cfe-e504c368406c.jpg)

Significant improvement, but now the numbers have black lines.

**Comment by Tasosgemah** [comment]
Yeah, i get those black lines as well.

Also, the lens flare effect is missing. But otherwise this is the best shape this game has ever been.

**Comment by AmbientMalice** [comment]
Game works fantastically now in HLE, but the HUD lines are still present.

**Comment by gonetz** [comment]
Fixed
