### ISSUE TITLE
Indiana Jones and the Infernal Machine Missing Sprites in LLE

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#467]
This bug is likely LLE related, and likely related to https://github.com/gonetz/GLideN64/issues/468 Everything from snow to water spray to Indy's lighter flame is affected.

Angrylion:
![nijp0002 - copy](https://cloud.githubusercontent.com/assets/10704701/7440344/9b7c2684-f0f2-11e4-9f55-95eff1a63809.jpg)

GLideN64:
![gliden64_indiana_jones_002 - copy](https://cloud.githubusercontent.com/assets/10704701/7440347/a831a264-f0f2-11e4-914c-c236be9c8cd6.jpg)

**Comment by purplemarshmallow** [comment]
I can see Indy's lighter flame
![gliden64_indiana_jones_000](https://cloud.githubusercontent.com/assets/7283660/7440488/d94d18f0-f0b7-11e4-970d-a8520868b633.jpg)

**Comment by AmbientMalice** [comment]
@purplemarshmallow There's supposed to be a light corona coming from the flame. The little flame itself is just rendered as part of the lighter model, I think.

Also, if you look over the cliff, you'll see the waterfall isn't splashing like it's meant to.

**Comment by purplemarshmallow** [comment]
Yes
I can see it if I compare with angrylion's plugin

**Comment by AmbientMalice** [comment]
Ziggy's LLE renders these effects correctly, too.

**Comment by theboy181** [comment]
What emu & plugin settings are you using to get this game work?

**Comment by purplemarshmallow** [comment]
patched version of pj64
https://github.com/project64/project64/pull/251
and
https://github.com/cxd4/rsp

**Comment by AmbientMalice** [comment]
Interestingly, the missing particle effects render when Indy is underwater.

![gliden64_indiana_jones_003](https://cloud.githubusercontent.com/assets/10704701/8224685/23a91ae4-15ce-11e5-840c-6a6904aa6ffa.jpg)

But disappear when you surface.

![gliden64_indiana_jones_004](https://cloud.githubusercontent.com/assets/10704701/8224689/33f197f0-15ce-11e5-8609-dce5d30aba43.jpg)

**Comment by StenApp** [comment]
Isn't that fixed?

**Comment by gonetz** [comment]
Fixed, but only in HLE.

**Comment by olivieryuyu** [comment]
fixed

**Comment by olivieryuyu** [comment]
@gonetz 

can it be closed?
