### ISSUE TITLE
Star Wars Episode I - Racer Lens Flare Flicker.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#469]
It can't be easily shown in screenshots, but GLideN64 doesn't reliably stop the sun flares rendering through walls, leading to an intermittent flicker. Changing settings doesn't seem to help.

**Comment by purplemarshmallow** [comment]
It's a problem with depth buffer emulation. Lights are visible through walls. If copy depth buffer is enabled they are still visilbe but flickering. Enabling frame buffer emulation kills performance in this game. It's below fullspeed in HLE on my system
![gliden64_star_wars_ep1_racer_005](https://cloud.githubusercontent.com/assets/7283660/7440423/8ea7d0e6-f0b3-11e4-9da7-00f631a12b6d.jpg)

**Comment by purplemarshmallow** [comment]
I did more testing and found out the mupen64plus version does not have this problem, it only happens with the zilmar spec version. Also the test build from #563 works for some reason.

**Comment by gonetz** [comment]
Seems to be fixed now.
@AmbientMalice -  please test and close. 
Test build:
https://drive.google.com/file/d/0B0YqMPjGo3B2MmpmNm5rTnJmdEU/view?usp=sharing

**Comment by AmbientMalice** [comment]
Problem is fixed. Worth noting GLideN64 has massive performance problems in this game if Counter Factor 1 is used.

**Comment by LegendOfDragoon** [comment]
>Worth noting GLideN64 has massive performance problems in this game if Counter Factor 1 is used.

1964 seems to get significantly better performance with cf=1 in that game. Same with games like Nuclear Strike.
