### ISSUE TITLE
Rocket Robot on Wheels - Bad Textures.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#471]
GLideN64:
![gliden64_rocketrobotonwheels_000](https://cloud.githubusercontent.com/assets/10704701/7440388/c679e270-f0f4-11e4-9499-d13667380d73.jpg)

Glide64:
![glide64_rocketrobotonwheels_01](https://cloud.githubusercontent.com/assets/10704701/7440389/e0b3eab4-f0f4-11e4-95bc-4515de92f42d.png)

This issue affects a number of other games.

**Comment by thecoreyburton** [comment]
I had a similar issue and was concerned about texture filtering. I found setting the windowed resolution to 960x720, and toggling filtering and enhancements to "off" fixed it. I did have to restart the emulator however, changes weren't immediate as with some of the other plugin features.

**Comment by gonetz** [comment]
Fixed with 
https://github.com/gonetz/GLideN64/commit/f7ee508c94fabd3485377c3bb0fd82758f37afba
