### ISSUE TITLE
Starcraft 64 Missing Images.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#472]
When you begin a new mission, a still image displays, such as this one.

![gliden64_starcraft_64_000](https://cloud.githubusercontent.com/assets/10704701/7440399/6ff5116c-f0f5-11e4-9c7c-429ffd7af133.jpg)

In LLE mode, these render correctly.

In HLE mode, they render as a blank screen.

However, loading a save state in HLE mode, regardless of whether save state was made with LLE or HLE, will make the image render. This might in theory be a problem related to the CPU framebuffer writing handling, but Glide64 ran this game fine.

**Comment by phly95** [comment]
What's wrong with using LLE?

**Comment by Predator82Germany** [comment]
May other things didn´t work in this game with LLE?

**Comment by phly95** [comment]
Well, play it through and find out. This plugin actually officially supports LLE, so if it works, then no worries. Though I think there should be some type of warning for games that only work properly under LLE.

**Comment by purplemarshmallow** [comment]
LLE ingame
![gliden64_starcraft_64_000](https://cloud.githubusercontent.com/assets/7283660/8434564/6a963612-1f4c-11e5-8898-190fbfb49d6c.jpg)

**Comment by AmbientMalice** [comment]
The screens working in LLE may have something to do with the fact depth/frame buffering is badly broken in LLE.

**Comment by purplemarshmallow** [comment]
If you complete a mission there's a similar problem. The image is incorrect but if I load a savestate it's correct (HLE)
![gliden64_starcraft_64_002](https://cloud.githubusercontent.com/assets/7283660/8435910/94d2de28-1f54-11e5-8980-0908920ce7e8.jpg)

**Comment by phly95** [comment]
I actually just recently tried LLE with majoras mask and it was really slow and buggy, so I guess LLE is not actually the best option

**Comment by standard-two-simplex** [comment]
Does entering/exiting fullscreen also solve them? I think it did when I tested, but since I had incredible slowdowns (99% CPU usage on r4300 side) couldn't be sure that was the problem.

It might be the same as this #478.

**Comment by phly95** [comment]
Not if he has an Intel ( https://github.com/gonetz/GLideN64/issues/576 ) obviously he doesn't since he is using save states and likely has the updated drivers

**Comment by phly95** [comment]
Save states are something I can live without, but if it's the only way to fix a bug, I guess it can be bad

**Comment by purplemarshmallow** [comment]
entering/exiting fullscreen does not help

**Comment by purplemarshmallow** [comment]
here's the savestate
the screen will load correctly but if you press A the next screen is also incorrect
https://drive.google.com/file/d/0B7Y6r4SpC_QQSEk4MnI4eFh4blU/view?usp=sharing

**Comment by olivieryuyu** [comment]
seems a HLE issue.

it works perfectly with Glide64 btw
