### ISSUE TITLE
Crash after save texture cache to hard disk

### ISSUE THREAD

**Issue by harlayzhou** [gonetz/GLideN64#476]
Project64 2.2.0.3
Crash after save texture cache to hard disk.

**Comment by gonetz** [comment]
More details please.

**Comment by waltzz92** [comment]
I am having the same issue as well. Here are my settings:

![gliden64 settings 1](https://cloud.githubusercontent.com/assets/12215466/7443697/732f6afc-f114-11e4-8785-be9c44dcd7d4.jpg)

![gliden64 settings 2](https://cloud.githubusercontent.com/assets/12215466/7443699/7eda608c-f114-11e4-80a2-a570f8ed524e.jpg)

I am using Project64 2.2.0.3 default settings. Every time I end emulation with any texture enhancement enabled, including "store", the emulator crashes. The crash happens on both windowed mode and fullscreen.

**Comment by gonetz** [comment]
Try older version of Project64 or another emulator. Project64 2.2.0.3 has a bug: if you loaded a savesate, plugin will not be de-initialized properly on exit.

I can't reproduce that crash even with Project64 2.2.0.3

**Comment by olivieryuyu** [comment]
@gonetz 

can it be closed?
