### ISSUE TITLE
Snowboard Kids causes segmentation fault

### ISSUE THREAD

**Issue by 7oxicshadow** [gonetz/GLideN64#477]
Core: Goodname: Snowboard Kids (E) [!]
Core: Name: SNOWBOARD KIDS      
Core: MD5: AB4382E583AE139EEDBAFCE5FA87E4C8
Core: CRC: 5FD7CDA0 D9BB51AD
Core: Imagetype: .v64 (byteswapped)
Core: Rom size: 8388608 bytes (or 8 Mb or 64 Megabits)
Core: Version: 1448
Core: Manufacturer: Nintendo
Core: Country: Europe (0x50)

Tested with mupen64plus on Linux. The emulator opens, shows a corrupted version of "Mupen64plus starting" and then the emulator instantly closes with segmentation fault.

**Comment by gonetz** [comment]
Well, on Windows emulators does not close instantly. It shows logos and then crashes.
I'l fix it. Currently you may disable frame buffer emulation for this game to bypass that bug.

**Comment by Predator82Germany** [comment]
Seems fixed

**Comment by 7oxicshadow** [comment]
Confirmed fixed with 1.1
