### ISSUE TITLE
Ogre battle missing textures (solved when going into/out of fullscreen)

### ISSUE THREAD

**Issue by standard-two-simplex** [gonetz/GLideN64#478]
The text is missing in the upper left box and textures in the menu in the middle.

![e05979f2-f0dc-11e4-83d7-3a2343cea248](https://cloud.githubusercontent.com/assets/12202580/16409737/56493a50-3d1f-11e6-8b25-a75ef931a006.png)

**Comment by AmbientMalice** [comment]
What version of PJ64 are you using?

**Comment by standard-two-simplex** [comment]
Its 2.2. I'll upload a save for easy testing now. It also happens in mupen64+ 2.5.

**Comment by AmbientMalice** [comment]
The reason I ask is because Ogre Battle 64 is broken in vanilla PJ64 2.2

**Comment by standard-two-simplex** [comment]
http://s000.tinyupload.com/?file_id=19787580719647874328

**Comment by standard-two-simplex** [comment]
The main issue, i.e. textures not loading, is fixed, so I close. The sprite misalignment is still there, but I believe it is a general problem.

**Comment by standard-two-simplex** [comment]
This issue has resurfaced between the revisions you published between the 12th of june and the 19th of june. There's only one commit those days to fix zelda pause screen.

I edited the first post and title to make things clearer.

**Comment by oddMLan** [comment]
You sure you dont have Native Res Texrects on this time?

**Comment by standard-two-simplex** [comment]
Its not on. The 12th june version was working and 19th june version isn't, both with the same settings. Can't you reproduce?

**Comment by oddMLan** [comment]
I can't test atm, I don't have my computer with me anymore
