### ISSUE TITLE
Missing Fade Transitions (Ex. Banjo Kazooie)

### ISSUE THREAD

**Issue by thecoreyburton** [gonetz/GLideN64#481]
Some fade transitions are missing in games. An example is the opening logos in Banjo-Kazooie, after the mosquito hits the Rareware logo the screen suddenly jumps to white in this plugin. In reality, it's supposed to fade to white.

**Comment by thecoreyburton** [comment]
Could this be a problem on the emulator's side? Or is definitely graphical?

**Comment by olivieryuyu** [comment]
confirmed for BK

**Comment by gonetz** [comment]
Please test with latest master.

**Comment by AmbientMalice** [comment]
Fixed.
