### ISSUE TITLE
Windowed resolution contains no widescreen resolutions

### ISSUE THREAD

**Issue by wfowler1** [gonetz/GLideN64#484]
In the GLideN64 settings, the "Windowed resolution" drop-down contains no widescreen resolutions. The closest thing available is 1600x1024, which has a 1.5625:1 aspect ratio. Ideally, there would be 1.6:1 (16:10) ratios or 1.7777:1 (16:9) ratios available.

It seems the "Full screen resolution" option grabs information directly from the currently active graphics device and so doesn't suffer this problem.

**Comment by thecoreyburton** [comment]
You can set a custom resolution in the ini file. I used this for 1600x900 to test and it works perfectly. The only issue is opening the plugin settings again resets it to one of the listed resolutions. Maybe a custom resolution button would be a good idea, but for now this is an adequate workaround I've found.

**Comment by Mushman** [comment]
I was wanting to implement a custom resolution option sometime after @gonetz released the repository. If this isn't changed, I'll do it. I also use the workaround @thecoreyburton mentioned.

Now that I think about it, would PAL games need specific resolution settings or do they just work as is?

**Comment by oddMLan** [comment]
I noticed this too.
It would be convenient to add 16:9 resolutions to the Windowed Resolution list without having to go fullscreen.

**Comment by AmbientMalice** [comment]
And lest we forget, 16:10 resolutions.

**Comment by PFCKrutonium** [comment]
And we should not forget super widescreen resolutions too.

**Comment by Mushman** [comment]
21:9 resolutions wouldn't work without tweaking the widescreen hack to expand even wider. It would definitely be best if there was someway to set an arbitrary render area though. The only game you can achieve 21:9 on is Jet Force Gemini using its widescreen mode that letterboxes instead of going anamorphic combined with the existing widescreen hack.

**Comment by thecoreyburton** [comment]
Perhaps a box to input a custom windowed resolution would be a good add-on.

Does the "adjust" radio button tweak the render area to match the resolution?

**Comment by Mushman** [comment]
No. It's hardcoded to 16:9 I'm pretty sure.

**Comment by gonetz** [comment]
> Does the "adjust" radio button tweak the render area to match the resolution?

Yes.

BTW, 1440x1080 is widescreen windowed resolution.

**Comment by wfowler1** [comment]
1440x1080 is 4:3.

**Comment by gonetz** [comment]
yep, sorry. 1600x1024 is not 4:3

**Comment by oddMLan** [comment]
Still, that's too big for most monitors, the maximum resolution my monitor supports is 1366x768. It would be handy to have  windowed widescreen resolutions analogue to the most common ones (640x480, 800x600, 1024x768) to accommodate most people.

**Comment by gonetz** [comment]
I don't mind

**Comment by thecoreyburton** [comment]
I agree with oddMLan, perhaps add 16:9 variants of common resolutions (854x480, 1366x768) and also frequently used 16:9 resolutions (960x540, 1280x720, 1600x900, 1920x1080) to the list.

**Comment by thecoreyburton** [comment]
And to accommodate people with other aspect ratios and resolutions, perhaps add an option "custom" to the list too. When it's selected there can be two text boxes "width" and "height" and the person can type their custom resolution if need be. That way all scenarios are met

**Comment by PFCKrutonium** [comment]
TBH I think ideally it would just be a custom input - no defaults added.

**Comment by thecoreyburton** [comment]
I'd be okay with that too, keeps the default resolutions the same aspect as the actual console's output.

**Comment by PFCKrutonium** [comment]
TBH if I knew C or C++ I would be all over this already :/

**Comment by gonetz** [comment]
I added custom windowed screen resolution option to GUI.
Select 'custom' from Windowed resolution combobox and set desired window size.

Binary:
https://drive.google.com/file/d/0B0YqMPjGo3B2RDgwUjJGZTVnRHM/view?usp=sharing
