### ISSUE TITLE
Mario Tennis Character Select Blank

### ISSUE THREAD

**Issue by waltzz92** [gonetz/GLideN64#488]
Choosing any character who completed the Star Cup results in a blank character select screen.
Steps to reproduce:
1. Complete Star Cup with a character.
2. Select 1 player mode and choose a character you won Star Cup with.
3. Choose Exhibition. When picking CPU characters, the words "Character Select" and all player details are blank.
![mario tennis character select](https://cloud.githubusercontent.com/assets/12215466/7443442/1911879a-f0ff-11e4-82a8-f367b1c14dbf.jpg)

![mario tennis character select 2](https://cloud.githubusercontent.com/assets/12215466/7443467/6acec114-f100-11e4-8703-0c1ee3f02161.jpg)

Using default settings for both Project64 2.2.0.3 and GLideN64.

**Comment by AmbientMalice** [comment]
Possibly related to https://github.com/gonetz/GLideN64/issues/215 where the second character doesn't render in the VS screen.

**Comment by waltzz92** [comment]
Hello. I wanted to let everyone know that this problem has been fixed by GLideN64 Public Release 1.1. Closing this issue.
