### ISSUE TITLE
GoldenEye - 4-Player Flickering

### ISSUE THREAD

**Issue by sweatypickle** [gonetz/GLideN64#489]
When selecting the Facility level in 4-player, flickering/seizuring occurs as shown in the image, making it unplayable.  As in issue #459, exiting or entering fullscreen seems to fix this. This doesn't work in mupen.   So close to being KING OF THE UNIVERSE!
![gliden64_goldeneye_003](https://cloud.githubusercontent.com/assets/12215615/7443885/7993db16-f138-11e4-8ffb-eb5252fd9004.jpg)

**Comment by sweatypickle** [comment]
After testing, while entering or exiting fullscreen corrects the flickering, it introduces waffle looking artifacts. This occurs on the frigate level in #459 as well.
![gliden64_goldeneye_011](https://cloud.githubusercontent.com/assets/12215615/7449109/fba8cb8e-f1fb-11e4-94eb-34424dc0ca58.jpg)

**Comment by purplemarshmallow** [comment]
Flickering stops if you switch window/fullscreen

**Comment by gonetz** [comment]
waffle looking artifacts often appears after savestate load. Another savestate load may fix it.

>Flickering stops if you switch window/fullscreen
Looks like frame buffer validity check fall. Try to change validity test method.

**Comment by purplemarshmallow** [comment]
a different validity test method does not help
strange
if I turn mip-maps off flickering is gone
but if I turn framebuffer emulation off and mip maps are on flickering is also gone

**Comment by sweatypickle** [comment]
specifically, turning off the depth buffer to RDRAM stops the issue. Texture loading issues in #459 are also resolved.

**Comment by baptiste0602** [comment]
Seems fixed

**Comment by gonetz** [comment]
Fixed in latest WIP
