### ISSUE TITLE
F1 Pole Position 64: ENORMOUS gx errors

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#49]
No comment ...

![f1](https://cloud.githubusercontent.com/assets/8987490/4693740/418c3f42-57aa-11e4-89b2-9cb6505ec92a.jpg)

**Comment by gonetz** [comment]
Fixed.

**Comment by gonetz** [comment]
Copy frame buffer to RDRAM is required to get correct car tuning menu.

**Comment by olivieryuyu** [comment]
game doesn't start

**Comment by gonetz** [comment]
Hmm, mupen64plus build has problems with that games. I'll check what's wrong.

**Comment by gonetz** [comment]
The problem is with mupen64plus on screen display callback function. It breaks some OGL state, which the game does not restore. I don't have time to dig in mupen64plus innards, so let's use Zilmar's build to test this game.
