### ISSUE TITLE
Top Gear Rally Black Swipe Effect in Menus issue

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#490]
When you navigate the menus in TGR the black swipe effect doesn't transition across the screen fully.

This effect seems to work fine without FB emulation turned on.

Press A, then B to see the issue while in the menus.
![capture](https://cloud.githubusercontent.com/assets/9299743/7444078/09342aaa-f12a-11e4-9a98-8332edf4d481.PNG)

**Comment by AmbientMalice** [comment]
This might sound weird, but the wipe seems to "jerk" at that point of the screen on Angrylion's.

**Comment by theboy181** [comment]
Seems OK now.  GJ!!
