### ISSUE TITLE
Unusual performance problem

### ISSUE THREAD

**Issue by Wellkins** [gonetz/GLideN64#498]
When transparency anti-aliasing is enabled in the NVIDIA control panel, paired with GlideN64 built-in anti-aliasing, performance decreases significantly, to make the game (Majora's Mask) completely unplayable. When I try to override the settings of the plugin with the ones from the control panel, it's even worse.

I don't think it's a config problem. I never had such problems with the previous plugin, Glide64, as well as Jabo's built-in anti-aliasing (performance aren't that bad in both case, even not affected at all). Same thing for any non-emulated games, DirectX or OpenGL. Maybe an optimization problem?

I'd like to be able to use transparency anti-aliasing because I work on an very detailed texture pack and it greatly improve the quality of distant textures.

*Sorry for my poor english.

**Comment by AmbientMalice** [comment]
I don't think GLideN64's framebuffer is compatible with forced AA. Dolphin has the same problem, AFAIK.

**Comment by theboy181** [comment]
Any links to your texture pack? I always enjoy good texture mods.

**Comment by fallaha56** [comment]
Try setting the AA to Sparse Grid using nvidiaInspector -I have no problems running 4xSSAA@1080p on my GTX970

**Comment by Wellkins** [comment]
Thanks for the reply, but the issue is gone since I have changed my video card (GTX 750Ti) and the SSAA works without any problems now. It was probably because of my poor laptop card.

@theboy181 : Not at the moment, I'm still working on it. I will post some screenshots soon on EmuTalk.net. Stay tuned!
