### ISSUE TITLE
Banjo Tooie: certain textures change/shift

### ISSUE THREAD

**Issue by WizLizard** [gonetz/GLideN64#499]
https://www.youtube.com/watch?v=--Yw8LaqV9U

I think this is worth looking into. I've tested both jacobsd3d8 and original glide plugin in the current project64 2.2. Just watch the video, the issue occurs with default setting and any custom settings that i have tried. This is the U version.

**Comment by theboy181** [comment]
Are you using texture enhancements?

**Comment by WizLizard** [comment]
I can confirm the same exact issue exists in mupen64.

**Comment by WizLizard** [comment]
LLE is not

**Comment by WizLizard** [comment]
Accidentally closed this trying to edit a comment. Oops! Reopened, my bad.

**Comment by gonetz** [comment]
Will be fixed soon.

**Comment by WizLizard** [comment]
Glad to hear! I should mention that i tested with LLE and this issue doesn't exist but a good portion of the right side of the screen is not displayed in full screen mode (about 1/4). Not an issue in windowed mode. Maybe i should open an issue for it?

**Comment by gonetz** [comment]
One issue more, one issue less...Ok, please open.

**Comment by WizLizard** [comment]
Public Release 1.1 fixed it.
