### ISSUE TITLE
Donkey Kong 64 (U): Character Model Stretching/dissappearing

### ISSUE THREAD

**Issue by PermaNulled** [gonetz/GLideN64#504]
Using latest Mupen64 ( mupen64plus-bundle-win32-2.0 )
Specs
Windows 8.1
GTX 780ti 4GB GDDR5
16GB RAM DDR3 1600mhz
Intel i7 4770k 3.5ghz
Samsung 250gb enterprise SSD.
(Even though I believe processor and such is unrelated I'll provide it anyways)

First I want to compliment the plugin for the most part it runs exceptionally well I'm able to achieve 60fps consistently no problem.

The actual bug...
After the first few minutes of playing I had noticed a few graphical glitches one was really strange when climbing a tree it made the game unplayable and later stopped occuring (The whole screen would turn black for awhile, sometimes the texture of the tree would still be there and be corrupted)

The only one I was able to capture was the graphics being distored/stretching.

The character also seems to bounce up and down slightly
![DK Screencap](http://i.gyazo.com/5de8e4269184284ff79e670b99a19e15.gif)
![DK Screencap2](http://i.gyazo.com/8e9a9354579c2e6c853029803ee1bc43.gif)
![DK Screencap4](http://i.gyazo.com/a568021d47466a6512ea893496dcd8ff.gif)
Lighting also gets strange here.
![DK Screencap5](http://i.gyazo.com/33af34f0e381d76c97ab98462ea3758f.gif)
Here's an example of climbing the tree
![DK Screencap3](http://i.gyazo.com/bd4137549aed33888913bb7aff730a19.gif)

**Comment by purplemarshmallow** [comment]
That's a bug in the emulator core
This game would require better timing and no emulator is currently good enough
these glitches are there with angrylion's pixel accurate plugin so GLideN64 can't fix it

**Comment by AmbientMalice** [comment]
This is an emulator core issue. PJ64 currently seems far less prone.

**Comment by Predator82Germany** [comment]
Report it @ Pj64
