### ISSUE TITLE
anisotropic filtering not working

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#505]
If I enable it in the config dialog it does not work. And if it is forced in the Nvidia settings it still does not work. The difference is obvious if I compare with Glide64.
GLideN64 16x AF
![gliden64_goldeneye_001](https://cloud.githubusercontent.com/assets/7283660/7473344/caf5fc7e-f33a-11e4-9bb1-84d1a46ad88f.jpg)
Glide64 AF enabled
![glide64_goldeneye_01](https://cloud.githubusercontent.com/assets/7283660/7473350/d688e01a-f33a-11e4-88f7-265daeb848d9.png)

**Comment by AmbientMalice** [comment]
This is likely mipmap related, but I haven't tested AF myself. Does disabling mipmaps change this behavior?

**Comment by purplemarshmallow** [comment]
No, looks the same without mipmaps

**Comment by gonetz** [comment]
What is wrong on this screen shot? Water?

**Comment by purplemarshmallow** [comment]
The problem affects every game but I added these pictures as an example because here you can see it very clear. The water should be fltered if anisotropic filtering is enabled (see Glide64 screenshot) but anisotropic filtering does not work.

**Comment by gonetz** [comment]
Will be fixed soon

**Comment by purplemarshmallow** [comment]
confirmed
good work
