### ISSUE TITLE
Perfect Dark Target Test target not displaying correctly

### ISSUE THREAD

**Issue by CraigClements** [gonetz/GLideN64#506]
Hi there. I found a small bug in GLideN64 Public Release to do with the Firing Range in Perfect Dark (U) (V1.1). To view this bug, you need to clear any of the weapon tests in the firing range on any difficulty.

The target is displayed incorrectly like so:

![pd_bug](https://cloud.githubusercontent.com/assets/12258094/7477938/1757e60e-f34f-11e4-9add-e4a3527f4649.png)

Turning off all of the texture enhancements as well as anti-aliasing and anisotropic filtering does not fix this.

Here, the target is displayed correctly with Glide64:

![pd_bug1](https://cloud.githubusercontent.com/assets/12258094/7477946/210594b2-f34f-11e4-8e31-09f2fd7cdde4.png)

Thank you.

**Comment by gonetz** [comment]
Could you give me a savestate? I never played this game and don't know where to find the Firing Range and how to clear the weapon tests.

**Comment by baptiste0602** [comment]
Here : https://drive.google.com/file/d/0ByOA3_oOu6O9S25tNjhqOWIwWFU/view?usp=sharing

**Comment by gonetz** [comment]
Thanks, I'll check it.

**Comment by AmbientMalice** [comment]
@CraigClements I think this can be closed?

**Comment by olivieryuyu** [comment]
can it be closed???
