### ISSUE TITLE
Corrupt borders on Conker bad fur day. (Only in linux)

### ISSUE THREAD

**Issue by bougar** [gonetz/GLideN64#508]
Hey, first of all congratulation by your good job.
The problem is not so big, but it is really annoying because it is flashing all the time.
![captura de pantalla de 2015-05-06 00 56 21](https://cloud.githubusercontent.com/assets/8965121/7484841/f2222e50-f38d-11e4-9c63-c258e06bb1d6.png)
I would like know if you have the same issues on linux.

**Comment by WizLizard** [comment]
I've noticed this on quite a few games with windows. Mario Kart and Bomberman 64 the Second Attack! just to name a couple. Seems to be a common issue.

**Comment by Yar4e** [comment]
I have the same issue in this game on Linux! Looks like its FBE related problem. 
Linux Mint 17.1
3.16.0-28-generic
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 970/PCIe/SSE2
OpenGL core profile version string: 4.3.0 NVIDIA 346.59
Mupen64Plus 2.5.0 + m64py 0.2.3 + GlideN64 PR 1.1

**Comment by matthewharvey** [comment]
Does this happen in the menu where you select which game you want? It's the bar? I just had a quick check and I don't see this happening on the following system:
Linux (Debian 9 in testing) 4.1 kernel
Intel HD4000 using the Mesa renderer version 3.3
mupen64plus from git + GLideN64 from git (495e0c7b9...)
Could be an NVidia only problem? I don't have one of their cards, otherwise I'd check.

**Comment by gonetz** [comment]
@bougar  seems to be fixed now. At least works as good as Windows build. Please test.

**Comment by bougar** [comment]
Yeah. Now it works properly. Sorry late response.

**Comment by orbea** [comment]
Can this issue be reopened? It seems to be occuring again. Here are some images from the above referenced issue.

![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/Conker's%20Bad%20Fur%20Day%20%28USA%29-160913-191045.png)
![2](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/Conker's%20Bad%20Fur%20Day%20%28USA%29-160913-192750.png)
