### ISSUE TITLE
Frequently hangs and crashes

### ISSUE THREAD

**Issue by jimbo1qaz** [gonetz/GLideN64#509]
Majora's Mask, M64Py Windows.
Plugin frequently slows down, stutters, then outright hangs for me.
Issues do not occur on Glide64mk2.

**Comment by gonetz** [comment]
It is a complaint, not a bug report.
I can't solve your problem with that piece of information.

Please specify:
Your hardware details,
M64Py version,
Plugin settings,
Scenarios: where slowdowns occur; where the game hangs. Try to find a place where the problem reproduced and give me savestate from that place,

Please understand: I don't have time to play games in search of possible slowdowns. Currently I can solve only those problems, which can be instantly and regularly reproduced.

**Comment by Mushman** [comment]
One scenario I can think of which can cause hangs and crashes is changing GLideN64's settings while a game is running. I was testing Paper Mario for another issue and frequently turned frame buffer emulation on and off, halting the emulator after a few times in one session. I considered this unideal use and thought that it might be an expected fault, so I haven't reported it myself.

**Comment by jimbo1qaz** [comment]
No, that's not my issue.
M64py can't even change settings mid-game, at least in latest Windows
stable.
I also think I got a crash without load state.

**Comment by Mushman** [comment]
Well, can you describe the steps you take to encounter the crashes you've found so that we may reproduce them?

**Comment by jimbo1qaz** [comment]
Some time in the future.
I don't want to debug the issue now, prefer to play games using working
plugins, and I'm busy.

**Comment by gonetz** [comment]
Ok, close until more details provided.

**Comment by jimbo1qaz** [comment]
I remembered to save state so I wouldn't lose progress in case of crash. It said "insufficient memory for save state". Ironically, it crashed a few seconds later, rendering my foresight useless. (M64Py used up ~400K KiB memory, private working set)

It might be a memory leak. The error's definitely random, and triggered randomly, sometimes when the game is beginning a new action (render bomb explosion, navigate menu, etc.)

I retested, then got error 0xE06D7363 in M64Py console. That's a generic VC++ exception code. (M64Py used up 465K KiB memory, private working set)

Is the increase of memory usage a result of caching textures, or a memory leak crash?

**Comment by jimbo1qaz** [comment]
Summary: I think cacheSize affects the time to crash - Lowering it causes the crash to happen sooner. If this is a texture issue, you must be in a texture-generating area... right???
Majora's Mask, reload from start, didn't crash in 3 in-game hours (was thinking of using in game clock as a timer).
Final boss fight, got a crash sooner (I did load a savestate though).
