### ISSUE TITLE
Star Wars Episode I - Racer (J)  Displaying wrong text.

### ISSUE THREAD

**Issue by exhalatio** [gonetz/GLideN64#510]
GLideN64 is wrong.
based glN64 graphics plugin is also wrong.
![gliden64](https://cloud.githubusercontent.com/assets/7089513/7488675/78eaac4e-f408-11e4-9e42-dbcea7d5b547.png)

Glide64 is correct.
![glide](https://cloud.githubusercontent.com/assets/7089513/7488678/7e5bbea2-f408-11e4-8f04-acaf9ef17beb.png)

**Comment by Mushman** [comment]
Oh wow. That's a really weird bug. For reference, the line of Japanese on top in the (U) version is the English title for the game. While I'm not certain exactly what characters the line should have, look at the number at the very right. In Glide64 it's a 1, consistent with the (U) version, but in GLideN64 it's a 4. Nice find.

**Comment by gonetz** [comment]
Fixed
