### ISSUE TITLE
Banjo Tooie: LLE portion of image is missing on right side

### ISSUE THREAD

**Issue by WizLizard** [gonetz/GLideN64#513]
When running the game in LLE a portion of the image is missing on the right side from top to bottom in full screen mode, window mode is fine. It seems to be due to using aa. With it on issue is present, with it off no issue. With Project64 LLE.

![screenshot 24](https://cloud.githubusercontent.com/assets/12180630/7516104/c22f0e62-f49a-11e4-9c05-d762e122c574.png)

**Comment by AmbientMalice** [comment]
This seems to be fixed.

**Comment by WizLizard** [comment]
@AmbientMalice If you have tested it and can confirm then i will close. I haven't had the time to do any testing as of late.

**Comment by WizLizard** [comment]
@AmbientMalice So is this good to close?

**Comment by AmbientMalice** [comment]
Should be, yes.

**Comment by WizLizard** [comment]
Ok closed.
