### ISSUE TITLE
Extreme-G AA & Emulate N64 depth compare

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#515]
This is an example of this combination of configuration and this game, but this combination in any game leads to this GFX issue. 
I get that the custom.ini can be set to not use AA, but I would like to know if the issue could be fixed over having to turn AA off.

![capture](https://cloud.githubusercontent.com/assets/9299743/7538623/2af22e82-f556-11e4-9f01-34279cd9f636.PNG)

**Comment by gonetz** [comment]
Unlikely. Depth image texture does not use multisampling and there is no way to use AA with it.

**Comment by theboy181** [comment]
I guess if there is no way we might want to add the option of no AA to the settings. 

Maybe post processing shaders in the future can overcome this?

**Comment by gonetz** [comment]
May be. Currently the good solution would be automatically disable AA when N64 depth compare is on.

**Comment by mudlord** [comment]
Post processing shaders could do this. You could add a SMAA postprocessing class like you did for bloom. A SMAA processing example is here: https://github.com/scrawl/smaa-opengl

**Comment by gonetz** [comment]
N64 depth compare is not post-processing shader. It is image texture which uses image load/store.

**Comment by AmbientMalice** [comment]
@gonetz he's saying that you could add a post-processing AA method. SMAA is currently the leading post-processing AA shader.

**Comment by gonetz** [comment]
Custom AA, got it. Yes,it is possible.

**Comment by theboy181** [comment]
Latest Depth Compare breaks fog in game. I was under the impression that this option was made for this game, or at least it was pointed at this game. 

AA is now disabled when you use this feature, but the last AA setting is not restored when you disable the depth compare. This is a let down. :(

**Comment by loganmc10** [comment]
What GPU do you have?

**Comment by theboy181** [comment]
GTX 1080

**Comment by loganmc10** [comment]
Do you have a screenshot? It looks normal to me
