### ISSUE TITLE
Perfect Dark lights glitch depending on angle + general 1.1 fullscreen issue

### ISSUE THREAD

**Issue by herpderpus** [gonetz/GLideN64#516]
In perfect dark the lights behave weirdly depending on where you are and at what angle you look at them. An example easy to reproduce is at the beginning of the game: start the game, select your file, when the menu appears press B to be able to move freely in carrington institute, move directly backwards and the lights will start to glitch like in this screenshot.

http://s1.postimg.org/6hacg7t3z/GLide_N64_Perfect_Dark_000.jpg

Actually nevermind the issue with fullscreen, that was my computer acting weird with all fullscreen programs, rebooting fixed it.

Using PJ64 latest, Windows 8.1, GTX660Ti.

**Comment by thecoreyburton** [comment]
Do you have hardware lighting enabled or disabled?

**Comment by AmbientMalice** [comment]
The visual artifact is like a series of squares.

![gliden64_perfect_dark_003](https://cloud.githubusercontent.com/assets/10704701/7548894/9265a326-f661-11e4-93e6-ffbdf50a11bf.jpg)

Seems to occur when viewing coronas that are overlapping or something. Even happens in LLE, which doesn't render coronas correctly.

**Comment by bankaiprimera** [comment]
I can confirm this issue. Doesn't happen with "Glide64 final", which renders it correctly.

**Comment by herpderpus** [comment]
Glide64 doesn't have that glitch but the lights flicker a lot and don't look right either. In GlideN they look right when they don't glitch out.

**Comment by gonetz** [comment]
It is an old, I would say "legacy" texture bug, which was "masked" by another bug until recently. I fixed later bug but overlooked this one. Strange, that it is reported only now: the bug exposed since and of March. The problem is that the bug nested in very core of emulation code. I can easily fix it, but that legacy code written for a purpose, and its modification can cause new glitches.

**Comment by gonetz** [comment]
@herpderpus - please test it again with this binary:
https://drive.google.com/file/d/0B0YqMPjGo3B2WUdUWFpnNk5YTXM/view?usp=sharing

and close if fixed.

**Comment by herpderpus** [comment]
Seems perfect now. Thank you.

**Comment by AmbientMalice** [comment]
This issue--or at least the main part of it--is fixed, AFAIK, so it can probably be closed.

**Comment by gonetz** [comment]
I think so. I can't download the savestate from Mega. My testing does not show extraordinary flashing.
