### ISSUE TITLE
Disable "Emulate frame buffer" breaks many things

### ISSUE THREAD

**Issue by DrHouse64** [gonetz/GLideN64#517]
Hello.
I need to disable frame buffer for performance reasons, this is the first Nintendo64 emulator plugin that takes my old 2008 MacBook to the knees. (Intel core 2 duo 2.0 Ghz, NVidia 9400m)

I realized that, when emulate frame buffer is off, some features don't work :
- Anti-aliasing
- Bloom
- Aspect ratio (Stretch whatever you checked)
- And maybe others things I didn't see/hard to see

I play with Project64 1.6.1, Windows 8.1 (BootCamp, completely native)

**Comment by AmbientMalice** [comment]
This is normal. The framebuffer is crucial to all those visual effects.

On a related note, make sure your Nvidia GPU is running in Prefer Maximum Performance mode, because GLideN64 is extremely slow with Adaptive mode.

**Comment by DrHouse64** [comment]
Thanks for the awnser :)
I'll take a look at it.
