### ISSUE TITLE
GoldenEye\Perfect Dark Portal Bug. (Caused by Noise.)

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#518]
These games use portals for some glass windows. When the player moves away from windows, the game is meant to use a black texture to conceal culling. But on GLideN64, the black texture isn't loaded correctly, and disappears when you move too far back, starting the fade all over again, and exposing the culling going on behind the texture.

![gliden64_perfect_dark_000](https://cloud.githubusercontent.com/assets/10704701/7548864/59a5a80c-f660-11e4-9367-fed86c08a174.jpg)

![gliden64_perfect_dark_001](https://cloud.githubusercontent.com/assets/10704701/7548868/62ec1bbc-f660-11e4-8563-495a8efc87ad.jpg)

![gliden64_perfect_dark_002](https://cloud.githubusercontent.com/assets/10704701/7548875/939a8b54-f660-11e4-8071-070c258cecbb.jpg)

**Comment by olivieryuyu** [comment]
any savestate please?

**Comment by AmbientMalice** [comment]
Here. http://s000.tinyupload.com/?file_id=04923948629511378333 It's for Perfect Dark 1.0 (U)

**Comment by theboy181** [comment]
exact think happens in goldeneye too.. was going to report it but got lazy

**Comment by AmbientMalice** [comment]
The culprit seems to be "emulate noise". Disabling noise cures the problem.

**Comment by gonetz** [comment]
Fixed:
https://github.com/gonetz/GLideN64/commit/1bf3b6e85afbf5be19fbb4d07e3d73f80efd9a21
