### ISSUE TITLE
Conkers BFD: Black line seems to follow Conker 

### ISSUE THREAD

**Issue by BParks21** [gonetz/GLideN64#519]
This seems to be a regression but not sure. Using PR 1.1. With AA disabled the line is gone.

![screenshot 25](https://cloud.githubusercontent.com/assets/12180630/7549353/f7a83626-f5fe-11e4-9697-e218045ba718.png)
![screenshot 26](https://cloud.githubusercontent.com/assets/12180630/7549355/f989c428-f5fe-11e4-86e6-196d8ca5e5a3.png)
![screenshot 29](https://cloud.githubusercontent.com/assets/12180630/7549356/fafa0340-f5fe-11e4-804b-dda7e54e5ddf.png)

**Comment by bankaiprimera** [comment]
I can confirm this. PR 1.0 didn't have this glitch, even with AA enabled.

Turning off anis. filtering in PR 1.1 doesn't resolve the issue; so it's not that either.

**Comment by WizLizard** [comment]
@bankaiprimera It does disappear for you when AA is off though correct?

**Comment by bankaiprimera** [comment]
Yes indeed. The black line disappears when I disable AA. But with PR 1 I had AA enabled and didn't see the black line - so it does seem to be a regression.

**Comment by AmbientMalice** [comment]
This is likely a side effect of AA being rewritten to work with framebuffer effects.

**Comment by WizLizard** [comment]
@bankaiprimera Ok.

**Comment by Yar4e** [comment]
Can't reproduce it on Linux with Nvidia card. Did you tried to upgrade or downgrade your video driver?

**Comment by oddMLan** [comment]
After the update to the Mupen64AE build, the bug became much less noticeable in PC also.

675d777
![last s week](https://cloud.githubusercontent.com/assets/7278372/13732353/4d89179e-e93e-11e5-91bf-2308204e5730.png)

0ec6d9d
![current week s](https://cloud.githubusercontent.com/assets/7278372/13732358/63966a0a-e93e-11e5-9dbf-e75b79d5daa8.png)

**Comment by AmbientMalice** [comment]
>creating a game-specific hack and crop 1px-2px of the aux buffer for the shadows.

That is really not ideal behavior, especially since Conker currently has broken auxiliary framebuffer to RDRAM copies. It's better to have a slightly broken effect than use dirty hacks to hide a problem.

**Comment by weinerschnitzel** [comment]
>Also, MSAA is something that should probably be removed and replaced with a postprocessing AA method because it breaks so much.
I agree.

**Comment by AmbientMalice** [comment]
Seems to be resolved? Can anyone else confirm?

**Comment by oddMLan** [comment]
Last time I checked, it's fixed but only if running on native res or with AA disabled. I will check again when I'm home.

**Comment by BParks21** [comment]
Fixed for me.

**Comment by ShareScene** [comment]
can this issue be closed?
