### ISSUE TITLE
Tigger's Honey Hunt : 2d missing in menu

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#52]
![sans titre](https://cloud.githubusercontent.com/assets/8987490/4694750/3ae14ee2-57d4-11e4-82b6-35b094b7cec6.jpg)

**Comment by olivieryuyu** [comment]
fixed enabledepthcompare option, no need of coverage :)

but this option is slow!

Fixed?

**Comment by gonetz** [comment]
The option is slow because I can't use triangles cache with it. But imo it's better than a hack. May be someday I'll find a way to make it faster. Let's consider it as fixed.

**Comment by olivieryuyu** [comment]
fixed
