### ISSUE TITLE
Linux: Top Gear Rally "Micro Stuttering"

### ISSUE THREAD

**Issue by 7oxicshadow** [gonetz/GLideN64#520]
Core: Goodname: Top Gear Rally (U) [!]
Core: Name: TOP GEAR RALLY      
Core: MD5: 6F7030284B6BC84A49E07DA864526B52
Core: CRC: 62269B3D FE11B1E8
Core: Imagetype: .v64 (byteswapped)
Core: Rom size: 8388608 bytes (or 8 Mb or 64 Megabits)
Core: Version: 1448
Core: Manufacturer: Nintendo
Core: Country: USA

Tested on 1.1 release but is present on earlier revisions. When in game the sound and video seems to suffer from "stuttering".

See: https://youtu.be/crmM89UvdUk

**Comment by olivieryuyu** [comment]
this is a emu core issue, not a gfx issue.

You can compare with other plugin

please close

**Comment by 7oxicshadow** [comment]
Sorry, I should have checked that first. Confirmed that it is a problem with the emu core.
