### ISSUE TITLE
Mario Tennis: 'hot air' distortion not working/not implemented?

### ISSUE THREAD

**Issue by fallaha56** [gonetz/GLideN64#521]
![image](https://cloud.githubusercontent.com/assets/11017537/7551878/d06570b4-f690-11e4-8b54-796286159aff.png)

-can't see this effect in Mario Tennis but did see it in the blog, bug or not yet implemented

**Comment by gonetz** [comment]
Rather 'hot air' distortion is a bug. At least, I can't enable that effect on real system. "Hot ball" is a frame buffer effect indeed, but now it works as on real N64.

**Comment by fallaha56** [comment]
Maybe you need to hit the ball harder? Lol

Seemed pretty convincing effect from the blogspot screenshot -was that from GLideN64, Glide64, software renderer or the real machine?

**Comment by theboy181** [comment]
@gonetz 

How can a person enable it on your plugin? its actually a very pretty bug.

**Comment by gonetz** [comment]
I don't understand: do you want me to break plugin's code to return that bug back?

**Comment by Predator82Germany** [comment]
Is that a bug?

**Comment by theboy181** [comment]
I think the effect was very nice looking in this game. I wouldn't call it a bug, I would call it an  enhancement. ;)

**Comment by gonetz** [comment]
It is a bug. Watch any video from real N64, e.g.

https://www.youtube.com/watch?v=HRgdH0s2k-Y
or
https://www.youtube.com/watch?v=qR5glDlv00c

No hot-air distortion. I don't know how I did it :)

**Comment by theboy181** [comment]
Too bad. This made your pluging stand out like it has enhanced features. Something that others have not accomplished. Do we know when the bug started.

**Comment by gonetz** [comment]
Try first monthly beta or NewYear beta. It should be there.
