### ISSUE TITLE
Super Mario Star Road: Nearly everything is black

### ISSUE THREAD

**Issue by lKomus** [gonetz/GLideN64#525]
Everything in the game is pretty much black (even the game logo at the start) except for Mario, trees, the sky, the water, the HUD, the file and star select screens, and other elements.

This issue was not present with the old Glide64.

Tested on Project64 1.6 and 2.2.

-
With GLide N64 1.1
![ss 2015-05-10 at 01 50 37](https://cloud.githubusercontent.com/assets/4800879/7552485/2268820e-f6b7-11e4-848d-4359335a1a94.jpg)
![ss 2015-05-10 at 01 44 52](https://cloud.githubusercontent.com/assets/4800879/7552476/c4b3c2ae-f6b6-11e4-80d3-66de5ede6219.jpg)
With Glide64 for PJ64 2.0.0.5
![ss 2015-05-10 at 02 04 08](https://cloud.githubusercontent.com/assets/4800879/7552519/e3380cc4-f6b8-11e4-8ef9-1c76349cb56f.jpg)
![ss 2015-05-10 at 02 06 25](https://cloud.githubusercontent.com/assets/4800879/7552524/37ce7890-f6b9-11e4-8262-6015bfc5ebdf.jpg)

**Comment by Mushman** [comment]
Might be related to #431.

**Comment by thecoreyburton** [comment]
I had just come here to post the same comment, Mushman. 

I'd suggest trying the same steps that lead to my issue (#431) being resolved. 

Try play the hack with angrylions pixel-accurate video plugin. If the textures are still black then it's being emulated correctly and GLideN64 is not at fault. The hack likely took advantage of the way less-accurate plugins emulate the video side of things.

**Comment by lKomus** [comment]
I tried with angrylions' plugin, and now the whole screen is black. Not sure if I should keep this issue open because GLideN64 doesn't "show" a black screen like this more accurate plugin.
