### ISSUE TITLE
Pokemon Stadium 2 anti-aliasing breaks some effects

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#526]
introduced in version 1.1
AA off
![gliden64_pokemon_stadium_2_014](https://cloud.githubusercontent.com/assets/7283660/7566159/97a50d64-f7f5-11e4-84a9-f6dab9d03fc3.jpg)
AA on
![gliden64_pokemon_stadium_2_014 2](https://cloud.githubusercontent.com/assets/7283660/7566163/9d786ef2-f7f5-11e4-9904-6235c66c441c.jpg)

**Comment by oddMLan** [comment]
Correct with Copy Aux Buffers to RDRAM

**Comment by purplemarshmallow** [comment]
fixed
I think https://github.com/gonetz/GLideN64/commit/04e90bee85d815ed2c5cc294a5184e00d16c5717 fixed it
