### ISSUE TITLE
Tetrisphere broken sprites

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#527]
I've opened a seperate issue because #414 is fixed
sprites in title screen are cut
![gliden64_tetrisphere_000](https://cloud.githubusercontent.com/assets/7283660/7566503/6d0ec336-f7f7-11e4-905b-b811bff66eb0.jpg)
if you play a game and then return to the menu missing sprites appear but colors are wrong
![gliden64_tetrisphere_000 2](https://cloud.githubusercontent.com/assets/7283660/7566473/4a97f0ca-f7f7-11e4-82ee-7c88b4ac8256.jpg)

**Comment by thecoreyburton** [comment]
I've noticed this too. It could be related to #450.

**Comment by purplemarshmallow** [comment]
fixed by https://github.com/gonetz/GLideN64/commit/5e5c3faed43be08a1f11bf4d880d8286af7b2233
