### ISSUE TITLE
cfb gfx issues

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#529]
"Detect CPU writes to framebuffer" needs to be enabled
the GB tower is fully functional but gfx are broken
correct with angrylion's plugin
![gliden64_pokemon_stadium_2_016](https://cloud.githubusercontent.com/assets/7283660/7574408/6c6572f0-f82d-11e4-81be-1d294eec0691.jpg)
![1](https://cloud.githubusercontent.com/assets/7283660/7574503/1784f566-f82e-11e4-916a-2e58b044cad9.jpg)

**Comment by olivieryuyu** [comment]
interesting!!

**Comment by DaEckster** [comment]
GB Tower doesn't even work properly with NRage plugin, how're you getting it to work?

**Comment by purplemarshmallow** [comment]
I did nothing special
Just PJ64 with default plugins (N-Rage for PJ64), default settings and it works

**Comment by purplemarshmallow** [comment]
correct with Glide64

**Comment by purplemarshmallow** [comment]
Namco museum 64 ploe position minigame - same problem
again Glide64 is correct
![gliden64_namcomuseum64_000](https://cloud.githubusercontent.com/assets/7283660/7775213/5a2b5230-00b1-11e5-8fe7-e4a47e5ca6fe.jpg)

**Comment by purplemarshmallow** [comment]
@gonetz VI.width is wrong
VI.cpp line 126
if I change it to:
frameBufferList().saveBuffer(*REG.VI_ORIGIN, G_IM_FMT_RGBA, size, VI.width+0x2F, VI.height, true);
ploe position looks correct
I hope this information can help you

**Comment by purplemarshmallow** [comment]
fixed
