### ISSUE TITLE
Black Screen in windowed mode

### ISSUE THREAD

**Issue by Talantyyr** [gonetz/GLideN64#530]
When i start a rom in fullscreen mode and switch to windowed only a black screen is shown. When imswitch back to fullscreen all is ok again.
Same behaviour with Project64 and Mupen64. Tested on my Surface Pro 3 with a core i3 and an intel hd 4000

**Comment by gonetz** [comment]
I can't reproduce it on my card.

**Comment by Talantyyr** [comment]
That issue is a a bit strange. When you start the plugin in windowed mode directly, it's working.

Though when you switch from windowed to fullscreen, wait a few minutes and then switch back there's a blackscreen.
When you start in fullscreen mode and switch to windowed (with alt + enter) there's also a black screen. 
Only happens with Intel HD cards what i've seen

**Comment by Talantyyr** [comment]
I've done further research. 
When the plugin is started In project64 directly in fullscreen mode, 3/4 of the screen is cut off. When i go to windowed mode, open the plugin settings the window resizes, the font becomes way larger and when i switch back to fullscreen again it's working correctly. But switching to windowed mode breaks everything. Just a blackscreen is shown even when i switch back to fullscreen.

**Comment by olivieryuyu** [comment]
can we close?

**Comment by Talantyyr** [comment]
I don't know, i don't have the surface anymore and no intel graphics card at hand. It works fine on my Radeon 290, but since no one else chimed in, either it's fixed or no one is using an intel graphics card. I'll close it, but we can reopen / reference this issue in case anyone else notices that too.
