### ISSUE TITLE
Mario Kart- thwomp textures

### ISSUE THREAD

**Issue by sublimejhn** [gonetz/GLideN64#532]
I know this is an issue in some other gfx plugins as well, but I was hoping it would be resolved in gliden64. Odd textures on the thwomps in bowser's castle, which is pretty big for me since it is one of the games I play the most. Hopefully you can get around to fixing it

**Comment by WizLizard** [comment]
Here's what it looks like. Hope this is fixed in next release.
![screenshot 31](https://cloud.githubusercontent.com/assets/12180630/7647784/8ccc3722-faa8-11e4-936b-7fdddeb40799.png)

**Comment by Nes-player4Life** [comment]
Confirmed.

**Comment by gonetz** [comment]
Savestate please.

**Comment by Predator82Germany** [comment]
Only drive Bowsers Castle

**Comment by gonetz** [comment]
No time for drive.

**Comment by WizLizard** [comment]
I can provide a save state later tonight.

**Comment by WizLizard** [comment]
@gonetz Here is a save state. https://drive.google.com/file/d/0By-W8sjqLxiyd1Z3bUpkZWNUS1U/view?usp=sharing

**Comment by gonetz** [comment]
Thanks for the save. Fixed.
It was harder than I thought. I had to dig in Angrylion's code. Right code requires non-trivial manipulation with input data. I wonder, how he found that solution.

**Comment by Predator82Germany** [comment]
Comes a binary?

**Comment by gonetz** [comment]
Binary:
https://drive.google.com/file/d/0B0YqMPjGo3B2WUdUWFpnNk5YTXM/view?usp=sharing

**Comment by WizLizard** [comment]
Np glad its fixed.

**Comment by gonetz** [comment]
@sublimejhn please test and close if fixed.

**Comment by sublimejhn** [comment]
Thanks for the hard work!

**Comment by standard-two-simplex** [comment]
Is the mupen64plus binary the correct one?
The one for zilmar spec emulators works but the one for mupen64plus doesn't.

**Comment by gonetz** [comment]
Does not work at all or does not fix that bug?

**Comment by standard-two-simplex** [comment]
The bug is not fixed in the Mupen64Plus binary you linked above. It boots correctly.

**Comment by gonetz** [comment]
It is very strange. Mupen64Plus build uses the same texture code. May be I built it from wrong commit.
Could you give me savestate for Mupen64Plus to check?

**Comment by purplemarshmallow** [comment]
I think Mupen64Plus can load savestates in PJ64 format

**Comment by purplemarshmallow** [comment]
But here's one in case it does not work:
https://drive.google.com/file/d/0B7Y6r4SpC_QQelppa0lyZXhmYjg/view?usp=sharing
but thwomp textures look correct for me

**Comment by standard-two-simplex** [comment]
@gonetz I thought the problem was either you compiled the wrong one or I had some wrong setting, which would be strange since they are the default ones and copyToRDRAM (activated through game ini) is on.

@purplemarshmallow Did you try the binary above or did you compile from source?

**Comment by standard-two-simplex** [comment]
Also, I noticed that this build (using PJ64) has fixed problems with texture mirroring that were present in ISS64, Zelda MM bombers notebook and probably some others in Public Release 1.1.

**Comment by purplemarshmallow** [comment]
I compiled from source so it's likely the wrong binary

**Comment by gonetz** [comment]
I tested the savestate, it's works ok. So , I must build those version from a wrong point.

Texture mirroring problem saved when I fixed #516, commit 98c9303cd
