### ISSUE TITLE
Smash Bros. - Intro Out of Sync. 

### ISSUE THREAD

**Issue by SuperL2** [gonetz/GLideN64#533]
On Smash Bros., the intro plays too fast and the intro becomes out of sync with the audio.

This is a problem with all N64 plugins, but this one has it worse than any of the others.

**Comment by LegendOfDragoon** [comment]
The sync issue is generally an audio plugin or emulator core issue. Unless you're usng vsync or something? Anyway, can you explain further, in event that there really is an additional problem.

I say this because it syncs well when using the right setup, but never tested this video plugin.

**Comment by SuperL2** [comment]
I'm using Mupen64plus, with the M64py frontend. GlideN64 is my video plugin. 

The audio just becomes gradually out-of-sync, by the time the hidden characters are flashed, the audio is severely out of sync.

**Comment by olivieryuyu** [comment]
please close it is an emu issue

**Comment by GamingHD** [comment]
If there's an option to sync the game to the audio that may fix the issue, but as others have said this is an emulator issue and not a GLideN64 issue.

**Comment by olivieryuyu** [comment]
please close this ticket
