### ISSUE TITLE
Hangs and crashes over time, possibly due to cache

### ISSUE THREAD

**Issue by jimbo1qaz** [gonetz/GLideN64#534]
See https://github.com/gonetz/GLideN64/issues/509

Since you closed the issue, I have done more research.

It doesn't crash when I do nothing after playing the Song of Time, and just hang around the Clock Tower.
It does crash in Majora boss room.
These crashes are random and cannot be reliably triggered.

Lowering "cacheSize" causes the crash to happen faster. It may or may not be a separate crash bug.
Lowering it too much will make it lag and display corrupt textures as soon as the game begins.

M64Py console shows error 0xE06D7363.

**Comment by thecoreyburton** [comment]
What hardware are you running?

**Comment by jimbo1qaz** [comment]
Windows 7 x64
Intel i7 3570k not overclocked
Nvidia gtx 660
Latest graphics drivers (not at PC, will update)
M64py latest 0.23 I think
Gliden64 PubR1 and 1.1 tested to crash (most testing was done on 1.0)

**Comment by AmbientMalice** [comment]
@jimbo1qaz Are you still having problems with latest version? If not, please close this issue.

**Comment by jimbo1qaz** [comment]
BitDefender detects EmuCR as malware. Also, my main PC is inactive at the moment. Should I close until further testing?

**Comment by gonetz** [comment]
Yes. You may reopen it later, if necessary.
