### ISSUE TITLE
64bit Zilmar Plugin Spec Support

### ISSUE THREAD

**Issue by Ember2528** [gonetz/GLideN64#537]
Seeing that there are now 64 bit builds of project64 it could be useful to allow 64 bit versions of the plugin

**Comment by gonetz** [comment]
I'll need to recompile all necessary libs with 64 bit. That is spend another GB for QT and Boost libs. Not right now.

**Comment by SwooshyCueb** [comment]
There are 64 bit builds of Project64? This is news to me.

**Comment by Ember2528** [comment]
They exist as of yesterday

**Comment by SwooshyCueb** [comment]
Cool, that saves me a lot of work. I might look into my own x86_64 pj64 build of GlideN64 when I get back in town.

**Comment by LegendOfDragoon** [comment]
zilmar still needs to do work for 64bit. Currently it doesn't work.

**Comment by SwooshyCueb** [comment]
AFAIK they're using MSVC and they have inline assembly. If they want to continue using MSVC they'd have to either get rid of the asm or start using yasm.

At some point in the near future I'm going to work on getting a mingw build system going and all that that entails.

**Comment by gonetz** [comment]
There is no problem to build GlideN64 64bit for Mupen64Plus. Linux and MacOsX builds are 64bit. Zilmar build will require 64bit QT build. This is the only problem, and it is pure technical.

**Comment by vgturtle127** [comment]
@gonetz Has this been worked on at all? Just curious. Also, what libraries are you using that need to be recompiled?

**Comment by gonetz** [comment]
@vgturtle127 I do nothing in that direction. Zilmar specs build of GLideN64 requires zlib, libpng, freetype, and QT libs.

**Comment by vgturtle127** [comment]
@gonetz OK, I was just curious.

**Comment by oddMLan** [comment]
Will be fixed when #2122 gets merged

**Comment by gonetz** [comment]
I've merged #2122. Tim, thanks!
