### ISSUE TITLE
High Resolution Texture support for Android version

### ISSUE THREAD

**Issue by fivefeet8** [gonetz/GLideN64#538]
I've been testing the version of Mupen64plus AE with the integrated Gliden64 alpha plugin and it seems texture loading is not working.  I'm guessing it isn't implemented yet on the Android version in it's current alpha state.  I'm testing the build on my Shield Tablet, HTC One M8(S801), and Note 3(S800).   All are running with Android Lollipop 5.01.  

Once it is implemented, where does the texture files go?  Currently the Mupen64plus AE dev builds look in the "storage/emulated/0/mupen64plusae-v3-alpha-gliden64/CoreConfig/UserData/mupen64plus/hires_texture/" directory for the Rice video plugin.  I've also edited the emulation.cfg file to point to the same folder to load the textures for Gliden64.  

Sorry if this is more of a question than a bug report, but I do intend to report bugs as I notice them on those devices.

**Comment by gonetz** [comment]
Please wait with Android bug reports until public release. Development version has many problems. I know about them. Such reports just obscure real problems from my attention.
