### ISSUE TITLE
Pokemon Stadium 2: Missing/corrupt images.

### ISSUE THREAD

**Issue by WizLizard** [gonetz/GLideN64#542]
Project64 2.2 Stable with GLideN64 PR 1.1 default settings. Some images won't display at all and some will display on the first viewing but leaving and returning to the images causes corruption. This is in the the Pokemon Academy's library. Watch video. https://www.youtube.com/watch?v=i4YbX_oJ6vw

Save state, for some reason loading the save state causes the VI to be at 54? just exit the academy and return to fix it. https://drive.google.com/file/d/0By-W8sjqLxiyZUdjRW43Z25fS1E/view?usp=sharing

**Comment by WizLizard** [comment]
Likely the same issue due to frame buffer #416

**Comment by purplemarshmallow** [comment]
Yes same issue
it's a problem with validity checking
the images in the library work with checksum option (older plugin version)
but checksum breaks everything else

**Comment by Predator82Germany** [comment]
I don´t know enough of these frame buffer things & may now comes a silly question but:
Is it possible to make a fb-option for every of them?

**Comment by Mushman** [comment]
Yes, but it's far better to find one method which accurately accounts for all possibilities just like the original hardware. @gonetz hasn't been able to solve that problem yet, unfortunately.

**Comment by purplemarshmallow** [comment]
the bigger problem is that no validity check method works perfectly for Mario Tennis and Pokemon Stadium 2

**Comment by WizLizard** [comment]
@purplemarshmallow Should propably close then?

**Comment by purplemarshmallow** [comment]
i've added information to #416 so I think it can be closed
