### ISSUE TITLE
Bomberman 64: the Second Attack Black Background

### ISSUE THREAD

**Issue by waltzz92** [gonetz/GLideN64#544]
On the Game Planet Starlight stage, a large black background is rendered instead of the regular one. This occurs in both GLideN64 HLE and LLE. Using Project64 2.2.0.3 and GLideN64 default settings.

GLideN64 Public Release 1.1:
![bomberman 64 second attack black background](https://cloud.githubusercontent.com/assets/12215466/7727355/134ab5d6-febd-11e4-8a59-6e05e2d5e247.jpg)

This is how the background looks on Jabo’s Direct3D8 plugin:
![bomberman 64 second attack correct background](https://cloud.githubusercontent.com/assets/12215466/7727367/25cf9550-febd-11e4-9970-790070eff779.jpg)

Here is the Savestate:
https://drive.google.com/file/d/0B98aajamsOCdSVJsOTBWa3BVV2s/view?usp=sharing

**Comment by gonetz** [comment]
Confirmed. Thanks for the save.

**Comment by Cetacea3691** [comment]
More places seem to be affected by this.

PJ64 2.2 savestate:https://drive.google.com/file/d/0Bygxj1zIGEscaUpMUmFUSjlPLW8/view?usp=sharing
Wrong
![gliden64_bomberman64u2_001](https://cloud.githubusercontent.com/assets/13789606/9426949/6a69bb66-4961-11e5-8fa5-f86e27f01161.png)
Correct (angrylion's RDP)
![nbve0001](https://cloud.githubusercontent.com/assets/13789606/9426951/757ec096-4961-11e5-9b04-f9e5a12244c9.png)

I think this belongs here too.
PJ64 2.2 savestate:https://drive.google.com/file/d/0Bygxj1zIGEscMl9YLXY3RTFvUEk/view?usp=sharing
Wrong
![gliden64_bomberman64u2_002](https://cloud.githubusercontent.com/assets/13789606/9426953/80ad1346-4961-11e5-9559-087f1896908d.png)
Correct (angrylion's RDP)
![nbve0002](https://cloud.githubusercontent.com/assets/13789606/9426955/896c3d86-4961-11e5-9404-b4364d0de747.png)

**Comment by purplemarshmallow** [comment]
Most likely blending issue like  #658

**Comment by gonetz** [comment]
Fixed now
