### ISSUE TITLE
copy depth to RDRAM breaks Pokemon Snap

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#547]
all these glitches are gone if I disable copy depth to RDRAM 
copy depth to RDRAM also causes Problems with Pokemon Stadium 2 and it's from the same developer so it's likely related
![gliden64_pokemon_snap_002](https://cloud.githubusercontent.com/assets/7283660/7745230/d6dc9162-ffa9-11e4-81e2-25ac0ddefff7.jpg)
![gliden64_pokemon_snap_001](https://cloud.githubusercontent.com/assets/7283660/7745231/d85e44e0-ffa9-11e4-8ca1-70ee4232a38c.jpg)
![gliden64_pokemon_snap_000](https://cloud.githubusercontent.com/assets/7283660/7745232/d997c8fe-ffa9-11e4-91df-5dbf7d7be0e1.jpg)

**Comment by purplemarshmallow** [comment]
The dolphin team did a lot of research on how this game works
See https://de.dolphin-emu.org/blog/2015/06/01/dolphin-progress-report-may-2015/
looks like accurate depth buffer emulation is needed
GLideN64 has similar problems, Professor Oak can't see the Pokémon in the pictures
maybe this can fix #380 ?

**Comment by purplemarshmallow** [comment]
This should be most important:
"The photo has separate depth copies for the Pokemon and terrain and assembles them later for the final picture"

**Comment by AmbientMalice** [comment]
My understanding is the game uses colour buffer for detecting whether a Pokemon is in the shot to turn the camera dot red. The "red dot detection" thing has to be emulated correctly otherwise the game's controls remain frozen during the tutorial. My impression is that depth buffer is a separate, but related issue.

But honestly, I'm not 100% clear on how the N64 handles its buffers.

**Comment by gonetz** [comment]
Please check again with depth buffer copy set to software render.

**Comment by purplemarshmallow** [comment]
no problem with software render

**Comment by gonetz** [comment]
> no problem with software render
Let's consider this as fixed
