### ISSUE TITLE
detectCFB causes crash in Pokemon Stadium 2

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#548]
detectCFB is needed for the GB tower see #529
at the title screen this setting causes a crash
only zilmar spec version seems to be affected

**Comment by purplemarshmallow** [comment]
crash at FrameBuffer.cpp line 1350
```col = src[idx];```

**Comment by gonetz** [comment]
Input address is out of memory.

**Comment by gonetz** [comment]
Fixed in 93f659c

**Comment by purplemarshmallow** [comment]
fixed
