### ISSUE TITLE
WCW Nitro: tv screen (fb effect) is displayed 3 times 1/3 of what should be displayed

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#55]
in game the tv screen is showing 3 times 1/3 of what should be displayed with HWBE

![no intro3](https://cloud.githubusercontent.com/assets/8987490/4696860/cce6baf6-581b-11e4-8810-7bc3f88a6b82.jpg)

With LLE software

![tsssddd](https://cloud.githubusercontent.com/assets/8987490/4696865/d855f7e4-581b-11e4-8180-29be274804fb.jpg)

**Comment by olivieryuyu** [comment]
fb not fixed

**Comment by oddMLan** [comment]
![gliden64_nitro64_001](https://cloud.githubusercontent.com/assets/7278372/15261803/53ab61f4-1913-11e6-8a48-add22d35f35d.png)
![gliden64_nitro64_000](https://cloud.githubusercontent.com/assets/7278372/15261804/53e8feec-1913-11e6-93e4-a7e36879fd8b.png)

Fixed?

**Comment by olivieryuyu** [comment]
fixed
