### ISSUE TITLE
Adjusting the aspect ratio in a linux build?

### ISSUE THREAD

**Issue by 7oxicshadow** [gonetz/GLideN64#551]
From what I can see there is support in the windows version to adjust advanced settings, one of which is aspect ratio.

Is there anyway to adjust these on Linux currently? If I enable widescreen in Banjo Tooie it just squashes the image to maintain 4:3 and keeps the black bars.

**Comment by 7oxicshadow** [comment]
Managed to dig around the source and find the section names and variables.

If anyone else is interested you use the following:

--set Video-GLideN64[EnableFBEmulation]=1 --set Video-GLideN64[AspectRatio]=0

The following list appears to be the configurable options

"configVersion"
"MultiSampling"
"AspectRatio"
"bilinearMode"
"MaxAnisotropy"
"CacheSize"
"EnableFog"
"EnableNoise"
"EnableLOD"
"EnableHWLighting"
"EnableFBEmulation"
"EnableCopyColorToRDRAM"
"EnableCopyDepthToRDRAM"
"EnableCopyColorFromRDRAM"
"EnableDetectCFB"
"EnableN64DepthCompare"
"ValidityCheckMethod"
"txFilterMode"
"txEnhancementMode"
"txFilterIgnoreBG"
"txCacheSize"
"txHiresEnable"
"txHiresFullAlphaChannel"
"txHresAltCRC"
"txDump"
"txCacheCompression"
"txForce16bpp"
"txSaveCache"
"fontName"
"fontSize"
"fontColor"
"EnableBloom"
"bloomThresholdLevel"
"bloomBlendMode"
"blurAmount"
"blurStrength"

**Comment by 7oxicshadow** [comment]
Just a quick update. If any of the values are boolean types you must use True or False instead of 1 and 0.

--set Video-GLideN64[EnableFBEmulation]=True

**Comment by gonetz** [comment]
It's better to edit mupen64plus.cfg. It should be somewhere in your Home folder.
Open it in text editor and find "AspectRatio" or "[Video-GLideN64]" section. You will see comment for this setting:
# Screen aspect ratio (0=stretch, 1=force 4:3, 2=force 16:9, 3=adjust)
AspectRatio = 0

Set it to 3 and you should get widescreen working. You may use command line as well, using config file  as reference for available settings.
