### ISSUE TITLE
[Mupen64Plus] Yoshis Story - Black Background and Yoshi Duplicates with LLE

### ISSUE THREAD

**Issue by Papermanzero** [gonetz/GLideN64#553]
Description:
Playing Yoshis Story with the default settings results in a black background and yoshis is duplicates itself.
Means If Yoshi is running the last frames from yoshi are still visible (so you have hundreds of yoshis on screen)

System: Windows 7
Frontend: M64Py 2.2
Graphic Plugin: GLideN64 1.1 
Graphic Plugin Setting: Default (no modification of default settings)
RSP Plugin: CXD4 SSSE3 (Comment Paperman: Only LLE, HLE was copy and paste issue)
Mupen64Plus Version: Build from 2015-05-09 (c7fa0de)
Game: Yoshis Story (PAL)

**Comment by gonetz** [comment]
I can't reproduce it. I started Yoshis Story (PAL) and entered the first level (treasure hunt) with no visible glitches. May be it is problem with your graphics card/drivers?

**Comment by Papermanzero** [comment]
I don't think so. I have the newest Nvidia drivers and modern graphic card.
Please find a screenshot and my settings (in general these should be the default settings).
You can try these settings with cxd4 and the training level (screenshot).

[Video-Gliden64]
# Settings version. Don't touch it.
configVersion = 3
# Enable/Disable MultiSampling (0=off, 2,4,8,16=quality)
MultiSampling = 0
# Screen aspect ratio (0=stretch, 1=force 4:3, 2=force 16:9, 3=adjust)
AspectRatio = 1
# Bilinear filtering mode (0=N64 3point, 1=standard)
bilinearMode = True
# Max level of Anisotropic Filtering, 0 for off
MaxAnisotropy = False
# Size of texture cache in megabytes. Good value is VRAM*3/4
CacheSize = 500
# Enable fog emulation.
EnableFog = True
# Enable color noise emulation.
EnableNoise = False
# Enable LOD emulation.
EnableLOD = True
# Enable hardware per-pixel lighting.
EnableHWLighting = False
# Enable frame and|or depth buffer emulation.
EnableFBEmulation = True
# Enable color buffer copy to RDRAM.
EnableCopyColorToRDRAM = True
# Enable depth buffer copy to RDRAM.
EnableCopyDepthToRDRAM = True
# Enable color buffer copy from RDRAM.
EnableCopyColorFromRDRAM = False
# Detect CPU writes to frame buffer.
EnableDetectCFB = False
# Enable N64 depth compare instead of OpenGL standard one. Experimental.
EnableN64DepthCompare = False
# Method to check validity of auxiliary texture frame buffer (0=write fingerprint to the buffer, 1=fill whole buffer in RDRAM with test value)
ValidityCheckMethod = False
# Texture filter (0=none, 1=Smooth filtering 1, 2=Smooth filtering 2, 3=Smooth filtering 3, 4=Smooth filtering 4, 5=Sharp filtering 1, 6=Sharp filtering 2)
txFilterMode = 0
# Texture Enhancement (0=none, 1=store as is, 2=X2, 3=X2SAI, 4=HQ2X, 5=HQ2XS, 6=LQ2X, 7=LQ2XS, 8=HQ4X, 9=2xBRZ, 10=3xBRZ, 11=4xBRZ, 12=5xBRZ)
txEnhancementMode = 0
# Don't filter background textures.
txFilterIgnoreBG = False
# Size of filtered textures cache in megabytes.
txCacheSize = 100
# Use high-resolution texture packs if available.
txHiresEnable = False
# Allow to use alpha channel of high-res texture fully.
txHiresFullAlphaChannel = False
# Use alternative method of paletted textures CRC calculation.
txHresAltCRC = False
# Enable dump of loaded N64 textures.
txDump = False
# Zip textures cache.
txCacheCompression = True
# Force use 16bit texture formats for HD textures.
txForce16bpp = False
# Save texture cache to hard disk.
txSaveCache = True
# File name of True Type Font for text messages.
fontName = "arial.ttf"
# Font size.
fontSize = 18
# Font color in RGB format.
fontColor = "B5E61D"
# Enable bloom filter
EnableBloom = 0
# Brightness threshold level for bloom. Values [2, 6]
bloomThresholdLevel = 4
# Bloom blend mode (0=Strong, 1=Mild, 2=Light)
bloomBlendMode = 0
# Blur radius. Values [2, 10]
blurAmount = 10
# Blur strength. Values [10, 100]
blurStrength = 20

![yoshi_story](https://cloud.githubusercontent.com/assets/10263536/7794864/4f3eb568-02cf-11e5-9700-2b4e1a1ca263.jpg)

**Comment by purplemarshmallow** [comment]
I can reproduce it in LLE but not in HLE

**Comment by Papermanzero** [comment]
Yeah, you are right. Was a copy and paste issue :)
It's only LLE.

**Comment by olivieryuyu** [comment]
is that still valid?

**Comment by olivieryuyu** [comment]
![GLideN64_YOSHI_STORY_000](https://user-images.githubusercontent.com/8987490/78967103-c8aa2900-7b01-11ea-821c-b168fce58990.png)

fixed
