### ISSUE TITLE
[Mupen64Plus] Pokemon Snap - LLE - empty Photos

### ISSUE THREAD

**Issue by Papermanzero** [gonetz/GLideN64#554]
Description:
In LLE (CXD4) the photos of the pokemon are empty (no pokemon detected).
![snap-lle](https://cloud.githubusercontent.com/assets/10263536/7795502/16084a46-02d6-11e5-9fa0-29d5a7c55a8a.jpg)

Also if the settings will be modified (e.g. EnableDetectCFB) the results are the same.

System: Windows 7
Frontend: M64Py 2.2
Graphic Plugin: GLideN64 1.1
Graphic Plugin Setting: Default (also tried with modification of default settings)
RSP Plugin: CXD4 SSSE3 and RSP-HLE
Mupen64Plus Version: Build from 2015-05-09 (c7fa0de)
Game: Pokemon Snap (PAL-G)

**Comment by purplemarshmallow** [comment]
copy color to rdram is needed but it does not work in LLE
