### ISSUE TITLE
CopyFromRDRAM loses colors

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#555]
Sometimes colors are missing. The screecshot is from Namco Museum 64 but it can happen in every game that uses cfb. It seems to happen randomly. Switching window/fullscreen can make colors disappear but it can also bring colors back.
edit: happens with Project64 and mupen64plus
![gliden64_namcomuseum64_000](https://cloud.githubusercontent.com/assets/7283660/7796061/b7ac5aa4-02db-11e5-9442-a6e044982ce8.jpg)

**Comment by purplemarshmallow** [comment]
There's a bug in CopyFromRDRAM, everything that relies on CopyFromRDRAM can have missing colors (pills in Dr. Mario, scoreboards in Mario Tennis, ...)

**Comment by gonetz** [comment]
Is it still actual? I can't reproduce it.

**Comment by purplemarshmallow** [comment]
Yes it happens with this week's master build. But it's hard to reproduce because it's completely random and hard to debug :/

**Comment by weinerschnitzel** [comment]
I cant reproduce the colors disappearing in the pills in Dr. Mario using the current build and Project64 2.3. However there are some backgrounds that do not persist when switching fullscreen and back. Is this the behavior of the same bug?

**Comment by gonetz** [comment]
> However there are some backgrounds that do not persist when switching fullscreen and back. Is this the behavior of the same bug?

No. Backgrounds in Dr. Mario stored in frame buffer objects, which destroyed on window mode change.
This bug is about rare case, when format of image in RDRAM wrongly detected as monochrome one.

**Comment by fzurita** [comment]
I wonder if this is fixed now.

**Comment by purplemarshmallow** [comment]
fixed
