### ISSUE TITLE
compiler optimizations cause flickering

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#559]
namco museum 64 is flickering in mupen64plus. flickering gets worse if the window isn't active. no flickering if the plugin was built without optimizations

**Comment by LegendOfDragoon** [comment]
is this still an issue?

**Comment by purplemarshmallow** [comment]
Yes but it shouldn't be hard to solve this one
A compiler optimizations needs to be disabled

**Comment by LegendOfDragoon** [comment]
I think it would be better to narrow down the function that is broken with inline. This is a fine temporary solution though.

**Comment by gonetz** [comment]
>I think it would be better to narrow down the function that is broken with inline.

Agreed. Discrepancy in behavior of debug and release builds is a sign of a problem with code. Better to find this problem, not to mask it with compiler options.

**Comment by purplemarshmallow** [comment]
How is is possible to find out which function is incompatible with InlineFunctionExpansion?

**Comment by LegendOfDragoon** [comment]
>How is is possible to find out which function is incompatible with InlineFunctionExpansion?

I've never tried this before, but I believe you can configure the compiler settings for each .cpp file. You can highlight multiple files at once by holding shift and clicking, or if you want to highlight multiple files individually, you can hold ctrl and click each file. Hopefully this will work. If not, you'd have to do tedious testing with things like __declspec(noinline) .

**Comment by olivieryuyu** [comment]
can it be tested again? the refactoring should have changed something here

**Comment by purplemarshmallow** [comment]
I can't reproduce it anymore
