### ISSUE TITLE
New Laptop with multiple videocards

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#561]
Please bare with me as this may be a Windows 8 or possible PJ64 issue.

I have a new laptop that has 2 video cards installed in it. Intel HD and Geforce 740m. The laptop uses power management to decide when you use Intel or Geforce as a primary. 

When I try and load a ROM the GFX are not correct. I think this might be because the game is trying to load the Intel drivers.

Has anyone else had issues on this type of multi carded setup?
![capture](https://cloud.githubusercontent.com/assets/9299743/7847683/aff3940c-0471-11e5-9c48-f0025a17fcd0.PNG)
http://www.geforce.com/hardware/notebook-gpus/geforce-gt-740m/specifications

**Comment by purplemarshmallow** [comment]
I have NVIDIA Optimus
I had to right click the application and execute with Nvidia or create a profile in the driver settings
but then I upgraded my drivers and now the Nvidia gpu is used automatically

**Comment by theboy181** [comment]
I have updated the drivers for the Nvidia and have tried to forcing Nvidia too. No luck. 

Glide64 and othe plugs are fine.

**Comment by theboy181** [comment]
Intel hd4600 supports OpenGL 4.0 .. I don't get what is going on here.

**Comment by WizLizard** [comment]
It should work when adding it to the nvidia control panel and setting project64 to use nvidia gpu as default. I have optimus as well, try going to Gliden64's settings to engage the plugin before booting a game. I get the same graphical mess when i use the intel hd graphics as well. Turning off aa and anisotropic filtering helps.

**Comment by theboy181** [comment]
I just updated the intel hd driver and It seems like it might be working correctly. However now I am not able to save any changes in the 3d management portion in the nvidia control panel. Access denied when hitting apply. 

Any ideas?

**Comment by WizLizard** [comment]
This is why i'm getting rid of my laptop. Optimus is a mess i've had so many issues from day 1. Mostly with opengl programs, plugins etc. Especially the micro stuttering. You could try clean installing the drivers.

**Comment by theboy181** [comment]
Micro stuttering?

**Comment by WizLizard** [comment]
Every emulator or game i have used on this laptop that uses an opengl backend, dolphin, ppsspp, snes9x, project64, epsxe all get a random stutter every so many frames like a frame is skipped resulting in a slight jutter. If i use a d3d plugin within any of these emulators no issues. It's a known problem and the dolphin devs are aware of it but there is nothing they can do because it's on nvidia's end. Unfortunately i wasn't aware of these issues before i bought the laptop. So i'm selling and building a desktop. Optimus is buggy.

**Comment by WizLizard** [comment]
A lot of the laptops that use optimus have a way of indicating when the nvidia gpu or intel gpu are being used. For me the power light stays white when using intel and turns orange when using nvidia gpu. You can also turn on the gpu activiy icon for the taskbar.

**Comment by WizLizard** [comment]
http://en.kioskea.net/faq/41241-nvidia-display-gpu-activity-icon-in-the-notification-area

**Comment by theboy181** [comment]
My laptop has a LED that turns from blue to red to let you know.. 
the clean install fixed the issue btw.. thanks!!

**Comment by WizLizard** [comment]
Np, believe me i know how frustrating optimus can be lol. Curious did you clean install both intel and nvidia drivers?

**Comment by theboy181** [comment]
just the nvidia drivers..

**Comment by WizLizard** [comment]
Ok thanks.

**Comment by theboy181** [comment]
I forgot to mention that my intel HD 4600 did work with Gliden64 but you have to turn off hardware lighting..

**Comment by WizLizard** [comment]
Yes thats how i was able to get it working.

**Comment by theboy181** [comment]
You can actually start out in LLE mode then change to HLE in  the RSP and that will work too.. however the colors get messed up.. Im not sure but LLE mode might not support HW lighting?

**Comment by WizLizard** [comment]
I'm not sure on that either?

**Comment by theboy181** [comment]
Hve you tested it?

**Comment by WizLizard** [comment]
I have not but i could later tonight after work.
