### ISSUE TITLE
Bio F.R.E.A.K.S. intro transitions

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#562]
There are CPU based effects, the plugin needs to switch to CPU rendering mode, detectCFB is needed. The problem is that some effects last for under a secound, the plugin currently switches to CPU rendering mode after 25 frames, that's too slow. The effect is already over. This value needs to be different for every game, it should be possible to set it in the ini file.

Same problem in Lego racers #362 
In this game the value needs to be higher to avoid unsharp image, Glide64 uses a built-in hack. But I think it's better to introduce a new setting in the ini file since every game needs a different value. It's impossible to find one value that works for every game

**Comment by AmbientMalice** [comment]
Reminds me of this - https://github.com/project64/project64/issues/72

It might be time to re-examine better methods for handling CPU framebuffer writes. (Not to mention FB in general, because GLideN64 is hitting some nasty snags with eccentric games.)

**Comment by purplemarshmallow** [comment]
with detectCFB this game will never be perfect, if the value is too low you see the unsharp image ingame, it's only possible to find a compromise. with proper notification from the emlator it should work.

I'm not sure about lego racers anymore. I thought it's needed for the map but the map works without it. Someone must have enabled it for a reason and it's enabled in Glide64 as well but I can't find a point in the game where it's needed

**Comment by purplemarshmallow** [comment]
@gonetz do you think it's possible to implement a better method to detect CPU writes? the plugin could save a copy of the data in the colorbuffer. And later it could compare with this copy and if there's any difference the plugin knows that the CPU wrote something there. Do you think this can work?

**Comment by gonetz** [comment]
It may work if the CPU will write to previously allocated color buffer. It's not necessary the case. But it may be used as additional check, which may trigger faster than my 25 frames barrier.

**Comment by purplemarshmallow** [comment]
fixed
