### ISSUE TITLE
Perfect Dark coronae and sun lens flares not fading out

### ISSUE THREAD

**Issue by Filipianosol** [gonetz/GLideN64#563]
The coronas and sun lens flares don't fade out when covered by the first person gun. The problem doesn't seem to occur with enemies, walls or any objects.

Corona:
<b>GLideN64</b>
![pderrorgliden64](https://cloud.githubusercontent.com/assets/12639838/7855621/6d476f9a-0523-11e5-98fd-eb6c81548202.png)
<b>Real hardware</b>
![pderrorn64](https://cloud.githubusercontent.com/assets/12639838/7855956/ba52b766-0525-11e5-9205-5af300fa476f.png)
<b>Glide64 For PJ64: 2.0.0.5</b>
![pderrorglide64](https://cloud.githubusercontent.com/assets/12639838/7855620/6d2f2138-0523-11e5-91b8-90658b830cb0.png)
Sun:
<b>GLideN64</b>
![pderror2gliden64](https://cloud.githubusercontent.com/assets/12639838/7862295/41923bd2-0555-11e5-929a-45ce7ccc2364.png)
<b>Real hardware</b>
![pderror2n64](https://cloud.githubusercontent.com/assets/12639838/7862306/4a7348d6-0555-11e5-8413-3ffaad8ef797.png)
<b>Glide64 For PJ64: 2.0.0.5</b>
![pderror2glide64](https://cloud.githubusercontent.com/assets/12639838/7862308/50950376-0555-11e5-93b3-5383e0061335.png)

**Comment by gonetz** [comment]
I need savestate to check it.

**Comment by Filipianosol** [comment]
Here's the savestate:
https://drive.google.com/file/d/0Bz3WFRZJ1ZbRaGRIQmpfYlUzWGc/view?usp=sharing

**Comment by gonetz** [comment]
Good news: I found how to fix it.

Bad news: Depth buffer must be read twice for each frame with coronas to make them work right.
This may have noticeable performance impact. My card can handle it without problems, but if you're NVidia user, you may notice slowdown.

Test build:
https://drive.google.com/file/d/0B0YqMPjGo3B2MmpmNm5rTnJmdEU/view?usp=sharing

**Comment by gonetz** [comment]
Any feedback?

**Comment by purplemarshmallow** [comment]
I can't notice a difference in performance
GPU: Geforce GT 525M

**Comment by Predator82Germany** [comment]
Fixed then?

**Comment by Filipianosol** [comment]
Yes, no slowdown on GTX 650, even without Prefer maximum performance.

**Comment by purplemarshmallow** [comment]
I can't run it at fullspeed if framebuffer effects are used (IR-Vision ...) even in performance mode. But this happens with every version of the plugin and there seems to be no noticeable slowdown caused by this change.

**Comment by purplemarshmallow** [comment]
@gonetz #469 is fixed with this test build

**Comment by gonetz** [comment]
I doubt that fix is caused by my latest changes. The bug in PD is fixed by commit 36fbcd5. PD uses very specific way to store data from depth buffer. I have special function for it, texturedRectDepthBufferCopy(), which is activated only for PD and CBFD. My commit changes work of that function. Thus, it is unclear for me how that fix could impact #469. Could you give me savestate for #469?

**Comment by purplemarshmallow** [comment]
https://drive.google.com/open?id=0B7Y6r4SpC_QQWm1jMVAwZ0J5S3c&authuser=0

**Comment by gonetz** [comment]
Thanks for the save. I've built the plugin from commit 4b6df9, which precedes commit 36fbcd5 with the fix. The #469 is fixed with it too. So, it was fixed somewhere in the past.

**Comment by AmbientMalice** [comment]
There's been a regression. Perfect Dark coronas are showing through walls again in GLideN64 1.2
