### ISSUE TITLE
Tile Texture option

### ISSUE THREAD

**Issue by Nes-player4Life** [gonetz/GLideN64#567]
Please re-add the Tile Texture option found in Glide64 finale.
Loading character textures brakes these files. 
GlideN64.
![gliden64_mariokart64_000](https://cloud.githubusercontent.com/assets/10325597/7900246/766917e4-0718-11e5-8eaf-86878a2dc41a.png)
Glide64.
![glide64_mariokart64_11](https://cloud.githubusercontent.com/assets/10325597/7900248/799ebd10-0718-11e5-9d51-457fb1634da8.png)
Unmodified. 
![gliden64_mariokart64_001](https://cloud.githubusercontent.com/assets/10325597/7903088/4c913cda-079f-11e5-9fed-497315de0c76.png)

**Comment by gonetz** [comment]
First, need to find what causes that glitch.
Is it hires texture pack or texture enhancement?

**Comment by Nes-player4Life** [comment]
Hires Texture pack. I don't use enhancement options. 
Also the textures are upscaled.8x.

I do have to say that I enjoy the slender look of the peach found in pix 1 but the error is not pleasant.     

Posted unmodified pix for reference.
Textures maybe found at:
 http://www.emulation64.com/files/getdownload/1364/ (28.7MB)
Save State
http://textures.emulation64.com/data/uploads/mario-kart-64-u.pj.zip

**Comment by gonetz** [comment]
I loaded the pack. It works without problems for me. Be sure that "Use alpha channel fully" option is on before loading the pack for the first time.
![gliden64_mariokart64_000](https://cloud.githubusercontent.com/assets/8983092/8232746/ce16157a-15f3-11e5-9eac-45f6b5bd8876.png)
![gliden64_mariokart64_001](https://cloud.githubusercontent.com/assets/8983092/8232748/d2eeabf2-15f3-11e5-86f6-8f4c3c1b0400.png)
![gliden64_mariokart64_004](https://cloud.githubusercontent.com/assets/8983092/8232751/d6c4b078-15f3-11e5-8d1b-7838cb9a1e7b.png)

**Comment by Nes-player4Life** [comment]
"Use alpha channel fully"
I should have tried that before posting.
Thanks again @gonetz
