### ISSUE TITLE
Paper Mario - Darkness effect wrongly emulated

### ISSUE THREAD

**Issue by standard-two-simplex** [gonetz/GLideN64#570]
The darkness effect in Paper Mario is wrongly shown in GlideN64.

GLIDEN64
![gliden64_paper_mario_002](https://cloud.githubusercontent.com/assets/12202580/8023626/1b8d6a3a-0d14-11e5-8110-b3797fdada22.png)
![gliden64_paper_mario_001](https://cloud.githubusercontent.com/assets/12202580/8023627/1ef2d07a-0d14-11e5-82ce-46aab4280522.png)

ANGRYLION'S RDP
![nmqe0001](https://cloud.githubusercontent.com/assets/12202580/8023629/2c8a6338-0d14-11e5-8755-bd7d3ab5339d.png)
![nmqe0002](https://cloud.githubusercontent.com/assets/12202580/8023632/321db8d6-0d14-11e5-8a81-8fd801ef717e.png)

SAVESTATE
http://s000.tinyupload.com/?file_id=07493448169940428025

**Comment by Nes-player4Life** [comment]
Confirmed.

**Comment by theboy181** [comment]
Did you guys try LLE?

**Comment by standard-two-simplex** [comment]
No difference.

**Comment by olivieryuyu** [comment]
framebuffer effect i guess

**Comment by purplemarshmallow** [comment]
I don't think so
Glide64 works even with framebuffer emulation disabled

**Comment by gonetz** [comment]
It is frame+depth buffer effect. Very tricky one. I have hacked it in Glide64.

**Comment by paradadf** [comment]
I´m not sure if this is would be the same issue, but a little further in the game when you enter the whale you can´t see anything.

![darkening_effect](https://cloud.githubusercontent.com/assets/15956550/14422475/44a0567e-ffd7-11e5-974a-06d45ac84471.png)

But with glide64mk2 the effect is correctly emulated:
![darkening_effect_glide64mk2](https://cloud.githubusercontent.com/assets/15956550/14422492/60d15b86-ffd7-11e5-88ff-904092ca2841.png)
![darkening_effect_glide64mk2_second](https://cloud.githubusercontent.com/assets/15956550/14422494/6451aa5e-ffd7-11e5-94a6-ede387b515d7.png)

[Save state](http://s000.tinyupload.com/?file_id=04747132814439040745)

**Comment by gonetz** [comment]
Yes, the same issue

**Comment by gonetz** [comment]
Fixed.

**Comment by standard-two-simplex** [comment]
Forgive me the delay, but I haven't been around for a while.
Confirmed.

**Comment by gonetz** [comment]
Ok
