### ISSUE TITLE
Zelda OOT wrong portals

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#571]
Savestate:
https://drive.google.com/file/d/0B7Y6r4SpC_QQQm1IejBsUkdHOGM/view?usp=sharing
glN64 looks correct
glN64:
![screen00](https://cloud.githubusercontent.com/assets/7283660/8046123/aa00bcd4-0e38-11e5-913a-4f78a14814a5.jpg)
GLideN64:
![gliden64_the_legend_of_zelda_000](https://cloud.githubusercontent.com/assets/7283660/8046125/b3333d0e-0e38-11e5-83b0-981270a07355.jpg)
angrylion:
![czle0000](https://cloud.githubusercontent.com/assets/7283660/8046135/c100931e-0e38-11e5-8d5a-9478c2b53c24.jpg)

**Comment by gonetz** [comment]
glN64 uses hack for that texture. That hack breaks textures in other games, so I removed it.
Proper fix requires quite serious changes in the code.

**Comment by purplemarshmallow** [comment]
fixed
