### ISSUE TITLE
Mario tennis texture mapping messed up

### ISSUE THREAD

**Issue by glass2** [gonetz/GLideN64#584]
![gliden64](https://cloud.githubusercontent.com/assets/12985044/8270707/66857160-17a3-11e5-99d8-80879598d19c.PNG)
![gliden64-1](https://cloud.githubusercontent.com/assets/12985044/8270711/94683e8c-17a3-11e5-8622-ccb15abbdf2b.PNG)
PJ 64 1.6, intel hd 3000, Public release 1.1 w/default settings

**Comment by purplemarshmallow** [comment]
intel hd 3000? it has OpenGL 3.1 i think and you need at least OperGL 3.3

**Comment by olivieryuyu** [comment]
can it be closed?
