### ISSUE TITLE
GLES2 update texture uniforms

### ISSUE THREAD

**Issue by Gillou68310** [gonetz/GLideN64#586]
I made some debugging using PowerVR SDK on windows and something seems to be wrong in the way texture uniforms are updated with GLES2. Here's a screenshot of the issue:

![mario](https://cloud.githubusercontent.com/assets/2852068/8282051/0f98a376-18ee-11e5-9076-750ebd704e2a.png)

If I remove the following check in ```void UniformSet::updateUniforms``` the problem disappear.
```if ((rs == OGLRender::rsTriangle || rs == OGLRender::rsLine) && _pCombiner->usesTexture())```

**Comment by gonetz** [comment]
Fixed. Your hint helped me to find the problem. Thanks!

**Comment by Gillou68310** [comment]
Thanks for the fix I'll update mupen64plus-ae for feedbacks!
