### ISSUE TITLE
Zelda OOT wrong pause menu background (framebuffer issue)

### ISSUE THREAD

**Issue by Gillou68310** [gonetz/GLideN64#589]
Here's a screenshot of the issue:
![sans titre](https://cloud.githubusercontent.com/assets/2852068/8337682/d9a12160-1aac-11e5-84b9-c70c0112ede6.png)

Please note that it's not happening every time, it sometimes has the correct behaviour.

There's a similar issue on GLES2 except that the background is white:
![oot3](https://cloud.githubusercontent.com/assets/2852068/8337491/c64a6b04-1aab-11e5-908a-3805a194aba5.png)

**Comment by purplemarshmallow** [comment]
mupen64plus uses a subscreen delay fix cheat by default for Zelda OOT
this cheat is incompatible with GLideN64 and breaks the framebuffer effect

GLideN64 has a built-in hack to fix the subscreen delay so the cheat is not needed
but the hack only works if copy color to rdram is enabled

**Comment by Gillou68310** [comment]
Yep comfirmed thanks for the info @purplemarshmallow ;-)
