### ISSUE TITLE
Automobili Lamborghini: missing "corona" in game with fb emulation on.

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#59]
Works with Direct64 & Rice.

It is during the first race and it lshould look like this.

![nope](https://cloud.githubusercontent.com/assets/8987490/4760967/408c4b62-5af4-11e4-9152-c74c95e37f2f.jpg)

**Comment by gonetz** [comment]
It seems that the game uses frame buffer content to decide when coronas must be rendered. Thus, "Copy frame buffer to RDRAM" option must be on for correct coronas work. Please check and close.
