### ISSUE TITLE
No build from source windows instructions

### ISSUE THREAD

**Issue by phly95** [gonetz/GLideN64#594]
You have instructions for linux ( https://github.com/gonetz/GLideN64/wiki/Build-From-Source-%28Linux%29 ) but nothing for windows.

**Comment by V1del** [comment]
It's a wiki, these are user submitted, so maybe you can do the first step :)

**Comment by purplemarshmallow** [comment]
I made a pull request to simplify compilation for windows #595 
but I don't know yet if @gonetz agrees with all changes

**Comment by theboy181** [comment]
Static libs included too please

**Comment by purplemarshmallow** [comment]
which libs should be included? Qt?
dolphin emulator has a seperate repo for Qt
https://github.com/dolphin-emu/ext-win-qt

**Comment by gonetz** [comment]
@purplemarshmallow - you know the project well. Could you make the instructions?

**Comment by purplemarshmallow** [comment]
I made a page in the wiki but it's not complete yet

**Comment by gonetz** [comment]
At least we have a basement now. Thanks!

**Comment by theboy181** [comment]
@purplemarshmallow 
I tried your fork and tried to compile.. I cant get any of them to compile.. Here is the results fro release_dll
2>..\..\src\TextDrawer.cpp(15): fatal error C1083: Cannot open include file: 'ft2build.h': No such file or directory
2>..\..\src\windows\ZilmarAPIImpl_windows.cpp(7): fatal error C1083: Cannot open include file: '../Revision.h': No such file or directory
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

**Comment by theboy181** [comment]
link to wiki please

**Comment by purplemarshmallow** [comment]
wiki: https://github.com/gonetz/GLideN64/wiki/Build-From-Source-(Windows)

@theboy181 have you tried this fork? https://github.com/gonetz/GLideN64/tree/3a638bea48c1a49e2e303468e0b16198c48a9250
it builds without modification if you select Release_mupenplus or Debug_mupenplus
if you want to compile the official repo you have to add Revision.h manually and add freetype to your include directories for now

**Comment by theboy181** [comment]
zilmar spec?

**Comment by purplemarshmallow** [comment]
you also have to build GLideNUI for zilmar spes version, there are no instructions yet, it's under "Todo"

**Comment by LegendOfDragoon** [comment]
Has anyone uploaded the GlideNUI lib?

**Comment by purplemarshmallow** [comment]
Gonetz uploaded the release version
https://drive.google.com/file/d/0B0YqMPjGo3B2N2lUcFNveWlTeUU/view?usp=sharing

**Comment by purplemarshmallow** [comment]
I updated the wiki
There are many steps, I hope it can be made easier in the future. Instructions for building GLideNUI are still missing, I don't know how to compile it so I can't write them, but it's possible to compile the plugin with GLideNUI.lib uploaded by Gonetz

**Comment by baptiste0602** [comment]
@Gonetz : could you upload the new revision of GLideNUI.lib, please ?

**Comment by tony971** [comment]
#676 requires instructions for building GlideNUI.lib. Visual Studio 2015 throws a fit if you don't do it yourself.

**Comment by gonetz** [comment]
https://github.com/gonetz/GLideN64/wiki/Build-From-Source-(Windows)
