### ISSUE TITLE
Banjo Kazooie texture bug

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#599]
on the chest the texture is wrong
does not happen with software LLE plugin and Jabo's d3d plugin
Savestate: https://drive.google.com/file/d/0B7Y6r4SpC_QQczRodmxsaXo5X1U/view?usp=sharing
![gliden64_banjo-kazooie_000](https://cloud.githubusercontent.com/assets/7283660/8449342/035a8874-1fd1-11e5-9c90-23269a3c2565.jpg)

**Comment by WizLizard** [comment]
This looks pretty similar to issue #487.

**Comment by purplemarshmallow** [comment]
but the chest also looks incorrect in LLE
In #487 only HLE mode is affected

**Comment by WizLizard** [comment]
Sorry i misread the issue. As soon as i seen this i just thought of that issue. I thought you meant doesn't happen with GlideN64 in LLE. My bad :/

**Comment by purplemarshmallow** [comment]
my description was a bit misleading, I edited it to make it more clear

**Comment by WizLizard** [comment]
Could also be that it's 7am where i live and i haven't been to sleep yet :)

**Comment by purplemarshmallow** [comment]
fixed
