### ISSUE TITLE
wrong viewport in some games

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#6]
mortal kombat subzero
pachinko nichi 365
fighting force (though currently the game is broken)
Eikou no Saint Andrews

**Comment by olivieryuyu** [comment]
would be nice to get this fixed without hack

really weird that nearly all plugin stumble on this issue at first

**Comment by oddMLan** [comment]
![gliden64_fighting_force_000](https://cloud.githubusercontent.com/assets/7278372/15261115/72835144-190f-11e6-8e62-fa06c1231b6c.png)
![gliden64_mk_mythologies_000](https://cloud.githubusercontent.com/assets/7278372/15261114/728240f6-190f-11e6-83cc-ff329c9a46a5.png)

Fighting force and Mortal Kombat Mythologies are the only two broken right now.

**Comment by rcaridade145** [comment]
The fix for #1426 corrects this one?

**Comment by AmbientMalice** [comment]
Fighting Force is still upside down.

**Comment by gonetz** [comment]
Fixed

**Comment by oddMLan** [comment]
Why is it considered a hack and not a general solution? The approach seems pretty solid to me, so can't it be considered a general solution?

**Comment by olivieryuyu** [comment]
why the 2 games whihc were fixed with #1426 are fixed again?

**Comment by AmbientMalice** [comment]
@olivieryuyu which two games?

**Comment by gonetz** [comment]
For example, mortal kombat subzero and Eikou no Saint Andrews use the same viewport, with nagative scale for Y. Whatever fixes I do in plugin's code, one of these game is upside down in HLE. Probably one of them uses custom ucode, which translates coordinates properly, because both work ok in LLE.

> why the 2 games which were fixed with #1426 are fixed again

#1426 added necessary corrections for negative viewport, which I forgot to add after my VI modification. That just returned the situation to the state it was before the modifications.

Plugin already inverts X coordinate for negative xscale. I made the same for Y to fix upside-down issue. As I said, any such fix corrects one game and breaks other. The hack is used to help games, which became upside down after the fix.

**Comment by olivieryuyu** [comment]
custom ucode? I would get set Seta games then. In which function the viewport is set by ucode?

**Comment by gonetz** [comment]
MoveMem

**Comment by olivieryuyu** [comment]
@gonetz 

Could I get the data you get from movemem for Eikou no Saint Andrews or pachinko nichi 365?

I mean the 4 32 bits words dowloade from memory. I cannot it for those games unfortunately.

**Comment by gonetz** [comment]
Eikou no Saint Andrews

|vpscale:
0x0280fe20
0x01ff0000

vptrans:
0x028001e0
0x01ff0000

same as Mortal Kombat Mythologies Sub-Zero

Yes, 0xFD80FE20 contains negative scales for viewport

**Comment by olivieryuyu** [comment]
Ok so only Fighting Force is a a slightly different. It is weird that Mortal Kombat Mythologies Sub-Zero does not work with the fix of Eikou no Saint Andrews and Pachinko Nichi 365

Now may be I did not spot something, but all those ucodes works exactly as the standard ones. Actually they are standard ones, even the Seta games (it is normal Fast3D ucode, you can even find the string in the memory). I cannot see any difference in their way of working. I checked MOVEMEM and G_VTX, they seems to be the same.

Is there a game with negative viewport that works ok with your current implementation? That would be interesting to compare if so.

The code of fast3d and f3dex (all of them, SuperMario included) is doing something which I don't understand though: it change the vpscale values just before sending to the G_VTX:

vpscale:
0x0280fe20 0x01ff0000

is changed to

0x028001E0 0x01ff0000

as the second and the 4th 16 bits 

0xXXXX**XXXX** 0xXXXX**XXXX** (the bold one) is multiply by  0x0001FFFF.

it would be to "match with opengl" as per the docs.

it is done for negative and positive viewport:

So for Super Mario it is:

0x028001E0 - 01FF0000

becomes

0280FE20 - 01FF0000.

Note that SWRG does not do this change (and then you have -z in the vertex).

Not sure it helps though.

**Comment by olivieryuyu** [comment]
ok i just checked again those 4 game with the last WIP version and all of them are correct !!!!

So is it actually fixed or is there still a hack in your code which we could try to get rid of?

**Comment by gonetz** [comment]
Yes, hack is enabled for Eikou no Saint Andrews (J) and Pachinko Nichi 365
The hack works as this:

```
	if ((config.generalEmulation.hacks & hack_NegativeViewport) != 0 && gSP.viewport.vscale[1] < 0.0f)
		gSP.viewport.vscale[1] = -gSP.viewport.vscale[1];

```

May be if I will multiply Vpscale by 0x0001FFFF for  fast3d and f3dex, it will fix situation as well.

**Comment by olivieryuyu** [comment]
Ok there is a hack. If you multiply by 0x0001FFFF all games so you will get all games with -y in your vertex processing and all games will have the graphics in Y inverted. it will not solve the matter.

I will dig further the Seta games, they are likely the culprit.

**Comment by olivieryuyu** [comment]
Hmm may be I am wrong but if G_VTX calculates the vertex with -y (this is what 0x0001FFFF does, Y is inverted!) in order to match the way it is done in OpengGL by the microcode itself, it does not mean that other areas are affected, like the scissor, the framebuffer etc...

Could it have an impact?

It could explain also this https://github.com/gonetz/GLideN64/issues/161

where "depth buffer" command is missing?

Just a wild guess.

**Comment by gonetz** [comment]
> Could it have an impact?

It should have impact on all games, but we have two exceptions. 

> It could explain also this #161 where "depth buffer" command is missing?

No. Missing depth buffer is not related to wrong viewport. Viewport problems not present in LLE, but Eiko St Andrews has the same depth issue in LLE.

**Comment by olivieryuyu** [comment]
So i digged further in the Seta games: I thought that the debugger was incorrect as the whole ucode was very unfamiliar compared a normal fast3d ucode. However it seems that it is a different ucode than the standard one.

We have now a clue where the issue stands!

**Comment by olivieryuyu** [comment]
Ok so I know where the issue stands, however I am not sure what the right way to solve the matter.

In the "normal" microcode (Fast3D, F3DEX), fact is that the G_VTX command, which first retrieved from memory vertices and then generates VTX structures that will be shipped by the TRI command to the RDP, uses the viewport information obtained with the movemem command. However just before being used, the code inverts the Y value (the multiplication by 0x0001FFFF is doing this). As per the documentation, it is to match the Y of OPENGL. So the microcode itself does this change.

Now Eikou no Saint Andrews and Pachinko nichi 365 does not use the standard Fast3D ucode. It uses Super3D ucode. 

As decribed in the oldest programming manual of the N64:

_SUPER setup code is a lot like TURBO, except it's been modified   to work with the FAST3D interfaces (regular gbi.h). This gives some of the significant speedup benefits of the turbo, and keeps the ease of use from gbi.h._

Now as for SWRG, there is no inversion of the Y before being sent to the G_VTX command.

Question on my side:

should we consider the vertex structure as:

x, 
y,
flag
- y

in SWRG and this Super3D ucode 

or should we consider actually this in the standard Fast3D ucode????

I am not sure what is the right answer compared to the way the N64 really works.

**Comment by gonetz** [comment]
Currently problem with Y in Saint Andrews and Pachinko nichi 365 is solved with a hack. If this problem is ucode specific, it should be solved as other ucode-specific issues. For example, we know that .Rej ucodes do not use near-plane clipping, so we set flag .NoN for them and force disable near-plane clipping. We can have a flag for ucodes, which do not inverse Y.

**Comment by olivieryuyu** [comment]
It is ucode specific. The ucode of those games is totally different than the standard one. It is an optimized version of FAST3D from SGI from I do believe Nintendo started to tweak with some of the code of its own microcode, TURBO3D.

We never noticed this before as the display list commands are the same. Amazing, I feel like the Indiana Jones of the microcode :)

Now the string of Saint Andrews and Pachinko nichi 365 are deceitful as they state they are a standard ucode where actually they are completely different in their internal way of working.

So we need to use the crc of the ucode for having such a flag and tweak a little by GlideN64 code somewhere and finally we can close the ticket without having a hack.

**Comment by gonetz** [comment]
Done. Thanks for the ucode discoveries!

**Comment by olivieryuyu** [comment]
less hack is always nice :)

**Comment by theboy181** [comment]
:)
