### ISSUE TITLE
crash when enabling/disabling fb emulation

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#601]
If framebuffer emulation is disabled or enabled while the emulator is running it will likely cause a freeze/crash. Only zilmar spec version allows to do that

**Comment by thecoreyburton** [comment]
I haven't experienced this yet using the public releases, could it be emulator or hardware specific? if you have a binary you want me to test I'll gladly run it and do so (I have an AMD R9-285 with the latest omega drivers for reference).

**Comment by AmbientMalice** [comment]
Happens for me. Running Nvidia GTX 750Ti.

**Comment by gonetz** [comment]
Fixed: https://github.com/gonetz/GLideN64/commit/cbbd5d17de7fe7d2d69259aec804c9cb4b60ab22

**Comment by purplemarshmallow** [comment]
Thanks, fixed
