### ISSUE TITLE
Jet force gemini square at the bottom

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#603]
If you enable "copy frame buffer to rdram" and "render frame buffer as texture" at the same time a square appears at the bottom left of the screen while you're ingame. Both options are needed to see all effects in this game. Usually the game should be in low-res if both options are enabled (#378 ) but only the square is in low-res. I suspect some important values in the framebuffer code are completely wrong for this game.
![gliden64_jet_force_gemini_000](https://cloud.githubusercontent.com/assets/7283660/8487305/7e1db104-210b-11e5-905b-0b15cdee6d7b.jpg)

**Comment by Mushman** [comment]
I have experienced this issue too. Interestingly enough, sometimes the character's shadow and other effects appear there. It looks like the contents of the frame buffer render there for whatever reason. If you need a save state, ask and I'll make one.

**Comment by purplemarshmallow** [comment]
seems to work with mupen

**Comment by AmbientMalice** [comment]
This has been fixed, as far as I'm aware.

**Comment by purplemarshmallow** [comment]
fixed
