### ISSUE TITLE
Mario tennis various issues and slowdowns

### ISSUE THREAD

**Issue by LuismaSP89** [gonetz/GLideN64#606]
Some graphical bugs with Gliden64 last version (Compilated: 4 July)

Green borders, bouncing ball effect, letter-cropped stripes, names of scoreboard, image of castle cropped in replay, and black/green letters in replay (When you win a match)

There are also many slowdowns during a match. 

(Update: When you play a match, icons doesn´t show in pause menu) (Camera options, controller, etc)

![gliden64_mariotennis_001](https://cloud.githubusercontent.com/assets/12205048/8513517/37ab5512-236f-11e5-9346-59956b676ac8.jpg)
![gliden64_mariotennis_005](https://cloud.githubusercontent.com/assets/12205048/8513518/37ac2ae6-236f-11e5-8a27-47a8ae9801c1.jpg)
![gliden64_mariotennis_006](https://cloud.githubusercontent.com/assets/12205048/8513519/37ae247c-236f-11e5-9681-0a4dfec680ed.jpg)
![gliden64_mariotennis_007](https://cloud.githubusercontent.com/assets/12205048/8513520/37afa810-236f-11e5-8bb3-b45434f67591.jpg)
![gliden64_mariotennis_009](https://cloud.githubusercontent.com/assets/12205048/8513521/37b137ac-236f-11e5-8d07-624978fbf224.jpg)

My PC:
GTX 970
I7 4790K
8 GB DDR3 1600

Tested with 5xbrz filter, smooth filtering 4, antialiasing 8x, anisotropic 16x, 1920x1080 fullscreen resolution.

**Comment by LuismaSP89** [comment]
I know that all previus can be solved with default settings of plugin, (but they are graphical bugs) except the last image bug that persist
![gliden64_mariotennis_001](https://cloud.githubusercontent.com/assets/12205048/8513595/78d6b326-2372-11e5-83fb-8c43820d8abc.jpg)
![gliden64_mariotennis_002](https://cloud.githubusercontent.com/assets/12205048/8513597/78d90392-2372-11e5-903c-1df48d56b42f.jpg)
![gliden64_mariotennis_000](https://cloud.githubusercontent.com/assets/12205048/8513596/78d81d4c-2372-11e5-9f4e-4a38581e6c2a.jpg)


, and this others:
-No chagenger image when you start a match
-Some stripes

**Comment by sergiobenrocha2** [comment]
I can get some of those issues on GLupeN64 too

**Comment by olivieryuyu** [comment]
i have none of those issues.

**Comment by oddMLan** [comment]
The only remaining issues are

-The ball trace (fire) might develop a while outline when the game is ran in non-integer resolutions and with Antialasing enabled
![white outline](https://cloud.githubusercontent.com/assets/7278372/20720423/3f9947c0-b61c-11e6-8650-6473e0e060d5.png)

-The validity check fails every time at the pause screen. This is a regression, before it just failed occasionally.

**Comment by purplemarshmallow** [comment]
>The validity check fails every time at the pause screen. This is a regression, before it just failed occasionally.

Maybe reopen #675 then

**Comment by gonetz** [comment]
Closed. If some issue still not fixed, please open new ticket for it.
