### ISSUE TITLE
Perfect Dark flickering lights

### ISSUE THREAD

**Issue by Filipianosol** [gonetz/GLideN64#609]
Since Public Release 1.2/one of the July 3rd commits the lights started to shimmer uncontrollably like so:
![ezgif-3842154586](https://cloud.githubusercontent.com/assets/12639838/8552781/8a2d6dae-24df-11e5-84e9-d28555e85b3e.gif)
Compared to:
![ezgif-2885995329](https://cloud.githubusercontent.com/assets/12639838/8552803/ae23855e-24df-11e5-93e6-1759d214c3dc.gif)
Before it used to be negligible since the shimmer was rare and only showed upon certain angles/lights like the blue light in the beginning:
![ezgif-1638080750](https://cloud.githubusercontent.com/assets/12639838/8554147/4fda79ea-24e8-11e5-98ac-54107deb3cf1.gif)
Compared to:
![ezgif-109060030](https://cloud.githubusercontent.com/assets/12639838/8553869/a383b91e-24e6-11e5-85b4-7244b6938308.gif)
Messing with frame buffer settings didn't seem to help.
Save state: https://drive.google.com/file/d/0Bz3WFRZJ1ZbRNUtyMzdqcVh3OUU/view?usp=sharing

**Comment by baptiste0602** [comment]
I confirm

**Comment by gonetz** [comment]
Fixed
