### ISSUE TITLE
High Rez Textures Not Working Gliden64 1.2

### ISSUE THREAD

**Issue by SwinglesMan** [gonetz/GLideN64#611]
Texture packs aren't working anymore in GlideN64 1.2. Tried with the community texture pack for Zelda OoT. They do work in 2.1 though. Using the new versions of  Project64.

Edit: Just tried 1.1 without a cache (fresh cache), and it's not working either @.@

**Comment by jfields687** [comment]
I have the same problem with several Mario Kart 64 packs. The textures work just fine on RiceVideo and Glide64 for PJ64. I did a texture dump on GLideN64 and the file names are different from the ones in the texture packs.

**Comment by Mushman** [comment]
Just tested with both 1.1 and 1.2 using custom textures I made and each worked correctly.

> I did a texture dump on GLideN64 and the file names are different from the ones in the texture packs. Probably something to do with memory addressing?

If GLideN64 is expecting a different filename than the one you have then yes, it won't load.

Keep in mind that GLideN64 requires background textures like the pre-rendered environments in Ocarina of Time to be a single file, as opposed to Glide64. This will explain why they aren't working, but not other regular textures.

**Comment by jfields687** [comment]
Ah, that explains it. Now to find a way to fix the background textures just for this plugin.... that will be painful. There are a lot of them in MK64. Thanks for the response.

**Comment by gonetz** [comment]
MK64 does not use BG command to load backgrounds, so all hd textures for this game must load.

There can be problem with 4bit textures dumped with RiceVideo, because of old bug in RiceVideo plugin. Use "Alternative CRC calculation" option to load such textures.

I just tried Zelda OOT with Djipi's texture pack - works without problems. Texture pack for MK64 also loaded.

**Comment by jfields687** [comment]
Ok, I use Kerb's Fixed MK64 pack. http://www.emulation64.com/files/getdownload/1313/ 
It loads the textures and shows in the debug log that they are successfully loaded, but the title, letters and numbers, and a few other things do not display in-game. Kerb's pack works just fine on RiceVideo and Glide64 plugins. I also tried the alternate CRC calculation with no luck. I dumped the the title textures that are not loading and it uses a completely different CRC. Don't know why those specific textures would use a different CRC. Anyways, thanks for all your hard work Gonetz!

**Comment by SwinglesMan** [comment]
If I already have a cache, then it will load. If I dont, I don't see textures loading anymore. I will update again to see but I just haven't been able to get the textures to load at all. If i use the old p64 1.6 with the same version of the plugin, only a few don't get loaded like you said gonetz.

**Comment by jfields687** [comment]
Did you try the "Alternative CRC calculation" setting SwinglesMan?

**Comment by SwinglesMan** [comment]
Yes, it's not even attempting to load. I've even deleted the cache and tried again, it just goes str8 to game. Remove texture cache and see if it still works then. I'm using the latest dev build of pj64 and gliden64. I've tried putting textures in the textures folder and in the gfx hires_texture folder and nothing is happening.
Is gliden64 paths working correctly or something? I don't know, all I know is I haven't been able to use textures for a while.

**Comment by jfields687** [comment]
Ah ok, don't use the dev build for GLideN64, use the public release. For some reason the dev builds screw up the whole texture pack function and does not work at all and won't show the text that it is even loading it. The public release does not do this. GLideN64 generates a glidenhq.dbg file in the same place as your PJ64 executable that you can open in notepad or something to figure out more problems.

**Comment by SwinglesMan** [comment]
The official build of gliden64 1.2 does the same thing. Hence the threads title.

This is what it says inside that file:
[code]
0:	------------------------------------------------------------------
0:	 GLideNHQ version 1.00.00.13480
0:	 Copyright (C) 2010  Hiroshi Morii   All Rights Reserved
0:	    email   : koolsmoky(at)users.sourceforge.net
0:	    website : http://www.3dfxzone.it/koolsmoky
0:	
0:	 GLideN64 GitHub : https://github.com/gonetz/GLideN64
0:	------------------------------------------------------------------
80:	Number of processors : 8
80:	Number of processors : 8
80:	gzfp:0 file:THE LEGEND OF ZELDA_MEMORYCACHE.htc
80:	Number of processors : 8
80:	gzfp:89685e8 file:THE LEGEND OF ZELDA_HIRESTEXTURES.htc
80:	[    1] added!! crc:00000000 D56C70D5 128 x 64 gfmt:80e5 total:0.00mb
80:	Error: cannot get size. unsupported gfmt:0
80:	hirestex: r_crc64:00000000 840EAC57, g64crc:00000000 3C6F20A0
80:	no cache hits.
80:	hirestex: r_crc64:00000000 2FC96317, g64crc:00000000 4F8AB850
80:	no cache hits.
80:	hirestex: r_crc64:00000000 3FC98347, g64crc:00000000 27B194C1
80:	no cache hits.
80:	hirestex: r_crc64:00000000 49B8CADB, g64crc:00000000 D3F9EEE4
80:	no cache hits.
80:	hirestex: r_crc64:00000000 FE4702FD, g64crc:00000000 AA8BE7B9
80:	no cache hits.
80:	hirestex: r_crc64:00000000 6B7CD504, g64crc:00000000 1A610221
80:	no cache hits.
80:	hirestex: r_crc64:00000000 5BC839FB, g64crc:00000000 3DA9BEB9
80:	no cache hits.
80:	hirestex: r_crc64:00000000 829042C1, g64crc:00000000 ABD14E43
80:	no cache hits.
80:	hirestex: r_crc64:00000000 D85BD55B, g64crc:00000000 ED5AC559
80:	no cache hits.
80:	hirestex: r_crc64:00000000 9C4A0577, g64crc:00000000 C2F53259
80:	no cache hits.
80:	hirestex: r_crc64:00000000 478D6444, g64crc:00000000 04D51726
80:	no cache hits.
80:	hirestex: r_crc64:00000000 81A31057, g64crc:00000000 7B758E55
80:	no cache hits.
80:	hirestex: r_crc64:00000000 92C1F51C, g64crc:00000000 C3C1F91E
80:	no cache hits.
80:	hirestex: r_crc64:00000000 03B66847, g64crc:00000000 0971DD34
80:	no cache hits.
80:	hirestex: r_crc64:00000000 31421734, g64crc:00000000 E92BBD3F
80:	no cache hits.
80:	hirestex: r_crc64:00000000 C0600EEA, g64crc:00000000 B38BA72A
80:	no cache hits.
80:	hirestex: r_crc64:00000000 840EAC57, g64crc:00000000 3C6F20A0
80:	no cache hits.
80:	hirestex: r_crc64:00000000 2FC96317, g64crc:00000000 4F8AB850
80:	no cache hits.
80:	hirestex: r_crc64:00000000 3FC98347, g64crc:00000000 27B194C1
80:	no cache hits.
80:	hirestex: r_crc64:00000000 49B8CADB, g64crc:00000000 D3F9EEE4
80:	no cache hits.
80:	hirestex: r_crc64:00000000 FE4702FD, g64crc:00000000 AA8BE7B9
80:	no cache hits.
80:	hirestex: r_crc64:00000000 6B7CD504, g64crc:00000000 1A610221
80:	no cache hits.
80:	hirestex: r_crc64:00000000 5BC839FB, g64crc:00000000 3DA9BEB9
80:	no cache hits.
80:	hirestex: r_crc64:00000000 829042C1, g64crc:00000000 ABD14E43
80:	no cache hits.
80:	hirestex: r_crc64:00000000 D85BD55B, g64crc:00000000 ED5AC559
80:	no cache hits.
80:	hirestex: r_crc64:00000000 9C4A0577, g64crc:00000000 C2F53259
80:	no cache hits.
80:	hirestex: r_crc64:00000000 478D6444, g64crc:00000000 04D51726
80:	no cache hits.
80:	hirestex: r_crc64:00000000 81A31057, g64crc:00000000 7B758E55
80:	no cache hits.
80:	hirestex: r_crc64:00000000 92C1F51C, g64crc:00000000 C3C1F91E
80:	no cache hits.
80:	hirestex: r_crc64:00000000 03B66847, g64crc:00000000 0971DD34
80:	no cache hits.
80:	hirestex: r_crc64:00000000 31421734, g64crc:00000000 E92BBD3F
80:	no cache hits.
80:	hirestex: r_crc64:00000000 C0600EEA, g64crc:00000000 B38BA72A
80:	no cache hits.
80:	hirestex: r_crc64:ACCB0CDB D5982DCA, g64crc:00000000 EF12A2C2
80:	no cache hits.
80:	hirestex: r_crc64:27556FD6 05473B44, g64crc:00000000 10E80465
80:	no cache hits.
80:	hirestex: r_crc64:6499CA45 4B515931, g64crc:00000000 FD5DCA0E
80:	no cache hits.
80:	hirestex: r_crc64:373D4A8B 0207E4DB, g64crc:00000000 2A1F1F7B
80:	no cache hits.
80:	hirestex: r_crc64:AB1A780A 850C8172, g64crc:00000000 2B0979C9
80:	no cache hits.
80:	hirestex: r_crc64:1485A261 F2DA4833, g64crc:00000000 D4755EAE
80:	no cache hits.
80:	hirestex: r_crc64:346DE5EC E2646F80, g64crc:00000000 5C98600D
80:	no cache hits.
80:	hirestex: r_crc64:00000000 E78D134A, g64crc:00000000 38C344D3
80:	no cache hits.
80:	hirestex: r_crc64:00000000 92F79B18, g64crc:00000000 8159CDD2
80:	no cache hits.
80:	hirestex: r_crc64:00000000 D0540287, g64crc:00000000 D2411F79
80:	no cache hits.
80:	hirestex: r_crc64:71B36383 D1991C1C, g64crc:00000000 26C20445
80:	no cache hits.
80:	hirestex: r_crc64:00000000 74977A65, g64crc:00000000 9A15D1D2
80:	no cache hits.
80:	hirestex: r_crc64:00000000 0FFA922B, g64crc:00000000 3E758146
80:	no cache hits.
80:	hirestex: r_crc64:00000000 99AADDFA, g64crc:00000000 1FF0B6E8
80:	no cache hits.
80:	hirestex: r_crc64:00000000 8734F77B, g64crc:00000000 DEBF048A
80:	no cache hits.
80:	hirestex: r_crc64:00000000 2E49F00F, g64crc:00000000 74606730
80:	no cache hits.
80:	hirestex: r_crc64:00000000 AF8B1043, g64crc:00000000 C5D10FFC
80:	no cache hits.
80:	hirestex: r_crc64:00000000 3810A294, g64crc:00000000 375DEB09
80:	no cache hits.
80:	hirestex: r_crc64:00000000 4F353B34, g64crc:00000000 A1630197
80:	no cache hits.
80:	hirestex: r_crc64:00000000 D3A9743B, g64crc:00000000 0FF4331A
80:	no cache hits.
80:	hirestex: r_crc64:00000000 5923C5E8, g64crc:00000000 D816217A
80:	no cache hits.
80:	hirestex: r_crc64:00000000 2CEE55E0, g64crc:00000000 0E56AB96
80:	no cache hits.
80:	hirestex: r_crc64:00000000 30241D79, g64crc:00000000 F4971740
80:	no cache hits.
80:	hirestex: r_crc64:00000000 1281CE2F, g64crc:00000000 9E8C57AD
80:	no cache hits.
80:	hirestex: r_crc64:00000000 B572853C, g64crc:00000000 4CA21797
80:	no cache hits.
80:	hirestex: r_crc64:00000000 C391A1C2, g64crc:00000000 90DDC8EA
80:	no cache hits.
80:	hirestex: r_crc64:1E324774 98F0DD7F, g64crc:00000000 7D2DE660
80:	no cache hits.
80:	hirestex: r_crc64:0E127774 FA5B7305, g64crc:00000000 7702929C
80:	no cache hits.
80:	hirestex: r_crc64:BA6C1733 B8F01C00, g64crc:00000000 34BECFB4
80:	no cache hits.
80:	hirestex: r_crc64:2D61901D AAECE502, g64crc:00000000 F1DF79BC
80:	no cache hits.
80:	hirestex: r_crc64:F012F878 1F3A4860, g64crc:00000000 F97F89D6
80:	no cache hits.
80:	hirestex: r_crc64:126E8325 D9C8DF3C, g64crc:00000000 9190D573
80:	no cache hits.
80:	hirestex: r_crc64:126E8325 88E21058, g64crc:00000000 37B6C5E7
80:	no cache hits.
80:	hirestex: r_crc64:ACCB0CDB D5982DCA, g64crc:00000000 3847AC11
80:	no cache hits.
80:	hirestex: r_crc64:B43911D0 98F0DD7F, g64crc:00000000 AA78E8B3
80:	no cache hits.
80:	hirestex: r_crc64:27556FD6 05473B44, g64crc:00000000 C7BD0AB6
80:	no cache hits.
80:	hirestex: r_crc64:77FC4E08 FA5B7305, g64crc:00000000 A0579C4F
80:	no cache hits.
80:	hirestex: r_crc64:6499CA45 4B515931, g64crc:00000000 2A08C4DD
80:	no cache hits.
80:	hirestex: r_crc64:BAF7A8C2 B8F01C00, g64crc:00000000 E3EBC167
80:	no cache hits.
80:	hirestex: r_crc64:373D4A8B 0207E4DB, g64crc:00000000 FD4A11A8
80:	no cache hits.
80:	hirestex: r_crc64:F9AB71F4 AAECE502, g64crc:00000000 268A776F
80:	no cache hits.
80:	hirestex: r_crc64:AB1A780A 850C8172, g64crc:00000000 FC5C771A
80:	no cache hits.
80:	hirestex: r_crc64:0BAB19F1 1F3A4860, g64crc:00000000 2E2A8705
80:	no cache hits.
80:	hirestex: r_crc64:1485A261 F2DA4833, g64crc:00000000 0320507D
80:	no cache hits.
80:	hirestex: r_crc64:3208DA42 D9C8DF3C, g64crc:00000000 46C5DBA0
80:	no cache hits.
80:	hirestex: r_crc64:346DE5EC E2646F80, g64crc:00000000 8BCD6EDE
80:	no cache hits.
80:	hirestex: r_crc64:3208DA42 88E21058, g64crc:00000000 E0E3CB34
80:	no cache hits.
[/code]

**Comment by jfields687** [comment]
Ok, I downloaded it just a bit ago from here http://www.emutalk.net/threads/55307-Zelda-Ocarina-of-time-Community-Retexture-Project-V7

But it's not one big texture pack file like it shows in your debug log, it's around 4000 texture files. It loaded just fine for me. Maybe try downloading it again? I used public release 1.2 with Alternative CRC calculation setting on. The path I used is PJ64/Plugin/GFX/hires_texture - I placed the whole THE LEGEND OF ZELDA folder there.
![lozoot](https://cloud.githubusercontent.com/assets/12734891/8889841/ebd71988-32b8-11e5-8178-af81102d0744.png)
The sky is screwed up, but that is a separate issue
![untitled](https://cloud.githubusercontent.com/assets/12734891/8889864/bdc60a44-32b9-11e5-984c-2facc201c988.png)

**Comment by gonetz** [comment]
>> For some reason the dev builds screw up the whole texture pack function and does not work at all and won't show the text that it is even loading it.

Where do you get the dev builds?

Zilmar build requires static QT libs. The libs must be built from sources and must not include libpng and  freetype. That is -no-freetype -no-libpng options must be set. Otherwise QT libpng conflicts with GLideNHQ one and hires textures don't work. This is the reason why I use bmp format for screenshots, not png.

**Comment by jfields687** [comment]
http://www.emucr.com/

**Comment by gonetz** [comment]
Need to tell them that they need to rebuild QT libs.

**Comment by SwinglesMan** [comment]
Of gliden64 or pj64?

**Comment by gonetz** [comment]
QT libs for GLideN64

**Comment by SwinglesMan** [comment]
Is that the only place to get the dev builds? They aren't gonna fix it, they never do.

**Comment by jfields687** [comment]
You can try emailing them gonetz, might listen to you more. 
emucr@crimsonrain.com

**Comment by theboy181** [comment]
Are you able to have bin files included I. The source too. This would ensure that we would have access too the latest builds as you progress
