### ISSUE TITLE
Texture Pack + Zelda OoT + + Nvidia DSR + Pause = Black Screen

### ISSUE THREAD

**Issue by SwinglesMan** [gonetz/GLideN64#612]
When using a texture pack for Zelda and you try to pause the game with Nvidia DSR set to a higher resolution, the screen turns black. When you get out of the menu, the screen stays black until you put your resolution back to your native rez or lower.

**Comment by gonetz** [comment]
Does it work correct without the texture pack?

**Comment by SwinglesMan** [comment]
Yes, it works correctly without the texture pack.

**Comment by gonetz** [comment]
I don't have Nvidia card, so the only way for me to fix it is to guess and try.
First, I need to know, is GL error happened during pause screen work.
Please try that build:
https://drive.google.com/file/d/0B0YqMPjGo3B2elhEeXJFLWJGYk0/view?usp=sharing
It will throw assert on GL error and write note about it to gliden64.log file. If you have gliden64.log file in your emulator's folder, remove it before run. After return from the black screen check if gliden64.log is created.

**Comment by SwinglesMan** [comment]
It did it at the game's launch. Can't get into game.

**Comment by gonetz** [comment]
What is in the gliden64.log ?

**Comment by Predator82Germany** [comment]
OpenGL Error: invalid value

**Comment by SwinglesMan** [comment]
^Yep, that.

**Comment by SwinglesMan** [comment]
Seems to be fixed in newest screen smoothing 2D version.
