### ISSUE TITLE
WWF No Mercy Graphic Issue

### ISSUE THREAD

**Issue by Breadwinka** [gonetz/GLideN64#623]
Everything default settings other then resolution get weird issues in the Smackdown Mall part of the game.

![wwf no mercy](https://cloud.githubusercontent.com/assets/13487931/8881659/8f3456a4-320f-11e5-80b8-c07ed848fdc9.png)

**Comment by olivieryuyu** [comment]
i have no issue, please check with another emulator

**Comment by Breadwinka** [comment]
Just tried with Mupen same issue
![mupen](https://cloud.githubusercontent.com/assets/13487931/8885038/15865d6e-322a-11e5-9914-00f720b283a5.png)

**Comment by olivieryuyu** [comment]
Confirmed. ok this is specific part of the menu indeed. I got it fixed by disabling the noise.

Something got incorrect with noise recently

**Comment by Breadwinka** [comment]
This is now working correctly.

**Comment by purplemarshmallow** [comment]
Are you sure, it's not fixed for me. Noise emulation causes this problem and the code for noise emulation has not changed

**Comment by Breadwinka** [comment]
I mean it's possible. I downloaded a build from emucr from August 17 noise emulation was on and I wasn't getting the bug anymore.

**Comment by purplemarshmallow** [comment]
fixed by https://github.com/gonetz/GLideN64/commit/1bf3b6e85afbf5be19fbb4d07e3d73f80efd9a21

**Comment by olivieryuyu** [comment]
pleazse close it is fixed
