### ISSUE TITLE
Toukon road 1 & 2, last legion UX: HLE implementation (extended turbo3D)?

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#624]
Revesering customs microcode are of course a very difficult task however it would be wonderful to have one day of full HLE plugin supporting all games.

For Toukon road 1 & 2, last legion UX, i ran a ram analysis with Nemu debugger of this game and I detected something interesting. 

Apparently the name of the microcode of those games is T3DUX (vers 0.83 for Toukon Road, 0.85 for Toukon Road 2 and Last Legion UX)

![t3d](https://cloud.githubusercontent.com/assets/8987490/8894651/e1e7dafa-33be-11e5-9b93-a9f17bec4618.jpg)

I guess T3D stands for Turbo3D and UX to show that this microcode was improved (as for F3DEX).

As the missing graphics are mostly 3D characters (as for Dark Rift) in those games,t it makes that the developer may have use such a microcode. Also the quality of the graphics seems likely to be the unprecised turbo3D microcode.

However I cannot understand why Rice debug plugin (and certainly others) is not able to "detect" the string in the memory when such a microcode is used. Is there something to dig in as a bug in this regard?

**Comment by theboy181** [comment]
Agreed!!

**Comment by LegendOfDragoon** [comment]
Glad to see there are others who want these games HLE'd :smile: . I do believe Last Legion uses Turbo3d, at least partially anyway. I did see some of the same code I saw in Turbo3d examples.

>However I cannot understand why Rice debug plugin (and certainly others) is not able to "detect" the string in the memory when such a microcode is used. Is there something to dig in as a bug in this regard?

Good find! It's because glN64, GlideN64, and Rice Video assume that the string starts with "RSP". All you have to do is also check for "T3D" and it will be found. I can't seem to find the text for WDC unfortunately.

**Comment by purplemarshmallow** [comment]
Last Legion UX works with Rice video, only the characters are missing
But GLideN64 in HLE shows nothing

**Comment by olivieryuyu** [comment]
There is 2 microcodes used for this game, the normal F3DEX for the background grahics and this T3DUX microcode. Rice has also implemented a hack to support 2D in games with unknown microcode.

GlideN64 can handle the background graphics easily as other plugins do.

**Comment by olivieryuyu** [comment]
after checking the ucode, it is clearly a modified turbo3d microcode that those game uses.

**Comment by LegendOfDragoon** [comment]
Can you take a look at Goldeneye's microcode and compare to Last Legion? I thought some of the code looked very familiar tbh. It made me wonder why this microcode hasn't been HLE'd yet.

I gotta figure out how to HLE the RDP since that's the main bottleneck, usually.

**Comment by olivieryuyu** [comment]
there is 2 ucodes for this game: f3dex v1 and t3dux.

In your dump, f3dex v1 can be found in "Last Legion Gfx 02".

F3DEX is nearly the same than GE007.

GlideN64 can render the background of the game, it is not issue at all.

in your dump T3DUX can be found in "Last Legion Gfx 06"

It is similar with "Dark Rift Gfx 06".

It is where HLE fails.

**Comment by olivieryuyu** [comment]
My small idea of mine:  this turbo3d microcode was extended to support the same format than F3DEX when it comes to manage the vertex. T3D = Turbo3D and UX = Unified eXtension. It is true that the manual says that the  the turbo3d microcode uses the same format as the vertex format in gbi.h so if gbi.h changes in F3DEX, the turbo3d microcode had to change accordinlgy.

Many part of the code is the same but things related to the vertex in the code was changed. Sometimes it looks like double,as if it was treating two triangles in the same time as gSP2Triangles.

**Comment by LegendOfDragoon** [comment]
Is it just me, or does that blocks.turbo demo you sent not work in GLideN64 HLE?

**Comment by olivieryuyu** [comment]
Yes but nothing to do with T3DUX microcode. It is working with Glide64. Fifo issue that can be easily fixed if I do remember.

**Comment by LegendOfDragoon** [comment]
I couldn't get it working in Glide64. I figured maybe fixing this could help with implementing T3DUX.

I think it would be a good start to at least get the game booting, and display the backgrounds. Maybe I'll just use Rice though, for studying that game.

**Comment by olivieryuyu** [comment]
I spent a bit time on this ucode and actually the code is different when it comes to handle the textures.

**Comment by olivieryuyu** [comment]
So I think more or less I understand what is going on.

Small explanation:

Here an example of a turbo display list:

![image](https://cloud.githubusercontent.com/assets/8987490/26788614/19a4e692-4a0e-11e7-8127-d1d0aa8715d9.png)

As you can see there is two more 32 words than the standard turbo3d.

The global state works in the same way.

The object state is a slightly different:

![image](https://cloud.githubusercontent.com/assets/8987490/26789137/a39a3e5a-4a0f-11e7-84c3-6e356273a028.png)

The simple matrix is downloaded from the object state memory address + 0x0018

The treatment of the RDP command list nearly the same, however the last process in the list is saved in a place in memory and used back when processing the textures.

The vertex in this ucode is very very simple: it does have only x, y and z information (2 32 bit words only!).

The colors and textures coordinates are provided with processing the tri, colors and textures coordinates list.

here what you do have in this list as an example:

![image](https://cloud.githubusercontent.com/assets/8987490/26789403/7d45a216-4a10-11e7-9963-53284721ec72.png)
 
the first line ( 0x740) from this list are, as for turbo3d, are the pointers to 3 vertex of the triangles (so here v0 = 00, v1 = 01, v2 = 02, flag = 00) and also the pointer to the 3 colors of those triangles as 

the second line ( 0x744) is the

**Comment by olivieryuyu** [comment]
I think that my explanation should be sufficient to have a HLE implemention of this ucode.

**Comment by olivieryuyu** [comment]
wiki created for for posterity :) 

https://github.com/gonetz/GLideN64/wiki/T3DUX-ucode

**Comment by LegendOfDragoon** [comment]
>PS: the ucode is written in a poor manner, it is quite a mess.

Out of curiosity, why do you say it's written in a poor manner?

**Comment by olivieryuyu** [comment]
actually the modifications are written with poor quality, the original code of turb3d being all right.

Why?

The code does not implement necessary checks to avoid sending to RDP meaningless information for instance.

For instance a part of the code sends to RDP 0x08000000 00000000 each time a triangle does not have a texture. It is a waste of resource.

**Comment by gonetz** [comment]
@olivieryuyu Thanks for the wiki page!
It would be great to create such pages for other custom ucodes decoded by you and other devs  - for posterity.
For example: F3DTEXA, F3DSETA, F3DBETA

**Comment by olivieryuyu** [comment]
I could do one for F3DTEXA indeed :)

**Comment by gonetz** [comment]
T3DUX implemented: 4722a75b243

Test build:
https://drive.google.com/file/d/0B0YqMPjGo3B2WUFxM0RiQjlfZXM/view?usp=sharing

**Comment by AmbientMalice** [comment]
Great work.

**Comment by gonetz** [comment]
Use RSP plugin from older PJ64 version to be sure that you run HLE.

**Comment by Frank-74** [comment]
Toukon Road 1+2, and Last Legion UX, all work with latest PJ64 in HLE.  Just select Use HLE in plugin selection for those games.

**Comment by olivieryuyu** [comment]
@gonetz 

just a short question about your code: why not detecting the microcode by its string, meaning "T3DUX"?

**Comment by gonetz** [comment]
Ucode name not started from "RSP". A bit more additional code needed to parse that case.

**Comment by olivieryuyu** [comment]
I see :)

No bug found, let's close the ticket then!

**Comment by gonetz** [comment]
It took almost to years to solve. A hard one.
