### ISSUE TITLE
AeroFighters Assault: texture are black on planes in intro!!!!

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#628]
![nooo](https://cloud.githubusercontent.com/assets/8987490/8915293/6f7e2db6-34a4-11e5-8ddf-2e5be3fd41fc.jpg)

**Comment by purplemarshmallow** [comment]
regression from https://github.com/gonetz/GLideN64/commit/2199dd4290440362b62c09850c169f012d2bd508

**Comment by purplemarshmallow** [comment]
fixed

**Comment by olivieryuyu** [comment]
fixed
