### ISSUE TITLE
The famous winback square bug 

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#63]
a long standing bug in all HLE plugin: a square appears at the start of the in game 

![box](https://cloud.githubusercontent.com/assets/8987490/4782154/a53c9988-5ce1-11e4-9e84-8f2b9cb60e36.jpg)

Correct with Z64

![corecskii](https://cloud.githubusercontent.com/assets/8987490/4782156/b810a28e-5ce1-11e4-81f2-041489a0fa99.jpg)

**Comment by stranno** [comment]
This problem have been there since the very beginning of the N64 emulation.

pokefan is the only one who have "fixed" it so far, i belive (i dont know if it was fixed or the square is just transparent).

https://www.youtube.com/watch?v=nO-vJ6qrYBs

**Comment by gonetz** [comment]
He hardly made a real fix for it, rather removed it with some hack.

I still hope that true solution will be found someday.

**Comment by stranno** [comment]
Even the Nintendo's Virtual Console emulator have this problem.

**Comment by vgturtle127** [comment]
Was the source to ACE64/NICE64/ICE64/1964mod ever released so we could see how the hack works? If we knew how the hack worked, maybe we could then understand why our emulation is off.

**Comment by gonetz** [comment]
I guess, there is no magic in the hack. That square is a texrect with weird set of parameters. It can be filtered and removed. I just don't want to make hackish solution. Right solution is to understand what the game actually intended to draw there.

**Comment by olivieryuyu** [comment]
hmm i think i tried to explain what was trying to be drawn. it is part of the sliding texture that there is in the level (from the sky to the water). the color is the primary one used for the texrec, which should not be displayed for some reasons.

**Comment by vgturtle127** [comment]
@gonetz Oh, of course. I just meant maybe by looking at what the hack did we could figure out what the console is doing to render that damn box. :laughing: 

@olivieryuyu I hear about this "sliding texture" a lot it seems. But I don't understand what is sliding from the sky to the water. Is it to simulate lighting, or is it a reflection? You also said that is the primary color used in the texrec, so I assume that means that the only color that is displayed happens to be the first color needed by the sliding texture? If that is the case, maybe we could try changing the box to a different part of the texture to see if that does anything?

**Comment by olivieryuyu** [comment]
best example is level 11 (you can access by cheat)

![sans titre](https://cloud.githubusercontent.com/assets/8987490/8123914/3e4413a0-10d2-11e5-9642-1b701dbfe5cd.jpg)

There is 2 square.

What are they relate to:

The grey one is linked to the sky which is moving in some direction (see 1st level, it is super obvious). Color shows you that: the sky is grey

The blue one is linked to the water which is moving in some direction. Color shows you that: the sky is blue.

It is always the same matter: 

level 22: the green square is linked to the moving water in the sewers.

moving, sliding, going some direction: not sure how to explain better.

Clear? For u too Sergey?

**Comment by gonetz** [comment]
Description is clear, thanks.

**Comment by vgturtle127** [comment]
Oh, OK. That makes a lot more sense now. Thanks @olivieryuyu :smile: 

I feel less dumb now. :laughing: 

So does the bug happen on NTSC/NTSC-J and PAL versions?

**Comment by olivieryuyu** [comment]
all versions. 

I would have thought that comparing HLE and LLE display list would help to figure out the way the texrec was handled but may be it is not that simple :(

**Comment by vgturtle127** [comment]
Has anybody tried to run the game in CEN64 or the MESS driver? Or in an emulator with a software renderer and extensive debugging/logging?

**Comment by olivieryuyu** [comment]
I think gliden64 lle works correctly. No need to go to other plugin

**Comment by vgturtle127** [comment]
Oh, so LLE works but HLE doesn't?

If that's the case, then can't we just compare how each handle that game specifically?

**Comment by olivieryuyu** [comment]
not such an easy task

**Comment by vgturtle127** [comment]
No, but it's definitely a start. I may take a good hard look at this later when I get my dev machine up.

**Comment by olivieryuyu** [comment]
http://160592857366.free.fr/joe/ebooks/ShareData/Game%20Graphics%20Programming%20By%20Allen%20Sherrod.pdf

I found this interesting manual.

Apparently the author refers to Perfect Dark and Goldeneye sky.

Goldeneye 007 used the most simple approach to rendering water in a
game. When this game was released, hardware limitations kept outdoor
scene complexity relatively low compared to today’s games. Because of
this, water in the game did not possess any properties of water other than
its color and that the player could not walk on it.
To render water, Goldeneye 007 essentially used a large textured
square that was placed in the game world to act as the environment’s
water. To give the water surface more of a distinct look and feel, the
game developers used moving texture coordinates to simulate the water
moving. In addition to using dynamic texture coordinates for the water’s
surface, they also used them for the sky plane. This gave the appearance
of moving clouds as well as moving water.

Rare’s 2000 game  Perfect Dark was the follow-up title to their blockbuster hit Goldeneye 007
for the Nintendo 64. Perfect Dark was built using a modified version of the framework (game engine) used in Goldeneye 007
.
Perfect Dark not only proved itself a worthy follow-up to Rare’s Goldeneye007
, but it used improved graphics and rendering techniques. This was in
part thanks to the Nintendo 64 expansion RAM add-on, which was used
to boost the graphical quality in many Nintendo 64 games that supported its use.Water in the original Perfect Dark still used the same generally simple idea as Goldeneye 007. In Goldeneye 007
the water’s animation movementwas linear and constant. This means that the speed at which the animation was viewed did not change, and neither did the direction of its
movement. In practice this is very easy, but when implemented, it doesn’t truly look like water. On hardware such as the Nintendo 64, there was only so much that could have been done anyway when compared totoday’s hardware.In Perfect Dark the water’s animation was modified so that it changed direction and speed as it was being viewed. This gave it a more believable water-like appearance using the game console’s hardware at a relatively cheap cost. To create the style of water seen in Goldeneye 007, a matrix can be used on the texture coordinates to rotate them in a specific direction. To implement the style of water seen in Perfect Dark, the direction and speed can be dynamically adjusted for each frame. This can be as simple as taking a velocity vector and using a sine wave that is based on time to move the vector forward and backward. Since velocity is being used, the speed decreases as each axis reaches 0 and increases asthey move farther away in either the positive or negative direction. This can be seen using the following equation if the water is moving only in the direction of the X-axis:

New_Velocity = Velocity_Constant * Vector3D( sin( time ), 0, 0 ) 

The sine waves more within the 1 to 1 range. Alternatively, the equation can be expanded to use each axis of the vector. If the original
velocity constant was given different values for each axis, the look of thewater using this method would appear more dynamic. Also, axis modifiers can be used by using random values to adjust the vector being multiplied by the velocity to give it an even more dynamic look that does not
appear like canned animations

I would believe that the sky in Winback is as well a rotating, dynamic texture. No idea how it could be achieve by FDEX2 microcode.

**Comment by olivieryuyu** [comment]
https://github.com/death-droid/Rice-Video/blob/master/Parser/RSP_GE.h

sky render in HLE with a texture rectangle by Rice plugin but without the rotating texture.

Would the rotating texture be generated by the same G_DMA_OFFSET command than in JFG/DKR?

rdphalf_cont could be instead this command?

**Comment by vgturtle127** [comment]
@olivieryuyu Thanks so much for the information! I am looking into the WinBack bug currently, and as of right now I am getting ready to start my testing of the N64 library.

So does LLE always work with any plugin, and HLE never works with any plugin?

**Comment by olivieryuyu** [comment]
yes

**Comment by vgturtle127** [comment]
@olivieryuyu Alright, thanks man.

**Comment by olivieryuyu** [comment]
http://fgfc.ddns.net/PerfectGold/ucode05.txt

**Comment by olivieryuyu** [comment]
#578

**Comment by olivieryuyu** [comment]
a hack is better than nothing of course.

Will check if all sliding textures are working as it should (sky, water, mud, etc)

If so will close the ticket

**Comment by gonetz** [comment]
I'm pretty sure that the hack will work in other similar cases.
I compared LLE and HLE display lists, starting from sky texture load. Both list are identical until texrect command in HLE. LLE list has no-op (do nothing) command on this place. That texrect is not normal HLE texrect command, so it is easy to filter out.

**Comment by olivieryuyu** [comment]
fixed

**Comment by olivieryuyu** [comment]
it is fixed by a hack. 

However it can certainly be fixed without an hack :)

**Comment by AmbientMalice** [comment]
You are a hero of N64 emulation, olivieryuyu.

**Comment by olivieryuyu** [comment]
@gonetz 

I understand what is going on but I am not sure how it can be solved or if there is anything to be solved actually.

This is what i guess you have in your display list:

![image](https://user-images.githubusercontent.com/8987490/27793259-9e026d88-5ffd-11e7-97d3-ff840d2dda0b.png)

There is no E1 or F1 command that comes after the E4 command.

In that case, the code is simply sending the 3rd word (0x000C000C) as the first half of the 64 bits RDP command and then a  second command found randomly in the RDP command stack.

Obvioulsy the result for the RDP is completely meaningless and is like a noop operation.

I guess that the matter is due to an programming error of the developers, which they didn't spot.

So conclusion: If there is no E1 command after the E4, do not draw the texture rectangle.

End of the mystery, after all those years :)

**Comment by gonetz** [comment]
"If there is no E1 command after the E4, do not draw the texture rectangle"
As you know, there are several exception from this rule.

Currently winback square hack works like this:
If there is no E1 or F1 command that comes after the E4 command and the game is WinBack, do not draw the texture rectangle.

**Comment by olivieryuyu** [comment]
Ah yes the All Star Baseballs games :)

Well your implementation matches the ucode, so it should be considered as a hack.

We can close the close the case once and forever.
