### ISSUE TITLE
BattleZone Lens Flare Issue

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#633]
Glide64:
![glide64_battlezone_01](https://cloud.githubusercontent.com/assets/10704701/8945967/a606e432-35cf-11e5-8eb4-6a136a73f150.png)

GlideN64:
![gliden64_battlezone_000](https://cloud.githubusercontent.com/assets/10704701/8945986/c67d2a32-35cf-11e5-82cd-35c4456d02d3.jpg)

**Comment by LegendOfDragoon** [comment]
How does it look with Angrylion's?

**Comment by AmbientMalice** [comment]
ANGRYLION'S
![nzoe0000](https://cloud.githubusercontent.com/assets/10704701/8946181/c9879e7c-35d1-11e5-9e06-3f31a0a056fe.jpg)

**Comment by LegendOfDragoon** [comment]
@AmbientMalice Thanks :smile: . Is this also a problem for GlideN64 LLE?

**Comment by AmbientMalice** [comment]
Yes. With the added bonus of the map being corrupted. Same as https://github.com/gonetz/GLideN64/issues/465

![gliden64_battlezone_002](https://cloud.githubusercontent.com/assets/10704701/8946463/c1fcb9a6-35d3-11e5-9632-c4bba707e9e2.jpg)

**Comment by LegendOfDragoon** [comment]
How about z64gl?

**Comment by AmbientMalice** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10704701/8947415/edce5896-35dd-11e5-8108-8822644e09df.jpg)

z64gl has correct lens flares, but corrupt map. (GLideN64 inherited the latter bug directly from z64)

**Comment by AmbientMalice** [comment]
Seems fixed. Not sure which commit, but I think it was a recent one.

![gliden64_battlezone_000](https://cloud.githubusercontent.com/assets/10704701/13918357/614d3cf4-efb2-11e5-963e-fca84c9ac7d2.jpg)

Interestingly, I don't think Angrylion's is rendering the terrain radar thing on the HUD correctly. It makes logical sense in GLideN64, showing you height elevation and such. But in Angrylion's it's a sea of swimming lines.

**Comment by purplemarshmallow** [comment]
Would be nice to see how the radar looks like on real hardware. I don't have I don't have this game ready to test unfortunately
