### ISSUE TITLE
(LLE) GoldenEye text texture issue.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#635]
HLE:
![gliden64_goldeneye_003](https://cloud.githubusercontent.com/assets/10704701/8947437/1d973f8e-35de-11e5-97ba-c84cd8e149be.jpg)

LLE:
![gliden64_goldeneye_002](https://cloud.githubusercontent.com/assets/10704701/8947440/2a1daa36-35de-11e5-8027-11c5813a48c1.jpg)

Reminds me of that flipped text issue HatCat's plugin used to have. (Can't recall if it was video or RSP plugin.)

**Comment by olivieryuyu** [comment]
yep how odd it is!!!!

**Comment by theboy181** [comment]
I'm sure this looks like the issue that is in zgl64. hats issue was the same issue that happened with charmeleon twist and the title screen.

**Comment by olivieryuyu** [comment]
seems solved

please check and if so please close

**Comment by olivieryuyu** [comment]
@AmbientMalice 

pls check and close, I have not such a bug, in LLE and HLE.
