### ISSUE TITLE
F-Zero X missing reflections [HLE]

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#638]
reflections are missing, they appear correctly with z64gl
![gliden64_f-zero_x_000](https://cloud.githubusercontent.com/assets/7283660/8970926/c6050638-364c-11e5-9180-f5d4174a0170.jpg)
![1](https://cloud.githubusercontent.com/assets/7283660/8970929/c7e59b34-364c-11e5-8cd3-7af24ccc173b.jpg)

**Comment by olivieryuyu** [comment]
i think reflections had deactivated, mostly because the game uses a specific microcode for this aspect

**Comment by Predator82Germany** [comment]
A unknown microcode?

**Comment by olivieryuyu** [comment]
not documented. certainly a very slighly changed for a very specific aspect

**Comment by purplemarshmallow** [comment]
>i think reflections had been deactivated

is there a hack in the plugin?
maybe reflections will show up in LLE if the hack is removed

**Comment by olivieryuyu** [comment]
hmm short question, on real N64, is there the reflections?

**Comment by purplemarshmallow** [comment]
Yes

**Comment by olivieryuyu** [comment]
it is somehow a hack indeed

**Comment by olivieryuyu** [comment]
microcode is called F3DFLX.

L for light I guess

Here with Angrylion plugin: indeed there is reflections.

![sds](https://cloud.githubusercontent.com/assets/8987490/8992204/989022ee-36fd-11e5-913a-a3a68bcc41e8.jpg)

**Comment by purplemarshmallow** [comment]
undocumented microcodes shouldn't be a problem in LLE
but GLideN64 in LLE shows no reflections

**Comment by olivieryuyu** [comment]
indeed it should be except if the hack for HLE affects LLE

**Comment by purplemarshmallow** [comment]
I don't think it's a microcode issue. The reflections appear at the vehicle selection. I also can't find a hack to disable reflections I don't think there's such a hack in the plugin.

I think the problem is blending. z64gl's blending method is different from other plugins. A special blend mode is used ingame. It would make sense but I can be wrong.

**Comment by olivieryuyu** [comment]
if (strncmp(&uc_str[14], "F3DF", 4) == 0)
						current.textureGen = false;

**Comment by purplemarshmallow** [comment]
I tested it and it does not help.
It's not a microcode problem otherwise it would work in LLE. This line does not affect LLE at all.

**Comment by purplemarshmallow** [comment]
Now fixed in LLE
HLE still incorrect

**Comment by olivieryuyu** [comment]
Weirdly the microcode of this game (F3DFLX) has less code than the normal F3DEX2 ucode. I guess to boost the performance and the speed.

**Comment by olivieryuyu** [comment]
Gosh, it seems that each ucode used in this game has a customized portion for lights. It is going to be challenging.

**Comment by theboy181** [comment]
I bet you will figure it out.. :)

**Comment by Aquatakat** [comment]
@olivieryuyu You're a superstar in my eyes.

**Comment by olivieryuyu** [comment]
No luck here, the code is horrendous. I may come back later on that one.

**Comment by olivieryuyu** [comment]
I begin to see the light (I hope), still a long road.

A new command exists.

G_TEXTURE_GEN flag leads to a new code and uses the data obtained from this new command to change the alpha of the vertex. 

Weird stuff...

**Comment by olivieryuyu** [comment]
Finally I understood what the code does. Weird way to implement reflections on the cars but it was to get the game as fast as possible.

**Comment by olivieryuyu** [comment]
Can it be closed?

**Comment by gonetz** [comment]
I guess yes :)
