### ISSUE TITLE
Zelda OOT wrong fog [HLE]

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#640]
in front of the temple of time fog is applied on Link's model, turning him gray
correct with z64gl
![gliden64_the_legend_of_zelda_006](https://cloud.githubusercontent.com/assets/7283660/8982867/64f0cdcc-36c5-11e5-8d3b-0abc7d951d01.jpg)
![1](https://cloud.githubusercontent.com/assets/7283660/8982868/6719faa6-36c5-11e5-8650-9513e61077ba.jpg)

**Comment by olivieryuyu** [comment]
a savestate is possible?

**Comment by purplemarshmallow** [comment]
https://drive.google.com/file/d/0B7Y6r4SpC_QQT3pEdmptV2h6Q1E/view?usp=sharing

**Comment by OldGnashburg** [comment]
Is it just me or does the depth look wrong on the z64gl screenshot? Link seems almost pasted on. But then again, it is one of Ocarina of Time's really sh*tty pre-rendered backgrounds (thankfully they are few). Not that z64gl has anything to do with GLideN64. Just thought I'd comment...

**Comment by AmbientMalice** [comment]
>Not that z64gl has anything to do with GLideN64.

GLideN64 has cut-pasted z64gl code in it.

**Comment by wareya** [comment]
I think that -- somehow -- z64gl isn't accurate in this effect either? What the hell?

https://www.youtube.com/watch?v=Ea1gSVzGag4#t=10m25s

Requesting real hardware high-quality image capture of this effect.

**Comment by purplemarshmallow** [comment]
Here's a screenshot from angrylion's plugin. That's usually a good reference and in the video the effect looks the same. I think z64gl emulates this effect correctly but it looks a bit strange because Link's model is rendered at a higher resolution over the low-res background
![czle0000](https://cloud.githubusercontent.com/assets/7283660/9096665/ce92e636-3bbe-11e5-9000-1c9ca1bad162.jpg)

**Comment by wareya** [comment]
I don't know, even that looks much more colorful than the z64gl screenshot.

**Comment by olivieryuyu** [comment]
I confirm that this HLE bug still exists.

**Comment by gonetz** [comment]
Fog factor is vertex alpha. Vertex alpha is 0 in LLE mode and 1 (0xFF) in HLE. Need to check olivieryuyu's docs about lighting in Zelda. May be there is a clue, when vertex alpha becomes zero.

**Comment by olivieryuyu** [comment]
With those values, it looks like a clamping issue.

**Comment by olivieryuyu** [comment]
it is a clamping issue

clamping between 0x0000 and 0x7F00 (F3DEX 0x00FF).

7F**00** leads to have value set to 0x00 above a certain threshold and not anymore FF.

**Comment by olivieryuyu** [comment]
F3DEX and F3DEX2 does not clamp alpha in the same way.

It seems than F3DEX3 set the maximum value to 0x7F00.

Alpha becomes 0x00 in this case and not 0xFF (0x7F**00**)

**Comment by Kidboy17** [comment]
This is still an issue present in the newest WIP build. Screenshot for proof. 
![gliden64_the_legend_of_zelda_000](https://user-images.githubusercontent.com/37382324/45275574-5e875900-b472-11e8-8265-6766ece5f9a4.png)

**Comment by Kidboy17** [comment]
This issue is still present in the newest WIP (Master + FB)

**Comment by gonetz** [comment]
I know that it is not fixed. No need to remind about it.

**Comment by gonetz** [comment]
Fixed.

**Comment by gonetz** [comment]
Lets close.
