### ISSUE TITLE
BSOD on Windows 10

### ISSUE THREAD

**Issue by phly95** [gonetz/GLideN64#641]
Windows 10 Bluescreens when running GlideN64. I've had a chance to try it with both an Nvidia and an Intel GPU and they both have a bluescreen.

**Comment by phly95** [comment]
compatibility mode for Windows 8 seems to fix the issue, however Intel cards still have the terrible graphical glitches. There needs to be a fix for Windows 10 though because not a lot of people are likely to try using compatibility mode.

**Comment by WizLizard** [comment]
It's not just GlideN64 go to Project64 forums. Also many other emulators are getting Bluescreens.

**Comment by Breadwinka** [comment]
I looked into this, its actually all versions of glide cause BSOD. Old Jabo plugin 1.7.0.57 doesnt BSOD, neither does Angrylions RDP.

**Comment by theboy181** [comment]
DEP?

**Comment by Breadwinka** [comment]
This issue is caused by Project64.

**Comment by GamingHD** [comment]
To confirm the above, it happens in Project 64 but neither the older Mupen64 (using the zilmar spec) nor Mupen64Plus experiences the issue. It does appear to be an emulator bug.

**Comment by gonetz** [comment]
O, if it is Project64 issue, I close it.
