### ISSUE TITLE
Add 6xBRZ

### ISSUE THREAD

**Issue by dartraiden** [gonetz/GLideN64#643]
xBRZ 1.4 just [relized](https://sourceforge.net/projects/xbrz/files/xBRZ/), bringing 6xBRZ support

**Comment by gonetz** [comment]
Done. Binaries:
https://drive.google.com/file/d/0B0YqMPjGo3B2YldKNEo1UmNfM0E/view?usp=sharing
Please test all xbrz filters and close if everything works.

**Comment by theboy181** [comment]
1080 Snowboarding has issues with he lens flare, and the title textures with this build.

**Comment by gonetz** [comment]
I see no <b>new</b> issues in 1080. Could you make comparison screenshot "new build vs ver 1.2", which illustrates new issues?

**Comment by theboy181** [comment]
After resetting to default. I noticed that the textures look OK with filters on, but are not correct with default settings.
The lens flares are also incorrect, they show through the mountains. 
![capture](https://cloud.githubusercontent.com/assets/9299743/9294558/d0f3bc9e-4405-11e5-964f-bf3fa4e3c87a.PNG)
![capture1](https://cloud.githubusercontent.com/assets/9299743/9294559/d0f61c96-4405-11e5-8014-f373ba5773f8.PNG)

**Comment by gonetz** [comment]
I asked about <b>new</b> issues, related to texture filtering. 
Incorrect logo issue is not related to texture filtering and presents in ver 1.2.
Lens texture by itself is correct; poke through mountain issue is not related to texture filtering.

**Comment by theboy181** [comment]
My bad. I have been using uniffical builds that don't share these issues. 

The filter works great.

**Comment by gonetz** [comment]
>The filter works great.

It should work, because I mostly replaced old zenju's code by the new one.
Since it works not only for me, I think it can be closed.
