### ISSUE TITLE
At least 3 Zelda: Ocarina of Time effects that display completely wrong

### ISSUE THREAD

**Issue by OldGnashburg** [gonetz/GLideN64#645]
Alright, I'll explain a little bit, I haven't actually tested, but as my computer is broken at the moment I haven't tested GLideN64 yet. I have pretty much memorized what the game is supposed to look like as I have an N64 with Ocarina of Time. I also have memorized the glitches in the the original Glide 64 plugin. I am posting this as issues for two reasons, A) since I haven't tested GLideN64 at all I'm not sure if they exist in this plugin. B) I'm only submitting them so others can see if they do still exist and confirm them, and then do something about it. Anyways, here are the potential bugs.

1) Bongo Bongo Fog effects:
After you beat the Water Temple and travel to Kakariko Village, there is a cutscene with Sheik, in which Kakariko Village is on fire. In the cutscene, Bongo Bog breaks out of the well and throws Sheik around (he is correctly invisible up to this point) he then moves around Kakariko village. On hardware the effect looks similar to a cloud of TV Static except purple and slightly three dimensional. With Glide 64 (and presumably GLideN64) the affect is a very very fine blur of lightish blue. Completely wrong. The effect occurs later in the game when you face Bongo Bongo in battle, and it is still completely wrong.

2) Dark Vortex Effect:
When you face Phantom Ganon in the Forest Temple and beat him, a dark purple vortex appears along with a little message from Ganondorf. On hardware, The vortex is solid and completely covers up the the area it takes up, but with Glide 64 and presumably GLideN64, most of the vortex fails to show up and it's pratically see-through. This effect also occurs (and displays incorrectly) when Nabooru is kidnapped by Koume and Kotake in the cutscene that occurs after you get the Silver Gauntlets.

3) Ganondorfs Attacks.
When you face the first form of Ganondorf, he will usually attack with a "black energy hole" at least once per fight. On hardware, the attack starts off when Ganondorf raises his arms and creates a ball of energy that starts off pitch black (with the edges/outline being yellowish light, like an eclipse) and then the ball transitions into pure light and then Ganondorf attacks you. In Glide 64, and presumably GLideN64, the attack doesn't transition at all and in fact begins as light and doesn't change.

There are a few other possible issues that might just be in my head, such as the Mirror Shield charge effects when fighting Twinrova, along with Twinrova's attacks. attacks (when they hit the ground they seem a bit odd). I also think that when Ganodorf attacks you during the cutscene with Ganondorf in Hyrule Field after getting the 3 Spiritual Stones, his attack is also supposed to start off dark and transition into light. I also think that the painting brightness differences (when you fight the first part of Phantom Ganon you are supposed to determine which painting he'll come out of by choosing the brightest one out of the paintings he appears to be leaving out of) during the fight with Phantom Ganon are either not working or not displaying properly.
Anyways I know there might be more bugs that could have possibly stuck around (like the portals which were recently fixed and shown correctly in the blog). Anyways please test and confirm. If they still do exist I hope they get fixed.

**Comment by purplemarshmallow** [comment]
>1) Bongo Bongo Fog effects:
After you beat the Water Temple and travel to Kakariko Village, there is a cutscene with Sheik, in which Kakariko Village is on fire. In the cutscene, Bongo Bog breaks out of the well and throws Sheik around (he is correctly invisible up to this point) he then moves around Kakariko village. On hardware the effect looks similar to a cloud of TV Static except purple and slightly three dimensional. With Glide 64 (and presumably GLideN64) the affect is a very very fine blur of lightish blue. Completely wrong. The effect occurs later in the game when you face Bongo Bongo in battle, and it is still completely wrong.

I think noise is used here. GLideN64 fully supports noise effects so it should be correct but I haven't tested

>3) Ganondorfs Attacks.
 When you face the first form of Ganondorf, he will usually attack with a "black energy hole" at least once per fight. On hardware, the attack starts off when Ganondorf raises his arms and creates a ball of energy that starts off pitch black (with the edges/outline being yellowish light, like an eclipse) and then the ball transitions into pure light and then Ganondorf attacks you. In Glide 64, and presumably GLideN64, the attack doesn't transition at all and in fact begins as light and doesn't change.

I opened #646

**Comment by OldGnashburg** [comment]
Thank you purplemarshmallow, you are a lifesaver (for most people, not really, but in my books you are). Any ideas about the vortexes? Not to be confused with the boss room portals (them blue ones). Also, is it just me or is the ruby in the hilt of the Kokiri Sword slightly off color? And have you noticed anything odd about the effects in the fight with Twinrova?

**Comment by OldGnashburg** [comment]
As a continuation, I may have forgotten about another issue that may be present. When you press start (to open the inventory) in the room where you get the Iron Boots in Ice Cavern; the walls in the background get all glitchy and almost make you trip. The same thing happens to the Great Fairy Fountain walls.

**Comment by purplemarshmallow** [comment]
>As a continuation, I may have forgotten about another issue that may be present. When you press start (to open the inventory) in the room where you get the Iron Boots in Ice Cavern; the walls in the background get all glitchy and almost make you trip. The same thing happens to the Great Fairy Fountain walls.

I haven't tested everything but the walls in the background are correct with GLideN64.

**Comment by OldGnashburg** [comment]
Sorry, not trying to rush you. A couple of these bugs will probably require you start a new game in order to test. And it takes time to play through. However, I think I remember another bug. Some seams in many places in the game do not appear completely closed.

**Comment by purplemarshmallow** [comment]
http://rainingchain.com/zelda/
This site has 500+ MBs of Zelda savestates

**Comment by purplemarshmallow** [comment]
>1) Bongo Bongo Fog effects:


>I think noise is used here. GLideN64 fully supports noise effects so it should be correct but I haven't tested

I'm correct, GLideN64 fully supports this effect
![gliden64_the_legend_of_zelda_006](https://cloud.githubusercontent.com/assets/7283660/9275214/c6472e0e-429b-11e5-9780-43aeafb26ce5.jpg)

**Comment by purplemarshmallow** [comment]
>2) Dark Vortex Effect:
 When you face Phantom Ganon in the Forest Temple and beat him, a dark purple vortex appears along with a little message from Ganondorf. On hardware, The vortex is solid and completely covers up the the area it takes up, but with Glide 64 and presumably GLideN64, most of the vortex fails to show up and it's pratically see-through. This effect also occurs (and displays incorrectly) when Nabooru is kidnapped by Koume and Kotake in the cutscene that occurs after you get the Silver Gauntlets.

Correct with GLideN64
![gliden64_the_legend_of_zelda_007](https://cloud.githubusercontent.com/assets/7283660/9276076/1cb36478-42a2-11e5-81e4-fb2ff91fe257.jpg)

**Comment by purplemarshmallow** [comment]
Is everything tested?
Then this can be closed I guess

**Comment by OldGnashburg** [comment]
I recently managed to test, and I was able view the portal around Nabooru and it was buggy, either the hardware I was using did not fully support GLideN64 effects, or it doesn't work. Anyways could you check? If it is the hardware I was using, then I will close.

**Comment by purplemarshmallow** [comment]
do you have a savestate?

**Comment by OldGnashburg** [comment]
I checked and it's all fixed. Issue closed.
