### ISSUE TITLE
Zelda OOT wrong effect during Ganondorf battle

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#646]
Ganondorf's attacks should be black, angrylion's plugin shows the correct effect.
Savestate: 
https://drive.google.com/file/d/0B7Y6r4SpC_QQR1I1X2Zfc2U2MEE/view?usp=sharing
![gliden64_the_legend_of_zelda_001](https://cloud.githubusercontent.com/assets/7283660/9044945/5881c524-3a20-11e5-86f5-362fee8b8351.jpg)
![czle0001](https://cloud.githubusercontent.com/assets/7283660/9044946/58860ddc-3a20-11e5-95fe-c7b753c14517.jpg)

**Comment by OldGnashburg** [comment]
Just as a little addendum, I believe the attack starts off black (as shown in the bottom image with angrylions plugin); and then when it finishes charging, it transitions into yellow light like in the top image. With Glide64 and GLideN64, they both skip the first effect and automatically starts off as light..

**Comment by purplemarshmallow** [comment]
it's fixed!
but why?
![gliden64_the_legend_of_zelda_001](https://cloud.githubusercontent.com/assets/7283660/24119263/dd55d41a-0db0-11e7-9295-a92438ae6590.jpg)

**Comment by oddMLan** [comment]
Probably due to getting rid of the hardcoded, legacy blending of N64 modes.

**Comment by purplemarshmallow** [comment]
yes likely...

**Comment by gonetz** [comment]
Most likely the blending fixes. Pretty cool effect btw.
