### ISSUE TITLE
Dark Rift: missing transition effect in menu

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#649]
![nope](https://cloud.githubusercontent.com/assets/8987490/9132256/800f695a-3cf2-11e5-932d-4af9e1972de6.jpg)

but with angrylion plugin

![hard](https://cloud.githubusercontent.com/assets/8987490/9132267/8e2b443c-3cf2-11e5-89c4-28021398afb5.jpg)

**Comment by AmbientMalice** [comment]
Fixed in LLE mode.
