### ISSUE TITLE
Body Harvest: incorrect/missing framebuffer effects: inventory/map

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#650]
This game has errors or completely missed framebuffer effects in game

For instance the inventory:

gliden64

![sdfdf](https://cloud.githubusercontent.com/assets/8987490/9143549/6c2ac01a-3d47-11e5-88d8-b66f91ce3846.jpg)

angrylion

![dsfsdffdfs](https://cloud.githubusercontent.com/assets/8987490/9143554/76347cb8-3d47-11e5-9e11-293120c8e9e1.jpg)

For instance the map:

gliden64:

![sdfsdffffffd](https://cloud.githubusercontent.com/assets/8987490/9143564/7f5b88e0-3d47-11e5-8833-be3504494b65.jpg)

angrylion

![map](https://cloud.githubusercontent.com/assets/8987490/9143572/8936f8b8-3d47-11e5-950e-51ccc39c2ad4.jpg)

**Comment by olivieryuyu** [comment]
it works with Glide64!!

**Comment by purplemarshmallow** [comment]
same problem as #529
VI.width calculation is wrong. If you remove one line from VI.cpp this is fixed:
VI.width = min((u32)floorf((hEnd - hStart)*xScale + 0.5f), *REG.VI_WIDTH);
but this might have side effects in other games. This line also causes a crash in Mario Tennis if "render frame buffer as texture" is enabled

**Comment by AmbientMalice** [comment]
>but this might have side effects in other games. This line also causes a crash in Mario Tennis if "render frame buffer as texture" is enabled

Are you aware of the "fix" breaking anything?

**Comment by purplemarshmallow** [comment]
Glide64 does not calculate VI.width, it uses REG.VI_WIDTH. GLideN64 calculates it but if I remove this line it uses REG.VI_WIDTH, like Glide64. I think REG.VI_WIDTH can be wrong if there's a bug in the emulator or in certain games, but I don't know a specific case. If VI.width is too high and copy frame buffer to RDRAM is enabled the emulator will crash. I think min is used here to make copy frame buffer to RDRAM more safe.

There are two ways to fix this:
Calculate VI.width more accurate or do not calculate it at all.

**Comment by olivieryuyu** [comment]
angrylion plugin does the correct calculation for VI width, so it can be made more accurate. That should be the goal anyhow.

**Comment by purplemarshmallow** [comment]
>angrylion plugin does the correct calculation for VI width

Are you sure? VI width is needed for copy color to and from RDRAM. In fact both of them are hacks to emulate CPU based effects that usually don't work with hardware renderers. Angrylion's plugin is a software renderer, I'm not sure if it needs these values at all

**Comment by purplemarshmallow** [comment]
https://drive.google.com/file/d/0B7Y6r4SpC_QQeTZZTHdVaGNNSTA/view?usp=sharing
@AmbientMalice this is current master plus #622 and the VI.width line is removed

**Comment by theboy181** [comment]
Thanks!!! I noticed that the banjo-tooie 60fps hack and the last build you provided was able to run at full speed.

**Comment by olivieryuyu** [comment]
not sure if it is relevant but VI is emulated by angrylion plugin (a part of the source code lead me to believe so)

I tested this proposed fix and the map still doesn't work.

**Comment by GamingHD** [comment]
@purplemarshmallow Could #651 be cause by the same issue?

**Comment by AmbientMalice** [comment]
Unfortunately, @purplemarshmallow the VI.width deletion doesn't fix Vigilante 8 (E) crashing. And it doesn't fix Body Harvest's map transition. I do notice however that Mario Tennis wipe transitions slightly more accurate (except the overlaid texture is black.) But it also causes Mario Tennis to flicker black constantly.

**Comment by purplemarshmallow** [comment]
>I do notice however that Mario Tennis wipe transitions slightly more accurate (except the overlaid texture is black.) 

This does not happen if you have (E) rom version

strange, the map transition looks ok for me with this build
![gliden64_body_harvest_000](https://cloud.githubusercontent.com/assets/7283660/9203010/e8ca9748-4054-11e5-85ce-13dfbd453187.jpg)

**Comment by olivieryuyu** [comment]
the map works only with E version, not U version

VI size is different depending if it is NTSC or PAL.

**Comment by purplemarshmallow** [comment]
I tested U version, works for me
which emulator do you use?

**Comment by olivieryuyu** [comment]
1964 & pj64

**Comment by purplemarshmallow** [comment]
I know what happens. If you enable depth buffer emulation it breaks this effect. So there are 2 bugs...

**Comment by olivieryuyu** [comment]
correct!

**Comment by purplemarshmallow** [comment]
VI width problems are fixed. Copy depth is now disabled by default for this game

**Comment by olivieryuyu** [comment]
fixed
