### ISSUE TITLE
Banjo-Tooie Framebuffer not working properly

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#651]
![capture](https://cloud.githubusercontent.com/assets/9299743/9185018/cfe06876-3f6d-11e5-88ac-51749c525d95.PNG)

The bubble is not functioning as it should

**Comment by GamingHD** [comment]
Can you provide a savestate please?

**Comment by theboy181** [comment]
https://www.dropbox.com/s/kpoyd5gtkkj7lm5/Banjo-Tooie%20%28U%29.pj.zip?dl=0

Banjo's reflection isn't working on ATI and its broken on Nvidia.

Running the 60 FPS hack on ATI runs really slow too, but Nvidia its not as bad.
http://forum.pj64-emu.com/showpost.php?p=63166&postcount=59

**Comment by theboy181** [comment]
![capture](https://cloud.githubusercontent.com/assets/9299743/9218504/f3899a5c-4087-11e5-995f-906fa06ac6c1.PNG)

**Comment by purplemarshmallow** [comment]
VI.width is correct here, it's not the same problem as #650

**Comment by baptiste0602** [comment]
It's OK now : 
![presse-papiers-1](https://cloud.githubusercontent.com/assets/11183826/12404040/a553f754-be38-11e5-8a09-61d72263c302.png)

**Comment by purplemarshmallow** [comment]
The problem is Banjo is not visible inside the bubble

**Comment by gonetz** [comment]
Fixed
