### ISSUE TITLE
Star Wars - Rogue Squadron: implementation of Lemmy HLE code?

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#653]
As it has a very partial support, implementing partial HLE support from Lemmy code would be nice but of course not a priority

**Comment by purplemarshmallow** [comment]
Some info from Lemmy:
>Rogue Squadron uses a so called heightfield microcode. So it is able to interprete height fields on the co-processor. The only other game with the same mechanism (to my knowledge) would the other Star Wars game.

>I did some special work for Rogue Squadron (it is very unique) but didn't do any of the heightfield stuff. That's why you can see more than with other emus, but still I'd say it is unplayable.

**Comment by olivieryuyu** [comment]
Indeed. The only thing I wished to know is whether Factor 5 microcode are not actually modified Z-Sort Microcode microcode with a lot of parallelism between the RSP and the CPU.

**Comment by olivieryuyu** [comment]
Looking into the ucode. 0xBD commands (which Lemmy supposes to be for the height fields) is indeed using the vector unit of the RSP to do calculations.

This commmand is really long: 288 lines of asm!!!! I do attach it for those who are interested.

[BD.xlsx](https://github.com/gonetz/GLideN64/files/836399/BD.xlsx)

The length of "immediate commands" is not 64 bits but 160 bytes. For instance that would be what you would get in the display list:

![image](https://cloud.githubusercontent.com/assets/8987490/23830495/176caddc-070c-11e7-936f-d447ce31c6cd.png)

I already figured out few things but those vector calculations will be a headache to figure out :/

**Comment by olivieryuyu** [comment]
So going on working on this command. 

The output for this command is maximum 10 words of 32 bits to the RDP.

Here the command:

![image](https://cloud.githubusercontent.com/assets/8987490/23925122/12bf7400-090e-11e7-856e-6b5fc8a39bd4.png)

Here the result in the RDP.

![image](https://cloud.githubusercontent.com/assets/8987490/23925162/3e03fbe0-090e-11e7-8dca-1db9c97bc9cd.png)

Few obvious things can be figure out:

![image](https://cloud.githubusercontent.com/assets/8987490/23925345/01226f8a-090f-11e7-9d34-c4807ba38147.png)

I have no clue what is supposed to do in the RDP

![image](https://cloud.githubusercontent.com/assets/8987490/23925374/238c5a2c-090f-11e7-954f-86d444088cf5.png)

Someone can have an idea (can it be triangles for instance?)?

**Comment by olivieryuyu** [comment]
As per code, the command identifier is either 0x24 or x025. The flag of the first half of the commands provide you this info.

Now I clearly wonder if actually what is generated is not simply a texture rectangle!!! 0x24 is for rdp texture rectangle and x025 for texture rectangle flip.

It would be so the famous heighmap that Lemmy mentionned.

![fbm](https://cloud.githubusercontent.com/assets/8987490/24012897/f6f518e2-0a7f-11e7-84a6-9669d0f687cc.png)

**Comment by olivieryuyu** [comment]
Small interesting link: http://satd.sk/pages/rs/

**Comment by olivieryuyu** [comment]
I believe that command 0x5, which Lemmy called JUMP3 and he did not analyzed, is the key to understand further the case, 0xBD seemingly leading to a mere textured rectangle for the time being. However 0x5 seems that this command can also generated triangles (aside TRI1 (0xBF) and TRI2 (0xB4).

For the time being, I understand that **if** the 3rd byte situated here 0x0505**00**01 is zero, then it retrieves data from the DRAM memory to DMEM to respectively 0x380 and 0x4E0. The DRAM address of such memory  is set at the 3rd and 4th 32 bits of the command. Each half of 5th 32 bits of the 0x5 command (when it is like this 0x0505**00**01) is used to set the SP DMA length in CP0.

![image](https://cloud.githubusercontent.com/assets/8987490/24332486/9f26cea6-1247-11e7-85cf-4347d02002ac.png)

Then **some** of those data is moved to another place in the DMEM memory ( 0xB70 and  0xCB4). The data retrieved are in a specific order. The RSP code uses a kind of loop to do so with parameters coming from some bytes of the first 32 bits of the command (05**05****00****01**). 

At the end here the results:

![image](https://cloud.githubusercontent.com/assets/8987490/24332599/a9513d1a-1249-11e7-81b2-755c5fa09640.png)

Anyone know what kind of value they could be: colors, textures? Is there something that looks like this in other ucodes?

I now need to check the other subtypes of 0x5 when it is not 00 here: 0x0505**00**01

**Comment by olivieryuyu** [comment]
2000 lines of asm just for the 0x5 command!!! It is really crazy. The entire Zelda ucode is 1500 asm line!

I investigated further the  0x0505**00**00. No great progress here yet.

I investigated the  0x0505**02**00. It is use less code to arrive to the RPD. I can confirm that this command generates triangles (without at all using the TRI command (B4/BF)B). I hope to be able to full understand how it works.

**Comment by gonetz** [comment]
You have taken very challenging task. I'm sure that regardless of the result with this ucode, you will became an expert in RSP work. I personally hope to see progress in Zelda MM point lighting someday. Good luck!

**Comment by olivieryuyu** [comment]
I become more and more familiar with RSP indeed but really far to understand even 50% of what I would need to decode ucodes.

I hope that Gilles will come back soon for Zelda MM. Otherwise I may have a look if I am getting stuck with Rogue Squadron.

I have an good idea now of what 0x05050200 does. However I am not sure if it is sufficient. Will send you info soon.

**Comment by olivieryuyu** [comment]
Summary of what 0x0505**02**00 does.

The command is not composed of two 32 bits words in the display list but 10 32 bits words as from instance:

![image](https://cloud.githubusercontent.com/assets/8987490/24604682/1640ca54-1866-11e7-8835-1f1338730595.png)

This is the general pattern of the code:

1. Check if the case is 02 and then go to related part of code.

2. From bytes of the 0x5 command, generates eight 32 bits words (eight 4 bytes words) stored in DMEM 0x280. The command G_VTX (0x04) uses this location in DMEM when retrieving data from memory. 
In that case the data are not retrieved from memory but build up from information contained in the 0x5 command.

3. Go to another part of the code for 02 through overlays.

4. The code goes to the part of the code of G_VTX. Without retrieving data from memory (the related code for that is skipped), G_VTX code uses the 8 32 bits words stored in DMEM at 0x280.  The 40 32 bits (40 4 bytes words) resulting are stored in DMEM at 0x670.

5. The code then uses the information contained in the 0x5 command and modify few parts of the 40 32 bits words obtained after 4. and located in DMEM 0x670.

6. Finally the 40 32 bits at DMEM 0x670 is sent to the code generating the RDP triangles. Depending on some parameters, the order of the data sent can be different. 
Indeed the 40 32 bits are somehow divided in 4, each one being 10 32 bits words long. The code sends two times information to the code generating the RDP triangles, with only 3 of the 10 32 bits words.

**Comment by olivieryuyu** [comment]
Information to 0x0505**02**00 sent!

I hope it will be enough!!!

This exercise allows me also to understand better what is going on potentially in the BD command.

**Comment by olivieryuyu** [comment]
0x05050000 also generates triangles but much much more. I believe 9 at once, a kind of TRI9!!

**Comment by gonetz** [comment]
Today I started crowdfunding campaign for HLE support of Star Wars - Rogue Squadron:
https://igg.me/at/swrs

I don't have accounts in FB or other social networks, so please spread the word :)

**Comment by loganmc10** [comment]
I loved this game so much as a kid, good luck you guys!

**Comment by olivieryuyu** [comment]
please spread the news !! thanks

**Comment by theboy181** [comment]
I would announce of discord.

Sent from my iPhone

On Jul 4, 2017, at 7:32 AM, Sergey Lipskiy <notifications@github.com<mailto:notifications@github.com>> wrote:


Today I started crowdfunding campaign for HLE support of Star Wars - Rogue Squadron:
https://igg.me/at/swrs

I don't have accounts in FB or other social networks, so please spread the word :)

**Comment by gonetz** [comment]
83% already. We are close. Thanks to everyone for support!

**Comment by theboy181** [comment]
I pm you on discord.

**Comment by weinerschnitzel** [comment]
The goal has been met. Nice!

**Comment by gonetz** [comment]
Honestly, I did not expect that it will met the goal so quickly. I had doubts that this task will be backed at all. I was wrong, that's good :) The task now gets top priority.

**Comment by theboy181** [comment]
HLE the microcode seems like an interesting topic..  I backed you because of the work you do not the the goal..  thanks again.

**Comment by gonetz** [comment]
Thanks to you for your support. It is important for me to know that my work is appreciated.

**Comment by olivieryuyu** [comment]
Just for informative purpose, it is interesting to note that SWRG ucode is vaguely based on the F3DEX. Factor5 did not completey wrote from scratch the ucode. 

Same applies for Battle of Naboo and Indiana Jones but this time it was based on F3DEX2. 

Of course the changes are dramatic so both ucodes are completely non compatible with their original ucodes.

Hence at the end no ucode was totally written from scratch by external parties, meaning outside Nintendo and SGI. From an historical point of view, it is quite an interesting fact :)

**Comment by olivieryuyu** [comment]
progress of the implementation are awesome :)

![gn0daxsqinroxjrdn4ny](https://user-images.githubusercontent.com/8987490/28502490-b56c0532-6ff3-11e7-9910-0f59ccfcd62c.png)

**Comment by theboy181** [comment]
@gonetz Question
1. What is the debug code you are using to show the terrain in the Indago post?
2. LLE is working for me but HLE has issues with the terrain in Alpha 2.7 zilmar spec. Was the above screenshot taken in HLE from Alpha2.7 build?

**Comment by theboy181** [comment]
@olivieryuyu is that screen shot taken with PJ64, and are you forcing HLE with the plugin per-game? I just found out the Rouge Squadron when using Zilmars RSP doesn't respond to the set global HLE option. forcing it HLE in per game options, it will do HLE, but there will be many gfx issues. 2.7 aplha looks no different than the first build to me.

**Comment by gonetz** [comment]
I use mupen64plus to work with RS. Screen shot taken with mupen64plus build. Debug mode enabled by some flags in code, so you need to rebuild the project to get it.

**Comment by gonetz** [comment]
I updated Indiegogo campaign with new video and screen shots:
https://igg.me/at/swrs

**Comment by gonetz** [comment]
https://youtu.be/uOorz-d2D6U

**Comment by Frank-74** [comment]
Looks good.  Indy and Naboo are also similar ucodes I think.  Looks like they'll be the last games to be HLE'd, unless they're very similar to SW RS.

**Comment by loganmc10** [comment]
@gonetz are the sources included in the alphas up to date? I'm trying to test this on Linux and I get:

```
gSP.cpp:1458:9: error: ‘struct SPVertex’ has no member named ‘st_scaled’
     vtx.st_scaled = 0;
```
If updating the sources is too much of a hassle or you aren't ready to do that yet don't worry about it.

**Comment by theboy181** [comment]
Not sure but explosions seem to be missing. 
https://www.youtube.com/watch?v=JOBegdjT60g

**Comment by gonetz** [comment]
I put recent sources, but probably some file was not updated.

Command for explosions is not implemented yet. It is also very large and complex.

**Comment by AmbientMalice** [comment]
You're doing great work, guys.

>Looks good. Indy and Naboo are also similar ucodes I think. Looks like they'll be the last games to be HLE'd, unless they're very similar to SW RS.

I'd be absolutely chuffed if Naboo/Indy were made easier to HLE by the work done here.

**Comment by theboy181** [comment]
Mario no Photopi seems to be working in HLE with Sephomore on.

**Comment by gonetz** [comment]
@loganmc10 
> gSP.cpp:1458:9: error: ‘struct SPVertex’ has no member named ‘st_scaled’
     vtx.st_scaled = 0;

I see, what happened. I removed st_scaled field, but forgot to correct __VEC4_OPT code since I don't use it for windows build. Just remove __VEC4_OPT code from gSPSWVertex, it need to be rewritten.

**Comment by olivieryuyu** [comment]
In order to do a good testing of the game, here the cheat code for having all levels: MEAKMAN

**Comment by theboy181** [comment]
how about forcing the game to Run Like the PC @ 60FPS.. ;)

Star Wars - Rouge Squadron (U) (V1.1)
60 FPS Hack

8002E4E8 0000

Note: Needs OC X2  to maintain 60FPS

**Comment by olivieryuyu** [comment]
> 
Looks good. Indy and Naboo are also similar ucodes I think. Looks like they'll be the last games to be HLE'd, unless they're very similar to SW RS.
> 

It will most likely WDC & Stunt Racer. 

Indy has some code similar to SWRG but some stuff are completely new.

**Comment by AmbientMalice** [comment]
>Indy has some code similar to SWRG but some stuff are completely new.

I assume Battle for Naboo is same as Indy, or at least similar?

**Comment by olivieryuyu** [comment]
similar indeed

**Comment by theboy181** [comment]
Good work.. @olivieryuyu did you help gonetz with this? Whats next? will it have to be behind a pay wall?

**Comment by olivieryuyu** [comment]
@theboy181 

I did a huge work on SWRG.

What's next is what I want to do, N64 emulation being a hobby which I do for free. 

Also note that supporting developers as Gonetz is nice contribution to the hard work they do.

**Comment by gonetz** [comment]
@olivieryuyu Jason aka theboy181 is one of most generous backers of the project. Hi also one of most generous backers of Rogue Squadron campaign. I wish to have more of such supporters :)

@theboy181 as for olivieryuyu, N64 emulation is a hobby for me which I do for free. We would do that work on Rogue Squadron regardless of the campaign result. If campaign would fall, that task would completed later and not so fast. Campaign is a motivation bonus, not a payment for our work.
We are planning to continue our HLE projects. There is no pay wall, if I correctly understand what it means.

**Comment by gonetz** [comment]
> I did a huge work on SWRG.

That's true. Started at April, finished this week. The task is not only huge, but also extremely difficult. I still can't believe that we done with it.

**Comment by loganmc10** [comment]
@gonetz F3DSWRS.cpp needs ```#include <cmath>``` in Linux for ```fabs()``` and ```modf()```

After including it, I get:
```
/home/loganmc10/mupen64plus-GLideN64/GLideN64/src/F3DSWRS.cpp: In function ‘void F3DSWRS_TexrectGen(u32, u32)’:
/home/loganmc10/mupen64plus-GLideN64/GLideN64/src/F3DSWRS.cpp:1281:68: error: cannot convert ‘float*’ to ‘double*’ for argument ‘2’ to ‘double modf(double, double*)’
  const f32 frac_x_f = fabs(modf(gSP.matrix.combined[0][0], &intpart));
                                                                    ^
/home/loganmc10/mupen64plus-GLideN64/GLideN64/src/F3DSWRS.cpp:1283:68: error: cannot convert ‘float*’ to ‘double*’ for argument ‘2’ to ‘double modf(double, double*)’
  const f32 frac_y_f = fabs(modf(gSP.matrix.combined[0][1], &intpart));
```

**Comment by loganmc10** [comment]
Just changing intpart to ```f64``` solved that problem. It looks really great you guys, runs at full speed in full screen on my laptop with Intel graphics (Linux)!

I hope the RetroPie form moderators are ready for the onslaught of people complaining that it doesn't run at full speed on a Raspberry Pi lol

**Comment by loganmc10** [comment]
One small issue I noticed, in the mission select screen, as well as the "Mission Accomplished!" screen after a mission, parts of the screen "flicker" with weird colours, example below:

![rogue_squadron-006](https://user-images.githubusercontent.com/848146/28998361-185fbcb4-79e6-11e7-94f6-2b9fdeeab6c2.png)

**Comment by LegendOfDragoon** [comment]
@loganmc10 that might be a emulator core issue. At least on older versions of Mupen64plus, I had some weird flickering issue in that part of the game, although it wasn't green.

**Comment by loganmc10** [comment]
@LegendOfDragoon yeah it's not always green, that's just the frame I happened to capture. It looks like you're right, CountPerOp=1 fixes the flickering, so it was a core issue.

**Comment by LegendOfDragoon** [comment]
Interesting, that reminds me of when I used overclocking in 1964 to get rid of the flickering in that menu. Can't remember whether OCing completely removed it, or if it just reduced it. I'm thinking it might be due to inaccurate floating point code in the CPU core.

Is mupen64plus's VI refresh rate at 2200 by default or something? Odd how merely setting CountPerOp to 1, would do the trick.

**Comment by loganmc10** [comment]
No it's 1500 by default. All the Factor 5 games have issues with CountPerOp=2 in mupen64plus. Indiana Jones and Naboo also have flickering. The background music doesn't work in Episode I racer unless CountPerOp=1. This is the same in Project64, I'm not sure about the flickering though

**Comment by theboy181** [comment]
@gonetz and @olivieryuyu I meant no disrespect. I hope to see more improvements in compatibility with GLideN64, I just wondered if there would be another campaign for the rest of the games that needed HLE work. 

I hope that you will take some time to polish what we have when you have achieved your personal goals. things like the FPS counter not being accurate, and the SSB64 bugged textures, and CRC issues with HD texture support still bother me and are on my wish list. 

Regressions with Bloom are on that list too, but lower priority.

**Comment by gonetz** [comment]
@theboy181 Your wish list is sub-list of mine to-do plans :) The problem is where to get time for all tasks. I spent all my time during last month to complete RS. Huge task requires maximal efforts, I had little time for anything else. I'll be on vacation from next week until September. So, the plans postponed.

Regarding another campaign for HLE projects: it is hardly. Indiegogo has minimal campaign goal $500. I can't expect that each campaign can take so much. Indy probably can - many people wish it be HLEed.
I'm planning to open project on Patreon. I already started it once in hope that it can collect enough funds for me to work on the project full time. It did not. But Patreon is good enough to get small monthly support.

**Comment by theboy181** [comment]
@gonetz You deserve vacation, but I am confused about your Indiegog timeline. If you were planing on 3 month campaign, and you had vacation planed this may look a little confusing to your supporters.

Anyway, I have this to share with you for (if) you plan on making Naboo HLE.

Star Wars Episode 1 - Battle for Naboo (U)
60 FPS Hack

81080296 0001

Note: Needs OC x2

**Comment by gonetz** [comment]
The Indiegog timeline was planned in concordance with task difficulty, our experience and my vacation. Three month for task completion looked reasonable. Since campaign reached the goal within few days from start, the work started immediately. We worked hard and fast and completed the task to the end of the campaign. We kept our promises, so I see no reason for supporters to be confused.

**Comment by fzurita** [comment]
To me it sounds like @gonetz of planning vacation after seriously exhausting his brain power :)

**Comment by gonetz** [comment]
@fzurita You pretty close :) I have plenty of hard tasks on my work, plus hard tasks with my hobby. It really makes me feel exhausted.

**Comment by AmbientMalice** [comment]
When will the Rogue Squadron code be merged into the main branch?

**Comment by fzurita** [comment]
@gonetz should I wait until you release the source code before doing a mobile release?

**Comment by gonetz** [comment]
I planned to spend a week or two on beta testing. I'm waiting for bug reports from backers. No reports yet, but the beta was sent just yesterday. I also need to clean up few things in code. The code will be merged to master either next week, if no major issue will be found, or when I will return from my vacation. I suggest to make no public builds from this code until it not merged.

**Comment by Sarkie** [comment]
Hope you had a great vacation, looking forward to the write up!

**Comment by Aquatakat** [comment]
Have a great vacation @gonetz, you've earned it.

**Comment by loganmc10** [comment]
In "The Search for the Nonnah" I noticed some artifacts in the water. It was hard to get a screenshot, but hopefully the screenshot below helps:

![rogue_squadron-019](https://user-images.githubusercontent.com/848146/29012904-25012e8c-7afc-11e7-8407-c8640aeea7d9.png)

I see that kind of thing all over the water. I don't know what it looked like on a real N64, but I assume that isn't right.

In "Defection at Corellia", it got a little slow when the city was in view (2X native res), but I'm testing this on integrated graphics, so it's probably better on a more powerful GPU, doesn't bode well for mobile GPU's though.

**Comment by loganmc10** [comment]
lol I just realized I was playing in LLE. You can disregard that last post... The water looks good and it's not slow....

**Comment by robertybob** [comment]
Yay looking forward to Patreon :D

**Comment by theboy181** [comment]
There seems to be regressions with Zelda, and Paper Mario with this @gonetz

**Comment by gonetz** [comment]
Ops, forgot to update shader cache version again. Thanks!

**Comment by olivieryuyu** [comment]
and voila, the code is released!!! 

I will have the great pleasure to close this ticket which I opened years ago :)
