### ISSUE TITLE
Twinrova Boss Battle effects display wrong...

### ISSUE THREAD

**Issue by OldGnashburg** [gonetz/GLideN64#654]
I just dragged and dropped the photos, however I compared the GLideN64 screenshots to Angrylions Per-Pixel RDP Plugin and it confirmed my suspicion, the effects are off. The GLideN64 screenshots are the higher quality, non-pixelated screenshots. Sorry for the bad image quality

![gliden64_the_legend_of_zelda_000](https://cloud.githubusercontent.com/assets/11412147/9234273/145f1e74-40f5-11e5-88df-14a0628b8d1a.jpg)
![gliden64_the_legend_of_zelda_001](https://cloud.githubusercontent.com/assets/11412147/9234274/1461621a-40f5-11e5-8ae4-0c8279306dde.jpg)
![gliden64_the_legend_of_zelda_002](https://cloud.githubusercontent.com/assets/11412147/9234269/144329e4-40f5-11e5-99b0-111838588d3c.jpg)
![gliden64_the_legend_of_zelda_003](https://cloud.githubusercontent.com/assets/11412147/9234270/144c29a4-40f5-11e5-9a20-5dccc19cc21f.jpg)
![gliden64_the_legend_of_zelda_004](https://cloud.githubusercontent.com/assets/11412147/9234271/1453aaa8-40f5-11e5-8181-cdc5f1277964.jpg)
![gliden64_the_legend_of_zelda_005](https://cloud.githubusercontent.com/assets/11412147/9234272/1456dd7c-40f5-11e5-8bf0-bf251083dffd.jpg)
![gliden64_the_legend_of_zelda_006](https://cloud.githubusercontent.com/assets/11412147/9234275/1462ddde-40f5-11e5-9c8f-5822c31d7d8c.jpg)

**Comment by olivieryuyu** [comment]
a savestate please? :)

**Comment by purplemarshmallow** [comment]
savestate: https://drive.google.com/file/d/0B7Y6r4SpC_QQQmRnTEczc3dTRk0/view?usp=sharing
fire effects are missing, likely same problem as #646 
everything else seems to be ok
![gliden64_the_legend_of_zelda_008](https://cloud.githubusercontent.com/assets/7283660/9281740/8e3d54e4-42c7-11e5-955e-2718ed62095c.jpg)
![czle0000](https://cloud.githubusercontent.com/assets/7283660/9281741/90690f06-42c7-11e5-9c2b-da9fe77e5de9.jpg)

**Comment by purplemarshmallow** [comment]
This screenshot is interesting, fire effects are drawn above everything else
Only angrylion's plugin emulates it, would be nice to know how they are drawn
Maybe something related with #226 ?
![1](https://cloud.githubusercontent.com/assets/7283660/9288082/546f808e-4335-11e5-92d9-f1729100a9c6.jpg)

**Comment by OldGnashburg** [comment]
I'm sorry, I haven't been online for a little while. I was using some really crappy AMD computer, I was surprised that I was able to run GLideN64.

**Comment by purplemarshmallow** [comment]
now fixed!

**Comment by gonetz** [comment]
I guess, this is result of color clamp/wrap, implemented in #661
#646 fix also can be result of it.

**Comment by olivieryuyu** [comment]
I guess it can be closed

**Comment by gonetz** [comment]
Closed
