### ISSUE TITLE
Extreme-G XG2 requires depth compare for some effects

### ISSUE THREAD

**Issue by ghost** [gonetz/GLideN64#655]
However depth compare has some bugs as well

Wrong (missing ground reflections)
![gliden64_extreme_g_2_001](https://cloud.githubusercontent.com/assets/13789606/9265272/5395cd8a-4231-11e5-8abe-47913aab9743.png)
Correct (angrylion's RDP)
![ng2p0000](https://cloud.githubusercontent.com/assets/13789606/9265279/646532d6-4231-11e5-97a6-a0dfbe446c87.png)

Wrong (I don't know what to say :) )
![gliden64_extreme_g_2_002](https://cloud.githubusercontent.com/assets/13789606/9265285/74b55e40-4231-11e5-8f26-c0a2dba3a20f.png)
Correct (angrylion's RDP)
![ng2p0001](https://cloud.githubusercontent.com/assets/13789606/9265290/7ce0b83a-4231-11e5-9895-4ab59abfb466.png)

Wrong (when the ring rotates the background should be some bluish violet clouds)
![gliden64_extreme_g_2_000](https://cloud.githubusercontent.com/assets/13789606/9265392/b8eb221a-4232-11e5-99f0-1996efef3a92.png)
Correct (angrylion's RDP)
![ng2p0002](https://cloud.githubusercontent.com/assets/13789606/9265395/c1f5f3d0-4232-11e5-9e25-2f94537264fa.png)

Would you like me to open individual issues for the bugs ?

**Comment by gonetz** [comment]
As I see, the problems with N64 depth compare in Extreme-G XG2 have been fixed so I enabled it in custom ini.
