### ISSUE TITLE
Extreme-G polygon flickering on the ground reflection

### ISSUE THREAD

**Issue by ghost** [gonetz/GLideN64#656]
This is hard to catch on a screenshot however angrylion's RDP renders the reflection correct without the polygon flickering

Wrong
![gliden64_extreme_g_000](https://cloud.githubusercontent.com/assets/13789606/9267278/7a9666c2-424c-11e5-8674-354bac316ec2.png)
Correct (angrylion's RDP)
![negp0000](https://cloud.githubusercontent.com/assets/13789606/9267287/978e286e-424c-11e5-9411-fcff86c651d7.png)

**Comment by oddMLan** [comment]
![GLideN64_extremeg_000](https://user-images.githubusercontent.com/7278372/68208438-5a7b9c00-ff8e-11e9-8b9d-53926dd0a07d.png)
No polygon flickering here, but maybe it's due to N64-style Depth compare? My GPU doesn't support it, so I can't test it.

**Comment by gonetz** [comment]
HLE mode with N64-style depth compare looks the same as with angrylion's RDP, no flickering.
LLE has depth issues - reflection is clipped.
Original issue is fixed and can be closed.
