### ISSUE TITLE
Extreme-G bike selection fade transition effect broken

### ISSUE THREAD

**Issue by Cetacea3691** [gonetz/GLideN64#657]
Wrong
![gliden64_extreme_g_001](https://cloud.githubusercontent.com/assets/13789606/9267452/9ab2ffc6-424f-11e5-9f86-0d704d927ad6.png)
Correct (angrylion's RDP)
![negp0001](https://cloud.githubusercontent.com/assets/13789606/9267455/a77903cc-424f-11e5-9c9f-2a800268a07f.png)

**Comment by olivieryuyu** [comment]
fixed

![sans titre](https://user-images.githubusercontent.com/8987490/30780196-d61bed90-a105-11e7-9fe9-417024a4e214.jpg)

please close

**Comment by Enker** [comment]
When switching between bikes, they are showing up black for me. Happens with HLE and LLE.

Tested with Intel HD Graphics
