### ISSUE TITLE
Bomberman 64 - The Second Attack! strange blending or texture issue on some objects

### ISSUE THREAD

**Issue by Cetacea3691** [gonetz/GLideN64#658]
Wrong (all objects which are invisible or transparent should be normally textured and visible)
![gliden64_bomberman64u2_000](https://cloud.githubusercontent.com/assets/13789606/9267592/029e19ac-4252-11e5-9346-81ff7279e0e1.png)
![gliden64_bomberman64u2_001](https://cloud.githubusercontent.com/assets/13789606/9267594/074ff970-4252-11e5-8465-be44fa31bfeb.png)
Correct (angrylion's RDP)
![nbve0001](https://cloud.githubusercontent.com/assets/13789606/9267606/16f2a77e-4252-11e5-828f-bce53c75e373.png)

**Comment by olivieryuyu** [comment]
savestate please?

**Comment by Cetacea3691** [comment]
Which emulator and version would you prefer for the savestate ?

**Comment by olivieryuyu** [comment]
PJ64

**Comment by Cetacea3691** [comment]
Project64 2.2

https://drive.google.com/file/d/0Bygxj1zIGEscaVc0SFB2MDRLcUU/view?usp=sharing

**Comment by purplemarshmallow** [comment]
There are two different bugs here: The squares in the box and the missing statues
squares: That's a HLE issue, correct in LLE mode
missing statues: very strange, I tested different plugins
correct with: Rice Video, z64gl, Jabo's D3D
wrong with: glN64, Glide64, GLideN64, Lemmy's gfx plugin

**Comment by olivieryuyu** [comment]
this game is known to have specific blender modes. That may explain the missing statues.

**Comment by Cetacea3691** [comment]
Little update

PJ64 2.2 savestate:https://drive.google.com/file/d/0Bygxj1zIGEscUHpJUGc2Y0xsVDg/view?usp=sharing
Wrong
![gliden64_bomberman64u2_000](https://cloud.githubusercontent.com/assets/13789606/9427109/fe419648-496a-11e5-859a-daeaf2255e41.png)
Correct (angrylion's RDP)
![nbve0000](https://cloud.githubusercontent.com/assets/13789606/9427111/0542480c-496b-11e5-8fae-6ad16cd05fbb.png)

**Comment by AmbientMalice** [comment]
Can anyone confirm if this is fixed now?

**Comment by gonetz** [comment]
Fixed now
