### ISSUE TITLE
[Mupen64Plus] Config File for certain Games

### ISSUE THREAD

**Issue by Papermanzero** [gonetz/GLideN64#660]
Currently GlideN64 can only work with global settings, if it is used as plugin in Mupen64Plus.
Compared to Project64 no game specific settings can be created (custom ini file).
A config file in which game specific settings can be stored would be convenient (gliden64.custom.ini), due to the amount of different settings which must be enabled and set to run certain games.

Glide64mk2 has already such a feature:
https://github.com/mupen64plus/mupen64plus-video-glide64mk2/blob/15f1f888422e248c6f640e587dffd12eeb48764b/src/Glide64/Ini.cpp

**Comment by rockaddicted** [comment]
Hi, is there more informations about how to use the `GLideN64.custom.ini` file when GLideN64 is used as a Mupen64Plus plugin ?

**Comment by purplemarshmallow** [comment]
You can't use GLideN64.custom.ini with mupen64plus. Qt reads the file and the mupen64plus version does not link to Qt. Ini file reading for mupen64plus still needs to be implemented

**Comment by rockaddicted** [comment]
Ok thanks for the answer. The feature will be great for our RPi =)

**Comment by Papermanzero** [comment]
Same here. I am not using GlideN64 due to this missing feature. 
But I am optimistic that it will be implemented. ^^

**Comment by orbea** [comment]
These issues are related.

https://github.com/mupen64plus/mupen64plus-core/issues/217
https://github.com/gonetz/GLideN64/issues/1271

**Comment by tony971** [comment]
GlupeN64 has this feature.

**Comment by Papermanzero** [comment]
Can be closed.
