### ISSUE TITLE
Missing black borders in some games cause flickering line issues and more

### ISSUE THREAD

**Issue by ghost** [gonetz/GLideN64#666]
Here are a few examples: Diddy Kong Racing (E), Yoshi's Story (E), Extreme-G XG2 (E), Blast Corps (E), Mario Kart 64 (E).

Wrong
![gliden64_diddy_kong_racing_000](https://cloud.githubusercontent.com/assets/13789606/9295145/0ddbb1a8-4464-11e5-935a-1ead31c0b719.png)
Correct (angrylion's RDP)
![ndyp0000](https://cloud.githubusercontent.com/assets/13789606/9295147/1b051d24-4464-11e5-9187-083b592c05c6.png)

Wrong
![gliden64_yoshi_story_000](https://cloud.githubusercontent.com/assets/13789606/9295148/24f7f608-4464-11e5-8377-d039ee6409ee.png)
Correct (angrylion's RDP)
![nysp0001](https://cloud.githubusercontent.com/assets/13789606/9295157/3ec1e968-4464-11e5-8c02-50db066fa0c9.png)

Wrong
![gliden64_extreme_g_2_000](https://cloud.githubusercontent.com/assets/13789606/9295158/4c54dd9c-4464-11e5-8d3f-68fa009e0f11.png)
Correct (angrylion's RDP)
![ng2p0000](https://cloud.githubusercontent.com/assets/13789606/9295159/54ee6478-4464-11e5-91d8-045d0025fb71.png)

Wrong (I know there is another bug here but I'm concerned with the flickering line on the right side :))
![gliden64_blast_corps_000](https://cloud.githubusercontent.com/assets/13789606/9295161/61d18abc-4464-11e5-8953-6750fe2dca40.png)
Correct (angrylion's RDP)
![nbcp0000](https://cloud.githubusercontent.com/assets/13789606/9295162/679f88d6-4464-11e5-8f65-5e3112832cd2.png)

Wrong
![gliden64_mariokart64_000](https://cloud.githubusercontent.com/assets/13789606/9295168/aad5adba-4464-11e5-9a2f-a38b27affe2a.png)
Correct (angrylion's RDP)
![nktp0000](https://cloud.githubusercontent.com/assets/13789606/9295171/b1782e22-4464-11e5-9a79-666c683b0257.png)

and more: Banjo-Kazooie (E), Bomberman 64 - The Second Attack! (U), Legend of Zelda, The - Majora's Mask (E), Super Mario 64 (E).

also the issue gets worse with increasing resolution.

**Comment by olivieryuyu** [comment]
VI emulation is not accurate enough. Overscan is as well not emulated.

**Comment by oddMLan** [comment]
![GLideN64_Diddy_Kong_Racing_000](https://user-images.githubusercontent.com/7278372/68208706-fefdde00-ff8e-11e9-9aa3-62fc0b924792.png)
in DKR the black borders match Angrylion. I guess this was fixed with #1981

**Comment by gonetz** [comment]
Let's close it then.
