### ISSUE TITLE
Scaling issues with adreno android devices

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#667]
I have two devices with adreno GPUs, the Nexus 7 2013 and the Xperia Z Ultra. Both of them have scaling issues. The image looks like below when frame buffer emulation is enabled. The image looks normal was frame buffer emulation is disabled. To me it looks like the image is being zoomed to take the full screen, but it's being cropped to 4:3.

![screenshot_2015-08-16-23-08-38](https://cloud.githubusercontent.com/assets/11581687/9297366/6cdb1b5a-446c-11e5-95c0-f927cf30e80d.png)

**Comment by gonetz** [comment]
I have the same issue with my Galaxy Note 3. glBlitFramebuffer works incorrect on this GPU. It was even worse with older drivers version. The picture was upside-down. If you have time, you may do experiments with FrameBufferList::renderBuffer function and find, is it possible to make glBlitFramebuffer work correct on this GPU.

**Comment by fzurita** [comment]
Yeah, I was trying to determine where this was happening to try to find a fix. That helps a lot. It's a shame that different GPU's can't produce the same output.

**Comment by fzurita** [comment]
I did some testing. I was able to get this to work correctly as long as the srcX0 is non-zero. So just adding 1 to srcX0 makes it work correctly. I don't know about srcY0 since it's not normally zero. I guess it wouldn't hurt to add 1 to that as well.

**Comment by purplemarshmallow** [comment]
Looks like you have specific information about a bug in adreno drivers. Maybe it should be posted at their developer forum
https://developer.qualcomm.com/forums/software/adreno-gpu-sdk

**Comment by fzurita** [comment]
I'm sure these bugs have been reported already. The Dolphin team has had issues with specifically glBlitFramebuffer on Adreno devices as well.

**Comment by gonetz** [comment]
>I did some testing. I was able to get this to work correctly as long as the srcX0 is non-zero.

Does not help to me. Please provide code fragment with your changes.

**Comment by fzurita** [comment]
I added one to the first argument of glBlitFramebuffer. I suspect that the adreno driver doesn't like 0 for the first argument.

Line 713:

```
	glBlitFramebuffer(
		srcCoord[0] + 1, srcCoord[1], srcCoord[2], srcCoord[3],
		dstCoord[0], dstCoord[1], dstCoord[2], dstCoord[3],
		GL_COLOR_BUFFER_BIT, filter
	);
```

Line 728:
```
			glBlitFramebuffer(
				1, (GLint)(srcY0*srcScaleY), ogl.getWidth(), min((GLint)(srcY1*srcScaleY), (GLint)pBuffer->m_pTexture->realHeight),
				hOffset, vOffset + (GLint)(dstY0*dstScaleY), hOffset + ogl.getWidth(), vOffset + (GLint)(dstY1*dstScaleY),
				GL_COLOR_BUFFER_BIT, filter
			);
```

There are a few more places where glBlitFramebuffer is used, but I didn't adjust those. I suspect that those are affected as well. At the very least, those 2 above changes make Super Mario 64 render correctly when FBE is enabled.

**Comment by fzurita** [comment]
I think to fix this, we are going to need GPU specific code paths....

**Comment by fzurita** [comment]
Hmm... Adding 1 to the 5th argument of glBlitFramebuffer has the same effect. It also fixes the issue.

**Comment by gonetz** [comment]
Your fix does not help to me :(
May be I missed something important. Please give me apk file with your fix.

**Comment by fzurita** [comment]
https://drive.google.com/file/d/0B57Ioy26LWegZnV0OVZxaEhad0U/view?usp=docslist_api

There you go, that one is working for me.

**Comment by gonetz** [comment]
Your build works for me. Cool! Problem with shading is still there, but issue with screen size is fixed.
Please give me your version of FrameBuffer.cpp
I want to make working build myself.

**Comment by fzurita** [comment]
Yeah, sure, once I get back to my computer at home I'll post it. Around 11 hours from now....

**Comment by gonetz** [comment]
Ok, thanks in advance.

**Comment by fzurita** [comment]
https://drive.google.com/file/d/0B57Ioy26LWegaGdCVnVSREl1YnM/view?usp=sharing

This works fine in my device. The above snippet I posted works too.I believe the apk is based off the one in the link.

**Comment by gonetz** [comment]
Yes, dstCoord[0]+1 fixes the issue. I suggest to do a workaround for Adreno GPU:
add "OpenGL renderer" field, and if it corresponds to Adreno, do that trick.

**Comment by gonetz** [comment]
https://github.com/gonetz/GLideN64/commit/5eddea5baf284b59aa8a2beb00676e23b58b13e6
