### ISSUE TITLE
depth buffer emulation in LLE

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#671]
In Zelda OOT if you switch fullscreen/window and then close the subscreen you can see the depth image. Here are 3 screenshots.
screenshot 1: depth values are taken from angrylion's plugin and loaded using savestates
screenshot 2: depth values calculated by GLideN64 in HLE
screenshot 3: depth values calculated by GLideN64 in LLE
In HLE depth values are a bit inaccurate, some games require near perfect depth buffer emulation
In LLE depth values are completely wrong
![gliden64_the_legend_of_zelda_013 angrylion](https://cloud.githubusercontent.com/assets/7283660/9313156/9e43d24e-4521-11e5-851c-a5e776fb033b.jpg)
![gliden64_the_legend_of_zelda_013hle](https://cloud.githubusercontent.com/assets/7283660/9313159/a4ad610e-4521-11e5-9062-1b04591356a8.jpg)
![gliden64_the_legend_of_zelda_014lle](https://cloud.githubusercontent.com/assets/7283660/9313160/a8ba304c-4521-11e5-97b0-9008f652c6d6.jpg)

**Comment by olivieryuyu** [comment]
Accurate depth values may be needed for #550. At least it is one of the hypothesis about this game.

**Comment by purplemarshmallow** [comment]
Pokemon Snap needs accurate depth values
With inaccurate values Professor Oak won't recognise the pictures

**Comment by olivieryuyu** [comment]
![sdfdsf](https://cloud.githubusercontent.com/assets/8987490/9323120/3202bc2e-457d-11e5-95a0-ddf30d6bd094.jpg)

yes Pokemon Snap has indeed an issue in this regards

**Comment by gonetz** [comment]
Fixed
