### ISSUE TITLE
(Regression.) Depth Buffer Issues.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#673]
Perfect Dark and Vigilante 8 and likely other games now have coronas and lens flares showing through walls. Likely caused by https://github.com/gonetz/GLideN64/pull/613

**Comment by purplemarshmallow** [comment]
Same with the sun in 1080 Snowboarding and it's caused by https://github.com/gonetz/GLideN64/commit/77f342fc630a20b6e3724f4dda5ea4bb02cc4bf4. A possible solution would be to first detect if the plugin runs in HLE or LLE and then revert this for HLE only. That's a bit ugly. Maybe there's a better solution that fixes this and #614

**Comment by AmbientMalice** [comment]
Indeed. It would be ideal to have accurate depth without the terrible performance overheads.

**Comment by AmbientMalice** [comment]
Unfortunately, if I revert https://github.com/gonetz/GLideN64/commit/77f342fc630a20b6e3724f4dda5ea4bb02cc4bf4 the coronas still flicker through the walls intermittently, particularly when moving sideways.

**Comment by purplemarshmallow** [comment]
Maybe #609 is related

**Comment by OldGnashburg** [comment]
The corona's on torches appear through walls on OOT and MM. This happens on the Public Release 1.2

**Comment by purplemarshmallow** [comment]
Does not happen for me, looks like depth buffer emulation does not work for you. Can you give more details (video card)?

**Comment by AmbientMalice** [comment]
This issue seems to be cured for Perfect Dark at least by https://github.com/gonetz/GLideN64/commit/444545baea0069bde8d9b9e42ec9ffc920373a62

**Comment by gonetz** [comment]
https://github.com/gonetz/GLideN64/commit/c6988bb9634e4dec14ff25811a97e6fdfa2342d8

**Comment by olivieryuyu** [comment]
short question

depth buffer is related to G_ZBUFFER?

**Comment by gonetz** [comment]
G_ZBUFFER enables depth buffer.
otherMode.depthMode set depth compare mode.
gDP.otherMode.depthUpdate set depth buffer update on/off.

**Comment by olivieryuyu** [comment]
Hmm do you mean that G_ZBUFFER is only a flag?

**Comment by gonetz** [comment]
Yes, a bit in geometry_mode in case of HLE.
In LLE mode us of depth buffer depends on polygon command. For example, RDP_TriFill command does not use depth buffer, RDP_TriFillZ uses it.
