### ISSUE TITLE
Mario Tennis pause menu

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#675]
screenshot1:
copy color enabled, copy depth disabled
![gliden64_mariotennis_001](https://cloud.githubusercontent.com/assets/7283660/9364705/0216b876-46ae-11e5-9e73-a44726532090.jpg)
screenshot2:
copy color disabled copy depth enabled
![gliden64_mariotennis_003](https://cloud.githubusercontent.com/assets/7283660/9364730/1a8f039a-46ae-11e5-8b43-891acd9b24ec.jpg)
screenshot3:
copy color enabled copy depth enabled
![gliden64_mariotennis_004](https://cloud.githubusercontent.com/assets/7283660/9364798/652f0e0e-46ae-11e5-88b9-896903b3a757.jpg)
screenshot4:
copy color disabled copy depth disabled
![gliden64_mariotennis_002](https://cloud.githubusercontent.com/assets/7283660/9364815/7c196fb0-46ae-11e5-8af6-894c818f15cf.jpg)

**Comment by baptiste0602** [comment]
Fixed with default settings

**Comment by oddMLan** [comment]
I can no longer reproduce, it used to happen before, but not anymore.

**Comment by gonetz** [comment]
Ok, closed. Thanks for testing!

**Comment by oddMLan** [comment]
*Thanks for the bugfixes!* We've been having a lot of those lately :)

However, there is still one case of corruption... sort of.. only when Copy Depth buffer to RDRAM is enabled... seems like Replays overwrite part of the menu graphics, although the corruption is different than the shown in the screenshots.

![gliden64_mariotennis_000](https://cloud.githubusercontent.com/assets/7278372/15246978/e1473e5a-18c5-11e6-8fa5-19f592bcd3b1.png)
![gliden64_mariotennis_001](https://cloud.githubusercontent.com/assets/7278372/15246979/e148d918-18c5-11e6-9d88-840cf5002c1f.png)

But the issue mentioned here was that, after invoking the pause menu a couple of times (twice or thrice would be enough) random corruption like in the pictures of the OP would show, and changing settings would make it vary to some extent. It was bad.
