### ISSUE TITLE
Building GlideNUI.dll required with MSVS 2015. Instructions needed.

### ISSUE THREAD

**Issue by tony971** [gonetz/GLideN64#676]
http://pastebin.com/m1TXqLUi

Trying to build the release dll for project64

**Comment by purplemarshmallow** [comment]
Are you building "release_dll" configuration? "release_dll" builds GLideNHQ as a seperate dll. This is currently broken. Look at https://github.com/gonetz/GLideN64/wiki/Build-From-Source-(Windows)

**Comment by tony971** [comment]
Okay, I tried building exactly as that page instructed and this is the new output: http://pastebin.com/p5aQB5az

**Comment by tony971** [comment]
Basically ft2build.h is missing.

**Comment by purplemarshmallow** [comment]
>1.1>------ Build started: Project: libGLideNHQ, Configuration: Release_dll Win32 ------

You are building "Release_dll" configuration, you have to build "Release" configuration

**Comment by purplemarshmallow** [comment]
Also your freetype folder is in the wrong directory
It has to be in the same directory where you cloned GLideN64, not in the GLideN64 directory
In your case the freetype folder must be in the Github folder

**Comment by tony971** [comment]
Well.. that was dumb of me. Everything's in place and it's trying to build but now I have 743 actual errors from the process. https://gist.github.com/anonymous/9ab1f943a211e55a8ed7

**Comment by purplemarshmallow** [comment]
Looks like you need to build GLideNUI using Visual Studio 2015. Unfortunately there are no instructions for that

**Comment by gonetz** [comment]
Current UI lib:
https://drive.google.com/file/d/0B0YqMPjGo3B2Y1lfVi1yOENBV3M/view?usp=sharing

Instructions will be later

**Comment by FuzzyQuills** [comment]
Dude, this might be a month old, but I was literally pulling my hair out over trying to build Qt! Mind if I use that lib?

**Comment by tony971** [comment]
https://www.dropbox.com/s/ugd6iz8f9asgd4v/GLideNUI.lib?dl=0

**Comment by FuzzyQuills** [comment]
That's 100MB? Damn... Anyway, thanks for that! :)

**Comment by FuzzyQuills** [comment]
Ok, it's not compiling; I keep getting this:
Error	54	error LNK2038: mismatch detected for '_MSC_VER': value '1900' doesn't match value '1800' in Combiner.obj	%USERPROFILE%\Documents\GLideN64-master\GLideN64-master\projects\msvc12\GLideNUI.lib(qglobal.obj)	GLideN64

**Comment by oddMLan** [comment]
@gonetz could you provide the latest glidenui.lib?

**Comment by olivieryuyu** [comment]
https://github.com/gonetz/GLideN64/wiki/Build-From-Source-(Windows)

That is now on the wiki

@tony971 

can it be closed?
