### ISSUE TITLE
depth buffer emulation is slow

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#677]
The list of issues with depth buffer emulation is endless
#675 #673 #671 #650 #614 #609 #583 #570 #549 #547 #511 ...
Glide64 uses a different method to emulate depth (software depth buffer rendering), it's described here http://gliden64.blogspot.co.at/2014/07/depth-buffer-emulation.html
Software depth buffer rendering has two advantages:
-It's much faster, depth buffer emulation in GLideN64 is way too slow
-It's more accure. On real hardware there's no copying to RDRAM.
Glide64 does not have the problems listed above. Copy depth to RDRAM in GLideN64 always breaks if a game uses depth buffer in a special way unless you add some special fixes
Edit: Beetle Adventure racing seems to be the only game that benefits from the depth buffer emulation method in GLideN64

**Comment by AmbientMalice** [comment]
I'm curious whether the current depth buffer method would be able to layer Resident Evil 2's backgrounds correct. RE2 was basically the only N64 game that couldn't handle Framebuffer Objects and needed software depth buffer. Unfortunately, RE2 is plagued by other issues.

Also, there's the fact GLideN64's depth buffer is still broken in LLE. And the mystery of Pokemon Snap's camera detection.

**Comment by purplemarshmallow** [comment]
>Zelda Majora's Mask (lens of truth + snowflakes)

I was wrong here, it's a problem with the wrapper in Glide64, the wrapper does not fully support depth buffer copy.
>Also, when Lens of Truth is used, some objects outside of the lens can be cut. This is not a bug - depth buffer copy must be emulated to fully emulate Lens of Truth. It is currently supported only by 3dfx Voodoo 4/5 cards. 

Resident Evil 2 also needs depth buffer copy and GLideN64 already supports it so there should not be a problem. Camera detection in  Pokemon Snap is certainly color buffer related but maybe depth buffer also plays a role.

**Comment by twarnercool2** [comment]
"Pokemon snap" has been figure out for Dolphin.

https://dolphin-emu.org/blog/2015/06/01/dolphin-progress-report-may-2015/

**Comment by WizLizard** [comment]
To think an emulator emulating an emulator can get it right. It's very impressive to say the least.

**Comment by AmbientMalice** [comment]
>To think an emulator emulating an emulator can get it right. It's very impressive to say the least.
And depressing. We've had years to investigate the problems with N64 colour buffer and depth buffer emulation and most of the people with the skills have just ignored it.

**Comment by gonetz** [comment]
1. Simple software depth buffer rendering is **less** accurate, because alpha testing is not taken into account. Alpha testing is possible only if frame buffer also will be rendered in software.

2. Software rendering will require software culling and clipping, that is throw benefits of OpenGL to trash can. At the end we will get Glide64 with shaders.

**Comment by purplemarshmallow** [comment]
That's very unfortunate. However the current depth buffer emulation method tends to break if a game does something special with the depth buffer. Also it is very slow.
example: Pokemon Snap
>The photo has separate depth copies for the Pokemon and terrain and assembles them later for the final picture

GLideN64's depth buffer emulation method completely fails here #547 . I wonder if it's possible to emulate this using the current method

**Comment by purplemarshmallow** [comment]
I don't think anymore that implementing software depth buffer rendering is a good idea.
Here's what degasus thinks about depth buffer emulation:
>The point is that image access (so his framebuffer writes and reads) are unsynchronized. So it may happen (and in fact, it happens often), that a pixel of a second primitive is executed before the pixel of the first primitive. Even worse, the caches are not coherent, so to update the cache of the second pixel, the cache of the first pixel must be flushed. Just remember that a GPU doesn't use the same hardware for two pixels at the same position...

> I think gonetz's way to fix it was to call glMemoryBarrier between every *primitive*, but this slows down the execution by far more than just do all of this work on the CPU...

 >Oh, and you should look for a way to detect when the CPU is trying to access the memory range. Those read & writes can be transformed in callbacks which to all of this ugly copying work "live". 

>There is a very good way to emulate the depth buffer of the N64, but the hardware requirements are HUGE:
> Implement all of the framebuffer with images just as gonetz did it. But don't get the same wrong assumtion that you don't need any synchronization. But D3D12.1 requires a new feature called "raster order views", which means you're able to configure a part of the pixel shader to run "in primitive order". So it's an easy way to program it, and the power requirements also aren't as high, but you'll need a very recent GPU:

 >Intel: Starting with Haswell
 Nvidia: maxwell 200+ (Geforce 900)
 AMD: Not right now
 Mobiles: All but adreno iirc (in primitive order is basicly free on tiled renderer)

> For OpenGL, there is also an extension which provides the same feature: ARB_fragment_shader_interlock, or legacy: INTEL_fragment_shader_ordering, EXT_shader_framebuffer_fetch (OpenGL ES)

**Comment by gonetz** [comment]
degasus correctly described the issue with my "emulate N64 depth compare" option. It really suffers from lack of synchronization between writes to image texture. I tried to use all synchronization methods, which in theory may work on my graphics card. Non of them helped with the problem.

However, it is not related to our problem: How to provide depth buffer in RDRAM with correct data. We still have two solutions here: 
- software render.
- copy depth buffer from video card

**Comment by purplemarshmallow** [comment]
How accurate is depth buffer emulation on the video card? Can it handle special uses of depth buffer without hacks? Like Pokemon Snap:
>The photo has separate depth copies for the Pokemon and terrain and assembles them later for the final picture

Is the copying process the only problem with this solution? This can be improved with help from the emulator's side.

**Comment by gonetz** [comment]
>How accurate is depth buffer emulation on the video card? 

depth buffer emulation on the video card is imperfect, because it is hard to reproduce RDP work on video card. "Emulate N64 depth compare" is my attempt to fix that issue. Anyway, hardware depth buffer is generally more accurate than software one because pixels rejected by alpha test will not put to depth buffer. 

> Can it handle special uses of depth buffer without hacks? Like Pokemon Snap:

It depends on the moment when the game reads depth value. If the game uses depth buffer data after frame is complete, there should be no problem.

>Is the copying process the only problem with this solution? This can be improved with help from the emulator's side.

Yes. Copying process has two problems: performance and timing.

**Comment by purplemarshmallow** [comment]
On top of the problem with alpha test I noticed a bug in Glide64's software depth buffer rendering. Part of the depth buffer is simply not rendered. I think software clipping works incorrect. Implementing software depth buffer rendering from Glide64 will also bring this bug to this plugin.

I think the best way is to improve timing and performance of the current depth buffer emulation method with help from the emulator's side and also use ARB_fragment_shader_interlock extension if supported for accurate depth buffer emulation

**Comment by gonetz** [comment]
>>On top of the problem with alpha test I noticed a bug in Glide64's software depth buffer rendering. Part of the depth buffer is simply not rendered. I think software clipping works incorrect.

It is impossible. Glide64 uses software clipping only. Everything, not only software depth buffer, would be incorrect if software clipping would fail. Also, I never met the problem "Part of the depth buffer is simply not rendered". I dumped Glide64 software depth buffer from many games for reference. It always was correctly filled.

>> I think the best way is to improve timing and performance of the current depth buffer emulation method with help from the emulator's side and also use ARB_fragment_shader_interlock extension if supported for accurate depth buffer emulation

I totally agree with you here. The question: will we get the help from emulator?

**Comment by purplemarshmallow** [comment]
I think Mupen64 already supports fb_Info extensions
In Glide64 something goes wrong. Compare this to #671 
The floor is missing in the depth image. On the fence you can see problems with alpha compare
![glide64_the_legend_of_zelda_02](https://cloud.githubusercontent.com/assets/7283660/9563436/b2213232-4e83-11e5-9393-5a77805a0582.png)

**Comment by gonetz** [comment]
Yes, Mupen64 supports fb_Info extensions, but this support is imperfect. We can use it for games, where it works well to prove the concept. However, we need more robust work of these extensions to rely on them.

Regarding Glide64 depth render error: yes, it's a bug. Did not know about that case, thanks.

**Comment by purplemarshmallow** [comment]
zilmar wrote this about ShowCFB:
>it was in mupen/1964 for rices plugin, I looked at it a little but required a decent amount of changes to memory manager to try and get it working and jabo said it was not worth it cause he could detect it other ways that worked out better.

>If it actually helps Gliden64 then I am happy to implement it, but was not one of my extensions, so not in the plugin spec.

**Comment by gonetz** [comment]
Yes, I read zilmar's words. I also have lots of plans, but don't have time for them.
Anyway, we can use Mupen64 to prove that the conception has its benefits. If it will prove its usefulness, it will be simpler for zilmar to decide how to implement it in Project64.

**Comment by purplemarshmallow** [comment]
I think it’s important to have proper communication between the emulator and the plugin. The goal here should be not only making the plugin faster but also improving the accuracy of the plugin in general.

I think fb_Info in Mupen64 can be really useful. These scenarios come to my mind:

blur pausescreen hack: without proper communication I think it’s impossible to do emulate it. But if you know about writes and reads it should work without a hack

depth buffer copy: it currently does not work in LLE. A notification from the emulator might fix this. Also it might help with CPU based depth buffer clear.

Then I think it’s worth to test some effects that work with Jabo’s software renderer. Jabo’s software renderer is not so accurate so these problems happen likely because of missing synchronisation. #267 comes to my mind would be nice to see what happens if writes and reads are emulated in the proper order. Also Superman 64 #617 copy color currently works completely wrong here. Maybe also check camera detection in Pokemon Snap.

So I think it would be nice to see what Mupen64 can do. I think it would make sense to create a branch to see how much it really helps.

**Comment by tony971** [comment]
@project64 @cxd4 @LegendOfDragoon @Nekokabu @AnyOtherActivePJ64Dev

**Comment by gonetz** [comment]
Closed since software depth render is implemented.
