### ISSUE TITLE
Tetrisphere intro lighting issues

### ISSUE THREAD

**Issue by Cetacea3691** [gonetz/GLideN64#681]
Wrong
![gliden64_tetrisphere_000](https://cloud.githubusercontent.com/assets/13789606/9427165/7dc91d8a-496d-11e5-91c2-a292a1d5845b.png)
Correct (angrylion's RDP)
![ntpp0000](https://cloud.githubusercontent.com/assets/13789606/9427166/8534bfca-496d-11e5-9496-1a9f3b0cddb2.png)

Wrong
![gliden64_tetrisphere_001](https://cloud.githubusercontent.com/assets/13789606/9427167/8d73076e-496d-11e5-9639-915571808ff1.png)
Correct (angrylion's RDP)
![ntpp0001](https://cloud.githubusercontent.com/assets/13789606/9427168/9540cb5c-496d-11e5-85d6-559659ce8732.png)

**Comment by Cetacea3691** [comment]
Almost all bugs are gone in LLE mode, only the horizontal and vertical seams remain.

**Comment by gonetz** [comment]
Fixed

**Comment by olivieryuyu** [comment]
should be closed
