### ISSUE TITLE
Tetrisphere blending or texture issue on Mr. Education'sphere

### ISSUE THREAD

**Issue by Cetacea3691** [gonetz/GLideN64#682]
Wrong
![gliden64_tetrisphere_002](https://cloud.githubusercontent.com/assets/13789606/9427244/6162e266-4972-11e5-8d39-6887bb111e99.png)
Correct (angrylion's RDP)
![ntpp0002](https://cloud.githubusercontent.com/assets/13789606/9427246/750df95e-4972-11e5-96d4-3566c5cfef78.png)

**Comment by tony971** [comment]
Same as #607 ? Taking the PCSX2 align/round sprite hacks would probably be very useful. They were mentioned in the aforementioned issue.

**Comment by AmbientMalice** [comment]
Reminds me of https://github.com/gonetz/GLideN64/issues/637 Does it happen in LLE, too?

**Comment by Cetacea3691** [comment]
Almost all bugs are gone in LLE mode, only the horizontal and vertical seams remain.

**Comment by gonetz** [comment]
Fixed
