### ISSUE TITLE
G.A.S.P!! Fighters' NEXTream (PAL) (Black Screen with Framebuffer Enabled) (Screen Shaking when Framebuffer Disabled)

### ISSUE THREAD

**Issue by Yui12** [gonetz/GLideN64#685]
I have a video of it here that I recorded. 

https://mega.nz/#!uxR3RajQ!wL8d6spVi0OXk_-fXgs_0ZZ3h936COxE2c6ZczS4TB0

This problem doesn't exist in the Japanese and NTSC versions of the game. Strangely Glide64 has this problem too even though we are talking about GlideN64 here. I updated my drivers as well, just to
make sure it wasn't that, but that didn't work. Maybe just a minor regression or bug.

**Comment by purplemarshmallow** [comment]
I tested with PJ64 2.2 and I don't get any shaking or black screen. However if I press start at the title screen the emulator crashes and I can't get ingame

**Comment by purplemarshmallow** [comment]
It seems to be a bug in PJ64, the game works in PJ64 2.2 if you set the CPU to Interpreter or if you use Mupen

**Comment by Yui12** [comment]
Where can I find GlideN64 for Mupenplus? I can't find it on their website. I'm also am using 1.6 since 2.2 has way too many regressions along with many games running slower the last time I used it.

**Comment by purplemarshmallow** [comment]
You can download GLideN64 for Mupen64plus here: https://github.com/gonetz/GLideN64/releases

Project64 1.6 is over 10 years old I don't recommend using it

**Comment by Yui12** [comment]
Oh I remember, that bad variant of it that doesn't work on my PC since it runs slow as well along with no way to configure the settings. The newer versions of GlideN64 fixed most of the speed issues that the frame buffer caused, and this is the old one that hasn't been updated. It doesn't matter anyway since there is other versions of the game that work fine. It's no longer a big deal. Secondly Project64 1.6 with the updated rdb from here http://preview.tinyurl.com/q9zuhkp works just fine. I still will not touch Project64 2.2 until it's actually stable enough and most regressions are gone. Like I said, all my games for the most part work in 1.6 run well. 1.7, 2.0, 2.1, and 2.2 had issues with games that work fine then. I guess I'll close the issue since it's caused by the emulator and not the plugin itself.

**Comment by purplemarshmallow** [comment]
I've reported it to the PJ64 developers https://github.com/project64/project64/issues/583

**Comment by Yui12** [comment]
Thanks for your help.
