### ISSUE TITLE
Texture Enhancements don't work? 

### ISSUE THREAD

**Issue by Yui12** [gonetz/GLideN64#686]
If you go to textures and try to use the filter and enhancement options, it seems to have no effect on the graphics. In game text still is pixelated even though the filter should smooth things out. I'm using the latest version of GlideN64 that was released on the 24th of this month.

**Comment by gonetz** [comment]
I see the effect clearly, check my screenshot
![diff](https://cloud.githubusercontent.com/assets/8983092/9519418/63d2cffe-4ce0-11e5-989d-6a2f4520cf4e.png)

**Comment by Yui12** [comment]
O nevermind, I had to disable ignore backgrounds for the filters to work.
