### ISSUE TITLE
Release GLideN64 for mupen64plus in Windows 64bit

### ISSUE THREAD

**Issue by HansKockrich** [gonetz/GLideN64#687]
Hello Sergey,

are you going to release the GLideN64 plugin for mupen64plus also for the Windows 64bit?

**Comment by gonetz** [comment]
Is it actual?

It's not hard to do. Sources are 64bit compatible. I just need 64bit versions of external libs to make 64bit build.

**Comment by tony971** [comment]
@cxd4 is making the plugins he works on x64 compatible. He also has pull requests in that will turn Project64 into a x64 program. It's definitely on the way.

**Comment by cxd4** [comment]
Well, actually it has been x64 all along.  You just need to disable the remaining breakpoints for the other, commercial images to load in the x64 build, but x64 support has already been here.

Though, apparently the same cannot be said with Mupen64Plus, at least with LLE.  I would not bother worrying about 64-bit M64+ plugins with their core under the lack of maintenance it is in.

**Comment by HansKockrich** [comment]
Hello,

thank you for ur answers. Unfortunately I'm not that much into programming and such stuff :-)

I just noticed the new GLideN64 plugin, which I'll need to play Mario Tennis.

I got an x64 operating system and emulated all the games with M64+ so far.

So do I need to switch my OS to x86 to make the GLideN64 plugin work, so I can play Mario Tennis?

**Comment by baptiste0602** [comment]
Of course not, you just need to use a 32-bit N64 Emulator, like mupen64plus or Project64.
Windows 64bit can run 32bit application.

**Comment by HansKockrich** [comment]
Hi there,

unfortunately it wont work.

I did download GlideN64 plugin and copied the dll into the main folder. But when I try to start the game it says: "mupen64plus-ui-console.exe" has stopped working ???

**Comment by HansKockrich** [comment]
Hello,

sorry for disturbing you, but I tried it several times and still cannot make it work!

It always says: "mupen64plus.exe has stopped working".

What am I doing wrong?

I got an Win7 64bit operating system and downloaded the mupen64plus 32bit edition.

My Bat-File for Mario tennis is:
"C:\Mupen64plus\mupen64plus.exe" --gfx mupen64plus-video-GLideN64.dll --audio mupen64plus-audio-sdl.dll --rsp mupen64plus-rsp-hle.dll --input mupen64plus-input-sdl.dll --configdir C:\Mupen64plus --fullscreen "C:\Mupen64plus\Mario Tennis.z64"

Do you have any clue why it is not working?

**Comment by HansKockrich** [comment]
Hello again!

I tried to execute GLideN64 (Project 2.2) on my Laptop and it crashes as well!

So I suspected the graphic card. And it was the graphic card all along!
I've a NVIDIA GT 525M and needed to select (within nvidia graphic card software) the "mupen64plus.exe" as a program for high graphic performance. Otherwise the performance of the graphic card for mupen64plus was only in energy saving mode. Thus the plugin GLideN64 crashed.

And suddenly: It worked !!!

BTW: I tried to execute GLideN64 (with mupen64plus) on my other Laptop (with poor graphic card) and it crashes as well! So you need to have a good graphic card for using the plugin!

BTW: At the beginning there was no fullscreen available. I removed the "read-only" tick of mupen64plus.cfg and also this problem was solved!

Now I'm happy and can enjoy Mario Tennis!

Thanks a lot for ur support ;-)
