### ISSUE TITLE
Hexen: sky is incorrect

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#688]
gliden64

![dsfsdf](https://cloud.githubusercontent.com/assets/8987490/9562553/2b5b523c-4e6f-11e5-9d5b-40c69ebab09a.jpg)

angrylion LLE

![ggg](https://cloud.githubusercontent.com/assets/8987490/9562556/35b1ee8a-4e6f-11e5-8d19-bc6708263f04.jpg)

No other plugin get correct sky?

**Comment by purplemarshmallow** [comment]
the sky is correct with Jabo's software renderer
TR64ogl is interesting, the sky is correct but nothing else...
![hexen_0001](https://cloud.githubusercontent.com/assets/7283660/9575448/3418151a-4fd0-11e5-809d-38fec654c147.jpg)

**Comment by olivieryuyu** [comment]
fixed
