### ISSUE TITLE
Jeremy McGrath Supercross 2000: missing speed jauge in game and lines pause menu

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#690]
With Glide64:

![sans titre](https://cloud.githubusercontent.com/assets/8987490/9565849/729b0118-4ee9-11e5-8df8-0b3e0ba57de1.jpg)

**Comment by AmbientMalice** [comment]
Here's how it looks now with GLideN64. Native resolution makes the lines thicker.

![jeremy_mcgrath_super-001](https://cloud.githubusercontent.com/assets/10704701/13836825/0ff4be22-ec51-11e5-8c81-000b4c440744.png)

![jeremy_mcgrath_super-002](https://cloud.githubusercontent.com/assets/10704701/13836831/20992632-ec51-11e5-84f0-78182b71cf33.png)

**Comment by gonetz** [comment]
So, missing graphics issue is fixed, isn't it?
Thick line in native resolution is another issue.

**Comment by AmbientMalice** [comment]
I think so, unless there's something wrong with the speed gauge I'm not seeing.

**Comment by olivieryuyu** [comment]
fixed
