### ISSUE TITLE
glTexImage2DMultisample being called with samples set to 0

### ISSUE THREAD

**Issue by matthewharvey** [gonetz/GLideN64#695]
This is an issue of great confusion, but after looking through the spec apparently 0 is not a valid value for samples, even though the man pages say it is. This starts failing on newer versions of the mesa driver, who have recently updated to be inline with the spec.
I'm just creating a bug so that I don't forget about this. If there is a way to assign bugs in Github, please assign it to me and I'll deal with it later.

**Comment by matthewharvey** [comment]
Oh right. This is called in this way at least from Textures.cpp. I haven't seen any others.

**Comment by gonetz** [comment]
Fixed with commit 18172a6
