### ISSUE TITLE
Majora's Mask wrong subscreen

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#698]
If you open the Bomber's Notebook and then close it again the background in the subscreen disappears. Sometimes you can see the depth image in the background, sometimes it's just black. Correct with z64gl.
![gliden64_zelda_majora s_mask_001](https://cloud.githubusercontent.com/assets/7283660/9630822/0fb39d76-517d-11e5-8dda-a8a0d6f1c753.jpg)

**Comment by gonetz** [comment]
Fixed
