### ISSUE TITLE
World Driver Championship wrong reflections

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#700]
correct with z64gl
![gliden64_world_driver_champ_000](https://cloud.githubusercontent.com/assets/7283660/9631119/1c7c30c0-517f-11e5-9686-c62186a1f7de.jpg)
![1](https://cloud.githubusercontent.com/assets/7283660/9631117/17bc0cea-517f-11e5-8591-c4143aab4ccb.jpg)

**Comment by LegendOfDragoon** [comment]
What RSP are you using?

**Comment by purplemarshmallow** [comment]
https://github.com/cxd4/rsp

**Comment by LegendOfDragoon** [comment]
@purplemarshmallow , I see. I just noticed another issue in your screenshot. Those dots at the far right, just before the black area. It reminds me of a bug Angrylion fixed in his plugin not too long ago.

**Comment by LegendOfDragoon** [comment]
@tony971 I was thinking of https://code.google.com/p/angrylions-stuff/source/detail?r=91 , but the one you linked is a good one too.

**Comment by tony971** [comment]
Ahh right. I should read more closely :p

**Comment by purplemarshmallow** [comment]
I fear there are some separate bugs in World Driver Championship unfortunately #466

**Comment by AmbientMalice** [comment]
Fixed.

**Comment by gonetz** [comment]
Good to know.
