### ISSUE TITLE
Turok 3 wrong night vision goggles 

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#707]
The lines are missing. Correct with z64gl/Jabo's software renderer
Savestate: https://drive.google.com/file/d/0B7Y6r4SpC_QQb184V1lMQkNtX2s/view?usp=sharing
![gliden64_turok_3 _shadow_of_o_000](https://cloud.githubusercontent.com/assets/7283660/9704537/78942db6-54ab-11e5-963e-1e86b8fb311a.jpg)
![turok 3 - shadow of oblivion u snap0000](https://cloud.githubusercontent.com/assets/7283660/9704538/7b9304a6-54ab-11e5-9c49-79df7984e9f7.jpg)

**Comment by AmbientMalice** [comment]
The goggles appear to partially work if framebuffer is disabled.

![gliden64_turok_3 _shadow_of_o_004](https://cloud.githubusercontent.com/assets/10704701/14814675/a371b48a-0bea-11e6-9f0a-17b4c3eb33a4.jpg)

**Comment by AmbientMalice** [comment]
Fixed by https://github.com/gonetz/GLideN64/commit/669337f5ab88d1d35d0c44d557a1c54218cdd904

![turok3](https://cloud.githubusercontent.com/assets/10704701/18231367/9ada6fec-72fb-11e6-830a-16026e4701c2.png)

**Comment by gonetz** [comment]
Cool!

**Comment by purplemarshmallow** [comment]
fixed
