### ISSUE TITLE
Star Wars Episode I - Racer bad performance

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#710]
The CPU spends the most time in tidtable.c. I'm not sure what's wrong here.

**Comment by purplemarshmallow** [comment]
I found the problem, it's NoiseTexture::update(). #711 fixes the problem but only if noise emulation is disabled. It's this line:
GLubyte* ptr = (GLubyte*)glMapBufferRange(GL_PIXEL_UNPACK_BUFFER, 0, dataSize, GL_MAP_WRITE_BIT);

**Comment by mudlord** [comment]
Would be more helpful to implement then noise emulation as a pixel shader. Considering that Shader Model 4.0 seems to be the baseline for this plugin, would make sense to offload work as a small pixel shader.

**Comment by purplemarshmallow** [comment]
Noise causes some slowdown in every game but in other games it's not so bad. This game uses noise excessively and it can use noise almost everywhere. Noise is already emulated using shaders (fragment_shader_noise). The slowdown seems to come from the RNG this seems to be done by the CPU. @mudlord you think the solution here is to generate random numbers on the GPU using shaders?

**Comment by AmbientMalice** [comment]
@purplemarshmallow Before the recent PR, was GLideN64 generating noise even if noise was disabled?

**Comment by purplemarshmallow** [comment]
One performance intensive part of noise emulation was not disabled if you disable noise before my PR.

**Comment by purplemarshmallow** [comment]
I'm not sure if the slowdown is caused by the RNG. Here's a screenshot. The CPU also spends time in tidtable.c. If I skip NoiseTexture::update() all performance problems are gone and there's also no bottleneck anymore in tidtable.c.
![unbenannt](https://cloud.githubusercontent.com/assets/7283660/9799156/cbc3db32-5805-11e5-96e4-f65e8171ad0b.jpg)

**Comment by mudlord** [comment]
In that case a shader for RNG sounds reasonable then. Would offload that performance bottleneck, tho I don't know whats so special about glMapBufferRange that causes such a performance hit.

**Comment by purplemarshmallow** [comment]
It only causes a performance hit in Star Wars Episode I - Racer. In other games there's only a small impact. Would be nice to find out why this happens. dataSize is always VI.width*VI.height. At this point it shouldn't matter how much noise a game uses. Here's Ocarina of Time. In both cases noise is updated once per frame.
![1](https://cloud.githubusercontent.com/assets/7283660/9807729/7474fe5e-5857-11e5-9ca8-e7f7ceadee9b.jpg)

**Comment by gonetz** [comment]
@purplemarshmallow  I have made experimental commit with rand loop moved to separate thread:
https://github.com/gonetz/GLideN64/commit/8759f92ee9f39b72911c8a89785efed223fa2124

Please test if it helps with performance hit in Star Wars Episode I - Racer.

**Comment by purplemarshmallow** [comment]
It seems to help a bit but it makes performance inconsistent. If depth buffer buffer emulation is enabled it makes things much worse. With depth buffer emulation + noise + rand loop in separate thread I get only 25 VI/s (before 45). I tested on a dual core (i5-2450M) maybe that's a problem

**Comment by mudlord** [comment]
I think I have a possible solution, however I need to compile the project in order for it to work. Is there instructions on compiling the plugin somewhere?

**Comment by mudlord** [comment]
highp float rand(vec2 co)
{
   return fract(sin(mod(dot(co.xy,vec2(12.9898,78.233)),3.14) * 43758.5453));
}
void main( void ) {
	highp float random =rand(time*vec2(rand(gl_FragCoord.xy*time),rand(gl_FragCoord.xy*time)));
        ...................
}

**Comment by gonetz** [comment]
@purplemarshmallow  I have uploaded optimized version of threaded noise:
https://github.com/gonetz/GLideN64/commit/1f07a45c39983506d452f5c3cf0281468913ee13
Please test it.

@mudlord have you tested it? Looks scary :)

**Comment by mudlord** [comment]
A test can be used here in Chrome or Firefox.
http://glslsandbox.com/e#27812.0

Uses WebGL though. Wasn't able to compile Qt5.5 though, getting some weird linking errors. Will try again at some stage.

**Comment by gonetz** [comment]
You may compile mupen64plus build without QT

**Comment by mudlord** [comment]
And yes, time, is time elapsed.

**Comment by gonetz** [comment]
Shader noise looks much less natural. May be you can tune it better.

```
uniform mediump vec2 uScreenScale;
uniform highp float uTimeElapsed;
float rand(in highp vec2 co) 
{														
return fract(sin(mod(dot(co.xy, vec2(12.9898, 78.233)), 3.14) * 43758.5453));	
}														
float snoise()									
{														
  mediump vec2 fcoord = gl_FragCoord.xy/uScreenScale;	
 return rand(uTimeElapsed * vec2(rand(fcoord * uTimeElapsed),rand(fcoord*uTimeElapsed))); 
//  return rand(vec2(rand(fcoord),rand(fcoord*uTimeElapsed))); 
}														
```
![rand](https://cloud.githubusercontent.com/assets/8983092/9986669/495fba3a-6061-11e5-8fd3-10c4ee1c5dc7.png)

**Comment by gonetz** [comment]
> Ah, I see what you did with the optimization. Pingponging PBOs. A common means to optimize glReadPixels when using PBOs.

Yes, but I use it to upload data there. It can be redundant. I don't understand, what can cause slowdown here, so I decided to use all possible optimizations.

**Comment by purplemarshmallow** [comment]
The recent commit does not help. With depth buffer emulation it's still much slower

**Comment by purplemarshmallow** [comment]
In other games shader might look more natural. I tested Mario Kart (dust). 1st screenshot shows the current implementation in GLideN64. 2nd screenshot shows angrylion's plugin. Also angrylion thinks the effect in Super Mario 64 is no dithering "only a clever use of alpha compares" see https://code.google.com/p/glidehqplusglitch64/issues/detail?id=7. This might be a bad example
![gliden64_mariokart64_000](https://cloud.githubusercontent.com/assets/7283660/9989329/d0eaea7e-6057-11e5-9515-ea1b29b56d18.png)
![nkte0000](https://cloud.githubusercontent.com/assets/7283660/9989332/d58dc6b4-6057-11e5-9049-947a80b37038.png)

**Comment by gonetz** [comment]
SM64 is the perfect example. Yes, it is a clever use of AC_DITHER alpha compare mode. In that mode alpha is tested against random value. Since "they draw a normal Mario but assign 0x80 alpha to its pixels", the equation "alpha > rand()" has 50% chance to hit. Perfect test for rand() function.

**Comment by gonetz** [comment]
> The recent commit does not help. With depth buffer emulation it's still much slower

That is 
depth buffer emulation + noise on = slow
depth buffer emulation + noise off = ok speed
?

Could you give me a savestate where it is noticeable? I don't understand, what is going on there.

**Comment by gonetz** [comment]
@mudlord 
>Wasn't able to compile Qt5.5 though, getting some weird linking errors.

You don't need to compile Qt5 if you just want to debug. You may link against pre-compiled libs and dlls. In that case you will not be able to share your build, but it will work fine on your PC and take much less space.

**Comment by purplemarshmallow** [comment]
Here's a savestate from the track selection: https://drive.google.com/file/d/0B7Y6r4SpC_QQWUxNbWNCSk9LN00/view?usp=sharing
depth buffer emulation is always slow here but the threaded noise commit makes it much worse

**Comment by gonetz** [comment]
Thanks for the save. I see no difference in performance between master and my threaded noise branch. However, I've found interesting thing: I've disabled noise texture update (return at start of NoiseTexture::update()), but still have performance drop with noise enabled. Probably dithering shader works slow.

I may measure performance difference between these two versions of  NoiseTexture::update(), but since new version works slower for you, I will not use it.

**Comment by purplemarshmallow** [comment]
>Edit: just noticed your "If I skip NoiseTexture::update() all performance problems are gone"

I had noise emulation disabled. I noticed NoiseTexture::update() causes a big slowdown even if noise emulation is disabled. Then I made this PR: #711 
I haven't tested skipping NoiseTexture::update() while dithering shaders are enabled

**Comment by mudlord** [comment]
Anyone got a savestate to the SM64 Vanish Cap in Mupen64Plus?

**Comment by gonetz** [comment]
This looks better. Need to solve the problem with noise "scaling". As you know, N64 uses low-res screen resolution, and thus large pixels. If we calculate rand() per pixel in high resolution, the result is visually different from the original one. I use "noise scaling": noise texture has N64 resolution and pixel's coordinates are scaled down before fetching from it.
```
ivec2 coord = ivec2(gl_FragCoord.xy/uScreenScale);
return texelFetch(uTexNoise, coord, 0).r;
```
Thus, all hi-res pixels, which corresponds to one low-res one get the same rand() value and noise effects look the same as on N64.

Is it possible to reproduce with your *random()* function?

**Comment by mudlord** [comment]
Does this look okay? 
![capture](https://cloud.githubusercontent.com/assets/14213419/10014061/0604fe0e-615a-11e5-8b28-03473765e340.PNG)

**Comment by gonetz** [comment]
Rand() function seems to work good, but the result is not pixelated enough. That is noise scale is not implemented or does not work right. You may check GLideN64 or angrylion's plugins for reference. Unfortunately, I have only 1964 save for this effect:
https://drive.google.com/file/d/0B0YqMPjGo3B2dlVaQjZvaXU2Nms/view?usp=sharing
![noise](https://cloud.githubusercontent.com/assets/8983092/10021835/ca923cda-616b-11e5-9a6c-f4c6e28940fb.png)

**Comment by mudlord** [comment]
Just one question, which games use noise apart from SM64?

**Comment by AmbientMalice** [comment]
Lots of them, AFAIK, but it's often for subtle stuff.

Eurocom's The World is Not Enough puts a fuzzy noise filter over everything because reasons. Might be worth investigating.

**Comment by gonetz** [comment]
Menu in Mission Impossible is a good example.

**Comment by purplemarshmallow** [comment]
@mudlord @gonetz Is there a commit with shader noise? I want to test performance in different games

**Comment by gonetz** [comment]
I did not upload it to github. Here my patch for early mudlord's version:
https://drive.google.com/file/d/0B0YqMPjGo3B2VEtVSElhemd6Tkk/view?usp=sharing

**Comment by purplemarshmallow** [comment]
It needs some fixing noise does not update correctly

**Comment by mudlord** [comment]
??? What sort of problem.
Mario 64 works here, so does SSB.

**Comment by purplemarshmallow** [comment]
noise needs to update every frame. I tried the patch and noise always looks the same from one frame to another it's not randomized every frame. Maybe something is wrong with the patch. If this does not happen on your end can you give me a patch or make a commit in a branch?

**Comment by loganmc10** [comment]
Someone should test this again with the latest master, noise emulation should have received a big performance boost with the code refactor

**Comment by purplemarshmallow** [comment]
fixed
