### ISSUE TITLE
Star Wars Episode I - Racer wrong noise

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#712]
I'm not sure if this is related with the performance problems in this game #710 so I opened a separate issue. GLideN64 shows noise at this point in the game: https://drive.google.com/file/d/0B7Y6r4SpC_QQMFBDU2gwMVI3Mms/view?usp=sharing
I can't see noise with angrylion's plugin. I tested on real hardware and I still can't see a noise effect
![gliden64_star_wars_ep1_racer_000](https://cloud.githubusercontent.com/assets/7283660/9808040/89e0e09c-585b-11e5-8af2-d4b88664a686.png)
![2](https://cloud.githubusercontent.com/assets/7283660/9808042/8ca92028-585b-11e5-8d70-fc134a555713.png)

**Comment by gonetz** [comment]
According to my logs, the game uses noise alpha dithering for many objects in this game. Noise alpha dithering is not very noticeable effect: it randomizes 3 lower bits of alpha value. You may just not notice it, especially with low-res software plugin.

**Comment by purplemarshmallow** [comment]
It's true it's hard to notice with angrylion's plugin. To test this I pause the game. If noise is used textures will change even if the game is paused. The game uses noise alpha dithering on the smoke only. On the walls there should be no noise effects. After https://github.com/gonetz/GLideN64/commit/1bf3b6e85afbf5be19fbb4d07e3d73f80efd9a21 this problem is fixed!
