### ISSUE TITLE
GlideN64 not starting in X64 android tablet

### ISSUE THREAD

**Issue by SuperL2** [gonetz/GLideN64#713]
The plugin won't start on my X86 android tablet, like at all. I know some people have had this problem in the past, and one guy was able to fix it by altering some code, but how did he do it? Where did he find the code to alter?  Please help. 

For reference, the post in question is here: https://github.com/gonetz/GLideN64/issues/604

**Comment by fzurita** [comment]
The latest Mupen64plus AE should have the fix included. Here is the link:

http://www.paulscode.com/source/Mupen64Plus-AE/AutoBuilds/

**Comment by fzurita** [comment]
@gonetz this should be closed. This was the big with the RomOpen mupen64plus API call that was fixed a while back.

**Comment by gonetz** [comment]
Ok, thanks
