### ISSUE TITLE
Flickering textures in Adreno android devices

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#714]
I have two devices with adreno GPUs, the Nexus 7 2013 and the Xperia Z Ultra. Both of them have the same issues with textures behaving strangely.

For example:
In Banjo Kazooie: textures flicker.
In Legend of Zelda - Ocarina of time: textures turn strange colors on and off flickering, specially in Link's costume.
Super smash brothers: textures on characters flicker
In Super Mario 64: everything looks normal.

Here is a screenshot with super smash brother. Also, this may be related, notice that instead of having a black border when FBE is enabled, we get strange repeat of what is currently being displayed.

![screenshot_2015-09-13-01-09-56](https://cloud.githubusercontent.com/assets/11581687/9835333/65f4525e-59b4-11e5-9c3f-e598f9bc4ea2.png)

**Comment by gonetz** [comment]
I may confirm the problem. Probably some texture format works incorrect on this device.

**Comment by fzurita** [comment]
Another data point, the issue doesn't happen with the GL ES 2.0 version of the plugin, only the GL ES 3.0 one.

I tried using the GL ES 2.0 texture formats in OpenGL.cpp and Textures.cpp, but it didn't seem to make a difference.

**Comment by fzurita** [comment]
After making pull request #739 the border now looks like static noise in Adreno devices.
