### ISSUE TITLE
regression in Pokemon Stadium

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#718]
if you start two battles things will break 
caused by https://github.com/gonetz/GLideN64/commit/702a0d820399a8e69b903569a3974bd498242509
![gliden64_pokemon_stadium_002](https://cloud.githubusercontent.com/assets/7283660/9982035/9bdc8114-5fce-11e5-92d7-b5957d6754ec.jpg)

**Comment by purplemarshmallow** [comment]
I can't reproduce this with savestates the fastest way to reproduce this problem:
start a battle at the stadium or the gym leader castle
give up
select re-enter

**Comment by gonetz** [comment]
I checked this scenario with your #717 fix. The bug is reproduced as well.

**Comment by purplemarshmallow** [comment]
But this prevents the bug: see #415  
```
void FrameBufferList::saveBuffer(u32 _address, u16 _format, u16 _size, u16 _width, u16 _height, bool _cfb)
{
    if (VI.width == 0 || (_width != VI.width && _height == 0))
        return;

    OGLVideo & ogl = video();
```
