### ISSUE TITLE
Pokemon Stadium 2 wrong images during credits

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#721]
Instead of showing the image GLideN64 just shows a white dot. Glide64(HWFBE) shows the correct images but the white dot sometimes appears in the top left corner. Also with Glide64 the text is wrong.
Savestate: https://drive.google.com/file/d/0B7Y6r4SpC_QQeDNkWmdDY2g1Q1E/view?usp=sharing
![gliden64_pokemon_stadium_2_012](https://cloud.githubusercontent.com/assets/7283660/10082963/94e93902-62fc-11e5-9997-43cd5f1d5d4e.jpg)
![glide64_pokemon_stadium_2_01](https://cloud.githubusercontent.com/assets/7283660/10082983/a563883c-62fc-11e5-854f-611cbfd90d22.png)

**Comment by gonetz** [comment]
Blender issue. 
Need to implement shader-based blending.

**Comment by gonetz** [comment]
I was wrong. It's not blender. It's couple of hard to solve problems, including pixel coverage calculation. Paradox, but Glide64 limitations in fb emulation helped it to draw the images.

**Comment by gonetz** [comment]
Fixed

**Comment by purplemarshmallow** [comment]
This fix breaks Pichu in the pokemon lab. Here's a savestate. https://drive.google.com/file/d/0B7Y6r4SpC_QQTG9pOGowYzl3VDA/view?usp=sharing If you load it you'll get a transfer pack error but Pichu is visible for a short time. Glide64 has this problem as well.
![gliden64_pokemon_stadium_2_000](https://cloud.githubusercontent.com/assets/7283660/10102784/aa4f3b30-63a0-11e5-8c70-738963e3734d.jpg)

![gliden64_pokemon_stadium_2_009](https://cloud.githubusercontent.com/assets/7283660/10102790/ae947282-63a0-11e5-99e1-a63e34736896.jpg)

**Comment by gonetz** [comment]
You found it very quickly, thanks!
Fixed.

**Comment by purplemarshmallow** [comment]
fixed
