### ISSUE TITLE
Pokemon Stadium missing crosses

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#722]
after you win a battle crosses are missing. correct with jabo's plugin but it emulates framebuffer in software...
Savestate: https://drive.google.com/file/d/0B7Y6r4SpC_QQRmc1ek5NdGVlZUk/view?usp=sharing
![gliden64_pokemon_stadium_007](https://cloud.githubusercontent.com/assets/7283660/10085586/4d385382-630a-11e5-97a2-c95d63b28181.jpg)
![pokemon stadium u v1 0 snap0001](https://cloud.githubusercontent.com/assets/7283660/10085589/5086188a-630a-11e5-9527-aae9cf0df5b1.jpg)

**Comment by purplemarshmallow** [comment]
Definitely related to #721 with the latest commit https://github.com/gonetz/GLideN64/commit/c9c6df8359dd97a2e9a846fdeeb9f1741048a33d it looks like this: 
![gliden64_pokemon_stadium_001](https://cloud.githubusercontent.com/assets/7283660/10102866/3018e27a-63a1-11e5-8b32-9811d8369bdc.jpg)

**Comment by standard-two-simplex** [comment]
This seems to have been fixed for some time now.

**Comment by gonetz** [comment]
Indeed, cool!
Interesting, when it became fixed? I thought that it is blender-fixes related, but no, it was fixed before.

**Comment by standard-two-simplex** [comment]
Yes, it was fixed before. I remember I checked when I was working with the blender and it was already fixed.
