### ISSUE TITLE
Pokemon Stadium (J) wrong monitors

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#724]
The monitor and the background of the monitor in Pokemon Stadium (J) are incorrect (screenshot1).
Savestate: https://drive.google.com/file/d/0B7Y6r4SpC_QQX0pueHlLWjhNTnM/view?usp=sharing
z64gl shows the correct monitors but the backgrounds are incorrect (screenshot2). I think the menus in Vigilante8 have the same problem (screenshot3).
![gliden64_pokemon_stadium_003](https://cloud.githubusercontent.com/assets/7283660/10086298/e4f10fc2-630d-11e5-8480-31cfc947bc4a.jpg)
![1](https://cloud.githubusercontent.com/assets/7283660/10086296/e2a15358-630d-11e5-9839-a8078df9c0dd.jpg)
![gliden64_vigilante_8_006](https://cloud.githubusercontent.com/assets/7283660/10086556/473fb740-630f-11e5-9a3f-64c0116dda73.jpg)

**Comment by gonetz** [comment]
Fixed.

**Comment by AmbientMalice** [comment]
Curious to see whether this fixes any other games. Good job, @Gonetz.

**Comment by purplemarshmallow** [comment]
In HLE monitors are fixed. https://github.com/gonetz/GLideN64/commit/586af36bfa9f5c0d017b16d940227071fb318ff6 fixed the framebuffer coordinates. The sky was fixed by a different commit. In LLE there's still a bug at the end of a battle see #415

**Comment by gonetz** [comment]
Please rename this issue to "Pokemon Stadium (J) wrong monitors" and close it.
"Vigilante8 wrong menu transitions" need to be a separate issue.
It's confusing to see issue "Vigilante8 wrong menu transitions", open it and see screen shots from PS.
Also, I doubt that these issues are related.
