### ISSUE TITLE
Mario Tennis Waluigi's eyes

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#726]
If Waluigi wins his eyes should start to glow. This effect is completely missing with all versions of GLideN64. I noticed removing all the code from gDPFillRDRAM fixes the problem (why?)
Savestate: https://drive.google.com/file/d/0B7Y6r4SpC_QQVE94UVgwR1NrMEk/view?usp=sharing
![gliden64_mariotennis_006](https://cloud.githubusercontent.com/assets/7283660/10087237/05664178-6313-11e5-91ae-f07b34b155fb.jpg)

**Comment by oddMLan** [comment]
I wonder if this is still actual.

**Comment by gonetz** [comment]
Fixed.
