### ISSUE TITLE
Pokemon Stadium wrong transparency in warning sign

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#728]
This screen appears after the intro. There should be black stripes on the warning sign. Correct with Jabo's plugin

![gliden64_pokemon_stadium_003](https://cloud.githubusercontent.com/assets/7283660/10106605/f5012e3a-63b5-11e5-835c-80776e0fbf85.jpg)
![npoe0000](https://cloud.githubusercontent.com/assets/7283660/10106608/f7131b3e-63b5-11e5-8c3a-c61abfa211d3.jpg)

**Comment by gonetz** [comment]
Fixed now. Note: the fix is incompatible with "Render 2D elements in N64 resolution" option.
@standard-two-simplex thanks!
