### ISSUE TITLE
Pokemon Stadium 2 (PAL) top of buffer is cut off

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#729]
only happens in pal version. Maybe something is wrong with address calculation like in https://github.com/gonetz/GLideN64/commit/1fb78594c84cda3cbb2ea2d15cbe9696defcf57a?
Savestate: https://drive.google.com/file/d/0B7Y6r4SpC_QQdEw2VGJPZ0l0MzQ/view?usp=sharing
![gliden64_pokemon_stadium_2_000](https://cloud.githubusercontent.com/assets/7283660/10116792/64296ffe-6440-11e5-9ba9-1fd53b7420a0.jpg)

**Comment by purplemarshmallow** [comment]
Seems to be fixed in fb_fixes_2 branch

**Comment by gonetz** [comment]
Would be nice - I did nothing special to fix it :)

**Comment by purplemarshmallow** [comment]
It does not happen anymore with my savestate but it can still happen :/

**Comment by AmbientMalice** [comment]
I wonder if this is fixed by VI improvements?

**Comment by purplemarshmallow** [comment]
Seems fixed!
