### ISSUE TITLE
Move ini file location

### ISSUE THREAD

**Issue by tony971** [gonetz/GLideN64#730]
There are talks of including GlideN64 into the next release of PJ64. However, if installed to the Program Files directory, keeping the ini files with the plugin could create permissions issues. I'd suggest moving them into the PJ64 Config dirctory.

**Comment by AmbientMalice** [comment]
This isn't a particularly bad idea, but it makes installation confusing. Especially for emulators like 1964. If PJ64 were to integrate GLideN64, it'd probably be better off using a fork with the directory changed.

**Comment by LegendOfDragoon** [comment]
>This isn't a particularly bad idea, but it makes installation confusing. Especially for emulators like 1964. If PJ64 were to integrate GLideN64, it'd probably be better off using a fork with the directory changed.

Agreed.

**Comment by tony971** [comment]
Ahh I forgot about 1964. Guess we'll have to get @Project64 's opinion on a fork, then.

**Comment by gonetz** [comment]
Would be better to provide API function, which returns path to config folder, as mupen64plus does.
