### ISSUE TITLE
Anti-aliasing broken.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#731]
![gliden64_banjo_tooie_000](https://cloud.githubusercontent.com/assets/10704701/10133501/435d2834-6610-11e5-8ab7-4cd5b55aa1f1.png)
![gliden64_banjo_tooie_001](https://cloud.githubusercontent.com/assets/10704701/10133502/435eb17c-6610-11e5-9d57-0884b00c0b41.png)

Likely caused by recent refactors or something.

**Comment by purplemarshmallow** [comment]
This breaks AA: https://github.com/gonetz/GLideN64/commit/a98aac9fd4a30ff86d7b1bbe94e13cbe6c55f113
