### ISSUE TITLE
Post-processing shaders

### ISSUE THREAD

**Issue by ADormant** [gonetz/GLideN64#732]
Gonetz if you ever decide to work on post-processing ever again things like ambient occlusion, global illumination and Depth of Field would be particularly innovative for N64 emulation.

https://github.com/Tinob/Ishiiruka/blob/master/Data/Sys/Shaders/IshiirukaFX.glsl
https://github.com/Tinob/Ishiiruka/blob/master/Data/Sys/Shaders/DolphinFX.glsl
@gonetz

**Comment by tony971** [comment]
Please ignore this forever until the vast majority of core emulation bugs are resolved.

**Comment by tony971** [comment]
Please ignore this forever until the vast majority of core emulation bugs are resolved.

**Comment by ADormant** [comment]
@tony971 One doesn't preclude the other.

**Comment by tony971** [comment]
Let's assume time is a limited resource. This is the lowest priority ticket that exists.

**Comment by mudlord** [comment]
The code to do a post processed quad already exists Someone just needs to extend it for handling arbitrary shaders. Thats if they have the motivation to do.

**Comment by ADormant** [comment]
https://github.com/Tinob/Ishiiruka/commit/a9560c8e3ae777cb2f57e185220bc9d8a9f0e9a4
https://github.com/Tinob/Ishiiruka/commit/bd3de2dc040520968c2ff63ce33a74cfa2f94a33
https://github.com/Tinob/Ishiiruka/commit/bbccbe938486cb954bc13f0935610abdc5885f45
@gonetz

**Comment by ADormant** [comment]
@gonetz  Tessellation and displacement mapping.
https://github.com/Tinob/Ishiiruka/commit/aad021262598a88fd9b07e5034b878ff35ad60dd
https://github.com/Tinob/Ishiiruka/commit/a713a7c2ccd910c7b632d74b93590a25413d8ce3
https://github.com/Tinob/Ishiiruka/commit/469f7ac546f8f4f8423507ed22ee11aec36ffdc4
https://github.com/Tinob/Ishiiruka/commit/d40f9df7ef04e467533ec515ef1c3075d06de12d
https://github.com/Tinob/Ishiiruka/commit/3374eb731c5128dcb843cbd17d904a1121f72aa1
https://github.com/Tinob/Ishiiruka/commit/f8cacdab52861d89eacabd7a69ae6019c3afc2da
https://github.com/Tinob/Ishiiruka/commit/bc87a8ea2705c1c17df96ad8dbd26b86154f09e1
https://github.com/Tinob/Ishiiruka/commit/bfa2915b1f34e1487a43672e6b3522007e8a761e
https://github.com/Tinob/Ishiiruka/commit/8f63da6f0985897e6f35a52d4f6c1a9536d1474f

**Comment by gonetz** [comment]
Thanks for the info. It should be useful for anyone who will take that task.

**Comment by SwinglesMan** [comment]
Adormant, just use reshade. No point in doing things that are already done for you ;)

**Comment by ADormant** [comment]
Reshade has different shaders than DolphinFX/IshiirukaFX and Glide still needs Z-buffer access to fully use Reshade.

https://github.com/dolphin-emu/dolphin/pull/3366/files
Depth https://github.com/Tinob/Ishiiruka/commit/5e55929bdcf8d49b92426fcbfc01f8f3d7188bec
https://github.com/Tinob/Ishiiruka/commit/af610d60086989f82f6cf13130260bf29e7cbb56
https://github.com/Tinob/Ishiiruka/commit/d2fb92518f50c6154f33f05be39128e48d6b83be
https://github.com/Tinob/Ishiiruka/commit/aad021262598a88fd9b07e5034b878ff35ad60dd
https://github.com/Tinob/Ishiiruka/commit/d4f525085234d54cc8d81f99eb4efa5e899b7bbc
https://github.com/Tinob/Ishiiruka/commit/a9560c8e3ae777cb2f57e185220bc9d8a9f0e9a4
https://github.com/Tinob/Ishiiruka/commit/bbccbe938486cb954bc13f0935610abdc5885f45
https://github.com/Tinob/Ishiiruka/commit/4c1d871fcf40567a35836b05ef3bc949afd1d6ff
Scaling filter https://github.com/Tinob/Ishiiruka/commit/4178659da9c47f4f5611d0b4112ef907d628c29d
https://github.com/Tinob/Ishiiruka/commit/c6df3fa13add5e0d17f69c574396929a01f3ce45

Multi pass https://github.com/Tinob/Ishiiruka/commit/ffa8a862e4b85ab1372b05e6253972cdd92385d4
https://github.com/Tinob/Ishiiruka/commit/6c1603447a630fe5f724d4812008490e627d7c92
https://github.com/Tinob/Ishiiruka/commit/1583f8a2abf593a64abca7566531a1a89ce02879
https://github.com/Tinob/Ishiiruka/commit/c6027f42776f9d7416a75c4906cbd254d49d66c5

PRNG https://github.com/Tinob/Ishiiruka/commit/357f09352562ffbdd9cde1de1f302c7436bee971

**Comment by DonelBueno** [comment]
@ADormant, nobody is going to read so much information about post-processing shaders just to implement it in GLide. Seriously, you've been updating this for 5 months.

**Comment by oddMLan** [comment]
I think this ticket should be closed.

**Comment by shinra358** [comment]
To be honest, having the plugin use retroarch common shaders and all of it's passes is the best solution of all. Therefore, gonetz doesn't even have to worry about shaders ever again after this for we'll already have everything provided for us. Reshade is just terribad now.

**Comment by theboy181** [comment]
That’s a pretty narrow minded view. There are other emulators that could benefit from filters/shaders.

**Comment by shinra358** [comment]
apparently you didn't even understand what I even said...

**Comment by gonetz** [comment]
I close it for now. #1548 is implemented, so if you need high-quality post-processing shaders, use Reshade. I agree that "having the plugin use retroarch common shaders and all of it's passes is the best solution of all", but I will not have time for that for a long time. There are plenty of more urgent tasks for me. Unless somebody else will take this task...
