### ISSUE TITLE
regression: line drawing microcodes broken

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#733]
all line drawing microcodes are broken in current master. Examples: Glover2 fishing rod, Turok Dinosaur Hunter map

**Comment by gonetz** [comment]
Fixed

**Comment by AmbientMalice** [comment]
This is still broken in LLE, I assume?

**Comment by purplemarshmallow** [comment]
Yes but it's broken with every LLE hardware renderer also z64gl and Jabo's LLE plugin. Possibly it's problematic to draw a line with this approach.
