### ISSUE TITLE
regression: Mario Tennis shadows are broken

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#734]
Ingame shadows are broken. Introduced by a very recent commit

**Comment by purplemarshmallow** [comment]
It's something after https://github.com/gonetz/GLideN64/commit/16136b04e91f5a29eab15d976a50925e2f1d7925 I think it's https://github.com/gonetz/GLideN64/commit/586af36bfa9f5c0d017b16d940227071fb318ff6 everything else shouldn't be able to break it

**Comment by gonetz** [comment]
Yes, it is 586af36. That's a bad news.

**Comment by gonetz** [comment]
Fixed.

**Comment by purplemarshmallow** [comment]
fixed
