### ISSUE TITLE
Antialiasing breaks Resident Evil 2 intro

### ISSUE THREAD

**Issue by tony971** [gonetz/GLideN64#737]
The intro breaks after getting to the eye, anyway, but antialiasing makes it so it doesn't even get past the capcom logo.

**Comment by purplemarshmallow** [comment]
SMAA should be implemented anyway to support AA+N64 depth compare #515 
I think multisampling is too much trouble. Some games are still broken with it #526 #249 
I think it's better to use SMAA globally for anti-aliasing...

**Comment by AmbientMalice** [comment]
I still think SMAA would be worth investigating, but I dunno whether it has any possible side effects like MSAA.

**Comment by GameRecover** [comment]
Post-processing methods like smaa and fxaa are good, but are also significantly lower in output quality when compared to traditional methods. I doubt they'd have any problems as they'd be getting the final image and then they'd be using that for edge-detected smoothing, but in the same breath they'd also be doing a less impressive job (I'm not a fan of how the edges turn out in most post-processing AA jobs and would much prefer a hardware intensive, but quality method). 

Seeing as the screen resolution can be raised without any adverse effects, I have an idea (although I'm not sure how to implement it). Would it be possible to have separate render and output resolutions? At the moment, if you run in windowed mode at 640x480 it renders at 640x480 and then displays that on the emulator; would it be possible to have it still show a window at 640x480 but have it actually render at 1280x960 and then downsample down? Or on the flip side, for slower machines have it render at 320x240 and resize up?

It'd eliminate the need for the MSAA in most (if not all) cases and is a viable alternative to SSAA if it's too tricky to implement. It's the same downsampling principal as Nvidia's DSR or AMD's VSR and has the advantage of being able to do lower resolutions scaled up too for worse-off PCs. If you combined a method like this with the post-processing AA (such as SMAA) the result could be beautiful every time, and the internal resolution could be tailored to your system, setting it as high or as low as need be.

**Comment by purplemarshmallow** [comment]
I mean SMAA the advantage is that it has no side effects because it's post processing
>would it be possible to have it still show a window at 640x480 but have it actually render at 1280x960 and then downsample down

pretty sure that's how traditional AA works

**Comment by GameRecover** [comment]
I agree and I'd love to see it included, I know a few shader based solutions exist for it so it might be possible to piggyback it on the code for the bloom shader. I just wanted to make sure it wasn't being used in place of traditional AA as a band-aid.

That is how traditional AA works but there are other ways to go about it. I wasn't sure it had been looked at from that angle yet or not, and if there'd be drawbacks to something like that.

**Comment by gonetz** [comment]
Fixed.
