### ISSUE TITLE
Beetle Adventure Racing Lens Flare Bug.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#740]
Lens flare shouldn't be visible.
![beetle_adventure](https://cloud.githubusercontent.com/assets/10704701/10248029/90d751f6-694f-11e5-8e6f-db636fddb179.jpg)

Save state: https://mega.nz/#!w9B21KqT!GONzRfdqz8moxixuEBPh7rR70mfwibnsbO9KUSbk4jo

**Comment by olivieryuyu** [comment]
simply needs copy depth buffer to rdram

**Comment by purplemarshmallow** [comment]
It's enabled by default for this game

**Comment by olivieryuyu** [comment]
Fixed?

**Comment by olivieryuyu** [comment]
@AmbientMalice 

it is fixed

can you please close?

![sans titre](https://user-images.githubusercontent.com/8987490/31358624-a40149c0-ad46-11e7-80bb-26425d39c4b4.jpg)
