### ISSUE TITLE
Roadsters - Mirror Glitchy.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#741]
Right side of rear view mirror in Roadsters is glitchy.
![gliden64_roadsters_trophy_000](https://cloud.githubusercontent.com/assets/10704701/10262773/dc1785a0-6a08-11e5-8145-28eaf0fb2400.png)

**Comment by AmbientMalice** [comment]
It looks as though the mirror isn't rendering at all now.

**Comment by gonetz** [comment]
Yes, broken after latest fixes. I found the reason, it will be fixed soon.

**Comment by gonetz** [comment]
Fixed. I can't reproduce initial bug - rear mirror always works correct for me. Be sure that you does not use "screen adjust" option.

**Comment by AmbientMalice** [comment]
Both original issue and regression fixed.
