### ISSUE TITLE
[WIP] Beginner friendly building guide for GLideN64 with Microsoft Visual Studio (2012-2015)

### ISSUE THREAD

**Issue by ghost** [gonetz/GLideN64#742]
# **[WIP2] = work in progress**

Tested from scratch ;)
Turning GLideN64 into a clone and compile solution ...
p.s. The screenshots aren't 100% coherent because this tutorial already went thru a few revisions.
p.s.s. You might have to delete your texture cache.

You need to update libpng and zlib for GLideN64 beacause of Qt5.6 and MSVS2015.
There might be problems building zlib on Windows 8 and higher, please leave a comment if you have issues.
# [Text version] zilmar spec version:
# [Complete version] zilmar spec version:
## Step.1 Getting ready

Create in your C:\ directory a folder named GLideN64 and download:
[Git 64-bit](https://github.com/git-for-windows/git/releases/download/v2.6.0.windows.1/Git-2.6.0-64-bit.exe) or [Git 32-bit](https://github.com/git-for-windows/git/releases/download/v2.6.0.windows.1/Git-2.6.0-32-bit.exe)
[Microsoft Visual Studio 2015](https://go.microsoft.com/fwlink/?LinkId=532606&clcid=0x409) or [Microsoft Visual Studio 2013](https://go.microsoft.com/fwlink/?LinkId=532495&clcid=0x409) or [Microsoft Visual Studio 2012](http://go.microsoft.com/fwlink/?LinkId=623358)
[Python 3.5.0](https://www.python.org/ftp/python/3.5.0/python-3.5.0.exe) or [Python 2.7.10](https://www.python.org/ftp/python/2.7.10/python-2.7.10.msi)
[Perl 64-bit](http://strawberryperl.com/download/5.22.0.1/strawberry-perl-5.22.0.1-64bit.msi) or [Perl 32-bit](http://strawberryperl.com/download/5.22.0.1/strawberry-perl-5.22.0.1-32bit.msi)
[Freetype-2.5.3](http://sourceforge.net/projects/freetype/files/freetype2/2.5.3/ft253.zip/download)
Updated: [Libpng and Zlib](https://drive.google.com/file/d/0Bygxj1zIGEsca2l4U2J5d0RsTHM/view?usp=sharing) or ([Libpng](http://prdownloads.sourceforge.net/libpng/lpng1618.zip?download) and [Zlib](http://zlib.net/zlib128.zip))
## Step.2 Installing, downloading git-repositories and building Qt5.6

Install Git 64-bit or Git 32-bit.
Use the Custom installation for Microsoft Visual Studio 2015 and
![1](https://cloud.githubusercontent.com/assets/13789606/10266542/7b32d528-6a6c-11e5-8ceb-2c14f7f5c5d7.png)

make sure to check the Programming Language Visual C++.
![2](https://cloud.githubusercontent.com/assets/13789606/10266540/7b3253dc-6a6c-11e5-9625-5316dd0514e4.png)

Install Python 3.5.0 with checked Add Python 3.5 to PATH or
![3](https://cloud.githubusercontent.com/assets/13789606/10266544/7b34462e-6a6c-11e5-97aa-03014fa1c4fe.png)

install Python 2.7.10 with the feature Add python.exe to Path.
![4](https://cloud.githubusercontent.com/assets/13789606/10266541/7b3295c2-6a6c-11e5-97cd-0c8ce88ac38a.png)
![5](https://cloud.githubusercontent.com/assets/13789606/10266539/7b31806a-6a6c-11e5-9a2f-177333bd4f02.png)

Install Perl 64-bit or Perl 32-bit.
**[Attention!** If you have MinGW installed, then make sure Perl comes before MinGW in your Environment Variables... .**]**
Now click on your start menu button, type Git into the search field and click on Git Bash.
![6](https://cloud.githubusercontent.com/assets/13789606/10266543/7b334878-6a6c-11e5-99f4-5507719373bc.png)

Copy and Paste the following commands into the black Git Bash window

> git clone https://code.qt.io/qt/qt5.git C:/GLideN64/Qt5.6-win32-msvc2015-static
> cd C:/GLideN64/Qt5.6-win32-msvc2015-static
> ./init-repository --no webkit
> git clone https://github.com/gonetz/GLideN64.git C:/GLideN64/GLideN64-master
> cd C:/GLideN64/GLideN64-master
> C:/GLideN64/GLideN64-master/src/getRevision.sh
> *

![7](https://cloud.githubusercontent.com/assets/13789606/10266547/7b489764-6a6c-11e5-83f3-51fee0320e09.png)

and wait until you see the \* and two new folders.
![8](https://cloud.githubusercontent.com/assets/13789606/10266548/7b48e19c-6a6c-11e5-98f2-21a7efb774b8.png)

Again click on your start menu button, type Developer into the search field and click on Developer Command Prompt for VS2015.
![9](https://cloud.githubusercontent.com/assets/13789606/10266549/7b49cf94-6a6c-11e5-854b-387e7506da53.png)

Copy and Paste the following commands into the black Developer Command Prompt window

> cd C:\GLideN64\Qt5.6-win32-msvc2015-static
> configure -static -release -platform win32-msvc2015 -static-runtime -c++11 -qt-pcre -opengl desktop -no-angle -no-freetype -no-libpng -no-crt -opensource -nomake tools -nomake examples -nomake tests -mp
> y
> nmake
> *

![10](https://cloud.githubusercontent.com/assets/13789606/10266545/7b488f4e-6a6c-11e5-9600-ff3e78061bc9.png)

and wait (10-30min+) while Qt5.6 is building until you see the *.
![11](https://cloud.githubusercontent.com/assets/13789606/10266546/7b487e6e-6a6c-11e5-83e6-6eebe6b7fba4.png)
## Step.3 Extracting and creating additional folders

Extract the updated libpng and zlib into C:\GLideN64\GLideN64-master\src\GLideNHQ\lib and overwrite the other ones or
![90](https://cloud.githubusercontent.com/assets/13789606/10415780/3fcf483c-6ffc-11e5-9f2d-dff00d8e3c40.png)

extract the (libpng and zlib) source codes directly into your GLideN64 folder and build them yourself.
Extract freetype-2.5.3 directly into your GLideN64 folder.
![12](https://cloud.githubusercontent.com/assets/13789606/10266550/7b4a78ea-6a6c-11e5-8456-d66c298c0887.png)

Your GLideN64 folder should look now somewhat like this.
![13](https://cloud.githubusercontent.com/assets/13789606/10266554/7b5ebd6e-6a6c-11e5-92f2-622613f080d0.png)

Create inside your GLideN64 folder a new folder with the name Plugin
![14](https://cloud.githubusercontent.com/assets/13789606/10266553/7b5ec1b0-6a6c-11e5-898d-3689c0b70703.png)

and make inside it another new folder with the name GFX.
![15](https://cloud.githubusercontent.com/assets/13789606/10266552/7b5e9578-6a6c-11e5-8290-43f96f40de96.png)
## Step.4 Configuring and building Freetype-2.5.3

In C:\GLideN64\freetype-2.5.3\builds\windows\vc2010 open the file freetype.sln (Microsoft Visual Studio Solution).
![16](https://cloud.githubusercontent.com/assets/13789606/10266551/7b5e6b16-6a6c-11e5-8960-ab9b1237c20e.png)

When MSVS2015 asks you to Upgrade the VC++ Compiler and Libraries click OK.
![17](https://cloud.githubusercontent.com/assets/13789606/10266556/7b61641a-6a6c-11e5-9552-b2b6df199f2b.png)

Right-click on Solution 'freetype' (1 project) and left-click on Properties.
![18](https://cloud.githubusercontent.com/assets/13789606/10266555/7b60d004-6a6c-11e5-9ef1-19fd0de56aaa.png)

Click on Configuration Properties and then on Configuration Manager... .
![19](https://cloud.githubusercontent.com/assets/13789606/10266562/7b78e45a-6a6c-11e5-8e57-d94ec0c45ffe.png)

Click on Active solution configuration and select Release Multithreaded.
Also make sure your Active solution platform is Win32.
![20](https://cloud.githubusercontent.com/assets/13789606/10266559/7b781034-6a6c-11e5-8078-b3681b1e7639.png)

Right-click on Solution 'freetype' (1 project) and left-click on Build Solution or Rebuild Solution.
![21](https://cloud.githubusercontent.com/assets/13789606/10266560/7b785ca6-6a6c-11e5-90a8-89cbb1101e2c.png)

Check your output log, it should say: 1 succeeded, 0 failed, 0 skipped.
![22](https://cloud.githubusercontent.com/assets/13789606/10266557/7b75b5be-6a6c-11e5-967c-17548151fd0b.png)
## Step.5 Configuring and building Libpng `#Optional#`

In C:\GLideN64\lpng1618\projects\vstudio open the file vstudio.sln (Microsoft Visual Studio Solution).
![23](https://cloud.githubusercontent.com/assets/13789606/10266561/7b78a4a4-6a6c-11e5-90b1-d4702f0f54c1.png)

When MSVS2015 asks you to Upgrade the VC++ Compiler and Libraries click OK.
![24](https://cloud.githubusercontent.com/assets/13789606/10266558/7b780670-6a6c-11e5-9405-47f94c3e3200.png)

Right-click on Solution 'vstudio' (7 projects) and left-click on Properties.
![25](https://cloud.githubusercontent.com/assets/13789606/10266563/7b8ba1a8-6a6c-11e5-9db7-9c2e3bcec75e.png)

Click on Configuration Properties and then on Configuration Manager... .
![26](https://cloud.githubusercontent.com/assets/13789606/10266564/7b8bda74-6a6c-11e5-893d-35040e940a57.png)

Click on Active solution configuration and select Release Library.
Also make sure your Active solution platform is Win32 and uncheck pngstest, pngtest, pngunknown and pngvalid.
![27](https://cloud.githubusercontent.com/assets/13789606/10266567/7b8f11ee-6a6c-11e5-9e04-292df7529aca.png)

Right-click on libpng and left-click on Properties.
![28](https://cloud.githubusercontent.com/assets/13789606/10266568/7b8febe6-6a6c-11e5-94e8-802923330e09.png)

Write into Output Directory

> `..\..\..\..\GLideN64-master\src\GLideNHQ\lib`

and into Target Name.

> `$(ProjectName)`

Click Apply.
![29](https://cloud.githubusercontent.com/assets/13789606/10266565/7b8e66c2-6a6c-11e5-898a-51daeb82ff90.png)

Right-click on Solution 'vstudio' (7 projects) and left-click on Build Solution or Rebuild Solution.
![30](https://cloud.githubusercontent.com/assets/13789606/10266566/7b8efd8a-6a6c-11e5-86ec-b901dfdb8ed2.png)

Check your output log, it should say: 3 succeeded, 0 failed, 4 skipped.
![31](https://cloud.githubusercontent.com/assets/13789606/10266569/7ba25132-6a6c-11e5-8138-fbab4e510f31.png)
## Step.6 Configuring and building Zlib `#Optional#`

In C:\GLideN64\zlib-1.2.8\contrib\masmx86 right-click on the file bld_ml32 and left-click on Edit.
![32](https://cloud.githubusercontent.com/assets/13789606/10266570/7ba2f6f0-6a6c-11e5-82fa-38056528db09.png)

Write into the Notepad window

> `ml /safeseh /coff /Zi /c /Flmatch686.lst match686.asm`
> `ml /safeseh /coff /Zi /c /Flinffas32.lst inffas32.asm`

and save it.
![33](https://cloud.githubusercontent.com/assets/13789606/10266571/7ba508be-6a6c-11e5-8198-9b3aa0206572.png)

In C:\GLideN64\zlib-1.2.8\contrib\vstudio\vc11 open the file zlibvc.sln (Microsoft Visual Studio Solution).
![34](https://cloud.githubusercontent.com/assets/13789606/10266572/7ba5ab2a-6a6c-11e5-8b15-9a77f9ee78de.png)

When MSVS2015 asks you to Upgrade the VC++ Compiler and Libraries click OK.
![35](https://cloud.githubusercontent.com/assets/13789606/10266573/7ba6aa2a-6a6c-11e5-846a-817aacf0c008.png)

Right-click on Solution 'zlibvc' (6 projects) and left-click on Properties.
![36](https://cloud.githubusercontent.com/assets/13789606/10266574/7ba6ff16-6a6c-11e5-8a05-4cf42508ffd9.png)

Click on Configuration Properties and then on Configuration Manager... .
![37](https://cloud.githubusercontent.com/assets/13789606/10266575/7bb93f1e-6a6c-11e5-8191-d76ed99b959e.png)

Click on Active solution configuration and select Release.
Also make sure your Active solution platform is Win32 and uncheck miniunz, minizip, testzlib and testzlibdll.
![38](https://cloud.githubusercontent.com/assets/13789606/10266576/7bb9e108-6a6c-11e5-934b-878523d5eae7.png)

Expand zlibvc by clicking on the little arrow.
![39](https://cloud.githubusercontent.com/assets/13789606/10266579/7bbc67ca-6a6c-11e5-888e-39335e8c6021.png)

Click on zlibvc.def and change the version number from VERSION 1.2.8 to VERSION 1.28 .
![40](https://cloud.githubusercontent.com/assets/13789606/10266578/7bbbf614-6a6c-11e5-893b-2673e80721bd.png)

Right-click on zlibstat and left-click on Properties.
![41](https://cloud.githubusercontent.com/assets/13789606/10266580/7bbc84d0-6a6c-11e5-8837-f88d49f7a25a.png)

Write into Output Directory

> `..\..\..\..\GLideN64-master\src\GLideNHQ\lib`

and into Target Name.

> `zlib`

Click Apply.
![42](https://cloud.githubusercontent.com/assets/13789606/10266577/7bbac906-6a6c-11e5-86c4-4ee0e4c23e08.png)

Expand C/C++ by clicking on the little arrow.
Click on Preprocessor and remove the line

> `ZLIB_WINAPI;`

in Preprocessor Definitions.
![43](https://cloud.githubusercontent.com/assets/13789606/10266582/7bcfee26-6a6c-11e5-8c3c-642cf8fb7bef.png)

Click Apply.
![44](https://cloud.githubusercontent.com/assets/13789606/10266581/7bcfd45e-6a6c-11e5-976c-f5599e314ea1.png)

Click on Librarian and write into Output File.

> `$(OutDir)$(TargetName)$(TargetExt)`

Click Apply.
![45](https://cloud.githubusercontent.com/assets/13789606/10266583/7bd010cc-6a6c-11e5-8b74-14b403afb202.png)

Right-click on Solution 'zlibvc' (6 projects) and left-click on Build Solution or Rebuild Solution.
![46](https://cloud.githubusercontent.com/assets/13789606/10266584/7bd2e4e6-6a6c-11e5-8443-9b7e2cc9e0e4.png)

Check your output log, it should say: 2 succeeded, 0 failed, 4 skipped.
![47](https://cloud.githubusercontent.com/assets/13789606/10266586/7bd570f8-6a6c-11e5-867f-bf61ff1a355a.png)
## Step.7 Configuring and building GLideN64

In C:\GLideN64\GLideN64-master\projects\msvc12 open the file GLideN64.sln (Microsoft Visual Studio Solution).
![48](https://cloud.githubusercontent.com/assets/13789606/10266585/7bd4c720-6a6c-11e5-9490-088d300e3864.png)

When MSVS2015 asks you to Upgrade the VC++ Compiler and Libraries click OK.
![49](https://cloud.githubusercontent.com/assets/13789606/10266587/7be82a22-6a6c-11e5-8b36-f10e418328d9.png)

Right-click on Solution 'GLideN64' (2 projects) and left-click on Add>Existing Project... .
![50](https://cloud.githubusercontent.com/assets/13789606/10266588/7be86762-6a6c-11e5-8d8f-4e997903419a.png)

In C:\GLideN64\GLideN64-master\src\GLideNUI open the file GLideNUI.
![51](https://cloud.githubusercontent.com/assets/13789606/10266589/7bea4e60-6a6c-11e5-8c48-55f9c4cd2d25.png)

Right-click on Solution 'GLideN64' (3 projects) and left-click on Properties.
![52](https://cloud.githubusercontent.com/assets/13789606/10266590/7bededea-6a6c-11e5-8a4b-a7a814761301.png)

Click on Project Dependencies, make sure GLideN64 is selected under Projects and check GLideNUI.
Click Apply.
![53](https://cloud.githubusercontent.com/assets/13789606/10266591/7beed700-6a6c-11e5-9263-8375c701dfac.png)

Click on Configuration Properties and then on Configuration Manager... .
![54](https://cloud.githubusercontent.com/assets/13789606/10266592/7bef3d30-6a6c-11e5-80f4-d626cef22fb4.png)

Click on Active solution configuration and select Release.
![56](https://cloud.githubusercontent.com/assets/13789606/10266594/7bfe9640-6a6c-11e5-9473-7314ca8ca220.png)

Right-click on GLideNUI and left-click on Add>New Filter.
![57](https://cloud.githubusercontent.com/assets/13789606/10266595/7bffc63c-6a6c-11e5-901d-985038a046d9.png)

Name it translations.
![58](https://cloud.githubusercontent.com/assets/13789606/10266596/7c017d06-6a6c-11e5-9d4b-bd9f5fd20469.png)

Right-click on translations and left-click on Add>Existing Item... .
![59](https://cloud.githubusercontent.com/assets/13789606/10266598/7c052208-6a6c-11e5-9372-76576f2aabef.png)

In C:\GLideN64\GLideN64-master\translations select all files and click Add.
![60](https://cloud.githubusercontent.com/assets/13789606/10266597/7c04c380-6a6c-11e5-90e3-8ce5c7c64b29.png)

Select all translation files, right-click on them and then left-click on Properties.
![61](https://cloud.githubusercontent.com/assets/13789606/10266599/7c14ab2e-6a6c-11e5-964a-a928318ebe28.png)

Change your Item Type to Custom Build Tool and click Apply.
![62](https://cloud.githubusercontent.com/assets/13789606/10266600/7c14e698-6a6c-11e5-8d93-35e3c3e31945.png)

Click on Custom Build Tool and write into Command Line.

> `"$(QTDIR)\bin\lrelease.exe" "%(FullPath)" -qm "$(Release)\%(Filename).qm"`

Write into Description.

> `%(Identity)...`

Write into Outputs.

> `%(Filename).qm`

Write into Additional Dependencies.

> `$(QTDIR)\bin\lrelease.exe`

Click Apply.
![63](https://cloud.githubusercontent.com/assets/13789606/10266601/7c1583dc-6a6c-11e5-9cb4-1b1c331ad922.png)

Right-click on GLideN64 and left-click on Add>New Filter.
![64](https://cloud.githubusercontent.com/assets/13789606/10266602/7c1b7ac6-6a6c-11e5-923b-737155d82c99.png)

Name it ini.
![65](https://cloud.githubusercontent.com/assets/13789606/10266603/7c1cdc7c-6a6c-11e5-8a84-1a13083fa9e8.png)

Right-click on ini and left-click on Add>Existing Item... .
![66](https://cloud.githubusercontent.com/assets/13789606/10266604/7c1d3d5c-6a6c-11e5-935a-b8fc68bee7c8.png)

In C:\GLideN64\GLideN64-master\ini select all files and click Add.
![67](https://cloud.githubusercontent.com/assets/13789606/10266605/7c27fada-6a6c-11e5-8d85-cdc2ce090b8a.png)

Select all ini files, right-click on them and then left-click on Properties.
![68](https://cloud.githubusercontent.com/assets/13789606/10266607/7c2b8de4-6a6c-11e5-8a61-4cd7a3e3f44a.png)

Change your Item Type to Custom Build Tool and click Apply.
![69](https://cloud.githubusercontent.com/assets/13789606/10266606/7c2b6198-6a6c-11e5-846c-7d0c0975f6a1.png)

Click on Custom Build Tool and write into Command Line.

> `xcopy "%(Identity)" "$(Release)" /s /i /y`

Write into Outputs.

> `%(Filename)%(Extension)`

Click Apply.
![70](https://cloud.githubusercontent.com/assets/13789606/10266608/7c31d712-6a6c-11e5-9f4b-1b4f1f3b815a.png)

Right-click on GLideNUI and left-click on Upgrade VC++ Compiler and Libraries.
![71](https://cloud.githubusercontent.com/assets/13789606/10266609/7c3250f2-6a6c-11e5-8ac3-9b84d417247d.png)

Click OK.
![72](https://cloud.githubusercontent.com/assets/13789606/10266610/7c3448c6-6a6c-11e5-8d14-b3c9a2452b14.png)

Right-click on GLideNUI and left-click on Properties.
![73](https://cloud.githubusercontent.com/assets/13789606/10266611/7c3cfeee-6a6c-11e5-8ece-15cf4ee1cb7e.png)

Click on Librarian and add/write into Additional Dependencies.

> `dwrite.lib;qtpcre.lib;`

Click Apply.
![74](https://cloud.githubusercontent.com/assets/13789606/10266613/7c43951a-6a6c-11e5-893a-55572b87ac88.png)

Right-click on GLideN64 and left-click on Properties.
![75](https://cloud.githubusercontent.com/assets/13789606/10266612/7c424eb2-6a6c-11e5-9113-1ab4e49692ae.png)

Click on C/C++ and overwrite in Additional Dependencies `../../../freetype/include` with.

> `../../../freetype-2.5.3/include`

Click Apply.
![76](https://cloud.githubusercontent.com/assets/13789606/10266614/7c479b1a-6a6c-11e5-8a3f-a2b5c8b586aa.png)

Click on Linker and write into Output File.

> `$(Release)\GLideN64.dll`

Write into Additional Library Directories.

> `../../../freetype-2.5.3/objs/win32/vc2010`

Click Apply.
![77](https://cloud.githubusercontent.com/assets/13789606/10266615/7c47cca2-6a6c-11e5-9309-44bfbb1cc4ec.png)

Click on View and then on Other Windows>Property Manager.
![78](https://cloud.githubusercontent.com/assets/13789606/10266616/7c4bc85c-6a6c-11e5-9bac-d226b1fea272.png)

Select all projects, right-click on them and then left-click on Add New Project Property Sheet... .
![79](https://cloud.githubusercontent.com/assets/13789606/10266617/7c552758-6a6c-11e5-9622-b1cb47933f53.png)

Write into the Name field

> `GlobalDirectoriesControl.props`

and click Add.
![80](https://cloud.githubusercontent.com/assets/13789606/10266618/7c578a0c-6a6c-11e5-8a18-5ec4e5831dd5.png)

Expand GLideN64, then expand Release|Win32 and right-click on GlobalDirectoriesControl and left-click on Properties.
![81](https://cloud.githubusercontent.com/assets/13789606/10266619/7c59c510-6a6c-11e5-9098-bf5bd1427df7.png)

Click on User Macros and then on Add Macro.
![82](https://cloud.githubusercontent.com/assets/13789606/10266621/7c5e8d16-6a6c-11e5-915e-f98c7ebaa22f.png)

Write into the Name field

> `QTDIR`

and into the Value field.

> `C:\GLideN64\Qt5.6-win32-msvc2015-static\qtbase`

Click OK.
![83](https://cloud.githubusercontent.com/assets/13789606/10266620/7c5df748-6a6c-11e5-8cc0-10ff4d39a62d.png)

Click again on Add Macro.
Write into the Name field

> `Release`

and into the Value field.

> `C:\GLideN64\Plugin\GFX`

_(This is your final GLideN64 output directory and you can put it wherever you want, for example C:\Program Files (x86)\Project64 2.2\Plugin\GFX)_

Click OK.
![84](https://cloud.githubusercontent.com/assets/13789606/10266622/7c5f2e7e-6a6c-11e5-8fd3-63f258778d28.png)

Your User Macros should look now somewhat like this and click Apply.
![85](https://cloud.githubusercontent.com/assets/13789606/10266623/7c6ae8f4-6a6c-11e5-8403-f714fe9e39ce.png)

Click on Solution Explorer and save all your changes by clicking on Save All.
![86](https://cloud.githubusercontent.com/assets/13789606/10266624/7c6d8bfe-6a6c-11e5-9c62-5149c664b7c5.png)

Right-click on Solution 'GLideN64' (3 projects) and left-click on Build Solution or Rebuild Solution.
![87](https://cloud.githubusercontent.com/assets/13789606/10266625/7c707d82-6a6c-11e5-97b2-d37cff639ce1.png)

Check your output log, it should say: 3 succeeded, 0 failed, 0 skipped.
![88](https://cloud.githubusercontent.com/assets/13789606/10266626/7c739576-6a6c-11e5-8920-0bd0705242ec.png)
## Step.8 Cut or Copy and Paste

Cut or Copy and Paste the files from C:\GLideN64\Plugin\GFX into your emulators Plugin directory.
![89](https://cloud.githubusercontent.com/assets/13789606/10415826/84dd8cae-6ffc-11e5-8fa1-f428eff4fd2b.png)
# [Text version] mupen64plus version:

Is anyone interested in mupen64plus version instructions?
# [Complete version] mupen64plus version:

Is anyone interested in mupen64plus version instructions?

**Comment by Cetacea3691** [comment]
rrrrrr

**Comment by Yui12** [comment]
I appreciate the effort despite it being a draft. I'll save this for a future date.

**Comment by purplemarshmallow** [comment]
Nice work maybe it's better to create another wiki page.
Why do you need Python?

**Comment by SigmaVirus** [comment]
WOAH!!!!

This right here is why I use EmuCR for regular updates and not build stuff myself.
Only thing I ever succeeded in building is Dolphin.

Thanks for your efforts though!

**Comment by oddMLan** [comment]
Dunno what you're talking about. This guide makes it look harder than it is; I just followed the steps that are in the current wiki page + I used the latest available gliden64.lib some user provided along with a precompiled zlib library for Windows 8+ and I had no problems compiling the plugin.

And what is Python needed for?

**Comment by purplemarshmallow** [comment]
Yes many steps are not needed you shouldn't need to configure anything in the project properties. Currently this is really confusing. libpng and zlib are included you don't need to care about them. And why Perl?
@SigmaVirus currently this guide is better: https://github.com/gonetz/GLideN64/wiki/Build-From-Source-(Windows)

**Comment by Cetacea3691** [comment]
Python and Perl are needed for Qt and this will be an all-inclusive guide (GlideNUI from scratch + MSVS2015).

**Comment by Cetacea3691** [comment]
[WIP2]
Brave MSVS2015 users may try now the [Complete version] zilmar spec version instructions.
p.s. Because of recent changes there will be one additional project (osal) in GLideN64 which builds straight out of the box ;)

**Comment by tony971** [comment]
Perl doesn't come with mingw32-make.exe. I keep getting errors after inputting

    configure -static -release -platform win32-msvc2015 -static-runtime -c++11 -qt-pcre -opengl desktop -no-angle -no-freetype -no-libpng -no-crt -opensource -nomake tools -nomake examples -nomake tests -mp

into the developer command prompt.

**Comment by Cetacea3691** [comment]
@tony971 
1. Thank you for testing it :)
2. There really shouldn't be a need for an additional MinGW64 or MinGW32 installation, if you have any further issues feel free to leave a comment and I'll tell you how to make a log, so we can debug it.
3. Did you make it thru until the end ? :)

**Comment by tony971** [comment]
I did make it through to the end, but only after adding MinGW to paths. Like I said, mingw32-make.exe isn't included in the Perl installation. Since It's required to build Qt, I needed MinGW.

**Comment by Cetacea3691** [comment]
:thumbsup: for making it thru until the end.
x86_64-w64-mingw32 is actually a part of Strawberry Perl.

**Comment by tony971** [comment]
Right, but the command looks for it to be named mingw32-make. It'll error out if it's not. You might need to include a step to rename it if you don't have MinGW.

**Comment by Cetacea3691** [comment]
Just out of curiosity, did you use make instead of nmake in
> cd C:\GLideN64\Qt5.6-win32-msvc2015-static
> configure -static -release -platform win32-msvc2015 -static-runtime -c++11 -qt-pcre -opengl desktop -no-angle -no-freetype -no-libpng -no-crt -opensource -nomake tools -nomake examples -nomake tests -mp
> y
> nmake
> *

**Comment by theboy181** [comment]
is this 30 page document really needed to build? I don't understand why so much effort is needed.
Will there be a day when you can clone and hit compile in MSVS2013-2015 ?

**Comment by Cetacea3691** [comment]
GLideN64 could indeed be overhauled into a clone and compile solution but I'm not sure about the freetype and Qt licenses and about what direction @gonetz wants to go with the project.
I wouldn't mind overhauling it into a clone and compile solution.

p.s. This 30 page document seems bigger than it is because of the screenshots and the optional libpng and zlib building instructions.

**Comment by theboy181** [comment]
I hope that gonetz will go with the compile solution you  suggested. 

Thanks for the reply too.

**Comment by gonetz** [comment]
I would not mind to keep all external libs in an external repo in form of distributives (e.g. tar.bz)
The only thing, which is needed in main repo is a script file, which will download necessary distributives, unpack somewhere, compile them with proper keys, remove temp files etc.
I can't make such a script  due to lack of time.

**Comment by Cetacea3691** [comment]
What about Qt? I think it would be better if we used our own precompiled build, because of all the dependencies and time it takes to build Qt and update it if necessary for distribution purpose.

p.s. I can make the script :)

**Comment by gonetz** [comment]
I think, QT should be optional (script option):
* either use official precompiled QT dlls (enough for debug purposes)
* or build from official QT sources. People use different compiler versions, so each dev must compile sources for himself. It is long operation, but it need to be done just once.

**Comment by purplemarshmallow** [comment]
I think Qt should be completely optional. So that you can build and use the plugin without UI if you don't have Qt

**Comment by tony971** [comment]
I know that Dolphin keeps Qt as a submodule that builds into externals https://github.com/dolphin-emu/ext-win-qt

**Comment by Marcelo20XX** [comment]
Hi Gonetz, Long time fan of your graphic plugin here...
I second purplemarshmellow idea to make QT completely optional, its a nonsense to download 1Ghz of files to build an UI that can be easily avoided by a proper use of the ini. Yes I know some people don't have the skill to configure the plugin properly without an UI but can we make at least a option in the compile process like #define UI or something like that?

Right now because of the trouble it is to build the Zilmar spec version I can only test your plugin in Mupen64Plus (I need to build it from sources because I have custom code added in for smoother FPS testing)...

So in the meantime can someone here could post a static lib that can be use to compile under MVS2013 that targets WindowsXP? Thanks!!!

**Comment by purplemarshmallow** [comment]
I think this would be ideal. I have a branch: https://github.com/purplemarshmallow/GLideN64/tree/NO_UI

The problem is if you don't link to Qt the plugin can't read any ini files. Qt currently does this. It's a problem the mupen64plus version should be able to read ini files a well

**Comment by Marcelo20XX** [comment]
I understand...I didn't know QT was used to read the inis...
So this would be difficult after all, can you please upload a GlideNUI.lib that is compatible with MVS2013 x86? So I can compile targeting XP...

If I understand you correctly, your branch can compile although it wont read the configuration from inis? If so, then is not a problem because I can set the plugin options in the source to suit my needs ...

**Comment by purplemarshmallow** [comment]
>So this would be difficult after all, can you please upload a GlideNUI.lib that is compatible with MVS2013 x86?

I don't have it

>So I can compile targeting XP...

I don't think this can work. You need to use the same platform toolset for GLideN64 and GLideNUI

>If I understand you correctly, your branch can compile although it wont read the configuration from inis? If so, then is not a problem because I can set the plugin options in the source to suit my needs ...

Yes there's a seperate configuration Release_noUI. You can change the settings in config.cpp. But there's another problem the plugin won't use per-game hacks. Should be easy to fix

**Comment by Marcelo20XX** [comment]
You can compile the plugin if you choose the platform toolset to 120_XP on MVS2013 and use a GlideNUI.lib that was compiled with MVS2013 and the same platform toolset...

I already compiled your Release_noUI and set the config.cpp to my liking, The per-game options is not a problem since I keep separate folders for every game (mind you I like to romhack my games so this measure is necessary)...

Everything worked as expected and now I can compile the plugin again to test it on PJ64, much to my grief is too slow on PJ64 at least for OoT (Kakariko brings the FPS to its knees) and it smooth as butter on Mupen64Plus so I will stick to this emu, thanks for all the help...

**Comment by purplemarshmallow** [comment]
>The per-game options is not a problem

I don't mean per-game options I mean per-game hacks like the subscreen delay fix in OOT or the scoreboard hack in Mario Tennis

>is too slow on PJ64 at least for OoT (Kakariko brings the FPS to its knees)

there's a problem with some gfx drivers. You might need to enable performance mode in your driver settings. Kakariko shouldn't  bring the FPS to its knees

**Comment by tony971** [comment]
> Just out of curiosity, did you use make instead of nmake in
    cd C:\GLideN64\Qt5.6-win32-msvc2015-static
    configure -static -release -platform win32-msvc2015 -static-runtime -c++11 -qt-pcre -opengl desktop -no-angle -no-freetype -no-libpng -no-crt -opensource -nomake tools -nomake examples -nomake tests -mp
    y
    nmake
    *

Nope. I used the code verbatim (well, except with a custom directory). You will need an instruction to rename x86_64-w64-mingw32 to mingw32-make if MinGW isn't installed.

**Comment by tony971** [comment]
I'm still able to build the plugin but building qt encounters an error. Apparently the developer command prompt is looking in the wrong directory for qquickpanel_p.h. It expects it to be in QtLabsTemplates/private/ but it's actually in qtquickcontrols2/src/templates/

**Comment by oddMLan** [comment]
This guide provided to be more useful than I thought.
One observation though, if you are going to compile libpng you have to make sure that libpng > Properties > Configuration Properties - General > Configuration type is set to *Static ibrary (.lib)* since libpng comes as set to Dynamic library (.dll) by default BUT still generates a .lib file (50kb only) for some reason. GLideN64 compiles as normal, no errors surprisingly but the plugin does not load in any emulator. I don't know if it loads if you put libpng.dll in the emulator's directory, probably, didn't try that.
But you want to set that to *Static ibrary (.lib)* so it is statically linked.
However in your screenshot it shows that configuration, you just didn't mention that change in the text.

**Comment by oddMLan** [comment]
Could you adjust the guide to work with the latest Qt (5.8)?  Stuff was moved around, there's no configure command now. I'm lost.

**Comment by gonetz** [comment]
https://github.com/gonetz/GLideN64/wiki/Build-From-Source-(Windows)
