### ISSUE TITLE
A Bug's Life (U) depth compare problem

### ISSUE THREAD

**Issue by oddMLan** [gonetz/GLideN64#743]
Affects the (E) version too

**Missing BG at warning screen**
![bug 1](https://cloud.githubusercontent.com/assets/7278372/10269095/b4d0f0c6-6a80-11e5-9803-8963be8dad4d.png)
**Incorrect level select background**
![bug 2](https://cloud.githubusercontent.com/assets/7278372/10269096/b793bae6-6a80-11e5-82ed-5619f6b57631.png)
**Missing Flik's eyes**
![bug 3](https://cloud.githubusercontent.com/assets/7278372/10269097/bd14cd0c-6a80-11e5-80bc-e8e9ae9a4e0e.png)

All correct with N64 depth compare
![bug 11](https://cloud.githubusercontent.com/assets/7278372/10269101/0a1207d2-6a81-11e5-87a8-b1a89f5e8452.png)
![bug 22](https://cloud.githubusercontent.com/assets/7278372/10269102/0c4026ce-6a81-11e5-9121-85f3686dfa06.png)
![bug 33](https://cloud.githubusercontent.com/assets/7278372/10269103/0e225552-6a81-11e5-8818-f2451c372a7b.png)
But it's a pretty resource-intensive option, I get 40-45 VI/s in main gameplay with no AA.

It also looks correct with Jabo's D3D8. Wonder if he used a hack, or maybe this is a side effect of his more inaccurate emulation.

Glide64 has the same problem, but if you put **zmode_compare_less = 1** in the ini file the symptoms are gone.

There's two ways to approach this:
-Add N64 depth compare to this game's settings in the INI, although it technically needs it in order to show these parts correctly, its use it's very minor. Option is resource-intensive. Requires highest OGL support for the depth shader to work (4.4).
-Maybe this can be done without the depth compare shader, polishing other parts in the graphics emulation process.
-Hack (ugly but maybe the best option considering the use of the depth shader is very minor and affects the speed, and reduces compatibility, or if the second suggestion can't be done)

**Comment by purplemarshmallow** [comment]
#52 same problem?

**Comment by oddMLan** [comment]
Looks like it.

**Comment by gonetz** [comment]
Fixed

**Comment by oddMLan** [comment]
Fixed. And no dirty hacks used! :tada:

**Comment by gonetz** [comment]
Yep, we're lucky here.
