### ISSUE TITLE
Texture Cache breaks on Beetle Adventure Racing

### ISSUE THREAD

**Issue by matthewharvey** [gonetz/GLideN64#744]
After playing Beetle Adventure racing for quite a while, I started to see some textures replaced by black, or some other background colour (one of them was white).
After a little investigation, I found that lowering the size of the texture cache caused the issue to happen much more quickly. What was happening was that the game was creating a whole bunch of textures that were used temporarily and then never using them again. This was filling up the cache. Then, when the cache was full, the _checkCacheSize function was removing textures from one "end" of the map of textures. I can only assume that the "end" to which new textures get inserted is platform dependent. On my platform the removal of textures from the cache was at the same end that they were being inserted, so when the texture cache became full, the textures that were currently on the screen were being removed from the cache, and when the emulator went to render those textures, they had already been removed from the cache (I can only guess on that last part, but it fits the behaviour).

Of course, this can be trivially fixed by changing the end of the cache that textures are removed from, but this will still have occasional corruption. Also, I believe that causes platform dependency issues. The proper solution is to convert the cache to a "least recently used" cache. That will ensure that as long as the cache is large enough, the texture will be properly loaded at render time. I have patches for both of these solutions. I will create a pull request for the lru cache solution in a moment.

**Comment by purplemarshmallow** [comment]
If you're using Mupen64plus you should test with CPU interpreter I know there's a bug in the recompiler that can break this game

**Comment by matthewharvey** [comment]
Thanks for the suggestion. I'm going to publish the pull request, and then give this a try later (I have to go to dinner. My girlfriend said she was hungry quite a while ago :D)

**Comment by matthewharvey** [comment]
Exactly the same behaviour with the CPU interpreter and the cached interpreter.

**Comment by purplemarshmallow** [comment]
I don't have this problem with Project64 how long do I need to play?

**Comment by matthewharvey** [comment]
I moved my texture cache down to 30MB and was able to get the issue without even getting to into a race.

**Comment by matthewharvey** [comment]
Also, I didn't provide platform details.

mupen64plus
Debian Sarge (testing)
Intel HD4000 graphics card using the Mesa OpenGL implementation

**Comment by matthewharvey** [comment]
Fixed with merge request #745
