### ISSUE TITLE
Extreme-G wrong framebuffer effect

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#746]
after selecting a bike
![gliden64_extremeg_000](https://cloud.githubusercontent.com/assets/7283660/10271158/588356b0-6b07-11e5-84a0-e187eb4c58e4.jpg)
z64gl looks more correct but still wrong
![1](https://cloud.githubusercontent.com/assets/7283660/10271159/5c39b7cc-6b07-11e5-986f-3bdaff2db2f6.jpg)

**Comment by purplemarshmallow** [comment]
Fixed in  an experimental branch. Framebuffer to RDRAM
![gliden64_extremeg_002](https://cloud.githubusercontent.com/assets/7283660/10674726/cb9928c0-78fc-11e5-8641-3c477ad5011c.jpg)

**Comment by AmbientMalice** [comment]
What was the difference between the framebuffer branch that fixed this, and the one that got merged? As i understand it, that one was auxiliary, this is primary framebuffer? But isn't the primary framebuffer already sent to RDRAM?

**Comment by purplemarshmallow** [comment]
The branch that showed this image copied everything and this was really slow. Also it did not always work correctly. I had to switch window/fullsceen to get rid of hardware framebuffers

You can try removing this line
https://github.com/gonetz/GLideN64/blob/master/src/FrameBuffer.cpp#L525

And this line
https://github.com/gonetz/GLideN64/blob/master/src/FrameBuffer.cpp#L527

>But isn't the primary framebuffer already sent to RDRAM?

Only if it's address is gDP.colorImage.address. Then the copy color option will copy it. But for example the pause menu background in OOT also does not get copied. The plugin always uses hardware framebuffer textures in this case but in ExtremeG the hardware framebuffer code does not work correctly

**Comment by gonetz** [comment]
Seems to be fixed. Please test

**Comment by AmbientMalice** [comment]
Seems fixed.
