### ISSUE TITLE
Glitchy text in perferct dark on Android Adreno devices

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#759]
Text is glitchy on Android Adreno devices in perfect dark. Here is a screenshot:

https://drive.google.com/file/d/0B57Ioy26LWegamUzd0hMTkhyRnM/view?usp=docslist_api

**Comment by gonetz** [comment]
Looks the same as #280: PD has garbled text under Linux.

**Comment by fzurita** [comment]
Hmmm... How is text like this rendered? Are there any areas of the plugin code that would be useful to look at?

**Comment by gonetz** [comment]
Any text is rendered as set of textured polygons. It can be a combiner issue, e.g. wrong tile is used. May also be a texture loading problem. Need to find, which texture type is used for text. Most likely it is 4bit I or CI texture.

**Comment by gonetz** [comment]
Fixed

**Comment by fzurita** [comment]
Just checked, it's fixed
