### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by tony971** [gonetz/GLideN64#760]
Playing more recent revisions of GlideN64 has given me crashes on ROM load. I finally turned on the debugger and got this:

    Unhandled exception at 0x0FF10899 (GlideN64.dll) in Project64.exe 0xC000005: Access violation writing location 0x747426C.
    
    If there is a handler for this exception, the program may be safely continued.

This happened while booting Mario Kart 64.

**Comment by SigmaVirus** [comment]
Hmm strange, I can't seem to replicate this on any of the newer revisions.
Which version of Project64 are you using and which OS are you on?

I'm using the latest GLideN64 and Project64 on Windows 8.1 with Update 3 and every game loads fine.

**Comment by tony971** [comment]
Actually, I built GLideNUI from scratch and the problem disappeared.
