### ISSUE TITLE
Goldeneye 64 "incorect bullet flares"

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#768]
![capture](https://cloud.githubusercontent.com/assets/9299743/10569637/176a6f74-75de-11e5-9f6d-b3d0ef3f43f4.PNG)

**Comment by purplemarshmallow** [comment]
I don't think this is a problem with AA
For me bullets break it I switch window/fullscreen

**Comment by SigmaVirus** [comment]
I'm pretty sure this ain't related to AA because I get the same result as @purplemarshmallow when I switch between windows/fullscreen and I use no AA.

It's a hit and miss kinda thing, sometimes it works as expected sometimes it don't and that's exactly what is happening on that image.

**Comment by Frank-74** [comment]
I get this sometimes with Jabo's as well.  It may be a PJ64 core issue.  Protect Memory used to fix it for me.

Does it happen with Protect Memory enabled?

**Comment by purplemarshmallow** [comment]
I tested with CPU interpreter and it does not happen anymore. Most likely it's a core issue

**Comment by purplemarshmallow** [comment]
No I managed to reproduce this problem with CPU interpreter. I guess something is wrong with OpenGL context creation

**Comment by Frank-74** [comment]
No, because it sometimes happens in D3D also.  Seems to only happen at certain resolutions.

**Comment by gonetz** [comment]
Seems to be core issue.
