### ISSUE TITLE
Mario Tennis 64's Versus Screen Issue

### ISSUE THREAD

**Issue by oOSuperMarioOo** [gonetz/GLideN64#771]
I'm not sure why this is happening when using GlideN64, but whenever I start a match, the VS screen will show only one character, not two (https://www.youtube.com/watch?v=4haFn88blRc). If I only see one character on the VS screen, who am I even going against, anyways?

**Comment by olivieryuyu** [comment]
yep seems you are right

**Comment by gonetz** [comment]
This is another crazy frame buffer effect from Nintendo programmers. One of the hardest to emulate.
![gliden64_mariotennis_000](https://cloud.githubusercontent.com/assets/8983092/18225612/d36dd640-7220-11e6-8a29-7dbc66568bd9.jpg)

**Comment by purplemarshmallow** [comment]
This somehow works with z64gl but not 100% correct. The white line is missing

![1](https://cloud.githubusercontent.com/assets/7283660/18226949/ca43fbc2-7215-11e6-85e8-51905ba7ff31.jpg)

**Comment by gonetz** [comment]
This is cool result. Plugin should be able to draw to depth buffer in order to show both players.

**Comment by gonetz** [comment]
Fixed

**Comment by oddMLan** [comment]
It works! Hurray! :grin: 
It's one of those really broken effects that had been never solved before in a HLE plugin

Now if it there was a way to fix the subscreen delays without using cheats...

**Comment by gonetz** [comment]
It is a frame buffer related issue, HLE/LLE does not matter there. Now it works with GLideN64 in both HLE/LLE modes.

**Comment by olivieryuyu** [comment]
it should be closed

**Comment by fzurita** [comment]
This seems to be broken again, at least I can't get it to work in Android. Any specific settings needed to get this vs screen working correctly?

**Comment by gonetz** [comment]
Shader depth write must be enabled.

**Comment by fzurita** [comment]
Ok, thanks.

**Comment by fzurita** [comment]
Yep, that did the trick.
