### ISSUE TITLE
Shader Storage Breaks Fog (Ocarina of Time)

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#775]
![gliden64_the_legend_of_zelda_000](https://cloud.githubusercontent.com/assets/10704701/10714339/81e3bd2a-7b37-11e5-8e91-641a81fe5a70.jpg)

![gliden64_the_legend_of_zelda_002](https://cloud.githubusercontent.com/assets/10704701/10714340/86bb36e8-7b37-11e5-89cb-8bbd06576e25.jpg)

The fog breaks if you go fullscreen or change resolution. Doing something to refresh textures, such as 3-point or enabling/disabling mipmapping, will bring it back.

**Comment by gonetz** [comment]
Yep, something wrong happens.

**Comment by gonetz** [comment]
Hopefully fixed:
https://github.com/gonetz/GLideN64/commit/868b708f710e7233aaca41f0b3f4e6fd85f12a32

Binaries to test:
https://drive.google.com/file/d/0B0YqMPjGo3B2NGVMZWo3MHRQMWc/view?usp=sharing

**Comment by AmbientMalice** [comment]
The fog does seem to occasionally disappear temporarily when I raise AA settings while ingame, but it comes back. So this is fixed.
