### ISSUE TITLE
Pokemon Snap Oak's check does not work

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#777]
Now this is the only thing that keeps Pokemon Snap from being playable. Depth buffer based effect. Correct with Glide64, Jabo's plugin and Direct64. There's already #547 but I thought it's better to have seperate issues.
![gliden64_pokemon_snap_000](https://cloud.githubusercontent.com/assets/7283660/10714901/2953b572-7b03-11e5-8eec-525397c6c7d2.jpg)

**Comment by purplemarshmallow** [comment]
The camera in Majora's Mask works similar. In Majora's Mask pictures are detected. Should be possible to get this working as well.

**Comment by AmbientMalice** [comment]
I'm no expert, but based on what happened with Dolphin, this is very likely a float rounding error, correct?

**Comment by vgturtle127** [comment]
@purplemarshmallow @AmbientMalice That or Professor Oak is really bad at spotting Pokemon.

**Comment by purplemarshmallow** [comment]
>I'm no expert, but based on what happened with Dolphin, this is very likely a float rounding error, correct?

I don't think this problem here is as simple as the problem Dolphin had. The N64 uses int and GLideN64 uses float for depth values this costs accuracy. I think that's the reason why it's not working. This game needs accurate values.

**Comment by AmbientMalice** [comment]
@purplemarshmallow Does the Wii natively use integer or floats?

**Comment by purplemarshmallow** [comment]
The Wii uses floats and dolphin uses floats as well. The reason why they have rounding errors is because depth on a Wii goes from -1 to 0 and OpenGL uses -1 to 1. They have to deal with this difference in hardware. GLideN64's problem is different.

**Comment by gonetz** [comment]
I just tested the first course, all pokemons on my pictures were correctly recognized.
Settings: 
* color buffer copy: sync
* depth buffer copy: software

**Comment by purplemarshmallow** [comment]
Still not working for me
Software depth buffer rendering in Glide64 works correctly here but software depth buffer rendering in GLideN64 is incorrect here

![gliden64_pokemon_snap_000](https://cloud.githubusercontent.com/assets/7283660/18044602/f78c4f3a-6dce-11e6-88ca-adf0b2daec57.jpg)

**Comment by AmbientMalice** [comment]
Something very interesting. If you enable aux FB to RAM, take the photos, and then turn off aux FB to RAM before leaving the course, Oak will mark the photographs correctly. They will render incorrectly, but obviously the depth buffer data is correct. However, if Aux FB to RAM is enabled while marking, none of the photos will be recognised. Also, accurate N64 depth seems to make the game think pictures of Pokemon are pictures of Pokemon Signs.

![gliden64_pokemon_snap_000](https://cloud.githubusercontent.com/assets/10704701/18815880/2cf0e82c-8380-11e6-8193-6446b033233c.png)

**Comment by AmbientMalice** [comment]
After recent depth buffer fixes, the photos render correctly during check. LLE doesn't work properly, but check seems to work fine with Aux FB to RAM disabled. Aux FB to RAM must be overwriting something. It's worth noting that Aux FB has corruption issues in other games. https://github.com/gonetz/GLideN64/issues/882

![gliden64_pokemon_snap_000](https://cloud.githubusercontent.com/assets/10704701/18841906/a34fef64-8456-11e6-941d-b4f88e85134e.jpg)

**Comment by purplemarshmallow** [comment]
https://github.com/gonetz/GLideN64/blob/5d7c02f7d11be277af625a630949d410aae79209/src/FrameBuffer.cpp#L549

removing these lines fixes this issue but it breaks the portraits in Knockout Kings

**Comment by olivieryuyu** [comment]
i cannot get portrait in Knockout Kings, how do you do that?

**Comment by AmbientMalice** [comment]
@purplemarshmallow Does it also fix broken shadows in games like Conker and Turok with aux FB enabled?

**Comment by purplemarshmallow** [comment]
@olivieryuyu enable copy aux but only one portrait will show up #350 

@AmbientMalice In Turok 3 the shadows appear. But these are HWFB textures, it will just mask the bug

**Comment by AmbientMalice** [comment]
>In Turok 3 the shadows appear. But these are HWFB textures, it will just mask the bug

Can you explain what you mean by this? In Turok 3, the shadows render as hard black shadows normally. Copying aux to RAM gives them soft edges, but the shadows rapidly corrupt. How do they look with that line removed? What exactly is removing that line doing? It looks like it's forcing a buffer clear.

**Comment by purplemarshmallow** [comment]
>What exactly is removing that line doing?

With these lines the plugin copies aux buffers instantly. If you remove these lines it will keep buffers on the GPU and copy them later at fullsync command.

>How do they look with that line removed?

same as with copy aux disabled, but in low res
![turok3](https://cloud.githubusercontent.com/assets/7283660/20330982/bed4e0a0-aba2-11e6-8df0-515ca4f3be84.jpg)

**Comment by purplemarshmallow** [comment]
So there is going to be a new release soon?
Maybe it would be a good idea to add a hack to get Pokemon Snap playable. GLideN64 could be the first plugin which makes this game fully playable

**Comment by gonetz** [comment]
Please remind me, which hack makes Pokemon Snap playable?

**Comment by purplemarshmallow** [comment]
https://github.com/gonetz/GLideN64/blob/5d7c02f7d11be277af625a630949d410aae79209/src/FrameBuffer.cpp#L549

removing these lines makes Oaks check work. And the ini settings need to be corrected. Enable copy color sync, copy aux and software depth buffer

**Comment by AmbientMalice** [comment]
Does photographing pokemon work with those lines removed, though? Also, fixing the underlying problem would probably be ideal. But that's just IMO.

**Comment by gonetz** [comment]
@purplemarshmallow could you make necessary changes and a pull request?

**Comment by purplemarshmallow** [comment]
#1272

**Comment by fzurita** [comment]
@gonetz This seems to be broken again after the refactor. I'm getting complains from people that it doesn't work anymore.

**Comment by fzurita** [comment]
The hack seems to still be in the correct place, and it looks identical. So I'm not sure what's going on.

**Comment by loganmc10** [comment]
@fzurita I just played through the whole first level on Linux. Everything worked, taking pictures, Prof Oak's check, etc. The only thing that doesn't work is displaying the red dot, which requires ```frameBufferEmulation\copyFromRDRAM=1```, but that setting causes flickering. The red dot thing is just a cosmetic thing though, the game is fully playable.

**Comment by fzurita** [comment]
This was a while back. I haven't heard people complaining about this for a while. So maybe it's fixed.

**Comment by rez-** [comment]
Not working with latest build :-(

![afbeelding](https://user-images.githubusercontent.com/10398036/32470178-a8a915cc-c356-11e7-879d-cf417d7a6492.png)

**Comment by fzurita** [comment]
Do you have a GLideN64.custom.ini file?

**Comment by rez-** [comment]
Yeah, placed it in the root m64p folder and in the config folder... perhaps its an issue with m64p? will investigate more tonite

**Comment by AmbientMalice** [comment]
There's a slim chance this was broken again by the depth buffer fixes. @rez- What version of m64p are you using?

**Comment by loganmc10** [comment]
Broken by bd10c7a788caf52b13989a555661f1d93043e666

**Comment by rez-** [comment]
your right loganmc10! i just reverted that commit, and it is working fine now! 👍

**Comment by rez-** [comment]
Btw, Vililante 8 is working kinda without that commit (where it was for):

windowed mode:
![afbeelding](https://user-images.githubusercontent.com/10398036/32576328-f07a9340-c4d6-11e7-960b-3a180747a343.png)

when i switch to fullscreen the black snow is gone, but the performance is horrible/laggy:
![afbeelding](https://user-images.githubusercontent.com/10398036/32576373-0e0f8a32-c4d7-11e7-8f79-ad3d2f1c4b34.png)

and when i switch back to windowed mode everything seems to work fine:
![afbeelding](https://user-images.githubusercontent.com/10398036/32576404-1f9602b8-c4d7-11e7-85a5-b3326d85de96.png)

**Comment by rez-** [comment]
When i start in fullscreen the sky is black:
![afbeelding](https://user-images.githubusercontent.com/10398036/32576551-935a30d4-c4d7-11e7-8b80-d5ca4954ea60.png)

when i switch to windowed mode everything is fine:
![afbeelding](https://user-images.githubusercontent.com/10398036/32576574-a0495932-c4d7-11e7-955c-464f11b14dcb.png)

**Comment by rez-** [comment]
By the way, when I not revoke that commit, vigilante is still laggy in fullscreen (but not in windowed mode)... but it does solve the black polygons

**Comment by fzurita** [comment]
Probably new issues should be made. Gonetz may miss this since the issue is closed.

**Comment by gonetz** [comment]
I don't miss it.

**Comment by AmbientMalice** [comment]
This has possibly regressed recently? I was testing today, and can't get any photographs to be recognised.

**Comment by gonetz** [comment]
May be. Could you find the last build where it worked?

**Comment by loganmc10** [comment]
I just tested the latest master and it seems to work fine for me.

**Comment by Kidboy17** [comment]
Pokemon has regression again. Can not choose photos for Professor Oak to check with newest WIP (Master+FB). 
It did work with this WIP 26 days ago, https://drive.google.com/file/d/1vQiGjOGdMbwc5P6s7xl3U4VzAYL0AGkW/view
![gliden64_pokemon_snap_000](https://user-images.githubusercontent.com/37382324/46515571-82dc1880-c819-11e8-81d9-18811d703249.png)

Does not work with this build, https://drive.google.com/file/d/1SBAZ9OqaBkejDyKzOaW2dEkENdNZeJiX/view
![gliden64_pokemon_snap_001](https://user-images.githubusercontent.com/37382324/46515593-ab641280-c819-11e8-8f4b-cf5820ed9864.png)

**Comment by Kidboy17** [comment]
Newest WIP (Master+FB) has fixed this issue. Nicely done Gonetz!

**Comment by retropieuser555** [comment]
Hi all I hate to be a pain but I believe this game has regressed again. Getting the same error unfortunately

**Comment by agademer** [comment]
Four year later and still the same bug. Can't validate the photo in Oak's lab.
Mupen64Plus-Next (Ipad or steam retroarch last version, default parameters)

Does anyone know if I need to configure some options ? or wait for some improbable patch ?

I was so eager to show this game to my daughter... :(

**Comment by Jj0YzL5nvJ** [comment]
> Can't validate the photo in Oak's lab.

Use `ParaLLEl RDP` or `Angrylion RDP*`, those are the only ones that work properly with Oak.

**Comment by TCaptainPancake** [comment]
Doesnt work still cant choose the photos I want to show him

**Comment by 1024jon** [comment]
> Four year later and still the same bug. Can't validate the photo in Oak's lab.
> Mupen64Plus-Next (Ipad or steam retroarch last version, default parameters)
> 
> Does anyone know if I need to configure some options ? or wait for some improbable patch ?
> 
> I was so eager to show this game to my daughter... :(

I got this to work by changing the RDP Plugin to ParaLLEI-RDP .  Under the options for that, I changed Dither SSAA framebuffer effects to ON.  Then I changed the RSP Plugin to ParaLLEI.  After restarting retroarch it worked correctly.  GL

**Comment by davidzenisu** [comment]
Thanks @1024jon thiw worked like a charm! Was worried for a second because the default upscale ratio was set to x1 by default after the change but cranking it back up to x4 and everything looked and played as before minus any of the former issues :)
