### ISSUE TITLE
Majora's Mask - bad lighting in West Clock Town

### ISSUE THREAD

**Issue by hertz4** [gonetz/GLideN64#778]
![snap1](https://cloud.githubusercontent.com/assets/11461551/10779840/400bc86a-7d04-11e5-8e9c-13280d200a67.png)
![snip2](https://cloud.githubusercontent.com/assets/11461551/10779838/400a6416-7d04-11e5-9503-44239b60bf5a.PNG)

It's too dark, and patches of lighting will often appear and disappear as the camera moves. This is not like a real n64. You have to play it to fully understand what I mean.

Rice video gave an effect almost identical to a real console:
![snap3](https://cloud.githubusercontent.com/assets/11461551/10779839/400b82b0-7d04-11e5-8bc5-f5ae8343e9a1.png)
![snip4](https://cloud.githubusercontent.com/assets/11461551/10779837/400847b2-7d04-11e5-8add-d2c14d0f19b5.PNG)

The lighting doesn't change as the camera moves, and there's sort of a shadow underneath things where there should be.

**Comment by purplemarshmallow** [comment]
HLE bug. Likely same problem as #681 . 2nd screenshot is correct (LLE)
![gliden64_zelda_majora s_mask_003](https://cloud.githubusercontent.com/assets/7283660/10782626/3d38040c-7d52-11e5-98b9-749b67efecee.jpg)
![gliden64_zelda_majora s_mask_004](https://cloud.githubusercontent.com/assets/7283660/10782628/3f80cdde-7d52-11e5-8b3b-f06d81708037.jpg)

**Comment by gonetz** [comment]
Yes, it is HLE bug. No, it is not related to #681

The game uses undocumented non-standard lighting method. I tried to guess how it works, but my implementation is not perfect. If Rice video does it better, it can be used as reference.

**Comment by gonetz** [comment]
I've made Zelda MM point lighting using Rice Video method. Please check, is it better:
https://drive.google.com/file/d/0B0YqMPjGo3B2eWJSU25JeWZjb2c/view?usp=sharing

Note: Rice Video algorithm is also imperfect. Plus I could make a mistake in its implementation.

**Comment by 44100hertz** [comment]
I couldn't seem to get that version of the plugin to work...
UI-Console Error: Specified Video plugin not found: GLideN64.dll

The windows mupen64plus is 32bit, is this the issue?

**Comment by gonetz** [comment]
This build is for Zilmar-specs plugins.
Please don't waste your time on this build, it is incorrect.
I'll upload a fix when it will be ready.

**Comment by death-droid** [comment]
@gonetz the Rice Video code you looked at uses the older version of the point light from the looks of it, the original implementation in Rice Video was very hacky.

The Daedalus team's lighting should be correct.
https://github.com/salvy/daedalus/blob/master/Source/HLEGraphics/BaseRenderer.cpp#L988

**Comment by gonetz** [comment]
I'll check it, thanks!

**Comment by gonetz** [comment]
Hmm, pretty much the same as my current code. There are some nuances though.

**Comment by gonetz** [comment]
After careful reading of the code I can say that Daedalus HLEGraphics uses the same algorithm as mine. I guess, it also was taken from Glide64. Daedalus code looks more clear but differs only in some optimization details and works the same as Glide64/GLideN64.

**Comment by death-droid** [comment]
Ahhhh thats interesting :), Salvy swore by it being the proper implementation of the lighting from memory.
Interesting to know though though!

**Comment by gonetz** [comment]
You may compare the code yourself. I know that code because I wrote it :)
I hoped that Daedalus team fixed it, but no, they just cleared it.

**Comment by olivieryuyu** [comment]
it seems clear for me that it is a customer ucode In the debug string of the game, you can find this (https://tcrf.net/Proto:The_Legend_of_Zelda:_Majora's_Mask/Debug_Version/Console_Output_Strings)

**G_LIGHTING_POSITIONAL** 

Which shows that the light are not directional but positional (=point lighting?).

There is no reference in the manual or in gbi.h of this G_LIGHTING_POSITIONAL (damn!!)

I tried to find if SGI published some docs (not N64 related) on the positional light.

I could find this for the time being: https://www.opengl.org/sdk/docs/man2/xhtml/glLight.xml

May be a good candidate for ucode decryting.

**Comment by olivieryuyu** [comment]
By the way i found this information on http://wiki.cloudmodding.com/mm/Microcode#F3DZEX.

Microcode Dump Feature

In the event of a fatal error, the Majora's Mask Debug Rom is capable of generating a dump of the entire microcode pipeline for the current frame, sending it to the IS64. This dump can be triggered with the following cheat code: 800A5A20 0000. Once the dump begins, it's recommended that you set the value back to 0001, since otherwise the game will constantly generate a dump.

Would the dump help to get an exact idea on how the game manage lights?

**Comment by LegendOfDragoon** [comment]
> Would the dump help to get an exact idea on how the game manage lights?

I already dumped and uploaded microcode from Zelda MM, although there's a chance it isn't a complete dump. If it's missing the lighting microcode, I would happily collect whatever microcodes I'm missing. Can you upload a PJ64 2.3 compatible savestate (part where the lighting happens?

**Comment by Frank-74** [comment]
@LegendOfDragoon 
>  PJ64 2.3 compatible savestate

I fixed it so old and new savestates work.  Current build of 2.3 should load old filenames compressed or uncompressed.

**Comment by olivieryuyu** [comment]
@LegendOfDragoon: short question: how do you dump the microcodes? I started some work on the ones you posted, there are very clearn :)

**Comment by Gillou68310** [comment]
Here's the complete dump for majora's mask: 
[Zelda_Majoras_Mask.txt](https://github.com/gonetz/GLideN64/files/643625/Zelda_Majoras_Mask.txt)

It's based on the F3DEX2 NoN fifo ucode, here's the dump (taken from n64sdk using objdump):
[gspF3DEX2.NoN.fifo.txt](https://github.com/gonetz/GLideN64/files/643626/gspF3DEX2.NoN.fifo.txt)

Here's the disassembly for both ucodes:
[Zelda_Majoras_Mask.txt](https://github.com/gonetz/GLideN64/files/643628/Zelda_Majoras_Mask.txt)
[gspF3DEX2.NoN.fifo.txt](https://github.com/gonetz/GLideN64/files/643629/gspF3DEX2.NoN.fifo.txt)

The same disassembly without program counter for easier comparing:
[gspF3DEX2.NoN.fifo.txt](https://github.com/gonetz/GLideN64/files/643631/gspF3DEX2.NoN.fifo.txt)
[Zelda_Majoras_Mask.txt](https://github.com/gonetz/GLideN64/files/643630/Zelda_Majoras_Mask.txt)

If you do a winmerge between the 2 above files you can see that the biggest difference is located in "overlay start: 2" which is probably the lighting overlay (to be confirmed).

**Comment by LegendOfDragoon** [comment]
I modified PJ64's RSP so that it automatically dumps all of IMEM, every time the recompiler detects a unique CRC, while also checking for the task types, since I'm usually only interest in 1 task type at a given time.

Problem with my method is that it only dumps the microcodes that the game has currently loaded. I want to look into finding the microcode in the ROM and just dumping that. I think it would be much nicer that way. Interestingly, some games seem to actually compress their microcode (like Gauntlet).

**Comment by Gillou68310** [comment]
> I modified PJ64's RSP so that it automatically dumps all of IMEM, every time the recompiler detects a unique CRC, while also checking for the task types, since I'm usually only interest in 1 task type at a given time.

@LegendOfDragoon I was doing the same at first. Now I'm dumping the complete ucode directly from RDRAM before it's beeing loaded into IMEM. The problem with this method is that you need to find the overlay description into the .data section in order to find the real program counter for overlays.

**Comment by olivieryuyu** [comment]
@LegendOfDragon: would it be ok to share this rsp pls? Thx!

**Comment by LegendOfDragoon** [comment]
>@LegendOfDragon: would it be ok to share this rsp pls? Thx!

Sure. When i get the time, i'll clean up the code and send it. Hopefully I'm productive today :smile: .

>@LegendOfDragoon I was doing the same at first. Now I'm dumping the complete ucode directly from RDRAM before it's beeing loaded into IMEM. The problem with this method is that you need to find the overlay description into the .data section in order to find the real program counter for overlays.

Interesting. What made you decide to do that? I still think looking at the ROM data is the most ideal way, but your method could help lead to something.

**Comment by Gillou68310** [comment]
The main idea is to get the whole ucode in one dump and not miss overlays that are not loaded yet. Also it's a lot easier to compare such a dump with a dump of the n64sdk ucodes created with objdump.

**Comment by theboy181** [comment]
Interesting.

**Comment by olivieryuyu** [comment]
I obtain the same ucode with Nemu. However the end address must be extended to not miss overlays. It is quite easy to spot where it ends (mostly goes to nope opcode).

[Zelda Ucode - Nemu.xlsx](https://github.com/gonetz/GLideN64/files/717916/Zelda.Ucode.-.Nemu.xlsx)

**Comment by Gillou68310** [comment]
I took a quick look at the point lighting part of the ucode and I noticed that when the ```light address + 3``` (pad0 in the Light structure) equal 0, the light intensity is computed using the normal lighting method ```DotProduct( &_vtx.nx, &gSP.lights[i].ix );```.

```
struct Light
{
    u8 pad0, b, g, r;
    u8 pad1, b2, g2, r2;
    s8 pad2, z, y, x;
};
```

The following code seems to produce somehow correct lighting. Also I didn't check the ucode part where  ```gSP.lights[l].pad0 != 0``` so the ```light_intensity``` computation might be wrong.

```
static void gSPPointLightVertex_majora(SPVertex & _vtx, float * _vPos)
{
    assert(_vPos != nullptr);

    float light_intensity = 0.0f;
    _vtx.HWLight = 0;
    _vtx.r = gSP.lights[gSP.numLights].r;
    _vtx.g = gSP.lights[gSP.numLights].g;
    _vtx.b = gSP.lights[gSP.numLights].b;
    for (u32 l=0; l < gSP.numLights; ++l) {
        if(gSP.lights[l].pad0 != 0)
        {
            float lvec[3] = {gSP.lights[l].posx, gSP.lights[l].posy, gSP.lights[l].posz};
            lvec[0] -= _vPos[0];
            lvec[1] -= _vPos[1];
            lvec[2] -= _vPos[2];
            const float light_len2 = lvec[0]*lvec[0] + lvec[1]*lvec[1] + lvec[2]*lvec[2];
            const float light_len = sqrtf(light_len2);
            const float at = gSP.lights[l].ca + light_len/65535.0f*gSP.lights[l].la + light_len2/65535.0f*gSP.lights[l].qa;
            if (at > 0.0f)
                light_intensity = 1/at;//DotProduct (lvec, nvec) / (light_len * normal_len * at);
            else
                light_intensity = 0.0f;
            if (light_intensity > 0.0f) {
                _vtx.r += gSP.lights[l].r * light_intensity;
                _vtx.g += gSP.lights[l].g * light_intensity;
                _vtx.b += gSP.lights[l].b * light_intensity;
            }
        }
        else{
            f32 intensity = DotProduct( &_vtx.nx, &gSP.lights[l].ix );
            if (intensity < 0.0f)
                intensity = 0.0f;
            _vtx.r += gSP.lights[l].r * intensity;
            _vtx.g += gSP.lights[l].g * intensity;
            _vtx.b += gSP.lights[l].b * intensity;
        }
    }
    if (_vtx.r > 1.0f) _vtx.r = 1.0f;
    if (_vtx.g > 1.0f) _vtx.g = 1.0f;
    if (_vtx.b > 1.0f) _vtx.b = 1.0f;
}
```

**Comment by olivieryuyu** [comment]
woa amazing! merci!

**Comment by gonetz** [comment]
I updated point light calculations: eae155d7419bc

Point lighting still works incorrect. Obviously, the point light part of code has errors.

**Comment by Gillou68310** [comment]
Well the point light part is not easy to understand because it has a lot of vector instructions so this is not going to be easy to fix unfortunately. At least we did one step forward ;-)

**Comment by standard-two-simplex** [comment]
Hi guys, two questions.

What is the division by 65535 for? Passing from fixed point to float? If so, when calculation the attenuation ```at``` I think that the term ``` light_len2 ``` should be divided by it twice, because you have previously squared this factor (when calculation ```light_len2```). 

Are you sure that the LLE scene is correct? I checked with angrylion and it is much darker.

This said, I tried by writing the formula in the comments (for regular point lighting) using the attenuation as I proposed and the result was quite similar to angrylions. The colors are a little bit different but the lights intensify in the correct places.

I also think that when calculation the dot product ```lvec``` should be used instead of ```gSP.lights.i_xyz[l]```.

This is the code I tried. Please, try and compare with the current version.

```
static void gSPPointLightVertex_default(SPVertex & _vtx, float * _vPos)
{
	assert(_vPos != nullptr);
	float light_intensity = 0.0f;
	_vtx.HWLight = 0;
	_vtx.r = gSP.lights.rgb[gSP.numLights][R];
	_vtx.g = gSP.lights.rgb[gSP.numLights][G];
	_vtx.b = gSP.lights.rgb[gSP.numLights][B];
	for (u32 l=0; l < gSP.numLights; ++l) {
		float lvec[3] = {gSP.lights.pos_xyzw[l][X], gSP.lights.pos_xyzw[l][Y], gSP.lights.pos_xyzw[l][Z]};
		lvec[0] -= _vPos[0];
		lvec[1] -= _vPos[1];
		lvec[2] -= _vPos[2];
		const float light_len2 = lvec[0]*lvec[0] + lvec[1]*lvec[1] + lvec[2]*lvec[2];
		const float light_len = sqrtf(light_len2);
		const float at = gSP.lights.ca[l] + light_len/65535.0f*gSP.lights.la[l] + light_len2/(65535.0f*65535.0f)*gSP.lights.qa[l];
		const float normal_len = sqrtf(DotProduct(&_vtx.nx, &_vtx.nx));
		if (at > 0.0f)
			light_intensity = DotProduct(lvec, &_vtx.nx)/(light_len*normal_len*at);
		else
			light_intensity = 0.0f;
		if (light_intensity > 0.0f) {
			_vtx.r += gSP.lights.rgb[l][R] * light_intensity;
			_vtx.g += gSP.lights.rgb[l][G] * light_intensity;
			_vtx.b += gSP.lights.rgb[l][B] * light_intensity;
		}
	}
	if (_vtx.r > 1.0f) _vtx.r = 1.0f;
	if (_vtx.g > 1.0f) _vtx.g = 1.0f;
	if (_vtx.b > 1.0f) _vtx.b = 1.0f;
}
```

**Comment by gonetz** [comment]
@standard-two-simplex You right about division by 65535? It is conversion from fixed point to float. Your fix is wrong though. light_len2 must be divided by 65535 before light_len calculation. I fixed it and point light works more-less correct now. I tried your code for light_intensity, it works much worse than the current one.

**Comment by standard-two-simplex** [comment]
@gonetz Which places are you talking about? I was testing the code in Majora's Mask west clock town. Which games need ``` light_intensity = 1/at```?

**Comment by gonetz** [comment]
This code is for Majora's Mask only.

**Comment by gonetz** [comment]
![point_light](https://cloud.githubusercontent.com/assets/8983092/25772772/3de84d70-329c-11e7-90e3-f931b315f056.png)

**Comment by standard-two-simplex** [comment]
Oh, I tried during the day.
I have to leave now. I see worse effects with current master than the changes I proposed so I'm puzzled. We shall talk later today or tomorrow.

**Comment by gonetz** [comment]
I guess, we mean different state of "current master". I mean that adding your fix for light_intensity to 45139a60d54c makes result much worse.

**Comment by standard-two-simplex** [comment]
I just tested the build you posted in the WIP thread. That build doesn't reproduce the intensifying effects when walking certain areas. Try walking near the bank keeper during the day to see what effect I'm talking about.

The effect can be seen in LLE, but it is not present in HLE. Using the dot product produces this effect, but the intensifying factor must be calculated correctly, I think.

**Comment by gonetz** [comment]
It returns us to the starting point: RSP asm need to be decoded to do the calculations correctly.

**Comment by aroenai** [comment]
Is it just me or do there seem to be a lot of lighting glitches and stuttering (particularly at spots where the lighting glitches are present/lighting noticeably changes) in East Clocktown after this change? At work so i can't post a screenshot at the moment.

**Comment by CornN64** [comment]
Would it be possible to inject some simple numbers in the LLE to see what the numeric result would be?
For example setting
ca=1 la=0 qa=0 then compare to ca=2 la=0 qa=0 to figure out how "ca" scales. 
Then try the same procedure using "la" and  last with "qa"

**Comment by mudlord** [comment]
I would have thought with point lighting in OpenGL you would get the "length" of the light vector (can easily be done in OpenGL or one of the many math/matrix libraries for C/C++, like gb_math.h and GLM), and then normalize the light vectors and normals.


I wonder why Nintendo did the lighting in the way presented in their ucode though o.o.

**Comment by gonetz** [comment]
> Would it be possible to inject some simple numbers in the LLE to see what the numeric result would be?

No. 'Lighting' is HLE level notion. LLE works with ready vertex colors. It is possible to print vertex colors for HLE and LLE, and try to guess how to manipulate HLE input data to get LLE result.

**Comment by Nerrel** [comment]
I just wanted to add that this issue also happens in a much worse form at the very start of the game, in the room with all the deku flowers.  It's blacked out to the point of barely being able to see anything.
LLE:  https://c1.staticflickr.com/5/4276/34831460421_b0f96b16a8_o.jpg
HLE: https://c1.staticflickr.com/5/4223/34799514792_31455b2543_o.jpg

**Comment by olivieryuyu** [comment]
just started to have a look at the specific part of light in Zelda MM. At first sight, from the current matrix a new matrix seems to be created within the VU. I would think it changes from 4x4 to 3x3. I would think it would be what is explained here: 

https://www.tomdalling.com/blog/modern-opengl/06-diffuse-point-lighting/

with the Matrix Transformation Of Normals

Just a wild guess for the time being

**Comment by olivieryuyu** [comment]
Can someone explain me in the simplest way possible the VRCP and VRSQ RSP instructions?

I cannot figure out how it works :(

How for instance can you have the reciprocal of 0x0035 = 0x4200

I am lost :(

**Comment by fzurita** [comment]
Are you saying that the reciprocal operation on 0x0035 results in 0x4200?

**Comment by olivieryuyu** [comment]
@fzurita 

For VRCP:

It is the lower 16 bits indeed of the 32 bits reciprocal divided by 2 and rounded in a weird way. Reciprocal of 0x35 is 0x026A439F >>  1. 0x439F seems to be rounded by 0x4200 in PJ64.

At least now I can understand somehow the operations carried out.

Now I need to understand VRSQ, which is the reciprocal of the square root.

**Comment by fzurita** [comment]
Wow, that's confusing. Scaling factor is 3.0517578e-05. So, 0x1/0x35 = 0x13521CF. We then have to multiply by 2 to get 0x26A439E.

**Comment by Gillou68310** [comment]
Yep for VRCP the radix point is right shifted by one. S15.16 format becomes S16.15 I agree this is confusing because you'll have to wait for a subsequent multiply instruction to have the correct value.

**Comment by LegendOfDragoon** [comment]
fyi, PJ64's VRCP is not 100% accurate. Probably the same for the other similar instructions.

**Comment by olivieryuyu** [comment]
with some efforts I understand now more or less VRSQ. Not easy those fixed point arithmetic instructions :1234: 

I begin to grasp the code, i can see that two new matrix are created from the current matrix and also that the reciprocal square of the sum of the vertex coordinates is calculated. I still need to go to the rest of the code, hopefully this week end.

**Comment by olivieryuyu** [comment]
What is the best place to see this point lighting effect in action? I would need to find a place where the effects is strong.  A PJ64 savestate would be good please.

**Comment by olivieryuyu** [comment]
What a code! Also it seems that my dump and the one of Gilles is incorrect...

It seems that there is another mode than point lighting ...

**Comment by standard-two-simplex** [comment]
West clock town during the day. Walk up and down the street. The effect is very strong near the banker. The  second and fourth pictures in the original post ilustrate it.

**Comment by olivieryuyu** [comment]
with some good examples, I am now able to document better the case. No everything is understood yet but it is going on the right direction :)

**Comment by olivieryuyu** [comment]
the code is really horrendous but I finally went through it.

Short question: how is calculated the distance between the light source and the vertex currently?

**Comment by standard-two-simplex** [comment]
> Short question: how is calculated the distance between the light source and the vertex currently?

I thinks it's in here:
https://github.com/gonetz/GLideN64/blob/bbc7131655a78ae887cee481f0a67674385fc2d2/src/gSP.cpp#L162

``light len`` is the variable storing the distance. ``lvec`` gets light postion, then current vertex is subtracted then the square root of the dot product by itself is calculated.

**Comment by gonetz** [comment]
I started new point-lighting implementation, based on olivieryuyu's decoding. First-shot implementation is available for patrons with early access: https://www.patreon.com/Gliden64
It will be published on GitHub after beta testing (current version is rather alpha).
![point_light](https://user-images.githubusercontent.com/8983092/30548463-6a464f68-9cbc-11e7-8c45-1d2ac843c693.png)

**Comment by olivieryuyu** [comment]
i guess the zeldaMM_light_rice branch is useless now :)

**Comment by gonetz** [comment]
It never was useful.

**Comment by gonetz** [comment]
The code is in zeldamm_point_light branch. I refactored vertex load code, so it is need to be tested before push to master. Test build:
https://drive.google.com/file/d/0B0YqMPjGo3B2ZEduaFJ0M3NvMW8/view?usp=sharing

**Comment by olivieryuyu** [comment]
@hertz4 

can it be closed?

**Comment by olivieryuyu** [comment]
@gonetz 

May be it could be closed? :)

**Comment by gonetz** [comment]
Sure
