### ISSUE TITLE
Gamma correction

### ISSUE THREAD

**Issue by Gillou68310** [gonetz/GLideN64#779]
A few games are hard to play because they are too dark (eg: duke nukem zero hour, doom 64, ...), especially on android where you cannot adjust gamma.

Here's a post processing implementation of gamma correction using shaders:
https://github.com/Gillou68310/GLideN64/commit/93e7fd2f9ce8f4d8108039a020fb6b50931c4eac

Gamma correction is applied after bloom effect if both are enable.
Also framebuffer emulation must be enable.

@gonetz I was wondering what should be done to implement gamma correction without framebuffer emulation?

**Comment by gonetz** [comment]
Wait. Gamma correction is already implemented:
		"  if (uGammaCorrectionEnabled != 0) \n"
		"    fragColor.rgb = sqrt(fragColor.rgb); \n"

If game uses gamma correction, it will work. For example, check Automobili Lamborghini with and without gamma correction. Frame buffer emulation is not necessary for gamma correction emulation.

Doom64 has built in gamma setting. Set it to max and the game will look pretty bright.

**Comment by Gillou68310** [comment]
Yes but this will only work if the game has built in gamma correction.
What about other games?
BTW I tested doom with maximum brightness and I still find the game really dark, I guess that's how it is meant to be played but it's almost unplayable on android unfortunately :-(

**Comment by gonetz** [comment]
Add "force gamma correction" options? Will it help for Doom64 on Android?

**Comment by Gillou68310** [comment]
You mean directly in the following shader?
```	strFragmentShader.append(
		"  if (uFogUsage == 257) \n"
		"    fragColor.rgb = mix(fragColor.rgb, uFogColor.rgb, vFogFragCoord); \n"
		"  if (uGammaCorrectionEnabled != 0) \n"
		"    fragColor.rgb = sqrt(fragColor.rgb); \n"
		);```

**Comment by gonetz** [comment]
Yes, force set uGammaCorrectionEnabled to 1.

**Comment by Gillou68310** [comment]
Hum it makes no difference

**Comment by Gillou68310** [comment]
Heu weird thing ShaderCombiner constructor is not called.

**Comment by Gillou68310** [comment]
Nevermind it makes a difference, still weird that my breakpoint is not hit in ShaderCombiner constructor.

**Comment by Gillou68310** [comment]
Lol nevermind I forgot you implemented shader storage. 

Ok I will add a force gamma correction option. Do you mind if I also add an option for the gamma value?

**Comment by gonetz** [comment]
> Do you mind if I also add an option for the gamma value?

Only if default gamma correction is not enough. Currently gamma correction works exactly as on N64.

**Comment by Gillou68310** [comment]
sqrt(color) == pow(color, 1/gamma)
With gamma == 2

So I can set 2 as the default value.

**Comment by Gillou68310** [comment]
Is this okay for you?
https://github.com/Gillou68310/GLideN64/commit/324c584e49341ac62a0b61803989e3b9e978c4b2

**Comment by ADormant** [comment]
@Gillou68310 How does this compare to gamma correction in DolphinFX/IshiirukaFX?
https://github.com/Tinob/Ishiiruka/blob/master/Data/Sys/Shaders/IshiirukaFX.glsl
https://github.com/Tinob/Ishiiruka/blob/master/Data/Sys/Shaders/DolphinFX.glsl

**Comment by gonetz** [comment]
> Is this okay for you?

Almost. Everything looks correct and accurate. The only notice: generalEmulation.gammaCorrectionLevel default value must be 2.0f.
User should just enable forceGammaCorrection and get visible result with default gammaCorrectionLevel.
```pow(fragColor.rgb, vec3(1.0 / uGammaCorrectionValue));```
has no effect with  uGammaCorrectionValue == 1

**Comment by Gillou68310** [comment]
Yeah I hesitated on what the default value should be but I think you're right the user should see visible diff if gamma correction is forced.

I"ll update the branch and open the PR tomorrow.

Thanks for you time ;-)

**Comment by gonetz** [comment]
Ok
