### ISSUE TITLE
WAVE RACE 64 - SCREEN CROPING

### ISSUE THREAD

**Issue by elcorsico** [gonetz/GLideN64#783]
hello can you solve this bug GLideN64 plugin

the screen of the game is not displayed in full, is trimmed down
The game: Wave Race 64 (E!)

![2015-10-31](https://cloud.githubusercontent.com/assets/10583821/10864587/dbd0adb0-7ff2-11e5-8c09-84327dac58c0.png)

thansk for this plugin great , i love it

the french lover emulation N64 ;-)

**Comment by matthewharvey** [comment]
Bonjour! Merci pour la réport. (and sorry for my weak French)

I can confirm this using the git version of GLideN64 and git mupen64plus on Linux Mesa graphics. It doesn't happen on the American version, only the European one. I'm afraid I don't know where to start on this one, but maybe one of the other developers can chime in with some insight.

**Comment by purplemarshmallow** [comment]
Best thing is to test if it works with framebuffer emulation disabled. It's most likely a bug in the VI emulation code (video interface)

**Comment by matthewharvey** [comment]
Good call purplemarshmallow. With framebuffer emulation disabled the issue does not occur.

**Comment by purplemarshmallow** [comment]
If framebuffer emulation is disabled VI emulation is also disabled. VI emulation renders the image according to VI registers. You'll get black bars and the image will have the correct aspect ratio. This is how it should look like (angrylion's). With framebuffer emulation disabled the aspect ratio is wrong, the image is stretched
![1](https://cloud.githubusercontent.com/assets/7283660/10870145/8fc61bea-80c3-11e5-8f24-7ea258ce5460.png)

**Comment by olivieryuyu** [comment]
may be useless but what about doing the same than dolphin? meaning  signal timings as explained here:

https://fr.dolphin-emu.org/blog/2016/02/02/dolphin-progress-report-january-2016/

**Comment by olivieryuyu** [comment]
duplicate #375

**Comment by gonetz** [comment]
Closed as duplicate
