### ISSUE TITLE
Build errors after 142ad0b

### ISSUE THREAD

**Issue by tony971** [gonetz/GLideN64#786]
https://gist.github.com/tony971/e0a8cbd772fc1a2f9690

**Comment by purplemarshmallow** [comment]
My changes caused build errors? Can you give more details? Can you build the mupen64plus version? No problem on my end

**Comment by gonetz** [comment]
I compiled the code for Windows and Android with no errors.

**Comment by tony971** [comment]
Never mind. I rebuilt everything from scratch and it succeeded.
