### ISSUE TITLE
(Mupen64Plus) Plugin not found

### ISSUE THREAD

**Issue by tony971** [gonetz/GLideN64#787]
Trying to run the latest git revision of GLideN64 results in the following error.

    UI-Console Error: LoadLibrary('D:/Emulation/Nintendo 64/Mupen64Plus\mupen64plus-video-GLideN64.dll') error: (null)
    UI-Console Error: Specified Video plugin not found: mupen64plus-video-GLideN64

No issues building the plugin and I've been successfully using the PJ64 version. This was my first time building for M64P, though.

**Comment by tony971** [comment]
I thought it might have been PEBCAK but even test builds that @gonetz have distributed lately have this problem. It should be noted that I'm using the latest git version of m64p, not the latest release.

**Comment by AmbientMalice** [comment]
You're not using 64bit m64p accidentally, are you?

**Comment by tony971** [comment]
https://bitbucket.org/ecsv/mupen64plus-mxe-daily/downloads

Not unless ecsv managed to get mingw to build in x64 and didn't tell anyone.

**Comment by AmbientMalice** [comment]
The bitbucket versions include 64bit executables. The 32 bit version is i686-pc-mingw32. Avoid x86_64-w64-mingw32

**Comment by tony971** [comment]
Welp, I'm an idiot.
