### ISSUE TITLE
Majora's Mask screen turns red

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#790]
Very weird bug. This does not happen on real hardware. Happens with public release 1 and also with https://github.com/gonetz/GLideN64/commit/93f659c8af5cdee99e57030389f8b19d8c795479 (latest). At several points in the game the screen turns red. For example when a day ends or in the Music Box House cutscene.

Here's the fastest way to reproduce this problem:
* Wait until a day ends or load my savestate https://drive.google.com/file/d/0B7Y6r4SpC_QQZnk5Zk56bkVzQU0/view?usp=sharing
* Open the subscreen once
* Wait until the screen shrinking effect starts
* The screen will turn red
![gliden64_zelda_majora s_mask_000](https://cloud.githubusercontent.com/assets/7283660/11187987/0dee8766-8c89-11e5-8170-6d2aa13b3021.jpg)

**Comment by LegendOfDragoon** [comment]
Does it happen in LLE?

**Comment by purplemarshmallow** [comment]
Yes also happens in LLE. But it does not happen if I don't open the subscreen

**Comment by purplemarshmallow** [comment]
I fixed Quake 2 #792 
But it does not help here

**Comment by SwinglesMan** [comment]
virtualboy! xD

**Comment by gonetz** [comment]
Fixed

**Comment by purplemarshmallow** [comment]
fixed
