### ISSUE TITLE
gamma correction breaks copy color

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#794]
Screenshots from a game that uses gamma correction. The first screenshot shows the image rendered on the GPU. The second screenshot shows the image copied to RDRAM. The second screenshot is incorrect. Gamma correction is applied multiple times before the image gets copied. 
![2](https://cloud.githubusercontent.com/assets/7283660/11220826/24397f9c-8d62-11e5-8750-2b48fed24f2d.jpg)
![1](https://cloud.githubusercontent.com/assets/7283660/11220831/27b6bbe4-8d62-11e5-9246-2ea93877da36.jpg)

**Comment by gonetz** [comment]
gamma correction should be made as post-filter. However, it will work only with fb emulation enabled.

**Comment by gonetz** [comment]
Implemented in gamma correction feature-branch.

Binary:
https://drive.google.com/file/d/0B0YqMPjGo3B2QzJKQzVtakxFcWc/view?usp=sharing

**Comment by theboy181** [comment]
What is different?  I thought you had implemented this already.

**Comment by purplemarshmallow** [comment]
Gamma correction is now implemented as post-filter and this fixes the problem I reported. Looks good I tested Bakushou Jinsei 64 and the framebuffer effects are no longer bleached out.

**Comment by gonetz** [comment]
Gamma correction moved from RDP emulaton level to Video Interface level. It is right place for that feature.

**Comment by purplemarshmallow** [comment]
In the settings I can't set "Gamma correction level" below 2. Is this intended? Or a bug?

**Comment by gonetz** [comment]
Yes, I set lower bound to 2. It's not right. Lower bound should be 1 or 1.1

**Comment by purplemarshmallow** [comment]
fixed by https://github.com/gonetz/GLideN64/commit/a9d1df569466e27a101db006e25ee89794ba394e
