### ISSUE TITLE
Textures disappears on different conditions

### ISSUE THREAD

**Issue by LuigiBlood** [gonetz/GLideN64#802]
You don't have to set anything, just going to GLideN64 settings and then go back makes textures disappear. It does NOT always need that to have textures to disappear though, but sometimes this happens.

For some reason, I had it happen with Mario Artist Paint Studio, Talent Studio and Polygon Studio.
I did this with Super Mario 64 PAL it still works fine. However, when I tried with Super Mario 64 and then back to Paint Studio, the bug was present. It stays until I close the emulator.

I should mention I use EmuCR builds (which always worked fine for me actually).
I usually use a build from 2015/10/12 which doesn't do this bug.

For this issue, I use a build from 2015/11/14.

Mario Artist Paint Studio:
Before bug:
![gliden64__000](https://cloud.githubusercontent.com/assets/952602/11318318/71198bf2-904d-11e5-9fcd-b20aa81b1396.jpg)

After bug:
![gliden64__001](https://cloud.githubusercontent.com/assets/952602/11318319/7715806a-904d-11e5-8664-2f2ae089ef6d.jpg)

Mario Artist Polygon Studio:
Regular GLideN64 (2015/10/12):
![polymenu_1](https://cloud.githubusercontent.com/assets/952602/11307578/7681ad7a-8fb9-11e5-87da-83e4015f888d.png)
GLideN64 (2015/11/14):
![polymenu_2](https://cloud.githubusercontent.com/assets/952602/11307586/84f76552-8fb9-11e5-8a60-3aea05fc8324.png)

**Comment by AmbientMalice** [comment]
This might be a Shader Storage bug? It's an experimental feature that tends to break stuff when you fullscreen and such. Try turning it off.

**Comment by LuigiBlood** [comment]
Oh, yeah, I disabled it. It doesn't do that bug anymore.

**Comment by gonetz** [comment]
So, it is shader storage. I've made a fix for it, please test this issue with new binaries:
https://drive.google.com/file/d/0B0YqMPjGo3B2NGVMZWo3MHRQMWc/view?usp=sharing

**Comment by LuigiBlood** [comment]
It didn't fix anything. Do you want the ROMs I'm using to test with?

**Comment by gonetz** [comment]
> Do you want the ROMs I'm using to test with?
Yes. I don't have these roms.

**Comment by LuigiBlood** [comment]
I can't seem to find any kind of PM system in Github so... http://bsxproj.superfamicom.org/64dd/dump/
