### ISSUE TITLE
Mario Artist problems (frame buffer?)

### ISSUE THREAD

**Issue by LuigiBlood** [gonetz/GLideN64#803]
Those problems were always present. Since Mario Artist is made of 3 games (+ Communication Kit but it emulates fine), I will talk about the problems for each game.

I will mention that I use EmuCR build from 2015/10/14 because of its stability.

Mario Artist Paint Studio:
- Transparency problems with the black color on the brush cursor. (Forgot that one)
- Stamps (Characters, Font, etc...) do not work. Overlays the drawing screen with white with the stamps, and it's slightly shifted. **(Auxiliary Copy fixes this issue)**
<br>Before putting the stamp:
![gliden64__002](https://cloud.githubusercontent.com/assets/952602/11318346/2b01c5a6-904f-11e5-8405-1ec4b0268fba.jpg)
After putting the stamp (notice the rainbow at the bottom):
![gliden64__003](https://cloud.githubusercontent.com/assets/952602/11318348/3bcbc77e-904f-11e5-9d8a-25dcd39d0cb8.jpg)

Mario Artist Polygon Studio:
- Cannot model, cannot select models, faces, points, etc...
- Model is always darker in the editor:
![gliden64__007](https://cloud.githubusercontent.com/assets/952602/11318380/2c630fbc-9050-11e5-82ef-bb4cdc034c03.jpg)
What it is supposed to look like:
![nddj0008](https://cloud.githubusercontent.com/assets/952602/11318381/32d67654-9050-11e5-80b4-99602c9503ae.png)
- Sound Bomber Mode (Wario Ware) doesn't make 2D renders of the model. **(Auxiliary Copy fixes this issue)**

Mario Artist Talent Studio:
- Cannot apply face changes, makes a black texture or garbage: **(Auxiliary Copy fixes this issue)**
![gliden64__004](https://cloud.githubusercontent.com/assets/952602/11318364/926f2616-904f-11e5-901d-2ae825af6248.jpg)
- Every kind of thumbnails are garbage, noticeable on save/load menu (**ACTUALLY FIXED**, explained in comment below):
![gliden64__005](https://cloud.githubusercontent.com/assets/952602/11318369/bf07825e-904f-11e5-973f-7d11679387d0.jpg)
- Catwalk doesn't render pictures of characters on the screen behind. **(Auxiliary Copy fixes this issue)**
![gliden64__009](https://cloud.githubusercontent.com/assets/952602/11318396/ec03c730-9050-11e5-903f-8bda23eb016e.jpg)
- Ending photo of Catwalk does not render. Black picture. **(Auxiliary Copy ALMOST fixes this issue, only the upper half is rendered.)**
- Cannot make custom animations for movies, cannot select body parts.

**Comment by LuigiBlood** [comment]
An update about the thumbnail in Talent Studio like in saving, etc.
I tried the build from this comment: https://github.com/gonetz/GLideN64/issues/802#issuecomment-158659753

The thumbnail seems to render fine here.

**Comment by purplemarshmallow** [comment]
If you enable copy auxiliary the faces in Mario Artist Talent Studio will look correct

**Comment by LuigiBlood** [comment]
In the face editor? Really? I need to try that out.

**Comment by LuigiBlood** [comment]
Doesn't seem to work. Couldn't find the option so I added "copyAuxToRDRAM=1" to the INI file but it doesn't work to me.

**Comment by purplemarshmallow** [comment]
It's not added to the zilmar spec version yet. For now you can use Mupen64plus or set it to 1 in config.cpp and compile the plugin.

**Comment by LuigiBlood** [comment]
Man I don't really feel like using mupen64plus right now.
Can you test Mario Artist Polygon Studio's Sound Bomber with it? Is it playable like this?
https://www.youtube.com/watch?v=40GhbBZGYZY (with GLideN64 the model was invisible)

**Comment by purplemarshmallow** [comment]
https://drive.google.com/file/d/0B7Y6r4SpC_QQRjR3NHc5bUowbEk/view?usp=sharing
You can test this binary the option is enabled with it.

**Comment by LuigiBlood** [comment]
I just tried it out: it fixes EVERYTHING.
One exception, the final picture at the end of the Talent Catwalk is only half-rendered.

**Comment by purplemarshmallow** [comment]
That's good it should be enabled for these titles by default later

I tested modeling in Polygon Studio with different plugins and only angryion's looks correct even Jabo's software renderer does not work. This seems to be a hard to solve problem.

**Comment by purplemarshmallow** [comment]
Now I tried again with GLideN64 and it seems to be working very weird
![1](https://cloud.githubusercontent.com/assets/7283660/12593894/a3c6e1d0-c473-11e5-8d85-2d65a95c8491.jpg)

**Comment by LuigiBlood** [comment]
I believe when you try to select a model between several, it selects every of them since it cannot seem to differenciate all of them.

**Comment by LuigiBlood** [comment]
I kinda wish I could use your build of GLideN64, but since the settings are forced and can't change anything, it's kinda meh D:

I also updated the first post saying the Auxiliary Copy mostly fixes the issues, except a few.

**Comment by LuigiBlood** [comment]
I've seperated several issues into their own so it is easier to follow:
https://github.com/gonetz/GLideN64/issues/1156
https://github.com/gonetz/GLideN64/issues/1157

**Comment by gonetz** [comment]
Ok, thanks
