### ISSUE TITLE
No compilation guide?

### ISSUE THREAD

**Issue by roflcopter777** [gonetz/GLideN64#804]
I don't know where else to put this, but EmuCR seems to break a lot of the builds that they compile, and at the time of writing, there are absolutely no guides or wikis to others who wish to compile this plugin on their own. Is there any way this will be corrected?

**Comment by wareya** [comment]
https://github.com/gonetz/GLideN64/tree/master/projects/cmake

**Comment by gonetz** [comment]
Press WiKi button and you will see two "Build from sources" articles.

Search issues for "guide" and you will find this:
https://github.com/gonetz/GLideN64/issues/742
