### ISSUE TITLE
ESC Key hardcoded to Toggle Full-Screen?

### ISSUE THREAD

**Issue by granumignis** [gonetz/GLideN64#809]
I'm interested in remapping the Full Screen toggle key from ESC to something else.  I don't see any way to configure it in the Plugin's Config GUI.

I use Project 64 1.6 (the 'zilmar' version of this plugin).

Is it true that this is hard coded? If so, can someone direct me to the place in the code where it is set that way? I'd appreciate it!!!!

**Comment by AmbientMalice** [comment]
It's controlled from the emulator's side.

![hotkey](https://cloud.githubusercontent.com/assets/10704701/11432203/94967512-94f4-11e5-990e-b94d4b9cb805.jpg)

But I don't think PJ64 1.6 lets you change the hotkeys? Modern PJ64 does. If you want, I could build PJ64 for you, or you could grab a latest x86 build from EmuCR.

http://www.emucr.com/search/label/Project64?&max-results=12

**Comment by granumignis** [comment]
Thank you so much! I have project 64 2.2 as well - somehow I missed what's
in your screenshot.

I'll look at that again.

**Comment by AmbientMalice** [comment]
Bear in mind 2.2 is kinda buggy and outdated.

**Comment by Nes-player4Life** [comment]
Not related to GlideN64. Please close.
