### ISSUE TITLE
CMake build failure in OpenGL ES 2 environments

### ISSUE THREAD

**Issue by Nebuleon** [gonetz/GLideN64#810]
When building GLideN64 with CMake in an environment having only OpenGL ES 2, and not OpenGL (desktop), GLideN64 will compile successfully, but the required project GLideNHQ will not.

[GLideN64's CMakeLists.txt](https://github.com/gonetz/GLideN64/blob/28d4993968ec1aafa74a198c435b10839023338a/src/CMakeLists.txt#L181-L202) uses a library according to whether or not `GLES2` is defined.

[GLideNHQ's CMakeLists.txt](https://github.com/gonetz/GLideN64/blob/28d4993968ec1aafa74a198c435b10839023338a/src/GLideNHQ/CMakeLists.txt#L60-L66) brings in OpenGL (desktop) regardless, and the build failure occurs on line 60.

There would be two resolutions to this issue:

a) Have only GLideN64's CMakeLists.txt contain the check for GLES2 or OpenGL, deleting it from GLideNHQ's.

b) Copy the GLES2 tests from GLideN64 to GLideNHQ.

**Comment by gonetz** [comment]
Solution a) is better. GLideNHQ is a sub-project.
Could you solve this issue and make a pull request?

**Comment by Nebuleon** [comment]
Moved to pull request #820.
