### ISSUE TITLE
Unable to compile latest code - Fedora (x64)

### ISSUE THREAD

**Issue by 7oxicshadow** [gonetz/GLideN64#812]
This might be related to (or the same as issue 811 and issue 810)

When trying to compile the latest branch I get the following compilation errors:

    /mnt/games/native_emulators/source_files/gliden64_plugin/src/GLideNHQ/TextureFilters_xbrz.cpp:442:15: error: redeclaration of ‘const unsigned char& blend’
    if (getTopR(blend) != BLEND_NONE && !eq(e, g)) //but support double-blending
               ^
    /mnt/games/native_emulators/source_files/gliden64_plugin/src/GLideNHQ/TextureFilters_xbrz.cpp:438:18: note: ‘const unsigned char& blend’ previously declared here
    if (getBottomR(blend) >= BLEND_DOMINANT)
                  ^
    /mnt/games/native_emulators/source_files/gliden64_plugin/src/GLideNHQ/TextureFilters_xbrz.cpp:444:18: error: redeclaration of ‘const unsigned char& blend’
    if (getBottomL(blend) != BLEND_NONE && !eq(e, c))
                  ^
    /mnt/games/native_emulators/source_files/gliden64_plugin/src/GLideNHQ/TextureFilters_xbrz.cpp:438:18: note: ‘const unsigned char& blend’ previously declared here
    if (getBottomR(blend) >= BLEND_DOMINANT)

I downloaded an older 1.2 release and was able to build that with no issues. Are there any new dependencies that I am missing?

**Comment by gonetz** [comment]
No new dependencies since the release,  but xbrz version updated. May be your  g++ version is outdated?

**Comment by 7oxicshadow** [comment]
g++ -v gives the following output:

    gcc version 5.1.1 20150618 (Red Hat 5.1.1-4) (GCC)

**Comment by 7oxicshadow** [comment]
I use the following cmake command:

cmake -DMUPENPLUSAPI=On ..

which gives the following output:

    -- The C compiler identification is GNU 5.1.1
    -- The CXX compiler identification is GNU 5.1.1
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    Looking for bcm_host.h
    bcm_host.h not found
    -- Found OpenGL: /usr/lib64/libGL.so  
    -- Found Freetype: /usr/lib64/libfreetype.so (found version "2.6.0") 
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /mnt/games/native_emulators/source_files/gliden64_plugin/src/build

The "looking for bcm_host.h" and "bcm_host.h not found" is new?

**Comment by gonetz** [comment]
Afair, it's for Pandora

g++ is a newer than I use. Probably additional compiler options needed. Sometimes older projects do not compile with new g++.

**Comment by 7oxicshadow** [comment]
I think you are correct about the g++ version.

This following link comes to the same conclusion for the same issue:

https://github.com/hrydgard/ppsspp/issues/7717

**Comment by gonetz** [comment]
You may either try to rewrite the problem part of code, or exclude TextureFilters_xbrz.cpp from src\GLideNHQ\CMakeLists.txt

**Comment by 7oxicshadow** [comment]
Was just about to respond :)

Re-writing the problem code fixes the issue.

This appears to be a GCC 5.1 bug and should be resolved in GCC 5.2

I will mark this issue as closed.

**Comment by gonetz** [comment]
> This appears to be a GCC 5.1 bug and should be resolved in GCC 5.2

Good if it is true.

**Comment by 7oxicshadow** [comment]
official bug here:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65885

and here:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65843

Thanks for your help

**Comment by gonetz** [comment]
Thanks for the info. I'll not install GCC 5.1 :)
