### ISSUE TITLE
Majora European debugger build on Android,text is broken with solid colors.

### ISSUE THREAD

**Issue by retrobenny** [gonetz/GLideN64#823]
Tested on Shield TV Pro on stock.

GLideN64 3.1 variant with issue.

![2015_12_23_23 32 41](https://cloud.githubusercontent.com/assets/16418716/11990211/f5841b96-a9cf-11e5-9ae1-69fb41dc391c.png)

Glide64 with proper text.

![2015_12_23_23 43 52](https://cloud.githubusercontent.com/assets/16418716/11990216/03addb80-a9d0-11e5-8f29-1aad9260463b.png)

The screens were taken with Screenshot Easy.
This issue is on every debug element in the area select,item values,and also happens on the Ocarina Master Quest debug build.

**Comment by purplemarshmallow** [comment]
like #495 ?

**Comment by retrobenny** [comment]
Sorry,didn't see that one,maybe merge or mark as duplicate,though the game is different while the issue is identical.
At least I called attention to it and you now know that Majora European debug version is also affected.

**Comment by retrobenny** [comment]
This issue has been fixed for both MM and OOT debug versions,but unfortunate emulation issues cause input to be trashed in Majora debug build and the sub screen to VERY frequently crash in OOT MQ debug.
