### ISSUE TITLE
Feature Request: Deposterization filter for xBRZ

### ISSUE THREAD

**Issue by DonelBueno** [gonetz/GLideN64#826]
xBRZ scaling leaves the textures with posterization issues. The same issue happened on PPSSPP, but they sorted it out with a deposterization step. The issue and the solution are both described here:

http://blog.metaclassofnil.com/?p=306

Example of the issue in GLideN64:

![project64 2015-12-27 08-06-57-84](https://cloud.githubusercontent.com/assets/4239694/12009833/247ee00e-ac71-11e5-89e4-2150ebb667d6.png)

![project64 2015-12-27 08-08-23-79](https://cloud.githubusercontent.com/assets/4239694/12009836/2b86d5be-ac71-11e5-9201-0075fa41ddf8.png)

Pay attention to the sky texture. The first one is xBRZ filtered, the second one is HQ4x.

It's way more evident in some games, like in Ocarina of Time. The ground texture in that game gets really distracting.

**Comment by ADormant** [comment]
@gonetz 
Deposterize https://github.com/Tinob/Ishiiruka/commit/d2fb92518f50c6154f33f05be39128e48d6b83be

**Comment by ADormant** [comment]
@gonetz Deposterize shader https://github.com/libretro/common-shaders/commit/cc81b1fd425869c05091ae8bf1138ba3d42fa3a4

**Comment by gonetz** [comment]
I've added the deposterization step.from Ishiiruka's code:
https://github.com/gonetz/GLideN64/commit/78d7c99b029deb5a17869a8254f4c44fd76edf0c
I don't see much difference though.

I can't share the binary via googledrive because it says that the file is infected. I tested the file via virustotal - ClamAV reports about Win.Adware.Browsefox-12346, others 54 antiviruses reports that the file is clean. If you need the binary, you may write me an email, I'll send the file to you.

**Comment by theboy181** [comment]
Zip with password protection and share the password in the info file.

**Comment by gonetz** [comment]
Good idea. The binary:
https://drive.google.com/file/d/0B0YqMPjGo3B2VU0tVkdST0ViUWc/view?usp=sharing

pass: deposterization

**Comment by ADormant** [comment]
@gonetz Changes are supposed to be subtle http://libretro.com/forums/showthread.php?t=4908

**Comment by gonetz** [comment]
If you see the positive difference in quality,  I'll add that code to master.

**Comment by DonelBueno** [comment]
I'll check it out soon and then post the results here. Thanks for the attention.

**Comment by DonelBueno** [comment]
Test Results:

![1- no scaling](https://cloud.githubusercontent.com/assets/4239694/12420150/ff1eb2ba-bea1-11e5-95aa-87dc172fb62e.png)
![Uploading 2- HQ 4x.png…]()
![Uploading 3- 6x xBRZ.png…]()
![4- 6x xbrz deposterization](https://cloud.githubusercontent.com/assets/4239694/12420149/ff1d0b22-bea1-11e5-9a3a-45ff00ef03d4.png)

As you can see, there is basically no change to the posterization.

**Comment by ADormant** [comment]
Colors are better with deposterize enabled, Buttons around Navi button become yellow instead of brown and green circle seems  to have better transparency.

**Comment by DonelBueno** [comment]
@ADormant You must be comparing the wrong images. Compare 6xBRZ Texture Scaling to 6xBRZ + Deposterization texture Scaling (the last two images). They are basically the same, aside from some very minor differences on the ground textures, but these differences aren't for better, they are just different.

**Comment by ADormant** [comment]
Still wouldn't hurt to add it looks somewhat different after all.

**Comment by gonetz** [comment]
It hurts performance, since the deposterization step is not free. I can make it optional though.

Regarding the result: it is probably a bad idea to use maximal BRZ level. Try 3x or 4x BRZ, may be difference will be more noticeable.

**Comment by gonetz** [comment]
I suggest to close this issue since deposterization step does not help to solve problems with xBRZ and N64 textures.

**Comment by ADormant** [comment]
@gonetz Deposterize is good for games with dithering https://github.com/tapcio/PeteOpenGL2Tweak/releases

**Comment by gonetz** [comment]
Most of N64 textures use 16bit color, however deposterization has no visible effect. N64 texture size may negate the effect, because N64 texture memory is just 4kb.

**Comment by ADormant** [comment]
Hmm PS1 texture cache in only 2kb.

**Comment by gonetz** [comment]
I have fixed an issue in GLideNHQ code and now deposterization effect is clearly visible

Test binary:
![super_mario_64-001](https://cloud.githubusercontent.com/assets/8983092/14356834/23e6afea-fd08-11e5-8db1-f76cf793fa65.png)
![super_mario_64-004](https://cloud.githubusercontent.com/assets/8983092/14356835/23e77f2e-fd08-11e5-891c-3df82502a0ff.png)


https://drive.google.com/file/d/0B0YqMPjGo3B2LTVtcHAzX3ZDUjg/view?usp=sharing

**Comment by oddMLan** [comment]
Earthworm Jim 64 - Normal
![ewj_no_post](https://cloud.githubusercontent.com/assets/7278372/14366064/d3588072-fcc5-11e5-8393-ce99369bdac8.png)
Earthworm Jim 64 - X2 + Deposterization
![ewj_x2_with_post](https://cloud.githubusercontent.com/assets/7278372/14366065/d50c4b24-fcc5-11e5-901b-8f0e355881dd.png)
Earthworm Jim 64 - xBR 3x Normal
![ewj_xbrx3_no_post](https://cloud.githubusercontent.com/assets/7278372/14366068/d72f3dbc-fcc5-11e5-9a66-1495c5337efc.png)
Earthworm Jim 64 - xBR 3x + Deposterization
![ewj_xbrx3_with_post](https://cloud.githubusercontent.com/assets/7278372/14366071/d928c1ec-fcc5-11e5-97da-5c02cfe71231.png)
Zelda OOT - Normal
![oot_no_post](https://cloud.githubusercontent.com/assets/7278372/14366074/dc09f08e-fcc5-11e5-8199-5f8a4d2b54df.png)
Zelda OOT - X2 + Deposterization
![oot_x2_with_post](https://cloud.githubusercontent.com/assets/7278372/14366077/dea58772-fcc5-11e5-8c52-eebe89ed1fbc.png)
Zelda OOT - xBR x4 Normal
![oot_xbrx4_no_post](https://cloud.githubusercontent.com/assets/7278372/14366079/e063590e-fcc5-11e5-80fd-bacf46e7f70c.png)
Zelda OOT - xBR x4 + Deposterization
![oot_xbrx4_with_post](https://cloud.githubusercontent.com/assets/7278372/14366081/e2718a4a-fcc5-11e5-8f00-e2171347552c.png)

I wonder how deposterization helps KI Gold. I'll test later.

**Comment by gonetz** [comment]
So, deposterization is useful after all. I'll add it to master. I think, it should be optional though.

**Comment by oddMLan** [comment]
I agree; it should be optional.

**Comment by DonelBueno** [comment]
I helps Earthworm Jim a lot, but it doesn't seem to help OOT.

I also think it's a good idea to include it into master.

**Comment by gonetz** [comment]
Done

**Comment by gonetz** [comment]
Has anybody my dev branch with Deposterization feature in your local git repository?
Deposterization is completely broken in master. It seems that I broke on when merged code to master.

**Comment by fzurita** [comment]
What's breaking it? I'm not seeing any issues right now with it enabled in Android. Amy specific examples?

**Comment by gonetz** [comment]
I have issues in every game, e.g.:
https://github.com/gonetz/GLideN64/issues/1301

**Comment by gonetz** [comment]
I see the problem. It happens only on devices with multicore CPU, if GLideNHQ can detect number of cores.

**Comment by gonetz** [comment]
Fixed.
