### ISSUE TITLE
Feature Request: Multithreaded Shader Compilation maybe Async Shader too .

### ISSUE THREAD

**Issue by retrobenny** [gonetz/GLideN64#827]
I saw something about it on the Ishiiruka version of Dolphin about it helping against lengthy stutters.

And the Asynchronous Shader Compilation would be a great option but lowering accuracy from pop-ins in favor of greater performance for everything that appears for the first time.
But I don't think this is possible on Android or even OpenGL,which is a shame.
At least having multithreaded shader compilation could help a lot.

**Comment by purplemarshmallow** [comment]
Async shader compilation is a hack and it partially breaks rendering for an undefined amount of time and that's the reason why the dolphin developers refuse to add it to the official version.

**Comment by retrobenny** [comment]
How about multithreaded shader compilation then,would it work without bad problems?

**Comment by purplemarshmallow** [comment]
Never heard about multithreaded shader compilation not sure if that's possible.

How big is this problem? Dolphin has more complex shaders. It's a bigger problem there. And GLideN64 already has a shader storage implemented.

**Comment by retrobenny** [comment]
It would help make GLES2 better if the stutters were greatly reduced as a result and would silence the first loads when storage is used on the other variants.
Paper Mario on GLES2 for example gets a stutter when you need to time the action command.

**Comment by gonetz** [comment]
I currently see no room for such kind of optimization. With shader storage enabled you will get a stutter only on the first time the combiner is used.

**Comment by retrobenny** [comment]
You ignored the fact about the GL[b]ES2[/b] variant since [u]it can't use storage[/u],the stuttering persists on each time you start the game,and multithreading would minimize the stutter length or end it entirely.

**Comment by gonetz** [comment]
There is no place for multithread shader compilation in current code. Multi-pass display list processing needed to get performance gain  from multithreading.  First pass will collect info about combines and start parallel shaders compilation,  the second pass works as usual. That's a lot of changes, which I don't want to do myself.
