### ISSUE TITLE
hexen: totally black in game (with or without fb on):  regression compared to GLN 0.4.1

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#83]
![ooo](https://cloud.githubusercontent.com/assets/8987490/4873042/4a354ada-61ff-11e4-9e22-45ea2aa8abd5.jpg)

**Comment by twinaphex** [comment]
Can anybody explain what the underlying cause for this was? I experience a similar issue right now with Parallel RDP.
