### ISSUE TITLE
.Htc loading across releaced plugins

### ISSUE THREAD

**Issue by Nes-player4Life** [gonetz/GLideN64#835]
It seems that a Htc created by one version of GlidN64 cannot be read by a later revision.
Is this assumption correct? If so is there a way to lock the Htc protocol so that Htc may be read no mater what plugin is used?

**Comment by gonetz** [comment]
I did not change .htc format since the first public release. However, I've added 6xbrz support. If you use 6xbrz, the .htc file can't be open with public release versions because they don't have 6xbrz support.

**Comment by Nes-player4Life** [comment]
I don't use any of the enhancement options whenever using textures. Could there be anything else keeping the archive from loading?

**Comment by gonetz** [comment]
Hmm, do you have .htc with HD textures and it does not loaded?
I really don't remember any change in texture cache format. Which plugin version was used to create the .htc and which one can't load it?

**Comment by Nes-player4Life** [comment]
I can't remember, i've swapped the plugins so often. Anyhow I think the issue was caused during 
rar compression/decompression.

If there was never a change to file loading the error must be on my end, so I'll close the issue.
If anyone finds this issue as true issue I'll reopen.

**Comment by gonetz** [comment]
"I really don't remember any change in texture cache format" - it does not mean that I did not change it. I have short memory. If you will meet that problem again, please get me details about incompatible plugin versions.
