### ISSUE TITLE
[Suggestion] render at constant factor of native resolution

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#837]
Many other emulators render by default at native resolution. Then as an enhancement they allow rendering at a constant factor of native resolution. For example 2x native.

I've asked myself can this bring any benefit for N64 emulators?

Whats the problem with the current method?
The problem is that you have to remove buffers if the in-game resolution changes. This breaks emulation of certain effects.

Which benefits are possible?
1. GLideN64 has hacks to support fb effects after resolution changes. Things like hack_skipvichangecheck. With this modification it should be possible to get rid of it.
2. GLideN64 ends up with buffers with different scale at the same time. This is very bad.

Pokemon Stadium 2: Buffers with different scale are created
![gliden64_pokemon_stadium_2_010](https://cloud.githubusercontent.com/assets/7283660/12539762/ca0b1e90-c2f9-11e5-9537-3faac6739496.jpg)

**Comment by AmbientMalice** [comment]
I think separating internal and display resolution would be a good idea. It would also allow easy downsampling, would it not?

**Comment by gonetz** [comment]
> GLideN64 ends up with buffers with different scale at the same time. This is very bad.

Why?

**Comment by AmbientMalice** [comment]
>Why it is bad?

Looking at the screenshot, it looks to me like the right hand Pokemon portrait is horrible and blurry and the right hand one is clear.

**Comment by purplemarshmallow** [comment]
I think it can cause glitches. Isn't that the reason why GLideN64 removes buffer at VI resolution change?

**Comment by gonetz** [comment]
> Looking at the screenshot, it looks to me like the right hand Pokemon portrait is horrible and blurry and the right hand one is clear.

constant factor of native resolution won't solve it.

> Isn't that the reason why GLideN64 removes buffer at VI resolution change?

GLideN64 removes buffers at VI resolution change because in that case old buffers are usually invalid, but validity check not always can detect it. That causes glitches. PS2 is probably the only game, which uses buffer created in low resolution as texture after resolution is changed. And the game does that for auxiliary buffers only.
Constant factor of native resolution will not help to solve validity issues.

**Comment by purplemarshmallow** [comment]
>constant factor of native resolution won't solve it.

Sure it will both buffer have the same width and if it is sacled (width*constant factor) they will look the same.

It's problematic to have buffers with different scale at the same time. I think the VI and the framebuffer code should work more independent. And complications like this can not help. I'll have to do more experiments.

**Comment by gonetz** [comment]
> Sure it will both buffer have the same width and if it is sacled (width*constant factor) they will look the same.

First pair of portraits is created before the battle, when game works in non-interlaced mode and has 320x240 resolution. Then battle begins and the game switches to 640x480 interlaced. When a  pokemon defeated, you call another one and new portrait created. I don't remember, is the buffer for new portrait  has the same width as previous one. If it is so - you right, the new buffer will look the same.

> It's problematic to have buffers with different scale at the same time.

There is no problem to use a buffer properly if you know how to scale it.

> I think the VI and the framebuffer code should work more independent.

Alas, VI is the only source of information about frame buffer height. It does not help for aux buffers though.

**Comment by purplemarshmallow** [comment]
>First pair of portraits is created before the battle, when game works in non-interlaced mode and has 320x240 resolution. Then battle begins and the game switches to 640x480 interlaced.

My testing showed it's the other way round. before battle it's 640x480 interlaced and during battle it's 320x240 non-interlaced. The low-res buffer is possibly created when the resoultion is zero.

>Alas, VI is the only source of information about frame buffer height. It does not help for aux buffers though.

The VI is not a good source of information about frame buffer height. It's not guaranteed. That was the problem in Donkey Kong 64 (E). I think a good way to solve this problem is to say height does not matter and make buffers too big so everything renders correctly. And then the VI must cut out the correct part and display it.

**Comment by gonetz** [comment]
> My testing showed it's the other way round

You should be right. I just remember that display mode is different for menu and for battle, and that portraits created before game switches the modes. That's why plugin removes only main buffers on internal resolution change and keeps the aux buffers.

**Comment by AmbientMalice** [comment]
Being able to render at native resolution upscaled to your monitor's resolution would be a fantastic enhancement for 2D games where the assets were designed to be viewed at a certain resolution. For example, Mischief Makers.

**Comment by purplemarshmallow** [comment]
rendering at native resoultion would be a useful tool for debugging. Because upscaling is not something unproblematic it can and it does cause problems. You can see it with z64gl. Some bugs are gone in z64gl's lowres mode.

**Comment by gonetz** [comment]
Ok, here the branch for "UseNativeResolutionFactor" feature : 
https://github.com/gonetz/GLideN64/tree/Feature%23837_factor_native_res

It is kinda unfinished. Don't set factor too high. Plugin works incorrect if buffer resolution is higher than screen resolution. For example, if your window resolution is 800x600, don't set factor above 2. You may try to find and fix that issue and remove that limitation.

**Comment by theboy181** [comment]
Could the plugin not detect the current resolution and disable non compatible resolutions? And what about video cards that allow resolutions higher than what they are set to physically.  Can't remeber what ATI called the feature VSR or something.

**Comment by AmbientMalice** [comment]
Setting the factor higher than native would effectively be downsampling if it actually worked. Ideally, GLideN64 should detect the desktop resolution and set GLideN64's "screen resolution" to match on first boot. Then the user can set internal resolution via a dropdown box or a slider.

**Comment by AmbientMalice** [comment]
![n64_resolution_issues](https://cloud.githubusercontent.com/assets/10704701/12935004/59ac218e-cfde-11e5-87fb-8c1ba73c252c.png)

This is pretty great.

**Comment by theboy181** [comment]
jelly!! you have  a bin I can test? still unable to compile over here.

**Comment by AmbientMalice** [comment]
@theboy181

https://mega.nz/#!U551ESJR!U3Ejr2JUtPW2OkndXBj0Rb4q2Q8kN2fraxELrVVbmTA

Only works with mupen64plus currently. You'll have to configure the ini.
UseNativeResolutionFactor = 0 (Normal, buggy behavior.)
UseNativeResolutionFactor = 1 (1x native)
UseNativeResolutionFactor = 2 (2x native)

And so on.

There's some complications. Some games benefit greatly from simply having multiples of native resolution, The black horizontal lines in some games are gone even at higher factors. But Mario Kart 64's vertically split portraits appear at anything higher than native.

**Comment by theboy181** [comment]
I'm not a fan of Mupen+ If only it had a built in Gui. .

**Comment by AmbientMalice** [comment]
>I'm not a fan of Mupen+ If only it had a built in Gui. .

Hopefully Zilmar spec support will be added soon. If I had QT working properly, I'd take a stab at adding it myself.

**Comment by theboy181** [comment]
Seems a little too complicated, but I guess comparability has to have its drawbacks ;)

**Comment by gonetz** [comment]
> And what about video cards that allow resolutions higher than what they are set to physically.

My graphics driver reports that max supported texture size is 16000x16000. If it is true, you can set internal resolution high above any available 4K displays. Currently if you set plugin's internal resolution above screen resolution, it will not work properly. It is not a hardware limitation, just a bug somewhere in the code.

> I'm not a fan of Mupen+ If only it had a built in Gui. .

Mupen64Plus with proper frontend is pretty easy to use.

**Comment by AmbientMalice** [comment]
Normal:
![armymenaircombat-001](https://cloud.githubusercontent.com/assets/10704701/12939137/e5b867b8-d007-11e5-9de6-4df227fd7db7.png)

1x-2x native:
![armymenaircombat-002](https://cloud.githubusercontent.com/assets/10704701/12939164/20716c42-d008-11e5-92fa-3859868c6890.png)

Unfortunately, jumping to 3x native and above causes the lines to reappear. But all in all, this seems like a significant improvement.

**Comment by purplemarshmallow** [comment]
The text in Quest64 is only correct in 1x native res
![1](https://cloud.githubusercontent.com/assets/7283660/12943026/d68640e0-cfde-11e5-849e-f08d68e931e3.jpg)

**Comment by PFCKrutonium** [comment]
Off Topic: I completely forgot Quest64 Existed.

**Comment by purplemarshmallow** [comment]
If the factor is too high part of the screen will be cut off and a square in the bottom left corner is visible. Looks like  #374 maybe these problems are related

**Comment by gonetz** [comment]
I added this branch to master.
New GUI option implemented.
Issues with this feature will be fixed later.

New binary:
https://drive.google.com/file/d/0B0YqMPjGo3B2RDgwUjJGZTVnRHM/view?usp=sharing

**Comment by oddMLan** [comment]
EWJ3D's title screen doesn't look misaligned at x1 resolution
![x1](https://cloud.githubusercontent.com/assets/7278372/13374709/bce2915c-dd49-11e5-96c0-b2a41a7f60d1.png)

EWJ3D's title screen at x2 doesn't look too shabby
![x2](https://cloud.githubusercontent.com/assets/7278372/13374710/be80879e-dd49-11e5-9809-13bb614dc43b.png)

2D Fix branch without optimizations
![x2](https://cloud.githubusercontent.com/assets/7278372/11768227/50b99f9a-a183-11e5-977b-b3c2b04ca4ab.png)

**Comment by gonetz** [comment]
2D fix algorithm does not work for text in that game, so the result.

**Comment by tony971** [comment]
Banjo Kazooie's puzzle effect at the intro screen breaks rendering at 2x resolution. 1x works fine.

**Comment by oddMLan** [comment]
> Banjo Kazooie's puzzle effect at the intro screen breaks rendering at 2x resolution. 1x works fine.

I think it's an issue related to FB effects.
![rendered wrong x2](https://cloud.githubusercontent.com/assets/7278372/13732025/8d37e356-e935-11e5-9579-565d2d57d20e.png)

Conker's pause screen looks wrong at 2x resolution. Works fine in 1x mode. Also works fine if not rendering at a constant factor.

**Comment by gonetz** [comment]
Implemented
