### ISSUE TITLE
[Regression] Perfect Dark enemy cloaking broken.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#839]
Not sure when this started happening, but it must have been fairly recently.

![gliden64_perfect_dark_000](https://cloud.githubusercontent.com/assets/10704701/12580521/061bbaec-c47c-11e5-8203-e9ce761ecba7.jpg)

**Comment by gonetz** [comment]
Ops!

**Comment by gonetz** [comment]
Hmm, regression introduced with commit 0735bd0372, 02 August 2015. Fairly recently :)

**Comment by purplemarshmallow** [comment]
Is it a regression? z64gl shows the correct framebuffer effect. I can't find a version of GLideN64 where it's correct.
![1](https://cloud.githubusercontent.com/assets/7283660/12626894/58a89252-c53b-11e5-98d7-0ccd8515e79c.jpg)

**Comment by AmbientMalice** [comment]
@purplemarshmallow It works somewhat on GLideN64 1.2. Refraction effect doesn't seem quite right, meaning it never "worked" per se, but the garbage is gone. So there's an underlying issue.

**Comment by AmbientMalice** [comment]
Seems fixed.

**Comment by AmbientMalice** [comment]
I am not 100% sure about the accuracy of the effect. It's a really subtle effect that doesn't really have a consistent appearance because of how it grabs FB data to make it. But it's definitely a lot better now.

**Comment by gonetz** [comment]
I am not sure about the accuracy either, but now it looks pretty close to Glide64 and angrylion's plugin.
I've tested the subimage copy functionality with Banjo Tooie, #651, it works correct there.
