### ISSUE TITLE
PGA European Tour framebuffer issue.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#840]
Basically, seems to by copying the wrong part of the image for the background framebuffer around the power meter while taking a swing.

![gliden64_pga_european_tour_000](https://cloud.githubusercontent.com/assets/10704701/12580728/9e4919e4-c47d-11e5-8bc7-10443e631024.jpg)

Angrylion's:
![neae0000](https://cloud.githubusercontent.com/assets/10704701/12580737/b235aa12-c47d-11e5-9f3d-c46eaf573320.jpg)

**Comment by olivieryuyu** [comment]
https://github.com/gonetz/GLideN64/issues/325

duplicate
