### ISSUE TITLE
cube demo wrong textures

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#841]
correct with z64gl
HLE not supported
![gliden64_cube_demo_000](https://cloud.githubusercontent.com/assets/7283660/12594190/1608df72-c475-11e5-9f66-5628669f52e7.jpg)

**Comment by AmbientMalice** [comment]
Maybe fixed now?

![-000](https://cloud.githubusercontent.com/assets/10704701/13976485/f4339ab8-f10b-11e5-9874-66853a6a98a7.png)

![-001](https://cloud.githubusercontent.com/assets/10704701/13976491/029108ca-f10c-11e5-83e4-eab8751fdfa3.png)

**Comment by purplemarshmallow** [comment]
Yes it's fixed
good work!

**Comment by gonetz** [comment]
Interesting, which commit fixed it.
I fixed few legacy texture load issues recently, must be one of those fixes did the job.

**Comment by purplemarshmallow** [comment]
I can't find it, some git versions don't seem to work for me
Looks like it's something before https://github.com/gonetz/GLideN64/commit/16f5bfa423fb248c1066acfe4c500bc008ac8942
