### ISSUE TITLE
Zelda MM:  G_BRANCH_Z not emulated

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#848]
This game uses a peculiar way the G_BRANCH_Z command. It leads without deactivating this command (see GBI.cpp: "else if (strncmp(&uc_str[14], "F3DZ", 4) == 0) current.branchLessZ = false") to have missing graphics in termina field (use demo for arriving to this point of the game)

![dsfdsf](https://cloud.githubusercontent.com/assets/8987490/12731940/8405e9b2-c933-11e5-85c7-ee950bb68bbe.jpg)

Some clue from the output debug strings would suggest that it uses gsSPBranchLessZraw but the values are unclear. This macro is not explained in the manual.

Here some comments about this command, if it can help out: http://wiki.cloudmodding.com/oot/F3DZEX/Opcode_Details#0x04_.E2.80.94_G_BRANCH_Z

Sergey, could you correct me if I am not correct here?

**Comment by olivieryuyu** [comment]
other plugin seems to have a very way to handle this command, but may be they are incorrect.

**Comment by olivieryuyu** [comment]
Angrylion suggested that zraw value could be be reversed by comparing GBI-level depth values as seen in GBI display lists to depth values for the same triangles as seen in low-level display lists.

Would it help?

**Comment by purplemarshmallow** [comment]
You have to keep in mind HLE is not something that can be completed it's endless work and it can never be complete. If you want completeness LLE is your only option.

**Comment by gonetz** [comment]
@olivieryuyu I don't see, how it can help. I don't have problems with GBI-level depth values, they are correct and most likely the same as with low-level display lists. The problem is how translate G_BRANCH_Z parameter to z-value. G_BRANCH_Z does not change vertex z, it just culls part of display list if objects in that part will be clipped by z-buffer. That is it is an optimization technique.
Also, I'm not sure that G_BRANCH_Z for Zelda MM ucode differs from standard G_BRANCH_Z only by format of the z-value. Logic can be altered also.

**Comment by gonetz** [comment]
>If you want completeness LLE is your only option.

Thanks, cap.

**Comment by olivieryuyu** [comment]
Indeed LLE software is the only option for total accuracy ;)

HLE is still a cool concept and i hope it will reach its best level.

**Comment by LegendOfDragoon** [comment]
I agree that HLE is a cool concept. I too hope it will reach its best level. I'm a fan of Zelda MM and would be interested in solving this issue.

Unfortunately I do not have hardware capable of properly running this plugin.

**Comment by purplemarshmallow** [comment]
What would be the benefit of correctly emulating Majora's Mask's G_BRANCH_Z command? Would there be a visible difference?

**Comment by olivieryuyu** [comment]
Hard to tell. It is a low priority case indeed.

**Comment by gonetz** [comment]
> Would there be a visible difference?

If G_BRANCH_Z is really has semantics of branchLessZ in that ucode, there will be no visible difference. Plugin will do more work processing objects, which later will be discarded by depth compare.

**Comment by olivieryuyu** [comment]
let's close this one

**Comment by oddMLan** [comment]
Does commit https://github.com/gonetz/GLideN64/commit/966b2d0f937f850e51510e050b7d97d543f599b6 help in some way (didnt check)

**Comment by gonetz** [comment]
No. Majora's Mask's G_BRANCH_Z  works differently.

**Comment by Gillou68310** [comment]
Here's the implementation of the G_BRANCH_Z command in Majora's Mask:
https://github.com/Gillou68310/GLideN64/commit/1c946bfe08b6fbaa8c3531bf4c805c912aa6460e

@olivieryuyu I could not reproduce the issue with majora's mask demo, could you check if the problem is fixed by your side?

**Comment by olivieryuyu** [comment]
Do you mean with your implementation or Sergey implementation?

In the one of Sergey, there is a hack to avoid the issue: GBI.cpp: "else if (strncmp(&uc_str[14], "F3DZ", 4) == 0) current.branchLessZ = false") which has to be removed.

**Comment by Gillou68310** [comment]
> Do you mean with your implementation or Sergey implementation?

Sergey's one, I'll check without the hack.

**Comment by Gillou68310** [comment]
Ok there's a lot of missing graphics without the hack, but no missing graphics with my implementation.

**Comment by olivieryuyu** [comment]
yes this is it!! :)

Well done!!!!!!

**Comment by gonetz** [comment]
Great! Can I take it?

**Comment by gonetz** [comment]
So, in fact it is not BranchLessZ, it is BranchLessW.
Better to rename it.

**Comment by Gillou68310** [comment]
> Great! Can I take it?

Sure!

> So, in fact it is not BranchLessZ, it is BranchLessW.
> Better to rename it.

Totally agree.

**Comment by gonetz** [comment]
@Gillou68310  Added to master. Works properly. Thanks!
@olivieryuyu I think it can be closed now

**Comment by olivieryuyu** [comment]
thanks a lot!!! :D

**Comment by olivieryuyu** [comment]
Was the comment about shift by one of Gillou taken in account?

**Comment by gonetz** [comment]
No, I just fixed it: 43d281e5bdd

**Comment by olivieryuyu** [comment]
fixed :) 

Merci Gilles!!!!
