### ISSUE TITLE
Goemon - Mononoke Sugoroku: wrong gfx (LLE and HLE)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#856]
![sff](https://cloud.githubusercontent.com/assets/8987490/12873793/269f474e-cdc7-11e5-9ee1-8048886b2a8c.jpg)

start a game, it quicky appears

**Comment by olivieryuyu** [comment]
works with angrylion plugin

**Comment by AmbientMalice** [comment]
Seems fixed. Likely by https://github.com/gonetz/GLideN64/commit/fbbbe147c629d041e3207aa38eadd7d8d3f650b6 https://github.com/gonetz/GLideN64/commit/67cab529090590d1720cf5f942ca17c92b25a98f

**Comment by olivieryuyu** [comment]
fixed
