### ISSUE TITLE
World Cup 98: wrong ground (mip mapping or lod?) (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#858]
![sqdqsdsqd](https://cloud.githubusercontent.com/assets/8987490/12874211/b1d8b342-cdcf-11e5-906b-c0f98e9bd866.jpg)

**Comment by gonetz** [comment]
It seems to be not a bug and definitely not a regression. This black line exists with glN64, Glide64 and angrylion's soft lle.

**Comment by AmbientMalice** [comment]
I think he's probably talking about the grass texture being tiled like that. Dunno how it looks on real hardware, though.

**Comment by gonetz** [comment]
Yes, grass is incorrect, sorry.

**Comment by olivieryuyu** [comment]
Indeed the grass 😄

**Comment by gonetz** [comment]
Several issues with mip-mapping revealed and fixed. Hopefully, mip-mapping is more correct now.
![gliden64_world_cup_98_000](https://cloud.githubusercontent.com/assets/8983092/15018288/c50868a4-123a-11e6-9864-baf8b7195693.jpg)

**Comment by olivieryuyu** [comment]
fixed
