### ISSUE TITLE
Pokemon Snap textures are upside down

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#859]
correct with Glide64
Savestate:
[Pokemon Snap (U).pj.zip](https://github.com/gonetz/GLideN64/files/120855/Pokemon.Snap.U.pj.zip)
![gliden64_pokemon_snap_001](https://cloud.githubusercontent.com/assets/7283660/12874442/4917143e-cdd4-11e5-9c72-005cf64c310e.jpg)
![gliden64_pokemon_snap_000](https://cloud.githubusercontent.com/assets/7283660/12874443/495aa4ec-cdd4-11e5-9ba2-fbae3ae1f2b5.jpg)

**Comment by purplemarshmallow** [comment]
This is a regression but a really old one.
Public Release 1 is incorrect but glN64 0.4.1 is correct.

**Comment by gonetz** [comment]
Fixed
