### ISSUE TITLE
Super Smash Bros. 64 Hitboxes Solid (Should be transparent with cube outline) 

### ISSUE THREAD

**Issue by DetreRaison** [gonetz/GLideN64#860]
How it looks - http://i.imgur.com/oa3PFyS.png

How it should look - http://www.ssbwiki.com/images/thumb/0/01/Fox_Down_Special_Initial_Hitbox_Smash_64.png/120px-Fox_Down_Special_Initial_Hitbox_Smash_64.png

The original glide64 version didn't have this problem but the hitboxes were solid red but included the pink outline, or that is how they are supposse to look  on console (I don't think so) but I can't verify.

**Comment by theboy181** [comment]
Already discussed here
https://github.com/gonetz/GLideN64/issues/830

**Comment by olivieryuyu** [comment]
please closed as it is a duplicate
