### ISSUE TITLE
MAME64 incorrect menu

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#861]
Correct with Glide64. But with Glide64 you can't start a game because this needs LLE.

![gliden64__000](https://cloud.githubusercontent.com/assets/7283660/12918290/b4c47ddc-cf3e-11e5-81ee-c6942a851961.jpg)

**Comment by gonetz** [comment]
Fixed

**Comment by purplemarshmallow** [comment]
fixed
