### ISSUE TITLE
bottom of the 9th: screen not centered

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#862]
![dfsfsdf](https://cloud.githubusercontent.com/assets/8987490/12928778/bb50d688-cf6f-11e5-8bbc-1102bf6cf8ab.jpg)

angrylion plugin:

![sdfsdf](https://cloud.githubusercontent.com/assets/8987490/12928780/c3adc84a-cf6f-11e5-921a-7f9f208db51d.jpg)

**Comment by gonetz** [comment]
Fixed
