### ISSUE TITLE
Aerofighter's Assault: wrong textures on planes

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#863]
![sans titre](https://cloud.githubusercontent.com/assets/8987490/12935849/5bcbdef4-cf99-11e5-982f-b78cfe35948f.jpg)

**Comment by AmbientMalice** [comment]
Isn't this a duplicate of https://github.com/gonetz/GLideN64/issues/628?

**Comment by gonetz** [comment]
Yes, duplicate.
