### ISSUE TITLE
Bettle Adv Racing: missing gfx (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#866]
![sans titre](https://cloud.githubusercontent.com/assets/8987490/13008165/0e9fba08-d195-11e5-90a2-ce4b95a6b893.jpg)

OOOOPPPPPPSSSSS!

**Comment by matthewharvey** [comment]
To be specific, it's not the clipping that is the issue, but the total lack of trees (2D sprites I'm assuming) that normally block the clipped off track from view.

Bisected back to 1d1f4bdbb4b065aae92fabbb3aa60434f7bf81bb : Alpha compare should happen after the 1st cycle of a two-cycle combiner
    Fixed invisible rocks in Mischief Makers intro.

Tested on Debian with Mesa as the graphics stack.

**Comment by purplemarshmallow** [comment]
This is really bad since https://github.com/gonetz/GLideN64/commit/1d1f4bdbb4b065aae92fabbb3aa60434f7bf81bb is an accuracy improvement confirmed by hardware tests and angrylion's plugin works correctly with it

**Comment by weinerschnitzel** [comment]
Or a really good lead?

**Comment by olivieryuyu** [comment]
well an accuracy fix may reveal a bug somewhere else ...

**Comment by AmbientMalice** [comment]
Vegetation is back, but disappears when camera is close, and mipmapped signposts lack transparency.

**Comment by gonetz** [comment]
Thanks for the bug reports!
I had to put my alpha compare fixes to separate branch, because it is hard matter. Lots of hard-to-take-into-account nuances, especially without pixel coverage emulation.

**Comment by gonetz** [comment]
Hopefully fixed.

**Comment by matthewharvey** [comment]
Looks fixed to me.

I'm noticing that there are no longer any reflections coming off of the wind shield of the cars. This is only when FBInfo is enabled. Should I file another bug?

**Comment by AmbientMalice** [comment]
@matthewharvey If you're using mupen64plus, it's likely the emulator's fault because m64+'s fbinfo support is flaky. If the reflections are missing with mupen64, too, it means it's the plugin's fault.

**Comment by gonetz** [comment]
or Mupen64 fault. Mupen64 is not perfect also.

**Comment by olivieryuyu** [comment]
fixed
