### ISSUE TITLE
High resolution textures not loading since public release 1.2

### ISSUE THREAD

**Issue by hellbringer616** [gonetz/GLideN64#868]
I'm having a strange issue with PJ64 and the public release of 1.2 (also any builds past that) where high resolution textures aren't functioning. they flat out don't load.

I have tried older version of PJ64 (back to v2.1) builds but still nothing.

If any more information is needed let me know.

OS is Windows 7 x64
GPU nVidia GTX 680
CPU Intel i5-4590k

**Comment by PFCKrutonium** [comment]
It's working for me, though the water texture in Majoras Mask doesn't seem to work.

**Comment by hellbringer616** [comment]
What builds are you using? I dunno how to compile myself so i use PJ64 and GlideN64 builds from Emucr.com

However the public release 1.2 is from here so i wasn't entirely convinced it was an issue with their builds

Anyway i am using PJ64 v2.2.0.9999 (dated 2/14/16 http://www.emucr.com/2016/02/project64-git-20160214.html)
GlideN64 vUnkown (dated 2/10/16 http://www.emucr.com/2016/02/gliden64-git-20160210.html)
nVidia Driver v361.43

**Comment by gonetz** [comment]
> GlideN64 builds from Emucr.com

This is the problem.  The plugin needs QT linked without libpng, otherwise HD textures won't load.  Emucr uses standard QT build. 
Try one of builds compiled by me.

**Comment by hellbringer616** [comment]
It happens in the 1.2 release from this very website though. Hence the bug report.

**Comment by gonetz** [comment]
Your system specs are ok, so texture packs must work. Have you tried to load the same pack with Glide64 or RiceVideo?

**Comment by hellbringer616** [comment]
Yes, it works fine in glide64, haven't been able to try rice video.

**Comment by gonetz** [comment]
I need to clarify : do you load the pack from original .png textures or from cache file? I ask it because texture cache file created with Glide64 is not compatible with GLideN64 .

**Comment by hellbringer616** [comment]
I load it from pngs, when testing I turn off the cache and delete it to make for sure it does.

**Comment by gonetz** [comment]
Ok, please give me a link to the pack. All packs I have load with no problems.

**Comment by hellbringer616** [comment]
Community texture pack v7
http://www.emutalk.net/threads/55307-Zelda-Ocarina-of-time-Community-Retexture-Project-V7

Here is the direct download link http://adf.ly/upDqB

**Comment by hellbringer616** [comment]
Not sure how double posting works with Github (frowned on for forums)
But what set up are you using for PJ64? and did you download/compile your version yourself?

**Comment by vgturtle127** [comment]
@hellbringer616 Double posting is fine as long as it is relevant information. :smile: 

Can I have a screenshot of your settings? Just curious.

**Comment by hellbringer616** [comment]
![emulation](https://cloud.githubusercontent.com/assets/11658143/13274918/59b6df80-da7d-11e5-9fd9-366f926c6123.PNG)
![texture](https://cloud.githubusercontent.com/assets/11658143/13274917/59b6955c-da7d-11e5-8cb3-e9160b6f6af3.PNG)
![video](https://cloud.githubusercontent.com/assets/11658143/13274919/59b78b2e-da7d-11e5-8876-4102147fe978.PNG)
Here you go, i don't have anything in post changed at all.

Adjusted the alpha and crc calculations doesn't effect it.

**Comment by gonetz** [comment]
The pack loaded with no problems. Just tested it with release 1.2
It has known issue with sky textures, but it is not plugin's fault.

* Be sure that path to pack is Plugin\hires_texture\THE LEGEND OF ZELDA\
* The packs takes more than 800mb of memory. You should have at least 1gb of free memory before running the emulator.
* Default texture cache size is probably too low for that pack. Set at least 800MB.
![gliden64_the_legend_of_zelda_005](https://cloud.githubusercontent.com/assets/8983092/13294707/752066e2-db4f-11e5-917a-3a08eeacbc53.png)
