### ISSUE TITLE
Bust-A-Move 2 wrong 2D during intro

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#870]
![gliden64_bust_a_move_2_000](https://cloud.githubusercontent.com/assets/7283660/13115968/4ebaf3ce-d59a-11e5-86f8-45a73a61e4ac.jpg)

**Comment by AmbientMalice** [comment]
Appears to be fixed now.

![bust_a_move_2-000](https://cloud.githubusercontent.com/assets/10704701/13976326/86957dc4-f10a-11e5-83d4-4790b3892d67.png)

**Comment by gonetz** [comment]
Great!

**Comment by purplemarshmallow** [comment]
fixed

**Comment by olivieryuyu** [comment]
not fixed, can u reopen?

**Comment by AmbientMalice** [comment]
It must have regressed very recently.

**Comment by gonetz** [comment]
Hmm, it works correct with Mupen64, but not with Project64 or 1964

**Comment by gonetz** [comment]
Fixed

**Comment by theboy181** [comment]
looks good here

**Comment by gonetz** [comment]
Lets close it then.
