### ISSUE TITLE
Anti Aliasing broken in OoT (even with texture packs)

### ISSUE THREAD

**Issue by OldGnashburg** [gonetz/GLideN64#876]
Hey all, while using anti-aliasing at any setting, this seems to happen on PR 1.2 with and without Djipi's OoT 2014 HD Texture Pack
![gliden64_the_legend_of_zelda_047](https://cloud.githubusercontent.com/assets/11412147/13411440/3f32e416-defa-11e5-8a1e-bd1e3651fac9.jpg)
![gliden64_the_legend_of_zelda_048](https://cloud.githubusercontent.com/assets/11412147/13411549/dfe86f70-defa-11e5-9724-17059e6393d1.jpg)

Also, since I cannot seem to build GLideN64 myself can somebody send me a build for Project 64 (which I easily installed without the malware, even before I knew there was malware in it) with the latest commits?

**Comment by OldGnashburg** [comment]
Sorry for double posting, but Majora's Mask has the same problem.

**Comment by AmbientMalice** [comment]
You've likely got N64 depth enabled.

**Comment by OldGnashburg** [comment]
Yes I do. Issue closed
