### ISSUE TITLE
Breakable walls in Majora's Mask display wrong

### ISSUE THREAD

**Issue by OldGnashburg** [gonetz/GLideN64#877]
Breakable walls seem to be discolored in Majora's Mask as if they are covered in shadows.

![gliden64_zelda_majora s_mask_024](https://cloud.githubusercontent.com/assets/11412147/13411760/456b20ee-defc-11e5-958c-e68a37756604.jpg)

It also happens in Glide64.

**Comment by OldGnashburg** [comment]
Also can somebody send me a build of GLideN64 with the latest commits for even further nitpicking?

**Comment by gonetz** [comment]
The same problem as #778, wrong implementation of point lighting.

**Comment by olivieryuyu** [comment]
@OldGnashburg

please check with the build zeldamm_point_light branch as you can find here:

#778

Is it fixed?

**Comment by olivieryuyu** [comment]
@gonetz 

May be it could be closed? :)

**Comment by gonetz** [comment]
Ok
