### ISSUE TITLE
[Majora's Mask] Specific Stock Pot Inn wall texture broken.

### ISSUE THREAD

**Issue by OldGnashburg** [gonetz/GLideN64#878]
The missing wallpaper texture in the Stock Pot Inn in the Knife Room displays improperly when you enter the room and when you view it from certain angles.
![gliden64_zelda_majora s_mask_005](https://cloud.githubusercontent.com/assets/11412147/13411950/42a774e2-defd-11e5-9568-7f5dca7f3126.jpg)

**Comment by olivieryuyu** [comment]
@OldGnashburg 

please check with the build zeldamm_point_light branch as you can find here:

https://github.com/gonetz/GLideN64/issues/778

Is it fixed?

**Comment by olivieryuyu** [comment]
@OldGnashburg 

can you please close?

**Comment by olivieryuyu** [comment]
@gonetz 

May be it could be closed? :)

**Comment by gonetz** [comment]
Must be closed :)
