### ISSUE TITLE
[Majora's Mask] Moon Fireball effect displays wrong.

### ISSUE THREAD

**Issue by OldGnashburg** [gonetz/GLideN64#879]
When the moon bursts into flames during the cutscene with the giants stopping the moon from crashing just in time. The flame effect displays wrong.

![gliden64_zelda_majora s_mask_001](https://cloud.githubusercontent.com/assets/11412147/13412055/ebdb42a0-defd-11e5-8bf4-35a4c7e3e51b.jpg)

Here is the effect using angrylion's plugin
![image](https://cloud.githubusercontent.com/assets/11412147/13412293/756ade30-deff-11e5-9c64-165f1a3b3428.png)

**Comment by gonetz** [comment]
savestate needed

**Comment by OldGnashburg** [comment]
Sure, here you go:
[https://www.dropbox.com/s/q36b811x37974i3/The%20Legend%20of%20Zelda%20-%20Majora%27s%20Mask%20%28U%29.pj.zip?dl=0](url)

Also Gonetz, do you think you would be able to upload a build of GLideN64 with the latest commits on to this issue thread so I can do some more testing/nitpicking.

**Comment by gonetz** [comment]
Last week master:
https://drive.google.com/file/d/0B0YqMPjGo3B2RDgwUjJGZTVnRHM/view?usp=sharing
Not so many changes made since then.

**Comment by gonetz** [comment]
The link to the save does not work. Please re-upload.

**Comment by gonetz** [comment]
I don't see any problems now. Please check again.

**Comment by gonetz** [comment]
Closed. Please reopen if problem still exists.
