### ISSUE TITLE
Screenshots cropped (worse in native resolution mode)

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#883]
This is from PAL Mischief Makers.

![gliden64_mischief_makers_001](https://cloud.githubusercontent.com/assets/10704701/13446735/b3ab88bc-e061-11e5-8bcb-39c4d8bfe276.jpg)

**Comment by oddMLan** [comment]
Enabling Antialasing makes the screenshots completely black for me.

**Comment by gonetz** [comment]
Better open a new ticket.
