### ISSUE TITLE
[HLE] Mario 64 incorrect darkening effect.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#884]
Mario 64 darkens doors when you look at them at certain angles. This effect is currently broken in HLE, but working in LLE. Works in Glide64.

![gliden64_super_mario_64_000](https://cloud.githubusercontent.com/assets/10704701/13448486/6cb06ae6-e06f-11e5-8080-141bad7f995a.jpg)

![gliden64_super_mario_64_001](https://cloud.githubusercontent.com/assets/10704701/13448504/860d08aa-e06f-11e5-833e-062998233e8f.jpg)

**Comment by purplemarshmallow** [comment]
Mario 64 and Tetrisphere use the same ucode #681

**Comment by fzurita** [comment]
It seems even worse in Android. It's always messed up at *any* angle.

See this screenshot:
https://drive.google.com/file/d/0B57Ioy26LWegUWRKaXp4UEJvbnc/view?usp=docslist_api

**Comment by AmbientMalice** [comment]
Seems fixed.

**Comment by fzurita** [comment]
Just tried in Android, it's no longer broken.
