### ISSUE TITLE
Some dumped textures have red and alpha channel swapped

### ISSUE THREAD

**Issue by TaoCG** [gonetz/GLideN64#886]
I noticed that some dumped textures have their red and alpha channels swapped. Actually I believe that all *0_all.png and *1_all.png files are affected, there are just some were you won't notice because every pixel has the same value in all channels. I swapped the channels back with ImageMagick and attached a few before/after examples from Majora's Mask.

![zelda majora s mask 8c2e47a1 3 0_all](https://cloud.githubusercontent.com/assets/966232/13499499/fd44259e-e15e-11e5-8d2b-f2f388721cab.png) ![zelda majora s mask 8c2e47a1 3 0_all](https://cloud.githubusercontent.com/assets/966232/13499622/73399748-e15f-11e5-9934-cd65887ec5ab.png)

![zelda majora s mask 3c8bfc6e 3 0_all](https://cloud.githubusercontent.com/assets/966232/13499670/9e445860-e15f-11e5-857f-c037f4877cd6.png) ![zelda majora s mask 3c8bfc6e 3 0_all](https://cloud.githubusercontent.com/assets/966232/13499673/a12aa980-e15f-11e5-91a9-d7889cb8b62f.png)

![zelda majora s mask a55a936c 3 1_all](https://cloud.githubusercontent.com/assets/966232/13499752/dd99aaba-e15f-11e5-8e3a-1e71a54e5b8c.png) ![zelda majora s mask a55a936c 3 1_all](https://cloud.githubusercontent.com/assets/966232/13499760/e5a72746-e15f-11e5-854e-fa59ff3939de.png)

![zelda majora s mask afe41a01 3 1_all](https://cloud.githubusercontent.com/assets/966232/13499751/dd964992-e15f-11e5-816c-d7b558d998ff.png) ![zelda majora s mask afe41a01 3 1_all](https://cloud.githubusercontent.com/assets/966232/13499759/e5a5f40c-e15f-11e5-9ff5-c5d5b1f21a61.png)

As you can see all the pixels that should be black are completetly transparent, which makes it difficult to identify some textures.

**Comment by gonetz** [comment]
I've corrected that particular issue:
91b48c9acd

Please report if you will find some other problems with texture dumping.

**Comment by gonetz** [comment]
Closed. Please reopen if you will find some other problems with texture dumping.
