### ISSUE TITLE
HD texture Loading broken 

### ISSUE THREAD

**Issue by fivefeet8** [gonetz/GLideN64#887]
With the latest changes, HD texture loading no longer works on Mupen64AE v3 alpha on Android.

**Comment by gonetz** [comment]
I just checked, it works.
Be sure that path to the HD pack is /storage/emulated/0/mupen64plusae-v3-alpha/CoreConfig/UserData/mupen64plus/hires_texture/
and that texture pack folder has correct name.
For example, for SM64 the full path is
/storage/emulated/0/mupen64plusae-v3-alpha/CoreConfig/UserData/mupen64plus/hires_texture/SUPER MARIO 64

**Comment by fivefeet8** [comment]
I'm using a .htc file in the /storage/emulated/0/mupen64plusae-v3-alpha/CoreConfig/UserCache/mupen64plus/cache folder.  It doesn't load the .htc at all.  Is there something that changed for using .htc files then?  It's always loaded the .htc file from there before.
