### ISSUE TITLE
DK64 Kiosk Demo crash.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#889]
Game crashes after the DK64 logo splash screen.

**Comment by gonetz** [comment]
Can't reproduce.

**Comment by AmbientMalice** [comment]
It's still happening for me. Occurs directly after this screen. For clarification, this only occurs with the Kiosk Demo version of DK64. Normal versions aren't affected.

![d_k_display-001](https://cloud.githubusercontent.com/assets/10704701/14226382/e64f24c4-f923-11e5-94e4-0ebc3d5dd08d.png)

**Comment by gonetz** [comment]
Can't reproduce it. I press start and fight with the dragon begins. No problems.

**Comment by AmbientMalice** [comment]
I'll do some more testing.
