### ISSUE TITLE
[Native Resolution] DK64 displaced screen on Android.

### ISSUE THREAD

**Issue by retrobenny** [gonetz/GLideN64#891]
In 4x mode and most likely the others,the logo screen problem is that only the bottom left portion is visible and when pausing and other events that display buffer images,the image drops to the bottom left slightly.
Hope the screenshots work.

![2016_03_05_12 53 09](https://cloud.githubusercontent.com/assets/16418716/13549787/f4bac05c-e2d2-11e5-926d-a1515cc925aa.png)

![2016_03_05_12 54 00](https://cloud.githubusercontent.com/assets/16418716/13549789/02db0b7e-e2d3-11e5-875d-438fb7fef549.png)

**Comment by retrobenny** [comment]
Also happens in Conker's pause menu and still happens in both games since the recent build update for Mupen64Plus AE.

**Comment by gonetz** [comment]
Plugin works incorrect when internal resolution is above screen resolution. It is known issue.

**Comment by retrobenny** [comment]
What scale factor do I use with non-wide 1080P then?

**Comment by gonetz** [comment]
Depends on game's internal resolution. For most common 320x240 3X is max for the moment.

**Comment by retrobenny** [comment]
Okay,the recent updates were merged again on Android,so I have Mupen64Plus AE on Native resolution (highest quality) "on the emu part" and anything above scaling 1x persists with the pause screen issue while 1x makes it look LESS sharp oddly enough.
I thought that setting was for making the default buffers render at higher resolution from the start to prevent the extra task of rendering the original buffer then upscaling it,and instead rendering an upscaled buffer immediately.
Maybe the Android port is broken in a unique way with either itself or driver related issues?

**Comment by gonetz** [comment]
DK64 internal resolution is 640x480 in some places, e.g. in logo. 2X means that your device must have resolution above 1280x960. I'm not sure that mupen64plus-ae uses all screen, thus real screen resolution available for the graphics plugin can be less than device resolution. You may check adb log for information about selected resolution.

**Comment by retrobenny** [comment]
I actually knew that because of the glitch in Glide64 Final on PJ64 that occurs after a crash that allows you to restart the game when I was code hunting,it would cut the sceen in a very similar way due to the Nintendo logo screen being 640x480 then switching to 320x240 for the main game.
And I know that from an address with dimensions in hex starting at the values for 640 then 320 respectively at those key moments,when I was trying to hack dimensions to make it fill the emu screen or maybe even a hack to force it to stay in 640x480 resolution which would be a really cool feat.

**Comment by retrobenny** [comment]
Pause screens like DK64 and Conker have been fixed as of the most recent update to Android,but DK64's logo intro still messes up.
