### ISSUE TITLE
[Regression] Conker shadows line on the invisible square.

### ISSUE THREAD

**Issue by retrobenny** [gonetz/GLideN64#894]
Even happens without the scale factor enabled and at 640x480 resolution,looks the same on 3.0 and 3.1.
Also appears on other NPCs and objects.

![2016_03_06_12 27 26](https://cloud.githubusercontent.com/assets/16418716/13556127/b0017b48-e397-11e5-9ece-01f9913f1b3f.png)
![2016_03_06_12 28 22](https://cloud.githubusercontent.com/assets/16418716/13556130/c13a862a-e397-11e5-948e-3a82c6c18805.png)
![2016_03_06_12 29 31](https://cloud.githubusercontent.com/assets/16418716/13556135/ca2191c0-e397-11e5-9b06-cb516ffa8409.png)
![2016_03_06_12 30 10](https://cloud.githubusercontent.com/assets/16418716/13556136/d3e9cdbc-e397-11e5-8a4e-25028089a521.png)

**Comment by oddMLan** [comment]
This is a side effect introduced ever since MSAA antialasing was implemented
@gonetz Could it be circumvented with a hack? It seems pretty much the only game with a side effect created by antialasing.

**Comment by purplemarshmallow** [comment]
duplicate #519 

>Could it be circumvented with a hack? It seems pretty much the only game with a side effect created by antialasing.

Not quite #526  #249

**Comment by AmbientMalice** [comment]
I've mentioned this before, but I think MSAA should be scrapped in favor of FXAA or SMAA plus internal resolution scaling. MSAA breaks native resolution mode's benefits, for example. It's just so much trouble. I know FXAA/SMAA have their own problems, especially with UI filtering, but MSAA is so much more broken.

**Comment by retrobenny** [comment]
Android can't use MSAA for the black screen issue happening likely caused by EGL issues.
Those screenshots of mine are without MSAA.

**Comment by gonetz** [comment]
> @gonetz Could it be circumvented with a hack?

It is possible to disable AA for 8bit aux buffers.

**Comment by oddMLan** [comment]
>It is possible to disable AA for 8bit aux buffers.

The smoothed out jagged borders of the shadows looked nice with AA, but if that's the viable solution then I agree. I was thinking of cropping the last few rows of pixels so the borders weren't visible, but that's a way more uglier hack in comparison.

**Comment by retrobenny** [comment]
Conker shadows are fixed now as of fzurita's build update for AE.
