### ISSUE TITLE
Black screen displayed in majora's mask and OoT until emu closes and restarts

### ISSUE THREAD

**Issue by shadelegend333** [gonetz/GLideN64#899]
I keep getting a black screen on the Zelda games (maybe others, haven't checked) when they aren't the first ROM I load when I start PJ64. This also happens when switching between the two.

Checked either some reddit thing or some forum and said not to use LLE, I think, but HLE is enabled? IDK...

**Comment by LegendOfDragoon** [comment]
Try seeing if this happens for other games too.

**Comment by shadelegend333** [comment]
Well what do ya know.
looks like it is happening to most of the games I'm trying (except for the ones that make the emulator crash from a memory error or not respond, but that I guess might be a separate issue).

**Comment by shadelegend333** [comment]
Sometimes after I successfully load roms, textures in a later scene will be missing and then the game crashes too.

**Comment by LegendOfDragoon** [comment]
I was thinking you might have an Intel IGP. If you do, then that's likely the reason for your problem.

**Comment by shadelegend333** [comment]
Yeah. Running on a laptop with Intel HD4600.

Is it drivers, or is it the actual hardware that's the problem?

**Comment by PFCKrutonium** [comment]
As I understand it, it is a Driver issue.

**Comment by LegendOfDragoon** [comment]
>Is it drivers, or is it the actual hardware that's the problem?

Either driver or software. z64gl does not have this problem for me, when I used Threaded. HatCat's OpenGL code also is fine for me, when initializing in InitiateGFX instead of Rom Open.

**Comment by olivieryuyu** [comment]
It is a driver issue. 

Can it be closed pls?
