### ISSUE TITLE
Tripleplay2000: pause menu in game leads to error line 69

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#90]
![sdf](https://cloud.githubusercontent.com/assets/8987490/4908882/3faf0062-646e-11e4-811b-0b45a26a1c26.jpg)

**Comment by gonetz** [comment]
Please test with newer build.

**Comment by olivieryuyu** [comment]
fixed but 3d goes wild now?

**Comment by gonetz** [comment]
3d goes wild only with new PJ64, with any gfx plugin. PJ64 1.6 works correct with that game.

**Comment by Predator82Germany** [comment]
Then should copied to PJ64 issues
