### ISSUE TITLE
REGRESSION: Conker's BFD shows FB as texture intermitently

### ISSUE THREAD

**Issue by oddMLan** [gonetz/GLideN64#902]
http://webm.host/6e538/vid.webm

Messing around with the FB options doesn't help.
Happen's in current week's master 0ec6d9d and past week's master 675d777

Doesn't happen in 78d7c99

I managed to find one spot in which you can see the bug while standing still
[bug.pj.zip](https://github.com/gonetz/GLideN64/files/171282/bug.pj.zip)

It's important to use the latest PJ64 builds to be able to load the state since the format it's incompatible with older versions, and I think with other emulators too.
Here you can find the latest builds http://hyvart.com/download/project64/ci/

If loading my savestate freezes the emulator, press F5 to make a savestate then F7, and then load my savestate to work around it.

Only tested the U version.

**Comment by gonetz** [comment]
Thanks, I found what broke it.

**Comment by oddMLan** [comment]
Fixed!!
