### ISSUE TITLE
Enabling and disabling Antialasing midgame makes the emulator crash

### ISSUE THREAD

**Issue by oddMLan** [gonetz/GLideN64#903]
Only tested Project64.

Happens when AA is disabled and then set to any level, but not the other way round.

GFX Card: AMD Radeon R7 200 Series with latest drivers
OS: Windows 10 x64 build 10586.164

**Comment by gonetz** [comment]
Will be fixed.

**Comment by oddMLan** [comment]
Fixed. :+1:
