### ISSUE TITLE
Taking a screenshot with Antialasing on come out completely black

### ISSUE THREAD

**Issue by oddMLan** [gonetz/GLideN64#905]
Can anyone confirm?

GFX card: AMD Radeon R7 200 Series
Tested with Project64.

**Comment by gonetz** [comment]
Confirmed. Will be fixed.

**Comment by oddMLan** [comment]
![gliden64_donkey_kong_64_000](https://cloud.githubusercontent.com/assets/7278372/13905156/601aa68a-ee74-11e5-9a7c-e32db7073456.png)
Fixed :)
