### ISSUE TITLE
(Regression) Duke Nukem 64 menu transparency bug.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#906]
When you transition between menus, a purple outline briefly appears around the text.

![gliden64_duke_nukem_000](https://cloud.githubusercontent.com/assets/10704701/13744737/831e7d34-ea35-11e5-9c8b-fda64e5c3955.jpg)

**Comment by gonetz** [comment]
Hmm. Very old regression, September 2015

**Comment by gonetz** [comment]
Fixed.
