### ISSUE TITLE
Super B-Daman - Battle Phoenix 64: Missing collision detection

### ISSUE THREAD

**Issue by ghost** [gonetz/GLideN64#908]
When my shots was hit, it will not be given the damage.
You loading my state, then hits A button.
https://mega.nz/#!V150zCpR!aiUN1Y3wPvnc4kWe1K_sVu1BiSqcpgD7uGzEE5OpcF4

In Glide64, it will work correctly enable Software depth buffer rendering.

**Comment by AmbientMalice** [comment]
Can confirm. Glide64 gives a blank screen with Glide64, so FB has to be disabled. Hit detection is broken. Almost certainly caused by GLideN64's broken depth buffer.

**Comment by gonetz** [comment]
I can't open the save file. Please test again with depth buffer copy set to software render.

**Comment by AmbientMalice** [comment]
Seems fixed by https://github.com/gonetz/GLideN64/commit/669337f5ab88d1d35d0c44d557a1c54218cdd904

**Comment by gonetz** [comment]
Thanks! Closed.
