### ISSUE TITLE
Super Robot Spirits: Crash rankings option in HLE.

### ISSUE THREAD

**Issue by exhalatio** [gonetz/GLideN64#909]
When I look at the rankings option in the HLE, PJ64 just crashed.
In LLE will work correctly.

You loading my state, then press A button.
https://mega.nz/#!o550GLyJ!1BQvURiEHZTm2PS9WvpZ2eb_7ubH0V8LDSV3NIJfF-s

**Comment by olivieryuyu** [comment]
Confirmed

As well in HLE there is now strange flickering. Just boot the game. That is a regresssion.

**Comment by gonetz** [comment]
The save file is incompatible with PJ64 2.X, I can't load it.

**Comment by AmbientMalice** [comment]
Save file works for me, @gonetz. I'm using recent-ish PJ64 compiled from source.

**Comment by gonetz** [comment]
I use pj64 2.x, so I need compatible save

**Comment by AmbientMalice** [comment]
PJ64 is still 2.x As far as I know, the save format hasn't changed.

**Comment by purplemarshmallow** [comment]
PJ64's savestates are currently buggy it needs to be fixed https://github.com/project64/project64/issues/954

**Comment by exhalatio** [comment]
@gonetz
You can test in two steps
Press the up button on the title screen, and select "オプション" (Options).
![title](https://cloud.githubusercontent.com/assets/7089513/13903665/6a21abfc-eec8-11e5-9ac5-f9fd1af06a78.png)

Select the third from the top Lanking options "ランキングオプション" in the next screen.
![option](https://cloud.githubusercontent.com/assets/7089513/13903666/706044ba-eec8-11e5-919a-08f42ffb236b.png)

**Comment by gonetz** [comment]
Thanks, I reproduced the bug. The problem somewhere in BG command, which is HLE macro.

**Comment by gonetz** [comment]
Fixed

**Comment by exhalatio** [comment]
Works fine, thank you.
