### ISSUE TITLE
Yoshi's Story 4-2 water artifacts + Paper Mario black subscreen background

### ISSUE THREAD

**Issue by SigmaVirus** [gonetz/GLideN64#911]
I have noticed recently that the water is somewhat broken in Yoshi's Story 4-2 Jungle Puddle again showing weird artifacts.

This is how it looked using a build from 2015-09-28 with only minor artifacts:
http://s22.postimg.org/mqwxj7okh/Yoshi_w.png

And this is how it looks today using a build from 2016-03-13:
http://s10.postimg.org/r5tmezd7d/Yoshi.png

As for Paper Mario the background is black on the subscreen but as far as I know it should be like this (build from 2015-09-28):
http://s10.postimg.org/8eiidc3vd/Paper_Mario_w.png

But this is how it's look today (build 2016-03-13):
http://s30.postimg.org/s96whvhwx/Paper_Mario.png

I don't really know what have happened since last September that could have caused this.

**Comment by baptiste0602** [comment]
Yoshi Story : no problem for me -> Project64 last version, GlideN64 2016-03-13 & GeForce GTX670
Paper Mario : i can't confirm, i don't have this game

**Comment by AmbientMalice** [comment]
Could you post a save state(s)?

**Comment by SigmaVirus** [comment]
@baptiste0602 
OK, the only thing I see that's different from what I'm using is a different GPU, I got a AMD R9 380 card which I use the latest drivers for.

I'm starting to feel more and more that it depends on what kind of GPU you have these days and AMD seems to be bad or something.

You are absolutely sure you don't see those artifacts?

@AmbientMalice 
You got the European versions? OK for which game then, Yoshi's Story or Paper Mario?
I'll try post them later today.

**Comment by SigmaVirus** [comment]
OK here is a save state for Yoshi's Story right at the artifacts:
http://s000.tinyupload.com/index.php?file_id=58563359036636046499

As for Paper Mario it seems related to whether Copy depth buffer to RDRAM is enabled or not.
Here is how it looks with it off (it was on before):
http://s23.postimg.org/e6wmznnx7/Paper_Mario_w2.png

As you can see it's semi working meaning it's not black but not correct either.
The background should be resembling the first screenshot I posted from the 2015-09-28 build where Mario stands and you press start.

Anyway here's a save state:
http://www.filedropper.com/papermarioeuropepj

**Comment by gonetz** [comment]
Please open one ticket per issue.

**Comment by gonetz** [comment]
I can't open your save state for Yoshi's Story. For which PJ64 version is it? Please upload save for PJ64 2.x

**Comment by SigmaVirus** [comment]
@gonetz 
I'll make sure to remember that next time, thanks!

As for the issues this is all you need:

Project64 2.2.0.9999
http://hyvart.com/download/project64/ci/0.0.0.427/Win32.zip

GLideN64 (2016-03-13) built by you gonetz:
https://drive.google.com/file/d/0B0YqMPjGo3B2VkZ6ZnE0M0RQZTQ/view?usp=sharing

Make sure you use the European/PAL versions of the games which I can't provide BTW for obvious reasons.

**Comment by gonetz** [comment]
GLideN64 current, default settings:
![gliden64_yoshi_story_000](https://cloud.githubusercontent.com/assets/8983092/13904057/960c699c-eebd-11e5-8dbd-aa9bc1a85c68.png)

**Comment by SigmaVirus** [comment]
@gonetz 

AMD or Nvidia?

I still get the artifacts with default settings.

**Comment by gonetz** [comment]
Radeon HD 6800

**Comment by SigmaVirus** [comment]
OK, so apparently it's not GPU brand related.

What OS are you on and which driver version?

I'm on Windows 10 and Crimson 16.1.1 WHQL

**Comment by gonetz** [comment]
I very doubt that it is OS or driver version related.

**Comment by SigmaVirus** [comment]
So what could it be then?

**Comment by gonetz** [comment]
I don't know. I tested on Win10 with other radeon card, no probs also.

Try my latest build from here:
https://github.com/gonetz/GLideN64/issues/885

**Comment by oddMLan** [comment]
Latest current build from #885 cf8d597458559e6535783f80526e78370148d6e1
Windows 10, AMD Radeon R7 200 Crimson Driver ver 15.30.1025.1001
![gliden64_yoshi_story_001](https://cloud.githubusercontent.com/assets/7278372/13905467/a28ea63e-ee7d-11e5-967b-f545362b484a.png)

Could not reproduce. 

@SigmaVirus Did you test using default settings? If not, try clicking "Restore Defaults" in GLideN64's config window. Then close the emulator and try again. Also make sure your "shaders" folder is empty. Or check "Disable shader storage" under the plugin's settings to see if that did the trick.

**Comment by SigmaVirus** [comment]
@gonetz and @oddMLan 

I have tried it all even with the latest plugin (#885 cf8d597) and it still ends up like this:
![yoshi_f](https://cloud.githubusercontent.com/assets/14175085/13911638/95e4b818-ef33-11e5-9cfe-32c230e02b43.png)

If no one else is experiencing this issue then there is nothing left for me to do but to close it.

**Comment by AmbientMalice** [comment]
You shouldn't close an issue if it still occurs.

**Comment by SigmaVirus** [comment]
@AmbientMalice 

I'll personally re-open this issue if one other single human being on this planet posts a screenshot with the same artifacts I have.

No one have been able to re-produce this so far and they are showing me screenshots of perfect water.

So until someone else experience this, I'll leave it closed assuming somethings wrong on my end.

Feels like I yelled wolf or something but there was no wolf there.

**Comment by AmbientMalice** [comment]
@SigmaVirus I can't load the save state. Is it possible to give me a normal game save that will get me to that level?

**Comment by SigmaVirus** [comment]
@AmbientMalice 
Sure I'll post one in a moment.

**Comment by SigmaVirus** [comment]
@AmbientMalice 
Here you go a complete save file:

[YOSHI STORY.zip](https://github.com/gonetz/GLideN64/files/181787/YOSHI.STORY.zip)

**Comment by AmbientMalice** [comment]
I can't reproduce the issue. So it must be something like a driver issue.

![gliden64_yoshi_story_001](https://cloud.githubusercontent.com/assets/10704701/13917480/bfeeed58-efac-11e5-8c5d-fd95121877c2.jpg)

**Comment by SigmaVirus** [comment]
I'm gonna try this driver:
Crimson Edition 16.3.1 Hotfix which is the latest driver you can get for this card so I'll report back whether it worked or not.

**Comment by SigmaVirus** [comment]
I give up!

Still the same problem with the latest drivers and @AmbientMalice 
N64 depth compare, hahaha yeah I wish my screen looked like that with it enabled.

N64 depth compare fix my water issue, but Yoshi and everything else object wise turns invisible.

It's safe to say that this game, my mix of hardware, software and drivers is unique because no one else could ever reproduce this.

So case closed and Fin!
