### ISSUE TITLE
Goldeneye Frigate water broken + GLideN64.custom does not seem to work

### ISSUE THREAD

**Issue by SigmaVirus** [gonetz/GLideN64#912]
This have been around for as long as I can remember even in Glide64 Final and I don't know if this have been reported or not but the water in Goldeneye Frigate looks like this:
http://s18.postimg.org/kb550f2s9/Goldeneye.png

It looks normal most of the time once you're up on the boat and I'm using a build of GLideN64 dated 2016-03-13 but this issue as I said earlier goes way back.

Here's a save state:
http://s000.tinyupload.com/?file_id=44317366785013724035

My other issue is related to the GLideN64.custom config file and I can't seem to get it to work no matter what I change in it.
Yes it's enabled in the settings BTW.

I want to know if this is an legitimate issue or not or if I'm doing something wrong because I want to make some changes and they don't seem to activate.

**Comment by AmbientMalice** [comment]
The water is a low level triangle issue. GoldenEye/Killer Instinct don't send the skies/water as display lists, and instead send them directly to the RDP, IIRC. So they have to be handled separetely, using code that translates them into visible polygons. This code is buggy, however.

**Comment by SigmaVirus** [comment]
Thanks for the explanation, so it's quite a difficult issue to solve then?

What about GLideN64.custom, does it work for you @AmbientMalice

**Comment by baptiste0602** [comment]
@SigmaVirus : maybe your problem with Gliden64.custom is the line "version=".
It needs to be equal to the same line in GlideN64.ini.

In Github sources, the number is 5, but it seems outdated. The actual version is 6 or 7 (i don't remember exactly).

**Comment by SigmaVirus** [comment]
@baptiste0602 

I feel bad, turned out I had version 5 not 7 and now everything works great.
How I could missed that is beyond me?

**Comment by gonetz** [comment]
Issue with LLE triangle will not be fixed anytime soon. Current ini version is 7.

**Comment by tony971** [comment]
It probably has something to do with the custom ini still being listed as version 5 in the repo. That should probably be updated.
