### ISSUE TITLE
bottom of the 9th: missing gfx (title screen ..): regression

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#913]
recent changes must have broken something, i cannot see the image (jpeg) displayed (fb on, sync)

**Comment by AmbientMalice** [comment]
Seems to be working for me, but with similar texture issues to World Driver Championship.

**Comment by gonetz** [comment]
Image not displayed? Yes. Recent changes? No.
I can't find a version, where it is displayed.

**Comment by olivieryuyu** [comment]
well it works for a very long time now, i tested it many times this game in the past.

Here the version of emucr from the the 1st of march.

![sdfdfsd](https://cloud.githubusercontent.com/assets/8987490/13899889/306ff3b6-edf9-11e5-8424-44c3dbb9cd48.jpg)

**Comment by gonetz** [comment]
I see now. I run it with wrong options.
The regression caused by commit 54e0c53. Unexpected result for commit, which removes a hack.

**Comment by gonetz** [comment]
Fixed

**Comment by olivieryuyu** [comment]
fixed
