### ISSUE TITLE
Broken copy color buffer from RDRAM with native resolution

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#914]
Copy color buffer from RDRAM is broken when native resolution is enabled. Here is a screenshot with 3x native resolution:
![screenshot_2016-03-19-18-13-55](https://cloud.githubusercontent.com/assets/11581687/13901576/f6d4fa1a-edfe-11e5-9496-b8491880c85c.png)

**Comment by fzurita** [comment]
I believe the smaller version of the image is supposed to be the correct one. Also, is everything being rendered twice when copy color buffer from RDRAM is enabled?

**Comment by retrobenny** [comment]
Just by looking at it,small is rasterized looking while big is what I think the factor scaled one is supposed to look like,I did this with Conker at random when trying some stuff.
Normally,it currently makes it look really rasterized and blurry when on 1x scale factor,but that might be what it is supposed to do on 1x mode,just a shame all higher scales break.

**Comment by gonetz** [comment]
Is it GLES2 or GLES3x ?

**Comment by fzurita** [comment]
3.0 version. This happens in both my Adreno based devices and NVidia shield TV.

**Comment by fzurita** [comment]
Fixed.
