### ISSUE TITLE
Missing "custom" option in the Windowed resolution list

### ISSUE THREAD

**Issue by oddMLan** [gonetz/GLideN64#917]
https://github.com/gonetz/GLideN64/issues/484#issuecomment-189640998

>I added custom windowed screen resolution option to GUI.
Select 'custom' from Windowed resolution combobox and set desired window size.
>Binary:
https://drive.google.com/file/d/0B0YqMPjGo3B2RDgwUjJGZTVnRHM/view?usp=sharing

There's no such option in the current build cf8d597458559e6535783f80526e78370148d6e1
But the build linked in the quote does include the option.

**Comment by gonetz** [comment]
Yep, strange.

**Comment by gonetz** [comment]
Fixed. Updated binary:
https://github.com/gonetz/GLideN64/issues/885#issuecomment-198932729

**Comment by oddMLan** [comment]
Fixxxxxxxed
