### ISSUE TITLE
Feature request: Saving screenshots as PNG?

### ISSUE THREAD

**Issue by oddMLan** [gonetz/GLideN64#918]
Libpng is already included in GlideNHQ, would it be possible to use it to directly save screenshots in PNG format?

**Comment by gonetz** [comment]
No. Screenshot  files have been creating with QT functions, and QT built without png support.

**Comment by oddMLan** [comment]
Aw :(
Any reason as on why QT is being built without PNG support?

**Comment by gonetz** [comment]
Because png in QT conflicts with png in GLideNHQ, and hd textures just won't load.
