### ISSUE TITLE
Textures pack issues, Textures are weirdly displaced/stretched.

### ISSUE THREAD

**Issue by Brehat** [gonetz/GLideN64#920]
Hello,

First of all, I really like this plugg in, and thank you for making it a reality.
I wanted to play some Majora's Mask using Djipi's 2011 texture pack.
I wanted to use GlideN64 instead of the Glide64 which is intended to be used with the pack.
As Djipi's Texture pack comes with .dat files, I extracted the .png of textures using [this guide](http://www.emutalk.net/threads/55257-GUIDE-Extract-dat-Glide64-Texture-Packs).

However, when I the game loads the textures their is this wierd displacement of textures and Im not sure what is causing it. [See this link](https://www.dropbox.com/sh/seqecc223r3aume/AABRDU3hLC84UqPZ4INpXnoza?dl=0)
[Same issue has been reported here](http://www.emutalk.net/threads/55889-Issues-with-loading-textures-on-GlideN64) with the OOT 2011 texture pack.

Is this an issue with GlideN64, or could it be the pngs?
Thanks for your help.

-------------
Windows 10 - 16Go Ram
Project 64 v2.2
I7 3770k - GTX 770

**Comment by gonetz** [comment]
I don't know the reason. Most likely conversion from .dat file is not 100% correct. Djipi's texture pack for Zelda OOT exists in original png form. This pack works well with GLideN64. You may try to load it with Glide64, then convert .dat  file back to textures form, load it with GLideN64

**Comment by Brehat** [comment]
Ok so I tried with the 2009 Cell pack of OOT, wich comes in a folder format.

Using GLideN64 directly to create a .htc file from the folder format of Cell pack 2009 => Works perfectly
Using Glide64 to create a .dat form thze folder format of Cell pack 2009, then extract pngs using the tutorial, and then with those pngs recreating a .htc file => Same bug as OP.

So as you said, most likely the extraction is not 100% correct :/
So no issue on GLideN64 side. False alarm ;)
Any idea on how to better extract from those .dat though?

**Comment by gonetz** [comment]
No, no idea. The transformation from png texture into internal format is not bijection (one-to-one correspondence). Internal format depends not only on original N64 texture format, but also on actual context of hd texture. Thus, inverse transformation from internal format back to png may produce different texture.

It is better to ask Djipi to release the pack in .htc format, if he don't want to release it as png textures.

**Comment by gonetz** [comment]
I close the ticket, since "no issue on GLideN64 side. "

**Comment by Brehat** [comment]
Yes ofc. Thanks for your time on the matter.
