### ISSUE TITLE
Enabling HW Lightning with Shader Storage enabled breaks lightning

### ISSUE THREAD

**Issue by oddMLan** [gonetz/GLideN64#922]
![gliden64_donkey_kong_64_001](https://cloud.githubusercontent.com/assets/7278372/13907603/1c37a6ee-eeaf-11e5-8c8f-eb48f0e6c888.png)

Already discussed here: https://github.com/gonetz/GLideN64/issues/693#issuecomment-145318214

Resetting Shader Cache on settings change sounds like the correct way to approach this.
Maybe doing so will also fix #916

**Comment by gonetz** [comment]
> Resetting Shader Cache on settings change sounds like the correct way to approach this.

This is already implemented and works for me. If I change HW Lightning setting, new shader cache created. Please give the scenario, how to reproduce that bug.

**Comment by theboy181** [comment]
Switch from lle to hle in game

**Comment by gonetz** [comment]
Cool! I forgot about that "trick". Need to process that "option" as well.

**Comment by theboy181** [comment]
Thumbs. :)

**Comment by oddMLan** [comment]
http://webm.host/2a186/vid.webm

**Comment by gonetz** [comment]
Great way to explain scenario of an issue, thanks!
I see, what causes the problem: shader storage saved **after** config changed, and storage header got wrong settings stamp, which does not correspond to actual shaders. Technical issue.

**Comment by oddMLan** [comment]
Yeah, WebMs come in really handy, they're small in size and can be opened directly by most internet browsers :)

Is this technical issue complex to address? Or coming up with a 'creative' solution? :laughing:

**Comment by gonetz** [comment]
Nothing serious, will be fixed soon. I'm not at home atm and can't upload solution right now.

**Comment by gonetz** [comment]
Fixed

**Comment by oddMLan** [comment]
Fixed indeed! :+1:
