### ISSUE TITLE
Rogue Squadron Sky is broken [regression]

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#924]
![gliden64_rogue_squadron_000](https://cloud.githubusercontent.com/assets/7283660/13969962/1f655ed2-f086-11e5-97a7-cab2ab6a645c.jpg)

**Comment by AmbientMalice** [comment]
Do you want me to track down the commit where it was introduced?

**Comment by purplemarshmallow** [comment]
I can't do it today I wanted to find more info tomorrow
If you can find the commit that would be nice

**Comment by AmbientMalice** [comment]
I've narrowed it to one of the March 19 commits. I'll test each one.

**Comment by AmbientMalice** [comment]
Found it. It's one of these. The two commits work in tandem.

https://github.com/gonetz/GLideN64/commit/7549e041571480c656301b689d70fa89c81b471b

https://github.com/gonetz/GLideN64/commit/80c954e5ccb95bda9caae86d013bd075e2c974bd

**Comment by gonetz** [comment]
Thanks for info about bad commit.
Fixed.

**Comment by purplemarshmallow** [comment]
fixed
