### ISSUE TITLE
Donald Duck - Goin' Quakers : coronas doesn't work

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#925]
![no](https://cloud.githubusercontent.com/assets/8987490/13982502/c39556e2-f0ea-11e5-9022-42adc34832d6.jpg)

**Comment by AmbientMalice** [comment]
Did they ever work? Because I'm reminded of https://github.com/gonetz/GLideN64/issues/740 My guess is it's caused by the incorrect depth buffer emulation. Glide64 seems to need software depth buffer for corona visibility for this game.

**Comment by olivieryuyu** [comment]
Yes it worked

**Comment by AmbientMalice** [comment]
I've gone back to GLideN64 1.1, and they're still broken. (Rendering regardless). I'll try some older builds when I get time, and also builds around the time Vigilante 8 was having corona problems.

**Comment by olivieryuyu** [comment]
coronas works in star wars racer, why is there a difference? odd!

**Comment by gonetz** [comment]
How to reproduce it? Is it right at the start?

**Comment by AmbientMalice** [comment]
>How to reproduce it? Is it right at the start?

Yes. Start game, wait for cinematic to finish, step onto pad, and then press B. I'll upload a save state.

**Comment by AmbientMalice** [comment]
Here's a save state of the spot. 
https://mega.nz/#!hp5CURpR!xyZIaUQcMnpP-VNZlQO8tweuhsjPnHpPO1QEr6yBnX8

**Comment by olivieryuyu** [comment]
fixed
