### ISSUE TITLE
Emulate depth compare corona issues in Ocarina of Time.

### ISSUE THREAD

**Issue by OldGnashburg** [gonetz/GLideN64#928]
When Emulate depth compare is enabled, in Ocarina of Time, Majora's Mask, and possibly other games, torch corona's are visible through walls with Emulate Depth Compare is on, when it's they are normal and don't render through the walls.

Picture with Depth Compare:
![gliden64_the_legend_of_zelda_079](https://cloud.githubusercontent.com/assets/11412147/14001501/c9cf4830-f10b-11e5-949e-b11ded6f234a.jpg)

Picture without Depth Compare
![gliden64_the_legend_of_zelda_081](https://cloud.githubusercontent.com/assets/11412147/14001540/0feb3928-f10c-11e5-949f-42a1b180221a.jpg)

**Comment by gonetz** [comment]
Depth buffer copy currently not implemented for "Emulate depth compare" mode.

**Comment by mudlord** [comment]
Would that take writing and reading from depth textures each frame and then doing the N64 depth compare modes?

**Comment by gonetz** [comment]
Only reading. Read depth values from image texture is not implemented.

**Comment by gonetz** [comment]
You may use software depth render now, to get working coronas in "Emulate N64 depth compare" mode.

**Comment by olivieryuyu** [comment]
can it be closed?

**Comment by gonetz** [comment]
I think it can.
