### ISSUE TITLE
(Regression) Quake 64 mupen64plus broken?

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#932]
I'm not sure when this started, but Quake 64 is now freezing with the screen flashing rapidly when 3D graphics are drawn. Occurs in both LLE and HLE.

**Comment by gonetz** [comment]
Is FBInfo enabled?

**Comment by AmbientMalice** [comment]
Ah, yes it was. Turning it off fixed it. I'll close this.

**Comment by gonetz** [comment]
The same problem is with Pilotwings. FBInfo is seriously broken in mupen64plus :(
