### ISSUE TITLE
lego racers: map doesn't appear anymore (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#935]
![dsfgdsf](https://cloud.githubusercontent.com/assets/8987490/14010861/820db368-f199-11e5-8d14-e415271795e7.jpg)

**Comment by AmbientMalice** [comment]
CPU write stuff is broken now. https://github.com/gonetz/GLideN64/issues/873

**Comment by olivieryuyu** [comment]
damn!

**Comment by olivieryuyu** [comment]
fixed with hack
