### ISSUE TITLE
PPL: incorrect background in game in native res (??)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#937]
![oppss](https://cloud.githubusercontent.com/assets/8987490/14011883/4b2e49da-f1a2-11e5-8c8c-557d950800e6.jpg)

**Comment by AmbientMalice** [comment]
Isn't PPL broken in every resolution? Other plugins use a hack.

**Comment by olivieryuyu** [comment]
it is correct with normal resolution, not sure about a hack.

**Comment by olivieryuyu** [comment]
fixed
