### ISSUE TITLE
Clay Fighter Sculptor's Cut: missing gfx with native res

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#938]
in menu

with native res

![oposdq](https://cloud.githubusercontent.com/assets/8987490/14013482/07243942-f1ad-11e5-82eb-d03906d4abc1.jpg)

with normal res:

![qsdsqd](https://cloud.githubusercontent.com/assets/8987490/14013489/0e2f0b72-f1ad-11e5-8f87-bbb35f1b404a.jpg)

**Comment by AmbientMalice** [comment]
Fixed.

**Comment by olivieryuyu** [comment]
fixed
