### ISSUE TITLE
tarzan: gfx are completely wrong (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#939]
![sdfsdf](https://cloud.githubusercontent.com/assets/8987490/14018841/1282f904-f1d0-11e5-8ba7-6b3128c2c93d.jpg)

**Comment by gonetz** [comment]
N64 game developers are very guileful.

**Comment by oddMLan** [comment]
Reminds me of https://www.youtube.com/watch?v=ho5rO4E1DZ8

**Comment by olivieryuyu** [comment]
fixed
