### ISSUE TITLE
Bettle Adv Racing: texts are now incorrect (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#940]
![dsfdf](https://cloud.githubusercontent.com/assets/8987490/14018856/292771b2-f1d0-11e5-803f-4ea7519d532f.jpg)

**Comment by olivieryuyu** [comment]
many places have wrong texts

**Comment by gonetz** [comment]
!!!

**Comment by matthewharvey** [comment]
Bisected back to 
f6be5fd39fdcc9fd992087303138f9b2cff7dfe0

**Comment by AmbientMalice** [comment]
Fixed.

**Comment by matthewharvey** [comment]
Yep. Fixed here too.

**Comment by olivieryuyu** [comment]
fixed
