### ISSUE TITLE
Bio F.R.E.A.K.S. (E): loading screen before battle goes black (correct with U version)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#941]
![sdfsdf](https://cloud.githubusercontent.com/assets/8987490/14018992/db83ad26-f1d0-11e5-814e-55d1b1424750.jpg)

**Comment by gonetz** [comment]
Seems to be fixed.

**Comment by olivieryuyu** [comment]
seems emu related. fixed
