### ISSUE TITLE
South Park - Chef's Luv Shack: incorrect gfx (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#942]
![sdfdsfffff](https://cloud.githubusercontent.com/assets/8987490/14019225/fc65ae26-f1d1-11e5-8e7a-2c0d887ec221.jpg)

**Comment by matthewharvey** [comment]
Bisected back to
8488ebccd2a356da60a59c000cfd18ab0ef8a208

**Comment by olivieryuyu** [comment]
title shows now errors

![nope](https://cloud.githubusercontent.com/assets/8987490/14112703/180821a2-f5d0-11e5-89bb-9a1f357e1b6b.jpg)

**Comment by gonetz** [comment]
:(
My attempt to bypass OGL limitation failed.
It seems a hack is the only solution.

**Comment by AmbientMalice** [comment]
Fixed.

**Comment by matthewharvey** [comment]
Fixed for me too. Sorry you had to add a hack :(

**Comment by olivieryuyu** [comment]
fixed
