### ISSUE TITLE
Aerofighter's Assault: text issue (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#943]
![dsfdsf](https://cloud.githubusercontent.com/assets/8987490/14039913/09d4200c-f262-11e5-850b-00876b0b4a47.jpg)

**Comment by gonetz** [comment]
All texture load regressions must be fixed by this commit:
https://github.com/gonetz/GLideN64/commit/06c99ad30fa6039f052ad5ea66fe094eca959255

**Comment by AmbientMalice** [comment]
Fixed.

**Comment by olivieryuyu** [comment]
fixed
