### ISSUE TITLE
Midway's Greatest Arcade: white screen (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#948]
damn!

![dsf](https://cloud.githubusercontent.com/assets/8987490/14079723/0baa5e46-f500-11e5-8b01-c40351ffdd40.jpg)

**Comment by gonetz** [comment]
Regression caused by 8d3e6ef2f9d8
The problem is in that game - it does not reset tlut flag to zero in HLE mode. As the result, RGBA texture loaded as CI one.

**Comment by olivieryuyu** [comment]
fixed
