### ISSUE TITLE
Excite bike64: missing:white texture (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#949]
the jauge has no colors anymore!

![sdfdsf](https://cloud.githubusercontent.com/assets/8987490/14111645/c2649248-f5cb-11e5-8c31-ac7dad5d24e5.jpg)

should be

![dsfdsf](https://cloud.githubusercontent.com/assets/8987490/14111646/c5c2360c-f5cb-11e5-804d-463fa8dfd46e.jpg)

**Comment by gonetz** [comment]
Fixed

**Comment by olivieryuyu** [comment]
fixed
