### ISSUE TITLE
WCW Backstage Assault: completely wrong 3d in game !!!

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#95]
![sdfff](https://cloud.githubusercontent.com/assets/8987490/4909323/58204cce-6472-11e4-8b60-25017a1d9675.jpg)

**Comment by olivieryuyu** [comment]
with all the changes in the plugin, may be fixing it would not kill performance anymore?
can we try?

**Comment by gonetz** [comment]
Fixed

**Comment by olivieryuyu** [comment]
no gfx for me

**Comment by gonetz** [comment]
Yes, there was another bug.

**Comment by gonetz** [comment]
Fixed
