### ISSUE TITLE
Programmable blending.

### ISSUE THREAD

**Issue by ADormant** [gonetz/GLideN64#951]
This is needed for correct emulation of N64 blending modes.

**Comment by ADormant** [comment]
@gonetz 
https://www.opengl.org/registry/specs/ARB/texture_barrier.txt
https://www.opengl.org/registry/specs/NV/texture_barrier.txt
https://www.khronos.org/registry/gles/extensions/EXT/EXT_shader_framebuffer_fetch.txt
https://www.khronos.org/registry/gles/extensions/ARM/ARM_shader_framebuffer_fetch.txt
https://www.khronos.org/registry/gles/extensions/ARM/ARM_shader_framebuffer_fetch_depth_stencil.txt
https://developer.nvidia.com/sites/default/files/akamai/opengl/specs/GL_NV_fragment_shader_interlock.txt
https://www.opengl.org/registry/specs/INTEL/fragment_shader_ordering.txt
https://www.opengl.org/registry/specs/ARB/shader_atomic_counters.txt
https://www.khronos.org/registry/gles/extensions/OES/OES_shader_image_atomic.txt
http://blog.icare3d.org/2014/09/maxwell-gm204-opengl-extensions.html

**Comment by olivieryuyu** [comment]
I was reading this news on PS2 emulation and I was wondering if it would be possible to do for the N64, even if it may be more complex to do.

http://pcsx2.net/developer-blog/268-explanation-impossible-blend.html
http://pcsx2.net/269-major-gsdx-progress-monthly-reports.html

**Comment by purplemarshmallow** [comment]
z64gl has programmable blending implemented maybe this can be used as reference

**Comment by ADormant** [comment]
@olivieryuyu @gonetz @purplemarshmallow 
Mind you even PCSX2  doesn't fully emulate  PS2' alpha blending because texture barrier is not enough for PS2 blending and you need this extension https://developer.nvidia.com/sites/default/files/akamai/opengl/specs/GL_NV_fragment_shader_interlock.txt
N64 blending is less advanced so texture barrier may be enough but maybe not.
I doubt z64gl has programmable blending because programmable blending is impossible with OpenGL2.

**Comment by purplemarshmallow** [comment]
z64gl's blender uses shaders and it does not use glBlendFunc
You need to compile with RGL_EXACT_BLEND

**Comment by ADormant** [comment]
Even if it uses shaders without right extensions that isn't programmable blending and even gl nv texture barrier needs at least OGL3 however if it works in z64gl then it may mean that N64 blending is simple enough that it only needs shaders though I doubt z64gl blending is 100% accurate.
@purplemarshmallow

**Comment by purplemarshmallow** [comment]
I don't think it's 100% accurate either I never said that. But z64gl gives good results in games with special blend modes like Vigilante 8

**Comment by gonetz** [comment]
cite from http://www.geeks3d.com/20120920/programmable-blending-on-mobile-and-desktop-gpus-opengl/

"glTextureBarrierNV was an extension till GL4.2, and so you cannot/couldn’t expect it to exist.
Neither works it afaik when polygons overlap in a single drawcall."

N64 polygons easily overlap in a single drawcall. I met this problem when worked on "N64 depth compare" shader. I had to draw polygons one by one to avoid it. PCSX devs also met this problem and came to the same solution: "There is a catch however. ... At this point we just need to split the draw calls into N draw calls without primitive overlap. It's not free performance wise to do this, but it remains reasonable in some cases."

**Comment by ADormant** [comment]
@gonetz 

> "glTextureBarrierNV was an extension till GL4.2, and so you cannot/couldn’t expect it to exist.
> Neither works it afaik when polygons overlap in a single drawcall."

Well GL NV Texture Barrier is pretty old but it still well supported however newst version of this extension is https://www.opengl.org/registry/specs/ARB/texture_barrier.txt
Does this extension https://www.opengl.org/registry/specs/ARB/fragment_shader_interlock.txt help with overlapping polygons in a single drawcall?

**Comment by oddMLan** [comment]
>N64 polygons easily overlap in a single drawcall. I met this problem when worked on "N64 depth compare" shader. I had to draw polygons one by one to avoid it. PCSX devs also met this problem and came to the same solution: "There is a catch however. ... At this point we just need to split the draw calls into N draw calls without primitive overlap. It's not free performance wise to do this, but it remains reasonable in some cases."

The PCSX2 team implemented an optimization of this algorithm not too long ago.
http://pcsx2.net/274-jan-feb-2016-progress-report.html

as for the actual code
https://github.com/PCSX2/pcsx2/commit/f3b6829c74c8d3530c4d6f5ed03e1094e489cb5e
https://github.com/PCSX2/pcsx2/compare/f3b6829c74...37deeb0d52
https://github.com/PCSX2/pcsx2/blob/master/plugins/GSdx/GSRendererOGL.cpp#L475

However, they mention it only helps sprite primitives.
I don't know if this might help too
https://github.com/PCSX2/pcsx2/commit/1853d0d16d975b83d397bfb82dbc0596249b85e2

**Comment by gonetz** [comment]
>Does this extension https://www.opengl.org/registry/specs/ARB/fragment_shader_interlock.txt help with overlapping polygons in a single drawcall?

Need to try it with depth compare shader.

> However, they mention it only helps sprite primitives.

Too bad

**Comment by gonetz** [comment]
Blending emulation will be done in #970
