### ISSUE TITLE
FIFA - Road to World Cup 98: black line in menu

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#952]
a black appears in menu. It goes accross the whole menu screens.

![dsfsf](https://cloud.githubusercontent.com/assets/8987490/14231808/a2bb09f8-f991-11e5-93ad-adad78cd5ab7.jpg)

**Comment by gonetz** [comment]
Fixed

**Comment by olivieryuyu** [comment]
Fixed
