### ISSUE TITLE
Mario Kart 64  showing black image of in-game camera [Mupen64Plus]

### ISSUE THREAD

**Issue by paradadf** [gonetz/GLideN64#953]
![mariokartblackscreen](https://cloud.githubusercontent.com/assets/15956550/14235032/128c639c-f9f3-11e5-953c-c0bc2c9ed9f3.png)

**Comment by paradadf** [comment]
[Save state to download](http://s000.tinyupload.com/?file_id=00800687876924679378)

**Comment by gonetz** [comment]
Is "EnableCopyColorToRDRAM" option enabled?

**Comment by paradadf** [comment]
"EnableCopyColorToRDRAM" is set to "copy in async mod"

**Comment by gonetz** [comment]
Should work then. Ok, I'll check it.

**Comment by gonetz** [comment]
Checked.
It works for me. 
"EnableCopyColorToRDRAM" = "copy in async mod"
"EnableFBEmulation" = 1

**Comment by AmbientMalice** [comment]
Maybe DisableFBInfo is set to False?

**Comment by gonetz** [comment]
Yep, it does not work with fb info enabled. The FB info feature is unusable in mupen64plus.
DisableFBInfo must be on. I think, it must be on by default for mupen64plus, at least for now.

**Comment by paradadf** [comment]
Turning on DisableFBInfo corrected it, thanks!

**Comment by MaximeMorel** [comment]
Is in-game camera animated ?
With these settings:
"EnableCopyColorToRDRAM" = "copy in async mod"
"EnableFBEmulation" = 1
DisableFBInfo = True

I have an image, but it's frozen. Is that because mupen64 never notifies when to update the buffer after the first copy once the race started ?

**Comment by gonetz** [comment]
It should work properly with these settings

**Comment by MaximeMorel** [comment]
Yes, I started again with a new mupen64plus.cfg and it was fine. Thanks !
