### ISSUE TITLE
ogre battle 64: wrong background jpeg (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#957]
![sans titre](https://cloud.githubusercontent.com/assets/8987490/14404406/52583b50-fe75-11e5-8076-ba2b7ac18f8e.png)

**Comment by oddMLan** [comment]
Protip: You can capture the whole window using Alt+Prnt Scr instead of manually cropping it :)

**Comment by gonetz** [comment]
Fixed

**Comment by olivieryuyu** [comment]
fixed
