### ISSUE TITLE
some games with native resolution is 1/4 of the screen!

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#958]
![sans titre](https://cloud.githubusercontent.com/assets/8987490/14410624/19a354e2-ff34-11e5-9192-f756dd5b47db.jpg)

**Comment by AmbientMalice** [comment]
Likely closely related to https://github.com/gonetz/GLideN64/issues/325 where the game grabs the far left corner of the image instead of the framebuffer underneath the swing gauge.

**Comment by olivieryuyu** [comment]
remind me vigilante 8

**Comment by olivieryuyu** [comment]
remind me vigilante 8 menu

**Comment by baptiste0602** [comment]
Happen also with StarFox

**Comment by olivieryuyu** [comment]
indeed

![sdf](https://cloud.githubusercontent.com/assets/8987490/14619271/f9d4a4de-05b6-11e6-8585-8b76b6f6efd7.jpg)

**Comment by olivieryuyu** [comment]
Waialae Country Club in game only

![wailia](https://cloud.githubusercontent.com/assets/8987490/14759516/d9beac76-0926-11e6-8afe-f9de15411363.jpg)

**Comment by olivieryuyu** [comment]
Mahjong Master the same

**Comment by gonetz** [comment]
Fixed

**Comment by olivieryuyu** [comment]
fixed
