### ISSUE TITLE
Missing Pills in Dr. Mario

### ISSUE THREAD

**Issue by jaburgeson** [gonetz/GLideN64#961]
When playing a game in Dr Mario everything renders great except for the Pills until they land.

So they only show up once in place, so you have no idea where they are falling to.

Hopefully this makes sense.  It happens no matter what mode or game you select.  As soon as you start to play the issue comes up.

It makes the game completely unplayable sadly.

**Comment by gonetz** [comment]
You probably missed necessary options.
Frame buffer emulation must be enabled, and 'Render frame buffer as texture' too.

**Comment by gonetz** [comment]
![Uploading GLideN64_DR.MARIO_64_001.jpg…]()
