### ISSUE TITLE
Core infinite loop while entering subscreen in LoZ: Ocarine of Time Master Quest (Debug)

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#962]
Sometimes, when entering the in-game subscreen in the LoZ: Ocarine of Time Master Quest (Debug), the core will lock up taking 100% of the CPU and the app has to be killed. This is using the arm dynarec. With interpreter the issue doesn't happen.

**Comment by gonetz** [comment]
How should it be fixed on plugin's side?

**Comment by fzurita** [comment]
This is very strange, I thought I made this issue in mupen64plus-core project. Whoops, sorry about that.

**Comment by fzurita** [comment]
Here is the real issue:

https://github.com/mupen64plus/mupen64plus-core/issues/156
