### ISSUE TITLE
Donkey Kong 64 PAL BlackScreen After Intro

### ISSUE THREAD

**Issue by Snipy44** [gonetz/GLideN64#963]
Hello, Donkey Kong 64 PAL (french) not worked, after the donkey rap, black screen :/
Is not playable, thank's and sorry for my bad english, im french :x

**Comment by AmbientMalice** [comment]
What emulator are you using? What build of the plugin? It seems to be working for me.

**Comment by Snipy44** [comment]
I used this : http://www.emucr.com/2016/04/project64-git-20160415.html , and this rev http://www.emucr.com/2016/04/gliden64-git-20160415.html

**Comment by AmbientMalice** [comment]
What is your GPU?

**Comment by Snipy44** [comment]
Nvidia GTX 760

**Comment by gonetz** [comment]
@Snipy44 
* please use my builds from this thread : 
https://github.com/gonetz/GLideN64/issues/885
* E version of the game has problem with copy buffer to RDRAM. If game will hang, disable that option.

**Comment by gonetz** [comment]
I can't reproduce it.

**Comment by LuismaSP89** [comment]
@gonetz

I can confirm this issue, but it doesn't happen 100% of time. Black screen after DK rap.

**Comment by LuismaSP89** [comment]
@gonetz 

Ok, after some testing i can confirm that it doesn´t happen if you skip immediately the DK rap. But if you skip after 3-4 seconds of video for example. The blackscreen appears, and freezes.
