### ISSUE TITLE
Star Fox 64 graphics glitch (see the attached image)

### ISSUE THREAD

**Issue by budtz** [gonetz/GLideN64#964]
I get flicking in Star Fox with the plugin. (The image is upside down)

what can cause this?

![img_4086](https://cloud.githubusercontent.com/assets/17853217/14574530/7ec32678-035c-11e6-8789-10fce4368321.JPG)

**Comment by gonetz** [comment]
I need more details:
plugin's build version
emulator's version

savestate also can help.

**Comment by baptiste0602** [comment]
Flickering happen when "Render frame buffer as texture" is enabled.
You can disable this parameter.

**Comment by budtz** [comment]
I have disabled ”Render frame buffer as texture". still have issues.

Plugin is latest from the tread: "No new releases posted in 8 months #885" where new builds are posted. 

emulator is also compiled recently

I have updated both regularly for a few months but it’s been the same

**Comment by gonetz** [comment]
I can't reproduce it. Tested with default settings with Project64.

**Comment by budtz** [comment]
Strange 

I dont get the error every time. also pressing esc two times to minimize and maximize makes it go away. so i guess i can do that but it is stille strange

**Comment by budtz** [comment]
I can add that there are no problems on glide64

**Comment by elcorsico** [comment]
no problems for me with wip GLideN64  ;-)
test Star Fox 64 (USA) (Rev A)

**Comment by Frank-74** [comment]
I get a border with trash in the top quarter of the screen.  It flashes on and off.  It first appears on this menu, and stays there for the rest of the game.  Continually flashing.
Using latest rev.0263eb3.  Latest Project64 from Github compiled with VS2008.  Intel HD Graphics, latest Intel drivers.
![gliden64_starfox64_000](https://cloud.githubusercontent.com/assets/11056843/16895239/1cff2b18-4b68-11e6-8e42-3bfb532c1f13.jpg)

**Comment by budtz** [comment]
Yes thats what I get on ny nvidia Gtx 760 system. Using latest versions. But it has been there 3 months maybe. Go farther back and its not there

**Comment by Frank-74** [comment]
It goes away if I go fullscreen.

**Comment by budtz** [comment]
I get it in fullscreen. But going in and out of fullscreen makes it go away

**Comment by budtz** [comment]
any update on this issue?

**Comment by gonetz** [comment]
I get this bug only when I load from savestate.

**Comment by Frank-74** [comment]
Seems to be fixed.  It's ok here now.  Can be closed I suppose.

**Comment by budtz** [comment]
I cant reproduce it any longer. I still can on older versions thou. It can be closed
