### ISSUE TITLE
banjo kazoiie: puzzle in intro doesn't work anymore (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#966]
![dsfsdf](https://cloud.githubusercontent.com/assets/8987490/14613412/a6aa2578-059c-11e6-8ee9-45a17380fc32.jpg)

Just after the intro

**Comment by AmbientMalice** [comment]
Did you make sure FBwrite is disabled.

**Comment by AmbientMalice** [comment]
It happens when loading a new screen. I see.

**Comment by fzurita** [comment]
I can confirm, it doesn't work in android any more either.

**Comment by gonetz** [comment]
Fixed

**Comment by olivieryuyu** [comment]
fixed
