### ISSUE TITLE
Racing Simulation - Monaco Grand Prix: missing gfx (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#967]
![sdfdsf](https://cloud.githubusercontent.com/assets/8987490/14664087/d917122e-06c7-11e6-8f9c-d88b53f58f5c.jpg)

**Comment by gonetz** [comment]
Is it latest master? I can't reproduce that bug.

**Comment by olivieryuyu** [comment]
weird i got this bug and not anymore.
