### ISSUE TITLE
hey you pikachu:hilarious texture bug

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#97]
![screen17](https://cloud.githubusercontent.com/assets/8987490/4959044/c0041138-66b4-11e4-8565-6c0e3777681d.jpg)

**Comment by DaEckster** [comment]
![Fog Disabled](https://cloud.githubusercontent.com/assets/2662835/7452370/8b7b6d24-f211-11e4-9b35-cdee3a8b93a6.png)

Tested with Public Release and PJ64 2.2, it had the exact same issue as before(the white texture), but I found that if I disabled Emulate Fog then I got the image right here. The facial features are bloated, but it's an improvement.

**Comment by olivieryuyu** [comment]
fog and texture are related? not sure, may be in some special way

**Comment by DaEckster** [comment]
Only thing I know is that this issue should definitely be named back to "hey you pikachu: hilarious texture bug :)"

**Comment by olivieryuyu** [comment]
the game uses a specific ucode

RSP Gfx ucode F3DAM       fifo 2.05  Yoshitaka Yasumoto 1998 Nintendo.

**Comment by oddMLan** [comment]
Still happening.
![gliden64_hey_you _pikachu_000](https://cloud.githubusercontent.com/assets/7278372/15262472/6ea59f2a-1917-11e6-8518-25ea2428085e.png)

No options seem to affect the end result. Although disabling fog is no longer an option.

**Comment by olivieryuyu** [comment]
is there a hack in Rice plugin or it is fixed in it?

**Comment by gonetz** [comment]
I have no time to check it.

**Comment by oddMLan** [comment]
@Gillou68310 could you check this one for microcode differences?

**Comment by Gillou68310** [comment]
> the game uses a specific ucode
> 
> RSP Gfx ucode F3DAM fifo 2.05 Yoshitaka Yasumoto 1998 Nintendo.

Actually the game keep switching between the F3DAM ucode and the L3DEX2 ucode (RSP Gfx ucode L3DEX fifo 2.08 Yoshitaka Yasumoto 1999 Nintendo).

The F3DAM ucode is really close to the F3DEX2 ucode but there are a few differences that needs to be investigated.

The L3DEX2 ucode is identical to the one provided in the n64sdk.

**Comment by olivieryuyu** [comment]
hmm interesting, i thought that AM was standing for Audio Motion but I can be wrong of course :)

**Comment by olivieryuyu** [comment]
I checked quickly the ucode.

Flag for light and fog are different. Way of calculation texture coordinates seems different.

Amazing to see the number of customized ucode...

**Comment by olivieryuyu** [comment]
is there a way to go a bit more further than the intro? may be with a savestate, a hack?

**Comment by tony971** [comment]
https://www.reddit.com/r/emulation/comments/5ogctn/hey_you_pikachu_finally_playable_with_offical_vru/?st=J4ILZ132&sh=2b4f779f

If you have the right hardware...

**Comment by tony971** [comment]
If not, you'll just have to wait for the HLE implementation.

http://www.emutalk.net/threads/55279-Hey-You!-Pikachu-Possible-HLE-Implementation

**Comment by Ecksters** [comment]
Holy! How did I miss seeing this! @olivieryuyu I'll get you a savestate in whatever emulator you want, going to order that adapter immediately, I have the original hardware.

**Comment by olivieryuyu** [comment]
i would need a savestate in various levels, one with fog if possible

**Comment by Ecksters** [comment]
I've ordered the adapter, should be here in a week or so, I believe the Polywag level will have exactly what you want fog-wise.

Multi-level save states are useful anyway, since the game actually sends different voice recognition instructions to the VRU depending on which level you're on.

**Comment by olivieryuyu** [comment]
pj64 savestate. Thx!

**Comment by olivieryuyu** [comment]
all right, I understand more or less what is going on. Impossible however to test a lot the game.

@gonetz 

Will send you info soon

**Comment by Ecksters** [comment]
Here are save states of the first several levels, I'll be adding to this folder as I play through the game, the level you want is the Day 9 - Lost Poliwags level, it's missing fog even in Rice Video, which actually makes it way easier than it should be.

[Hey You, Pikachu! PJ64 Savestates](https://www.mediafire.com/folder/ve1rdcrkiry2q/Hey_You%2C_Pikachu!)

I had the game crash twice on me while playing, but otherwise it does appear that the Raphnet adapter + VRU is a perfect combination.

**Comment by olivieryuyu** [comment]
many thanks we will be able to test the implementation of th ucode.

**Comment by Ecksters** [comment]
Cool, once you think it's implemented I'll play through the whole game and report any graphical issues.

**Comment by gonetz** [comment]
@Ecksters the ucode is implemented, you can play the game now. Windows build posted in #1364

**Comment by olivieryuyu** [comment]
great :)

**Comment by olivieryuyu** [comment]
@Ecksters 

would be great if you can check the game, some cases were not totally clear to us so better double checking

Thanks!

**Comment by Ecksters** [comment]
Appears to be working perfectly, tested for two hours, only noticed some slight graphical glitches with the seams of textures, and perhaps some lines around certain bits of text, but nothing majorly wrong, at this point the audio plugin is the far bigger issue.

Here's the two hours of gameplay if you're interested:
https://www.twitch.tv/videos/159911960

**Comment by gonetz** [comment]
@Ecksters Thanks!

**Comment by tony971** [comment]
It looks right, but you might want to disable per-pixel lighting in the gliden64.custom.ini for this game now. Having it checked gives pikachu some weird effects.
