### ISSUE TITLE
N64 blending emulation

### ISSUE THREAD

**Issue by gonetz** [gonetz/GLideN64#970]
Goal: implement emulation of N64 blending modes with minimal hacks and heuristics.

Explanation:

Blending is a part of pixel pipeline. Color of incoming pixel interpolated with color of pixel in buffer to achieve various effects, mainly transparency.
Blending process on N64 also blends incoming and stored colors, but not only that. N64 blending also can mix incoming color with two constant colors: fog color and blend color. This is used mainly to apply fog, but creative programmers used that option as additional stage of color combiner. Standard OpenGL blending is good enough to blend pixel and memory colors, but when it is first necessary to mix input color with constant colors, it fails.

OpenGL blending is part of fixed functionality. Shaders cannot use blending. There are GL extensions, which actually allowed blending in shaders, but only when several conditions met. Shader-based blending is hardly possible with N64 emulation. Thus, currently GLideN64 uses legacy glN64 blending method. The correspondence between N64 blending modes and OpenGL ones is hardcoded. If blending mode mixes input color with constant colors, it is emulated in shader with special code.

New blending uses general method of blending emulation. No more hardcoded blending modes. All special code in shaders replaced by general blending functions. Note that it is not true “shader blending”. New method uses standard one-pass OpenGL blending with no extensions. It will work on all supported hardware without performance sacrifices. From the other side, shader can’t blend input color with memory color. Usually it is not necessary because standard blending will do the job. However, some crazy blend modes will _probably_ left unemulated.

New blending resides in experimental_blend feature branch. Binary to test:
https://drive.google.com/file/d/0B0YqMPjGo3B2azZuTG9jX3pEaEU/view?usp=sharing
Visually there should be no difference with master in 99.9% of cases. Please report about regressions in that ticket, not open a new one.

**Comment by AmbientMalice** [comment]
Looks to me like you've already squashed some bugs.

F-Zero X seems to have black borders and specular now. I could be wrong, though.
![gliden64_f-zero_x_001](https://cloud.githubusercontent.com/assets/10704701/14768291/bc566ff0-0a81-11e6-8965-a4e905a3c8d3.jpg)

World Driver Championship reflections seem to be fixed.
![gliden64_world_driver_champ_005](https://cloud.githubusercontent.com/assets/10704701/14768301/e1602ad4-0a81-11e6-8f26-1ec8423e4d06.jpg)

**Comment by gonetz** [comment]
>F-Zero X seems to have black borders and specular now. I could be wrong, though.

Yep, but ingame cars are broken :(

**Comment by olivieryuyu** [comment]
Was not the lights deaxtivated for this game? I thought it was a mixrocode issue, not blending

**Comment by gonetz** [comment]
> Was not the lights deaxtivated for this game?

F-Zero? No, it uses lighting. As I remember, there was a problem with specular reflection.
BTW, blending works ok in LLE mode. Looks like HLE issue.

**Comment by olivieryuyu** [comment]
If I remember correctly, you have deactivated a long time ago something for the reflections for this game.

if (strncmp(&uc_str[14], "F3DF", 4) == 0)
						current.textureGen = false;

May be not related, dunno

**Comment by AmbientMalice** [comment]
https://github.com/gonetz/GLideN64/issues/481 seems to be fixed. Fade to white looks smooth.

**Comment by ADormant** [comment]
@gonetz 
This is how it's done in PPSSPP and Yabause.
https://github.com/Yabause/yabause/commit/46bd80bd8f076f4e60cf86d18e8a5f259e962f07
https://github.com/Yabause/yabause/pull/22/files
https://github.com/Yabause/yabause/commit/b307da5386fd73950f1acb5c5824fb8c89e49e00
https://github.com/Yabause/yabause/commit/c6ffab78439de82e80cf1298b0747440c8f2a364
https://github.com/Yabause/yabause/commit/f04d3c5fcdf038e70848e0bac6140911d977fab4

https://github.com/devmiyax/yabause/commit/2e9375ff05da2f473b701d43dfb057410119c0d9
https://github.com/devmiyax/yabause/commit/1652ed93df80ac1650479f1f6c3b4ec5c43f142b
https://github.com/devmiyax/yabause/commit/f2125165ba32ef3a3d8576b9f6e62396c7fcaf78
https://github.com/devmiyax/yabause/commit/eef956ef19b9de974c48993dac7b6c12b1aa35ba
https://github.com/devmiyax/yabause/commit/215e23aea0e07c28adc0e9600a74ad44dfd4a292
https://github.com/devmiyax/yabause/commit/90643058dff07746f61ff122f5a594607997b762
https://github.com/devmiyax/yabause/commit/e66676928681cdd9355867554509281017058b9c
https://github.com/devmiyax/yabause/commit/812bf2acc53575384979bc9b6c20473c81fdc092


https://github.com/hrydgard/ppsspp/pull/6313/files
https://github.com/hrydgard/ppsspp/pull/6070/files
https://github.com/hrydgard/ppsspp/pull/5917/files
https://github.com/hrydgard/ppsspp/pull/5859/files
https://github.com/hrydgard/ppsspp/pull/6063/files
https://github.com/hrydgard/ppsspp/pull/6679/files
https://github.com/hrydgard/ppsspp/pull/6350/files
https://github.com/hrydgard/ppsspp/pull/8218/files
https://github.com/hrydgard/ppsspp/pull/8213/files
https://github.com/hrydgard/ppsspp/pull/8163/files
https://github.com/hrydgard/ppsspp/pull/8210/files
https://github.com/hrydgard/ppsspp/pull/7964/files
https://github.com/hrydgard/ppsspp/pull/7567/files
https://github.com/hrydgard/ppsspp/pull/7520/files
https://github.com/hrydgard/ppsspp/pull/1614/files
https://github.com/hrydgard/ppsspp/pull/5767/files

**Comment by gonetz** [comment]
@ADormant why do you think it will help me? Have you checked these links yourself?

**Comment by ADormant** [comment]
Are texture barrier and shader interlock working with N64 blending?

**Comment by gonetz** [comment]
I don't use them.

**Comment by ADormant** [comment]
Why it should be most accurate this way?

**Comment by gonetz** [comment]
Why not?

**Comment by ADormant** [comment]
Because it's probably less accurate with fixed function opengl.

**Comment by gonetz** [comment]
I explained **possible ** issue with this method.
Nobody proved yet that this possible issue actually resulted as graphics glitch.
Nobody proved yet that GL extensions are applicable for N64 emulation.
If you really want to help, learn the links you provided and suggest a way how to improve my code.
Or at least find a case, where new blending emulation fails.

**Comment by gonetz** [comment]
> if (strncmp(&uc_str[14], "F3DF", 4) == 0) current.textureGen = false;

This disables specular reflection, not lighting. F3DF is F-Zero ucode, true.

**Comment by AmbientMalice** [comment]
Vigilante 8 no longer misbehaves when looking directly at lens flares.

@ADormant I think Gonetz may be right. Using shaders for blending is probably putting the cart before the horse if there aren't any known issues with fixed function. It ends up being technology for the sake of technology.

**Comment by olivieryuyu** [comment]
having tested the new blending, i cannot see new bugs, only improvments, except this F-Zero but this is peculiar game with something specific in HLE.

**Comment by gonetz** [comment]
@olivieryuyu good to know, thanks!

**Comment by gonetz** [comment]
More improvements:
Donald Duck: background has correct color hue now.
ISS64: shadows look correct now - solid with right transparency level. The game needs N64 depth compare enabled.

**Comment by AmbientMalice** [comment]
I've found what seems to be a regression. If you load a game, and turn Aux FB to RAM on and then off, it breaks transparencies. It's very obvious in Extreme-G, with the flares from the vehicles.

![gliden64_turok_3 _shadow_of_o_000](https://cloud.githubusercontent.com/assets/10704701/14780963/e9d533d4-0b22-11e6-8d1f-901239b538aa.jpg)

**Comment by olivieryuyu** [comment]
#688 seems to be fixed?

I cannot see that. 

You may compare with Angrylion plugin.

**Comment by AmbientMalice** [comment]
GLideN64
![gliden64_hexen_003](https://cloud.githubusercontent.com/assets/10704701/14781314/201eaf22-0b25-11e6-9faa-6753a69dc3be.jpg)
Angrylion's
![nhxe0000 2](https://cloud.githubusercontent.com/assets/10704701/14781328/2e453fda-0b25-11e6-9b93-d7f65b4ed597.jpg)

**Comment by AmbientMalice** [comment]
This behavior seems new.

HLE:
![gliden64_turok_3 _shadow_of_o_002](https://cloud.githubusercontent.com/assets/10704701/14781354/5adf50a8-0b25-11e6-936d-8bf31a13dd07.jpg)
LLE:
![gliden64_turok_3 _shadow_of_o_003](https://cloud.githubusercontent.com/assets/10704701/14781368/734ca78a-0b25-11e6-9e46-6a82199e0db7.jpg)

In addition, most of the geometry is missing with the thermal goggles in LLE mode now.

**Comment by gonetz** [comment]
@AmbientMalice savestate please.

**Comment by AmbientMalice** [comment]
Extreme-G:
http://s000.tinyupload.com/index.php?file_id=27632938566080491951
Random elements will become buggy when turning Aux FB on and off. Dust trails from zig-zagging can become triangular. Vehicle lights can break. 2D weapon elements can break. Annoyingly, the corruption is very random. I'm not 100% sure it's caused by this branch, but today is the first time I noticed it.

Turok 3:
http://s000.tinyupload.com/?file_id=02433454240150271099
Light texture disappears in LLE mode.

**Comment by gonetz** [comment]
Can't load the saves. Could you make PJ64 2.2 compatible saves?

**Comment by gonetz** [comment]
Updated binary:
https://drive.google.com/file/d/0B0YqMPjGo3B2eWkyZEJCampjR2c/view?usp=sharing

**Comment by oddMLan** [comment]
Keep in mind that Project64 2.2 is bugged now. You ought to load the game, press F5 to make an instant save, press F7 to load it and THEN load your external savestate.

I just tested the Extreme-G savestate AmbientMalice uploaded, it loads succesfully following this workaround. https://github.com/project64/project64/issues/1032

**Comment by oddMLan** [comment]
Found a regression in Donkey Kong 64 (U)
https://u.pomf.is/zelokv.webm

notice how the watermelon slice when rising it has a green background

Doesn't happen in 5f7cdb4

**Comment by LegendOfDragoon** [comment]
>You ought to load the game, press F5 to make an instant save, press F7 to load it and THEN load your external savestate.

What problem does Pj64 have, that requires you to do something like this?

**Comment by oddMLan** [comment]
I can only speculate something is not getting initialized and only gets initialized when you press F7, but not at the moment of selecting the "Load... (Crtl+L)" and that's why the emulator deadlocks and only loading a previous savestate by pressing F7 fixes it. But I don't think this is the appropriate place for discussion, for that we should use the ticket I linked.

**Comment by AmbientMalice** [comment]
>Can't load the saves. Could you make PJ64 2.2 compatible saves?

I'll see what I can do. I haven't used 2.2 in quite some time because it tends to BSOD my PC, even with Win 7 compatibility mode.

**Comment by gonetz** [comment]
What about 2.0? 1.6 saves also  OK for me.
I have large collection of saves, which are compatible between older versions of PJ64, but saves from latest builds work only with it.

**Comment by AmbientMalice** [comment]
>What about 2.0?
The BSOD problem was introduced before 2.0, and was fixed after 2.2 I believe save state backwards compatibility was accidentally broken after 64DD support was added.

**Comment by gonetz** [comment]
Ok, Turok issue fixed,  DK64 issue fixed by itself. @AmbientMalice is the bug with aux copy and extreme g still exists? I can't reproduce it.

**Comment by AmbientMalice** [comment]
>@AmbientMalice is the bug with aux copy and extreme g still exists? I can't reproduce it.

I'll test some more later, and if I can find a case of it happening, I'll try to find a reliable one.

**Comment by gonetz** [comment]
>Tested a bunch of games and so far I thought I found a regression in DK64, but it turns out I forgot to delete the shader cache

That is strange actually. I changed shader cache version, so old cache should not load.

**Comment by AmbientMalice** [comment]
Something odd is going on. I built GLideN64 for Zilmar using the GLideNUI from the other thread. The thermal goggles are partially working, but only with the Zilmar build. mupen64plus is still broken. However, I can't change the settings without crashing the emulator. Not sure why, since I can't see any recent changes to the UI on the commit list.
 
![gliden64_turok_3 _shadow_of_o_004](https://cloud.githubusercontent.com/assets/10704701/14813850/023f9aee-0be7-11e6-8434-53831b76cb22.jpg)

**Comment by AmbientMalice** [comment]
Okay, so I came across this. I think it is new behavior. If you turn off the framebuffer, the thermal goggles half work. Pretty sure it is exclusive to this branch, but need to test.

![gliden64_turok_3 _shadow_of_o_004](https://cloud.githubusercontent.com/assets/10704701/14814405/7684297c-0be9-11e6-946c-8a2bfaf2b2db.jpg)

**Comment by gonetz** [comment]
> I built GLideN64 for Zilmar using the GLideNUI from the other thread. 

Bad idea. I changed config.h, old lib will not work correct.

I posted updated binary yesterday:
https://drive.google.com/file/d/0B0YqMPjGo3B2eWkyZEJCampjR2c/view?usp=sharing

**Comment by AmbientMalice** [comment]
@gonetz Thanks. I notice LLE fog is fixed, which is very nice. https://github.com/gonetz/GLideN64/issues/384

**Comment by gonetz** [comment]
Yes, nice bonus.

**Comment by gonetz** [comment]
All reported bugs seems to be fixed (except unconfirmed issue with aux copy on/off).
The only thing left is to fix GLES2 support.

**Comment by matthewharvey** [comment]
I hate to be the bearer of bad news, but the experimental_blend branch is totally broken on the Intel mesa driver. 

I've reported a bug upstream (https://bugs.freedesktop.org/show_bug.cgi?id=95164). Basically the dev version throws an assertion, and the non-dev version doesn't render very much. It looks like both depth and texture rendering are thrown way off. I'm not sure how else to describe it, but I've tried several games that other people in this thread have posted pictures of, and they are not working at all.
I'm going to wait for now and see what the mesa devs say.

The shader that causes the issue seems to be fragment_shader_dither.

**Comment by gonetz** [comment]
fragment_shader_dither not changed in experimental_blend branch.
I don't have access to PC with Intel mesa driver. So, please help me with diagnostics.
First, make debug build of GLideN64, and run mupen64plus under gdb.
Set breakpoints in checkShaderCompileStatus and checkProgramLinkStatus after if (status == GL_FALSE) to be sure that shader compiled ok.
Then, if you think that fragment_shader_dither can be a problem, disable it. It's not a big deal.In compileCombiner 
replace #ifndef GLES2
by 
#if 0

**Comment by gonetz** [comment]
#151 seems to be fixed also
![gt64-000](https://cloud.githubusercontent.com/assets/8983092/14851102/86df4124-0c9f-11e6-9bdf-ad4a44b54942.png)
![gt64-002](https://cloud.githubusercontent.com/assets/8983092/14851103/86e097e0-0c9f-11e6-8cd2-b76a3d48aed3.png)

**Comment by olivieryuyu** [comment]
indeed fog is now fine in GT64 now

Just now to fix the branch z issue :)

**Comment by matthewharvey** [comment]
I was mistaken before about which shader was causing the problem. It's the linking of shaders that causes the issue, so it won't be so easy to work around. Seeing as it's an assertion in the glsl driver, I'm sure there's an upstream solution. We'll see what happens for now, and if a fix gets accepted into the next stable release then it might not be a problem. At the very least maybe a workaround will become more obvious after we find a solution there.

**Comment by gonetz** [comment]
> It's the linking of shaders that causes the issue

What kind of issue? What "shader_link error" in log says?

**Comment by gonetz** [comment]
> Just now to fix the branch z issue

It is issue only for Zelda MM, and even there it causes no glitches.

**Comment by olivieryuyu** [comment]
Branch z causes to have some 3d gfx missing in the background:

![sdfsdf](https://cloud.githubusercontent.com/assets/8987490/14875995/b6f75434-0d10-11e6-9481-b88dcb72f584.jpg)

**Comment by matthewharvey** [comment]
mupen64plus: brw_fs_channel_expressions.cpp:412: virtual ir_visitor_status ir_channel_expressions_visitor::visit_leave(ir_assignment*): Assertion `!"should have been lowered"' failed.
Aborted

It's not really something we can debug very effectively, but that's OK because the defect is fixed upstream! I asked whether the fix is likely to make stable branch, and I can watch the mailing list to find out as well.

So Mesa now works well for me using the development version.

**Comment by gonetz** [comment]
@matthewharvey I've got crash issue with Android GLES3x build. When I removed 

```
	if (config.generalEmulation.enableNoise != 0) {
		_strShader.append(
			"  if (uColorDitherMode == 2) colorNoiseDither(snoise(), color2);	\n"
			"  if (uAlphaDitherMode == 2) alphaNoiseDither(snoise(), alpha2);	\n"
			);
	}

```

the problem gone. I don't understand why that code causes the crash. You may try to remove that code also, probably mesa has similar issue.

**Comment by fzurita** [comment]
I'm Android in my Adreno 330 gpu, everything seems to work ok with GLES 3.0 but GLES 2.0 had a lot of issues.

Mario's head in the intro:
![screenshot_2016-04-28-10-31-42](https://cloud.githubusercontent.com/assets/11581687/14889612/8a58d476-0d2d-11e6-9877-eab720ef2997.png)

When loading a save state:
![screenshot_2016-04-28-10-31-57](https://cloud.githubusercontent.com/assets/11581687/14889678/ca4b3f6a-0d2d-11e6-9147-cd879ef90fd5.png)

Mario's errors are missing:
![screenshot_2016-04-28-10-30-46](https://cloud.githubusercontent.com/assets/11581687/14889705/e0515c18-0d2d-11e6-8d17-609572f60d31.png)

**Comment by fzurita** [comment]
Ok, the GLES 2.0 issues may not even be related to this branch. This is the first time I test GLES 2.0 in a very long time. I should probably check master with it.

**Comment by gonetz** [comment]
After two days of debugging I finally found what causes crash with GLES3 build. It took so long because it crashes somewhere inside gl drivers and I got no errors on app level. Also, the problem could disappear when I removed part of code, which, as I found later, absolutely unrelated to the problem. I'm not sure what exactly happened because I don't have driver sources. I think, it is optimization issue. Shader compiler removes unused variables. If you declare uniform variable, but not use it in the code, compiler will not include that variable into shader program. I declared uniform vector of size 2. For 1cycle combiner the shader uses only first element of the vector. Looks like compiler allocates place only for one element of the vector, and when I update the variable with glUniform2i, gl crashes. I did not expect that from NVidia.

**Comment by gonetz** [comment]
@fzurita I have fixed issues with post-processor and GLES2. I have tested it on my device with Adreno 330 gpu, no new issues.

**Comment by fzurita** [comment]
Majora's Mask still gives me issues with GLES 3.0. This issue doesn't happen with the master branch.

**Comment by gonetz** [comment]
Probably different drivers version.

**Comment by fzurita** [comment]
I'll throw some debugging in later to figure out which piece of code is causing issues.

**Comment by gonetz** [comment]
I hope you will find a solution once again :)

**Comment by fzurita** [comment]
I was able to track down the issue to this call in Shaders_ogl3x.h in the snoise method.

```"  return texelFetch(uTexNoise, coord, 0).r;			\n"```

Given that this is only used when noise emulation is enabled. I tried turning off noise emulation and all issues in OpenGL ES 3.0 go away. Curiously, you did not change this in this branch, although, if I go back to the master branch the issue also goes away.

**Comment by AmbientMalice** [comment]
@fzurita Maybe https://github.com/gonetz/GLideN64/issues/958 is related?

**Comment by fzurita** [comment]
It's possible, but it's only causing a display driver crash on my device, which is what I'm seeing and trying to debug here.

**Comment by gonetz** [comment]
It can be induced issues, as with my recent experience with debug for NVidia Shield:
https://github.com/gonetz/GLideN64/issues/970#issuecomment-215670509
I had a crash in Zelda OOT. When I removed alpha dithering, game stopped to crash. I found real problem by chance: adb log contained stack trace after crash, which says that crash happened in gl function glUniform2i. That is, no issue with shader compile or link. Shader did not crash without alpha dithering code, but most likely it did not work correct either. Can you check adb log for clues after game crash?

**Comment by fzurita** [comment]
Shader compilation and link work just fine. I do get logs when the driver crashes but they are very cryptic:

```
04-30 01:46:05.717 2892-7288/org.mupen64plusae.v3.alpha W/Adreno-GSL: <gsl_ldd_control:416>: ioctl fd 31 code 0xc02c093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
04-30 01:46:05.717 2892-7288/org.mupen64plusae.v3.alpha W/Adreno-GSL: <log_gpu_snapshot:331>: panel.gpuSnapshotPath is not set.not generating user snapshot
04-30 01:46:05.717 2892-7288/org.mupen64plusae.v3.alpha W/Adreno-GSL: <gsl_ldd_control:416>: ioctl fd 31 code 0xc02c093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
04-30 01:46:05.717 2892-7288/org.mupen64plusae.v3.alpha W/Adreno-GSL: <log_gpu_snapshot:331>: panel.gpuSnapshotPath is not set.not generating user snapshot
04-30 01:46:05.717 2892-7288/org.mupen64plusae.v3.alpha W/Adreno-GSL: <gsl_ldd_control:416>: ioctl fd 31 code 0x400c0907 (IOCTL_KGSL_DEVICE_WAITTIMESTAMP_CTXTID) failed: errno 35 Resource deadlock would occur
04-30 01:46:05.717 2892-7288/org.mupen64plusae.v3.alpha W/Adreno-GSL: <log_gpu_snapshot:331>: panel.gpuSnapshotPath is not set.not generating user snapshot
04-30 01:46:05.717 2892-7288/org.mupen64plusae.v3.alpha E/Adreno-ES20: <rb_timestamp_wait_on_timestamp:341>: gsl_device_waittimestamp failed in rb_timestamp_wait_on_timestamp
04-30 01:46:05.717 2892-7288/org.mupen64plusae.v3.alpha W/Adreno-GSL: <gsl_ldd_control:416>: ioctl fd 31 code 0xc02c093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
04-30 01:46:05.717 2892-7288/org.mupen64plusae.v3.alpha W/Adreno-GSL: <log_gpu_snapshot:331>: panel.gpuSnapshotPath is not set.not generating user snapshot
04-30 01:46:05.717 2892-7288/org.mupen64plusae.v3.alpha W/Adreno-EGL: <eglTimestampCreate:5600>: EGL_CONTEXT_LOST
```

**Comment by gonetz** [comment]
These logs won't help :(
Could you log GL version string? I wonder, why that code works ok on my device.

**Comment by fzurita** [comment]
Here you go:

```
05-02 23:29:32.048 12458-12546/org.mupen64plusae.v3.alpha I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1.1_RB1.05.00.02.042.016_msm8974_LA.BF.1.1.1_RB1__release_AU ()
                                                                        OpenGL ES Shader Compiler Version: E031.25.03.00
                                                                        Build Date: 02/11/15 Wed
                                                                        Local Branch: mybranch7539026
                                                                        Remote Branch: quic/LA.BF.1.1.1_rb1.10
                                                                        Local Patches: NONE
                                                                        Reconstruct Branch: AU_LINUX_ANDROID_LA.BF.1.1.1_RB1.05.00.02.042.016 + 62ca4eb + acd831d + 9f8b442 + e027a02 + cba30ba + 53c303a + a649d79 + 23e16f8 + 5e97da7 + cbd2a44 + 33d072a + 7aacf06 + 72b33e7 + 28f6f60 + b4c13d8 +  NOTHING
05-02 23:29:32.053 12458-12546/org.mupen64plusae.v3.alpha I/OpenGLRenderer: Initialized EGL, version 1.4
```

**Comment by fzurita** [comment]
So, I'm testing more games. Most games seem to be broke. The only difference in the shader program for games that work and that don't work is that the ones that work have this extra:

```

  if (uForceBlendCycle2 != 0) {				
    muxPM[0] = vec4(color2, alpha2);			
    muxA[0] = alpha2;							
    muxB[0] = 1.0 - muxA[uBlendMux2[1]];		
    lowp vec4 blend2 = muxPM[uBlendMux2[0]] * muxA[uBlendMux2[1]] + muxPM[uBlendMux2[2]] * muxB[uBlendMux2[3]];	
    color2 = clamp(blend2.rgb, 0.0, 1.0);		
  }	
```

**Comment by gonetz** [comment]
My drivers are older:

05-03 16:03:11.560: I/Adreno-EGL(16208): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1_RB1.05.00.00.002.025_msm8974_LA.BF.1.1_RB1__release_AU ()
05-03 16:03:11.560: I/Adreno-EGL(16208): OpenGL ES Shader Compiler Version: E031.25.01.03
05-03 16:03:11.560: I/Adreno-EGL(16208): Build Date: 11/19/14 Wed
05-03 16:03:11.560: I/Adreno-EGL(16208): Local Branch: mybranch5813579
05-03 16:03:11.560: I/Adreno-EGL(16208): Remote Branch: quic/LA.BF.1.1_rb1.11
05-03 16:03:11.560: I/Adreno-EGL(16208): Local Patches: NONE
05-03 16:03:11.560: I/Adreno-EGL(16208): Reconstruct Branch: AU_LINUX_ANDROID_LA.BF.1.1_RB1.05.00.00.002.025 + 30e7589 +  NOTHING
05-03 16:03:11.560: I/OpenGLRenderer(16208): Initialized EGL, version 1.4


>  so after commenting this piece of code out, uScreenScale has a valid value and the display driver stops crashing.

As I thought, the issue with uScreenScale is induced by an issue in new code. That code
```
if (uForceBlendCycle2 != 0) { 
}
```
is part of new blending. It is 2nd cycle of the blending, for 2cycle mode combiners.
I don't see anything suspicious in that part of code though.

**Comment by fzurita** [comment]
It's probably a driver bug... I just have to find a workaround.

**Comment by gonetz** [comment]
@fzurita I found an issue with my code: cycle2 specific code added for cycle_copy and cycle_fill modes. It could cause an issue. Please apply my patch 638a4166 and check again.

**Comment by fzurita** [comment]
Nope, didn't fix it.

**Comment by gonetz** [comment]
:( No more ideas yet

**Comment by gonetz** [comment]
BTW, have you cleared shader cache?

**Comment by fzurita** [comment]
Yeah, I have had it disabled for this testing.

**Comment by gonetz** [comment]
May be uBlendMux2 uniform is used being uninitialized. Please try to replace ShaderCombiner::updateBlendMode by this code

```
void ShaderCombiner::updateBlendMode(bool _bForce)
{
	m_uniforms.uBlendMux1.set(gDP.otherMode.c1_m1a,
							  gDP.otherMode.c1_m1b,
							  gDP.otherMode.c1_m2a,
							  gDP.otherMode.c1_m2b,
							  _bForce);
	m_uniforms.uBlendMux2.set(gDP.otherMode.c2_m1a,
							gDP.otherMode.c2_m1b,
							gDP.otherMode.c2_m2a,
							gDP.otherMode.c2_m2b,
							_bForce);
	int forceBlend1 = gDP.otherMode.cycleType == G_CYC_2CYCLE ? 1 : 0;
	int forceBlend2 = 0;

	if (gDP.otherMode.forceBlender != 0 && gDP.otherMode.cycleType < G_CYC_COPY) {
		forceBlend1 = 1;
		if (gDP.otherMode.cycleType == G_CYC_2CYCLE) {
			forceBlend2 = 1;
		}
	}

	m_uniforms.uForceBlendCycle1.set(forceBlend1, _bForce);
	m_uniforms.uForceBlendCycle2.set(forceBlend2, _bForce);
}

```

It will guarantee that uBlendMux2 is initialized.

**Comment by fzurita** [comment]
I did think that it may have been uninitialized, so I set it all zeroes always and that didn't work. But I'll try this as well.

**Comment by fzurita** [comment]
Ok, I finally had success..... I think there is something wrong with the driver.

In GLSLCombiner.h, I replaced:
```
		i4Uniform uBlendMux1, uBlendMux2;
```

with 

```
	    iUniform uBlendMuxC1_0, uBlendMuxC1_1, uBlendMuxC1_2, uBlendMuxC1_3;
	    iUniform uBlendMuxC2_0, uBlendMuxC2_1, uBlendMuxC2_2, uBlendMuxC2_3;
```

And used everything that way.

There must be something wrong with the glUniform4i GL function.

**Comment by gonetz** [comment]
Good finding!
May be glUniform4iv will work better? It would be great, because glUniform4i can be easily replaced by 
glUniform4iv. Use 8 uniforms instead of 2 uniform vectors is ugly.

**Comment by fzurita** [comment]
I had to head off to my job, so I'll give glUniform4iv a try tonight.

**Comment by gonetz** [comment]
ok, good luck :)

**Comment by fzurita** [comment]
Exact same issue with glUniform4iv. Now that I think about it, commenting out the set the glUniform4iv does not fix the issue.... so it can't be that.

**Comment by fzurita** [comment]
Ok, bad news. My original fix of replacing the vec4 with ints doesn't work. It does substantially delay the problem though.

**Comment by gonetz** [comment]
Is it the only device, which has issues with new blending?

**Comment by fzurita** [comment]
I should probably try my Nexus player which has a PowerVR GPU. My NVidia Shield TV had no issues.

**Comment by gonetz** [comment]
I tested with NVidia Shield Tablet and Note3 (adreno 330), no new issues.
As I understand, GLSE2 build works ok on your adreno device, so it will not be completely broken when this feature will come to master.

**Comment by fzurita** [comment]
True, also, disabling noise emulation also works.

**Comment by fzurita** [comment]
Just tried on the Nexus player with a PowerVR GPU with GLES 3.1. It works fine albeit extremely slow like it had always been.

The weird thing is that the first time I ran it, the blending was all bugged, second time I ran it, it worked fine.

**Comment by fzurita** [comment]
The reason I was asking was because in the PowerVR Android GPUs frame buffer emulation is very slow but only in GL ES 3.0 mode. The speed is fine in GL ES 2.0. I wonder if this is because GLES 3.0 is using FBOs.

**Comment by gonetz** [comment]
GLES2 uses FBO as well.
You may disable frame buffer emulation and compare speed. GLES3 shaders are more complex, it can be the reason. 
Regarding FB emulation: the main difference is that GLES3 uses glBlitFramebuffer to draw FBO on screen, while GLES2 renders textured rect with glDrawArrays. glBlitFramebuffer should work faster. Again, you may try to use GLES2 method with GLES3: replace
```
#ifndef GLES2
void FrameBufferList::renderBuffer(u32 _address)

```
by
```
#if 0
void FrameBufferList::renderBuffer(u32 _address)

```

**Comment by gonetz** [comment]
Another important difference between GLES2 and GLES3 is that GLES3 uses uniform blocks. Use of uniform blocks should improve performance, because it allows to change block of data for all shaders with just one GL call. GLES2 does not support that feature and thus it uses standard uniforms. May be GLES3 does not work well with uniform blocks.

**Comment by fzurita** [comment]
Yeah, sure, I'll try those things out. Thanks for the info!

**Comment by gonetz** [comment]
Merged to master
