### ISSUE TITLE
Shader storage seems broken [regression]

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#971]
It seems like shader storage is broken, at least in Android. Not sure for how long though, I only noticed after clearing my shaders folder and nothing is being generated anymore.

**Comment by fzurita** [comment]
This seems to work fine on my Nvidia Shield TV, but not in my phone... Interesting.

**Comment by gonetz** [comment]
Your GL drivers must support GL_NUM_PROGRAM_BINARY_FORMATS and GET_PROGRAM_BINARY_EXTENSION.

**Comment by fzurita** [comment]
It was working fine before. Also, I added some logging and it's failing when opening the file to write the shader storage. The errno is "No such file or directory". I'm trying to figure out why.

**Comment by gonetz** [comment]
May be something changed on emulator's side? Plugins asks emulator for path to store cache.

**Comment by fzurita** [comment]
Path is correct: /storage/emulated/0/mupen64plus/CoreConfig/UserCache/mupen64plus/shaders/GLideN64.eb4d37c1.shaders

I double checked that directory and it exists in my device.

**Comment by gonetz** [comment]
Yes, looks correct. Is shaders subfolder created? May be problem with permissions?

**Comment by fzurita** [comment]
Possibly permissions. The whole path exists and when looking at the directory permissions, they seem correct. I may have to use root explorer to look at the permissions more fully.

**Comment by fzurita** [comment]
Writing to /storage/emulated/0/mupen64plus/CoreConfig/UserCache/mupen64plus succeeds. It seems like there is something wrong specific to my phone and that directory. I'll close the issue.

**Comment by fzurita** [comment]
Yep, rebooting my phone worked. Great way to chase my tail.
