### ISSUE TITLE
Lego Racers broken menus (Regression)

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#974]
The menus/menu transitions where the CPU writes to FB are all broken now.
![gliden64_legoracers_000](https://cloud.githubusercontent.com/assets/10704701/14781877/b8020994-0b28-11e6-9620-f001fd2ff1c5.jpg)

**Comment by gonetz** [comment]
menu transitions? CPU writes to FB?
I see no difference in that game when run it with default settings.

**Comment by AmbientMalice** [comment]
I'm probably misunderstanding the issue, sorry. Anyway, here's what is happening.

GLideN64 1.2
![gliden64_legoracers_012](https://cloud.githubusercontent.com/assets/10704701/14988320/a1c43e4e-1196-11e6-8ae4-77cdc555bdc3.jpg)

Current build:
![gliden64_legoracers_011](https://cloud.githubusercontent.com/assets/10704701/14988165/1c03f376-1196-11e6-98c7-ca38d8799e1b.jpg)

I previously assumed the loadscreens like this were some sort of framebuffer effect that was broken when Jet Force Gemini's rain broke, but I realise now I was probably mistaken.

**Comment by gonetz** [comment]
hack_legoRacers helps to draw the map. It renders map from RDRAM to new frame buffer.
I tested with current master. The map may blink, but it does not disappear.

**Comment by gonetz** [comment]
@AmbientMalice please check the current version. I don't see reported issue.

**Comment by AmbientMalice** [comment]
Seems fixed.
