### ISSUE TITLE
Majora's mask incorrect graphics

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#978]
In some scenes the game displays some odd visual artifacts. See the screenshots, it also happens right before the title screen.

![screenshot_2016-04-30-02-03-57](https://cloud.githubusercontent.com/assets/11581687/14934250/1d086aa6-0e79-11e6-9d01-f526cd0fa0af.png)
![screenshot_2016-04-30-02-07-58](https://cloud.githubusercontent.com/assets/11581687/14934251/242cde20-0e79-11e6-8067-949d6d0c4ffe.png)
![screenshot_2016-04-30-02-08-08](https://cloud.githubusercontent.com/assets/11581687/14934253/2c05c0ee-0e79-11e6-862f-7aa3752fb4d1.png)
![screenshot_2016-04-30-02-08-19](https://cloud.githubusercontent.com/assets/11581687/14934254/32859da4-0e79-11e6-8b50-8aa09d0028c6.png)

This happens with the Nvidia Shield Android TV and Adreno 330 phone. I don't think it's GPU driver related.

**Comment by fzurita** [comment]
Another data point, this only happens with native resolution factor on.

**Comment by gonetz** [comment]
What is the value of native resolution factor?

**Comment by fzurita** [comment]
2x

**Comment by fzurita** [comment]
I can't reproduce this anymore in the latest. I think it's fixed.

**Comment by gonetz** [comment]
Good, thanks!
