### ISSUE TITLE
Frame buffer emulation without having to copy from GPU memory

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#979]
With current mobile devices copying GPU memory to system memory is terribly slow and we seem to be doing a lot of that during frame buffer emulation. The question is, why are we doing so many copies from GPU memory to system memory when the same memory is shared between the GPU and CPU in  a mobile device?

I was reading a little bit about this and there is an OpenGL ES extension that could potentially help with this. The extension is OES_EGL_image_external but it may only apply to shaders reading system memory.

I think this is something worth investigating.

**Comment by fzurita** [comment]
@gonetz Here is kind of a guide. I may try to take a shot at this? How doable do you think it is? I guess I would be converting the glReadPixels calls to using memory directly.

https://vec.io/posts/faster-alternatives-to-glreadpixels-and-glteximage2d-in-opengl-es

**Comment by gonetz** [comment]
It would be great to improve buffer read speed,  by I doubt that it is possible.  GLES3 implementation already uses PBO. The problem with PBO is that it has little to no performance gain when you use buffer right after read, that is in sync mode. It is possible to use async mode for color buffer read in many games, and it is really many times faster than sync mode. However,  depth buffer emulaton can't use async buffer read, which creates performance issue on PC as well. You may try EGLImage extension, may be it uses faster platform specific data transfer.

**Comment by fzurita** [comment]
For reference, from Gonetz:

> 
GLES2 uses FBO as well.
You may disable frame buffer emulation and compare speed. GLES3 shaders are more complex, it can be the reason. 
Regarding FB emulation: the main difference is that GLES3 uses glBlitFramebuffer to draw FBO on screen, while GLES2 renders textured rect with glDrawArrays. glBlitFramebuffer should work faster. Again, you may try to use GLES2 method with GLES3: replace
```
#ifndef GLES2
void FrameBufferList::renderBuffer(u32 _address)

by

#if 0
void FrameBufferList::renderBuffer(u32 _address)
```
>

**Comment by fzurita** [comment]
@gonetz I found why glReadPixels is so slow on Adreno devices even when using PBOs. We are some how passing the wrong color format to the glReadPixels call. When hard coding the color format to GL_RGB, glReadPixels turns into a non-blocking call!

Now to find out why it's getting set wrong....

**Comment by fzurita** [comment]
As far as I can tell, everything is configured to use RGBA. So glReadPixels shouldn't have to be doing any conversion, yet it is. Somehow it thinks that the frame buffer is in RGB format.

**Comment by gonetz** [comment]
Interesting. May be it is worth to play with formats in glReadPixels on desktop as well.

**Comment by fzurita** [comment]
Is there any advantage to using RGBA over RGB?

**Comment by fzurita** [comment]
The more I look at this, the more I think it's an android only problem. The java fronted in android is in charge of creating the EGL context. I don't believe we are doing it correctly which leads the GPU to have the incorrect internal format. Which means that the glReadPixels will have to convert.

**Comment by gonetz** [comment]
> Is there any advantage to using RGBA over RGB?

Alpha can be critical when FB is used as texture. Destination alpha can be used in blender in rare cases.

**Comment by fzurita** [comment]
After making this change some frame buffer effects look corrupted. Although, I figured out that in the java front end, we are setting the format to RGB888 with no alpha.

**Comment by fzurita** [comment]
After setting the color format to RGB8 in the front end and hard coding ```GL_RGBA_INTEGER``` for ```glReadPixels``` I get no corruption and no slowdown. Unfortunately, if I set the ```colorFormat``` to ```GL_RGBA_INTEGER``` in ```FBOTextureFormats::init()``` I get a black screen.

I think we are mixing up colorFormat and colorInternalFormat somewhere.

Hmmm, the mario kart screen works with ```GL_RGBA_INTEGER``` but the Banjo Kazooie puzzle effect doesn't.

**Comment by gonetz** [comment]
>Hmmm, the mario kart screen works with GL_RGBA_INTEGER but the Banjo Kazooie puzzle effect doesn't.

That's strange, because both effects use the same code.

**Comment by fzurita** [comment]
Not sure what you mean by that:
```
#define GL_RGBA                           0x1908
#define GL_RGBA_INTEGER                   0x8D99
```

**Comment by gonetz** [comment]
yep :)

**Comment by fzurita** [comment]
Never mind, it wasn't actually working in Mario kart, it was just a static image.

**Comment by fzurita** [comment]
In the end, I'm not having much luck with PBO and glReadPixels. No matter what I do, the ```glReadPixels``` call is not asynchronous since it blocks for too long.

I have gone down the path of using the OES_EGL_image_external extension and it's very promising. In fact, I got the the mario kart 64 screen looking perfect and it's VERY fast. The problem is that the results are not consistent across games. Even though the mario kart 64 screen looks perfect, the Banjo Kazooie puzzle effect looks broken. After reading data use the OES EGL extension, I had to do this to get the Mario Kart screen to look correct:

```
int widthBytes = width*colorFormatBytes;
int strideBytes = stride*colorFormatBytes;
for(unsigned int lnIndex = 1; lnIndex < height; ++lnIndex)
{
    memcpy(pixelData + lnIndex*widthBytes, pixelData+(lnIndex*strideBytes), widthBytes);
}
```

Here is a couple of screenshots of Banjo Kazooie with the above code taken during the same puzzle effect transition.

![screenshot_2016-05-22-20-11-31](https://cloud.githubusercontent.com/assets/11581687/15457763/afc3216a-205d-11e6-8f2b-dac1652341ae.png)
![screenshot_2016-05-22-20-11-41](https://cloud.githubusercontent.com/assets/11581687/15457767/bb557a0a-205d-11e6-84b7-e0a2d828e705.png)

Here is the same effect but without the above code:
![screenshot_2016-05-22-18-30-59](https://cloud.githubusercontent.com/assets/11581687/15457772/d645ccac-205d-11e6-98a6-a9c6ab50714f.png)

And here is my code so far... specifically look at ``FrameBufferToRDRAM::_copy```:

[FrameBuffer.cpp.txt](https://github.com/gonetz/GLideN64/files/276661/FrameBuffer.cpp.txt)

This code is by no means final, and there is a lot to do to clean it up before making any kind of pull request, and this will work for OpenGL ES 2.0 and 3.0.

So, my question... do you have any insight as to why the mario kart 64 screen looks fine, yet the puzzle effect in Banjo Kazooie is broken? Do you know what's different about the two?

**Comment by fzurita** [comment]
Ok, I found the right answer. The for loop should be this:

```
int widthBytes = width*colorFormatBytes;
int strideBytes = m_pTexture->realWidth*colorFormatBytes;
for(unsigned int lnIndex = 1; lnIndex < height; ++lnIndex)
{
    memmove(pixelData + lnIndex*widthBytes, pixelData+(lnIndex*strideBytes), widthBytes);
}
```

**Comment by fzurita** [comment]
I believe I can use this same method for reading back the depth buffer as well as wiring back to the GPU frame buffer in Android. I'm not sure how many games it would break though since this is similar to having dual PBOs like async color buffer to RDRAM has.

**Comment by fzurita** [comment]
By the way, this is very fast since we are completely bypassing the GPU to get to its memory. This is possible due to the shared memory architecture of embedded SOCs.

**Comment by gonetz** [comment]
Banjo Kazooie puzzle effects won't work with async buffers reads. There are several other games, which will not work right with async mode. That's why GLideN64 has sync mode as well. You may implement async reads for depth buffer, but our testing proved that async mode kills depth buffer emulaton.

**Comment by fzurita** [comment]
The puzzle effect is working perfect with this extension. Once I figured out the bug....

**Comment by fzurita** [comment]
Here is some more info on the extension I'm using:

http://blog.imgtec.com/powervr/supported-zero-copy-flows-inside-the-powervr-imaging-framework

I'll try to make a pull request soon once u clean it up...

**Comment by gonetz** [comment]
That's strange.  Actually it should not. Looks like a bug :)

**Comment by fzurita** [comment]
Maybe it's not exactly like having dual PBO's. I'll let you be the judge.

**Comment by purplemarshmallow** [comment]
>Banjo Kazooie puzzle effects won't work with async buffers reads

They do work with async reads

>By the way, this is very fast since we are completely bypassing the GPU to get to its memory. This is possible due to the shared memory architecture of embedded SOCs

Is it possible to render directly in RDRAM instead of copying? Would be more accurate

**Comment by fzurita** [comment]
That's a good thought, somehow map the emulator RDRAM to the GPU memory. But the formats are different, there would have to be some conversion.

**Comment by fzurita** [comment]
I'm very naive at this, but maybe that would be possible if we use a shader to convert each pixel before rendering to screen.

**Comment by gonetz** [comment]
> They do work with async reads

As I remember, the image for puzzle effect rendered just for one frame. It must be copied to current buffer, and that will not be done in case of async read. Strange, that it actually works.

> Is it possible to render directly in RDRAM instead of copying?

Not only formats are different, but buffer sizes also (except for native resolution).

> I'm very naive at this, but maybe that would be possible if we use a shader to convert each pixel before rendering to screen.

Convert to N64 internal format?

**Comment by fzurita** [comment]
Right, using a shader to convert to internal format. I think it would be very fast since all the pixels are done in parallel. 

Also, don't take anything I say to seriously since since I know relatively little about what would have to be done.

**Comment by gonetz** [comment]
If GL supports pixel format, which is the same as N64 uses, you may create texture with that format, attach to FBO and GL will automatically convert pixel to that format. If there are no such format, you can't do anything.

**Comment by purplemarshmallow** [comment]
https://www.opengl.org/wiki/Image_Format#Special_color_formats
GL_RGB5_A1 is that what we need?
 5 bits each for RGB, 1 for Alpha

**Comment by fzurita** [comment]
GL_RGB5_A1 seems to be the N64 pixel format as well, it also seems to be supported by many GPUs.

**Comment by purplemarshmallow** [comment]
Sounds very promising
If it's possible to create a texture inside RDRAM with the correct format it would help a lot with framebuffer emulation especially with CPU based effects. And without any performance cost

**Comment by gonetz** [comment]
Yes, GL_RGB5_A1 is direct analog of N64 16bit rgba format, and GL_RGBA8 is direct analog of N64 32bit rgba format.

**Comment by fzurita** [comment]
@gonetz I updated the master branch at https://github.com/mupen64plus-ae/mupen64plus-ae if you want to try this optimization out. It should really speed up frame buffer emulation in android. I'm getting close to submitting a pull request here.

**Comment by rcaridade145** [comment]
Wouldn't this be a good case to use GL_ARB_buffer_storage https://www.opengl.org/registry/specs/ARB/buffer_storage.txt 

>  Finally, this extension introduces the concept of persistent client
    mappings of buffer objects, which allow clients to retain pointers to a
    buffer's data store returned as the result of a mapping, and to issue
    drawing commands while those mappings are in place.

A discussion i found which you may found relevant - http://stackoverflow.com/a/20858898/6356465

**Comment by gonetz** [comment]
GL_ARB_buffer_storage can be used for buffer reads. The discussion on stackoverflow is not relevant, since it discuss writing data to GL buffers. Example 2 from GL_ARB_buffer_storage description is relevant. However, I very doubt that that extension can get noticeable speed boost in compare with currently used PBO based async reads. Besides, Francisco is trying to improve buffer reads on Android, while GL_ARB_buffer_storage available only on recent desktop GPUs.

Anyway, thanks for the hint. I'll try it when I'll have time.

**Comment by rcaridade145** [comment]
I thought it could be helpful due to this comment  "Another solution for fully asynchronous resource updates is using a ring of PBOs, so that you can upload the next frame to another PBO while the GPU is still sourcing data from the current PBO" and @fzurita comment - https://github.com/gonetz/GLideN64/issues/979#issuecomment-220878410 .

Thank you for work and for answering @gonetz

**Comment by gonetz** [comment]
'ring of PBOs' is generally the same as 'dual PBOs'; ring may contain two or more PBOs.

**Comment by gonetz** [comment]
@fzurita do you have performance improvement in color buffer copy on your devices in compare with current PBO-based async read? What is the difference in sync mode?

**Comment by fzurita** [comment]
In the original code, in my device they're was zero difference between sync and async mode performance. This was because the glReadPixels call would always block even though it shouldn't block when using PBOs.

With my changes, the performance is about 100% to 150% better in async mode in my device. 

This is completely different in the shield a Android TV because PBOs work correctly there is seems.

**Comment by gonetz** [comment]
So, when device supports PBO properly, using of EGL extension gives nothing. When PBO does not work well or does not supported (GLES2), using that extensions speedups glReadPixels twice. Is it correct?

**Comment by fzurita** [comment]
Yep

**Comment by fzurita** [comment]
Also, Copy color buffer to RDRAM seems to be disabled by #ifdefs for GLES 2.0.

**Comment by fzurita** [comment]
Tested in latest Mupen64Plus-AE build, seems ok.
