### ISSUE TITLE
Top Gear Rally Texture Corruption.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#981]
This is possibly related to https://github.com/gonetz/GLideN64/issues/975 but I can't be sure. Issue turned up fairly recently, and likely related to new blending.

![top_gear_rally-000](https://cloud.githubusercontent.com/assets/10704701/15098078/b55084da-1575-11e6-9b3b-9c811aa46818.png)

![top_gear_rally-002](https://cloud.githubusercontent.com/assets/10704701/15098080/ccf3ac2a-1575-11e6-9e39-d44a3ebb6343.png)

As you can see, the car light textures flip-flop between normal and corrupted.

![top_gear_rally-003](https://cloud.githubusercontent.com/assets/10704701/15098082/f3b89168-1575-11e6-888c-e2f697a85942.png)

Also, the tunnel lights are purple instead of brown-ish.

**Comment by weinerschnitzel** [comment]
Is this a corner case with new blending?

**Comment by gonetz** [comment]
@weinerschnitzel No. Lamps color broken after fixes in mip-mapping. Window broken after changes in combiners.

**Comment by gonetz** [comment]
Fixed
