### ISSUE TITLE
Error in latest git version when compling on rpi3

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#982]
I get this error when I run mupen64plus:

shader_link error: ERROR:CUSTOM-14 (fragment shader, line 73) Support for indexing array/vector/matrix with a non-constant is not mandated in the fragment shader

**Comment by gonetz** [comment]
Looks like hardware-specific. What is your GPU?

**Comment by loganmc10** [comment]
This is a Raspberry Pi 3, so it is a Broadcom Videocore IV I believe (GLES2)

**Comment by gonetz** [comment]
Bad. Actually, GLES2 does not have that limitation. This code works on Android devices.
I may rewrite the code with only constant indexing, but it will look ugly.

**Comment by loganmc10** [comment]
Ya when I Google that error, I only see references to the Raspberry Pi, it would be nice if this plugin worked with the Pi though

**Comment by gonetz** [comment]
As I understand, the problem is with code like this:
`muxB[0] = 1.0 - muxA[uBlendMux1[1]];`
It is prohibited to access vector via non-constant index. Thus, it must be rewritten something like this:
```
lowp float muxa;
if (uBlendMux1[1] == 0)
  muxa = muxA[0];
else if (uBlendMux1[1] == 1)
  muxa = muxA[1];
else if (uBlendMux1[1] == 2)
  muxa = muxA[2];
else if (uBlendMux1[1] == 3)
  muxa = muxA[3];
muxB[0] = 1.0 - muxa;

```
And this is only beginning. Now we need to rewrite next equation:
`lowp vec4 blend1 = (muxPM[uBlendMux1[0]] * muxA[uBlendMux1[1]]) + (muxPM[uBlendMux1[2]] * muxB[uBlendMux1[3]]);
`
That is that clumsy set of ifs must be repeated for each mux source. I left it to you as an exercise :)

**Comment by loganmc10** [comment]
So is it fair to say that 0ad53ad0e8a551e89563b03c279e1fb0ac4d9b86 caused this problem? I was wondering why it just stopped working recently

**Comment by gonetz** [comment]
Yes, new blending code causes this problem.

**Comment by loganmc10** [comment]
I'm not seeing this issue anymore, I'll re-open if it comes up again, I'm not sure why it went away.

**Comment by loganmc10** [comment]
I'm willing to write all those if statements and test it, but can you confirm the possible values for uBlendMux1[0-3], are the possible values only 0, 1, 2, or 3?

**Comment by gonetz** [comment]
All mux inputs are either vectors of size 4 or matrices of size 4x4. uBlendMux1/2 indices are guaranteed to be in range [0,3].

**Comment by loganmc10** [comment]
I have created a pull request to fix this issue:

https://github.com/gonetz/GLideN64/pull/993

**Comment by loganmc10** [comment]
Fixed in pull request
