### ISSUE TITLE
Custom Game Settings not Being Loaded

### ISSUE THREAD

**Issue by jaburgeson** [gonetz/GLideN64#984]
Hi Everyone,

It appears Custom Game Settings aren't being loaded in Project64.

I have the option checked in the options, but it doesn't appear to make a difference.

Tested with Mupen64Plus and custom settings get loaded, but I seem to have better compatibility with Project64.

Am I doing something wrong?

The GLideN64.custom.ini is in the same folder as the plugin.

**Comment by gonetz** [comment]
Must be also the same version as GLideN64.ini

**Comment by theboy181** [comment]
Have you released all required ini files with master? Have there been updated to the customer.ini?

**Comment by gonetz** [comment]
version of custom ini in master can be outdated.

**Comment by jaburgeson** [comment]
Ah that fixed it.  Changed it from 7 to 9 and now it's working!

Thank you for the quick tip!

**Comment by oddMLan** [comment]
maybe there should be a comment at the top of the ini file to avoid further complications
****must match with GLideN64.ini ver number to load****

**Comment by gonetz** [comment]
I think it is better to disable version check for custom ini.
