### ISSUE TITLE
"Show FPS/VI/sec on screen" option

### ISSUE THREAD

**Issue by MAKOS1230** [gonetz/GLideN64#985]
Is there an option to implement an option in GLideN64 to show statistics like FPS or VI/sec on screen. While now it's possible to detect any slowdown basing on sound slowdown, an accurate number would be IMHO better option to testers and end-user

**Comment by gonetz** [comment]
Emulator usually have vi/s or fps counters.

**Comment by MAKOS1230** [comment]
Yes, they have, but i didn't specified that i mean the VI/s or fps counter in fullscreen (which mean that it have to show it in framebuffer IIRC) just like you can in Glide64

**Comment by gonetz** [comment]
Ok, it can be implemented. Someday.

**Comment by gonetz** [comment]
Done. OSD options.
