### ISSUE TITLE
Crash when toggling full screen

### ISSUE THREAD

**Issue by kufii** [gonetz/GLideN64#989]
Emulator: Project64 2.2.0.3
ROM: Paper Mario

For some reason, often when I switch from full screen to windowed or vise versa, Project64 crashes. When I click debug, the only information I'm given is "Exception thrown at 0x5BF0CDD2 (GLideN64.dll) in Project64.exe: 0xC0000005: Access violation reading location 0x133177F0."

**Comment by olivieryuyu** [comment]
@gonetz 

can it be closed?

I tried many time to get a crash without success.
