### ISSUE TITLE
chopper attack wrong textures

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#99]
![chopper](https://cloud.githubusercontent.com/assets/8987490/4927473/cef28c26-653b-11e4-804d-9cf28d900c52.jpg)

**Comment by olivieryuyu** [comment]
those wrong texture are also on the planes

**Comment by AmbientMalice** [comment]
Fixed in LLE, seemingly.

**Comment by olivieryuyu** [comment]
in LLE but not HLE? that is odd

**Comment by gonetz** [comment]
Nothing odd. It is modified ucode, which uses non-standard method of Specular Highlights calculation. I can't decipher it. In LLE mode it is processed by RSP.

**Comment by olivieryuyu** [comment]
A modified ucode! the game uses RSP SW Version: 2.0H but it can be misleading indeed.

**Comment by gonetz** [comment]
TEXTURE MODE - Enable or disable texture filtering
It is hardly about reflecting textures.

**Comment by olivieryuyu** [comment]
ok i went to the debug menu, useless indeed.

![dsfdsf](https://cloud.githubusercontent.com/assets/8987490/15556334/b50aa090-22cd-11e6-9748-18632188fbc9.jpg)

here with TR64. Seems ok. 

I cannot find the source of the plugin though!!

**Comment by gonetz** [comment]
Please compare with LLE first. It can be another hack.

**Comment by gonetz** [comment]
LLE looks different:

![gliden64_chopper_attack_000](https://cloud.githubusercontent.com/assets/8983092/15564978/01b65608-2339-11e6-94a3-737fa8de5df6.jpg)

**Comment by olivieryuyu** [comment]
Indeed

😢

**Comment by Gillou68310** [comment]
I extracted the load vertex ucode from both goldeneye and chopper attack in order to compare both ucode.

Here's the diff:
Left: goldeneye, right: chopper attack
![capture](https://cloud.githubusercontent.com/assets/2852068/20136590/fa1efff6-a675-11e6-8594-bfb222a7ff95.PNG)

Here's the full load vertex ucode extract:
[F3D_VTX_chopper.txt](https://github.com/gonetz/GLideN64/files/580598/F3D_VTX_chopper.txt)
[F3D_VTX_golden.txt](https://github.com/gonetz/GLideN64/files/580599/F3D_VTX_golden.txt)

I also extracted the load vertex ucode from pilot wings and the code is exactly the same as goldeneye.

Now I just have to understand what these diff are about :-)

**Comment by olivieryuyu** [comment]
@Gillou68310: may i get your email address? I need to give you some docs which should be able to help you out in your work.

**Comment by gonetz** [comment]
> I also extracted the load vertex ucode from pilot wings and the code is exactly the same as goldeneye.

This is expected result, but anyway good to get the proof. Load vertex for both games works the same in my code. PD is different, but it is not enigma also. Also it is good to get the proof that load vertex for Chopper attack is really different.

**Comment by Gillou68310** [comment]
> may i get your email address

You can get it from https://github.com/Gillou68310 ;-)

**Comment by olivieryuyu** [comment]
ah yes indeed :)

merci bien gilles :)

**Comment by Gillou68310** [comment]
De rien ;-)

**Comment by Gillou68310** [comment]
Well from what I see this only has an impact on the final value of ```r8``` which is then stored in memory for each vertex.
```sh r8, $0024(r7)```
The least-significant 16-bit halfword of register ```r8``` is stored in memory at the location ```r7 + 0x24```, which is if I'm correct, the location address of ```vtx.g```

``` sw r8, $004c(r7)``` 
The least-significant 32-bit word of register ```r8``` is stored in memory at the location ```r7 + 0x4c```, which is if I'm correct, the location address of ```vtx.HWLight, vtx.clip and vtx.flag```

**Comment by Gillou68310** [comment]
@gonetz this doesn't explain why the logo has wrong tex coords. Is it possible that tex coords are modified  after load vertex by another GBI command?

**Comment by olivieryuyu** [comment]
what is puzzling to me is that there is less asm instructions in Chopper attack than the normal one, right? What are the purpose of those instructions? May be the tex coords calculation are depending on them in the normal ucode? Sorry if I am totally wrong here ...

**Comment by Gillou68310** [comment]
From what I see those instructions have no impact on tex coords calculation.

**Comment by weinerschnitzel** [comment]
What about lighting? LLE is also a lot darker than HLE.

**Comment by gonetz** [comment]
> Is it possible that tex coords are modified after load vertex by another GBI command?

gSPModifyVertex can be used to change any attribute of a vertex. However, it never used to modify generated texture coordinates. Texture coordinates for reflective surfaces generated on vertex load as function of angle between light direction and normal to the surface. If this difference in ucodes not related to vertex texture coordinates (s, t), it is possible that my implementation of texgen functionality is somehow incomplete or does not take into account some important stuff. In that case it also would be useful to decode that part of ucode and find how it works in reality.

**Comment by gonetz** [comment]
> sw r8, $004c(r7) 
The least-significant 32-bit word of register r8 is stored in memory at the location r7 + 0x4c, which is if I'm correct, the location address of vtx.HWLight, vtx.clip and vtx.flag

It is wrong idea to consider SPVertex struct as N64 structure.  Actual vertex structure is different, see GBI.h for Vtx_t, Vtx_tn, Vtx

**Comment by gonetz** [comment]
@Gillou68310 
>Well from what I see this only has an impact on the final value of r8 which is then stored in memory for each vertex.

This difference in calculations should explain, why Chopper Attack lighting code produces darker result.
What does code, which is missing in Chopper Attack ucode?

**Comment by olivieryuyu** [comment]
Sorry for the dummy question: $707 is a kind of value?

**Comment by Gillou68310** [comment]
@olivieryuyu shared some usefull ressources with me yesterday.

Here's the original source code of the microcode:
```
#ifdef NEAR_CLIP_OFF
    ; draw stuff even when it is in front of the near clipping plane
    vmudn   voutbakf, vout12f, voutbaki[0]  ; mult x frustrum
    mfc2    flg1, vout12i[6]                ;n w comp of vtx 1
    andi    flg1, flg1, 0x8000              ;n  neg bit
    srl     flg1, flg1, 13                  ;n  in place
    vmadh   voutbaki, vout12i, voutbaki[0]  ;
    mfc2    flg2, vout12i[14]               ; w comp of vtx 2
    andi    flg2, flg2, 0x8000              ;  neg bit
    srl     flg2, flg2, 9                   ;  in place
    vch     vtmp, vout12i, vout12i[3h]      ; rejection clipcodes
    or      flg2, flg2, flg1                ;n  vtx 1 & 2
    vcl     vtmp, vout12f, vout12f[3h]      ; rejection clipcodes
    cfc2    flg1, $vcc                      ; rejection clipcodes
    vch     vtmp, vout12i, voutbaki[3h]     ; clip/accept clipcodes
    vcl     vtmp, vout12f, voutbakf[3h]     ; clip/accept clipcodes
;n  andi    tmp,  flg1, 0x0707              ; reject clipcodes - vtx 1
;n  andi    flg1, flg1, 0x7070              ; reject clipcodes - vtx 2
    andi    tmp,  flg1, 0x0703              ;n reject clipcodes - vtx 1
    andi    flg1, flg1, 0x7030              ;n reject clipcodes - vtx 2
    or      flg1, flg1, flg2                ;n complete with nearclip
    sll     tmp,  tmp,  4                   ; vtx 1 in 0x00007070
    sll     flg1, flg1, 16                  ; vtx 2 in 0x70700000
    or      flg1, flg1, tmp                 ; all reject clipcodes in place
#else ; NEAR_CLIP_OFF
    ; Don't draw anything in front of the near clipping plane
    vmudn   voutbakf, vout12f, voutbaki[0]  ; mult x frustrum
    vmadh   voutbaki, vout12i, voutbaki[0]  ;
    vch     vtmp, vout12i, vout12i[3h]      ; rejection clipcodes
    vcl     vtmp, vout12f, vout12f[3h]      ; rejection clipcodes
    cfc2    flg1, $vcc                      ; rejection clipcodes
    vch     vtmp, vout12i, voutbaki[3h]     ; clip/accept clipcodes
    vcl     vtmp, vout12f, voutbakf[3h]     ; clip/accept clipcodes
    andi    tmp,  flg1, 0x0707              ; reject clipcodes - vtx 1
    andi    flg1, flg1, 0x7070              ; reject clipcodes - vtx 2
    sll     tmp,  tmp,  4                   ; vtx 1 in 0x00007070
    sll     flg1, flg1, 16                  ; vtx 2 in 0x70700000
    or      flg1, flg1, tmp                 ; all reject clipcodes in place
#endif ; NEAR_CLIP_OFF
```

As you can see this describes both goldeneye and chopper attack situation. So the only difference between both ucodes is that NEAR_CLIP_OFF is defined for goldeneye and not defined for chopper attack.

Also I made a mistake in the ucode extract I provided.
 ```040015D8 bne    r1, 0, $04001774 <- load code if not loaded yet```

This is actually jumping to the doLight routine, loading the routine code to IMEM if not loaded yet ;-)

> sh r8, $0024(r7)
> The least-significant 16-bit halfword of register r8 is stored in memory at the location r7 + 0x24, which is if I'm correct, the location address of vtx.g
> 
> sw r8, $004c(r7)
> The least-significant 32-bit word of register r8 is stored in memory at the location r7 + 0x4c, which is if I'm correct, the location address of vtx.HWLight, vtx.clip and vtx.flag

This was also incorrect, those addresses are pointing to the points buffer structure, 2 points are defined,
40 bytes per point, here's the structure definition:

```
 #  bytes:
 #  0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
 #  .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
 #  -----------------------------------------------------------------
 #  | x.int | y.int | z.int | w.int | x.frac| y.frac| z.frac| w.frac|
 #  ----------------------------------------------------------------|
 #  | r | g | b | a |   s   |   t   | xscr  | yscr  | zscr.i|zscr.f |
 #  -----------------------------------------------------------------
 #  | 1/w.i | 1/w.f |  0c0c |flg| 00|
 #  ---------------------------------
```

> If this difference in ucodes not related to vertex texture coordinates (s, t), it is possible that my implementation of texgen functionality is somehow incomplete or does not take into account some important stuff. In that case it also would be useful to decode that part of ucode and find how it works in reality.

That's what I'm going to do next ;-)

**Comment by gonetz** [comment]
Hmm. Is doLight routine different for Chopper attack? Why result of lighting is different?

**Comment by Gillou68310** [comment]
Will check

**Comment by Gillou68310** [comment]
Hum I need to make another ucode dump for goldeneye because the path is never taken in the dump I made. However I compared the doLight routine from the chopper attack ucode dump and the one from the original source code and they are identical.

**Comment by olivieryuyu** [comment]
Golden eye is may be not the best one as it may use a customs ucode for the sky. I do recommend **Super Mario 64 Shindou Edition** (not the original ones as there may have apparently some differences with the standard ucode).

**Comment by Gillou68310** [comment]
> Golden eye is may be not the best one as it may use a customs ucode for the sky. I do recommend Super Mario 64 Shindou Edition (not the original ones as there may have apparently some differences with the standard ucode for texrec).

Too late I already checked with goldeneye ;-)

This was expected but the doLight routine used in goldeneye and chopper attack are identical. 

> If this difference in ucodes not related to vertex texture coordinates (s, t), it is possible that my implementation of texgen functionality is somehow incomplete or does not take into account some important stuff.

This seems to be our last bullet.

**Comment by weinerschnitzel** [comment]
Does chopper attack follow the doLight routine in GLideN64? 

If that routine is never used in goldeneye, will forcing it make lighting darker?

**Comment by Gillou68310** [comment]
The doLight routine is used in both game, it was just not used in the first ucode dump I made from goldeneye.

**Comment by weinerschnitzel** [comment]
Ah ok. Thanks so much for the RE work. I can't stress enough how appreciated it is.

**Comment by gonetz** [comment]
> The doLight routine is used in both game

Strange. Lighting calculation works correct for all games with standard ucodes.
Only Chopper Attack logo is wrong, ingame is ok.

**Comment by olivieryuyu** [comment]
Yes only this logo seems to be darker, the rest is fine indeed.

The texture issue is also visible on the cockpit of the planes. It is clearly visible when selecting planes in menu. Here no light issue I think both issues may not be link.

What is odd is that only this blue texture is incorrect and all other textures works fine. May be the format of this texture is not properly apprehended, dunno.

**Comment by Gillou68310** [comment]
@gonetz where can I get vertex processed by rsp from memory in LLE, I'd like to compare both HLE and LLE results.

**Comment by gonetz** [comment]
@Gillou68310 
OGLRender::drawTriangles() for HLE triangles
OGLRender::drawScreenSpaceTriangle for LLE ones

**Comment by Gillou68310** [comment]
And where is triangles.dmaVertices filled with data :-)
Sorry I'm not used to c++ ;-)

**Comment by LegendOfDragoon** [comment]
>Hum I need to make another ucode dump for goldeneye because the path is never taken in the dump I made. 

So I guess the dump I had for Goldeneye is incomplete?

**Comment by gonetz** [comment]
> And where is triangles.dmaVertices filled with data :-)
> Sorry I'm not used to c++ ;-)

If you use Visual Studio, set breakpoint in drawScreenSpaceTriangle
and in debugger you can place triangles.dmaVertices to Watch and see its content.
Or use debugPrint to output content of SPVertex to console.
For example:

```
	for (u32 i = 0; i < _numVtx; ++i) {
		SPVertex & vtx = triangles.dmaVertices[i];
		debugPrint("vtx[%d].x = %f\n", i, vtx.x);
		vtx.modify = MODIFY_ALL;
	}

```

**Comment by olivieryuyu** [comment]
just noticed that Jabo is totally correct in HLE with this game. Damn!

**Comment by Gillou68310** [comment]
@gonetz lol I know how to watch the content of triangles.dmaVertices :-)
What I want to know is where in your code are vertex processed by rsp copied from rdram to the triangles.dmaVertices vector.

**Comment by gonetz** [comment]
@Gillou68310 ok, sorry.
gDPLLETriangle deals with data prepared by RSP.

**Comment by Gillou68310** [comment]
I see it now. I got fooled by the getDMAVerticesData method. I though this was returning a pointer to the vertex data, while it's actually returning a pointer to where vertex data are going to be stored. Sorry for wasting your time.

**Comment by olivieryuyu** [comment]
@gonetz and Gillou68310

It may not be an issue of ucode. See #1232. G_TEXTURE_GEN seems to not work as it should.

**Comment by Gillou68310** [comment]
@gonetz LLE and HLE triangles are not in the same space coordinate. Do you have any advice in order to compare them?

**Comment by gonetz** [comment]
You need to transform model space coordinates to screen space, like this
```
void OGLRender::drawTriangles()
{
...
	for (int i = 0; i < triangles.num; ++i) {
		SPVertex & v = getVertex(triangles.elements[i]);
		float x = gSP.viewport.vtrans[0] + (v.x / v.w) * gSP.viewport.vscale[0];
		float y = gSP.viewport.vtrans[1] + (v.y / v.w) * -gSP.viewport.vscale[1];
		float z = (gSP.viewport.vtrans[2] + (v.z / v.w) * gSP.viewport.vscale[2]) * 32768.0f;
		debugPrint(...);
	}

```
Note, that due to clipping and precision errors you will not get one-to-one correspondence with LLE triangles. Most likely that even not-clipped triangles will be out in different order in HLE and LLE. It was a pain for me to compare. I usually dumped some portion of vertices in HLE and LLE , copied dump to text file and sorted by coordinates (x and y coordinates logged first) using bash shell: cat log.txt | sort -u > log.out
Then I visually compared LLE and HLE dumps for records with the same coordinates, comparing only integer part of coordinates.

**Comment by Gillou68310** [comment]
Well that's painful like you said.
Anyway thanks for the tuto ;-)

**Comment by olivieryuyu** [comment]
@Gillou68310 

the source of the texture transformation/reflection mapping is in the GFLIGHT.S.

It is in TEXTURE COORDINATE GENERATION / REFLECTION MAPPING, in the texGenRet (which is for regular method in the texGenRet part).

The code is complex compared to linear. 

IN GlideN64 gSP.cpp it is here I think:

if (GBI.isTextureGen() && (gSP.geometryMode & G_TEXTURE_GEN) != 0) {
			for(int i = 0; i < 4; ++i) {
				SPVertex & vtx = render.getVertex(v+i);
				f32 fLightDir[3] = {vtx.nx, vtx.ny, vtx.nz};
				f32 x, y;
				if (gSP.lookatEnable) {
					x = DotProduct(&gSP.lookat[0].x, fLightDir);
					y = DotProduct(&gSP.lookat[1].x, fLightDir);
				} else {
					x = fLightDir[0];
					y = fLightDir[1];
				}
				if (gSP.geometryMode & G_TEXTURE_GEN_LINEAR) {
					vtx.s = acosf(-x) * 325.94931f;
					vtx.t = acosf(-y) * 325.94931f;
				} else { // G_TEXTURE_GEN
					vtx.s = (x + 1.0f) * 512.0f;
                                       vtx.t = (y + 1.0f) * 512.0f;

Is it possible to do a comparison? may it could help on this issue and #1232.

**Comment by gonetz** [comment]
Sorry for dumb question,  but where GFLIGHT.S. is ?

**Comment by olivieryuyu** [comment]
sending you an email to remind you :)

**Comment by Gillou68310** [comment]
> Is it possible to do a comparison?

That's what I'm working on these days ;-)
The doLight routine in GFLIGHT.S is not easy to understand even with the source code. So my current idea is to compare vertex processed by the load vertex command in both LLE and HLE.

I'm also spending time reading all the documentation you keep providing :-)

BTW in the N64 programming manual they often talk about coordinates format, for example S10.5. What is this format? How is it encoded?

**Comment by gonetz** [comment]
Fixed point. 10.5 is 15 bit number with 10 bit of integer part and 5 bit for fractional part.

**Comment by Gillou68310** [comment]
What about bit 16, sign?

**Comment by Gillou68310** [comment]
Also they gave an example 0x8000 -> 0.5, why?

**Comment by gonetz** [comment]
16 bit should be sign. For example, matrix elements have fixed point s15.16 format.

**Comment by gonetz** [comment]
0x8000 -> 0.5 for s15.16 format
1 << 16 = 65536
0x8000 / 65536 = 0.5
See _FIXED2FLOAT macro in GLideN64 code.

**Comment by Gillou68310** [comment]
Understantood, thanks for the course ;-)

**Comment by olivieryuyu** [comment]
Hmm can u h

**Comment by olivieryuyu** [comment]
I was reading the N64 programming manual about how the regular method of texture coordinate transformation. Do i understand correctly that it is actually the method used is a quaternion??

**Comment by Frank-74** [comment]
I never fully understood quaternions, they were taught with the idea of 4D space in school.  I could never get the idea of time being a dimension.  I understood vectors ok.  But got confused over rotating vectors in space/time.

**Comment by Gillou68310** [comment]
I finally made some progress on this. The current HLE code is not exactly reflecting what the original ucode is doing. Here's the differences:

1) Normal isn't transformed with model matrix.
```
TransformVectorNormalize( &vtx.nx, gSP.matrix.modelView[gSP.matrix.modelViewi] );
```

2) Lights (```gSP.lights[].xyz```) + reflectance (```gSP.lookat[].xyz```) directions are transformed with the 3x3 (transposed?) model matrix and normalized. Currently they are just normalized.

3) The normal should be converted from fixed point to float.
```
if (gSP.geometryMode & G_LIGHTING) {
    vtx.nx = _FIXED2FLOAT( vertex->normal.x, 7 );
    vtx.ny = _FIXED2FLOAT( vertex->normal.y, 7 );
    vtx.nz = _FIXED2FLOAT( vertex->normal.z, 7 );
    vtx.a = vertex->color.a * 0.0039215689f;
} else {
    vtx.r = vertex->color.r * 0.0039215689f;
    vtx.g = vertex->color.g * 0.0039215689f;
    vtx.b = vertex->color.b * 0.0039215689f;
    vtx.a = vertex->color.a * 0.0039215689f;
}
```

Doing points 1. and 3. fixes texture coordinate + light color, but this is only true because the 3x3 model matrix has the current form:
```
x  0  0
0  y  0
0  0  z
```
with x=y=z

**Comment by gonetz** [comment]
Dot( TransformNormalize(VertexNormal), Normilize(LightVector)) == Dot(Normalize(VertexNormal), InverseTransformNormilize(LightVector))

Glide64 does InverseTransformNormilize(LightVector), result is the same as with GLideN64. Could you tell me, where it is not true?

Vertex normal is normalized before use, so "The normal should be converted from fixed point to float." is redundant.

**Comment by Gillou68310** [comment]
I understand your point, but here's what the ucode do:

Dot(VertexNormal, InverseTransformNormilize(LightVector))

VertexNormal isn't normalized before use.

**Comment by gonetz** [comment]
TransformVectorNormalize returns normalized vector. Does it matter that it is not normalized before transformation?

**Comment by gonetz** [comment]
Plugin does transformations, equivalent to ones in ucode. Glide64 does the same transforms as ucode. Result is the same. Both Glide64 and GLideN64 have wrong result in Chopper.

**Comment by gonetz** [comment]
> Doing points 1. and 3. fixes texture coordinate + light color

Do you have version of code, which produces correct result in Chopper?

**Comment by Gillou68310** [comment]
It works with the following code:

```
if (gSP.geometryMode & G_LIGHTING) {
    vtx.nx = _FIXED2FLOAT( vertex->normal.x, 7 );
    vtx.ny = _FIXED2FLOAT( vertex->normal.y, 7 );
    vtx.nz = _FIXED2FLOAT( vertex->normal.z, 7 );
    vtx.a = vertex->color.a * 0.0039215689f;
} else {
    vtx.r = vertex->color.r * 0.0039215689f;
    vtx.g = vertex->color.g * 0.0039215689f;
    vtx.b = vertex->color.b * 0.0039215689f;
    vtx.a = vertex->color.a * 0.0039215689f;
}
```

And remove this line.
```TransformVectorNormalize( &vtx.nx, gSP.matrix.modelView[gSP.matrix.modelViewi] );```

But like I said this is only working because x=y=z in the model matrix I described above. Light should be transformed with the inverse model matrix instead.

**Comment by Gillou68310** [comment]
Normalize(light) == InverseTransformNormilize(light)

With the above model matrix ;-)

**Comment by gonetz** [comment]
Interesting. That way it really work. But there must be no difference.
Look: we need to find angle (dot for cosine) between two vectors: light direction and vertex normal.
Vertex normal not in its true position: transformation matrix must be applied to turn it in its space.
We either can apply transformation matrix to normal vector (GLideN64 approach) or apply inverse model matrix to light vector and turn light vector to normal (Glide64 and ucode approach). Angle between vectors must be the same in both cases. Where is mistake in my reasoning?

**Comment by gonetz** [comment]
Hmm, 
> The normal should be converted from fixed point to float.
vtx.nx is not normalized after that. Everything works if normal vector is used like this, not normalized. Normalization causes the error! I don't understand it.

**Comment by Gillou68310** [comment]
Yeah that's what I wanted to point out in the first place, I'm just bad at explaining things. I can't explain the math behind it but that's what the ucode is doing.

**Comment by gonetz** [comment]
I see the math behind it. My reasoning is correct until we work with normalized vectors. As soon as one vector is not normalized, transformations became not equivalent. All games use normalized normal vectors and lighting works fine. Chopper does weird things, which violates my math. Glide64 does same transformations as ucode, but it normalizes normal vector before use and ергы breaks behavior intended by Chopper programmers, damn them!

**Comment by gonetz** [comment]
Ok, thanks you! You lit the light of truth to that problem. Now I know how to fix it.

**Comment by Gillou68310** [comment]
You're welcome ;-)

Just for the reference I found a post on http://gamedev.stackexchange.com that explains the math behind doing a dot product between one unit vector U and one arbitrary vector V.

![capture](https://cloud.githubusercontent.com/assets/2852068/20620336/7eea6aec-b2f9-11e6-9a28-1b2bdff26952.PNG)

**Comment by gonetz** [comment]
The problem with my math is that I apply transformation to normalized normal vector and then normalize the resulted vector. You discovered, that normal vector must not be normalized. If I will apply transformation to original normal vector, resulted vector length will be different. If I will use the resulted vector without normalization to calculate dot with light vector, result will be wrong.

**Comment by olivieryuyu** [comment]
wonderful!!!!!! one issue solved :)

**Comment by gonetz** [comment]
Correction: One solution found :)

**Comment by Gillou68310** [comment]
Perfect teamwork ;-)

**Comment by gonetz** [comment]
Fixes in branch fix_lighting. Lots of changes in many many places had to be done; regressions are very possible. Thus, it is in a fix branch for the moment.

Windows binary:
https://drive.google.com/file/d/0B0YqMPjGo3B2U0gtMzVZSG0wNVU/view?usp=sharing

@fzurita Please test compilation and work on Android. HW lighting changed for both GLES2 and GLES3 version.

**Comment by fzurita** [comment]
Sure, will test!

**Comment by gonetz** [comment]
Thanks in advance :)

**Comment by fzurita** [comment]
Lighting looks wrong in Mario 64 with HW lighting enabled or disabled:

![super_mario_64-001](https://cloud.githubusercontent.com/assets/11581687/20631594/7b86fe72-b305-11e6-9b0f-5d4ff7a54647.png)

**Comment by gonetz** [comment]
I guess, I made a mistake in Vertex4 functions. Standard version works ok with HW light.

**Comment by fzurita** [comment]
I'll disable that to make sure that is the issue.

**Comment by Gillou68310** [comment]
Yeah no issue by my side with the standard version too.

**Comment by Gillou68310** [comment]
Probably caused by this line in gSPLightVertex4_default
```gSPTransformNormal4(v, gSP.matrix.modelView[gSP.matrix.modelViewi]);```

**Comment by fzurita** [comment]
I verified that it is VEC4 causing the issue. I'll fix that line and see if that fixes it.

**Comment by fzurita** [comment]
Yeah, removing the line that @Gillou68310 suggested seems to fix the issue.

**Comment by olivieryuyu** [comment]
Tested few games, so far no new bug. However it does not fix the issue #1232.

**Comment by gonetz** [comment]
> Yeah, removing the line that @Gillou68310 suggested seems to fix the issue. I removed it in all VEC4 functions since none of the normal functions seem to have it.

544ed32db63ef

**Comment by gonetz** [comment]
@olivieryuyu original problem is fixed. Can we close it?

**Comment by olivieryuyu** [comment]
With pleasure

**Comment by olivieryuyu** [comment]
@Gillou68310 

Short question: did you entirely compare GE007 and Chopper Attack and they are the same?

I don't have the same result :(

**Comment by Gillou68310** [comment]
I can check again if you want (not until monday) but I'm pretty sure they were identical, expected for the NEAR_CLIP_OFF related code.

**Comment by olivieryuyu** [comment]
will send you my file, would be easier to understand why I am confused :)

**Comment by Gillou68310** [comment]
Ok :-)

**Comment by olivieryuyu** [comment]
sent by email :)
