### ISSUE TITLE
extrem g 2 : gfx issue during intro

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#990]
![sdf](https://cloud.githubusercontent.com/assets/8987490/15341040/a022c280-1c8c-11e6-80de-0663c18fd5e9.jpg)

weird and incorrect effect during the intro

**Comment by gonetz** [comment]
This is depth compare issue. Probably, depth compare issue on hardware/drivers level, because I see no issues when I run this game on Linux with NVidia card.

**Comment by olivieryuyu** [comment]
indeed
