### ISSUE TITLE
Build issue on rpi3

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#991]
```
[  4%] Building CXX object GLideNHQ/CMakeFiles/GLideNHQ.dir/TextureFilters.cpp.o
In file included from /home/alarm/GLideN64/src/GLideNHQ/TextureFilters.h:34:0,
                 from /home/alarm/GLideN64/src/GLideNHQ/TextureFilters.cpp:26:
/home/alarm/GLideN64/src/GLideNHQ/TxInternal.h:56:19: fatal error: GL/gl.h: No such file or directory
 #include <GL/gl.h>
                   ^
compilation terminated.
GLideNHQ/CMakeFiles/GLideNHQ.dir/build.make:62: recipe for target 'GLideNHQ/CMakeFiles/GLideNHQ.dir/TextureFilters.cpp.o' failed
make[2]: *** [GLideNHQ/CMakeFiles/GLideNHQ.dir/TextureFilters.cpp.o] Error 1CMakeFiles/Makefile2:178: recipe for target 'GLideNHQ/CMakeFiles/GLideNHQ.dir/all' failed
make[1]: *** [GLideNHQ/CMakeFiles/GLideNHQ.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

This is a Raspberry Pi 3 with Arch Linux, GCC 6.1.1 and cmake 3.5.2

**Comment by loganmc10** [comment]
I assume this is because GLES2 isn't being passed through properly

**Comment by loganmc10** [comment]
I'm having this same issue on Raspbian (gcc 4.9), am I doing something wrong?

**Comment by loganmc10** [comment]
I got this working by adding:
```
if(BCMHOST)
  add_definitions(
    -DGLES2
   )
endif(BCMHOST)
```
to src/GLideNHQ/CMakeLists.txt

But now I get:

```
/home/pi/mupen/GLideN64/src/GLideNHQ/TxFilter.cpp:153:15: error: ‘GL_RGBA8’ was not declared in this scope
   srcformat = GL_RGBA8;
```

**Comment by loganmc10** [comment]
I fixed this by installing libgl1-mesa-dev, but really it should work without that installed since the rpi doesn't support OpenGL

**Comment by gonetz** [comment]
Can it be closed?

**Comment by loganmc10** [comment]
If you want, https://github.com/gonetz/GLideN64/blob/master/src/GLideNHQ/TxInternal.h has "#elif defined(GLES2)", but the CMakeLists.txt in GLideNHQ doesn't have anything that will ever set GLES2 to True, so the build process is broken for GLES2 devices in my view.

Even when I fix that by setting -DGLES2 in the CMakeLists.txt file, I get:
```
/home/pi/mupen/GLideN64/src/GLideNHQ/TxFilter.cpp:153:15: error: ‘GL_RGBA8’ was not declared in this scope
   srcformat = GL_RGBA8;
```
presumably because it needs this kind of thing:
https://github.com/gonetz/GLideN64/blob/master/src/CMakeLists.txt#L51-L71

in the CMakeLists.txt file for GLideNHQ.

Anyway, the CMakeLists.txt file is not working for GLideNHQ and the Raspberry Pi, I'll try fixing it up

**Comment by loganmc10** [comment]
So the GLES2 issue is fixed by adding:
```
if(GLES2)
  add_definitions(
    -DGLES2
   )
endif(GLES2)
```
to the GLideNHQ CMakeLists.txt file, I don't know if you just want to make that change or if you want a pull request. It doesn't look like the Raspberry Pi supports GL_RGBA8 in its GLES2 implementation, so I don't know what to do about that.

**Comment by loganmc10** [comment]
Here is a stackoverflow thread with someone that seemed to have the same problem on an iPhone:

http://stackoverflow.com/questions/4064706/ios-using-gl-rgba8

**Comment by loganmc10** [comment]
I created a pull request which will solve this problem for me:

https://github.com/gonetz/GLideN64/pull/992

Although GLideNHQ is still broken for GLES2

**Comment by loganmc10** [comment]
Fixed in latest commit
