### ISSUE TITLE
Builds 5-14-15 and newer break PJ64

### ISSUE THREAD

**Issue by jfields687** [gonetz/GLideN64#995]
Something in the 5-14-15 build breaks PJ64 from opening or changing the settings. Build 5-13-15 works without any problems. Using the latest build of PJ64 and GLideN64 from EmuCR.

When GLideN64 is set as default and trying to open PJ64
![1](https://cloud.githubusercontent.com/assets/12734891/15443276/02df5224-1eb5-11e6-88f0-bdb25d79477f.png)

When GLideN64 is not default and trying to open settings
![2](https://cloud.githubusercontent.com/assets/12734891/15443273/fd399d98-1eb4-11e6-8675-8f3833bab734.png)

**Comment by gonetz** [comment]
I have no responsibility for EmuCR builds. Please don't open any tickets about it.

**Comment by jfields687** [comment]
I understand you have no responsibility for EmuCR builds, but are you so sure it has something with their builds? Do you have this problem with your build?

**Comment by gonetz** [comment]
My builds have no problems with config dialog.
You may try my builds from #885

**Comment by jfields687** [comment]
Ok, thanks for replying and I will definitely try it! I sent a email to EmuCR to let them know of their build problems too.
