### ISSUE TITLE
glGetError 0x500 (invalid enumerant) - Raspberry Pi 3

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#999]
This assertion is failing for me every time on the Raspberry Pi 3:

https://github.com/gonetz/GLideN64/blob/master/src/Textures.cpp#L504

It doesn't seem to cause any issues in game (that I can see), but this gets printed every time I start a game:

```
glGetError 0x500
OpenGL Error: invalid enumerant
```

**Comment by loganmc10** [comment]
After adding "assert(!isGLError());" everywhere, I tracked down the source of the GL Error to this line:

https://github.com/gonetz/GLideN64/blob/master/src/GLES2/GLSLCombiner_gles2.cpp#L119

**Comment by loganmc10** [comment]
Indeed, removing both "glEnable(GL_TEXTURE_2D);" lines stops the error from happening. I'm not in front of my computer right now so I can't say what the picture looks like (I'm testing this over SSH).

It appears that you shouldn't be using GL_TEXTURE_2D with glEnable?

http://gamedev.stackexchange.com/a/20660

https://www.khronos.org/opengles/sdk/docs/man/xhtml/glEnable.xml

**Comment by CubanRudeBoy** [comment]
I was getting this same error while using Showcase theme. Also, the fan on my pi reved higher while using this theme. I switched back to crt theme and i never see that error anymore.
